### ISSUE TITLE
想知道这个框架的主要思路

### ISSUE THREAD

**Issue by yaoxiong** [baidu/amis#1]
想知道这个框架的主要思路

**Comment by 2betop** [comment]
近期正打算要分享，等分享完再放出来ppt吧

**Comment by 2betop** [comment]
https://github.com/baidu/amis/issues/15

**Comment by giscafer** [comment]
有玩过类似的demo，看了源码，思路大致一样的。https://github.com/giscafer/ngx-form-builder

之前的简单思路：

![](https://github.com/giscafer/ngx-form-builder/raw/master/screenshot/process.png)

**Comment by jasonHzq** [comment]
使用的人肯定很痛苦

**Comment by 2betop** [comment]
可以结合其他辅助工具，比如代码提示，可视化编辑器，脚手架等等。

**Comment by realeve** [comment]
https://github.com/baidu/amis/issues/2#issuecomment-491221313


编辑器可以这样:把一些现成的组建按列表渲染出来，点击一个期望的组建，把对应的配置信息自动复制到剪贴板，用户在编辑部分粘帖即可。

**Comment by FatDong1** [comment]
期待可视化编辑器
