### ISSUE TITLE
分页组件是否可以去掉最后一页页码

### ISSUE THREAD

**Issue by polandeme** [baidu/amis#1000]
看文档里面，分页分为两种：
1. 常规的显示总数，这种情况下会显示最后一页
2. 后端不返回总数，返回是否还有下一页

目前使用的第一种情况，但是第一种有个问题是，数据量较大，显示最后一页，有用户会不经意点下最后一页，导致查询较慢。
但其实这个功能并用不着。

也可以按照方法二进行改造后端，但是也希望可以直接支持前端隐藏掉最后一页定制

**Comment by 2betop** [comment]
你直接让接口返回 total 变少点？

**Comment by polandeme** [comment]
也是一种思路，但是也是治标不治本

现在用了返回hasNext解决的，但是这个组件过于简单了些，只有前一页后一页按钮，是否可以显示当前页码的前3-5页的页码

**Comment by 2betop** [comment]
目前没有配置项，而且我觉得这个功能很不合理。这个参数其实附带到地址栏的，如果用户手动修改这个参数呢？我还是觉得 Math.min 是比较好，既然不想让他点那么多页。

**Comment by polandeme** [comment]
这个原本想法是类似百度和google搜索的翻页模式

> Math.min 是比较好，既然不想让他点那么多页。
这个能够解决当前问题，后面会有两种情况：
1. 正常可选择页面，加上最多返回条数（页码）
2. 只显示是否还有下一个模式

**Comment by nwind** [comment]
可以通过 css 干掉
