### ISSUE TITLE
6.22升级6.3后，Tab组件mode:tiled时，tab标题不居中

### ISSUE THREAD

**Issue by FirthTuckman** [baidu/amis#10006]
#### 描述问题：

6.22升级6.3后，Tab组件mode:tiled时，tab标题不居中

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/38678332/cb6f2a0b-eef3-4caa-a07b-4a6aba2ccdbb)

**Comment by AlohaL** [comment]
@qkiroc 加上width:100%之后文本居中了，但是icon还是居左的
![2024-04-12_18-19](https://github.com/baidu/amis/assets/30368698/38793a00-3fe8-4569-aad3-22861e85b76b)
