### ISSUE TITLE
CRUD 增删改查 输入内容 查询(搜索)后  点击重置按钮 无法清空值

### ISSUE THREAD

**Issue by zwbuber** [baidu/amis#10002]
#### 描述问题：

CRUD 增删改查 输入内容 查询(搜索)后 点击重置按钮 无法清空值
操作地址：https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E6%9F%A5%E8%AF%A2%E6%9D%A1%E4%BB%B6%E8%A1%A8%E5%8D%95

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/75597366/5b4a46c7-2af5-44c6-96fe-d82a1c53ea65)
输入内容 查询(搜索)后无法被清空值
![image](https://github.com/baidu/amis/assets/75597366/f34976e7-dfdc-4807-b461-11119320e614)
操作流程 ：
1. 输入内容  如输入123456
2. 点击查询(搜索)
3. 点击重置按钮 无法清空值

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网
https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E6%9F%A5%E8%AF%A2%E6%9D%A1%E4%BB%B6%E8%A1%A8%E5%8D%95

4. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
5. https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E6%9F%A5%E8%AF%A2%E6%9D%A1%E4%BB%B6%E8%A1%A8%E5%8D%95

6. 粘贴有问题的完整 `amis schema` 代码：
7. https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E6%9F%A5%E8%AF%A2%E6%9D%A1%E4%BB%B6%E8%A1%A8%E5%8D%95
```
code here...
```

8. 操作步骤
操作流程 ：
1. 输入内容  如输入123456
2. 点击查询(搜索)
3. 点击重置按钮 无法清空值

**Comment by 2betop** [comment]
重置按钮用 clear-and-submit 而不是 reset-and-submit

**Comment by zwbuber** [comment]
> 按钮重置用清除并提交而不是重置并提交

明白了 感谢
