### ISSUE TITLE
飞书内嵌浏览器使用标签输入组件提示Object.hasOwn()报错 

### ISSUE THREAD

**Issue by leaf188** [baidu/amis#10021]
飞书内嵌浏览器使用标签输入组件提示Object.hasOwn()报错

**Comment by vexos-io** [comment]
我在其他浏览器也碰到了，但我不会调试，不知道是哪个组件的问题，等结果

**Comment by CheshireJCat** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn
可能是飞书浏览器的内核版本比较低，不能兼容这个比较新的api，
另外，源码中没搜到用 `hasOwn` 这个方法的代码，有可能是某个第三方库用了？
这个特殊环境我们目前没有条件复现，请自己debug一下使用此方法的库，并报给我们，感谢。

**Comment by 2betop** [comment]
是第三方依赖里面，请在自己的工程中添加 ployfill, jssdk 版本已经添加了 https://github.com/baidu/amis/commit/c7d9dd3cb4058435fb0d1f8723c15045290c1065
