### ISSUE TITLE
文件无法下载问题

### ISSUE THREAD

**Issue by Miao0er** [baidu/amis#10023]
向各位大佬请教一下：为什么无法正常下载Excel文件，浏览器没有任何反应
amis版本：6.3.0

![631712991459_ pic](https://github.com/baidu/amis/assets/37327757/893b54a0-037c-4495-9268-ae6b27fc9259)
![641712991460_ pic](https://github.com/baidu/amis/assets/37327757/422bd4fe-720d-4dee-9997-491bd3996c13)
![651712991461_ pic](https://github.com/baidu/amis/assets/37327757/a4344103-e819-4270-958a-14ce83736dae)

**Comment by hq520it** [comment]
同问，一更新就不行了，唉

**Comment by CheshireJCat** [comment]
请参考这个文档，需要配置 `"responseType": "blob"`
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD

**Comment by Miao0er** [comment]
> 请参考这个文档，需要配置 `"responseType": "blob"` https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD

加了这个也不行，最后写了个自定义组件实现了下载按钮

**Comment by konan66** [comment]
可以参考改造 fetcher 函数内部使用这些参数来进行请求，并在响应拦截器中添加文件下载逻辑。
`import axios from 'axios';

// ...

const fetcher = async ({
  url,
  method,
  data,
  responseType,
  config,
  headers,
}: any) => {
  try {
    const response = await axios({
      url,
      method,
      data,
      responseType,
      headers,
      ...config, // 可能需要传递其他配置项
    });

    const contentDisposition = response.headers['content-disposition'];

    if (responseType === 'blob' && contentDisposition) {
      const filename = contentDisposition.split('filename=')[1];

      const downloadUrl = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = downloadUrl;
      link.setAttribute('download', filename); // 设置下载的文件名
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(downloadUrl);
      return; // 不进行 Amis 渲染，直接返回
    }

    // 处理其他响应逻辑
    // ...
  } catch (error) {
    // 处理错误
    // ...
  }
};

// ...`

**Comment by 2betop** [comment]
可以参考这个 https://github.com/baidu/amis/blob/master/examples/embed.tsx#L211
