### ISSUE TITLE
颜色选择器颜色微调卡顿

### ISSUE THREAD

**Issue by LAMMUpro** [baidu/amis#10038]
#### 描述问题：

使用颜色选择器，鼠标按住移动来微调选择颜色时异常卡顿，好像是加了防抖？可以优化一下吗

#### 截图或视频：

![颜色选择器](https://github.com/baidu/amis/assets/38106851/e9f3e2f2-54de-4b33-83c4-1170bfe8c486)

#### 如何复现（请务必完整填写下面内容）：

官方demo可以复现：https://aisuda.bce.baidu.com/amis/examples/theme

4. 操作步骤
打开https://aisuda.bce.baidu.com/amis/examples/theme
随便点击一个元素选择器，点击选中任意一个颜色，左键按住，移动鼠标进行微调

**Comment by nwind** [comment]
可以通过 `"changeImmediately": true` 缓解点，但想再流畅就比较难了，目前渲染是比较耗时
