### ISSUE TITLE
inputFile和pdfViewer在配合使用时inputfile的autofilll无法生效

### ISSUE THREAD

**Issue by azalpy** [baidu/amis#10039]
描述问题：
inputFile和pdfViewer在配合使用时inputfile的autofilll没生效，显示URL的内容为空

截图或视频：
![1](https://github.com/baidu/amis/assets/1881858/5a94d460-d4bd-41c5-99a1-53d2eb9a84a8)

如何复现（请务必完整填写下面内容）：
在官方例子中，直接修改配置内容，参考：https://baidu.github.io/amis/zh-CN/components/form/input-file

参考的配置
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "body": [
      {
        "type": "input-file",
        "name": "file",
        "label": "File",
        "accept": ".pdf",
        "asBlob": true,
        "receiver": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/upload/file",
        "autoFill": {
          "myUrl": "${url}"
        }
      },
      {
        "type": "input-text",
        "name": "myUrl",
        "label": "url"
      },
      {
        "type": "pdf-viewer",
        "id": "pdf-viewer",
        "name": "file",
        "width": 500
      }
    ]
  }
}

**Comment by allenve** [comment]
asBlob 设置为 false 即可   autoFill 是取接口返回的值进行填充  
asBlob true 会将当前文件以二进制的形式赋值给当前组件
