### ISSUE TITLE
设置disabledTip：'xxxx'，之后，该按钮样式padding变为0，

### ISSUE THREAD

**Issue by WangShaoyu1** [baidu/amis#1007]
![image](https://user-images.githubusercontent.com/16829507/96849519-47582980-1488-11eb-8639-e3c285d763ac.png)

![image](https://user-images.githubusercontent.com/16829507/96849535-4c1cdd80-1488-11eb-9356-998e7206495e.png)

code如下：
{
              type: 'button',
              // icon: 'fa fa-times text-danger',
              label: '删除',
              level: 'primary',
              disabledOn: `enabled === true`,
              actionType: 'ajax',
              tooltip: '删除',
              disabledTip: '启用状态的不能直接删除，需要先设置为未启用才可以删除。',
              confirmText: '你确定要删除该数据源吗？',
              api: `delete:${baseUrl}/projectDataSource/$id`,
},
移除了disabledTip属性，样式即恢复

**Comment by RickCole21** [comment]
https://github.com/baidu/amis/commit/49a3ad13544ebbd67061755e61f0bd154e68dec9

**Comment by RickCole21** [comment]
更新最新版再试试
