### ISSUE TITLE
Can't resolve 'file-selector'

### ISSUE THREAD

**Issue by lhkg1988** [baidu/amis#1009]
build报错

Module not found: Error: Can't resolve 'file-selector' in '/home/jenkins/agent/workspace/cmall-system/node_modules/_react-dropzone@10.1.10@react-dropzone/dist/es'

**Comment by 2betop** [comment]
依赖缺失，npm 安装问题？删了重新来？

**Comment by RickCole21** [comment]
无反馈，先关了
