### ISSUE TITLE
浏览器兼容性: IE11

### ISSUE THREAD

**Issue by hackee** [baidu/amis#1010]
amis页面在IE11下无法显示，包括[官方文档](https://baidu.gitee.io/amis/docs/index)。

- 用jssdk写的简单页面，报SCRIPT438: 对象不支持xxx属性或方法
- 用react写的页面，报SCRIPT1046: strict 模式下不允许一个属性有多个定义，SCRIPT5022: [ModJS] Cannot find module `5f106aa`等错误。

**Comment by nwind** [comment]
目前已经简单支持了，不过没仔细测过，后续有问题再单独开 issue，不过 IE 11 肯定有功能没法用，比如代码编辑器，这还是微软开源 monaco-editor。。。
