### ISSUE TITLE
用一个select的name值有无来控制另一个组件的显隐 在这个select回调中为这个组件赋值  赋值未生效

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#10101]
#### 实现场景：
用一个select的name值有无来控制另一个组件的显隐 在这个select回调中为这个组件赋值 

#### 存在的问题：
赋值未生效 应该是执行赋值时组件还在隐藏状态 请问怎么实现这个业务场景

**Comment by hsm-lv** [comment]
嗯，当前无法找到被隐藏的组件，有两种方式：
方式一：通过给页面变量赋值，组件去绑定这个变量值即可，这样不受隐藏的限制
方式二：先让组件显示再隐藏，感觉方式一更适合页面交互
