### ISSUE TITLE
npm使用方式存在amisScoped吗？

### ISSUE THREAD

**Issue by zhj135** [baidu/amis#1012]
#### 实现场景：
文档中只有SDK中提供了amisScoped的使用示例：amisScoped.getComponentByName('page1.form1').getValues()

#### 存在的问题：
npm使用方式中是否有类似方法，可以获取表单项的值？

**Comment by zhj135** [comment]
![amis](https://user-images.githubusercontent.com/11358618/97155143-de3a2400-17af-11eb-94f2-6544a93bf244.png)
例如，在p组件的内部获取renderAmis中表单的值

**Comment by 2betop** [comment]
参考 jssdk 里面的实现 https://github.com/baidu/amis/blob/master/examples/embed.tsx#L118
