### ISSUE TITLE
JSSDK乱码

### ISSUE THREAD

**Issue by menglilanshan** [baidu/amis#10125]
#### 描述问题：

打包JSSDK 乱码

#### 截图或视频：

 
<img width="676" alt="4E8FABEB-17B2-434f-AA4F-6181DE1F63F3" src="https://github.com/baidu/amis/assets/164308893/3b783c91-0cf8-429e-b75a-ec2bf02431b0">
<img width="673" alt="06E8CA30-6F01-43eb-A348-03875A51D5C9" src="https://github.com/baidu/amis/assets/164308893/e13923f0-a709-44c5-973e-48e315ff4e1e">

/

#### 如何复现（请务必完整填写下面内容）：

就 build 打包出来，sdk/sdk.js开头就乱码。不乱码的时候，amisRequire("amis/embed") 里面是空的

**Comment by nwind** [comment]
如果是 windows 的话先试试在 wsl 下 build

**Comment by menglilanshan** [comment]
找到问题了，一个插件的问题

**Comment by menglilanshan** [comment]
1
