### ISSUE TITLE
爱速搭模组件模版功能有开源计划吗?

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#10149]
#### 是否关联于某个问题吗：
爱速搭模版组件有开源计划吗？

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by 2betop** [comment]
不打算开源，感觉没啥东西啊，主要是后台管理模版
