### ISSUE TITLE
接口url用模板字符串加入变量后被转义导致请求发送失败

### ISSUE THREAD

**Issue by backToNature** [baidu/amis#1014]
![image](https://user-images.githubusercontent.com/7525630/97170293-675c5580-17c6-11eb-9146-9a8a1516a593.png)

如图的url会被转义为http%3A%2F%2F127.0.0.1%3A8081/api/list，导致请求发送失败，请问这里有什么办法绕过转义吗

**Comment by RickCole21** [comment]
https://baidu.gitee.io/amis/docs/concepts/data-mapping#raw

**Comment by backToNature** [comment]
感谢解答
