### ISSUE TITLE
select控件搜索功能，输入搜索条件后，如果搜索结果没有包含当前控件本身已选中值项的话，已选中项会显示为选项value，应该显示为选项label

### ISSUE THREAD

**Issue by yinlianghui** [baidu/amis#10143]
#### 描述问题：

如题，amis官网 [自动补全 autoComplete](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select#%E8%87%AA%E5%8A%A8%E8%A1%A5%E5%85%A8-autocomplete) 示例中的autoComplete接口返回的所有选项label和value值是相同的，所以看不出来有没有问题。

把示例中的代码copy到amis环境的项目中运行，autoComplete接口换成选项label和value值是不同的接口就能重现问题。

#### 截图或视频：
![select_search_bug3](https://github.com/baidu/amis/assets/6219465/50da80f5-9759-469d-a11c-fe0721bc0edd)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.3和3.6都有问题

4. 粘贴有问题的完整 `amis schema` 代码：
简单点说就是想办法让amis官网 [自动补全 autoComplete](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select#%E8%87%AA%E5%8A%A8%E8%A1%A5%E5%85%A8-autocomplete) 示例中的autoComplete属性指向的接口返回的选项label和value值不相同就能按上面视频操作步骤重现问题。
```
{
  "type": "page",
  "body": {
    "type": "form",
    "body": [
      {
        "name": "select1",
        "type": "select",
        "label": "选项自动补全（单选）",
        "autoComplete": ...//官网示例中这个接口返回的选项label和value值相同，让接口返回的选项label和value值不同即可
        "placeholder": "请输入",
        "clearable": true
      },
      {
        "name": "select2",
        "type": "select",
        "label": "选项自动补全（多选）",
        "autoComplete": "/amis/api/mock2/options/autoComplete?labelField=name&valueField=id&term=${term}",
        "placeholder": "请输入",
        "labelField": "name",
        "valueField": "id",
        "clearable": true,
        "multiple": true,
        "maxTagCount": 2
      }
    ]
  }
}
```

![image](https://github.com/baidu/amis/assets/6219465/32b9731b-eaf7-4522-9798-44eb3f0fa053)

5. 操作步骤
- 把amis官网 [自动补全 autoComplete](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select#%E8%87%AA%E5%8A%A8%E8%A1%A5%E5%85%A8-autocomplete) 示例中 schema copy到amis运行环境的项目中运行。
- 把官网示例代码中autoComplete属性换成一个本地能访问的接口，并且接口中的选项label和value值不相同
- 如上视频所示，先选中一个选项值。
- 再在搜索输入框中输入搜索关键字，可以看到选中值后再搜索，能触发autoComplete接口请求，且接口返回的值是正确的。
- 但是因为接口返回的是只是符合搜索条件的选项，并没有返回之前已选中项的数据。
- 所以此时会看到select控件中之前已选中项从选项label变成选项value了

**Comment by CheshireJCat** [comment]
已修复 https://github.com/baidu/amis/pull/10173
