### ISSUE TITLE
dynamic input-range

### ISSUE THREAD

**Issue by SergShulga** [baidu/amis#10144]
Input-range is a nice element, but has static min\max values. 

This notation is unacceptable

```python
amis_filter_item = {
            "type": "input-range", "multiple": True, "size": "lg",
            "min": "${xxx}", "max": "${xxx}", "step": "${xxx}"
        }
``` 

How can I set them dynamically from the database? Is there no way to use _source_ or _initApi_?

This element is used in my filter on ModelAdmin representation (fastapi-amis-admin), and I want to set limits depending on the target data.

it`s real?

**Comment by allenve** [comment]
it's supports variables after version 3.3.0
see https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-range#%E5%B1%9E%E6%80%A7%E8%A1%A8
