### ISSUE TITLE
自定组件生成的文件怎么在amis 里使用

### ISSUE THREAD

**Issue by menglilanshan** [baidu/amis#10156]
#### 实现场景：
自定义组件生成的外链在amis 编辑器里使用。而不是在amis-sass里

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
无法使用, amis 有自己的方式 https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react

**Comment by menglilanshan** [comment]
> 无法使用， amis 有自己的方式 https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react

 =  那些各种自定义框架模板，是不是都用不了。。

**Comment by 2betop** [comment]
对的，amis-saas 里面的东西没办法直接用在 amis 里面，需要额外东西桥接

**Comment by menglilanshan** [comment]
> amis-saas
这一块涉及到东西是不是没开源，思路是不是需要解析最终生成的js 然后插入到自定义组件里。。。。

**Comment by menglilanshan** [comment]
> 对的，amis-saas 里面的东西没办法直接用在 amis 里面，需要额外东西桥接

这一块涉及到东西是不是没开源，思路是不是需要解析最终生成的js 然后插入到自定义组件里。。。。

**Comment by 2betop** [comment]
amis-saas 没有开源，是平台里面的功能

**Comment by menglilanshan** [comment]
> amis-saas 没有开源，是平台里面的功能

行吧，那只能写在一起了。不能用链接的形式了。。。。
