### ISSUE TITLE
CRUD增删改查组件的列和内容出现错位

### ISSUE THREAD

**Issue by wubin1989** [baidu/amis#10155]
![image](https://github.com/baidu/amis/assets/12456315/89bb8c4e-2338-4516-b534-b5efcfaa59d9)

页面初始化时候的显示是正常的，在侧滑窗里进行编辑操作，给“测试实体2”属性新增了几个值之后，关闭侧滑窗刷新CRUD组件，出现错位问题。

麻烦maintainer帮忙看一下！

谢谢！

**Comment by 2betop** [comment]
这个新版本已修复，请升级，还有问题再开
