### ISSUE TITLE
咨询扩展表单验证怎么写

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#10160]
#### 实现场景：
我需要写扩展表单验证,我用的sdk。看文档里面是
```
let amisLib = amisRequire('amis');
amisLib.addRule(
```
我用sdk加载的时候是：
```
 let amis = amisRequire('amis/embed');
```
我的代码就写成了：
```
  let amis = amisRequire('amis/embed');
      amis.addRule(
```

#### 存在的问题：

就报错了（索引）:98 Uncaught TypeError: amis.addRule is not a function

#### 当前方案：
无

```
code here...
```

**Comment by 2betop** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/addon#%E6%99%AE%E9%80%9A%E7%94%A8%E6%B3%95

**Comment by 2betop** [comment]
按文档的方式来

**Comment by xiahao90** [comment]
我前端的能力一般，就是看文档中https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/getting-started，中amisRequire加载的方式和扩展表单的加载不一样。我理解的是amisRequire只能出现一次，是我理解的这样吗？

**Comment by 2betop** [comment]
不对，可以出现很多次

**Comment by lhtuling** [comment]
给后来的同学详细说下：
请直接按照文档方式来。。。不要自己发挥想象。。。文档写的那么清楚要用
``````
let amisLib = amisRequire('amis');
``````
为什么非要用
``````
amisRequire('amis/embed');
``````
不出错才怪！

**Comment by xinzhyu** [comment]
给后来的同学详细说下：
文档说的不够明确,可以

 let amis = amisRequire('amis/embed');

//可以这样写多次调用
let amisLib = amisRequire('amis');
amisLib.addRule(


amis.embed()
