### ISSUE TITLE
amis-editor-edmo 在编辑器中配置初始化接口 预览的时候 会报跨域 请问怎么通过配置解决

### ISSUE THREAD

**Issue by Xinxinz-l** [baidu/amis#10162]
文档上是这样解释的  不是太明白 具体需要怎么配置呢

schemaFilter?: (schema: any, isPreview?: boolean) => any 配置过滤器。可以用来实现 api proxy，比如原始配置中请求地址是 http://baidu.com 如果直接给编辑器预览请求，很可能会报跨域，可以自动转成 /api/proxy?_url=xxxx，走 proxy 解决。
![image](https://github.com/baidu/amis/assets/76441230/46234131-03e8-4be6-9cd3-fb83b497df83)

**Comment by allenve** [comment]
schemaFilter 用于替换 schema的内容，这里的思路是把api替换到自己的服务上，通过后端服务去转发请求实际的接口从而解决跨域。

**Comment by Xinxinz-l** [comment]
请问线上后端已经解决了跨域 在编辑器中还会报跨域吗

**Comment by Xinxinz-l** [comment]
现在有一个问题 后端已经配置了跨域 同样的接口 在编辑器中或者是通过配置生成的页面 会报跨域 是什么问题呢

**Comment by allenve** [comment]
host、端口不一致都会导致跨域    跨域问题和 amis 无关哈
