### ISSUE TITLE
6.0.x 版本 dialog无法在最外层直接渲染

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#10169]
#### 实现场景：
需要在页面初始化就弹出一个dialog

#### 存在的问题：
6.0.x 版本 dialog无法直接渲染 3.6.0版本可以渲染

![image](https://github.com/baidu/amis/assets/141314006/d93a004d-8568-4166-9461-c7795ce1ba76)

![image](https://github.com/baidu/amis/assets/141314006/d916eabe-d2d0-4a63-8d23-0c5692256e47)

#### 当前方案：
{
  "type": "dialog",
  "body": [
  ],
  "size": "md",
  "title": "请确认",
  "actions": [
    {
      "type": "button",
      "actionType": "cancel",
      "label": "取消",
    },
    {
      "type": "button",
      "actionType": "confirm",
      "label": "确定",
      "primary": true,
    }
  ]
}

**Comment by 2betop** [comment]
需要属性受控 show: true 属性

**Comment by coffin03** [comment]
> 需要属性受控 show: true 属性
明白了 谢谢
