### ISSUE TITLE
amis-core 升级到6.4.0后，编辑器添加“Flex布局”组件后浏览器报错

### ISSUE THREAD

**Issue by JackZhangCNCC** [baidu/amis#10170]
#### 描述问题：

amis-core 升级到6.4.0后，编辑器中拖拽添加“Flex布局”组件后浏览器报错：
Warning: Each child in a list should have a unique "key" prop.

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/33971427/bce851d1-d133-487b-bfd8-384617abbe01)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.4.0套装 是

3. 操作环境
项目package.json：
{
  "name": "react-amis-editor",
  "version": "1.0.0",
  "description": "react-webpack脚手架搭建的react amis-editor微前端子项目。",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode production",
    "start": "webpack-dev-server",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jackzhangcncc/react-amis-editor.git"
  },
  "keywords": [
    "react-amis-editor",
    "simple-react-app",
    "react",
    "webpack",
    "babel"
  ],
  "author": "Johnson",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/jackzhangcncc/react-amis-editor/issues"
  },
  "homepage": "https://github.com/jackzhangcncc/react-amis-editor#readme",
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.15.3",
    "amis": "6.4.0",
    "amis-core": "6.4.0",
    "amis-editor": "6.4.0",
    "amis-editor-core": "6.4.0",
    "amis-formula": "6.4.0",
    "amis-ui": "6.4.0",
    "axios": "0.21.1",
    "copy-to-clipboard": "^3.2.0",
    "css-loader": "^5.2.7",
    "html-webpack-plugin": "^4.2.0",
    "qs": "6.5.3",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-hook-form": "^7.39.3",
    "react-router": "5.0.1",
    "react-router-dom": "5.0.1",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.3.0",
    "url-loader": "^4.1.1",
    "webpack": "^4.47.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.11.3"
  },
  "dependencies": {
    "@babel/plugin-proposal-decorators": "^7.24.1",
    "@types/lodash": "^4.14.123",
    "@types/node": "^11.13.8",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@types/react-router": "5.0.1",
    "@types/react-router-dom": "^5.3.3",
    "acorn": "^8.8.2",
    "amis-widget-cli": "^3.2.5",
    "monaco-editor-webpack-plugin": "6.0.0",
    "prettier": "^2.2.1",
    "sass": "^1.63.4",
    "typescript": "^4.5.5"
  }
}
项目线上地址：
https://github.com/JackZhangCNCC/react-amis-editor

**Comment by zhangtao07** [comment]
可先忽略，不影响编辑。相关修复已合入master，将在下版本更新。
