### ISSUE TITLE
目前使用sdk的方式，怎么解决跳转问题？

### ISSUE THREAD

**Issue by is-vino** [baidu/amis#10175]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
想要通过路由跳转页面，所有在编辑页面的时候，使用自定义js，进行路由跳转开发，但是失败！

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
提示没有push方法，该怎么解决？

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
![Uploading 自定义跳转路由失败.png…]()

```
code here...
```

**Comment by is-vino** [comment]
![自定义跳转路由失败](https://github.com/baidu/amis/assets/74162391/3de852e3-ba71-4a5a-b836-84b4c66cd406)

**Comment by allenve** [comment]
看着可以直接用事件动作的跳转页面实现
