### ISSUE TITLE
SchemaRenderer 里对 activeKey 和 defaultActiveKey 的特殊处理是否可以移除

### ISSUE THREAD

**Issue by UltramanTix** [baidu/amis#10182]
#### 是否关联于某个问题吗：
SchemaRenderer 里面将 activeKey 和 defaultActiveKey 做了转换，导致自定义组件只要用到这两个 key 都可能导致异常，实际上amis-core 核心库没有任何逻辑跟这两个字段相关，只是在 amis-ui 有部分组件有这两个字段，amis-ui的逻辑不应该放在 amis-core 里面做兼容。
![image](https://github.com/baidu/amis/assets/161700543/308b3a27-73e2-4352-98d6-ddfb47abeea5)

#### 预期的解决方案：
删除amis-core 里面对这两字段的特殊处理

**Comment by 2betop** [comment]
schema 里面不应该存在受控属性，把 value 装成  defaultValue 把 activeKey 转成 defaultActiveKey 看起来都正常啊

**Comment by 2betop** [comment]
目前看来不需要移除，有问题可 reOpen 讨论
