### ISSUE TITLE
浏览3D文件

### ISSUE THREAD

**Issue by huangzz1024** [baidu/amis#10180]
#### 是否关联于某个问题吗：
我想上传3D文件，然后页面上可以预览3D文件，

#### 预期的解决方案：
在页面上使用鼠标全方位浏览3D文件

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
引入 three 或 babylon 体积太大了，amis 中不打算集成，建议方案是自己写自定义组件或 iframe 服务，使用类似 https://github.com/google/model-viewer 的工具来实现
