### ISSUE TITLE
6.3.0  6.4.1  cookie数据映射异常

### ISSUE THREAD

**Issue by jiang1988tao1** [baidu/amis#10207]
#### 描述问题：

使用 ${cookie:Admin-Token} 取cookie中的值会只能取到第一个sidebarStatus的值0，用其他几个name也是取到的0，取不到应该取到的值

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/16534377/05eb00eb-3ebf-4554-8be7-a1d80bdfb708)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
  目前用的版本为6.3.0和 6.4.1

**Comment by 2betop** [comment]
应该是要转义一下 `-` => `\-`

**Comment by jiang1988tao1** [comment]
> 应该是要转义一下 `-` => `\-`
> 
> `"${cookie:Admin\\-Token} "` 或者 `"${cookie:&['Admin-Token']} "`

第二个可以，谢谢
