### ISSUE TITLE
Amis文件分块上传用法，希望提供更详细的使用demo

### ISSUE THREAD

**Issue by Kandde** [baidu/amis#10205]
#### 实现场景：
想要做游戏安装包的批量上传，每个游戏安装包大概2G

#### 存在的问题：
https://baidu.github.io/amis/zh-CN/components/form/input-file#%E5%88%86%E5%9D%97%E4%B8%8A%E4%BC%A0

帮助文档中，对于分块上传的三个接口不太清晰，这里是要求用户自己编写接口，以及三个接口数据的拼接，都是用户自己实现么

startChunkApi 用来做分块前的准备工作
chunkApi 用来接收每个分块上传
finishChunkApi 用来收尾分块上传

**Comment by 2betop** [comment]
amis 里面没有对应后端接口实现，爱速搭平台内部有实现，能对接各种对象存储。

自己写接口请参考代码处的参数传递

https://github.com/baidu/amis/blob/master/packages/amis/src/renderers/Form/InputFile.tsx#L1076-L1230

**Comment by Kandde** [comment]
1. 如果前端用的amis对接，需要自己编写后端接口，根据你提供的代码进行参数传递
2. 如果当前使用的amis平台，可以某个页面单独对接爱速搭吗

**Comment by 2betop** [comment]
amis 平台也有实现，可以对接 bos，群组配置里面有上传配置相关

**Comment by Kandde** [comment]
您第一个回复里“amis 里面没有对应后端接口实现”， 第二个回复里“amis 平台也有实现”；
第二个回复的意思，是我们不需要自己写后端接口，相应的后端接口可以直接对接bos么，如果可以直接对接bos，是否有可参考的demo呢

**Comment by 2betop** [comment]
我以为你说的是厂内 amis 平台，如果是 amis 渲染器，没有对接的 demo

**Comment by Kandde** [comment]
我说的就是厂内的amis平台呀， 看的这个文档：https://baidu.github.io/amis/zh-CN/components/form/input-file#%E5%88%86%E5%9D%97%E4%B8%8A%E4%BC%A0

**Comment by 2betop** [comment]
如果是厂内 amis 平台，不需要实现那三个接口，直接在群组系统配置里面填写 bos 信息即可

**Comment by Kandde** [comment]
大文件也可以直接上传么，那我试一下

**Comment by Kandde** [comment]
请问在“上传相关-局部设置”里面，如果是大文件上传，想使用局部设置，应该在代码里如何配置
![image](https://github.com/baidu/amis/assets/24707302/2e4a03de-5641-4707-9199-9e8714fddb0a)

我尝试这样配置，但是finishChunk失败，不知道如何配置，麻烦指点下，谢谢~
![image](https://github.com/baidu/amis/assets/24707302/40d1b774-c98a-4073-ba13-4a4cfb15d23b)

报错信息：
![image](https://github.com/baidu/amis/assets/24707302/490742ff-fdef-4ef0-9b51-b9dc5787997a)

这是请求参数，请求参数里的key是全局配置里面的存储路径，不知道怎样可以使用局部配置的存储路径
![image](https://github.com/baidu/amis/assets/24707302/876df595-677b-47cb-92b3-939d922242d7)

**Comment by Kandde** [comment]
问题已解决，正确的配置方式为：
![image](https://github.com/baidu/amis/assets/24707302/8676c5a2-5671-4365-b49a-f9b758fc89b5)
