### ISSUE TITLE
react+vite环境在使用日期组建的的方式报错

### ISSUE THREAD

**Issue by shudj** [baidu/amis#10215]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/45382185/cd02f04a-0eb7-4879-8cd2-93f8cc3ec125)
只要一点击日期范围的组件就会包以下错误
[amis-react-demo-master1.zip](https://github.com/baidu/amis/files/15281545/amis-react-demo-master1.zip)

![image](https://github.com/baidu/amis/assets/45382185/978e4adf-fd78-4ce0-b093-810ba6cd29cc)

#### 如何复现（请务必完整填写下面内容）：
上传的代码可以fu'xi复现这个问题，这是找的一个开源的，代码复现，不管版本是6.0.0还是最新版本都有这个问题，
路径在pages/Examples/Form.jsx中
4. 操作步骤
运行项目，然后跳到示例页面 -> 表单页面 -> 点击检索时间，就会出现这个bug

**Comment by shudj** [comment]
没有人解决这个问题么

**Comment by 2betop** [comment]
`src/App.tsx` 262 行，注释后可解决此问题，透传了 `viewMode: "pc"` 到渲染器里面去了，这个属性跟  calendar 里面的不兼容，导致找不到组件

**Comment by 2betop** [comment]
<img width="801" alt="image" src="https://github.com/baidu/amis/assets/2698393/43a0c37a-c4c9-4ef5-b77e-964c06cb6c8e">

**Comment by shudj** [comment]
谢谢您，完美解决
