### ISSUE TITLE
请问 amis官方示例 的框架页面，是用amis-admin搭建的，还是纯amis搭建的？

### ISSUE THREAD

**Issue by woxiangbo** [baidu/amis#10226]
#### 实现场景：
我目前在用  amis-admin 来搭建后台管理系统，但是感觉样式不太好看
后来发现官方的示例 样式很好看，字体也不错
https://aisuda.bce.baidu.com/amis/examples/index

请问这个示例 界面是用 amis-admin搭建的，还是纯amis搭建的？
这个example有计划分享到github上么？
感谢回复~！

**Comment by 2betop** [comment]
https://github.com/baidu/amis/tree/master/examples
