### ISSUE TITLE
使用FormulaPicker点击右侧数据显示两个

### ISSUE THREAD

**Issue by onlyThat** [baidu/amis#10223]
![image](https://github.com/baidu/amis/assets/114373085/803626db-b6f3-453a-9cc6-94c906377891)
![image](https://github.com/baidu/amis/assets/114373085/370db96b-1bd8-4f22-ab16-46426b747638)

**Comment by 2betop** [comment]
不能复现，是否使用的最新版本？master 分支试验长这样
<img width="607" alt="image" src="https://github.com/baidu/amis/assets/2698393/18b857a9-caa9-4416-a4aa-c65fa04ef44f">
