### ISSUE TITLE
自定义文件上传组件在编辑器里右侧属性面板渲染错误

### ISSUE THREAD

**Issue by wubin1989** [baidu/amis#10237]
![image](https://github.com/baidu/amis/assets/12456315/19a0aa2e-7d92-43e4-9444-aadea6d7e5c5)

自定义文件上传组件在编辑器里右侧属性面板渲染错误，且toolbar里显示unknown。用了@FormItem注解

**Comment by 2betop** [comment]
自定义组件需要开发编辑器插件 https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/editor#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8F%92%E4%BB%B6
