### ISSUE TITLE
怎么配置标签选择器标签回显的颜色？

### ISSUE THREAD

**Issue by wubin1989** [baidu/amis#10235]
<img width="607" alt="image" src="https://github.com/baidu/amis/assets/12456315/e2fdc6dd-16a1-43f7-8ce7-d1faeffa585d">

**Comment by 2betop** [comment]
inputTag 无法配置标签颜色，目前只能通过 css 变量来修改 `--ResultBox-value-bg: red`

**Comment by wubin1989** [comment]
这个需求我提个feat，后续版本可以提供支持吗？
