### ISSUE TITLE
v6.4.0和v6.4.1点击switch开关的时候，控制台报错

### ISSUE THREAD

**Issue by wubin1989** [baidu/amis#10234]
<img width="1017" alt="image" src="https://github.com/baidu/amis/assets/12456315/fcf289a2-7667-4ffd-bcf1-6721af52e372">

如上图所示，点击switch开关的时候，控制台报了下面这个错，同时开关不能正常使用，点击没反应：

Error: custom 动作执行失败，原因：[mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'Row', Path upon death: '/rows/0', Subpath: 'data', Action: ''). Either detach nodes first, or don't use objects after removing / replacing them in the tree.

v6.4.0和v6.4.1都有这个问题。是用的amis-editor-demo这个脚手架搭建的工程。v6.0.0没有这个问题。

**Comment by 2betop** [comment]
无法复现，能否提供问题 schema
