### ISSUE TITLE
表单项下的组件中，没有穿梭器（transfer）

### ISSUE THREAD

**Issue by YuunYang** [baidu/amis#1023]
#### 描述问题：
无论当前容器是不是表单，都无法在左侧组件栏中找到；但通过手动添加代码可以加载

#### 截图或视频：
![image](https://user-images.githubusercontent.com/15278220/97823340-a83af980-1cf3-11eb-8aeb-2dc087bb8967.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. 粘贴有问题的完整 `amis schema` 代码：
无

3. 操作步骤
选择表单容器，查找 transfer 组件，无法找到

**Comment by 2betop** [comment]
嗯，穿梭器还没做到编辑器里面呢。
