### ISSUE TITLE
url上输入传参不生效

### ISSUE THREAD

**Issue by YSceshi** [baidu/amis#10243]
#### 描述问题：

url上输入传参不生效

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/161827768/0029bac2-72ed-4108-9fb8-46635b04e38b)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

6.4.1

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
url包含id的传参，无法传入到对应ID的过滤条件

**Comment by 2betop** [comment]
要开启同步地址栏，否则需要等 #10253
