### ISSUE TITLE
Select组件配置了searchApi但是无效，同样的配置改为Input-tree组件可以生效

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#10242]
#### 描述问题：

select希望根据搜索框输入内容进行远程搜索，input-tree可以生效，但是select组件无效

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/37805363/dd2f7539-18ae-4147-a3d5-381fcd3a1e04)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

6.2.2

3. 粘贴有问题的完整 `amis schema` 代码：
无法生效的select代码：
```
{
  "type": "select",
  "name": "select",
  "label": "Select",
  "searchApi": "/test?name=${term}",
  "id": "u:9a0239d31566",
  "multiple": false,
  "searchable": true
}
```

可以生效的input-tree代码：
```
{
  "type": "input-tree",
  "name": "tree",
  "label": "Tree Select",
  "id": "u:9a0239d31566",
  "searchApi": "/test?name=${term}",
  "multiple": false,
  "searchable": true
}
```

5. 操作步骤
点击select，在出现的下拉框中输入内容，F12查看是否发送接口

**Comment by 2betop** [comment]
select 是通过 `autoComplete` 属性来配置的，目前 `searchApi` 是给 select 的其他模式用的，比如 table 模式，group 模式等
