### ISSUE TITLE
运行出现环境问题

### ISSUE THREAD

**Issue by 21Llx** [baidu/amis#1024]
我把amis项目拷到本地，npm run dev 报 
Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)
我也按照了node-sass，这个要怎么解决？？？？

安装依赖需要python环境的支持吗
![image](https://user-images.githubusercontent.com/53612853/97854605-a80f1e00-1d34-11eb-9da9-d51f92072b64.png)

**Comment by nwind** [comment]
已经不需要 node-saas 了。
