### ISSUE TITLE
身份证校验 输入正确的身份证 校验无法通过

### ISSUE THREAD

**Issue by 18049684135** [baidu/amis#10257]
身份证校验 输入正确的身份证 校验无法通过  使用  validations  -  isId

**Comment by CheshireJCat** [comment]
没复现，贴一下你的schema以及校验的身份证号

**Comment by 18049684135** [comment]
在官网试了也是不行的  身份证 429005200407300043      {
        "type": "input-text",
        "name": "name",
        "validations": {
          "isId": true
        },
        "label": "身份证："
      }
