### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by citynook** [baidu/amis#10268]
#### 描述问题：
项目为vite3 + vue3，引用了 veaury 插件将 amis editor 引入到 Vue3 项目中使用，在弹出窗口中显示 amis 编辑器。

截止到6.3.0版本，使用过程还都正常，在升级到6.4.0和6.4.1版本后，关闭对话框时就会报错，降级回 6.3.0 版本后错误消失。

我不清楚是 veaury 的问题还是 amis editor 的问题，但至少 6.3.0 版本运行是正常的，所以在 veaury 里提交了 issue后，也在此提交了issue，希望可以找是哪方面的原因造成的，能否修复这个问题。

初步debug，感觉是removeCustomStyle的问题。

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/127393297/ee9e9a26-f3bb-4064-85f7-20140ef5b42f)
![image](https://github.com/baidu/amis/assets/127393297/296b2988-59c5-4b3d-933b-16dd90d42ba7)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.4.1

3. 粘贴有问题的完整 `amis schema` 代码：
代码仓库：https://github.com/citynook/amiseditor-vue

4. 操作步骤
4.1 执行 npm install --legacy-peer-deps 安装依赖
4.2 执行npm run dev启动项目，用谷歌浏览器进入主页面，按F12打开开发工具
4.3 点击【Open Editor】按钮弹出 Amis 编辑对话框
4.4 关闭对话框，此时控制台会输出错误信息

**Comment by citynook** [comment]
@nwind 升级到最新的6.5.0，问题依旧，现在项目中没办法使用新版本的 amis 了，咋办？

**Comment by citynook** [comment]
@2betop 请问这个问题有望修复吗？

**Comment by 2betop** [comment]
@citynook  http://nexus-d.efoxconn.com/repository/npm-group/csstype/-/csstype-3.1.2.tgz 无法下载，问题工程跑不起来

**Comment by citynook** [comment]
@2betop 抱歉，这个是公司内部的仓库，忘记替换了，请将 .npmrc 的内容换成下面的，再重装下依赖就可以了。
```
shamefully-hoist=true
strict-peer-dependencies=false
registry=https://registry.npmmirror.com/
```

**Comment by 2betop** [comment]
看起来是 vuera 的问题，里面把 document.getElementById 方法给覆写，在之后调用 document.getElementById('a') 都会报错，只是 amis-editor 里面也用了这个方法而已

**Comment by citynook** [comment]
向 veaury 提了 issue，veaury 更新版本后，此问题已解决。
