### ISSUE TITLE
新版本6.4.1赋值无法判断0

### ISSUE THREAD

**Issue by YSceshi** [baidu/amis#10270]
#### 描述问题：
6.2.2可以读取0，但是新版本6.4.4无法读取0的值
#### 截图或视频：

![image](https://github.com/baidu/amis/assets/161827768/b5801946-35d0-4b68-96a3-11ef334abfe2)

![image](https://github.com/baidu/amis/assets/161827768/f63ef791-0e16-4af2-90bf-65ee53590e93)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
预期结果为6.4.1时，当输入框填入0，需要显示提交/放弃按钮

**Comment by 2betop** [comment]
原始值是什么填 0 没检测出来？我这貌似不能复现

**Comment by YSceshi** [comment]
原始值为空



在 2024-07-16 18:53:06，"liaoxuezhi" ***@***.***> 写道：

原始值是什么填 0 没检测出来？我这貌似不能复现

**Comment by 2betop** [comment]
已经修复合入了代码，下个版本会解决这个问题

**Comment by YSceshi** [comment]
好的谢谢













在 2024-07-17 10:56:14，"liaoxuezhi" ***@***.***> 写道：

已经修复合入了代码，下个版本会解决这个问题
