### ISSUE TITLE
日期时间组件，无法正常输入， 比如小时，输入1，会 double 变成 11，再输入一个数，会变成 23

### ISSUE THREAD

**Issue by IMEVEN** [baidu/amis#1027]
#### 描述问题：
日期时间组件，输入框无法正常输入， 比如小时，输入1，会 double 变成 11，再输入一个数，会变成 23。

#### 截图或视频：
![image](https://user-images.githubusercontent.com/8068731/97944657-2533a500-1dc0-11eb-916e-091759acf5b3.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "datetime",
  "format": "YYYY-MM-DD HH:mm:ss",
  "name": "begin_time",
  "value": "$begin_time",
  "label": "开始时间",
  "maxDate": "${end_time}"
},
{
  "type": "datetime",
  "format": "YYYY-MM-DD HH:mm:ss",
  "name": "end_time",
  "value": "$end_time",
  "label": "结束时间",
  "minDate": "${begin_time}"
}
```

3. 操作步骤
可在官方 demo 中重现：
[https://baidu.gitee.io/amis/docs/components/form/datetime#显示格式](https://baidu.gitee.io/amis/docs/components/form/datetime#%E6%98%BE%E7%A4%BA%E6%A0%BC%E5%BC%8F)
> PS：不是每台机器都能重现，能重现的机器大概率一直都会有这个问题，有些机器一直都不能重现，另外重现的都是 chrome，IE 没重现。
> PS：在外面复制再粘贴进去则正常。

**Comment by zimo888** [comment]
是不是键盘案件粘连了 - - ，一下敲了俩1，再敲111，超过23小时上限了。。

**Comment by bolianlai** [comment]
在firefox上没问题，在edge和chrome上也是这个问题

**Comment by nwind** [comment]
可能是升级 downshift 修了？
