### ISSUE TITLE
crud组件，如何才能显示列分隔线

### ISSUE THREAD

**Issue by woxiangbo** [baidu/amis#10285]
https://aisuda.bce.baidu.com/amis/zh-CN/components/table?page=1#%E8%A1%A8%E5%A4%B4%E6%A0%B7%E5%BC%8F
“表头样式”章节 下的第一个crud组件，列之间有分割线
第2个crud组件，列之间没有分割线，如何才能显示分割线

![image](https://github.com/baidu/amis/assets/3446874/fe64846e-2c97-4af6-98a1-3c3737cc0d8b)

**Comment by allenve** [comment]
table2 支持  
https://aisuda.bce.baidu.com/amis/zh-CN/components/table2#%E5%B8%A6%E8%BE%B9%E6%A1%86

**Comment by allenve** [comment]
"tableClassName": "Table-table--withCombine"  也可以曲线救国

**Comment by woxiangbo** [comment]
> "tableClassName": "Table-table--withCombine" 也可以曲线救国

好的，因为table不支持分页，所以我就用你这个方案了，谢谢

**Comment by woxiangbo** [comment]
> "tableClassName": "Table-table--withCombine" 也可以曲线救国

不好意思，怎么才能给CRUD加上这个样式呢？className这个属性貌似不行
`{
      "type": "crud",
      "name": "crud",
      "initFetch": false,
      "title": "方法覆盖率",
      "className": "Table-table--withCombine",
      "api": "${API_HOST}/build/coverage/list_package_trend"
    }`

**Comment by woxiangbo** [comment]
"combineNum": 20,
 加上这个参数，可以显示分割线，hoho
