### ISSUE TITLE
amis-editor可不可以通过JS SDK的形式在页面内使用啊

### ISSUE THREAD

**Issue by Guwengo** [baidu/amis#10292]
amis-editor可不可以通过JS SDK的形式在页面内使用啊

**Comment by 2betop** [comment]
不可以，不支持

**Comment by xqhu2010** [comment]
{
    "type": "form",
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "body": [
        {
            "type": "editor",
            "name": "editor",
            "label": "编辑器",
            "language": "myLan",
            "editorDidMount": (editor, monaco) => {
                // editor 是 monaco 实例，monaco 是全局的名称空间
                const dispose = monaco.languages.registerCompletionItemProvider('myLan', {
                    /// 其他细节参考 monaco 手册
                });

                // 如果返回一个函数，这个函数会在编辑器组件卸载的时候调用，主要用于清理资源
                return dispose;
            }
        }
    ]
}

这个地方editorDidMount请问怎么用，我想进行定制开发这个editor，但是直接配置在json里面会报错，请问知道吗
