### ISSUE TITLE
依赖Bug

### ISSUE THREAD

**Issue by lqPrototype** [baidu/amis#10296]
#### 描述问题：

使用amis包，直接报错依赖。

```
Could not find module in path: 'amis-ui/lib/node_modules/smooth-signature/es/index.js' relative to '/node_modules/amis-ui/lib/components/Signature.js'

```

#### 截图或视频：

<img width="610" alt="image" src="https://github.com/baidu/amis/assets/30515981/f1863f32-9bdf-4e9e-abb2-3e34869d0af7">

[code](https://codesandbox.io/p/sandbox/ce-shi-amis-nk5j8j?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwimpyfd00063b6ivknouni9%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwimpyfd00023b6ixfbkxzd9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwimpyfd00033b6i30u6cwni%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwimpyfd00053b6i5rjt2965%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwimpyfd00023b6ixfbkxzd9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwimpyfc00013b6inldy36b5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clwimpyfd00023b6ixfbkxzd9%2522%252C%2522activeTabId%2522%253A%2522clwimpyfc00013b6inldy36b5%2522%257D%252C%2522clwimpyfd00053b6i5rjt2965%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwimpyfd00043b6i6jzytf0j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwimpyfd00053b6i5rjt2965%2522%252C%2522activeTabId%2522%253A%2522clwimpyfd00043b6i6jzytf0j%2522%257D%252C%2522clwimpyfd00033b6i30u6cwni%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwimpyfd00033b6i30u6cwni%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

6.4.1

建议重新打包

**Comment by allenve** [comment]
没复现 重装依赖试试？
