### ISSUE TITLE
请问有js 和css的CDN地址没？

### ISSUE THREAD

**Issue by dayuliu** [baidu/amis#1029]
#### 实现场景：
快速实现一个页面，不想依赖太多。

#### 存在的问题：
我需要下载js sdk去存起来，还要配置路由解析，比较麻烦。
#### 当前方案：
希望可以直接引用cdn资源

```
code here...
```

**Comment by nuan1989** [comment]
你真懒

**Comment by dayuliu** [comment]
难道这不是刚需吗？我只需要一个后台页面，还要建一个文件夹去存很多资源文件。
请问您勤快在自己把css js 存下来了吗？

**Comment by dayuliu** [comment]
> 你真懒

难道这不是刚需吗？我只需要一个后台页面，还要建一个文件夹去存很多资源文件。
请问您勤快在自己把css js 存下来了吗？

**Comment by dayuliu** [comment]
> 你真懒

难道这不是刚需吗？我只需要一个后台页面，还要建一个文件夹去存很多资源文件。
请问您勤快在自己把css js 存下来这一点吗？还是您自己勤快到写了一个NB的框架？
您做出来的产品是针对很勤快的人用的吗？有的人懒是智慧，有的人勤快是自以为勤快。

**Comment by 2betop** [comment]
难道cdn不要钱的吗，不要钱的cdn服务也不能保证啊，不嫌弃那就用 unpkg 上的。

https://unpkg.com/amis@{version}/sdk/sdk.js
https://unpkg.com/amis@{version}/sdk/sdk.css

比如：

https://unpkg.com/amis@1.0.18/sdk/sdk.css 
https://unpkg.com/amis@1.0.18/sdk/sdk.js

**Comment by dayuliu** [comment]
> 难道cdn不要钱的吗，不要钱的cdn服务也不能保证啊，不嫌弃那就用 unpkg 上的。
> 
> [https://unpkg.com/amis@{version}/sdk/sdk.js](https://unpkg.com/amis@%7Bversion%7D/sdk/sdk.js)
> [https://unpkg.com/amis@{version}/sdk/sdk.css](https://unpkg.com/amis@%7Bversion%7D/sdk/sdk.css)
> 
> 比如：
> 
> https://unpkg.com/amis@1.0.18/sdk/sdk.css
> https://unpkg.com/amis@1.0.18/sdk/sdk.js

cdn 当然要钱了，我记得以前文档上是有的。用起来很方便，免费的cdn不好使也怪不到amis上。amis已经做的很好了，十分感谢🙏🙏

**Comment by yes-github** [comment]
https://cdnjs.com/libraries/amis

**Comment by tsy19900929** [comment]
感谢楼上，you save my life
