### ISSUE TITLE
源码packages里的amis-editor打包构建的esm和lib可以单独使用吗

### ISSUE THREAD

**Issue by fang1305** [baidu/amis#10308]
1、amis-editor源码怎么单独构建，并且查看编辑器效果
2、amis-editor源码构建的文件可以单独引入到react+vite项目中吗（其它amis、amis-ui等通过npm引入）

**Comment by 2betop** [comment]
1. `npm run build --workspace amis-editor` 可以单独构建某个 package
2. 你可以选择也用 npm 包（自己改个名发包），也可以直接把源码 copy 到你的项目里面

**Comment by fang1305** [comment]
如果不发包的话，可以直接引入amis-editor的esm、lib吗

**Comment by 2betop** [comment]
虽然可以，但是你还不如直接用源码

**Comment by fang1305** [comment]
源码包里packages里amis-editor可以直接当成react项目打包部署到服务器吗，怎么配置啊

**Comment by 2betop** [comment]
工程问题要自己研究
