### ISSUE TITLE
关于Editor编辑器的使用

### ISSUE THREAD

**Issue by xqhu2010** [baidu/amis#10316]
#### 实现场景：
想使用type=editor，对xml或json数据进行渲染，然后想特定的行进行底色加色并且鼠标悬浮给出提示

#### 存在的问题：
查阅了官方文档，介绍可以如下参考monaco进行定制开发，但是这种写法在json里面会编译报错（editorDidMount后面不写引号会报错）
`
{
    "type": "form",
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "body": [
        {
            "type": "editor",
            "name": "editor",
            "label": "编辑器",
            "language": "myLan",
            "editorDidMount": (editor, monaco) => {
                // editor 是 monaco 实例，monaco 是全局的名称空间
                const dispose = monaco.languages.registerCompletionItemProvider('myLan', {
                });
                return dispose;
            }
        }
    ]
}
`

#### 请求解决方法
1.请问在json里面怎么写上面的定制js让其不报错
2.请问操作monaco底色变色怎么写

**Comment by nwind** [comment]
json 里必须按 json 格式，要将代码写在一行用字符串的形式，类似 https://aisuda.bce.baidu.com/amis/zh-CN/components/action#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%82%B9%E5%87%BB%E4%BA%8B%E4%BB%B6。

monaco 的操作需要查询相关文档 https://microsoft.github.io/monaco-editor/docs.html，我们也不太熟，对于这种简单需求不会 monaco 可以试试 CSS
