### ISSUE TITLE
日期组件可以以周为单位选择吗？

### ISSUE THREAD

**Issue by hcf1997** [baidu/amis#10313]
类似于input-month这种，可以加个input-weeks吗

**Comment by allenve** [comment]
场景是什么  如果只是选周几的话 select 就可以

**Comment by hcf1997** [comment]
> 场景是什么 如果只是选周几的话 select 就可以

填写周计划与总结，按照每周进行过滤，比如：第一周05.06-05-12，这种

**Comment by xwayway** [comment]
> > 场景是什么 如果只是选周几的话 select 就可以
> 
> 填写周计划与总结，按照每周进行过滤，比如：第一周05.06-05-12，这种

我是自己后端输出选项，然后使用select组件

**Comment by hcf1997** [comment]
> > > 场景是什么 如果只是选周几的话 select 就可以
> > 
> > 
> > 填写周计划与总结，按照每周进行过滤，比如：第一周05.06-05-12，这种
> 
> 我是自己后端输出选项，然后使用select组件

目前我们也是这样实现的
