### ISSUE TITLE
数据映射好像没生效

### ISSUE THREAD

**Issue by Kimwill** [baidu/amis#1035]
#### 实现场景：
使用service容器初始化数据域，把数据传递给自定义组件

#### 存在的问题：
数据映射好像没生效，自定义组件中拿到的数据依旧是${data}格式的字符串
![D07D0516-D350-4FFD-8618-CDDF3D95D9D5_13757](https://user-images.githubusercontent.com/37266209/98191455-2dbce480-1f54-11eb-98e2-ba8ed530a8be.png)
（接口数据)
![42DF8E9D-7BCD-43CC-AB41-8554CDD2BA8E_22473](https://user-images.githubusercontent.com/37266209/98191516-5218c100-1f54-11eb-8f04-ebc468de543a.png)
（自定义组件中打印的props）

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
{
  "type": "service",
  "api": "/api/getAuthInfo",
  "body": {
    "type": 'my-tree-select',
    "datas": "${authData}",
    "options": {},
    "nodeKey": "id",
    "defaultExpandAll": true,
    "leftColName": "视图",
    "rightColName": "操作"
  }
}
```

**Comment by 2betop** [comment]
并不支持这种调用

**Comment by 2betop** [comment]
自定义组件自己在 this.props.data 里面取就行了
