### ISSUE TITLE
React注册自定义类型无效

### ISSUE THREAD

**Issue by NickJiangDev** [baidu/amis#10374]
#### 描述问题：

我想要增加一个自定义的组件，自定义组件满足我的功能需要符合以下三点： 
1. 支持json schema；
2. 可以在编辑器里面可拖拽；
3. 配置面板符合组件属性。
按照官网提供的自定义React组件方法，我创建了tsx文件
```tsx
import * as React from 'react';
import { Renderer } from 'amis';

class CustomRenderer extends React.Component<{tip: string}> {
  // eslint-disable-next-line @typescript-eslint/explicit-member-accessibility
  render() {
    const { tip } = this.props;
    return <div>这是自定义组件：{tip}</div>;
  }
}
Renderer({
  type: 'my-renderer',
  autoVar: true,
  // @ts-ignore
})(CustomRenderer);
```

然后在json里面直接使用：
```
{
  "type": "page",
  "title": "自定义组件示例",
  "body": {
    "type": "my-renderer",
    "tip": "简单示例"
  }
}
```
json的类型报错。
#### 截图或视频：

![image](https://github.com/baidu/amis/assets/45092189/29c3bae4-d3a4-4168-a3ec-8a3e1a625f89)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

4. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.5.0

6. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "page",
  "title": "自定义组件示例",
  "body": {
    "type": "my-renderer",
    "tip": "简单示例"
  }
}

7. 操作步骤
我自定义渲染的amis-editor的<Editor />,在此基础上我直接在同级目录下创建了文件，定义了组件，通过Renderer去挂载，没有其他多余的操作。

**Comment by mindhacker0** [comment]
老哥，这个是啥原因
