### ISSUE TITLE
请问一下 combo 新增的触发条件可以由其他button触发吗？ 

### ISSUE THREAD

**Issue by YuunYang** [baidu/amis#1038]
#### 实现场景：
![image](https://user-images.githubusercontent.com/15278220/98240294-2a514980-1fa4-11eb-80fe-9fd81761d850.png)
例如上图场景中，我希望点击 `文本信息` 来添加文本输入框，而不是点击 `新增` 下的 `文本` 项

#### 存在的问题：
目前依据文档，似乎发现新增的逻辑无法定制化

#### 当前方案：

```
code here...
```

**Comment by 2betop** [comment]
来两个 combo, 然后结合 visibleOn 实现，或者还有个代码级别的配置方式就是addableOn: '表达式'
