### ISSUE TITLE
想触发自定义组件（amis-widget-cli开发）的reload重载方法，提示组件动作没有找到，大佬帮忙看看哪里出了问题？

### ISSUE THREAD

**Issue by joelost** [baidu/amis#10387]
#### 实现场景：
点击刷新按钮，触发我的流程图组件重新加载渲染。（流程图是用amis-widget-cli开发的react组件）
<img width="1469" alt="image" src="https://github.com/baidu/amis/assets/1925898/d736d162-3913-4eb0-9cc3-9dce1649d15e">
#### 存在的问题：
点击直接报错
<img width="1230" alt="image" src="https://github.com/baidu/amis/assets/1925898/1fb353af-240e-4e22-86ae-d090c8660c4c">
#### 当前方案：
流程图组件代码：
<img width="879" alt="image" src="https://github.com/baidu/amis/assets/1925898/6645bf61-a0a8-493d-a533-8e9197e70f2b">
context打印情况：
<img width="984" alt="image" src="https://github.com/baidu/amis/assets/1925898/157aabba-6ff5-46e4-a3aa-3fd8d0879c18">
好几处undefined？？？导致注册不上吗？？？

**Comment by wibetter** [comment]
@joelost  你这个是react组件，amis-widget（组件注册器）层没有做任何包裹，出现问题基本上可以判断是组件本身设计有问题。初步怀疑没有指定 contextType，
看下这个使用文档：https://aisuda.bce.baidu.com/aisuda-docs/NPM%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E5%A6%82%E4%BD%95%E5%AF%B9%E6%8E%A5amis%E4%BA%8B%E4%BB%B6%E5%8A%A8%E4%BD%9C。

**Comment by wibetter** [comment]
@joelost 不好意思哈，刚没注意到你的截图，看写法是没问题的，怀疑可能是amis最近改动影响导致reload失效，我们先排查和定位下，有结果反馈给你。

**Comment by wibetter** [comment]
@wibetter 我这边刚验证了下，是可以正常触发自定义组件的reload方法，
<img width="1304" alt="image" src="https://github.com/baidu/amis/assets/11958920/721e2566-9de7-43f9-8688-475604d83860">
写了简单的例子，你对比下：https://github.com/aisuda/react-custom-widget-template/tree/feat-api-data

**Comment by joelost** [comment]
总感觉较新版本的amis没有把scope context里的一些属性设置完整，导致registerComponent失效。
