### ISSUE TITLE
amis-editor-demo使用build功能不生效

### ISSUE THREAD

**Issue by echammy** [baidu/amis#10391]
#### 实现场景：
amis-editor-demo使用npm run build功能，build后的内容只有在github上拉下来的模版内容，没有自己在amis-editor-demo代码上新增修改后的内容，怎么解决？
(https://aisuda.github.io/amis-editor-demo/#/hello-world?id=1)

**Comment by wibetter** [comment]
@echammy amis-editor-demo 只是一个线上Demo啊，用的构建工具是[akfun](https://github.com/wibetter/akfun)。如果项目在用这个构建工具，可以看下配置文档。
