### ISSUE TITLE
pdf-viewer 报错

### ISSUE THREAD

**Issue by Lwenguang** [baidu/amis#10405]
#### 描述问题：

pdf-viewer 报错

#### 截图或视频：

![20240606142207](https://github.com/baidu/amis/assets/52692616/5fa4a983-45ed-42f1-bc15-802ecf415099)
![20240606142254](https://github.com/baidu/amis/assets/52692616/d2707026-b130-4142-bba5-51268549a354)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
 npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.5.0

3. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "pdf-viewer",
  "id": "u:1022e039d31f",
  "source": "src",
  "src": "http://localhost:8096/rest/uploadFile/get/name/20240604150849693-173b21ffb9d6431888246a9c3dbba9ef.pdf"
}

**Comment by shiliu2023** [comment]
这个问题已经解决并且发布了sdk吗？最新的sdk似乎还有这个问题

**Comment by Lwenguang** [comment]
> 这个问题已经解决并且发布了sdk吗？最新的sdk似乎还有问题

还没有

**Comment by codering** [comment]
@2betop
