### ISSUE TITLE
key是由多个变量拼接的情况下怎么获取到sessionStorage

### ISSUE THREAD

**Issue by month-june** [baidu/amis#10423]
#### 实现场景：
通过${ss: ['name'+ 'age']}获取不到key为nameage的sessionStorage，应该怎么获取呢

#### 存在的问题：
 通过${ss: ['name'+ 'age']}获取不到key为nameage的sessionStorage，应该怎么获取呢

#### 当前方案：
${ss: ['name'+ 'age']}

```
code here...
```

**Comment by 2betop** [comment]
试试 `${ss:&['name' + 'age']}`

**Comment by month-june** [comment]
> 试试 `${ss:&['name' + 'age']}`

试过了，没效果

**Comment by month-june** [comment]
> ${ss:&['name' + 'age']}
有效果了

**Comment by month-june** [comment]
> 试试 `${ss:&['name' + 'age']}`
多谢

**Comment by month-june** [comment]
> 试试 `${ss:&['name' + 'age']}`
多谢
