### ISSUE TITLE
Error: Invalid `workerSrc` type.     at set workerSrc

### ISSUE THREAD

**Issue by hury88** [baidu/amis#10431]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
我在用iframe访问amis-editor
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
访问后提示 __webpack_exports__GlobalWorkerOptions.workerSrc = pdfJSWorkerURL; 
提示这个pdfJSWorkerURL worksrc不是字符串 经过断点发现pdfJSWorkerURL是一个workerhanlder对象
版本
    "amis": "^6.5.0",
    "amis-core": "^6.5.0",
    "amis-formula": "^6.5.0",
    "amis-ui": "^6.5.0",
    "amis-editor": "^6.5.0",
    "amis-editor-core": "^6.5.0",
    "amis-widget": "3.2.0",

    "react": "^18.2.0",
    "react-dom": "^18.2.0",
#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
![image](https://github.com/baidu/amis/assets/22925682/8c637b5f-526b-4f2e-bacb-0479d47a27f8)
![image](https://github.com/baidu/amis/assets/22925682/007c7929-f50a-4be9-af08-bfb8befa0869)

```
code here...
```

**Comment by codering** [comment]
@2betop 6.6.0这个问题还在。 我没用到pdf相关的功能，在开发模式下没有报错，但打包压缩后就有这个问题。
