### ISSUE TITLE
如何拿到接口请求失败时后端返回的错误消息？

### ISSUE THREAD

**Issue by maxmeng93** [baidu/amis#10443]
#### 实现场景：
axios请求失败时，status code !== 200，但是接口响应中有接口自定义的错误消息，如何把这个错误消息弹出来？

#### 存在的问题：
notify: (type: 'success' | 'error' | 'info', msg) => {
  // msg 是字符串，拿不到接口失败时，后端的响应数据
}

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by CheshireJCat** [comment]
在接口适配器中，将消息赋值给 msg 字段就会显示这个错误，
```
return {
    status: 200,
    msg: '错误提示'
}
```
适配器可参考：https://baidu.github.io/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8

**Comment by maxmeng93** [comment]
@CheshireJCat 适配器在接口报错时，好像不执行吧

**Comment by CheshireJCat** [comment]
> @CheshireJCat 适配器在接口报错时，好像不执行吧

要看那种报错，你可以试试，不行就调整一下接口，让 httpCode 返回 200，数据按照 API标准格式返回就行
