### ISSUE TITLE
如何实现异步提交form 表单

### ISSUE THREAD

**Issue by Hu3sky** [baidu/amis#10449]
#### 实现场景：

实现异步提交form 表单，因为后端对表单的处理时间很长，需要前端异步提交表单，如何实现

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

没有找到如何进行异步提交表单

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by CheshireJCat** [comment]
提交后返回列表页，列表显示一个状态正在处理中
