### ISSUE TITLE
关于this.context.send的问题

### ISSUE THREAD

**Issue by Kimwill** [baidu/amis#1045]
#### 实现场景：

在自定义组件中把通过调用this.context.send()方法把authData这个数据传递给父组件，然后在自定义组件的componentWillReceiveProps钩子中拿到父组件新的值，更新authData

#### 存在的问题：

在自定义组件send给父组件的authData，在componentWillReceiveProps中接收时放在了__super中，而不是直接在data里，这是为什么？__super代表的不是更新前的数据吗
![549ad304becbc547831f4da983365830_24086](https://user-images.githubusercontent.com/37266209/98517295-a7343a00-22a8-11eb-8a1a-be2ff41d64e7.png)

#### 当前方案：

```
code here...
// 自定义组件send
scoped.send('auth', {authData: this.state.authData, flag: 1})

// 父组件schema
{
  "type": "service",
  "api": "/api/getAuthInfo",
  "body": {
    "type": 'my-tree-select',
    "nodeKey": "id",
    "defaultExpandAll": true,
    "leftColName": "视图",
    "rightColName": "操作"
  }
}
``

**Comment by 2betop** [comment]
`__super` 上个数据域的数据  `__prev` 才上之前的数据。这里有相关文档： https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/datascope-and-datachain#%E6%95%B0%E6%8D%AE%E9%93%BE

有问题欢饮再开
