### ISSUE TITLE
带有点的key值怎么链式获取？

### ISSUE THREAD

**Issue by GuridMa** [baidu/amis#10453]
#### 实现场景：
![image](https://github.com/baidu/amis/assets/74485252/817382ba-d31a-432a-94d0-c75bef961ad4)

#### 存在的问题：
请问这种带有点的key值怎么链式获取？

#### 当前方案：
我这样获取是不行的
![image](https://github.com/baidu/amis/assets/74485252/bd8ba4b1-b122-4471-bc85-c004ee3d981a)

```
code here...
```

**Comment by allenve** [comment]
```JSON
{
    "name": "ingress.xx.xxx.kubernetes['io/rewrite-target']"
}
```
