### ISSUE TITLE
关于Tree组件的新增和编辑使用

### ISSUE THREAD

**Issue by wjjhhh** [baidu/amis#1047]
#### 实现场景：
树形数据第一层跟第二层的添加和编辑内容都不同

#### 存在的问题：
1.怎么配置动态的addControls
2.编辑怎么弹框来修改的

**Comment by hq5544** [comment]
我也有同样的疑问

**Comment by RickCole21** [comment]
addControls 里用显隐吧，前提你数据中能区分开不同层级的节点

**Comment by nwind** [comment]
补了一下 addControls 的文档
