### ISSUE TITLE
在请求拦截器里面如何根据逻辑按需取消请求并且弹出提示？？

### ISSUE THREAD

**Issue by is-vino** [baidu/amis#10471]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
想要在请求拦截器里面根据逻辑按需取消请求并且弹出提示

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
无效，无法处理

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```
![Snipaste_2024-06-19_09-27-40](https://github.com/baidu/amis/assets/74162391/6caed30b-bab2-4828-b0f6-098ccadef0ef)

**Comment by 2betop** [comment]
请参考文档：https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E6%8B%A6%E6%88%AA%E8%AF%B7%E6%B1%82
