### ISSUE TITLE
searchbox控件一直是禁用状态，直接用官网的编辑器也是禁用状态

### ISSUE THREAD

**Issue by 230806bing** [baidu/amis#10485]
#### 描述问题：

searchbox控件一直是禁用状态，直接用官网的编辑器也是禁用状态

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/65208343/147f00f0-3833-4902-bf3c-2604fafbef1f)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "title": "Hello world",
  "body": [
    {
      "type": "search-box",
      "name": "keyword",
      "body": [
        {
          "type": "tpl",
          "tpl": "搜索框",
          "wrapperComponent": "",
          "inline": false,
          "disabled": false
        }
      ],
      "level": "info",
      "id": "u:31e65a4e3410",
      "visible": true,
      "mini": false,
      "searchImediately": false,
      "clearAndSubmit": false,
      "clearable": false
    }
  ],
  "id": "u:11a61911c321"
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by allenve** [comment]
searchbox 需要搭配其他组件使用  或者配置上 search 事件
具体参考文档：https://aisuda.bce.baidu.com/amis/zh-CN/components/search-box#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95
