### ISSUE TITLE
iframe组件onload/inited事件

### ISSUE THREAD

**Issue by unihon** [baidu/amis#10483]
#### 实现场景：
iframe内容加载完成事件监听

#### 存在的问题：
未找到iframe组件相关事件说明

#### 当前方案：
null

**Comment by allenve** [comment]
参考这里：https://aisuda.bce.baidu.com/amis/zh-CN/components/iframe#%E5%A6%82%E4%BD%95%E5%92%8C-iframe-%E9%80%9A%E4%BF%A1

**Comment by unihon** [comment]
iframe通信在子站点是内部研系统的情况下才可以掌控相关事件，如果是引用一些外部站点就会受限制
我的情景就是后者

**Comment by Allen-u** [comment]
`onLoad` 会通过 `postMessage` 发一个 `init` 
https://github.com/baidu/amis/blob/master/packages/amis/src/renderers/IFrame.tsx#L171
