### ISSUE TITLE
请问dialog弹出的form如果提交的时候存在必填项未输入时，dialog底部会显示“依赖的部分字段没有通过验证”

### ISSUE THREAD

**Issue by lawbc** [baidu/amis#10500]
我想要默认的情况下dialog弹出框点击提交的时候，底部不显示“依赖的部分字段没有通过验证”，或者可以api设置隐藏

**Comment by CheshireJCat** [comment]
可配置：showErrorMsg: false
![image](https://github.com/baidu/amis/assets/16409259/504390ab-c2f2-4e4b-9874-5c5f9f7c77ee)

**Comment by 2betop** [comment]
如果没有提示，通常是没有触发 form 的提交动作，而是直接保存数据了。改成触发弹窗的提交动作可显示
