### ISSUE TITLE
增删改查控件如果mode是cards，不支持rowClick事件吗，设置了点击卡片无效

### ISSUE THREAD

**Issue by 230806bing** [baidu/amis#10510]
#### 描述问题：

增删改查控件如果mode是cards，不支持rowClick事件吗，设置了点击卡片无效

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/65208343/c1876e7e-17a4-4102-a3a4-89d00d3ab918)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by CheshireJCat** [comment]
是这样设计的，rowClick 字面意思是 行点击 事件，卡片模式时没有行的概念
你需要再卡片上设置行为来给卡片添加事件，参考：https://aisuda.bce.baidu.com/amis/zh-CN/components/card#%E7%82%B9%E5%87%BB%E5%8D%A1%E7%89%87%E7%9A%84%E8%A1%8C%E4%B8%BA
