### ISSUE TITLE
表格的复制功能，可以不复制id吗，操作流程：后端返回表格数据后，然后点击复制。这样会导致这2行的id一样，提交给后端，后端处理数据的时候就会认为是同一条数据，导致数据覆盖

### ISSUE THREAD

**Issue by dengdamei** [baidu/amis#10524]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/25976723/724d823a-4920-42fd-a795-c189a9eeb679)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by CheshireJCat** [comment]
因为无法知道哪一行是 唯一列，所以无法实现
