### ISSUE TITLE
TreeSelect 树形选择器，开启多选，onlyLeaf设置为true不生效

### ISSUE THREAD

**Issue by lcl-101** [baidu/amis#10527]
#### 描述问题：

TreeSelect 树形选择器，开启多选，onlyLeaf设置为true不生效

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/13747322/13a21c5a-0efb-438a-9a2b-4e90f7f4be12)

**Comment by CheshireJCat** [comment]
![image](https://github.com/baidu/amis/assets/16409259/49cd2f96-8e74-4a62-8004-e6c660c93f9b)
抱歉，目前仅支持在单选是设置 onlyLeaf
对于多选，可以设置onlyChildren，实现只包含子节点的值

**Comment by CheshireJCat** [comment]
c
