### ISSUE TITLE
建议二维码 组件渲染的时候 将svg转成canvas 这样可以右键复制,否则无法复制图片 需要截图才可以在其他地方用

### ISSUE THREAD

**Issue by huimingxie** [baidu/amis#10535]
建议二维码 组件渲染的时候 将svg转成canvas 这样可以右键复制,否则无法复制图片 需要截图才可以在其他地方用

**Comment by CheshireJCat** [comment]
可以使用下载动作进行下载

**Comment by huimingxie** [comment]
@CheshireJCat  在钉钉或者微信移动端，下载功能无法使用。而且下载的svg图片，发送给别人微信，默认打不开的。
