### ISSUE TITLE
如何在curd里显示combo组件提交的内容？

### ISSUE THREAD

**Issue by shiliu2023** [baidu/amis#10534]
如何在curd或者table里显示combo组件提交的内容？目前按照字符串显示出来是：[{"label": "选项1", "value": "1"}, {"label": "选项2", "value": "2"}, {"label": "选项3", "value": "3"}] 这样的。想实际显示label的值，应该如何做呢？是使用tpl吗？

**Comment by allenve** [comment]
可以用 `mapping` 组件
参考：https://aisuda.bce.baidu.com/amis/zh-CN/components/mapping#%E5%AF%B9%E8%B1%A1%E6%95%B0%E7%BB%84
