### ISSUE TITLE
number显示组件精度问题

### ISSUE THREAD

**Issue by arenaswan** [baidu/amis#10566]
#### 描述问题：

当kilobitSeparator配置为false时，precision配置的值大于0，小数位最后面出现的0没有显示出来，当kilobitSeparator为true时没有这个问题

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/20719450/d3721323-f492-4fb3-96e3-5698d38a744f)
![image](https://github.com/baidu/amis/assets/20719450/0ad25d25-840a-4cae-9623-edf0db4e0891)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.5.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "number",
    "value": "13525646.30",
    "kilobitSeparator": false,
    "precision": 2
  }
}
```

4. 操作步骤
粘贴上述代码到渲染器中即可复现。

**Comment by donglixiaoche** [comment]
看了下代码
<img width="959" alt="image" src="https://github.com/baidu/amis/assets/19243114/499ddf30-01db-48d4-87f4-ea982706c7e2">

`packages/amis/src/renderers/Number.tsx` 用 `getMiniDecimal` 处理了带精度的字符串，并且做了 `toNumber` 的处理，如果精度不够用 “0” 来补充末尾的话，专成 number 会导致精度丢失。

不知道直接改成 `value = toFixed(num2str(value), '.', precision);` 是不是合理的处理方式

**Comment by donglixiaoche** [comment]
@arenaswan 对应的修改已经被合入了，后续发布了新版本可以尝试更新下看看有没有解决你的问题

**Comment by arenaswan** [comment]
> @arenaswan 对应的修改已经被合入了，后续发布了新版本可以尝试更新下看看有没有解决你的问题

太感谢了！
