### ISSUE TITLE
Each组件是否支持对item设置不同的样式

### ISSUE THREAD

**Issue by Mengleijin** [baidu/amis#10570]
#### 实现场景：
我想要通过each组件实现一个聊天对话框，用户A和用户B的聊天内容框样式不同，一个靠左，一个靠右，请问如何实现？

**Comment by CheshireJCat** [comment]
1. className 支持表达式 https://baidu.github.io/amis/zh-CN/docs/types/classname
2. style 属性也支持表达式
3. item 弄个容器，然后在里面写不同情况时的渲染，然后用 visibleOn 控制
