### ISSUE TITLE
Textarea 组件增加行数属性

### ISSUE THREAD

**Issue by 925166151** [baidu/amis#10579]
Textarea 多行文本输入框，在输入完后可以显示已经显示的行数，在用户输入完成后能直观的显示输入了多少行，用户体验会更好

**Comment by lhtuling** [comment]
![image](https://github.com/user-attachments/assets/9721f4df-42b4-4631-a6f6-1d84cd1e1348)

``````
      {
        "type": "tpl",
        "tpl": "共 ${split(a,'\n').length} 行"
      },
``````

**Comment by CheshireJCat** [comment]
目前有showCounter属性，可以显示输入字数，显示行数极少使用，不打算支持
https://baidu.github.io/amis/zh-CN/components/form/textarea#%E6%98%BE%E7%A4%BA%E8%AE%A1%E6%95%B0%E5%99%A8

**Comment by 925166151** [comment]
好吧。这个可能和场景有关系，有时候添加数据就几十个，上传文件比较麻烦。直接多行文本里面复制进来就简单快捷。你这个方案 {
        "type": "tpl",
        "tpl": "共 ${split(a,'\n').length} 行"
      }
      可以解决，但是显示在外部，不能在多行文本的输入框中显示
