### ISSUE TITLE
每个api的调用都会自动加上 $$id 这个参数，但实际会对我接口造成困扰，我想去除，应该怎么做？

### ISSUE THREAD

**Issue by XuTuKe** [baidu/amis#1057]
![image](https://user-images.githubusercontent.com/7031415/98886409-fa87d180-24ce-11eb-8924-190fa164150a.png)

**Comment by 17** [comment]
也发现了这问题。

**Comment by 2betop** [comment]
应该时编辑器的问题，用最新编辑器？或者自己写代码，传给 amis 前把这个 $$id 给干掉

**Comment by XuTuKe** [comment]
> 应该时编辑器的问题，用最新编辑器？或者自己写代码，传给 amis 前把这个 $$id 给干掉

是最新的编辑器，我是直接定义的数据，但还是会自动添加

**Comment by bluehr** [comment]
me too ，希望能fix这个问题

**Comment by nwind** [comment]
应该是已经去掉了
