### ISSUE TITLE
多语言默认中文未生效 日期选择框显示英文

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#10571]
#### 存在的问题：
语言没有设置英文，但日期选择器显示英文

![image](https://github.com/baidu/amis/assets/141314006/72b9f221-44ec-4c5c-8cc1-12827ac164e2)

**Comment by Liurf27** [comment]
你也是二次修改后单独发的包吗，有修复好这个问题不？我也遇到了这个问题

**Comment by coffin03** [comment]
> 你也是二次修改后单独发的包吗，有修复好这个问题不？我也遇到了这个问题
对 解决了 在vite.config.js 里resolve.alias 别名里加下moment的配置就行了

**Comment by Liurf27** [comment]
这个截图是已经修改后的吗，我刚刚看了一下vite.config.ts文件已经是和截图的是一样的，但是打包后发布还是无法展示中文
![1719991589204](https://github.com/baidu/amis/assets/73633448/1473e78b-59b6-4154-9b7b-d5cd6f591a50)

**Comment by Liurf27** [comment]
目前的效果图是这样的，动作配置模块的确认按钮模块也展示的英文（基于最新6.6.0版本才出现的，6.3.0版本是正常的）
![image](https://github.com/baidu/amis/assets/73633448/bb4337c6-9d1a-48dc-86c4-96975813afd0)

**Comment by hury88** [comment]
我也遇到这个问题 默认的 但是显示的是中文的时间插件  版本都是^6.5.0
