### ISSUE TITLE
嵌套弹窗中如何传递数据呢？

### ISSUE THREAD

**Issue by 973209706** [baidu/amis#10577]
一个弹窗中嵌套了一个子弹窗
子弹窗  如何把选中的数据传递给父弹窗

**Comment by skj198568** [comment]
选中的组件是否有change事件？change之后，再调用父一级的setValue，如果父一级没有setValue，则需要在父一级之上建一个service层，用于存储数据，父一级，自动继承该service的数据，不知道说清楚了没有？

**Comment by CheshireJCat** [comment]
弹窗支持data属性，把要传递的数据传到data上就可以。
data不设定将默认将触发按钮的上下文中继承数据。
