### ISSUE TITLE
Link标签是不是会有xss问题？

### ISSUE THREAD

**Issue by codedaybyday** [baidu/amis#1058]
#### 截图或视频：
![image](https://user-images.githubusercontent.com/15086407/98891619-8f8fc800-24d9-11eb-813f-0835d3e4e61b.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "link",
    "href": "javascript:alert('xss')",
    "body": "百度一下，你就知道"
  }
}
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
需要自己处理
