### ISSUE TITLE
button loading不能通过变量进行控制，只要是变量控制都认为是true

### ISSUE THREAD

**Issue by haoLingLing** [baidu/amis#10582]
{
  "type": "page",
  "data": {
      "test": false
  },
  "body": {
    "type": "button-toolbar",
    "buttons": [
      {
        "type": "button",
        "label": "默认",
        "loading": "${test}"
      },
      {
        "type": "button",
        "label": "主要",
        "level": "primary"
      },
      {
        "type": "button",
        "label": "次要",
        "level": "secondary"
      }
    ]
  }
}

官网测试代码，辛苦排查一下，需要通过变量控制

**Comment by allenve** [comment]
用  `loadingOn`

**Comment by eminoda** [comment]
@haoLingLing 

参考 form 里数据更新方式来更新 loading 字段：https://aisuda.bce.baidu.com/amis/zh-CN/components/form/index#%E5%90%88%E5%B9%B6%E6%95%B0%E6%8D%AE
