### ISSUE TITLE
最新版本，官方文档这是怎么了

### ISSUE THREAD

**Issue by Bortala17** [baidu/amis#106]
![image](https://user-images.githubusercontent.com/19968973/61114829-ba23d800-a4c3-11e9-92ea-a8c66c33cd21.png)

**Comment by 2betop** [comment]
失误，已解决，多谢反馈

**Comment by 2betop** [comment]
可能有缓存，需要等会

**Comment by 2betop** [comment]
罪过，我看现在更新过来了

**Comment by Bortala17** [comment]
我其实是想请教下，这个实时编辑预览功能是怎么实现的；
还有就是json-editor编辑器为什么我用的时候不能实时检测语法错误，比方说多加了一个逗号，但是文档上的就可以呢。

**Comment by 2betop** [comment]
跟这个有关 https://github.com/baidu/amis/blob/master/examples/components/Play.jsx#L185-L188

**Comment by 2betop** [comment]
跟开不开启 validate 有关
