### ISSUE TITLE
each组件无法使用

### ISSUE THREAD

**Issue by 13832198312** [baidu/amis#10630]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
![image](https://github.com/user-attachments/assets/e1be0da2-b3ee-499c-9a7d-cb0a82df6c2e)
```
code here...


```

**Comment by allenve** [comment]
使用 source: '${arr}' 或者在form中配合使用name
