### ISSUE TITLE
CRUD组件动态columns

### ISSUE THREAD

**Issue by unihon** [baidu/amis#10640]
#### 实现场景：
如何通过上下文变量动态配置columns
![image](https://github.com/user-attachments/assets/2dc7aa89-7331-45ce-a83b-c981caaf8371)

#### 存在的问题：
通过上下文章变量配置columns，不生效

#### 当前方案：
无

**Comment by Ben127** [comment]
尝试改成service方案吧，columns好像没法动态，我也是尝试反复查文档，最后我觉得应该不行。

**Comment by starzhuimeng** [comment]
怎么解决的呀
