### ISSUE TITLE
actionType新增toast

### ISSUE THREAD

**Issue by 502647092** [baidu/amis#1064]
#### 是否关联于某个问题吗：
点一下按钮直接触发toast提示

#### 预期的解决方案：
```
{
    "actionType": "toast",
    "toast": "toast提示"
}
```

#### 其他可接受方案：
无

#### 任何附加信息：
无

**Comment by zimo888** [comment]
不同平台toast 长得不一样，iOS，Android展示的时候就变了，我觉得这种动态的内容，还是应该由使用者决定toast 的表现形式。

**Comment by 502647092** [comment]
@zimo888 没看懂你说的意思
我一的意思支持button的actionType加一个直接触发toast的类型 和平台有什么关系

**Comment by 2betop** [comment]
一个按钮点击触发 纯粹的只是提示一下？应该是做了什么实质操作才提示吧？

**Comment by 502647092** [comment]
> 一个按钮点击触发 纯粹的只是提示一下？应该是做了什么实质操作才提示吧？

iframe相互通讯
我想用amis的toast提示
里面的提示在iframe里面 不好看
但是又没办法直接触发amis的toast提示
我现在是让他触发了一个假的ajax请求
然后在fetcher拦截 直接返回msg提示
但是总感觉不是很好
能直接通过action触发toast就方便很多了

**Comment by 2betop** [comment]
import {toast} from 'amis' 可以直接弹出
