### ISSUE TITLE
editor.worker.js 加载失败

### ISSUE THREAD

**Issue by zhd785576549** [baidu/amis#10645]
![图片](https://github.com/user-attachments/assets/8abef50b-1893-49c2-9f8a-1ab7fd7847ec)

使用react vite 集成 amis 6.0.0 版本加载Editor的时候遇到  已拦截加载自“http://localhost:5173/pkg/editor.worker.js”的 Worker，它使用了不允许的 MIME 类型（“text/html”）
请问大佬有解决方案吗

{
"scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "amis": "6.0.0",
    "amis-core": "6.0.0",
    "amis-editor": "6.0.0",
    "amis-editor-core": "6.0.0",
    "amis-formula": "6.0.0",
    "amis-ui": "6.0.0",
    "mobx": "4.15.7",
    "mobx-react": "6.3.1",
    "mobx-state-tree": "3.17.3",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-hook-form": "^7.39.3",
    "react-router": "5.0.1",
    "react-router-dom": "5.0.1",
    "vite-plugin-monaco-editor": "^1.1.0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
    "@types/lodash": "^4.14.123",
    "@types/node": "^11.13.8",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@typescript-eslint/eslint-plugin": "^7.15.0",
    "@typescript-eslint/parser": "^7.15.0",
    "@vitejs/plugin-react": "^4.3.1",
    "acorn": "^8.8.2",
    "amis-widget-cli": "^3.2.0",
    "eslint": "^8.57.0",
    "eslint-plugin-react-hooks": "^4.6.2",
    "eslint-plugin-react-refresh": "^0.4.7",
    "monaco-editor-webpack-plugin": "6.0.0",
    "prettier": "^2.2.1",
    "sass": "^1.63.4",
    "typescript": "^5.2.2",
    "vite": "^5.3.4"
  }
}

**Comment by 2betop** [comment]
vite 有个 monaco-editor 插件，要使用，用了后会覆盖 worker 地址

**Comment by zhd785576549** [comment]
> vite 有个 monaco-editor 插件，要使用，用了后会覆盖 worker 地址

"vite-plugin-monaco-editor": "^1.1.0"  是这个吗，"monaco-editor-webpack-plugin": "6.0.0", 这两个同时存在会冲突么

**Comment by zhd785576549** [comment]
在vite.config.ts中添加这个插件
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import monacoEditorPlugin from 'vite-plugin-monaco-editor'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    monacoEditorPlugin({})
  ],
})

package.json中删除
type: "module" 配置
加载成功了

**Comment by zzzz-llll** [comment]
"dependencies": {
    "@chenfengyuan/vue-qrcode": "^1.0.1",
    "@riophae/vue-treeselect": "0.4.0",
    "@wangeditor/editor": "^5.1.23",
    "amis": "6.9.0",
    "amis-core": "6.9.0",
    "amis-editor": "6.9.0",
    "amis-editor-core": "6.9.0",
    "amis-theme-editor": "^2.0.22-beta.2",
    "amis-theme-editor-helper": "^2.0.26",
    "amis-ui": "6.9.0",
    "avue-plugin-ueditor": "^0.1.4",
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "classlist-polyfill": "^1.2.0",
    "clipboard": "^2.0.4",
    "codemirror": "^5.53.2",
    "crypto-js": "^3.1.9-1",
    "echarts": "^4.2.1",
    "el-tree-transfer": "^2.4.7",
    "element-ui": "2.15.8",
    "js-cookie": "^2.2.0",
    "less-loader": "^6.0.0",
    "mobx": "^6.13.5",
    "mobx-react": "^9.1.1",
    "mobx-state-tree": "^7.0.0",
    "moment": "^2.29.4",
    "nprogress": "^0.2.0",
    "pdfjs-dist": "^4.3.136",
    "pig-avue-form-design": "^1.5.15",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "script-loader": "^0.7.2",
    "sockjs-client": "1.0.0",
    "splitpanes": "^2.4.1",
    "stomp-websocket": "2.3.4-next",
    "vue": "2.6.14",
    "vue-axios": "^2.1.2",
    "vue-clipboard2": "^0.3.0",
    "vue-cnname-avatar": "^1.0.6",
    "vue-cron": "^1.0.9",
    "vue-echarts": "^4.0.1",
    "vue-json-editor": "^1.2.3",
    "vue-json-tree-view": "^2.1.4",
    "vue-quill-editor": "3.0.6",
    "vue-router": "^3.0.2",
    "vuereact-combined": "^1.2.11",
    "vuex": "^3.0.1",
    "vxe-table": "3.6.9",
    "vxe-table-plugin-element": "1.11.4",
    "wangeditor5-for-vue2": "^0.0.8",
    "xe-utils": "^3.5.7"
  },
  "devDependencies": {
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.18.6",
    "@babel/plugin-proposal-optional-chaining": "^7.21.0",
    "@babel/plugin-proposal-private-methods": "^7.18.6",
    "@babel/plugin-transform-modules-commonjs": "^7.20.11",
    "@babel/plugin-transform-strict-mode": "^7.18.6",
    "@babel/preset-env": "^7.26.9",
    "@vue/cli-plugin-babel": "^3.12.0",
    "@vue/cli-service": "^3.12.0",
    "babel-plugin-component": "^1.1.1",
    "babel-plugin-import": "1.13.6",
    "benz-amr-recorder": "^1.0.14",
    "chai": "^4.1.2",
    "compression-webpack-plugin": "^3.1.0",
    "sass": "1.32.13",
    "sass-loader": "10.1.1",
    "tslib": "^2.8.1",
    "vue-template-compiler": "2.6.14",
    "vue-video-player": "^5.0.2"
  },  相同的问题 这应该加什么
