### ISSUE TITLE
编辑器 Shadow.tsx 内的一段代码在本地编译时候报错 

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#10667]
Node版本：v16.20.2
Npm版本：8.19.4

``````
    (shadowData!.realValue[index][type] as string) = value;
``````
修改成
``````
    shadowData!.realValue[index][type] = value;
``````
就可以正常运行！请看如何修复！本地运行各种出问题！

![image](https://github.com/user-attachments/assets/59e5abe6-a2dd-4df9-8909-bac1e6b03096)

![image](https://github.com/user-attachments/assets/6b165c64-bcf7-4b89-8d25-a7bc2b3d14ee)

**Comment by 2betop** [comment]
注释掉 i18n 插件，可能跟 `@babel/generator` 发新版本有关。或者将本地包固定成 `"@babel/generator": "7.24.7"` 的版本
