### ISSUE TITLE
刚拉的项目，跑起来报错

### ISSUE THREAD

**Issue by tiaoshuiseng** [baidu/amis#10673]
amis/packages/amis-theme-editor-helper/src/renderers/Shadow.tsx:289:49: ERROR: Expected ";" but found "="

<img width="526" alt="image" src="https://github.com/user-attachments/assets/e84703b7-61cc-41c2-8fc7-7f76c38e5b26">

**Comment by 2betop** [comment]
跟这个是一个问题 https://github.com/baidu/amis/issues/10667
