### ISSUE TITLE
[Bug report] 表头分组时 fixedTop table 表头宽度无效

### ISSUE THREAD

**Issue by Zclhlmgqzc** [baidu/amis#1068]
#### 描述问题：
表头分组时 fixedTop table 表头宽度设置无效，table-layout: fixed 去掉后正常
但是去掉 table-layout: fixed 后单行表头出现问题
加上 colgroup 后正常

#### 截图或视频：
![WC_E0%WVWV37MW }LKFN(E1](https://user-images.githubusercontent.com/31752986/99185476-216f2d80-2785-11eb-9500-fd2ab2e755d0.png)
![PZHS4PZY34Z9WONG}5$D$H0](https://user-images.githubusercontent.com/31752986/99185481-27650e80-2785-11eb-9937-c89d63a096d8.png)
![J~MRVKFK%1OJOUY6(NVBH@G](https://user-images.githubusercontent.com/31752986/99185488-2c29c280-2785-11eb-87e3-5ad397060cd1.png)
![2NE2XSM1DZJ9MC@~UT{%`FR](https://user-images.githubusercontent.com/31752986/99186563-14097180-278c-11eb-94ea-75f010661b06.png)

**Comment by nwind** [comment]
可能新版修了，目前没看到 table-layout: fixed，如果还有再报
