### ISSUE TITLE
表单项的 可见和 隐藏 的功能区别

### ISSUE THREAD

**Issue by yujxjh** [baidu/amis#10682]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by lhtuling** [comment]
就字面意思，一个可见一个隐藏，特殊场景会2个都用到，可见值取反就等于隐藏，隐藏值取反就是可见   一样效果！

**Comment by lhtuling** [comment]
Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by CheshireJCat** [comment]
字面意思，想用哪个用哪个
