### ISSUE TITLE
如何把图片点击放大的位置从中心点改成图片任何位置

### ISSUE THREAD

**Issue by qindede** [baidu/amis#10686]
#### 实现场景：
移动端，点击图片任何位置放大展示

#### 存在的问题：
需要点击图片正中心的才能放大，且还有个蒙版小眼睛的图标，我想把这些限制去掉，一点都不合理，哪怕是在pc端，我不点击图片中间就不能放大吗？这难道犯法吗？真不知道这个设计是谁想的。。。

#### 当前方案：
{
  "type": "page",
  "body": {
    "type": "image",
    "src": "../images/1578395692722/4f3cb4202335.jpeg",
    "enlargeAble": true
  }
}

**Comment by lhtuling** [comment]
增加Css样式就解决的问题~~
组件库不可能满足所有需求，提问不要那么大火气。。。
``````
.cxd-Image-overlay-view-icon{
    width: 100%;
    height: 100%;
    text-align: center;
    display: flex;
    justify-content: center;
    align-items: center;
}
``````

**Comment by lhtuling** [comment]
Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by qindede** [comment]
> Amis低代码前端框架交流群【QQ1群】：717791727 Amis低代码前端框架交流群【QQ2群】：721182449

早点有QQ群就没有那么大的怨言了，文档说不全还挺多，但是东少一块西少一块的，想交流还要硬推那个百度的企业工具，火能不大？好好的一个框架，非要这么搞

**Comment by skj198568** [comment]
直接监听image的click事件，想怎么控制都可以……

**Comment by qindede** [comment]
> 直接监听image的click事件，想怎么控制都可以……

主要是我还要用到点击放大的功能，不然又要自己写方法了
