### ISSUE TITLE
缺少年组件

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#1069]
#### 是否关联于某个问题吗：
都有月、日、时间的组件，唯独缺一个年的组件。顺便加一下呗。

年组件主要使用在一些需要直接使用年份的地方，虽然用下拉之类的模拟，但使用体验上并不好。所以，直接提供一个，月组件中选择年的组件呗

**Comment by 2betop** [comment]
年为何不直接用 select 呢

**Comment by juqkai** [comment]
比如年计划。需要选择年。
通常是下一年。这个确实可以使用select或者单选来做。但需要每次计算下一年。

如果项目运行多年，需要查询年计划，则需要往前选择。
这里就存在一个问题，select自动生成多少年的？如果生成11年，下拉上下就有5年，超过这个范围，就没法选择了。

**Comment by 2betop** [comment]
有道理
