### ISSUE TITLE
select组件，使用change事件，无法通过setValue修改回显的数据

### ISSUE THREAD

**Issue by YesterdayAk** [baidu/amis#10697]
#### 描述问题：

当选择标签中的label值，可以回显成对应的value值嘛，好像目前用setValue无效果

#### 如何复现（请务必完整填写下面内容）：

1. 粘贴有问题的完整 `amis schema` 代码：
```
      {
        "type": "select",
        "label": "标签",
        "name": "tags",
        "autoComplete": "https://user-opt-bgm.smzdm.com/api/intervention/plan/ajax_tag_search?call_service_desc=user-opt-bgm&name_like=$term",
        "placeholder": "请输入标签名",
        "multiple": true,
        "optionsTip": "请输入标签名",
        "joinValues": true,
        "checkAll": false,
        "visibleOn": "${intervention_type === 0 || intervention_type == 2}",
        "options": [],
        "onEvent": {
          "change": {
            "actions": [
              {
                "actionType": "setValue",
                "args": {
                  "value": "${value}"
                },
                "componentId": "setvalue_text"
              }
            ]
          }
        },
        "id": "setvalue_text",
        "extractValue": true // 开启仅提取值
      }
```

**Comment by lhtuling** [comment]
你这种情况换个思路就ok了 没必要这样走
给你个示例你参考一下，应该也满足你需求

![image](https://github.com/user-attachments/assets/384def7a-c96d-43ab-9fdd-80b34bbd43e0)

``````
{
  "type": "form",
  "id": "u:aaf52f08c558",
  "title": "表单",
  "mode": "horizontal",
  "dsType": "api",
  "feat": "Insert",
  "body": [
    {
      "type": "select",
      "label": "选项",
      "name": "test1",
      "options": [
        {
          "label": "选项A",
          "value": "A"
        },
        {
          "label": "选项B",
          "value": "B"
        }
      ],
      "id": "u:13206391a4f6",
      "multiple": false,
      "visibleOn": "${!test1}"
    },
    {
      "type": "group",
      "title": "",
      "collapsable": true,
      "body": [
        {
          "type": "static",
          "label": "显示选项",
          "name": "test1",
          "id": "u:165b47de8342",
          "visibleOn": "${test1}",
          "multiple": false,
          "quickEdit": false,
          "popOver": false,
          "copyable": false
        },
        {
          "type": "button",
          "label": "重新选择",
          "onEvent": {
            "click": {
              "actions": [
                {
                  "componentId": "u:aaf52f08c558",
                  "ignoreError": false,
                  "actionType": "setValue",
                  "args": {
                    "value": {
                      "test1": null
                    }
                  }
                }
              ]
            }
          },
          "id": "u:28aeee2ebf44",
          "visibleOn": "${test1}"
        }
      ],
      "id": "u:c9b926fee00e"
    }
  ],
  "actions": [
    {
      "type": "button",
      "label": "提交",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "submit",
              "componentId": "u:aaf52f08c558"
            }
          ]
        }
      },
      "level": "primary",
      "id": "u:3109e8c5a41e"
    }
  ],
  "resetAfterSubmit": true
}
``````

**Comment by lhtuling** [comment]
Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by YesterdayAk** [comment]
> 你这种情况换个思路就ok了 没必要这样走 给你个示例你参考一下，应该也满足你需求
> 
> ![image](https://private-user-images.githubusercontent.com/44140500/354207264-384def7a-c96d-43ab-9fdd-80b34bbd43e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzA3ODcsIm5iZiI6MTcyMjkzMDQ4NywicGF0aCI6Ii80NDE0MDUwMC8zNTQyMDcyNjQtMzg0ZGVmN2EtYzk2ZC00M2FiLTlmZGQtODBiMzRiYmQ0M2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3NDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlODdiNWNkYWMxY2FjYWJjMGViYzczMDM5NGYyNDk4YmRlNzYxYzU5YWFkNzUwNDUyOTNhOTk3MzJmOWFmMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3POnDKL90JmDZhui5E93uO10XSvlbLL9FdbimhyGTT0)
> 
> ```
> {
>   "type": "form",
>   "id": "u:aaf52f08c558",
>   "title": "表单",
>   "mode": "horizontal",
>   "dsType": "api",
>   "feat": "Insert",
>   "body": [
>     {
>       "type": "select",
>       "label": "选项",
>       "name": "test1",
>       "options": [
>         {
>           "label": "选项A",
>           "value": "A"
>         },
>         {
>           "label": "选项B",
>           "value": "B"
>         }
>       ],
>       "id": "u:13206391a4f6",
>       "multiple": false,
>       "visibleOn": "${!test1}"
>     },
>     {
>       "type": "group",
>       "title": "",
>       "collapsable": true,
>       "body": [
>         {
>           "type": "static",
>           "label": "显示选项",
>           "name": "test1",
>           "id": "u:165b47de8342",
>           "visibleOn": "${test1}",
>           "multiple": false,
>           "quickEdit": false,
>           "popOver": false,
>           "copyable": false
>         },
>         {
>           "type": "button",
>           "label": "重新选择",
>           "onEvent": {
>             "click": {
>               "actions": [
>                 {
>                   "componentId": "u:aaf52f08c558",
>                   "ignoreError": false,
>                   "actionType": "setValue",
>                   "args": {
>                     "value": {
>                       "test1": null
>                     }
>                   }
>                 }
>               ]
>             }
>           },
>           "id": "u:28aeee2ebf44",
>           "visibleOn": "${test1}"
>         }
>       ],
>       "id": "u:c9b926fee00e"
>     }
>   ],
>   "actions": [
>     {
>       "type": "button",
>       "label": "提交",
>       "onEvent": {
>         "click": {
>           "actions": [
>             {
>               "actionType": "submit",
>               "componentId": "u:aaf52f08c558"
>             }
>           ]
>         }
>       },
>       "level": "primary",
>       "id": "u:3109e8c5a41e"
>     }
>   ],
>   "resetAfterSubmit": true
> }
> ```

感谢大佬提供的思路，这个方案应该是可行的

**Comment by YesterdayAk** [comment]
> Amis低代码前端框架交流群【QQ1群】：717791727 Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by YesterdayAk** [comment]
感谢大佬提供的思路和方案，已经解决了~
