### ISSUE TITLE
如何完整实作一支客户订单的单据类功能(Master-Detail) ? (有偿请报价)

### ISSUE THREAD

**Issue by gexMichael** [baidu/amis#10703]
#### 实现场景：
由于对 Input-Table 的不熟悉，所以单据类程序的操作，很多功能无法实现。请参见附档。
需求：请依目前提供的简单版本，实作出相关功能，有兴趣的高手，请私信给我报价，感谢。
[genie.michael@qq.com](mailto:genie.michael@qq.com)

PS: 如果有违反版规的情况，请通知我，我会立即删除本单。
另外，如果真有类似请高手帮忙开发的需求，应该寻求哪些管道，谢谢

#### 存在的问题：
表身明细的相关操作
1.输入产品编号有2种方式，一是开窗查询产品主文件并取回(Picker)，另外也允许直接输入产品编号，重点是：当离开产品编号字段时 (OnBlur)
2.要自动带回单价 (呼叫 API，传入产品编号及客户编号)
3.并自动计算 数量*单价=小计 (应使用 Formula)
4.将数量加总，并显示到表头的【合计数量】字段 (虚拟字段)
5.将小计加总，并显示到表头的【未税合计】字段 (TotalAmount)
6.将小计加总后乘上 0.05得到税金，四舍五入到整数，并显示到表头的【税金】字段 (TaxAmount)
7.将【未税合计】+【税金】加总后，显示到表头的【总计】字段(虚拟字段)
8.除此之外，还有一个需求是将表头和表身的同名字段，当表头有输入时，在表身新增时，自动带入表头的值，但表身仍可修改 (Default Value 的概念)，常用的是预定出货日。

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```
[sa-OPOM02-CustomerOrder.docx](https://github.com/user-attachments/files/16435782/sa-OPOM02-CustomerOrder.docx)

**Comment by lhtuling** [comment]
老板，我刚好做过类似的可以帮你！QQ:644602535

下面是我建立的交流群也可以加下
Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by gexMichael** [comment]
感謝各位大神的回覆，已結案
