### ISSUE TITLE
使用OfficeViewer组件打开页面变成直接下载URL的文件，无法预览和打印

### ISSUE THREAD

**Issue by atliwen** [baidu/amis#10726]
#### 描述问题：

使用OfficeViewer组件打开页面变成直接下载URL的文件，无法预览和打印。

#### 截图或视频：
![image](https://github.com/user-attachments/assets/4f952388-5864-42ce-bd52-2ab064cc4f09)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.6.0 版本

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "id": "u:239931e3915a",
  "body": [
    {
      "id": "u:0c6b3cc55d5d",
      "type": "action",
      "label": "打印",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "print",
              "componentId": "office-viewer-print"
            }
          ]
        }
      }
    },
    {
      "id": "office-viewer-print",
      "src": "/prod-api/mapi/file/list?nameid=44a03291050b40f2bab6fe08f5626ced",
      "type": "office-viewer",
      "display": true
    }
  ],
  "regions": [
    "body"
  ],
  "pullRefresh": {
    "disabled": true
  },
  "asideResizor": false
}
```
vue文件

<template>
  <div id="box" class="divPadding"></div>
</template>

<script>
import 'amis/sdk/sdk';
import 'amis/sdk/charts';
import 'amis/sdk/exceljs';
import 'amis/sdk/papaparse';
import 'amis/sdk/tinymce';
import 'amis/sdk/xlsx';
import 'amis/sdk/barcode';
import 'amis/sdk/office-viewer';
import 'amis/sdk/markdown';
import 'amis/sdk/cropperjs';
import 'amis/sdk/color-picker';
import 'amis/sdk/codemirror';
import 'amis/sdk/json-view';

import 'amis/sdk/sdk.css'
import 'amis/lib/themes/default.css';
import 'amis/sdk/iconfont.css'
import 'amis/sdk/helper.css'

import {getId} from "@/api/tool/amis";
import {checkPermi, checkRole} from "@/utils/permission"; // 权限判断函数
export default {
  data() {
    return {
      json: {},
      amisScoped: null
    }
  },
  mounted() {
    getId(this.$route.query.amisid).then(response => {
          var json = response.data[0].json
          this.amisScoped = amisRequire('amis/embed').embed("#box", JSON.parse(json), {
            data: {checkPermi: checkPermi}
          })
        }
    );
  }
}
</script>

<style scoped>
.divPadding {
  padding: 8px;
  position: absolute;
}
</style>

5. 操作步骤

**Comment by atliwen** [comment]
发现问题了， 使用固定的 docx文件就可以，使用通过后端加载解析的docx文件就不行。

**Comment by lhtuling** [comment]
好像要修改全局的fetcher内关于文件下载的相关的位置，不要触发下载，直接返回文件流内容就行了

**Comment by lhtuling** [comment]
Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by atliwen** [comment]
API即可数据返回类型 请求头需要完全和 静态的文件一样才行。
