### ISSUE TITLE
npm run build打包报错，无法成功打包

### ISSUE THREAD

**Issue by MaybeWe** [baidu/amis#10735]
#### 实现场景：
对amis-editor-core代码进行了修改，想执行npm run build进行打包

#### 存在的问题：
打包的时候报了很多：请执行i18n update。执行了npm run i18n update后，重新执行npm run build打包，还是有一样的问题，而且有很多的错误，无法打包成功
![image](https://github.com/user-attachments/assets/26d58ac0-0dfe-439f-b35d-3a35074fda8d)
![image](https://github.com/user-attachments/assets/6b31220c-3e1a-41ab-8218-6d3cbf7a2c82)
![image](https://github.com/user-attachments/assets/a379a5d3-45f3-4dac-b9c2-368ff64c4d3c)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
部分中文没翻译，不是 fatal error，算是个 warning，所以可以继续

**Comment by MaybeWe** [comment]
> 部分中文没翻译，不是 fatal error，算是个 warning，所以可以继续

但是结束了也没有生成对应的打包后的文件，没有生成dist目录

**Comment by 2betop** [comment]
不是生成 dist 目录，是 esm 和 lib 目录，而且 vscode 的配置了不可见那些目录。

**Comment by luoyouxiu** [comment]
> 不是生成 dist 目录，是 esm 和 lib 目录，而且 vscode 的配置了不可见那些目录。

感谢回复，想请教一下，我打包确实生成了esm 和 lib 目录，但是我想生成离线文档，当我使用官方克隆下来的代码npm run就能看到该离线文档，打包之后生成了esm 和 lib 目录，那我应该怎么搞才能看到该文档呢？

**Comment by 2betop** [comment]
`npm run deploy-gh-page` 具体看 deploy-gh-pages.sh

**Comment by MaybeWe** [comment]
> 不是生成 dist 目录，是 esm 和 lib 目录，而且 vscode 的配置了不可见那些目录。

感谢回复，确实是生成了，vscode没有见，一直在vscode，以为没有生成，谢谢

**Comment by lilihong571** [comment]
想问一下，生成的esm/lib要怎么用到新项目上去呢
