### ISSUE TITLE
两三年了，问题该修了吧？

### ISSUE THREAD

**Issue by cainiaokan** [baidu/amis#10743]
https://github.com/baidu/amis/blob/9fcf8492f6023da4e09f7d07037352196f439847/packages/amis/src/renderers/Chart.tsx#L433

onChartMount和onChartUnMount没有函数体了，这样写了没有任何意义

**Comment by 2betop** [comment]
内部使用通常都是传入函数体，字符串形式缺失很少用，下个版本修复
