### ISSUE TITLE
List 列表组件通过 amis-editor 搭建，数据过多，引起整个页面滚动，有什么办法可以做List 列表局部滚动吗

### ISSUE THREAD

**Issue by 738326776zby** [baidu/amis#10744]
#### 描述问题：
List 列表组件通过 amis-editor 搭建，数据过多，引起整个页面滚动，有什么办法可以做List 列表局部滚动吗

#### 截图或视频：

![image](https://github.com/user-attachments/assets/69b28a3a-fda1-4979-8771-fe9d69a76687)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.7.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 738326776zby** [comment]
@2betop

**Comment by 2betop** [comment]
目前不支持这个，没有啥好方案，因为你要让他内滚就得设置高度，而这个高度目前只支持固定值

**Comment by 738326776zby** [comment]
> 目前不支持这个，没有啥好方案，因为你要让他内滚就得设置高度，而这个高度目前只支持固定值

嗯嗯，了解，我寻思也是，谢谢了哥
