### ISSUE TITLE
返回适配器不生效，返回数据格式仍然是原数据

### ISSUE THREAD

**Issue by doraemon424** [baidu/amis#10787]
在返回适配器里配置这样一段
<img width="527" alt="image" src="https://github.com/user-attachments/assets/b325036f-1751-40f4-a517-12b519fbce53">
打印payload可以看到已经有columns字段
<img width="466" alt="image" src="https://github.com/user-attachments/assets/00289e79-67ca-4bdb-9274-ba49869bdcca">
但查看实际返回数据仍然是原始数据
<img width="531" alt="image" src="https://github.com/user-attachments/assets/134171f7-3d2e-452e-867f-9265a0176a0d">

**Comment by 2betop** [comment]
最后一张图无法干预，这是浏览器的实际范围，但是传给组件前是你可以干预的，比如你的倒数第二张图

**Comment by 2betop** [comment]
你再补一个 status: 0 看看组件是否有效果

**Comment by doraemon424** [comment]
> 最后一张图无法干预，这是浏览器的实际范围，但是传给组件前是你可以干预的，比如你的倒数第二张图

<img width="1390" alt="image" src="https://github.com/user-attachments/assets/3827e18c-c36d-4728-ae30-9eb142f405fd">
但是官方这个例子就能在浏览器的network里看到变化

**Comment by 2betop** [comment]
没有，那个接口就是原始返回

**Comment by 2betop** [comment]
你可以通过 copy as curl 然后terminal 里面跑一下就知道了

**Comment by 2betop** [comment]
有问题再开
