### ISSUE TITLE
crud 表格合并行列

### ISSUE THREAD

**Issue by qzo123** [baidu/amis#10790]
#### 描述问题：

现在crud使用combineNum这个属性，可以实现自动合并行的，但是不能合并列呢，使用colSpan或者colSpanExpr配置不生效呢，该怎么去配置合并列呢？

![image](https://github.com/user-attachments/assets/3782a0e6-2f7b-4f89-8fac-91ea053d55e1)

**Comment by CheshireJCat** [comment]
crud不支持，table2组件支持，参考：https://baidu.github.io/amis/zh-CN/components/table2#%E8%A1%A8%E6%A0%BC%E8%A1%8C-%E5%88%97%E5%90%88%E5%B9%B6
