### ISSUE TITLE
post:https://houtai.baidu.com/api/sample 这种格式的api访问 有问题

### ISSUE THREAD

**Issue by kangxiangzhi** [baidu/amis#108]
![image](https://user-images.githubusercontent.com/18476183/61183083-0f501d00-a66f-11e9-8f2a-96fb9716b1ef.png)

post:https://houtai.baidu.com/api/sample 带前缀的url访问有问题

**Comment by kangxiangzhi** [comment]
官网的例子 都是这样的
https://baidu.github.io/amis/crud/table?page=1 
![image](https://user-images.githubusercontent.com/18476183/61183123-ab7a2400-a66f-11e9-8f81-de380e06c725.png)

**Comment by catchonme** [comment]
`amis@1.0.0-rc.7` 版本api验证存在问题，目前已修复，可以使用 `amis@1.0.0-rc.8`版本

**Comment by kangxiangzhi** [comment]
咦，我看最新的release版本是1.0.0-rc.6耶
https://github.com/baidu/amis/releases

**Comment by kangxiangzhi** [comment]
咦，我看最新的release版本是1.0.0-rc.6耶，没有你说的 amis@1.0.0-rc.8版本
https://github.com/baidu/amis/releases
![image](https://user-images.githubusercontent.com/18476183/61207794-8eedf280-a728-11e9-957c-cfc1b055aa9f.png)

**Comment by catchonme** [comment]
发版了，没有更新 release，因为是为了修复问题而发版的
