### ISSUE TITLE
crud表格 总计 出现小数计算精度问题

### ISSUE THREAD

**Issue by xiukun** [baidu/amis#10804]
#### 描述问题：

crud表格 总计 统计出现小数计算精度问题

#### 截图或视频：

![QQ_1724124475984](https://github.com/user-attachments/assets/d8813c4e-3bf5-4863-8971-c58a5e414ed8)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

amis@6.7.0

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
可以用公式调整一下输出 https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#round
