### ISSUE TITLE
饼图通过点击legend隐藏部分图表，占比不对，如何升级 echarts版本

### ISSUE THREAD

**Issue by 822795778** [baidu/amis#10849]
饼图通过点击legend隐藏部分图表，饼图占比错误。当隐藏分类时候，相邻下一个显示分分类的百分比变成隐藏的分类分百分比。例如测试数据中【Search Engine】占比 33.3%，当隐藏后，【Direct】占比就变成33.3%
  隐藏 Search Engine，Direct占比就变成原来Search Engine的占比33.3% 
看到 【 fix(amis): echarts版本升级到5.5.1 #10711】，如何AMIS中 升级版本
 {
  "type": "chart",
  "id": "u2cd875f747b7",
  "config": {
    "tooltip": {
      "trigger": "item"
    },
    "legend": {
      "top": "5%",
      "left": "center"
    },
    "series": [
      {
        "name": "Access From",
        "type": "pie",
        "radius": [
          "40%",
          "70%"
        ],
        "label": {
          "show": true,
          "formatter": "{b} {d}% \n 数量：{c}"
        },
        "data": [
          {
            "value": 1048,
            "name": "Search Engine"
          },
          {
            "value": 735,
            "name": "Direct"
          },
          {
            "value": 580,
            "name": "Email"
          },
          {
            "value": 484,
            "name": "Union Ads"
          },
          {
            "value": 300,
            "name": "Video Ads"
          }
        ]
      }
    ]
  },
  "dataFilter": ""
}

**Comment by songyinhai2006** [comment]
+1

**Comment by wibetter** [comment]
@songyinhai2006 @822795778  amis版本升级到6.8.0以上（含6.8.0）即可解决此问题。
