### ISSUE TITLE
如何删除重新上传按钮功能

### ISSUE THREAD

**Issue by personzhangjiazhen** [baidu/amis#10856]
#### 描述问题：

我想禁用重新上传图片那个功能按钮应该如何做？

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lhtuling** [comment]
隐藏不想要的东西最简单方式就是用css  不要总找配置，，不一定都有，不一定都能满足所有人要求
```
a[data-tooltip='重新上传'] {
    display: none !important;
}
```
![image](https://github.com/user-attachments/assets/a9898d80-31d3-46df-8537-302fc58a1d43)

Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by personzhangjiazhen** [comment]
我是一个后端开发，不知道把你上面那段代码放到哪里？是直接放到"type": "input-image" 这个组件中么？应该怎么放？
