### ISSUE TITLE
CRUD 的 Images 组件的 source 参数不支持过滤器吗？

### ISSUE THREAD

**Issue by 17** [baidu/amis#1086]
#### 实现场景：
使用 CRUD 组件展示图片的时，只想要展示数组中的部分图片

#### 存在的问题：
Images 组件，使用 source 定义来源时，却发现 images 组件中的 source 不支持过滤器，Json 组件却能够正常使用。

#### 当前方案：

```
{
    "type": "images",
    "label": "图片集",
    "source": "${details|pick:cover|first}"
}
```

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/1087

**Comment by 17** [comment]
thx , 最近发布的更新对整合 react 的人太友好了，期待早点发布新版本。
