### ISSUE TITLE
复制事件如何自定义提示内容

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#10863]
#### 实现场景：
![image](https://github.com/user-attachments/assets/c36a92a0-0483-46b2-9983-90bfa65b33bc)

#### 存在的问题：
想要自定义提示内容，发现设置"preventDefault": true,和"stopPropagation": true,都无法阻止默认提示弹出。
能参数修改提示的内容吗？或者是不弹出默认提示。

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
{
      "type": "button",
      "label": "复制一段文本",
      "level": "primary",
      "className": "mr-2",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "copy",
              "preventDefault": true,
              "stopPropagation": true,
              "args": {
                "content": "http://www.baidu.com"
              }
            }
          ]
        }
      }
    },
```

**Comment by lhtuling** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/getting-started#copy
看文档，初始化时候env里面做配置就行了

``````
          copy: (content, options) => {
            amisLib.toast.success('测试内容！');
            return;
          },
``````

Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449
