### ISSUE TITLE
上传图片和上传文件能不能加个输入框，既可以上传，也可以填写网址

### ISSUE THREAD

**Issue by warran2** [baidu/amis#10868]
在做内容管理系统的时候，如果要求一个图片有可能是上传，也有可能是填写url，就方便很多。免得下面在加个input-text

因为字段非常多，如果那样加，工作量很大，页面也不好布置

**Comment by lhtuling** [comment]
![image](https://github.com/user-attachments/assets/cea3e668-18c7-4449-9111-7ee97751b25f)

很简单的，下面放一个同name的文本框就搞定了！

Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by CheshireJCat** [comment]
没有这个计划，因为这个是组件库，组件的功能设计要遵循单一性，上传组件就只负责上传，而不负责填写地址
你的混合逻辑属于业务层面，需要自己实现
