### ISSUE TITLE
Next.js使用Amis-Editor报错[mobx-state-tree] expected mobx-state-tree node as argument 1, got undefined instead

### ISSUE THREAD

**Issue by ryangamil** [baidu/amis#10872]
#### 描述问题：
想在Next.js项目中使用编辑器，根据可视化编辑器的文档 [https://github.com/aisuda/amis-editor-demo](https://github.com/aisuda/amis-editor-demo) “在其他项目中使用amis-editor”章节（图1）的使用方式引入报错
1、使用npx create-next-app 创建项目后，直接引入Amis-Editor后运行报错mobx-react未找到（图2）
2、手动引入与amis相同版本的mobx-react后再运行，报错[mobx-state-tree] expected mobx-state-tree node as argument 1, got undefined instead（图3）

#### 截图或视频：
![3c10ff3c65883da50484066a4e5a4ee2](https://github.com/user-attachments/assets/dd771da7-889d-47b1-bd31-e039f4c8d913)

![5d64f209a835793c13adb9c7839a60ec](https://github.com/user-attachments/assets/4fe7027e-39a7-4e35-bd80-53f900a11bf3)

![6443ef81d58db4004f7e6f8d89cdec57](https://github.com/user-attachments/assets/1aa1c46e-5973-441c-a4f3-890f74c91cca)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm
node版本18.19.1

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis-editor版本为最新的6.8.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
const amisJSON = {
    type: "page",
    body: "测试",
    title: "标题",
}
```

4. 操作步骤
此处提供一个rep：[https://github.com/ryangamil/nextjs-amis-editor-demo](https://github.com/ryangamil/nextjs-amis-editor-demo)
执行
npm i --legacy-peer-deps
npm run dev
后可在网页中查看

**Comment by ryangamil** [comment]
```
const nextConfig = {
    reactStrictMode: false,
};
```
在nextConfig中关闭react的严格模式可以打开了

**Comment by linxiaowu66** [comment]
这个真的是坑货啊，文档也不写一些开发环境下开启严格模式会导致打不开，不要用React.StrictMode就可以打开

**Comment by lizyChy0329** [comment]
> 这个真的是坑货啊，文档也不写一些开发环境下开启严格模式会导致打不开，不要用React.StrictMode就可以打开

`React.StrictMode: false` 又会导致只能使用 page routes, 进而出现 `Global CSS cannot be imported from within node_modules` 错误

**Comment by linxiaowu66** [comment]
> > 这个真的是坑货啊，文档也不写一些开发环境下开启严格模式会导致打不开，不要用React.StrictMode就可以打开
> 
> `React.StrictMode: false` 又会导致只能使用 page routes, 进而出现 `Global CSS cannot be imported from within node_modules` 错误

不会的，直接把Strict的那个标签去掉就行了，不去配置false这种
