### ISSUE TITLE
如果整个表单禁用，希望可设置单个表单项不禁用

### ISSUE THREAD

**Issue by BobsLi** [baidu/amis#10879]
#### 是否关联于某个问题吗：
需求是：当禁用整个表单后，我希望可以设置单个表单项不被禁用
代码如下：
`{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "disabled": true,
    "body": [
      {
        "type": "input-text",
        "name": "name",
        "label": "姓名：",
        "disabled": false
      },
      {
        "name": "email",
        "type": "input-email",
        "label": "邮箱："
      }
    ]
  }
}`

#### 预期的解决方案：
单个表单项设置优先级比整个表单优先级高

#### 任何附加信息：
目前不生效图片

**Comment by lhtuling** [comment]
这个功能感觉确实有必要，如果表单项多是会设置简单很多，看看官方是否修改了


Amis低代码前端框架交流群【QQ 1群】：717791727
Amis低代码前端框架交流群【QQ 2群】：721182449

**Comment by CheshireJCat** [comment]
不会修改
1. 这种场景不常见，逻辑上也有歧义，禁用类似于权限控制，子权限不能高于父级
2. 可以改用 static 静态展示，表单设置 static: true，表单项 static: false
