### ISSUE TITLE
可以把图片上传从裁剪框变为选取框？

### ISSUE THREAD

**Issue by personzhangjiazhen** [baidu/amis#10888]
#### 是否关联于某个问题吗：
可以把图片上传从裁剪框变为选取框么？或者从裁剪框变为选取框？

#### 预期的解决方案：
支持裁剪框和选取框

#### 其他可接受方案：
使用其他CSS的方式也可以

#### 任何附加信息：
![image](https://github.com/user-attachments/assets/4e526519-2abc-4fae-baab-d93f1d60d96f)

**Comment by CheshireJCat** [comment]
啥意思？

**Comment by personzhangjiazhen** [comment]
选取框就像微信或者其他软件的截图，是通过拖拽的方式

> 啥意思？什么是选取框

**Comment by CheshireJCat** [comment]
> 选取框就像微信或者其他软件的截图，是通过拖拽的方式
> 
> > 啥意思？什么是选取框

没有，不支持
