### ISSUE TITLE
amis渲染器（不是编辑器），有没api直接设置当前页面所有组件为禁用，或者有没只读模式直接进入。

### ISSUE THREAD

**Issue by youlika1234** [baidu/amis#10896]
#### 实现场景：
我想实现当工单进入已办的时候，直接进入只读模式不允许编辑

#### 存在的问题：
查不到当前的文档有任何设置的地方。需要类似的api或者配置。

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by lhtuling** [comment]
据我所知没有，单个对父级组件设置static吧   应该也不算太麻烦  比如form直接设置static:true，整个就禁用了   一样效果


Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by youlika1234** [comment]
如果是对于不具备static属性的组件，只能是逐个的去遍历去控制？

**Comment by CheshireJCat** [comment]
没有一棒子全打死的配置，也不合理，只能是根据需求去配置，form 表单项组件的话，给 父级 form 设置 static 或者 disabled 就行了
