### ISSUE TITLE
amis渲染器有没事件可以监听到当前的页面渲染完成。或者说有没类似的钩子

### ISSUE THREAD

**Issue by youlika1234** [baidu/amis#10897]
#### 实现场景：
我想在页面渲染完后对组件进行控制

#### 存在的问题：
发现我无法预知amis的页面如何才算渲染完成。

#### 当前方案：

```
code here...
```

**Comment by lhtuling** [comment]
根据我简单测试结果
page的初始化事件就是在内部组件全部渲染完毕后执行的

以下代码通过F12预览执行，断点逐步调试你会发现我的测试结果，应该可以满足大部分需求了

Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449


``````
{
  "type": "page",
  "body": [
    {
      "type": "service",
      "body": [
        {
          "id": "u:4290634dc4e9",
          "type": "crud2",
          "mode": "table2",
          "dsType": "api",
          "syncLocation": true,
          "primaryField": "id",
          "loadType": "pagination",
          "headerToolbar": [
            {
              "type": "flex",
              "direction": "row",
              "justify": "flex-start",
              "alignItems": "stretch",
              "style": {
                "position": "static"
              },
              "items": [
                {
                  "type": "container",
                  "align": "left",
                  "behavior": [
                    "Insert",
                    "BulkEdit",
                    "BulkDelete"
                  ],
                  "body": [],
                  "wrapperBody": false,
                  "style": {
                    "flexGrow": 1,
                    "flex": "1 1 auto",
                    "position": "static",
                    "display": "flex",
                    "flexDirection": "row",
                    "flexWrap": "nowrap",
                    "alignItems": "stretch",
                    "justifyContent": "flex-start"
                  },
                  "id": "u:7173149631e4",
                  "isFixedHeight": false
                },
                {
                  "type": "container",
                  "align": "right",
                  "behavior": [
                    "FuzzyQuery"
                  ],
                  "body": [],
                  "wrapperBody": false,
                  "style": {
                    "flexGrow": 1,
                    "flex": "1 1 auto",
                    "position": "static",
                    "display": "flex",
                    "flexBasis": "auto",
                    "flexDirection": "row",
                    "flexWrap": "nowrap",
                    "alignItems": "stretch",
                    "justifyContent": "flex-end"
                  },
                  "id": "u:46ec70a2fa48"
                }
              ],
              "id": "u:e49fcd3381f5"
            }
          ],
          "footerToolbar": [
            {
              "type": "flex",
              "direction": "row",
              "justify": "flex-start",
              "alignItems": "stretch",
              "style": {
                "position": "static"
              },
              "items": [
                {
                  "type": "container",
                  "align": "left",
                  "body": [
                    {
                      "type": "service",
                      "body": [],
                      "id": "u:9c0ecbda148b",
                      "dsType": "api",
                      "onEvent": {
                        "init": {
                          "weight": 0,
                          "actions": [
                            {
                              "ignoreError": false,
                              "script": "// table内部 service初始化\ndebugger",
                              "actionType": "custom"
                            }
                          ]
                        }
                      }
                    }
                  ],
                  "wrapperBody": false,
                  "style": {
                    "flexGrow": 1,
                    "flex": "1 1 auto",
                    "position": "static",
                    "display": "flex",
                    "flexBasis": "auto",
                    "flexDirection": "row",
                    "flexWrap": "nowrap",
                    "alignItems": "stretch",
                    "justifyContent": "flex-start"
                  },
                  "id": "u:9c2d523b573b"
                },
                {
                  "type": "container",
                  "align": "right",
                  "body": [
                    {
                      "type": "pagination",
                      "behavior": "Pagination",
                      "layout": [
                        "total",
                        "perPage",
                        "pager"
                      ],
                      "perPage": 10,
                      "perPageAvailable": [
                        10,
                        20,
                        50,
                        100
                      ],
                      "align": "right",
                      "id": "u:d4b7ab72cfc8"
                    }
                  ],
                  "wrapperBody": false,
                  "style": {
                    "flexGrow": 1,
                    "flex": "1 1 auto",
                    "position": "static",
                    "display": "flex",
                    "flexBasis": "auto",
                    "flexDirection": "row",
                    "flexWrap": "nowrap",
                    "alignItems": "stretch",
                    "justifyContent": "flex-end"
                  },
                  "id": "u:0b3415e18c49"
                }
              ],
              "id": "u:3c2375968cbb"
            }
          ],
          "columns": [],
          "editorSetting": {
            "mock": {
              "enable": true,
              "maxDisplayRows": 5
            }
          }
        }
      ],
      "id": "u:83359982b32f",
      "dsType": "api",
      "onEvent": {
        "fetchSchemaInited": {
          "weight": 0,
          "actions": [
            {
              "ignoreError": false,
              "script": "// service  schema接口请求完成\ndebugger",
              "actionType": "custom",
              "args": {}
            }
          ]
        },
        "init": {
          "weight": 0,
          "actions": [
            {
              "ignoreError": false,
              "script": "// service  初始化\ndebugger",
              "actionType": "custom"
            }
          ]
        },
        "fetchInited": {
          "weight": 0,
          "actions": [
            {
              "ignoreError": false,
              "script": "// service  初始化数据接口请求完成\ndebugger",
              "actionType": "custom"
            }
          ]
        }
      }
    }
  ],
  "id": "u:ed174190b6c5",
  "asideResizor": false,
  "pullRefresh": {
    "disabled": true
  },
  "data": {
    "arr": [
      {
        "name": "a",
        "subList": [
          "a1",
          "a2"
        ]
      }
    ]
  },
  "aside": [],
  "toolbar": [],
  "regions": [
    "body"
  ],
  "onEvent": {
    "init": {
      "weight": 0,
      "actions": [
        {
          "ignoreError": false,
          "script": "//页面初始化\r\ndebugger",
          "actionType": "custom",
          "args": {}
        }
      ]
    }
  }
}
``````

**Comment by youlika1234** [comment]
我是通过sdk的方式，如果我是想通过amisScope实例来监听是否就没办法？我是要在外部控制不直接去污染配置信息。

**Comment by youlika1234** [comment]
> 根据我简单测试结果 page的初始化事件就是在内部组件全部渲染完毕后执行的
> 
> 以下代码通过F12预览执行，断点逐步调试你会发现我的测试结果，应该可以满足大部分需求了
> 
> Amis低代码前端框架交流群【QQ1群】：717791727 Amis低代码前端框架交流群【QQ2群】：721182449
> 
> ```
> {
>   "type": "page",
>   "body": [
>     {
>       "type": "service",
>       "body": [
>         {
>           "id": "u:4290634dc4e9",
>           "type": "crud2",
>           "mode": "table2",
>           "dsType": "api",
>           "syncLocation": true,
>           "primaryField": "id",
>           "loadType": "pagination",
>           "headerToolbar": [
>             {
>               "type": "flex",
>               "direction": "row",
>               "justify": "flex-start",
>               "alignItems": "stretch",
>               "style": {
>                 "position": "static"
>               },
>               "items": [
>                 {
>                   "type": "container",
>                   "align": "left",
>                   "behavior": [
>                     "Insert",
>                     "BulkEdit",
>                     "BulkDelete"
>                   ],
>                   "body": [],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-start"
>                   },
>                   "id": "u:7173149631e4",
>                   "isFixedHeight": false
>                 },
>                 {
>                   "type": "container",
>                   "align": "right",
>                   "behavior": [
>                     "FuzzyQuery"
>                   ],
>                   "body": [],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexBasis": "auto",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-end"
>                   },
>                   "id": "u:46ec70a2fa48"
>                 }
>               ],
>               "id": "u:e49fcd3381f5"
>             }
>           ],
>           "footerToolbar": [
>             {
>               "type": "flex",
>               "direction": "row",
>               "justify": "flex-start",
>               "alignItems": "stretch",
>               "style": {
>                 "position": "static"
>               },
>               "items": [
>                 {
>                   "type": "container",
>                   "align": "left",
>                   "body": [
>                     {
>                       "type": "service",
>                       "body": [],
>                       "id": "u:9c0ecbda148b",
>                       "dsType": "api",
>                       "onEvent": {
>                         "init": {
>                           "weight": 0,
>                           "actions": [
>                             {
>                               "ignoreError": false,
>                               "script": "// table内部 service初始化\ndebugger",
>                               "actionType": "custom"
>                             }
>                           ]
>                         }
>                       }
>                     }
>                   ],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexBasis": "auto",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-start"
>                   },
>                   "id": "u:9c2d523b573b"
>                 },
>                 {
>                   "type": "container",
>                   "align": "right",
>                   "body": [
>                     {
>                       "type": "pagination",
>                       "behavior": "Pagination",
>                       "layout": [
>                         "total",
>                         "perPage",
>                         "pager"
>                       ],
>                       "perPage": 10,
>                       "perPageAvailable": [
>                         10,
>                         20,
>                         50,
>                         100
>                       ],
>                       "align": "right",
>                       "id": "u:d4b7ab72cfc8"
>                     }
>                   ],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexBasis": "auto",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-end"
>                   },
>                   "id": "u:0b3415e18c49"
>                 }
>               ],
>               "id": "u:3c2375968cbb"
>             }
>           ],
>           "columns": [],
>           "editorSetting": {
>             "mock": {
>               "enable": true,
>               "maxDisplayRows": 5
>             }
>           }
>         }
>       ],
>       "id": "u:83359982b32f",
>       "dsType": "api",
>       "onEvent": {
>         "fetchSchemaInited": {
>           "weight": 0,
>           "actions": [
>             {
>               "ignoreError": false,
>               "script": "// service  schema接口请求完成\ndebugger",
>               "actionType": "custom",
>               "args": {}
>             }
>           ]
>         },
>         "init": {
>           "weight": 0,
>           "actions": [
>             {
>               "ignoreError": false,
>               "script": "// service  初始化\ndebugger",
>               "actionType": "custom"
>             }
>           ]
>         },
>         "fetchInited": {
>           "weight": 0,
>           "actions": [
>             {
>               "ignoreError": false,
>               "script": "// service  初始化数据接口请求完成\ndebugger",
>               "actionType": "custom"
>             }
>           ]
>         }
>       }
>     }
>   ],
>   "id": "u:ed174190b6c5",
>   "asideResizor": false,
>   "pullRefresh": {
>     "disabled": true
>   },
>   "data": {
>     "arr": [
>       {
>         "name": "a",
>         "subList": [
>           "a1",
>           "a2"
>         ]
>       }
>     ]
>   },
>   "aside": [],
>   "toolbar": [],
>   "regions": [
>     "body"
>   ],
>   "onEvent": {
>     "init": {
>       "weight": 0,
>       "actions": [
>         {
>           "ignoreError": false,
>           "script": "//页面初始化\r\ndebugger",
>           "actionType": "custom",
>           "args": {}
>         }
>       ]
>     }
>   }
> }
> ```

我是通过sdk的方式，如果我是想通过amisScope实例来监听是否就没办法？我是要在外部控制不直接去污染配置信息。

**Comment by youlika1234** [comment]
暂时看不到有外部的api去控制。我是通过在vue中封装了amis渲染器，外部使用amis需要知道amis是否渲染完成。我的方案代码如下，希望能帮到其他人。
```
function emitTrigger(params) {
        this.$emit('ready')
}

window.emitTrigger = emitTrigger.bind(this)
// 需要通过在schema中扩展额外的actionType，避免将外部的actionType给覆盖。通过自定义脚本的方式控制emit触发事件
actions: [
         
     {
            actionType: 'custom',
            script: 'emitTrigger()'
     }
 ]
````

**Comment by liuling1314** [comment]
> 根据我简单测试结果 page的初始化事件就是在内部组件全部渲染完毕后执行的
> 
> 以下代码通过F12预览执行，断点逐步调试你会发现我的测试结果，应该可以满足大部分需求了
> 
> Amis低代码前端框架交流群【QQ1群】：717791727 Amis低代码前端框架交流群【QQ2群】：721182449
> 
> ```
> {
>   "type": "page",
>   "body": [
>     {
>       "type": "service",
>       "body": [
>         {
>           "id": "u:4290634dc4e9",
>           "type": "crud2",
>           "mode": "table2",
>           "dsType": "api",
>           "syncLocation": true,
>           "primaryField": "id",
>           "loadType": "pagination",
>           "headerToolbar": [
>             {
>               "type": "flex",
>               "direction": "row",
>               "justify": "flex-start",
>               "alignItems": "stretch",
>               "style": {
>                 "position": "static"
>               },
>               "items": [
>                 {
>                   "type": "container",
>                   "align": "left",
>                   "behavior": [
>                     "Insert",
>                     "BulkEdit",
>                     "BulkDelete"
>                   ],
>                   "body": [],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-start"
>                   },
>                   "id": "u:7173149631e4",
>                   "isFixedHeight": false
>                 },
>                 {
>                   "type": "container",
>                   "align": "right",
>                   "behavior": [
>                     "FuzzyQuery"
>                   ],
>                   "body": [],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexBasis": "auto",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-end"
>                   },
>                   "id": "u:46ec70a2fa48"
>                 }
>               ],
>               "id": "u:e49fcd3381f5"
>             }
>           ],
>           "footerToolbar": [
>             {
>               "type": "flex",
>               "direction": "row",
>               "justify": "flex-start",
>               "alignItems": "stretch",
>               "style": {
>                 "position": "static"
>               },
>               "items": [
>                 {
>                   "type": "container",
>                   "align": "left",
>                   "body": [
>                     {
>                       "type": "service",
>                       "body": [],
>                       "id": "u:9c0ecbda148b",
>                       "dsType": "api",
>                       "onEvent": {
>                         "init": {
>                           "weight": 0,
>                           "actions": [
>                             {
>                               "ignoreError": false,
>                               "script": "// table内部 service初始化\ndebugger",
>                               "actionType": "custom"
>                             }
>                           ]
>                         }
>                       }
>                     }
>                   ],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexBasis": "auto",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-start"
>                   },
>                   "id": "u:9c2d523b573b"
>                 },
>                 {
>                   "type": "container",
>                   "align": "right",
>                   "body": [
>                     {
>                       "type": "pagination",
>                       "behavior": "Pagination",
>                       "layout": [
>                         "total",
>                         "perPage",
>                         "pager"
>                       ],
>                       "perPage": 10,
>                       "perPageAvailable": [
>                         10,
>                         20,
>                         50,
>                         100
>                       ],
>                       "align": "right",
>                       "id": "u:d4b7ab72cfc8"
>                     }
>                   ],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexBasis": "auto",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-end"
>                   },
>                   "id": "u:0b3415e18c49"
>                 }
>               ],
>               "id": "u:3c2375968cbb"
>             }
>           ],
>           "columns": [],
>           "editorSetting": {
>             "mock": {
>               "enable": true,
>               "maxDisplayRows": 5
>             }
>           }
>         }
>       ],
>       "id": "u:83359982b32f",
>       "dsType": "api",
>       "onEvent": {
>         "fetchSchemaInited": {
>           "weight": 0,
>           "actions": [
>             {
>               "ignoreError": false,
>               "script": "// service  schema接口请求完成\ndebugger",
>               "actionType": "custom",
>               "args": {}
>             }
>           ]
>         },
>         "init": {
>           "weight": 0,
>           "actions": [
>             {
>               "ignoreError": false,
>               "script": "// service  初始化\ndebugger",
>               "actionType": "custom"
>             }
>           ]
>         },
>         "fetchInited": {
>           "weight": 0,
>           "actions": [
>             {
>               "ignoreError": false,
>               "script": "// service  初始化数据接口请求完成\ndebugger",
>               "actionType": "custom"
>             }
>           ]
>         }
>       }
>     }
>   ],
>   "id": "u:ed174190b6c5",
>   "asideResizor": false,
>   "pullRefresh": {
>     "disabled": true
>   },
>   "data": {
>     "arr": [
>       {
>         "name": "a",
>         "subList": [
>           "a1",
>           "a2"
>         ]
>       }
>     ]
>   },
>   "aside": [],
>   "toolbar": [],
>   "regions": [
>     "body"
>   ],
>   "onEvent": {
>     "init": {
>       "weight": 0,
>       "actions": [
>         {
>           "ignoreError": false,
>           "script": "//页面初始化\r\ndebugger",
>           "actionType": "custom",
>           "args": {}
>         }
>       ]
>     }
>   }
> }
> ```

大佬你好，我用你的代码试用了下，确实是page的初始化在最后执行，但是当我page里面有crud卡片列表组件时，在page初始化，写js脚本获取所有卡片dom树时，获取不到，我的目的是想在鼠标悬浮卡片时，卡片里面的查看详情按钮出现。当我在最里面加一个 service定义一个初始化 脚本获取dom树时，能获取到，但是每个卡片都会执行一次，大佬帮忙给看看，这个有其他解决方案吗，谢谢

**Comment by liuling1314** [comment]
> 暂时看不到有外部的api去控制。我是通过在vue中封装了amis渲染器，外部使用amis需要知道amis是否渲染完成。我的方案代码如下，希望能帮到其他人。
> 
> ```
> function emitTrigger(params) {
>         this.$emit('ready')
> }
> 
> window.emitTrigger = emitTrigger.bind(this)
> // 需要通过在schema中扩展额外的actionType，避免将外部的actionType给覆盖。通过自定义脚本的方式控制emit触发事件
> actions: [
>          
>      {
>             actionType: 'custom',
>             script: 'emitTrigger()'
>      }
>  ]
> ```

我也碰到这个问题了，像你这个，如果用原生js有实现方式吗，还有这个actions: 应该加在哪里

**Comment by youlika1234** [comment]
> > 暂时看不到有外部的api去控制。我是通过在vue中封装了amis渲染器，外部使用amis需要知道amis是否渲染完成。我的方案代码如下，希望能帮到其他人。
> > ```
> > function emitTrigger(params) {
> >         this.$emit('ready')
> > }
> > 
> > window.emitTrigger = emitTrigger.bind(this)
> > // 需要通过在schema中扩展额外的actionType，避免将外部的actionType给覆盖。通过自定义脚本的方式控制emit触发事件
> > actions: [
> >          
> >      {
> >             actionType: 'custom',
> >             script: 'emitTrigger()'
> >      }
> >  ]
> > ```
> 
> 我也碰到这个问题了，像你这个，如果用原生js有实现方式吗，还有这个actions: 应该加在哪里

用原生的也可以的。问题不大，但是我不知道你的项目是怎么样的。有兴趣也可以加我vx: 534228345

**Comment by ghost** [comment]
原来如此, 谢谢. 这个方法好.

**Comment by ghost** [comment]
> 根据我简单的测试结果 页面的初始化事件就是在内部组件全部渲染完毕后执行的
> 
> 以下代码通过F12预览执行，断点逐步调试你会发现我的测试结果，应该可以满足大部分需求了
> 
> Amis低代码前端框架交流群【QQ1群】：717791727 Amis低代码前端框架交流群【QQ2群】：721182449
> 
> ```
> {
>   "type": "page",
>   "body": [
>     {
>       "type": "service",
>       "body": [
>         {
>           "id": "u:4290634dc4e9",
>           "type": "crud2",
>           "mode": "table2",
>           "dsType": "api",
>           "syncLocation": true,
>           "primaryField": "id",
>           "loadType": "pagination",
>           "headerToolbar": [
>             {
>               "type": "flex",
>               "direction": "row",
>               "justify": "flex-start",
>               "alignItems": "stretch",
>               "style": {
>                 "position": "static"
>               },
>               "items": [
>                 {
>                   "type": "container",
>                   "align": "left",
>                   "behavior": [
>                     "Insert",
>                     "BulkEdit",
>                     "BulkDelete"
>                   ],
>                   "body": [],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-start"
>                   },
>                   "id": "u:7173149631e4",
>                   "isFixedHeight": false
>                 },
>                 {
>                   "type": "container",
>                   "align": "right",
>                   "behavior": [
>                     "FuzzyQuery"
>                   ],
>                   "body": [],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexBasis": "auto",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-end"
>                   },
>                   "id": "u:46ec70a2fa48"
>                 }
>               ],
>               "id": "u:e49fcd3381f5"
>             }
>           ],
>           "footerToolbar": [
>             {
>               "type": "flex",
>               "direction": "row",
>               "justify": "flex-start",
>               "alignItems": "stretch",
>               "style": {
>                 "position": "static"
>               },
>               "items": [
>                 {
>                   "type": "container",
>                   "align": "left",
>                   "body": [
>                     {
>                       "type": "service",
>                       "body": [],
>                       "id": "u:9c0ecbda148b",
>                       "dsType": "api",
>                       "onEvent": {
>                         "init": {
>                           "weight": 0,
>                           "actions": [
>                             {
>                               "ignoreError": false,
>                               "script": "// table内部 service初始化\ndebugger",
>                               "actionType": "custom"
>                             }
>                           ]
>                         }
>                       }
>                     }
>                   ],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexBasis": "auto",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-start"
>                   },
>                   "id": "u:9c2d523b573b"
>                 },
>                 {
>                   "type": "container",
>                   "align": "right",
>                   "body": [
>                     {
>                       "type": "pagination",
>                       "behavior": "Pagination",
>                       "layout": [
>                         "total",
>                         "perPage",
>                         "pager"
>                       ],
>                       "perPage": 10,
>                       "perPageAvailable": [
>                         10,
>                         20,
>                         50,
>                         100
>                       ],
>                       "align": "right",
>                       "id": "u:d4b7ab72cfc8"
>                     }
>                   ],
>                   "wrapperBody": false,
>                   "style": {
>                     "flexGrow": 1,
>                     "flex": "1 1 auto",
>                     "position": "static",
>                     "display": "flex",
>                     "flexBasis": "auto",
>                     "flexDirection": "row",
>                     "flexWrap": "nowrap",
>                     "alignItems": "stretch",
>                     "justifyContent": "flex-end"
>                   },
>                   "id": "u:0b3415e18c49"
>                 }
>               ],
>               "id": "u:3c2375968cbb"
>             }
>           ],
>           "columns": [],
>           "editorSetting": {
>             "mock": {
>               "enable": true,
>               "maxDisplayRows": 5
>             }
>           }
>         }
>       ],
>       "id": "u:83359982b32f",
>       "dsType": "api",
>       "onEvent": {
>         "fetchSchemaInited": {
>           "weight": 0,
>           "actions": [
>             {
>               "ignoreError": false,
>               "script": "// service  schema接口请求完成\ndebugger",
>               "actionType": "custom",
>               "args": {}
>             }
>           ]
>         },
>         "init": {
>           "weight": 0,
>           "actions": [
>             {
>               "ignoreError": false,
>               "script": "// service  初始化\ndebugger",
>               "actionType": "custom"
>             }
>           ]
>         },
>         "fetchInited": {
>           "weight": 0,
>           "actions": [
>             {
>               "ignoreError": false,
>               "script": "// service  初始化数据接口请求完成\ndebugger",
>               "actionType": "custom"
>             }
>           ]
>         }
>       }
>     }
>   ],
>   "id": "u:ed174190b6c5",
>   "asideResizor": false,
>   "pullRefresh": {
>     "disabled": true
>   },
>   "data": {
>     "arr": [
>       {
>         "name": "a",
>         "subList": [
>           "a1",
>           "a2"
>         ]
>       }
>     ]
>   },
>   "aside": [],
>   "toolbar": [],
>   "regions": [
>     "body"
>   ],
>   "onEvent": {
>     "init": {
>       "weight": 0,
>       "actions": [
>         {
>           "ignoreError": false,
>           "script": "//页面初始化\r\ndebugger",
>           "actionType": "custom",
>           "args": {}
>         }
>       ]
>     }
>   }
> }
> ```

实际测试, 这个不是渲染完成的事件, 是接口请求完毕的事件.
