### ISSUE TITLE
picker能否选择多行回填对应inputtable多行

### ISSUE THREAD

**Issue by songyinhai2006** [baidu/amis#10905]
#### 是否关联于某个问题吗：
![image](https://github.com/user-attachments/assets/4d5c6029-6a80-4831-9d34-45198a329b98)
picker能否选择多行回填到inputtable,如截图

#### 任何附加信息：
![image](https://github.com/user-attachments/assets/ad267096-bd48-4b21-b5f7-e06f3064c495)

**Comment by lhtuling** [comment]
应该是可以通过自定义js赋值来处理的！

**Comment by lhtuling** [comment]
可以加群发个示例代码  有空帮你看下

**Comment by CheshireJCat** [comment]
流程上支持，但是细节需要你自己写：
基本就是 picker onChange的 时候 拿到数据，然后 setValue
