### ISSUE TITLE
使用了组合输入组件，组合输入里面表单过多或导致很卡顿

### ISSUE THREAD

**Issue by yijunjun1** [baidu/amis#10918]
![组合输入](https://github.com/user-attachments/assets/87010cea-e563-4c2c-ae98-0534f8de5367)
这是组合输入的配置页面，新增多个之后会越来越卡 有无好的优化方式

**Comment by CheshireJCat** [comment]
试试 Tabs 模式 https://baidu.github.io/amis/zh-CN/components/form/combo#tabs-%E6%A8%A1%E5%BC%8F

这种场景确实比较复杂，感觉不适合用combo处理

如果不行的话用，可以换 inputTable 试试，建议把 过于复杂的配置放到 弹窗里里配置
