### ISSUE TITLE
【Javascript模板引擎】里面的 <%-  和<%= 有什么区别吗？ 

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#10911]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/template#javascript-%E6%A8%A1%E6%9D%BF%E5%BC%95%E6%93%8E

官方文档上面写了个
```
<%- date(data.xxx, 'YYYY-MM-DD') %>
```

发现换成
```
 <%= date(data.xxx, 'YYYY-MM-DD') %>
```
是一样效果，是这里的笔误还是说有什么特性没有详细说明

**Comment by 2betop** [comment]
用的 lodash 的 template 机制 https://lodash.com/docs/4.17.15#template

`<%=` 原样输出 `<%-` 会做 html escape。具体用法请看前面的文档
