### ISSUE TITLE
组合条件中的下拉框不支持分组展示模式和级联选择

### ISSUE THREAD

**Issue by yuhuating** [baidu/amis#10914]
#### 是否关联于某个问题吗：
组合条件中的下拉框选项较多，想使用分组展示或者级联模式，把option格式修改后，组合条件下拉框无法选择

#### 预期的解决方案：
下拉框支持级联或者分组

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by allenve** [comment]
分组展示：https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select#%E5%88%86%E7%BB%84%E5%B1%95%E7%A4%BA%E6%A8%A1%E5%BC%8F
级联展示：https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select#%E7%BA%A7%E8%81%94%E9%80%89%E6%8B%A9
