### ISSUE TITLE
图片上传是否支持tif格式？

### ISSUE THREAD

**Issue by personzhangjiazhen** [baidu/amis#10920]
#### 描述问题：

图片上传如何支持tif格式？

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
sdk
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by CheshireJCat** [comment]
https://baidu.github.io/amis/zh-CN/components/form/input-image?page=1#%E9%99%90%E5%88%B6%E6%96%87%E4%BB%B6%E7%B1%BB%E5%9E%8B

可以配置 accept属性，默认值是 .jpeg,.jpg,.png,.gif
