### ISSUE TITLE
sdk、lib、esm之间的关系，及项目build后如何部署？

### ISSUE THREAD

**Issue by 6LWa6ZKx** [baidu/amis#10931]
大家好，我现在使用是：“https://github.com/aisuda/amis-editor-demo”
修改打包编辑器，我发现他只是通过npm安装了amis-edit，无法在这个基础上做一些二开。

于是我下载“amis”这个项目源码可以二开并且修改根源上的内容，然后在linux下“npm run build”后在“packages”文件夹不同的模块下得到一些“lib、esm、sdk”。

我知道的是“amis”文件夹下的sdk是运行时。那么我修改“编辑器源码某些内容”通过build后得到的“lib、esm”是否可以直接引入在“html”中并且使用“二开后的编辑器”？

似乎搜索不到相关的案例，还请赐教。

感谢。

**Comment by allenve** [comment]
`sdk` 是对amis的进一步封装，方便项目快速接入；
`lib` 和 `esm` 打包后输出的两种格式，本质上是一样的，关于这个可以去了解一下前端npm相关的知识。
