### ISSUE TITLE
希望Options 的Item项能自定义

### ISSUE THREAD

**Issue by zimo888** [baidu/amis#1094]
#### 是否关联于某个问题吗：
Select的Option 现在是普通的文本，希望能够自定义Item，可以Render Amis Json.

#### 预期的解决方案：

比如可以Label 渲染json，且能高亮搜索，
点击 + 按钮，能够同时使用Amis的 ”多功能选择器“，弹出列表进行选择。
```
{
   "type":"select",
    "options":[
       {
         "label":{
              "type":"组件名称"  
           },
         "value":"0"    
       }
     ]
}
```

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
![image](https://user-images.githubusercontent.com/4545006/99686744-da53a600-2abe-11eb-9e54-e78faeaad5d9.png)

**Comment by RickCole21** [comment]
Duplicate of #1019

**Comment by 2betop** [comment]
相关 pr https://github.com/baidu/amis/pull/1545
通过  menuTpl 支持 schema 或者直接就是 tpl 字符串。
