### ISSUE TITLE
6.8 更新后编辑器上面的按钮属性面板变了，事件动作没了，完全没法用了

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#10960]
#### 描述问题：
按钮属性面板变了，事件动作没了，完全没法用了

#### 截图或视频：
![image](https://github.com/user-attachments/assets/ca01bcc0-cd66-45a0-9137-135b1acf944b)

**Comment by lhtuling** [comment]
感觉这次更新多了好多bug。。。
组件id自定义后会自动变回自动生成的
````
"id": "u:be16d6fc6496",// 修改成自定义的  切换控件不知道什么时候就自动变了。。。导致很多动作有问题
````

**Comment by qkiroc** [comment]
> 感觉这次更新多了好多bug。。。 组件id自定义后会自动变回自动生成的
> 
> ```
> "id": "u:be16d6fc6496",// 修改成自定义的  切换控件不知道什么时候就自动变了。。。导致很多动作有问题
> ```

组件id有重复吗？如果重复的话，会被重新赋值。提供下具体的版本

**Comment by blankzust** [comment]
我也遇到了
