### ISSUE TITLE
找不到node_modules/react-dom/node_modules/object-assign/index

### ISSUE THREAD

**Issue by jiajianrong** [baidu/amis#11]
输入 http://127.0.0.1:8888/examples/pages/simple
后找报错

```
mod.js:141 Uncaught [ModJS] Cannot find module `node_modules/react-dom/node_modules/object-assign/index`
require @ mod.js:141
(anonymous) @ npm.js:3461
(anonymous) @ npm.js:24719
require @ mod.js:151
(anonymous) @ npm.js:24764
require @ mod.js:151
(anonymous) @ index.jsx:6
require @ mod.js:151
updateNeed @ mod.js:207
require.async @ mod.js:216
require @ mod.js:126
(anonymous) @ simple:272
```

**Comment by 2betop** [comment]
第一个 `npm i` 失败了吗？

**Comment by jiajianrong** [comment]
没失败，只有个包提升我node版本低（8.9.0），貌似要求至少8.10.0，没管他
另外我是windows本，run 完dev后控制台一直打印圆点正常吗？

`D:\jiajianrong-d\js-src\baidu\amis>

D:\jiajianrong-d\js-src\baidu\amis>npm run dev

> amis@1.0.0-rc.1 dev D:\jiajianrong-d\js-src\baidu\amis
> fis3 release -cwd ./public


 [INFO] Currently running fis3 (D:\jiajianrong-d\js-src\baidu\amis\node_modules\fis3)

 δ 2525ms

 δ 2ms

 Ω ...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
 [WARNI] Can't resolve `vertx` in file [/node_modules/flv.js/dist/flv.js], did you miss `npm install vertx`?
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................终止批处理操作吗(Y/N)?`

**Comment by 2betop** [comment]
是正常的，在编译把代码编译后发布到 public 目录，这一步一定要执行完

**Comment by 2betop** [comment]
刚虚拟机 windows 8.1 跑了一遍流程， node 10.x 表示很正常啊

**Comment by jiajianrong** [comment]
升级node后没问题了：）

**Comment by SnailSword** [comment]
我这也出现了这个问题，升级node之后也没有解决。

**Comment by FatDong1** [comment]
错误
```
 Uncaught [ModJS] Cannot find module `node_modules/react-dom/node_modules/object-assign/index`
```
Fixed
```
npm i object-assign --save-dev
```
我是这样解决的
@SnailSword

**Comment by ly525** [comment]
我的使用 `cnpm i` 也报了同样的错误，使用 `npm` 安装太慢，换成 `yarn install` ok 了，node v10.15.3
