### ISSUE TITLE
您好！ 有办法获取接口返回的整个data数据吗，而不是data内的某些元素

### ISSUE THREAD

**Issue by xdlove** [baidu/amis#1101]
#### 实现场景：
amis 的接口定义为
`{
  "status": 0,
  "msg": "",
  "data": {
    ...其他字段
  }
}`
我想实现获取 data 整个字段

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by RickCole21** [comment]
接收适配器里自己包一个字段

**Comment by xdlove** [comment]
> 接收适配器里自己包一个字段

应该怎么写啊

**Comment by PieNam** [comment]
（基于 6.10 版本）实测可以直接在 responseData 里取 `&` 这个变量表示 data 本身。比如：

```json
"responseData": {
    "options": "${& | someFilter}"
}
```

表示对返回数据中的 data 本身以此进行 someFilter 过滤器操作。
