### ISSUE TITLE
跨域访问问题

### ISSUE THREAD

**Issue by kangxiangzhi** [baidu/amis#111]
想咨询一下 怎么配置跨域访问或者配置代理访问，目前发现api 只能本地路径访问
![image](https://user-images.githubusercontent.com/18476183/61229347-962df400-a75a-11e9-9624-ff8cdf866b99.png)
使用external 配置发现也没有用

**Comment by 2betop** [comment]
`external:` 已经不需要了，这是平台内部的用法，直接使用渲染器不需要关心。

要支持跨域需要服务端返回以下 Header

* `Access-Control-Allow-Origin` 最好固定域名否则没办法携带 cookie
* `Access-Control-Allow-Methods` 一般设置成这些就够 `POST,GET,PUT,PATCH,DELETE,OPTIONS`
* `Access-Control-Expose-Headers` 这个自己看着来吧, 如果浏览器报了啥不支持，你就补上。
* `Access-Control-Allow-Credentials` 允许携带 cookie， 可以根据你自己需求

**Comment by kangxiangzhi** [comment]
感谢

**Comment by kangxiangzhi** [comment]
感谢
