### ISSUE TITLE
在vue项目中使用amis 打包成静态文件之后部署报错 无法正常加载出页面

### ISSUE THREAD

**Issue by 369pie** [baidu/amis#1112]
#### 描述问题：
我在一个 vue项目中使用 amis 创建了一个页面、使用 npm run dev 时用nodejs serve时页面能正常访问、但build成静态文件之后使用 nginx 部署则出现以下错误并且无法加载出页面：
chunk-libs.2f76296f.js:11 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btag%2C%20data%2C%20children%2C%20text%2C%20elm%2C%20ns%2C%20context%2C%20fnContext%2C%20fnOptions%2C%20fnScopeId%2C%20key%2C%20componentOptions%2C%20componentInstance%2C%20parent%2C%20raw%2C%20isStatic%2C%20isRootInsert%2C%20isComment%2C%20isCloned%2C%20isOnce%2C%20asyncFactory%2C%20asyncMeta%2C%20isAsyncPlaceholder%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

#### 截图或视频：
![image](https://user-images.githubusercontent.com/22891991/100303173-e798f500-2fd6-11eb-9196-08c0eb53268a.png)

#### 如何复现（请务必完整填写下面内容）：
在vue中创建amis页面、使用 npm run build打包 使用nginx部署

1. 你是如何使用 amis 的？
`npm`

2. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

3. 操作步骤
在vue中创建amis页面、使用 npm run build打包 使用nginx部署

**Comment by RickCole21** [comment]
不太好找原因，有一种可能是和数据有关
