### ISSUE TITLE
form 穿梭器searchApi 使用问题

### ISSUE THREAD

**Issue by dayuliu** [baidu/amis#1119]
#### 实现场景：
我想要实现在穿梭器使用searchApi的时候，获取当前form里面某一个下拉框的值，当作searchApi的一个参数。
searchApi如何实现联动？
#### 当前方案：

```
code here...
```

**Comment by 2betop** [comment]
这个 case 穿梭器需要配置 `strictMode: false`，否则拿不到最新的其他表单项的值。

此问题先关了，有问题欢迎再开
