### ISSUE TITLE
用iframe嵌入 amis页面，在火狐浏览器预览，报错（window.getComputedStyle(.) is null）

### ISSUE THREAD

**Issue by jokerys** [baidu/amis#112]
系统：windows10,32位（专业版）
浏览器版本：火狐60.8.0esr（32位）
问题定位：amis/lib/helper.js getScrollParent函数 ，以及 amis/lib/resize.js getComputedStyle 调用window.getComputedStyle获取不到值 ，导致后续代码执行报错。
解决方法：调用window.getComputedStyle，增加一层判断逻辑
       if (window.getComputedStyle(element, undefined) === null) {
            return null
        } else {
            return window.getComputedStyle(element, undefined).getPropertyValue(prop);
        }
具体实现：
helper.js
function getScrollParent(node) {
    if (node == null) {
        return null;
    }
    if (getComputedStyle(node) === null) {
        return null;
    } else {
        var style = getComputedStyle(node);
        var text = style.getPropertyValue('overflow') + style.getPropertyValue('overflow-x') + style.getPropertyValue('overflow-y');
        if (/auto|scroll/.test(text) || node.nodeName === 'BODY') {
            return node;
        }
        return getScrollParent(node.parentNode);
    }
}

resize-sensor.js
function getComputedStyle(element, prop) {
    if (element.currentStyle) {
        return element.currentStyle[prop];
    }
    else if (window.getComputedStyle) {
        if (window.getComputedStyle(element, undefined) === null) {
            return null
        } else {
            return window.getComputedStyle(element, undefined).getPropertyValue(prop);
        }
    }
    else {
        return element.style[prop];
    }
}

**Comment by 2betop** [comment]
请提 pr，谢谢

**Comment by nwind** [comment]
如果有更详细信息再打开
