### ISSUE TITLE
导出到excel文档后 特殊的标签取出的值不对 应该要过滤下特殊标签

### ISSUE THREAD

**Issue by hury88** [baidu/amis#11200]
#### 描述问题：

见图

#### 截图或视频：

![image](https://github.com/user-attachments/assets/90232618-1da6-45bc-9c9b-10cfe3be11bc)
![image](https://github.com/user-attachments/assets/0bb5c3ed-e5bb-4016-b768-f684af58a6c2)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

见图

**Comment by CheshireJCat** [comment]
标签的部分 schema 是啥？

**Comment by hury88** [comment]
> 标签的部分 schema 是啥？

是标签 他获取的是item的值不应该是label的值吗
![image](https://github.com/user-attachments/assets/fc5b9112-1461-4901-b11d-0d8775aa3d1a)

**Comment by hury88** [comment]
没有规范使用导致的
