### ISSUE TITLE
文档样式错误

### ISSUE THREAD

**Issue by AprildreamMI** [baidu/amis#11214]
#### 描述问题：

文档样式错误，
```css
.markdown-body 类样式影响

min-height: 100vh;
```

#### 截图或视频：

![image](https://github.com/user-attachments/assets/edbe722e-e570-4d86-9822-c2e86f60b279)
![image](https://github.com/user-attachments/assets/3f921355-3390-49bd-931f-847ab19b1355)
![image](https://github.com/user-attachments/assets/e10fb48e-b651-41bf-b1e4-6178cbbcd529)

#### 如何复现（请务必完整填写下面内容）：

直接访问文档
https://baidu.github.io/amis/zh-CN/components/form/checkbox

**Comment by 2betop** [comment]
没有搜到相关代码，难道是 fork 版本的？

**Comment by AprildreamMI** [comment]
> 没有搜到相关代码，难道是 fork 版本的？

我直接访问官网就发现的
https://baidu.github.io/amis/zh-CN/components/form/checkbox

![image](https://github.com/user-attachments/assets/b140f8b7-ebaf-45dc-ba69-bfbf033aefc6)

**Comment by 2betop** [comment]
找到了，看来要外围覆盖了 https://github.com/sindresorhus/github-markdown-css/blob/main/github-markdown.css#L135
