### ISSUE TITLE
编辑器选中任意组件，属性里面【外观】-【状态】点击切换，报错必现

### ISSUE THREAD

**Issue by xxshhh** [baidu/amis#11215]
#### 描述问题：

官方Demo，选中任意组件，属性选择：外观 -> 状态 -> 切换“悬浮”或“点击”，出现报错，最新版本本地尝试仍未修复该问题。

#### 截图或视频：

![image](https://github.com/user-attachments/assets/3922653b-1c95-44c6-84f5-fd43b7f22682)
![image](https://github.com/user-attachments/assets/69ba49f2-4366-4a45-b67f-cfb537cce89c)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v6.9.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
https://aisuda.github.io/amis-editor-demo/#/edit/0
访问官方线上Demo，点击某个页面进行编辑，选中任意组件，属性选择：外观 -> 状态 -> 切换“悬浮”或“点击”，出现报错。

**Comment by lhtuling** [comment]
是的我也发现了，，，
偶然间发现的。。
不过影响不大因为也不用这个功能。。。
忽略就行了


Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by xxshhh** [comment]
6.10.0 今天发布了，本地验证了一下还是没修复该问题

**Comment by qkiroc** [comment]
将amis-theme-editor-helper更新到2.0.27试试

**Comment by xxshhh** [comment]
刚试了下，本地 yarn.lock 把这个 amis-theme-editor-helper 版本升级上去，就解决了，赞一个👍
