### ISSUE TITLE
自由容器中，如何使自定义组件可拖拽？

### ISSUE THREAD

**Issue by JSoon** [baidu/amis#11302]
#### 是否关联于某个问题吗：
因为 Container 组件不能当做 UI 组件引入，所以没办法在自由容器组件中，实现可拖拽的自定义组件。

#### 预期的解决方案：
在自由容器中拖入自定义组件，自定义组件可像系统组件一样，可以进行位置拖拽。
<img width="953" alt="image" src="https://github.com/user-attachments/assets/b7ef0615-12e1-4f2e-b85d-4bf2c20123c2">

#### 其他可接受方案：
自定义组件能否接受系统组件 type 作为其类型？例如：

```js
自定义组件：
@Renderer({
  type: 'container',
  name: 'renderer-demo'
})
```

这样，自定义组件通过 name 唯一标识，但能够使用系统组件作为它的容器节点，从而具备系统组件的功能特性。

**Comment by JSoon** [comment]
已解决。

**Comment by mindhacker0** [comment]
你好，请问这个是在哪个版本修改的

**Comment by wibetter** [comment]
@mindhacker0 在自定义组件层支持下行内样式即可，可参照chart组件实现：
<img width="952" alt="image" src="https://github.com/user-attachments/assets/ed276bf1-345d-49bc-a981-91758cf1b0f5" />

**Comment by JSoon** [comment]
> 你好，请问这个是在哪个版本修改的

请参考 [ref(docs): 优化如何让渲染器可通过拖拽调整宽高文档说明 #11330](https://github.com/baidu/amis/pull/11330)

**Comment by mindhacker0** [comment]
感谢诸位大佬👍
