### ISSUE TITLE
sdk v6.10.0 crud table组件 操作栏右侧固定，出现位置排序错误

### ISSUE THREAD

**Issue by cube3power** [baidu/amis#11328]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
 CRUD table 组件设置操作栏固定在右侧，但渲染出现了位置错误.

#### 截图或视频：

![1733457143081](https://github.com/user-attachments/assets/aabd40bb-6984-407b-9cf8-22aee909416d)

![1733457252660](https://github.com/user-attachments/assets/04fc5d67-dc51-4fa4-ab34-84b973ec0739)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
  sdk v6.10.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...
设计页面排序正常，但在jssdk环境下出现如上错误。

**Comment by cube3power** [comment]
清空一下浏览器缓存 不出现此情况

**Comment by boxui** [comment]
确实会有这个问题，同样也是6.10，清空缓存也没用
