### ISSUE TITLE
amis是否支持 shell执行器终端

### ISSUE THREAD

**Issue by dulinhao** [baidu/amis#11335]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
我想要实现连接K8s的pod的功能.
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
没有找到对应的组件
#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
还没启动，调研中~
```
code here...
```

**Comment by nwind** [comment]
这是后端实现的功能，amis 只有前端
