### ISSUE TITLE
"actionType": "show", 能否支持消抖效果

### ISSUE THREAD

**Issue by yanquer** [baidu/amis#11430]
比如我分别给三个 `container` 设置鼠标移入时候显示设置按钮, 每个容器的事件定义大致为

```
const _mouseEnterShow = {
        "mouseenter": {
            "actions": [
                {
                    "actionType": "show",
                    "componentId": "contanierId"
                }
            ]
        },
    }
    const _mouseLeaveHidden = {
        "mouseleave": {
            "actions": [
                {
                    "actionType": "hidden",
                    "componentId": "contanierId"
                }
            ]
        }
    }
```

当从 `第一个控件` 移动到 `第三个控件` 的时候,  `第二个控件` 会有按钮显示/隐藏的闪烁.
实际想要的效果是  **鼠标在第二个控件上移动非常快速, 就取消掉这一次的显示/隐藏**

在当前的文档暂时没有找到实现方式.

**Comment by lhtuling** [comment]
问问他可以把完整代码或者模拟一份类似情况，粘贴出来好帮你处理，你这样还要回答的人去模拟以下你的情况再去处理。。。。


Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by yanquer** [comment]
此问题仅出现于组件非常多的情况, 所以就没有贴代码, 另外某些方面来说, 属于业务自己的问题.

目前暂时用CSS的hover解决, 可以关闭了
