### ISSUE TITLE
Can't resolve `vertx`

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#115]
npm run dev时出现一个告警错误：[WARNI] Can't resolve `vertx` in file [/node_modules/flv.js/dist/flv.js], did you miss `npm install vertx`? 

按提示 npm install vertx 但是根本就装不了，各种404不存在的报错。

**Comment by 2betop** [comment]
可以忽略

**Comment by foxfire881** [comment]
研究了三天了，还是没法上手。东西是好东西，就是文档太简陋了，像我们这种没有前端开发基础只会做后端+HTML的人根本没法上手，看着一大堆文件很茫然，想用起来帮忙推广都使不上力。希望能有一些零基础开始的教程一步步教着怎么做，毕竟搞这个东东出来主要是给不会前端的人用的（会前端React、Vue的人直接手写他们自己的框架了，基本也不会用这个），比如我们这种后端开发人员，主要实现功能，但是前端做的Web界面就太简陋了，希望有个模板快速套用一下画个漂亮的前端界面出来。这个amis研究了三天，感觉似乎没有宣传中那样只用简单配置json就能画出界面来，感觉还是要些React、配置一大堆东西（也或许是我感觉错误，确实没有前端经验），这无疑就提高了使用门槛。希望能进一步优化。

**Comment by 2betop** [comment]
感谢反馈，想要直接能用的要看这个 https://github.com/fex-team/amis-admin  这个里面已经用 React 的方式搭建了一些页面。其实内容区已经可以配置出来，就是周边的比如导航、顶部栏、登录、权限配置还需要自己折腾，这块因为是用  React 搭的，所以还是需要掌握一些 React 基础。

**Comment by 2betop** [comment]
拿走不谢，https://github.com/baidu/amis/blob/master/docs/getting_started.md#jssdk

**Comment by RickCole21** [comment]
之后有了可视化编辑器就好多了应该

**Comment by FatDong1** [comment]
@RickCole21 会开源可视化编辑器？

**Comment by foxfire881** [comment]
> 拿走不谢，https://github.com/baidu/amis/blob/master/docs/getting_started.md#jssdk

哇！瞬间找到新大陆的赶脚，明天赶紧试用~~ 有这种不需整React，直接js+html渲染的方式最好了！感谢提供这么好用的东西，希望能进一步优化，本来就是为了简化开发给不会前端的人用的，如果再搞一堆nodejs、React相关的东西反而违背了初衷。祝好Fex团队越来越好~

**Comment by fatlao** [comment]
search vertx in the file and do :

from - require('vertx');
to - require('@vertx/core'); 

and also installing @vertx/core with npm
