### ISSUE TITLE
通过 formula 导致的表单项值改变，如何触发校验？

### ISSUE THREAD

**Issue by zhumengyue** [baidu/amis#1168]
#### 描述问题：
form 中 表单项 A 是由其他多个表单项的值计算得出（用 formula 实现的）。A 不可手动修改。期望 A 在改变时，可以触发校验。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. 粘贴有问题的完整 `amis schema` 代码：
https://codesandbox.io/s/xenodochial-smoke-qci1i?file=/src/App.tsx

3. 操作步骤
修改输入框1的的值，另一个表单项的值会跟随改变，但不会触发校验

看了下源码，本身校验是在 `input` 的 `onChange` 属性中做的，所以 formula 导致的改动不会触发 `onChange` 其实是预期内的。但是我这种使用场景有什么解决办法吗？

举个具体的点的例子，我有4个输入框来填概率，最终要保证这些概率和为100。

**Comment by 2betop** [comment]
我看是会校验的呢，提交的时候，提交过也会自动校验。你的意思是没提交前 并且配置了 validateOnChange 要校验？

**Comment by 2betop** [comment]
已优化，换了个地方，不管什么方式只要值发生变化，就会触发验证。https://github.com/baidu/amis/pull/1550
