### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by MrStrangeBao** [baidu/amis#117]
![image](https://user-images.githubusercontent.com/19922686/61441067-6d367a80-a977-11e9-826b-027d6a892aad.png)

https://baidu.github.io/amis/docs/getting-started
谷歌浏览器 版本 75.0.3770.100（正式版本） （64 位）, 
Mac 15寸下和外接显示器都有这个小问题

**Comment by 2betop** [comment]
缓存问题，应该是，中间有个版本有问题，现在最新的 gh-pages 是 可以的

**Comment by foxfire881** [comment]
采用JSSDK的方式加载了样例，发现图标都显示不出来？样式倒是对的。
引用的是以下两个文件：
https://bce.bdstatic.com/fex/amis-v2/page/embed.tpl_aio_d5d9504.css
https://bce.bdstatic.com/fex/amis-v2/page/embed.tpl_aio_0005f84.js

![捕获](https://user-images.githubusercontent.com/273961/61471172-e1dbda00-a9b4-11e9-922d-22c7a69bad6b.PNG)

**Comment by 2betop** [comment]
cdn 上的字体文件跨域限制了，只允许百度域下面使用，目前没有好办法，你先把样式 copy 到你本地？然后改一下字体路径？

**Comment by 2betop** [comment]
我这边再想想办法

**Comment by 2betop** [comment]
@foxfire881 字体换了个地址，有空试试

**Comment by tianyk** [comment]
个人建议抓紧时间丰富**构建**和文档，希望能更方便的开箱使用。

`SDK`这个不错，建议发布到`NPM`的包含`SDK`，直接通过`unpkg`或者`jsdelivr`就能用了。

希望能重视一下这个项目，SDK一推出就出现跨域错误不应该出现。项目挺不错的，支持。

**Comment by 2betop** [comment]
感谢支持，sdk 其实内部一直在使用，cdn 地址限制了内网域名，后续把它放到 npm 里面一起发布。

**Comment by gozeon** [comment]
> 采用JSSDK的方式加载了样例，发现图标都显示不出来？样式倒是对的。
> 引用的是以下两个文件：
> https://bce.bdstatic.com/fex/amis-v2/page/embed.tpl_aio_d5d9504.css
> https://bce.bdstatic.com/fex/amis-v2/page/embed.tpl_aio_0005f84.js
> 
> ![捕获](https://user-images.githubusercontent.com/273961/61471172-e1dbda00-a9b4-11e9-922d-22c7a69bad6b.PNG)

`yarn add glyphicons-only-bootstrap`

**Comment by 2betop** [comment]
更新一下 csssdk 的地址

**Comment by 2betop** [comment]
font 字体换环境了，应该没这个问题了，有问题请重新开
