### ISSUE TITLE
使用JSSDK方式访问ttf和woff文件报CORS错误

### ISSUE THREAD

**Issue by dotxu** [baidu/amis#118]
使用JSSDK方式时，jssdk会引用一些ttf和woff文件，这些文件位于“https://bce.bdstatic.com”域，所以报了CORS错误，详细如下：

> Access to font at 'https://bce.bdstatic.com/fex/amis-v2/n/font-awesome/fonts/fontawesome-webfont_af7ae50.woff2?v=4.7.0' from origin 'http://localhost:8080' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://amis.baidu.com' that is not equal to the supplied origin.

**Comment by 2betop** [comment]
重新 cssdk 获取以下地址？我记得我已经修改了 字体文件的路径

**Comment by dotxu** [comment]
好使了，谢谢！
