### ISSUE TITLE
使用 [ 导出 Excel ] 功能时，仅导出当前 CRUD 组件显示的内容

### ISSUE THREAD

**Issue by 17** [baidu/amis#1180]
#### 是否关联于某个问题吗：
导出 Excel 会携带 API 其他参数，有时候其他参数并不需要或不想用户知晓。

#### 预期的解决方案：
仅导出当前 CRUD 组件显示的内容

**Comment by lengqingfeng** [comment]
一样遇到相同问题,最好来个都支持下,api 冗余字段太多
