### ISSUE TITLE
自定义组件数据域问题

### ISSUE THREAD

**Issue by Kimwill** [baidu/amis#1183]
#### 实现场景：
在自定义组件中与外层组件通信

#### 存在的问题：
在自定义组件中打印出的data不是所在数据域的data，而是最外层的data
![mmexport1607930182096](https://user-images.githubusercontent.com/37266209/102051319-5a033500-3e1f-11eb-942a-52de97a031c7.jpg)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
{
  "type": "page",
  "name": "auth",
  "data": {
    "activeStep": 2
  },
  "body": {
    "type": "hbox",
    "columns": [
      {
        "data": {
          "bbbbbbbbbbbbbbbbbbbbbb": 2
        },
        "type": "container",
        "body": {
            "type": "auth-btn",
            "data": {
              "aaaaaaaaaaaaaaaaaaaa": 1
            }
          }
      }
    ]
  }
```

此时打印的data不应该是上一层的数据域即 bbbbbbbb 吗。如果想取 bbbbbbb该如何操作

**Comment by nwind** [comment]
只有少数几个容器有数据域，需要使用 service 包裹一层，data 放 service 中
