### ISSUE TITLE
formItem中的group组件的样式问题

### ISSUE THREAD

**Issue by zsfish** [baidu/amis#1184]
#### 描述问题：
formItem中的group组件，其margin-bottom与普通的formItem的margin-bottom间隔不一致，且表单内最后一个group与它紧挨着的下一个普通formItem间隔消失

目前只能统一给每个formItem加个样式或者将fromItem都用group包起来。希望官方能够解决这个样式问题

**Comment by RickCole21** [comment]
是input-group还是group，发下具体schema？

**Comment by zsfish** [comment]
group, 可将下面这个schema复制到官网https://baidu.gitee.io/amis/docs/components/form/group,group基本用法那里看效果。
{
  "type": "page",
  "body": {
    "type": "form",
    "mode": "horizontal",
    "horizontal": {
        "left": 1,
        "right": 11
     },
    "controls": [
      {
        "type": "group",
        "controls": [
          {
            "type": "text",
            "name": "text1",
            "label": "文本1"
          },
          {
            "type": "text",
            "name": "text2",
            "label": "文本2"
          }
        ]
      },
      {
        "type": "text",
        "label": "ceshi"
      }
    ]
  }
}

**Comment by RickCole21** [comment]
#1448
