### ISSUE TITLE
不是所有组件都有data属性吗

### ISSUE THREAD

**Issue by Kimwill** [baidu/amis#1187]
#### 实现场景：
在container中配置data，发现在他的下级组件中取不到data的数据

#### 存在的问题：
是container这个组件不能配置data吗？具体哪些组件有data呢？以及想在A组件里渲染子组件，并且子组件要用A的data的数据，用什么组件合适呢？

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
const schema = {
  type: "page",
  body: {
    type: 'container',
    data: {
      value: 'test'
    },
    body: {
      type: 'tpl',
      tpl: '${value}'
    }
  }
}
```
tpl组件中取不到value

**Comment by nwind** [comment]
不是，只有 Service、CRUD、Dialog、Form 等组件有，建议都放 Page 下，通过 xxx.yyy 来获取深层数据，或者用 Service。
