### ISSUE TITLE
drawer组件中rich-text被遮挡

### ISSUE THREAD

**Issue by chenyphaaa** [baidu/amis#1194]
![image](https://user-images.githubusercontent.com/18170710/102442906-74782100-4060-11eb-9043-884b768dbaca.png)
 amis版本为1.0.16

**Comment by chenyphaaa** [comment]
@nwind 请问如何添加class，我在浏览器中发现修改tox-tinymce-aux的z-index可以展示出来，但是我再scss中添加了样式
`.tox-tinymce-aux {
    z-index: 1400;
}`
没有生效，被原始的属性覆盖了

**Comment by nwind** [comment]
新版应该修了
