### ISSUE TITLE
请问，为何用react不用vue呢？主要考虑哪些方面的原因？

### ISSUE THREAD

**Issue by janeze** [baidu/amis#12]
1、我在做类似的东西，但是实现是用vue来做的，主要考虑的是自己知识体系的问题，我想知道，这个项目出于什么原因考虑用的react?
2、我有个项目是通过拖动组件的方式生成json，然后根据json的可视化配置渲染页面，现在发现你们这个项目可以简化我的组件开发和json定义，我是否可以在这个项目的基础上做二次开发，直接根据你们这个项目的json做配置？这么做是否会涉及侵权？（商用）
3、有没有移动端的一套类似的json和对应组件，开源分享一下？同样我在此基础上做2、描述中的二次开发来使用，是否涉及侵权？（商用）

**Comment by 2betop** [comment]
1. 应该都没问题，只要是 mvvm 应该都可以，当时选 react 主要是看生态上 react ui 组件更多。
2. 采用的是 apache 2 协议，可商用，但需要带原来的协议 https://baike.baidu.com/item/Apache/6848636
3. 移动端，其实是可以直接适配的吧！当然要追求极致体验，额外开发更好，我们目前没有专门正对移动端开发一套 ui。

**Comment by janeze** [comment]
奥，了解，多谢啦。。
