### ISSUE TITLE
在移动设备上隐藏键盘时页面下方有一片白色区域

### ISSUE THREAD

**Issue by dotxu** [baidu/amis#120]
在移动设备上打开页面，点击text系统会自动弹出键盘，收入完后移动焦点键盘会自动隐藏，这时页面下方有一片白色区域，如图：
![image](https://user-images.githubusercontent.com/9528284/61520284-73dcf480-aa40-11e9-962d-0466d37a528c.png)
还有一点，组件里的Select和Date是用的自定义样式，有时还会出现显示位置偏移的问题，如下图所示，可以增加一个选项让他们在移动设备上自动适配成系统默认滚轮样式吗？
![image](https://user-images.githubusercontent.com/9528284/61520512-f2d22d00-aa40-11e9-8e3a-4f03bacc7bbb.png)

**Comment by 2betop** [comment]
这个后面会优化

**Comment by 2betop** [comment]
![image](https://user-images.githubusercontent.com/2698393/140897086-aa73dc6f-19f2-4a21-a9da-2a03968efc41.png)
应该已经优化了，有问题再开
