### ISSUE TITLE
picker组件禁用后依然可以操作

### ISSUE THREAD

**Issue by Lzw2016** [baidu/amis#1202]
#### 描述问题：
picker组件禁用后依然可以操作

#### 截图或视频：
![image](https://user-images.githubusercontent.com/19291563/102583270-5a614000-413f-11eb-8166-59ac35231d10.png)

**Comment by RickCole21** [comment]
感谢反馈，下个版本修复

**Comment by RickCole21** [comment]
最新版已修复：https://github.com/baidu/amis/releases/tag/1.1.0
