### ISSUE TITLE
sdk缺少/amis/sdk/thirds/monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf文件

### ISSUE THREAD

**Issue by Lzw2016** [baidu/amis#1203]
#### 描述问题：
sdk缺少/amis/sdk/thirds/monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf文件

#### 截图或视频：

![image](https://user-images.githubusercontent.com/19291563/102584373-4a4a6000-4141-11eb-978c-29bb5e455175.png)

**Comment by RickCole21** [comment]
Duplicate of #1163

**Comment by RickCole21** [comment]
最新版已修复：https://github.com/baidu/amis/releases/tag/1.1.0
