### ISSUE TITLE
表格出现溢出滚动条

### ISSUE THREAD

**Issue by Lzw2016** [baidu/amis#1204]
#### 描述问题：
表格出现溢出滚动条

#### 截图或视频：
![image](https://user-images.githubusercontent.com/19291563/102584551-a3b28f00-4141-11eb-89f5-41d744a23e99.png)

**Comment by nwind** [comment]
Windows 下的 Chrome？有自定义 css 了么？

**Comment by Lzw2016** [comment]
> Windows 下的 Chrome？有自定义 css 了么？

是的 Windows10 Chrome87.0.4280.88

全局样式

html {
  font-size: 0.925rem;
}

**Comment by nwind** [comment]
按说 html 下不该使用 rem 的，改成 font-size: 100% 或 16px 吧
