### ISSUE TITLE
dialog中的rich-text的插入图片的弹窗出现在dialog的下方，被覆盖

### ISSUE THREAD

**Issue by zsfish** [baidu/amis#1205]
#### 描述问题：
dialog中的rich-text的插入图片的弹窗出现在dialog的下方，被覆盖

**Comment by zsfish** [comment]
版本：1.0.20-beta.15

**Comment by zsfish** [comment]
是rich-text【tinyMCE】所有操作，包括下拉列表，预览弹窗等功能会被覆盖

**Comment by nwind** [comment]
Duplicate of #1194

**Comment by nwind** [comment]
可以先自己加 class 设置更高的 z-index

**Comment by nwind** [comment]
大概这次是真修了。。
