### ISSUE TITLE
schemaApi渲染的子表单，提交失败，修改了主表单的数据，子表单的所有数据就都消失了

### ISSUE THREAD

**Issue by sringly** [baidu/amis#1213]
#### 描述问题：
比如我有一个主表单的壳子，主表单有一个表单项叫活动名称，通过schemaAPi获得了子表单。第一次提交失败了，然后我修改了活动名称，发现子表单的数据都没了。而且提交不会再校验子表单的是否必填。

**Comment by RickCole21** [comment]
发下schema

**Comment by 2betop** [comment]
由于长时间未反馈，问题先关了，有问题再开
