### ISSUE TITLE
样式全局污染和spinner-default问题

### ISSUE THREAD

**Issue by zimo888** [baidu/amis#1238]
#### 描述问题：

// @import '~amis/scss/base/reset';
// @import '~amis/scss/base/normalize';
// @import '~amis/scss/base/typography';

三个文件有全局样式，当做组件库时，会污染。

spinner-default.svg 在webpack 下会找不到,希望能改成base64。

**Comment by nwind** [comment]
全局样式中 html 的 font-size 不好改，因为其他地方都用 rem 了，完全依赖这个。

svg 那个是得改了。
