### ISSUE TITLE
并不是所有的的弹框都走了 getModalContainer 函数

### ISSUE THREAD

**Issue by Lzw2016** [baidu/amis#1245]
#### 描述问题：
并不是所有的的弹框都 走了  getModalContainer 函数

#### 截图或视频：

![image](https://user-images.githubusercontent.com/19291563/103084561-42476000-461a-11eb-9e08-ccf9e7b46785.png)

![image](https://user-images.githubusercontent.com/19291563/103084583-4e332200-461a-11eb-8d83-598f83706176.png)

![image](https://user-images.githubusercontent.com/19291563/103084594-5723f380-461a-11eb-9c38-b7b424518210.png)

全局变量 window.currentAmisId 没有变过，我在一个页面挂载了多个amis应用

**Comment by 2betop** [comment]
已确认，原因是 embed 用法 modalContainer 没有传进去默认的 confirm 和 alert 实例里面

**Comment by 2betop** [comment]
已经发布在 1.1.0 中

**Comment by Lzw2016** [comment]
> 已经发布在 1.1.0 中

1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4-beta.x 都有问题，使用方式是jssdk，我亲测！

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/1546 已亲测，之前确实是被复用了，待 1.1.4 发布后有问题再开
