### ISSUE TITLE
Combo 中 Nested-Select 配置unique的问题

### ISSUE THREAD

**Issue by RickCole21** [baidu/amis#1255]
#### 描述问题：
Combo 中 Nested-Select 配置unique的时候，只会判断顶层节点，然后隐藏添加按钮

**Comment by zhumengyue** [comment]
遇到了同样的问题，看源码应该是计算 total 的时候直接取了 options.length，没有对 children 进行处理

**Comment by RickCole21** [comment]
暂时没想好怎么实现，后续再支持这个feature

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/8438 已修复次问题
