### ISSUE TITLE
actionType为ajax没有弹窗

### ISSUE THREAD

**Issue by FatDong1** [baidu/amis#126]
```
                  {
                        "type": "button",
                        "icon": "fa fa-times text-danger",
                        "actionType": "ajax",
                        "tooltip": "删除",
                        "confirmText": "您确认要删除?",
                        "api": "delete:https://houtai.baidu.com/api/sample/$id"
                    }
```

版本：1.0.0-rc.8
项目结构：amis-admin

**Comment by 2betop** [comment]
git pull,
之前是系统的 alert 和 confirm，现在改成了 amis 内置的 alert 和confirm

**Comment by FatDong1** [comment]
谢谢

**Comment by Flourad** [comment]
> git pull,
> 之前是系统的 alert 和 confirm，现在改成了 amis 内置的 alert 和confirm

我现在还是有这个问题

**Comment by 2betop** [comment]
用最新版本的 amis

**Comment by Flourad** [comment]
> 用最新版本的 amis

![image](https://user-images.githubusercontent.com/1535874/89054573-9f045e80-d38b-11ea-9344-2d333760ce9b.png)
我安装的是最新版本的amis

**Comment by 2betop** [comment]
这个是可以自己传入的，看看是不是自己传入了一个系统的。
另外建议渲染的时候在 env 那个参数里面传入个 session: 'xxx'，更其他 env 分开来

**Comment by Flourad** [comment]
> 这个是可以自己传入的，看看是不是自己传入了一个系统的。
> 另外建议渲染的时候在 env 那个参数里面传入个 session: 'xxx'，更其他 env 分开来

找到原因了，是我在env里没有定义confirm
