### ISSUE TITLE
为什么我这里打包是正常的但是打出来的包却不能使用，报错define未定义

### ISSUE THREAD

**Issue by gong9** [baidu/amis#1266]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
需要提供详细操作步骤，是用什么方式打包了什么
