### ISSUE TITLE
【Form > Image组件】程序实际功能与文档描述不符

### ISSUE THREAD

**Issue by Yonysun** [baidu/amis#1267]
#### 描述问题：
【Form > Image组件】程序实际功能与文档描述不符

#### 截图或视频：
![bug-文档](https://user-images.githubusercontent.com/3928873/103253000-3cef6a00-49ba-11eb-9ff7-ab1b0c623159.png)
![bug-代码](https://user-images.githubusercontent.com/3928873/103253004-41b41e00-49ba-11eb-8153-0e33e833953a.png)
![bug-页面](https://user-images.githubusercontent.com/3928873/103253003-4082f100-49ba-11eb-8924-a5463eebb8a7.png)

**Comment by 2betop** [comment]
文档错了，抱歉，马上改一下
