### ISSUE TITLE
JS SDK source url 联动的 BUG 

### ISSUE THREAD

**Issue by djunny** [baidu/amis#1279]
#### 描述问题：

source 地址在某些格式下无法正常联动

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk  1.0.20-beta

2. 粘贴有问题的完整 `amis schema` 代码：

```
{
"body":{
        "label": "选项1",
        "type": "radios",
        "name": "a",
        "inline": true,
        "options": [
          {
            "label": "选项A",
            "value": 1
          },
          {
            "label": "选项B",
            "value": 2
          }
        ]
      },
      {
        "label": "选项2",
        "type": "select",
        "size": "sm",
        "name": "b",
        "source": "api/mock2/options/level2?a=${a}"
      }
}
}
```

将以上代码的 source 地址换成：

/api/mock2/options/level2?a=${a}

(就多了一个 / 前缀) 或者加

https://xxx/api/mock2/options/level2?a=${a}

就可以正常联动，没有 / 就不能正常联动

**Comment by nwind** [comment]
bug？这是两种路径，绝对和相对的，出问题是因为通过相对路径没法访问吧

**Comment by djunny** [comment]
所以相对路径请求都不给发么？？？

加 / 的路径也不能访问，请求就可以发？

行为不一致为啥不是bug？

**Comment by nwind** [comment]
打开开发者工具看看有没网络报错。

如果页面地址是 a.com/xxx/yyy，使用相对路径 api 请求的将会是 a.com/xxx/api，使用 /api 请求的才是 a.com/api。

**Comment by djunny** [comment]
开发者工具显示没有网络请求

**Comment by djunny** [comment]
我直接说 BUG 在哪吧:

```

export function isValidApi(api: string) {
  return (
    api &&
    /^(?:(https?|wss?|taf):\/\/[^\/]+)?(\/[^\s\/\?]*){1,}(\?.*)?$/.test(api)
  );
}
```

这个正则判断 API 的方法只能匹配：
http[s]://xxx.com/xxx/....
/xxx/....

不能匹配
xxx/...

**Comment by djunny** [comment]
个人觉得没必要要求这么严格，api 里最多要求有一个 / 就够用了

^(?:(?:https?|wss?|taf):\/\/)?(?:[^\s]+\/)(?:.*)$

**Comment by nwind** [comment]
谢谢，已修复 #1283
