### ISSUE TITLE
filter中使用select并且source异步加载options，有没有方法默认选中options的第一项

### ISSUE THREAD

**Issue by hotmaycold** [baidu/amis#1299]
#### 存在的问题：
filter中使用select并且source异步加载options，有没有方法默认选中options的第一项

**Comment by RickCole21** [comment]
https://baidu.gitee.io/amis/docs/components/form/options#%E9%9D%99%E6%80%81%E9%85%8D%E7%BD%AE

` "selectFirst": true`

**Comment by hotmaycold** [comment]
> https://baidu.gitee.io/amis/docs/components/form/options#%E9%9D%99%E6%80%81%E9%85%8D%E7%BD%AE
> 
> ` "selectFirst": true`

多谢多谢，感觉文档的搜索有优化空间，不知道是不是我搜索方法的问题，这种小的api容易漏，amis用了快大半年了，还是很难快速定位一些属性
