### ISSUE TITLE
对话框弹出与关闭的缓动效果可以通过设置关闭

### ISSUE THREAD

**Issue by zku8** [baidu/amis#1301]
建议增加可以关闭对话框缓动效果的设置。特别是业务人员再进行频繁的列表数据操作时，缓动效果会明显增加等待时间，会让业务人员愈加不耐烦

**Comment by nwind** [comment]
嗯，理解，先自己加 css 吧

如果是默认主题

```
.a-Modal-content.in, .a-Modal-content.out {
  animation-duration: 0;
}
.a-Modal-overlay {
  transition: none;
}
```

如果是 cxd 就将其中的 a 改成 cxd

**Comment by nwind** [comment]
目前新增了 css 变量 `--animation-duration`
