### ISSUE TITLE
SDK 模式下，File不支持reciever的url属性支持联动配置

### ISSUE THREAD

**Issue by liuzhijun** [baidu/amis#1306]
#### 是否关联于某个问题吗：
表单select字段切换，触发File字段的url变化，用以配置不同的上传参数；现在无法切换上传参数

#### 预期的解决方案：
实现文件上传字段的上传URL变化。

#### 其他可接受方案：
需要变化，指定上传字段的data属性也可以，貌似目前也无法支持。

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...
"controls": [
                            {
                                "type": "select",
                                "name": "collectionId",
                                "label": "选择分类",
                                "target": "audioFile",
                                "source": buildAudioCollectionApi(),
                            },
                            {
                                "type": "file",
                                "name": "audioFile",
                                "label": "视频文件",
                                "accept": ".mp4,.avi,.zip",
                                "useChunk": false,
                                "fileField": "audioFile",
                                "reciever": {
                                    "method": "POST",
                                    "headers": {
                                        "SESSIONID": "${session_id}"
                                    },
                                    "data": {aid: "${collectionId}"},
                                    "requestAdaptor": function (api) {
                                        return api;
                                    },
                                    "url": build_request_url("/api/audio/upload_audio?aid=${collectionId}"),
                                    "adaptor": function (data, rs) {
                                        data.data.value = data.data.row.filePath;
                                        data.data.filename = data.data.row.filePath;
                                        data.data.url = data.data.row.fileUrl;
                                        return data;
                                    },
                                }
                            },
]

**Comment by liuzhijun** [comment]
以上URL里的aid的变量collectionId无法动态改变

**Comment by nwind** [comment]
看起来是顺序导致的，@2betop 似乎修过类似的，示例可以简化为

```
{
    type: 'form',
    body: [
      {
        label: '选项',
        type: 'select',
        name: 'collectionId',
        menuTpl: '<div>${label} 值：${value}, 当前是否选中: ${checked}</div>',
        options: [
          {
            label: 'A',
            value: 'a'
          },
          {
            label: 'B',
            value: 'b'
          },
          {
            label: 'C',
            value: 'c'
          }
        ]
      },
      {
        type: 'input-file',
        name: 'audioFile',
        label: '视频文件',
        accept: '.mp4,.avi,.zip',
        useChunk: false,
        fileField: 'audioFile',
        receiver: {
          url: '/api/upload/file?aid=${collectionId}'
        }
      }
    ]
  }
```

现象是拿到 collectionId 的值是上一次的，改了一次后下一次才能拿到

**Comment by 2betop** [comment]
后面看一下，不过可以先尝试给第二个 input-file 添加个 strictMode: false
