### ISSUE TITLE
CRUD的filter条件无法置空

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#1329]
#### 描述问题：
现在好像select, NestedSelect 好像都没有清除选中的功能。
这个在查询条件的时候非常不友好。

另外，默认查询的时候，只有一个【搜索】按钮。而没有【重置】按钮。这就更导致了使用了以上组件后，无法对查询条件清除。

如果手动添加【重置】action，数据依然没有清空，页面会刷新一下。

这个问题关联 #1114

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. 粘贴有问题的完整 `amis schema` 代码：
```
"filter": {
            "title": "过滤条件",
            "actions":[
                {
                    "type": "reset",
                    "label": "重置"
                },
                {
                    "type": "submit",
                    "label": "搜索",
                    "primary": true
                }
            ]
}
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by RickCole21** [comment]
`select` 上配 `clearable:true`
