### ISSUE TITLE
新增 Grid 2D 布局

### ISSUE THREAD

**Issue by nwind** [baidu/amis#1334]
## 概述

目前的 Grid 和 HBox 是使用线性布局，为了方便做出更复杂的界面，需要新增一种二维的布局方式。

## 动机

Grid 和 HBox 只有一维，有下面两个缺点：

* 不符合直觉，尤其是对没接触过 CSS 的开发者，一般人会以二维的方式来理解布局，而 CSS 早期只有绝对定位和流式布局，要通过流式布局来实现页面效果需要多层嵌套，只有掌握 CSS 规律的开发者才能灵活运用。
* 难以实现非线性布局，比如下面的例子难以在一个布局结构中实现
![image](https://user-images.githubusercontent.com/6889/103850920-76735400-50e3-11eb-8f2a-092fdf622924.png)

## 示例

本来最好的 type 应该是 grid，但 grid 已经被占用了，而且实际上是 flex，所以 type 命名为 grid-2d，清晰表示它是二维的，这也是它和现有布局最大的区别。

为了简化使用成本，在设计上参考了 react-grid-layout 而不是 CSS Grid，因此更像是绝对定位的思路。

```json
{
  "type": "grid-2d",
  "grids": [
  {
    "x" : 0,
    "y": 0,
    "w": 12,
    "h": 2
    ...其它组件配置
  },
  {
    "x": 0,
    "y": 2,
    "w": 6,
    "h": 3,
    ...其它组件配置
  }
  ]
}
```

## 详细设计

```typescript
interface Grid2DSchema {
  type: 'grid-2d';
  // 列数量，默认是 12
  cols?: number;
  // 移动端下的列数量，默认是 1，也就是移动端只有一列，如果加大这个值，比如 6，则两个宽度是 3 的 grid 就能并排展示
  colsMobile?: number;
  // grid 2d 容器宽度，默认是 auto
  width?: number | string | 'auto'; 
  // grid 间距，默认 1rem，包含行和列
  gap?: number | string;
  // grid 行级别的间距，如果不设置就和 gap 一样
  gapRow?: number | string;
  // 单位行高度，默认 50 px
  rowHeight?: number | string;
  grids: Array<Grid2DItem>;
}

interface Grid2DItem {
  // 起始位置，以 0 作为起点
  x: number;
  y: number;
  // 宽度，跨几列，如果设置 auto 会使得那一列变成 auto
  w: number | 'auto';
  // 高度，跨几行，auto 用于支持高度不确定的容器，最终高度由内容决定
  h: number | 'auto';
  // 用于内容宽度比 grid 小的情况，默认是 auto 自动撑开
  align?: 'left' | 'right' | 'center' | 'auto';
  // 用于内容高度比 grid 小的情况，默认是 auto 自动撑开，
  vAlign?: 'top' | 'bottom' | 'middle' | 'auto';
}
```

具体实现是转成 CSS Grid，优点是实现简单，比如高度自适应不需要动态算，直接设置对应列的 grid-template-rows 为 auto 就行，缺点是对 IE11 支持不好，因为 IE11 支持的是旧版规范，需要研究是否能兼容，但这个是新功能，如果页面要支持 IE11 不用就好了，对现有功能不影响。

## 缺陷

- 容易和现有 Grid 混淆。
- 容易和将来可能新增的绝对定位布局混淆，因为也将会是类似 x/y/w/h 的设置方式。

## 替代选择

- 基于 container + helper 中的 grid 可以实现类似效果，还能更灵活，但需要熟悉 CSS Grid，上手成本较高。
- 绝对布局方式，后续可能会新增这种布局，但绝对布局难以实现响应式，需要分开设计，而且会导致底部区域需要重新定位，不然会有遮挡问题。

## 适配策略

手写二维有难度，需要编辑器支持。

**Comment by Lizhooh** [comment]
跟文档有点差异：https://aisuda.bce.baidu.com/amis/zh-CN/components/grid-2d#%E5%B1%9E%E6%80%A7%E8%A1%A8

1. x，y 这里说从 0 开始，实际是 从1 开始
2. rowHeight 文档说是一个 int 类型，我设置 100 没有效果，反而要设置 `100px`
