### ISSUE TITLE
接收适配器中提供访问数据域的方法

### ISSUE THREAD

**Issue by steven-sun** [baidu/amis#1350]
如题，很多时候需要结合一些条件对返回数据进行处理，目前看接收适配器仅能访问返回数据和api参数，实际使用时有时候需要将两次（或多次）请求的结果在一起处理，较难实现，是否能有个机制暴露数据域给接收适配器访问？
谢谢

相关issue：[#846](https://github.com/baidu/amis/issues/846)

**Comment by nwind** [comment]
api.data

**Comment by steven-sun** [comment]
api.data无法解决此问题，两次请求之间如何共享数据呢？

**Comment by steven-sun** [comment]
我又创建了一个issue( #4450 )
