### ISSUE TITLE
编译之后首页无法打开：exports is not defined

### ISSUE THREAD

**Issue by miscomputer** [baidu/amis#1352]
#### 实现场景：
使用amis-admin代码
npm i
npm run dev
npm start

#### 存在的问题：
启动后首页打不开了，前几天还可以的，今天编译后打不开了
浏览器报下面这个错误：
config.js:2 Uncaught ReferenceError: exports is not defined

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

![image](https://user-images.githubusercontent.com/19248527/104117239-abd5a700-535a-11eb-9cad-c6f46fd8655d.png)

```
code here...
```

**Comment by nwind** [comment]
可能是 ts 的问题，新版应该没有了

**Comment by winterZhao** [comment]
fis-config里的  `// 这些用了 esm fis.match(`  这里把那一项加进去，跳过处理
