### ISSUE TITLE
嵌套表格能否支持自定义子表格的列

### ISSUE THREAD

**Issue by kangxiangzhi** [baidu/amis#136]

**Comment by kangxiangzhi** [comment]
![image](https://user-images.githubusercontent.com/18476183/62421894-1b625400-b6dc-11e9-9ded-2b10e78fcc16.png)
 我看例子目前 嵌套表格的 列 是一样的，没法自定义

**Comment by 2betop** [comment]
https://baidu.github.io/amis/crud/footable?page=1

用折叠模式，里面放 table

**Comment by 2betop** [comment]
没有反馈关了，有问题请重新打开。

**Comment by Ruphi** [comment]
你好 关于这个问题 你说的折叠模式有没有具体的例子 上面的链接页面失效了

**Comment by BOOM-0** [comment]
你好，这个问题有实现方法吗？

**Comment by mizililo** [comment]
> 你好，这个问题有实现方法吗？

Hi, 我也遇到同样的问题，按照上面的评论研究了下
首先他给的链接失效了，可以看这个https://aisuda.bce.baidu.com/amis/examples/crud/footable?page=1
这是一个对可折叠的介绍，按上面的评论，他说的是打开可折叠功能，即Footable，可以在Table组件的文档中找到这个Footable配置
然后对需要折叠的column使用breakpoint字段折叠，再把这个折叠的column的type配置成table(把一列变成一个表格)

这个一定程度上能实现折叠了二级表格的功能，缺点是一次列表页会把所有的二级行都拉出来(比如一次请求十条一级行，然后分别请求十次二级行，一共十一个请求)。不是特别优雅，如果有更好的方式欢迎回复，谢谢。
