### ISSUE TITLE
1.1.1版本 在form里渲染二维码失败

### ISSUE THREAD

**Issue by 502647092** [baidu/amis#1370]
#### 描述问题：
1.1.1在form渲染二维码无效 1.1.0正常

#### 截图或视频：
如图
![%$2L@}ILIBF8WJ2LW(9`UF8](https://user-images.githubusercontent.com/10203793/104270099-a00cf080-54d2-11eb-8828-09ed80660fa9.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
jssdk 1.1.1

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "controls": [
      {
        "label": "保证金支付码",
        "type": "qr-code",
        "codeSize": 128,
        "className": "text-center",
        "value": "https://www.baidu.com",
        "description": "支付宝/微信/QQ均可扫码付款"
      }
    ]
  }
}
```

3. 操作步骤
在form中渲染二维码

**Comment by 2betop** [comment]
代码已经修了，待今天 1.1.2 发版本
