### ISSUE TITLE
autobind decorator ，在子类继承的时候，父类方法会自动绑定到子类。

### ISSUE THREAD

**Issue by zimo888** [baidu/amis#1371]
#### 描述问题：
autobind decorator ，在子类继承的时候，父类方法会自动绑定到子类。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. 操作步骤
请简单描述一下复现的操作步骤...
定义自定义Action子类，继承自Amis的Action。
override handleAction 方法时候就会出现。

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/1433
