### ISSUE TITLE
组件交互时React报错<Error: Unable to find node on an unmounted component.>

### ISSUE THREAD

**Issue by walkstreet** [baidu/amis#1375]
#### 描述问题：
组件交互时React报错<Error: Unable to find node on an unmounted component.>

#### 截图或视频：
![image](https://user-images.githubusercontent.com/10673870/104286957-b88c0380-54f0-11eb-94a0-4f4a1c5ff0b3.png)
![image](https://user-images.githubusercontent.com/10673870/104287037-d8232c00-54f0-11eb-99dc-2d8784869f53.png)
![image](https://user-images.githubusercontent.com/10673870/104287055-df4a3a00-54f0-11eb-9b2e-0351bc7b886b.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. 粘贴有问题的完整 `amis schema` 代码：
```
        {
            'type': 'page',
            'body': {
                'type': 'button-group',
                'buttons': [
                    {
                        'type': 'button',
                        'label': 'Button',
                        'actionType': 'dialog',
                        'dialog': {
                            'confirmMode': false,
                            'title': '提示',
                            'body': '对，你刚点击了！'
                        }
                    },
                    {
                        'type': 'button',
                        'actionType': 'url',
                        'url': 'https://www.baidu.com',
                        'blank': true,
                        'label': '百度一下'
                    },
                    {
                        'type': 'button',
                        'label': '普通按钮'
                    }
                ]
            }
        };
```

3. 操作步骤
项目依赖，React@17.0.1，amis@1.1.0
该示例是展示一个按钮组，按钮组能正常展示，在点击第一个有弹框的按钮后，弹出框动画能正常显示，但是动画完成后页面展示报错

**Comment by 2betop** [comment]
react 还不支持 17 先用  React 16

**Comment by walkstreet** [comment]
react和react-dom降到16.14.0即可
