### ISSUE TITLE
iframe中使用“增删改查”点击分页异常（JSSDK模式）

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#138]
在iframe或其他前端框架使用JSSDK时，“增删改查”表单（如嵌套）中如果涉及到分页，只有首次加载是正常的，在点击2、3、4、5…等其他分页按钮时，页面清空了，刷新也无法显示。

**Comment by 2betop** [comment]
你那边是什么路由，分页默认是会跳转页面，跳到目标页面后是否还会走到 amis 的初始化逻辑？可以考虑把 crud 的 syncLocation 关了，这样就不会跳转页面了

**Comment by foxfire881** [comment]
这个就是关键问题，因为不会折腾React、Vue这些前端的东西，所以根本没涉及到“路由”的概念，就是引用了amis的js/css两个地址，其他都是传统的HTML和js代码。

但是用一堆html文件嵌入不同的json实现不同的页面功能又太丑陋了，所以想只用一个html模板文件（就是示例中给的那个html文件），把json作为变量传进去，点击不同按钮加载不同json。为此有两种不同的实现方式：

1、客户端实现。把不同的json放进不同的js页面文件（如add.js、list.js）通过点击菜单中不同的按钮（在button上实现一个js函数loadpage加载不同的包含json的js）改变页面内容 —— 这种情况下只有一个index.html页面和一个http://localhost/index.html地址，如果加载不涉及分页的amis组件/页面都是正常的，但是一旦涉及分页就会清空页面。

2、服务端实现（python/django）：把add、list作为参数传给后端django，如请求http://localhost/add、http://localhost/list，后台接收到add、list参数后，把add.js、list.js渲染进index.html模板文件 —— 这种情况下所有页面都可以正常显示，但又是分页的问题，每次点击分页按钮时，页面会连续刷新两次。

所以，有没有啥完美点的方法？不折腾React，就用JSSDK实现一个html文件加载不同的json/js文件实现不同页面功能？

**Comment by foxfire881** [comment]
反馈：试了把syncLocation关了，似乎已经好用了，不会清空页面了。感谢~~ 继续使用中，又问题继续反馈。
