### ISSUE TITLE
在使用抽屉展示tinymce编辑器时，工具栏被覆盖了，需要设置z-index才能完全显示

### ISSUE THREAD

**Issue by 265525** [baidu/amis#1384]
在使用抽屉展示tinymce编辑器时，工具栏被覆盖了，需要设置z-index才能完全显示

**Comment by 265525** [comment]
.tox{z-index:9999!important;} 设置这个即可解决

**Comment by nwind** [comment]
新版应该解决了，我先关了如果有发现问题再开

**Comment by BeMxself** [comment]
现在在dialog里又出现这个问题
版本:1.4.2-beta.6
如下图：
![image](https://user-images.githubusercontent.com/3793855/142410977-ca24aa3a-6add-49e3-a7d3-d9df049a835f.png)

.tox-tinymce-aux 的 `z-index:3000` 样式被覆盖了

**Comment by IvanChen008** [comment]
> .tox{z-index:9999!important;} 设置这个即可解决

解决问题了额哦
