### ISSUE TITLE
希望form等组件也能够使用相对路由

### ISSUE THREAD

**Issue by Chise1** [baidu/amis#1392]
概述：
在我开发的时候，由于组件是通用的，比如crud或者一些别的需要请求的组件。以CRUD为例，我会在每个使用的地方配置一个相对路由。然后我希望在多页面的时候能够和对应的路由拼接起来，这样就能够不用遍历所有组件来寻找需要添加绝对路径的组件。具体示例如下图：
https://blog.csdn.net/weixin_36179862/article/details/112618058

**Comment by nwind** [comment]
链接挂了，没看懂相对是啥？url 地址？
