### ISSUE TITLE
Form表单不显示按钮的情况下配置Feedback

### ISSUE THREAD

**Issue by bluehr** [baidu/amis#1394]
#### 是否关联于某个问题吗：
无

#### 预期的解决方案：
在表单仅包括 **文件上传** 一个组件，没有按钮的情况下 能支持Feedback

#### 其他可接受方案：
无

#### 任何附加信息：
无

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/1420

**Comment by bluehr** [comment]
> #1420

感谢大佬，辛苦
