### ISSUE TITLE
 JSSDK左侧缩进后的两个小问题

### ISSUE THREAD

**Issue by quant-cat** [baidu/amis#1397]
1、左侧缩进后，点击一级菜单无法出页面
2、左侧缩进后，如果左边栏太靠屏幕底下，右边明细菜单无法全部显示

**Comment by 2betop** [comment]
问题1已修复
问题2 只能控制一下菜单数量了，之前是可以滚动的，但是又会有其他问题，等后面换整体布局样式再改。
