### ISSUE TITLE
后端返回的json数据格式有没有格式规定？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#140]
各种各样的数据接口，“增/删/改/查”、“上传”、“成功/失败”、“原因” …… 请问后端返回的json数据格式有没有标准格式规范？比如必须包含哪些字段、哪些字段可以自定义、成功/失败的原因是啥…… 等等 —— 数据接口规范在哪里可以查到？

**Comment by foxfire881** [comment]
就是右上角红色、绿色消息提示返回的结果

**Comment by 2betop** [comment]
```json
{
  status: 0,
 msg: ''
}
```

status 非0就是错误

```json
{
  status: 1,
 msg: '操作失败'
}
```

接口可以通过 msg 来控制提示信息
