### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by abasse** [baidu/amis#1406]
Hi,
Thanks for the great project!

I would like to add more languages to amis (German and Spanish). How can I do that?

Thanks,

Andre

**Comment by zimo888** [comment]
Using registerLocale to replace  the  default locale of amis, and the  key string of locale is chinese character.

```
import {registerLocale} from 'amis';
```

https://github.com/zimo888/amis-tutorial/blob/master/src/i18n/amisLocaleRegister.ts

**Comment by nwind** [comment]
Thank you, but please wait two weeks, we about to refactor on this, make it easier to add new language.
