### ISSUE TITLE
sdk模式下crud示例下拉后表头离会空出一定的高度位置

### ISSUE THREAD

**Issue by hukaiping** [baidu/amis#1407]
#### 实现场景：
使用sdk模式，实现增删改查功能，表格模式

#### 存在的问题：
从后端拉取数据后，进行鼠标下拉发现表头离顶部会空出一个高度位置，如图

![image](https://user-images.githubusercontent.com/16658678/104935046-b8ef3780-59e5-11eb-8c5a-e9aa994f537c.png)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

{
    "type": "page",
    "title": "",
    "body": [
        {
            "type": "crud",
            "draggable": true,
            "api": "https://houtai.baidu.com/api/sample?waitSeconds=1",
            "keepItemSelectionOnPageChange": true,
            "labelTpl": "${id} ${engine}",
            "filter": {
                "title": "条件搜索",
                "submitText": "",
                "controls": [
                    {
                        "type": "text",
                        "name": "keywords",
                        "placeholder": "通过关键字搜索",
                        "addOn": {
                            "label": "搜索",
                            "type": "submit"
                        }
                    },
                    {
                        "type": "plain",
                        "text": "这里的表单项可以配置多个"
                    }
                ]
            },
            "quickSaveApi": "https://houtai.baidu.com/api/sample/bulkUpdate",
            "quickSaveItemApi": "https://houtai.baidu.com/api/sample/$id",
            "filterTogglable": true,
            "headerToolbar": [
                {
                    "type": "filter-toggler"
                },
                {
                    "type": "bulk-actions"
                },
                {
                    "type": "tpl",
                    "tpl": "定制内容示例：当前有 ${count} 条数据。",
                    "className": "v-middle"
                },
                {
                    "type": "button",
                    "align": "right",
                    "label": "按钮"
                },
                {
                    "type": "drag-toggler",
                    "align": "right"
                },
                {
                    "type": "pagination",
                    "align": "right"
                },
                {
                    "type": "tpl",
                    "tpl": "内容"
                }
            ],
            "footerToolbar": [
                "statistics",
                "switch-per-page",
                "pagination"
            ],
            "messages": {
            },
            "interval": 3000,
            "silentPolling": false,
            "mode": "table",
            "autoJumpToTopOnPagerChange": true,
            "columns": [
                {
                    "name": "id",
                    "label": "ID",
                    "width": 20,
                    "sortable": true,
                    "type": "text",
                    "toggled": true,
                    "remark": "Bla bla Bla"
                },
                {
                    "name": "engine",
                    "label": "Rendering engine",
                    "sortable": true,
                    "searchable": true,
                    "type": "text",
                    "toggled": true
                },
                {
                    "name": "browser",
                    "label": "Browser",
                    "sortable": true,
                    "type": "text",
                    "toggled": false
                },
                {
                    "name": "platform",
                    "label": "Platform(s)",
                    "popOver": {
                        "body": "Popover 内容：${platform}"
                    },
                    "sortable": true,
                    "type": "text",
                    "toggled": true
                },
                {
                    "name": "version",
                    "label": "Engine version",
                    "quickEdit": true,
                    "type": "text",
                    "toggled": true,
                    "filterable": {
                        "options": [
                            {
                                "label": "4",
                                "value": "4"
                            },
                            {
                                "label": "5",
                                "value": "5"
                            },
                            {
                                "label": "6",
                                "value": "6"
                            }
                        ]
                    }
                },
                {
                    "type": "text",
                    "name": "grade",
                    "label": "CSS grade",
                    "quickEdit": {
                        "saveImmediately": true,
                        "mode": "inline",
                        "type": "select",
                        "options": [
                            "A",
                            "B",
                            "C",
                            "D",
                            "X"
                        ]
                    }
                },
                {
                    "type": "operation",
                    "label": "操作",
                    "width": 100,
                    "buttons": [
                        {
                            "type": "button",
                            "icon": "fa fa-eye",
                            "actionType": "dialog",
                            "tooltip": "查看",
                            "dialog": {
                                "title": "查看",
                                "body": {
                                    "type": "form",
                                    "controls": [
                                        {
                                            "type": "static",
                                            "name": "engine",
                                            "label": "Engine"
                                        },
                                        {
                                            "type": "divider"
                                        },
                                        {
                                            "type": "static",
                                            "name": "browser",
                                            "label": "Browser"
                                        },
                                        {
                                            "type": "divider"
                                        },
                                        {
                                            "type": "static",
                                            "name": "platform",
                                            "label": "Platform(s)"
                                        },
                                        {
                                            "type": "divider"
                                        },
                                        {
                                            "type": "static",
                                            "name": "version",
                                            "label": "Engine version"
                                        },
                                        {
                                            "type": "divider"
                                        },
                                        {
                                            "type": "static",
                                            "name": "grade",
                                            "label": "CSS grade"
                                        },
                                        {
                                            "type": "divider"
                                        },
                                        {
                                            "type": "html",
                                            "html": "<p>添加其他 <span>Html 片段</span> 需要支持变量替换（todo）.</p>"
                                        }
                                    ]
                                }
                            }
                        },
                        {
                            "type": "button",
                            "icon": "fa fa-pencil",
                            "tooltip": "编辑",
                            "actionType": "drawer",
                            "drawer": {
                                "position": "left",
                                "size": "lg",
                                "title": "编辑",
                                "body": {
                                    "type": "form",
                                    "name": "sample-edit-form",
                                    "api": "https://houtai.baidu.com/api/sample/$id",
                                    "controls": [
                                        {
                                            "type": "text",
                                            "name": "engine",
                                            "label": "Engine",
                                            "required": true
                                        },
                                        {
                                            "type": "divider"
                                        },
                                        {
                                            "type": "text",
                                            "name": "browser",
                                            "label": "Browser",
                                            "required": true
                                        },
                                        {
                                            "type": "divider"
                                        },
                                        {
                                            "type": "text",
                                            "name": "platform",
                                            "label": "Platform(s)",
                                            "required": true
                                        },
                                        {
                                            "type": "divider"
                                        },
                                        {
                                            "type": "text",
                                            "name": "version",
                                            "label": "Engine version"
                                        },
                                        {
                                            "type": "divider"
                                        },
                                        {
                                            "type": "select",
                                            "name": "grade",
                                            "label": "CSS grade",
                                            "options": [
                                                "A",
                                                "B",
                                                "C",
                                                "D",
                                                "X"
                                            ]
                                        }
                                    ]
                                }
                            }
                        },
                        {
                            "type": "button",
                            "icon": "fa fa-times text-danger",
                            "actionType": "ajax",
                            "tooltip": "删除",
                            "confirmText": "您确认要删除?",
                            "api": "delete:https://houtai.baidu.com/api/sample/$id"
                        }
                    ],
                    "toggled": true
                }
            ]
        }
    ],
    "aside": [
        {
            "type": "image",
            "thumbMode": "cover",
            "title": "",
            "imageCaption": "",
            "defaultImage": "sds",
            "src": "",
            "enlargeAble": false,
            "thumbRatio": "16:9",
            "className": "b-a b-primary r-2x",
            "imageClassName": "w-full",
            "showDimensions": false
        },
        {
            "type": "divider"
        },
        {
            "type": "nav",
            "stacked": true,
            "links": [
                {
                    "label": "页面1",
                    "to": "?id=1"
                },
                {
                    "label": "页面2",
                    "to": "?id=2"
                }
            ]
        }
    ],
    "messages": {
    },
    "headerClassName": "bg-primary",
    "className": "",
    "toolbar": [
        {
            "type": "dropdown-button",
            "label": "下拉按钮",
            "buttons": [
                {
                    "type": "button",
                    "label": "个人信息",
                    "actionType": "dialog",
                    "dialog": {
                        "title": "系统提示",
                        "body": "对你点击了"
                    }
                },
                {
                    "type": "button",
                    "label": "修改密码",
                    "actionType": "dialog",
                    "dialog": {
                        "title": "系统提示",
                        "body": "对你点击了"
                    }
                },
                {
                    "type": "button",
                    "label": "退出登录",
                    "actionType": "dialog",
                    "dialog": {
                        "title": "系统提示",
                        "body": "对你点击了"
                    },
                    "tooltip": "受到收到",
                    "tooltipPlacement": "bottom",
                    "size": "md",
                    "block": true,
                    "className": "r-3x"
                }
            ],
            "closeOnClick": true,
            "level": "info",
            "className": "text-white r-t r-r r-b r-l font-bold b-a w-full r-2x b-4x",
            "size": "md",
            "disabled": "",
            "disabledOn": ""
        }
    ]
}

**Comment by RickCole21** [comment]
用 [affixOffsetTop](https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started#affixoffsetbottom-number)
