### ISSUE TITLE
在 React 原生项目中引入 amis编辑器,如何创建自定义组件并在amis 编辑器上的组件上显示

### ISSUE THREAD

**Issue by a775611** [baidu/amis#1415]

**Comment by yifv** [comment]
amis文档上有介绍，照着做就行了

**Comment by a775611** [comment]
> amis文档上有介绍，照着做就行了

在页面上可以正常使用，但是 在amis 编辑器标签上不显示

**Comment by a775611** [comment]
> amis文档上有介绍，照着做就行了

在 amis-editor-demo 这个项目上就可以实现子自定义组件并且在 amis 编辑器上可以显示,但是React 纯生项目,通过npm引入 amis编辑器,按照文档进行自定义组件的编写，在amis编辑器上是看不到自定义组件的

**Comment by nwind** [comment]
按文档是肯定行的，我们自己就是这样用，不行的话后续再发一下具体代码
