### ISSUE TITLE
hash模式报错

### ISSUE THREAD

**Issue by FatDong1** [baidu/amis#142]
报错如下：

![image](https://user-images.githubusercontent.com/22772600/62702448-55ec2980-ba19-11e9-84a2-58fcdb10b5fd.png)

复现路径：
1. 开启hash模式
2. 跳转到http://127.0.0.1:8081/#/admin/dashboard?page=1
3. 点击左侧导航栏，改变hash值为http://127.0.0.1:8081/#/admin/dashboard

**Comment by 2betop** [comment]
没有复现，不过，我加了个判断不知道你那用最新的beta版本(1.0.0-beta.99)会不会复现。

**Comment by FatDong1** [comment]
新版本没问题了。

http://127.0.0.1:8081/#/admin/dashboard?page=1这里面是一个crud渲染器
