### ISSUE TITLE
分页：分页组件能否把是否总是显示页数和数据量做成可配置项？

### ISSUE THREAD

**Issue by zhht1204** [baidu/amis#1423]
#### 是否关联于某个问题吗：
有些需求需要不管数据量是多少，都想要显示统计和分页，但是amis现在只能在数据量大于当前分页每页量才会显示。

#### 预期的解决方案：
添加一个配置参数，例如alwaysShowPagination，默认为false（符合当前情况）。

当为true时不管有没有达到分页条件都会显示统计和切换页数组件

**Comment by 2betop** [comment]
1.1.4 将新增此配置。相关 pr https://github.com/baidu/amis/pull/1544
