### ISSUE TITLE
多层嵌套 Dialog 中，url行为会弹出多个 页面tab

### ISSUE THREAD

**Issue by RickCole21** [baidu/amis#1427]
#### 描述问题：
如题

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
不能复现了，应该是已经修复，先关了：）
