### ISSUE TITLE
增删改查的级联

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#143]
目前增删改查的“嵌套”都是针对同一个模型，比如一级分类、二级分类、三级分类（一、二、三级分类都在同一个表，包含的字段属性完全一样），所以调用的"增删改查"API都是同一个。

当前有个“一对多”的需求，比如 “唱片（发行商、发行时间） -  歌曲（歌名、作曲、作词、歌手、所属专辑）” —— 这种情况下想做类似嵌套那样的增删改查，点击”+“展开当前唱片下有哪些歌曲及其属性，并且唱片的增删改查API和歌曲的增删改查API是不一样的   ——  这个需求AMIS可以做到吗？用哪个组件模型呢？

**Comment by 2betop** [comment]
用可折叠功能，底部再放个 crud ？

**Comment by foxfire881** [comment]
意思是每一行”唱片“都折叠起来里面放一个”歌曲“的CURD？这要怎么配置呢，"折叠"里面配置的是对要对折叠的columns进行折叠，CURD怎么配进columns呢？

**Comment by 2betop** [comment]
折叠的栗子看这：https://baidu.github.io/amis/crud/footable?page=1

底部展示的列，可以配置成 type: crud

**Comment by foxfire881** [comment]
搞定~ 谢谢支持！太牛掰了~
