### ISSUE TITLE
想知道百度内部是怎么可视化编辑json的？

### ISSUE THREAD

**Issue by FatDong1** [baidu/amis#144]
可以透露下吗？用json-editor不太好转，看到文档有$schema这个字段

**Comment by FatDong1** [comment]
json-editor只支持v4，不支持v7草案

**Comment by FatDong1** [comment]
你们不会自己做了个支持v7草案的json editor吧

**Comment by 2betop** [comment]
monaco-editor 支持 draft07, 可视化编辑器还没办法对外，预计这个 q 提供闭源版本。

**Comment by FatDong1** [comment]
nice

**Comment by yeyuqiudeng** [comment]
@2betop 想问下，百度内部的可视化编辑器是基于拖拽的方式生成吗？大概什么时候可以提供闭源版本参考下呢？可以提供一下实现思路吗？谢谢。

**Comment by 2betop** [comment]
https://fex-team.github.io/amis-editor/

**Comment by junegod** [comment]
> https://fex-team.github.io/amis-editor/

啥时候开源呀

**Comment by 2betop** [comment]
写得太戳还不敢放出来丢人现眼

**Comment by junegod** [comment]
可以私聊给我😄

**Comment by thbgh** [comment]
> 可以私聊给我😄

给你了吗？ @junegod @2betop @nwind
