### ISSUE TITLE
【树形选择器】和【级联选择器】子节点全部被选中后，父节点未自动选中

### ISSUE THREAD

**Issue by Yonysun** [baidu/amis#1442]
#### 描述问题：
【树形选择器】和【级联选择器】子节点全部被选中后，父节点未自动选中

#### 截图或视频：
![image](https://user-images.githubusercontent.com/3928873/105567996-21853e00-5d71-11eb-8694-3bb73dc5f8e2.png)
![image](https://user-images.githubusercontent.com/3928873/105567983-09adba00-5d71-11eb-8015-e3f8d1d9fa97.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
react前端工程中使用npm安装amis

2. 粘贴有问题的完整 `amis schema` 代码：
https://baidu.gitee.io/amis/zh-CN/docs/components/form/tree
```
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "controls": [
      {
        "type": "tree",
        "name": "tree2",
        "label": "自动带上子节点的值",
        "multiple": true,
        "withChildren": true,
        "options": [
          {
            "label": "A",
            "value": "a"
          },
          {
            "label": "B",
            "value": "b",
            "children": [
              {
                "label": "B-1",
                "value": "b-1"
              },
              {
                "label": "B-2",
                "value": "b-2"
              },
              {
                "label": "B-3",
                "value": "b-3"
              }
            ]
          },
          {
            "label": "C",
            "value": "c"
          }
        ]
      }
    ]
  }
}
```

3. 操作步骤
点击选中某一节点的所有子节点。

看了下源码，确实未处理这个逻辑：
![image](https://user-images.githubusercontent.com/3928873/105568021-56919080-5d71-11eb-8929-9e51fd3ac7c4.png)

个人认为子节点全被选中后父节点应该自动被选中，用户角度来说可能算是个常识。

感谢大佬们支持！

**Comment by 2betop** [comment]
Tree 部分可以关注 https://github.com/baidu/amis/pull/1539

Nested Select 待处理
