### ISSUE TITLE
补充渲染器功能 - 实现穿梭器左边部分。

### ISSUE THREAD

**Issue by vinfolhu** [baidu/amis#1449]
#### 描述问题：
请用一段清晰简洁的文字描述问题是什么...
amis想实现类型这样的效果，如下图
左边是接口调用获得列表，右边是根据左边的选择，调取右边的接口获取列表

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://user-images.githubusercontent.com/18110163/105816020-b3e64580-5fee-11eb-99f1-26fcd51d358d.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
npm
2. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
有两种方式，收下  transfer 本身就支持选项远程加载和部分节点懒加载，

**Comment by 2betop** [comment]
有问题再开
