### ISSUE TITLE
sdk引入amis下，导出csv报错，应该是找不到导出csv代码，请问需要额外引入其他sdk js 吗？

### ISSUE THREAD

**Issue by hotmaycold** [baidu/amis#1450]
crud 导出csv报错，直接用的实例代码

**Comment by nwind** [comment]
没复现，记得部署所有 sdk 里的 js，比如这个功能需要加载 papaparse.js 文件

**Comment by hotmaycold** [comment]
> 没复现，记得部署所有 sdk 里的 js，比如这个功能需要加载 papaparse.js 文件

找到了papaparse.js了，大佬，但是导出的csv格式还是不太理想，有些tpl或者object的属性没打出来，效果不太理想，有没有地方可以配置的

**Comment by nwind** [comment]
这些只有「导出 Excel」支持
