### ISSUE TITLE
Update the data object via JS

### ISSUE THREAD

**Issue by abasse** [baidu/amis#1454]
Hi,

is it possible to update the data object of a form via JavaScript from outside of the components?

I have a external JS  event handler for multi user editing support, based on pusher.com, that receives updates via websockets.  I would like to populate these updates to the data object in the form.

Thanks,

André

**Comment by nwind** [comment]
It can, example:

```javascript
let amisScoped = amis.embed(
  '#root',
  {
    "type": "page",
    "name": "page1",
    "title": "form-title",
    "body": {
      "type": "form",
      "name": "form1",
      "controls": [
        {
          "label": "Name",
          "type": "text",
          "name": "name1"
        }
      ]
    }
  },
  {}, {}
);

let formValues = amisScoped.getComponentByName('page1.form1').getValues();

// set input value
amisScoped.getComponentByName('page1.form1').setValues({'name1': 'othername'});
```

**Comment by abasse** [comment]
Fantastic! Thank you very much. I got collaborative editing working. :)

![image](https://user-images.githubusercontent.com/3475978/106023284-f3806080-60c6-11eb-85f3-8a57580f7798.png)
