### ISSUE TITLE
是否有滚动条属性？页面内容太多放不下

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#146]
page、body、或者dialog弹窗、侧边栏弹窗 …… 请问这些控件是否有滚动条属性？试了一个dialog弹窗，只有size属性，设置成lg最大之后仍然放不下全部的表单项，但是没有滚动条，dialog冲破屏幕边缘了，也拉不下去 —— 这种情况如何处理好？

**Comment by 2betop** [comment]
不科学啊, dialog 是有滚动的，是不是使用方式不对，你可以尝试把你的配置放到 amis 的 examples 试试。

**Comment by foxfire881** [comment]
难道是样式表重叠了？我看amis引用了bootstrap的一些css样式，我的web里面菜单和导航条部分用的是AdminLTE前端框架（因为不会用React整那个菜单），里面也有bootstrap的css…… 难道是有冲突了？

**Comment by foxfire881** [comment]
> 不科学啊, dialog 是有滚动的，是不是使用方式不对，你可以尝试把你的配置放到 amis 的 examples 试试。

试了example，确认dialog没有滚动条，看来是个bug，修复一下吧？？测试样本见附件，点右上角按钮会弹出来一个超长的dialog冲破屏幕，没有滚动条。
[test.zip](https://github.com/baidu/amis/files/3486305/test.zip)

**Comment by foxfire881** [comment]
再补充一个样本，用自带的example试了也不没有滚动条。见附件，
[弹个表单.zip](https://github.com/baidu/amis/files/3486361/default.zip)
“弹个表单”试试。

**Comment by 2betop** [comment]
hi, sdk 版本的样式确实有问题，现已修复，刷新看看效果吧

**Comment by foxfire881** [comment]
谢谢修复问题，刚试了dialog已经有滚动条出来了，不过似乎还有一点小问题滚动条只能通过鼠标中键滚轮来回滚动？把鼠标移上去按住左键滑动不了。不过影响不大，不麻烦的话看看能否再优化一下，麻烦的话就算啦，现在这样也能用。
