### ISSUE TITLE
ajax操作，提醒配置confirmText 弹窗不显示

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#1461]
#### 描述问题：
ajax操作，提醒配置confirmText ，在二级弹窗下不显示

#### 截图或视频：
![image](https://user-images.githubusercontent.com/11575908/105954123-333b4e00-60af-11eb-9bb9-127109584689.png)
![image](https://user-images.githubusercontent.com/11575908/105954218-5bc34800-60af-11eb-8e54-69c8c0da70e3.png)
关闭该弹窗后，出现了删除提醒
![image](https://user-images.githubusercontent.com/11575908/105954283-6ed61800-60af-11eb-84fd-ad37758575ce.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk1.1.2

2. 粘贴有问题的完整 `amis schema` 代码：
```
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by RickCole21** [comment]
贴schema

**Comment by xiahao90** [comment]
用dialog弹出的添加页面，在富文本框中在点击上传图片，上传图片的框在背后看不到

{
						"label": "新增文章",
						"type": "button",
						"actionType": "dialog",
						"level": "success",
						"dialog": {
							"title": "新增文章",
							"size": "lg",
							"body": {
								"type": "form",
								"api": "post:/doc",
								"reload": "docList",
								"controls": [{
										"type": "text",
										"name": "title",
										"label": "标题:",
										"required": 1,
										"validations": {
											"maxLength": 80
										}
									},
									{
										"type": "text",
										"name": "keyword",
										"label": "关键字",
										"placeholder": ""
									},
									{
										"type": "textarea",
										"name": "info",
										"label": "摘要",
          								"description": "",
									},
									[{
										"type": "text",
										"name": "author",
										"label": "作者"
									},
									{
										"type": "datetime",
										"name": "ptime",
										"label": "发布时间"
									},
									{
										"type": "checkbox",
										"name": "boutique",
										"label": "是否加精"
									}],
									[
									{
										"type": "hidden",
										"name": "type_id",
									}],
									{
								        "type": "rich-text",
								        "name": "content",
								        "label": "文章内容",
								        "options": {
							                  "menubar": False,
							                  "height": 200,
							                  "plugins": [
							                    "advlist autolink lists link image charmap print preview anchor",
							                    "searchreplace visualblocks code fullscreen",
							                    "insertdatetime media table paste code help wordcount"
							                  ],
							                  "toolbar ": "undo redo | formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help"
							                }
							        }
								]
							}
						}
					}

**Comment by nwind** [comment]
是说了两个问题？都没复现，如果还有的话再单独报吧
