### ISSUE TITLE
【CRUD】删除某一页最后一条数据后，自动刷新没有自动加载前一页

### ISSUE THREAD

**Issue by Yonysun** [baidu/amis#1478]
#### 描述问题：
【CRUD】删除某一页最后一条数据后，已无此页更无数据，自动刷新还是以当前页码获取列表数据，没有自动改变页码加载前一页

#### 截图或视频：
![image](https://user-images.githubusercontent.com/3928873/106138797-8e506c00-61a7-11eb-868c-8d929a5f4895.png)

#### 如何复现（请务必完整填写下面内容）：

1. CRUD组件，我有11条数据，每页显示10条，共两页。

2. 进入第2页，删除第11条数据后，因此时只剩10条数据，只能分1页

3. 但自动刷新功能仍回去请求第二页数据，因分页组件只有1页时并不显示分页按钮，此时只能显示暂无数据页面，没办法回到第1页，只能通过手动刷新实现，用户体验差。

```
 {
  "label": "删除",
  "type": "button",
  "actionType": "ajax",
  "level": "danger",
  "confirmText": "确认要删除？",
  "reload": "houseKeeperTable",
  "api": {
    "method": "post",
    "url": "/manage/delete",
    "data": {
      "id": "${id}"
    },
    "dataType": "form"
  },
  "tooltip": "删除信息",
  "tooltipPlacement": "top",
  "icon": "fa fa-remove",
  "iconClassName": "pull-left",
  "className": "m-l-lg b-danger"
}
```

**Comment by RickCole21** [comment]
删除按钮上配置 `reload:'xxx?page=1'`

**Comment by Yonysun** [comment]
> 删除按钮上配置 `reload:'xxx?page=1'`

您的意思是不管当前第几页，删除完当前页唯一一条数据后，强制跳转到第一页？

**Comment by RickCole21** [comment]
嗯，最后一页页数好像没法知道啊，除非你删除接口返回到前端

**Comment by 2betop** [comment]
感觉这个case 应该接口层适配，数据返回的时候同时返回 page:1 字段，也能让前端切回上一页，前端无法判断这个场景。

由于长时间没回复这个issue先关了，有问题欢迎再开。
