### ISSUE TITLE
如何使 API 可以接收一个方法？

### ISSUE THREAD

**Issue by Soar360** [baidu/amis#148]
最近在做一个框架（ABP）和 AMIS 适配的工作。

ABP 是一个 Web 开发框架，其内置了一套动态代理系统，方便后端将一个 POCO 类型转换为 WebApi。

ABP 中也对常见的列表请求、响应等做了一个封装，拥有统一的返回格式和约定。但问题是，ABP 所实现的封装和 AMIS 并不兼容。最大的问题就是字段名称不一致。

我尝试过阅读 Amis 的代码，但我对 React 和 TypeScript 并不擅长，虽然找到了突破口（fetcher），但并没有想到好办法可以做适配，fetcher中并没有办法知道请求来源是 list 还是 一个form，所以直接篡改字段可能会引入其他问题。

我也试着去改变 ABP 的代码，但目前来看，我仍旧没有找到突破口。

如果API可以接受一个方法作为参数，那么也许就能解决我的问题，因为可做的事情有了更大的可能性。那么，如何改造才能让 Amis 的 API 可以接受一个方法呢？

ABP：  https://github.com/aspnetboilerplate/aspnetboilerplate

**Comment by 2betop** [comment]
api 配置里面，如果不是用json配置，而是直接用 js 配置的话，可以配置 apator，比如：

```
{
  "type": "crud",
  "api": {
  "url": "/xx/xxx",
  "method": "get",
  "adpator": (payload, response, api) => {
      ... 
     return payload;
  }
}
}
```

实际上 fetcher 里面也能拿到，fether 后面补一个 then， then 里面也能拿到api 信息

**Comment by FatDong1** [comment]
@2betop 文档里面好像找不到这个字段apator的说明

**Comment by RickCole21** [comment]
adaptor, 后续补一下
