### ISSUE TITLE
在列表模式下如何设置列操作列在左边和批量修改和select控件冲突问题

### ISSUE THREAD

**Issue by zengqinchris** [baidu/amis#1481]
第一个问题：在列表模式下批量修改和select控件冲突问题，如何解决
有批量操作情况
![image](https://user-images.githubusercontent.com/44901627/106355983-cf2abb00-6336-11eb-91f9-eb2ac3f57962.png)

代码
`import schema2component from "../../../utils/schema2component";

const schema = {
    "title": "有埋点事件全量管理",
    "body": {
        "type": "crud",
        "draggable": true,
        "name":"event_one",
        "api": "/app/point/xxxx",
        "keepItemSelectionOnPageChange": true,
        "loadDataOnce": true, //全部加载分页
        "loadDataOnceFetchOnFilter": false,
        "mode": "list",
        "quickSaveApi": "post:/app/point/xxxx",

        "headerToolbar": {
            "wrapWithPanel": false,
            "type": "form",
            "className": "text-right",
            "target": "thelist",
            "mode": "normal",
            "controls": [
                {
                    "type": "text",
                    "name": "keywords",
                    "addOn": {
                        "type": "submit",
                        "label": "搜索",
                        "level": "primary",
                        "icon": "fa fa-search pull-left"
                    }
                },
                {
                    "label": "批量删除",
                    "level": "primary",
                    "type": "button",
                    "actionType": "ajax",
                    "api": "delete:/app/client/delete/${ids|raw}",
                    "confirmText": "确定要批量删除?"
                },
            ]
        },
        "footerToolbar": [
            "statistics",
            "switch-per-page",
            "pagination",
        ],
        "listItem": {
            "actions": [
                {
                    "type": "button",
                    "icon": "fa fa-times text-danger",
                    "actionType": "ajax",
                    "tooltip": "删除",
                    "confirmText": "您确认要删除?",
                    "api": "delete:/app/client/delete/$id"
                }
            ],
            "body": [
                {
                    "type": "hbox",
                    "columns": [
                        {
                            "type": "text",
                            "name": "event_version",
                            "label": "初始上线版本",
                            "sortable": true,
                            "quickEdit": true,
                            "required": true,
                        },
                        {
                            "name": "app_platform",
                            "label": "平台",
                            "sortable": true,
                            "type": "text",
                            "toggled": true,
                            "quickEdit": {
                                "type": "select",
                                // "multiple": true,
                                "required": true,
                                "options": [
                                    {
                                        "label": "ANDROID",
                                        "value": "ANDROID"
                                    },
                                    {
                                        "label": "IPHONE",
                                        "value": "IPHONE"
                                    },
                                ]
                            },
                        },
                        {
                            "name": "event_side",
                            "label": "埋点端",
                            "sortable": true,
                            "type": "text",
                            "toggled": true,
                            "quickEdit": {
                                "type": "select",
                                "required": true,
                                "inline": true,
                                "multiple": false,
                                "options": [
                                    {
                                        "label": "客户端",
                                        "value": "client"
                                    },
                                    {
                                        "label": "服务端",
                                        "value": "server"
                                    },
                                    {
                                        "label": "H5",
                                        "value": "H5"
                                    }
                                ]
                            },
                        },
                        {
                            "type": "text",
                            "name": "id",
                            "label": "ID",
                            "sortable": true,
                            "fixed": "left"
                        },
                    ]
                },
                {
                    "type": "hbox",
                    "columns": [
                        {
                            "name": "event_type",
                            "label": "事件类型",
                            "sortable": true,
                            "type": "text",
                            "toggled": true,
                            "quickEdit": {
                                "type": "textarea",
                            },
                            "required": true,
                        },
                        {
                            "name": "func_name",
                            "label": "事件名",
                            "sortable": true,
                            "type": "text",
                            "toggled": true,
                            "quickEdit": {
                                "type": "textarea",
                            },
                            "required": true,
                        },
                        {
                            "name": "app_id",
                            "label": "产品",
                            "type": "mapping",
                            "map": {
                                "1": "Athena",
                                "2": "内容运营"
                            },
                            "quickEdit": {
                                "type": "select",
                                "required": true,
                                "multiple": false,
                                "options": [
                                    {
                                        "label": "Athena",
                                        "value": "1"
                                    },
                                    {
                                        "label": "内容运营",
                                        "value": "2"
                                    },
                                ]
                            },
                        },
                        {
                            "name": "event_status",
                            "label": "启用状态",
                            "sortable": true,
                            "type": "mapping",
                            "map": {
                                "1": "上线",
                                "0": "下线"
                            },
                            "toggled": true,
                            "quickEdit": {
                                "type": "select",
                                "required": true,
                                "multiple": false,
                                "options": [
                                    {
                                        "label": "上线",
                                        "value": "1"
                                    },
                                    {
                                        "label": "下线",
                                        "value": "0"
                                    },
                                ]
                            },
                        },
                    ]
                },
            ],
        },
    }
};

export default schema2component(schema);`

没有批量操作情况
![image](https://user-images.githubusercontent.com/44901627/106356176-97bd0e00-6338-11eb-9c0d-849aef988d97.png)

代码
`import schema2component from "../../../utils/schema2component";

const schema = {
    "title": "有埋点事件全量管理",
    "body": {
        "type": "crud",
        "draggable": true,
        "name":"event_one",
        "api": "/app/point/xxxx",
        "keepItemSelectionOnPageChange": true,
        "loadDataOnce": true, //全部加载分页
        "loadDataOnceFetchOnFilter": false,
        "mode": "list",
        "quickSaveApi": "post:/app/point/xxxx",

//注释了这些代码就可以单选，但是就设置了不了多选了
// "headerToolbar": {
            // "wrapWithPanel": false,
            // "type": "form",
            // "className": "text-right",
            // "target": "thelist",
            // "mode": "normal",
            // "controls": [
            //     {
            //         "type": "text",
            //         "name": "keywords",
            //         "addOn": {
            //             "type": "submit",
            //             "label": "搜索",
            //             "level": "primary",
            //             "icon": "fa fa-search pull-left"
            //         }
            //     },
            //     {
            //         "label": "批量删除",
            //         "level": "primary",
            //         "type": "button",
            //         "actionType": "ajax",
            //         "api": "delete:/app/client/delete/${ids|raw}",
            //         "confirmText": "确定要批量删除?"
            //     },
            // ]
        // },

        "footerToolbar": [
            "statistics",
            "switch-per-page",
            "pagination",
        ],
        "listItem": {
            "actions": [
                {
                    "type": "button",
                    "icon": "fa fa-times text-danger",
                    "actionType": "ajax",
                    "tooltip": "删除",
                    "confirmText": "您确认要删除?",
                    "api": "delete:/app/client/delete/$id"
                }
            ],
            "body": [
                {
                    "type": "hbox",
                    "columns": [
                        {
                            "type": "text",
                            "name": "event_version",
                            "label": "初始上线版本",
                            "sortable": true,
                            "quickEdit": true,
                            "required": true,
                        },
                        {
                            "name": "app_platform",
                            "label": "平台",
                            "sortable": true,
                            "type": "text",
                            "toggled": true,
                            "quickEdit": {
                                "type": "select",
                                // "multiple": true,
                                "required": true,
                                "options": [
                                    {
                                        "label": "ANDROID",
                                        "value": "ANDROID"
                                    },
                                    {
                                        "label": "IPHONE",
                                        "value": "IPHONE"
                                    },
                                ]
                            },
                        },
                        {
                            "name": "event_side",
                            "label": "埋点端",
                            "sortable": true,
                            "type": "text",
                            "toggled": true,
                            "quickEdit": {
                                "type": "select",
                                "required": true,
                                "inline": true,
                                "multiple": false,
                                "options": [
                                    {
                                        "label": "客户端",
                                        "value": "client"
                                    },
                                    {
                                        "label": "服务端",
                                        "value": "server"
                                    },
                                    {
                                        "label": "H5",
                                        "value": "H5"
                                    }
                                ]
                            },
                        },
                        {
                            "type": "text",
                            "name": "id",
                            "label": "ID",
                            "sortable": true,
                            "fixed": "left"
                        },
                    ]
                },
                {
                    "type": "hbox",
                    "columns": [
                        {
                            "name": "event_type",
                            "label": "事件类型",
                            "sortable": true,
                            "type": "text",
                            "toggled": true,
                            "quickEdit": {
                                "type": "textarea",
                            },
                            "required": true,
                        },
                        {
                            "name": "func_name",
                            "label": "事件名",
                            "sortable": true,
                            "type": "text",
                            "toggled": true,
                            "quickEdit": {
                                "type": "textarea",
                            },
                            "required": true,
                        },
                        {
                            "name": "app_id",
                            "label": "产品",
                            "type": "mapping",
                            "map": {
                                "1": "Athena",
                                "2": "内容运营"
                            },
                            "quickEdit": {
                                "type": "select",
                                "required": true,
                                "multiple": false,
                                "options": [
                                    {
                                        "label": "Athena",
                                        "value": "1"
                                    },
                                    {
                                        "label": "内容运营",
                                        "value": "2"
                                    },
                                ]
                            },
                        },
                        {
                            "name": "event_status",
                            "label": "启用状态",
                            "sortable": true,
                            "type": "mapping",
                            "map": {
                                "1": "上线",
                                "0": "下线"
                            },
                            "toggled": true,
                            "quickEdit": {
                                "type": "select",
                                "required": true,
                                "multiple": false,
                                "options": [
                                    {
                                        "label": "上线",
                                        "value": "1"
                                    },
                                    {
                                        "label": "下线",
                                        "value": "0"
                                    },
                                ]
                            },
                        },
                    ]
                },
            ],
        },
    }
};

export default schema2component(schema);`

第二个问题：在列表模式下如何设置列操作列在左边
实现场景：
![image](https://user-images.githubusercontent.com/44901627/106234477-dfa63d00-6233-11eb-8f43-6ca1a4c4ccc8.png)
在列表模式下，设置操作列在左边，
使用 "position": "left", 方式设置不管用，不知道如何设置
![image](https://user-images.githubusercontent.com/44901627/106234528-f8165780-6233-11eb-878b-64da8c8b58b7.png)

**Comment by RickCole21** [comment]
直接columns里配在前面啊，哪来的`position:left`

**Comment by zengqinchris** [comment]
而且在列表模式下
![image](https://user-images.githubusercontent.com/44901627/106267300-6a9f2b80-6264-11eb-8c30-bfd539593840.png)
无法设置 单选，设置了这个   "multiple": false, 还是不行

{
                            "name": "event_side",
                            "label": "埋点端",
                            "sortable": true,
                            "type": "text",
                            "toggled": true,
                            "quickEdit": {
                                "type": "select",
                                "required": true,
                                "multiple": false,
                                "options": [
                                    {
                                        "label": "客户端",
                                        "value": "client"
                                    },
                                    {
                                        "label": "服务端",
                                        "value": "server"
                                    },
                                    {
                                        "label": "H5",
                                        "value": "H5"
                                    }
                                ]
                            },
                        },

**Comment by 2betop** [comment]
待 1.1.4 发布，有问题之后再提，可以关注这个 pr https://github.com/baidu/amis/pull/1543
