### ISSUE TITLE
jssdk 如何reload pages

### ISSUE THREAD

**Issue by miwoy** [baidu/amis#1483]
#### 实现场景：
我使用jssdk搭建的App 多页应用。使用[这个模板](https://github.com/fex-team/amis-admin)

我的pages使用api从服务器拉取的配置

现在有一个需求，要实现动态菜单。

就是在其中一个page内增加菜单项保存至服务器，然后让app组件重新拉取api服务器的最新pages数据

#### 存在的问题：
但是我使用actionType=reload并没有任何效果

同样的使用在api中插入动态数据也没有效果

而且我发现对于app层定义的data，在page中是无法修改的。

不知道是否有什么方法能够实现这种需求

#### 当前方案：
当前我使用了强制刷新页面的方法，这显然不够优雅

**Comment by 2betop** [comment]
待 1.1.4 发布，后面还有问题再开
