### ISSUE TITLE
弹框弹出的时候滚动条消失

### ISSUE THREAD

**Issue by liuchy73** [baidu/amis#149]
弹框弹出的时候滚动条消失，页面会自动拉伸，弹框消失后页面又会恢复
![image](https://user-images.githubusercontent.com/18005741/62844458-1a40b080-bcf4-11e9-8c92-7025735111f4.png)

**Comment by 2betop** [comment]
确实是这样设计的呢，弹出的时候，应该 body 不能滚动了，以弹出的内容为主，如果弹框内容过高，出现滚动也应该是针对弹框的，而不是 body 内容的。

**Comment by 2betop** [comment]
个人觉得这个不是问题，先关了，有问题接受 argument。
