### ISSUE TITLE
jssdk 多页应用切换菜单问题

### ISSUE THREAD

**Issue by miwoy** [baidu/amis#1493]
#### 描述问题：
模板：[admin-amis模板](https://github.com/aisuda/amis-admin)
amis版本: 1.1.4-beta.4

pages是从api接口中动态配置的。在同一分组下的菜单使用了同一个page模板（也是由api中获取的）
但是当我切换菜单时，我发现page中的api参数使用的是上一个page中的参数

#### 截图或视频：
![image](https://user-images.githubusercontent.com/6166336/106420842-75410700-6496-11eb-9923-aa0e58195908.png)
从图中1和2的部分可以看出，我已经切换到了测试模型菜单中。由3也可以看出我正常加在了tes的page schema数据，理论上page schema中引用的api使用的参数应当是tes，而从图4中可以看出实际上却是使用了article参数。我确定我配置中并没有问题。而且在刷新页面时，请求是没有问题的，只有在切换菜单时才会出现，我怀疑是环境污染导致的
#### 如何复现（请务必完整填写下面内容）：

[源码](https://github.com/miwoy/cms)

3. 操作步骤

1. 安装依赖
`yarn`

2. 启动
`yarn dev`

3. 访问 [http://localhost:3000/#/collection/article?id=article](http://localhost:3000/#/collection/article?id=article)
4. 尝试切换`内容模型>文章`菜单和`内容模型>测试模型`

**Comment by miwoy** [comment]
使用CRUD设置"syncLocation": false请求会多发一次，最后一次的请求是正常的
注意必须设置false,不能为空或者true。

**Comment by 2betop** [comment]
这是个历史问题，请升级最新版本，有问题再开
