### ISSUE TITLE
新增的Combo->table 的422校验，在errors 是行级信息的时候会崩溃

### ISSUE THREAD

**Issue by zimo888** [baidu/amis#1498]
#### 描述问题：
服务器校验422 回来的errors，当不定位到字段，只到行时候，
当 item.setError不存在会崩溃，希望增加一个undefined判断。

store/form.ts

  if (Array.isArray(items) && items.length) {
                  items.forEach(item => **item.setError** && item.setError(`${errors[key]}`));
                  delete errors[key];
                }
#### 截图或视频：
![image](https://user-images.githubusercontent.com/4545006/106436719-69157380-64af-11eb-8e69-02b77b4fb6b1.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`&`npm` 

2. 粘贴有问题的完整 `amis schema` 代码：
```
  "errors": {
    "combo.table[1]": "服务器端说，这一行有问题"
  }
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
没复现应该是加了 filter 后修了
