### ISSUE TITLE
Table中的项目是否可以按列自定义渲染？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#150]
比如一个Table，其中有一列column是“身份证号”，当前都是文本显示的，希望把这一列渲染成链接或者按钮，可以点击之后弹出一个框显示身份详情（姓名、生日、归属等）  —— 这个要怎么做？样例给出的模板都是对一整行Item在最后一列加增删改查的操作，现在是希望每一列自定义不同的渲染、功能按钮。能实现吗？

**Comment by 2betop** [comment]
列类型用 `container`， body 里面放个按钮就行了。

```
{ 

   type: "container",
  button: [
     {
        label: "${xxx}",
        type: "button",
        actionType: "dialog", 
        dialog: {...}
     }
  ]
}
```

**Comment by foxfire881** [comment]
good~

**Comment by FatDong1** [comment]
@2betop 上面的json示例写错了，是body，不是button
