### ISSUE TITLE
子表的任意表单项修改会触发所有表单项渲染，卡顿明显

### ISSUE THREAD

**Issue by zimo888** [baidu/amis#1505]
#### 描述问题：

子表修改会触发全部字段重绘

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

![image](https://user-images.githubusercontent.com/4545006/106543495-cdccde80-6540-11eb-8486-ec97827452e2.png)

**Comment by 2betop** [comment]
居然是因为 isVisible 的判断传入了 store.data
https://github.com/baidu/amis/issues/1505

**Comment by 2betop** [comment]
先关了，1.1.4 发布后还有问题再开
