### ISSUE TITLE
mapping组件的map值能否从data中获取

### ISSUE THREAD

**Issue by zsfish** [baidu/amis#1522]
#### 是否关联于某个问题吗：
因为项目枚举值是从一个接口中一次性获取，我将获取到的枚举值处理成map格式，通过renderAmis的data值传递到渲染器内部，让每一个组件都可以直接拿到。但crud中的columns中为mapping的那一列，map无法渲染出data里存储的数据

#### 预期的解决方案：
map能够直接渲染存储在data里的map对象

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
1.1.6 后支持了
