### ISSUE TITLE
表单name绑定重名的问题

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#153]
场景是域环境下使用，需要根据输入账号的ID查询返回ID对应的中文姓名。

一个表单里面有两项：负责人1、负责人2。输入是账号ID，点击后面的查询按钮后调用API查询返回中文姓名。

当前的问题是，由于两个手工查询按钮调用的都是同一个API（/api/search），只是传入的参数不一样（id1、id2），但是返回的json结构都是一样的，如{"uid":"id1","uname":"uname1"}、{"uid":"id2","uname":"uname2"}，前端做name绑定时只能绑定到统一的字段uname。 如果希望”负责人1“返回结果绑定到name1、”负责人2"返回结果绑定到name2 —— 这要怎么配置呢？

**Comment by 2betop** [comment]
https://baidu.github.io/amis/docs/renderers/Types#api
用接口适配器关联一下？

**Comment by foxfire881** [comment]
这部分没看太明白呢，给的样例是重构前端的字段结构（比如把前端的title字段映射成subject，构造成符合后端参数接收要求的形式），然后发送请求，让前端适配后端的参数传递的形式。

我遇到的问题是反过来的，两个不同的前端表单项调用同一个后端，后端返回的json结构都是一样的，如何把返回结果绑定到前端，让同一个后端适配两个不同的前端的name？

**Comment by RickCole21** [comment]
第一个api里吧参数里的id1映射成id

**Comment by RickCole21** [comment]
例如：
请求时：
第一个api中，用适配器把参数"id1"映射成"id"
第二个api中，用适配器把参数"id2"映射成"id2"

返回时：
第一个api，用适配器把参数"uname"映射成"name1"
第二个api，用适配器把参数"uname"映射成"name2"

**Comment by foxfire881** [comment]
> 例如：
> 请求时：
> 第一个api中，用适配器把参数"id1"映射成"id"
> 第二个api中，用适配器把参数"id2"映射成"id2"
> 
> 返回时：
> 第一个api，用适配器把参数"uname"映射成"name1"
> 第二个api，用适配器把参数"uname"映射成"name2"

多谢回复。返回时如何用适配器做映射呢？amis给的样例都是请求时的映射，好像没看到返回时如何对服务端的json做二次重映射？

**Comment by RickCole21** [comment]
api上可以直接配置：
```
api: {
    method: 'get',
    url: '/api/xxx',
    data:{
        x: 'xxx'
    },
    // 这里可以配置请求接收适配器
    adaptor: (payload, response) => {
        let data = payload.data;
        // ...对data进行一些normalize操作
        
        return {
              ...payload,
              data
        }
    },
    // 这里配置发送适配器
    requestAdaptor:(api)=>{
        // 这里可以在请求前对api进行改写
        return {
              ...api,
              data:{
                  ...api.data,
                  other: 'somedata' // 加点其他数据
              }
        }
    }
}
```

**Comment by foxfire881** [comment]
果然，这个才是最关键的地方。文档和样例里面似乎都没找到adaptor、requestAdaptor相关的介绍。谢谢~ 我试一下，有问题再请教。

**Comment by foxfire881** [comment]
请问可以给个完整的例子吗？比如怎么做字段输入和输出的二次重映射，amis文档中没有找到关于request/response适配器使用的相关说明，网上也没找到相关资料，不知道具体语法应该怎么写，前端技能太菜了。

**Comment by foxfire881** [comment]
return完整应该返回什么呢？比如原封不动返回的话，应该怎么写？ 

adaptor: (payload, response) => {
        let data = payload.data;
        // ...对data进行一些normalize操作
        
        **return {
              ...payload,
              data
        }**
    },
    // 这里配置发送适配器
    requestAdaptor:(api)=>{
        // 这里可以在请求前对api进行改写
        **return {
              ...api,
              data:{
                  ...api.data,
                  other: 'somedata' // 加点其他数据
              }
        }**
    }

**Comment by 2betop** [comment]
你发的这个就原封不动啊

**Comment by foxfire881** [comment]
谢谢，已搞定~
顺便请问一下，return中“..."三个点是什么语法、什么意思？从来没见过这种写法，昨天一直卡在这里以为是省略号少了一些代码，后来才发现语法就是这样的。

 return {
              ...payload,
              data
        }

**Comment by foxfire881** [comment]
另外建议完善一下文档，这个amis前端框架太强了，之前比较了AntDesign、ElementUI，门槛都太高要结合React、Vue才能用，新手很难上手，后来才找到了amis，真的很强大门槛很低，后面再继续完善一下，肯定比antd和elementui更受欢迎~ 感谢提供这么好的开源项目。

**Comment by RickCole21** [comment]
...是es6的扩展运算符http://es6.ruanyifeng.com/#docs/object#对象的扩展运算符

感谢支持，我们会继续完善文档
