### ISSUE TITLE
表单中的"type":"date"出现一个奇怪的bug

### ISSUE THREAD

**Issue by 265525** [baidu/amis#1531]
![%O)6LW2ACK98}_ ))W%{D_C](https://user-images.githubusercontent.com/30653455/106843184-66e62b80-66e0-11eb-9c8e-5512989ecdce.png)
如图，当value设置成与name获取的内容相同时，打开form的编辑组件才会渲染出来，否则时空
![MOCSR6ASTJ3QQRWVM)RC%TF](https://user-images.githubusercontent.com/30653455/106843254-92691600-66e0-11eb-8ed3-30ac588ea22e.png)
初步判断此问题为一个冲突设置

**Comment by 2betop** [comment]
format: 'YYYY-MM-DD',
valueFoamt: ''

这样就行了
