### ISSUE TITLE
列表中有个字段限制长度鼠标滑上去显示完整的值

### ISSUE THREAD

**Issue by chenzhen1991** [baidu/amis#1557]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
列表中有个字段限制长度鼠标滑上去显示完整的值
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
我写了hover，但是还是click才可以看到完整的值

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
{
            "type": "tpl",
            "name": "tenantName",
            "label": "租户名称",
            "tpl": "${tenantName|truncate:20}",
            "popOver": {
                "trigger": "hover",
                "position": "left-top",
                "showIcon": false,
                "body": {
                    "type": "tpl",
                    "tpl": "${tenantName}"
                }
            }
        }
```

![image](https://user-images.githubusercontent.com/21083926/107020210-8d3dc100-67dd-11eb-865d-45dbf4938fdf.png)

**Comment by nwind** [comment]
可以 tpl 里写个 span，里面的 title 字段放完整的，后续再考虑加个啥字段
