### ISSUE TITLE
自定义组件赋值，无法删除

### ISSUE THREAD

**Issue by zimo888** [baidu/amis#1568]
#### 描述问题：
自定义组件，文本框的值删不掉

#### 截图或视频：
![image](https://user-images.githubusercontent.com/4545006/107216357-9e8a0600-6a47-11eb-967d-39350135647f.png)

https://user-images.githubusercontent.com/4545006/107216385-a8ac0480-6a47-11eb-9195-bd95e8ee1ad9.mp4

#### 如何复现（请务必完整填写下面内容）：

样例写在了下面 ： 

https://github.com/iWuzhi/amis-react-starter

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/1577

**Comment by 2betop** [comment]
目前最新版本已无此问题，请升级版本，有问题再开issue
