### ISSUE TITLE
App渲染器文档链接404

### ISSUE THREAD

**Issue by maliails** [baidu/amis#1569]
#### 描述问题：
API文档里的 APP渲染器链接失效了，能否提供一份使用手册。

#### 截图或视频：
https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started#%E5%A4%9A%E9%A1%B5%E6%A8%A1%E5%BC%8F
https://baidu.gitee.io/components/app

#### 如何复现（请务必完整填写下面内容）：
想要学习使用APP渲染器

**Comment by RickCole21** [comment]
https://baidu.gitee.io/amis/zh-CN/components/app
