### ISSUE TITLE
1.1.4版本中RootRenderProps.location类型定义错误

### ISSUE THREAD

**Issue by gymmer** [baidu/amis#1572]
#### 描述问题：
1.1.4版本中，`RootRenderProps`中`location?: Location`没有注明`import { Location } from 'history';`，导致索引到了VSCode默认的`lib.dom.d.ts`，路径为`/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts`，从而导致使用报错：`TS2740: Type 'Location<any>' is missing the following properties from type 'Location': ancestorOrigins, host, hostname, href, and 6 more.`

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://user-images.githubusercontent.com/9761363/107344643-a906d700-6afd-11eb-9311-64c9b0d84186.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. 粘贴有问题的完整 `amis schema` 代码：
```
render() {
  const {
    router,
    match,
    location,
    history,
    store,
    schema: schemaProp,
    jumpTo,
    updateLocation,
    embedMode,
    ...rest
  } = this.props;
  const finalSchema = schemaProp || schema;
  finalSchema.type || (finalSchema.type = 'page');

  const body: React.ReactNode = render(
    finalSchema,
    {
    location, 
    data: utils.createObject({
        ...match.params,
        amisStore: store,
        pathname: location.pathname,
        params: match.params,
    }),
    ...rest,
    propsTransform: transform,
    },
    this.getEnv(),
  );

  return <>{body}</>;
}
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by gymmer** [comment]
1.1.1版本没有报错。我找了RootRenderProps.location的定义，对比不同，发现1.1.1版本中有`import { Location } from 'history';`

**Comment by nwind** [comment]
报错是指 vscode 里？另外这个用浏览器 location 的话也是可以的
