### ISSUE TITLE
Text组件选择器模式下，提示文字多了个}符号

### ISSUE THREAD

**Issue by hiro0729** [baidu/amis#1578]
#### 描述问题：
Text组件选择器模式下，提示字符多了个大括号

#### 截图或视频：
![1](https://user-images.githubusercontent.com/7811341/107744528-d053e300-6d4d-11eb-8833-4dce53530234.png)

#### 如何复现：

src/locale/zh-CN.ts中多了个大括号

![2](https://user-images.githubusercontent.com/7811341/107744589-efeb0b80-6d4d-11eb-83f5-fdae450bdeb9.png)

**Comment by nwind** [comment]
已修复，谢谢
