### ISSUE TITLE
table的多选模式，如果有横滚动条，在横滚动条移动的时候，会导致第一列的选择框位置错位

### ISSUE THREAD

**Issue by vvelement** [baidu/amis#1586]
table的多选模式，如果有横滚动条，在横滚动条移动的时候，会导致第一列的选择框位置错位
![image](https://user-images.githubusercontent.com/79433774/108654165-1144b800-7503-11eb-8a65-f135567c0a18.png)

**Comment by 2betop** [comment]
新版本已无此问题，请升级版本
