### ISSUE TITLE
drawer 和 dialog的actions中 actionType: reload 的自动关闭无效

### ISSUE THREAD

**Issue by xuhandong18** [baidu/amis#1587]
#### 描述问题：
drawer 和 dialog的actions中 actionType: reload ,即使设置了close:true, 也自动关闭无效

#### 截图或视频：
![image](https://user-images.githubusercontent.com/51759053/108682514-5bda2a80-752b-11eb-8ffc-c12abc97230e.png)

**Comment by xuhandong18** [comment]
但reload 目标是有效的

**Comment by 2betop** [comment]
新版本已经修复了，请升级，有问题再开
