### ISSUE TITLE
ajax action的自动跳转第一次无效

### ISSUE THREAD

**Issue by xuhandong18** [baidu/amis#1588]
#### 描述问题：
第一次点击 ajax action,在 ajax执行成功后, 从ajax返回的结果中获取redirect的地址, 但不会跳转
要第二次点击后,才会跳转.

按正常逻辑来讲,就是ajax获取了要跳转的链接, 然后直接跳转到这个链接即可

#### 截图或视频：
![image](https://user-images.githubusercontent.com/51759053/108682861-cee3a100-752b-11eb-97bd-86b6b9131b12.png)

#### 如何复现（请务必完整填写下面内容）：
随便找个api返回一个链接, 给redirect设置数据映射, 就可以复现了.

**Comment by CheshireJCat** [comment]
未复现，若数据返回符合api要求格式，可正确从表达式中解析到 url，并进行跳转
