### ISSUE TITLE
希望全局抓取指定的API异常

### ISSUE THREAD

**Issue by swtseaman** [baidu/amis#1590]
#### 实现场景：
在API请求中，希望能抓取到指定的错误进行特殊处理，比如检测status为600的时候说明用户登录已过期，自动跳转页面到登录页，尝试了responseAdpater，但好像不执行，因为不是很懂前端

#### 存在的问题：
responseAdpater方法中的代码不执行

#### 当前方案：
```

let amisScoped = amis.embed('#root', amisJSON,{},{
  fetcher:(config) => {
  config.url = 'http://localhost:8088' + config.url
  config.headers = {};
  config.headers["x-token"] = localStorage.userToken \|\| "token";
  return axios(config);
  }, updateLocation:(to, replace) => {
  }, responseAdpater(api, response, query, request) {
  console.info(api);
  console.info(response);
  console.info(query);
  console.info(request);
  return response;
  }
  });
```
按理解应该是API调用完成后，amis会调用这里注册的responseAdpater方法，并传入api,response,query,request这几个对象，所以应该能在控制台看到这几个对象的输出，但是并没有，所以是不是我哪里理解不对

**Comment by RickCole21** [comment]
fetcher里自己catch

**Comment by swtseaman** [comment]
已解决，代码留给有需要的人
```
let axios = amisRequire('axios');
// 为axios添加请求拦截器
axios.interceptors.response.use(function (response) {
    // 以下可以根据自己的逻辑进行判断和页面跳转，或者干做其他的事情
    if(response.data.status === 50008) {
        top.location.href = '/login';            
    }
    return response;
}); 
```

**Comment by AUSERGEE** [comment]
> 已解决，代码留给有需要的人
> 
> ```
> let axios = amisRequire('axios');
> // 为axios添加请求拦截器
> axios.interceptors.response.use(function (response) {
>     // 以下可以根据自己的逻辑进行判断和页面跳转，或者干做其他的事情
>     if(response.data.status === 50008) {
>         top.location.href = '/login';            
>     }
>     return response;
> }); 
> ```

谢谢，可以了
