### ISSUE TITLE
API的GET请求在URL中变量的使用问题

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#1594]
#### 描述问题：

我的使用场景。
在页面中URL是动态的，现在的方法是在schema的data中记录一个URL，然后需要使用api的地方使用${key}的方式取到真实的URL。
但是，这种方式在get请求中，无法获取到参数。
如："api": "get:${url.list|raw}",

具体原因如下：

在文件api.ts中的buildApi方法，会构建URL，
其中有代码：
```
...
const raw = (api.url = api.url || '');
...
if (!~raw.indexOf('$') && !api.data && autoAppend) {
      api.query = api.data = data;
    } else if (
      api.attachDataToQuery === false &&
      api.data &&
      !~raw.indexOf('$') &&
      autoAppend
    ) {
...
}

```

由于raw 中包含了$，所以导致不会对参数再做处理。从而导致无法获取到请求参数。

**Comment by 2betop** [comment]
目前是这样，crud的 api，如果不主动配置参数，默认会把所有可能的参数自动加进去，但是一旦设置了，就会以用户配置的参数为准，不会多加。所以一旦配置了参数，就得主动把后端需要的参数都配置上。在 url 路径中的变量也算参数。

所以我认为这个不是个问题，使用的时候把需要的参数补上即可。
