### ISSUE TITLE
clearValueOnHidden 配置后不生效

### ISSUE THREAD

**Issue by hotmaycold** [baidu/amis#1595]

**Comment by RickCole21** [comment]
信息太少，没法看

**Comment by nwind** [comment]
补充 schema 再开吧

**Comment by needood** [comment]
用1.5.3 发现不生效
{
                    "type": "input-group",
                    "body": [
                        {
                            "type": "select",
                            "name": "timekind",
                            "options": [
                                {
                                    "label": "时间1",
                                    "value": "1"
                                },
                                {
                                    "label": "时间2",
                                    "value": "2"
                                },
                                {
                                    "label": "时间3",
                                    "value": "3"
                                }
                            ],
                            "value": "1"
                        }, {
                            "type": "input-date-range",
                            "name": "time1",
                            "clearValueOnHidden": true,
                            "hiddenOn": "data.timekind !=='1'",
                        }, {
                            "type": "input-text",
                            "name": "time2",
                            "clearValueOnHidden": true,
                            "hiddenOn": "data.timekind !=='2'",
                        }, {
                            "type": "input-date-range",
                            "name": "time3",
                            "clearValueOnHidden": true,
                            "hiddenOn": "data.timekind !=='3'",
                        }
                    ]
                }
