### ISSUE TITLE
请问发送验证码的倒计时功能该如何实现，能否在文档中加一个例子呢

### ISSUE THREAD

**Issue by mackyuqimack** [baidu/amis#1599]
#### 实现场景：
请问发送验证码的倒计时功能该如何实现，能否在文档中加一个例子呢

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by RickCole21** [comment]
暂时需要自已自定义组件实现
