### ISSUE TITLE
datetime、datetime-range，限制日期失效

### ISSUE THREAD

**Issue by zhumengyue** [baidu/amis#1601]
#### 描述问题：
datetime、datetime-range，设置 minDate、maxDate 后、，直接输入时间，会绕过限制，自动处理为1号的对应时间

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. 粘贴有问题的完整 `amis schema` 代码：
https://codesandbox.io/s/silly-bell-cbx49?file=/src/App.tsx

```
{
  type: "page",
  body: {
    type: "form",
    debug: true,
    controls: [
      {
        type: "datetime-range",
        name: "select",
        label: "日期时间范围",
        minDate: "today"
      },
      {
        type: "datetime",
        format: "YYYY-MM-DD",
        minDate: "today",
        name: "datetime"
      }
    ]
  }
}
```

3. 操作步骤

3.1 点开 datetime 或 datetime-range 组件
3.2 直接修改下方的时间（不用选择日期）
3.3 点击确认
3.4 会发现即使设置了 minDate，但是确认后日期自动变成了 1 号，而不是设置的 minDate

**Comment by summer-wu** [comment]
确实有这个bug，我复现了
![image](https://user-images.githubusercontent.com/2476434/115195650-958d7300-a121-11eb-8f12-3b631b67405e.png)

**Comment by nwind** [comment]
大概是之前的 bug，弄反了
