### ISSUE TITLE
textarea 支持配置 readonly 参数

### ISSUE THREAD

**Issue by 502647092** [baidu/amis#1604]
#### 是否关联于某个问题吗：
textarea 支持配置 readonly参数 目前只能配置disabled 这样子的话 界面就是灰色的了
我只是想阻止他编辑
因为\n换行符等控制字符只能用textarea渲染
没法后端把\n换成<br>

#### 预期的解决方案：
textarea 支持配置 readonly参数

**Comment by nwind** [comment]
tpl 或 static 等几个组件可以设置 wrapperComponent，改成 pre 就行

```
        "type": "static",
        "wrapperComponent": "pre"
```

**Comment by 502647092** [comment]
emm 可以实现功能 但是formitem最好支持一下readonly属性
