### ISSUE TITLE
App 多页应用中如何根据数据动态产生菜单项

### ISSUE THREAD

**Issue by softice70** [baidu/amis#1611]
在项目中，App 多页应用中的左边菜单项希望根据数据动态产生，比如利用each组件

现在的问题是，貌似label属性不支持模板数据，比如在数据中定义了userName，在header中写
    {
      "type": "tpl",
      "tpl": "你好，${userName}",
    }
可以正常显示，然而在pages中如果如下写：
          {
            "label": "${userName}",
            "url": "/themes/xxx",
             ...
          }
则直接在界面上显示${userName}

以上仅仅是尝试验证动态产生菜单的第一步，在pages中如何使用each也没有找到合适的例子，如果有的话，也希望能给出来。

谢谢！

**Comment by 2betop** [comment]
新版本已经支持，请升级版本
