### ISSUE TITLE
Open drawer from picker

### ISSUE THREAD

**Issue by abasse** [baidu/amis#1616]
Is it possible to open a drawer from within the picker? eg. clicking on the value ("b" in the example below)
![image](https://user-images.githubusercontent.com/3475978/110014200-ce64ba80-7d22-11eb-83b0-023fb7d77d73.png)

I would like to show a form in the drawer that allow the user to edit the fields of the "B" relationship entry.

谢谢你的帮助

André

**Comment by 2betop** [comment]
It's not supported right now, but we will consider this feature in 1.1.5

**Comment by abasse** [comment]
That would be awesome!

Another related question, can we use lodash in the initAPI URL field?

**Comment by 2betop** [comment]
no we can't, but we got a lots of filters may be help. eg. ${xxx|url_encode} ${items|unique:name}.

If it's not enough, you can write a filter by your own. like:

```ts
import {registerFilter} from 'amis';

registerFilter('my-replace', (input: string, search: string, repalceWith) =>
  typeof input === 'string' ? input.replace(search, repalceWith) : input
);
```

**Comment by abasse** [comment]
Any chance to get this into 1.1.6?

**Comment by abasse** [comment]
Hey guys, any update on this? It would be great if you could open a form to the related field from the picker.

> Is it possible to open a drawer from within the picker? eg. clicking on the value ("b" in the example below) ![image](https://user-images.githubusercontent.com/3475978/110014200-ce64ba80-7d22-11eb-83b0-023fb7d77d73.png)
> 
> I would like to show a form in the drawer that allow the user to edit the fields of the "B" relationship entry.
> 
> 谢谢你的帮助
> 
> André

Hey guys, any update on this? It would be great if you could open a form to the related field from the picker.

**Comment by abasse** [comment]
@2betop Ok, last try. Could please let me know if this could be added.
