### ISSUE TITLE
缺少对原生HTML标签的支持

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#1623]
#### 是否关联于某个问题吗：
在一些定制页面中，需要控制页面的整体结构，所以需要使用一些div之类的原生标签。
而Container组件是两层div。导致有的时候使用并不是很方便。

所以，是不是可以考虑有限的支持一下某些原生标签呢？

**Comment by nwind** [comment]
最新的 wrapper 已经支持 style，它只有一层
