### ISSUE TITLE
Editor.js support

### ISSUE THREAD

**Issue by abasse** [baidu/amis#1625]
It would be great to get native support for EditorJS - https://editorjs.io
There is also a react version on https://github.com/Jungwoo-An/react-editor-js

I was able to implement EditorJS via a custom component in vanilla JS, but this seems to be a bit hacky.
Your consideration would be very much appreciated.

**Comment by CheshireJCat** [comment]
We have supported and open sourced amis-editor. For details, please see https://github.com/baidu/amis/tree/master/packages/amis-editor
