### ISSUE TITLE
上传文件的参数可否为空？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#163]
file类型的字段attachment，如果上传了文件，则发送到后端的json是attachment:{"value":"xxx","url":"yyy"}；如果没有上传文件，则发送到后端的json根本没有attachment这一项。

能否统一一下，如果前端没有上传文件，则传递到后端的json可以是空值{"value":"","url":""}，这样后端就不用再做判断了，直接接收参数入库就好。现在还要在后端判断一下是否存在attachment的key值，感觉代码比较丑陋。

**Comment by 2betop** [comment]
如果有文件，发送给后端的只能是 form-data/multiple 格式，默认情况下发送给后端的是 application/json  第二个不支持发送文件。
