### ISSUE TITLE
APP多个页面基于hash跳转，CRUD初始化混乱

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#1632]
#### 描述问题：

在APP组件的菜单中，配置了多个page，每个页面都使用完全相同层次结构的curd。除了API和列不同。

jumpTo中使用`location.hash = to`跳转页面。

在切换页面时，会发送两个URL，第一个是schemaApi请求需要渲染的页面。
第二个是初始化CRUD的请求。

问题出在第二个CRUD初始化请求。使用的地址是跳转前的地址，返回数据后，也是渲染的跳转前的表格。

点击查询后，页面恢复。

**Comment by belongwqz** [comment]
相同问题报了好多个，官方似乎不打算解决，不清楚背后什么原因。

**Comment by belongwqz** [comment]
这个问题还没解决就发布1.1.5了么？

**Comment by RickCole21** [comment]
先用 1.1.6-beta.20
