### ISSUE TITLE
File上传文件能否提供一个七牛的例子？

### ISSUE THREAD

**Issue by FatDong1** [baidu/amis#164]
- reciever 默认 /api/upload/file 如果想自己存储，请设置此选项。(PS: 如果想存自己的 bos, 系统配置中可以直接填写自己的 bos 配置。)
- startChunkApi 默认 /api/upload/startChunk 想自己存储时才需要关注。
- chunkApi 默认 /api/upload/chunk 想自己存储时才需要关注。
- finishChunkApi 默认 /api/upload/finishChunk 想自己存储时才需要关注。

对这些字段不太熟悉

**Comment by foxfire881** [comment]
文件上传我昨天刚做完，如果不配置reciever的话默认上传接口就是/api/upload/file，如果配置了reciever就是你指定的后端上传接口。

至于上传时发送了啥数据出去，你点开Chrome F12开发工具或者其他抓包工具看看amis前端发送了啥包出去就知道后端应该怎么接收了。
