### ISSUE TITLE
构建工具链

### ISSUE THREAD

**Issue by hunter-xue** [baidu/amis#1646]
#### 实现场景：
使用SDK模式开发应用时，如果进行打包和构建？

#### 存在的问题：
现有的版本中没有集成构建工具链

#### 当前方案：
自行配置webpack等构建和打包工具。但是这对Low-Code来说，还是不够方便。

```
code here...
```

**Comment by ahnuljz** [comment]
如果没有使用react的话，推荐fis3

**Comment by nwind** [comment]
sdk 的话不需要构建
