### ISSUE TITLE
padding 和margin在div上不工作

### ISSUE THREAD

**Issue by fayeah** [baidu/amis#1647]
#### 描述问题：
尝试使用class来更新样式，但是没有应用到元素上。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. 粘贴有问题的完整 `amis schema` 代码：
```
 <div className="hidden-xs pt-72"></div>
```

pt值可以是其他值

3. 操作步骤
padding，改成margin也不能生效。在浏览器的elements能看到添加到元素上了，但是 styles没有加上` padding-top: 18rem`的样式。

请问是我使用的方式不对吗？还是其他问题，请指教，谢谢啦～

**Comment by bolianlai** [comment]
同样的问题，class显示已经加上了，样式似乎没有生效

**Comment by fayeah** [comment]
> 同样的问题，class显示已经加上了，样式似乎没有生效

请问你有解决方案了吗？我依然存在这个问题。

**Comment by fayeah** [comment]
感谢大佬们的帮助，在如流群里找到了解决办法，关注“_utilities.scss”这个文件，可以直接用这里的样式。
