### ISSUE TITLE
select的clearable属性

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#165]
两个级联的select菜单，都有clearable属性。正常情况下一级菜单选择的option改变后会自动发送一个请求（带上一级菜单选择的option id）拉回级联二级菜单的options。

但是一级菜单点击X clear后，由于option也改变了，所以也会自动发送一个级联二级菜单的请求出去，但此时是没有带上一级菜单的option id的，导致会产生一个报错。

有没有什么办法，一级菜单点击clear时不要自动发送级联请求出去，或者可以自动级联clear二级菜单？

**Comment by foxfire881** [comment]
另外，filter搜索框中的text、select控件长度可以调整吗？试了width属性无效，似乎是固定长度的。

**Comment by RickCole21** [comment]
配置size，支持：xs、sm、md、lg

**Comment by 2betop** [comment]
有没有什么办法，一级菜单点击clear时不要自动发送级联请求出去，或者可以自动级联clear二级菜单？

case 1: 想要接口不发送，你可以加个 api 的sendOn 配置，只有第一个option1 有值时才发送
case2: 你搜一下 formula 看最底下的说明。

**Comment by foxfire881** [comment]
> 配置size，支持：xs、sm、md、lg

试了，确实可以，但选择项太少了，text希望更比xs更短一点，select希望比lg更长一点…… 为啥不支持width属性呢？可控程度更高。

**Comment by RickCole21** [comment]
还可以设置inputClassName，支持：
![image](https://user-images.githubusercontent.com/19327810/63087222-2b9fec00-bf84-11e9-8d9d-418743cde782.png)

**Comment by foxfire881** [comment]
> 还可以设置inputClassName，支持：
> ![image](https://user-images.githubusercontent.com/19327810/63087222-2b9fec00-bf84-11e9-8d9d-418743cde782.png)

谢谢！

**Comment by RickCole21** [comment]
样式相关可以参考这里哈：https://baidu.github.io/amis/docs/style
