### ISSUE TITLE
CRUD的批量操作按钮，是否可以追加一个【是否根据CRUD的选择项来禁用】的属性

### ISSUE THREAD

**Issue by vvelement** [baidu/amis#1650]
CRUD的批量操作按钮，如果没有勾选，则不可用，勾选了则可用。
但有些业务场景，如果没有勾选的话，就直接根据查询条件进行批量操作，所以这个批量操作按钮始终是可以使用的。
是否可以在批量操作按钮的属性上追加一个【是否根据CRUD的选择项来禁用】的属性。

**Comment by CheshireJCat** [comment]
既然不根据选择项来禁用的话，就不必放在批量操作按钮里了，可以在头部工具栏里放个按钮，执行想要的操作，例如
```
{
  "type": "crud",
  "headerToolbar": [
    {
      "label": "按钮",
      "type": "button"
    }
  ]
}
```
