### ISSUE TITLE
关于下拉 Checkbox 选择器

### ISSUE THREAD

**Issue by sky91** [baidu/amis#1670]
想做如图表单，左侧选择器控制右侧表单项显隐，请问左侧的下拉 Checkbox 用什么组件实现？

![表单](https://user-images.githubusercontent.com/4961291/111320625-2647dd80-86a2-11eb-8edf-2b1d6b85cbaf.png)

谢谢~

**Comment by lengqingfeng** [comment]
https://baidu.gitee.io/amis/examples/form/reaction  通过显隐 属性控制     "visibleOn": "data.type == 3",
