### ISSUE TITLE
内部一整套组件可适配切换到antd，便于在已有antd项目中使用，统一组件风格

### ISSUE THREAD

**Issue by gavanx** [baidu/amis#1671]
RT

**Comment by 17** [comment]
有 antd 主题，为啥一定要切换刀 antd ?

**Comment by nwind** [comment]
不打算做，基础的组件主题适配一下就看起来差不多了，而且 amis 大量组件都没有 antd 对应的，amis 的组件数量有 110 多

**Comment by gavanx** [comment]
> 有 antd 主题，为啥一定要切换到 antd ?

antd主题略有差异，集成到已有antd系统里不一致

**Comment by nwind** [comment]
> antd主题略有差异，集成到已有antd系统里不一致

有不一致的地方单独提 issue 吧
