### ISSUE TITLE
Table 在表头有分组的情况下,固定列样式有问题

### ISSUE THREAD

**Issue by The-Only-One33** [baidu/amis#1672]
#### 描述问题：
Table 在表头有分组的情况下,固定列样式有问题

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. 粘贴有问题的完整 `amis schema` 代码：
 {
                "type": "page",
                "body": {
                    "type": "service",
                    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/sample?perPage=5",
                    "className": "w-xxl",
                    "body": [
                        {
                            "type": "table",
                            "source": "$rows",
                            "className": "m-b-none",
                            "columns": [
                                {
                                    "name": "engine",
                                    "label": "Engine",
                                    "groupName": "分组1"
                                },
                                {
                                    "name": "grade",
                                    "label": "Grade",
                                    "groupName": "分组1"
                                },
                                {
                                    "name": "version",
                                    "label": "Version",
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "browser",
                                    "label": "Browser",
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "id",
                                    "label": "ID",
                                    "toggled": false,
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "grade",
                                    "label": "Grade",
                                    "groupName": "分组1"
                                },
                                {
                                    "name": "version",
                                    "label": "Version",
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "browser",
                                    "label": "Browser",
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "id",
                                    "label": "ID",
                                    "toggled": false,
                                    "groupName": "分组2"
                                }, {
                                    "name": "grade",
                                    "label": "Grade",
                                    "groupName": "分组1"
                                },
                                {
                                    "name": "version",
                                    "label": "Version",
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "browser",
                                    "label": "Browser",
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "id",
                                    "label": "ID",
                                    "toggled": false,
                                    "groupName": "分组2"
                                }, {
                                    "name": "grade",
                                    "label": "Grade",
                                    "groupName": "分组1"
                                },
                                {
                                    "name": "version",
                                    "label": "Version",
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "browser",
                                    "label": "Browser",
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "id",
                                    "label": "ID",
                                    "toggled": false,
                                    "groupName": "分组2"
                                }, {
                                    "name": "grade",
                                    "label": "Grade",
                                    "groupName": "分组1"
                                },
                                {
                                    "name": "version",
                                    "label": "Version",
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "browser",
                                    "label": "Browser",
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "id",
                                    "label": "ID",
                                    "toggled": false,
                                    "groupName": "分组2"
                                },
                                {
                                    "name": "platform",
                                    "label": "Platform",
                                    "groupName": "分组2",
                                    "fixed": "right"
                                }
                            ]
                        }
                    ]
                }
            }

3. 操作步骤
分组后固定列样式有问题

**Comment by nwind** [comment]
应该是修了 #2616
