### ISSUE TITLE
子表Table，每一个Cell 鼠标滑过的时候都会触发重绘，影响性能

### ISSUE THREAD

**Issue by zimo888** [baidu/amis#1679]
#### 描述问题：
子表的Table,在鼠标滑过的时候，会触发子表重绘,当子表数据较多的时候，页面明显卡顿。

#### 截图或视频：

https://user-images.githubusercontent.com/4545006/111592551-e7319d80-8803-11eb-85d2-55f3001f8b14.mp4

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 

2. 操作步骤

![image](https://user-images.githubusercontent.com/4545006/111592737-2364fe00-8804-11eb-8312-e00f4c76e3b2.png)

打开React devtools 插件监听重绘。

**Comment by 2betop** [comment]
#7449 调整后将解决此问题

**Comment by 2betop** [comment]
已调整，新版本已无此问题，先关了
