### ISSUE TITLE
filter表单中的date类型format属性无效

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#168]
增删改查时把date类型的format属性设置成"YYYY-MM-DD"是以json方式向后端发送"2019-01-01"格式化后的数据。

但是在filter中的date类型format属性设置成"YYYY-MM-DD"无效，因为它发的不是json，抓包发现是GET形式把时间戳数字参数放在URL中传的 —— 有什么好的解决方案吗？可以不写adapter？

**Comment by 2betop** [comment]
filter 中的 format 应该也是生效的，用法一样。

**Comment by 2betop** [comment]
crud 默认是 get 请求，如果想用 post，需要改一下 api 配置比如： 

```
{
  api: {
    url: "xxx",
    method: "post"
  }
}
```

**Comment by foxfire881** [comment]
跟GET/POST无关吧？filter中的type:submit搜索按钮调用的是crud本身的api，但是搜索时是以GET形式如http://localhost/api/list?page=2&perPage=10&create_time=1564416000往后端发送参数的，不是GET/POST问题，是数据格式的问题，如果是json格式的话确实是格式化后的数据，但是如果放在filter中提交的话还是时间戳的形式。

刚才又试了一遍，确认filter中的format:"YYYY-MM-DD"无效，难道又是js SDK的问题？

**Comment by 2betop** [comment]
你贴一下 你 filter 里面 date 的配置

**Comment by foxfire881** [comment]
{
"name":"dead_time",
"placeholder":"超期时间",
"type":"date",
"format":"YYYY-MM-DD",
"clearable":true
},
{
"label":"搜索"
"type":"submit"
}

**Comment by foxfire881** [comment]
同样的配置，放在curd中是好用的，放在filter中就不行了。

**Comment by foxfire881** [comment]
抱歉，又试了一次filter中的date已经正常可以格式化了，很诡异…… 不知道怎么回事，可能是本地的js缓存没有更新。

**Comment by 2betop** [comment]
可能是之前的结果已经同步到了地址栏，然后你刷新的时候地址栏上的数据又不会更新。so。。

**Comment by foxfire881** [comment]
倒不是这个原因，我把syncLocation关了，地址栏上没有参数，我是F12抓包看后台ajax发送的数据，之前可能是js缓存了没有更新（我是把json配置放在js中的），刚把缓存清空了再来一次就好了。
