### ISSUE TITLE
如何根据data动态设置type，从而实现不同数据类型显示不同组件

### ISSUE THREAD

**Issue by fayeah** [baidu/amis#1681]
一组数据里面可能有图片或视频，想要根据数据的类型，配置不同的type，显示响应的组件，请问如何做到呢？
![image](https://user-images.githubusercontent.com/29644978/111761469-e3247f00-88da-11eb-85a7-418957f01098.png)

以上的`type`里面不可以写变量，否则无法解析渲染器，有办法动态设置吗？

**Comment by fayeah** [comment]
或者不用这种方式，其它方式也可以，是不是代码设计思路还不对？

**Comment by lengqingfeng** [comment]
"visibleOn": "this.type == 1"

**Comment by fayeah** [comment]
> "visibleOn": "this.type == 1"

谢啦～
