### ISSUE TITLE
nav可以添加  按钮，“按钮”再自定义点击事件吗

### ISSUE THREAD

**Issue by StormKennen** [baidu/amis#1686]
![image](https://user-images.githubusercontent.com/62087166/111932134-cb761200-8af7-11eb-8b42-0c0f841baa3d.png)

**Comment by yinan666** [comment]
同问

**Comment by allenve** [comment]
参考：https://aisuda.bce.baidu.com/amis/zh-CN/components/nav?cat=1#%E6%9B%B4%E5%A4%9A%E6%93%8D%E4%BD%9C
