### ISSUE TITLE
值为null，textarea控件会直接显示null，希望为空

### ISSUE THREAD

**Issue by Leonard-Li777** [baidu/amis#169]
![image](https://user-images.githubusercontent.com/16662626/63152169-bee92800-c03d-11e9-9af1-550b790a4c3a.png)

**Comment by foxfire881** [comment]
mapping处理一下试试，不行用tpl也可以

**Comment by foxfire881** [comment]
今天也遇到这个问题了，试了用mapping不行，tpl倒是可以自定义，但得自己写HTML代码渲染控件，又达不到和amis一样的外观效果。看样子只能上adapter了，确实有点重量级了。

**Comment by 2betop** [comment]
等待发布：https://github.com/baidu/amis/commit/374c94d08aadf593394c16e89c273a6e16b6e559

**Comment by 2betop** [comment]
https://github.com/baidu/amis/releases/tag/1.0.1

**Comment by Leonard-Li777** [comment]
强大！
