### ISSUE TITLE
可以通过一个按钮直接更改某个数据域的值吗？

### ISSUE THREAD

**Issue by jessetalk** [baidu/amis#1694]
reload  (xxx?a=b) 的方式来更改不是很适合场景 ，因为不想刷新那个组件。有没有直接更改数据，但不reload的方法吗？

**Comment by icoco** [comment]
同问，比如 主页 按钮 弹出dialog, 输入值，然后更新 主页上的数据项

 貌似是基础问题，不过例子程序没看到类似的

**Comment by nwind** [comment]
onClick 有个例子 https://baidu.gitee.io/amis/zh-CN/components/action#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%82%B9%E5%87%BB%E4%BA%8B%E4%BB%B6

**Comment by lijianmincn** [comment]
终于来了，赞
