### ISSUE TITLE
CRUD，调出“删除”窗口，就会出现下面错误

### ISSUE THREAD

**Issue by TwoPens** [baidu/amis#1695]
react-dom.development.js:88 Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    in Themeable(I18N(Alert))

![image](https://user-images.githubusercontent.com/62087166/112085399-68eb4780-8bc5-11eb-90a5-11cc9e217efa.png)

**Comment by FxPixels** [comment]
我也出现了这个问题，不知道怎么解决

**Comment by nwind** [comment]
官网未复现，估计是没加 Alert 组件到页面中？仔细看文档的示例
