### ISSUE TITLE
可编辑的  树形选择器，支持拖拽吗

### ISSUE THREAD

**Issue by StormKennen** [baidu/amis#1696]
![image](https://user-images.githubusercontent.com/62087166/112085662-e57e2600-8bc5-11eb-8732-833b17f42462.png)

**Comment by lengqingfeng** [comment]
有这么复杂的需求吗，貌似不支持。

**Comment by RickCole21** [comment]
目前不支持

**Comment by CheshireJCat** [comment]
暂不支持
