### ISSUE TITLE
数据链问题

### ISSUE THREAD

**Issue by chenyphaaa** [baidu/amis#1699]
数据链:https://baidu.gitee.io/amis/zh-CN/docs/concepts/datascope-and-datachain#%E6%95%B0%E6%8D%AE%E9%93%BE

如何不去取上层的数据？可以通过类似`__prev`的方法只去本级的数据？没有则不显示

**Comment by RickCole21** [comment]
```
data:{}
```

或者form，combo组件可以配置 `canAccessSuperData:false`

**Comment by chenyphaaa** [comment]
> ```
> data:{}
> ```
> 
> 或者form，combo组件可以配置 `canAccessSuperData:false`

amis版本1.0.17
使用的crud组件，canAccessSuperData:false不生效，在最外层`type:page`配置`data:{}`和在`type:crud`配置`data:{}`都没有生效

**Comment by nwind** [comment]
换个名字吧
