### ISSUE TITLE
images组件放大时，图片src被设置为[object object]

### ISSUE THREAD

**Issue by Akitata** [baidu/amis#1700]
#### 描述问题：
在使用images组件时，设置了enlargeAble属性以支持放大预览，但点击放大后，图片裂开无法显示

#### 截图或视频：
![image](https://user-images.githubusercontent.com/71656615/112270031-1dfc2d80-8cb4-11eb-8d1c-86dca3aae9e1.png)

这个是文档demo的例子，也是裂开的。。

#### 如何复现（请务必完整填写下面内容）：

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
                    "type":"images",
                    "label":"图片内容",
                    "source":"${imageResponseList}",
                    "src":"${imgUrl}",
                    "enlargeAble": true
               },
```

**Comment by xdlove** [comment]
我这边也遇到这个问题了

**Comment by xdlove** [comment]
放大组件好像有点问题
