### ISSUE TITLE
options 的label不支持模板

### ISSUE THREAD

**Issue by nankaidi** [baidu/amis#1701]
#### 描述问题：
请用一段清晰简洁的文字描述问题是什么...

options 文档里些的是label支持模板，但是实际上不支持模板，希望label支持模板，并且能够支持jsx语法

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
是用这个 http://localhost:8888/zh-CN/components/form/select#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8F%9C%E5%8D%95
