### ISSUE TITLE
AMIS无法兼容Vitejs

### ISSUE THREAD

**Issue by chareice** [baidu/amis#1703]
#### 是否关联于某个问题吗：
https://github.com/baidu/amis/blob/26358721096ad279073729a206130834b412b970/src/components/DatePicker.tsx#L17

如上在组件中引入了外部样式，在组件发布之后依旧保留了require样式方法，致使Vitejs无法正常使用amis，

#### 任何附加信息：
![image](https://user-images.githubusercontent.com/1624785/112337952-5a05b180-8cf9-11eb-8031-4895bdf7d44c.png)

**Comment by Ghostdar** [comment]
同样遇到了这个问题

**Comment by agileago** [comment]
+1

**Comment by agileago** [comment]
官方早点出esm版本的 @nwind

**Comment by allenve** [comment]
建议升级到最新版本试试
