### ISSUE TITLE
CRUD的`bulkActions`的items属性能用吗？

### ISSUE THREAD

**Issue by fayeah** [baidu/amis#1712]
bulkActions有选中的功能，我在使用的时候用`selectedItems`可以操作，而 `items`不行，官方文档推荐用`items`。所以想问下`items`可还能用？
![image](https://user-images.githubusercontent.com/29644978/112717858-31183300-8f2a-11eb-8046-285de4b31eaf.png)

**Comment by nwind** [comment]
用 selectedItems 吧，目前看来一开始加载的时候也会运行，导致一直都 disabled 了 @2betop 看看要不要改文档

**Comment by 2betop** [comment]
确实是文档有问题，items 是当前页所有数据，selectedItems 是已选数据。文档已更新

**Comment by ufologist** [comment]
尝试这样才能映射出需要的数据, 使用版本为 `amis@1.7.0`
```json
"data": {
  "orderId": "${selectedItems | json | toJson | pick:orderId | join}"
}
```
