### ISSUE TITLE
CRUD的filter功能，filter参数无法传到API

### ISSUE THREAD

**Issue by fayeah** [baidu/amis#1713]
利用filter功能的时候，如果不使用adaptor，filter的参数可以正常传到API，但是如果使用了adaptor之后，filter无法添加到API的请求参数里面，这种怎么解决呀？

**Comment by RickCole21** [comment]
信息太少

**Comment by fayeah** [comment]
show you the code:

`{
      type: "crud",
      api: {
        method: "get",
        url:'',
        data: {
          page_entries: "${page_entries}",
          page_index: "${page|minus:1}",
        },
        requestAdaptor: function (api: ApiObject) {
          return {
            ...api,
          };
        },
      filter: {
        title: "条件搜索",
        mode: "inline",
        controls: [
          {
            label: "通过关键字搜索",
            type: "text",
            name: "keywords",
            placeholder: "通过关键字搜索",
          },
          {
            label: "用户",
            type: "text",
            name: "xx",
            value: 'xx',
          },
          {
            type: "submit",
            label: "搜索"
          }
        ],
      },
    },`

这里的Filter 里面的值，我点了“搜索”按钮，传不到request里面。

**Comment by fayeah** [comment]
> 信息太少

show you the code:

```
{
      type: "crud",
      api: {
        method: "get",
        url:'',
        data: {
          page_entries: "${page_entries}",
          page_index: "${page|minus:1}",
        },
        requestAdaptor: function (api: ApiObject) {
          return {
            ...api,
          };
        },
      filter: {
        title: "条件搜索",
        mode: "inline",
        controls: [
          {
            label: "通过关键字搜索",
            type: "text",
            name: "keywords",
            placeholder: "通过关键字搜索",
          },
          {
            label: "用户",
            type: "text",
            name: "xx",
            value: 'xx',
          },
          {
            type: "submit",
            label: "搜索"
          }
        ],
      },
    },
```
这里的Filter 里面的值，我点了“搜索”按钮，传不到request里面。

**Comment by RickCole21** [comment]
get请求的话，参数应该拼接在url上了，就是`api.url`

**Comment by fayeah** [comment]
> get请求的话，参数应该拼接在url上了，就是`api.url`

不用`requestAdaptor `是可以拼上去的，用了之后就没了

**Comment by fayeah** [comment]
> get请求的话，参数应该拼接在url上了，就是`api.url`

我找到原因了， 是因为"data"，如果在api里面设置了`data`，那filter 参数就无法自动传到api了，但是我这里data有用的，因为pageIndex需要从0开始，而默认的是从1开始。
