### ISSUE TITLE
如果涉及到更细粒度的交互，推荐写自定义组件吗？

### ISSUE THREAD

**Issue by fayeah** [baidu/amis#1714]
有个需求是在blur之后进行后端校验，查看文档好像没有相关的功能；自己写了一个自定义的组件并用于form当中；

出现这种类似情况，是建议自定义组件还是用其他的方法解决呢？

**Comment by RickCole21** [comment]
好像，是得写自定义组件

**Comment by fayeah** [comment]
> 定义

哈哈 好
