### ISSUE TITLE
select组件添加选择全部option

### ISSUE THREAD

**Issue by lin1005q** [baidu/amis#1716]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

下拉框有一种场景
如果选择a ，查询条件就是a
如果选择b，查询条件就是b
但我们还希望提供**选择全部**的option，这个时候可以没有此查询条件或者 查询条件=全部
。

我使用了adapter做请求参数修改，  但是数据一会在data里面，一会在query里面。有点头疼。

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by RickCole21** [comment]
```
{
  type:"select",
  multiple: true,
  checkAll: true,
  ...
}
```

**Comment by lin1005q** [comment]
这种的话变成多选了。

**Comment by Heming9** [comment]
请问解决了吗, 这个选择全部, 有时候只是想让其作为一个全选标记发给后端, 而不是要把所有选项都发给后端, 如果是自己给下拉多选框加一个'全部'的option, 前端效果就不好
