### ISSUE TITLE
这里可以提需求吗？Table、CURD的列宽、顺序可否自由调整？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#172]
之前用过easyui的框架，Table的列宽可以用鼠标自由拉长缩短的，列的顺序也可以按住鼠标不动拖拽重新排列 —— 这个amis能做到吗？当前CURD的列宽、顺序都是固定的，有点不太好管理。

**Comment by 2betop** [comment]
这个目前不支持，后续可以考虑

**Comment by foxfire881** [comment]
期待~~ 可以参考一下easyui的代码，实现起来应该不难，但是意义很大

**Comment by JackChenLucky** [comment]
> 期待~~ 可以参考一下easyui的代码，实现起来应该不难，但是意义很大

坐等这个功能好上线。

**Comment by nwind** [comment]
已经支持

**Comment by idjerry** [comment]
现在好像只能支持总列数没多少的时候，如果总列数过多横向生成滚动条的时候，这个时候列宽就没法拖拽了
![image](https://user-images.githubusercontent.com/49178286/215409008-11302c05-9304-41eb-95bd-5410883cf08d.png)
