### ISSUE TITLE
CRUD怎么导出全部数据?

### ISSUE THREAD

**Issue by trdmm** [baidu/amis#1723]
自带的导出CSV,EXCEL只能导出当前页的.
如果CRUD表头增加一个按钮,请求下载的接口,还是没用.

有什么方法导出所有数据嘛?

**Comment by lengqingfeng** [comment]
让服务端提供接口api 啊，然后吧api 配置到action 跳转中就可以了

**Comment by nwind** [comment]
目前只能 download 的方式在，这个功能本来也想做，不过还没具体计划

**Comment by mingsanshao** [comment]
csv已经支持全量导出了，excel什么时候能实现呢？

**Comment by nwind** [comment]
已经支持了 https://baidu.gitee.io/amis/zh-CN/components/crud#%E9%80%9A%E8%BF%87-api-%E5%AF%BC%E5%87%BA-excel
