### ISSUE TITLE
代码编辑器增强

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#1727]
#### 是否关联于某个问题吗：
无

#### 预期的解决方案：
代码编辑器editor：

1. 支持tpl表达式
2. 高亮语法支持shell脚本

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
shell 目前就支持，一会补一下文档

**Comment by nwind** [comment]
tpl 是指什么？

**Comment by belongwqz** [comment]
> tpl 是指什么？

就是语言类型可以使用动态变量，比如“${some_param}”这样根据变量动态改变language参数。
