### ISSUE TITLE
JSSDK是否有计划发布离线部署的版本？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#174]
这两天发现在家里写好的代码拿到公司环境下部署跑不起来，调试了好久发现是公司的网络有问题，内网生产环境是封闭的不让访问外网，所以导致调用的云端JSSDK无法访问。请问后续是否有发布离线版JSSDK的计划？（包括那些css、字体等资源）

另外报告一下textarea控件绑定null值会显示“null”字符串的问题，能否调整为""

**Comment by 2betop** [comment]
今天发布正式版本，sdk 其实已经在 beta版本了

**Comment by foxfire881** [comment]
期待~~ 加油！非常看好这个项目

**Comment by 2betop** [comment]
https://github.com/baidu/amis/releases/tag/1.0.1
