### ISSUE TITLE
select 组件 无法正确弹出 msg 错误信息

### ISSUE THREAD

**Issue by renshengzigusheiwusi** [baidu/amis#1746]
![image](https://user-images.githubusercontent.com/79554710/113470172-1a239480-9486-11eb-86e2-ab1752003429.png)
![image](https://user-images.githubusercontent.com/79554710/113470176-20197580-9486-11eb-8b4d-5bc79326864e.png)
经自查 错误出现在 lib/store/formitem.js/ 329行附近 请更正

**Comment by nwind** [comment]
主要是 500 导致的没处理，我们优化一下
