### ISSUE TITLE
combo组合框中的控件如何绑定值？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#175]
这种写法是可以获取data中的create_time值并绑定到create_time控件的：
{
    "name" : "create_time",
    "label" : "创建时间",
    "type" : "static"
},
{
    "name" : "combo1",
    "label"  : "内容",
    "type" : "combo",
    "inline" : true,
    "controls" : [
        {
            "name" : "content",
            "type" : "static",
            "inline" : true
        }
    ]
}

但是把create_time控件放进combo的controls里面就绑定不到data中的create_time值了：
{
    "name" : "combo1",
    "label"  : "内容",
    "type" : "combo",
    "inline" : true,
    "controls" : [
        {
            "name" : "create_time",
            "label" : "创建时间",
            "type" : "static"
        },
        {
            "name" : "content",
            "type" : "static",
            "inline" : true
        }
    ]
}

以上这种写法要如何把data.create_time绑定到combo controls对应的create_time控件去呢？

**Comment by 2betop** [comment]
你发的这个绑定的是 combo1.create_time 如果 combo 设置成可多选 multiple: true 那么对应的就是 

`combo1: [{create_time: xxx}, {create_time: xxx}]`

**Comment by foxfire881** [comment]
谢谢，原来如此，是我用错控件了，把combo换成group就好了。
