### ISSUE TITLE
列表操作栏添加按钮后 整体内容不是居中的

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#1765]
#### 是否关联于某个问题吗：
amis 后面添加按钮后，整体内容不是居中的，antd 是居中的。

#### 预期的解决方案：
希望能用flex 布局居中显示，看起来舒服些

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
antd
![list](http://ww1.sinaimg.cn/large/b383e575ly1gpcgnqo3noj21ey0m2wh5.jpg)
amis
![list](http://ww1.sinaimg.cn/large/b383e575ly1gpcglbp4jxj21600fwjt0.jpg)

**Comment by nwind** [comment]
是说垂直居中？默认都垂直居中也不太合适，主要是按钮高度比较大导致，可以先用 "level": "link" 改成文字按钮
