### ISSUE TITLE
建议将Root改为Entrance，将rootStore改为entranceStore

### ISSUE THREAD

**Issue by summer-wu** [baidu/amis#1778]
## 概述

建议将这几个变量进行改名：
将Root改为Entrance
将RendererStore改名为EntranceStore
将RootStoreContext改为EntranceStoreContext
将rootStore改为entranceStore
将withRootStore改为withEntranceStore

## 动机

为什么要做出这个更改？看下面的代码，正常人都会认为rootStore的类型是RootStore，但实际类型是RendererStore。
![image](https://user-images.githubusercontent.com/2476434/114344400-56e04180-9b92-11eb-846b-65d43d782b1d.png)
这么修改的好处是什么？好处是代码更易读、更易于理解。

**Comment by nwind** [comment]
谢谢建议，预计暂时不改
