### ISSUE TITLE
Grid文档描述了不支持的功能

### ISSUE THREAD

**Issue by summer-wu** [baidu/amis#1779]
#### 描述问题：
Grid组件的文档中说支持offset pull push，但实际上不支持。

#### 截图或视频：
![image](https://user-images.githubusercontent.com/2476434/114356092-ca8a4a80-9ba2-11eb-85ee-8087443d0ed4.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
https://aisuda.github.io/amis-editor-demo

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  type: 'page',
  title: 'page_title',
  body: [
    {
      type: 'grid',
      columns: [
        {
          type: 'tpl',
          tpl: '第一列',
          inline: false,
          xsOffset: 1,
          xsHidden: true,
          xsPull: 3,
          xsPush: 4,
          xs: 2
        },
        {
          type: 'tpl',
          tpl: '第二列',
          inline: false
        }
      ]
    }
  ]
};
```

3. 操作步骤
粘贴如上代码

**Comment by nwind** [comment]
谢啦应该是后来删了
