### ISSUE TITLE
内置组件库文档

### ISSUE THREAD

**Issue by fnll** [baidu/amis#1780]
#### 实现场景：
基于组件库实现自定义渲染器

#### 存在的问题：
请问内置的组件库是否有API及相关用例文档？如果没有文档是否有计划让社区贡献？基于内置组件的自定义渲染器非常需要这个。如果没有的话开发者只能选择第三方组件库，主题功能可能会失效。

**Comment by nwind** [comment]
主要是我们自己老改，很容易造成不向下兼容，还得维护这个 api 的变化，因此目前只推荐有源码阅读能力的用开发者使用，另外自定义组件也能用 props 里的 render 方法来渲染标准组件
