### ISSUE TITLE
多级service下   column 表头重复

### ISSUE THREAD

**Issue by renshengzigusheiwusi** [baidu/amis#1781]
![youdu图片20210412153456](https://user-images.githubusercontent.com/79554710/114357704-a9c2f480-9ba4-11eb-9725-a63eb4547884.png)

暂时不太确定是否是多级service 导致的

**Comment by RickCole21** [comment]
是最新版本吗

**Comment by renshengzigusheiwusi** [comment]
是最新版 
自测中发现  目前使用方式中   通过service 使用 单独使用crud  存在表头重复 如果在 crud 中加个 按钮 就不存在重复 如图 
![youdu图片20210415154612](https://user-images.githubusercontent.com/79554710/114833383-1a1a8180-9e02-11eb-82d1-da95c989c5b8.png)
![youdu图片20210415154847](https://user-images.githubusercontent.com/79554710/114833392-1d157200-9e02-11eb-92ad-d469176b9336.png)

下图 只增加了一个filter 字段

**Comment by renshengzigusheiwusi** [comment]
>=1.1.3有问题 1.1.3以下没问题

**Comment by nwind** [comment]
可能是之前的 affixOffsetTop 问题
