### ISSUE TITLE
editor load problem

### ISSUE THREAD

**Issue by morance** [baidu/amis#1782]
#### 描述问题：
load editor failed because fetch worker found nothing.
#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://user-images.githubusercontent.com/24826592/114360025-29ea5980-9ba7-11eb-9071-eeffe9c98da8.png)

#### 如何复现（请务必完整填写下面内容）：
1. 你是如何使用 amis 的？
yarn add amis -D

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "controls": [
      {
        "type": "editor",
        "name": "editor",
        "label": "编辑器"
      }
    ]
  }
}
```

3. 操作步骤
keep input word

#### 源码定位
![image](https://user-images.githubusercontent.com/24826592/114360500-aaa95580-9ba7-11eb-8d98-32940b44b5c6.png)
which will lead to load /pkg/json document, but the path is empty

#### 解决方案
1. maybe need to put the resource on the path but this is the bad way.
2. cover above window.monacoEnvirment use  monaco provide esm

**Comment by 2betop** [comment]
什么用法？jssdk?还是npm

**Comment by morance** [comment]
> 什么用法？jssdk?还是npm

npm

**Comment by Anonymity94** [comment]
同碰到此问题。

**Comment by nwind** [comment]
补了个文档说明，需要 monaco-editor-webpack-plugin 插件，参考 https://github.com/microsoft/monaco-editor-webpack-plugin
