### ISSUE TITLE
希望可以增加自定义属性

### ISSUE THREAD

**Issue by knight-peter** [baidu/amis#1801]
#### 是否关联于某个问题吗：
希望能够在渲染的组件上增加自定义属性，例如：`data-id="1"`之类的，目前是没办法增加自定义属性。

#### 预期的解决方案：
希望有这种自定义属性，方便拿来当钩子做一些操作。

**Comment by nwind** [comment]
具体是哪个？这个取决于每个组件的实现，有些组件会透传剩余 props 所以支持，但很多都没透传

**Comment by agileago** [comment]
+1

用在权限控制场景， 比如我在某个按钮上面加上  `data-auth-code="admin"` , 然后在页面初始化的时候根据权限，隐藏掉某些按钮或者禁用
