### ISSUE TITLE
字体颜色不生效

### ISSUE THREAD

**Issue by fayeah** [baidu/amis#1807]
#### 描述问题：
想要改变icon的颜色，使用了`className`的方式，但是有些颜色不生效

#### 如何复现（请务必完整填写下面内容）：

1. 粘贴有问题的完整 `amis schema` 代码：
```
{
          "type": "icon",
          "label": "操作",
          "icon": "ellipsis-v",
          "className": "text-gray-100 text-xl"
        }
```
在CRUD里面使用的，typography 的"text-white"是生效的，但是gray相关的都不生效，字体大小也是生效的。

**Comment by nwind** [comment]
需要自己引入 helper.css

**Comment by fayeah** [comment]
> 需要自己引入 helper.css

哦哦，可以了，感谢！
