### ISSUE TITLE
建议删除HocStoreFactory中的scope属性，直接用store.data替代

### ISSUE THREAD

**Issue by summer-wu** [baidu/amis#1813]
#### 描述问题：
建议删除scope属性，改为用store.data替代

#### 截图或视频：
![image](https://user-images.githubusercontent.com/2476434/114990098-c2941880-9eca-11eb-8cec-1f26d5dc36f7.png)

**Comment by summer-wu** [comment]
删掉scope属性后，有些地方数据域继承关系不正确。还需要额外修改几行代码，都位于WithStore.tsx中。
修改的内容：将props.scope替换为props.store.data。
原理：scope实际只是一个别名，直接从store.data中读就可以。
![image](https://user-images.githubusercontent.com/2476434/115828178-ee218080-a43f-11eb-8a28-e9c1fc1c9e76.png)

**Comment by CheshireJCat** [comment]
添加scope属性而不是直接使用store.data可能是为了限定渲染函数使用的数据范围。这样做可以使得数据的管理更加清晰，便于后续的维护和理解。
