### ISSUE TITLE
使用editor组件无法编辑

### ISSUE THREAD

**Issue by yangyubue** [baidu/amis#1814]
#### 描述问题：
使用editor组件无法编辑

#### 截图或视频：
![image](https://user-images.githubusercontent.com/82646204/115001100-fc1e5100-9ed5-11eb-88ba-8f4e17220996.png)
![image](https://user-images.githubusercontent.com/82646204/115001132-04768c00-9ed6-11eb-9e9c-701b3096567f.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm
2. 粘贴有问题的完整 `amis schema` 代码：
    {
        "type": "editor",
        "name": "editor",
        "label": "编辑器",
        "language": "javascript"
      },
                  {
                    "type": "diff-editor",
                    "name": "diff",
                    "label": "Diff-Editor",
                    "diffValue": "hello world",
                    "value": "hello"
                  }

3. 操作步骤
请简单描述一下复现的操作步骤...
页面浏览器打开 编辑区打开无法编辑 控制台报错

**Comment by summer-wu** [comment]
我用在线的编辑器试了下，是可以的运行的。
![image](https://user-images.githubusercontent.com/2476434/115175779-3cf8ae80-a0fe-11eb-8086-00de53827b66.png)

**Comment by yangyubue** [comment]
我是之前用的低版本的 amis无法使用编辑器  然后后续升级到1.1.15 然后就报错了

**Comment by nwind** [comment]
更新一下 typescript 和 tslib 的依赖
