### ISSUE TITLE
amis 当做 UI 库来用时，InputBox 的 onChange 函数问题

### ISSUE THREAD

**Issue by biley** [baidu/amis#1816]
#### 描述问题：

amis 当做 UI 库来用时，InputBox 的 onChange 函数正常情况参数类型为 string；但使用了 clearable 的功能直接 clear 内容时，参数应该是变成了原生的 event 类型

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. 粘贴有问题的完整 `amis schema` 代码：
```
<InputBox
            className="flex-grow"
            type="text"
            value={value}
            onChange={(value) => this.handleChange(value)}
          />
```

3. 操作步骤
输入值后 clear 内容

**Comment by nwind** [comment]
value 放在 state 里参考 https://github.com/baidu/amis/blob/master/examples/components/App.tsx#L403

**Comment by 2betop** [comment]
确实是个拼写错误，已经提交 pr 了 https://github.com/baidu/amis/pull/2854/files
