### ISSUE TITLE
Service 会生成新的数据域还是将数据放到了上层数据域？

### ISSUE THREAD

**Issue by Fnll** [baidu/amis#1821]
#### 实现场景：

在一个表单里有两个 `Select`，一个通过 `Service` 包裹，拉取以`payload`作为约定key的请求。另一个直接读取上层数据域保存的`options`
[复现传送门](https://codesandbox.io/s/amis-2oj7q?fontsize=14&hidenavigation=1&theme=dark)

#### 存在的问题：
下拉菜单展示的选项组完全一致

#### 当前方案：
配置如下：

```
    {
      type: "page",
      data: {
        options: [{ label: "aaaa", value: "aaaa" }]
      },
      body: [
        {
          type: "form",
          controls: [
            {
              type: "service",
              api: {
                method: "get",
                url:
                  "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/getOptions?waitSeconds=1"
              },
              controls: [
                {
                  label: "选项",
                  type: "select",
                  name: "select",
                  source: "${options}"
                }
              ]
            },
            {
              label: "选项",
              type: "select",
              name: "select",
              source: "${options}"
            }
          ]
        }
      ]
    },

```

**Comment by summer-wu** [comment]
代码中有两个Service.tsx，基础ServiceRenderer是不会将数据传递给上级的，但Form中的ServiceRenderer做了特殊处理，会将数据传递给Form组件（见代码中的`formStore.setValues(payload.data);`）

![image](https://user-images.githubusercontent.com/2476434/115183909-4dfdeb80-a10f-11eb-9a8a-f082e54f434e.png)

**Comment by fnll** [comment]
> 代码中有两个Service.tsx，基础ServiceRenderer是不会将数据传递给上级的，但Form中的ServiceRenderer做了特殊处理，会将数据传递给Form组件（见代码中的`formStore.setValues(payload.data);`）
> 
> ![image](https://user-images.githubusercontent.com/2476434/115183909-4dfdeb80-a10f-11eb-9a8a-f082e54f434e.png)

感谢回复。因为需要兼容老协议，我表单里的`select`无法直接使用`api`属性加载远端数据。这里我是用service实现的，感觉配置量会比较多。请问这样的需求一般如何配置？

**Comment by CheshireJCat** [comment]
会产生新的数据域，取数据的时候也是就近原则，详情请查看文档https://baidu.github.io/amis/zh-CN/docs/concepts/datascope-and-datachain#%E6%95%B0%E6%8D%AE%E9%93%BE
