### ISSUE TITLE
仿 Antd 主题下确认弹窗样式错误

### ISSUE THREAD

**Issue by fnll** [baidu/amis#1824]
#### 描述问题：
使用 antd 主题无法正确渲染弹窗

#### 截图或视频：
![image](https://user-images.githubusercontent.com/22774281/115207912-a0023980-a12e-11eb-8a2e-c8c6b20cd09d.png)

#### 如何复现（请务必完整填写下面内容）：
```
import "amis/lib/themes/antd.css";
import { render } from "amis";
import "./styles.css";

export default function App() {
  return render(
    {
      type: "page",
      body: [
        {
          label: "ajax请求",
          type: "button",
          actionType: "ajax",
          confirmText: "确认要发出这个请求？",
          api:
            "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm"
        }
      ]
    },
    {},
    {
      theme: "antd"
    }
  );
}

```

3. 操作步骤
[复现传送门](https://codesandbox.io/s/amis-forked-nw2b8?file=/src/App.js:0-494)

**Comment by summer-wu** [comment]
workaround方法：添加`import "amis/lib/themes/default.css";`

原理：Root组件使用的主题是传入的值，但Modal组件使用的仍然是default主题。

Root组件使用的是antd主题，截图如下：
![image](https://user-images.githubusercontent.com/2476434/115329887-8eb83c00-a1c5-11eb-8f90-d65940e815aa.png)
Modal组件使用的是default主题，截图如下：
![image](https://user-images.githubusercontent.com/2476434/115329911-9d9eee80-a1c5-11eb-8225-29c8bc27a4cf.png)

**Comment by nwind** [comment]
需要引入 AlertComponent 并设置主题，参考 https://codesandbox.io/s/amis-forked-itfjm?file=/src/App.js
