### ISSUE TITLE
jssdk版本bug有没有大佬帮忙维护一下

### ISSUE THREAD

**Issue by 18814865326** [baidu/amis#1829]
#### 实现场景：
问题提了很久了，我也遇到这个问题了，但是没人维护，跪求大佬

#### 存在的问题：
https://github.com/aisuda/amis-admin/issues/75

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
用最新 beta 版本

**Comment by nwind** [comment]
Duplicate of #1619
