### ISSUE TITLE
如何在amis中实现获取全局变量

### ISSUE THREAD

**Issue by s315746262** [baidu/amis#1839]
#### 实现场景：
因为要做前后端分离，所以用户的密钥不能在后端做，只能够通过浏览器cookies来实现，但我发现amis好像不能传全局变量进去，或者是我还不知道怎么用，文档上也没有什么地方可以参考

**Comment by xiahao90** [comment]
https://baidu.gitee.io/amis/zh-CN/docs/types/definitions 看这里小伙

**Comment by s315746262** [comment]
已经在其他文章中找到答案了，但是还有一个问题，就是发现这样写，会不传data过去，这jssdk的fetcher也没有例子，很难看懂
fetcher: function(params){
                    var method = params.method;
                    var url = params.url;
                    return new Promise(function (resolve, reject) {
                        fetch(url, {
                            method: method,
                            headers: new Headers({
                                "Content-Type": "application/json;",
                                "Authorization": accessToken
                            }),
                        }).then(function(res){
                            return res.json();
                        }).then(function(response){
                            resolve({
                                "data": response,
                            });
                        });
                    });
                }

**Comment by chen1tian** [comment]
这个fetcher没处理data啊。我修改了一下：

```
fetcher: function (params) {
    var method = params.method;
    var url = params.url;
    var data = params.data;
    return new Promise(function (resolve, reject) {
        fetch(url, {
            method: method,
            headers: new Headers({
                "Content-Type": "application/json;",
                "Authorization": access_token
            }),
            body: JSON.stringify(data)
        }).then(function (res) {
            return res.json();
        }).then(function (response) {
            resolve({
                "data": response,
            });
        });
    });
}
```
