### ISSUE TITLE
City 城市选择器 extractValue:false模式下未清空所有字段

### ISSUE THREAD

**Issue by hiro0729** [baidu/amis#1853]
#### 描述问题：
City 城市选择器  extractValue:false模式下， 点击X清空任意一个下拉框如“市”，未清空所有字段，“省”的值还存在，
导致保存到后台残留信息

#### 截图或视频：
![image](https://user-images.githubusercontent.com/7811341/115649148-5ba6b180-a359-11eb-8ccd-2cd42d2ed567.png)
![image](https://user-images.githubusercontent.com/7811341/115649199-72e59f00-a359-11eb-9a31-306dc4bc567f.png)
![image](https://user-images.githubusercontent.com/7811341/115649219-7f69f780-a359-11eb-8710-aa011162fcad.png)

#### 如何复现：

1. 你是如何使用 amis 的？
官网示例

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "controls": [
      {
        "name": "city",
        "type": "city",
        "label": "城市",
        "extractValue": false
      }
    ]
  }
}
```

3. 操作步骤
清空市或区选项，对象中只清空了code和当前select的值，前面的select的值还残留

**Comment by CheshireJCat** [comment]
清除的时候只清除当前及子项值，涉及逻辑是这样的，也更符合使用逻辑，没问题
