### ISSUE TITLE
自定义组件传值

### ISSUE THREAD

**Issue by tongluyang** [baidu/amis#186]
请问如何将一个组件A 的值传递给另外一个组件B

我现在知道的是，如果组件A和组件B都是form，那没有问题

那如果其中一个组件或者两个组件都是自定义的，不是form，除了外面套个form外应该怎么做

例如有这么一个场景：

A改变，提交到B，B根据A的值渲染不同的表单内容，B再提交表单内容到C，C进行加工展示

首先A，可以用select或者tree之类的submitOnChange，form上加target，没有问题

然后B，因为B要根据A的值渲染不同的表单，那我想着把B做成一个自定义组件，自定义组件内部根据A的值 通过```renderAmis```再渲染不同的form，那这里有个问题：如果A的target是这个自定义组件的name，这个自定义的组件好像收不到A的值；如果自定义组件上面套个form，A的target为上面form的name，那可以通过form把A的值传递到B中，但这样又引入另外一个问题，B本身渲染的就是一个form，造成了form嵌套

B->C，和上一步类似，C如果不是form，怎么接收B的数据并加工，这一块我更想知道的是，amis的组件有没有直接执行react方法的配置，现在看action的文档，actionType只有枚举的那几种类型

**Comment by 2betop** [comment]
先看看组件间通信： https://baidu.github.io/amis/docs/dev#%E7%BB%84%E4%BB%B6%E9%97%B4%E9%80%9A%E4%BF%A1

**Comment by tongluyang** [comment]
是不是用```send``` ```receive```这些？建议在文档里提一句，之前都不知道有这东西

**Comment by chenzhen1991** [comment]
> 先看看组件间通信： https://baidu.github.io/amis/docs/dev#%E7%BB%84%E4%BB%B6%E9%97%B4%E9%80%9A%E4%BF%A1

地址404 可以再发个显得吗 我也遇到了这个问题  很急迫 谢谢了

**Comment by nwind** [comment]
https://baidu.gitee.io/amis/zh-CN/docs/concepts/linkage，通过数据联动，而不是调用 react 方法
