### ISSUE TITLE
Form中的button调用onBulkChange不生效

### ISSUE THREAD

**Issue by summer-wu** [baidu/amis#1868]
#### 描述问题：
Form中的button调用onBulkChange不生效

#### 截图或视频：
![image](https://user-images.githubusercontent.com/2476434/115849525-870fc600-a457-11eb-9cd0-0f43c8f99b4f.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  type: "button",
  label: "button without name",
  onClick: (e, props) => {
    props.onBulkChange({ user_name: "button without name" });
  }
}
```

3. 操作步骤
复现代码 https://codesandbox.io/s/amis-yanshiwufabulkchange-mwytb?file=/src/App.js

**Comment by CheshireJCat** [comment]
第二个按钮没有配置name
![image](https://github.com/baidu/amis/assets/16409259/fb502a24-e3d3-43bb-afb6-1123b0e69565)
