### ISSUE TITLE
使用demo时遇到问题

### ISSUE THREAD

**Issue by wooooc** [baidu/amis#1869]
**问题1：**
npm安装，使用table时出现重复表头，类名class="a-Table-fixedTop"，去除css后显示如下
```
表格1
Engine
Version
暂无数据
表格1
Engine
Version
```
**问题2：**
本地sdk，调用demo的api无数据报错如下

> Access to XMLHttpRequest at 'https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/sample?perPage=5' from origin 'null' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**盼复，谢谢！**

**Comment by nwind** [comment]
1. 看 https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started#affixoffsettop-number 或 "affixHeader": false
2. 跨域问题，用相对地址
