### ISSUE TITLE
为什么一旦切换页面之后 crud渲染器就出问题，获取的是上一个页面的数据 得刷新一下才可以

### ISSUE THREAD

**Issue by s315746262** [baidu/amis#1872]
用的是jssdk的写法
![image](https://user-images.githubusercontent.com/34090065/115944652-917aa000-a4e9-11eb-9d70-2491f780b3c9.png)
![image](https://user-images.githubusercontent.com/34090065/115944673-a9eaba80-a4e9-11eb-95ea-13d61268edc7.png)
![image](https://user-images.githubusercontent.com/34090065/115944687-c1c23e80-a4e9-11eb-8b1d-d00b171e4e85.png)

**Comment by nwind** [comment]
app 模式吧，用最新 beta 版本，或者新的正式版预计明天发。 Duplicate of #1619

**Comment by s315746262** [comment]
好的，用了新的beta，好了
