### ISSUE TITLE
使用了fetcher之后文件上传不上去了，用的是jssdk

### ISSUE THREAD

**Issue by s315746262** [baidu/amis#1874]
![image](https://user-images.githubusercontent.com/34090065/115949000-402bda00-a504-11eb-910f-7bb78469e343.png)
![image](https://user-images.githubusercontent.com/34090065/115949017-66ea1080-a504-11eb-8b67-6963179e87a7.png)

后端除了文件上传不是用json，其他都是传json数据

**Comment by s315746262** [comment]
把params打印出来，也找不到那个文件在哪
![image](https://user-images.githubusercontent.com/34090065/115950523-4c1c9980-a50e-11eb-8166-ca09912dcbde.png)

**Comment by nwind** [comment]
需要自己构建 formdata，不会的话建议写个 requestAdaptor 来加 header
