### ISSUE TITLE
如何在fetcher指定适配某一批接口或者说能否只定义传一个headers，其他不影响

### ISSUE THREAD

**Issue by s315746262** [baidu/amis#1875]
现在用的是jssdk，发现用了这个fetcher之后，会影响上传文件的接口，导致无法上传，也不知道是什么问题，但是这个headers又是必须要传，所以有什么办法可以只传headers然后又不会影响其他接口，或者说只是上传文件的接口不用这个fetcher适配
![image](https://user-images.githubusercontent.com/34090065/115952981-9ce6bf00-a51b-11eb-8259-8fe18de0a7f4.png)

**Comment by 2betop** [comment]
* url 应该能判断出来这是什么接口
* api 配置的时候，其实可以配置发送适配器，可以把逻辑放到那
* api 也能配置 headers 对象，可以取上下文数据，也可以取 window 或者 localstorage 数据
