### ISSUE TITLE
action类型的组件可否修改react state？

### ISSUE THREAD

**Issue by fayeah** [baidu/amis#1886]
#### 实现场景：
想要通过`visibleOn`来实现edit mode的展示与否，按钮是否可以通过某种方式修改react state，从而改变页面组件的状态呢？

```
const [editMode, setEditMode] = useState(false)

{
    type: "page",
    body: [
      {
        type: "button-toolbar",
        buttons: [
          {
            type: "action",
            actionType: "dialog",
            label: "修改",
            primary: true,
            dialog: {
              title: "弹框标题",
              body: "这是一个弹框"
            }
          }
        ]
      },
      {
        type: "form",
        initApi: initApi,
        api: initApi,
        title: "详情",
        mode: "horizontal",
        actions: [],
        controls: [
          {
            type: 'group',
            controls: [
            ...
          ]
        ],
       visible: !editMode
      },
      {
        type: "form",
        api: "xxx",
        controls: [
          {
            type: "text",
            name: "name",
            label: "姓名："
          }
        ],
        visible: editMode
      }]
  }
```

`action`那个地方有没有可能修改`editMode`这个状态呢？或者要通过什么样的方式来实现`viewMode` 和`editMode`的切换呢？

**Comment by 2betop** [comment]
你说的这个 state 其实是外部的 state 而不是 amis 内部的 state，感觉已经到了 js ui 层面了。可以配置 onClick: () => setState({xxx}) 来修改。

如果是 amis 内部的 state，有个动作倒是能修改比如这个 form 配置个 name: "myForm"

```
{
  type: "button",
  label: "修改",
  actionType: "reload", 
  target: 'myForm?editMode=1'
}
```

**Comment by fayeah** [comment]
> 你说的这个 state 其实是外部的 state 而不是 amis 内部的 state，感觉已经到了 js ui 层面了。可以配置 onClick: () => setState({xxx}) 来修改。
> 
> 如果是 amis 内部的 state，有个动作倒是能修改比如这个 form 配置个 name: "myForm"
> 
> ```
> {
>   type: "button",
>   label: "修改",
>   actionType: "reload", 
>   target: 'myForm?editMode=1'
> }
> ```

学到了，谢谢！

**Comment by Gitwinters1973** [comment]
> 你说的这个 state 其实是外部的 state 而不是 amis 内部的 state，感觉已经到了 js ui 层面了。可以配置 onClick: () => setState({xxx}) 来修改。
> 
> 如果是 amis 内部的 state，有个动作倒是能修改比如这个 form 配置个 name: "myForm"
> 
> ```
> {
>   type: "button",
>   label: "修改",
>   actionType: "reload", 
>   target: 'myForm?editMode=1'
> }
> ```

您好，按照您的方法，在amis配置的按钮上onClick: () => setState({xxx})  ；不能修改主页面（amis外部）中state的值，可否详细说下过程，谢谢
