### ISSUE TITLE
这个框架是否能做一些ifels的判断逻辑

### ISSUE THREAD

**Issue by s315746262** [baidu/amis#1891]
因为添加和修改数据的页面都是一样的，不太想分开两个json页面
![image](https://user-images.githubusercontent.com/34090065/116049055-6db18880-a6a8-11eb-8339-33dbda648beb.png)
像这样的

**Comment by nwind** [comment]
部分属性支持 tpl，这个 title 不太清楚得确认一下

**Comment by 2betop** [comment]
支持的。

"title": "<% if (data.is_edit) { %>编辑<% } else { %>添加<% }%>"

**Comment by 2betop** [comment]
相关文档 https://baidu.gitee.io/amis/zh-CN/docs/concepts/template
