### ISSUE TITLE
location

### ISSUE THREAD

**Issue by githubliujiawei** [baidu/amis#1895]
#### 描述问题：
使用location组件的时候 偶尔页面报错
![报错](https://user-images.githubusercontent.com/21271310/116492864-ed6d6c00-a8cf-11eb-8561-c0a4af219140.png)

**Comment by 2betop** [comment]
麻烦补充一下错误信息？

**Comment by githubliujiawei** [comment]
> 麻烦补充一下错误信息？

![Uploading 报错.png…]()

**Comment by nwind** [comment]
先关了，等后续补充 schema 信息
