### ISSUE TITLE
crud导出的excel没有数据

### ISSUE THREAD

**Issue by 1178615156** [baidu/amis#1899]
#### 描述问题：
crud导出的excel没有数据
#### 截图或视频：

实际的数据:
![image](https://user-images.githubusercontent.com/8329255/116346202-5dbab580-a81c-11eb-9a0b-548e2850bea6.png)

导出的excel,只有表头,和错误的第一列:
![image](https://user-images.githubusercontent.com/8329255/116346315-9490cb80-a81c-11eb-8b56-b34c4692eb59.png)

#### 如何复现（请务必完整填写下面内容）：

```json
{
  "body": [
    {
      "api": "<URL>",
      "headerToolbar": [
        "export-excel"
      ],
      "type": "crud"
    }
  ],
  "data": {
    "user_type": "<TYPE>"
  },
  "name": "service",
  "type": "service"
}
```

1. 你是如何使用 amis 的？
`sdk`
- 由于是直接使用`<script src="https://cdn.jsdelivr.net/npm/amis@beta/sdk/sdk.js"></script>-->`,不能确认正常运行的但是是那个版本
- 尝试了1.1.6版本的sdk`https://github.com/baidu/amis/releases/tag/1.1.6`,问题依旧.

2. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

3. 操作步骤
所有的crud都如此下载的excel不正常

**Comment by 1178615156** [comment]
使用`v1.1.6-beta.19`功能恢复正常了

**Comment by nwind** [comment]
先用 1.1.7-beta.5

**Comment by Lzw2016** [comment]
1.1.7-beta.5 还是有问题

![image](https://user-images.githubusercontent.com/19291563/116521952-312f9800-a907-11eb-9989-454a627c7ea0.png)

**Comment by nwind** [comment]
@Lzw2016 tpl？没复习，就这一列发个完整例子吧，包括返回数据

**Comment by nwind** [comment]
没搞懂，直接去掉 _super 好了

**Comment by lengqingfeng** [comment]
1.1.7 同样的问题

**Comment by nwind** [comment]
试试最新版本如果有复现再开 issue 吧
