### ISSUE TITLE
事件监听 onFinished 

### ISSUE THREAD

**Issue by mingsanshao** [baidu/amis#1906]
#### 描述问题：
在完成批量操作后 没有禁掉 amis 后续的默认行为

#### 截图或视频：
![image](https://user-images.githubusercontent.com/46732461/116384967-f23c0c80-a84a-11eb-9396-9962c6f6704f.png)

#### 如何复现（请务必完整填写下面内容）：
批量编辑或其他批量操作后，页面会默认提转到第一页

1. 你是如何使用 amis 的？
`sdk`

2. 粘贴有问题的完整 `amis schema` 代码：
```
onFinished: values => {
        console.log('form', values);
        return false; // 这样可以禁掉 amis 后续的默认行为
      },
```

3. 操作步骤
1、在分页的非第一页的页面，
2、点击批量操作后弹框是一个表单
3、提交表单，希望停留在当前页面，实际上默认跳转到了第1页。

**Comment by CheshireJCat** [comment]
请使用最新版本尝试
