### ISSUE TITLE
tree 组件无法反选

### ISSUE THREAD

**Issue by biley** [baidu/amis#1907]
#### 是否关联于某个问题吗：请用一段简单清晰的文字描述你的想法是关联于某个问题，
这应该是一种相当常见的使用场景：当我们选中了一个父节点之后，可以取消选中某些子节点。比如当子节点数量很多时，可以先选中父节点，再来取消一些子节点以达到快速选中目标的目的。

当前情况：目前试下来是如果设置了 onlyChildren 为 true，那么选中父节点后可以取消选中子节点。其他情况子节点都会被 disable 掉。

#### 预期的解决方案：
子节点应该是无论何时都可以取消的，如：
![image](https://user-images.githubusercontent.com/15087577/116384622-9f625500-a84a-11eb-9e9d-aeaa1400350e.png)
子节点不是 disable 状态。
取消选中子节点 B-3 后，变成：
![image](https://user-images.githubusercontent.com/15087577/116385091-0c75ea80-a84b-11eb-8038-3e779de14633.png)

这里的表现类似 antd 提供的 treeSelect: https://ant.design/components/tree-select-cn/

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by CheshireJCat** [comment]
这个与 onlyChildren 属性无关，与 cascade 有关，默认禁止子节点反选
> cascade默认为 false，子节点禁止反选，值不包含子节点值，配置"cascade": true，子节点可以反选，值包含父子节点值（1.9.0 之前的版本 cascade 配置为 true 的效果为：选中父节点不默认选中子节点）

详情请参考：

https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-tree#%E9%80%89%E4%B8%AD%E7%88%B6%E8%8A%82%E7%82%B9%E8%87%AA%E5%8A%A8%E9%80%89%E4%B8%AD%E5%AD%90%E8%8A%82%E7%82%B9-%E6%95%B0%E6%8D%AE%E6%98%AF%E5%90%A6%E5%8C%85%E5%90%AB%E7%88%B6%E5%AD%90%E8%8A%82%E7%82%B9%E7%9A%84%E5%80%BC
