### ISSUE TITLE
导出的时候能不能设置一个属性来决定是否导出这一列呢？

### ISSUE THREAD

**Issue by bolianlai** [baidu/amis#1914]
#### 是否关联于某个问题吗：
有些列我只需要导出部分列，并不需要导出所有列，比如我列表列使用了mapping，导出就会出现显示的时HTML代码

#### 预期的解决方案：
在每列中通过一个属性标记是否导出

**Comment by CheshireJCat** [comment]
已支持，参考：https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E5%8F%AA%E5%AF%BC%E5%87%BA%E9%83%A8%E5%88%86%E5%88%97
