### ISSUE TITLE
如何获取select控件的label？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#192]
一个combo组件，里面放了一个text和一个select，目标是当select每次改变时text上自动更新成select选中的label(不是value，value有其他用途），试了直接绑定name、source、value都不行。如何获取select的label呢？
{
                                "type": "combo",
                                "name": "cols",
                                "label": "分类聚合",
                                "multiple": true,
                                "controls": [
                                    {
                                        "name": "col.label",
                                        "type": "text",
                                        "source":"${col}"
                                    },
                                    {
                                        "name": "col",
                                        "type": "select",
                                        "options": [
                                            {"label": "进度", "value": "status"},
                                            {"label": "时间", "value": "tstatus"},
                                            {"label": "科室", "value": "group"},
                                            {"label": "部门", "value": "dept"},
                                        ]
                                    }
                                ]
                            },

**Comment by foxfire881** [comment]
另外，文档中提到 select “多选模式：选中的多个选项的 value 会通过 delimiter 连接起来，否则直接将以数组的形式提交值。” —— 请问这里的“否则”怎么理解，配置哪个参数、设置成什么？当前需要以数组形式提交。
https://baidu.github.io/amis/docs/renderers/Form/Select

**Comment by juqkai** [comment]
额，兄弟你是解决了还是不用这种方式了？给个回复呗
