### ISSUE TITLE
样式例子中"panelClassName": "border-solid border-2 border-blue-500 rounded-xl shadow-lg" 不起作用

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#1923]
#### 描述问题：
使用html+jssdk的方式，1.1.6版本。
运行样式示例中的json，没有得到结果：
panel没有变圆脚。

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://user-images.githubusercontent.com/13453002/116951356-318ab300-acba-11eb-8ed1-2d45eb66f161.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`  1.1.6

2. 粘贴有问题的完整 `amis schema` 代码：
```

{
  "type": "page",
  "body": {
    "type": "form",
    "panelClassName": "border-solid border-2 border-blue-500 rounded-xl  shadow-lg",
    "controls": [
      {
        "type": "text",
        "className": "text-green-700",
        "label": "文本框",
        "name": "text"
      },
      {
        "type": "password",
        "label": "密码",
        "name": "password"
      }
    ]
  }
}

```

3. 操作步骤
使用sdk中index.html,替换其中的json 内容为上述内容。

**Comment by nwind** [comment]
需要引入 helper.css
