### ISSUE TITLE
crud固定表头后表头重复

### ISSUE THREAD

**Issue by ZG1711** [baidu/amis#1924]
#### 描述问题：
固定表格,表头距离页面顶部出现50px的距离,导致出现表头重复的现象

正常情况,没有移动滚动条:
![1620270457(1)](https://user-images.githubusercontent.com/25605653/117236995-85350200-ae5c-11eb-8227-8a93fa9e6464.jpg)
移动滚动条之后:
![1620270507(1)](https://user-images.githubusercontent.com/25605653/117237005-89f9b600-ae5c-11eb-8706-fac7bf0d7b6b.jpg)

#### 如何复现（请务必完整填写下面内容）：

在示例以及amis的编辑器中有头部导航的关系,所以不会出现这情况,单单设置表格,会出现这情况

**Comment by CheshireJCat** [comment]
新版的固定表头实现逻辑已优化
