### ISSUE TITLE
如何获取全局内容 / How to access global context

### ISSUE THREAD

**Issue by Vokinloksar** [baidu/amis#1925]
#### 实现场景：
希望可以获取到全局使用的 locale
Wish could access global used locale

#### 存在的问题：
不知道如何获取 props 中传递的 `locale` 变量 ，当然这里可以通过 `props.data` 额外传入一个 `locales` 字段， 但是这个方式不太优雅，而且这里获取全局变量的场景应该不止这一个， 比如获取 props 或者 env 中传递的内容。 
Don't know the proper way to access global contents like `props` or `env`, though I can pass global locale into `props.data` and access it using data scope, but this would cause extra maintenance and there would be more use case for global contents accessing. 

请问下这里有没有方式可以获取到比如 `props.locale` 或者 `env.theme` 之类的全局内容
Wish to know if there's any proper way to access contents like `props.locale` or `env.theme`, or if there's any other design considerations.

谢谢

**Comment by allenve** [comment]
3.1 开始支持 context： https://aisuda.baidu-int.com/amis/zh-CN/docs/start/getting-started#%E5%88%9D%E5%A7%8B%E5%80%BC
