### ISSUE TITLE
哪个参数是调整chart大小的？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#193]
同样的配置，放在echart里面图很大，放在amis里面就很小了，怎么调大一点呢
![echart](https://user-images.githubusercontent.com/273961/63636118-b62bce00-c69d-11e9-80ee-5236c62f1b9c.PNG)

  
![chart](https://user-images.githubusercontent.com/273961/63636130-d9567d80-c69d-11e9-999c-c3f1606dd53f.PNG)

配置如下：

  {
        $schema: "https://houtai.baidu.com/v2/schemas/page.json#",
        title: "图表示例",
        type: 'page',
        body: [
            {
                type: "form",
                title: "过滤条件",
                target: "chart",
                submitOnInit: true,
                wrapWithPanel: false,
                mode: "inline",
                controls: [
                    {
                        type: "date",
                        label: "开始日期",
                        name: "starttime",
                        value: "-8days",
                        maxDate: "${endtime}",
                        format: "YYYY-MM-DD"
                    },
                    {
                        type: "date",
                        label: "结束日期",
                        name: "endtime",
                        value: "-1days",
                        minDate: "${starttime}",
                        format: "YYYY-MM-DD"
                    },
                    {
                        name: "cols",
                        type: "select",
                        multiple: true,
                        clearable: true,
                        joinValues: false,
                        extractValue: true,
                        options: [
                            {label: "进度", value: "status"},
                            {label: "时间", value: "tstatus"},
                            {label: "责任部门", value: "dept"},
                        ]
                    },
                    {
                        type: "submit",
                        label: "搜索",
                        level: "primary"
                    }
                ],
                actions: []
            },
            {
                type: "divider"
            },
            {
                type: "chart",
                name: "chart",
                initFetch: false,
                api: {
                    url: "/api/pie",
                    method: "post",
                    data: {
                        starttime: "${starttime}",
                        endtime: "${endtime}",
                        cols: "${cols}"
                    }
                }
            }
        ]
    };

**Comment by foxfire881** [comment]
改了sdk.css中的Chart类，从300px改到了600px，图已经变大了。不过有没有公布配置接口出来？给个width、height之类的接口也好呀，不然每次要去改css太不灵活了。

.amis-scope .a-Chart {
  min-height: 600px;
  position: relative;
}

**Comment by foxfire881** [comment]
顺便报告一个bug： Chart图表上面有搜索条件，每次搜索时没有清空原来的图表，而是直接覆盖 —— 这样会导致图错乱。测试样本：环图 https://www.echartsjs.com/examples/editor.html?c=pie-nest

比如第一次搜索时生成2层嵌套环，第二次搜索时目标只生成1个环，但是实际上一次生成的2个环并没有抹掉，重叠覆盖了，很乱。

如下图，第一次加了进度、时间两个维度统计搜索得到2层环：
![1](https://user-images.githubusercontent.com/273961/63639454-c48de000-c6c5-11e9-9f3c-c7a84317762e.PNG)

第二次只加一个进度维度统计，目标是只得到一层环，但实际得到的是下面这样的：
![2](https://user-images.githubusercontent.com/273961/63639474-fc952300-c6c5-11e9-92bf-a62da2e7449b.PNG)

刷新页面，同样条件重来一次只生成一层环，正常情况下应该是这样的：
![3](https://user-images.githubusercontent.com/273961/63639480-159dd400-c6c6-11e9-8487-c907fe6e7db8.PNG)

推测应该是每次生成Chart时没有清空画布，直接在上面覆盖了。建议修复一下，每次生成Chart绘图前，先清空画布。

**Comment by catchonme** [comment]
修改图表的大小，可在与`type: chart` 同级设定`width` 和`height`属性，示例如下
```
"type": "chart",
"width": "100px",
"height": "100px"
```
或者直接配置`style` 属性，[文档](https://baidu.github.io/amis/docs/renderers/Chart) 中有说明
```
"type": "chart",
"style": {
      "width": "100px",
      "height": "100px"
}
```

嵌套的问题，我们这边跟进一下，感谢反馈

**Comment by foxfire881** [comment]
谢谢，不是嵌套的问题，我又试了包括柱形图在内的其他形式的chart，也会出现类似的问题，如果上面有搜索栏时，只有第一次渲染是正常的，第二次再点搜索画出来的图会覆盖，而不是刷新。可能是缓存的问题，或者绘图前少了一步清空画布。排查一下吧~ 谢谢！有结果了更新一下

**Comment by 2betop** [comment]
chart 里面有个属性 `replaceChartOption` 默认是false，设置成 true 试试

**Comment by foxfire881** [comment]
> chart 里面有个属性 `replaceChartOption` 默认是false，设置成 true 试试

试了，好用！看来文档不够全呀，还有好多隐藏参数、隐藏功能没有列出来~ 得遇到问题了上来问。
