### ISSUE TITLE
当前页面的data是否能够赋值？

### ISSUE THREAD

**Issue by s315746262** [baidu/amis#1933]
#### 实现场景：
![image](https://user-images.githubusercontent.com/34090065/117523540-89435a00-afeb-11eb-8c85-898b7270bb6c.png)
比如说这个参数，是否能够在下面的service请求数据之后，赋值进去，然后整个页面都可以调用这个参数呢？

**Comment by allenve** [comment]
参考事件动作的更新数据：https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE
