### ISSUE TITLE
请引出 src\renderers 里的组件，比如Chart，方便第三方进行功能扩展，谢谢！

### ISSUE THREAD

**Issue by softice70** [baidu/amis#1934]
#### 是否关联于某个问题吗：
amis 中 src\components 中的组件都已经引出了，但不是什么原因没有引出src\renderers 中的组件，导致我们希望增强比如Chart的功能时不能方便的从Chart类派生子类。虽然amis是开源的，第三方可以自己引出，但由于 amis-editor 并不开源且依赖 amis ，导致该方案也几乎不可行。

#### 预期的解决方案：
amis 中 src\components 中的组件都已经引出了，就顺便将 src\renderers 中的组件引出，这样大家就可以方便的进行扩展了。

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
可以直接路径引入 amis/lib/renderers
