### ISSUE TITLE
 Dialog 对话框 里面的form表单 部分字段无法通过initApi进行赋值，如下拉，图片；

### ISSUE THREAD

**Issue by nxushichao** [baidu/amis#1937]
#### 描述问题：
 Dialog 对话框 里面的form表单 部分字段无法通过initApi进行赋值，如下拉，图片；Dialog 里面的 Image 组件上传成功后无法通过必填验证。

**Comment by 2betop** [comment]
不能复现，麻烦贴一下 dialog 下面 form 的配置
