### ISSUE TITLE
CRUD为什么有一列是空的？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#194]
官方github上的代码也有一列是空的，试了也不是全选，勾上不勾上似乎没有区别？

![t](https://user-images.githubusercontent.com/273961/63636259-b3ca7380-c69f-11e9-8406-3376d2631f29.PNG)

**Comment by catchonme** [comment]
感谢反馈，我们尽快修复

**Comment by 2betop** [comment]
已修复
