### ISSUE TITLE
在localStorage设置的userName，在service控件中怎样引入这个变量呢？

### ISSUE THREAD

**Issue by sqzhou** [baidu/amis#195]

**Comment by RickCole21** [comment]
visibleOn和hiddenOn等表达式中可以"localStorage.getItem('xxx')"来获取

**Comment by sqzhou** [comment]
data对应的可以吗？

**Comment by sqzhou** [comment]
如果要设置在data应该如何做？

**Comment by sqzhou** [comment]
我本来想在data获取localStorage的值，发现直接用“localStorage.getItem('xxx')”，发现不可以。后来直接用表达式localStorage.getItem('xxx')就可以了。
