### ISSUE TITLE
API中使用了state，当state发生改变时，不能重新发送请求

### ISSUE THREAD

**Issue by fayeah** [baidu/amis#1951]
#### 描述问题：
在使用CRUD组件时，API的url使用到了state，然而当state发生变化时，并没有重新发送请求。

#### 如何复现（请务必完整填写下面内容）：

1. 粘贴有问题的完整 `amis schema` 代码：
```
// crud 组件,xxx 为state值
body: {
  type: "crud",
  syncLocation: false,
  mode: "cards",
  columnsCount: 6,
  api: `${xxx}/data`,  // xxx为state值
  primaryField: "item",
  card: {
    xxx...
  },
}
```

**Comment by nwind** [comment]
只能是 amis 里的变量才能联动，需要 setValues https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA
