### ISSUE TITLE
自定义代码中 props.state.updateData 无效

### ISSUE THREAD

**Issue by YuunYang** [baidu/amis#1959]
#### 描述问题：
在自定义代码中，

#### 截图或视频：
![image](https://user-images.githubusercontent.com/15278220/118098287-48da4680-b406-11eb-8003-d68015029e5b.png)

![image](https://user-images.githubusercontent.com/15278220/118098533-99ea3a80-b406-11eb-8e8f-db9b70a653e7.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  type: 'button',
  label: '确认',
  onClick: (e, props) => {
    const abc2 = props.store.updateData({
      data: '1111111111111',
    });
    console.log(props, abc2);
  },
}
```

3. 操作步骤

**Comment by nwind** [comment]
不要再包一层，使用 scene_id: 2
