### ISSUE TITLE
请问表单如何修改关于网络失败的提示消息？

### ISSUE THREAD

**Issue by gonejack** [baidu/amis#1963]
#### 存在的问题：
![image](https://user-images.githubusercontent.com/2720676/118247660-02541d00-b4d6-11eb-98d0-1f1ca095b0f9.png)

表单在断网的时候会提示此错误，但我并不需要此不正确的提示，请问如何修改这个提示消息？

进一步，开发者能否去掉这一提示，所指的是`未配置跨域CORS`。

**Comment by nwind** [comment]
可以覆盖默认 env 里的 alert
