### ISSUE TITLE
下拉列表值变动如何触发crud数据刷新？

### ISSUE THREAD

**Issue by lin1005q** [baidu/amis#1968]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

crud上方添加了一些输入框（filter），我希望下拉列表值变动后，自动触发crud重新拉取数据。

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

目前，必须在filter中添加一个type=“”submit“的按钮，修改了下拉列表项值后，必须手动点击

**Comment by lengqingfeng** [comment]
"submitOnChange": true
