### ISSUE TITLE
action.fromDialog 无用代码

### ISSUE THREAD

**Issue by morance** [baidu/amis#1969]
#### 描述问题：
dialog 和 drawer中 action触发会判断是否用里面组件的action进行触发， fromDialog 配置无效被清洗了。
#### 截图或视频：
![image](https://user-images.githubusercontent.com/24826592/118453824-3b84cb00-b72a-11eb-899c-3c663e8f43cc.png)

清洗如下：
![image](https://user-images.githubusercontent.com/24826592/118454298-c9f94c80-b72a-11eb-9ac4-792e43c7dae9.png)

#### 如何复现（请务必完整填写下面内容）：
          dialog: {
            title: '确认',
            actions: [{
              "label": "xxxx",
              "actionType": "ajax",
              "primary": true,
              "type": "button",
              close: true,
              "api": {
                method: 'post',
                url: "/xxxxx",
                data: {
                  keys: "${xxxx}"
                }
              }
            },
            {
              "type": "button",
              "actionType": "close",
              "label": "取消"
            }],
            body: {
              type: 'form',
              controls: [ 
                {type:'tpl', tpl: '计算展示东西'}
              ]
            }
          },

1. 你是如何使用 amis 的？
npm

2. 粘贴有问题的完整 `amis schema` 代码：
```
如上
```

3. 操作步骤
按上图配置即可

**Comment by morance** [comment]
i will pleasure to fix it if you need this feature . this feature will reduce the script running time

**Comment by nwind** [comment]
看的真仔细。。可能这个功能不用了 @2betop

**Comment by 2betop** [comment]
是不用了，原来 fromDialog 来避免死循环，后来改成 from: this.$$id 了。 准备删了，https://github.com/baidu/amis/pull/2831
