### ISSUE TITLE
1.1.6 JS SDK CRUD导出excel数据为空白

### ISSUE THREAD

**Issue by Sansnn** [baidu/amis#1978]
1.1.6 JS SDK CRUD导出excel数据为空白

**Comment by 17** [comment]
1.1.6 react 版本同样失效，仅仅能导出部分信息。

**Comment by nwind** [comment]
用最新 beta 或 gitpage 里的 master 版本

**Comment by Sansnn** [comment]
> 用最新beta或gitpage里的master版本

感谢，已解决
