### ISSUE TITLE
session丢失的问题

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#198]
我有一些后端的接口部分用到了session，需要从session中取数据，但amis每次发送到服务端的请求是通过ajax实现的，测试发现有时候会丢session，第一次拉取数据的时候正常，隔一会再拉数据就失败了，测试发现是session id变了。 我的后端已经设置session不超时了，但是前端amis用ajax发送请求如何维持session呢？

**Comment by 2betop** [comment]
你说的这些好像都是浏览器自动完成的，首先设置 cookie 应该是你的接口返回了 set-cookie 这个 header，然后发送请求，这个 cookie 是自动带过去的。session id 变了，说明 cookie 已经过期了，你要检查的是你那个 set-cookie 的 header 里面的过期时间问题。 seesion过期，应该跳转 login，你可以输出一个这样的返回试试

```
{
  "status": 302,
  "url": "/login"
}
```

**Comment by foxfire881** [comment]
谢谢，我再试试，现在不清楚是前端还是后端的问题，我在后端已经设置了session不超时了，网上查了一些资料前端ajax发送请求时也会涉及到一些session失效的问题，所以开case问问情况

https://blog.csdn.net/chaoyangsun/article/details/79648055

刚才检查了一下set-cookie，确实有效期很短只有1秒时间，可能是后端哪里设置错了，我再检查下。

**Comment by 2betop** [comment]
你发的那个是跨域的 case，跨域是有个开关来设置是否携带 cookie，不过，这个已经开了

**Comment by vkiller178** [comment]
> 你说的这些好像都是浏览器自动完成的，首先设置 cookie 应该是你的接口返回了 set-cookie 这个 header，然后发送请求，这个 cookie 是自动带过去的。session id 变了，说明 cookie 已经过期了，你要检查的是你那个 set-cookie 的 header 里面的过期时间问题。 seesion过期，应该跳转 login，你可以输出一个这样的返回试试
> 
> ```
> {
>   "status": 302,
>   "url": "/login"
> }
> ```

我按照示例返回了相同的数据格式：

![image](https://user-images.githubusercontent.com/19320239/111942177-bf954a80-8b0d-11eb-84f2-0cca08aecb33.png)

使用的skd版本：https://cdn.jsdelivr.net/npm/amis@1.1.4/sdk/sdk.js
目前只引用了这个sdk.js，是还需要引入其他js文件吗？
