### ISSUE TITLE
如何导入csv文件到table或crud？

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#1985]
#### 实现场景：
用户需要导入批量的数据。

#### 存在的问题：
使用 文件上传 组件，无法预览。希望用于导入csv，预览没问题后，再提交到后端。

#### 当前方案：
计划通过自定义组件，解析选择的csv文件，生成json数据。但是如何将js代码里生成的json数据传递给指定的crud组件？

**Comment by nwind** [comment]
目前增加了个 input-excel 组件，倒是也能支持 csv，不过主要问题是字段得提前确定

**Comment by ArrNNG** [comment]
@nwind 目前不支持上传csv 了吗？官网示例中无法上传csv格式的文件了
<img width="494" alt="截屏2024-11-08 10 49 39" src="https://github.com/user-attachments/assets/5a6d8d2f-35b7-4f4e-8c83-51bdbe77b0dd">
