### ISSUE TITLE
silentPolling 不生效

### ISSUE THREAD

**Issue by wudiwen** [baidu/amis#1993]
#### 描述问题：
给页面配置 silentPolling: true 还是能看到加载动画（转圈状态）

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://user-images.githubusercontent.com/42435495/119101217-52d5f800-ba4b-11eb-988d-f213d45f5152.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`jssdk`

2. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

3. 操作步骤

- page页面，在body中有一个大表单，表单中有三个组件，select，button，crud
- 每次打开页面会有两个动画效果

**Comment by CheshireJCat** [comment]
可以给 form 配置  loadingConfig 来关闭或者合并到上层，参考https://baidu.github.io/amis/zh-CN/components/spinner#%E5%B1%9E%E6%80%A7%E8%A1%A8
