### ISSUE TITLE
maximum 遇到字符串时错误的提示

### ISSUE THREAD

**Issue by tonglsh** [baidu/amis#1994]
#### 描述问题：
如图，判断数字 ，如果输入的是字符串，会出现不合理的提示

#### 截图或视频：
![image](https://user-images.githubusercontent.com/57531513/119103113-5cf8f600-ba4d-11eb-9fb7-ce24bf72d2c4.png)

#### 如何复现（请务必完整填写下面内容）：
                  validations: {
                      isInt: true,
                      maximum: 100,
                      minimum: 1
                    },
一个字符串直接与数字比较：
‘someStr’ > 0   false
‘someStr’ < 0   false

**Comment by nwind** [comment]
主要是这里需要 parseFloat，按说不应这样用
