### ISSUE TITLE
可以支持Vue的自定义组件吗

### ISSUE THREAD

**Issue by FatDong1** [baidu/amis#20]

**Comment by FatDong1** [comment]
https://github.com/baidu/amis/issues/12

**Comment by RickCole21** [comment]
目前已支持基于 [San](https://baidu.github.io/san/) 开发自定义组件，基于 Vue 的正在开发中

**Comment by 2betop** [comment]
应该说是内部平台已经支持，可以分享下实现思路，其实不难

**Comment by FatDong1** [comment]
期待！
