### ISSUE TITLE
Select怎样动态绑定，获取source返回的列

### ISSUE THREAD

**Issue by mingpeng2005** [baidu/amis#200]
如题

**Comment by RickCole21** [comment]
你意思是数据适配？

**Comment by mingpeng2005** [comment]
如下，返回了一个list，我指定了下拉选项的列；
列表显示正确了，但是选择一行以后，无法把name带到主页面，是不是还缺什么设置。
{
                            name: "order-type",
                            label:"订单类型",
                            type: "select",                            
                            source:"http://localhost:8770/resource-dispatcher/orderType/findAll", 
                            valueField: "id",
                            labelField: "name",                          
                            autoFill:{"order-type": "${name}"},
                            clearable: true,
                            searchable: true,
                            required: true
}

**Comment by 2betop** [comment]
你把 autoFill 删了吧，本来选中后就会把  value 设置给 order-type 然后，这个 autoFill 又设置了一次，而且设置的 name  导致选择关联不上了。  想要获取 name，倒是可以把 autoFill 里面的第一个 key 换个其他表单项的名字。比如 `{type: "hidden", name: "order-name"}`

**Comment by mingpeng2005** [comment]
就是因为value选不上我才用autofill的，去掉后，选择选项后一直是“请选择”

**Comment by 2betop** [comment]
那应该是 labelField 和 valueField 有问题，不要修改这个，把接口改成以下这种格式试试？

```
{
 status: 0,
msg: '',
  data: {
   options: [
    {label: xxx, value: xxxx}
  ]
  }
}
```

或者用接口适配器，适配成这种格式。

**Comment by mingpeng2005** [comment]
试过了，好像不行，目前是不是没有更好的办法了，我看text里面也有这个问题

**Comment by RickCole21** [comment]
试下最新版是否还有问题
