### ISSUE TITLE
CRUD支持点击行/卡片选中整行数据么？是否可以同时设置不显示多选框？

### ISSUE THREAD

**Issue by liuchy73** [baidu/amis#201]
文档和demo里面貌似都没有找到。。。请教。。

**Comment by RickCole21** [comment]
点击行/卡片选中整行数据：试试checkOnItemClick

**Comment by RickCole21** [comment]
不配置bulkactions就不显示多选框了，或者在crud那层配置itemCheckableOn表达式来指定某行是否可选中

**Comment by liuchy73** [comment]
可以了，感谢~~
