### ISSUE TITLE
下载文件的配置按照官方文档写的，后台也按文档配置头

### ISSUE THREAD

**Issue by yangyubue** [baidu/amis#2011]
但是下载总是报错 too many properties to enumrate
![image](https://user-images.githubusercontent.com/82646204/119335692-4a85f300-bcbf-11eb-90b2-be89662ec729.png)
后台：
![image](https://user-images.githubusercontent.com/82646204/119335732-540f5b00-bcbf-11eb-944f-5d84c7d3cd85.png)

**Comment by fayeah** [comment]
> 但是下载总是报错 too many properties to enumrate
> ![image](https://user-images.githubusercontent.com/82646204/119335692-4a85f300-bcbf-11eb-90b2-be89662ec729.png)
> 后台：
> ![image](https://user-images.githubusercontent.com/82646204/119335732-540f5b00-bcbf-11eb-944f-5d84c7d3cd85.png)

hi，请问你后来解决了吗？我也遇到了这个问题，按照文档写的，也是下载不了。

**Comment by nwind** [comment]
可能是之前正则匹配导致的问题，试试新版
