### ISSUE TITLE
复制示例使用无法产生联动

### ISSUE THREAD

**Issue by 673036325** [baidu/amis#2014]
没有任何修改,直接拿到在线AMIS的编辑器里,预览或用1.1.6的版本复制粘贴示例都无法产生联动,UI是正常的,但是文档中的示例是可以的

这是示例地址:
[https://baidu.gitee.io/amis/examples/crud/aside?cat=cat1&page=1](https://baidu.gitee.io/amis/examples/crud/aside?cat=cat1&page=1)

**Comment by 673036325** [comment]
[https://baidu.gitee.io/amis/examples/crud/aside?cat=cat1&page=1](https://baidu.gitee.io/amis/examples/crud/aside?cat=cat1&page=1)

**Comment by 673036325** [comment]
示例不用给crud设置name,复制过来的需要设置

**Comment by 1518648489** [comment]
设置那个名称 我也遇到了同样的问题
