### ISSUE TITLE
csv中文显示乱码问题

### ISSUE THREAD

**Issue by plenjoy** [baidu/amis#2023]
表格中如果字段有中文导出csv时内容为乱码，这个怎么解决？

**Comment by nwind** [comment]
是用什么打开的？Excel？版本和操作系统是啥？感觉估计是因为不支持 utf8 格式，这个没办法，没法转成 gbk，要加载个很大的表

**Comment by plenjoy** [comment]
excel打开，系统win10，应该是不支持utf8造成的，用记事本转成ANSI就不会乱码了。不知道导出时可不可以通过指定字符集的方式解决这个问题。
