### ISSUE TITLE
inputGroup的text大小不能调节，一直占据整行

### ISSUE THREAD

**Issue by tonglsh** [baidu/amis#2026]
#### 截图或视频：
![image](https://user-images.githubusercontent.com/57531513/119631526-901ef900-be42-11eb-8a49-a05fc3acfd1a.png)

#### 如何复现（请务必完整填写下面内容）：

https://baidu.gitee.io/amis/zh-CN/components/form/input-group#%E6%A0%A1%E9%AA%8C
官方文档的例子

**Comment by nwind** [comment]
size 应该设置在 input-group 上，不然会不对齐
