### ISSUE TITLE
data中使用tpl

### ISSUE THREAD

**Issue by chenyphaaa** [baidu/amis#2029]
#### 实现场景：
data中使用tpl

#### 存在的问题：
data中使用${ls:game_id}无法成功，只能在tpl组件中使用，想把localStorage中的内容赋值给初始化数据

#### 当前方案：

```
"data": {
    "game": "${ls:game_id}"
},
```

**Comment by tongji1907** [comment]
localstorage 无法在 data中获取到,是bug

**Comment by nwind** [comment]
这里不支持数据映射，表单里好像可以，可以直接在最外层 render 的时候传入，参考 https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started#%E5%88%9D%E5%A7%8B%E5%80%BC
