### ISSUE TITLE
crud嵌套crud无法通过API获取数据，只能获取父级crud的数据

### ISSUE THREAD

**Issue by liuchy73** [baidu/amis#203]
在crud1里面通过button调起dialog，里面是crud2，配置了crud2的API，调起时会发请求获取数据，但是crud2无法获取API的数据，只能拿到父级curd1的数据，配置了source也没有用，只有一个系统错误的提示，没有具体的报错点，请教下这个该怎么配置呢？

**Comment by 2betop** [comment]
crud2 的 api 接口返回是什么格式？

**Comment by liuchy73** [comment]
> crud2 的 api 接口返回是什么格式？

{"status":0,"msg":"ok","data":
{
"count":"4",
"reports":[]
}
}

**Comment by 2betop** [comment]
应该是这样

```json
{
    "status": 0,
    "msg": "ok",
    "data": {
        "count": "4",
        "items": []
    }
}
```

**Comment by liuchy73** [comment]
可以了，是我写错了，api多了个逗号。。打扰了。。。
