### ISSUE TITLE
markdown组件显示问题   （amis 1.1.7-beta.14版本）

### ISSUE THREAD

**Issue by shuracwf** [baidu/amis#2032]
#### 描述问题：
我使用之前的amis-admin作为模板用fis3构建的，使用amis 1.1.7-beta.14版本，在markdown组件下报以下错误：

[ModJS] Cannot find module `node_modules/markdown-it/node_modules/entities/lib/maps/entities.json`

1. 你是如何使用 amis 的？
`npm` 用fis3构建 

2. 粘贴有问题的完整 `amis schema` 代码：
```
                {
                    "type": "markdown",
                    "value": "# title\n markdown **text**"
                }
```

--我需要在fis-conf.js里增加什么配置项么？

**Comment by nwind** [comment]
应该是 fis-conf.js 里加这个

```
fis.match('markdown-it/**', {
  preprocessor: fis.plugin('js-require-file')
});
```
