### ISSUE TITLE
通过adaptor修改全局变量

### ISSUE THREAD

**Issue by chenyphaaa** [baidu/amis#2038]
#### 实现场景：
想通过接口返回的adaptor修改全局变量，使用的是jssdk

#### 存在的问题：
想通过接口返回的adaptor修改全局变量，使用的是jssdk

#### 当前方案：

```
#index页面
let amisScoped = amis.embed(
      '#root',
      app,     
 {
   "data":{"pid":3}
  },

#子页面中
{
      "type": "form",
      "api": {
        "method": "post",
        "url": "...",
        "adaptor": "console.log(return);\n  想在这个里面修改全局data.pid的值"
 },
```

**Comment by nwind** [comment]
`amisScoped.updateProps({data: {pid: 4}})`

**Comment by lawbc** [comment]
> `amisScoped.updateProps({data: {pid: 4}})`

请问如果data对象有N个属性，但只想修改其中一个属性用这个方法可以吗，我测试后会变成整个data就只有一个属性有值，其他都没有，或者还有没有其他方案
