### ISSUE TITLE
crud中如何自定义footerToolbar中组件的位置？

### ISSUE THREAD

**Issue by liuchy73** [baidu/amis#204]
在crud的footerToolbar中配置了几个button和"pagination", "statistics","switch-per-page"，如何自定义配置其顺序和左右的位置呢？

**Comment by RickCole21** [comment]
数组的顺序就是显示顺序，如果要想靠左靠右，可以这么配对象数组：
```
{
    type: 'pagination',
    align: 'right' // or left
}
```
