### ISSUE TITLE
之前引入sdk样式 import "amis/sdk/sdk.css", 后来引入 amis/lib/themes/default.css 发现略微不同

### ISSUE THREAD

**Issue by hotmaycold** [baidu/amis#2045]
之前引入sdk样式 import "amis/sdk/sdk.css", 后来引入 amis/lib/themes/default.css 发现略微不同
有没有方式引入amis/sdk/sdk.css 且不带amis-scope

**Comment by nwind** [comment]
amis-scope 是为了避免冲突，这个要去掉的话自己删吧
