### ISSUE TITLE
使用向导组件wizard时，actions中的"actionType": "dialog"未生效

### ISSUE THREAD

**Issue by MerryKristina** [baidu/amis#2060]
#### 实现场景：
在使用向导组件wizard时，重写了第二页的底端按钮，其中一个按钮是预览功能，通过获取当前数据域中的数据展示到弹框中

#### 存在的问题：
"actionType": "dialog",未生效，网页提示Uncaught TypeError: Cannot read property 'dialog' of undefined

#### 当前方案：
1、完整结构
![image](https://user-images.githubusercontent.com/31977140/120795121-aa0bba80-c56b-11eb-8739-e15179621471.png)
2、重写的按钮
![image](https://user-images.githubusercontent.com/31977140/120795213-c576c580-c56b-11eb-8feb-48c72e1e1fa0.png)
3、网页报错
![image](https://user-images.githubusercontent.com/31977140/120795416-04a51680-c56c-11eb-96ab-f1be4f3e1837.png)

**Comment by hsm-lv** [comment]
新版没有复现
