### ISSUE TITLE
helper.css.map文件404

### ISSUE THREAD

**Issue by zhongwencool** [baidu/amis#2066]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

引用不到helper.css.map这个文件，自己下载的JSSDK解压也没有这个文件。

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/amis@beta/sdk/helper.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

-------
DevTools failed to load SourceMap: Could not load content for file:///Users/zo/assets/amis/helper.css.map: System error: net::ERR_FILE_NOT_FOUND

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by PavelHank** [comment]
遇到了同样的问题，下载的是 [1.1.7](https://github.com/baidu/amis/releases/tag/1.1.7) 版本的 sdk.tar.gz

**Comment by PavelHank** [comment]
我通过 npm i amis 安装，然后从 node_modules/amis/sdk 中copy出来，然后就可以正常使用了，虽然也会报 helper.css.map 找不到，不过不影响使用

**Comment by nwind** [comment]
忘拷贝 map 文件了，master 里已经修复
