### ISSUE TITLE
crud 中 api 参数问题

### ISSUE THREAD

**Issue by yang2wuhen** [baidu/amis#2070]
在crud中 api请求参数中有一个参数的值为变量同时这个变量的值为后台返回时候,存在不断请求直到这个变量的值不在变化为止

例如:
"type":"crud",
 "api":"getVideosAction?page=${page}&perPage=${perPage}&cursor=${cursor}",

cursor 的值为后端动态返回,这样就会存在前端api接口不断的请求直到cursor的值不在变化

**Comment by allenve** [comment]
通过 这种方式不会监听：api: {url: 'xxx', data: {cursor: ${cursor}}}
