### ISSUE TITLE
时间组件的format 设置无法生效，且和之前的值格式默认为时间戳有了冲突，盼修复。

### ISSUE THREAD

**Issue by hellozqy** [baidu/amis#2074]
#### 描述问题：
时间组件的format 设置无法生效，且和之前的值格式默认为时间戳有了冲突，盼修复。

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://user-images.githubusercontent.com/48118280/121128320-cb1b2680-c85d-11eb-8689-088c65fb7a27.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
    {
      "type": "form",
      "debug": true,
      "controls": [
        {
          "type": "time",
          "label": "创建时间",
          "name": "time",
          "format": "X"
        },
        {
          "type": "tpl",
          "tpl": "${time|date:X:HH\\:mm}"
        }
      ]
    }
  ]
}code here...
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
1.2.0 中应该已经修复了，没复现
