### ISSUE TITLE
如何在最顶层处理url参数

### ISSUE THREAD

**Issue by Leonard-Li777** [baidu/amis#208]
比如curd组件每页显示条数 rows是number格式，当成了url参数后，返回到data里的是string格式
希望有个地方能在顶层拦截做格式转换，如果总是在类似requestAdaptor里做转换有点繁锁！

**Comment by 2betop** [comment]
抱歉才看到，这个确实不好处理，url 的参数肯定是 string 类型，如果发送前想做些格式转换，除了 requestAdaptor 外，我能想到的是扩充 filter https://baidu.github.io/amis/docs/sdk#%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86 然后通过数据映射来满足比如：

```json
{
  "api": {
     "method": "post",
     "url": "xxx",
     "data": {
        "&": "$$",
        "count": "${count | toInt}"
     }
  }
}
```

实际上现在应该可以用 `${count | toJson}` 达到这个效果

**Comment by Leonard-Li777** [comment]
学到了！！
