### ISSUE TITLE
把amis当组件用，使用select组件报错

### ISSUE THREAD

**Issue by ClintLee1101** [baidu/amis#2095]
错误：Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `Select`.
代码：
`import {Button, InputBox, Select } from 'amis/lib/components/index';`
render(){
    const { value, options } =  this.state;
    return(
      <div>
        <div>
          <Select type='select' options={options} />
        </div>
      <div/>
    );
  }

**Comment by nwind** [comment]
例子不完整，预计是能用的
