### ISSUE TITLE
CRUD API 如果含有变量，不能正常扩展 data

### ISSUE THREAD

**Issue by xtao** [baidu/amis#210]
代码位置: https://github.com/baidu/amis/blob/master/src/utils/api.ts#L82
如果配置中有 "$" 就会忽略补充当前 URL 的参数？这是个 bug 么?

**Comment by 2betop** [comment]
故意的，一旦显式的指定参数，就切成了白名单模式，也就是说，你指定了啥发送啥。

**Comment by xtao** [comment]
明白了, 谢谢
