### ISSUE TITLE
stream 文件无法下载

### ISSUE THREAD

**Issue by fayeah** [baidu/amis#2120]
#### 描述问题：
使用`ajax`方式下载文件，能成功获取到resonse，但是没有下载到本地。

#### 截图或视频：

Response Headers：
![image](https://user-images.githubusercontent.com/29644978/122628183-4ba41780-d0e7-11eb-8f31-2afdff399e7e.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
amis@1.1.5

2. 粘贴有问题的完整 `amis schema` 代码：

```
{
  label: "Download",
  actionType: "ajax",
  api: {
    method: 'get',
    url: 'xxx',
    responseType: "blob"
  }
},
```

3. 操作步骤
按钮下载触发API请求。

**Comment by fayeah** [comment]
补充：通过一下代码是可以下载的
```
<a href='xxx' download>Download</a>
```
所以应该不是API的问题，可能是amis这块写法不太对，麻烦帮忙看下，谢谢

**Comment by fayeah** [comment]
额，可以下载了，用的是Link:
```
{
  type: "link",
  href: "xxx",
  body: "Download"
},
```

**Comment by fayeah** [comment]
但是，请问用link的方式下载如何重命名文件名呢？使用a标签的话可以使用download属性：
```
<a href='xxx' download='rename.txt'>Download</a>
```

**Comment by fayeah** [comment]
不过，为什么ajax的方式不工作呢？还是需要ajax的方式下载额。

**Comment by nwind** [comment]
看起来配置是对的，先升级到 1.2 最新 beta 版本试试吧

**Comment by fayeah** [comment]
> 看起来配置是对的，先升级到 1.2 最新 beta 版本试试吧

好的～

**Comment by nwind** [comment]
如果还有问题再开启
