### ISSUE TITLE
${ls:xxxxxlocalStrorageKey.xxxx}取值以后不能当表达式使用么

### ISSUE THREAD

**Issue by ClintLee1101** [baidu/amis#2121]
"headerToolbar": [
      "filter-toggler",
      "bulkActions",
      {
        "label": "添加",
        "type": "button",
        "actionType": "dialog",
        "level": "primary",
        "hiddenOn": "ls:foss-agency-admin.data.token == '330dc6b9-7ced-ea9e-80d8-6611c7e1f35d'",

**Comment by CheshireJCat** [comment]
可以，可能是键名问题，换成不用 - 链接key 实测是可以的
```
localStorage.setItem('fossAgencyAdmin', '{"data": {"token": "hello"}}')
```
```
{
  "type": "page",
  "body": "${ls:fossAgencyAdmin.data.token}",
  "hiddenOn": "${ls:fossAgencyAdmin.data.token === 'hello'}"
}
```
