### ISSUE TITLE
数据链里只能写字符串？我想使用localstorage怎么办

### ISSUE THREAD

**Issue by ClintLee1101** [baidu/amis#2122]
数据链里只能写字符串？我想使用localstorage怎么办

**Comment by lengqingfeng** [comment]
默认取值都是从当前组件上下文数据链中取数据，但是有些数据可能不在这个数据链中，比如有些数据存在全局变量，有的数据存在 localstorage 中。

从 1.1.6 版本开始，支持了一种新的语法如：${window:document.title} 意思是从全局变量中取页面的标题。

目前有以下三种 namespace

window 即全局变量
ls 即 localStorage， 如果值是 json 对象，可以直接当对象用比如：${ls:xxxxxlocalStrorageKey.xxxx}
ss 即 sessionStorage，同上。
