### ISSUE TITLE
Something interesting and internal I want to know ahout AMIS.

### ISSUE THREAD

**Issue by stellar2012wxg** [baidu/amis#2124]
## 概述

大概了解到AMIS的原理是将JSON转化成React组件来做渲染，那能不能直接将JSON转化成React代码？最终呈现的是React工程源码。

1.这样做有没有必要？
2.这样做可不可行? 甚至有没有可能反向？
3.这样做有没有好处？

## 动机

performance improvement & curiosity.

## 示例

None.

## 详细设计

可选。

## 缺陷

我们是不是可以不做这个功能，请考虑：

- 实现这个功能的投入：包括代码的复杂度、代码体积的增加
- 这个功能是不是不需要 amis 提供，比如基于 amis 自己扩展更合适
- 对 amis 现有功能的影响，以及用户进行迁移的成本

## 替代选择

还有其他的方案也可以实现这个功能吗？

## 适配策略

如果我们实现了这个提案，有没有什么办法可以帮助开发者更好地适应这个改动？

**Comment by nwind** [comment]
之前考虑过不太好实现，因为不仅是转成 react 组件就行，还有很多功能依赖 store，所以实现陈本不低，目前不打算做
