### ISSUE TITLE
crud 能否指定固定高度 

### ISSUE THREAD

**Issue by githubliujiawei** [baidu/amis#2125]
#### 是否关联于某个问题吗：
curd能否添加固定高度属性,比如不管是一条数据还是10条数据的时候crud高度都不变,现在是数据少的时候table自动缩短了,分页条也跟着上去了
#### 预期的解决方案：
curd能否添加固定高度属性,数据行数不足的时候撑满指定高度,统一界面

#### 其他可接受方案：
能否添加最小高度或者最大高度属性

**Comment by nwind** [comment]
tableClassName？

**Comment by ztky01** [comment]
使用tableClassName确实能设置高度,但是很难看,即使有一条数据,数据的高度也很高;
附几张图片,是期待的效果
@2betop @nwind 
![Dingtalk_20210817171420](https://user-images.githubusercontent.com/54745508/129701035-78a7d4e1-598d-47b3-8a8d-2f2589cca56e.jpg)
![Dingtalk_20210817171743](https://user-images.githubusercontent.com/54745508/129701066-a8d7f8c2-a95c-45c6-b869-b5762a47bd67.jpg)
![Dingtalk_20210817172011](https://user-images.githubusercontent.com/54745508/129701080-43f13671-501a-427c-8c1e-7e6472b127a9.jpg)
![Dingtalk_20210817172317](https://user-images.githubusercontent.com/54745508/129701096-53729dc8-7bd0-4660-93ca-517a0a295808.jpg)

**Comment by ztky01** [comment]
特别期待这个功能的优化

**Comment by ztky01** [comment]
@2betop 后期会有这方面考虑吗

**Comment by nwind** [comment]
这个自己写 css 挺好加的，我们得想想怎么简化

**Comment by ztky01** [comment]
尝试过自己加css但是不太理想
高度固定后table通过itemActions加的按钮，在各行之间游走时，偏底部的数据按钮就漂移到了原本的位置，没有在本行数据上

**Comment by ztky01** [comment]
也可能我样式写的不对吧

**Comment by ztky01** [comment]
特期待这个功能的到来

**Comment by ztky01** [comment]
特期待这个功能的到来
因为我们这边用户的使用习惯，就像上边的截图一样，每个模块样子都差不多。（其实有点过时不太符合潮流）
查询区域+按钮区域+表格区域（屏幕高度减去查询条件和按钮的剩余全部，滚动条在表格内，随浏览器大小动态计算靠Jquery）

**Comment by ztky01** [comment]
感谢 ~感谢~感谢

**Comment by DadGuo** [comment]
![image](https://user-images.githubusercontent.com/59001670/142368236-f45650b1-6d2a-4d53-9da3-e1d5ffffa639.png)
1.5.0及以上...现在有这个版本吗？

**Comment by ztky01** [comment]
还没有正式发布，快了
