### ISSUE TITLE
LocationPicker 地理位置官网运行报错

### ISSUE THREAD

**Issue by githubliujiawei** [baidu/amis#2128]
#### 描述问题：
如图

#### 截图或视频
![LocationPickerError](https://user-images.githubusercontent.com/21271310/122704831-10d8e580-d287-11eb-97c8-6ed9211557f2.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

3. 操作步骤
就官方文档demo

**Comment by stellar2012wxg** [comment]
allow the browser to get your position...

**Comment by stellar2012wxg** [comment]
make sure the Baidu map shows up...

**Comment by githubliujiawei** [comment]
> 确保百度地图出现...

I know, but if the Google browser location prompt is slower, it will report an error

**Comment by stellar2012wxg** [comment]
understand...

**Comment by nwind** [comment]
未复现有出现再报，后续打算增加别的
