### ISSUE TITLE
后端返回的图片是base64的要怎么展示

### ISSUE THREAD

**Issue by ChenSen5** [baidu/amis#213]
后端返回的图片信息是base64，不是url地址，image组件找不到可以配置支持的地方。

**Comment by RickCole21** [comment]
直接配src呀

**Comment by RickCole21** [comment]
你是form里配image表单项还是直接用image组件

**Comment by ChenSen5** [comment]
> 你是form里配image表单项还是直接用image组件

curd里面使用image 来进行显示图片。

**Comment by RickCole21** [comment]
那直接配src就行

**Comment by RickCole21** [comment]
返回的图片数据字段映射到列就行，img也是支持base64的

**Comment by ChenSen5** [comment]
> 返回的图片数据字段映射到列就行，img也是支持base64的

试了一下，如果内容是：data:image/png;base64,xxxxxx 的可以正常显示，但是没有[data:image/png;base64]前缀，只有base64码的情况下无法显示。
这种可以怎么操作呢？

**Comment by RickCole21** [comment]
后端加或者适配器里加

**Comment by FatDong1** [comment]
```
{
   "name": "aaa",
   "type": "tpl",
   "tpl": "<img src=${data.aaa}>"
}
```
记得tpl也是可以的

**Comment by ChenSen5** [comment]
> {
>    "name": "aaa",
>    "type": "tpl",
>    "tpl": "<img src=<%=data.aaa}%>>"
> }
用这种可以显示
```
            {
                label: "image2",
                name: "image2",
                type: "tpl",
                tpl: "<img src=data:image/jpeg;base64,<%= data.image2 %> >"
             }
```
