### ISSUE TITLE
需求：文档是否对应有一个文档工具

### ISSUE THREAD

**Issue by caiyongmin** [baidu/amis#2130]
#### 预期的解决方案：

RT，最近也在整 json 配置开发这块，要配套有一个文档站点，看到 amis 的文档站点展示形式不错，于是想接入使用。

issue 提问文档是否对应有一个文档工具，可以方便接入使用

**Comment by RickCole21** [comment]
这个目前没有呢

**Comment by caiyongmin** [comment]
> 这个目前没有呢

好的，感谢回复~
