### ISSUE TITLE
Form表单配置body不显示

### ISSUE THREAD

**Issue by edcson** [baidu/amis#2133]
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "body": [
      {
        "type": "input-text",
        "name": "name",
        "label": "姓名："
      },
      {
        "name": "email",
        "type": "input-email",
        "label": "邮箱："
      }
    ]
  }
}

官方文档代码  无法正确显示姓名和邮箱

**Comment by lucky358** [comment]
我也是，macos，使用chorme和safari都不能显示

**Comment by 2betop** [comment]
这是 1.2.x ， 1.1.x 里面不能显示，相关信息请查看： https://baidu.gitee.io/amis/zh-CN/docs/start/1-2-0

**Comment by lucky358** [comment]
> 这是 1.2.x ， 1.1.x 里面不能显示，相关信息请查看： https://baidu.gitee.io/amis/zh-CN/docs/start/1-2-0

我的问题已解决，感谢～
