### ISSUE TITLE
自定义Toast文字失效了

### ISSUE THREAD

**Issue by bluehr** [baidu/amis#2136]
#### 描述问题：
自定义Toast文字无法使用

#### 截图或视频：
![222.gif](https://i.loli.net/2021/06/22/wpugSeU13WYavfq.gif)

#### 如何复现（请务必完整填写下面内容）：
官方文档就可以复现
https://aisuda.github.io/amis-1.1.7/zh-CN/components/action?page=1#%E8%87%AA%E5%AE%9A%E4%B9%89-toast-%E6%96%87%E5%AD%97

1. 你是如何使用 amis 的？
sdk

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "button",
    "label": "ajax 请求",
    "actionType": "ajax",
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "messages": {
      "success": "成功了！欧耶",
      "failed": "失败了呢。。"
    }
  }
}
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lengqingfeng** [comment]
提示信息可以服务端返回，msg字段，表单也会有提示

**Comment by bluehr** [comment]
> 提示信息可以服务端返回，msg字段，表单也会有提示

是的可以服务端返回，我只是看到这个功能失效了，我记得在以前的版本中是可以生效的。
