### ISSUE TITLE
json 配置页面开发生产环境部署如何处理 

### ISSUE THREAD

**Issue by pangxieju** [baidu/amis#2138]
#### 实现场景：
前端页面通过接口返回的 json 来配置页面；
工作流程是开发环境开发页面配置 json 存到数据库；
上线需要导出开发环境配置的数据库 SQL 来更新到生成。

#### 存在的问题：
1、每次上线需要导出 SQL；
2、配置无法管理修改范围（多分支上线，改的范围很难控制）；
3、每次上线存在覆盖（无法回滚）。

#### 当前方案：
暂时每次 导出 SQL 覆盖到生成。

看下大家有什么好的方案来解决这个问题。（数据库版本管理暂不考虑）

**Comment by lengqingfeng** [comment]
为什么不做个版本管理和发布呢

**Comment by 502647092** [comment]
可以把导出的数据上传到Git做版本控制

**Comment by Akitata** [comment]
可以参考amis的商业产品 爱速达，取自己需要的功能，自己开发一套前后端平台

**Comment by nwind** [comment]
取决于自己的需求，和 amis 不相关
