### ISSUE TITLE
The schemaApi property of the Service component returns the array without rendering

### ISSUE THREAD

**Issue by Oscar-ren** [baidu/amis#214]
When the schemaApi return array, the schema property of the Service is null.

And I found the reason https://github.com/baidu/amis/blob/master/src/store/service.ts#L280
```javascript
if (!isEmpty(json.data)) {
     self.schema = json.data;
     self.schemaKey = '' + Date.now();
}
```
isEmpty is here https://github.com/baidu/amis/blob/master/src/utils/helper.ts#L506
```javascript
export function isEmpty(thing: any) {

    if (isObject(thing) && Object.keys(thing).length) {
        return false;
    }

    return true;
}
```
If `fetchSchema` return array, `isEmpty` function will return false, `self.schema` is initial value: null;

Should the Service component support configuring array schema？

I think it should be rendered as normal.

Thanks.

**Comment by 2betop** [comment]
https://github.com/baidu/amis/commit/7f9516f38c087fa56884bdc7e3224dea1b48afa3

待 1.0.2 发布
