### ISSUE TITLE
card的avatar能否支持icon？

### ISSUE THREAD

**Issue by tonglsh** [baidu/amis#2141]
### Avatar 头像 组件提供了丰富的功能，支持icon，style，文字等展示，card的avatar可否内嵌Avatar？

![image](https://user-images.githubusercontent.com/57531513/122929996-2260e100-d39e-11eb-9f0c-fb13f8744e3d.png)
![image](https://user-images.githubusercontent.com/57531513/122930176-50debc00-d39e-11eb-89a2-59e432d3e797.png)

**Comment by user-huage** [comment]
这个需求解决了吗，我也有这种需求
