### ISSUE TITLE
avatar 的icon 想通过上下文动态获取。

### ISSUE THREAD

**Issue by tonglsh** [baidu/amis#2143]
src、text 都支持变量，可以从上下文中动态获取图片或文字，下面的例子中第一个获取到了，而第二个没获取到，因此降级为显示 icon。

**Comment by nwind** [comment]
？补充一下 schema

**Comment by tonglsh** [comment]
您好， @nwind 
我想要这样配置，但现在icon这个关键字不支持从上下文取。
```
{
"data": {
    "icon": "fa fa-server"
  },
  "type": "page",
  "body": {
    "type": "avatar",
    "icon": "${icon}"
  }
}
```

图片和文字是可以从上下文取的
```
{
  "data": {
    "myAvatar": "https://suda.cdn.bcebos.com/images/amis/ai-fake-face.jpg"
  },
  "type": "page",
  "body": [
    {
      "type": "avatar",
      "icon": "fa fa-user",
      "src": "${myAvatar}"
    },
    {
      "type": "avatar",
      "icon": "fa fa-user",
      "src": "${other}"
    }
  ]
}
```

**Comment by tonglsh** [comment]
我看到这段代码里并没有对icon进行额外的解析，仅是作为字符串传入。
amis/src/renderers/Avatar.tsx 
```
  render() {
    let {
      className,
      icon = 'fa fa-user',
      text,
      src,
      fit = 'cover',
      data,
      shape = 'circle',
      size = 40,
      style,
      classnames: cx,
      props
    } = this.props;

    let sizeStyle = {
      height: size,
      width: size,
      lineHeight: size + 'px'
    };

    let avatar = <i className={icon} />;

    if (typeof text === 'string' && text[0] === '$') {
      text = resolveVariable(text, data);
    }

    if (typeof src === 'string' && src[0] === '$') {
      src = resolveVariable(src, data);
    }

    if (text) {
      if (text.length > 2) {
        text = text.substring(0, 2).toUpperCase();
      }
      avatar = <span>{text}</span>;
    }

    if (src) {
      avatar = <img src={src} style={{objectFit: fit}} />;
    }

    return (
      <div
        className={cx('Avatar', className, `Avatar--${shape}`)}
        style={{...sizeStyle, ...style}}
        {...props}
      >
        {avatar}
      </div>
    );
  }
}
```

**Comment by Chen-Wendong** [comment]
现在支持了吗？

`{
    "type": "page",
    "title": "",
    "body": [
        {
            "type": "tabs",
            "tabs": [
                {
                    "title": "选项卡1",
                    "body": [
                        {
                            "type": "tpl",
                            "tpl": "${icon1}",
                            "inline": false,
                            "style": {
                            }
                        }
                    ],
                    "icon": "fa fa-snapchat"
                },
                {
                    "title": "选项卡2",
                    "body": [
                        {
                            "type": "tpl",
                            "tpl": "${icon2}",
                            "inline": false
                        }
                    ],
                    "icon": "${icon2}"
                }
            ]
        }
    ],
    "messages": {
    },
    "regions": [
        "body"
    ],
    "className": "no-border p-none m-none",
    "bodyClassName": "dashboard-pad",
    "name": "server-module",
    "data": {
        "icon1": "fas fa-shield-virus",
        "icon2": "fab fa-unity"
    }
}`

![image](https://user-images.githubusercontent.com/88780174/142833445-c332459e-a549-4d35-b531-d327ae780eab.png)

我测试下还是不行，最新版本的编辑器1.4.2-bate版本！
