### ISSUE TITLE
分支判断，简单计算  等；是不是需要自定义组件才可以？

### ISSUE THREAD

**Issue by mingpeng2005** [baidu/amis#215]
Amis提供的组件，如果需要在里面做逻辑判断的话，例如：分支判断，简单计算  等；是不是需要自定义组件才可以？

**Comment by 2betop** [comment]
主要看要实现什么。

如果是显隐切换，可用不可用切换，有 `visibleOn` 和 `disabledOn` 用表达式来实现。

如果是要基于现有变量计算后得到一个新值，可以用 forumla 来实现
