### ISSUE TITLE
page组件，侧边栏 aside  是否可有隐藏按钮？

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#2156]
#### 是否关联于某个问题吗：
侧边栏太占地方，选择完后就没用了，是否可以隐藏和显示按钮，需要的时候点击打开和隐藏？

**Comment by 2betop** [comment]
https://baidu.gitee.io/amis/zh-CN/components/page#aside-%E5%8F%AF%E8%B0%83%E6%95%B4%E5%AE%BD%E5%BA%A6 新加边栏宽度调整功能
