### ISSUE TITLE
面包屑路径国际化不完全的问题

### ISSUE THREAD

**Issue by gillbates** [baidu/amis#2157]
#### 描述问题：
面包屑路径那，首页是中文。。。

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

![image](https://user-images.githubusercontent.com/783547/123518848-6cb5cb00-d6da-11eb-8e2a-d17fa04899fd.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. 粘贴有问题的完整 `amis schema` 代码：
```
let amisScoped = amis.embed('#root', amisJSON, {"locale": "en-US"}, {"theme": "antd"})
```

已经在locale里面用了英文，并且所有页面标题都是英文。。。
版本：1.1.7

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
咦这个 label 不是你自己控制的？

**Comment by gillbates** [comment]
> 咦这个 label 不是你自己控制的？

不是哦。我的这个页面，因为全是英语的。。源文件里面都没有出现中文过。。。不知道哪里生成出来的。。。

**Comment by gillbates** [comment]
> 咦这个 label 不是你自己控制的？

这个就是简单的用app做个多页面，然后locale设置为英文，就出来了。。。
