### ISSUE TITLE
amis-editor 不稳定

### ISSUE THREAD

**Issue by css-master** [baidu/amis#2160]
我这边使用 amis 的方式是结合 amis-editor 的。

amis 有 bug 还能定位，但是 amis-editor 有问题就没办法。问题在于 amis-editor 要使用的话似乎又跟 amis 的版本有关系，搞得 amis 版本也不好升级。。。。。有什么办法吗？ amis-edior 有考虑开源吗，或者稳定一点。。。我看 amis-editor 周下载量也很少。

**Comment by nwind** [comment]
先等这两天的 1.2 版本对应的编辑器试试，还有问题的话发一下对应的配置和复现方式，amis-editor 目前还没有开源计划
