### ISSUE TITLE
ScopedContext单例问题

### ISSUE THREAD

**Issue by lkjx19812006** [baidu/amis#2169]
#### 描述问题：
ScopedContext 目前是一个全局单例，会导致如下问题
1.每通过JSON render 一个页面，或一个自定义组件的时候，组件内部共用一个ScopedContext。
这样组件之间通讯使用的name就不能重复。导致json配置时受限。

#### 期望
通过 JSON render 一个页面或者组件的时候，希望可以指定当前使用的ScopedContext

**Comment by 2betop** [comment]
ScopedContext 不是全局单例，每个页面都会重新创建一个。另外页面内也没有其他 scope，比如一个 form 是个独立的 scope，一弹框是个独立的 scope。也就是说表单里面的 name 和表单外面的 name 是可以重复的。查找规则是就近查找。

**Comment by lkjx19812006** [comment]
那自定义组件中 采用 scoped.registerComponent(this); 如何才能做到注册到某个scope下

**Comment by lkjx19812006** [comment]
@2betop 有这样一种场景
1.我通过json + amis render 构建一个自定义组件。
2.这个自定义组件中包含了很多原子级自定义组件。
3.他们要实现相互通信已达到数据通信的目的。
4.这样封装完成后的组件，我可能使用到很多地方。
5.但是由于json是确定了，里面的name不会再修改，这样就导致了一个组件中的原子组件动作，会影响到其他组件的原子组件动作（原因是，同一个name this.context.getComponentByName 拿到的组件会重复）

**Comment by 2betop** [comment]
我感觉你是需要一个独立的 scoped，这个组件下面的所有组件注册在这个这个独立的 scope 里面，这样在这里面查找就不会混乱。

注册组件的时候加个参数，参考：https://github.com/baidu/amis/blob/master/src/renderers/Dialog.tsx#L596

**Comment by lkjx19812006** [comment]
刚刚找源码，已经解决了 非常感谢。跟你说的一样，越使用感觉amis越强大
