### ISSUE TITLE
crud-table的select表头筛选在搜狗浏览器无法对齐

### ISSUE THREAD

**Issue by FatDong1** [baidu/amis#217]
![image](https://user-images.githubusercontent.com/22772600/64009101-d3ebae00-cb49-11e9-8a59-09a3c4380c7b.png)

浏览器信息
![image](https://user-images.githubusercontent.com/22772600/64009168-ec5bc880-cb49-11e9-93e0-0c88a3ff2ce7.png)

**Comment by 2betop** [comment]
装了同样的版本但是没有复现出来，能否提供 schema ？

![image](https://user-images.githubusercontent.com/2698393/64500458-d7242e00-d2ef-11e9-938d-faba48414826.png)

**Comment by 2betop** [comment]
已修复，原来复现条件是居左摆不下时居右摆的时候出现的位置错误，已修复：https://github.com/baidu/amis/commit/f2a0f798442c54d93414dc2e5f549607f798121a
