### ISSUE TITLE
visibleOn 是否支持 window ls ss 等数据域

### ISSUE THREAD

**Issue by 502647092** [baidu/amis#2173]
#### 实现场景：
在visibleOn中使用window ls ss等数据

#### 存在的问题：
在tpl中可以正常使用 但是visibleOn等环境中不支持

#### 当前方案：

```
// 登录后保存用户数据到sessionStronge
{
    "type": "tpl",
    "tpl": "${ss:CircleCloudUser.username}(ID: ${ss:CircleCloudUser.id})", 这里正常
    "className": "m-r-sm"
}, {
    "label": "后台",
    "type": "button",
    "level": "primary",
    "actionType": "link",
    "link": "/index/admin",
    "visibleOn": "data.role == 'admin'" <<<< 这里没办法使用ss这些数据
}
```

**Comment by nwind** [comment]
这是 tpl 中的方法，可以在调用 amis render 的时候富裕初始值来实现类似功能，刚补了文档，参考这里 https://github.com/baidu/amis/commit/1b8216e78c9a1022de995ce7d4fc0d5e77d0b3a6

**Comment by 502647092** [comment]
@nwind emm 我的数据不是初始化的时候赋值的
是某些动作的时候 会把数据存到SessionStronge或者localStronge
有办法把数据填充到这里 让visibleOn可以识别嘛

**Comment by nwind** [comment]
这里面能写 javascript，所以可以直接 `localStorage.getItem('xxx')`

**Comment by 502647092** [comment]
> 这里面能写 javascript，所以可以直接 `localStorage.getItem('xxx')`

好的 我试试

**Comment by 2betop** [comment]
这个等 1.2.x 后应该可以支持可以先 form 配置个 data: {"xxx": "${ls:xxx}"} 把 localstorage 里面的数据设置到 form 的数据里面，然后 visibleOn 通过 xxx 来判断。

**Comment by 2betop** [comment]
1.2.0 发布了，可以这么用了

**Comment by 502647092** [comment]
嗯 可以了
