### ISSUE TITLE
amis-editor 能否提供一个 schema 更新的回调

### ISSUE THREAD

**Issue by css-master** [baidu/amis#2187]
假设 schema 写的有问题的话（例如 json 末尾多了个逗号），onChange 事件是不会触发的。但我这边场景还是期望在这个时候能拿到这个错误的 schema，给用户一些提示。

**Comment by 2betop** [comment]
我们要做同样的事情，amis-editor 自己会 cover 这个事情

**Comment by cyboning** [comment]
> 我们要做同样的事情，amis-editor 自己会 cover 这个事情

我来说一下我的场景吧，我这边就是将 editor 作为一个受控组件来使用，点击保存的时候会将 schema 发送到服务端。 现在问题就在于假设用户编写 json，他新增了这样一个片段

```
"api": {
	"method": "post",
	"url": "/xxxxx",
	"headers": {
		"xxx": "xxxx"
	},
},
```
如下图：
![image](https://user-images.githubusercontent.com/34802622/124061438-6d938780-da61-11eb-9293-01168fd605c2.png)

很明显用户写错了，因为 headers 下面多了个逗号，但是我的外层就压根没办法感知 editor 内部的变化，editor 目前也没有提示。

在用户点击我的保存按钮的时候我只能感知到这次的表单和上次保存的表单的 schema 是相同的（因为 onChange 没有触发）， 我如果单纯 diff ，判断两次保存的 schema 是一样的就报错也不太合适，所以期望 editor 能提供一些更强的能力。 或者请问有什么好的建议么？

**Comment by fxwing** [comment]
我本地可以运行 为什么打完包生成好多js文件

**Comment by nwind** [comment]
目前有提示了
