### ISSUE TITLE
如何协助开发amis？

### ISSUE THREAD

**Issue by FatDong1** [baidu/amis#219]
虽然不会react，但想深入了解amis并协助开发这个有意思的项目

**Comment by 2betop** [comment]
哈哈，感谢对这个项目感兴趣，首先你要跑起来，安装 npm 依赖后， npm start 开服务，npm run dev 进入开发模式。

需要掌握的技术栈：

* `typescript` 代码带类型的，可读性要高很多
* `mobx-state-tree` 做数据处理的。
* `react`

然后看下 amis 工作原理 https://baidu.github.io/amis/docs/sdk#%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86 我觉得就可以开发了，任何合理的修改和新功能引入都是受欢迎的。

**Comment by FatDong1** [comment]
嗯嗯好嘞
