### ISSUE TITLE
使用1.2.0-beta.2 AMIS  body渲染表单页失败

### ISSUE THREAD

**Issue by shenliuming** [baidu/amis#2196]
#### 描述问题：
使用示例JSON无法渲染 表单

#### 截图或视频：
![image](https://user-images.githubusercontent.com/26403954/124140975-8f215d00-dabb-11eb-828f-f2ebefe28f06.png)

![image](https://user-images.githubusercontent.com/26403954/124141044-a06a6980-dabb-11eb-9de7-fe49de4b6ae0.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网start
![image](https://user-images.githubusercontent.com/26403954/124141135-bb3cde00-dabb-11eb-9a38-53d9a5c349be.png)

2. 粘贴有问题的完整 `amis schema` 代码：

{
  "type": "page",
  "title": "表单页面",
  "body": [
    {
      "type": "form",
      "mode": "horizontal",
      "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
      "body": [
        {
          "label": "Name",
          "type": "input-text",
          "name": "name"
        },
        {
          "label": "Email",
          "type": "input-email",
          "placeholder": "请输入邮箱地址",
          "name": "email"
        }
      ]
    }
  ]
}

3. 操作步骤

{
  "type": "page",
  "title": "表单页面",
  "body": [
    {
      "type": "form",
      "mode": "horizontal",
      "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
      "body": [
        {
          "label": "Name",
          "type": "input-text",
          "name": "name"
        },
        {
          "label": "Email",
          "type": "input-email",
          "placeholder": "请输入邮箱地址",
          "name": "email"
        }
      ]
    }
  ]
}

**Comment by 2betop** [comment]
你的 amis 还是 1.1.x 吧，1.2.0 正式版本已经发布了，可以试试最新版本

**Comment by shenliuming** [comment]
我用的是1.2.0 昨晚也重新安装了，我发现应该是使用schemaApi渲染的问题。
![image](https://user-images.githubusercontent.com/26403954/124213541-561cd300-db23-11eb-91ad-001b4ac1a09d.png)

**Comment by nwind** [comment]
改成 1.2.x 就好了
