### ISSUE TITLE
显示模式的图片可以支持一下旋转功能么？表格行与其他组件之间的关联可以开发一下么？

### ISSUE THREAD

**Issue by jie04baichi** [baidu/amis#2203]
#### 是否关联于某个问题吗：

1.图片旋转感觉还是很有必要的常用功能啊

2.像平时主表，从表这样，从表根据主表的行数据，显示对应的明细信息，这个在erp管理软件里也是比较常见的模式啊

**Comment by CheshireJCat** [comment]
1. 图片旋转已支持，[用法](https://aisuda.bce.baidu.com/amis/zh-CN/components/image#%E5%B7%A5%E5%85%B7%E6%A0%8F)
2. table 已支持事件动作，可以使用事件动作和其他组件交互
