### ISSUE TITLE
富文本框的图片上传 报网络错误

### ISSUE THREAD

**Issue by edcson** [baidu/amis#2209]
按照个人理解 富文本框的上传图片不应该是上传到这个文本框里面么，为什么会调用API去访问，添加图片到文本框只能输入地址么？

**Comment by nuan1989** [comment]
你让我汗颜. 不调用api, 怎么上传? 传到哪里? 难道等提交表单的时候一起上传? 大图片等个几分钟才能提交完毕表单?

**Comment by edcson** [comment]
富文本的组件有两个功能，1是按照图片地址输入的，2的名字叫做上传  1这个功能输入完图片地址后会显示在富文本框里面，2这个功能是类似于文件打开的方式，选择一张图片，这个时候就默认调用api了， 我的意思是 功能1为什么一定要写地址的方式呢，为什么不能以文件选择的方式打开一张图片然后出现在文本框里面，我是这个意思------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月12日(星期一) 晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] 富文本框的图片上传 报网络错误 (#2209)

**Comment by nwind** [comment]
虽然理论上是可以用 base64 图片，但会导致内容太大，也没法并行下载图片
