### ISSUE TITLE
TypeError: rootStore.addStore is not a function

### ISSUE THREAD

**Issue by SunshineH2** [baidu/amis#222]
按照文档来的，但是写了之后报错TypeError: rootStore.addStore is not a function，不知道是什么原因，react版本16.9.0
![image](https://user-images.githubusercontent.com/31178307/64235997-16d3ca00-cf2c-11e9-8ade-08c6a6fa75e1.png)
![image](https://user-images.githubusercontent.com/31178307/64236011-1d624180-cf2c-11e9-85bf-f08ad7f3f2c4.png)

**Comment by 2betop** [comment]
可能是 react-dom 的版本问题

**Comment by SunshineH2** [comment]
@2betop react-dom也是16.9.0

**Comment by SunshineH2** [comment]
![image](https://user-images.githubusercontent.com/31178307/64250080-cf5b3700-cf47-11e9-9907-5f3eacde63fa.png)

**Comment by 2betop** [comment]
存在多个版本的 react ？

**Comment by SunshineH2** [comment]
@2betop 啥意思？

**Comment by 2betop** [comment]
`npm ls react` 看看结果

**Comment by SunshineH2** [comment]
![image](https://user-images.githubusercontent.com/31178307/64250450-b99a4180-cf48-11e9-8a8c-bdc436755ab1.png)

**Comment by SunshineH2** [comment]
哦，我这个是自己公司的脚手架，然后添加了amis，我看官方文档上的快速开始不是说添加amis之后就可以正常使用的嘛

**Comment by 2betop** [comment]
理论上是可以，那个报错是因为新的 Context API 没支持导致的，但是看你的版本应该是支持了，所以我也不知道是哪都原因了。

**Comment by SunshineH2** [comment]
@2betop 请问如果自己的项目里面用的是less，但是我看amis用的是scss，这样子会导致amis的样式加载不出来吗，我写了个button的样式就没加载出来，或者是npm i amis之后需要做什么处理才能加载出样式吗，我看了下官方文档好像没有这部分的说明

**Comment by 2betop** [comment]
amis/lib/themes/default.css

**Comment by SunshineH2** [comment]
@2betop 请问是什么意思，没有理解，我看了下node_modules下面是有这个文件的

**Comment by SunshineH2** [comment]
能否说的稍微详细些呢

**Comment by 2betop** [comment]
我的意思是，你可以直接引入那个 css 文件啊，不要去管 scss 文件

**Comment by SunshineH2** [comment]
好的，我懂你的意思了，现在都正常了，就是icon显示不出来，
![image](https://user-images.githubusercontent.com/31178307/64338728-064b4e80-d015-11e9-8978-4b19ec94550b.png)
我看了下别的issue，没找到解决问题的方法，请问是什么原因导致的呢icon显示不出来

**Comment by 2betop** [comment]
可能你还需要引入 font-awesome 4.7

**Comment by SunshineH2** [comment]
![image](https://user-images.githubusercontent.com/31178307/64394556-52d07180-d089-11e9-9170-274baec90473.png)
引入了耶，请问还需要在别的地方引入吗

**Comment by SunshineH2** [comment]
噢，可以了，谢谢哈

**Comment by SunshineH2** [comment]
@2betop 我想问一下，amis对于rem的转换是怎么转换的呢，是按照什么规则进行转换的

**Comment by 2betop** [comment]
n/16 同时 head 要设置字体为  16px;

https://github.com/baidu/amis/blob/master/scss/_functions.scss#L32

**Comment by Kellercai** [comment]
@SunshineH2 @2betop 
你好，”rootStore.addStore is not a function“这个问题你是怎么解决的呢？现在项目引入自定义组件库，注册成功了，就是拖拽组件出来后就报错了，如果没有使用formItem这些类来拓展组件就不会报错
