### ISSUE TITLE
快捷编辑quickEdit希望能只提交修改的字段

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#2236]
#### 描述问题：
使用快捷编辑quickEdit的时候 每次只是修改了一次字段，结果全部数据都提交了。
希望能改成修改那个字段就只是提交那个字段
#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. 粘贴有问题的完整 `amis schema` 代码：

3. 操作步骤

**Comment by 2betop** [comment]
这个可以配置 api 的数据体

**Comment by xiahao90** [comment]
@2betop 恕我眼拙
