### ISSUE TITLE
AMIS组件内部自定义，与编辑器结合，实现组件本身的编辑等（希望我描述得清楚）

### ISSUE THREAD

**Issue by stellar2012wxg** [baidu/amis#2241]
## 概述

在AMIS中使用semantic-ui的accordion组件，每个手风琴的内容区能否实现自定制。

## 动机

能否在第三方库和AMIS之间形成标准化接口，实现组件本身的定制。还是组件要从头开发才能实现？这样在AMIS的editor中手风琴的每个内容去就能出现+号，就可以定制其渲染Plain Text还是其他内容。

## 示例

如果提案新增或更改 JSON 配置。

## 详细设计

可选。

## 缺陷

我们是不是可以不做这个功能，请考虑：

- 实现这个功能的投入：包括代码的复杂度、代码体积的增加
- 这个功能是不是不需要 amis 提供，比如基于 amis 自己扩展更合适
- 对 amis 现有功能的影响，以及用户进行迁移的成本

## 替代选择

还有其他的方案也可以实现这个功能吗？

## 适配策略

如果我们实现了这个提案，有没有什么办法可以帮助开发者更好地适应这个改动？

**Comment by nwind** [comment]
可以用自定义组件来实现，里面使用 props.render 方法来渲染 body，参考一下 https://github.com/baidu/amis/blob/master/src/renderers/Flex.tsx，不过编辑器要支持的话还得写个编辑器扩展 https://github.com/aisuda/amis-editor-demo，能实现和内置组件一样的效果，但就是编辑器扩展的文档还有很多待补充

**Comment by stellar2012wxg** [comment]
3q very much!
