### ISSUE TITLE
请求本地api问题

### ISSUE THREAD

**Issue by manguanghui** [baidu/amis#2243]
#### 实现场景：
使用amis请求go语言下的本地api接口

#### 存在的问题：
每次请求，虽然结果返回成功，但是会出现系统错误，不知道如何解决

#### 当前方案：
![image](https://user-images.githubusercontent.com/76045750/124872649-1c9f0880-dff8-11eb-9cb9-faeefa960be1.png)

```
code here...
```

**Comment by 2betop** [comment]
搜 cors 相关的文档

**Comment by nwind** [comment]
最好同域不然问题太多
