### ISSUE TITLE
amis-editor和amis升级之后，不稳定问题

### ISSUE THREAD

**Issue by WangYingYaTou** [baidu/amis#2245]
#### 实现场景：
<img width="588" alt="截屏2021-07-08 下午4 46 25" src="https://user-images.githubusercontent.com/39847179/124891984-0a2eca00-e00c-11eb-8d48-38dc8450a912.png">

#### 存在的问题：
第一个拉进来编辑器的组件，一直会这样报错
拉进来第二个有时候才会正常渲染

**Comment by nwind** [comment]
试试最新版本
