### ISSUE TITLE
amisScoped.getComponentByName   setValues  设置后,组件内容不更新

### ISSUE THREAD

**Issue by elinoxp** [baidu/amis#2248]
amisScoped.getComponentByName('page1.form1').setValues({'name1': 'othername'})
不起作用

**Comment by 2betop** [comment]
版本问题？目前看来是起作用的
![image](https://user-images.githubusercontent.com/2698393/124931295-a79df400-e034-11eb-9440-b4bc45d5fc73.png)

**Comment by elinoxp** [comment]
"amis": "^1.2.0"  版本有问题,之前1.1.7的版本可以的

**Comment by elinoxp** [comment]
let amisJSON = JSON.parse(template);
                    amisJSON.data = node || {};//我现在强制在这里赋值,才起作用
                    self.$nextTick(() => {
                        if (self.$refs["mitemconfig"]) {
                            self.amisScoped = amis.embed(
                                self.$refs["mitemconfig"],
                                amisJSON, {},//这里 {} 赋值也不管用
                                axios.baidu
                            );
                            try {
                                self.amisScoped
                                    .getComponentByName("mpage.mform")
                                    .setValues(node);////这里 赋值也不管用
                            } catch (ex) {}
                        }
                        self.$forceUpdate();
                    });

**Comment by 2betop** [comment]
我那个截图是最新的 1.2.1，你那个 form 可能在 crud 里面？如果是这样，还得加一层。1.2.x 里面， service 和 crud 都变成了独立的空间

**Comment by rumunanfeng** [comment]
想请教下，在React情况下，value值改动了，但是amis组件没有更新，有什么办法强制更新吗？ @2betop
