### ISSUE TITLE
restful接口delete方法一定需要返回吗？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#225]
最近把项目改成用django restframework的restful接口，前端在amis里面配置了delete方法，但是后端返回时只有header里面一个HTTP 204状态，并不会返回给前端json数据（这是后端drf框架保证的，要返回数据只能修改后端框架，动作太大了），然后amis一直提示“Response is empty”错误。 delete一定需要返回吗？

 {
     type: "button",
     icon: "fa fa-times text-danger",
     actionType: "ajax",
     confirmText: "您确认要删除?",
     api: "delete:/api/source/$id"
}

![1](https://user-images.githubusercontent.com/273961/64469698-458ab400-d169-11e9-8196-e240bf51a4fb.PNG)
![2](https://user-images.githubusercontent.com/273961/64469700-46bbe100-d169-11e9-861c-b5b4de3e679d.PNG)
![3](https://user-images.githubusercontent.com/273961/64469701-46bbe100-d169-11e9-93d9-506a57261bcb.PNG)

**Comment by FatDong1** [comment]
配置接口适配器不知道行不行，不行配置fetcher嘛
```
{
  "type": "button",
  "icon": "fa fa-times text-danger",
  "actionType": "ajax",
  "confirmText": "您确认要删除?",
  "api": {
      "method": "delete",
      "url": "/api/source/$id",
      "requestAdaptor": "console.log(api.data)",
      "adaptor": "payload.data={}; return payload"
  }
} 
```

**Comment by foxfire881** [comment]
> 配置接口适配器不知道行不行，不行就配置fetcher嘛
> 
>       "adaptor": "payload.data={}; return payload"

试过了，这方法不行，adaptor做接口转换首先要有payload.data存在才行，但是delete方法时服务端根本就没有payload返回，就只返回一个HTTP 204状态，没有response，更没有payload和data产生，前端的adaptor没用

**Comment by foxfire881** [comment]
看了sdk源代码，这里检查只要没有data就抛错了。事实上根据HTTP协议标准，delete成功的话返回204状态就已经代表删除成功了，204状态本身就代表没有content内容也不会返回content内容（即使给content强制赋值让它返回，HTTP协议只要检测到是204状态，也会忽略content的赋值），所以不可能有payload和data。django framework框架是严格按照HTTP协议标准返回的204状态，应该是amis没有适配HTTP标准协议，delete了就不需要返回payload和data了，就靠HTTP状态码就能判断正常或异常了。

```
function n(t) {
        var e = t.data;
        if (!e) throw new Error("Response is empty!");
        ...
    }

```


另外附上HTTP 204状态码的定义：
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/204



204 No Content
服务器成功处理了请求，但不需要返回任何实体内容，并且希望返回更新了的元信息。响应可能通过实体头部的形式，返回新的或更新后的元信息。如果存在这些头部信息，则应当与所请求的变量相呼应。如果客户端是浏览器的话，那么用户浏览器应保留发送了该请求的页面，而不产生任何文档视图上的变化，即使按照规范新的或更新后的元信息应当被应用到用户浏览器活动视图中的文档。由于204响应被禁止包含任何消息体，因此它始终以消息头后的第一个空行结尾。

**HTTP协议中 204 No Content 成功状态响应码表示目前请求成功，但客户端不需要更新其现有页面。**204 响应默认是可以被缓存的。在响应中需要包含头信息 ETag。

使用惯例是，在 PUT 请求中进行资源更新，但是不需要改变当前展示给用户的页面，那么返回 204 No Content。如果新创建了资源，那么返回 201 Created 。如果页面需要更新以反映更新后的资源，那么需要返回 200 。

**Comment by foxfire881** [comment]
希望适配一下HTTP 204状态的判断，不然后端要写大量代码去适配amis会很麻烦，况且后端本来就是标准restful接口，按照规范DELETE方法返回的也是204状态，反而是amis非要强制delete方法返回一个json data会比较奇怪（都delete了，哪来的data？）要修改rest framework框架返回200或其他状态既麻烦又不太合适。如果amis前端适配了204状态的判断，后端rest framework框架几乎不用改动任何代码就可以兼容delete方法了。

**Comment by foxfire881** [comment]
覆盖重写了drf框架的部分代码，这个问题已经解决了（强制delete返回http 200不是204了），不过还是期待能够处理一下204的问题。

**Comment by 2betop** [comment]
主要是 amis 只认 json response，fetcher 里面加一层识别，转成 amis 认得 json reponse 其实就够了

**Comment by foxfire881** [comment]
主要是对象种类如果多起来的话，每种类型的delete都要加fetcher，太累了哇~ 这种标准的东西最好能写在统一的框架里面，这样调用起来就省事了

**Comment by 2betop** [comment]
fetcher 是统一的哈，不是说的api单独适配器。
