### ISSUE TITLE
api不支持options、head、patch等方法？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#226]
restful接口有很多种，光get/post/put/delete四个不够用呀~ 拉取select的选项时希望扩展一个options方法，结果发现在chrome中报错说什么同源策略之类的问题，明明就是在同一个站点下面，为什么还涉及到同源问题呢？直接用fiddler抓包发options请求到后端倒是没问题可以拉取数据，前端amis配成下面这样就会报错，啥原因呢？

{
                                name: "source.id",
                                type: "select",
                                label: "来源",
                                source: "options:/api/source",
                                required: true
                            }

![4](https://user-images.githubusercontent.com/273961/64474979-e5b6fc00-d1ae-11e9-9607-78b0392c7d8b.PNG)

**Comment by foxfire881** [comment]
试了patch可以用，head、options都用不了，HTTP有近20种方法，不知道有没有一个完整支持的列表。。。

**Comment by 2betop** [comment]
你可能需要配置成 

```
{
api: {
    method: "options",
    url: "/api/source"
}
}
```

我没做字符串形式的 options 支持

**Comment by foxfire881** [comment]
method试了好用。为啥不统一一下格式呢？

**Comment by 2betop** [comment]
补上了 https://github.com/baidu/amis/commit/782a767943bf3b93159a3e7cb6bd311ac993f387
