### ISSUE TITLE
app多页应用

### ISSUE THREAD

**Issue by manguanghui** [baidu/amis#2271]
#### 实现场景：
实现一个简单的app多页应用

#### 存在的问题：
使用本地的sdk时，app多页应用无法正常显示，比如说 url ，跳转之后就显示没有该文件
![image](https://user-images.githubusercontent.com/76045750/125418030-1f8fbbd1-8d11-4860-a5eb-d2d8b88443f3.png)

#### 当前方案：
<script>
        (function () {
            let amis = amisRequire('amis/embed');
            let amisJSON = {
                "type": "app",
                "brandName": "license管理系统",
                "logo": "public/logo.png",
                "pages": [
                    {
                        "label": "Home",
                        "url": "/",
                        "redirect": "/index/1"
                    },
                    {
                        "label": "示例",
                        "children": [
                            {
                                "label": "页面A",
                                "url": "index",
                                "schema": {
                                    "type": "page",
                                    "title": "页面A",
                                    "body": "页面A"
                                }
                            }
                        ]
                    }
                ]
            }
            let amisInstance = amis.embed('#root', amisJSON)
        })();
    </script>
```
code here...
```

**Comment by nwind** [comment]
建议参考 https://github.com/aisuda/amis-admin 项目
