### ISSUE TITLE
列表里的某列的内容是来自接口返回的映射

### ISSUE THREAD

**Issue by pineapplebin** [baidu/amis#228]
例如列表里有一列的数据为userId，想通过 GetUser 接口返回的内容显示 userName，请问要如何配置？

**Comment by foxfire881** [comment]
这没法配置，你这不是一行数据，是一列数据（N行），得发N次请求调用GetUser才能抓回来，不现实，设计也很糟糕。

比较好的做法是改后端，设计一个list()接口，在list函数中循环N次调用GetUser，然后把list结果一次性输出成一个json给前端渲染。

**Comment by 2betop** [comment]
虽然可以，但是正如 @foxfire881 说的不推荐。

如果一定要这么干，那就那列配置成 service 类型，配置 api，然后孩子节点去取变量。

**Comment by pineapplebin** [comment]
感谢回复，可能我表述有点歧义，如果是 GetUserList 这样可以批量获取用户信息的接口呢？像表单的select选项是来自接口那样，希望在表格显示这个字段的label而不是value

**Comment by 2betop** [comment]
还是列表接口直接返回 label 吧，目前没好办法另外接口返回，然后映射过去。

**Comment by pineapplebin** [comment]
了解了，感谢
