### ISSUE TITLE
官网中的 html 过滤器 使用方式没有生效

### ISSUE THREAD

**Issue by biley** [baidu/amis#2281]
#### 描述问题：
官方文档中的 html 过滤器的使用没有生效

#### 截图或视频：
地址：https://baidu.gitee.io/amis/zh-CN/docs/concepts/data-mapping#html 可以看到，html 标签依然保留着的
![截屏2021-07-15 18 02 05](https://user-images.githubusercontent.com/15087577/125781635-b6449bf3-3c0b-4f5c-8c5e-e7f12a3e806c.png)

#### 如何复现（请务必完整填写下面内容）：
请访问官网： https://baidu.gitee.io/amis/zh-CN/docs/concepts/data-mapping#html

**Comment by 2betop** [comment]
就是要保留成 html 原样输出，否则就容易 xss，如果你一定要就用 `${html | raw}`
