### ISSUE TITLE
crud 的样式问题

### ISSUE THREAD

**Issue by css-master** [baidu/amis#2286]
#### 描述问题：

正常的 crud：
![image](https://user-images.githubusercontent.com/34802622/125888829-2985ab33-db3c-4520-88b8-ce7365885ff6.png)

但是限制 crud 的最大高度后，滚动到下面就不合适了。

![image](https://user-images.githubusercontent.com/34802622/125888769-a73ebc9c-b1c8-4065-893b-d633010063fd.png)

主要是因为这个属性

![image](https://user-images.githubusercontent.com/34802622/125888803-9000f8a3-3137-456e-9204-167a19fc30e6.png)

感觉这个地方有点多余，但是可能你们设计有别的目的？ 我不好改，官方改一下吧。。。

**Comment by nwind** [comment]
没复现，可能是最近修改那个  affixOffsetTop 修了，如果还有的话再发详细 schema 吧
