### ISSUE TITLE
如何使用 seesionStronge

### ISSUE THREAD

**Issue by manguanghui** [baidu/amis#2287]
#### 实现场景：
登录验证

#### 存在的问题：
如何将后台返回的数据存入 SeeionStronge 或者 LocalStronge ，在需要进行接口验证的时候，取出来让后端进行验证

#### 当前方案：

现在的方式后台获取请求头里的token，得到的是token这个字符串，而不是token对应的数据
```
code here...
```
{
      "type": "crud",
      "name": "sample",
      "data": {
        "token": "${ls:token}"
      },
      "api": {
        "method": "get",
        "url": "http://localhost:7000/api/v1/select_alladmin",
        "headers": {
          "token": "token"
        }
      },

**Comment by 502647092** [comment]
推荐你直接修改fetcher把请求参数附加上
https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA
里面可以修改fetcher
渲染页面前 先请求用户Token
然后在fetcher里面把Token加上就好了

**Comment by nwind** [comment]
用 ss:token
