### ISSUE TITLE
each组件的value数组是否支持json格式？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#229]
https://baidu.github.io/amis/docs/renderers/Each
示例给的value只有1个值，对单个值进行循环迭代。当前有需求对对象进行循环（比如User对象有姓名、年龄两个属性），这样应该怎么写？

如下，tpl中如何取到title、count两个属性呢？试了用data.item.title、data.item.count无效。
{
    "type": "page",
    "body": {
        "type": "each",
        "value": [
            {"title":"A", "count":1},
            {"title":"B", "count":2},
            {"title": "C", "count": 3}
        ],
        "items": {
            "type": "tpl",
            "tpl": "<span class='label label-default'><%= data.item %></span> "
        }
    }
}

**Comment by foxfire881** [comment]
刚开了case自己就搞定了，用data.title、data.count就可以了，item是多余的。

**Comment by foxfire881** [comment]
刚开了case自己就搞定了，用data.title、data.count就可以了，item是多余的。

顺便问一下value支持api、souce之类的属性吗？从后端拉数据回来，然后在前端遍历？

**Comment by 2betop** [comment]
你可以和 Service 组合使用。
