### ISSUE TITLE
requiredOn 无效

### ISSUE THREAD

**Issue by flowerbin** [baidu/amis#2293]
#### 描述问题：
`requiredOn`  能在表单中显示星号，但是可以提交表单。

看了源码：getExprProperties 方法执行了，但是props没有更新到store中。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

3. 操作步骤

官网的文档中能够复现，数字超过1后，有红色的星号，但是可以提交：

https://baidu.gitee.io/amis/zh-CN/components/form/formitem#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%A1%E9%AA%8C%E4%BF%A1%E6%81%AF

**Comment by Vokinloksar** [comment]
Same issue, document not working as expected also
![image](https://user-images.githubusercontent.com/18415961/126118103-6c033ce7-0385-4f7a-9160-3c7cf3a0691e.png)

**Comment by nwind** [comment]
没复现，修了？ 我先关了，如果了解相关代码，可以直接提 pr
