### ISSUE TITLE
diff编辑器没有对比颜色

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#2298]
#### 描述问题：
加载diff编辑器没有颜色,日志报警告,
Uncaught SyntaxError: Unexpected token '<'

#### 截图或视频：
![](http://ww1.sinaimg.cn/large/b383e575ly1gsmg7otak3j216w07q751.jpg)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
 npm 版本 ^1.2.1

2. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "data": {
      "value1": "hello world",
      "value2": "hello"
    },
    "body": [
      {
        "type": "diff-editor",
        "name": "value2",
        "label": "Diff-Editor",
        "diffValue": "${value1}"
      }
    ]
  }
}

3. 操作步骤
 发布到web 页面中

**Comment by nwind** [comment]
npm 报错大概是因为这个 https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started#webpack-%E9%85%8D%E7%BD%AE%E5%8F%82%E8%80%83
