### ISSUE TITLE
自定义组件的问题

### ISSUE THREAD

**Issue by theojia** [baidu/amis#2300]
在自定义组件-React的方式中，如何嵌入amis的内置组件，比如嵌入 
{
        "type": "input-table",
        "name": "table",
        "columns":: []
}
的组件,各位大佬麻烦帮忙解答一下~

**Comment by theojia** [comment]
'amis/lib/components/index'这里面找不到input-table，不知道还有什么办法

**Comment by nwind** [comment]
props 里有 render 方法，不过还是更推荐再用 amis 顶层的 render 方法来重新渲染，避免数据链冲突
