### ISSUE TITLE
打包amis项目

### ISSUE THREAD

**Issue by manguanghui** [baidu/amis#2305]
#### 实现场景：
将写好的amis项目打包

#### 存在的问题：
无法进行打包，不知道怎么打包

#### 当前方案：
就是说，我是在amis-admin模板基础上，增加和修改了自己需要的东西，但是，这个该如何打包呢？还是说不需要打包

现在只能使用 npm start 命令执行后，项目才可以运行，如何使他不需要 npm环境也可以直接运行

```

```

**Comment by nwind** [comment]
目前 amis-admin 默认改成了 app 模式，不需要打包了
