### ISSUE TITLE
将amis-admin模板的sdk.css换成本地sdk

### ISSUE THREAD

**Issue by manguanghui** [baidu/amis#2306]
#### 实现场景：
将sdk.css换成本地sdk

#### 存在的问题：
换成本地之后，页面无法正常显示
![image](https://user-images.githubusercontent.com/76045750/126421008-30b6de91-3493-4a8d-bc77-af1ee39fd4fb.png)

#### 当前方案：
![image](https://user-images.githubusercontent.com/76045750/126421052-f62616bc-1ae6-4ea7-bd02-89475a87cc65.png)

![image](https://user-images.githubusercontent.com/76045750/126421122-99f1d38d-60be-4615-9535-ad14e3781d84.png)

```
code here...
```

**Comment by nwind** [comment]
通过 server 启动就好了，外链的好处是不用老更新
