### ISSUE TITLE
纯json或js配置的项目 自定义过滤器是怎么使用的，有没有demo？

### ISSUE THREAD

**Issue by xzw1030** [baidu/amis#2309]
#### 实现场景：
刚接触amis，请问下纯js配置的页面

#### 存在的问题：
registerFilter怎么用

**Comment by theojia** [comment]
举个🌰
```
// 注册
import { registerFilter } from 'amis';
registerFilter('getLength', (input) => (typeof input === 'string' ? input.length : 0));

// 使用
‘${items|getLength:xxx}’
```

**Comment by xiahao90** [comment]
let amisLib = amisRequire('amis');
amisLib.registerFilter('count', function (input) {
  return typeof input === 'string' ? input.length : 0;
});
https://baidu.gitee.io/amis/zh-CN/docs/concepts/data-mapping#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%87%E6%BB%A4%E5%99%A8
