### ISSUE TITLE
URIError: URI malformed crud中添加图片，点击修改时，出现

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#2312]
URIError: URI malformed

    in Dropzone
    in div
    in t
    in div
    in div
    in FormItem(input-image)
    in a
    in WithRootStore(a)
    in Renderer
    in div
    in t
    in WithStore(t)
    in Scoped(WithStore(t))
    in Renderer
    in div
    in div
    in div
    in i
    in Portal
    in t
    in Themeable(t)
    in t
    in WithStore(t)
    in Scoped(WithStore(t))
    in Renderer
    in form
    in div
    in div
    in t
    in Renderer
    in t
    in WithStore(t)
    in Scoped(WithStore(t))
    in Renderer
    in div
    in div
    in div
    in div
    in t
    in WithStore(t)
    in Scoped(WithStore(t))
    in Renderer
    in t
    in t
    in I18N(t)
    in Themeable(I18N(t))
    in t
    in Scoped(t)
    in div

#### 描述问题：
请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
不知道怎么复现，后续完整配置发一下吧，或者可能是之前的问题
