### ISSUE TITLE
想实现一个全局的url配置，在json文件中调用它

### ISSUE THREAD

**Issue by manguanghui** [baidu/amis#2326]
#### 实现场景：
实现一个url配置，在其他json文件中调用它，去请求接口，这样不需要去更改全部json文件中的请求接口的url。

#### 期望：
希望能够有实现这部分的代码。

```
code here...
```

**Comment by MoNianGolang** [comment]
代码如下
```
{
  "type": "page",
  "body": {
    "label": "点击开始下载",
    "type": "button",
    "level": "info",
    "actionType": "link",
    "link": "http://10.255.255.20:9091/api/v2/download_license?id=${params.id}"
  }
}
```
我这里是想将url里面的ip换成配置文件中的ip，到时候修改的之后只需要修改配置文件就可，
但是我现在不知道该怎么实现这个功能，有没有能回答一下的，希望有代码！！！
万分感谢！！！

**Comment by css-master** [comment]
开始的时候读取一下文件配置，然后遍历一下 json，当作环境变量一样注入进去就行了。

**Comment by MoNianGolang** [comment]
> 开始的时候读取一下文件配置，然后遍历一下 json，当作环境变量一样注入进去就行了。

有代码吗？有点不会 ^v^

**Comment by lhtuling** [comment]
最简单的是拦截ajax 请求  自己重新封装下
                fetcher: (params) => {
//自己封装http请求  可以用jq或者axios都行  返回一个Promise 即可
}

参数都可以得到  随意你怎么操作了

**Comment by lhtuling** [comment]
文档在这
https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA
