### ISSUE TITLE
CURD中text怎么设置成dialog弹窗？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#233]
一个CURD列太多了（N>20），当前是参考样例在最后一列放了operation排了几个小图标做查看、编辑等。

由于列太多导致整个CURD很长，虽然有列选择功能，但每次查看详情都要点击最后一列那个小图标，太费眼神了经常点错，能不能把CURD一些文本列（比如text类型的title标题字段）做成类似dialog弹窗那种形式？鼠标移动到title上点击title直接就弹出详情对话框页面了，眼睛不用横来横去找每一行对应的那个小图标，太累了，也经常点错。但是把title做成button那种按钮又太丑了，能不能保持text文本的前提下做成点击链接、弹窗那种效果？

**Comment by 2betop** [comment]
样式问题可以自己写 css 优化哈，还有 按钮的 level: "link" 配置成这个，长得差不多了。

另外列可以固定，可以配置 fixed: 'right'

**Comment by foxfire881** [comment]
所以只能把title列设置成button类型，然后用css渲染成一个没有透明的按钮？行倒是行，但是不太优雅呢。

title列用tpl只能渲染成href链接形式，点击之后跳到另一个页面了，做不出来dialog那种单页应用效果，看看有没有啥好的方法？现在眼睛横来横去太累了。

**Comment by 2betop** [comment]
按钮的 level 配置成 "link" 就是链接效果

**Comment by foxfire881** [comment]
> 按钮的 level 配置成 "link" 就是链接效果

测试发现异常：把title列的type=button并且level=link后确实是链接效果，但是由于是在CURD中显示数据（有很多行，每行都有一个title字段），所以为了在这个button上显示文本，配置如下：

{
name:"xxx"
type:"button",
label:"$title",
level:"link",
actionType:"dialog",
...
}

如此配置后，每一行的 button 文字确实变成对应的文本了，但是整个CURD的表头列名部分变成了"$title"这个字符串，还是有缺陷啊~~ 有啥好的解决方案吗？

**Comment by 2betop** [comment]
```
{
 "type": "container",
 "label": "列标题",
  "body": [
  
{
name:"xxx"
type:"button",
label:"$title",
level:"link",
actionType:"dialog",
...
}

 ]
}
```

**Comment by 2betop** [comment]
列那一层不要直接放按钮，而是放个容器，容器里面再放按钮。

**Comment by foxfire881** [comment]
还有这种玩法……这姿势太飘逸了。。测试好用，谢谢！
