### ISSUE TITLE
CURD中如何动态拉取列信息？

### ISSUE THREAD

**Issue by GuoTengda1993** [baidu/amis#2334]
#### CURD中动态拉取列信息
后端返回**列信息**及**每列的数据**，amis能动态加载这些列吗？翻了半天文档没找到类似的解决办法

**Comment by lhtuling** [comment]
https://baidu.gitee.io/amis/zh-CN/components/service
直接整个动态渲染试试

**Comment by lhtuling** [comment]
https://baidu.gitee.io/amis/zh-CN/components/service#%E5%8A%A8%E6%80%81%E6%B8%B2%E6%9F%93%E9%A1%B5%E9%9D%A2
