### ISSUE TITLE
json-editor的bug

### ISSUE THREAD

**Issue by sqzhou** [baidu/amis#234]
如果在json中出现一个逗号，再出现一个空格，会被推荐加入一个“$schema”的key。

**Comment by 2betop** [comment]
没懂

**Comment by sqzhou** [comment]
<img width="1078" alt="5b00aae814e64e3dfb85380f2" src="https://user-images.githubusercontent.com/19909056/64664129-be974d80-d480-11e9-8921-143b5fa3d361.png">

**Comment by sqzhou** [comment]
你应该知道bug了

**Comment by 2betop** [comment]
推荐个 `$schema` 有啥不妥？有了这个东西就能做更多输入提示。

**Comment by 2betop** [comment]
比如：

![image](https://user-images.githubusercontent.com/2698393/64664746-ac1e1380-d482-11e9-8758-4ce6f06d8894.png)

**Comment by sqzhou** [comment]
ok
