### ISSUE TITLE
通过点击按钮，实现定义一个变量，或者改变一个上下文中的变量

### ISSUE THREAD

**Issue by fox-momo** [baidu/amis#2344]
我的页面使用2个大panel组成，希望通过变量控制实现不同的panel显示和隐藏；这样我可以在一个页面操作多个页面的效果；

下面的代码，我希望我点击按钮，改变page变量，来实现内容的切换，可以吗？

{
  "type": "page",
  "title": "默认页面",
  "body": [
    {
      "type": "form",
      "title": "表单",
      "body": [
        {
          "label": "文本框",
          "type": "input-text",
          "name": "text"
        }
      ],
      "visibleOn": "page == 'page1'"
    },
    {
      "type": "form",
      "title": "表单",
      "body": [
        {
          "label": "文本框",
          "type": "input-text",
          "name": "text"
        }
      ],
      "visibleOn": "page == 'page2'"
    },
    {
      "type": "button",
      "label": "按钮",
      "actionType": "dialog",
      "dialog": {
        "title": "系统提示",
        "body": "对你点击了"
      }
    }
  ],
  "data": {
    "page": "page1"
  }
}

**Comment by xiahao90** [comment]
{
"type": "page",
"name": "page1",
"title": "默认页面",
"body": [
{
"type": "form",
"title": "表单",
"name": "form1",
"body": [
{
"label": "文本框1",
"type": "input-text",
"name": "text"
}
],
"visibleOn": "this.pageeeeeeeeeeee == '1'"
},
{
"type": "form",
"title": "表单",
"body": [
{
"label": "文本框不是1",
"type": "input-text",
"name": "text"
}
],
"visibleOn": "this.pageeeeeeeeeeee != '1'"
},
{
"type": "button",
"label": "按钮",
"actionType":"reload",
"target":"page1?pageeeeeeeeeeee=${pageeeeeeeeeeee|isEquals:'1':'0':'1'}",
}
],
"data": {
  "pageeeeeeeeeeee": "1"
}
},

**Comment by fox-momo** [comment]
谢谢

**Comment by nwind** [comment]
建议用 switch，另外新的 onClick 倒是也能做这个
