### ISSUE TITLE
froala-editor的license问题

### ISSUE THREAD

**Issue by theojia** [baidu/amis#2353]
Froala Edito在使用上仍需要用户去掏钱买许可证，后续amis中会考虑替换掉或者是由用户来自定义使用吗？

**Comment by 2betop** [comment]
默认是 tinymce 的，也可以配置成 tinymce 的版本

**Comment by theojia** [comment]
> 默认是 tinymce 的，也可以配置成 tinymce 的版本

喔喔，我们现在的问题是这样的 ╥﹏╥ 
我们公司使用amis是需要进行入库的，然后package.json里依赖了需要收费的froala-editor会导致amis入不了库，所以想建议一哈你们是不是可以去掉这个收费的~ 🍻

**Comment by nwind** [comment]
目前内部强依赖这个，所以短期内没法去掉
