### ISSUE TITLE
curd重置按钮bug

### ISSUE THREAD

**Issue by guchenhui** [baidu/amis#2359]
#### 描述问题：
curd的查询条件表单如果增加重置按钮，重置按钮并不能初始化成第一页

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm 版本1.2.1

2. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

3. 操作步骤
一个curd页面，增加一个查询条件表单，里面增加重置按钮。这个查询条件表单的filterTogglable: true,filterDefaultVisible: false。正常进入页面，先切换页码到3，然后显示查询条件表单，此时再切换页面至5。然后点击重置按钮，此时页面会到3。之后不管页面点击到哪一页，点击重置按钮，页面都会到3

**Comment by CheshireJCat** [comment]
未复现，已修复
