### ISSUE TITLE
static中的换行问题

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#236]
后端返回的数据中有大段文本，其中包括了"\n"换行符（这些\n换行符是之前在前端中通过textarea上传给后端的，在textarea中是分段显示的），但是这些\n在static控件中展示时没有换行，而是直接连成一大片了，如何换行？

**Comment by foxfire881** [comment]
请问这个case有解吗？

**Comment by 2betop** [comment]
用 prev 包起来

```html
<prev>${xxx|raw}</prev>
```

**Comment by foxfire881** [comment]
意思是把static换成tpl？试了不行呢~~ 还是连成一片的。配置如下，其中content是多段文本，换行符是"\n"，tpl、static、prev都没有把\n解释成换行。
{
name:"content",
label:"内容",
type:"tpl",
tpl:"<prev>${content|raw}</prev>"
}

**Comment by 2betop** [comment]
不可能啊

```
{
name:"content",
label:"内容",
type:"tpl",
tpl:"<prev>${content|raw}</prev>"
}
```

**Comment by foxfire881** [comment]
确实是没有换行，公司内网不能发截图，晚上回家我发个截图出来

**Comment by RickCole21** [comment]
是<pre>吧

**Comment by RickCole21** [comment]
试试`<pre>`

**Comment by 2betop** [comment]
:( 溜了

**Comment by foxfire881** [comment]
> 试试`<pre>`

试了用pre结果更可怕 ——  在static里面只是段与段之间的\n换行符没有解释出来，但是每段文字是可以适配dialog的宽度自动换行的；用了pre后，段落之间的换行倒是有了，但是由于原始文本每段文字都很长没有换行，结果导致pre宽度太宽直接撑破了dialog和屏幕，冲出屏幕外面去了。。 汗。。。。

**Comment by 2betop** [comment]
自己加个换行的样式就可以了，偷懒你就加个 "word-break" 这个 className

**Comment by foxfire881** [comment]
不太好描述呢。。等我晚上回去截图个图发上来看看吧，不光是word-break的问题

**Comment by 2betop** [comment]
这个是样式问题，自己解决吧，我这边没环境搞不定。没说飞得改 sdk.css 你自己可以加个样式表啊
