### ISSUE TITLE
Editor 是否可以主动触发代码提示 而不是输入一个字符后才提示 方便新手查看全部属性等情况

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#2361]
#### 实现场景：
主动触发代码提示 而不是输入一个字符后才提示

如果没有这个功能看是否能考虑增加  增加后新手入门编写amisjson会更方便   
否则新手刚开始用因为对属性的不了解导致一直翻看文档  
有代码提示根据属性的名字能大概判断  或者想起用法!

**Comment by nwind** [comment]
好像是因为比较干扰，所以 monaco 似乎不提供这个配置，不知道怎么开启，建议是配合可视化编辑器用
