### ISSUE TITLE
api地址中使用模板文本后，data不会拼接到 GET 的url里

### ISSUE THREAD

**Issue by qjebbs** [baidu/amis#2362]
#### 描述问题：

crud的api里配置模板文本后，data不会拼接到 GET 的url里。
预期：`/api/v1/list?page=3&perPage=10`  
实际：`/api/v1/list`  

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. 粘贴有问题的完整 `amis schema` 代码：
```jsonc
{
    "type": "crud",
    "name": "list",
    "api": "get:${apiPath | raw}/list" //apiPath定义在app组件中
    // ...
}
```

根据以下代码，似乎api地址里出现过`$`就不会拼上去（sdk不方便调试，人肉定位的不一定对）：

https://github.com/baidu/amis/blob/771c676424795447b7d368c8168993cdc6cc8f52/src/utils/api.ts#L99-L120

**Comment by xiahao90** [comment]
已经提过了https://github.com/baidu/amis/issues/1995

**Comment by qjebbs** [comment]
感谢，那我这先关了

**Comment by linjinglan** [comment]
换成post就行了
