### ISSUE TITLE
自定义组件--表单项初始化onChange不生效的问题

### ISSUE THREAD

**Issue by csychenci** [baidu/amis#2377]
#### 描述问题：
使用FormItem自定义的表单项，在componentDidMount中进行表单项对应的value进行初始化，使用onChange不生效

#### 截图或视频：
如下，这是我初始化页面内容的数据，现在我需要在页面挂载完成后对它进行初始化，无数据时初始化成一个空字符串，有数据时拼接成一个字符串
![image](https://user-images.githubusercontent.com/59555441/128995352-f4bd886a-e012-4af0-b442-f7d59a5ff56f.png)
但是，this.props.value的值并未改变，还是初始化的数据，并且在表单进行提交时，value也还是初始化的数据(但相应的编辑操作在提交是没问题的，onChange可以改变value的值)
![image](https://user-images.githubusercontent.com/59555441/128996340-b293df6c-4547-4d22-b0d0-9add85dcbc0b.png)
我希望在初始化后并提交表单(无任何编辑操作)，它的提交值能以以下方式组织(即formitemvalue被初始化)
![image](https://user-images.githubusercontent.com/59555441/128996295-b959ece4-18f2-42f9-859f-b9a28bc469b8.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. 粘贴有问题的完整 `amis schema` 代码：
```js
  componentDidMount() {
    const { data, name, onChange} = this.props;
    let content;
    content = data[name as string];
    if (content) {
      const {  value } = content;
// 有数据时初始化对应的值
    onChange(value);
 // ....
}else{
// 无数据时初始化为一个空字符串
    onChange('');
}
}
```
3. 操作步骤
其他地方均与自定义组件的实现方式一致，操作上没有问题，就此处初始化存在问题

**Comment by wibetter** [comment]
custom自定义组件目前已经不作为表单项组件了。
