### ISSUE TITLE
想在本地或者云上私有化部署一套有完整的文档吗

### ISSUE THREAD

**Issue by jinjiaxing** [baidu/amis#238]
问下，如果在自己本地或者云机器上去单独私有化部署一份，想要一份明细的文档

**Comment by foxfire881** [comment]
https://baidu.github.io/amis/
这文档已经很详细了，虽然还有些欠缺，但也足够满足你90%左右的常见需求了。

**Comment by 2betop** [comment]
https://github.com/fex-team/amis-admin 还有这个
