### ISSUE TITLE
select 组件 根据option中的指定字段来确认是否选中

### ISSUE THREAD

**Issue by kingofzihua** [baidu/amis#2384]
#### 是否关联于某个问题吗：
select 组建默认选中的方式放在options 中，放在value中有些功能不好实现

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...
{
        "label": "选项",
        "type": "select",
        "name": "select",
        "options": [
          {
            "label": "A",
            "value": "a",
            "selectd":true,
          },
          {
            "label": "B",
            "value": "b",
           "selectd":false,
          },
          {
            "label": "C",
            "value": "c",
            "selectd":false,
          }
        ]
      }

**Comment by zhyc9de** [comment]
什么功能不好实现，具体场景呢

**Comment by kingofzihua** [comment]
JSSDK 中，我需要根据后台接口来渲染select 的option，选中哪个需要后端返回

**Comment by gexMichael** [comment]
如果 form 上有2个以上的 select 要由 api 取得资料，会因同名而报错，请问应如何避开此问题?
