### ISSUE TITLE
Create-react-app --typescript  创建的项目，在调用CRUD的api，老是调用不起来

### ISSUE THREAD

**Issue by peidongGuo** [baidu/amis#239]
问题描述：
1、我用Create-react-app xxx --typescript创建了一个react 项目;
2、App.tsx里的代码如下：
`
import React from "react";
import logo from "./logo.svg";
import "./App.css";
import { render as renderAmis } from "amis";
import "amis/lib/themes/default.css";

const App: React.FC = () => {
  return (
    <>
      {renderAmis(
        {
          type: "page",
          // $schema: "http://amis.baidu.com/v2/schemas/page.json#",
          title: "增删改查示例",
          body: {
            type: "crud",
            api: "https://houtai.baidu.com/api/mock2/crud/list",
            columns: [
              {
                name: "name",
                label: "名字",
                width: 20,
                sortable: true,
                type: "text",
                toggled: true,
                remark: "Bla bla Bla"
              },
              {
                name: "description",
                label: "描述",
                sortable: true,
                searchable: true,
                type: "text",
                toggled: true
              },
              {
                name: "sinkClass",
                label: "下沉类",
                sortable: true,
                type: "text",
                toggled: false
              }
            ]
          }
        }

        // {
        //   fetcher: function(api) {
        //     // 适配这种格式 {"code": 0, "message": "", "result": {}}

        //     return axios(api.config).then(response => {
        //       console.log(response);
        //       let payload = {
        //         status: response.data.code,
        //         msg: response.data.message,
        //         data: response.data
        //       };

        //       return {
        //         ...response,
        //         data: payload
        //       };
        //     });
        //   }
        // }
      )}
    </>
  );
};

export default App;

`
3、页面报错如下

![image](https://user-images.githubusercontent.com/44695948/64761177-0ba51d80-d56e-11e9-8f49-aa32b5dc5ca8.png)

**Comment by 2betop** [comment]
env 要传入，参考：https://github.com/fex-team/amis-admin/blob/master/components/AMisRenderer.tsx#L74

**Comment by peidongGuo** [comment]
是env里的哪个参数要配置？

**Comment by peidongGuo** [comment]
env里的fetch需要自己写。
