### ISSUE TITLE
补充一些常用组件功能需求

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#2402]
1、提供timeline组件
2、地理位置选择器，最好点击后能弹出浮动窗口，当前的下拉交互性不好。
3、边框组件（参考element）
4、目前之只有input-tag（标签选择器），没有标签展示的组件，参考element的标签组件，包括颜色和主题
5、Badge 角标目前只能支持头像，需要支持文字、链接、按钮，甚至是容器等组件
6、提供Notification 通知组件，参考element
7、抽屉弹出的默认的X（关闭）样式丑陋，需要优化样式
8、能否提供无限滚动组件，比如大数据量的List列表，通过鼠标滚轮，支持无限分页滚动
9、日历
近期在考察使用amis的功能，整理了一些常用的需求，目前发现amis尚不支持，或者不完善。希望社区给与关注。
感谢。

**Comment by nwind** [comment]
1. timeline 后续会加，目前有设计稿了
2. 有参考的示例么？弹出是为了更大空间？
3. 这个？https://element.eleme.io/#/zh-CN/component/border 按说边框是属于每个组件的样式设置，后续组件会增加样式设置功能
4. 这个是打算做，目前可以用 mapping 配合 tpl 实现
5. 这个本来是支持的但由于 ts 类型没搞定然后忘了，后续加回去
6. 这个功能是嵌入到使用中的，比如发送请求失败的报错，似乎没有必要单独调用
7. 这个目前的最新设计稿是放标题右边，预计近期会改
8. 会在组件级别支持，比如目前 select 是默认支持的，其它组件也会逐步支持，具体看需求
9. 之前考察过，预计要做也是用第三方库，但这里有些交互功能还没想好怎么配置化，所以近期没计划

**Comment by Lijie0981** [comment]
> 8\. 会在组件级别支持，比如目前 select 是默认支持的，其它组件也会逐步支持，具体看需求

CURD、Table、Card、List 这些有支持计划吗？
