### ISSUE TITLE
SDK版本能够自定义headers中的Authorization值，或者有fetcher的具体实例

### ISSUE THREAD

**Issue by chen1tian** [baidu/amis#2424]
简单说明一下问题，在后台api中经常会使用token进行验证。因此需要设置headers的Authorization值。在sdk版本中，设置headers需要在fetcher中进行自定义，实际上fetcher的传输是比较复杂的，需要判断是否是form-data，form，json中的哪一种，根据不同的datatype发送不同的响应，因此要写一个完善无错误的fetcher比较困难（比如我就写不出来啊）。

#### 预期的解决方案：
在amis初始化时候传入Authorization值，考虑到token会过期，那么传入获取Authorization的函数对象更好。这样到达定义Authorization的目的，也不需要修改fetcher了。

#### 其他可接受方案：
在文档中给出sdk的fetcher示例。

#### 任何附加信息：
我认为amis的优势就是让不会react，对js也仅仅有一些了解的开发人员用上酷炫功能强大的前端，但是现在auth问题会把这批人挡住，挺可惜的。

**Comment by nwind** [comment]
可以写个 requestAdaptor 而不用覆盖 fetcher

**Comment by DataAlert-cn** [comment]
有requestAdaptor实例吗

**Comment by BruceLee569** [comment]
能不能多给点代码，在不了解前端框架的情况下，我为了一个跨域问题查遍全网没找到一句解决的代码，对非js程序员太不友好了，本地开发数据都返还了还被浏览器摆一道。。。

还是贴个报错，哪天来个大佬扔给我解决方案：
```
Access to XMLHttpRequest at 'http://localhost:8000/' from origin 'http://localhost:63342' has been blocked by CORS policy: 
The value of the 'Access-Control-Allow-Credentials' header in the response is 'ture' which must be 'true' when the request's credentials mode is 'include'. 
The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

MDN 告诉我设置 xhr.withCredentials = true; ，但是请问 amis 的这个请求参数在哪儿改？请求是封装的 XMLHttpRequest 么？我用的是打包好的sdk，sdk.js 里都是压缩后的代码，想改源码太难找了。能不能在 amisJSON 或者 index.html 中修改这个参数，以支持跨域请求。

官方文档找出来相关的 api 配置项是 requestAdaptor ，但是好像只支持修改请求头？

@nwind 大佬在之前的 issue 也解答过，但是就说了句 `自己覆盖 fetcher 去掉这个 withCredentials，或者用 https` ，问题官方文档里也没提到怎么修改 fetcher 啊，我连 fetcher 是啥在哪儿都没找到；所以我只能遵守第二句用 https ，服务器自签了个证书，开启了https，但是还是报同样的错，我好累。。。

**Comment by yuyu816** [comment]
给后来的小伙伴们补一个用requestAdaptor的示例：
 {
          requestAdaptor: (api) => {
            console.log(api);
            if (localStorage.getItem("token")) api.headers["Authorization"] = localStorage.getItem("token");
            let url = api.url;
            // 防止路径不携带分页参数
            if (url.indexOf("/list") > -1) {
              let project = "/" + localStorage.getItem("project");
              url =addStr(url, project, "/xxxxx"); //这块是自己写的方法用来拼接路径的 
            }
            return api;
          },

**Comment by BruceLee569** [comment]
> 给后来的小伙伴们补一个用requestAdaptor的示例： { requestAdaptor: (api) => { console.log(api); if (localStorage.getItem("token")) api.headers["Authorization"] = localStorage.getItem("token"); let url = api.url; // 防止路径不携带分页参数 if (url.indexOf("/list") > -1) { let project = "/" + localStorage.getItem("project"); url =addStr(url, project, "/xxxxx"); //这块是自己写的方法用来拼接路径的 } return api; },

你这个是修改请求头部，我的问题是跨域，需要修改 xhr 的 withCredentials 属性值。

**Comment by yuyu816** [comment]
> > 给后来的小伙伴们补一个用requestAdaptor的示例： { requestAdaptor: (api) => { console.log(api); if (localStorage.getItem("token")) api.headers["Authorization"] = localStorage.getItem("token"); let url = api.url; // 防止路径不携带分页参数 if (url.indexOf("/list") > -1) { let project = "/" + localStorage.getItem("project"); url =addStr(url, project, "/xxxxx"); //这块是自己写的方法用来拼接路径的 } return api; },
> 
> 你这个是修改请求头部，我的问题是跨域，需要修改 xhr 的 withCredentials 属性值。
![image](https://user-images.githubusercontent.com/50612027/177484713-a7dc0b00-6c52-4b4c-b083-bedc942bc980.png)

有没有一种可能。。你可以通过api.withCredentials = true|false 就可以修改呢。。
不过这个跨域问题 我们都放到服务器端去解决额

**Comment by BruceLee569** [comment]
> > > 给后来的小伙伴们补一个用requestAdaptor的示例： { requestAdaptor: (api) => { console.log(api); if (localStorage.getItem("token")) api.headers["Authorization"] = localStorage.getItem("token"); let url = api.url; // 防止路径不携带分页参数 if (url.indexOf("/list") > -1) { let project = "/" + localStorage.getItem("project"); url =addStr(url, project, "/xxxxx"); //这块是自己写的方法用来拼接路径的 } return api; },
> > 
> > 
> > 你这个是修改请求头部，我的问题是跨域，需要修改 xhr 的 withCredentials 属性值。
> > ![image](https://user-images.githubusercontent.com/50612027/177484713-a7dc0b00-6c52-4b4c-b083-bedc942bc980.png)
> 
> 控制台打印看到值已经是true了。你可以通过通过api.withCredentials = true|false 去设置。。 但是跨域问题 我们一般放到服务端去解决额

感谢回复，终于知道是哪里错了，服务端 Access-Control-Allow-Credentials 响应头的值写错了，true 写成了 ture，我说浏览器怎么 true 等于 true 还报错，一字之差坑死我了 🤣

**Comment by chen1tian** [comment]
> @chen1tian 老哥这个问题解决了么？我快被挡住了
我是重新了fetcher。代码如下：
```javascript
var options = {
  fetcher: function (params) {
      var method = params.method;
      var url = params.url;
      var data = params.data;
      return new Promise(function (resolve, reject) {
          fetch(url, {
              method: method,
              headers: new Headers({
                  "Content-Type": "application/json;",
                  "Authorization": "Bearer " + access_token
              }),
              body: JSON.stringify(data)
          }).then(function (res) {

              if (!res.ok) {
                  if (res.status == 401 || res.status == 403) {
                      ddAlert('提示', '无权访问')
                  }
              }

              return res.json();
          }).then(function (response) {
              resolve({
                  "data": response,
              });
          });
      });
  }
}

let amisScoped = amis.embed('#root', amisJSON, null, options);
```
注意第10~11行，access_token是登录接口返回的，把它放入header中。

**Comment by d0uub** [comment]
SDK是如何解決的？看完也不太明白。React版本可以通過修改withCredentials解決，但是在SDK版本中找不到相應的方法。
