### ISSUE TITLE
还是一些独立部署问题

### ISSUE THREAD

**Issue by jinjiaxing** [baidu/amis#243]
1：我之前也是在百度使用amis。因为有平台可以直接新建空间，新建页面，设置权限，通过在amis平台直接编辑json最后生成页面，保存发布上线，这个流程很赞，问题是：现在开源出来的amis-render其实只是渲染器，而不是将整个前后端平台都开放出来，所以之前那些功能都是需要自己开发是吧？

2：比如amis-admin，其实我就是通过npm使用amis的渲染器而已，然后在其他地方编辑好json在我自己的react项目中引入amis 在进行渲染而已了？所以之前百度内的整套内容是不打算开源的把？或者说及时代码不开源，是否考虑是否会提供一个完整工具呢，比如我现在要进行独立部署，基本上那一套东西我都要重新开发一次了

**Comment by FatDong1** [comment]
这个季度快过了呀，日常催更

**Comment by songjin** [comment]
催更催更

**Comment by 2betop** [comment]
一脸懵逼啊，是指这个吗？http://fex-team.github.io/amis-editor

**Comment by nwind** [comment]
https://aisuda.bce.baidu.com/
