### ISSUE TITLE
请问api请求如何设置使用同一的host

### ISSUE THREAD

**Issue by osenlin** [baidu/amis#244]
现在我的表单api都是写成下面这种形式：
```
"api": "post:http://192.168.136.129:8081/app/manager/update"
```
如果遇到域名切换，每个页面都需要修改，很是繁琐，请问AMIS如何避免这种操作？

**Comment by 2betop** [comment]
```
"api": "post:/app/manager/update"
```

这样？

**Comment by Songziyuan** [comment]
fetcher里拦截一下：
![image](https://user-images.githubusercontent.com/15028748/65040095-36d0a800-d986-11e9-924a-7715d2acbdf4.png)
