### ISSUE TITLE
redirect动态链接跳转有点问题

### ISSUE THREAD

**Issue by ChenSen5** [baidu/amis#2451]
{
        label: "远程获取连接",
        type: "button",
        actionType: "ajax",
        api: {
            url: "/api/getUrl"
        },
feedback:{
            "title": "点击下方链接进行加载",
            "body":{
                "type": "link",
                "href": "${url}",
                "body": "去下载",
                "blank": true
            }
        }
}
url是从api接口返回的，现在返回的是：http://www.baidu.com，实际点击去下载的时候跳转的是http:&#x2F;&#x2F;baidu.com

**Comment by ChenSen5** [comment]
> 用最新版本试试

使用了，新版本1.2.0-beta.1，href的已经正常了，但是使用redirect的还是不行。
```json
{
	label: "远程获取连接",
	type: "button",
	actionType: "ajax",
	api: {
		url: "/api/getUrl"
	},
	redirect: "${url}"
}
```

**Comment by hyzx86** [comment]
> 用最新版本试试

editor 里面关掉 ，blank 
但始终只能从新页面打开

官方示例
https://aisuda.bce.baidu.com/amis/zh-CN/components/link#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95
![image](https://user-images.githubusercontent.com/15613121/203970977-c74e8b8d-d189-44d3-a001-9331bc17bf62.png)

**Comment by allenve** [comment]
用最新版试试
