### ISSUE TITLE
amis editor编辑器自定义组件

### ISSUE THREAD

**Issue by getChange** [baidu/amis#2453]
#### 描述问题：
amis editor编辑器自定义组件拖拽保存到页面之后，再次刷新页面会提示找不到对应渲染器

#### 截图或视频：
![image](https://user-images.githubusercontent.com/23140007/131067505-c99cc73e-7346-4fa6-bb64-fe153c2ddf82.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. 粘贴有问题的完整 `amis schema` 代码：
amis-editor官网原始代码

3. 操作步骤
将自定义组件拖拽到编辑器内，点击保存之后退出，刷新页面就会提示找不到对应渲染器！

**Comment by getChange** [comment]
> 需要在引入编辑器的项目中再引入自定义组件的相关代码

项目中有引入的，但是现在amis-editor官网的自定义组件添加之后保存，再次刷新页面也是这样的提示
![image](https://user-images.githubusercontent.com/23140007/131959864-18b250cc-24f1-4788-8504-55045693d799.png)

**Comment by lck123357** [comment]
同文

**Comment by lck123357** [comment]
同问
