### ISSUE TITLE
mapping组件如何把一个不存在的status映射成默认值？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#2457]
#### 实现场景：
mapping组件绑定字段为空或不存在时，希望映射为一个默认值。

#### 存在的问题：
当返回data中child是空值时，其属性child.status不存在，此时用星号”*“映射显示出来是一个减号”-“而不是期望的”待提交“字段。如何给一个不存在或空值的status绑定一个默认mapping呢？

#### 当前方案：

{
            "type": "static-mapping",
            "label": "当前状态",
            "name": "child.status",
            "map": {
              "*": "<span class='label label-default'>待提交</span>",
              "0": "<span class='label label-warning'>待审核</span>",
              "1": "<span class='label label-danger'>审核不通过</span>",
              "2": "<span class='label label-success'>审核通过</span>"
            }
          }

**Comment by nwind** [comment]
用 placeholder
