### ISSUE TITLE
get请求手动修改参数问题

### ISSUE THREAD

**Issue by nankaidi** [baidu/amis#2464]
#### 描述问题：
get请求在requestAdaprtor中修改了query里的参数，但是没有效果，实际参数还是url后的参数，期望url后的参数应该和query中的数据进行联动

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by allenve** [comment]
requestAdaprtor 直接修改url试试
