### ISSUE TITLE
引入 sdk 报错， Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by imyangyong** [baidu/amis#2465]
按照文档示例，引入的 sdk 报错：

<img width="512" alt="E7CFE70C-8E2F-4C85-8DCA-23F0F6F9C288" src="https://user-images.githubusercontent.com/42476396/131170219-ed3c3786-d976-45f0-8b50-8dab7050cafc.png">

**Comment by mrchi** [comment]
我也遇到这个问题了，根据文档中的说明设置 `locale` 并不生效。
https://baidu.github.io/amis/zh-CN/docs/extend/i18n#js-sdk

**Comment by RickCole21** [comment]
先给 `amis.embed()` 的第四个参数传入一个空对象，例如：

```
amis.embed(
  '#root',
  {
    // amis schema
  },
  {
    // 这里是初始 props
  },
  {} // 空对象
);
```

下版本会做一下兼容处理
