### ISSUE TITLE
组合条件condition-builder里面的defaultOp貌似不起作用

### ISSUE THREAD

**Issue by WuGUOJ** [baidu/amis#2468]
#### 描述问题：
条件组合这个功能非常强大好用，但有些细节希望解答下：
组合条件condition-builder里面的defaultOp貌似不起作用，或者我不明白这个参数的意义是什么？
我理解是当我选择一个字段后，中间选择操作的下拉选项和右边的输入框会自动显现出来，而不是还要点一下下拉，即使我设置的操作只有equal。另外，还想请教下，条件组合的文本输入框如何调整宽度呢？

#### 截图或视频：
![微信截图_20210828150751](https://user-images.githubusercontent.com/34879913/131209983-8e128eb6-071b-4edd-a3da-86a8096f9a0e.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？
   1.2.2

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "body": [
      {
        "type": "condition-builder",
        "label": "条件组件",
        "name": "conditions",
        "description": "适合让用户自己拼查询条件，然后后端根据数据生成 query where",
        "fields": [
          {
            "label": "A",
            "type": "text",
            "name": "a",
            "operators": ["equal"],
            "defaultOp": "equal"
          }
        ]
      }
    ]
  }
}
```

4. 操作步骤

**Comment by xiazimi** [comment]
我想问一下，条件组件如何自定义条件？（大于、等于、小于等默认条件能覆盖么？我在官网上没找到）

**Comment by WuGUOJ** [comment]
目前我还没找到如何自定义条件，但是它默认的条件判断基本都够用了吧。

**Comment by hsm-lv** [comment]
> 我想问一下，条件组件如何自定义条件？（大于、等于、小于等默认条件能覆盖么？我在官网上没找到）

自定义条件主要是通过为fields内每项定义operators实现，例如：
```json
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "body": [
      {
        "type": "condition-builder",
        "label": "条件组件",
        "name": "conditions",
        "description": "适合让用户自己拼查询条件，然后后端根据数据生成 query where",
        "searchable": true,
        "fields": [
          {
            "label": "文本",
            "type": "text",
            "name": "text",
            "defaultValue": "bbbb",
            "operators": [
              {
                "lable": "aaaa",
                "value": "aaaa"
              },
              {
                "lable": "bbbb",
                "value": "bbbb"
              }
            ]
          },
          {
            "label": "数字",
            "type": "number",
            "name": "number"
          }
        ]
      }
    ]
  }
}
```

**Comment by hsm-lv** [comment]
> #### 描述问题：
> 条件组合这个功能非常强大好用，但有些细节希望解答下： 组合条件condition-builder里面的defaultOp貌似不起作用，或者我不明白这个参数的意义是什么？ 我理解是当我选择一个字段后，中间选择操作的下拉选项和右边的输入框会自动显现出来，而不是还要点一下下拉，即使我设置的操作只有equal。另外，还想请教下，条件组合的文本输入框如何调整宽度呢？
> 
> #### 截图或视频：
> ![微信截图_20210828150751](https://user-images.githubusercontent.com/34879913/131209983-8e128eb6-071b-4edd-a3da-86a8096f9a0e.png)
> 
> #### 如何复现（请务必完整填写下面内容）：
> 1. 你是如何使用 amis 的？
>    `sdk`
> 2. amis 版本是什么？
>    1.2.2
> 3. 粘贴有问题的完整 `amis schema` 代码：
> 
> ```
> {
>   "type": "page",
>   "body": {
>     "type": "form",
>     "debug": true,
>     "body": [
>       {
>         "type": "condition-builder",
>         "label": "条件组件",
>         "name": "conditions",
>         "description": "适合让用户自己拼查询条件，然后后端根据数据生成 query where",
>         "fields": [
>           {
>             "label": "A",
>             "type": "text",
>             "name": "a",
>             "operators": ["equal"],
>             "defaultOp": "equal"
>           }
>         ]
>       }
>     ]
>   }
> }
> ```
> 
> 4. 操作步骤

目前还没支持defaultOp，后面会考虑补充

**Comment by hsm-lv** [comment]
https://github.com/baidu/amis/pull/8914
