### ISSUE TITLE
amis npm 1.2.3版本设置theme default属性不生效

### ISSUE THREAD

**Issue by gtopia** [baidu/amis#2475]
#### 描述问题：
amis npm 1.2.3版本设置theme default属性不生效

#### 截图或视频：
设置theme属性为`default`不生效，主题被错误渲染为了`cxd`。
![image](https://user-images.githubusercontent.com/8113851/131292291-54fb2a66-ef5c-406b-8806-30d123873112.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. amis 版本是什么？
1.2.3

3. 操作步骤
通过renderAmis设置theme属性为`default`。

**Comment by nwind** [comment]
不要用 default，用 ang
