### ISSUE TITLE
如何获取select组件的label值哦？

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#2478]
#### 实现场景：
如何获取select组件的label值哦？
![image](https://user-images.githubusercontent.com/11575908/131321705-d7ad0300-a08d-48ba-b5f6-5c3348d239aa.png)

#### 当前方案：
我需要获取lebel的值，在另外的组件用作title显示

```
code here...
```

**Comment by 2betop** [comment]
1. select 组件配置 autoFill
2. 修改 select 的值格式，比如 joinValues: false
