### ISSUE TITLE
如何打包整个项目

### ISSUE THREAD

**Issue by x1194785386** [baidu/amis#248]
没有 npm build 的问题

**Comment by 2betop** [comment]
这个跟本项目没有关系吧

**Comment by x1194785386** [comment]
那我现在想要将改动过的该项目打包我该怎么做呢？

**Comment by 2betop** [comment]
sh publish.sh 会生成 npm 相关文件，修改 package.json 里面的 name 发不成你们自己的名字

**Comment by x1194785386** [comment]
用了 publish.sh脚本出现了以下错误
![QQ图片20190920165929](https://user-images.githubusercontent.com/51640396/65314102-2dcf1900-dbc8-11e9-8b2e-986dabcaac3c.png)

**Comment by x1194785386** [comment]
用了 publish.sh脚本出现了以下错误

- [ ] 
![QQ图片20190920165929](https://user-images.githubusercontent.com/51640396/65314161-51925f00-dbc8-11e9-91b8-78c3306491ba.png)

**Comment by x1194785386** [comment]
![ccc](https://user-images.githubusercontent.com/51640396/65314201-6969e300-dbc8-11e9-8f87-635caedd7e9e.png)

**Comment by x1194785386** [comment]
![ccc](https://user-images.githubusercontent.com/51640396/65314343-bd74c780-dbc8-11e9-9547-b8564a8f937f.png)

**Comment by x1194785386** [comment]
运行publish.sh出现了以下错误问题：

publish.sh: line 14: tsc: command not found
publish.sh: line 16: cd: output: No such file or directory

**Comment by catchonme** [comment]
安装一下 typescript




在2019年09月20日 17:06，x1194785386 写道：

运行publish.sh出现了以下错误问题：

publish.sh: line 14: tsc: command not found
publish.sh: line 16: cd: output: No such file or directory

**Comment by 2betop** [comment]
要用 linux 或者 mac

**Comment by baozai6795** [comment]
不能一起指定allowJs --declaration

![S8W(JUK7C7)O4FXM$3QO18Y](https://user-images.githubusercontent.com/53046357/65406780-26e81680-de13-11e9-8934-3199c501aa3d.png)

**Comment by 2betop** [comment]
这个可以忽略，我只是想生成点 类型文件，虽然报错但是能生成。

**Comment by baozai6795** [comment]
> 这个可以忽略，我只是想生成点类型文件，虽然报错但是能生成。

我用git打包的

**Comment by baozai6795** [comment]
打包后多三个文件夹，如何部署
![BA5 8$JM_6XU0 N5}19 MWC](https://user-images.githubusercontent.com/53046357/65407573-92cb7e80-de15-11e9-87ee-b6cbcd00c7f9.png)

**Comment by 2betop** [comment]
最简单的方式是 改一下 package.json 换个名字发布到 npm 上

**Comment by baozai6795** [comment]
> npm

他都要js类型文件，不像vue那样生成一个dist文件

**Comment by baozai6795** [comment]
> > NPM


> 最简单的方式是改一下package.json换个名字发布到npm上

这样我们的生产环境要安装nodejs，有没有办法搞成只搞成用nginx代理的

**Comment by 2betop** [comment]
看不懂你的意图，理论来说你只需要把  lib copy 出去就能用了

**Comment by baozai6795** [comment]
> 看不懂你的意图，理论来说你只需要把 lib copy 出去就能用了

lib如何部署

**Comment by baozai6795** [comment]
单独的lib如何跑动

**Comment by baozai6795** [comment]
> 看不懂你的意图，理论来说你只需要把 lib copy 出去就能用了

问题解决了

**Comment by icodingx** [comment]
> 打包后多三个文件夹，如何部署
> ![BA5 8$JM_6XU0 N5}19 MWC](https://user-images.githubusercontent.com/53046357/65407573-92cb7e80-de15-11e9-87ee-b6cbcd00c7f9.png)

打包命令是什么呢？

**Comment by icodingx** [comment]
sdk.js 足足2M 有没有优化方案啊 ？

**Comment by CareyToboo** [comment]
@icodingx @x1194785386 @baozai6795  [rt-admin]( https://github.com/CareyToboo/rt-admin) 这是我目前采用 amis 二次封装的一个admin解决方案。正在开发中，虽然amis包的大小很大，但是使用dll强制长期缓存，缓存命中后，打开速度极快。现在还很多功能在开发中，但是打包这块应该没有问题了。希望能够有点帮助, 有任何问题可以随时@我。
