### ISSUE TITLE
Nav 导航 hash模式的地址 不会自动计算是否高亮  

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#2480]
#### 描述问题：
比如
#/index 
这样类型的链接
点击跳转页面后  高亮无变化  只有重新刷新页面才可以   

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？
1.2.3

3. 粘贴有问题的完整 `amis schema` 代码：

```
{
    "type": "nav",
    "stacked": true,
    "links": [
        {
            "label": "首页",
            "to": "#/index",
            "activeOn": "location.hash.includes('index')"
        },
        {
            "label": "测试1",
            "to": "#/test1",
            "activeOn": "location.hash.includes('test1')"
        }
    ]
 #}
```

4. 操作步骤
点击即可看到效果

**Comment by lhtuling** [comment]
测了下发现 导航是一次性渲染然后后面数据就不会在变动的样子
等于是没有双向绑定  activeOn也只在渲染时候一次性计算了
后面修改公式里面的变量也没有用 不会重新计算
vue路由模式下就比较难受了 用不了~~

**Comment by lawbc** [comment]
我改成Browser模式也不会自动计算，不知道为什么每次都无法选中，用的是6.5.0版本
