### ISSUE TITLE
dark 主题 微调

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#2487]
针对官网的组件和实例两个板块，测试了下dark 主题样式的感官。还有一些细微的感觉不太友好，比如radio的选中状态不醒目；一些组件的hover一片白，遮挡后方的内容；日历时间、向导、富文本、textarea、代码编辑器等一些组件的内部暗色样式不完全。建议官方围绕暗色主题的样式，整体做次检查和优化。
感谢。

**Comment by nwind** [comment]
后来改过一次颜色，不过现在这个配色没时间维护了
