### ISSUE TITLE
crud api依赖更新异常

### ISSUE THREAD

**Issue by fox-momo** [baidu/amis#2489]
crud table的api地址为：
get:/api/sys/module/menu/menu-tree?menuType=${menuType}&moduleNo=${moduleNo}

依赖上下文中的两个表单项，原来可以用，升级后，只有一个参数有联动效果，另一个失效了
![1](https://user-images.githubusercontent.com/88315383/131644434-19e56df5-fb39-4683-8bd0-242e2b2635d8.png)

**Comment by fox-momo** [comment]
也可能是input-tree无法触发change事件了

**Comment by hsm-lv** [comment]
没有复现，尝试一下新版本再看看呢
