### ISSUE TITLE
property 插件使用报错

### ISSUE THREAD

**Issue by JeremyGGit** [baidu/amis#2493]
#### 描述问题：
使用插件property的时候，外层嵌套service， 内部拉去数据报错。

#### 截图或视频：
![image](https://user-images.githubusercontent.com/41996437/131800021-b956f680-9e0f-4fd3-b950-7dc331c43746.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？
最新版本

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```
{
          "type": "service",
          "api": "/ceih/v1/base/${ggfs}",
          "body":{
	          "type": "property",
	          "column": 2,
	          "title": "测试信息",
	          "source": "${items}",
	          "labelStyle":{
		          "textAlign": "left",
		          "verticalAlign": "top",
		          "width": "10%",
	          }
          }
},
4. 操作步骤
请简单描述一下复现的操作步骤...
service 中返回的数据格式:
{
	"status": 0,
	"msg": "请求成功",
	"data": {
		"items": [{
			"label": "名称",
			"content": "bjajsgffdd",
			"span": 2
		}, {
			"label": "csussss",
			"content": "周强"
		}]
	}
}

在crud->columns->operation->buttons->drawer->body 中显示正常，但是在其他使用场景均显示错误

**Comment by hsm-lv** [comment]
没有复现，测试代码如下：
```json
{
  "type": "page",
  "body": [
    {
      "type": "service",
      "body": [
        {
          "type": "property",
          "title": "机器配置",
          "id": "u:e45467779287",
          "column": 3,
          "mode": "table",
          "source": "${props}"
        }
      ],
      "id": "u:3c95bdd41897",
      "dsType": "apicenter",
      "api": {
        "method": "post",
        "url": "/api/test/amrSKLuDyd1dvfJRdewakt"
      }
    }
  ],
  "title": "Hello world",
  "editorState": "default"
}
```

接口返回数据如下：
```json
{
    "status": 0,
    "msg": "",
    "data": {
        "props": [
            {
              "label": "cpu",
              "content": "1 core",
              "span": 1
            },
            {
              "label": "memory",
              "content": "4G",
              "span": 1
            },
            {
              "label": "disk",
              "content": "80G",
              "span": 1
            },
            {
              "label": "network",
              "content": "4M",
              "span": 2
            },
            {
              "label": "IDC",
              "content": "beijing",
              "span": 1
            },
            {
              "label": "Note",
              "content": "其它说明",
              "span": 3
            }
          ]
    }
}
```
