### ISSUE TITLE
容器组件可以自定义吗？

### ISSUE THREAD

**Issue by lhkg1988** [baidu/amis#2496]
现有的容器都是去选样式，但是在C端使用时，会需要一个背景色，或者背景图，最终是给到运营的人使用的，希望可以可视化的去配置

#### 预期的解决方案：
期望可以提供自定义容器的方式

#### 其他可接受方案：
现有的容器支持背景色和背景图的配置

**Comment by lhkg1988** [comment]
实在不行，现有的容器可以支持修改背景色也行？

**Comment by nwind** [comment]
已经支持了
