### ISSUE TITLE
CRUD 组件单条数据的onClick事件如何设置？

### ISSUE THREAD

**Issue by Gitwinters1973** [baidu/amis#2498]
#### 实现场景：
点击（onClick）CRUD单个数据条目，触发onClick事件，获取单条目数据值（如 id）

#### 存在的问题：
不知如何在CRUD设置onClick事件

#### 当前方案：
无

```
code here...
```

**Comment by kevin50ster** [comment]
同问，某种场景下希望能接管行点击事件，从而触发其他操作。

**Comment by dikar** [comment]
注意看 官方文档
有2个方式，一个是用action （官方推荐）
另外一个是可以传递一段代码进去

**Comment by Gitwinters1973** [comment]
> 注意看 官方文档
> 有2个方式，一个是用action （官方推荐）
> 另外一个是可以传递一段代码进去

您好，我是想操作CRUD列表的单条数据，官方给出的方法是在单条数据上放置一个按钮，才能获取单条数据ID，再进行其它操作，我是想直接单击（click）或双击（dblClick）单条数据，然后获取单条数据ID进行其它操作。

**Comment by duqingyu** [comment]
我也找不到，目前只能放在操作栏去点击按钮

**Comment by hsm-lv** [comment]
https://baidu.github.io/amis/zh-CN/components/crud#rowclick
