### ISSUE TITLE
aisuda / amis-editor-demo使用

### ISSUE THREAD

**Issue by break60** [baidu/amis#2501]
#### 描述问题：
![image](https://user-images.githubusercontent.com/28628088/131943442-8315763f-c3cc-42c2-8eee-eb0bbca6bd5e.png)
![image](https://user-images.githubusercontent.com/28628088/131943481-aefb87a3-5b33-4040-a422-a5e53a62546d.png)
hi，我在使用amis-editor-demo时，通过npm i和npm start运行，public里面的内容始终为空
![image](https://user-images.githubusercontent.com/28628088/131943584-1084c6fa-a4e9-41ea-8df8-b431abf9602d.png)

**Comment by nwind** [comment]
npm run dev
