### ISSUE TITLE
Action 行为按钮，增加键盘快捷键触发

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#2502]
#### 是否关联于某个问题吗：
希望为Action增加快捷键触发的方式，如我用Editor 打开一个代码编辑框，编辑完代码后，按Control+c可以进行提交

#### 任何附加信息：
![image](https://user-images.githubusercontent.com/11575908/131944331-6bfe4244-148c-4de3-9db1-e1eece81444a.png)

**Comment by cmdares** [comment]
对，我这边有类似的需求，比如文本框的快速回复alt+s。在线富文本保存ctrl+s等操作。
