### ISSUE TITLE
Web Component Error: 找不到对应的渲染器

### ISSUE THREAD

**Issue by Gitwinters1973** [baidu/amis#2505]
#### 实现场景：
调用Web Component 组件
#### 存在的问题：
Error: 找不到对应的渲染器

Path: page/body/0/grid/column/1/0/wrapper/body/0/component

{
  "type": "component",
  "tag": "random-number",
  "props": {
    "prefix": "hello",
    "class": "my-class"
  }
}

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
"type": "web-component"
