### ISSUE TITLE
自定义组件接收动态props

### ISSUE THREAD

**Issue by Gitwinters1973** [baidu/amis#2507]
#### 实现场景：
自定义组件：
使用其它组件对自定义组件进行reload操作，并修改其属性，自定义组件进行刷新，并更新内部props

#### 存在的问题：
使用其它组件对自定义组件进行reload操作，修改其属性，自定义组件内的props没有更新

#### 当前方案：
{
   "type": "operation",
                          "label": "",
                          "buttons": [
                            {
                              "label": "更新自定义组件props",
                              "type": "action",
                              "actionType": "reload",
                              "target": "CustomComponent?index=${Index}"
                            },
                          ]
                        }

自定义组件：

function CustomComponent(props) {
      let dom = React.useRef(null);
      React.useEffect(function () {
        dom.current.innerHTML = props.index;
      });
      return React.createElement('div', {
        ref: dom
      });
    }

**Comment by fxwing** [comment]
自定义组件需要Renderer包一层吧？

**Comment by leung0727** [comment]
你好想问问，你这个自定义组件能否引入amis内置的组件呢

**Comment by hsm-lv** [comment]
组件通信问题分两种情况：
方式一：自定义组件包装成renderer，那就可以通过amis联动机制或者事件动作直接通信
方式二：amis组件与Vue或者React组件通信，可以看这里： https://baidu.github.io/amis/zh-CN/docs/extend/ui-library#%E7%9B%91%E5%90%AC%E5%B9%BF%E6%92%AD%E4%BA%8B%E4%BB%B6，https://baidu.github.io/amis/zh-CN/docs/start/getting-started#%E8%B0%83%E7%94%A8-amis-%E5%8A%A8%E4%BD%9C（调用amis动作是新增，需要等下下个版本）
