### ISSUE TITLE
button上设置onClick代码->修改state无效

### ISSUE THREAD

**Issue by Gitwinters1973** [baidu/amis#2508]
#### 实现场景：
在amis配置中，按钮上添加onClick代码，修改React  jsx组件中的 state 状态，从而进行页面刷新

#### 存在的问题：
在代码中 setState 无效

#### 当前方案：
``

```
{
        type: 'button',
        label: '按钮',
        onClick: () => {
           this.setState({
             value : '123'
           })
        }
      }
```

**Comment by nwind** [comment]
```
onClick: (e, props) => {
    props.formStore.setValues({value: '123'});
}
```

**Comment by Gitwinters1973** [comment]
感谢帮助！



***@***.***
 
发件人： 吴多益
发送时间： 2021-09-10 14:57
收件人： baidu/amis
抄送： winters; Author
主题： Re: [baidu/amis] button上设置onClick代码->修改state无效 (#2508)
Closed #2508.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
