### ISSUE TITLE
控件的属性值能否动态修改？

### ISSUE THREAD

**Issue by Leonard-Li777** [baidu/amis#251]
比如想修改name, className，placeholder等等
通过condition什么的，目前想做到这样，都只能通过复制一个控件，通过visibleOn来模拟

**Comment by 2betop** [comment]
动态配置，另外可以考虑用 service 配置 schemaApi，由后端动态返回配置。

**Comment by Leonard-Li777** [comment]
我想实现type: 'combo' 的 removable属性可以按条件设置，具体需求是，当只有一项时就不可以删除，否则可以删除，目前我能想到的办法是用 condition 通过复制一个combo来做，你有什么好办法吗？

**Comment by 2betop** [comment]
配置 minLength: 1
