### ISSUE TITLE
希望table实现select功能

### ISSUE THREAD

**Issue by fox-momo** [baidu/amis#2513]
#### 是否关联于某个问题吗：
页面有多个数据表格组成，点击第一个数据表格，第二个数据表格根据第一个数据表格选中的记录，进行加载和处理，以此类推。

#### 预期的解决方案：
table实现select功能，用户点击某一条记录时，把选中的记录付给指定变量，其他组件根据上下文变量进行关联操作。

![2](https://user-images.githubusercontent.com/88315383/132272301-bbc71bb5-2e27-4cb2-a067-a1b83d9d57ff.png)

**Comment by nwind** [comment]
目前有个 itemAction 可以实现点击，打算再加个选中状态

**Comment by fox-momo** [comment]
非常感谢了，我看了很久，没有想到怎么通过checkOnItemClick实现单选行的功能，有建议吗？

**Comment by nwind** [comment]
如果联动是 https://baidu.gitee.io/amis/examples/crud/item-action，如果是选择是 https://baidu.gitee.io/amis/zh-CN/components/form/transfer
