### ISSUE TITLE
在vue项目中渲染报错

### ISSUE THREAD

**Issue by break60** [baidu/amis#2514]
描述问题：
![image](https://user-images.githubusercontent.com/28628088/132290242-99d3d46d-6e08-445e-8377-d56753bd60b6.png)
window.amisRequire('amis/embed')这段代码引入报错
![image](https://user-images.githubusercontent.com/28628088/132290202-91b7426f-a8d8-41f7-879f-deeea76a9543.png)

**Comment by break60** [comment]
已解决

**Comment by OmywishO** [comment]
> 已解决

请问怎么处理的？能截个图吗
