### ISSUE TITLE
AMIS,如何支持CROS跨域请求

### ISSUE THREAD

**Issue by osenlin** [baidu/amis#252]
采用SpringBoot+AMIS作为我们的MIS系统
SpringBoot服务端部署到8082端口（已经支持跨域请求），
```
    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**")
                .allowedOrigins("*")
                .allowedMethods("*")
                .allowedHeaders("*")
                .allowCredentials(true);
    }
```
AMIS前端部署到8080端口，
但是登陆的时候会遇到跨域的问题，如下：

> Access to XMLHttpRequest at 'http://b-1.wu.net:8082/api/login' from origin 'http://b-1.wu.net:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by 2betop** [comment]
这是符合预期的啊

**Comment by 2betop** [comment]
看那个 Options 请求头是否返回了正确的 header，最好还是不要跨域，设置一下proxy 吧

**Comment by osenlin** [comment]
> 看那个 Options 请求头是否返回了正确的 header，最好还是不要跨域，设置一下proxy 吧

服务端和客户端分开部署，只能跨域了。设置Proxy？有个例子吗，服务端开发人员比较不懂前端技术

**Comment by 2betop** [comment]
我说的就是后端的 proxy 啊

**Comment by 2betop** [comment]
那你还是继续 cors 方案吧，报错是 cors header 没配置对。

**Comment by 2betop** [comment]
关了，跟amis本身没有关系

**Comment by sidrong** [comment]
我也遇到这个问题，接口用axios都能调用，但是amis调用死活不行
