### ISSUE TITLE
amis-editor二次开发

### ISSUE THREAD

**Issue by break60** [baidu/amis#2521]
描述问题：
你好，我想知道amis-editor左侧组件拖拉拽功能和组件的配置的代码是在哪个位置，能否把我拉到amis交流群，QQ：790061044
截图或视频：
![image](https://user-images.githubusercontent.com/28628088/132433197-d8808a25-baa5-41b3-b148-f386f6ec2a18.png)

**Comment by nwind** [comment]
目前控制不了，后续打算做，还没具体时间
