### ISSUE TITLE
amis-editor-demo无法运行

### ISSUE THREAD

**Issue by agileago** [baidu/amis#2526]
#### 描述问题：
找不到 `node_modules/axios/package.json`
![image](https://user-images.githubusercontent.com/11799110/132481711-dc165f0e-ad79-4a01-a5a4-ff5c373df1de.png)

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by agileago** [comment]
是 `axios` 版本的问题，超过 0.21.1 编译就不行了， 并且我看build gh-pages后  找不到 `/amis-editor-demo/scss/style_c91cc6f.css` 这个文件确定没问题？

**Comment by agileago** [comment]
又发现一个editor的问题，ya样式错乱

![image](https://user-images.githubusercontent.com/11799110/132500098-8fea53ff-da0b-4230-a9b3-161ff7b8efa5.png)

**Comment by nwind** [comment]
嗯目前 0.21.2 及以上无法编译，我们先固定一下

**Comment by nwind** [comment]
修复了，后续有空改成 webpack 好了

**Comment by agileago** [comment]
`/amis-editor-demo/scss/style_c91cc6f.css` 这个文件打包后找不到不用解决？

**Comment by agileago** [comment]
@nwind 期待赶快改成webpack的，现在这fis3得配置看着真复杂
