### ISSUE TITLE
Markdown 无法动态渲染

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#2536]
#### 描述问题：
Markdown 无法通过变量进行动态渲染。稍微改装了一下官网demo，发现并不能动态渲染。

#### 截图或视频：
![image](https://user-images.githubusercontent.com/11575908/132631979-237109a4-040d-4a32-88a3-d91c62d14dd3.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？
1.2.3
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "data":{
    "md":"# 预览啊1"
  },
  "body": {
    "type": "form",
    "data": {
      "md": "# 预览啊2"
    },
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "body": [
      {
        "type": "group",
        "body": [
          // {
          //   "type": "editor",
          //   "name": "md",
          //   "language": "markdown"
          // },
          {
            "type": "markdown",
            "value":"$md",
            "name": "md"
          }
        ]
      }
    ]
  }
}
```

4. 操作步骤
........

**Comment by nwind** [comment]
目前 value 只用做静态值，通过 name 一致就能动态

**Comment by xiahao90** [comment]
常规的操作方式是，录入完成后存入数据库。然后再浏览展示，浏览展示的时候，要么就是我上面发的demo进行data赋值进行name一致性展示，要么就是配置initApi获取数据进行展示啊。  这种方式的Schema 改怎么写呢？

**Comment by RickCole21** [comment]
https://baidu.gitee.io/amis/zh-CN/components/form/index#%E8%A1%A8%E5%8D%95%E9%A1%B9%E6%95%B0%E6%8D%AE%E5%88%9D%E5%A7%8B%E5%8C%96

或者

https://baidu.gitee.io/amis/zh-CN/components/form/formitem#%E9%85%8D%E7%BD%AE%E9%BB%98%E8%AE%A4%E5%80%BC
