### ISSUE TITLE
onClick support for  picker component

### ISSUE THREAD

**Issue by abasse** [baidu/amis#2544]
I noticed 1.3 will offer JavaScript onClick support for buttons.

It would be great to get onClick support in the picker component as well. 
So that a click on the selected value will call the defined onClick event including the item label or value who trigged it .

This would allow to present further amis dialogs or drawers  with detailed information to the item, see https://github.com/baidu/amis/issues/1616

{
        "type": "page",
        "body": {
          "type": "form",
          "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
          "body": [
            {
              "type": "picker",
              "name": "picker",
              "multiple": true,
              "label": "Picker",
              "placeholder": "Select...",
              "onClick": "whatever(thispicker.item)",
              "options": [
                {
                  "label": "Entry A",
                  "value": "a"
                },
                {
                  "label": "Entry B",
                  "value": "b"
                },
                {
                  "label": "Entry C",
                  "value": "c"
                }
              ]
            }
          ]
        }
      }

**Comment by hsm-lv** [comment]
https://github.com/baidu/amis/pull/5253
