### ISSUE TITLE
amis-editor建议amis使用peerdependencies

### ISSUE THREAD

**Issue by agileago** [baidu/amis#2545]
#### 描述问题：
`amis-editor-edmo`使用`yarn`安装的话会在editor库里面再安装一次amis,这样会导致fis在编译的时候页面会出现2个不同的amis实例，尤其是在注册自定义组件的场景会报错

#### 截图或视频：
yarn安装，页面异常

#### 如何复现（请务必完整填写下面内容）：

yarn

**Comment by nwind** [comment]
之前是，可能是不小心改了，后续改回去，先保持版本一致
