### ISSUE TITLE
使用vite打包amis时会由于动态引入css而报错

### ISSUE THREAD

**Issue by hellozqy** [baidu/amis#2547]
#### 描述问题：
请用一段清晰简洁的文字描述问题是什么...
使用vite打包amis时会由于动态引入css而报错
#### 截图或视频：
![image](https://user-images.githubusercontent.com/48118280/133023242-87b77e0d-b0cb-45f3-b17c-92e53eea4204.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm
2. amis 版本是什么？
最新
3. 操作步骤
请简单描述一下复现的操作步骤...
创建一个vite项目，选择ts+react版本，npm方式引入amis，即报错。
原因可能是因为vite基于rollup但是rollup本身就很难支持dynamic require。

**Comment by nwind** [comment]
你可以先去掉这句看看还有别的报错么，这个 css 可以自己在别的地方引入

**Comment by osindex** [comment]
目前在vite中使用编辑器需要修改源码，fis编译之后import变成了require css，vite无法识别。
```
# 需要注释以下语句
node_modules/amis/lib/components/DatePicker.js
// require("react-datetime/css/react-datetime.css");

node_modules/amis/lib/components/CodeMirror.js
// require("codemirror/lib/codemirror.css");

node_modules/amis/lib/renderers/Form/InputImage.js
// require("cropperjs/dist/cropper.css");

node_modules/amis/lib/renderers/Video.js
// require("video-react/dist/video-react.css");
```
然后可用正常启动和编辑，但是无法获得`源码`
存在以下报错 `ReferenceError: regeneratorRuntime is not defined` 应该是Monaco的冲突，内部使用可用通过`onChange: this.changeVal`实时获取渲染源码

**Comment by smadey** [comment]
vite + amis 有很多问题，所以写了个插件，可以参考一下
[vite-plugin-amis](https://gist.github.com/smadey/a5284b673c4a5f5dc2d468acc85444bc)

**Comment by agileago** [comment]
@smadey https://github.com/agileago/vite-amis
