### ISSUE TITLE
如果数据源要支持grpc和graphql ，有什么好的建议吗

### ISSUE THREAD

**Issue by AviorAlong** [baidu/amis#2556]
内部接口大部分都是grpc和graphql ，如何快速的支持这些数据源，又不用重复编码呢，加网关转发？

**Comment by avtion** [comment]
可以采用 [Envoy](https://www.envoyproxy.io/) 解决

**Comment by nwind** [comment]
grpc 必须用网关，graphql 的话可以通过 data 配置 query 的内容，不过 json 不能换行写起来是麻烦点
