### ISSUE TITLE
searchbox搜索框搜索一次之后变为只读无法修改框里的关键字

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2557]
#### 描述问题：
searchbox搜索框搜索一次之后变为只读无法修改框里的关键字
官网的示例也一样，比如输入关键字“接口”然后回车，然后就无法修改关键字了。
鼠标可以选中，使用右键“剪切”也无法改变框里的关键字。

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？
1.2.3

3. 粘贴有问题的完整 `amis schema` 代码：
[详见官网示例](https://baidu.gitee.io/amis/zh-CN/components/search-box)

4. 操作步骤
如问题描述

**Comment by belongwqz** [comment]
这大BUG放弃治疗了么？

**Comment by xsbchen** [comment]
试了一下的确是无法再搜索了
