### ISSUE TITLE
crud export excel error with image-crud的导出execl功能在有图片时不能导出

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#2559]
#### 描述问题：

1 crud组件，使用导出excel功能，无下载出现，提示错误（见下）；
2 其中，去除,有图片字段后，点击导出可出现下载        {
          "name": "tupian",
          "label": "物料图片",
          "enlargeAble": true,
          "type": "image"
        }

有图片字段时，点击excel导出时，提示的错误：
xxlb:1 Uncaught (in promise) 
Event {isTrusted: true, type: "error", target: null, currentTarget: null, eventPhase: 0, …}
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
eventPhase: 0
isTrusted: true
path: [img]
returnValue: true
srcElement: null
target: null
timeStamp: 6402.004999999917
type: "error"
__proto__: Event

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk方式 version 1.2.3

2. amis 版本是什么？
1.2.3
3. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "page",
  "title": "物料档案",
  "body": [

    {
      "type": "crud",
      "syncLocation": false,
      "pageField": "page",
      "perPageField": "page_size",
      "perPage": 10,
      "api": {
        "url": "/api/Wuliao/?page=${page}&page_size=${page_size}&search=${search_name}&fenlei_id=${fenlei_sj}&ordering=${orderDir|isMatch:'desc':'-':'' }${orderBy}",
        "headers": {
          "Authorization": "Token ${ls:my_token}"
        }
      },

      "columns": [
        {
          "name": "id",
          "label": "ID"
        },
        {
          "name": "name",
          "label": "物料名称"
        },        {
          "name": "tupian",
          "label": "物料图片",
          "enlargeAble": true,
          "type": "image"
        }
      ],
      "messages": {},
      "name": "wuliao_xxlb_crud",
      "headerToolbar": [
        "bulkActions",
        {
            "type": "export-excel",
          "name": "export_exc1",
          "label": "导出本页Excel"
          },
        {
        "type": "export-excel",
        "label": "导出全量Excel",
          "name": "export_exc2",
        "api": {
            "url": "/api/Wuliao/",
            "headers": {
                "Authorization": "Token ${ls:my_token}"
            },
          "method": "get"
        }
      },
        "switch-per-page",
        "pagination"
      ]
    }
  ]
}

4. 操作步骤
点击 导出 按钮（2个导出按钮都有同样的错误）

**Comment by nwind** [comment]
看来是图片加载报错，估计和那个 token 有关，后续加个 try 好了

**Comment by Jiangshan00001** [comment]
果然好了，多谢
