### ISSUE TITLE
日期范围选择器切换上下月箭头icon乱码问题

### ISSUE THREAD

**Issue by lxxs226** [baidu/amis#2567]
使用amis日期范围选择器出现icon乱码
原组件：
![image](https://user-images.githubusercontent.com/61958648/133532570-9f21f1c6-98bb-42a9-b0f4-3d1df8696e21.png)
使用效果：
![image](https://user-images.githubusercontent.com/61958648/133532591-15d2edfa-1c46-41fa-a5a7-9f5cd7ceb312.png)
我是通过引入js css文件使用的amis
以下是使用代码
![image](https://user-images.githubusercontent.com/61958648/133532641-7c5e05fd-26fd-4c39-ab61-2826962dd576.png)

**Comment by nwind** [comment]
用 cxd 主题

**Comment by lxxs226** [comment]
您好，我们使用的是外辱引入sdk的方式，有cxd主题么？sdk方式如何解决按钮乱码问题呢？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 中午11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] 日期范围选择器切换上下月箭头icon乱码问题 (#2567)





 
用 cxd 主题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
