### ISSUE TITLE
编排组件

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2569]
#### 是否关联于某个问题吗：
实现类似于[爱速搭接口编排](https://baidu.gitee.io/aisuda-docs/API%E5%AF%B9%E6%8E%A5/API%E7%BC%96%E6%8E%92) 这样的组件

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
爱速搭里这个功能非常定制，包括条件分支、循环等功能都是由后端实现方式决定的，因此不适合放 amis 里，后续 amis 会考虑弄个更通用的图节点功能

**Comment by dongyinuo** [comment]
> 爱速搭里这个功能非常定制，包括条件分支、循环等功能都是由后端实现方式决定的，因此不适合放 amis 里，后续 amis 会考虑弄个更通用的图节点功能

这个现在实现了吗？ @nwind
