### ISSUE TITLE
`type` field is missing in `TableColumnWithType`

### ISSUE THREAD

**Issue by Kingwl** [baidu/amis#2572]
#### 描述问题：

可以看到 TableColumnWithType 的定义为

```ts
export declare type TableColumnWithType = SchemaObject & TableColumnObject;
```

而生成的 schema 为: 
![image](https://user-images.githubusercontent.com/6831019/133588431-b93f92c6-b8d2-4849-8028-53aaeac32d88.png)

TableColumnWithType 中 AllOf 的第一个 type 不应该具有 patternProperties.

#### 如何复现（请务必完整填写下面内容）：

2. amis 版本是什么？

1.1.7. 但1.2.x也有这个问题

**Comment by 2betop** [comment]
为何不应该来着？

**Comment by Kingwl** [comment]
`SchemaObject & TableColumnObject` 的类型应该是 `SchemaObject` 的全部属性和 `TableColumnObject` 属性的并集。

目前的schema 等于是从 SchemaObject 里面 pick 了TableColumnObject 具有的的属性 然后和 TableColumnObject 又并了一下。

例如 `{ a: string} & { b: boolean }` 的类型应该是 ` {a: string, b: boolean }`
而 schema 里面的类型则是 Pick<{a: string}, 'b'> & { b: boolean }.
