### ISSUE TITLE
dialog里的ajax之后的feedback如何获取ajax的返回

### ISSUE THREAD

**Issue by dikar** [baidu/amis#2573]
#### 实现场景：
请简单描述你想要实现的原始场景，

我在dialog里发起ajax请求，请求之后有个feedback ，然后希望feedback拿到ajax的返回。

 "dialog": { 
   "actionType": "ajax",
        "feedback": {
                  "body": [
                    {
                      "type": "tpl",
                      "tpl": "${successMessage} 点击确认 ${msg}, ${data} , ${store}"
                    }
                  ],

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

当前用tpl语法拿不到ajax的返回。

同时会有个 System.message的消息会在 dialog之前的CRUD模块 最上面展示，这个如何去掉。

另外我想使用toast 怎么使用。

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by whuwangyong** [comment]
#478

**Comment by CheshireJCat** [comment]
> #478

请参考这个解决方法
