### ISSUE TITLE
ajax之后toast怎么获取ajax的返回结果

### ISSUE THREAD

**Issue by dikar** [baidu/amis#2574]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
body 里可以用 tpl 语法

···
{
    "type": "button",
    "label": "ajax 反馈弹框",
    "actionType": "ajax",
    "api": "/api/mock2/form/saveForm",
    "feedback": {
      "title": "操作成功",
      "body": "${id} 已操作成功"
    }
  }
···
