### ISSUE TITLE
JSON 设置支持对象结构来设置

### ISSUE THREAD

**Issue by dikar** [baidu/amis#2579]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

当前页面结构复杂以后，JSON会非常大，难易维护

#### 预期的解决方案：
请简单描述你想达到的效果...

期望的结果是

let page = amis.components("page",{

})

page.addComponents("toolbar",{
})

let  crud = amis.components("crud",{})

crud.addComponents("crud",{
})

page.addComponents("crud",{
})

相当于 构造JSON 按照对象方式构造。然后页面按照你们的 结构方式拼装起来。这样便于局部维护。

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

![image](https://user-images.githubusercontent.com/251375/133718535-45f94e2f-cbf6-452b-a21b-b1993937be6f.png)

**Comment by nwind** [comment]
1. 自己用函数实现并组装。
2. 使用可视化编辑器，在可视化编辑器中点击某个具体组件就只看到那个组件的代码。
