### ISSUE TITLE
怎么配置fis3打包有dist静态web文件

### ISSUE THREAD

**Issue by baozai6795** [baidu/amis#258]

**Comment by baozai6795** [comment]
你好，我们想用fis3打包有dist静态文件，但是amis这个项目是不是要修改配置文件，怎么修改呐

**Comment by baozai6795** [comment]
就是打包后不依赖fis3，直接怼到nginx配置里直接跑

**Comment by 2betop** [comment]
产出代码是 commonjs 规范的，不做任何处理肯定是跑不起来的，需要其他工具才能跑起来比如: fis3、webpack 或者别的

**Comment by 2betop** [comment]
如果你没有修改源码的需求，可以用 sdk 版本

**Comment by timiil** [comment]
能否通过:
```
fis3 release -d ./output
```

这样，把amis编译构建部署到一个文件夹，这个文件夹再用nginx之类的静态服务器对外伺服？
