### ISSUE TITLE
saveImmediately即时保存后会导致页面重新刷新

### ISSUE THREAD

**Issue by 512067461** [baidu/amis#2585]
#### 实现场景：
可以通过配置来实现saveImmediately即时保存后页面是否刷新

#### 存在的问题：
saveImmediately即时保存后会导致页面重新刷新

#### 当前方案：
 const sendData = createObject(data, rows);
      store
        .saveRemote(quickSaveItemApi, sendData)
        .then(() => {
          reload && this.reloadTarget(reload, data);
**是不是每次都会调用搜索查询？增加一个reload 校验是否可以实现？reload &&  this.search(undefined, undefined, true, true);  **
          this.search(undefined, undefined, true, true);
        })
        .catch(() => {
          resetOnFailed && this.control.reset();
        });

**Comment by 2betop** [comment]
quickEdit 支持配置 reload 属性如：

```
{
    "name": "grade",
    "label": "CSS grade",
    "quickEdit": {
        "mode": "inline",
        "type": "select",
        "size": "xs",
        "reload": "None", // 一个不存在的目标，则会跳过刷新
        "options": [
            "A",
            "B",
            "C",
            "D",
            "X"
        ],
        "saveImmediately": {
            "api": "/api/mock2/sample/$id"
        }
    }
}
```

配置一个不存在的目标，则会跳过刷新
