### ISSUE TITLE
toast使用文档

### ISSUE THREAD

**Issue by dikar** [baidu/amis#2587]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

希望有toast的使用文档

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

拷贝样例中的CRUD组件 ，但是新增之后 toast位置和样式都不一样，希望手工控制

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

![image](https://user-images.githubusercontent.com/251375/133892911-13d423ed-13ee-4360-8d1a-ad4d39e8a058.png)

**Comment by nwind** [comment]
仔细看文档，漏了这两个组件
```
 <ToastComponent theme={theme} key="toast" position={'top-right'} />
 <AlertComponent theme={theme} key="alert" />
```

**Comment by dikar** [comment]
这2个组件，能否在API 调用之后绑定，我这边测试了 alert与toast 或者 messages 都不行 。我也看到有人提issues 说事例中 ajax 返回后显示toast失效 （貌似老版本可以显示，另外只会显示服务端返回的msg，那么这个messages组件还有什么意义呢）

**Comment by dikar** [comment]
这2个组件，能否在API 调用之后绑定，我这边测试了 alert与toast 或者 messages 都不行 。我也看到有人提issues 说事例中 ajax 返回后显示toast失效 （貌似老版本可以显示，另外只会显示服务端返回的msg，那么这个messages组件还有什么意义呢）
