### ISSUE TITLE
form组件和actionType=ajax组件能否对接alert或者toast组件

### ISSUE THREAD

**Issue by dikar** [baidu/amis#2589]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

我想实现表单提交 ，不管是通过form  还是 ajax方式提交，都能自己控制显示 alert 或者toast

当前表单提交默认显示 toast 。不能手工控制。

#### 预期的解决方案：
请简单描述你想达到的效果...

form以及ajax 支持 后续绑定alert 或者 toast

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by CheshireJCat** [comment]
可以在 api 中自定义message 内容，置空就不提示了
也可以在 提交成功的事件中自己 toast 提示
```
"api": {
    "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "method": "get",
    "dataType": "json",
    "requestAdaptor": "",
    "adaptor": "",
    "messages": {
      "success": "",
      "failed": ""
    }
  },
```
