### ISSUE TITLE
amis文档搜索框样式错乱

### ISSUE THREAD

**Issue by iceqing** [baidu/amis#2593]
#### 描述问题：
`amis`文档`搜索框`样式错乱
文档链接地址：https://aisuda.github.io/amis-1.1.7/zh-CN/docs/index

#### 截图或视频：
异常情况：
![image](https://user-images.githubusercontent.com/39587710/134275877-add8fb35-5194-4d7b-98c9-425fd333f168.png)

正常情况：
![image](https://user-images.githubusercontent.com/39587710/134275930-5b766aa5-d3de-478d-a0b8-d66c41b38279.png)

#### 如何复现（请务必完整填写下面内容）：

文档链接地址：
https://baidu.github.io/amis/zh-CN/docs/index
https://aisuda.github.io/amis-1.1.7/zh-CN/docs/index

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？
1.2.3 

3. 粘贴有问题的完整 `amis schema` 代码：
官网示例即可复现
文档链接地址：https://aisuda.github.io/amis-1.1.7/zh-CN/docs/index

4. 操作步骤
5.官网示例即可复现
文档链接地址：
https://baidu.github.io/amis/zh-CN/docs/index
https://aisuda.github.io/amis-1.1.7/zh-CN/docs/index

**Comment by nwind** [comment]
嗯我们也发现了正打算修
