### ISSUE TITLE
input-number 验证提示问题

### ISSUE THREAD

**Issue by lin1005q** [baidu/amis#2597]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

目前number组件,当输入字母时,光标离开会删除字母,如何设置不自动删除,而是进行验证失败提示处理.
目前只能是修改成input-text处理,这样的话提交前还得将字符类型修改为数字类型

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
目前故意这样做的，是为啥要有字母？

**Comment by lin1005q** [comment]
例如一个端口的输入框,如果使用了number组件,设置了最大8888,最小8000. 理论上客户需要输入这个范围内的端口号,但是客户随意输入一个数值,只要超过8888,输入框自动变成8888.这个客户认为应该是提示错误,而不是直接修改.



字母是因为客户那边有边界测试.

目前现在就是前面说的使用input-text组件,会有error提示,但是提交前requestadaptor要parseInt一下,也挺麻烦的.

不知道有没好的解决方案.
