### ISSUE TITLE
initApi可否不使用url, 而使用自己的service呢?

### ISSUE THREAD

**Issue by g770728y** [baidu/amis#26]
原因: \
基于老系统进行改造, 不方便重写后台接口
3x

**Comment by 2betop** [comment]
fetch 方法是自己实现的，你完全可以 请求完后.then 做适配的

**Comment by g770728y** [comment]
看到了, 在开源渲染器一节.
今天看了一天文档, 感觉amis真是太周到了!
第一次看到能够把普通CRUD考虑得这么完善的, 感觉各种情况都考虑到了, 真是太赞了!!!!
👍 👍 👍
