### ISSUE TITLE
sdk使用方式下，使用cxd主题，日期选择器左右切换上下月箭头乱码

### ISSUE THREAD

**Issue by lxxs226** [baidu/amis#2600]
#### 实现场景：
在sdk引入js文件的方法下，引入了cxd主题的css，想实现使用crud组件增加日期选择器。

#### 存在的问题：
之前提问：日期选择器切换上下月箭头乱码，收到回复使用cxd主题，改为cxd主题后仍有乱码情况
![image](https://user-images.githubusercontent.com/61958648/134438439-3a7dc398-852b-4cde-90be-56e3f35a85b4.png)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
1、引入cxd.css文件
![image](https://user-images.githubusercontent.com/61958648/134438536-9562ed8b-c410-4bf1-ac45-a752babd8065.png)
![image](https://user-images.githubusercontent.com/61958648/134438626-e915b41a-a954-46fa-931d-c9f23c1614a8.png)

2、切换主题
![image](https://user-images.githubusercontent.com/61958648/134438670-db3dbc9c-fe64-4bee-8126-76632ffe3868.png)

3、使用日期选择器
![image](https://user-images.githubusercontent.com/61958648/134438806-c2946015-7bac-47f1-8b7c-3aa90e23426a.png)

```

**Comment by nwind** [comment]
页面难道不是 utf8，没复现，十分钟后试试 https://github.com/baidu/amis/blob/gh-pages/sdk.tar.gz

**Comment by lxxs226** [comment]
页面使用的是utf-8

尝试了重新下载,更新css文件还是没有效果，发现cxd.css有错误信息，，
***@***.*** “UTF-8”放置在了css文件开头，，不报错了，但日期选择器箭头仍乱码。
还有什么解决方法么？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] sdk使用方式下，使用cxd主题，日期选择器左右切换上下月箭头乱码 (#2600)





 
页面难道不是 utf8，没复现，十分钟后试试 https://github.com/baidu/amis/blob/gh-pages/sdk.tar.gz
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lxxs226** [comment]
> 页面难道不是 utf8![image](https://user-images.githubusercontent.com/61958648/134469063-6c736c76-1ec9-4603-bde2-734bd5713fe0.png)没复现，十分钟后试试 https://github.com/baidu/amis/blob/gh-pages/sdk.tar.gz

页面使用的是utf-8
![image](https://user-images.githubusercontent.com/61958648/134469015-659c00a7-3427-4f1b-98ec-fcab269ad50f.png)
尝试了重新下载,更新css文件还是没有效果，发现cxd.css有错误信息（有两处）
![image](https://user-images.githubusercontent.com/61958648/134469039-bbfacbac-b497-42ed-9a76-d42012bf670a.png)

将@charset “UTF-8”放置在了css文件开头
![image](https://user-images.githubusercontent.com/61958648/134469063-6c736c76-1ec9-4603-bde2-734bd5713fe0.png)
不报错了，但日期选择器箭头仍乱码。
还有什么解决方法么？

**Comment by nwind** [comment]
没法复现呢，浏览器和版本是啥？另外官网能复现么 https://baidu.gitee.io/amis/zh-CN/components/form/input-date

**Comment by lxxs226** [comment]
使用的是chrome浏览器

官网没有出现&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] sdk使用方式下，使用cxd主题，日期选择器左右切换上下月箭头乱码 (#2600)





 
没法复现呢，浏览器和版本是啥？另外官网能复现么 https://baidu.gitee.io/amis/zh-CN/components/form/input-date
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lxxs226** [comment]
使用的是chrome浏览器
![image](https://user-images.githubusercontent.com/61958648/134600150-a7683c9d-6351-4124-a535-e44c4d816af5.png)
官网暂未发现

**Comment by nwind** [comment]
主要是没法复现，发个能复现的例子压缩包吧
