### ISSUE TITLE
组件文档属性表内容不全

### ISSUE THREAD

**Issue by imooni** [baidu/amis#2617]
#### 实现场景：
文档属性表展示属性不全，很多字段 （例如 CRUD.columns.label）只在示例中有，并未在属性表中出现

#### 当前方案：

或许是文档看的不够仔细，又或者这种情况在别处有说明

**Comment by xl-wenqiang** [comment]
看代码吧，可读性蛮高的

**Comment by nwind** [comment]
其实是在 https://baidu.gitee.io/amis/zh-CN/components/table?page=1#%E5%88%97%E9%85%8D%E7%BD%AE 里，只是 CRUD 文档太长了容易遗漏，一会补一下
