### ISSUE TITLE
1.2.3版本tree-select组件使用hideNodePathLabel无效

### ISSUE THREAD

**Issue by xl-wenqiang** [baidu/amis#2618]
#### 描述问题：
1.2.3版本tree-select组件使用hideNodePathLabel无效

#### 截图或视频：
![image](https://user-images.githubusercontent.com/22266819/134803780-02ca572f-fc80-4e99-b0eb-4accbdc72644.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 

2. amis 版本是什么？
1.2.3

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  type: "tree-select",
  name: "classId",
  label: "所属班级",
  source:
    "/api/exercitation/general/GetTreeSelectAllAsync?selectEnum=2",
  required: true,
  hideNodePathLabel: true,
},

```

**Comment by 2betop** [comment]
近期加入的功能，用 amis@beta 或者等下一个正式版本
