### ISSUE TITLE
当表格出现横向滚动条时，拖拽列失效

### ISSUE THREAD

**Issue by SheenaghF** [baidu/amis#2638]
#### 描述问题：
当表格出现横向滚动条时，拖拽列失效
#### 截图或视频：
正常时
![image](https://user-images.githubusercontent.com/33509031/135411583-e30a3cf1-b313-4fbb-96e5-22e90ec08b36.png)
拖拽后
![image](https://user-images.githubusercontent.com/33509031/135411678-3cecc2ca-c344-4cea-8992-1dca31011967.png)
出现滚动条时
![image](https://user-images.githubusercontent.com/33509031/135411739-6b692fba-1a49-4dbb-a32c-62bd17f05f50.png)
没有生效
![image](https://user-images.githubusercontent.com/33509031/135411798-99c2810a-c86a-4693-8b05-2e72d51973ae.png)

**Comment by nwind** [comment]
没复现，如果有问题就再开
