### ISSUE TITLE
建议static-mapping控件增加绑定空值的功能

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#2642]
#### 是否关联于某个问题吗：
当前mapping组件只能绑定有1、2、3这种有固定值的映射，但是有时候后端返回的某个字段的值是空的，尚未设置此字段的值，因此无法绑定映射（使用default也无法绑定空值）

#### 预期的解决方案：
增加mapping对于null或者""空值的绑定。

 {
              "type": "static-mapping",
              "label": "是否符合",
              "name": "isOk",
              "map": {
                “null”: "<span class='label label-danger'>待审核</span>",     //建议增加对空值的绑定
                "0": "<span class='label label-danger'>不符合</span>",
                "1": "<span class='label label-success'>符合</span>"
              }
},

**Comment by 2betop** [comment]
目前可以用 '*': "xxx" 来命中其他
