### ISSUE TITLE
CURD组件以及table组件可否支持条件渲染

### ISSUE THREAD

**Issue by spemed** [baidu/amis#2652]
#### 是否关联于某个问题吗：
当后端返回枚举值类型时，前端需要将其转换为人类可读的标签，如isValid=1 ==> 可用,isValid=0 ==> 不可用

#### 预期的解决方案：
提供一个表达式属性，可以根据枚举值动态计算标签值

#### 任何附加信息：
![image](https://user-images.githubusercontent.com/37761110/136008054-6d9c401b-7bf0-4bb5-aa69-1596092d0661.png)

**Comment by spemed** [comment]
找到办法了，在columns的元素中使用
`{
                    "type": "page",
                    "data":{
                        "isValid":"${is_valid}"
                    },
                    "body":[
                        {
                            "type": "tpl",
                            "tpl": "<%= data.isValid == 1 ?  '是' : '否' %>"
                        }
                    ],
                    "label":"小程序是否展示",
                    "sortable":true
                }`

**Comment by BeMxself** [comment]
试试mapping组件
