### ISSUE TITLE
表格冻结列

### ISSUE THREAD

**Issue by woody0907** [baidu/amis#2654]

**Comment by 2betop** [comment]
列有冻结功能，https://baidu.gitee.io/amis/examples/crud/fixed

**Comment by 2betop** [comment]
应该能满足需求了，有问题再开

**Comment by BrentHuang** [comment]
@2betop 可以像设置显示/隐藏哪些列那样，让用户自己设置哪些列冻结在左边、哪些列冻结在右边吗？
