### ISSUE TITLE
在node_modules里面使用sdk加载不到thirds这个目录

### ISSUE THREAD

**Issue by SheenaghF** [baidu/amis#2655]
#### 描述问题：
在node_modules里面使用sdk加载不到thirds这个目录

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？
1.3.0

3. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "body": [
      {
        "type": "json-editor",
        "name": "editor",
        "disabled": true,
        "label": "JSON编辑器"
      }
    ]
  }
}
4. 操作步骤
![image](https://user-images.githubusercontent.com/33509031/136500041-a7007ead-be46-42e5-b336-5b6d0321727c.png)

**Comment by joker77877** [comment]
都快一年了，这个问题不能修复一下吗，vite也是主流工具了

**Comment by joker77877** [comment]
> #### 描述问题：
> 在node_modules里面使用sdk加载不到thirds这个目录
> 
> #### 截图或视频：
> 可以的话，尽可能提供截图或视频来补充描述你的问题...
> 
> #### 如何复现（请务必完整填写下面内容）：
> 1. 你是如何使用 amis 的？
>    npm
> 2. amis 版本是什么？
>    1.3.0
> 3. 粘贴有问题的完整 `amis schema` 代码：
>    {
>    "type": "page",
>    "body": {
>    "type": "form",
>    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
>    "body": [
>    {
>    "type": "json-editor",
>    "name": "editor",
>    "disabled": true,
>    "label": "JSON编辑器"
>    }
>    ]
>    }
>    }
> 4. 操作步骤
>    ![image](https://user-images.githubusercontent.com/33509031/136500041-a7007ead-be46-42e5-b336-5b6d0321727c.png)

请教一下之前这个问题解决了吗

**Comment by Lisheri** [comment]
请问上述问题解决了吗, vite构建vue3项目, skd内部的引入逻辑是这样的
![6e7597a1-419d-42ad-a1e5-9f5730b71872](https://github.com/baidu/amis/assets/49238808/f18c351d-5530-4699-94cd-c6a355f97a2a)

**Comment by 2betop** [comment]
用 vite-plugin-static-copy 直接将 sdk 文件复制过去，不要尽心二次编译。

参考 ： https://github.com/aisuda/vue2-amis-demo 的 main 分支，可以正常渲染

**Comment by Lisheri** [comment]
牛逼大哥, 非常完美, 已经解决了~

**Comment by 2betop** [comment]
这个 issue 先关了，有问题再开

**Comment by Lisheri** [comment]
很丝滑~感谢老哥~

**Comment by qiufeng520** [comment]
> 牛逼大哥, 非常完美, 已经解决了~
怎么解决的。我参考了demo使用插件还是不行，报一样的错。我的环境是vue3 + vite6，copy插件使用的是3.xx，1.x不兼容vite6好像
