### ISSUE TITLE
1.3.1版本表单提交时请求参数不完整

### ISSUE THREAD

**Issue by joe-zhan** [baidu/amis#2658]
#### 描述问题：
表单里的service组件返回的数据，在表单提交的时候没有带上

#### 截图或视频：
form里加了个service，返回了这样的数据，
![image](https://user-images.githubusercontent.com/3829984/136520138-16ef803d-7435-4d15-9144-a2ed9c920576.png)
在1.3.1版本的SDK中，表单提交的时候没有带上service组件返回的数据，
![image](https://user-images.githubusercontent.com/3829984/136520174-b4227015-4ef9-4eac-aba2-ed137a10efd6.png)
在1.2.3版本的SDK里，表单提交会把service组件返回的数据全部带上
![image](https://user-images.githubusercontent.com/3829984/136520197-950a0c7c-3e0d-49ea-b39e-156b2178c4e5.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？
1.3.1
3. 粘贴有问题的完整 `amis schema` 代码：
```

```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/3525 中解决了这个问题，但是有可能后续还会调整，感觉最好可能是把数据merge到 items 里面的对线个里面
