### ISSUE TITLE
请问如何得到combo数组当前 index

### ISSUE THREAD

**Issue by Leonard-Li777** [baidu/amis#266]
```
{
    type: 'combo',
    name: 'supplierAccounts',
    label: '供应商账户',
    removable: true,
    minLength: 1,
    multiple: true,
    controls: [
      { type: 'hidden', name: 'id' },
      {
        name: 'accountName',
        type: 'text',
        placeholder: '请输入帐户名称',
        disabledOn: 'Boolean(data.supplierAccounts[index].id)', //  请问这里如何得到数组当前 index
      },
      {
        name: 'remark',
        type: 'text',
        placeholder: '请输入账户备注',
      },
    ],
  },
```

**Comment by 2betop** [comment]
直接判断 disabledOn: 'this.id'

**Comment by 2betop** [comment]
或者 'disabledOn: 'data.id''

**Comment by Leonard-Li777** [comment]
'disabledOn: 'data.id''  和 disabledOn: 'this.id' 都不行
反倒是我上面的代码有效，原来index是有效的，我先没试过，不知道！

**Comment by 2betop** [comment]
https://github.com/baidu/amis/blob/master/src/renderers/Form/Combo.tsx#L398

应该是有效的，回头我验证一下

**Comment by 2betop** [comment]
不要意思，现在才回复。试了下是可以了的。

![image](https://user-images.githubusercontent.com/2698393/68009202-4f89e880-fcbc-11e9-818e-b68d8de3c640.png)

我手动吧 id 改成了 1 后，添加是禁用状态。

如果只是想要行数据参与计算，直接拿 this.id 就可以。如果一定要那 index，变量名就是 index，你可以来个 `{type: 'tpl', tpl: '${index}'}` 来验证。


另外这有 demo https://amis.baidu.com/docs/examples/form/combo#others

**Comment by 2betop** [comment]
有问题再开
