### ISSUE TITLE
希望把dialog不依赖行为按钮，独立使用

### ISSUE THREAD

**Issue by tangjion** [baidu/amis#2660]
在日常开发者，有如下场景，需要dialog展示：
1、ajax返回后需要通过dialog来展示一些信息，如果使用按钮，交互不太友好
2、进入某个页面时，需要用dialog来展示一些提示信息

**Comment by joe-zhan** [comment]
我是service里面包了一个"type": "dialog"的组件，然后有visibleOn条件，这样当service请求返回值符合visibleOn条件就可以弹出dialog， 同理我觉得dialog组件应该是可以独立在页面上使用的

**Comment by BeMxself** [comment]
> 请问, 没有结合本身 react 的页面里有个自定义的组件, 这个组件点击了 onClick 怎么去触发弹出 amis 的 dialog 啊@BeMxself
你可以尝试访问amis渲染后返回的scope对象，这个scope对象里可以修改数据，也可以拿到某个具名amis组件的实例，结合@joe-zhang 的做法应该就可以实现了，但是对话框的返回和数据等怎么绑定我就不清楚了。

如果你的这个自定义组件是嵌在amis里可以尝试一下能不能在自定义组件中拿到ScopedContext

**Comment by BeMxself** [comment]
> 请问, 没有结合本身 react 的页面里有个自定义的组件, 这个组件点击了 onClick 怎么去触发弹出 amis 的 dialog 啊@BeMxself

你可以尝试访问amis渲染后返回的scope对象，这个scope对象里可以修改数据，也可以拿到某个具名amis组件的实例，结合@Joe-Zhang 的做法应该就可以实现了，但是对话框的返回和数据等怎么绑定我就不清楚了。

如果你的这个自定义组件是嵌在amis里可以尝试一下能不能在自定义组件中拿到ScopedContext

**Comment by tangjion** [comment]
> 我是service里面包了一个"type": "dialog"的组件，然后有visibleOn条件，这样当service请求返回值符合visibleOn条件就可以弹出dialog， 同理我觉得dialog组件应该是可以独立在页面上使用的

我试了，但是这样dialog好像是无法通过关闭按钮来进行关闭的

**Comment by 1562217380** [comment]
使用是可以独立使用的，但是无法关闭，触发关闭会报错，这个是不是框架内部本身存在的bug呢？报错信息如下：
![image](https://user-images.githubusercontent.com/44864844/170176515-4e7d5df8-66bc-4a42-8705-d5cf080b6fe0.png)

**Comment by 2betop** [comment]
> 请问, 没有结合本身 react 的页面里有个自定义的组件, 这个组件点击了 onClick 怎么去触发弹出 amis 的 dialog 啊@BeMxself

自己写的组件可以直接  this.props.onAction(null, {actionType: 'dialog', dialog: {},{/*上下文数据*/}}) 这样触发一个弹窗动作，amis 内部会拦截弹出一个弹窗。

amis的弹窗渲染器，不能单独使用，好像也没有业务场景需要它自己自动弹出来
