### ISSUE TITLE
嵌套crud 组件  勾选问题

### ISSUE THREAD

**Issue by HaoWang81** [baidu/amis#2664]
#### 描述问题：
在使用 嵌套crud 组件时,勾选 子 数据时 
1.第一次点击无法选中,连击两次可选择,
2.取消勾选,对应的pick组件不会自动取消

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...
![1633745468](https://user-images.githubusercontent.com/20764572/136640294-7878d2d1-66c2-4663-a9aa-2d61b23dbadf.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？
1.2.1

3. 粘贴有问题的完整 `amis schema` 代码：
直接设置多选属性,就可呈现该问题

4. 操作步骤
嵌套crud 配合 picker组件 即可呈现

**Comment by 2betop** [comment]
请更新最新的版本
