### ISSUE TITLE
custom自定义组件获取不到表单initApi返回字段的值

### ISSUE THREAD

**Issue by sanye4639** [baidu/amis#2665]
#### 描述问题：
自定义组件custom设置了name为content，但是无法获取到表单初始化接口返回的content内容。

#### 截图或视频：
![image](https://user-images.githubusercontent.com/30991208/136640960-ff5bc251-4326-4c17-bef8-6091f3886ade.png)
![image](https://user-images.githubusercontent.com/30991208/136640997-639a1979-73ec-41c7-a1f8-07e1cc78df96.png)
![Uploading image.png…]()

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？
1.1.6

3. 粘贴有问题的完整 `amis schema` 代码：
{
                                          "name": "content",
                                          "requiredOn": "this.type == 1",
                                          "type": "custom",
                                          "label": "内容",
                                          "id": "wangEditor",
                                          "onMount": "console.log(value);console.log(props);var E = window.wangEditor;var editor = new E('#wangEditor');editor.config.uploadFileName='file';editor.config.uploadImgServer='/wangEditor/upload/image';editor.config.uploadVideoName='file';editor.config.uploadVideoServer='/wangEditor/upload/video'; editor.config.showFullScreen = true;editor.config.onblur=function(newHtml){console.log(newHtml);console.log(editor.txt.html());onChange(newHtml);};editor.create();var oldContent = props.data.content;editor.txt.html(oldContent);"
                                        }
4. 操作步骤

**Comment by 2betop** [comment]
custom 不是表单项组件，所以没办法直接配置 name 就能通过 props.value 拿到值，只能 props.data.xxx 去拿

**Comment by mizhicangyue** [comment]
同样遇到这个问题了，通过props.data的去拿一样 无法及时获取到initApi返回的结果 这个值拿不到
