### ISSUE TITLE
页面和弹窗都使用增删改查分页问题

### ISSUE THREAD

**Issue by ryonchen** [baidu/amis#2667]
#### 实现场景：
页面和弹窗都使用了增删改查表单和分页，我在页面操作分页，例如选了第二页，弹窗里面的组件也变成了第二页，因为他们都用到page变量，反之在弹窗里面操作分页，页面也会修改，我想实现的场景是页面和弹窗的分页变量参数分开

#### 存在的问题：
我想实现的场景是页面和弹窗的分页变量参数分开

**Comment by nwind** [comment]
可以在弹框里的 CRUD 设置 "syncLocation": false

说起来弹框里感觉是应该默认 false
