### ISSUE TITLE
打包体积过大问题请教

### ISSUE THREAD

**Issue by xiaoqingb** [baidu/amis#2669]
#### 实现场景：
目前已经用amis实现一个小系统，以微前端的形式嵌入

#### 存在的问题：
但是打包整个js文件到cdn上，体积太大了，单单引入amis就占了8成以上的体积，发现有一些依赖并不是真正需要使用到的，amis主动引入了，这有可以优化的方案吗，或者有其他打包方案上的建议

![image](https://user-images.githubusercontent.com/49091613/136651847-9ceaf9d9-537a-4aee-afac-eed9f824c327.png)

![image](https://user-images.githubusercontent.com/49091613/136651882-6d09e412-1cef-4735-bc46-561e851e84b6.png)

**Comment by xiaoqingb** [comment]
![image](https://user-images.githubusercontent.com/49091613/136654402-c32b6396-a08f-431d-8be9-d55aec0d188a.png)
剔除掉这几个，体积已经剩下6mb了
![image](https://user-images.githubusercontent.com/49091613/136654428-ee0f460c-5d61-431e-80e6-be7a6c266893.png)

**Comment by nwind** [comment]
这些都是异步加载的，估计是 tsconfig.json 里的问题，要有这些

```
"moduleResolution": "node",
"module": "esnext",
"strict": true,
"importHelpers": true
```

**Comment by rumunanfeng** [comment]
> 这些都是异步加载的，估计是 tsconfig.json 里的问题，要有这些
> 
> ```
> "moduleResolution": "node",
> "module": "esnext",
> "strict": true,
> "importHelpers": true
> ```

有这些配置，但也并不能减少包的体积啊
