### ISSUE TITLE
表单下拉框select的远程获取source无法动态添加下拉框选项值

### ISSUE THREAD

**Issue by user-huage** [baidu/amis#2678]
表单下拉框select用source属性实现远程访问API获取，能拿到规定格式的JSON，但无法渲染到下拉框
```
前端代码部分：
{
     "type": "page",
     "body": [{'type':'form','name':'sample-edit-form','api':'http://127.0.0.1:3000/api/insertstore',
                    'controls': [{'type':'select','name':'Brand','label':'品牌','required':true,'source':'http://127.0.0.1:3000/api/Brand'}]}]
}
http://127.0.0.1:3000/api/Brand请求返回结果
{"data":{"options":[{"value":"RB","label":"RayBan"},{"value":"LC","label":"Lenscrafters"}]},"status":200,"msg":""}
```

**Comment by 2betop** [comment]
用法没问题，看看是不是网络请求出问题了，比如说跨域了？

**Comment by user-huage** [comment]
> 用法没问题，看看是不是网络请求出问题了，比如说跨域了？

同样的代码，我用options属性就可以渲染下拉框，用souce属性就不行，看了F12，http://127.0.0.1:3000/api/Brand这个请求是200，能拿到数据

**Comment by user-huage** [comment]
> status 应该是 0

ok，谢谢大哥，问题解决了，status改为0就可以了，还有一个问题我想问下，我项目搞了个axios请求拦截器，发现没法拦截amis发送的axios请求，我该怎么拦截amis发送的axios请求

**Comment by user-huage** [comment]
> amis 的所有请求通过 env.fetcher 来发出的，直接在这里面实现拦截功能就好。
> 
> 文档： https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started#fetcher-%E5%BF%85%E9%A1%BB%E5%AE%9E%E7%8E%B0- 参考： https://github.com/baidu/amis/blob/master/examples/embed.tsx#L252-L320

好的谢谢大哥

**Comment by 2betop** [comment]
统一入口？或者寸一个fetcher 多处引用一个

**Comment by user-huage** [comment]
> import {alert} from 'amis'

好的，谢谢大哥
