### ISSUE TITLE
How to use Javascript Object instead of JSON Pages

### ISSUE THREAD

**Issue by phxgbl** [baidu/amis#2679]
Amis multiple page sample https://github.com/aisuda/amis-admin uses JSON pages . I would like to know how to use JS Object instead of JSON, also how to load those ?

**Comment by phxgbl** [comment]
@nwind thank you for the response . Yes, I was looking for onClick like custom event handlers, Then I found this commit [](https://github.com/baidu/amis/commit/cf0ed6b4619ca4f91679da16d25a39f3bac6108c). Only onClick is supported?

**Comment by nwind** [comment]
Yes, only onClick is supported for now.

**Comment by nwind** [comment]
Close in #4866
