### ISSUE TITLE
input-tag多选类型的组件设置默认数据value问题。

### ISSUE THREAD

**Issue by jeromehan** [baidu/amis#2688]
#### 描述问题：
由于设数据映射只支持用户通过${xxx}或$xxx获取当前数据链中某个变量的值，其实渲染的都是字符串。设置设置数组或者对象的值的时候是没有办法的

**Comment by hsm-lv** [comment]
没太明白，可以贴在具体case吗？

**Comment by jeromehan** [comment]
> 没太明白，可以贴在具体case吗？

<img width="981" alt="image" src="https://github.com/baidu/amis/assets/19773879/ea4d6151-ae63-4b52-b549-33052642bf4f">
比如这个组件我想设置多个默认值，或者在其他组件也可以支持设置设置数组或者对象

**Comment by jeromehan** [comment]
看来近2年增加了不少功能，之前用的时候，遇到比较多问题，所以放弃了
