### ISSUE TITLE
低代码集成到react希望支持按需加载

### ISSUE THREAD

**Issue by jeromehan** [baidu/amis#2689]
目前编辑器代码所有都添加进去

**Comment by nwind** [comment]
编辑器？还是 amis？amis 就是按需的，看看 https://github.com/aisuda/amis-react-starter

**Comment by nwind** [comment]
目前只有几个体积较大的库异步加载，其它都内嵌，有很多相互依赖导致优化空间不大，还不如一张图的大小，因此不打算这样做
