### ISSUE TITLE
编辑器的页面配置能否增加一个背景色设置

### ISSUE THREAD

**Issue by lhkg1988** [baidu/amis#2696]
#### 是否关联于某个问题吗：
因为我没办法实现移动端页面的背景色设置，我们把编辑器嵌入到业务系统中，让运营人员自己去配置页面，在配置移动端活动页时，就需要配置页面的颜色，现在改代码是可以实现，但是没办法要求运营人员也去修改json代码。

#### 预期的解决方案：
希望可以在编辑器右侧的编辑位置加一个背景色的样式的配置

<img width="830" alt="1634099367(1)" src="https://user-images.githubusercontent.com/7578173/137067471-ea039b13-b6b8-4eba-a1c8-1e2967e78fef.png">

**Comment by wibetter** [comment]
目前page已增加外观配置面板，但背景色被page中的aside、content等子元素覆盖，需要将page子元素的默认背景色剔除。
