### ISSUE TITLE
请问crud渲染器如何normalize通过api配置获取的数据供columns使用？

### ISSUE THREAD

**Issue by unsad** [baidu/amis#27]
比如crud的table类型，每个columns渲染器似乎只能获取到原始data，有办法在curd渲染器这一层normalize吗？

**Comment by RickCole21** [comment]
每一个api请求都可以使用对象类型配置，像这样：
```
api: {
    method: 'get',
    url: '/api/xxx',
    data:{
        x: 'xxx'
    },
    // 这里可以配置请求接收适配器
    adaptor: (payload, response) => {
        let data = payload.data;
        // ...对data进行一些normalize操作
        
        return {
              ...payload,
              data
        }
    },
    // 这里配置发送适配器
    requestAdaptor:(api)=>{
        // 这里可以在请求前对api进行改写
        return {
              ...api,
              data:{
                  ...api.data,
                  other: 'somedata' // 加点其他数据
              }
        }
    }
}
```
但是请注意，处理后的数据结构要遵循amis的规范才可以正常工作
例如crud的结构是：
```
{
    status:0,
    msg:'xxx',
    data:{
        items:[], // 这里列表数据
        count: 10,
        page: 1,
        pageSize: 10
        ...其他
    }
}
```

**Comment by unsad** [comment]
@RickCole21 谢谢解答，不过有个问题是，配置文件是JSON格式的，从JSON解析到对象的过程中，类似于adaptor这层函数类型的配置是怎么处理的呢？

**Comment by 2betop** [comment]
1. 配置如果使用 json 文件来配置的话，不支持 function，所以这种情况只能用 js 来配置 json
2. 如果一定要用json，只能在统一的入口 fetcher 那一层，做适配了，根据 api 地址不同，写不同的适配逻辑。

**Comment by unsad** [comment]
> 1. 配置如果使用 json 文件来配置的话，不支持 function，所以这种情况只能用 js 来配置 json
> 2. 如果一定要用json，只能在统一的入口 fetcher 那一层，做适配了，根据 api 地址不同，写不同的适配逻辑。

我的想法是这样，要进一步提高生产效率的话还是需要做一套可视化编辑器处理配置文件，那么配置文件选择json入库存储应该是比较合适的选择，但管理系统对接的api结构不统一，normailize这一层又比较频繁，这种场景下的解决方案只有在统一入口的fetcher做适配吗？

**Comment by 2betop** [comment]
嗯，目前平台做了个适配器配置的东西，就是走统一的 fetcher 那的钩子
