### ISSUE TITLE
编辑表单时，部份丢失表单数据

### ISSUE THREAD

**Issue by Leonard-Li777** [baidu/amis#271]
![image](https://user-images.githubusercontent.com/16662626/66460130-e2ae7480-eaa8-11e9-9da5-f87c70acf289.png)

**Comment by 2betop** [comment]
发一下 schema 配置？

**Comment by 2betop** [comment]
可能这个数据你不是用 form 的initApi 拉取的吧，而是 page 的initApi，然后这个时候可能需要给表单项配置个默认值空才会从顶级同步下来，这个设定确实有问题，但是没有想到好的实现方案。

**Comment by 2betop** [comment]
这个先关掉了，后续关注这个 https://github.com/baidu/amis/issues/321
