### ISSUE TITLE
crud组件，如果图片不存在，无法导出

### ISSUE THREAD

**Issue by koala-wei** [baidu/amis#2715]
#### 描述问题：
如果curd组件中，部分图片不存在，点击导出excel，会报错。如果全部图片存在，正常导出。

#### 截图或视频：
![image](https://user-images.githubusercontent.com/57615200/137573311-dcde3ed8-ab63-4b72-a4f0-6a3343c9b703.png)

![image](https://user-images.githubusercontent.com/57615200/137572481-8b5f7e08-73d9-448e-ada2-58cb63667833.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？
1.3.2
3. 粘贴有问题的完整 `amis schema` 代码：
```
 {
          "type": "crud",
          "combineNum": 2,
          "syncLocation": false,
          "affixHeader": false,
          "headerToolbar": [
            "export-excel",
            "export-csv"
          ],
          "columns": [
            {
              "name": "Img",
              "label": "图片",
              "type": "image",
              "enlargeAble": true
            }
          ]
        }
```

**Comment by koala-wei** [comment]
点击导出无任何反应，且无提示。我认为就算部分不存在，也应该能导出现有内容。

**Comment by nwind** [comment]
没复现，返回的数据是什么？按说这个版本加 try 了，试试下载最新版本 https://github.com/baidu/amis/blob/gh-pages/sdk.tar.gz

**Comment by koala-wei** [comment]
> 没复现，返回的数据是什么？按说这个版本加 try 了，试试下载最新版本 https://github.com/baidu/amis/blob/gh-pages/sdk.tar.gz

尴尬，我也复现不出来了，可能是我自己的问题。
