### ISSUE TITLE
sdk项目，通过fis发布项目，无法按需加载静态资源

### ISSUE THREAD

**Issue by koala-wei** [baidu/amis#2716]
#### 实现场景：
项目是通过fis发布的，项目上线时，会通过 fisp release -md ，这样会自动为静态资源加上后缀。但是在amis的sdk版本中，通过绝对路径，按需引入js文件。这会导致找不到加了后缀的js文件。

![image](https://user-images.githubusercontent.com/57615200/137581877-2423b742-2aca-4849-b6f9-f417f729f7c1.png)

**Comment by 2betop** [comment]
针对这几个文件把加戳功能关掉
