### ISSUE TITLE
列表点击按钮弹窗第一次参数传递不过去

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#2718]
#### 描述问题：
列表点击按钮弹窗第一次参数传递不过去

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
react

2. amis 版本是什么？
1.3.x 都不行
3. 粘贴有问题的完整 `amis schema` 代码：

code here...
```

4. 操作步骤
列表操作栏添加编辑,弹窗,映射id

**Comment by 502647092** [comment]
1.4.x版本已修复
