### ISSUE TITLE
input-date-range编辑时显示异常

### ISSUE THREAD

**Issue by xl-wenqiang** [baidu/amis#2719]
#### 描述问题：
input-date-range编辑时显示异常

#### 截图或视频：
![image](https://user-images.githubusercontent.com/22266819/137681310-e384da84-8785-4be5-8833-3ad0625fe3c0.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. amis 版本是什么？
1.3.4

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
    type: "input-date-range",
    name: "internshipTime",
    label: "实习日期${internshipBeginTime},${internshipEndTime}",
    placeholder: "请选择实习日期",
    format: "YYYY-MM-DD",
    inputFormat: "YYYY-MM-DD",
    required: true,
    embed: false,
    //ranges: ["yesterday"],
    //"value": "-1months,today"
    value:
      "${internshipBeginTime},${internshipEndTime}",
},
```

4. 操作步骤

**Comment by nwind** [comment]
没复现，怀疑是之前版本不支持 inputFormat
