### ISSUE TITLE
关于fis3打包该项目的一些问题

### ISSUE THREAD

**Issue by x1194785386** [baidu/amis#272]
目的：想将该项目打包用Nginx部署运行。

问题：用了fis3打包命令打包后Nginx配置部署运行的时候资源报错500，页面也什么都加载不出来。
```
`fis3 release -d ./dist`
```
错误截图：
![QQ图片20191009173247](https://user-images.githubusercontent.com/51640396/66469741-fcf14e00-eaba-11e9-93e8-ba722868cec9.jpg)

 另一个项目amis-admin用同样的fis3打包命令，Nginx配置部署运行正常，用同样的打包命令出来的包结构不一样，我该怎么解决？

**Comment by 2betop** [comment]
你问都问题其实是fis3 相关的东西，还是去看看 fis 相关的东西吧，或者去参考这个项目里面的配置 https://github.com/fex-team/amis-admin/

理论来说 amis 对外其实是 npm 包形式的，你用 webpack 也能跑起来的。
