### ISSUE TITLE
page和弹窗页查询条件参数传递问题

### ISSUE THREAD

**Issue by ryonchen** [baidu/amis#2729]
#### 实现场景：
page页面和弹窗页面都使用了crud组件，body里都加了syncLocation: false，都有一个查询条件为关键字，对应字段都是keyword，我在page页输入关键字，点击搜索，在弹窗页面的关键字不应该也显示出来

#### 存在的问题：
问题是page的关键字传递给了弹窗，导致在page页输入关键字在弹窗页也显示出来，如图
page页
![image](https://user-images.githubusercontent.com/2850983/138024265-a1431e6e-38ea-4076-b4f8-64971ac4fe54.png)
弹窗
![image](https://user-images.githubusercontent.com/2850983/138024182-8c29f26c-d3ac-428d-9dbc-9c34c20b45ff.png)

#### 当前方案：
弹窗和page页代码的body里都加了syncLocation: false，但依然会传递

**Comment by nwind** [comment]
看起来是用了同样的名字？换个 name 吧

**Comment by ryonchen** [comment]
> 看起来是用了同样的名字？换个 name 吧

不换名字有没有办法解决？

**Comment by 2betop** [comment]
可以，需要设置弹窗的数据映射，具体看这：https://baidu.gitee.io/amis/zh-CN/components/dialog?page=1#%E5%BC%B9%E6%A1%86%E4%B8%8E%E6%95%B0%E6%8D%AE%E6%98%A0%E5%B0%84
