### ISSUE TITLE
如何在Table中将数字显示的更可读

### ISSUE THREAD

**Issue by fs714** [baidu/amis#2731]
#### 实现场景：
在Table/CRUD中显示byte的统计时，会有一些比较大的数字，如123456789这样很多位的数字

#### 存在的问题：
这种数字对用户不是很友好，希望能显示为 5.8K, 12.3M，3.12G这样的格式。如果后端直接处理成字符串显示的话，就没法使用前端的排序了。

请问这个要怎么实现？

**Comment by nwind** [comment]
可以 

```
"type": "tpl",
"tpl": "${inbound_bytes | bytes}"
```
