### ISSUE TITLE
inputexcel支持标题映射以及行列范围限制

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2738]
#### 是否关联于某个问题吗：
比如excel里的标题列是：姓名，账号。希望读取后可以映射成name,account。
比如excel的某个页签里数据是从第三行开始，到第30行结束（30行以后还有一些内容，但是比希望读取到）。
比如希望读取3到20列，其他列忽略。

#### 预期的解决方案：
可以像api一样读取到数据之后加一层hook 的adapt来做自定义转换，或者直接在组件参数了做配置。

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by fanpocha** [comment]
这个映射功能感觉还是很需要的，不知道什么时候可以实现。请问有没有其它的解决方案可以替代
