### ISSUE TITLE
在一个新的项目中，npm i amis 之后如何使用amis中的组件？

### ISSUE THREAD

**Issue by x1194785386** [baidu/amis#274]

**Comment by 2betop** [comment]
就是这个统一的入口啊。 https://baidu.github.io/amis/docs/getting-started#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-

**Comment by x1194785386** [comment]
没有样式，是因为什么大佬？
![QQ图片20191010155555](https://user-images.githubusercontent.com/51640396/66549718-7f8b1380-eb76-11e9-9e7d-fa9f00def9cd.jpg)

**Comment by 2betop** [comment]
要引入样式文件

**Comment by 2betop** [comment]
amis/lib/themes/default.css

**Comment by 2betop** [comment]
html 里面用 link 标签引入，如果你的工程中有 css loader 那就改成 `import 'amis/lib/themes/default.css'`

**Comment by x1194785386** [comment]
好的样式已经出来了谢谢大佬！！！
