### ISSUE TITLE
向导组件列表弹窗编辑时数据不对

### ISSUE THREAD

**Issue by xl-wenqiang** [baidu/amis#2742]
#### 描述问题：
将向导组件用于CURD操作列弹窗编辑时，多次点击之后，数据呈现的是上一条数据

#### 截图或视频：
![X @186)KZ {V {0(%}MS}WV](https://user-images.githubusercontent.com/22266819/138222124-60662fbd-3c3b-4fb7-aae5-5d472eb2c06f.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. amis 版本是什么？
1.3.4

3. 粘贴有问题的完整 `amis schema` 代码：
以下代码仅供参考，多次尝试均复现了次问题：
```
{
    label: "编辑11",
    type: "button",
    actionType: "dialog",
    level: "link",
    dialog: {
        title: "编辑用户",
        body: {
            type: "wizard",
            //reload: "internshipTeam",
            mode: "horizontal",
            steps: [
                {
                    title: "第一步",
                    description: "填写小组信息",
                    body: [
                        {
                            name: "userName",
                            label: "用户名",
                            type: "input-text",
                            required: true,
                            disabled: true,
                            validations: "minLength:3,maxLength:45",
                            description: "用户名长度为3~45。",
                        },
                    ]
                }
            ]
        }
    }
},

```

4. 操作步骤

- 选择一行数据编辑打开，然后关闭
- 换一行数据编辑打开，即可发现问题

**Comment by duqingyu** [comment]
我也出现了这个问题

**Comment by duqingyu** [comment]
我目前退回来1.2.4-beta.16，也没发现问题，看看这个版本你能不能用着先。我升1.3.5是因为要用input-tree的一个属性

**Comment by xl-wenqiang** [comment]
> 我目前退回来1.2.4-beta.16，也没发现问题，看看这个版本你能不能用着先。我升1.3.5是因为要用input-tree的一个属性

input-tree的那个显示属性我们也需要用。。。  哈哈。
算了，先拆成表单进行编辑，或者写个弹窗关闭刷新页面的逻辑
