### ISSUE TITLE
表单出现重复嵌套警告

### ISSUE THREAD

**Issue by lkjx19812006** [baidu/amis#2743]
#### 描述问题：
form嵌套 出现警告

#### 截图或视频：
![微信截图_20211021162336](https://user-images.githubusercontent.com/24791498/138240031-b6187b81-8820-4a7a-a4cd-5fbfd6ba1df3.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
自定义了一个picker组件

2. amis 版本是什么？
版本由1.2.3升级到了1.3.4出现

**Comment by nwind** [comment]
用 1.4.0
