### ISSUE TITLE
请问如何在存档后，再呼叫另一个 api 执行过账作业?

### ISSUE THREAD

**Issue by gexMichael** [baidu/amis#2746]
#### 是否关联于某个问题吗：
用途类似出库单存档后，会去扣库存档，并新增帐款余额等。
目前进入窗体时有InitApi可以取所需的数据，是否能有一个 postApi于执行完某个Action 后可以再呼叫另一支 api ?

#### 预期的解决方案：
新增 postApi method

#### 其他可接受方案：
none

#### 任何附加信息：
none

**Comment by 502647092** [comment]
你可以用feedback打开一个对话框自动执行下一个操作

**Comment by 2betop** [comment]
新版可以用事件动作来做动作编排，比如监听 form 的 init 事件，然后配置 ajax 动作
