### ISSUE TITLE
【请教】接口请求返回后根据返回值做对应的操作, 比如登录操作 登录成功后返回的Token存到localStorage里面 怎么操作

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#2753]
#### 实现场景：
接口请求返回后根据返回值做对应的操作, 比如登录操作 登录成功后返回的Token存到localStorage里面
类似情况的需求感觉很多
用amis的话怎么实现方便点? 我现在用的是tpl  js模板里直接写js判断  感觉应该不是最好的方法 
请指教

#### 当前方案：

```
```

**Comment by 2betop** [comment]
嗯，接收适配器里面实现
