### ISSUE TITLE
上传控件设置不自动上传后，怎么设置选择文件后不显示开始上传按钮。

### ISSUE THREAD

**Issue by ChenSen5** [baidu/amis#277]
我使用上传文件控件，设置了不自动上传：
```
{
    label: "上传:",
    type: "file",
    name: "file",
    autoUpload:false,
    maxLength:1,
    accept:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel",
    required: true,
}
```
实际的显示效果如图，有开始上传按钮出现以及出现了等待上传文案。
我期望不自动上传的情况下都不出现这两个内容。
我是想在form表单提交的时候一起提交数据的，要怎么设置才能生效？
![image](https://user-images.githubusercontent.com/9099096/66622979-591fb380-ec1c-11e9-93cf-428d967fd4ed.png)

**Comment by 2betop** [comment]
试试加个 hideUploadButton: true https://github.com/baidu/amis/blob/master/src/renderers/Form/File.tsx#L89
