### ISSUE TITLE
提示信息如何修改： " 文件即将开始下载。。"

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#2777]
#### 描述问题：
当前文件下载时，提示：" 文件即将开始下载。。"
里面有2个中文句号，比较奇怪。
是否有可以自己设置的方式。
还有其他的ajax请求的amis自带提示信息，是否有修改的方式？

#### 截图或视频：
![image](https://user-images.githubusercontent.com/13453002/139183170-3d21de34-0272-40f7-a4ed-add129f05b0d.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？
1.3.4

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
      "type": "button",
      "label": "模板文件下载",
      "level": "light",
      "actionType": "ajax",
      "api": {
        "method": "post",
        "url": "/download_signup_template/",
        "responseType": "blob"
      }
    }
```

4. 操作步骤
点击按钮

**Comment by yangfeng2022** [comment]
有可以选择下载目录的方法吗？
