### ISSUE TITLE
建议考虑加强 input-file 和 input-image 对 OSS 直传的支持

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#2778]
#### 是否关联于某个问题吗：
建议考虑加强 input-file 和 input-image 对 OSS 直传的支持，现在OSS直传是这样的流程：
1. 通过应用服务器的 STS 服务获取 OSS 的临时访问签名
2. 浏览器上生成OSS的存储key（路径+文件名）
3. 调用OSS直传接口，上传成功不会返回url等相关信息

现在的input-file等控件只能配置上传API，要获取上传签名只能在form和service里配置，但有这么三个问题：
1. 这个上传签名是有有效期的，而且有效期最好不要太长，最好能有办法能在上传前获取，用form的initAPI或者service的时候就要考虑文件上传的时候这个签名有没有过期，如果过期了怎么刷新
2. 因为OSS直传的文件名是由客户端指定的，也就是要在客户端组装成一个文件名字符串。但如果只用数据映射的话，在api的data属性做数据映射的时候没办法取到待上传文件的文件名；如果只用requestAdaptor的话requestAdaptor里又取不到数据域里的字段值（因为可能要根据业务对象的id/name等属性来确定文件名）。因此现在就必须在api的数据映射里把用来拼接文件、路径名做映射，然后在requestAdaptor里取到待上传文件的文件名（后缀名）和映射进来的属性，然后才能做key字段的拼装。这样实现起来非常丑。
3. 因为OSS服务器并不会返回任何能够拼装成访问url的值，所以要把第二步生成的key作为表单项的值，但是responseData只能映射接口返回的值，也许只能从response参数里找到关联的request配置才能取到key值。

#### 预期的解决方案：
1. 增加对OSS直传模式的兼容

#### 其他可接受方案：
1. 允许在requestAdaptor和adaptor等地方能够访问当前scope的内容（数据和组件实例），可以在部分解决这个问题的同时让amis更灵活（当然也许也会更容易被各种骚操作搞乱）

**Comment by qiwang97** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react  
https://ant.design/components/upload-cn/#components-upload-demo-upload-with-aliyun-oss

参考 amis 的自定义组件 + antd 的 upload 组件，即可实现 oss 直传效果
