### ISSUE TITLE
咨询两个问题

### ISSUE THREAD

**Issue by tomerry** [baidu/amis#279]
1、作用域内字段同名冲突，字段冗余，节点对外输出哪些数据由用户控制是不是会比较好？
2、面对后端接口各种各样，有好多是来自于两个接口或者串行接口，后端数据格式也是各种各样，有没有合适的方案，感觉框架对接口还是有要求对。

**Comment by 2betop** [comment]
1. 如果输出形式 api，api 是可以自己决定发送什么数据的，配置 api.data 具体参考 api 说明。
2. 最好能统一，如果不能统一只能配置接口适配器。另外如果需要两个接口，可以用两个可以拉取接口的容器包一起，比如 Service 套 Service，默认是 并行获取，如果要串行，说明有依赖，我假设 B 接口依赖 A 接口的 a 字段，那么配置 B 的接口时候写上 '/api/b?a=${a}' 另外配置个 sendOn `this.a` 这样 B 接口默认不会拉取了，然后等 A 接口数据 回来了，有 a 字段了，这个时候 B 发现接口地址结果变了，就会重新发起请求。https://baidu.github.io/amis/docs/renderers/Types#api
