### ISSUE TITLE
设计器更换主题出错！！！

### ISSUE THREAD

**Issue by qianxiaofendou** [baidu/amis#2791]
问题：当amis升级到1.2.2之后，使用默认主题(default)设计器样式会出错，看了changelog，1.2.2之后默认主题更换为`ang`了，当引入`ang`，并且编辑器也设置为这个主题后样式会错乱，经过测试，使用云舍`cxd`是正常的，出错是因为设计器左边导航在更换主题时一直是`cxd`模式(使用'antd'主题也是这样)，如下：

![WX20211029-114356](https://user-images.githubusercontent.com/20673152/139376657-0dfc2cf7-c513-400b-b381-aa6f4093d472.png)

还请麻烦看一下是什么原因，另外升级后使用默认主题`ang`也是会样式错乱，希望以后升级的时候能告知一下当前编辑器所适配的主题模式

页面使用代码部分如下：
```js
import '../node_modules/font-awesome/css/font-awesome.css'
import '../node_modules/bootstrap/dist/css/bootstrap.css'
import '../node_modules/amis/lib/themes/ang.css'
import '../node_modules/amis-editor/dist/style.css'

……

<Editor
      ref={$editor}
      value={initJson}
      className='am-editor-container'
      preview={isPreview}
      isMobile={isMobile}
      theme='ang'
      onChange={editorChange}
  />
```

`package.json`部分如下：
```json
{
    "amis": "1.3.4",
    "amis-editor": "3.3.10",
}
```

**Comment by wibetter** [comment]
目前amis-editor 4.1.0-beta.21 已经没有这个问题了，可以使用新版Editor哈。

**Comment by wibetter** [comment]
可以通过这个地址，在线试用新版Editor：https://aisuda.github.io/amis-widget/test/preview.html
