### ISSUE TITLE
支持表单提交后配置动作

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2792]
#### 是否关联于某个问题吗：
支持表单提交后配置动作

#### 预期的解决方案：
比如有“工单申请”和“工单清单”两个tab的tabs组件。当在“工单申请”tab点击提交表单之后切换到“工单清单”tab。
或者提交表单之后跳转到新页面进行一些提示之类的。

#### 其他可接受方案：
{
    “type”: "form",
    "after_submit": {
        "type": "url"
        "url": "www.baidu.com"
    }
    ....
}

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by 2betop** [comment]
目前form有 redirect 可以实现跳转其他页面，同时如果 tab 设置 hash 后，redirect 应该也能跳过去

**Comment by belongwqz** [comment]
redirect配置为“#hashvalue”这样跳转不了，amis怎么获取当前页面的地址以便组装出location#hash这样的格式呢？

**Comment by belongwqz** [comment]
试了一下，redirect在此场景跳转不了，不用tabs就可以跳转，不知为何

**Comment by 2betop** [comment]
试了下，没问题参考：

```js
{
  type: 'page',
  title: '表单页面',
  body: [
    {
      type: 'tabs',
      tabs: [
        {
          title: 'Tab1',
          body: [
            {
              type: 'form',
              mode: 'horizontal',
              redirect: '#tab2',
              body: ['直接提交']
            }
          ]
        },
        {
          title: 'Tab2',
          hash: 'tab2',
          body: ['233']
        }
      ]
    }
  ]
}
```

**Comment by belongwqz** [comment]
> 试了下，没问题。参考：
> 
> ```js
> {
>   type: 'page',
>   title: '表单页面',
>   body: [
>     {
>       type: 'tabs',
>       tabs: [
>         {
>           title: 'Tab1',
>           body: [
>             {
>               type: 'form',
>               mode: 'horizontal',
>               redirect: '#tab2',
>               body: ['直接提交']
>             }
>           ]
>         },
>         {
>           title: 'Tab2',
>           hash: 'tab2',
>           body: ['233']
>         }
>       ]
>     }
>   ]
> }
> ```

我用jssdk方式（1.4.1）试了一下，发下浏览器地址栏hash改变，但是页面没有变化，而使用官网里的例子是会产生页面跳转的。是不是还得手工监听onhashchange消息做强制重新跳转才行？

要是能配置一个类似于currentTab之类的变量，当变量改变时tab自动切换，提交表单后有机会去更新这个变量就好了。

**Comment by 2betop** [comment]
jssdk 模式如果要监控地址栏变化自动更新，则需要下发 location 属性，正常如果在 spa 项目里面，都会有前端路由，把前端路由最新的 location 对象下发即可。如果没有自动路由，则可以像下面这样简单处理一下也能变化。

```
let location = { ...window.location };
        let amisScoped = amis.embed("#root", amisJSON, {
          location,
        });
        window.addEventListener("hashchange", function () {
          amisScoped.updateProps({
            location: { ...window.location },
          });
        });
```
