### ISSUE TITLE
amis源码+自定义组件如何构建新的sdk

### ISSUE THREAD

**Issue by lkjx19812006** [baidu/amis#2803]
因公司业务需求，需要基于amis自定义组件。
想问下，如何利用f3 或者 webpack 构建一个amis源码+自定义组件的新的sdk

**Comment by nwind** [comment]
参考 https://baidu.gitee.io/amis/zh-CN/docs/extend/contribute

**Comment by nwind** [comment]
使用 sh build.sh 命令，就会生成 sdk 目录
