### ISSUE TITLE
表单不要直接嵌套在表单下面 提示是什么原因，会导致什么异常？需要怎么修改？

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#2805]
表单不要直接嵌套在表单下面 提示是什么原因，会导致什么异常？需要怎么修改？

![image](https://user-images.githubusercontent.com/13453002/139519975-187d0abe-992f-43be-ae17-3e538021fe7b.png)

#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
用最新的版本，这个之前限制了 form 嵌套 form，后来又放开了
