### ISSUE TITLE
npm start后访问是空白页面

### ISSUE THREAD

**Issue by tteat** [baidu/amis#281]
![image](https://user-images.githubusercontent.com/28376200/66727634-055ad780-ee73-11e9-94d4-53935584cac8.png)

**Comment by 2betop** [comment]
tslib 需要升级一下

**Comment by 2betop** [comment]
git pull 一下

**Comment by tteat** [comment]
> git pull 一下

pull之后执行了npm i，npm start还是报一样的错

**Comment by 2betop** [comment]
不好意思，我忘记 pull request 了。或者你手动改成这个吧 "tslib": "^1.10.0",

**Comment by tteat** [comment]
> ^1.10.0

改了还是不行。。

**Comment by 2betop** [comment]
npm ls tslib 看看结果

**Comment by tteat** [comment]
> npm ls tslib 看看结果

![image](https://user-images.githubusercontent.com/28376200/66794256-5fbb6d00-ef33-11e9-94a3-a5df73a54ef8.png)

**Comment by 2betop** [comment]
我刚删了 node_modules 试了一遍没问题的，你是不是忘记再次执行 npm run dev 了？

**Comment by tteat** [comment]
> 我刚删了 node_modules 试了一遍没问题的，你是不是忘记再次执行 npm run dev 了？

![image](https://user-images.githubusercontent.com/28376200/66794723-08b69780-ef35-11e9-9522-b8f816376e3f.png)
执行了呀，这个vertx的warning会有影响吗？

**Comment by 2betop** [comment]
不会有影响，还是不行？

**Comment by tteat** [comment]
> 不会有影响，还是不行？

嗯，还是不行诶

**Comment by 2betop** [comment]
git pull

**Comment by tteat** [comment]
> git pull

可以了，谢谢！
