### ISSUE TITLE
分页支持limit+offset方式传参

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2810]
#### 是否关联于某个问题吗：
一些通用框架的分页参数是limit+offset方式，目前无法通过将page+perpage转化为limit+offset方式传递

#### 预期的解决方案：
兼容分页的limit+offset方式

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/2818

**Comment by 2betop** [comment]
等这个合了后，可以 api: "/api/xxx?limit=${perPage}&offset=${page|minus|times:perPage}"
