### ISSUE TITLE
iframe需要添加一个name属性

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#2817]
#### 是否关联于某个问题吗：
我希望使用一个 iframe 来显示一些东西，但是现在的 iframe 组件不能指定 name 所以其它地方就没有办法使用 target 来使用这个 iframe 显示数据。

#### 预期的解决方案：
在 iframe 组件中添加一个 name 属性。

**Comment by 2betop** [comment]
iframe 支持name属性

**Comment by juqkai** [comment]
在 IFrame.tsx 179-188 行代码中，是没有 name 属性的

```
return (
      <iframe
        className={className}
        frameBorder={frameBorder}
        style={style}
        ref={this.IFrameRef}
        onLoad={this.onLoad}
        src={finalSrc}
      />
    );
```

**Comment by 2betop** [comment]
amis 的通信机制不是靠 tag 上面加name实现的，内部有个 ScopedContext 管理的

**Comment by juqkai** [comment]
如果要实现`<a target="abc" href="abc.com">`或者`window.open("abc.com", "abc")`这样的功能，应该怎么实现呢？

**Comment by juqkai** [comment]
之所以有这个需要，是因为在使用`app`组件来做后台管理的时候，没有办法在右边使用`iframe`来做显示。
但是，菜单中的页面，不一定全是当前系统的页面。可能是其它业务系统的页面，开发页面的语言也不一定是amis。

**Comment by 2betop** [comment]
你说的是 amis 外的通信，我以为说的是 amis 内的，那我们加一下好了
