### ISSUE TITLE
CRUD Table中的列宽如何强制不换行？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#282]
当前CURD Table中的列宽似乎是按照宽度值等比例缩放的，比如把所有列的列宽width属性设置成800，和把所有列的列宽width设置成200是相同的效果。

如果列比较多的话，有些列因为内容比较长，即使设置了width属性但无效，仍然会被强制换行 —— 如何设置成强制不换行呢？比如把所有列的width都设置成800，就是想让它显示超长超长，突破屏幕的话自动产生横向滚动条 —— 这要怎么设置？

**Comment by foxfire881** [comment]
补充：我的场景是在CURD的中嵌套了一个折叠的二层CURD，二层CURD的列总宽度似乎是固定的，所以导致width属性无效仍然会按比例缩放。如何自动突破总宽呢？

**Comment by foxfire881** [comment]
再把问题简化一点：折叠嵌套的二层CRUD中，只有第一层CRUD的横向滚动条有效，被折叠的第二层CRUD展开后没有横向滚动条，导致所有的列都挤在一起非常丑陋。 如何让折叠的CRUD也有横向滚动条呢？

**Comment by 2betop** [comment]
就设置放crud那列的宽度到足够宽？我也没啥好办法

**Comment by foxfire881** [comment]
> 就设置放crud那列的宽度到足够宽？我也没啥好办法

试过了呢，设置放CRUD那列的width属性无效，即使设置成10000，实际最大宽度也就是第一层CRUD的总宽度。

没有办法把第二层的CRUD用div包装一下弄个横向滚动条出来吗？

**Comment by nwind** [comment]
可以自己加 css 解决，但横向滚动条很难操作所以默认不提供
