### ISSUE TITLE
amis官网默认主题（云舍）样式错乱

### ISSUE THREAD

**Issue by iceqing** [baidu/amis#2828]
#### 描述问题：
https://baidu.github.io/amis/zh-CN/docs/index

#### 截图或视频：
![image](https://user-images.githubusercontent.com/39587710/139854748-b69564b1-fd86-42eb-9899-bcb72ad8b13a.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？
1.4.1

3. 粘贴有问题的完整 `amis schema` 代码：
无

4. 操作步骤
打开官网首页即可复现

**Comment by nwind** [comment]
嗯正在修
