### ISSUE TITLE
Alert组件的prompt弹窗关闭有bug！！！

### ISSUE THREAD

**Issue by qianxiaofendou** [baidu/amis#2840]
问题：
当使用alert的prompt方法弹框时，点击取消按钮，内部的prompt属性为设置为false，导致调用alert的其它方法时一直弹出的是prompt的弹框

`Alert`源码部分：
```js
 handleCancel() {
    this.close(false);
  }

  close(confirmed: boolean) {
    const isConfirm = this.state.confirm || this.state.prompt;

    this.setState(
      {
        show: false
      },
      isConfirm ? () => this._resolve(confirmed) /*this._reject()*/ : undefined
    );
  }
```

从上面源码看到，只是设置了`show`属性为`false`，`prompt`属性并没有设置，还是true，导致渲染出错，麻烦看下，多谢！！！

**Comment by 2betop** [comment]
多谢反馈，下次可以考虑直接来个 pr ：），关联 pr：https://github.com/baidu/amis/pull/2842
