### ISSUE TITLE
导航栏可以配置成联动吗？

### ISSUE THREAD

**Issue by tteat** [baidu/amis#285]
1.我目前的想法是通过设置hidden参数，通过控制hidden的true/false控制导航栏相关页面的展示与否，遇到了如下问题，
![image](https://user-images.githubusercontent.com/28376200/66882385-c062ac80-effc-11e9-9321-bfabe67f504b.png)
可以获得infold的值，当infold!=3时表达式为true，但是hidden不起作用。
2.请问项目运行起来之后可以通过界面上的配置操作自动生成页面和导航而不需要重新编译吗？

**Comment by 2betop** [comment]
1. 导航部分其实不是 amis 渲染器负责的，但是你说的这个是可以实现的，可以参考这个逻辑：https://github.com/fex-team/amis-admin/blob/master/routes/admin/index.tsx#L187

2. 不行，你开启 npm run dev 就不要关，会按需编译的。

**Comment by tteat** [comment]
> 1. 导航部分其实不是 amis 渲染器负责的，但是你说的这个是可以实现的，可以参考这个逻辑：https://github.com/fex-team/amis-admin/blob/master/routes/admin/index.tsx#L187
> 2. 不行，你开启 npm run dev 就不要关，会按需编译的。

好的，谢谢您！
