### ISSUE TITLE
amis editor编辑器扩展自定义组件，如何配置？

### ISSUE THREAD

**Issue by thbgh** [baidu/amis#2853]
#### 实现场景：
我想要扩展自定义组件，使用效果和amis原来的组件一样

#### 存在的问题：
现在项目中的README例子无法满足自定义组件的扩展配置

@nwind

**Comment by nwind** [comment]
参考 https://baidu.gitee.io/amis/zh-CN/docs/extend/custom-react#react-%E6%B3%A8%E5%86%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%9E%8B

**Comment by thbgh** [comment]
> 参考 https://baidu.gitee.io/amis/zh-CN/docs/extend/custom-react#react-%E6%B3%A8%E5%86%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%9E%8B

不是这个意思，而是在editor中的组件。
能留个联系方式请教一下吗？
@nwind

**Comment by nwind** [comment]
编辑器扩展文档目前只有 README，后续再抽空补文档了，有细节问题发 issue，时间有限不提供单独的咨询服务
