### ISSUE TITLE
Nav  env变量中的jumpTo方法实现spa单页模式跳转

### ISSUE THREAD

**Issue by user-huage** [baidu/amis#2855]
#### 实现场景：
我现在React项目中使用了Nav组件，但默认不是spa单页跳转，每次点击链接都会刷新整个页面，导致我的Nav组件每次都会重新渲染，无法保留上次的操作记录，比如保留点击哪个链接

#### 当前方案：
麻烦提供下React项目的jumpTo方法实现spa单页模式跳转的案例

**Comment by xiaoxijin** [comment]
这个问题已经解决了么？ 我也遇到了这个问题呀。？
是新版本直接支持了还是？

**Comment by xiaoxijin** [comment]
@user-huage
