### ISSUE TITLE
transfer穿梭器option文本超长导致显示异常

### ISSUE THREAD

**Issue by zgsdharry** [baidu/amis#2861]
#### 描述问题：
transfer穿梭器option文本超长导致显示异常

#### 截图或视频：
![image](https://user-images.githubusercontent.com/3224377/140453479-72ca6859-f348-4200-8bf1-d5b046c53e7b.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
SDK

2. amis 版本是什么？
  1.4.1

**Comment by hsm-lv** [comment]
新版本已修复
<img width="817" alt="image" src="https://github.com/baidu/amis/assets/80095014/5c3f3d0a-0024-401b-a703-1307790849ef">
