### ISSUE TITLE
【强烈建议】crud-table 增加rowClassNameExpr的配置项

### ISSUE THREAD

**Issue by fox-momo** [baidu/amis#2862]
1、crud-table中数据需要根据状态或者属性，标记样式
2、itemAction需要支持操作数据集的功能

**Comment by 2betop** [comment]
1. 应该已经有了. 参考：https://baidu.gitee.io/amis/zh-CN/components/table#%E9%AB%98%E4%BA%AE%E8%A1%8C
2. 没看懂，我的理解是你应该用 bulkActions ？

**Comment by fox-momo** [comment]
> 2. 没看懂，我的理解是你应该用 bulkActions ？

就是我点击行后，执行一个动作，比如有一个全局变量：selectRow: rowData, 记录选中的记录，itemAction： selectRow = currentRowData，这样我就可以使用第一条说的判断rowClassExpre: selectRow.id == data.id?"red":"blue"；页面中其他的组件可以会根据选中的行，动态加载数据。

或者有别的方式可以实现选中行，并触发事件的方式也可以。

**Comment by 2betop** [comment]
这个最近在调整联动机制，会考虑这个情况，后面更新这个 issue

**Comment by fox-momo** [comment]
非常感谢

**Comment by 2betop** [comment]
2. 目前可以用 picker + service 实现，picker 有内联模式，相当于一个带选择功能 crud
