### ISSUE TITLE
Alert组件，调用过的 prompt 后再调用 confirm，对话框内容会一直显示上次 prompt 的内容 

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#2863]
#### 描述问题：
Alert组件，在调用过 prompt 后再调用 confirm，对话框内容会显示上次 prompt 的内容 

#### 截图或视频：
调用prompt前会正常显示：
![image](https://user-images.githubusercontent.com/3793855/140477193-8b171936-b70b-4051-8095-ad937a6d29da.png)
调用prompt：
![image](https://user-images.githubusercontent.com/3793855/140477820-9c9b2669-ccff-413a-952e-1ce69145ec3c.png)
再调用刚才的confirm对话框：
![image](https://user-images.githubusercontent.com/3793855/140478015-1bf02c13-2ee7-40e4-8701-b7808e499a27.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm、sdk

2. amis 版本是什么？
1.2.1、1.3.4、1.4.1

3. 代码
```js
import { confirm as amisConfirm, prompt as amisPrompt } from 'amis'
// ……
// ……balabala
// ……
await amisPrompt('这个会一直显示', '', '请输入', '确定')
await amisConfirm('而不会显示这个', '确认', '确认')

```

**Comment by 2betop** [comment]
在这个 pr 里面修复了https://github.com/baidu/amis/pull/2842
