### ISSUE TITLE
Combo组件minLength、maxLength支持持变量取值

### ISSUE THREAD

**Issue by leaf188** [baidu/amis#2864]
#### 是否关联于某个问题吗：
目前combo组件的minLength、maxLength只能设为固定值，当设为变量的时候不生效

**Comment by jackhansir** [comment]
![C0C0098E-B1EF-4371-A719-BAC97329FD00](https://user-images.githubusercontent.com/26846260/216507623-be7ea4ae-3061-4139-9578-da147967d3c4.png)
select多选改变选中，maxLength设置成动态也只取默认的1，即使添加选中动态改变maxLength的大小，红色框的添加按钮没有显示，有什么解决办法，或者有没有刷新更新组件之类的方法实现
