### ISSUE TITLE
我想要实现隐藏银行卡号后四位的功能

### ISSUE THREAD

**Issue by Chen-Wendong** [baidu/amis#2865]
#### 实现场景：
我想要实现隐藏银行卡号后四位的功能

#### 存在的问题：
使用 "type": "static-text" 时内容是银行卡号，想隐藏内容后四位，使用 * 替代，目前static-text无法实现！

#### 当前方案：
没

请问有其他组件支持吗？

**Comment by dbkuaizi** [comment]
我感觉这个可以通过后端 把数字替换成 *** 实现

**Comment by nwind** [comment]
最好后端隐藏，不然看网络请求就暴露了
