### ISSUE TITLE
我想要实现审计功能，在执行post或put时后，根据返回结果，再自动执行一次或多次post请求发送操作日志！

### ISSUE THREAD

**Issue by Chen-Wendong** [baidu/amis#2866]
#### 实现场景：
我想要实现审计功能，在执行post或put时后，根据返回结果，再自动执行一次或多次post请求发送操作日志！

请问怎样配置才能实现？

**Comment by nwind** [comment]
fetcher 里可以自己重写，不过目前会加个专门用来跟踪行为的接口

**Comment by Chen-Wendong** [comment]
https://baidu.gitee.io/amis/zh-CN/docs/extend/tracker

从 1.5.0 版本开始，amis 内置了跟踪用户交互行为采集功能。

@nwind 是这个吗？
