### ISSUE TITLE
我想要实现勾选框位选中后再取消选中时删除该字段键值

### ISSUE THREAD

**Issue by Chen-Wendong** [baidu/amis#2871]
#### 实现场景：
我想要实现勾选框位选中后再取消选中时删除该字段键值

#### 存在的问题：
未选择时，没有键值
![image](https://user-images.githubusercontent.com/88780174/140544016-c5e7afb1-7d6e-4ccc-bb7c-f9b782b65904.png)

选中后再取消选中时，有键值
![image](https://user-images.githubusercontent.com/88780174/140544193-360eb9dd-adf8-4344-b7aa-34ef7cc008ed.png)

希望实现勾选框位选中后再取消选中时删除该字段键值，如下：
![image](https://user-images.githubusercontent.com/88780174/140544475-959c8033-89ce-4f20-b1f6-d362b60b7ae1.png)

```
{
    "type": "form",
    "title": "表单",
    "body": [
        {
            "type": "checkbox",
            "option": "勾选框1",
            "name": "checkbox1"
        },
        {
            "type": "checkbox",
            "option": "勾选框2",
            "name": "checkbox2"
    ],
    "debug": true
}
```

**Comment by BeMxself** [comment]
可以试试formula组件
