### ISSUE TITLE
APP模式下 移动端菜单栏切换图标丢失问题

### ISSUE THREAD

**Issue by dbkuaizi** [baidu/amis#2872]
#### 描述问题：
APP模式下 移动端菜单栏切换图标丢失，发现是因为JS SDK 中的 `bui-icon iconfont icon-collapse` 字体图标不存在导致
#### 截图或视频：
![image](https://user-images.githubusercontent.com/44014601/140543915-d933993e-43e2-4e54-8e3e-3d82ebe4d2cf.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
JS SDK

2. amis 版本是什么？
1.4.1

目前我的解决方案是 搜索这个class 然后修改为 fas fa-bars，即可正常显示。但这样每次更新amis sdk的时候都需要替换一次，希望官方解决这个问题
![image](https://user-images.githubusercontent.com/44014601/140544635-ab96c932-057f-4b82-a01b-e94abdcf6bdf.png)

**Comment by gozeon** [comment]
see https://github.com/baidu/amis/issues/1971#issuecomment-990470738
