### ISSUE TITLE
各组件生成的html元素的id如何来指定？

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#2876]
例如，一个form，想指定组件生成的html中的form的element的id="my_first_form" 如何操作？

**Comment by nwind** [comment]
最好还是通过数据变更的方式影响展现，不然容易出现数据不一致 https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA
