### ISSUE TITLE
接口数据读取有很多种方式，比较混乱，可以整理一份说明文档吗？ 

### ISSUE THREAD

**Issue by zhenghongqiang** [baidu/amis#288]
获取变量方式，
$xxx ,  ${xxx} ,  data.xxx ,   $& 之类的 有很多种，很难记住那种形式用哪种方式，而且现在的文档对这些内容的说明比较分散，  能出一份归类整理文档吗？  辛苦~

**Comment by 2betop** [comment]
$xxx ${xxx} $& ${xxx | xxx} 的文档在这： https://baidu.github.io/amis/docs/renderers/Tpl

<%= data.xxx %> 这块时 lodash.template 里面的语法

data.xxx 这块只能用在表达式中。这就是js的语法，内部也就是 eval 的，没特殊处理。

**Comment by zhenghongqiang** [comment]
感谢~
