### ISSUE TITLE
action支持ajax请求结束后弹出已定义好的对话框或者抽屉

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2880]
#### 是否关联于某个问题吗：
现在action支持配置feedback来做后续动作，但是需要在feedback里定义弹出的对话框或者抽屉。能否弹出某个在其他地方已经定义好的对话框。比如一个任务，你可以点击“详情”去查看当前的执行情况，你也可以在点击“执行”按钮了之后自动弹出任务的“详情”对话框。也就是，对话框在一个地方定义，可以根据不同场景进行触发，比如可以点击按钮弹出，同时也能在api返回以后弹出。看起来也可以使用类似definitions的思路实现（没试过），但是如果在定义弹出对话框的地方有一些动态数据（比如csrf_token）就不能使用definitions了。

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by BeMxself** [comment]
api类型的action是可以配置feedback属性，应该能满足大部分需求场景

**Comment by BeMxself** [comment]
ajax类型的action是可以配置feedback属性的，应该能满足大部分需求场景
