### ISSUE TITLE
CRUD 删除弹窗显示异常

### ISSUE THREAD

**Issue by dikar** [baidu/amis#2885]
#### 描述问题：
请用一段清晰简洁的文字描述问题是什么...

使用CRUD组件时，配置删除逻辑时，点击X按钮 弹出alert异常

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

![image](https://user-images.githubusercontent.com/251375/140773815-6fea7dc8-ed22-4222-8146-2b4653f2d1ba.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

sdk

2. amis 版本是什么？
1.4.1

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
              "type": "button",
              "icon": "fa fa-times text-danger",
              "actionType": "ajax",
              "tooltip": "删除11",
              "confirmText": "您确认要删除?",
              "api": "http://localhost:8080/pageRest/del?id=$id"
            }
```

4. 操作步骤
请简单描述一下复现的操作步骤...

chrome 版本
 95.0.4638.69（正式版本） (x86_64)

sdk使用方式 ，引入CRUD 然后配置删除 ，alert弹出位置异常。

**Comment by nwind** [comment]
没复现，感觉是 npm 引入的吧，仔细看文档，还有两个组件要引入

**Comment by dikar** [comment]
我是sdk使用方式 ，css也加载了，其他组件需要引入单独的js文件吗？
我其实用toast 和alert  显示都有问题，虽然展示了，但是展示位置和样式都不对，还请指教，我只会简单的js，不会react 之类的
