### ISSUE TITLE
多语言

### ISSUE THREAD

**Issue by caixiaojia** [baidu/amis#289]
渲染器部分是否有支持多语言？

**Comment by 2betop** [comment]
目前没有，没想好这块要怎么做

**Comment by caixiaojia** [comment]
> 目前没有，没想好这块要怎么做
把组件的内部文本部分都用一个函数包一下，如果用户实现这个函数，就用用户的，如果用户未实现直接返回默认的？

**Comment by CareyToboo** [comment]
语言这块，从json配置文件读文本时候，不好区分。内部组件渲染倒是可以用函数包一下。倒是可以考虑写一个`babel-plugin`用语法分析来处理这个问题，这个思考路是否可行？ @2betop

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/644

**Comment by mengjuan** [comment]
@2betop 请教大神，已经支持多语言了么？文档里好像还没有i18n相关的信息，能给个例子怎么用么？
