### ISSUE TITLE
amis CRUD中的table的表头如何实现多语言

### ISSUE THREAD

**Issue by 969937484** [baidu/amis#2892]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
参考 https://baidu.gitee.io/amis/zh-CN/docs/extend/i18n#json-%E9%85%8D%E7%BD%AE%E4%B8%AD%E8%AE%BE%E7%BD%AE%E5%A4%9A%E8%AF%AD%E8%A8%80

**Comment by 969937484** [comment]
> 参考 https://baidu.gitee.io/amis/zh-CN/docs/extend/i18n#json-%E9%85%8D%E7%BD%AE%E4%B8%AD%E8%AE%BE%E7%BD%AE%E5%A4%9A%E8%AF%AD%E8%A8%80

是这样的，组件我试了下国际化，发现是可以的，但这个crud中的表格，我试了下国际化不知道为什么不生效
示例代码如下：
"columns": [
        {
          "name": "full_name",
          "en-US": {
            "label": "chinese name"
          },
          "label": "中文姓名",
          "type": "text",
          "sortable": false,
          "toggled": true
        }
]

**Comment by 969937484** [comment]
> 参考 https://baidu.gitee.io/amis/zh-CN/docs/extend/i18n#json-%E9%85%8D%E7%BD%AE%E4%B8%AD%E8%AE%BE%E7%BD%AE%E5%A4%9A%E8%AF%AD%E8%A8%80

是这样的，其他组件我用了多语言，发现是可以的，但是这个表格的columns里面的label不能切换成英文
示例代码如下：
"columns": [
        {
          "name": "full_name",
          "en-US": {
            "label": "chinese name"
          },
          "label": "中文姓名",
          "type": "text",
          "sortable": false,
          "toggled": true
        }
]
