### ISSUE TITLE
Status组件支持配置真假值

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2896]
#### 是否关联于某个问题吗：
Status组件支持配置真假值，和switch一样支持truevalue和falsevalue的配置。

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by 2betop** [comment]
status 是个枚举不是 boolean，目前可以通过配置 labelMap 来给不通知的做不同的描述。map 可以给不同的值加不同的 icon

**Comment by belongwqz** [comment]
> status 是个枚举不是 boolean，目前可以通过配置 labelMap 来给不通知的做不同的描述。map 可以给不同的值加不同的 icon

能帮忙给个示例不

**Comment by belongwqz** [comment]
@nwind 用map配置的默认图标是黑色的，怎么配置成其他风格的呢？
