### ISSUE TITLE
Json组件增强

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2897]
#### 是否关联于某个问题吗：
Json组件增强：

1、支持关闭节点的值类型，节点value前有个“string”看起来不太舒服

2、支持去掉key和value包裹的引号

3、支持关闭+和-控制按钮，显示纯json

4、value支持显示换行

#### 预期的解决方案：
```
{
    "type": "json",
    "showValueType": false,
    "showQuotes ": false,
    "showControl": false,
    "showWrap": true
}
```

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
#2965 数据类型可以关闭了
如果想显示纯 json 可以用只读模式的 editor
