### ISSUE TITLE
提供一个在线dashboard用于练手或者验证

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2898]
#### 是否关联于某个问题吗：
提供一个在线dashboard用于练手或者验证，左边为json代码，右边为预览，类似于](https://run.iviewui.com/)

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
所有文档里的示例都能实时修改生效，就是小了点。。
