### ISSUE TITLE
table的角标不显示

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2899]
#### 描述问题：
Table的itembadge配置了不生效

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？
v1.4.1

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
    "type": "service",
    "schemaApi": {
        "url": "/api/xxxx",    ---api返回table使用itemBadge角标的json配置，json为官网示例
        "method": "get"
    }
}
```

4. 操作步骤
不确定是否因为使用了schemaApi的原因

**Comment by nwind** [comment]
用最新版本 sdk https://github.com/baidu/amis/blob/gh-pages/sdk.tar.gz

**Comment by belongwqz** [comment]
> 用最新版本 sdk https://github.com/baidu/amis/blob/gh-pages/sdk.tar.gz

换了这个sdk，结果link组件的blank属性失效了，不管怎么设置渲染出来的都是`<a target="_self">`

**Comment by belongwqz** [comment]
> > 用最新版本 sdk https://github.com/baidu/amis/blob/gh-pages/sdk.tar.gz
> 
> 换了这个sdk，结果link组件的blank属性失效了，不管怎么设置渲染出来的都是`<a target="_self">`

应该是link添加htmlTarget改出来的问题，意图是让htmlTarget优先于blank参数，结果是让blank参数失效了只有htmlTarget起作用。

**Comment by 2betop** [comment]
收到，我晚点提 pr
