### ISSUE TITLE
evalExpression 直接 new Function 还是有点危险的

### ISSUE THREAD

**Issue by shepherdwind** [baidu/amis#29]
我这边做过类似的表单工具，也有遇到需要支持配置表达式的场景，一开始也是使用 new Function ，但是这样开发者还是很容易拿到完整的 dom 对象，后来有对外开放过，需要考虑安全场景，所以我这边写了一个简单的表达式解析工具 https://github.com/shepherdwind/simple-evaluate 。

如果你们有需要考虑安全问题，可以参考下 😄 

https://github.com/baidu/amis/blob/e076c6bf6586e545447a6f6acafeb85114b5db10/src/utils/tpl.ts#L30-L42

**Comment by 2betop** [comment]
嗯，你说的有道理，之前就是嫌麻烦没弄。不过，要防止拿 dom 貌似有其他思路比如：

```js
`var window, document, top, self, parent; /*其他危险对象*/ return !!(${expression});}`
```

**Comment by shepherdwind** [comment]
这种方式可以部分避免，但也还是很容易绕过的，举个例子

```js
const evalString = expression => new Function(`
  var window, document, top, self, parent; /*其他危险对象*/ return !!(${expression});
`) 

// 这样会报错
evalString('alert(document.cookie)')()

// 但稍微绕一下，就可以拿到 document 了
evalString('alert(LC40.getRootNode().cookie)')()
```

这里 LC40 是页面上一个 id ，任何 id 都可以直接拿到对应的 dom 对象。

这种属于黑名单机制，没法做到绝对安全的。
