### ISSUE TITLE
umi使用amis-editor

### ISSUE THREAD

**Issue by zouchao1** [baidu/amis#2903]
在umi3.5 中的.umirc.ts已配置

**Comment by zouchao1** [comment]
chainWebpack: (config) => {
    config.plugin('monaco-editor').use(MonacowebpackPlugin, [
      {
        languages: ['json'],
      },
    ]);
  },      在.umirc.ts已配置还是报错
Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule

**Comment by nwind** [comment]
信息太少了最好提供完整示例，amis 的开发团队从没用过 umi，大概是 umi 或 webpack 配置问题，去 github 搜吧，比如 https://github.com/microsoft/monaco-editor/issues/2741

**Comment by hyzx86** [comment]
主要是  MonacowebpackPlugin 这玩意要对应 MonacoEditor 的版本， amis 用的也不是最新版，所以去 MonacowebpackPlugin 仓库仔细看看 说明 对应的版本使用 对应的插件
https://www.npmjs.com/package/monaco-editor-webpack-plugin
<html>
<body>
<h2 style="box-sizing: border-box; color: rgb(17, 17, 17); margin: 8px 0px 16px; padding-bottom: 8px; font-weight: 600; line-height: 1.25; font-size: 1.875rem; border-bottom: 1px solid rgba(0, 0, 0, 0.1); letter-spacing: -0.3px; font-family: &quot;Source Sans Pro&quot;, &quot;Lucida Grande&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Version Matrix</h2>

monaco-editor-webpack-plugin | monaco-editor
-- | --
7.*.* | >= 0.31.0
6.*.* | 0.30.*
5.*.* | 0.29.*
4.*.* | 0.25.*, 0.26.*, 0.27.*, 0.28.*
3.*.* | 0.22.*, 0.23.*, 0.24.*
2.*.* | 0.21.*
1.9.* | 0.20.*
1.8.* | 0.19.*
1.7.* | 0.18.*


</body>
</html>
