### ISSUE TITLE
【BUG】异步加载信息组件显示异常

### ISSUE THREAD

**Issue by fox-momo** [baidu/amis#2905]
mapping、input-tree、list-select等组件在设置source后，可能数据加载和表单initApi初始化有先后不确定性，导致第一次打开时，无显示，再次打开才显示；如果我换一条记录，则第一次显示前一次的数据。
![1](https://user-images.githubusercontent.com/88315383/141082073-1a8cf6b9-aa97-4dc0-ad43-5c4b27dae165.png)

----------------------------------------------
![2](https://user-images.githubusercontent.com/88315383/141082104-6e0bd1af-65a6-4c7d-b2f3-21684b5d2961.png)
-

**Comment by 2betop** [comment]
这个看着像是历史问题，用最新版本试试？

**Comment by fox-momo** [comment]
是的，我更新了，好了，非常感谢
