### ISSUE TITLE
能否在导出的表格带总结行

### ISSUE THREAD

**Issue by ZG1711** [baidu/amis#2911]
我在文档的例子和实际程序中测试导出带有总结行的增删改查组件，是没有导出总结行的，需要手工在表格里汇总，所有希望能在导出的时候连总结行一起导出

**Comment by nwind** [comment]
之前想支持发现有点麻烦说，得再看看

**Comment by 673036325** [comment]
> 之前想支持发现有点麻烦说，得再看看

期待中0.0
