### ISSUE TITLE
定时刷新频率自选

### ISSUE THREAD

**Issue by ryonchen** [baidu/amis#2913]
#### 实现场景：
我想改配置一个下拉框设定刷新频率，字段名是_refresh，枚举值是关闭、30秒、60秒，crud表格读取该值，来修改刷新频率和开启关闭刷新

#### 存在的问题：
我crud开启了定时刷新，将刷新频率设置为$_refresh，但是无法设置

**Comment by 2betop** [comment]
目前不支持这种功能
