### ISSUE TITLE
求助，如何在react中使用amis-editor

### ISSUE THREAD

**Issue by 15271991153** [baidu/amis#2923]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
https://github.com/aisuda/amis-editor-demo

**Comment by 15271991153** [comment]
这个可以用到公司的项目中嘛
