### ISSUE TITLE
env.jumpTo 中拿到产生这个事件组件的上下文

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#2936]
#### 实现场景：
我想在 env.jumpTo 中拿到产生这个事件组件的上下文。希望从它的data中去判断是否存在某些值，来做一些不同的逻辑。

#### 存在的问题：
除了有 url 和部分组件有 action 外，完全拿不到其它数据。
即便想通过 amisScoped 来找到组件，也因为无法确定事件源，无法拿到 name 的值。

**Comment by 2betop** [comment]
```
jumpTo: (to: string, action?: Action, ctx?: object) => void;
```

第三个参数看看呢

**Comment by juqkai** [comment]
试了一下，不行。
具备第三个参数的调用，只有 RootRenderer.handleAction 。其它地方要么只有一个参数，要么是两个参数。
至少 App 的菜单是无法拿到第三参数的，但是button可以。

**Comment by juqkai** [comment]
换个说法。
我现在在使用APP组件，但是APP不是根组件，还有其它东西，所以页面上除了APP内有链接外，其它地方也有。
因为无法区分点击事件是在APP内，还是在APP外。所以无法使用hash来变更URL。
只能全部进行跳转。

原本是想，如果在 jumpTo 中可以获取到上下文中的data，那么在 APP 的 data 中给一个默认值。那么，APP 内的链接被点击的时候，就可以判断出是在 APP 内，就可以使用 hash 来做跳转。而 APP 外则拿不到这个值，就可以直接改变 URL。
