### ISSUE TITLE
文档【隐藏时删除表单项值】clearValueOnHidden 配置后不生效

### ISSUE THREAD

**Issue by xsqjptxj** [baidu/amis#2937]
#### 实现场景：
文档地址：https://baidu.github.io/amis/zh-CN/components/form/formitem#%E9%9A%90%E8%97%8F%E6%97%B6%E5%88%A0%E9%99%A4%E8%A1%A8%E5%8D%95%E9%A1%B9%E5%80%BC
```
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": "true",
    "body": [
      {
        "type": "input-number",
        "label": "数量",
        "name": "number",
        "value": 0,
        "description": "调整数量大小查看效果吧！"
      },
      {
        "type": "input-text",
        "label": "文本",
        "value": "这是一段文本",
        "name": "text",
        "hiddenOn": "this.number > 1",
        "description": "当数量大于1的时候，该文本框会隐藏",
        "clearValueOnHidden": true
      }
    ]
  }
}
```

#### 存在的问题：
 clearValueOnHidden 配置后不生效，当数字框输入大于1的数字，文本框隐藏后，文本框内容没有清空

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
不能复现，你应该观察debug 信息，隐藏后对应的 text 变量已经被删除了。你在设置成小于或者等于1的值时，由于文本框会再次出现，同时又有默认值 "这是一段文本"，所以再次出现时原来的值又回来了。有问题再开
