### ISSUE TITLE
如何在数据映射和api钩子中使用数据域的变量？

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#2940]
#### 实现场景：
比如提交表单根据`{"name": "abc"}`去查abc的值，返回`{"abc": xxxx}`，想通过过滤器pick取abc的值，`${return|pick:${name}}`这种写法不行。

想用api的adaptor来变换，不知道如果获取数据域的变量name

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
api.data
