### ISSUE TITLE
总结行中如果有隐藏列的问题

### ISSUE THREAD

**Issue by ZG1711** [baidu/amis#2942]
如果启用总结行，而某些列又被隐藏的情况下就需要有多少列就要使用多少tpl或者text才能一一对应，另外使用colSpan无法对隐藏列进行合并
![image](https://user-images.githubusercontent.com/25605653/141711587-1ea86209-490b-49f0-b625-59d858c5eeb8.png)
{
  "type": "page",
  "body": {
    "type": "service",
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/sample?perPage=10",
    "body": [
      {
        "type": "table",
        "source": "$rows",
        "columns": [
          {
            "name": "browser",
            "label": "Browser"
          },
          {
            "name": "version",
            "label": "Version"
          },
          {
            "name": "version",
            "label": "Version",
            "toggled": false
          },
          {
            "name": "version",
            "label": "Version",
            "toggled": false
          },
          {
            "name": "version",
            "label": "Version",
            "toggled": false
          },
          {
            "name": "version",
            "label": "Version"
          },
          {
            "name": "version",
            "label": "Version"
          },
          {
            "name": "version",
            "label": "Version"
          }
        ],
        "affixRow": [
          {
            "type": "text",
            "text": "总计"
          },
          {
            "type": "tpl",
            "tpl": "${rows|pick:version|sum}"
          },
          {
            "type": "tpl",
            "tpl": "${rows|pick:version|sum}"
          },
          {
            "type": "tpl",
            "tpl": "${rows|pick:version|sum}",
            "colSpan": 2
          },
          {
            "type": "tpl",
            "tpl": "${rows|pick:version|sum}"
          },
          {
            "type": "tpl",
            "tpl": "${rows|pick:version|sum}"
          },
          {
            "type": "tpl",
            "tpl": "${rows|pick:version|sum}"
          }
        ]
      }
    ]
  }
}

**Comment by 2betop** [comment]
新版本已修复，请更新到最新版本
