### ISSUE TITLE
[文档页面无法打开表单验证页面的文档无法打开

### ISSUE THREAD

**Issue by tgxhenry** [baidu/amis#295]
文档页面无法打开，路径：表单>表单验证，右侧的文档按钮，点击后显示404.
https://baidu.github.io/docs/renderers/Form/FormItem

**Comment by 2betop** [comment]
麻烦问下你是怎么点过去的？从导航中点进去应该没问题

页面正确的地址是这个：https://baidu.github.io/amis/form/validation
