### ISSUE TITLE
建议返回数据status成功代码为200

### ISSUE THREAD

**Issue by tufeiping** [baidu/amis#2953]
#### 描述问题：
status: 返回 0，表示当前接口正确返回，否则按错误请求处理；

建议status返回符合标准，目前大部分应用都是按照http 协议code来映射，如200表示ok

**Comment by 2betop** [comment]
这个通过全局适配器来处理吧，现有这个已经不能改了。

**Comment by nwind** [comment]
这样会重复，如果应用只靠 http 状态码可以自己返回数据，不放在 data 下
