### ISSUE TITLE
curd 字段 mapping 未达到预期效果

### ISSUE THREAD

**Issue by jiangbowen** [baidu/amis#2962]
#### 实现场景：
sdk 方式使用，字段 type:"mapping" 后 显示成了【通配值】
sdk 版本： v1.4.2-beta.6
![1](https://user-images.githubusercontent.com/11420570/141948789-2affe361-ec31-46f3-b43a-5945b5314993.jpg)

#### 存在的问题：
显示为【通配值】与期望不一致，后台返回数据如下

![2](https://user-images.githubusercontent.com/11420570/141948939-75bae063-29bb-4083-95a3-481b058fba94.jpg)

#### 当前方案：
![4](https://user-images.githubusercontent.com/11420570/141948965-91bb6f1a-f39a-486e-91cb-d7d66e37be1b.jpg)

```
{
          "name": "user.is_input",
          "label": "境外输入",
          "type": "mapping", 
          "map:": {
            "1": "否",
            "2": "是"
          }
        },
        {
          "name": "is_recovery",
          "label": "是否出院",
          "type": "mapping",
          "map:": {
            "1": "否",
            "2": "是"
          }
        },
        {
          "name": "is_asymptomatic",
          "label": "是否无症状",
          "type": "mapping",
          "map:": {
            "1": "否",
            "2": "是"
          }
        }
```

**Comment by nwind** [comment]
"map:" -> "map"

**Comment by jiangbowen** [comment]
感谢
