### ISSUE TITLE
目前的渲染器不适用于顶部工具的JSON化？有解决方案吗？

### ISSUE THREAD

**Issue by YUHUAJ** [baidu/amis#297]
想把顶部工具栏JSON化（用JSON数据的方式来编写标题，内容【按钮，文本，输入框，图标】，工具栏标题），但用目前的渲染器编写的工具栏会出现比较多的问题：会样式变样或是无法改变字体样式。。。麻烦给一下解决方法，谢谢。

**Comment by nwind** [comment]
不确定是指啥，太久远了先关了后续再问吧
