### ISSUE TITLE
app组件里面，右上角放一个用户按钮，一点下拉，可以进入用户个人页面和退出登陆

### ISSUE THREAD

**Issue by gillbates** [baidu/amis#2977]
#### 实现场景：
想像官网一样，在右上角放用户按钮（下拉菜单），一点，提供用户个人中心和退出的按钮。

#### 存在的问题：
不知道怎么居右。。。选择的方案默认巨左。。。

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
            let amis = amisRequire('amis/embed');

            const app = {
                type: 'app',
                brandName: 'Admin',
                // logo: '/public/logo.png',
                header: {
                    "type": "dropdown-button",
                    "className": "content-end",
                    "label": "用户XXX",
                    "trigger": "hover",
                    "buttons": [
                        {
                            "type": "button",
                            "label": "个人配置"
                        },
                        {
                            "type": "button",
                            "label": "退出"
                        }
                    ]
                }

            };


            
            let amisScoped = amis.embed('#root', app, {
                locale: 'en-US'
            });
```
想如图这样，居右，不知道有什么属性可以做到这样吗。。。

![image](https://user-images.githubusercontent.com/783547/142200746-5310363b-685e-44df-832f-f86e876fc1bb.png)

**Comment by Chen-Wendong** [comment]
用布局

**Comment by gillbates** [comment]
![image](https://user-images.githubusercontent.com/783547/142372912-3749cca9-5e79-4665-992f-f0d8885e1d20.png)


```
const app = {
                type: 'app',
                brandName: 'Admin',
                // logo: '/public/logo.png',
                header: {
                    "type": "grid",
                    // "className": "b-a bg-dark lter",
                    "columns": [
                        {
                            "md": 10,
                            "body": [
        
                            ]
                        },
                        {
                            "md": 2,
                            "body": [
                                {
                                    "type": "dropdown-button",
                                    "className": "content-end",
                                    "label": "用户XXX",
                                    "trigger": "hover",
                                    "icon": "fa fa-user-circle",
                                    "buttons": [
                                        {
                                            "type": "button",
                                            "label": "个人配置"
                                        },
                                        {
                                            "type": "button",
                                            "label": "退出"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            };

```

后端出身，折腾了半天，但是感觉这个下拉框的宽度比 上面宽很难看。

@Chen-Wendong 不知道能帮忙给个例子吗。。。

**Comment by dbkuaizi** [comment]
@gillbates  可以通过 css样式修改这个按钮的宽度
```css
.amis-scope .cxd-DropDown-menu{min-width: 100%;}
```
![Uploading Snipaste_2021-11-24_22-42-56.jpg…]()

**Comment by gillbates** [comment]
@dbkuaizi 好的，谢谢楼上的同学！！！

**Comment by gillbates** [comment]
突然发现用grid 布局，在有些宽度上，按钮没有在最右边，一直尝试flex，发现按钮老是要移动到左边去。。。不知道有没有同学有代码可以参考下的。。。
![image](https://user-images.githubusercontent.com/783547/147877241-09695a1a-fdfd-4d97-bf78-ba143db974d7.png)

**Comment by gillbates** [comment]
哪位前端的朋友能帮忙下嘛。。。年前可以fix下。。。

**Comment by nwind** [comment]
"className": "pull-right"

**Comment by 625412505** [comment]
@gillbates 搞定了么？我遇到了相同的问题

**Comment by 625412505** [comment]
> @gillbates 可以通过 css样式修改这个按钮的宽度
> 
> ```css
> .amis-scope .cxd-DropDown-menu{min-width: 100%;}
> ```
> 
> ![](https://camo.githubusercontent.com/7a9f6b04a86959b74d411d156ae3707137d7efc2283a8e523bbc1e1be3fc3a30/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032312f31312f323139376131306566313233333665352e6a7067)

这个有具体的案例么？帮助一下小白门，谢谢。

**Comment by gillbates** [comment]
我最后就是加了个 pull-right 就好了。

**Comment by 625412505** [comment]
> pull-right

噢噢，上面的css样式：.amis-scope .cxd-DropDown-menu{min-width: 100%;}你是怎么设置的？

**Comment by haohaochong** [comment]
> 我最后就是加了个 pull-right 就好了。

求代码，我尝试了好多次没成功，还是居左。

**Comment by 625412505** [comment]
> > 我最后就是加了个 pull-right 就好了。
> 
> 求代码，我尝试了好多次没成功，还是居左。

我用的代码：
        app.header = {"type": "flex",
                      "justify": "flex-end",
                      "alignItems": "flex-end"
                      "className": 'w-full',
                      "items": [
                            {
                                "type": "dropdown-button",
                                "trigger": "hover",
                                "icon": "fa fa-user",
                                "buttons": [
                                    {
                                        "type": "button",
                                        "label": "个人信息"
                                    },
                                    {
                                        "type": "button",
                                        "label": "退出登录"
                                    }
                                ]
                            }
                        ]
                     }

css配置：
.amis-scope .cxd-DropDown-menu {
  background: var(--DropDown-menu-bg);
  list-style: none;
  padding: var(--DropDown-menu-paddingY) var(--DropDown-menu-paddingX);
  min-width: 100%;
  text-align: center;
  border: none;
  user-select: none;
}

css配置有更优雅的可以把具体代码发下
