### ISSUE TITLE
嵌套表格如何设置默认全部展开

### ISSUE THREAD

**Issue by imlida** [baidu/amis#2978]
<img width="1164" alt="iShot2021-11-17 21 32 37" src="https://user-images.githubusercontent.com/5794390/142210337-585a0c6b-1dea-463e-9ff7-3465b4ddde28.png">

**Comment by rencoo** [comment]
+1

**Comment by kaiddddddd** [comment]
+1

**Comment by 2betop** [comment]
```
{
  type: 'crud',
  expandConfig: {
    expand: 'all'
  },
}
```
