### ISSUE TITLE
请教editor不换行方法

### ISSUE THREAD

**Issue by VonnOoO** [baidu/amis#2979]
#### 实现场景：
editor组件使用

#### 存在的问题：
如何让单行文本根据组件宽度换行，相反的，如何让单行文本不根据组件宽度换行？
![image](https://user-images.githubusercontent.com/37405103/142339896-4c68af22-a0ae-43f1-91b8-f6f5cb7f3110.png)

**Comment by nwind** [comment]
默认就是不换行，要换的话 options 里加 wordWrap: 'on'
