### ISSUE TITLE
弹窗问题

### ISSUE THREAD

**Issue by YUHUAJ** [baidu/amis#298]
目前项目中的dialog对话框是否不适合用在“查看”这个操作上呢？是否会更新提供多几个弹窗类型？

**Comment by 2betop** [comment]
查看没问题啊，里面可以放 service 或者 form，一般都是放 form 然后配置 initApi，然后配置 static 类型的 formItem，可以参考这个：https://baidu.github.io/amis/crud/table?page=1

**Comment by 2betop** [comment]
有问题再开
