### ISSUE TITLE
transfer发起请求的时候，sendOn没有效果，不会重新请求接口渲染组件

### ISSUE THREAD

**Issue by tanjiancheng** [baidu/amis#2980]
#### 描述问题：

transfer发起请求的时候，sendOn没有效果，不会重新请求接口渲染组件

#### 如何复现（请务必完整填写下面内容）：
npm:  "6.14.8"
amis: "^1.4.2-beta.6",

粘贴有问题的完整 `amis schema` 代码：
```
{
        "name": "app_id",
        "type": "select",
        "selectFirst": true,
        "label": "应用",
        "description": "搜索应用",
        "source": "${items}"
 },
{
          "label": "策略",
          "type": "transfer",
          "name": "policy_id",
          "selectMode": "chained",
          "searchable": true,
          "sortable": true,
          "source":{
            "url": "http://localhost:8000/api/iam/policy/search_policy_by_name",
            "method": "post",
            "data": {
              "name": "${term}",
              "user_pool_id": "${user_pool_id}",
              "app_id": "${app_id}",
            },
            "sendOn": "data.app_id != undefined"
          },
},
```

操作步骤
![image](https://user-images.githubusercontent.com/7401570/142341422-8ef3d4f7-56e2-465f-9770-11deda1f5dcc.png)

如上，我的目的是选中不同的应用拉取筛选后的值重新请求接口渲染transfer

上面的sendOn我试过很多次是能条件为true的，但是并没有发起
```
http://localhost:8000/api/iam/policy/search_policy_by_name
```
重新渲染组件

**Comment by 2betop** [comment]
sendOn 是判断接口要不要发，并不监控数值变化是否发送。从你的描述来看，是需要监控  app_id，而监控 app_id 重新加载你目前的配置是有问题的。可以看一下这个，要不配置在 url 参数里面，要不配置 trackExpression https://baidu.gitee.io/amis/zh-CN/docs/types/api#%E8%87%AA%E5%8A%A8%E5%88%B7%E6%96%B0
