### ISSUE TITLE
引入sdk/iconfont.css报错

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#2981]
#### 描述问题：
用npm的方式使用amis
```js
import 'amis/sdk/iconfont.css'
```
webpack编译报错Can't resolve iconfont.woff(ttf、svg)
我看了下sdk目录下没有这三个文件，把相关引入语句删除后才能正常编译

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.4.2-beta.6

**Comment by nwind** [comment]
刚补了这两天发版

**Comment by rumunanfeng** [comment]
> 刚补了这两天发版

请问发版了吗？
