### ISSUE TITLE
如何关闭校验的弹窗，只显示表单的校验提示

### ISSUE THREAD

**Issue by DadGuo** [baidu/amis#2982]
#### 实现场景：
如何关闭校验的弹窗，只显示表单的校验提示，或者能更改校验弹窗提示的样式么？

#### 存在的问题：
校验的弹窗提示样式太简单，而且样式不符合需求，想要更改或者不显示，但无从下手
![image](https://user-images.githubusercontent.com/59001670/142348944-6b5ee7ae-7cd1-4a60-898b-0bdb8fb3883c.png)

#### 当前方案：
当前版本：@license amis v1.3.4

```
code here...
```

**Comment by DadGuo** [comment]
希望尽快解决。。在线等

**Comment by 2betop** [comment]
form 的 messages 里面可以配置validateFailed为空。

```
{
  type: 'form',
  messages: {
    validateFailed: ''
  }
}
```

**Comment by DadGuo** [comment]
收到，非常感谢

**Comment by belongwqz** [comment]
考虑补一下文档，readOnly属性也没有文档。
