### ISSUE TITLE
建议dropdown-button可配置为的按钮点击后下拉菜单自动收起

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#2987]
#### 是否关联于某个问题吗：
当前点击dropdown-button中的按钮后，下拉菜单不会自动收回，不太理解现在这样设计的原因。
但是很多场景下，点击按钮后菜单应该自动收起吧？

#### 预期的解决方案：
增加配置项，允许点击后自动收起菜单

**Comment by lurunze1226** [comment]
`closeOnClick`属性应该可以解决你的问题，文档里缺少这条属性的描述了，稍后会更新一下

![image](https://user-images.githubusercontent.com/36724300/142559677-7e386acc-9e66-40a7-9451-5093d4ac2054.png)
