### ISSUE TITLE
加载顺序问题

### ISSUE THREAD

**Issue by DadGuo** [baidu/amis#2991]
#### 实现场景：
页面加载时先加载查询条件之后才加载列表

#### 存在的问题：
因为下拉数据较多，会出现2s左右的卡顿，才开始加载列表数据
![image](https://user-images.githubusercontent.com/59001670/142415460-4615039e-ce09-4394-b093-d0fa6d973a2e.png)

能不能先加载列表或者点击下拉时再加载下拉数据

#### 当前方案：

```
 {
    "type": "select",
    "className": "m-l",
    "label": "下单渠道：",
    "name": "channelKey",
    "placeholder": "请选择",
    "size": "md",
    "clearable": true,
    "searchable": true,
    "source":"get:/amis/options/getChannelListByLevel?level=2",
},
```

**Comment by nwind** [comment]
jssdk？按说这两没关联，是并行请求的，最好发完整复现示例

**Comment by 2betop** [comment]
确实串行的，这个机制已经不能动了，因为担心 source 接口返回默认值，影响不到 crud 的查询接口里面。

如果 select 改成 autoComplete 则没这个问题。

历史比较悠久了，这个问题先关了，有问题再开
