### ISSUE TITLE
优化amis静态资源

### ISSUE THREAD

**Issue by h7ml** [baidu/amis#2994]
#### 描述问题：

已将amis 的``css``,``sdk.js``cdn加载，但是打包后仍然过大(占打包后文件总体积的50.94%）
dist打包后的 amis文件总体积34.84MB 
dist文件目录总体积68.44
#### 截图或视频：

![image](https://user-images.githubusercontent.com/55233292/142418507-a5c4cc96-6d81-4546-acc6-165a7c2ab5c8.png)
![image](https://user-images.githubusercontent.com/55233292/142418544-60864919-8c2a-4818-93f8-773c7f71d71a.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm`、`cdn`.
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
```
    "amis-editor": "^3.3.12-beta.1",
    "amis-editor-sdk": "^0.1.3",
    "amis": "1.4.1",
```
 beta 版本测试问题存在该问题
3. 粘贴有问题的完整 `amis schema` 代码：
https://github.com/dgiot/dgiot-dashboard
4. 操作步骤
克隆项目后,pnpm install && pnpm build

**Comment by h7ml** [comment]
使用amis 后 构建内存溢出 
详见[action](https://github.com/dgiot/dgiot-dashboard/runs/4251377429?check_suite_focus=true)

**Comment by cmdares** [comment]
关注

**Comment by nwind** [comment]
amis-editor-sdk 不是官方发布的，我们也不清楚是怎么实现的，得联系对应的作者解决
