### ISSUE TITLE
crud 使用 api: '${HOST|raw}/api'

### ISSUE THREAD

**Issue by mrwangyin** [baidu/amis#2995]
分页查询不带分页参数，且搜索条件也带不上；

{
        "type": "crud",
        "name": "list",
        "api": "${HOST|raw}/goods/listPage",
        "primaryField": "apiId",
        "syncLocation": false,
        "filter": {
          "title": "条件搜索",
          "body": [
            {
              "type": "input-text",
              "name": "keywords",
              "clearable": true,
              "placeholder": "关键字"
            }
          ]
        },...............

**Comment by mrwangyin** [comment]
版本：v1.4.1

**Comment by nwind** [comment]
一旦有数据映射就得自己指定了，等新的 url 替换方案吧

**Comment by mrwangyin** [comment]
感谢解答
