### ISSUE TITLE
transfer组件搜索框的placeholder如何配置？

### ISSUE THREAD

**Issue by josselu** [baidu/amis#3003]
#### 描述问题：

transfer组件：
- 希望能够配置 搜索框的placeholder，我们在源码的interface中发现了`searchPlaceholder: string`的声明，但是在真正的实现中，却没有应用该属性。

#### 截图或视频：

![image](https://user-images.githubusercontent.com/23567196/142583497-50bd8cfa-d848-4c6d-a23a-0bb89a17639e.png)

![image](https://user-images.githubusercontent.com/23567196/142585275-87e044ed-57da-4ce7-bd26-064fec7ca64e.png)

**Comment by hsm-lv** [comment]
searchPlaceholder，resultSearchPlaceholder
