### ISSUE TITLE
如何在index.html里定义一个变量，在所有页面里可以通过模板字符串获取？

### ISSUE THREAD

**Issue by coolxv** [baidu/amis#3004]
#### 实现场景：
在index.html里定义.类似于数据域，ccDomain: 'http://127.0.0.1:8000'
```
 let amisInstance = amis.embed(
        '#root',
        app,
        {
          location: history.location
        },
        {
          data: {
            ccDomain: 'http://127.0.0.1:8000'
          },
```
在其他任何页面里都可以使用模板字符串引用"api": "${ccDomain}/full_data?start_date=20210101&stop_date=20211201",
```
  "body": [
    {
      "type": "crud",
      "name": "sample",
      "api": "${ccDomain}full_data?start_date=20210101&stop_date=20211201",
      "filter": {
```
#### 存在的问题：
查看文档没有发现类似指导

#### 当前方案：
index.html中
 window.ccDomain = String.raw`http://127.0.0.1:8000`;

页面引用
"${window:ccDomain|raw}/full_data?start_date=20210101&stop_date=20211201"

**Comment by BeMxself** [comment]
你可以看看文档里数据映射的namespace小节

**Comment by nwind** [comment]
如果只是 url 替换建议等新的 replaceText 方案
