### ISSUE TITLE
input-tree组件提交source数据需求

### ISSUE THREAD

**Issue by rurico** [baidu/amis#3007]
#### 描述问题：

当前的组件点击input-tree之后，通过form传输的数据只是点击项的数据，无法将编辑过后的input-tree数据保存

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.4.1

3. 粘贴有问题的完整 `amis schema` 代码：
```json
 {
  "type": "input-tree",
  "name": "name",
  "hideRoot": false,
  "showIcon": false,
  "rootLabel": "label",
  "showRadio": false,
  "creatable": true,
  "removable": true,
  "editable": true,
  "showOutline": true
}
```

**Comment by blackhu0804** [comment]
同样存在这个问题，请问如何解决

**Comment by lhtuling** [comment]
你们思路应该走错了...
新增应该是在提交的时候直接就通过接口处理的不是添加到树之后再去获取树的结构数据去保存
看下文档然后自己测试下看看吧!
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-tree#%E5%B1%9E%E6%80%A7%E8%A1%A8
![image](https://user-images.githubusercontent.com/44140500/156988375-3c2b00c5-d603-4f06-8ccd-3e9487b2bd24.png)

建立了一个Amis交流QQ群 感兴趣的可以加下
QQ群号：717791727
