### ISSUE TITLE
能不能实现将固定模式的schema注册作为自定义组件

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#3008]
#### 实现场景：
比如我要实现一个时间跨度编辑器，编辑一个x?月 y?日z?小时的数据结构，这个用combo可以很快就组合出来，可能我有好几处表单都需要编辑这样的值，现在好像只能把这段schema粘贴到不同的地方，或者写一个react组件注册到amis里。

#### 存在的问题：
schema能否在更细的粒度上复用？

**Comment by 2betop** [comment]
自定义组件里面可以这么写 render

```
render() {
  return this.props.render('inner', {
    type: 'combo',
    
  })
}
```

**Comment by BeMxself** [comment]
> 自定义组件里面可以这么写 render
> 
> ```
> render() {
>   return this.props.render('inner', {
>     type: 'combo',
>     
>   })
> }
> ```

好的，感谢解答！

**Comment by BeMxself** [comment]
> 自定义组件里面可以这么写 render
> 
> ```
> render() {
>   return this.props.render('inner', {
>     type: 'combo',
>     
>   })
> }
> ```
我看了下这个函数貌似是 src/Root.tsx 中定义的 renderChild 吧？我看到有三个参数，分别是`prefix, node, props`后两个很容易理解，第一个貌似跟amis的内部运行机制相关的，这个参数有什么要注意的吗？

**Comment by 2betop** [comment]
你可以认为这个是区域，regionName，比如 header, body，footer 什么的，随便填

**Comment by BeMxself** [comment]
> 

好的，感谢！
