### ISSUE TITLE
我想要实现tabs里显示chart

### ISSUE THREAD

**Issue by ccbwx** [baidu/amis#3014]
我想要实现tabs里显示chart

#### 存在的问题：
单独在page里显示chart可以正常显示，如果把chart放到到tabs里什么也不显示

#### 正常方案：
![111](https://user-images.githubusercontent.com/18642187/142732884-8a33f1e0-42f4-4a95-ad55-6c7ab630060a.png)

#### 不正常方案：
![112](https://user-images.githubusercontent.com/18642187/142732886-7b4ab30f-b461-4c55-acda-02688b30d26c.png)

**Comment by nwind** [comment]
没复现版本较老？在官网试试

**Comment by ccbwx** [comment]
谢谢，重新下载最新sdk的beta 1.42正常了
