### ISSUE TITLE
消息提示如何更改？

### ISSUE THREAD

**Issue by DadGuo** [baidu/amis#3017]
#### 实现场景：
我想要相官网一样的消息提示如何做
![image](https://user-images.githubusercontent.com/59001670/142790993-41c829ae-b7d8-43cb-a954-620d2d46be15.png)

#### 存在的问题：
这个提示太靠右了，不美观，还有而且时间太短，form提交成功跳转列表页，那个提示根本就看不见。。
![image](https://user-images.githubusercontent.com/59001670/142791045-d7d7505f-0d8a-4c58-8ab3-edefd3422bb5.png)

#### 当前方案：
当前版本：@license amis v1.3.4

```

```

**Comment by nwind** [comment]
toast 显示问题升级 amis 版本。

消息时间可以通过 msgTimeout 控制，不过似乎新版有问题，等修复。

**Comment by DadGuo** [comment]
这个修复之后是不是要新版本发布之后才能用?大概啥时候发版？

**Comment by DadGuo** [comment]
还有个问题，表单添加成功之后会返回列表页，跨页面之后这个消息提示能一直存在吗？

**Comment by Chen-Wendong** [comment]
@DadGuo 您解决了 toast 在页面中间提示了吗？ 是怎么配置的？是全局配置的吗？
