### ISSUE TITLE
升级最新版本报错！！！

### ISSUE THREAD

**Issue by DadGuo** [baidu/amis#3018]
#### 实现场景：
想要升级最新版本，报错。。

#### 存在的问题：
1.3.4升级到1.4.1
![image](https://user-images.githubusercontent.com/59001670/142796334-4e1e5722-1cb2-4a76-a36f-023e65cc3ab9.png)
![image](https://user-images.githubusercontent.com/59001670/142796355-a9ba9d82-7033-436f-8ec8-1fc276b61537.png)

#### 当前方案：
当前版本：1.3.4
期望：1.4.1

```
code here...
```

**Comment by DadGuo** [comment]
在线等。。求指教

**Comment by nwind** [comment]
文件不存在放错目录了吧

**Comment by DadGuo** [comment]
位置没放错，可能是缓存吧。。方便问下官网文档用的什么版本？感觉升级了没什么变化，跟官网的很多都不一样。
