### ISSUE TITLE
date控件的赋值

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#302]
1、date控件的初始化默认value只能用-2days、+1week之类的相对值吗？能否赋"2019-10-10"之类的绝对值？

2、value是否支持函数赋值？比如希望value是当年元旦（当年是2018年，则是2018-01-01；当年是2019，则是2019-01-01）

**Comment by 2betop** [comment]
1. 当然可以，但是你要注意 format 的设定，默认是 'X' 也就是说初始值你需要设置成时间戳格式。
2. 这个不支持，控件初始值除了前端设置外也可以后端配置，给 form来个 initApi 从后端返回即可，跟编译表单是一个意思。

**Comment by foxfire881** [comment]
已经加了format了，但是不对呢，下面这样设置的话实际在控件显示出来的是”1970-01-01“

{
type:"date",
label:"开始日期",
name:"time1",
value:"2019-10-08",
format:"YYYY-MM-DD"
}

**Comment by 2betop** [comment]
bug 了 https://github.com/baidu/amis/pull/304
着急用就用 1.0.2-beta.25 版本，后面会更新到 1.0.3 版本里面

**Comment by foxfire881** [comment]
嗯，每月一个版本迭代速度慢了点，加油~

**Comment by 2betop** [comment]
1.0.3 发布了
