### ISSUE TITLE
button submit 可以指定对应form提交吗

### ISSUE THREAD

**Issue by SheenaghF** [baidu/amis#3021]
#### 是否关联于某个问题吗：
因为我没办法实在在page层的toolbar进行form表单的提交，首先获取不到对应的数据

#### 预期的解决方案：
指定对应的form设定的name，进行提交

#### 其他可接受方案：
暂无

#### 任何附加信息：
暂无

**Comment by 2betop** [comment]
可以，设置 target 为 form 的 name 属性
