### ISSUE TITLE
Condition-builder通过source动态获取条件不可用

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#3026]
#### 描述问题：

Condition-builder通过source动态获取条件不可用，两个问题：
1、之前接口返回一个数组即可自动识别，现在必须要返回一个`{“fields”: [xxx]}`才能用而直接返回数组会报错，break change。
2、通过接口返回了符合要求的格式，添加条件时下拉框能看到条件，但是选择某个条件时只看到key，无法选择operation和value，严重bug。

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
V 1.4.2-beta.1

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
参见官网[例子](https://baidu.gitee.io/amis/zh-CN/components/form/condition-builder#%E5%AD%97%E6%AE%B5%E9%80%89%E9%A1%B9%E8%BF%9C%E7%A8%8B%E6%8B%89%E5%8F%96)

**Comment by belongwqz** [comment]
@nwind @2betop 帮看看，因为以上原因这个组件已经不能用了，官网例子也是失效的

**Comment by lurunze1226** [comment]
[780e65370e8f49a281a7996fcb13557a82ea8a22](https://github.com/baidu/amis/commit/780e65370e8f49a281a7996fcb13557a82ea8a22) 问题修复了
