### ISSUE TITLE
我想实现在table表columns列居中对齐或右对齐后，affixRow汇总行无法居中对齐或右对齐

### ISSUE THREAD

**Issue by ccbwx** [baidu/amis#3038]
#### 实现场景：
我想实现在table表affixRow汇总行和对应的columns列一样的对齐方式

#### 存在的问题：
在table表columns列居中对齐或右对齐后，affixRow汇总行无法居中对齐或右对齐

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
![111](https://user-images.githubusercontent.com/18642187/143067856-cbf7b21d-83c7-4fbd-a90b-89b1db8d6363.jpg)
![222](https://user-images.githubusercontent.com/18642187/143067899-2bad5409-910c-499c-ab76-bd390edb1749.jpg)

```
code here...
```

**Comment by 2betop** [comment]
总结行需要配置 `cellClassName` 为 "text-right"，后续修改成也支持 align 属性
