### ISSUE TITLE
crud 列中根据每行内容设置className，列的表头的className出错问题

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#3039]
#### 描述问题：
crud用来显示的Reports中数据，每行记录中有一个 审核状态 字段. 希望根据状态的不同，显示不同的颜色。
设置如下：

{
              "type": "text",
              "label": "审核状态",
              "name": "shenhe_zt",
              "className": {
                "bg-success": "this.shenhe_zt=='未审核'",
                "bg-warning": "this.shenhe_zt=='审核中'",
                "bg-gray-400": "this.shenhe_zt=='审核通过'",
                "bg-danger": "this.shenhe_zt=='审核未通过'",
                "bg-info": "this.shenhe_zt=='待复审'"
              }
            }

问题：当前1.4.1版本的js版本的sdk中，"审核状态" 的表头会变为红色。期望是表头无颜色，各行内容变颜色
         

#### 截图或视频：

![image](https://user-images.githubusercontent.com/13453002/143153256-16294c9f-b387-4221-9c2f-66e7f9cb59b1.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.4.1

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "title": "测试页面",
  "body": [
        {
          "type": "crud",
          "api": {
            "url": "/api/Baobiao/",
            "headers": {
              "Authorization": "Token ${ls:my_token}"
            },
            "adaptor": "for (let i=0;i<payload.data.items.length;++i){if(payload.data.items[i].shenhe_zt==0)payload.data.items[i].shenhe_zt='未审核';if(payload.data.items[i].shenhe_zt==1)payload.data.items[i].shenhe_zt='审核中';if(payload.data.items[i].shenhe_zt==2)payload.data.items[i].shenhe_zt='审核未通过';if(payload.data.items[i].shenhe_zt==3)payload.data.items[i].shenhe_zt='待复审';if(payload.data.items[i].shenhe_zt==4)payload.data.items[i].shenhe_zt='审核通过'}  return payload;\n",
            "method": "get"
          },
          "columns": [
            {
              "name": "id",
              "label": "ID",
              "type": "text"
            },
            {
              "type": "text",
              "label": "审核状态",
              "name": "shenhe_zt",
              "className": {
                "bg-success": "this.shenhe_zt=='未审核'",
                "bg-warning": "this.shenhe_zt=='审核中'",
                "bg-gray-400": "this.shenhe_zt=='审核通过'",
                "bg-danger": "this.shenhe_zt=='审核未通过'",
                "bg-info": "this.shenhe_zt=='待复审'"
              }
            }
          ]
        }
  ]
}
```

4. 操作步骤
直接渲染

**Comment by 2betop** [comment]
不要设置在列上，可以来个 container，放在里面比如

```
{
  "type": "container",
  "label": "审核状态",
  "name": "shenhe_zt",
  "body": [{
    "type": "text",
    "className": {
    "bg-success": "this.shenhe_zt=='未审核'",
    "bg-warning": "this.shenhe_zt=='审核中'",
    "bg-gray-400": "this.shenhe_zt=='审核通过'",
    "bg-danger": "this.shenhe_zt=='审核未通过'",
    "bg-info": "this.shenhe_zt=='待复审'"
  }
  }]
}
```

**Comment by Jiangshan00001** [comment]
解决header上有颜色的问题了。
但是带来了和之前的不兼容问题： 之前设置的颜色是背景，当前单元格背景颜色。现在变成了单元格内文字的背景颜色。
有什么设置方式能改为和之前一样么（根据内容，设置单元格的背景颜色）？

之前的显示方式：是 每一列每一行的单元格背景颜色修改（）
![image](https://user-images.githubusercontent.com/13453002/144201312-ae2d2bc1-1c64-4083-8204-e71a133db4ec.png)


改为container之后，变为：行列内的文字区域的背景颜色
![image](https://user-images.githubusercontent.com/13453002/144201447-7f5fc78a-d455-4784-877a-3cf5116486b8.png)

如何根据数据内容，修改单元格背景颜色？
