### ISSUE TITLE
当前的API请求顺序是由内向外，会导致部分作用域被覆盖

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#3046]
#### 描述问题：
可能使用的方式不是很对。

在 form 中有 service 请求数据，假设 service 返回值是一个数组，那么会默认成 【data.items】。如果 form 的初始化接口返回值中也有【items】，此时 form 中的 items 会把 service 中的 items 给覆盖。

原因是因为 service 的请求先于 form 的请求。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
type: form
api:xxx
body:[
{
type: service
api: xxx
}
]
}
```

4. 临时解决办法
在 service 的 API 中使用【responseData】修改成其它名称
api: {
responseData{
ABC: "$$"
}
}

**Comment by 2betop** [comment]
嗯，目前加载时机确实是 react 的 didMount, 是里面的先执行，然后外面的。不过可以通过这个方式控制时序。

https://baidu.gitee.io/amis/zh-CN/docs/types/api#%E8%87%AA%E5%8A%A8%E5%88%B7%E6%96%B0
