### ISSUE TITLE
CURD组件其它组件触发reload的时候怎么重置分页到第一页

### ISSUE THREAD

**Issue by yangyining** [baidu/amis#3056]
#### 实现场景：
例如新增页面提交后触发刷新表格，目前会在当前分页刷新，我想实现将分页号重置为1刷新

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by yangyining** [comment]
找到方法了，可以在刷新目标后面增加参数，如：xxx`?page=1`。但是这个文档好像没写啊。

**Comment by 2betop** [comment]
文档在这：https://baidu.gitee.io/amis/zh-CN/docs/concepts/linkage?page=1#%E5%8F%91%E9%80%81%E6%8C%87%E5%AE%9A%E6%95%B0%E6%8D%AE
