### ISSUE TITLE
tagret: 'window' 会重复base路径

### ISSUE THREAD

**Issue by Leonard-Li777** [baidu/amis#306]
当项目根路径为http://xxx.com/basePath 的时候，如

http://xxx.com/basePath/abc
tagret: 'window' 会变成
http://xxx.com/basePath/basePath/abc?a=x&b=y

**Comment by 2betop** [comment]
这个应该是 env.updateLocation 里面的逻辑问题吧，这个是使用法传入的，我想处理一下一下这个应该就可以了。

**Comment by Leonard-Li777** [comment]
好的，我看看
