### ISSUE TITLE
form submit按钮多次点击时会出现报错

### ISSUE THREAD

**Issue by tangjion** [baidu/amis#3062]
具体报错如下：
`[mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'FormStore', Path upon death: '', Subpath: 'submiting', Action: '.submit()'). Either detach nodes first, or don't use objects after removing / replacing them in the tree.`

**Comment by 2betop** [comment]
请提供更多的信息，比如页面的配置，如果有接口，接口的返回数据等，否则不好定位问题呢
