### ISSUE TITLE
"background": "url(${imgHost}/04679ac087956b820d3c5c1513985b6e.png)"  这样写不行吗 ？imgHost映射不了？

### ISSUE THREAD

**Issue by ZSSsongshu** [baidu/amis#3070]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by ZSSsongshu** [comment]
"api": "${HOST|raw}/standard_data_screen_api"

**Comment by ZSSsongshu** [comment]
"api": "${HOST|raw}/standard_data_screen_api"

**Comment by ZSSsongshu** [comment]
"api": "${HOST|raw}/standard_data_screen_api"  api可以这样   backgound url下 该怎么弄？

**Comment by nwind** [comment]
等新版换新方案吧
