### ISSUE TITLE
官方文档无法查看多出屏幕尺寸的左侧导航

### ISSUE THREAD

**Issue by wero-dev** [baidu/amis#3076]
![image](https://user-images.githubusercontent.com/82741732/143673013-996bceef-b61e-40f1-bc5e-18acd682e09e.png)
这里已经到底 , 但是左侧导航还有非常多的东西 .
已经无法再滑动了.
使用的Edge浏览器
在chrome也尝试了, 依然是无法滑动 .

Microsoft Edge
Version 96.0.1054.34 (Official build) (64-bit)

Chrome is up to date
Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by wero-dev** [comment]
gitee.io 是这样
github.io 没有问题

**Comment by lurunze1226** [comment]
已修复 @wero-dev
