### ISSUE TITLE
自定义的组件使用接口的问题

### ISSUE THREAD

**Issue by lck123357** [baidu/amis#3088]
请问：自定义的组件可以直接在右侧使用类似通用组件的那种接口配置吗？如果可以应该怎么配置呢？
 还是说自定义组件右侧配置框内的都要自己实现？

**Comment by nwind** [comment]
编辑器？有个 `getSchemaTpl('api', {label: '接口'})` 方法，在 component/schemaTpl 里

**Comment by lck123357** [comment]
不好意思，我没有找到这个方法，也没有找到对应的文件

**Comment by lck123357** [comment]
感谢。找到了
