### ISSUE TITLE
提供百度地图组件

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#3092]
能否像集成echarts类似的方式，集成百度地图的api到amis中。
经过研究当前系统已经提供了LocationPicker 地理位置选择器，这仅是选择位置的一个表单项。
我希望官方能够提供的组件是能够暴露地图更多的api，便于二次开发基于百度地图的位置类应用。比如多边形查询、动态热力等效果。
感谢。

**Comment by nwind** [comment]
目前 echarts 里的 bmap 已经集成了，如果还不能满足，建议写自定义组件
