### ISSUE TITLE
property组件通过source获取上下文的样例挂了

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#3095]
#### 描述问题：

property组件通过source获取上下文的样例挂了，不知是不是新特性修改引入

#### 截图或视频：

https://baidu.gitee.io/amis/zh-CN/components/property

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
#3089 中修复了
