### ISSUE TITLE
使用antd封装的自定义组件，可以配置原生组件的那些接口方法吗？

### ISSUE THREAD

**Issue by lck123357** [baidu/amis#3098]
我使用antd封装了一个自定义的类型增删查改的组件，想在这个组件上使用接口调用，请问是需要我自己写，还是可以直接用原声组件的那些方法呢？

**Comment by nwind** [comment]
建议用 env.fetcher 保持统一 https://baidu.gitee.io/amis/zh-CN/docs/extend/custom-react#%E5%85%B6%E4%BB%96%E5%8A%9F%E8%83%BD%E6%96%B9%E6%B3%95

**Comment by xiaoji201509** [comment]
@nwind 你给的地址无法打开，请问用vue3-amis-widget 注册的vue组件如何才能拿到这个env.fetcher ，目前是拿不到的
