### ISSUE TITLE
${xxx|division:2} not work

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#3106]
#### 描述问题：

除法不好使

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
    {
      "type": "input-text",
      "label": "文本",
      "name": "value"
    },
    {
      "type": "plain",
      "tpl": "${value| division:2}",
      "inline": false
    }
  ]
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
有报错吗？

**Comment by lengqingfeng** [comment]
> 有报错吗？

除法不生效

**Comment by 2betop** [comment]
什么版本？可能是版本问题？最新版本应该可以
