### ISSUE TITLE
amis@1.5.0 启动白屏

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#3107]
#### 描述问题：

用官方的快速开始项目测试，更新至1.5.0后启动项目白屏，控制台输出：

> Uncaught TypeError: Cannot read properties of undefined (reading 'call')
>    at __webpack_require__ (index.js:3042)
>    at Object.752 (index.js:3018)
>    at __webpack_require__ (index.js:3042)
>    at Object.303 (index.js:1209)
>    at __webpack_require__ (index.js:3042)
>    at index.js:3053
>    at Object../node_modules/amis-formula/dist/index.js (index.js:3058)
>    at __webpack_require__ (bootstrap:63)
>    at Object../node_modules/amis/lib/utils/tpl-builtin.js (tpl-builtin.js:7)
>    at __webpack_require__ (bootstrap:63)

#### 截图或视频：

![image](https://user-images.githubusercontent.com/3793855/144164661-eb490ef0-9d54-4094-a307-98db941415da.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.5.0

3. 粘贴有问题的完整 `amis schema` 代码：
无

4. 操作步骤

* 克隆 amis-react-starter 代码
* 更新 amis 版本到 1.5.0（以及安装 font-awesome 包）
* npm run start

**Comment by yangyining** [comment]
遇到了同样的问题，我还以为我集成的有问题

**Comment by nwind** [comment]
已经更新了，看起来是 webpack 需要 5
