### ISSUE TITLE
1.5.0 filter行为发生改变造成break change

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#3109]
#### 描述问题：

1.5.0 filter行为发生改变，导致crud的前端一次性加载前端搜索功能失效。

#### 截图或视频：

1.4.1版本的“crud的前端一次性加载前端搜索”例子可以加载出表格数据，1.5.0中的例子已经加载不出数据表格为空。

另外，配置loadDataOnce前端一次性加载后，配置filter进行搜索，还是会先使用api去后端拉取一次数据再filter，按理应该在点击搜索时直接使用之前加载来的前端数据进行filter无须调用api获取后端数据了。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
   1.5.0

3. 粘贴有问题的完整 `amis schema` 代码：
1.5.0将 
```
"source": "${rows | filter:engine:match:keywords}"
```
改为
```
"source": "${IF(ISEMPTY(keywords), rows, ${rows|filter:engine:match:keywords})}"
```
则可用，新语法不该影响老语法的行为造成break change。

4. 操作步骤
见crud[官网例子](https://baidu.gitee.io/amis/zh-CN/components/crud#%E5%89%8D%E7%AB%AF%E4%B8%80%E6%AC%A1%E6%80%A7%E5%8A%A0%E8%BD%BD)

**Comment by 2betop** [comment]
感谢反馈，可以先手动升级 amis-formula 到 1.1.7 解决这个问题。

之前的用例不到位，补充了相关用例：https://github.com/aisuda/amis-formula/blob/main/__tests__/compat.test.ts#L468-L522
