### ISSUE TITLE
amis1.5.0 Uncaught TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by h7ml** [baidu/amis#3110]
#### 描述问题：

``amis1.5.0`` 报错 ``Uncaught TypeError: Cannot read properties of undefined (reading 'call')``

#### 截图或视频：

![image](https://user-images.githubusercontent.com/55233292/144179330-05783818-e4bc-4957-ad3c-df8b1fcc1b8a.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. amis 版本是什么？
``1.5.0``

4. 操作步骤
webpack引入``amis1.5.0``

**Comment by nwind** [comment]
已经更新了，看起来是 webpack 需要 5
