### ISSUE TITLE
在api里怎么实现 "http://www.baidu/com?q=${count}*100"这种效果

### ISSUE THREAD

**Issue by ZSSsongshu** [baidu/amis#3112]
#### 描述问题：

在api里怎么实现 "http://www.baidu/com?q=${count}*100"这种效果  因为有时候需要更改参数才能传递到后段

**Comment by h7ml** [comment]
配数据映射，在数据请求的时候拦截下

**Comment by 2betop** [comment]
1.5.0 开始可以这样写 ${count * 100} 

https://baidu.gitee.io/amis/zh-CN/docs/concepts/expression#%E6%96%B0%E8%A1%A8%E8%BE%BE%E5%BC%8F%E8%AF%AD%E6%B3%95
