### ISSUE TITLE
下拉如何实现联动+搜索（远程：autoComplete）

### ISSUE THREAD

**Issue by DadGuo** [baidu/amis#3128]
#### 实现场景：
下拉如何实现联动+搜索（远程：autoComplete）

#### 存在的问题：
单独使用source可以实现联动："source":"get:/amis/options/getPersonByDeptId?deptId=${deptId}",
单独使用autoComplete可以实现远程搜索："autoComplete":"get:/amis/options/getDutyPersonByDeptId?term=${term}&deptId=${deptId}",
但是我想实现上一个部门下拉切换的时候，人员下拉能联动，同时我的人员也能支持远程搜索，现在怎么弄都不行，文档上有个searchApi，但是也不生效
![Uploading image.png…]()
![normal video](https://user-images.githubusercontent.com/59001670/144388780-cda16a95-2e67-44fd-acfa-26d8843b71f4.gif)
![normal video2](https://user-images.githubusercontent.com/59001670/144390959-d58a6e78-382c-4b70-bb83-be99f69811f8.gif)

如图，实现远程搜索之后，就不会联动了...只有我清除了搜索文字或者重新输入才会，不然我上面的部门怎么切，下面的数据都不会变化，求解

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
{
    "type": "select",
    "label": "责任人姓名：",
    "name": "dutyStaffId",
    "required": true,
    "placeholder": "请选择",
    "mode": "horizontal",
    "size": "lg",
    "clearable": true,
    "searchable": true,
    // "source":"get:/amis/options/getPersonByDeptId?deptId=${deptId}",
    "autoComplete":"get:/amis/options/getPersonByDeptId?term=${term}&deptId=${deptId}",
},
```

**Comment by ITstyle** [comment]
唉，升级之后我也遇到这个问题了，害的我都不敢更新，又退回老版本

**Comment by Brian175** [comment]
和这个类似的，https://github.com/baidu/amis/issues/2289。

**Comment by zyifan** [comment]
请问解决了吗
