### ISSUE TITLE
reset 重置在这种情况下无效

### ISSUE THREAD

**Issue by ZSSsongshu** [baidu/amis#3129]
具体操作是，先输入数字，然后点击查询，此时接口url中有填写的数字参数p有值，此时点击重置，表单中显示没了，但是这时候再次点击查询，接口url中有填写的数字参数p还是有值？

{
    "type": "page",
    "body": [
        {
            "type": "form",
            "body": [
                {
                    "type": "input-number",
                    "placeholder": "",
                    "name": "rep_ms_min",
                    "size": "lg",
                    "showSteps": false,
                    "label": "数字"
                }
            ],
            "title": "",
            "mode": "horizontal",
            "actions": [
                {
                    "type": "reset",
                    "label": "重置"
                },
                {
                    "type": "submit",
                    "label": "查询"
                }
            ],
            "target": "target_service"
        },
        {
            "name": "target_service",
            "type": "service",
            "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/page/initData?p=${rep_ms_min}",
            "body": [
                {
                    "type": "panel",
                    "title": "$title",
                    "body": [
                        {
                            "type": "tpl",
                            "tpl": "现在是：${date}",
                            "inline": false
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by hsm-lv** [comment]
target的功能是向目标组件的数据域发送数据，第一次发送的值比如是rep_ms_min:111，重置后form的里的数据是空，再次查询向target发送数据的时候其实发送的数据是空的，所以并不能覆盖上一次的值
