### ISSUE TITLE
api中使用data定义的参数不支持联动

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#3133]
#### 描述问题：
api中使用data定义的参数不支持联动

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
url:"abc.html"
data:{
type:"${abc}"
}
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
文档有说明：https://baidu.gitee.io/amis/zh-CN/docs/types/api#%E8%87%AA%E5%8A%A8%E5%88%B7%E6%96%B0
