### ISSUE TITLE
过滤器 pick 对空值也有效果

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#3134]
#### 描述问题：

在list-select中通过API请求数据，在返回结果中做映射。使用了：

`${xxx|pick:label~cnName,value~cnName}`

这里的xxx不存在，所以是空值。
此时会有两个框。

#### 截图或视频：
![image](https://user-images.githubusercontent.com/436109/144442301-2df375e3-8049-4ed1-a21f-1e49b4cd2c37.png)
![image](https://user-images.githubusercontent.com/436109/144442326-619088b3-2e27-4f86-9f00-5b5fe8f09192.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
              "type": "list-select",
              "name": "one",
              "label": "abc",
              "source": {
                "method": "post",
                "url": "baidu.com"
                "responseData": {"options":"${xxx|pick:label~cnName,value~cnName}"}
              }
            }
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by hsm-lv** [comment]
可以在前面加个filter过滤，再进行pick
