### ISSUE TITLE
动态name

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#3135]
#### 是否关联于某个问题吗：
我想使用 service 的 schemaApi 来构建基于基础组件的远程复杂组件。

现在的问题是通过 schemaApi 调用后，无法动态的修改 formItem 的 name 属性。这就导致适应性上存在缺陷。

第二预期：
如果实现动态 name ，那么这个 name 的值只能配置在 service 的 data 中。
这是否会导致提交 form 表单的时候把这些临时的名称变量也提交到服务器？
是不是可以在现在的数据域与数据链外面加一个临时空间？用来存放不需要提交的数据。

#### 预期的解决方案：
实现动态 name。

**Comment by 2betop** [comment]
schemaApi 返回的表当项 name，对于后端来说这个 name 是动态的呢

**Comment by lameroy** [comment]
radios/checkboxes 可以动态设置name吗？
将radios/checkboxes 放在each循环里导致name都是一个, 取值只能取到一个值

**Comment by 17671881483** [comment]
请问这个现在有对应解决方案吗

**Comment by nwind** [comment]
新版已经支持了 #8452
