### ISSUE TITLE
返回格式里面的字段名能否自定义

### ISSUE THREAD

**Issue by osenlin** [baidu/amis#3144]
在对接服务端服务的时候，有个api，但是返回值的状态码是return_code不是status，就无法正确判断,请问amis有提供这种字段名自定义的功能，把status改为return_code?

**Comment by lurunze1226** [comment]
使用接收适配器 https://baidu.gitee.io/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8
