### ISSUE TITLE
表单提交会执行 validateApi ，导致修改页面保存时无法保存

### ISSUE THREAD

**Issue by Chen-Wendong** [baidu/amis#3149]
#### 描述问题：

表单提交会执行 validateApi ，导致修改页面保存时无法保存，因为validateApi会去检查，因为没修改，本来就已存在，后台返回422！

新增时，如果validateApi如果不设置data，也会有同样的问题，会新增完后检查，新增界面没消失，停留在那报错！

#### 截图或视频：

![image](https://user-images.githubusercontent.com/88780174/144714810-37476d5a-5ada-4227-93d2-eeaecefee509.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.4.2-bate

3. 粘贴有问题的完整 `amis schema` 代码：
```

{
  "type": "input-text",
  "label": "名称",
  "name": "Name",
  "required": true,
  "validateOnChange": true,
  "validateApi": {
    "method": "post",
    "url": "/ram/server/module/exist",
    "data": {
      "Name": "${Name}"
    }
  },
  "validations": {
    "maxLength": 32
  }
}

```

**Comment by 2betop** [comment]
是不是应该把 id 传给后端，后端判断的时候把 not(thisId) 条件加上？
