### ISSUE TITLE
ajax动作无法下载文件

### ISSUE THREAD

**Issue by GYICN** [baidu/amis#3153]
#### 描述问题：
配置ajax下载文件，能成功获取response，但是下载不到本地
报错：
Error Unexpected token P in JSON at position 0

#### amis版本：
1.3.2

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
{
    "type": "button",
    "label": "按钮",
    "actionType": "ajax",
    "api": {
        "method": "post",
        "url": "xxxxx",
        "responseType": "blob"
    },
    "confirmText": "确认下载？",
    "disabled": false
}
```

#### 操作步骤：
点击按钮

注：在postman上进行测试，可以正常下载

**Comment by 2betop** [comment]
需要提供 api 的 responseHeader 信息。或者用最新版本试试看

**Comment by GYICN** [comment]
已解决，跨域问题~
