### ISSUE TITLE
关于简单新增/修改表单共用一个form的问题如何实现更合理？

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#3160]
#### 实现场景：

有一些简单的业务，新建和修改的的表单一摸一样，只是调用接口不一样，比如：
新增使用接口：post:/api/collection
修改使用接口：put:/api/collection/$id

#### 存在的问题：
在大多数情况下，可以直接用类似这样的模版字符串：
`${id|isTrue:"put:/collection/":"post:/collection"}${id}`
但是一旦需要重映射data就无能为力了，因为对象形式的api不能动态改变method字段，有没有办法能够优雅的处理这个场景呢？

#### 当前方案：
当前可以用definition来处理，但是总觉得差点意思。

**Comment by hsm-lv** [comment]
目前没有比较好的方式，最好后端根据id参数进行区分，method可以不做区分
