### ISSUE TITLE
表达式增强

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#3161]
#### 是否关联于某个问题吗：
已有STARTSWITH表达式，要是能增加ENDSWITH就好了。

#### 预期的解决方案：
比如像把“ABC.BCD.xlsx”转换为“ABC.BCD”，ENDSWITH可以帮助先判断是否以".xlsx"结尾。当然，以当前的表达式，要达到去掉结尾的".xlsx"还是不太好实现，也帮看看怎么写比较好。

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by leaf188** [comment]
如果字段名字为a，公式写法如下：
`"formula": "this.a.substr(0,this.a.lastIndexOf('.'))"`

如果只是用模板展示数据，写法如下：
`"tpl": "<%=this.a.substr(0,this.a.lastIndexOf('.')) %>"`

**Comment by nwind** [comment]
ENDSWITH 已经有了
