### ISSUE TITLE
input-datetime值格式设为时间戳（x或X）时，值类型能否自动转为整数？

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#3165]
#### 实现场景：
后端接口要求传入整型时间戳，使用input-datetime没有办法配置成整数类型的时间戳
使用formula转换会产生不必要的临时数据，使用数据映射无法处理未知层级的树形结构

#### 存在的问题：
input-datetime 不能返回整数类型的时间戳

**Comment by leaf188** [comment]
使用js函数转换

**Comment by leaf188** [comment]
公式用法：

**Comment by leaf188** [comment]
使用公式转换日期字段，公式对应的组件类型设置为input-number，公式使用js函数parseInt转换，后端接收转换：
`parseInt(fieldName)`
然后配置数据映射，把日期字段对应的值设为`__undefine`
