### ISSUE TITLE
建议 GridNav  增加支持 onClick

### ISSUE THREAD

**Issue by Chen-Wendong** [baidu/amis#3166]
建议 GridNav  增加支持 onClick

我想通过 GridNav 的 onClick 将左侧栏收起来！

 "onClick": "var e = document.getElementsByClassName('antd-AppFoldBtn');\nif(e[0].outerHTML.includes('fa-dedent')) {e[0].click();}"

**Comment by hsm-lv** [comment]
https://baidu.github.io/amis/zh-CN/components/grid-nav#%E7%82%B9%E5%87%BB%E4%BA%A4%E4%BA%92
