### ISSUE TITLE
日历日程的颜色配置只有云舍主题生效

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#3167]
#### 描述问题：

官网日历日程的颜色配置只有云舍主题生效，其他主君看不到颜色。

#### 截图或视频：

见[官网示例](https://baidu.gitee.io/amis/zh-CN/components/form/input-date#%E6%97%A5%E5%8E%86%E6%97%A5%E7%A8%8B)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by allenve** [comment]
用最新版再看看
