### ISSUE TITLE
amis有icon列表可以选择吗

### ISSUE THREAD

**Issue by koala-wei** [baidu/amis#3181]
#### 实现场景：
我需要用到一些常用的icon，由于一些通用的icon，自己引入比较麻烦，我现在只能通过f12看示例源码，获取到amis中的一些icon进行使用。

#### 存在的问题：
没有icon文档，以及示例
![image](https://user-images.githubusercontent.com/57615200/145331926-2fbd15e1-b128-494f-8370-30acac9039fc.png)

**Comment by Chen-Wendong** [comment]
https://fontawesome.com/v5.15/icons

**Comment by xiahao90** [comment]
恭喜你触发隐藏组件：
{
                                        "type": "icon-picker",
                                        "name": "icon",
                                        "label": "图标",
                                        "labelField": "text",
                                    }

**Comment by Twelveeee** [comment]
> 恭喜你触发隐藏组件： { "type": "icon-picker", "name": "icon", "label": "图标", "labelField": "text", }

没显示全

**Comment by MaxToby** [comment]
> 
```
import { setIconVendor } from 'amis'

setIconVendor([
  {
    name: 'Font Awesome 4.7',
    prefix: 'fa fa-',
    icons: [
      'slideshare',
      'snapchat',
      'snapchat-ghost',
      'snapchat-square',
      'soundcloud',
      'spotify',
      'stack-exchange',
      'stack-overflow',
      'arrows-alt',
      'clock-o',
    ],
  },
])
```

**Comment by nwind** [comment]
https://fontawesome.com/icons

**Comment by xiahao90** [comment]
> > 
> 
> ```
> import { setIconVendor } from 'amis'
> 
> setIconVendor([
>   {
>     name: 'Font Awesome 4.7',
>     prefix: 'fa fa-',
>     icons: [
>       'slideshare',
>       'snapchat',
>       'snapchat-ghost',
>       'snapchat-square',
>       'soundcloud',
>       'spotify',
>       'stack-exchange',
>       'stack-overflow',
>       'arrows-alt',
>       'clock-o',
>     ],
>   },
> ])
> ```

请问有没有sdk的使用版本？
