### ISSUE TITLE
如何列表展示字符串数组

### ISSUE THREAD

**Issue by ArataLee** [baidu/amis#3188]
#### 实现场景：
列表展示后端返回的字符串数组，比如查看某个目录下的文件，后端返回如下格式：{"files": ["a","b","c"]}，期望文件名能以列表的形式展开显示，求大佬指点

#### 存在的问题：
目前使用input-table，可以展示，但是文件在一行展示并展示了相同的多行
![image](https://user-images.githubusercontent.com/89568835/145550743-a3ca7735-4ec7-4f1d-8724-966335c20147.png)

#### 当前方案：
目前是使用input-table

{
  "type": "input-table",
  "title": "文件",
  "name": "files",
  "submitText": "",
  "wrapWithPanel": false,
  "columns": [
      {
              "name": "files",
              "label": "文件"
      }
  ]
}

**Comment by haoxj0823** [comment]
> #### 实现场景：
> 列表展示后端返回的字符串数组，比如查看某个目录下的文件，后端返回如下格式：{"files": ["a","b","c"]}，期望文件名能以列表的形式展开显示，求大佬指点
> 
> #### 存在的问题：
> 目前使用input-table，可以展示，但是文件在一行展示并展示了相同的多行 ![image](https://user-images.githubusercontent.com/89568835/145550743-a3ca7735-4ec7-4f1d-8724-966335c20147.png)
> 
> #### 当前方案：
> 目前是使用input-table
> 
> { "type": "input-table", "title": "文件", "name": "files", "submitText": "", "wrapWithPanel": false, "columns": [ { "name": "files", "label": "文件" } ] }

把 column 的 name 改为 "${files[index]}"

**Comment by ArataLee** [comment]
> 
改完不显示了
![image](https://user-images.githubusercontent.com/89568835/145943395-ca18943d-b0de-4cc2-ae8e-71b958539067.png)

**Comment by haoxj0823** [comment]
```json
{
  "type": "page",
  "data": {
    "files":[
      "a",
      "b",
      "c"
    ]
  },
  "body": [
    {
      "type": "input-table",
      "title": "文件",
      "name": "files",
      "columns": [
        {
          "name": "files[index]",
          "label": "文件"
        }
      ]
    }
  ]
}
```
上面的JSON是可以的，你可以复制看一下效果

**Comment by ArataLee** [comment]
> 

按上边的新写了一个页面还是不显示，我用的是sdk
![image](https://user-images.githubusercontent.com/89568835/145948863-823d397f-e3e4-480d-963c-1e20addbd5aa.png)

**Comment by haoxj0823** [comment]
![image](https://user-images.githubusercontent.com/16603014/145949755-a17c8c6a-7bc1-4fa2-972a-065537ae56a3.png)
这是把JSON放到官网示例中的效果

**Comment by ArataLee** [comment]
> ![image](https://user-images.githubusercontent.com/16603014/145949755-a17c8c6a-7bc1-4fa2-972a-065537ae56a3.png) 这是把JSON放到官网示例中的效果

解决了，把sdk升级到最新的可以了
