### ISSUE TITLE
CRUD column name中包含符号时无法正常显示数据

### ISSUE THREAD

**Issue by 1178615156** [baidu/amis#3189]
#### 描述问题：

例如`name`为`hello-world`时候,因为包含符号`-`会无法正常显示数据. 去掉符号`-`之后就能正常显示了.    

测试过基本所有的符号都会触发这个问题,英文字符和中文字符没问题例如`hello你好`能正常显示.  

```json
"columns": [
  {
    "name": "hello-world",
    "label": "hello-world"
  }
]
```
#### 截图或视频：
![1639128861(1)](https://user-images.githubusercontent.com/8329255/145551613-9ff9eb19-e30e-4971-a129-47ae7ecfaa70.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdts

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.5.3

3. 粘贴有问题的完整 `amis schema` 代码：
```json
 {
    "type": "service",
    "data":{
      "rows":[
        {
          "hello-world": "aaaaaa",
          "id": 1
        }
      ]
    },
    "body": [
      {
        "type": "table",
        "title": "表格",
        "source": "$rows",
        "columns": [
          {
            "name": "hello-world",
            "label": "hello-world"
          },
          {
            "name":"id",
            "label":"id"
          }
        ]
      }
    ]
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by haoxj0823** [comment]
把 column 的 name 改为 "&['hello-world']"

**Comment by 1178615156** [comment]
> 把 column 的 name 改为 "&['hello-world']"

可以了,多谢.

**Comment by 1178615156** [comment]
> 把 column 的 name 改为 "&['hello-world']"

这样子虽然能够正常显示了,但是导出的excel了又会没数据...

**Comment by haoxj0823** [comment]
这样操作始终都是一些临时方案，同时还会有一些限制，最好用 API 的接收适配器，把属性名修正过来

**Comment by 1178615156** [comment]
> 



> 这样操作始终都是一些临时方案，同时还会有一些限制，最好用 API 的接收适配器，把属性名修正过来

恩,谢谢了.
