### ISSUE TITLE
数字选择器上下箭头显示不正确

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#3191]
![image](https://user-images.githubusercontent.com/5292190/145702647-ee9fe58d-0693-4500-b9c5-644e5b12950b.png)
使用amis-editor-demo，添加input-number发现选择器上下箭头不正确。

**Comment by zhyc9de** [comment]
试试补上`iconfont.css`

**Comment by dbkuaizi** [comment]
缺少图标文件导致的
 在页面引入 图标css即可
 `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/amis/sdk/iconfont.css">`

**Comment by nwind** [comment]
嗯是少了 iconfont

**Comment by cmdares** [comment]
感谢回复，希望官方补充到代码库中。

**Comment by iceqing** [comment]
> 缺少图标文件导致的 在页面引入 图标css即可 `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/amis/sdk/iconfont.css">`

👍我使用的react项目，添加样式后好了。
```
import 'amis/sdk/iconfont.css'
```
