### ISSUE TITLE
官方示例，页面样式异常

### ISSUE THREAD

**Issue by Yansh-vic** [baidu/amis#3198]
#### 描述问题：官方示例，页面样式异常,具体见下方复现步骤

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频： 
![图片](https://user-images.githubusercontent.com/49512312/145797723-26f5cc66-fe3b-4a41-825c-abb41c514e83.png)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...
官方示例链接：https://baidu.github.io/amis/examples/dialog/simple
点击【弹个表单】按钮，在弹窗中直接点击【确认】按钮，展示如截图

**Comment by nwind** [comment]
这个界面比较特殊，一般弹框没那么多按钮，我们加宽一下好了
