### ISSUE TITLE
condition-builder增加children折叠

### ISSUE THREAD

**Issue by VonnOoO** [baidu/amis#3201]
#### 是否关联于某个问题吗：
我想实现组合条件condition-builder组件中的left(第一个选项框)中具有层次信息，并可折叠，类似于TreeSelect组件

#### 预期的解决方案：
期望可以类似于TreeSelect组件，具有层次信息，并可折叠

**Comment by allenve** [comment]
已支持，参考 https://aisuda.bce.baidu.com/amis/zh-CN/components/form/condition-builder
