### ISSUE TITLE
app模式下后台的某些二级页面不在pages里面，怎么处理

### ISSUE THREAD

**Issue by gillbates** [baidu/amis#3202]
#### 实现场景：
比如说某个列表，表单里面有个编辑按钮，会有个二级的编辑页面。这个页面不想出现在左边的目录树里面。

#### 存在的问题：
貌似，如果这个二级的编辑页面如果不在app的pages里面定义，amis就找不到路由了。。。不知道是否有什么属性可以定义下。。。

**Comment by dbkuaizi** [comment]
可以依旧放在菜单中，通过 visible 参数隐藏掉就可以了

**Comment by gillbates** [comment]
好的，搞定了，谢谢楼上的同学。@dbkuaizi
