### ISSUE TITLE
表单服务端校验提交后后端没有errors字段返回，前端如何低代码的方式实现提交后校验

### ISSUE THREAD

**Issue by ClausClaus** [baidu/amis#3207]
#### 实现场景：
请问下表单的服务端校验这块，我看文档的中的这个[位置](https://baidu.gitee.io/amis/zh-CN/components/form/formitem#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%A0%A1%E9%AA%8C)说的是：

**点击提交，api 接口返回中，需要在 errors 变量中，返回某个表单项的报错信息，key值为该表单项的name值。**

后端接口需要返回一个errors字段，现实情况是项目只是前端重构，需要兼容旧的后端接口，后端并不做改动，接口返回中没有errors字段，前端想要使用表单项的`validationErrors`属性在提交前配置好提交后可能需要展示的错误信息的话，有什么办法能实现吗？
validationErrors对象的属性都是提交前的校验，排除类型错误将数据交给后端做计算之后，响应结果中没有errors字段，前端如何做到用低代码的方式展示错误呢？

目前能想到的是在表单项的下面新增一个标签作为占位符，但实现起来都不够优雅，会增加组件层级。

**Comment by lurunze1226** [comment]
使用接收适配器把后端返回的接口字段transform成标准格式 https://baidu.gitee.io/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8

**Comment by ClausClaus** [comment]
> 使用接收适配器把后端返回的接口字段transform成标准格式 https://baidu.gitee.io/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8

谢谢！解决了

**Comment by ClausClaus** [comment]
> [lurunze1226](/lurunze1226)

**Comment by ClausClaus** [comment]
> 使用接收适配器把后端返回的接口字段transform成标准格式 https://baidu.gitee.io/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8

谢谢！已经解决了 @lurunze1226
