### ISSUE TITLE
Form 与 Page 的 initApi 数据同步优化。

### ISSUE THREAD

**Issue by 2betop** [baidu/amis#321]
问题：  如果 form 的数据是从 Page 的 initApi 拉取的。form 中的表单项如果没有配置默认值，同时没有修改，form 的保存 api 不会携带此数据。

目前可以通过给表单项设置默认值空来避免这个问题。但是后续 amis 需要内部解决这个问题。

**Comment by 2betop** [comment]
内部已优化 form 数据与上层数据同步问题，只有配置了表单项就会同步。

**Comment by 1532332928** [comment]
那我需要在 form 配置 initApi 的时候，不希望保存的 api 携带此些数据，只需获取表单的怎么配置？
