### ISSUE TITLE
编译完成会报错

### ISSUE THREAD

**Issue by theojia** [baidu/amis#3210]
报了一个与react-visibility-sensor相关的错误

ERROR in ./node_modules/react-visibility-sensor/dist/visibility-sensor.js
Module not found: Error: Can't resolve 'ReactDOM' in 'xxxxxxx\node_modules\react-visibility-sensor\dist'
请确认一下~

**Comment by nwind** [comment]
这个很久没改了，估计是 webpack 配置问题之类的，整理完整能复现的例子吧

**Comment by minzhenyu** [comment]
https://github.com/joshwnj/react-visibility-sensor/issues/148
这里找到了出处,但只有改了dist里面的内容才不报错,webpack 配置问题,但是具体怎么解决其实还是存疑

**Comment by tangchaoren1** [comment]
> [joshwnj/react-visibility-sensor#148](https://github.com/joshwnj/react-visibility-sensor/issues/148) 这里找到了出处,但只有改了dist里面的内容才不报错,webpack 配置问题,但是具体怎么解决其实还是存疑

这个问题 有解决方案了吗

**Comment by theojia** [comment]
这个问题我研究了一下，最后通过别名解决了，大家遇到同样问题的可以参考一下
```
alias: {
    ReactDOM: path.join(_ROOTPATH, `node_modules/react-dom`),
},
```

**Comment by tangchaoren1** [comment]
> ReactDOM: path.join(_ROOTPATH, `node_modules/react-dom`),

in node_modules/React/index.js     does not match the corresponding path on disk `react
这个问题遇到了吗
