### ISSUE TITLE
增加pdf查看器

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#3214]
不少企业应用有生成pdf的需求，需要在系统中预览pdf。希望官方可以提供该组件。
查找了一些资料，可以提供集成到amis中。
https://github.com/react-pdf-viewer/react-pdf-viewer
https://github.com/wojtekmaj/react-pdf
感谢。

**Comment by dbkuaizi** [comment]
一般浏览器都自带pdf查看功能，可以使用 iframe 或者 link 的方式实现

**Comment by nwind** [comment]
pdf.js 性能太差，我们也推荐直接用 iframe，目前主流的浏览器都支持了

**Comment by cmdares** [comment]
@nwind 感谢回复。
