### ISSUE TITLE
CRUD组件结合truncate来展示超长表格字段，popOver展示错位！

### ISSUE THREAD

**Issue by jiafluo** [baidu/amis#3218]
CRUD组件结合truncate来展示超长表格字段，popOver展示错位！

**Comment by lurunze1226** [comment]
请贴一下出现问题的代码

**Comment by JaFengLuo** [comment]
结果图：
![image](https://user-images.githubusercontent.com/58316770/146484302-df82e7e2-6c54-4a9e-a5ef-5fdf81c497ff.png)
代码图：
![image](https://user-images.githubusercontent.com/58316770/146484372-f612b02a-8c51-4835-aea0-d4bb0cc130b0.png)
我这里使用的是CRUD组件

**Comment by lurunze1226** [comment]
> 结果图： ![image](https://user-images.githubusercontent.com/58316770/146484302-df82e7e2-6c54-4a9e-a5ef-5fdf81c497ff.png) 代码图： ![image](https://user-images.githubusercontent.com/58316770/146484372-f612b02a-8c51-4835-aea0-d4bb0cc130b0.png) 我这里使用的是CRUD组件

没有复现，使用的AMIS版本是什么？

**Comment by JaFengLuo** [comment]
版本：1.4.2-beta.6

**Comment by JaFengLuo** [comment]
> > 结果图：我这里使用的是CRUD组件
> 
> 没有复现，使用的AMIS版本是什么？

版本：1.4.2-beta.6

**Comment by wibetter** [comment]
@jiafluo 和这个应该是同一类问题，请升级amis到最新验证下是否还有此问题：
https://github.com/baidu/amis/pull/9843
