### ISSUE TITLE
头像增加click和hover效果

### ISSUE THREAD

**Issue by leaf188** [baidu/amis#3220]
#### 是否关联于某个问题吗：

1. 鼠标在头像上悬停自动弹出下拉菜单（可以是链接，也可以是按钮），类似DropDownButton组件的效果。
2. 点击头像可以定义行为

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by xiahao90** [comment]
想法很好
