### ISSUE TITLE
Checkboxes组件能否实现   点击每个checkbox的时候  获取seleted值并发送一个ajax请求？

### ISSUE THREAD

**Issue by JaFengLuo** [baidu/amis#3223]
![image](https://user-images.githubusercontent.com/58316770/146484651-6c201a30-6d1d-4f68-9293-350993e16627.png)
Checkboxes组件能否实现   点击每个checkbox的时候  获取seleted值并发送一个ajax请求？框架使用小白，希望大佬们指点一下哈

**Comment by RickCole21** [comment]
[接口联动](https://baidu.gitee.io/amis/zh-CN/docs/concepts/linkage#%E6%8E%A5%E5%8F%A3%E8%81%94%E5%8A%A8) 应该可以。
