### ISSUE TITLE
amis1.5.3 云舍样式下的InputNumber组件，up和down按钮的图标丢失了

### ISSUE THREAD

**Issue by lglbeo** [baidu/amis#3225]
#### 描述问题：

将amis打包放到项目后，发现云舍样式下的InputNumber组件，up和down按钮的图标丢失了。
没打包前，在amis项目是正常的。
文字苍白，上图片

#### 截图或视频：
![Snipaste_2021-12-18_20-59-49](https://user-images.githubusercontent.com/67648334/146644570-18f19d84-5b18-4aad-9e5e-35e73fb29791.png)
![Snipaste_2021-12-18_21-09-47](https://user-images.githubusercontent.com/67648334/146644574-04ef02bc-9b9c-43d7-b8ba-3ee894c773a1.png)
![Snipaste_2021-12-18_21-10-33](https://user-images.githubusercontent.com/67648334/146644582-da680379-f111-47a0-b40a-0268bf957475.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
 用的build.sh 打包的方式，引入到自己的项目中

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis版本1.53

3. 粘贴有问题的完整 `amis schema` 代码：
  --Number-handler--up-content: '\e6dd';
 --Number-handler--down-content: '\e6dd';
![Snipaste_2021-12-18_20-59-49](https://user-images.githubusercontent.com/67648334/146644570-18f19d84-5b18-4aad-9e5e-35e73fb29791.png)

执行构建./build.sh脚本后，生成的代码如下
  --Number-handler--up-content: "";
  --Number-handler--down-content: "";

**Comment by minzhenyu** [comment]
这个问题怎么解决的，我现在准备使用的项目直接引入 https://github.com/baidu/amis/blob/9da4b43f338180cff8a6287dac5d6147521c076a/examples/static/iconfont.css#L1224

这个字体了
