### ISSUE TITLE
如何将生成的json代码在已有的项目中渲染出来？

### ISSUE THREAD

**Issue by lck123357** [baidu/amis#3229]
文档看得不是很理解，希望能教一下解释一下，感谢🙏

**Comment by nwind** [comment]
如果是 react 项目参考 https://github.com/aisuda/amis-react-starter

**Comment by lck123357** [comment]
@nwind 如果自定义组件的渲染器想引入项目中应该怎么使用呢？
我的理解是：我封装好自定义组件的渲染器后 -> 把它放在入npm包中（**这一步不理解应该怎么实现**） -> 然后实际的项目拉取最新的npm通过他的render方法渲染自定义组件
🙏，麻烦指教一下

**Comment by lck123357** [comment]
> 

@nwind 你好，可以指教一下吗？
