### ISSUE TITLE
建议树形table可以像nav一样支持懒加载

### ISSUE THREAD

**Issue by 688862** [baidu/amis#3238]
现在树形table是:返回有item.children字段,就自动会展示树形,希望像nav导航一样,可以配置一个deferApi接口,然后item.defer字段返回是否为懒加载项.
这个功能其实比nav的懒加载要实用,因为树形table往往有大量数据,后端一次性返回不太现实.
由于本人能力有限,研究了2天也没实现,所以只好来提Issue了

**Comment by bluehr** [comment]
+1

**Comment by easysg** [comment]
@688862 目前有方案了

**Comment by jojo-Tony** [comment]
> @688862 目前有方案了

请问什么方案呀，可以说一下吗，谢了

**Comment by hsm-lv** [comment]
https://baidu.github.io/amis/zh-CN/components/crud#%E5%B5%8C%E5%A5%97%E6%87%92%E5%8A%A0%E8%BD%BD
