### ISSUE TITLE
解析/渲染性能方面是否有做对应的策略？

### ISSUE THREAD

**Issue by wupengFEX** [baidu/amis#324]
当页面 schema 量级非常大，抑或是通过迭代器类似组件渲染（一份 schema 模版，多份数据渲染出来 n 个模版），amis 目前有没有对应的性能优化策略（ps：从引擎代码侧没有看到），比如针对首屏加载时间，资源加载策略等 @2betop

**Comment by 2betop** [comment]
这块还没有考虑，主要是可能也没必要考虑，因为基本上都是作为内部管理系统。
