### ISSUE TITLE
amis-editor-demo预览模式下header的配置无效.

### ISSUE THREAD

**Issue by cnluderson** [baidu/amis#3240]
amis-editor-demo预览模式下header的配置无效.
（amis-editor-demo项目issue建议来这发issue）

可以在线上复现：

在amis-editor-demo官方演示中：https://aisuda.github.io/amis-editor-demo/#/edit/0   
随意在一个api加入header适配，例如：  
``` json
"headers": {
      "token2": "123"
 },
"requestAdaptor": "return {\r\n  ...api,\r\n  headers: {\r\n    ...api.headers,\r\n    token:'000' \r\n  },\r\n  data: { ...api.data }\r\n}"
``` 
``` javascript
// 以上requestAdaptor等同：
return {
    ...api,
    headers: {
        ...api.headers
        token2: '000'
   },
    data: {
        ...api.data
    }
}
```
你会发现在amis-editor-demo预览模式下，以上两个位置配置的headers**都不生效**。

![amis-editor-demo中没有生效](https://user-images.githubusercontent.com/6993345/146886338-3581e129-97e7-4a7d-b1f9-ee620bac9e6c.jpg)

amis文档站点，以及自行引入的jssdk的方式都生效生效
见https://baidu.gitee.io/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E6%95%B0%E6%8D%AE

![amis文档和通过jssdk引入的方式生效](https://user-images.githubusercontent.com/6993345/146886310-5c007f89-3142-46f5-b497-a04d115c3261.jpg)

**Comment by cmdares** [comment]
关注！！！

**Comment by RickCole21** [comment]
editor 相关 issue 请转到 https://github.com/aisuda/amis-editor-demo

**Comment by wangyalong** [comment]
解决了吗
