### ISSUE TITLE
Tabs 选项卡的动态生成不工作

### ISSUE THREAD

**Issue by kuviki** [baidu/amis#3250]
#### 描述问题：

Tabs 选项卡的动态生成不工作，官网文档中的示例就不工作

#### 截图或视频：

![image](https://user-images.githubusercontent.com/13548063/147068864-144c05cc-04c3-4819-a4b5-62c8e17dc1eb.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.5.6

3. 粘贴有问题的完整 `amis schema` 代码：
```json
{
  "type": "page",
  "data": {
    "arr": [
      {
        "a": "收入",
        "b": 199
      },
      {
        "a": "支出",
        "b": 299
      }
    ]
  },
  "body": [
    {
      "type": "tabs",
      "source": "${arr}",
      "tabs": [
        {
          "title": "${a}",
          "body": {
            "type": "tpl",
            "tpl": "金额：${b|number}元"
          }
        }
      ]
    }
  ]
}
```

4. 操作步骤
不需要操作

**Comment by Chen-Wendong** [comment]
这个问题我也提过

https://github.com/baidu/amis/issues/3199

**Comment by Cherry-Ran** [comment]
这个框架还是不太完善

**Comment by kuviki** [comment]
``1.6.0``下没有该问题了
