### ISSUE TITLE
富文本编辑器 richText 的插件使用

### ISSUE THREAD

**Issue by biley** [baidu/amis#3253]
#### 实现场景：
richText 支持 codesample 等插件的使用

#### 存在的问题：
要插入一些 js，go 或其他代码是，无法使用 codesample 做到代码的高亮和格式化

当前看来 amis 的 richText 是安装了 25 个插件，那有什么办法可以支持其他插件的使用吗？或者或许会有这方面的更新吗？
#### 当前方案：

```
```

**Comment by nwind** [comment]
这个插件倒是简单，就是要高亮的话还得加另一个，得看看体积

**Comment by linjinglan** [comment]
楼主，富文本编辑的txt，在amis上有什么组件可以展示，在数据库获取到内容，用文字展示的话，绑定字段后不会识别html标签

**Comment by biley** [comment]
> 楼主，富文本编辑的txt，在amis上有什么组件可以展示，在数据库获取到内容，用文字展示的话，绑定字段后不会识别html标签

可以用 过滤器，当 html 显示出来
