### ISSUE TITLE
CRUD 弹出框popOver,无法选中,鼠标点击时候会消失(1.2.1能够正常选中)

### ISSUE THREAD

**Issue by 1178615156** [baidu/amis#3255]
#### 是否关联于某个问题吗：
CRUD 弹出框（popOver）无法选中,当鼠标点击弹出的内容时候,弹框会消失.

#### 预期的解决方案：
允许鼠标点击和选中弹框的内容.

#### 任何附加信息：
1.5.3
![popOver-1 5 3](https://user-images.githubusercontent.com/8329255/147182111-b312ca3c-93d8-4f93-b2cb-8ef3a9b363b6.gif)

1.2.1 是符合期望的
![popOver-1 2 1](https://user-images.githubusercontent.com/8329255/147182365-25421d02-d1e7-4904-95c6-347c32900fcf.gif)

**Comment by guchenhui** [comment]
我也有相同的烦恼，有人能解决吗
