### ISSUE TITLE
弹框组件字符处理BUG

### ISSUE THREAD

**Issue by Chen-Wendong** [baidu/amis#3257]
#### 描述问题：

弹框组件字符处理BUG

#### 截图或视频：

![image](https://user-images.githubusercontent.com/88780174/147215690-a7f126f4-de10-4024-91f3-a181d6e59886.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.5.3

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "label": "弹个框",
    "type": "button",
    "actionType": "dialog",
    "dialog": {
      "title": "弹框",
      "body": "MENyXLSI0Uybcmd/1i4cSrSgcun4fJcS4DpcAiAwdmOP2cP3ISwj+0HW4Do5Ze147ew=="
    }
  }
}
```

**Comment by Chen-Wendong** [comment]
换成中文可以正常换行！

**Comment by Chen-Wendong** [comment]
![image](https://user-images.githubusercontent.com/88780174/147216069-72d19a55-32b4-4764-9fc2-f3727db92df2.png)

**Comment by nwind** [comment]
css 问题，先加 bodyClassName 解决 https://baidu.gitee.io/amis/zh-CN/docs/start/faq#%E5%A6%82%E4%BD%95%E6%8A%98%E8%A1%8C
