### ISSUE TITLE
【重要bug】最新版本input-text 选择器模式 选择后显示不正确  经过测试1.2.3版本正常 

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#3258]
#### 描述问题：
input-text 选择器模式 选择内容后 input-text中显示的是value的值 应该显示 label的值

#### 截图或视频：
![image](https://user-images.githubusercontent.com/44140500/147250841-1442665f-4d53-4a11-821f-e3e078b261d7.png)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：
[https://baidu.gitee.io/amis/zh-CN/components/form/input-text#%E9%80%89%E6%8B%A9%E5%99%A8%E6%A8%A1%E5%BC%8F](https://baidu.gitee.io/amis/zh-CN/components/form/input-text#%E9%80%89%E6%8B%A9%E5%99%A8%E6%A8%A1%E5%BC%8F)

**Comment by lurunze1226** [comment]
这里显示value才是正确的，这个组件是输入框，应该展示用户输入的值，选择器组件才应该展示选项的label字段

**Comment by lhtuling** [comment]
> 这里显示value才是正确的，这个组件是输入框，应该展示用户输入的值，选择器组件才应该展示选项的label字段

并不是啊！！！  都是显示label  value是用于后端的啊
