### ISSUE TITLE
怎么配置多层级的数据流

### ISSUE THREAD

**Issue by hellosean1025** [baidu/amis#326]
![image](https://user-images.githubusercontent.com/17695103/68098106-d5dd3f00-fef5-11e9-9af8-20ab0409b181.png)
如图所示，filter1 会传给下面两个模块，filter2 跟 filter3 只会传给自己的模块，请教怎么配置呢

> 这里假设是有两个层级，在实际的需求中，可能存在 N 个

**Comment by 2betop** [comment]
最外层一个 form + service,  service 底下放两个 crud， 记得 crud 把同步地址栏给关了。

**Comment by hellosean1025** [comment]
@2betop form 表单有个问题，必须有提交按钮
现在能支持去掉提交按钮，只要 input, 或者 select 触发了 change 就会自动提交这个功能吗？

**Comment by hellosean1025** [comment]
另外还有个问题，目前在文档没有找到解决方案，我们这边所有查数据，修改数据请求都是 post 请求，所有的请求参数会统一包裹到  params 里面，amis 支持自定义请求方法吗

**Comment by 2betop** [comment]
> @2betop form 表单有个问题，必须有提交按钮
现在能支持去掉提交按钮，只要 input, 或者 select 触发了 change 就会自动提交这个功能吗？

form 配置 submitText 为 空就没有按钮了，然后配置 submitOnChange。

> 另外还有个问题，目前在文档没有找到解决方案，我们这边所有查数据，修改数据请求都是 post 请求，所有的请求参数会统一包裹到 params 里面，amis 支持自定义请求方法吗

api 可以配置成  post ，每个 api 都可以配置 method 类型。 请看这里： https://baidu.github.io/amis/docs/renderers/Types#api   默认的 post 内容体是 json， 可以尝试修改成 form 或者 form-data, 然后结合配置 qsOptions 可以适配大部分的后端了。另外如果 amis 默认的 post 方式不是你想要的数据格式，你可以尝试自己实现fetcher 方法。
