### ISSUE TITLE
官方qq群加了没反应  找资料问问题太麻烦了  建了个Amis交流群 QQ群号：717791727

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#3275]
**官方qq群加了没反应  找资料什么太麻烦  自己新建了个交流群 感兴趣的加下吧！！！
点击链接加入群聊【Amis低代码前端框架交】：https://jq.qq.com/?_wv=1027&k=rqgy0asZ
QQ群号：717791727**

**Comment by nwind** [comment]
申请 2 群吧
