### ISSUE TITLE
为log实时日志组件增加自定义header功能

### ISSUE THREAD

**Issue by imlida** [baidu/amis#3283]
我们的后台系统使用jwt方式认证，使用log实时日志组件时发现无法携带header。能否为该组件的source增加自定义header的功能，谢谢！

**Comment by RickCole21** [comment]
source 应该支持配置 api 形式，所以可以 [自定义header](https://baidu.gitee.io/amis/zh-CN/docs/types/api?page=1#%E9%85%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%B7%E6%B1%82%E5%A4%B4)
