### ISSUE TITLE
富文本编辑器上传问题

### ISSUE THREAD

**Issue by vibirds001** [baidu/amis#3287]
#### 描述问题：

InputFile文件上传组件可以自定义fileField，但是富文本编辑器的却是写死的，只能是file，这里能不能也多加个配置参数，不然都不统一，要么就只能用默认的

#### 截图或视频：

          const formData = new FormData();
          formData.append('file', blobInfo.blob(), blobInfo.filename());

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新版

**Comment by RickCole21** [comment]
froala 可以用下面配置，具体可以看 [froala文档](https://froala.com/wysiwyg-editor/docs/options#imageUploadParam)
```
{
  label: 'rich',
  type: 'input-rich-text',
  name: 'rich',
  vendor: 'froala',
  options: {
    imageUploadParam: 'myfile'
  }
},
```

**Comment by vibirds001** [comment]
默认的tinymce可以配置吗？froala 收费的
