### ISSUE TITLE
values of the textfields in a combo as options of a select box

### ISSUE THREAD

**Issue by phxgbl** [baidu/amis#3303]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

I am tryng to implement Database table creator.  Please find the image attached. Here i have a textbox for table name, then a combo for column details with items: textbox for column name and select for column type . column combo items can be added or deleted.

Below the column combo i have a primary key select , which should have the column names entered in above column combo as options. Since column combo items are not saved, i cannot retrieve the items from any API.
![table](https://user-images.githubusercontent.com/37118923/147715009-296fd860-af8d-4812-8072-15a024f96b53.png)

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

so for above scenario, i do not know how to populate the primary key select from above combo. Please let me know if this functionality can be done using Amis. Any idea will be appreciated

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by RickCole21** [comment]
use [this](https://baidu.gitee.io/amis/zh-CN/components/form/options#%E9%80%9A%E8%BF%87%E6%95%B0%E6%8D%AE%E5%9F%9F%E4%B8%AD%E5%8F%98%E9%87%8F%E9%85%8D%E7%BD%AE) feature
```
{
  type: 'form',
  body: [
    {
      type: 'combo',
      name: 'columns',
      label: 'Columns',
      multiple: true,
      items: [
        {
          name: 'name',
          label: 'Name',
          type: 'input-text'
        },
        {
          name: 'type',
          label: 'Type',
          type: 'select',
          options: ['varchar', 'int']
        }
      ]
    },
    {
      label: 'pk',
      type: 'select',
      name: 'pk',
      valueField: 'name',
      labelField: 'name',
      source: '${columns}'
    }
  ]
}
```

**Comment by phxgbl** [comment]
@RickCole21 Thank you for your time. This is what I was looking for.
