### ISSUE TITLE
表单重复提交问题，有防抖属性可配置吗？

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#3305]
#### 是否关联于某个问题吗：
表单重复提交问题

#### 预期的解决方案：
按钮或API有没有配置防抖的属性？

**Comment by nwind** [comment]
不需要防抖，提交的时候会禁用按钮，直到 api 返回的时候才能再次点击

**Comment by pq-dong** [comment]
> 不需要防抖，提交的时候会禁用按钮，直到 api 返回的时候才能再次点击

大佬请问这个是从哪一个版本开始出现的机制呢？我们从1.9.0版本上发现在极短时间内多次点击同一个按钮，会发送多次请求，请求都被发送成功了
