### ISSUE TITLE
CRUD的动态列的colums的button包含confirmText时,按钮不生效.

### ISSUE THREAD

**Issue by 1178615156** [baidu/amis#3306]
#### 描述问题：

在为CRUD添加一个删除按钮的时候发现:
CRUD的动态列的colums的button包含confirmText时,按钮不生效,不会发起对应请求操作.

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.5.3

3. 粘贴有问题的完整 `amis schema` 代码：

crud:
```json
 {
    "type": "crud",
    "api": "..."
  }
```
api返回的数据:
```json
{
  "columns": [
    {
      "label": "id",
      "name": "id"
    }
    {
      "buttons": [
        {
          "actionType": "ajax",
          "api": "DELETE:/delete?id=$id",
          "confirmText": "确认要删除？",
          "label": "删除",
          "level": "danger",
          "type": "button"
        }
      ],
      "label": "操作",
      "type": "operation"
    }
  ],
  "items": [
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    }
  ]
}
```

4. 操作步骤
删掉`buttons`里的`confirmText`就能正常发起请求了

**Comment by RickCole21** [comment]
没复现，你配置了confirmText，点击按钮的时候没有弹框提示么？

如果是这样的话，看一下console有啥报错，可能你的env配置有问题。参考[这里](https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started)

**Comment by 1178615156** [comment]
> 没复现，你配置了confirmText，点击按钮的时候没有弹框提示么？
> 
> 如果是这样的话，看一下console有啥报错，可能你的env配置有问题。参考[这里](https://baidu.gitee.io/amis/zh-CN/docs/start/getting-started)


-_-我也复现不出来了,可能是哪里配置错了.

**Comment by liuzyong** [comment]
![image](https://user-images.githubusercontent.com/33834517/188776376-3bbadd71-cf67-4279-8884-ef5afc9274a8.png)

**Comment by liuzyong** [comment]
我也遇到了同样的问题，从控制台看到了如下信息：
![image](https://user-images.githubusercontent.com/33834517/188776487-62e357d8-04b0-468b-a67f-9e27a48b591e.png)
