### ISSUE TITLE
前端一次性加载后 前端检索功能失效，还是会请求后端

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#3307]
#### 描述问题：

前端一次性加载后，前端检索不能真的前端检索，还是会请求后端。

#### 截图或视频：

官网的案例都有这个bug https://baidu.gitee.io/amis/zh-CN/components/crud?page=1#%E5%89%8D%E7%AB%AF%E4%B8%80%E6%AC%A1%E6%80%A7%E5%8A%A0%E8%BD%BD

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.5.3，beta版不知道哪里可以下载呢？
3. 粘贴有问题的完整 `amis schema` 代码：
```
```

4. 操作步骤

**Comment by RickCole21** [comment]
CRUD 配置 `loadDataOnceFetchOnFilter:false`
