### ISSUE TITLE
Tabs组件需要实现点击标签刷新其他组件的功能

### ISSUE THREAD

**Issue by vipjson** [baidu/amis#3320]
#### 是否关联于某个问题吗：
吴老大，Tabs组件需要实现一个点击标签后触发刷新其他组件效果，比如同级CURD组件可以根据Tabs点击刷新数据。相当于把Tabs仅做标签使用，并且不配置内容时不显示TabsContent。

#### 预期的解决方案：
点击Tabs标签刷新其他组件并传递数据。

还要新版的Editor编辑器没有了表单项组功能了，包括爱速搭也没有了，请核实下。

**Comment by vipjson** [comment]
我的场景一般是把Tabs标签当做状态选项，比如订单有未付款、待发货、待确认等，同级CURD根据Tabs状态刷新数据。

**Comment by Cherry-Ran** [comment]
大佬tabs点击事件监听怎么用对象来接？

**Comment by nwind** [comment]
有个新的事件机制预计能实现，得确认一下

**Comment by hsm-lv** [comment]
已支持了 https://baidu.github.io/amis/zh-CN/docs/concepts/event-action
