### ISSUE TITLE
input-table中formula 无效

### ISSUE THREAD

**Issue by dikar** [baidu/amis#3321]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

这个bug貌似很早之前就有人提过 。如果input-table不能使用formula，是否有其他方式来联动计算 多个列

我试过tpl 也不行 

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

SDK
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.5.3

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
好像是的，得看看是什么原因

**Comment by webboyvc** [comment]
我暂时是，把quickEdit设置为false，就可以了，如下:
        {
            "formula": "${a+b}",
            "label": "公式",
            "name": "c",
            "quickEdit":false,
            "type": "formula"
        },

**Comment by dikar** [comment]
你看formula的标准例子，套在inputtable里的
