### ISSUE TITLE
Error: 找不到对应的渲染器  Path: app/page/page/body/form/modal/drawer/body/body/form/1/lucky-sheet

### ISSUE THREAD

**Issue by Barnett-Guo** [baidu/amis#3327]
#### 描述问题：

自己简单测试制作了一个组件

#### 截图或视频：

![image](https://user-images.githubusercontent.com/38901066/147816054-03c377ba-d051-4113-9f84-aec7c1d3fa18.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.4

3. 粘贴有问题的完整 `amis schema` 代码：
======================================================== 组件
import * as React from 'react';
import {Renderer, ScopedContext} from 'amis';
@Renderer({
  type: 'lucky-sheet'
})
class LuckySheet extends React.Component {
  render() {
const luckysheet = window.luckysheet;
      luckysheet.create({
        container: "luckysheet",
        plugins:['chart']
      });
    const luckyCss = {
      position: 'absolute',
      width: '100%',
      height: '100%',
      left: '0px',
      top: '0px'
    }
    return (
        <div
            id="luckysheet"
            style={luckyCss}
        ></div>
    )
  }
}

export default LuckySheet
======================================================== 使用
{
        type: "lucky-sheet",
 },
code here...
```

4. 操作步骤
我是在一个弹出框要展示这个组件 目前只是测试 弹出后提示。
Error: 找不到对应的渲染器

Path: app/page/page/body/form/modal/drawer/body/body/form/1/lucky-sheet

{
  "type": "lucky-sheet"
}
 我测试发现将组件写在配置处 类似下面 然后再用上面的在对应页面中调用就不会报错。但是渲染在了整个页面上。不是我想要的结果
<ToastComponent theme={theme} key="toast" position={'top-center'} />
 <LuckySheet/>

**Comment by nwind** [comment]
import 这个文件了么？

**Comment by Barnett-Guo** [comment]
> 

当时 import 了 也不行 后面我是用js包了一层调用js方法实现了

**Comment by yuhonyon** [comment]
![image](https://user-images.githubusercontent.com/9654460/165949640-ac09eb62-70c8-4b7b-9a2c-8413569f27a5.png)
总是报类似的问题， curd组件 配置的好好的可以正常运行， 后面再打开就突然这样， 新增弹窗之前的配置全部丢失， 填充所有表格字段，下面有这个报错

**Comment by wxlandzyb** [comment]
> import 这个文件了么？

我用最新版amis3.0的，按照官方文档自定义react插件也是一样的问题，请问是啥问题
