### ISSUE TITLE
table表格设置affixHeader: false, 页面滚动，显示错误

### ISSUE THREAD

**Issue by jokerys** [baidu/amis#333]
<img width="1340" alt="5262c45f1b683ab0e94fc86f8" src="https://user-images.githubusercontent.com/39823370/68386704-9170ce00-0197-11ea-9f03-54173d3a0e21.png">

**Comment by 2betop** [comment]
affixHeader: false 应该是关闭了，你说的是 affixHeader: true 位置显式有问题？

**Comment by jokerys** [comment]
不好意思，affixHeader: 设置的为 true，显示错误。

**Comment by 2betop** [comment]
你的的页面有没有其他固顶的元素？比如共用头部？如果没有把这个设置一下 env.affixOffsetTop，默认是 50。

![image](https://user-images.githubusercontent.com/2698393/68556419-2829dd00-046d-11ea-99b9-0826a00f50c3.png)

可以看一下这块的参数说明。https://baidu.github.io/amis/docs/getting-started#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-
