### ISSUE TITLE
url无法用post跳转页面

### ISSUE THREAD

**Issue by CzGleo** [baidu/amis#3330]
#### 是否关联于某个问题吗：
我没办法实现用post方法并携带参数跳转到新的页面，并且这个页面是在新的标签页打开的
{                        
                            "type": "button",
                            "label": "xxx",
                            "actionType": "url",
                            "url": "http://xxx",
                            "blank":true,
                            "level": "info"
}
上面这个代码只能是get方法
![image](https://user-images.githubusercontent.com/70244756/147927765-1ef109eb-d6c5-42a8-8c21-c5d22da1c41f.png)
#### 预期的解决方案：
ajax也支持新开页面的页面跳转

#### 其他可接受方案：
url可实现用post的方法发请求

**Comment by RickCole21** [comment]
跳转的时候可以把参数拼在链接后面，例如`"url": "www.baidu.com?query=${query}"`，然后另外一个页面里通过数据域取值
