### ISSUE TITLE
card模式的图片无法居中？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#3332]
#### 实现场景：
实现电影点播，展示海报列表，如图（这个图是网上截来的，实际用amis实现有问题），上面是图片**居中**显示，下面是标题简介
![捕获](https://user-images.githubusercontent.com/273961/148030039-fe3d31c8-6b03-405e-9644-f31d7ae66597.PNG)

#### 存在的问题：
用curd的cards模式展示出来的图片无法实现居中，右侧总是会多出来一块fieldValue的样式，即使删掉card的header部分也没用。

![222](https://user-images.githubusercontent.com/273961/148030857-d9c20725-4ef2-4282-9888-a71ed60f3fa4.PNG)

#### 当前方案：
用curd的cards模式

```
{
  "title": "列表",
  "body": {
    "type": "crud",
    "api": "/api/list",
    "mode": "cards",
    "card":{
       "actions":[ ... ],
       "body": [
        {
          "type": "image",
          "name": "thumbnail"
        },
        {
          "name": "title"
        }
      ]
    }
}
```

**Comment by Aipuhs** [comment]
[设置多媒体卡片](https://baidu.gitee.io/amis/zh-CN/components/card#%E8%AE%BE%E7%BD%AE%E5%A4%9A%E5%AA%92%E4%BD%93%E5%8D%A1%E7%89%87)

**Comment by foxfire881** [comment]
测试无效，多媒体卡片的url属性无法绑定json数据，渲染不出来。

测试如下：
服务端返回crud的json格式 
{"msg":"","data":{"total":100,"items":[{"id":1,"title":"哈利波特","url":"http://xxx.com/xx.jpg"}]}

客户端：
```
{
    "type":"crud",
    ....
    ....
    "card": {
        "header": {
          "title": "$title"   //可以正常引用渲染
        },
        "media": {
          "type": "image",
          "className": "w-36 h-24",
          "url": "$url",     //无法引用，$url被当作字符串解析，无法渲染
          "position": "top"
        },
        "body": "$title",    //可以正常引用渲染
        "secondary": "次要说明",
      }
}

```

用的是amis最新版

> [设置多媒体卡片](https://baidu.gitee.io/amis/zh-CN/components/card#%E8%AE%BE%E7%BD%AE%E5%A4%9A%E5%AA%92%E4%BD%93%E5%8D%A1%E7%89%87)

**Comment by foxfire881** [comment]
测试无效，多媒体卡片的url属性无法绑定json数据，渲染不出来。

测试如下：
服务端返回crud的json格式 
{"msg":"","data":{"total":100,"items":[{"id":1,"title":"哈利波特","url":"http://xxx.com/xx.jpg"}]}

客户端：
```
{
    "type":"crud",
    ....
    ....
    "card": {
        "header": {
          "title": "$title"   //可以正常引用渲染
        },
        "media": {
          "type": "image",
          "className": "w-36 h-24",
          "url": "$url",     //无法引用，$url被当作字符串解析，无法渲染
          "position": "top"
        },
        "body": "$title",    //可以正常引用渲染
        "secondary": "次要说明",
      }
}

```

用的是amis最新版

> [设置多媒体卡片](https://baidu.gitee.io/amis/zh-CN/components/card#%E8%AE%BE%E7%BD%AE%E5%A4%9A%E5%AA%92%E4%BD%93%E5%8D%A1%E7%89%87)

**Comment by foxfire881** [comment]
更新到1.6解决
