### ISSUE TITLE
condition-builder的字段类型没有传到后台？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#3336]
#### 描述问题：

condition-builder在前端渲染时可以指定type是number、text、time等，可是传给后端的type参数值却是"field"，那么在后端接受参数的时候怎么判断它是什么类型呢？

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
SDK

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
npm下载的最新版

3. 粘贴有问题的完整 `amis schema` 代码：
https://baidu.gitee.io/amis/zh-CN/components/form/condition-builder
文档中给的样例全部都是这样，明明json中指定了type是time、number、text等，但是debug显示实际传给后端的type值都是"field"，实测后端接收到的type值也都是“field”

**Comment by nwind** [comment]
目前是用 field，这个 type 后续预览给高级字段用
