### ISSUE TITLE
Tabs点击监听

### ISSUE THREAD

**Issue by Cherry-Ran** [baidu/amis#3337]
![image](https://user-images.githubusercontent.com/32769218/148179239-cba51bb3-a24c-4c85-9265-cac6799fd874.png)

**Comment by Cherry-Ran** [comment]
Tabs监听，我点击标签信息，上面的面包屑显示为，工程师画像/工程师标签管理/标签信息，
我点击标签数据，上面的面包屑显示，工程师画像/工程师标签管理/标签数据
请问amis是怎么实现的？ tabs的监听就一个onSelect ？里面能用对象去接吗？

**Comment by Cherry-Ran** [comment]
这里面能像Vue一样用v-model去动态的控制这些吗？

**Comment by nwind** [comment]
onSelect 后自己去改 dom 节点吧

**Comment by Cherry-Ran** [comment]
> onSelect 后自己去改 dom 节点吧

你那里面写不了JS代码，怎么改？

**Comment by Cherry-Ran** [comment]
> onSelect 后自己去改 dom 节点吧

我们现在没用React来写，用的静态HTML+SDK的方式

**Comment by nwind** [comment]
这个是老问题，现在已经有事件动作机制了
