### ISSUE TITLE
设置valueField后，Select渲染异常

### ISSUE THREAD

**Issue by joey-lucky** [baidu/amis#3341]
#### 描述问题：

如果设置了valueField,且options中的value字段为null，会导致渲染异常

#### 截图或视频：

![](https://joey-markdown.oss-cn-beijing.aliyuncs.com/2021/20220105184736.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

将schema复制到编辑器
https://aisuda.github.io/amis-editor-demo

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

v1.5.1

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
    {
      "type": "select",
      "label": "子项",
      "name": "children",
      "labelField": "name",
      "valueField": "id",
      "options": [
        {
          "name": "测试1",
          "id": "测试1",
          "value": null
        },
        {
          "name": "测试2",
          "id": "测试2",
          "value": null
        }
      ]
    }
  ]
}.
```

4. 操作步骤
略

**Comment by nwind** [comment]
先把那两个 value: null 去掉吧

**Comment by joey-lucky** [comment]
> 先把那两个 value: null 去掉吧

我尝试按提PR，提示没有权限？
