### ISSUE TITLE
新版editor搜索在vite模式下无法搜索

### ISSUE THREAD

**Issue by agileago** [baidu/amis#3342]
#### 描述问题：

amis-editor搜索组件无法搜索，但是在webpack下面就可以，在vite下就不行

#### 截图或视频：

![2022-01-05 23 22 53](https://user-images.githubusercontent.com/11799110/148243141-393142e0-f809-4f1f-b78a-3d4629a1b489.gif)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
 `vite`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新版 1.6

3. 粘贴有问题的完整 `amis schema` 代码：
无

4. 操作步骤
复现仓库  https://github.com/agileago/vite-amis

**Comment by nwind** [comment]
大概的自己研究了，看起来 vite 你比我们更了解呢

**Comment by agileago** [comment]
也有可能是editor的bug呢，目前看来是 输入框的 `onblur` 事件先于 浮层的 `onclick` 执行， 导致浮层直接关闭，未触发 `onclick` 事件，这个没源码还真的不知道怎么查，只从 devtool上看到 onblur使用的 capture 模式,把blur事件删掉就可以，所以这个还真不知道从哪里下手

![image](https://user-images.githubusercontent.com/11799110/148350325-8f215357-17b4-4cac-b1d8-39eb2e52991f.png)

**Comment by agileago** [comment]
我自己有空再研究一下

**Comment by agileago** [comment]
@nwind 是不是马上就要支持vite了？我看commit里面都写了，大概啥时间

**Comment by agileago** [comment]
@nwind 我的锅，之前看到amis-editor-demo中依赖了bootstrap,以为需要他的样式，就引入了， 发现他的 `hidden` 样式覆盖了你们的 `hidden`, 导致无法点击到
