### ISSUE TITLE
amis-editor-demo 一个页面多行文本填写记录，影响另外一个多行文本

### ISSUE THREAD

**Issue by b1gcat** [baidu/amis#3344]
#### 描述问题：

我用最新amis-editor-demo生成gh-pages，做了两个页面。在一个页面的多行文本输入信息，另外一个页面的多行文本也自动填充信息，也或者在一个页面写入信息，同一个页面的另一个多行文本也自动填充信息。 

期间没有后台交互，就是普通输入。

#### 截图或视频：

![Untitled](https://user-images.githubusercontent.com/15025254/148320791-978887a0-a5ee-4f32-b271-f1654429667a.gif)

#### 如何复现（请务必完整填写下面内容）：
需要我提供什么信息 给我留言，我是前端小白。

4. 操作步骤

**Comment by Aipuhs** [comment]
字段名重复了

**Comment by b1gcat** [comment]
> 字段名重复了（我确认两遍都改掉了 不过也可能我哪里疏忽了）

请问 字段名字 是指 这里的name吗
![image](https://user-images.githubusercontent.com/15025254/148544115-eebfb733-4dab-41c3-aaa6-d6b2ea91fa38.png)

**Comment by nwind** [comment]
是 name 改成不一样就行

**Comment by b1gcat** [comment]
> 是 name 改成不一样就行

我发誓我已经改成不一样了 😂

**Comment by b1gcat** [comment]
[gh-pages.zip](https://github.com/baidu/amis/files/7853280/gh-pages.zip)
附件是有问题的：
操作：
1、修改sm4的密文
2、点sm2页面，明文区出现sm4页面的信息
