### ISSUE TITLE
如何给组件添加背景图

### ISSUE THREAD

**Issue by zcgelppa** [baidu/amis#3346]
#### 描述问题：

wrapper组件支持自定义style，但是不支持background-image

#### 截图或视频：

想实现组件背景图：
![image](https://user-images.githubusercontent.com/300425/148325464-62c14b6f-41ec-4b00-9af8-1acde48e2a07.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.5.3

3. 粘贴有问题的完整 `amis schema` 代码：
```
              "type": "wrapper",
              "style": {
                "background": "#00ff00 url('/assets/diff/par/title_bk.png')",
                "background-image": "url('/assets/diff/par/title_bk.png')",
              },
```

两种方式都没有效果

**Comment by nwind** [comment]
第一个应该可以吧，第二个要用 backgroundImage，不过这个效果其实建议自定义组件

**Comment by zcgelppa** [comment]
是可以，是我写错了，谢谢
