### ISSUE TITLE
栅格布局自是适应是否调整为24

### ISSUE THREAD

**Issue by SheenaghF** [baidu/amis#3347]
#### 是否关联于某个问题吗：
因为12我没办法实现一行五个

### 预期的解决方案：
我希望能调整布局或者说支持小数

**Comment by 2betop** [comment]
24 也解决不了一行 5 个，另外格子成员不配置占比是平均分配。

**Comment by SheenaghF** [comment]
那能否设置小数，如果为2.4 那12可以一行五个，平均分配那就不能配响应式的，我现在大概十八个 lg 2 ， md 4 ， sm 3 ，但是6实在是太窄了
