### ISSUE TITLE
和ueditor等其他富文本编辑器集成？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#335]
amis自带的富文本编辑器太简陋了不够用，而且还有License限制，能否和其他富文本编辑器集成，比如百度自己的UEditor？那个引用编辑器的script脚本应该怎么配置呢？

**Comment by foxfire881** [comment]
另外刚才开的那个file accept的问题怎么给我关闭了？我用的就是最新的1.0.4版，无论*还是留空都仍然提示文件类型不符，上传不了啊~

**Comment by 2betop** [comment]
这个自己集成吧，amis 不打算集成其他 富文本编辑器了。

留空是要配置 accept: '' 是不是删了？删了就是默认的 'text/plain'， 1.0.4 可能没处理 * 问题。应该是在 beta 版本上，可以通过 `npm info amis` 查看最新的版本

**Comment by foxfire881** [comment]
好的，谢谢！最新版本是1.0.4 beta3，我再试试
