### ISSUE TITLE
amis-editor编辑器中怎么生成带变量的表单

### ISSUE THREAD

**Issue by fxwing** [baidu/amis#3351]
比如input的value为"${value}"怎么在编辑器中生成，而不手动修改schema

**Comment by wibetter** [comment]
已支持，使用方式请看文档：https://aisuda.bce.baidu.com/amis/zh-CN/components/form/formitem#%E9%85%8D%E7%BD%AE%E9%BB%98%E8%AE%A4%E5%80%BC
