### ISSUE TITLE
crud的mode可以改变吗？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#3353]
#### 实现场景：
做一个select控件，选择table或者cards模式，crud根据select的值改变mode值进行不同形式的展示。由于此时data已经拉回到前端，希望通过本地方法实现展示模式改变，不用再向后端发起请求。

#### 存在的问题：
crud的mode值似乎是初始化时就固定写死了，后期无法动态更改，否则会报错无法渲染。

**Comment by nwind** [comment]
mode 不支持变量，先用显影吧，也就是用两个 crud
