### ISSUE TITLE
如何实现采用弹框的方式显示表单提交后的返回结果

### ISSUE THREAD

**Issue by Chen-Wendong** [baidu/amis#3356]
#### 实现场景：
如何实现采用弹框的方式显示表单提交后的返回结果？

提交表单后关闭第一次表单弹框，展示显示返回结果的新弹框！

#### 存在的问题：
我看官网的例子没有实现采用弹框的方式显示表单提交后的返回结果

![image](https://user-images.githubusercontent.com/88780174/148374824-036d30b5-54bc-4f15-a17b-d7b6f5b9585c.png)

#### 当前方案：
无

```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "title": "用户信息",
    "body": [
      {
        "type": "input-text",
        "name": "name",
        "label": "姓名"
      },
      {
        "type": "static",
        "name": "id",
        "visibleOn": "typeof data.id !== 'undefined'",
        "label": "返回 ID"
      }
    ]
  }
}
```

**Comment by foxfire881** [comment]
用Action
[请求成功后，显示反馈弹框](https://baidu.gitee.io/amis/zh-CN/components/action#%E8%AF%B7%E6%B1%82%E6%88%90%E5%8A%9F%E5%90%8E-%E6%98%BE%E7%A4%BA%E5%8F%8D%E9%A6%88%E5%BC%B9%E6%A1%86)

**Comment by Chen-Wendong** [comment]
@foxfire881 
谢谢 可以了，如下例子，但是还有一个问题：

设置close参数，我想把把祖先弹框关闭掉先，但是没生效，只会在最后提交后一起关闭，麻烦看看：当值为字符串，并且是祖先层弹框的名字的时候，会把祖先弹框关闭掉。这个我哪里弄错了！

![Uploading image.png…]()


下面时官网说明的解析：
boolean or string 
当action配置在dialog或drawer的actions中时，配置为true指定此次操作完后关闭当前dialog或drawer。当值为字符串，并且是祖先层弹框的名字的时候，会把祖先弹框关闭掉。


```
{
    "type": "page",
    "title": "cc",
    "body": [
        {
            "type": "tpl",
            "tpl": "这是你刚刚新增的页面。",
            "inline": false
        },
        {
            "type": "button",
            "label": "按钮",
            "actionType": "dialog",
            "dialog": {
                "type": "dialog",
                "title": "系统提示ddd",
                "body": [
                    {
                        "type": "form",
                        "body": [
                            {
                                "type": "input-text",
                                "name": "email",
                                "label": "邮箱"
                            },
                            {
                                "type": "input-password",
                                "name": "password",
                                "label": "密码"
                            }
                        ],
                        "title": "表单"
                    }
                ],
                "actions": [
                    {
                        "type": "button",
                        "label": "ajax 反馈弹框",
                        "actionType": "ajax",
                        "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
                        "feedback": {
                            "0": {
                                "title": "操作成功",
                                "body": "${id} 已操作成功"
                            },
                            "type": "dialog",
                            "body": [
                                {
                                    "type": "static",
                                    "label": "描述"
                                },
                                {
                                    "type": "form",
                                    "title": "表单",
                                    "body": [
                                        {
                                            "label": "文本框",
                                            "type": "input-text",
                                            "name": "text"
                                        }
                                    ]
                                }
                            ]
                        },
                        "close": "FirstDialog"
                    }
                ],
                "closeOnEsc": false,
                "closeOnOutside": false,
                "showCloseButton": true,
                "name": "FirstDialog"
            }
        }
    ]
}
```

**Comment by nwind** [comment]
> @foxfire881 谢谢 可以了，如下例子，但是还有一个问题：
> 
> 设置close参数，我想把把祖先弹框关闭掉先，但是没生效，只会在最后提交后一起关闭，麻烦看看：当值为字符串，并且是祖先层弹框的名字的时候，会把祖先弹框关闭掉。这个我哪里弄错了！
> 
> ![image](https://user-images.githubusercontent.com/88780174/148483105-3aa93464-8ec3-4bfd-b137-b179a7e410a0.png)
> 
> 下面时官网说明的解析： boolean or string 当action配置在dialog或drawer的actions中时，配置为true指定此次操作完后关闭当前dialog或drawer。当值为字符串，并且是祖先层弹框的名字的时候，会把祖先弹框关闭掉。
> 
> ```
> {
>     "type": "page",
>     "title": "cc",
>     "body": [
>         {
>             "type": "tpl",
>             "tpl": "这是你刚刚新增的页面。",
>             "inline": false
>         },
>         {
>             "type": "button",
>             "label": "按钮",
>             "actionType": "dialog",
>             "dialog": {
>                 "type": "dialog",
>                 "title": "系统提示ddd",
>                 "body": [
>                     {
>                         "type": "form",
>                         "body": [
>                             {
>                                 "type": "input-text",
>                                 "name": "email",
>                                 "label": "邮箱"
>                             },
>                             {
>                                 "type": "input-password",
>                                 "name": "password",
>                                 "label": "密码"
>                             }
>                         ],
>                         "title": "表单"
>                     }
>                 ],
>                 "actions": [
>                     {
>                         "type": "button",
>                         "label": "ajax 反馈弹框",
>                         "actionType": "ajax",
>                         "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
>                         "feedback": {
>                             "0": {
>                                 "title": "操作成功",
>                                 "body": "${id} 已操作成功"
>                             },
>                             "type": "dialog",
>                             "body": [
>                                 {
>                                     "type": "static",
>                                     "label": "描述"
>                                 },
>                                 {
>                                     "type": "form",
>                                     "title": "表单",
>                                     "body": [
>                                         {
>                                             "label": "文本框",
>                                             "type": "input-text",
>                                             "name": "text"
>                                         }
>                                     ]
>                                 }
>                             ]
>                         },
>                         "close": "FirstDialog"
>                     }
>                 ],
>                 "closeOnEsc": false,
>                 "closeOnOutside": false,
>                 "showCloseButton": true,
>                 "name": "FirstDialog"
>             }
>         }
>     ]
> }
> ```

没看懂问题是啥

**Comment by Chen-Wendong** [comment]
![image](https://user-images.githubusercontent.com/88780174/149074393-302acdea-6d38-4152-868b-6ce1a51ae114.png)
close 参数
当action配置在dialog或drawer的actions中时，配置为true指定此次操作完后关闭当前dialog或drawer。当值为字符串，并且是祖先层弹框的名字的时候，会把祖先弹框关闭掉。

**当值为字符串，并且是祖先层弹框的名字的时候，会把祖先弹框关闭掉。**
这个场景，我设置"close": "FirstDialog"值为字符串时，没把祖先弹框关闭掉。
![image](https://user-images.githubusercontent.com/88780174/149074653-4904e3be-a6be-400f-98af-be394ede17ad.png)
