### ISSUE TITLE
权限控制

### ISSUE THREAD

**Issue by ForeverCm** [baidu/amis#336]
![Uploading image.png…]()

能力管理和权限管理 两个页面打不开

**Comment by ForeverCm** [comment]
为了能加入权限控制，表达是中允许可以用 acl.can 方法来检测当前用户是否拥有某个权限。 如： {"disabledOn": "!acl.can('some-resource')"}。权限能力部分，请前往能力管理， 权限配置请前往权限配置管理。                        能力管理和权限管理   这两个页面打不开

**Comment by 2betop** [comment]
不好意思，这是平台内部的文档，单纯的渲染器不包含这块逻辑。

**Comment by ForeverCm** [comment]
那有什么办法实现  权限控制 吗？

**Comment by 2betop** [comment]
如果你那边想实现类似的功能，就是 amis 入口 render 的第二个参数里面加入 data: {acl: xxxx} 自己实现一个 can 方法。比如:

```
amisRender(schema, {
  data: {
    acl: {
       can: (permission:string) => true
    }
 }
}, env);
```

这样配置里面就可以在 `disabledOn` 或者 `visibleOn` 中加入 acl 的判断了。

**Comment by ForeverCm** [comment]
好的，多谢，我试试。
