### ISSUE TITLE
如何直接获取到form表单的数据data（用户修改后的data数据）

### ISSUE THREAD

**Issue by 2ue** [baidu/amis#3361]
#### 实现场景：
B项目使用amis+微前端渲染一个form表单页面，在A项目中使用，但是提交表单的行为控制在A项目，请问怎么能够直接拿到form的数据data

#### 存在的问题：
目前看文档貌似没办法拿到data数据

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by dikar** [comment]
用api 提交的吗 ？用$$可以拿
