### ISSUE TITLE
项目启动，但是浏览器报错：Uncaught [ModJS] Cannot find module `node_modules/react/node_modules/prop-types/lib/ReactPropTypesSecret`

### ISSUE THREAD

**Issue by caomingjiang** [baidu/amis#3365]
报错详情：Uncaught [ModJS] Cannot find module `node_modules/react/node_modules/prop-types/lib/ReactPropTypesSecret`

**Comment by nwind** [comment]
信息不足，大概猜是 react、mobx 版本不一致的问题，要保持和 amis 用到的一致
