### ISSUE TITLE
使用react官方脚手架或者dva来集成amis渲染器是否可行？

### ISSUE THREAD

**Issue by maybeyourking** [baidu/amis#337]
我看官方例子里是依托mobx和fis3，希望官方大大给个demo。

**Comment by 21paradox** [comment]
我写了个非官方的demo，可以参考下 https://github.com/21paradox/webpack-amis-boilerplate

**Comment by maybeyourking** [comment]
> 我写了个非官方的demo，可以参考下https://github.com/21paradox/webpack-amis-boilerplate

十分感谢，研究一下。
