### ISSUE TITLE
Markdown 存入数据库再读出时，会多出 \r\n 然后格式就乱了

### ISSUE THREAD

**Issue by gexMichael** [baidu/amis#3374]
#### 实现场景：
关于 Markdown，延续原 [issue 3328](https://github.com/baidu/amis/issues/3328) 的问题，在建立文件时，一切正常，但是存入数据库再读出时，会多出 \r\n 然后格式就乱了。请问markdown 如果是读写入数据表，要多做那些处理以避免上述错误，谢谢。

#### 存在的问题：
建立文件时，一切正常
![image](https://user-images.githubusercontent.com/22609092/148796899-14fc029a-1333-4e62-b061-d762a2dd5e0a.png)

存入数据库再读出时，会多出 \r\n 然后格式就乱了
![image](https://user-images.githubusercontent.com/22609092/148797151-03bbecb8-5900-44e5-9682-1370713f6f97.png)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
大概是多了一次转义导致，检查一下后端保存时做了什么，另外编辑器是用什么的，editor 组件？

**Comment by gexMichael** [comment]
后端应该没有特别处理，我再检查一下。是用 editor 没错，另外如果用 textares 的话，只会多存入 \r
Thanks

```
{
	"type": "group",
	"body": [
	  {
		"type": "editor",
		"name": "book_desc",
		"language": "markdown",
		"size": "xxl",
		"label": "內容"
	  },
	  {
		"type": "markdown",
		"name": "book_desc"
	  }
	]
}
```

**Comment by gexMichael** [comment]
我到后端查了一下Log，区段1是post 呼叫 api 时的传入参数，区段2是实际执行修改存盘的 api 程序，可以看出 post按 [存盘] 后呼叫 api 时，就已经将[ENTER] 换成 \r\n，请问是否有办法避开此问题? 谢谢

![image](https://user-images.githubusercontent.com/22609092/149175712-58bd1a44-f268-46c2-82ca-eca854fb80eb.png)

**Comment by gexMichael** [comment]
问题的确是因为不晓得哪个环节存档时将 ENTER 存成 \r\n
我改为在存盘后再多执行 update 语法更新即可。谢谢

update eip_online_books set book_desc = replace(book_desc,'\r\n',char(10)) where classid = '1-4';
update eip_online_books set book_desc = replace(book_desc,'\n',char(10)) where classid = '1-4';
