### ISSUE TITLE
nested-select 不能控制只有叶子节点可以选择吗？

### ISSUE THREAD

**Issue by nmf2019** [baidu/amis#3383]
nested-select 不能控制只有叶子节点可以选择吗？就是根节点和中间节点都不能选，只可以选择最终的叶子节点，这个要怎么设置呢

**Comment by Twelveeee** [comment]
试看看这个
https://baidu.gitee.io/amis/zh-CN/components/form/select#%E7%BA%A7%E8%81%94%E9%80%89%E6%8B%A9

![image](https://user-images.githubusercontent.com/48245733/149257852-3438f052-3044-4651-977b-4998858d06d5.png)

**Comment by nmf2019** [comment]
这个可以，谢谢
