### ISSUE TITLE
editor 主题设置为antd主题时，增删改的设置弹框还是cxd主题

### ISSUE THREAD

**Issue by fangsueluo** [baidu/amis#3384]
#### 描述问题：

editor 主题设置为antd主题时，增删改的设置弹框还是cxd主题

#### 截图或视频：

![image](https://user-images.githubusercontent.com/20941761/149061172-d8180b41-f171-4f47-9902-ba062b96e327.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
"amis": "1.4.2-beta.6",
 "amis-editor": "3.3.12-beta.1"

3. 粘贴有问题的完整 `amis schema` 代码：
```
<Editor
          theme="antd"
          preview={isPreview}
          value={schema}
          onChange={this.onEditorChange}
          className="is-fixed"
          $schemaUrl={schemaUrl}
          iframeUrl={iframeUrl}
          isMobile={isMobile}
          plugins={[NewRenderPlugin]}
        />
```

4. 操作步骤
在编辑器里添加增删改查组件，之后选中某一列，选择设置，dom加载了，但是主题确实cxd，而不是外部传入的antd，两边主题不一致。期望的是antd-xxx

**Comment by wibetter** [comment]
目前4.1.0-beta.21版本已经没有这个问题了，可以改用新版的Editor。
