### ISSUE TITLE
page组件asideResizor属性不生效

### ISSUE THREAD

**Issue by yangyining** [baidu/amis#3394]
#### 描述问题：

page组件在设置asideResizor属性后没有生效

#### 截图或视频：
![image](https://user-images.githubusercontent.com/3253098/149258776-4589ca55-1dd4-4a62-a996-a25b68ca7674.png)
![image](https://user-images.githubusercontent.com/3253098/149258915-5271dcfb-e86f-4d2e-9a0c-0fce6709ecde.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.6.1
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
    {
      "type": "tpl",
      "tpl": "这是内容区"
    }
  ],
  "aside": [
    {
      "type": "tpl",
      "tpl": "这是侧边栏部分"
    }
  ],
  "asideResizor": true,
  "asideMinWidth": 150,
  "asideMaxWidth": 400
}

```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lurunze1226** [comment]
`1.9.0` 版本应该已经修复了

**Comment by uoa-2019** [comment]
js-sdk方式使用，用的上面一样的配置代码，从1.7.0版本一直试到1.10.2版本，asideResizor均未生效
asideResizor只有在可视化编辑器amis-editor-demo里能看到效果，放到自己项目里都没有效果

> `1.9.0` 版本应该已经修复了
