### ISSUE TITLE
如何关掉调试信息的错误页面

### ISSUE THREAD

**Issue by cn-src** [baidu/amis#3395]
#### 实现场景：
能否关掉错误页面，像下面的这种错误页面如果呈现给客户不太友好。
![image](https://user-images.githubusercontent.com/8263180/149261435-57751f18-7b4a-4363-9680-b17bc658ea6a.png)

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
这种一般是组件问题，按说都应该修的，给个复现例子再开
