### ISSUE TITLE
amis-editor更新到最新版组合组件combo报错

### ISSUE THREAD

**Issue by duqingyu** [baidu/amis#3398]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

![image](https://user-images.githubusercontent.com/30541930/149281511-d9e42e84-9b85-4129-9040-48801a423e1a.png)
![image](https://user-images.githubusercontent.com/30541930/149282066-e988b1d7-8df6-47ff-8942-a455c6b6ffae.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis版本：1.6.1
amis-editor版本：4.0.1-beta.19

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by DC3** [comment]
cards 组件也有这个问题

**Comment by duqingyu** [comment]
经过版本回退测试，amis版本由1.6.x回退到1.5.5暂时没问题，可能是amis-editor依赖于amis的版本导致，期望官网在新的amis版本修复下这个问题，影响到amis-editor组件的使用了。
另外：amis-editor在4.0.1-beta.19版本发现适配器界面那打不开，应该是个bug
