### ISSUE TITLE
map组件文档错误

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#3401]
#### 描述问题：

map组件文档错误

#### 截图或视频：

文档低端type参数感觉拷贝了color组件的没改过来

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
见 https://baidu.gitee.io/amis/zh-CN/components/mapping
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
谢谢反馈，去掉了，下次可以提个 pr
