### ISSUE TITLE
请问amis是否有打印功能？如果有，该如何实现呢？

### ISSUE THREAD

**Issue by 969937484** [baidu/amis#3411]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
简单的自己调用 window.print() 吧
