### ISSUE TITLE
配置url或者api的时候，如果出现${}还未配置完整的情况下会直接报错

### ISSUE THREAD

**Issue by duqingyu** [baidu/amis#3424]
#### 描述问题：

配置url或者api的时候，如果出现${}还未配置完整的情况下会直接报错，在使用amis-editor配置接口url的时候，很可能会先写${},再去填写变量值，但是写到${}这一步的时候就报错了，希望amis底层能加个兼容判断

#### 截图或视频：
![image](https://user-images.githubusercontent.com/30541930/149721401-7da8dc08-7e98-4a69-8205-e6318bc88bbf.png)

![image](https://user-images.githubusercontent.com/30541930/149721417-07d32b22-80fa-4a78-bc29-b92faa5db210.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
amis版本：1.6.0
amis使用：npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
    "name": "Page",
    "type": "page",
    "title": "Mis测试页面2",
    "definitions": {},
    "body": {
        "type": "crud",
        "syncLocation": false,
        "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample/${}",
        "columns": [
            {
                "name": "id",
                "label": "ID",
                "sortable": true
            },
            {
                "name": "engine",
                "label": "Rendering engine",
                "sortable": true
            }
        ]
    }
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
官网没复现，可能是 @2betop 修了？升级到 1.6.2 试试

**Comment by duqingyu** [comment]
升级版本试了下还是不行，我尝试在官网复现了这个问题。
![image](https://user-images.githubusercontent.com/30541930/149870730-c3fa71a9-7bb2-4d42-b0b8-cafd61069b3c.png)
![1642479852(1)](https://user-images.githubusercontent.com/30541930/149870738-84ed015e-0bcc-47bf-b4af-5bcf7af25ecb.jpg)

**Comment by duqingyu** [comment]
> 官网没复现，可能是 @2betop 修了？升级到 1.6.2 试试

官网复现这个问题了，请问短期有计划修复吗？
