### ISSUE TITLE
amis-editor 类型错误：TypeError: (0 , i.__spreadArray) is not a function

### ISSUE THREAD

**Issue by wzxm** [baidu/amis#3442]
#### 描述问题：

简单使用 amis-editor 时，正常显示，当引入 Sentry 监控后，报错：

#### 截图或视频：

![image](https://user-images.githubusercontent.com/13127730/150105342-ad0cca18-269f-46f5-8ab3-ee6b03e20517.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
yarn add amis-editor

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis: 1.6.2
amis-editor:  4.0.1-beta.19

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
type: "page",
title: "测试"
}
```

4. 操作步骤
使用 react 初始化一个简单的项目
```
$ npx create-react-app my-app
$ cd my-app
$ yarn add amis amis-editor @sentry/react
$ yarn start
```

**Comment by nwind** [comment]
看着是没装 tslib
