### ISSUE TITLE
如何获取当前host？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#3443]
#### 实现场景：
点击button按钮，复制当前url的host地址，拼接上自己生成的动态参数。

#### 存在的问题：
如何获取host地址？扩展一下，客户端上有很多参数本来就可以直接通过javascript获取（如document.location.host、width等属性），如何在data中嵌入js代码获取这些参数进而用${xxx}的形式取值呢？难道这么一个简单的js参数，要从后端通过api传回来？太复杂了，有没有直接在客户端获取的方法？

#### 当前方案：
无

```
code here...
```

**Comment by foxfire881** [comment]
搞定了，adptor适配，不过还是想说太麻烦了，最好能简化下

**Comment by 2betop** [comment]
"${window:location.host}"

**Comment by 2betop** [comment]
https://baidu.gitee.io/amis/zh-CN/docs/concepts/data-mapping#namespace

**Comment by foxfire881** [comment]
> https://baidu.gitee.io/amis/zh-CN/docs/concepts/data-mapping#namespace

谢谢~大意了，没注意到这条文档。
