### ISSUE TITLE
子表单多条，新增一项按钮的文案，是否可以改为自定义？

### ISSUE THREAD

**Issue by Bamzc** [baidu/amis#3457]
#### 是否关联于某个问题吗：
在使用amis构建表单项的时候，使用了<<子表单多条>>，需求是需要新增一条附件信息，但是实际只能展示新增一项按钮

#### 预期的解决方案：
新增一项按钮可以自定义文案

#### 其他可接受方案：
暂无

#### 任何附加信息：
![页面](https://wx2.sinaimg.cn/mw2000/eb588756ly1gyk8tcqffuj20hh0er75v.jpg)

**Comment by gauliang** [comment]
```json
{
        "type": "input-sub-form",
        "addButtonText":"自定义新增按钮名",
         ...
}
```
