### ISSUE TITLE
解析 url 参数时，如果参数带 “+”

### ISSUE THREAD

**Issue by gitwd** [baidu/amis#3460]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
麻烦请再描述清晰点

**Comment by 2betop** [comment]
看来是重复了
