### ISSUE TITLE
crud按钮权限控制

### ISSUE THREAD

**Issue by tenyears94** [baidu/amis#3464]
#### 使用场景：
表格增删改功能，但是删除按钮仅部分角色或权限可见

#### 疑惑：
在文档的CRUD增删改查看到 "actions" 有个属性 "disabledOn"控制了按钮不可点击，但是我希望是没有权限就不显示（而且这个属性好像在属性介绍里面并没有）

#### 期望：
请问是否有一个属性或者方法控制元素满足某种条件才显示，类似Vue的v-show

```
code here...
```

**Comment by gauliang** [comment]
``hiddenOn

**Comment by 123lujiaqiang** [comment]
设置hiddenOn，设定一个条件值

**Comment by qiu-1231** [comment]
某些用户才能看的可以实现吗
