### ISSUE TITLE
日历的放大模式里某天的数据过多会导致弹框的关闭按钮被浮动层的header挡住而无法关闭

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#3466]
#### 描述问题：

日历的放大模式里某天的数据过多会导致弹框的关闭按钮被浮动层的header挡住而无法关闭，因为没地方设置affixOffsetTop为false，导致点击某天后，弹框显示表格页面就卡死了。如果手工缩放一下页面就会恢复。

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
20220120版本

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
提供个复现例子吧

**Comment by belongwqz** [comment]
看起来是默认的表格展示有问题，但是可以用scheduleAction来自定义，不折腾了。
