### ISSUE TITLE
amis 1.6.3版本crud的分页配置和Pagination组件不匹配

### ISSUE THREAD

**Issue by chenjianfang** [baidu/amis#3478]
#### 描述问题：

amis 1.6.2版本crud的分页配置和Pagination组件不匹配

#### 截图或视频：

![image](https://user-images.githubusercontent.com/13289959/150664053-0b038015-062d-4448-9f16-d54ce6796e28.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3. 1.6.3

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 7inspire** [comment]
1.6.4已修复
