### ISSUE TITLE
React方式时，button 的actionType为 ajax的时候，英文没有翻译

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#3479]
#### 描述问题：

使用方式是React，button 的actionType为 ajax的时候，语言为英文时，弹框文字仍为中文
和[2158](https://github.com/baidu/amis/issues/2158)问题基本一致，就是使用方式不同，这个issue是SDK方式

#### 截图或视频：

![image](https://user-images.githubusercontent.com/37805363/150712732-f36433d0-602b-4296-9ec9-64a2bd290342.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

amis版本为1.6.3，是目前最新版

3. 粘贴有问题的完整 `amis schema` 代码：
```
type: 'button',
label: 'Delete',
actionType: 'ajax',
api: 'delete:https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/sample/${ids|raw}',
confirmText: 'Sure you want to delete in bulk?',
icon: 'fa fa-trash',
```

4. 操作步骤

**Comment by nwind** [comment]
参考这个 https://github.com/baidu/amis/pull/2170/files 在 <AlertComponent 和 <ToastComponent 里加 locale

**Comment by rumunanfeng** [comment]
> AlertComponent

不是很明白要如何配置，我用React，按钮就是一个JSON文件，在json文件中如何配置locale？

**Comment by rumunanfeng** [comment]
> 参考这个 https://github.com/baidu/amis/pull/2170/files 在 <AlertComponent 和 <ToastComponent 里加 locale

不是很明白要如何配置，我用React，按钮就是一个JSON文件，在json文件中如何配置locale？

**Comment by LiuZixia** [comment]
> > 参考这个 https://github.com/baidu/amis/pull/2170/files 在 <AlertComponent 和 <ToastComponent 里加 locale
> 
> 不是很明白要如何配置，我用React，按钮就是一个JSON文件，在json文件中如何配置locale？

您好，请问您解决这个问题了吗？如果解决了的话，能否分享一下具体解决方法？
