### ISSUE TITLE
配置请求数据时，请求字段不填时，使用default:undefined加过滤器失效

### ISSUE THREAD

**Issue by light-1986** [baidu/amis#3482]
#### 描述问题：

文档Api地址，
#
https://baidu.gitee.io/amis/zh-CN/docs/types/api
配置请求数据时，请求字段不填时，
"create_time_start": "${create_time_start_range|split|first|date:YYYY-MM-DD|default:undefined}",

chrome network 中，请求数据会变成Invalid date

create_time_start: Invalid date
create_time_end: Invalid date

#### 截图或视频：
![image](https://user-images.githubusercontent.com/1289921/150753257-100eb661-115c-4f30-a92e-f8702c9b6899.png)

如果仅使用"create_time_start": "${create_time_start_range|default:undefined}"，则可以正常使用，数据没填时不发送此字段。

单独使用 "create_time_start": "${create_time_start_range|split|first|date:YYYY-MM-DD}“，这样也可以使用

**Comment by allenve** [comment]
使用公式  过滤器是按顺序执行的
比如 "${IF(create_time_start_range, SPLIT(create_time_start_range), undefined)}"
