### ISSUE TITLE
最近几次升级的功能文档不太好找

### ISSUE THREAD

**Issue by ztky01** [baidu/amis#3488]
比方说
1.6.1
组件广播事件机制 (#3326) @hsm-lv
amis Debug 辅助工具 (#3370) @nwind
文档不太好找,目前没找到
而且通过文档右上角的检索,能不能直接搜1.6.1等,就可以把每次升级的新增内容找出来方便学习,其实也能搜出来一些,但不全.
感谢

其实现在amis已经很好了,赞!!!

**Comment by nwind** [comment]
第一个功能还不完整，等完善后再补充文档；第二个是路由漏了已补充。

一般 release 说明会附上文档链接，后续考虑文档也加个页面。
