### ISSUE TITLE
table的footerToolbar固定问题

### ISSUE THREAD

**Issue by YUHUAJ** [baidu/amis#349]
tabler的footerToolbar底部工具栏，有没有像headertoolbar这样有一个属性 affixHeader来固定footertoolbar？因为如果我的每页数据显示是100条，当我要跳页时就需要把数据拉到最底部才能点击跳页。

**Comment by 2betop** [comment]
你可把分页放到顶部呢

**Comment by 2betop** [comment]
headerToolbar 是可以配置元素的 比如这个栗子 https://baidu.github.io/amis/crud/table?page=1

**Comment by 2betop** [comment]
有问题再开，先关了。
