### ISSUE TITLE
API接口方法使用

### ISSUE THREAD

**Issue by tenyears94** [baidu/amis#3490]
#### 实现场景：
页面初始化时，我需要去后台请求部分配置信息，比如我将主题配置到后台，启动项目时需要去后台获取默认主题

#### 存在的问题：
这种请求可以直接使用amis封装的api请求吗？还是需要自行配置axios或者Ajax来实现？

```
code here...
```

**Comment by nwind** [comment]
可以放页面模板变量里，或者自己 axios 请求
