### ISSUE TITLE
封装了一套基于 react 的amis-admin 项目模版，希望得到推荐

### ISSUE THREAD

**Issue by nolan1230** [baidu/amis#3491]
#### 内容：
封装了一套基于 react 的amis-admin 项目模版，希望得到推荐

#### 特性：
支持在代码里直接写amis  json 文件，也可以自己写 react 组件

#### 任何附加信息：
git 地址：
https://github.com/nolan1230/react-amis-admin-tpl

**Comment by nwind** [comment]
加油，先记下了，打算等再多点第三方项目的时候集中放 README 里引流
