### ISSUE TITLE
crud组件，导出EXCEL 功能按钮支持配置吗？例如配置icon图标

### ISSUE THREAD

**Issue by BarronLin** [baidu/amis#3499]
#### 实现场景：
我在配置crud组件时，这样配置了：
`      "headerToolbar": [
        {
          "type": "export-excel",
          "align": "right",
          "label": "XLSX",
          "icon": "iconfont icon-excel"
        }
      ]
`

#### 存在的问题：
但 “导出Excel” 按钮没有显示icon 图标

**Comment by nwind** [comment]
目前还不支持这些配置，看来得换一下实现才行

**Comment by lurunze1226** [comment]
```
{
        "type": "export-excel",
        "icon": "fa fa-plus"
}
```
1.9.0支持了
