### ISSUE TITLE
amis-editor 作为一个页面被调用

### ISSUE THREAD

**Issue by unruledboy** [baidu/amis#3507]
#### 实现场景：
我们使用amis-admin 模板 ( https://github.com/aisuda/amis-admin ) 来快速搭建我们的管理器，这个管理器里面我需要用到amis-editor 编辑具体功能的界面。

就是类似现在amis-admin例子里面editor.json，那个是monaco-editor的例子。但是怎么加载amis-editor，接受json schema然后用户可以进行界面设计？

#### 存在的问题：
请问如何定义这个amis-editor的schema？需要自己写自定义组件吗(SDK或者React)？还是已经这样的解决方案？

#### 当前方案：
目前还没有可行的方案。

**Comment by nwind** [comment]
amis-editor 这个项目 https://github.com/aisuda/amis-editor-demo，找个熟悉 React 的前端开发来支持吧
