### ISSUE TITLE
无法自动获取当前位置

### ISSUE THREAD

**Issue by hcf1997** [baidu/amis#3509]
{
"type": "page",
"body": {
"type": "form",
"api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
"debug": true,
"body": [
{
"type": "location-picker",
"name": "location",
"ak": "LiZT5dVbGTsPI91tFGcOlSpe5FDehpf7",
"label": "地址"
}
]
}
}
这个组件只支持弹框选择位置

**Comment by nwind** [comment]
没复现，可能是浏览器关了权限？
