### ISSUE TITLE
form text autoComplete

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#351]
在使用text 的 autoComplete时，本文本的值 怎么没有包含到请求参数内呢 ？

**Comment by 2betop** [comment]
`${term}` 用这个取，比如 `autoComplete: "/api/xxx?term=${term}"`

**Comment by icodingx** [comment]
请问由关于 AMis 的技术讨论群吗 ？

**Comment by icodingx** [comment]
@2betop 这个属性可以设置为 text 到指定长度后，再发请求吗？

**Comment by 2betop** [comment]
目前不支持，加入下个版本计划

**Comment by icodingx** [comment]
> @2betop 1.0.6 预计什么时候 发布呢？还有，API可以设置参数为空时不发请求吗？

**Comment by 2betop** [comment]
着急先用这个版本 `amis@1.0.5-beta.24`，支持以下配置实现你的需求。

```
autoCompelte: {
   method: "get",
   url: 'xxxx',
   sendOn: 'this.term && this.term.length > 2'
}
```

当有输入值，且大于2个字符时发送请求。

**Comment by 2betop** [comment]
发布了正式版本，所以先关了
