### ISSUE TITLE
ajax提交表单时，如何调用表单验证方法

### ISSUE THREAD

**Issue by dikar** [baidu/amis#3534]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

ajax提交表单时，如果执行表单验证方法

使用1.6.1 的sdk 

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```

```

**Comment by nwind** [comment]
https://baidu.gitee.io/amis/zh-CN/components/form/formitem#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%A0%A1%E9%AA%8C
