### ISSUE TITLE
过滤器 date 不完整

### ISSUE THREAD

**Issue by ywzhaiqi** [baidu/amis#3537]
#### 描述问题：

过滤器 date 不完整。`${now|date:YYYY-MM-DDTHH:mm:ssZ}` 渲染为 `2022-02-03T00`

#### 截图或视频：

![2022-02-03_011533](https://user-images.githubusercontent.com/3016136/152203954-0519580b-52e0-4d24-bcf3-215011552170.jpg)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 、官网

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

1.6.2、1.6.4 都存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "data": {
    "now": 1586865590
  },
  "body": {
    "type": "tpl",
    "tpl": "now is ${now|date:YYYY-MM-DDTHH:mm:ssZ}"
  }
}
```

4. 操作步骤
无

**Comment by nwind** [comment]
冒号冲突了，用 {now|date:YYYY-MM-DDTHH\\:mm\\:ssZ}

**Comment by huangmengjiao-hmj** [comment]
我用的2.2.0的版本这个问题还是存在 并且使用格式为您说到这个时间变成53944-12-13T14:42:38+08:00

**Comment by huangmengjiao-hmj** [comment]
当格式为YYYY-MM-DD HH\\:mm\\:ss 显示正确但是时间并没有格式化对 53944-12-13 14:42:38 毫秒戳为1640170968158
