### ISSUE TITLE
角标位置优化

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#3538]
参考了一些设计较好网站，头像的角标往往用于显示用户在线状态。如下图所示：
![image](https://user-images.githubusercontent.com/5292190/152468952-6d0b0a83-4282-4b0c-80a3-8fbf84b9b10a.png)
![image](https://user-images.githubusercontent.com/5292190/152469008-b288bf44-15e8-4311-bf62-3ea88761a69f.png)
结合当前amis的官方样例，position 设定之后，角标远离头像位置，至少我觉得不是很美观
以下建议：
1、能否多提供一种类型位置的设置，符合上述图片的样式，简化开发。
2、能否开放position 的上下偏移量参数，交付用户根据实际情况自我微调。
感谢！

**Comment by lurunze1226** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/badge#%E6%98%BE%E7%A4%BA%E4%BD%8D%E7%BD%AE 角标可以通过offset属性调整偏移量
