### ISSUE TITLE
What icon does amis have?amis icon有哪些？

### ISSUE THREAD

**Issue by gqs2924255155** [baidu/amis#3542]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：What icon does amis have?
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by gqs2924255155** [comment]
可以罗列一些吗，比如文件夹，文件等图标

**Comment by nwind** [comment]
对外使用主要是 fontawesome https://baidu.gitee.io/amis/zh-CN/components/icon，内置虽然也有几个图标，但未开放使用
