### ISSUE TITLE
Feature:api支持链式操作

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#3550]
#### 是否关联于某个问题吗：
api支持链式操作，比如请求成功后出发某个都想的刷新，类似于action的reload，

比如form里某个required为true的select组件配置了source为api，希望这个select获取到数据后立马对form做一次提交，此时配置form的submitOnChange不管用，如果这个select的source的api支持链式调用来触发提交表单就可以达到目的。

#### 预期的解决方案：
```
{
   "url": "xxx",
    "reload": "xxxname"
}
```

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by lurunze1226** [comment]
1.9.0的[事件动作](https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action) 应该可以实现你的需求
