### ISSUE TITLE
如何配置导出文件的按钮

### ISSUE THREAD

**Issue by osenlin** [baidu/amis#356]
1. 按下面配置，会说没有按照要求返回数据
`                                {
                                    "type": "button",
                                    "label": "导出",
                                    "api": "/export",
                                },`
2. 按文档的例子，点击没有啥反应
`                                {
                                    "type": "button",
                                    "label": "导出",
                                    "url": "/export",
                                },`
3. 按下面的方式，会和第一种一样，报返回格式不符合要求

`                                {
                                    "type": "button",
                                    "label": "导出",
                                    "actionType": "ajax",
                                    "url": "/export",
                                    "level": "success"
                                },`

哪个同学有配置过导出excel按钮的，帮指导下

**Comment by 2betop** [comment]
amis 不带导出功能，这无非是一个按钮，按钮的类型是页面跳转，跳转到一个可以生成下载文件的地址，这个地址要自己提供。

**Comment by osenlin** [comment]
> amis 不带导出功能，这无非是一个按钮，按钮的类型是页面跳转，跳转到一个可以生成下载文件的地址，这个地址要自己提供。

配置成如下方式就可以导出，但是url要填全路径信息，有没有一种方式能够定义成相对路径直接用
"url:'get:/export'"，或者能够将http://192.168.200.133:10022抽象称站内全局，能够直接“url:$globalhost/export”
```
                                {
                                    "label": "导出",
                                    "type": "button",
                                    "level": "success",
                                    "actionType": "url",
                                    "url": "http://192.168.200.133:10022/export"
                                },
```

**Comment by 2betop** [comment]
这个 jumpTo 貌似在 env 里面控制的。实现相对路径可以看下那块地逻辑

**Comment by osenlin** [comment]
![图片](https://user-images.githubusercontent.com/7776208/69316934-c93a4400-0c74-11ea-95d1-8150ea7813f4.png)
@2betop JumpTo这样的逻辑不知道正不正确，设成相对路径，没起作用

**Comment by 2betop** [comment]
debugger 一下，可能进入的是 updateLocation 这个 env 属性。

**Comment by osenlin** [comment]
> debugger 一下，可能进入的是 updateLocation 这个 env 属性。

修改components/AMisRenderer.tsx中的jumpTo就可以解决，但是又出现一个新的问题
在上面的url如果带有参数，"url": "http://192.168.200.133:10022/export?参数1=$control_name1&参数2=$control_name2"
如果参数2是由 引用的控件提供的$control_name2拿到的是一个Object，如下
“http://192.168.200.133:10022/export?s=&start_date=2019-10-22&where_dim_cond=[object Object]”
**怎么样拿到引用控件的值，而不是[object Object]**
下面是我的tsx配置：

>                        {
                            "$ref": "queryGroup",
                            "name": "where_dim_cond",
                            "value": {},
                            "minLength": 0,
                            "label": "条件筛选："
                        },
                        {
                            "type": "divider"
                        },
                        {
                            "type": "group",
                            "mode": "horizontal",
                            "controls": [
                                {
                                    "type": "date",
                                    "label": "开始日期",
                                    "name": "start_date",
                                    "value": "-30days",
                                    "format": "YYYY-MM-DD",
                                    // "inline": true,
                                    "size": "full",
                                    "maxDate": "${end_date}"
                                },
                                {
                                    "type": "date",
                                    "label": "结束日期",
                                    "name": "end_date",
                                    "value": "-1days",
                                    "format": "YYYY-MM-DD",
                                    "size": "full",
                                    "minDate": "${start_date}"
                                },
                                {
                                    "type": "submit",
                                    "label": "查询",
                                    "level": "primary"
                                },
                                {
                                    "label": "导出",
                                    "type": "button",
                                    "level": "success",
                                    "actionType": "url",
                                    "url": "/export?s=$group_dim_ids&start_date=$start_date&where_dim_cond=$where_dim_cond&ss1=$service1.api",
                                },

                            ]
                        }

**Comment by 2betop** [comment]
`http://192.168.200.133:10022/export?参数1=${control_name1}&参数2=${control_name2}` 试试这个格式

**Comment by osenlin** [comment]
> `http://192.168.200.133:10022/export?参数1=${control_name1}&参数2=${control_name2}` 试试这个格式

${control_name2} 这种方式拿到的 **引用控件** 的值还是 [object object] @2betop

**Comment by 2betop** [comment]
不好意思，现在才看到，目前 url 参数里面数据映射确实还不支持对象类型，包括数组也是。这个我在下个版本种解决这个问题。

**Comment by osenlin** [comment]
好的，谢谢

**Comment by 2betop** [comment]
新版本已经可以了。
