### ISSUE TITLE
【建议】希望crud导出Excel支持导出children节点数据

### ISSUE THREAD

**Issue by Cloydhe** [baidu/amis#3563]
目前试了一下只能导出外层数据，嵌套内容无法导出

**Comment by Chen-Wendong** [comment]
表格字段配置是下级，导出时也是空白，希望也可以支持"${OperateName.zh-CN}"这种！
表格字段：
{
  "type": "text",
  "label": "操作名",
  "placeholder": "-",
  "name": "${OperateName.zh-CN}"
}

数据：
"OperateName":{
       "zh-CN":"登录系统",
       "en-US":"Login System"
}

![image](https://user-images.githubusercontent.com/88780174/155097077-85fdefa3-f499-4523-b390-6099fd216f8c.png)


![image](https://user-images.githubusercontent.com/88780174/155096956-d7465dd9-3499-4f5b-b50a-24e79c5e3cd8.png)

**Comment by Chen-Wendong** [comment]
api返回数据时可以使用responseData处理先
