### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#358]
通过 `sh publish.sh` 后, 有如下提示:
```
  node_modules/@types/whatwg-fetch/index.d.ts:8:1
    8 interface Window {
      ~~~~~~~~~
    Conflicts are in this file.


Found 176 errors.
```

**Comment by 2betop** [comment]
node 版本问题？什么版本？试试 10？

**Comment by icodingx** [comment]
@types/whatwg-fetch/index.d.ts:6:23 - error TS2688: Cannot find type definition file for 'whatwg-streams'.

bkf$ node -v
v12.13.0

**Comment by icodingx** [comment]
$ node -v
v10.17.0

还是这个错 @2betop 

```
Found 176 errors.
```
