### ISSUE TITLE
所有组件添加备注

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#3593]
#### 是否关联于某个问题吗：
因为页面是使用json来写的，所以没有办法写注释，但是有的时候又希望在文件中记录一点什么。

#### 预期的解决方案：
所以，希望在所有的字段上添加一个注释的字段。

额。。。好像自己随便写一个属性来记录也可以。。。
先提issue，要是觉得没有必要加，就关闭吧

**Comment by nwind** [comment]
amis-editor 里支持通过 `//` 写注释，自定义属性可以加个下划线避免冲突
