### ISSUE TITLE
组件上添加【失效】属性

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#3594]
#### 是否关联于某个问题吗：
有的时候写了一些功能，但是又不希望显示出来，现阶段不需要了。但是可能在未来是需要的。
普通的javascript直接不管，或者注释掉就可以了。
但是在json中无法注释或者不管。
而使用visibleOn，又会参与到渲染过程中

#### 预期的解决方案：
添加一个属性，用来标记当前组件失效，不再使用。同时也不再做任何渲染

**Comment by xiahao90** [comment]
不是应该用// 或者# 注释吗？

**Comment by 2betop** [comment]
可以让编辑器去支持注释

**Comment by lhtuling** [comment]
还有就是用js配置文件   我一直都用js配置文件搞的 其中一个原因就是注释问题  还有必须双引号 尾部不能多逗号这种情况
所以建议用js写配置文件  更顺手!

建立了一个Amis交流QQ群 感兴趣的可以加下
QQ群号：717791727
