### ISSUE TITLE
关于CRUD

### ISSUE THREAD

**Issue by 807y** [baidu/amis#3595]
#### 实现场景：
CURD用query参数初始化筛选表单项，重置之后表单清空

#### 存在的问题：
重置后筛选表单项无法清空，请问怎么清空它

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
![image](https://user-images.githubusercontent.com/38170365/154216781-12cc379e-8270-4aaa-b98b-2128cdaf84d8.png)
![image](https://user-images.githubusercontent.com/38170365/154216825-ec319123-aad8-4bb7-a721-fb5a13a092ea.png)
```
code here...
```

**Comment by duqingyu** [comment]
同问

**Comment by 807y** [comment]
找到方法了 用clear

**Comment by duqingyu** [comment]
似乎clear-and-submit可以

**Comment by kzf32** [comment]
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/26158377/156115769-5ed3260c-a6c3-431f-883c-4987a4817ff4.png">
设置成false，地址栏不会带条件，重置之后表单清空
