### ISSUE TITLE
select组件在低网速的情况下source会渲染不出来

### ISSUE THREAD

**Issue by tangjion** [baidu/amis#3598]
在crud的外层包一个service来获取原始数据，然后在filter中使用时，在网速低的情况下，会出现select组件的source渲染不出来的情况

**Comment by lurunze1226** [comment]
可以使用Service的[轮询](https://aisuda.bce.baidu.com/amis/zh-CN/components/service#%E5%AE%9A%E6%97%B6%E8%BD%AE%E8%AF%A2%E5%88%B7%E6%96%B0)
