### ISSUE TITLE
service中需要solt

### ISSUE THREAD

**Issue by juqkai** [baidu/amis#3602]
#### 是否关联于某个问题吗：
我想做一个CMS，很多组件都是通过serviceAPI来加载的json。
比如布局的组件只会负责布局，但是呢具体内容我又希望在调用这个组件时放在service中。

#### 预期的解决方案：
在service中添加solt，让组件可以扩展。

**Comment by 2betop** [comment]
没太看懂，不知道是否 service 的 schemaApi 能否满足你的需求

**Comment by lurunze1226** [comment]
duplicated with #3646
