### ISSUE TITLE
amis-editor按钮没有clear-and-reset类型的动作选项

### ISSUE THREAD

**Issue by duqingyu** [baidu/amis#3603]
#### 描述问题：

amis-editor按钮没有clear-and-reset类型的动作选项，无法配置clear类型的按钮，该按钮在开启syncLocation时必须用它来用来重置

#### 截图或视频：

![image](https://user-images.githubusercontent.com/30541930/154441192-1aa68923-f800-498a-85fc-691f16108b4f.png)

**Comment by nwind** [comment]
补充了等待新版
