### ISSUE TITLE
城市组件能否获取到省市区的code？

### ISSUE THREAD

**Issue by agileago** [baidu/amis#3625]
#### 实现场景：
![image](https://user-images.githubusercontent.com/11799110/155048809-4518530b-e048-4c96-8a4b-e822696b552a.png)
原型是这样设计的，数据库设计了3个字段省、市、区分别保存code
#### 存在的问题：
但现在城市组件貌似只能获取到最后一级的code，获取不到省市区的code

#### 当前方案：
不知道怎么做

```
code here...
```

**Comment by Akitata** [comment]
内置城市组件太难用，建议自己用多个select或者tree-select做。。
