### ISSUE TITLE
目前是不是还不支持react17嘛？

### ISSUE THREAD

**Issue by shlroland** [baidu/amis#3627]
#### 描述问题：
在react 17.0.2 下报错
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```
切换成react16.14正常
看文档是1.6.5开始支持react 17，想问一下大概什么时候会发布？
#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.6.4
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
这是哪个组件报出来的？麻烦再帮忙看看

**Comment by shlroland** [comment]
> 这是哪个组件报出来的？麻烦再帮忙看看

我直接按照文档中的react实例启动在公司项目里面就报错了

**Comment by shlroland** [comment]
> 这是哪个组件报出来的？麻烦再帮忙看看

<img width="938" alt="image" src="https://user-images.githubusercontent.com/45024986/155075042-9e96145b-2f7e-4723-8ae2-e07612ee9643.png">

**Comment by nwind** [comment]
应该是最新 beta 才支持，目前官网已经使用 React 17 了
