### ISSUE TITLE
是否有考虑维护一个LTS版本

### ISSUE THREAD

**Issue by hereisok** [baidu/amis#3628]
#### 是否关联于某个问题吗：
我们考虑将一些面向用户的低频率页面使用amis来实现，但按照目前amis的迭代方式， 每个小版本都有很多feature引入和bug修复， 这种迭代方式对生产环境的服务部署不是那么友好。

#### 预期的解决方案：
维护一个较为长时间的lts版本， 如半年，该版本只做bugfix和有限的feature引入

**Comment by nwind** [comment]
目前人力有限，不会考虑，长期会不断补充测试用例的覆盖面来减小风险

**Comment by hereisok** [comment]
好的， 谢谢

**Comment by PurplestViper** [comment]
LTS 计划应尽早提上日程，否则采用该产品的客户最终将维护一个内部版本（比如我司），这极不利于双方产品发展，开源带来的好处将被掩盖。

**Comment by xiahao90** [comment]
+1

**Comment by xianlinzhang** [comment]
+1
