### ISSUE TITLE
鸡肋的Froala富文本编辑器

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#363]
Amis自带的那个Froala富文本编辑器实在太鸡肋了，食之无味弃之可惜，用Amis大半年了从来就没用过这个富文本组件，本来功能就少，居然还要收费，集成进去的还是个unlicensed没有破解、没有注册的，用几次就用不了了，实话实说真的挺恶心的，画蛇添足狗尾续貂，真的搞不明白为什么要集成这个编辑器进去。

网上有很多免费好用的富文本编辑器，比如程序员流行的editor.md（ http://editor.md.ipandao.com/ ）  Markdown开源编辑器超级好用还是开源免费的，最近一直在折腾想把它集成进amis，无奈代码太复杂（是amis代码太复杂）整了半天整不明白，希望官方后续能把editor.md整合进amis，或者给个整合教程让我们自己动手整合也好啊。。谢谢了

**Comment by 2betop** [comment]
已经换成 tinymce 了如果用的 amis 的 cdn 地址需要配置好 vendor: "tinymce"， 其他模式默认就是 tinymce
