### ISSUE TITLE
textarea怎么赋初始值呢？value属性无效

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#364]
{
type:"textarea"
name:"desc"
label:"描述"
value:"this is a test"
}

value无效，要怎么给textarea赋初始值呢？

**Comment by 2betop** [comment]
就是这样，无效说明有值了，注意 form 的 initApi 是不是已经返回了。

**Comment by foxfire881** [comment]
的确有点问题，我是好几个弹出按钮嵌套在一起的，最外层的form init取了一个desc字段显示出来，然后内层的desc字段就无效了 —— 现在希望内层的desc时个初始化值，不要被外层的同名字段覆盖，有好的方法不？只是想给它赋个初始值而已啊…… 难道为了给前端赋个初始值还要在后端再写一个initApi然后再给前段做初始化调用？这样就小题大做啦

**Comment by foxfire881** [comment]
觉得应该把优先级调整一下，显示赋值的值，优先级应该大于后端api取回来的值；内层的值优先级应该大于外层的同名字段值

**Comment by 2betop** [comment]
弹出按钮的 dialog 里面配置个 data: {} 这样就不会继承了。

{
  dialog: {
    title: 'xxxx',
    data: {}
  }
}

**Comment by foxfire881** [comment]
测试data好用！谢谢！

{
  dialog: {
    title: 'xxxx',
    data: {desc:"this is a test"}
  }

}

**Comment by 2betop** [comment]
data 也可以留空，这样 表单的默认值就有用了。主要原因是默认弹窗会继承所在环境的数据。通过设置 data 后就不再默认继承了。

**Comment by foxfire881** [comment]
原来如此，很好的设计框架，继续加油，持续完善！
