### ISSUE TITLE
Support Webscroket

### ISSUE THREAD

**Issue by h7ml** [baidu/amis#3640]
#### 是否关联于某个问题吗：
 At present, Amis can support HTTP communication, but some scenarios need to use webscroket. Can this be supported

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by phxgbl** [comment]
@h7ml  https://baidu.github.io/amis/zh-CN/components/service#通过-websocket-实时获取数据
