### ISSUE TITLE
NAV 中嵌入一个Drawer / Dialogue 弹出401

### ISSUE THREAD

**Issue by ssonow** [baidu/amis#3644]
#### 描述问题：

           {

                                        "label": "1.3 检查过程\n",
                                        "type": "button",
                                        "actionType": "dialog",
                                        "dialog": {
                                            "title": "弹框",
                                            "body": "这是个简单的弹框。"
                                        }

                                    },
#### 截图或视频：
弹出401: 

 
![image](https://user-images.githubusercontent.com/3630791/155866578-f8e4ddde-ac48-4468-9c3d-abfda77dfd63.png)

 
#### 如何复现（请务必完整填写下面内容）：

Erupt 开源中带的AMIS组件

4. 操作步骤
如上

**Comment by lurunze1226** [comment]
这个问题和amis无关
