### ISSUE TITLE
大量数据下场景下的表格/表单性能差

### ISSUE THREAD

**Issue by gillbates** [baidu/amis#3647]
#### 是否关联于某个问题吗：

大数据的一个展示场景，用的现在的crud组件，因为后台有每个查询组合下都有上千万接近亿条数据，所以分页，每页做的10000条，要不翻起来太累了。。。

之前项目里面用的aggrid，显示大数据量的时候（一页10w条）页面不卡。。。最近在所有项目都迁移到amis。。。
发现amis，单页1w条数据的时候 在 我的m1 max 64g下的chrome里要卡2分钟，其他测试机8-16g内存，i5 cpu要卡5分钟。。。希望各位高手有空可以优化下。。。

之前我们用的表格组件：https://www.ag-grid.com/example.php

#### 预期的解决方案：
能优化下js的性能，渲染10000条的时候不卡顿。。。如果能10w条，那当然更好。。。

#### 其他可接受方案：
希望各位高手有空优化下。。。我们开始全线迁移到amis了。。。

**Comment by cmdares** [comment]
的确AG-Grid 挺NB

**Comment by agileago** [comment]
amis适合通用展示型的页面，你这种超级重的页面不适合用amis,建议嵌个微前端做

**Comment by gillbates** [comment]
> amis适合通用展示型的页面，你这种超级重的页面不适合用amis,建议嵌个微前端做

主要是现在所有项目都开始迁移到amis了。。。想以后全部在amis里面一次性搞定嘛。。。

**Comment by agileago** [comment]
....那你等着哭吧，amis不可能会解决你的所有问题的，就我目前所搭建的系统 (可视化amis + 微前端)，前端在配页面的时候各种不适应，展示型页面很顺畅，但稍微涉及点数据流交互就很难搞，这个时候我就让他们用微前端做，别想着amis全部做

**Comment by joeoops** [comment]
也碰到这个问题了，数据多实在太卡，期待快解决

**Comment by nwind** [comment]
3.4.1 之后版本加了延迟渲染，应该好多了，有问题再开

**Comment by mixiaodiao** [comment]
1，amis很好，95%都是了
2，table太拉，不管是table,crud,input-table都一样，100条都觉得要命
3，希望改善，感觉最近资源投入变少了，去年每月固定跟新，如今3个月不到2次了
