### ISSUE TITLE
点击button发送两个请求

### ISSUE THREAD

**Issue by 0undefined0** [baidu/amis#3650]
#### 实现场景：
点击buton发送一个请求，请求回来根据上一个请求返回参数判断再发另一个请求

#### 存在的问题：
无发捕获请求返回

#### 当前方案：
暂无

```
{
  "type": "button",
  "label": "取消发布",
  "onClick": "props.onAction(event, {\n  \"actionType\": \"ajax\",\n  \"api\": {\n    \"method\": \"post\",\n    \"url\": \"/api/mock2/form/saveForm\",\n    \"data\": {\n        \"conds\":{\n          \"id\": {\n            \"eq\": 1\n        }\n      }\n    }\n  }\n})"
}
```

**Comment by lhtuling** [comment]
第一次发送请求不需要用onclick啊  直接用行为按钮就行了
然后配置接收器可以获取到结果  根据结果自己写代码二次请求
https://aisuda.bce.baidu.com/amis/zh-CN/components/action
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8

**Comment by lurunze1226** [comment]
[事件动作](https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action)应该也可以实现你的需求
