### ISSUE TITLE
property组件搭配breadcrumb组件页面会报错

### ISSUE THREAD

**Issue by guikeyy** [baidu/amis#3656]
#### 描述问题：

在breadcrumb组件配置了source，property组件搭配breadcrumb组件下页面会报错

#### 截图或视频：

![property组件搭配breadcrumb组件页面会报错](https://user-images.githubusercontent.com/24204572/156115178-0832b10d-4a2b-4a47-96ca-354c8d4d88ef.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

skd方式

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

1.6.2，1.7.0

4. 粘贴有问题的完整 `amis schema` 代码：
```json
{
    "type":"property",
    "title":"基本信息",
    "labelStyle":{
        "width":120,
        "height":46,
        "textAlign":"center",
        "verticalAlign":"center"
    },
    "contentStyle":{
        "verticalAlign":"center"
    },
    "items":[
        {
            "label":"所属",
            "content":{
                "type":"breadcrumb",
                "separator":">",
                "separatorClassName":"text-black",
                "source":"${breadcrumb}"
            },
            "span":3
        }
    ]
}
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by wibetter** [comment]
@guikeyy 已在amis中修复，相关改动见：https://github.com/baidu/amis/pull/9948/commits/508e33f113d19868a8908fcd91520fa8f7b6c2ee
