### ISSUE TITLE
提供前端状态存储能力

### ISSUE THREAD

**Issue by rencoo** [baidu/amis#3664]
#### 是否关联于某个问题吗：
希望能提供一个前端状态存储的解决方案，用来存储诸如用户基本信息等内容

#### 预期的解决方案：
对于用户基本信息等基础内容（或者其他全局变量），统一存储，无论哪里用到都可以获取到

**Comment by lhtuling** [comment]
正常用localStorage   就可以了啊!    表达式可以轻松获取   文档表达式里面有说明   多看看文档就会发现很多隐藏功能!

**Comment by rencoo** [comment]
看了文档表达式可以做到取localStorage里的数据并显示，另外通过dataProvider也可以做到。但是往localStorage里存数据，是不是只有在button的onClick的回调逻辑里才能做到呢？有没有类似于类似于生命周期的概念，比如接口调用前可以自定义一段逻辑，接口调用后可以自定义一段逻辑

**Comment by rencoo** [comment]
> 正常用localStorage 就可以了啊! 表达式可以轻松获取 文档表达式里面有说明 多看看文档就会发现很多隐藏功能!

看了文档表达式可以做到取localStorage里的数据并显示，另外通过dataProvider也可以做到。但是往localStorage里存数据，是不是只有在button的onClick的回调逻辑里才能做到呢？有没有类似于类似于生命周期的概念，比如接口调用前可以自定义一段逻辑，接口调用后可以自定义一段逻辑

**Comment by lhtuling** [comment]
> 建议碰到问题了多看几遍文档... 
比在这里问等答案好的多  也快的多   这里回复很慢的  管理可能比较忙   然后社区一点都不活跃....
文档内容很全  就是稍微有点散乱的感觉  你说的这些在文档里都可以找到答案  
https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA
https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/ui-library

建立了一个Amis交流QQ群 感兴趣的可以加下
QQ群号：717791727

**Comment by lhtuling** [comment]
> > 正常用localStorage 就可以了啊! 表达式可以轻松获取 文档表达式里面有说明 多看看文档就会发现很多隐藏功能!
> 
> 看了文档表达式可以做到取localStorage里的数据并显示，另外通过dataProvider也可以做到。但是往localStorage里存数据，是不是只有在button的onClick的回调逻辑里才能做到呢？有没有类似于类似于生命周期的概念，比如接口调用前可以自定义一段逻辑，接口调用后可以自定义一段逻辑

建议碰到问题了多看几遍文档...
比在这里问等答案好的多 也快的多 这里回复很慢的 管理可能比较忙 然后社区一点都不活跃....
文档内容很全 就是稍微有点散乱的感觉 你说的这些在文档里都可以找到答案
https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA
https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/ui-library

建立了一个Amis交流QQ群 感兴趣的可以加下
QQ群号：717791727
