### ISSUE TITLE
使用JSSDK方式如何跳转页面

### ISSUE THREAD

**Issue by skyshore2001** [baidu/amis#3665]
#### 实现场景：

页面间跳转，如果使用App组件，会出现左侧菜单栏。有时不想要菜单栏，比如登录页就是独立的页面，或是在移动端，也不想要菜单栏。

#### 存在的问题：

1. 如果用App组件（用它定义路由），怎么只显示Page组件（不显示菜单或导航，比如显示独立的登录页）？如果不用App组件，怎样实现路由，是否能实现页面跳转？
2. 可否不定义urlpath与页面的关联，当访问比如`#page1`时自动取`pages/page1.json`文件？如何实现
3. 跳转指定页面有API函数吗？

#### 当前实现

我现在想在进入应用前显示一个登录页，
我使用`amis.embed("#root", loginPage)` 做登录页，则它是一个单页面，似乎无法跳转其它页面。
如果我使用`amis.embed("#root", app)`，然后把登录页做成一个路由项，则登录页左侧会有菜单导航。

**Comment by lhtuling** [comment]
思维被局限了哇  可能会有更好的方式  但是为啥不在搞个login.html的登陆页面呢?  特殊的不需要左侧菜单栏的直接就单独建个页面多简单了~~跳转1可用用按钮跳转   2可用提交表单后设置成功跳转    3可在事件里面直接用原生js   location.href跳转

**Comment by lhtuling** [comment]
建立了一个Amis交流QQ群 感兴趣的可以加下
QQ群号：717791727

**Comment by moge10086** [comment]
> 建立了一个Amis交流QQ群 感兴趣的可以加下 QQ群号：717791727

群满人了
