### ISSUE TITLE
JSSDK模式下,InputText在移动端无边框

### ISSUE THREAD

**Issue by ray929** [baidu/amis#3669]
#### 描述问题：
JSSDK模式下,InputText在移动端无边框,PC端正常
文档中的"组件"演示并没有这个问题,"示例"演示则同样有这个问题

#### 截图或视频：
<img width="710" alt="Snipaste_2022-03-02_11-02-34" src="https://user-images.githubusercontent.com/41984067/156287769-3ac2afda-fe1e-4e7f-9bcc-5815ab1f010d.png">
<img width="317" alt="Snipaste_2022-03-02_11-02-26" src="https://user-images.githubusercontent.com/41984067/156287771-c909f55c-a661-4551-ab39-1b2f5cce5da6.png">

#### 如何复现（请务必完整填写下面内容）：
1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.6.4/1.7.0

3. 粘贴有问题的完整 `amis schema` 代码：
`{
	"status": 0,
	"data": {
		"type": "page",
		"title": "修改密码1",
		"subTitle": "请定期修改密码",
		"body": {
			"type": "form",
			"mode": "horizontal",
			"affixFooter": true,
			"api": "/system/password?act=submit",
			"rules": [{
				"rule": "!(data.pass2 != data.pass3)",
				"message": "两次输入的新密码不一致"
			}],
			"body": [{
				"type": "input-password",
				"label": "原密码",
				"name": "pass1",
				"required": true,
				"validations": {
					"minLength": 8,
					"maxLength": 64
				}
			}, {
				"type": "input-password",
				"label": "新密码",
				"name": "pass2",
				"required": true,
				"validations": {
					"minLength": 8,
					"maxLength": 64
				}
			}, {
				"type": "input-password",
				"label": "重复新密码",
				"name": "pass3",
				"required": true,
				"validations": {
					"minLength": 8,
					"maxLength": 64
				}
			}]
		}
	},
	"msg": ""
}`

4. 操作步骤
无

**Comment by nwind** [comment]
移动端定制样式，参考了 weui zend 等常见设计，可以通过 css 自行修改，或者通过 useMobileUI: false 关闭 https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/mobile

**Comment by ray929** [comment]
感谢您的回复,使用了useMobileUI: false并没有效果

分别在1.6.4/1.7.0两个版本测试
分别使用默认,antd,ang等主题下测试
分别加到全局或者某个组件下 
都没有效果

<img width="179" alt="Snipaste_2022-03-02_20-16-57" src="https://user-images.githubusercontent.com/41984067/156360365-b15d5fc2-422b-496f-906a-b91141813682.png">
<img width="307" alt="Snipaste_2022-03-02_20-17-47" src="https://user-images.githubusercontent.com/41984067/156360374-995a570d-7625-4a1f-b12e-4ad2065148fb.png">

**Comment by ray929** [comment]
使用的是aisuda/amis-admin
