### ISSUE TITLE
如何自定义一个button按钮的点击事件？

### ISSUE THREAD

**Issue by YUHUAJ** [baidu/amis#367]
我想要通过button按钮来触发我在本地的编写的事件，把事件返回的FORM表单通过弹窗dialog来显示出来，请问一下能实现吗？

**Comment by 2betop** [comment]
从你粗略的描述来分析，我估计你是要自定义个组件。看看这：https://baidu.github.io/amis/docs/dev

把事件返回的 form 表单，这个不明白什么意思。

你的需求是在  form 里面有个 按钮，点击后可以通过 dialog 形式展示这个 form 里面的所有数据？

**Comment by YUHUAJ** [comment]
我在本地写了一个onClick的点击事件，希望能通过你们的button按钮来触发这个点击事件，想法是这个事件会返回一个JSON的FORM页面参数，再通过dialog把这个FORM页面显示出来。

**Comment by 2betop** [comment]
很难理解，你说一下原始需求？为啥不直接使用 actionType: "dialog" 的按钮？

**Comment by YUHUAJ** [comment]
原始需求是，不同的table里面“新增”这个功能的form页面内容不同，因此想通过编写一个本地点击事件来传递参数，从而确定form表单的内容（该表单的json不能写死在dialog里，需求通过以变量的形式传递过来），而这个点击事件返回的form表单再通过dialog来显示。

**Comment by 2betop** [comment]
1. 如果可以枚举可以多来几个 按钮然后结合 visibleOn 来配置实现不同的行新增的表单不一样。
2. 如果不能枚举，可以让弹出来的 dialog 中的 form，放一个 service，这个 service 通过 schemaApi 去拉取不同的 controls。

**Comment by 2betop** [comment]
比如这个：https://baidu.github.io/amis/services/form

ps: 左上角可以查看源码

**Comment by YUHUAJ** [comment]
button的actionType能否扩展？我还是需要通过点击button来触发一个函数。

**Comment by 2betop** [comment]
如果你是用 js 的方式配置的 amis 的按钮，那应该可以这样 hack。

```js
{
  type: 'button',
 label: '按钮',
onClick: (e, props) => {
 // 这里执行你自己的函数。

// 完事了你想继续 amis 的事件触发就这样.
props.onAction(e, {
  actionType: 'dialog',
 dialog: {
    // 省略了
  }
})

   return false;// 后面的逻辑就不执行了。
 }
}
```

可以看看这个 https://github.com/baidu/amis/blob/master/src/renderers/Action.tsx#L95

**Comment by YUHUAJ** [comment]
好的，我测试一下，谢谢您！

**Comment by YUHUAJ** [comment]
您好，我的JSON返回接口是MOCK接口，所以我是在.tsx页面写的onClick，结果有下面的问题，请教一下要怎么解决呢？麻烦您了







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liaoxuezhi"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 晚上6:01
收件人:&nbsp;"baidu/amis"<amis@noreply.github.com&gt;;
抄送:&nbsp;"唯"<674125216@QQ.COM&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baidu/amis] 如何自定义一个button按钮的点击事件？ (#367)




如果你是用 js 的方式配置的 amis 的按钮，那应该可以这样 hack。
 {   type: 'button',  label: '按钮', onClick: (e, props) =&gt; {  // 这里执行你自己的函数。 // 完事了你想继续 amis 的事件触发就这样. props.onAction(e, {   actionType: 'dialog',  dialog: {     // 省略了   } })    return false;// 后面的逻辑就不执行了。  } }
 
可以看看这个 https://github.com/baidu/amis/blob/master/src/renderers/Action.tsx#L95

**Comment by 2betop** [comment]
看样子你不是用 js 来配置页面的。这样的，你需要自定义一个按钮。依然是要看这个：https://baidu.github.io/amis/docs/dev  最后可以通过 this.props.onAction 来派送 amis 的事件，一样可以弹出弹框。

**Comment by YUHUAJ** [comment]
![QQ图片20191210105334](https://user-images.githubusercontent.com/51392760/70499675-a2c14780-1b54-11ea-950c-10dc720c2a01.png)
![QQ图片20191210105343](https://user-images.githubusercontent.com/51392760/70499679-a5bc3800-1b54-11ea-88c5-2f9d3305717d.png)
![QQ图片20191210105351](https://user-images.githubusercontent.com/51392760/70499683-a81e9200-1b54-11ea-9c4b-a4770569c0f1.png)

**Comment by 2betop** [comment]
哦，你的图片才显示出来，之前没看到。加第三个参数试试？

props.onAction(actionType: "dialog", dialog: {}, props.data)

**Comment by YUHUAJ** [comment]
加了第三个参数后也是报这个错
![11](https://user-images.githubusercontent.com/51392760/70501010-dfdb0900-1b57-11ea-85c7-6e5caf93e11e.png)
![22](https://user-images.githubusercontent.com/51392760/70501016-e36e9000-1b57-11ea-8c3c-406c7a7fb912.png)

**Comment by 2betop** [comment]
是不是你的 crud 接口没有正常返回数据？

**Comment by YUHUAJ** [comment]
是的，是接口没数据返回的原因，非常感谢！！

**Comment by YUHUAJ** [comment]
老师，现在我是在table表里的operation操作行，想给查看这个按钮自定义一个点击事件并弹窗，这次是点击事件绑定成功，但弹窗时没有取dialog的数据，不知道问题出在哪了。
![1234](https://user-images.githubusercontent.com/51392760/70764551-d8ec0a80-1d92-11ea-8d9d-5351ad9f84a5.jpg)
![432](https://user-images.githubusercontent.com/51392760/70764556-dc7f9180-1d92-11ea-9613-84a1ef0656c8.jpg)
![76543](https://user-images.githubusercontent.com/51392760/70764558-df7a8200-1d92-11ea-8a62-bc873a468cc8.jpg)
