### ISSUE TITLE
表单项默认值设置的问题

### ISSUE THREAD

**Issue by theojia** [baidu/amis#3671]
问题描述：
Switch 开关在初始化渲染表单后，是关闭false状态，未做任何表单值变更，直接提交表单，amis不会将该switch的表单值false带入请求体

问题截图：
![amis-switch-form](https://user-images.githubusercontent.com/21030082/156306216-0f63b2ff-c4fa-460f-b84a-4b48ff1ba511.png)

麻烦老哥们帮忙确认一下这个问题~

**Comment by nwind** [comment]
默认没有值是不会提交的，如果要设置默认值，可以加上 "value": false

**Comment by theojia** [comment]
> 默认没有值是不会提交的，如果要设置默认值，可以加上 "value": false

好的，感谢😊~
