### ISSUE TITLE
action可以支持监听到双击事件吗？

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#3675]
#### 是否关联于某个问题吗：
想action组件可以监听到双击事件

#### 预期的解决方案：
1. 添加action类型，
2. 或者可以支持onDbClick，像onClick一样

#### 其他可接受方案：
可实现的方案都可以

**Comment by nwind** [comment]
等新的事件动作机制，会补充 action 的事件 https://aisuda.bce.baidu.com/amis/examples/event-action/common
