### ISSUE TITLE
新版editor变形

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#3680]
"amis": "1.7.0",
"amis-editor": "4.0.2-beta.10"
amis 版本为1.6.4，编辑器没有问题，升级版本到1.7.0后，如下图所示，出现错位走形：
![image](https://user-images.githubusercontent.com/5292190/156374474-a025fe88-f575-4f61-b8d5-8889605d8eda.png)

**Comment by nwind** [comment]
需要升级到 4.0.2-beta.12

**Comment by cmdares** [comment]
amis 1.7.0 配套editor 4.0.2-beta.12 是如下结果，继续变形
![image](https://user-images.githubusercontent.com/5292190/156496852-00cc1494-e4e0-48b9-9efd-6d6775b6b703.png)
@nwind
