### ISSUE TITLE
如何配置Table的高亮行颜色？

### ISSUE THREAD

**Issue by whuter** [baidu/amis#369]
![row-class](https://user-images.githubusercontent.com/32240639/70613536-c57e5980-1c43-11ea-969d-8da838498210.png)
参考 ElementUI 的效果，需要根据表格内某字段，在不同的取值范围内，显示不同的高亮颜色，请问是否可以实现？

**Comment by 2betop** [comment]
目前看来不支持，下个版本支持这个

**Comment by whuter** [comment]
感谢！

**Comment by 2betop** [comment]
crud 上现在可以配置

`rowClassNameExpr: '<%= data.id == 1 ? "bg-success" : "" %>',`

最新的 beta 版本支持
