### ISSUE TITLE
amis 可以配合vue typescript使用吗？有没有文档 或者 demo

### ISSUE THREAD

**Issue by westeast** [baidu/amis#370]

**Comment by FatDong1** [comment]
https://github.com/FatDong1/amis-admin/tree/vue

写了一个简单示例

**Comment by westeast** [comment]
> https://github.com/FatDong1/amis-admin/tree/vue
> 
> 写了一个简单示例 vue分支

厉害了，支持json里直接配置vue组件吗？比如 element-ui的组件
