### ISSUE TITLE
App 多页应用  schemaApi 拉取配置 如果包含Definitions引用会报错

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#3703]
如题
![image](https://user-images.githubusercontent.com/44140500/156918274-ba5f0402-b20b-4bab-991d-832c0dd30d2a.png)

**Comment by XuTuKe** [comment]
遇到相同的问题了，是否解决了？

**Comment by XuTuKe** [comment]
将definitions设置在app里可解决该问题
