### ISSUE TITLE
amis再请求json中initApi的过程中是否有接口可以再请求时加一些header?

### ISSUE THREAD

**Issue by westeast** [baidu/amis#371]

**Comment by 2betop** [comment]
api 的配置中可以配置 header, 具体看这： https://baidu.github.io/amis/docs/renderers/Types#api

**Comment by BadFishy** [comment]
> api 的配置中可以配置 header, 具体看这： https://baidu.github.io/amis/docs/renderers/Types#api

headers 头部，配置方式和 data 配置一样，下面不详讲。【如果要使用，请前往群组系统配置中，添加允许。】
我现在使用的JSSDK方法，使用headers参数没有效果，可以让JSSDK允许headers头部吗

**Comment by 2betop** [comment]
嗯，我知道了，jssdk 用法没发送，今天晚些时候更新线上那个版本。

**Comment by 2betop** [comment]
现在应该可以了
