### ISSUE TITLE
React项目中引入css相关文件报错

### ISSUE THREAD

**Issue by Tigerremy** [baidu/amis#3717]
#### 实现场景：
希望引入amis内置的css文件

#### 存在的问题：
项目运行报错Error: Cannot find module 'postcss-custom-properties'
![image](https://user-images.githubusercontent.com/29435792/157153886-c88019a5-751d-4127-8673-911d72f9573a.png)

**Comment by nwind** [comment]
是因为没装 postcss-custom-properties 吧

**Comment by Tigerremy** [comment]
> 

本地项目装了也没用，我看是amis里面postcss.config.js里面用到这个了

**Comment by ltsj404** [comment]
> > 
> 
> 本地项目装了也没用，我看是amis里面postcss.config.js里面用到这个了

请问一下这个问题中如何解决呢？
