### ISSUE TITLE
为什么在Webpack环境下报这么多错？

### ISSUE THREAD

**Issue by crissii** [baidu/amis#372]
ERROR in [at-loader] ./node_modules/amis/lib/factory.d.ts:3:26 
    TS7016: Could not find a declaration file for module 'history'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/history/index.js' implicitly has an 'any' type.
  Try `npm install @types/history` if it exists or add a new declaration (.d.ts) file containing `declare module 'history';`

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:7:23 
    TS2307: Cannot find module '../icons/close.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:8:22 
    TS2307: Cannot find module '../icons/undo.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:9:22 
    TS2307: Cannot find module '../icons/redo.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:10:23 
    TS2307: Cannot find module '../icons/enter.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:11:24 
    TS2307: Cannot find module '../icons/volume.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:12:22 
    TS2307: Cannot find module '../icons/mute.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:13:22 
    TS2307: Cannot find module '../icons/play.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:14:23 
    TS2307: Cannot find module '../icons/pause.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:15:27 
    TS2307: Cannot find module '../icons/left-arrow.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:16:28 
    TS2307: Cannot find module '../icons/right-arrow.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:17:23 
    TS2307: Cannot find module '../icons/check.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:18:22 
    TS2307: Cannot find module '../icons/plus.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:19:23 
    TS2307: Cannot find module '../icons/minus.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/icons.d.ts:20:24 
    TS2307: Cannot find module '../icons/pencil.svg'.

ERROR in [at-loader] ./node_modules/amis/lib/components/Checkboxes.d.ts:7:10 
    TS2440: Import declaration conflicts with local declaration of 'Option'.

ERROR in [at-loader] ./node_modules/amis/lib/components/ColorPicker.d.ts:7:29 
    TS7016: Could not find a declaration file for module 'react-color'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/react-color/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-color` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-color';`

ERROR in [at-loader] ./node_modules/amis/lib/components/Textarea.d.ts:1:22 
    TS7016: Could not find a declaration file for module 'react-textarea-autosize'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/react-textarea-autosize/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-textarea-autosize` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-textarea-autosize';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Cards.d.ts:5:27 
    TS7016: Could not find a declaration file for module 'sortablejs'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/sortablejs/Sortable.js' implicitly has an 'any' type.
  Try `npm install @types/sortablejs` if it exists or add a new declaration (.d.ts) file containing `declare module 'sortablejs';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Table.d.ts:5:27 
    TS7016: Could not find a declaration file for module 'sortablejs'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/sortablejs/Sortable.js' implicitly has an 'any' type.
  Try `npm install @types/sortablejs` if it exists or add a new declaration (.d.ts) file containing `declare module 'sortablejs';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/Button.d.ts:4:18 
    TS2320: Interface 'ButtonProps' cannot simultaneously extend types 'FormControlProps' and 'Button'.
  Named property 'disabled' of types 'FormControlProps' and 'Button' are not identical.

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/Button.d.ts:4:18 
    TS2320: Interface 'ButtonProps' cannot simultaneously extend types 'FormControlProps' and 'Button'.
  Named property 'size' of types 'FormControlProps' and 'Button' are not identical.

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/Date.d.ts:4:18 
    TS2430: Interface 'DateProps' incorrectly extends interface 'FormControlProps'.
  Type 'DateProps' is not assignable to type 'FormItemProps'.
    Property 'disabled' is optional in type 'DateProps' but required in type 'FormItemProps'.

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/DateRange.d.ts:5:18 
    TS2430: Interface 'DateRangeProps' incorrectly extends interface 'FormControlProps'.
  Type 'DateRangeProps' is not assignable to type 'FormItemProps'.
    Property 'disabled' is optional in type 'DateRangeProps' but required in type 'FormItemProps'.

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/Image.d.ts:3:21 
    TS7016: Could not find a declaration file for module 'react-cropper'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/react-cropper/dist/react-cropper.js' implicitly has an 'any' type.
  Try `npm install @types/react-cropper` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-cropper';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/Combo.d.ts:5:27 
    TS7016: Could not find a declaration file for module 'sortablejs'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/sortablejs/Sortable.js' implicitly has an 'any' type.
  Try `npm install @types/sortablejs` if it exists or add a new declaration (.d.ts) file containing `declare module 'sortablejs';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/Editor.d.ts:1108:48 
    TS7016: Could not find a declaration file for module 'lodash'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/Editor.d.ts:1112:51 
    TS7016: Could not find a declaration file for module 'lodash'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/DiffEditor.d.ts:1116:48 
    TS7016: Could not find a declaration file for module 'lodash'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/DiffEditor.d.ts:1120:51 
    TS7016: Could not find a declaration file for module 'lodash'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/DiffEditor.d.ts:3353:48 
    TS7016: Could not find a declaration file for module 'lodash'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/DiffEditor.d.ts:3357:51 
    TS7016: Could not find a declaration file for module 'lodash'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/HBox.d.ts:4:11 
    TS2430: Interface 'HBoxProps' incorrectly extends interface 'FormControlProps'.
  Type 'HBoxProps' is not assignable to type 'FormItemProps'.
    Types of property 'size' are incompatible.
      Type 'string' is not assignable to type '"xs" | "sm" | "md" | "lg" | "full"'.

ERROR in [at-loader] ./node_modules/amis/lib/renderers/Form/InputGroup.d.ts:3:18 
    TS2430: Interface 'InputGroupProps' incorrectly extends interface 'FormControlProps'.
  Type 'InputGroupProps' is not assignable to type 'FormItemProps'.
    Types of property 'size' are incompatible.
      Type '"normal" | "xs" | "sm"' is not assignable to type '"xs" | "sm" | "md" | "lg" | "full"'.
        Type '"normal"' is not assignable to type '"xs" | "sm" | "md" | "lg" | "full"'.

ERROR in [at-loader] ./node_modules/amis/lib/renderers/List.d.ts:5:27 
    TS7016: Could not find a declaration file for module 'sortablejs'. '/Users/criss/Desktop/projectDev/2019/axim/axim/node_modules/sortablejs/Sortable.js' implicitly has an 'any' type.
  Try `npm install @types/sortablejs` if it exists or add a new declaration (.d.ts) file containing `declare module 'sortablejs';`
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 351 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.

**Comment by 2betop** [comment]
你应该把 typescript 类型报错关了吧，或者 安装amis依赖的类型包？

**Comment by crissii** [comment]
有没有一个现成的脚手架，需要我们一步一步搭建吗？样式也弄不出来，好痛苦

**Comment by 2betop** [comment]
样式你得手动引用一下 css 文件 npm 包里面。有个脚手架但是是 fis3 的 https://github.com/fex-team/amis-admin

**Comment by crissii** [comment]
有看过，但是现在基本上都是WebPack的吧，有没有办法整一个

**Comment by Oscar-ren** [comment]
这个要自己配置，我们也是自己迁移到 webpack 的

**Comment by CareyToboo** [comment]
@crissii [rt-admin](https://github.com/CareyToboo/rt-admin) 使用webpack打包的amis，看看是否可以参考。
