### ISSUE TITLE
建议给input-text添加当输入框失去焦点时触发事件的方法

### ISSUE THREAD

**Issue by lglbeo** [baidu/amis#3723]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by lhtuling** [comment]
用js写配置文件   
```
"onChange": (nvalue, ovalue, e, store) => {
                                console.log(nvalue, ovalue, e, store);
//更新数据域信息
                                store.updateData({
                                    "BatchNo": ""
                                })
                            }
```
onblur  应该也可以用  自己同样方法测下 我没用过

**Comment by hsm-lv** [comment]
事件动作已支持：https://baidu.github.io/amis/zh-CN/docs/concepts/event-action  可以查看输入框的「事件表」
