### ISSUE TITLE
tab 在 service 下无法定位

### ISSUE THREAD

**Issue by faceair** [baidu/amis#373]
![image](https://user-images.githubusercontent.com/3659110/70716277-ff745c00-1d26-11ea-97bd-ab480f6e908a.png)

主要结构如上图，在 page.body 下有个 service，service 下有 tabs。点击 tab 后锚点能自动同步到地址栏，但刷新页面后无法定位到刚才打开的 tab。

在没加 service 时是好使的，能自动重新打开刚才的 tab。希望大佬能帮我检查一下是哪里的问题，谢谢！

**Comment by 2betop** [comment]
看不出来有什么问题，把service 的 api 放到 page 的 initApi 就好了？

**Comment by faceair** [comment]
service api 里有变量，当数据改变时用 form tagret 指向 service 刷新了，所以不能放到 page 里

**Comment by 2betop** [comment]
hash route 里面放的是什么？不是 crud 吧？

**Comment by faceair** [comment]
tab 里放的是 form 和 curd。
刚才我尝试移除了 service，并使用了 page initAPI 来初始化数据发现也还是不行。
最后定位是，如果 page 有 initAPI，那下面的 tabs 的 hash 锚点不生效，如果删掉 initAPI 就好使。

**Comment by 2betop** [comment]
我尝试复现一下

**Comment by 2betop** [comment]
这的问题，你 copy normalizeLink 的时候处理一下试试。https://github.com/baidu/amis/commit/4a0d1a26ee428af8f034dfc16b5f6c03990f7742

**Comment by faceair** [comment]
浏览器重载页面的时候没有触发 updateLocation，跟 url 里的 hash 处理没关系。
不好意思我最后确认原因是我给 tab 加了 visibleOn，可能是 page initApi 刷新数据导致这个 tab 的初始状态不太明确。

**Comment by faceair** [comment]
😂可能是我的用法有点复杂了，这种用法能从框架上兼容不？

**Comment by faceair** [comment]
另外 embed.jsx 跟 SchemaRender.jsx 里 normalizeLink 的实现没有统一，应该也有必要共用一下函数？

**Comment by 2betop** [comment]
> 可能是我的用法有点复杂了，这种用法能从框架上兼容不？

我这边来处理一下，就是一开始不可见，然后 page 的 api 回来可见了，但是 hash 没起作用是吧。

**Comment by faceair** [comment]
是的，是这么个情况
