### ISSUE TITLE
水平模式下的表单项配置问题

### ISSUE THREAD

**Issue by theojia** [baidu/amis#3735]
![image](https://user-images.githubusercontent.com/21030082/157575971-fe3be3c1-990d-4405-b4df-149e4edc534c.png)
当前水平模式下的表单项如果配置了比较长label，会有这样的遮挡问题存在
<br/><br/>

这里有两个配置想法：
1、如下图这样，做溢出处理并提供相应的title提示
![image](https://user-images.githubusercontent.com/21030082/157575065-71d6ea66-af62-466a-90a9-1f960680cf08.png)
<br/><br/>

2、如下图这样，超长的文本做换行处理
![image](https://user-images.githubusercontent.com/21030082/157577944-b5479b66-ba46-4d40-8d79-b29833b56b05.png)
<br/><br/>

另外这两种都需要注意label后的帮助提示图标不能被挤到下一行。
<br/><br/>

请老哥们确认一下，万分感谢~

**Comment by allenve** [comment]
<img width="1011" alt="image" src="https://github.com/baidu/amis/assets/21256044/335bb679-1a20-4924-85cc-76cb8b7150f9">
