### ISSUE TITLE
js sdk updateLocation 能否默认使用 history.pushState 方式？

### ISSUE THREAD

**Issue by faceair** [baidu/amis#374]
curd 一改筛选条件整个页面就都刷新了，视觉效果不太好...
或者我本来可以自己覆写 updateLocation 的，但 normalizeLink 方法没有暴露出来，自己抄一遍的话又很臃肿，有更优雅的解决办法吗？

**Comment by 2betop** [comment]
没有更好的了，normalize copy 出去吧。

**Comment by faceair** [comment]
😂好的，谢谢
