### ISSUE TITLE
sdk模式下 请求后端接口如果鉴权失败如何重定向到登录页面

### ISSUE THREAD

**Issue by lchg** [baidu/amis#3754]
#### 实现场景：
用户登录管理后台后，jwt_token鉴权失败，需要重定向到登录页面让用户登录 

#### 存在的问题：
sdk的模式 接口返回  http code=200  返回数据 {"message":"bad","status":302,"url":"/login.html"}
参考了这个问题 https://github.com/baidu/amis/issues/357 但是并没有生效

#### 当前方案：
没有解决
```
code here...
```

**Comment by metooweb** [comment]
在 responseAdaptor中 处理

**Comment by lchg** [comment]
3Q,已解决，如下代码 实现接口返回302重定向到登录页面            
responseAdaptor: (api, response, query, request) =>{
                 console.log(api);
                 console.log(response)
                 if (response.hasOwnProperty("status")){
                   console.log(response["status"])
                   if (response["status"] == 302){
                     if (response.hasOwnProperty("url")) {
                       location.href = response["url"];
                     }
                   }
                 }
                 return response;
               },

**Comment by lchg** [comment]
通过responseAdaptor 实现
