### ISSUE TITLE
input-tree这个组件 选中子节点时，怎么同时包含半选的父级节点值？

### ISSUE THREAD

**Issue by zp1230323** [baidu/amis#3756]
![image](https://user-images.githubusercontent.com/37198452/158129796-f755327b-3429-4f89-9199-0e7cc004df5f.png)

**Comment by lurunze1226** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-tree#%E9%80%89%E4%B8%AD%E7%88%B6%E8%8A%82%E7%82%B9%E8%87%AA%E5%8A%A8%E9%80%89%E4%B8%AD%E5%AD%90%E8%8A%82%E7%82%B9-%E6%95%B0%E6%8D%AE%E6%98%AF%E5%90%A6%E5%8C%85%E5%90%AB%E7%88%B6%E5%AD%90%E8%8A%82%E7%82%B9%E7%9A%84%E5%80%BC
