### ISSUE TITLE
希望多文件上传提供刷新curd控件的方法

### ISSUE THREAD

**Issue by xedcoing** [baidu/amis#3763]
#### 是否关联于某个问题吗：
如何实现多文件上传展示文件列表

#### 预期的解决方案：
提供刷新curd控件的方法， 或者 多文件能够数据初始化，打开界面能展示已上传的文件

#### 任何附加信息：

**Comment by lurunze1226** [comment]
[input-file](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-file#%E4%BA%8B%E4%BB%B6%E8%A1%A8) 监听到 `input-file`的`change`事件后触发CURD的reload动作
