### ISSUE TITLE
amis自定义组件 移动端显示时 类型错误

### ISSUE THREAD

**Issue by crizydevl** [baidu/amis#3767]
#### 描述问题：

amis自定义组件 移动端显示时 类型错误

#### 截图或视频：
![1647332019(1)](https://user-images.githubusercontent.com/43633044/158334257-4f51889e-3c1d-4a59-b706-c4b317fd467e.png)

#### 如何复现（请务必完整填写下面内容）：

有大佬知道这个怎么解决吗

**Comment by nwind** [comment]
因为移动端那个 html 里没引入这个自定义组件

**Comment by crizydevl** [comment]
感谢 已解决

**Comment by hcf1997** [comment]
@crizydevl 方便说下在那个文件里添加吗

**Comment by crizydevl** [comment]
![1650533782(1)](https://user-images.githubusercontent.com/43633044/164426686-76d8cb49-c03d-4a16-8008-87d4cf22e282.png)
我在这里面添加的

**Comment by crizydevl** [comment]
![1650533782(1)](https://user-images.githubusercontent.com/43633044/164427207-49a6e579-63cd-4852-be05-774407abd063.png)

**Comment by hcf1997** [comment]
@crizydevl 感谢大佬！还想问下，大佬有用FormItem这种方式创建自定义组件吗

**Comment by hcf1997** [comment]
@crizydevl 

![8891650588155_ pic](https://user-images.githubusercontent.com/86106459/164574779-8413f35d-0aae-4c5b-9a00-661a1634de53.jpg)

**Comment by crizydevl** [comment]
有用啊

**Comment by hcf1997** [comment]
@crizydevl 方便给我说一下吗。 我按照editor-demo readme里面的方法可以实现注册。但是上面说的这种不太清楚。要怎么搞了

**Comment by crizydevl** [comment]
就按文档上的来就行 不行就看看源码
