### ISSUE TITLE
InputRichText 粘贴word table无边框

### ISSUE THREAD

**Issue by 0undefined0** [baidu/amis#3772]
#### 描述问题：

富文本编辑器 粘贴 word table无边框

#### 截图或视频：

![Uploading image.png…]()

#### 如何复现（请务必完整填写下面内容）：
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-rich-text#tinymce-%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE
或
https://aisuda.bce.baidu.com/amis/examples/form/rich-text
粘贴word中的table即可复现

**Comment by nwind** [comment]
这功能在 tinymce 里是收费的，我们没法提供，目前 3 个办法：

1. 自己买 tinymce 的[powerpaste 功能](https://www.tiny.cloud/docs/plugins/premium/powerpaste/)，然后 fork amis 修改一下开启这个插件。
2. 使用 froala，这也是收费的。
3. 通过 options 里的 content_css 设置项，自己给 .mce-item-table 加样式。
