### ISSUE TITLE
amis-editor 使用 WebSocket 来实时获取数据，函数wsFetcher JSON.parse 报错

### ISSUE THREAD

**Issue by rencoo** [baidu/amis#3781]
#### 描述问题：

amis-editor 编辑器使用 WebSocket 来实时获取数据，factory.tsx 中函数wsFetcher JSON.parse 报错

#### 截图或视频：
![截屏2022-03-16 上午11 57 49](https://user-images.githubusercontent.com/39717611/158542979-fa389a52-0e10-4489-aae4-798076c61674.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
amis-editor Editor模块报错

4. 操作步骤
服务端 WebSocket 返回不可 JSON.parse 的字符串，amis-editor 编辑器接收到之后，factory.tsx 中函数 wsFetcher JSON.parse 报错希望 Editor 能提供重写wsFetcher的能力，或者支持下 WebSocket 返回非对象字符串的场景

**Comment by nwind** [comment]
这里如果非 json 的话后面更新数据也不知道怎么更新了呢

**Comment by rencoo** [comment]
```javascript
let response = null;
try {
  response = JSON.parse(event.data); // websocket返回对象时
  onMessage({ ...response });
} catch(e) {
  onMessage({ stream: response }); // websocket返回非对象时，可以定义个字段来存储响应字符串即可
}
```
这是个挺常见的需求，还是希望能支持下

**Comment by rencoo** [comment]
```javascript
let response = null;
try {
  response = JSON.parse(event.data); // websocket返回对象字符串时
  onMessage({ ...response });
} catch(e) {
  response = event.data; // websocket返回非对象字符串时
  onMessage({ stream: response }); // 可以将结果字符串放在一个约定的字段上
}
```

这个需求还是挺常见的，服务端倾向于直接推流，而不是通过对象把流包一层；
希望还是能支持下这个需求，同时把JSON.parse报错问题兼容了~

**Comment by rencoo** [comment]
```javascript
"ws": {
    "url": "ws://localhost:8777?name=${name}",
    "data": {
      "name": "${name}"
    },
    // ...
    "receiveKey": "stream" // 可以将接收响应非对象字符串的字段进行配置，这样使用 onMessage({ [ws.receiveKey]: response })
}
```
