### ISSUE TITLE
 "amis": "^1.7.0",amis使用的这个版本，启动项目报错。

### ISSUE THREAD

**Issue by sHeep1on** [baidu/amis#3784]
ERROR in ./node_modules/amis/node_modules/monaco-editor/esm/vs/language/typescript/tsMode.js 686:30
Module parse failed: Unexpected token (686:30)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       }
|       const tags = [];
>       if (entry.kindModifiers?.indexOf("deprecated") !== -1) {
|         tags.push(monaco_editor_core_exports.languages.CompletionItemTag.Deprecated);
|       }

**Comment by nwind** [comment]
更新 typescript
