### ISSUE TITLE
如何实现全局拦截器呢？

### ISSUE THREAD

**Issue by runc** [baidu/amis#38]
如果要增加权限控制，如何添加基于axios/api的全局拦截器，跳转到无权限页面呢？

**Comment by Soar360** [comment]
如果服务端更新权限，接口会返回403错误码或其他形式，此时就需要提示用户进行重新登录之类的操作。所以，拦截，或者说过滤器是很必要的。

**Comment by 2betop** [comment]
所有的请求都走 fetcher , fetcher 里面加个 then 用来做拦截就行。

**Comment by Songziyuan** [comment]
> 所有的请求都走 fetcher , fetcher 里面加个 then 用来做拦截就行。

你好，是在App.tsx里添加then么？
如果不是的话，能否告知是在哪里添加呢？或者有没有一个demo可以参考，amis-admin这个demo里，没有找到类似的写法

**Comment by 2betop** [comment]
在这 补个 then 就可以了 https://github.com/fex-team/amis-admin/blob/master/App.tsx#L44

**Comment by Songziyuan** [comment]
> 在这 补个 then 就可以了 https://github.com/fex-team/amis-admin/blob/master/App.tsx#L44

成功了，感谢你！
![image](https://user-images.githubusercontent.com/15028748/63835519-35751680-c9aa-11e9-915e-ff2cd8cfaff9.png)

**Comment by renpengben** [comment]
jssdk 怎么实现啊？

**Comment by ZainCheung** [comment]
> jssdk 怎么实现啊？

同问

**Comment by qiu-1231** [comment]
jssdk 怎么实现啊？

有结果了吗，同问

**Comment by YiRan96** [comment]
> jssdk 怎么实现啊？
> 
> 有结果了吗，同问

可以自己实现fetcher，然后在fetch返回里面做处理吧。
// amis envConfig
const envConfig = {
  fetcher: async (config) => {
    const token = getToken()
    if (token) {
      config.headers = {
        ...config.headers,
        authorization: token,
      }
    }

    if (config.method.toLocaleLowerCase() === 'get') {
      delete config.body
    }
    // 兼容 amis 接口配置的缓存
    if (config.cache) {
      config.headers['Cache-Control'] = `max-age=${config.cache}`
      delete config.cache
    }
    const response = await fetch(config.url, config)
    const { url, status, statusText } = response

    if (response.status >= 200 && response.status < 300) {
      const data = await response.json()
      return { data }
    }
    if (status === 401) {
     const token =  await _fetchToken()
      config.headers = {
        ...config.headers,
        authorization: getToken()
      }
      // 重新发起请求
      const res = await fetch(config.url, config)
      const data = await res.json()
      return { data }
    }

    return {
      data: {
        status: -1,
        msg: statusText || '服务器错误!',
        statusCode: status,
        statusText
      }
    }
  }
}
