### ISSUE TITLE
想要给表单确定按钮绑定一个自定义点击方法

### ISSUE THREAD

**Issue by x1194785386** [baidu/amis#380]
![删除1](https://user-images.githubusercontent.com/51640396/70961088-cf78e000-20bb-11ea-9499-c86375efb71f.jpg)
![删除2](https://user-images.githubusercontent.com/51640396/70961091-d273d080-20bb-11ea-8213-9ddda3b50459.jpg)
![新增](https://user-images.githubusercontent.com/51640396/70961138-eb7c8180-20bb-11ea-9614-daf397378018.jpg)

**Comment by 2betop** [comment]
点击后做什么操作？好奇，截图貌似还是老版本。

**Comment by x1194785386** [comment]
是想让确定按钮去执行一个自己的后端接口调用方法

**Comment by 2betop** [comment]
actionType 配置成 'ajax', 然后配置 api 属性就够了。这里面有很多种按钮类型。

https://baidu.github.io/amis/docs/renderers/Action

**Comment by x1194785386** [comment]
是这样的，我是有一套后端接口调用函数，是想用这个确认按钮去调用。

**Comment by 2betop** [comment]
确认按钮就是配置个 actionType 为 'ajax' 类型的按钮，然后配置 api, 再配置个  confirmText 就完了。

点击的时候自动会弹出个确认框，确认完了就会走 ajax 操作。

**Comment by 2betop** [comment]
跟这个栗子的用法时一样的。https://baidu.github.io/amis/crud/table?page=1

ps：左上角可以查看源码。

**Comment by x1194785386** [comment]
那是没办法，给确认按钮配置可以去调用函数吗？

**Comment by x1194785386** [comment]
作者大大这个我是知道的，只不过需求是要用确认按钮去调用函数。

**Comment by 2betop** [comment]
调用后端的函数都是走 api，你的意思是前端的函数？

**Comment by x1194785386** [comment]
是的前端函数

**Comment by 2betop** [comment]
如果你是用  js 来配置 amis，可以这么弄。

```js
{
   type: "button"
   label: "删除",
  actionType: "dialog",
  dialog: {
      title: "系统消息",
      body: "确认要删除？",
      actions: [
          {
             type: "button",
             label: "确认",
             actionType: "close"
             onClick: () => {
                   alert('clicked');
                   // return false 可以阻止 amis 里面后续的动作。
             }
          },
          {
              label: "取消",
              type: "button",
              actionType: "close"
          }
      ]
  }
}
```

**Comment by x1194785386** [comment]
作者大大，我在onClik写了一个函数，它并不加载该函数，甚至actionType以下都不执行。

![代码1](https://user-images.githubusercontent.com/51640396/70975200-68bbec80-20e4-11ea-941a-a41a029122de.jpg)



![弹框1](https://user-images.githubusercontent.com/51640396/70975182-6063b180-20e4-11ea-9c5e-f53760d8e427.jpg)

**Comment by 2betop** [comment]
最外层的 onClick 进去没？

**Comment by x1194785386** [comment]
在props.onAction前面的都执行了

---原始邮件---
发件人: "liaoxuezhi"<notifications@github.com&gt;
发送时间: 2019年12月17日(周二) 下午5:28
收件人: "baidu/amis"<amis@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"x1194785386"<1935775132@qq.com&gt;;
主题: Re: [baidu/amis] 想要给表单确定按钮绑定一个自定义点击方法 (#380)



最外层的 onClick 进去没？

**Comment by 2betop** [comment]
那就没问题了，你下面一看就好乱，自己先理一理。

1. 不知道你 viewJson 是啥
2. 用了 map，但是 方法没有返回。
3. actionName 是啥？

**Comment by 2betop** [comment]
看这像是进入了第二个分支。你看看 第二个 onAction 那块

**Comment by x1194785386** [comment]
好的我先理理



---原始邮件---
发件人: "liaoxuezhi"<notifications@github.com&gt;
发送时间: 2019年12月17日(周二) 下午5:47
收件人: "baidu/amis"<amis@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"x1194785386"<1935775132@qq.com&gt;;
主题: Re: [baidu/amis] 想要给表单确定按钮绑定一个自定义点击方法 (#380)



那就没问题了，你下面一看就好乱，自己先理一理。
  
不知道你 viewJson 是啥 

用了 map，但是 方法没有返回。 

actionName 是啥？

**Comment by x1194785386** [comment]
作者大大我这边代码少了一层return false;，已经解决了，麻烦您了。
