### ISSUE TITLE
service嵌套了一层 service-body, 导致高度传不到子组件

### ISSUE THREAD

**Issue by agileago** [baidu/amis#3807]
#### 描述问题：

<img width="818" alt="image" src="https://user-images.githubusercontent.com/11799110/158930062-1e53a8c0-1fff-4ab2-adc7-e0e5470f5948.png">

想设置子组件的高度充满，但是service这一层有个 `service-body` 挡着，无法传递高度

**Comment by nwind** [comment]
可以再加 css 解决，不过这个层级是没啥用，去掉了 #3818
