### ISSUE TITLE
获取echart实例

### ISSUE THREAD

**Issue by agileago** [baidu/amis#3808]
https://github.com/baidu/amis/blob/305c22e91ca1755ca76e09d565e1c564a95c198e/src/renderers/Chart.tsx#L281

这里是不是写错了

**Comment by nwind** [comment]
没有，第一个是 echart 实例，第二个是 echarts 模块，看后面那一行

**Comment by agileago** [comment]
但函数体呢？ 应该是 下面这样才对吧

```typescript
onChartMount = new Function('chart', 'echarts', onChartMount) as any; 
```

**Comment by cainiaokan** [comment]
这个问题都两年多了还没解决。。。函数体都没有啊
