### ISSUE TITLE
Markdown渲染加载外部文件会导致API请求无限次循环

### ISSUE THREAD

**Issue by charescape** [baidu/amis#3814]
出问题的代码看起来是在 `componentDidUpdate` 这个 hook 里：

https://github.com/baidu/amis/blob/d961b42753f3a860ba33003f218b7efc80b684c0/src/renderers/Markdown.tsx#L65-L75

逻辑错误：

https://github.com/baidu/amis/blob/d961b42753f3a860ba33003f218b7efc80b684c0/src/renderers/Markdown.tsx#L71-L73

**Comment by charescape** [comment]
markdown 内容肯定不会变化

**Comment by charescape** [comment]
应该是 `this.updateContent()`  导致 `componentDidUpdate` 反复被触发

**Comment by nwind** [comment]
没复现，给个例子吧，官网看也是正常的 https://aisuda.bce.baidu.com/amis/zh-CN/components/markdown#%E5%8A%A0%E8%BD%BD%E5%A4%96%E9%83%A8-markdown-%E6%96%87%E4%BB%B6

**Comment by charescape** [comment]
@nwind 我这里可以复现，这个是录屏

![bug](https://user-images.githubusercontent.com/53265646/159660277-7c49024f-bc99-4a39-b0b1-354dd05be53e.gif)

**Comment by charescape** [comment]
@nwind 配置如下：

```jsx
{
      type: 'app',
      brandName: '后台管理系统',
      pages: [
        {
          label: '其他',
          children: [
            {
              icon: 'fas fa-code-branch',
              label: '版本更新',
              url: '/changelog',
              schema: {
                type: 'page',
                "body": {
                  "type": "markdown",
                  "src": "https://cdn.jsdelivr.net/gh/facebook/react@master/CHANGELOG.md",
                },
              }
            },
          ]
        },
      ]
    }
```

**Comment by charescape** [comment]
@nwind 官网可以复现这个BUG，

[https://aisuda.bce.baidu.com/amis/zh-CN/components/markdown#加载外部-markdown-文件](https://aisuda.bce.baidu.com/amis/zh-CN/components/markdown#加载外部-markdown-文件)

![bug2](https://user-images.githubusercontent.com/53265646/160285560-c5617c9f-717b-4d78-8a26-63bcd0ca044a.gif)
