### ISSUE TITLE
input-text，用户完成输入，向后端发起请求保存数据

### ISSUE THREAD

**Issue by lhxidian** [baidu/amis#3820]
#### 实现场景：
input-text，用户完成输入，向后端发起请求保存数据

#### 存在的问题：
"type": "input-text",
"name": "requirementCode",
"label": "需求编码",
onChange: value => {
    console.log(value);
}
现在的问题一有修改就出发事件。
如果用户修改完成再出发修改事件。

#### 当前方案：
无

**Comment by nwind** [comment]
试试 onBlur
