### ISSUE TITLE
amis的input-tree如何获取树节点的点击事件？

### ISSUE THREAD

**Issue by liaotianfeng** [baidu/amis#3823]
renderAmis({
            type: 'input-tree',
            name: 'tree',
            showOutline: true,
            treeContainerClassName: style.treeStyle,
            options: treeData,  
})

**Comment by hsm-lv** [comment]
可以看下事件动作章节，结合该组件的事件表 https://baidu.github.io/amis/zh-CN/components/form/input-tree#%E4%BA%8B%E4%BB%B6%E8%A1%A8
