### ISSUE TITLE
crud导出excel的时候，时间戳格式的日期列不能正确导出

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#3826]
#### 描述问题：

crud导出excel的时候，时间戳格式的日期列不能正确导出，会忽略format的配置，直接导出数字
现在只能配置成tpl类型的列

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis@1.8.0-beta.5

**Comment by Heming9** [comment]
请问解决了吗，最新版datetime类型导出 还是原来值的格式
