### ISSUE TITLE
新增tag组件

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#3828]
![image](https://user-images.githubusercontent.com/5292190/159620375-d48ca101-3de4-4f9f-b433-b65dff7d00dc.png)
新增tag组件，类似elementui的tag功能

**Comment by nwind** [comment]
因为比较简单，所以直接做在 mapping 例子里了，后续多补点例子方便知道，另外就是 tag 这个 type 之前被 form 里用了，加了可能会有兼容性问题

**Comment by cmdares** [comment]
收到。
