### ISSUE TITLE
导航条组件变形

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#3829]
amis 顶部导航效果
{
  "type": "page",
  "body": {
    "type": "nav",
    "stacked": false,
    "className": "w-md",
    "links": [
      {
        "label": "Nav 1",
        "to": "/docs/index",
        "icon": "fa fa-user",
        "active": true
      },
      {
        "label": "Nav 2",
        "unfolded": true,
        "children": [
          {
            "label": "Nav 2-1",
            "children": [
              {
                "label": "Nav 2-1-1",
                "to": "/docs/api-2-1-1"
              }
            ]
          },
          {
            "label": "Nav 2-2",
            "to": "/docs/api-2-2"
          }
        ]
      },
      {
        "label": "Nav 3",
        "to": "/docs/renderers"
      }
    ]
  }
}

![image](https://user-images.githubusercontent.com/5292190/159621595-2da2021a-a9fa-4b8d-8f99-3b2563763f5d.png)

element顶部导航效果
![image](https://user-images.githubusercontent.com/5292190/159621254-790cfee9-a5a6-4c44-ac4d-2b34a46993e3.png)

对比一下

**Comment by allenve** [comment]
用最新版再试试
