### ISSUE TITLE
1.6.4版本之后动态组件页面间broadcast广播失效

### ISSUE THREAD

**Issue by CKask** [baidu/amis#3862]
#### 描述问题：

1.6.4版本下，使用Service 功能型容器schemaApi加载动态页面之间使用broadcast正常使用，但是升级到1.7.0之后版本，这种使用方式全部失效

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm react

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
现在使用1.6.4 最新版本任然存在
3. 粘贴有问题的完整 `amis schema` 代码：
```
接收组件
 "onEvent": {
    "product_broadcast": {
      "actions": [
        {
          "actionType": "reload",
          "args": {
            "product_name": "${event.data.product_name}",
            "product_uuid": "${event.data.product_uuid}"
          }
        }
      ]
    }
  },

发送组件：
 "onEvent": {
                "click": {
                  "actions": [
                    {
                      "actionType": "broadcast",
                      "eventName": "product_broadcast",
                      "args": { "product_name": "${product_name}" }
                    },
                    { "actionType": "close" }
                  ]
                }
              },
```

4. 操作步骤
使用1.6.4版本正常 升级到1.7.0之后不起作用

**Comment by hsm-lv** [comment]
> #### 描述问题：
> 1.6.4版本下，使用Service 功能型容器schemaApi加载动态页面之间使用broadcast正常使用，但是升级到1.7.0之后版本，这种使用方式全部失效
> 
> #### 如何复现（请务必完整填写下面内容）：
> 1. 你是如何使用 amis 的？
>    npm react
> 2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
>    现在使用1.6.4 最新版本任然存在
> 3. 粘贴有问题的完整 `amis schema` 代码：
> 
> ```
> 接收组件
>  "onEvent": {
>     "product_broadcast": {
>       "actions": [
>         {
>           "actionType": "reload",
>           "args": {
>             "product_name": "${event.data.product_name}",
>             "product_uuid": "${event.data.product_uuid}"
>           }
>         }
>       ]
>     }
>   },
> 
> 发送组件：
>  "onEvent": {
>                 "click": {
>                   "actions": [
>                     {
>                       "actionType": "broadcast",
>                       "eventName": "product_broadcast",
>                       "args": { "product_name": "${product_name}" }
>                     },
>                     { "actionType": "close" }
>                   ]
>                 }
>               },
> ```
> 
> 4. 操作步骤
>    使用1.6.4版本正常 升级到1.7.0之后不起作用

看你发出来的配置没有什么问题，需要具体看下完整的schema

**Comment by CKask** [comment]
经测试 升级到1.8.0后正常使用了
