### ISSUE TITLE
NestedSelect 级联选择器 change 事件无效  无法触发

### ISSUE THREAD

**Issue by cxkking** [baidu/amis#3882]
$format = [
                    'type'=> $amis[$value['type']],
                    'label'=> $value['title'],
                    'name'=> $value['field'],
                    'onlyChildren'=> true,
                    'multiple'=> false,
                    'visible'=> $value['hidden'] ? false : true,
                    'required'=> $value['required'] ? true : false,
                    'selectFirst'=> $value['first'] ? true : false,
                    'onEvent'=> [
                        "change" => [
                            "actions" =>[
                                [
                                    "actionType" =>"broadcast",
                                    "eventName" =>"broadcast_1",
                                    "args" => [
                                        "myrole" =>'${' . $value['field'] . '}',
                                        "age" =>18
                                    ]
                                ],
                                [
                                    "actionType" =>"ajax",
                                    "api" => url("source/source/Typeinfo", ['uniacid'=>$uniacid, 'id'=>13]),
                                    "messages" => [
                                        "success" =>"成功了！欧耶",
                                        "failed" =>"失败了呢。。"
                                    ]
                                ],
                                [
                                    "actionType" =>"toast",
                                    "msgType" =>"info",
                                    "msg" =>"派发点击事件1"
                                ],
                            ]
                        ],
                        'blur'=> [
                            'actions'=> [
                                [
                                    "actionType" =>"ajax",
                                    "api" => url("source/source/Typeinfo", ['uniacid'=>$uniacid, 'id'=>13]),
                                    "messages" => [
                                        "success" =>"成功了！欧耶",
                                        "failed" =>"失败了呢。。"
                                    ]
                                ],
                                [
                                    'actionType'=> 'broadcast',
                                    'eventName'=> 'broadcast1',
                                    'args'=> [
                                        'y3349119197064'=> '55',
                                    ]
                                ],
                                [
                                    "actionType" =>"toast",
                                    "msgType" =>"info",
                                    "msg" =>"派发点击事件2"
                                ],
                            ]
                        ]
                    ],
                ];

获得焦点 失去焦点事件都正常，修改事件无法触发

**Comment by cxkking** [comment]
新发现 Edge 在PC端是可以触发change事件的，移动端无法触发  chrome 均无效

**Comment by nwind** [comment]
这是 php？发个最终的 json 示例吧

**Comment by cxkking** [comment]
> 这是 php？发个最终的 json 示例吧

{
    "type": "page",
    "title": "巡检上传",
    "body": {
        "type": "form",
        "title": "",
        "submitText": "提交",
        "redirect": "./index.php?c=user&a=approve&do=launchlist&uniacid=52",
        "resetAfterSubmit": true,
        "api": "./index.php?c=form&a=form&do=submit&uniacid=52",
        "data": [],
        "body": [
            {
                "type": "nested-select",
                "label": "巡检问题类型",
                "name": "y5884719648547",
                "onlyChildren": true,
                "multiple": false,
                "visible": true,
                "required": true,
                "selectFirst": false,
                "onEvent": {
                    "change": {
                        "actions": [
                            {
                                "actionType": "ajax",
                                "api": "./index.php?c=source&a=source&do=Dedu&uniacid=52&id=${value}",
                                "outputVar": "y3349119197064",
                                "messages": {
                                    "success": "数据更新成功！",
                                    "failed": "接口数据异常！"
                                }
                            },
                            {
                                "actionType": "broadcast",
                                "eventName": "y3349119197064",
                                "args": {
                                    "y3349119197064": "${event.data.y3349119197064}"
                                }
                            },
                            {
                                "actionType": "ajax",
                                "api": "./index.php?c=source&a=source&do=Timelimit&uniacid=52&id=${value}",
                                "outputVar": "y9453419207129",
                                "messages": {
                                    "success": "数据更新成功！",
                                    "failed": "接口数据异常！"
                                }
                            },
                            {
                                "actionType": "broadcast",
                                "eventName": "y9453419207129",
                                "args": {
                                    "y9453419207129": "${event.data.y9453419207129}"
                                }
                            }
                        ]
                    }
                },
                "source": "./index.php?c=source&a=source&do=ProblemType&uniacid=52"
            },
            {
                "type": "input-text",
                "label": "扣分",
                "placeholder": "请填写扣分",
                "name": "y3349119197064",
                "visible": true,
                "required": false,
                "ak": "zhDkGQmwyyoZI6G4gBpiCG5twLDXhHZx",
                "coordinatesType": "gcj02"
            },
            {
                "type": "input-text",
                "label": "整改时限",
                "placeholder": "请填写整改时限",
                "name": "y9453419207129",
                "visible": true,
                "required": false,
                "ak": "zhDkGQmwyyoZI6G4gBpiCG5twLDXhHZx",
                "coordinatesType": "gcj02"
            },
            {
                "type": "textarea",
                "label": "备注",
                "placeholder": "请填写备注",
                "name": "y3325819239577",
                "visible": true,
                "required": true,
                "ak": "zhDkGQmwyyoZI6G4gBpiCG5twLDXhHZx",
                "coordinatesType": "gcj02"
            },
            {
                "type": "hidden",
                "name": "y2422544427397",
                "value": 1
            },
            {
                "type": "hidden",
                "name": "workflow",
                "value": "3"
            },
            {
                "type": "hidden",
                "name": "lng",
                "value": 114.345762
            },
            {
                "type": "hidden",
                "name": "lat",
                "value": 30.592754
            },
            {
                "type": "hidden",
                "name": "street_number",
                "value": "友谊大道537号"
            }
        ],
        "onEvent": {
            "y3349119197064": {
                "actions": {
                    "actionType": "reload",
                    "args": {
                        "y3349119197064": "${event.data.y3349119197064.result}"
                    }
                }
            },
            "y9453419207129": {
                "actions": {
                    "actionType": "reload",
                    "args": {
                        "y9453419207129": "${event.data.y9453419207129.result}"
                    }
                }
            }
        }
    }
}

**Comment by hsm-lv** [comment]
> > 这是 php？发个最终的 json 示例吧
> 
> { "type": "page", "title": "巡检上传", "body": { "type": "form", "title": "", "submitText": "提交", "redirect": "./index.php?c=user&a=approve&do=launchlist&uniacid=52", "resetAfterSubmit": true, "api": "./index.php?c=form&a=form&do=submit&uniacid=52", "data": [], "body": [ { "type": "nested-select", "label": "巡检问题类型", "name": "y5884719648547", "onlyChildren": true, "multiple": false, "visible": true, "required": true, "selectFirst": false, "onEvent": { "change": { "actions": [ { "actionType": "ajax", "api": "./index.php?c=source&a=source&do=Dedu&uniacid=52&id=${value}", "outputVar": "y3349119197064", "messages": { "success": "数据更新成功！", "failed": "接口数据异常！" } }, { "actionType": "broadcast", "eventName": "y3349119197064", "args": { "y3349119197064": "${event.data.y3349119197064}" } }, { "actionType": "ajax", "api": "./index.php?c=source&a=source&do=Timelimit&uniacid=52&id=${value}", "outputVar": "y9453419207129", "messages": { "success": "数据更新成功！", "failed": "接口数据异常！" } }, { "actionType": "broadcast", "eventName": "y9453419207129", "args": { "y9453419207129": "${event.data.y9453419207129}" } } ] } }, "source": "./index.php?c=source&a=source&do=ProblemType&uniacid=52" }, { "type": "input-text", "label": "扣分", "placeholder": "请填写扣分", "name": "y3349119197064", "visible": true, "required": false, "ak": "zhDkGQmwyyoZI6G4gBpiCG5twLDXhHZx", "coordinatesType": "gcj02" }, { "type": "input-text", "label": "整改时限", "placeholder": "请填写整改时限", "name": "y9453419207129", "visible": true, "required": false, "ak": "zhDkGQmwyyoZI6G4gBpiCG5twLDXhHZx", "coordinatesType": "gcj02" }, { "type": "textarea", "label": "备注", "placeholder": "请填写备注", "name": "y3325819239577", "visible": true, "required": true, "ak": "zhDkGQmwyyoZI6G4gBpiCG5twLDXhHZx", "coordinatesType": "gcj02" }, { "type": "hidden", "name": "y2422544427397", "value": 1 }, { "type": "hidden", "name": "workflow", "value": "3" }, { "type": "hidden", "name": "lng", "value": 114.345762 }, { "type": "hidden", "name": "lat", "value": 30.592754 }, { "type": "hidden", "name": "street_number", "value": "友谊大道537号" } ], "onEvent": { "y3349119197064": { "actions": { "actionType": "reload", "args": { "y3349119197064": "${event.data.y3349119197064.result}" } } }, "y9453419207129": { "actions": { "actionType": "reload", "args": { "y9453419207129": "${event.data.y9453419207129.result}" } } } } } }

不好意思😁， 移动端遗漏掉了，马上补上
