### ISSUE TITLE
tab工具栏 按钮位置设置

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#3888]
如何调整样式功能，支持按钮出现再tab工具栏右侧：
![image](https://user-images.githubusercontent.com/5292190/160568016-aa19de59-faff-4ca9-a54e-f1af80bb343b.png)
当前配置：
{
  "type": "page",
  "body": [
    {
      "type": "tabs",
      "toolbar": [
        {
          "type": "button",
          "label": "按钮1",
          "size": "sm",
          "actionType": "dialog",
          "dialog": {
            "title": "弹窗标题",
            "body": "你点击了"
          },
          "className": "m-l-xs m-r-xs"
        },
        {
          "type": "button",
          "label": "按钮2",
          "size": "sm",
          "actionType": "dialog",
          "dialog": {
            "title": "弹窗标题",
            "body": "你点击了"
          },
          "className": "m-l-xs m-r-xs"
        }
      ],
      "tabs": [
        {
          "title": "Tab 1",
          "tab": "Content 1"
        },
        {
          "title": "Tab 2",
          "tab": "Content 2"
        }
      ]
    }
  ]
}

![image](https://user-images.githubusercontent.com/5292190/160568657-7b347a94-19b2-44b4-9b18-4e5335926108.png)

点击后报错
![image](https://user-images.githubusercontent.com/5292190/160568876-b2778b9a-260d-432a-b650-a5c18d28d2a0.png)

**Comment by lurunze1226** [comment]
应该已经解决了 https://aisuda.bce.baidu.com/amis/zh-CN/components/tabs#%E9%85%8D%E7%BD%AE%E9%A1%B6%E9%83%A8%E5%B7%A5%E5%85%B7%E6%A0%8F
