### ISSUE TITLE
editor在form的时候 怎么全屏

### ISSUE THREAD

**Issue by 502647092** [baidu/amis#389]
![image](https://user-images.githubusercontent.com/10203793/71149261-017b7500-2269-11ea-9f8b-fb02675e6986.png)
```
{
                type: "button",
                level: "info",
                label: "原始数据",
                actionType: "drawer",
                drawer: {
                    position: "right",
                    size: "lg",
                    title: "服务 ${name} 的 原始 JSON 数据",
                    body: {
                        type: "form",
                        controls: [{
                            name: 'raw',
                            label: false,
                            type: "json-editor"
                        }]
                    }
                }
```

**Comment by 502647092** [comment]
![image](https://user-images.githubusercontent.com/10203793/71149370-4b645b00-2269-11ea-9fae-3bca9b67c73a.png)
就是类似这种效果

**Comment by 2betop** [comment]
这个要自己撸样式了。给 json-editor 上加个 className 然后补充样式表。

**Comment by 502647092** [comment]
emm 能不能搞一个直接填满父级的参数
或者就是editor直接和展示json的一样效果

**Comment by 502647092** [comment]
@2betop 我自己试了一下 好像不行
能不能给个实例
我就想高度能填满form

**Comment by 502647092** [comment]
```
        .editor-class {
            height: 800px;
        }
```
```
{
                                    name: "content",
                                    type: "editor",
                                    className: 'editor-class',
                                    language: "json",
                                    label: false,
                                }
```
![image](https://user-images.githubusercontent.com/10203793/71301486-9e115480-23da-11ea-9a3c-6a4c385ecf24.png)
好像并不行

**Comment by 2betop** [comment]
下面那个div 是不是配置了 maxHeight 之类的？

**Comment by 502647092** [comment]
对的 配置不配置都不行
editor好像不会填充

**Comment by nwind** [comment]
css 问题直接解决吧

**Comment by hyzx86** [comment]
有哪位道友可以分享下css 不？🤣

**Comment by xiahao90** [comment]
我在2.7.1还是可以的全屏，2.7.2就不行了

**Comment by hyzx86** [comment]
> 我在2.7.1还是可以的全屏，2.7.2就不行了

全屏，你说的是点击右上角的 双箭头是么？
其实我是想说 高度~~~
比如 ：

```json
{
"type":"editor",
"name":"code",
"style":{"height":"1800px"}

}
```
看起来没有任何效果，所以可能要写个class 去调整内部元素的样式，但在浏览器控制台怎么调都不合适
![image](https://user-images.githubusercontent.com/15613121/224887380-ea8c9369-8cbd-4a9d-a33f-80df88b5c834.png)

**Comment by BeMxself** [comment]
> 有哪位道友可以分享下css 不？🤣

其实是这样的，Editor的高度被FormItem 下面的 EditorControl 的max-height限制住了，你可以通过
inputClassName 重新设置一下max-height

**Comment by hyzx86** [comment]
@BeMxself 是的，没毛病

``` css 

.cxd-EditorControl {
--
max-height: 100% !important;
}
  
```
