### ISSUE TITLE
分页标签宽度不够支持4位数以上的页码。。。

### ISSUE THREAD

**Issue by gillbates** [baidu/amis#3894]
#### 描述问题：

如果分页后有1000+页，那个输入框的宽度就不够了。。。

#### 截图或视频：

<img width="646" alt="image" src="https://user-images.githubusercontent.com/783547/160740981-3dc9af1b-5894-4154-893a-1532ea8da073.png">

1425 已经显示不全了。。。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.7.0

4. 操作步骤
如果数据让分页超过1000页就必现这个问题。。。

**Comment by nwind** [comment]
#3917
