### ISSUE TITLE
amisPage / amisUser 如何使用? 

### ISSUE THREAD

**Issue by g770728y** [baidu/amis#39]
文档 高级用法中提到: 

> page 等价于全局变量，因为顶级渲染器就是它，所以下面的所有组件都能用到这个里面的数据。
amisPage 当前页面的数据信息，包含标题，id，key 之类的信息。
amisUser 当前用户信息，包含邮箱和用户名信息。

但在源码中, 并未找到相关内容, 请问具体如何使用这两个属性呢?

**Comment by 2betop** [comment]
不好意思，这是平台里面注入的 amisPage 和 amisUser，你也可以通过第二个参数传入

render(schema, {data: {
xxxx: xx
}});

data 的数据就是全局的。

**Comment by g770728y** [comment]
感谢!
