### ISSUE TITLE
表单如果初始化值里面含有$等特殊字符，会自动去映射数据，导致初始化值为空

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#3905]
#### 描述问题：

我的表单的input框需要输入$catId，但是保存后，如果作为初始化的表单值，那么会自动去映射数据，有没有办法使表单里面的数据不去映射数据

#### 截图或视频：
有$字符的情况：
![image](https://user-images.githubusercontent.com/37805363/160797673-a8f81f3f-cb74-4131-aa1a-be86784d5fc5.png)
没有$字符的情况正常：
![image](https://user-images.githubusercontent.com/37805363/160797739-727651e8-e7fc-4edc-97d4-5dc657eb2bf8.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.6.3

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
    "type": "form",
    "body": [
        {
            "type": "input-text",
            "name": "key",
            "label": "Key"
        }
    ],
    "data": {
        "key": "$catId"
    }
}
```

5. 操作步骤
见上

**Comment by nwind** [comment]
先用 initApi 吧，后来不知道为啥这里做了数据映射， @2betop 要不要加个 props 属性禁止这种行为？似乎 Sugar 提过类似的

**Comment by 2betop** [comment]
静态配置目前会做数据映射，如果不想映射可以用 initApi，或者像下面的示例把 dollor 转义处理。

```
{
    "type": "form",
    "body": [
        {
            "type": "input-text",
            "name": "key",
            "label": "Key"
        }
    ],
    "data": {
        "key": "\\$catId"
    }
}
```
