### ISSUE TITLE
支持`esm`打包

### ISSUE THREAD

**Issue by iceqing** [baidu/amis#3908]
#### 是否关联于某个问题吗：

由于`Webpack`开发编译相对较慢，想用`Vite`支持`amis` （[react-amis-admin](https://github.com/iceqing/react-amis-admin/tree/vite) ）。

但是由于`amis`未提供`ems`版本编译包，导致部分功能会报错，比如https://github.com/iceqing/react-amis-admin/issues/3

```
Uncaught (in promise) Error: Dynamic require of "echarts" is not supported
    at chunk-ACCAMVX6.js?v=64adb3e9:12:9
    at Chart.js:106:91
    at new Promise (<anonymous>)
    at Chart.js:106:61
    at async Promise.all (index 0)
```

该报错示例代码可参考[react-amis-admin](https://github.com/iceqing/react-amis-admin/tree/vite) `vite`分支

#### 预期的解决方案：
类似于[redux](https://github.com/reduxjs/redux/blob/master/rollup.config.js)分别提供`cjs`、`esm`的包，
或者[lodash-es](https://www.npmjs.com/package/lodash-es)等，提供单独的`esm`依赖。

#### 其他可接受方案：
提供amis的vite示例

#### 任何附加信息：

`vite` 使用`ESM` 作为模块化方案，因此不支持使用`require` 方式来导入模块，我尝试过对于一般的`require`做转换为import使用（使用vite-plugin-commonjs插件），但是对于这种`Dynamic require of "echarts"`仍然支持不够好，期望官方能提供`esm`的包支持。

**Comment by agileago** [comment]
其实你用上vite后，会发现编译其实也就那样，我现在就是用的vite编译amis的，没有想象中那么美好

**Comment by iceqing** [comment]
目前amis 2.0已经支持了esm，amis开发同学辛苦了，暂时关闭该问题

**Comment by iceqing** [comment]
@agileago 我利用webpack和vite测试了下，编译生产包的耗时几乎差距不大。

但是本地热加载差距非常大，webpack热加载开启HMR基本每次刷新在2到3秒之间，vite几乎是瞬间（0.5s内），可以大幅减少开发时的不必要等待，如果是对热加载时间有追求，vite值得尝试下。

我在github创建了一个示例项目可以参考（测试的分支分别是`vite3`分支和`webpack`分支）：
https://github.com/iceqing/react-amis-admin
