### ISSUE TITLE
时间控件变形

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#3929]
"amis": "1.8.0",
"amis-editor": "**4.1.0-beta.4**"
如下图所示：
![image](https://user-images.githubusercontent.com/5292190/161091546-559667cd-8073-4aeb-8a12-89b01c599ea6.png)

"amis": "1.8.0"
"amis-editor": "**4.0.2-beta.16**"
则显示正常

请对比改进"amis-editor": "4.1.0-beta.4"版本，感谢。

**Comment by nwind** [comment]
https://github.com/aisuda/amis-editor-demo 没复现，我猜是没引入最新的 amis css，input 样式明显不对
