### ISSUE TITLE
箭头变成了小方格

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#3930]
![image](https://user-images.githubusercontent.com/5292190/161096267-410c1c27-b2ba-4861-916e-121c72642dec.png)
使用editor发现箭头变成了小方格，好像一直存在这个问题。看了下F12，没有发现少什么东西。
请给指点下，怎么解决。
谢谢。

**Comment by cmdares** [comment]
缺少图标文件导致的，在页面引入 图标css即可
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/amis/sdk/iconfont.css">

**Comment by nwind** [comment]
谢谢提醒，amis-editor-demo 刚更新了
