### ISSUE TITLE
增加全局api返回结果的配置项

### ISSUE THREAD

**Issue by junphine** [baidu/amis#3934]
#### 是否关联于某个问题吗：
比如我已有的api返回格式是 
code，message，result，
还存在第三方的接口返回是： response.errorno, response.body

而且返回格式不能修改。每次写适配太麻烦了，能不能在全局做个api结果解析配置
	
	

#### 预期的解决方案：
比如：
amis.api.config.fieldMapping.data=result or response.body
amis.api.config.fieldMapping.status=code or response.errorno

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
在 fetcher 里做就行
