### ISSUE TITLE
getComponentByName 方法的疑问和建议

### ISSUE THREAD

**Issue by qaz3954179** [baidu/amis#3977]
#### 是否关联于某个问题吗：
1、我没有办法通过onEvent里面的actions 打开一个 dialog对话框
2、当我找到根节点的dialog做弹窗的时候，dialog 里面的button 的reload 目标就变成了Page 。无法定位到真实的parent。

#### 预期的解决方案：
1、onEvent 里面的action 可以打开dialog
2、reload 里面的 getComponentByName 为什么只查找parent。并且 参数 target 的 ‘a.b.c’ 这种操作竟然是 找到a 就调用a的 reload，而不是调用 路径为 “a.b.c” 找到的那个 Component.reload。

#### 其他可接受方案：
getComponentByName 的 查找支持层级查找

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by hsm-lv** [comment]
1.是支持的
2.可以换做getComponentById
