### ISSUE TITLE
select组件中的change事件如何使用？

### ISSUE THREAD

**Issue by manguanghui** [baidu/amis#3979]
#### 实现场景：
![图片](https://user-images.githubusercontent.com/76045750/161931242-2706ca93-578b-490e-b4a3-1c4b20570dd6.png)
我想要实现select下拉框的值改变之后进行重新请求api，并刷新当前crud组件

#### 存在的问题：
不知道如何使用

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
{
                  "type": "select",
                  "name": "status",
                  "label": "状态",
                  "change": {
                    "type": "button",
                    "label": "发布",
                    "level": "success",
                    "actionType": "dialog",
                    "dialog":{
                      "body": "你还啊"
                    }
                  },
                  "options": [
                    {
                      "label": "未发布",
                      "value": "1"
                    },
                    {
                      "label": "发布中",
                      "value": 2
                    },
                    {
                      "label": "已结束",
                      "value": 3
                    }
                  ]
                },
```

**Comment by hsm-lv** [comment]
> #### 实现场景：
> ![图片](https://user-images.githubusercontent.com/76045750/161931242-2706ca93-578b-490e-b4a3-1c4b20570dd6.png) 我想要实现select下拉框的值改变之后进行重新请求api，并刷新当前crud组件
> 
> #### 存在的问题：
> 不知道如何使用
> 
> #### 当前方案：
> 请粘贴你当前方案的完整 amis schema 代码...
> 
> ```
> {
>                   "type": "select",
>                   "name": "status",
>                   "label": "状态",
>                   "change": {
>                     "type": "button",
>                     "label": "发布",
>                     "level": "success",
>                     "actionType": "dialog",
>                     "dialog":{
>                       "body": "你还啊"
>                     }
>                   },
>                   "options": [
>                     {
>                       "label": "未发布",
>                       "value": "1"
>                     },
>                     {
>                       "label": "发布中",
>                       "value": 2
>                     },
>                     {
>                       "label": "已结束",
>                       "value": 3
>                     }
>                   ]
>                 },
> ```

可以给select添加onEvent配置，通过事件动作实现值变化后的动作触发，参考：事件动作章节 https://baidu.github.io/amis/zh-CN/docs/concepts/event-action
