### ISSUE TITLE
reload 的疑问

### ISSUE THREAD

**Issue by qaz3954179** [baidu/amis#3980]
https://github.com/baidu/amis/blob/0b9cef0b64c78d59868f92aad1d100062fce6946/src/Scoped.tsx#L159

这个位置为什么要加"." 的层级过滤，导致不能reload 级联结构的目标组件。

**Comment by hsm-lv** [comment]
可以试试事件动作，支持跨层级 https://baidu.github.io/amis/zh-CN/docs/concepts/event-action
