### ISSUE TITLE
app组件在iPhone 13 Pro的safari 横竖，Android的Chrome 竖版里面都不显示左边的菜单栏了。。。

### ISSUE THREAD

**Issue by gillbates** [baidu/amis#3983]
#### 描述问题：

app组件在iPhone 13 pro的Safari里面不现实左边的菜单栏了。。。
即使在Safari里面请求桌面网站，也依然不显示了。。。

iPhone 13 Pro Safari 的浏览器版本 (最新版本)

`
Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1
`

Android Chrome 的浏览器版本 (Google Play最新版本)

`
Mozilla/5.0 (Linux; Android 12; SM-G973F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.88 Mobile Safari/537.36
`

#### 截图或视频：

pc版的正常显示：

<img width="1245" alt="desktop1" src="https://user-images.githubusercontent.com/783547/162000171-0f82c84c-b62b-46f7-aba5-4e6598ff717f.png">

android 竖版，chrome，已经没有菜单那个图标了。。。

![androidportrait](https://user-images.githubusercontent.com/783547/162001302-b00c05dd-8827-49fb-ad17-1d061acc0e91.png)

android 横版，左边菜单还在。。。

![androidlandscape](https://user-images.githubusercontent.com/783547/162001366-af4a8a3f-1700-43d3-b5f6-41fda4b61a2d.png)

iphone safari 竖版，也没有菜单那个图标了。。。

![IMG_1528](https://user-images.githubusercontent.com/783547/162001623-e5c27a35-0d2f-4e8e-a572-556b190a3a07.PNG)

iphone safari 横版，也看不到左边的菜单栏了。。。

![IMG_1529](https://user-images.githubusercontent.com/783547/162001825-296e8bfb-1d5c-4744-85bb-139afba529be.PNG)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.8.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
const app = {
                type: 'app',
                brandName: 'Admin',
                // logo: '/public/logo.png',

                "pages": [
                    {
                        "label": "",
                        "children": [
                            {
                                "label": "首页",
                                "icon": "fas fa-tachometer-alt",
                                "url": "",
                                "isDefaultPage": true,
                                "schema": {
                                    type: 'page',
                                    title: '表单页面',

                                    body: [{
                                        "type": "form",
                                        "title": "搜索",
                                        "target": "total,list",
                                        "mode": "horizontal",
                                        "defaultCheckAll": true,
                                        "controls": [
                                            {
                                                "label": "账号",
                                                "type": "text",
                                                "name": "owner"
                                            },
                                            {
                                                "type": "divider"
                                            }
                                        ],
                                        "actions": [
                                            {
                                                "label": "查询",
                                                "level": "primary",
                                                "type": "submit"
                                            }
                                        ]
                                    },
                                    ]
                                }
                            },
                            {
                                "label": "其他页面",
                                "icon": "fa fa-th-list",
                                "url": "/opened",
                                "schemaApi": "get:/api/pages/opened"
                            },
                        ]
                    }
                ],
            }

let amisScoped = amis.embed('#root', app, { "locale": "zh-CN" }, { "theme": "antd" });
```

5. 操作步骤
上面的schema打开即可。。。

**Comment by nwind** [comment]
需要引入 iconfont.css，比如 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/amis@1.8.0/sdk/iconfont.css" />
