### ISSUE TITLE
默认的消息提示不居中

### ISSUE THREAD

**Issue by HiKit** [baidu/amis#3996]
* 和文档不一致，见图

![image](https://user-images.githubusercontent.com/4343299/162225510-b20b834b-cb46-4ea0-8be2-ff4efe609fa3.png)

![image](https://user-images.githubusercontent.com/4343299/162225634-a612bb70-e5ac-4fd4-a72e-c7c172caf57a.png)

**Comment by hsm-lv** [comment]
您那边的amis版本号是多少？

**Comment by HiKit** [comment]
版本V1.8.0
**看源代码后发现，必须启动时指定toastPosition，否则默认是top-right**

```
let amisScoped = amis.embed('#root', amisJSON,{},{toastPosition:"top-center"});
```
