### ISSUE TITLE
json schema 文件外网貌似访问不了

### ISSUE THREAD

**Issue by qiu8310** [baidu/amis#4]
如：http://amis.baidu.com/v2/schemas/page.json

![image](https://user-images.githubusercontent.com/1094697/56943866-f4800900-6b53-11e9-89d0-c2dc54fa513f.png)

**Comment by 2betop** [comment]
看来 json editor 的提示信息显示不了了，后面换个地址，感谢反馈

**Comment by 2betop** [comment]
切外网地址了，如： https://baidu.github.io/amis/#/docs/getting-started
