### ISSUE TITLE
静态标签的组件有嘛

### ISSUE THREAD

**Issue by 502647092** [baidu/amis#400]
![image](https://user-images.githubusercontent.com/10203793/71334490-6d1b5600-2579-11ea-863a-431e44b1cf41.png)
类似这种样式的

**Comment by 2betop** [comment]
看着像 button-group

**Comment by 502647092** [comment]
![image](https://user-images.githubusercontent.com/10203793/71400412-9f07e780-2661-11ea-9f04-ed98e09ede26.png)
emm 感觉用按钮组 中间有缝隙

**Comment by RickCole21** [comment]
自己样式微调一下？
