### ISSUE TITLE
amis在1.7.0 和 1.8.0 报错: Module not found: Error: Can't resolve 'ReactDOM' in /xx/react-visibility-sensor/dist

### ISSUE THREAD

**Issue by tangchaoren1** [baidu/amis#4001]
#### 描述问题：

问题1.amis在1.7.0 和 1.8.0 报错: Module not found: Error: Can't resolve 'ReactDOM' in   /xx/react-visibility-sensor/dist
问题2 .amis在1.7.0 和 1.8.0 报错: in React/index.js   does not match the corresponding path on disk `react`.
#### 截图或视频：
![image](https://user-images.githubusercontent.com/19602189/162368764-81064d22-dd1f-4e9c-9629-2e31cd8d9353.png)
![image](https://user-images.githubusercontent.com/19602189/162368742-afe90d34-2197-441b-9ce7-b3b61bcc5581.png)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 我是用的amis-admin 框架
2. amis 版本: 1.7.0 或 1.8.0
3.  "react": "^17.0.2",
    "react-dom": "^17.0.2"
react 在 1.18.0版本下 有同样的问题

4. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis 版本是1.1的时候。没有这样的问题。但是缺少很多编辑器中存在的组件。

6. 粘贴有问题的完整 `amis schema` 代码：
 schema: {
        type: 'page',
        title: '12',
        body: [
          {
            type: 'tpl',
            tpl: '这是你刚刚新增的页面。',
            inline: false
          },
          {
            type: 'crud',
            syncLocation: false,
            api: '',
            columns: [
              {
                name: 'id',
                label: 'ID',
                type: 'text'
              },
              {
                name: 'engine',
                label: '渲染引擎',
                type: 'text'
              }
            ],
            bulkActions: [],
            itemActions: [],
            id: 'u:05e4a89325d1'
          },
          {
            type: 'list',
            listItem: {
              body: [
                {
                  type: 'tpl',
                  tpl: '简单的展示数据：$a $b'
                }
              ],
              actions: [
                {
                  icon: 'fa fa-eye',
                  type: 'button'
                }
              ]
            },
            id: 'u:de642d2ac716'
          },
          {
            type: 'steps',
            value: 1,
            steps: [
              {
                title: '第一步',
                subTitle: '副标题',
                description: '描述'
              },
              {
                title: '第二步'
              },
              {
                title: '第三步'
              }
            ],
            id: 'u:050059c158d1'
          },
          {
            type: 'button',
            label: '按钮',
            actionType: 'dialog',
            dialog: {
              title: '系统提示',
              body: '对你点击了'
            },
            id: 'u:8fa13ed005d4',
            level: 'primary'
          }
        ]
      }
code here...
页面代码

AMisRenderer 组件代码
<template>
  <div class="box" ref="renderBox"></div>
</template>

<script>
import { render as renderSchema } from 'amis'
import copy from 'copy-to-clipboard'
import ReactDOM from 'react-dom'
import * as qs from 'qs'
import { toast, alert, confirm } from 'amis'
import axios from 'axios'

export default {
  props: {
    schema: {
      type: Object
    },
    updateLocation: {
      type: Function
    },
    onAction: {
      type: Function
    }
  },
  data() {
    return {
      theme: 'default'
    }
  },

  mounted() {
    this.initEnv()
    ReactDOM.render(
      renderSchema(
        this.schema,
        {
          onAction: this.onAction || this.handleAction,
          theme: this.theme
        },
        this.env
      ),
      this.$refs.renderBox
    )
  },

  methods: {
    initEnv() {
      this.env = {
        session: 'global',
        updateLocation: this.updateLocation || this.updateRoute,
        isCurrentUrl: to => {
          const link = this.normalizeLink(to)
          const location = window.location
          let pathname = link
          let search = ''
          const idx = link.indexOf('?')
          if (~idx) {
            pathname = link.substring(0, idx)
            search = link.substring(idx)
          }
          if (search) {
            if (pathname !== location.pathname || !location.search) {
              return false
            }
            const query = qs.parse(search.substring(1))
            const currentQuery = qs.parse(location.search.substring(1))
            return Object.keys(query).every(key => query[key] === currentQuery[key])
          } else if (pathname === location.pathname) {
            return true
          }
          return false
        },
        fetcher: ({ url, method, data, config, headers }) => {
          config = config || {}
          config.headers = config.headers || {}
          config.withCredentials = true

          if (config.cancelExecutor) {
            config.cancelToken = new axios.CancelToken(config.cancelExecutor)
          }

          config.headers = headers || {}
          config.method = method

          if (method === 'get' && data) {
            config.params = data
          } else if (data && data instanceof FormData) {
            // config.headers = config.headers || {};
            // config.headers['Content-Type'] = 'multipart/form-data';
          } else if (
            data &&
            typeof data !== 'string' &&
            !(data instanceof Blob) &&
            !(data instanceof ArrayBuffer)
          ) {
            data = JSON.stringify(data)
            // config.headers = config.headers || {};
            config.headers['Content-Type'] = 'application/json'
          }

          data && (config.data = data)

          return axios(url, config)
        },
        isCancel: e => axios.isCancel(e),
        alert,
        notify: (type, msg) => {
          toast[type]
            ? toast[type](msg, type === 'error' ? '系统错误' : '系统消息')
            : console.warn('[Notify]', type, msg)
          console.log('[notify]', type, msg)
        },
        confirm,
        copy: (contents, options = {}) => {
          const ret = copy(contents, options)
          ret && (!options || options.shutup !== true) && toast.info('内容已拷贝到剪切板')
          return ret
        }
      }
    },

    updateRoute(location, replace) {
      if (location === 'goBack') {
        return this.$router.go(-1)
      }
      this.$router[replace ? 'replace' : 'push'](this.normalizeLink(location))
    },

    handleAction(e, action) {
      this.env.alert(`没有识别的动作：${JSON.stringify(action)}`)
    },

    normalizeLink(to) {
      if (/^\/api\//.test(to)) {
        return to
      }
      to = to || ''
      const location = window.location
      if (to && to[0] === '#') {
        to = location.pathname + location.search + to
      } else if (to && to[0] === '?') {
        to = location.pathname + to
      }
      const idx = to.indexOf('?')
      const idx2 = to.indexOf('#')
      let pathname = ~idx ? to.substring(0, idx) : ~idx2 ? to.substring(0, idx2) : to
      const search = ~idx ? to.substring(idx, ~idx2 ? idx2 : undefined) : ''
      const hash = ~idx2 ? to.substring(idx2) : ''
      if (!pathname) {
        pathname = location.pathname
      } else if (pathname[0] != '/' && !/^https?:\/\//.test(pathname)) {
        const relativeBase = location.pathname
        const paths = relativeBase.split('/')
        paths.pop()
        let m
        while ((m = /^\.\.?\//.exec(pathname))) {
          if (m[0] === '../') {
            paths.pop()
          }
          pathname = pathname.substring(m[0].length)
        }
        pathname = paths.concat(pathname).join('/')
      }
      return pathname + search + hash
    }
  }
}
</script>

7. 操作步骤
复现步骤：在一个vue项目中。 下载如上描述的amis 版本  使用amis-admin中提供的vue模板

**Comment by hsm-lv** [comment]
尝试下新版本呢
