### ISSUE TITLE
使用amis-editor时, 即使定义了接口数据为json, 在预览时发出的请求头仍然是application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by one-pyy** [baidu/amis#4005]
#### 描述问题：

使用amis-editor时, 即使定义了接口数据为json, 在预览时发出的请求头仍然是application/x-www-form-urlencoded。当把代码复制下来跑的时候, 问题不再出现。

#### 截图或视频：

![image](https://user-images.githubusercontent.com/72590023/162580178-59a5af8e-4ec6-4446-852b-49c7e726efd1.png)
![image](https://user-images.githubusercontent.com/72590023/162580201-890825da-d947-4025-8e90-445a53c5114d.png)
当我如此设置这个接口时
![image](https://user-images.githubusercontent.com/72590023/162580220-64b08b24-5eeb-43df-9de2-73597f8e6629.png)
它在预览界面发出了这个请求
![image](https://user-images.githubusercontent.com/72590023/162580243-125c72f3-8b67-460e-9e9d-20bc09043cbc.png)
即使负载页面为
![image](https://user-images.githubusercontent.com/72590023/162580288-c702b89f-addd-4a46-bee2-fa353d6a3307.png)
但由于请求头的问题, 我的后端应用无法正常解析它
(当把代码复制下来, 不在editor中跑时, 问题不再出现)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
amis-editor

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.8, 应该就是这几天才有的版本

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "title": "",
  "body": [
    {
      "type": "form",
      "title": "管理员登录",
      "body": [
        {
          "label": "用户名",
          "type": "input-text",
          "name": "username"
        },
        {
          "type": "input-password",
          "label": "密码",
          "name": "password",
          "id": "u:0da61e018bd1"
        }
      ],
      "api": {
        "method": "post",
        "url": "http://127.0.0.1:60080/admin/login",
        "dataType": "json",
        "data": {
          "username": "${username}",
          "password": "${password}"
        },
        "replaceData": true
      },
      "id": "u:c22a20cfcc8b",
      "autoFocus": true,
      "panelClassName": "r w-full",
      "mode": "normal",
      "horizontal": {
        "leftFixed": "normal",
        "left": 2,
        "right": 10
      },
      "className": "",
      "wrapWithPanel": true,
      "rules": [
      ]
    },
    {
      "type": "grid",
      "columns": [
      ],
      "id": "u:da98173374a1"
    },
    {
      "type": "grid",
      "columns": [
      ],
      "id": "u:0c46d0c1a673"
    }
  ],
  "messages": {
  },
  "style": {
  }
}
```

4. 操作步骤
如上图片段(好像写错地方了)

**Comment by one-pyy** [comment]
(抱歉之前的那个回复没看到)

目前的话是用了[使用后端语言热部署amis页面](https://github.com/one-pyy/amis_helper)的方式来绕过这个问题

(大佬们加油, 辛苦了)

**Comment by wibetter** [comment]
这个问题已经修复了，是amis-editor-demo的写法问题，相关改动点：https://github.com/aisuda/amis-editor-demo/commit/1823d4cbf42e414e07ec48dccf99547b06539353
