### ISSUE TITLE
getComponentById和getComponentByName问题

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#4010]
amis版本：1.8.0-beta.17  采用jssdk方式测试，index.html中定义：
let amisScoped = amis.embed(.....)  预先定义全局环境
按照官网的教程在chrome console中执行：
amisScoped.getComponentByName('page1.form1').setValues({'name1': 'othername'})  好用，生效。

于是我想测试修改一下其他组件属性看看效果，比如针对button对象修改下某些属性：
amisScoped.getComponentByName('page1.button1')   发现获取不到对象

测试了一下getComponentById 函数的效果：
amisScoped.getComponentById('page1')  有
amisScoped.getComponentById('form1')  有
amisScoped.getComponentById('button1') 无

测试了一下getComponentByName函数的效果：
amisScoped.getComponentByName('page1.form1') 有
amisScoped.getComponentByName('page1.button1') 无

json：
{
    "type": "page",
    "name": "page1",
    "id": "page1",
    "title": "test",
    "body": [
      {
        "type": "button",
        "name": "button1",
        "id": "button1",
        "label": "按钮",
        "actionType": "dialog",
        "dialog": {
          "title": "系统提示",
          "body": "对你点击了"
        }
      },
      {
        "type": "form",
        "name": "form1",
        "id": "form1",
        "body": [
          {
            "label": "Name",
            "type": "input-text",
            "name": "name1"
          }
        ]
      }
    ]
  }

【严重】：我想是否版本不够新，当升级amis版本为1.8.0 后，神奇效果出现了。
getComponentByName
getComponentById
这类函数全没有了！

求助！！！
感谢！！!

**Comment by hyzx86** [comment]
文档上说 sdk 和 react 是同一个东西。。
但具体用下来发现并不一样。。
https://github.com/baidu/amis/issues/4388

**Comment by lurunze1226** [comment]
resolved by #4050
