### ISSUE TITLE
怎么在打开Dialog时候，不默认调用autoComplete的接口

### ISSUE THREAD

**Issue by Tigerremy** [baidu/amis#4017]
#### 实现场景：
点击新增，弹出Dialog，在搜索时候再去调用接口

#### 存在的问题：
默认打开Dialog的时候，调用了autoComplete接口，此时入参为空，查询不到数据

#### 当前方案：
{
      type: 'select',
      name: 'name',
      label: '搜索词',
      searchable: true,
      placeholder: '请输入',
      required: true,
      labelField: 'title',
      valueField: 'nid',
      searchImediately: false,
      autoComplete: {
          method: 'post',
          url: 'xxxxxxxx',
          data: {
              name: '$term',
          },
      },
  },

**Comment by lurunze1226** [comment]
接口可以配置`sendOn`属性控制是否发送请求 https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api?page=1#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E6%9D%A1%E4%BB%B6
