### ISSUE TITLE
Calendar 日历日程 放大模式 largeMode = true 仍然太小

### ISSUE THREAD

**Issue by gexMichael** [baidu/amis#4019]
#### 描述问题：

官网的 Calendar 日历日程
放大模式 largeMode = true 仍然太小，放大为全屏幕较合理
[Calendar 日历日程](https://baidu.github.io/amis/zh-CN/components/calendar)

#### 截图或视频：

![image](https://user-images.githubusercontent.com/22609092/162781749-7ddacfeb-fe98-4f30-ab28-52ecf2ad465e.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.8

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lurunze1226** [comment]
1.9.0 已修复
