### ISSUE TITLE
在文件上传中，如何能够做到，显示的名称和服务器上真实名称不一致

### ISSUE THREAD

**Issue by noahsoft** [baidu/amis#402]
比如：logo.jpg图片上传到服务器上，服务器上文件重新命名为：1577092243096.jpg，返回value会自动绑定到File组件上，如何能够做到，显示名称和真实名称不一致的情况，显示使用原始名称，下载绑定使用真实名称呢？

**Comment by nwind** [comment]
新版可以自定义 downloadUrl
