### ISSUE TITLE
自定义表单的保存按钮后表单的输入验证失去了关联，要怎么关联上？

### ISSUE THREAD

**Issue by YUHUAJ** [baidu/amis#403]
![11](https://user-images.githubusercontent.com/51392760/71399926-31a78700-2660-11ea-9d7d-8f3ce769f637.jpg)
![22](https://user-images.githubusercontent.com/51392760/71399932-39ffc200-2660-11ea-9e03-81f9029e5a13.jpg)

**Comment by RickCole21** [comment]
用自带的验证？

**Comment by 2betop** [comment]
你把这个 onClick 逻辑删了，改成去 form 里面监听 onSubmit

**Comment by YUHUAJ** [comment]
作者大大，不好意思，我这个form是放在dialog里面的呢，这种情况我还是去监听form的submit吗？那样的话dialog的保存按钮怎么处理？
![11](https://user-images.githubusercontent.com/51392760/71452651-c4136c00-27c1-11ea-9d8e-8580b2e0d574.jpg)

**Comment by 2betop** [comment]
dialog 里面监听 onConfirm 事件，关闭是 onClose

**Comment by YUHUAJ** [comment]
能不能麻烦写个dialog 里面监听 onConfirm 事件例子呀，文档里没有找到，小菜鸡跪谢大佬！！

**Comment by 2betop** [comment]
就是你的 type: "dialog" 的配置同级添加 onConfirm 属性，类型为： (values:Array<Object>) => void;

**Comment by YUHUAJ** [comment]
![22](https://user-images.githubusercontent.com/51392760/71460879-9988d980-27e8-11ea-8548-1251eab124d0.jpg)
是这样吗？可是触发不了呢

**Comment by 2betop** [comment]
dialog 里面，就是你现在的基础上，再进去一层

**Comment by YUHUAJ** [comment]
也试过了，也触发不了，是不是我的用法有问题？还是因为我自定义了“取消”“保存”这两个按钮？
![221](https://user-images.githubusercontent.com/51392760/71464580-e5da1680-27f4-11ea-942a-a59d6a2c78d6.jpg)

**Comment by YUHUAJ** [comment]
作者您好，目前遇到的问题是这样的：如果actionType不为close时点击‘保存’按钮是能触发表单验证的，但是点击的时候也触发了onClick事件。现在想问的是：怎么取到整个表单的渲染参数（写验证时需要遍历每个item是否有require）或是有什么监听事件能代替onClick（点击时通过了验证才触发后面的逻辑操作）
![123](https://user-images.githubusercontent.com/51392760/71565864-bb86a280-2aed-11ea-90c4-a6e8b3274b2e.jpg)
![124](https://user-images.githubusercontent.com/51392760/71565868-c04b5680-2aed-11ea-9cc0-2d3d72864060.jpg)

**Comment by 2betop** [comment]
前面说了啊，你应该去帮 dialog 的 onConfirm 事件呢，而不是 onClick

**Comment by 2betop** [comment]
确认按钮的  actionType 用 "confirm" 而不是 "close"

**Comment by YUHUAJ** [comment]
像您说的那样执行了后仍无法触发onConfirm，麻烦看一下是哪里有问题，谢谢
![43231](https://user-images.githubusercontent.com/51392760/71566239-f63e0a00-2af0-11ea-8e79-5bc2fdb2689a.jpg)

**Comment by 2betop** [comment]
body 里面是什么？body 放个 form 然后配置 controls ?

**Comment by YUHUAJ** [comment]
body里面是这样的配置
![32](https://user-images.githubusercontent.com/51392760/71566351-e2df6e80-2af1-11ea-9c3f-acd64fb109cf.jpg)

**Comment by 2betop** [comment]
一切都看着很正常呢，下午我本地试一下

**Comment by YUHUAJ** [comment]
好的，麻烦了。下午等你的好消息。

**Comment by 2betop** [comment]
![image](https://user-images.githubusercontent.com/2698393/71570736-b9ced600-2b11-11ea-818f-ff9661df4fa6.png)

表示可以进来啊

**Comment by YUHUAJ** [comment]
这个会因为版本的问题吗？

**Comment by 2betop** [comment]
你看看是不是外层的 onClick  执行了两次？难倒是 onClick   透传下去了导致的？

**Comment by YUHUAJ** [comment]
onClick也没有执行两次
![53](https://user-images.githubusercontent.com/51392760/71574417-94e35e80-2b23-11ea-9817-aeb57aec4d0a.jpg)

**Comment by 2betop** [comment]
跟你的用法真的是一样的了。要不你用下最新的版本试试看？

![image](https://user-images.githubusercontent.com/2698393/71578471-3a51fe80-2b33-11ea-997e-a06b6fa30e9c.png)

![image](https://user-images.githubusercontent.com/2698393/71578485-4938b100-2b33-11ea-9f8b-ff3f3260b9a9.png)

**Comment by 2betop** [comment]
或者你把我这一坨拿过去试试

```js
{
          type: 'button',
          label: '测试',
          onClick: (e, props) => {
            setTimeout(() => {
              props.onAction(e, {
                actionType: 'dialog',
                dialog: {
                  title: 'test',
                  onConfirm: () => {
                    debugger;
                  },
                  body: {
                    type: 'form',
                    controls: [
                      {
                        name: 'a',
                        type: 'text',
                        label: 'Test',
                        required: true
                      }
                    ]
                  },
                  actions: [
                    {
                      type: 'button',
                      actionType: 'confirm',
                      label: '确认'
                    }
                  ]
                }
              });
            }, 200);
          }
        }
```

**Comment by YUHUAJ** [comment]
应该和版本无关了，同一版本下测试的两个结果
![22](https://user-images.githubusercontent.com/51392760/71609094-c78f6480-2bc0-11ea-8cae-42c96431da67.jpg)

**Comment by YUHUAJ** [comment]
作者你好，经多次测试后我发现这个自定义按钮能不能触发onConfirm取决于该actions配置是放在第几层渲染器里面，如下图，actions配置是放在page这个第一层渲染器下就能触发onConfirm，如果是放在第二层渲染器Form下面就触发不了onConfirm，麻烦你测试一下我有没有弄错。
![1111](https://user-images.githubusercontent.com/51392760/71703185-6230b300-2e0e-11ea-9ff4-641c507b684e.jpg)

**Comment by 2betop** [comment]
感谢提供这么详细的信息，问题定位了，因为 form 默认就监听了 onConfrim 事件，所以 schema 中配置的 onConfirm 被盖了，我这边想像办法，两个都执行。

**Comment by 2betop** [comment]
https://github.com/baidu/amis/commit/10df6f2a712c8067b852d4b84d0cf1d4592c7400

先用这个版本：1.0.8-beta.29

**Comment by YUHUAJ** [comment]
好的，做了几次测试都可以触发了，非常感谢！！
