### ISSUE TITLE
群号不对

### ISSUE THREAD

**Issue by h7ml** [baidu/amis#4032]
#### 描述问题：
群号不对

#### 截图或视频：
![image](https://user-images.githubusercontent.com/55233292/163157794-657cbba2-a80e-4d61-a77f-b6074c657009.png)

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
是对的，如流是百度的 IM，不是 qq
