### ISSUE TITLE
关于amis 依赖  monaco-editor 版本问题

### ISSUE THREAD

**Issue by minzhenyu** [baidu/amis#4034]
#### 实现场景：
 amis升级到1.8之后   monaco-editor 报错

#### 存在的问题：
https://github.com/aisuda/amis-widget/issues/4
麻烦看下有没有什么解决方案,
不然每次安装amis 都需要单独去删除amis依赖的monaco-editor 

#### 当前方案：
https://github.com/aisuda/amis-widget/issues/4

**Comment by nwind** [comment]
可能是 webpack 版本要升到 5

**Comment by nwind** [comment]
决定暂时降低版本了 #4057

**Comment by minzhenyu** [comment]
thx,👍

**Comment by zhaoqize** [comment]
同样的问题
