### ISSUE TITLE
关于amis-editor 是否有开源计划的问题

### ISSUE THREAD

**Issue by minzhenyu** [baidu/amis#4036]
@nwind #### 是否关联于某个问题吗：
amis-editor 是否有开源计划,项目中用了amis-editor
一方面觉得不稳定
另一方面对于开发者来说完全是黑盒,有问题无法定位,找官方反馈速度也无法保证

**Comment by nwind** [comment]
目前没有计划，不过 amis-editor 文档确实比较欠缺，所以近期会先补充文档和将定制所需了解的代码展示出来方便修改
