### ISSUE TITLE
文档中图表示例 在切换到其他组件的文档页面后 还在一直发起图表相关请求

### ISSUE THREAD

**Issue by Akitata** [baidu/amis#4037]
#### 描述问题：

先访问图表组件的文档 https://aisuda.bce.baidu.com/amis/zh-CN/components/chart

下拉到底后，在console里可以看到有/amis/api/mock2/chart/chart和/amis/api/mock2/chart/chartData的请求

切换到其他组件的文档，看console，上面说的两个请求会一直持续。

#### 截图或视频：

![](https://cache.akitata.pro/20220414014227.png)

**Comment by wibetter** [comment]
@Akitata 新版没复现这个问题。看问题现象，是路由页面切换后，没有清除chart组件中的定时器（chart组件定时刷新功能），但看代码记录，四年前就有清除逻辑：
<img width="719" alt="image" src="https://github.com/baidu/amis/assets/11958920/51c19cce-a0cf-4944-aaec-98062c247753">
看下新版能不能复现你的问题，如果复现的话，辛苦录屏看下。
