### ISSUE TITLE
关于升级到 Bootstrap 4.x 版本

### ISSUE THREAD

**Issue by charescape** [baidu/amis#404]
有计划升级到 Bootstrap 4.x 版本吗？毕竟 3.x 版本在 2016 年之后就已经不再维护了

![image](https://user-images.githubusercontent.com/53265646/71417022-165b6c80-269e-11ea-879b-70771e04343b.png)

**Comment by 2betop** [comment]
应该可以不依赖这个

**Comment by 2betop** [comment]
直接用 4 应该也可以

**Comment by charescape** [comment]
好的，明白了，我试一下，感谢这么快回复 👍

**Comment by charescape** [comment]
@2betop 不过还是期待能从框架层面直接支持 Bootstrap 4.x，毕竟对使用 JSSDK 方式的开发者更加友好

**Comment by 2betop** [comment]
好的，后续我尝试把 jssdk 的 bootstrap 版本切到 4

**Comment by nwind** [comment]
目前已经去掉这个依赖了
