### ISSUE TITLE
css报错

### ISSUE THREAD

**Issue by knight-peter** [baidu/amis#4041]
#### 描述问题：
node_modules/amis/lib/themes/antd.css
node_modules/amis/lib/themes/default.css
这两个文件下css有写错，`calc`中`+var`中间没加空格

#### 截图或视频：
![88508670907E86F9076282E5C2357F81](https://user-images.githubusercontent.com/3077802/163305324-1e8ee15b-877a-434b-968d-0ac323b3a2c2.jpg)

**Comment by sogud** [comment]
同样遇到这个问题

**Comment by luanwulin** [comment]
已经有人mr了，估计要等下次发版才行。可以自己拷贝css出来，然后把空格加上

**Comment by nwind** [comment]
> 已经有人mr了，估计要等下次发版才行。可以自己拷贝css出来，然后把空格加上

嗯 #3965，可以用 amis@1.9.0-beta.10
