### ISSUE TITLE
addOn发送POST请求无法解析模板字符串 

### ISSUE THREAD

**Issue by qsy1403813547** [baidu/amis#4056]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
addOn发送POST请求无法解析模板字符串 

#### 截图或视频：
![b0f20a1964d7ab22ea16169deddbd6c](https://user-images.githubusercontent.com/46235687/163509768-c3b43c2c-ca13-47dd-bead-a68d3a7a8d9e.png)

![9e3f5536b80f4fe598cf25da43b0909](https://user-images.githubusercontent.com/46235687/163509790-32e05cfe-cd0b-41e3-8c44-a9b9d4c7fe60.png)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.8

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```
{
                        "type": "input-text",
                        "label": "手机号码",
                        "name": "mobile",
                        "mode": "normal",
                        "validateOnChange": true,

                        "validations": {

                            "isPhoneNumber": true

                        },
                        "addOn": {
                            "label": "发送验证码",

                            "type": "button",

                            "countDown": 5,

                            "countDownTpl": "${timeLeft} 秒后重发",

                            "actionType": "ajax",

                            "level": 'primary',

                            "api": {

                                "method": "post",

                                "url": apiDomain + "/captcha/sms2",

                                "dataType": "json",

                                "data": {
                                    "mobile": '${mobile}',
                                    "type": "register"

                                }

                            }
                        },
                         "required": true

4. 操作步骤
请简单描述一下复现的操作步骤...
发送请求，无法解析

**Comment by qsy1403813547** [comment]
改成 “&”: “$$”, 
可以成功，也获取到{$mobile}参数值，
所以不知道怎么写获取mobile的模板字符串

**Comment by lurunze1226** [comment]
测试没问题：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "body": [
      {
        "type": "input-text",
        "label": "手机号码",
        "name": "mobile",
        "mode": "normal",
        "validateOnChange": true,
        "validations": {
          "isPhoneNumber": true
        },
        "addOn": {
          "label": "发送验证码",
          "type": "button",
          "countDown": 5,
          "countDownTpl": "${timeLeft} 秒后重发",
          "actionType": "ajax",
          "level": "primary",
          "api": {
            "method": "post",
            "url": "/api/mock2/form/saveForm",
            "dataType": "json",
            "data": {
              "mobile": "${mobile}",
              "type": "register"
            }
          }
        }
      }
    ]
  }
}
```
