### ISSUE TITLE
边栏没有自适应宽度和高度

### ISSUE THREAD

**Issue by Yansh-vic** [baidu/amis#4061]
#### 描述问题：

边栏没有自适应宽度和高度

#### 截图或视频：
![image](https://user-images.githubusercontent.com/49512312/163548003-aed8170b-4be1-49c7-8eb6-b64e7c1c64f1.png)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.8
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lurunze1226** [comment]
`asideMinWidth` , `asideMaxWidth` , `asideClassName` 用这几个属性控制一下侧边栏吧

**Comment by ddebug** [comment]
我也出现这个问题，树节点+表单导致的，求问大佬解决了吗

**Comment by AndongWang** [comment]
问下解决了吗，我今天也遇到了
