### ISSUE TITLE
鼠标右键菜单里面没了粘贴选项

### ISSUE THREAD

**Issue by gosunny2050** [baidu/amis#4067]
请教个问题，我把这个代码https://github.com/aisuda/amis-editor-demo下下来跑了起来，用127.0.0.1访问，右键里面有粘贴选项，我把www.abc.xiaomimi360.com绑定了host：127.0.0.1访问，拿它访问
里面的粘贴选项没了，知道怎么回事吗

![VHL6O%0VEG(N8M}3TXKZXCD](https://user-images.githubusercontent.com/64143527/163705601-87d24d2e-50bf-40b2-9f3f-7bbb1cce7111.png)

![XXOM`J1 Q@161@WKOW)P0 7](https://user-images.githubusercontent.com/64143527/163705604-4c0268ec-2f35-42ec-8cbb-ff1aa5ca86be.png)

**Comment by nwind** [comment]
浏览器限制，页面必须是 https 才行
