### ISSUE TITLE
input-kv 解析数据的问题

### ISSUE THREAD

**Issue by theojia** [baidu/amis#4070]
![image](https://user-images.githubusercontent.com/21030082/163751685-80972231-e778-4fd7-a073-daae8700b8d6.png)

如图，form里有input-kv组件，通过两种方式data和value赋初始值时，通过data的方式会存在问题：
input-kv会将 { “aaa.aaa”: 1 } 解析为 { “aaa”: { “aaa”: 1 } } ,擅自改变了用户自定义的key值。

😭麻烦老哥们帮忙确认一下~~谢谢~

**Comment by nwind** [comment]
因为这里会做数据映射，@2betop 看看要不要在 env 里加个 convertKeyToPath 配置

**Comment by theojia** [comment]
> 因为这里会做数据映射，@2betop 看看要不要在 env 里加个 convertKeyToPath 配置

老哥，这个问题还有在看麽🙏 @nwind
