### ISSUE TITLE
希望Json，Code，Editor组件增加一键复制功能

### ISSUE THREAD

**Issue by Yansh-vic** [baidu/amis#4076]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by wibetter** [comment]
Editor 4.1.0-beta.21 已经新增复制快捷键功能（ctrl + c 复制、ctrl + v 粘贴），你可以选中这几个组件，然后使用快捷键将其复制下来
