### ISSUE TITLE
Chart模块的大小可以改变吗？如果可以想请教一下如何改。

### ISSUE THREAD

**Issue by Actionpeak** [baidu/amis#408]
如题：目前问题是，chart模块固定大小，改幕布大小chart也不会变。
想问一下是没有实现改变图chart大小的功能还是有隐藏的改变方案

**Comment by 2betop** [comment]
chart 大小是会自动的，你可以看看这个里面。左侧收起，宽度自动变大。https://baidu.github.io/amis/chart
