### ISSUE TITLE
事件自定义js 无法隐藏控件

### ISSUE THREAD

**Issue by bitray** [baidu/amis#4081]
#### 描述问题：

在Checkbox上启用change事件, 控制页面中其他控件进行隐藏和现实的切换. 可以在控制台看到输出,但是控件不隐藏

#### 截图或视频：
暂时提供不了

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.6.4
3. 粘贴有问题的完整 `amis schema` 代码：
```
http://amis.baidu.com/v2/schemas/page.json#

{
                            "actionType": "custom",
                             "script": "var selectedVal=event.data.value;if(selectedVal!=''){doAction({actionType:'disabled',componentId:'min_value_id'});console.log('hidden')}else{doAction({actionType:'enabled',componentId:'min_value_id'});console.log('show')}"
                          }
```

4. 操作步骤
正常在checkbox下面增加以上代码. 如果选中的话, selectedVal会有值,目前hidden可以输出, 但是控件不隐藏

**Comment by hsm-lv** [comment]
你的意思是动作控制其显示后，虽然属性设置hidden但是没有隐藏是吗？

**Comment by bitray** [comment]
@hsm-lv hello 是的. 实际上并没有生效

而且我发现文档中也没有具体介绍各类事件的参数

**Comment by hsm-lv** [comment]
动作的处理是最权威的，如果动作为显示，则属性无效。

**Comment by bitray** [comment]
@hsm-lv ok 那我基本明白了. 就是说其实可能自定义js并不支持hidden这种属性. 可能只有部分特有的属性才支持
那请问,如果我想在点击一个checkbox的时候,onchange事件变化时, 讲表单中的某个控件隐藏或者disable. 可以用哪些方式呢? 除了disableOn之外,有事件编程方式么
