### ISSUE TITLE
如何在本地运行amis在线编辑器？

### ISSUE THREAD

**Issue by mrsmallyi** [baidu/amis#4088]
#### 实现场景：
我把编辑器项目clone 下来本地 https://github.com/aisuda/amis-editor-demo
然后npm i 安装依赖，然后npm run start 发现并没有像官方文档一样，显示编辑页面，而是一个空页面
![image](https://user-images.githubusercontent.com/17785263/164053384-e42ba7c9-cdce-4342-8b66-ec8614314816.png)
![image](https://user-images.githubusercontent.com/17785263/164053418-80688f71-74a0-40ac-a7d6-614ec60c641c.png)

#### 疑问：
请问我要怎样才能想官方文档一样显示编辑器页面
![image](https://user-images.githubusercontent.com/17785263/164053638-d05bfdc2-1825-4c16-9ef0-ebc2f93649c9.png)

```
code here...
```

**Comment by nwind** [comment]
开另一个窗口运行 npm run dev

**Comment by mrsmallyi** [comment]
谢啦

**Comment by fan0920** [comment]
![image](https://user-images.githubusercontent.com/43081888/231919789-b490668b-4d3e-41ae-b077-7a966319562b.png)
run dev后刷新页面是空白的，发现终端报这三个warn，手动install后还是重复报这三个warn。想问问有谁运行出来了吗？
