### ISSUE TITLE
inputTree的cascade属性无效

### ISSUE THREAD

**Issue by cbz20000** [baidu/amis#4093]
#### 描述问题：

inputTree的cascade属性设置为true，并不能像官网demo一样，选中父节点级联选中子节点，全选子节点可反选父节点，实际上父子节点之间没有任何互动

#### 截图或视频：
官网demo效果
![image](https://user-images.githubusercontent.com/79636715/164153888-55c70efc-daa6-497d-b4c6-4417c391f8ee.png)
本地demo效果
![image](https://user-images.githubusercontent.com/79636715/164153946-a923b0b5-4734-4574-9402-3c4e31539c94.png)
![image](https://user-images.githubusercontent.com/79636715/164154024-3e52b834-efaa-4015-9b2b-c7fd5a46d75b.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v1.8.0

3. 粘贴有问题的完整 `amis schema` 代码：
{
        "type": "input-tree",
        "name": "tree2",
        "label": "子节点可以反选，值包含父子节点值",
        "multiple": true,
        "cascade": true,
        "options": [
          {
            "label": "A",
            "value": "a"
          },
          {
            "label": "B",
            "value": "b",
            "children": [
              {
                "label": "B-1",
                "value": "b-1"
              },
              {
                "label": "B-2",
                "value": "b-2"
              },
              {
                "label": "B-3",
                "value": "b-3"
              }
            ]
          },
          {
            "label": "C",
            "value": "c"
          }
        ]
      }

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by pianruijie** [comment]
您好，官网文档中inputTree组件的最新功能在1.9.0-beta.12（包含）及以上的版本生效
新增功能点：
