### ISSUE TITLE
JSSDK 怎么使用主题

### ISSUE THREAD

**Issue by 502647092** [baidu/amis#410]

**Comment by solarisy** [comment]
我也是想问这个问题，个人感觉定制一个主题是基本需求，但是不知道怎样能定制一个主题样式呢？

**Comment by whitekyo** [comment]
同问

**Comment by nuan1989** [comment]
同问

**Comment by 2betop** [comment]
可以自己编译一个，把 examples 里面的 sdk-placeholder.html 中的 <link rel="stylesheet" title="default" href="../scss/themes/default.scss" />换成对应的主题，然后运行 sh publish.sh 就可以了。

**Comment by belongwqz** [comment]
如何做成官网文档页面一样，通过下拉框选择动态切换主题？
