### ISSUE TITLE
1.9 事件动作设计疑问

### ISSUE THREAD

**Issue by beairs** [baidu/amis#4106]
官方文档的“事件动作”对应的 amis 版本竟然是 1.9，这版本到现今为止还没正式发布，写文档的同学能不能稍微说明一下，这个问题太让人头大了。我以为在看现有文档，没想到在看“未来”

另外 1.9 的 beta 版本问题多到爆炸，由于是beta版，问题多也正常，那些不正常的 bug 就先不提了。

1.9 与 1.8 相比 “事件动作”设计差距比较大，例如，原本广播里面有一个execOn字段，用来控制事件发生时机， 1.9 已经删除了，请问如果需要实现监听 ajax 请求结果再进行特定广播动作，是否有什么替代方案？或者说 1.9 的现有方案组合起来就可以解决，只是文档比较缺失，导致看文档的人不知道怎么实现，如果是这样的话，是怎么组合才能实现呢？

**Comment by gemryan** [comment]
Amis 这文档...快弃坑了，My God!

**Comment by hsm-lv** [comment]
> Amis 这文档...快弃坑了，My God!

so sorry！ 为了保持设计一致，execOn字段改为expression了

**Comment by beairs** [comment]
1.9 各种组件逻辑一堆bug，看上去没救了，希望你们加油，框架初衷是好想法，可是还是要注意稳定性，不然谁敢用，正式版都这么多 bug

**Comment by lurunze1226** [comment]
> 1.9 各种组件逻辑一堆bug，看上去没救了，希望你们加油，框架初衷是好想法，可是还是要注意稳定性，不然谁敢用，正式版都这么多 bug

你好，辛苦反馈一下你遇到的具体问题

**Comment by beairs** [comment]
> > 1.9 各种组件逻辑一堆bug，看上去没救了，希望你们加油，框架初衷是好想法，可是还是要注意稳定性，不然谁敢用，正式版都这么多 bug
> 
> 你好，辛苦反馈一下你遇到的具体问题

![image](https://user-images.githubusercontent.com/21998638/167337377-88300734-7b29-4198-95e7-b7f69d62aa10.png)

select 组件设置多选后

**Comment by beairs** [comment]
> > 1.9 各种组件逻辑一堆bug，看上去没救了，希望你们加油，框架初衷是好想法，可是还是要注意稳定性，不然谁敢用，正式版都这么多 bug
> 
> 你好，辛苦反馈一下你遇到的具体问题

![image](https://user-images.githubusercontent.com/21998638/167337673-b0140590-8df8-486e-9be9-3b8c19c93fd8.png)

![image](https://user-images.githubusercontent.com/21998638/167337688-db52a39d-2eef-4140-80ec-0ab50a22a793.png)

![image](https://user-images.githubusercontent.com/21998638/167337702-239eeb8d-d2ed-4226-b84d-cf8aeebfc0cf.png)

日期范围的选择控件的size设置为小或者中,显示就有问题了

**Comment by beairs** [comment]
其他组件问题也还有很多，事件动作也同样有很多 bug，你们自己测吧，不想说了，太多有问题的地方

**Comment by beairs** [comment]
![image](https://user-images.githubusercontent.com/21998638/167364536-d48e87da-e043-4616-b1c6-a31a8a409ebe.png)

select 组件设置多选后
