### ISSUE TITLE
form中如何从服务端获取各输入默认值

### ISSUE THREAD

**Issue by XiuPunica** [baidu/amis#411]
formitem中，有关于默认值的定义，但是默认值value只能本地定义。如果交由服务端来控制，该怎么实现呢？
https://baidu.github.io/amis/docs/renderers/Form/FormItem

**Comment by RickCole21** [comment]
form配置initApi，然后返回数据格式：
```
{
  status:0,
  msg:'',
  data:{
      age:'aaa' // 你要映射的表单项name值
  }
}
```

**Comment by XiuPunica** [comment]
响应真迅速！感谢，我去试试~

**Comment by XiuPunica** [comment]
补充一下吧。
如果想实现页面内，数据A变动时其他字段修改默认值，也可以使用 service https://baidu.github.io/amis/docs/renderers/Form/Service
