### ISSUE TITLE
input-file组件change事件的参数是个空数组

### ISSUE THREAD

**Issue by ztky01** [baidu/amis#4118]
#### 描述问题：

input-file组件change事件的参数file是个空数组
代码不变的基础上，换成input-image组件,事件的参数则有值,可获得到文件名
success事件的参数正常无此问题

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.8.0

4. 粘贴有问题的完整 `amis schema` 代码：
let amisJSON = {
        "type": "page",
        "body": {
            "type": "form",
            "id": "form_data",
            "debug": true,
            "initApi": "/Public/GetOssSignature",
            "data": {

            },
            "preventEnterSubmit": true,
            "wrapWithPanel": false,
            "body": [
                {
                    "type": "input-file",//input-image
                    "name": "myfile",
                    "label": false,
                    "accept": ".csv,.pdf,.doc,.xls,.ppt,.docx,.xlsx,.pptx,.gif,.jpg,.jpeg,.bmp,.png,.zip,.rar",
                    "receiver": {
                        "method": "post",
                        "url": "http://${UpBucketName}.oss-cn-qingdao.aliyuncs.com",
                        "dataType": "form-data",
                        "data": {
                            "x-oss-forbid-overwrite": true,
                            "Content-Disposition": "attachment;filename=${name|url_encode}",
                            "success_action_status": "200",
                            "key": "${key}",
                            "policy": "${policy}",
                            "OSSAccessKeyId": "${OSSAccessKeyId}",
                            "signature": "${Signature}",
                            "testName": "${name|url_encode}"
                            //"&": "$$",
                        },
                        "requestAdaptor": function (api) {
                            console.log(api);
                            return {
                                ...api,
                                config: {
                                    withCredentials: false
                                }
                            };
                        }
                    },
                    "drag": true,
                    "useChunk": false,
                    "onEvent": {
                        "change": {
                            "actions": [
                                {
                                    "actionType": "toast",
                                    "msgType": "info",
                                    "msg": "开始上传",
                                    "position": "center"
                                },
                                {
                                    "actionType": "setValue",
                                    "componentId": "form_data",
                                    "value": "${file|first}"
                                },
                            ]
                        },
                        "success": {
                            "actions": [
                                {
                                    "actionType": "toast",
                                    "msgType": "success",
                                    "msg": "上传成功",
                                    "position": "center"
                                },
                                {
                                    "actionType": "custom",
                                    "script": function (context, doAction, event) {
                                        var result = {
                                            filename: event.data.file.name,
                                            filekey: event.data.__super.key,
                                            //filesize: $('#filenametext').attr('filesize')
                                        };
                                        console.log(result);
                                        parent.upbigfileobject = result;
                                        var index = parent.layer.getFrameIndex(window.name); //获取窗口索引
                                        parent.layer.close(index);
                                    }
                                }
                            ]
                        }
                    }
                },
            ],
            "actions": []
        }
    }

5. 操作步骤
请简单描述一下复现的操作步骤...
目的是为了通过change事件,在上传前就获取到文件名

**Comment by hsm-lv** [comment]
amis版本号是多少，另外确认一下取file值的候时通过event.data.file能否取到

**Comment by ztky01** [comment]
1.8.0  event.data.file同样问题

**Comment by hsm-lv** [comment]
没有复现你说的问题，确认一下接口是否正确返回了呢？
![image](https://user-images.githubusercontent.com/80095014/165008772-87778299-a3cf-4d83-a142-5ed518296dd7.png)

![image](https://user-images.githubusercontent.com/80095014/165008830-b526c405-2a1d-440f-bebd-8d1de315331a.png)

**Comment by ztky01** [comment]
问题依然存在
不同版本效果不一致
如下
'/Public/FileReceiverTest'  是个测试方法仅返回Empty无任何逻辑
代码结构无任何改动  仅改变版本号后用各个版本测试

当1.9.0-beta.14
success事件先触发
参数event.data.file有值  
状态"uploaded"
change事件后触发
参数event.data.file有值  是个数组
状态"uploaded"

当1.8.0
change事件先触发
参数event.data.file无值  是个空数组
success事件后触发
参数event.data.file有值  
状态"uploaded"

当1.7.0
change事件先触发
参数event.data.file有值  是个数组
状态"uploading"
success事件后触发
参数event.data.file有值  
状态"uploading"

下面是完整的代码
let amisJSON = {
        "type": "page",
        "body": [
            {
                "type": "form",
                "id": "form1",
                "debug": true,
                //"api": {

                //},
                //"data": {

                //},
                "preventEnterSubmit": true,
                "wrapWithPanel": false,
                "body": [
                    {
                        "type": "input-file",
                        "id": "file1",
                        "name": "file",
                        "label": false,
                        "accept": ".csv,.pdf,.doc,.xls,.ppt,.docx,.xlsx,.pptx,.gif,.jpg,.jpeg,.bmp,.png,.zip,.rar",
                        "multiple": false,
                        "drag": true,
                        "useChunk": false,
                        "autoUpload": true,
                        "receiver": "/Public/FileReceiverTest",
                        "onEvent": {
                            "change": {
                                "actions": [
                                    {
                                        "actionType": "setValue",
                                        "componentId": "form1",
                                        "value": {
                                            "path": "${file}"
                                        },
                                    },
                                    {
                                        "actionType": "custom",
                                        "script": function (context, doAction, event) {
                                            debugger;
                                        }
                                    }
                                ]
                            },
                            "success": {
                                "actions": [
                                    {
                                        "actionType": "custom",
                                        "script": function (context, doAction, event) {
                                            debugger;
                                        }
                                    }
                                ]
                            }
                        }
                    },
                ],
                "actions": [],
            },
        ]
    }

**Comment by ztky01** [comment]
再补充一点
刚刚发现 1.8.0时
如果页面刷新完
第一次传个附件
change事件 file是个空数组
第二次开始再上传个附件  file就有值了 但状态是"uploaded"
预期结果
change事件中的状态应该是uploading
success事件中的状态应该是uploaded

**Comment by hsm-lv** [comment]
嗯，因为实际应用中遇到一些小问题，所以在1.9.x里面对派发逻辑做了微调

**Comment by ztky01** [comment]
也就是说这个问题可能已经修复,我等着发版就好了

**Comment by hsm-lv** [comment]
以1.9.x为准

**Comment by ztky01** [comment]
感谢
