### ISSUE TITLE
combo 的 columnClassName 为 w-sm 时样式不符合预期

### ISSUE THREAD

**Issue by faceair** [baidu/amis#412]
当 columnClassName 为 w-xs 时
![image](https://user-images.githubusercontent.com/3659110/71732379-0e5fb180-2e82-11ea-82a7-2f60d656b761.png)

当 columnClassName 为 w-sm 时
![image](https://user-images.githubusercontent.com/3659110/71732326-ec662f00-2e81-11ea-8a7c-e2385c309f49.png)

宽度似乎直接变成一半了

**Comment by 2betop** [comment]
下个版本更新，已提交代码。

**Comment by faceair** [comment]
👍
