### ISSUE TITLE
如何实现自定义一个容器组件

### ISSUE THREAD

**Issue by Bamzc** [baidu/amis#4123]
#### 实现场景：
我想要自定义一个容器组件，并且让这个自定义容器组件支持内部插入其他组件以及自定义组件，这个如何实现呢？
![image](https://user-images.githubusercontent.com/10151046/164958743-21d1435d-923f-4c02-a08e-cc4155401337.png)

#### 存在的问题：
目前没有看到amis主入口开放container的使用方法？

**Comment by Ding4514** [comment]
import { BasePlugin } from 'amis-editor';



import pluginName from "../pluginName"


let rendererName: string = pluginName.myRenderer;

export default class MyRendererPlugin extends BasePlugin {
    rendererName = rendererName;

    // 暂时只支持这个，配置后会开启代码编辑器
    $schema = '/schemas/UnkownSchema.json';

    // 用来配置名称和描述
    name = '自定义组件';
    description = '这只是个示例';

    // tag，决定会在哪个 tab 下面显示的
    tags = ['自定义'];

    // 图标
    icon = 'fa fa-user';

    // 用来生成预览图的
    previewSchema = {
        type: rendererName,
        target: 'demo',
        body: []
    };



    // 拖入组件里面时的初始数据
    scaffold = {
        type: rendererName,
        target: '233',

        body: [ // 容器类字段

        ]
    };

    regions = [
        {
            key: 'body',
            label: '内容区'
        },
    ];



    // 右侧面板相关
    panelTitle = '自定义组件';
    panelControls = [
        {
            type: 'tabs',
            tabsMode: 'line',
            className: 'm-t-n-xs',
            contentClassName: 'no-border p-l-none p-r-none',
            tabs: [
                {
                    title: '常规',
                    controls: [
                        {
                            name: 'target',
                            label: 'Target',
                            type: 'text'
                        }
                    ]
                },

                {
                    title: '外观',
                    controls: []
                }
            ]
        }
    ];
}

**Comment by Bamzc** [comment]
> import { BasePlugin } from 'amis-editor';
> 
> import pluginName from "../pluginName"
> 
> let rendererName: string = pluginName.myRenderer;
> 
> export default class MyRendererPlugin extends BasePlugin { rendererName = rendererName;
> 
> ```
> // 暂时只支持这个，配置后会开启代码编辑器
> $schema = '/schemas/UnkownSchema.json';
> 
> // 用来配置名称和描述
> name = '自定义组件';
> description = '这只是个示例';
> 
> // tag，决定会在哪个 tab 下面显示的
> tags = ['自定义'];
> 
> // 图标
> icon = 'fa fa-user';
> 
> // 用来生成预览图的
> previewSchema = {
>     type: rendererName,
>     target: 'demo',
>     body: []
> };
> 
> 
> 
> // 拖入组件里面时的初始数据
> scaffold = {
>     type: rendererName,
>     target: '233',
> 
>     body: [ // 容器类字段
> 
>     ]
> };
> 
> regions = [
>     {
>         key: 'body',
>         label: '内容区'
>     },
> ];
> 
> 
> 
> // 右侧面板相关
> panelTitle = '自定义组件';
> panelControls = [
>     {
>         type: 'tabs',
>         tabsMode: 'line',
>         className: 'm-t-n-xs',
>         contentClassName: 'no-border p-l-none p-r-none',
>         tabs: [
>             {
>                 title: '常规',
>                 controls: [
>                     {
>                         name: 'target',
>                         label: 'Target',
>                         type: 'text'
>                     }
>                 ]
>             },
> 
>             {
>                 title: '外观',
>                 controls: []
>             }
>         ]
>     }
> ];
> ```
> 
> }

这个确实是新增一个自定义组件的方式，但是控制的是右侧面板相关哈。我想问的问题是左侧渲染器的容器组件，如何自定义？

**Comment by Bamzc** [comment]
自己解答一下，新发现。结合楼上@[Ding4514](https://github.com/Ding4514)说的，在自定义渲染器界面，还需要调用render方法，渲染schemaNode节点。

**Comment by Bamzc** [comment]
`
1.第一步
const {body, render}  = this.props
2.第二步
{
  body.map((el, k) => (<>render(el, k)</>))
}

`

**Comment by wibetter** [comment]
![face_48@2x](https://user-images.githubusercontent.com/11958920/167257088-2d9a73ea-8539-4165-a18c-3e645d73afb0.png)

**Comment by wibetter** [comment]
如果需要定制一个复杂的容器组件，可以看下这个示例：https://github.com/aisuda/container-custom-widget-template。

**Comment by hcf1997** [comment]
@Bamzc 大佬 按照你上面说的注册了文件，报了这个错误
![image](https://user-images.githubusercontent.com/86106459/168005473-f605f84b-4897-4e41-adca-2e2b4630feb9.png)
![image](https://user-images.githubusercontent.com/86106459/168005493-6325b4c2-f384-470e-beff-f01783bacab6.png)
![image](https://user-images.githubusercontent.com/86106459/168005610-0e11e554-7830-44d7-ba7a-a8deb8b25939.png)

**Comment by wibetter** [comment]
这个看截图是没有import 那个自定义组件，import一下就可以。
