### ISSUE TITLE
api接口动画怎么关闭

### ISSUE THREAD

**Issue by heisen16129** [baidu/amis#4142]
#### 是否关联于某个问题吗：
![image](https://user-images.githubusercontent.com/57136111/165097532-28918cb7-bd20-468c-94e0-c0c3df53f59b.png)

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by 2betop** [comment]
新版多个加载 loading 会共用一个，请升级，有其他问题再开
