### ISSUE TITLE
Form-Table-默认数据加载问题

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#415]
我通过 Form 的 initApi 加载了初始数据，Table(FormItem) 该如何设置 value ？
```
 {
  "type": "form",
  "initApi": {
     "url": "xxx?corpId=$corpId",
     "sendOn": "corpId"
  }
  "controls": [
      {
         "type": "table",
          "label": "自建应用配置",
          **"value": "$apps",**
         "columns": [
                        {
                            "name": "agentId",
                            "label": "AgentId"
                        },
------------------------
{"msg":"操作成功",
"data":{
"corpId":"ww937153bcd346934e",
"apps":"[{\"secret\": \"xxxxxx\", \"agentId\": \"1000013\"}, {\"secret\": \"xxxxxxxxxxxxxxxxxxxxxxxx\", \"agentId\": \"1000014\"}]"},
"status":0}

```

**Comment by icodingx** [comment]
@2betop 请教了
initApi 取到的 apps 是一个数组（），form -> table 的 value 如何设置？

**Comment by icodingx** [comment]
有没有 ${apps | str2json} 的用法？

**Comment by 2betop** [comment]
你配置一下 name 为 "apps" 另外，你返回的数据看似是 string，正常应该都是后端直接解开。

**Comment by icodingx** [comment]
form -> table 的 value 如何设置？可以是 json 数组吗 ？可以添加 ${apps | str2json} 的用法吗？

**Comment by 2betop** [comment]
value 不支持取变量，都是 表单项的 name 关联一个变量。要做加工处理的话，要不就用接口的返回适配器，要不就是用 formula 来处理。

不过，我建议还是直接接口就返回 json 格式，而不是字符串。

**Comment by icodingx** [comment]
@2betop 请问 formula 怎么用 ?

**Comment by icodingx** [comment]
```
 "initApi": {
    "url": "/xxx",
    "adaptor": "(payload, response) => {payload.data.apps=JSON.parse(payload.data.apps); return (payload, response);}"
  },
```
提示：
Response is empty!

**Comment by 2betop** [comment]
```
 "initApi": {
    "url": "/xxx",
    "adaptor": (payload, response) => {payload.data.apps=JSON.parse(payload.data.apps); return payload;}
  },
```

**Comment by icodingx** [comment]
![form_table](https://user-images.githubusercontent.com/57850028/71797258-3456a300-3088-11ea-96de-3baf810dd834.png)

**Comment by icodingx** [comment]
> ```
>  "initApi": {
>     "url": "/xxx",
>     "adaptor": (payload, response) => {payload.data.apps=JSON.parse(payload.data.apps); return payload;}
>   },
> ```

还是提示：

**Comment by icodingx** [comment]
> ```
>  "initApi": {
>     "url": "/xxx",
>     "adaptor": (payload, response) => {payload.data.apps=JSON.parse(payload.data.apps); return payload;}
>   },
> ```

提示：
Response is empty!

**Comment by 2betop** [comment]
里面加 debugger; 语句调试一下吧，不能返回一个空的结果。

**Comment by icodingx** [comment]
![form_table](https://user-images.githubusercontent.com/57850028/71798122-e04dbd80-308b-11ea-8aab-5a8196f01428.png)

**好难搞！2天了！！！**

**Comment by 2betop** [comment]
能把大致 schema 贴出来吗
