### ISSUE TITLE
amis编辑器 移动端预览样式缺少内容

### ISSUE THREAD

**Issue by hcf1997** [baidu/amis#4158]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://user-images.githubusercontent.com/86106459/165425335-b2172944-295c-48ae-ab74-a3eef4fe9ef2.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by hcf1997** [comment]
本地跑没有问题，把fis3打包后的放在服务器上，就会缺少样式

**Comment by wibetter** [comment]
你是说打包后放服务器，截图中的几个icon就没有显示是吗？方便的话，发一下这个页面的地址，

**Comment by hcf1997** [comment]
@wibetter 没问题了  在editory页面忘记引入iframeUrl了，但是还是有个问题，就是editor打包后，部署到iis站点，只能部署到iis根目录下，不是根目录就不行了
![image](https://user-images.githubusercontent.com/86106459/167048733-7817ba32-79a5-42ad-bf4d-0851ab543447.png)

**Comment by wibetter** [comment]
看你这个截图中的报错，跟Editor本身没啥关系，初步判断是你们引入这几个css的方式有问题，引入的路径不正常，可以试着换成相对路径。

**Comment by hcf1997** [comment]
之前提过一个issues，有个大佬说的是用这个 .match('*', {host: '/fe_emdp_amis_editor'})，我感觉我应该是用错了，
![image](https://user-images.githubusercontent.com/86106459/167231498-aca7c42f-4782-4ef8-9e57-c4c14a0dff1c.png)
@wibetter

**Comment by hcf1997** [comment]
感觉应该要在node_module前面再加上/fe_emdp_amis_editor的

**Comment by wibetter** [comment]
你自己的项目可以考虑使用webpack，应该比较了解webpack吧，可以参考下这个示例：https://github.com/aisuda/amis-widget。
