### ISSUE TITLE
想使用 shadowRoot 隔离正常项目和amis的样式，但是helper.js 报错

### ISSUE THREAD

**Issue by shlroland** [baidu/amis#4176]
#### 描述问题：

function getScrollParent(node) {
    if (node == null) {
        return null;
    }
    var style = getComputedStyle(node);
    if (!style) {
        return null;
    }
    var text = style.getPropertyValue('overflow') +
        style.getPropertyValue('overflow-x') +
        style.getPropertyValue('overflow-y');
    if (/auto|scroll/.test(text) || node.nodeName === 'BODY') {
        return node;
    }
    return getScrollParent(node.parentNode);
}

这里拿到的是一个 document-fragment getComputedStyle方法会报错

#### 截图或视频：

<img width="1521" alt="image" src="https://user-images.githubusercontent.com/45024986/165559919-232ff663-ff86-407f-9059-11bc497dd5f7.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.7.0
3. 粘贴有问题的完整 `amis schema` 代码：

4. 操作步骤
```typescript
export const ShadowView: FC<ShadowViewProps> = ({
  children,
  mode = 'open',
}) => {
  const placeholder = useRef<HTMLElement>(null)
  const [shadowRoot, setShadowRoot] = useState<Element | null>(null)

  useLayoutEffect(() => {
    if (placeholder.current) {
      // 因为 ReactDom.createPortal 只接受 Element,类型暂时就这么强制改写一下
      // TODO: 带寻找更好的类型表达方式
      const shadowRoot = (placeholder.current.parentElement?.attachShadow({
        mode,
      }) as unknown) as Element
      if (shadowRoot) {
        setShadowRoot(shadowRoot)
      }
    }
  }, [mode])

  return shadowRoot ? (
    createPortal(children, shadowRoot)
  ) : (
    <span ref={placeholder}></span>
  )
}
```
使用如上容器对 amis组件进行包裹就会报错

**Comment by 2betop** [comment]
amis 不支持此用法，如果要样式隔离，请使用 jssdk，所有 css 都是加了前缀的
