### ISSUE TITLE
examples/pages/simple 不能被打开

### ISSUE THREAD

**Issue by WindyGao** [baidu/amis#4185]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
打开页面
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
打开没有反应，F12如下
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/36130371/165804852-26d868ac-a2ff-44e0-9350-f41600863d2a.png">

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by lurunze1226** [comment]
pull 最新的代码，更新dependencies试试

**Comment by 2betop** [comment]
请更新最新的代码
