### ISSUE TITLE
CRUD-bulkActions-filter 问题

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#419]
有个需求，想在 crud 执行批量操作前，通过表单选择部分条件，问题：如何在 bulkActions 动作时，取出表单字段？

**Comment by 2betop** [comment]
bulkActions，你可以配置成 dialog 类型，在 dialog 里面放个表单，然后 items 这个变量就是用户选择的条目。

**Comment by icodingx** [comment]
感谢，可以了 :-)

**Comment by liming37** [comment]
感谢
