### ISSUE TITLE
amis-editor只能部署到iis根目录，部署到子目录就报错

### ISSUE THREAD

**Issue by hcf1997** [baidu/amis#4193]
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/86106459/165910114-d431d8ea-61c6-4763-b432-6470570f56d2.png">

**Comment by hcf1997** [comment]
查找不到资源显示，应该是要修改fis打包的配置，有大佬知道怎么改吗

**Comment by 2betop** [comment]
fis.match('*', {host: '/fe_emdp_amis_editor'})

**Comment by hcf1997** [comment]
@2betop 
![image](https://user-images.githubusercontent.com/86106459/165917017-725492f3-2d78-4e27-8711-07eb755c3e1a.png)是这样配置吗

**Comment by hcf1997** [comment]
@2betop 大佬。还在吗

**Comment by wibetter** [comment]
amis-editor只是一个npm模块哈，你说的部署到某个服务上，是需要先将当前项目打包成静态资源，最后再将静态资源部署到服务器上，整个过程实际上跟amis-editor没有强关联关系。如果部署到服务器上访问有问题，需要确保下，是不是项目路由配置有问题，或者打包的时候配置的根路径不对。另外需要说明下，项目打包你可以使用任何你熟悉的打包工具哈，比如webpack。
