### ISSUE TITLE
ActionType可以增加upload上传行为吗？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#4203]
#### 是否关联于某个问题吗：
现在的input-file组件必须放在Form表单里面作为一个Formtem项，而且外观形式单一。

有时需求就是简单上传一个文件，文件到服务端后，服务端对这个文件有一些读写处理逻辑。不需要记录这个文件的文件名、大小等信息，所以不需要把上传按钮作为input组件放在form表单里，相反需要对这个按钮有些其他要求，比如像button ajax那样上传完毕后可以自动关闭dialog窗口，或者弹出一个feedback。。等等。

#### 预期的解决方案：
希望用button组件+ActionType实现简单的upload功能。ActionType都有download了，再增加一个upload呗？
#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by foxfire881** [comment]
input-file放在dialog里面，想实现选择文件上传完毕后自动关闭窗口，现有的input-file能实现码？button可以轻易实现啊，input-file能码？

**Comment by hsm-lv** [comment]
你可以尝试监听input-file的上传成功事件，执行关闭弹窗和弹出feedback的动作，例如

`  
{
  "type": "button",
  "label": "按钮",
  "id": "u:ab6ee0f2e004",
  "onEvent": {
    "click": {
      "actions": [
        {
          "actionType": "dialog",
          "dialog": {
            "type": "dialog",
            "title": "模态弹窗",
            "id": "dialog_001",
            "body": [
              {
                "type": "input-file",
                "name": "myfile",
                "mode": "horizontal",
                "onEvent": {
                  "success": {
                    "actions": [
                      {
                        "actionType": "closeDialog"
                      },
                      {
                        "actionType": "alert",
                        "args": {
                          "msg": "<a href=\"http://www.baidu.com\" target=\"_blank\">${event.data.file|json}~</a>"
                        }
                      }
                    ]
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
`
input-file的事件列表参考：https://baidu.github.io/amis/zh-CN/components/form/input-file#%E4%BA%8B%E4%BB%B6%E8%A1%A8
onEvent事件动作用法参考：https://baidu.github.io/amis/zh-CN/docs/concepts/event-action

**Comment by Niqian** [comment]
> input-file放在dialog里面，想实现选择文件上传完毕后自动关闭窗口并弹出一个feedback，现有的input-file能实现码？button可以轻易实现啊，input-file能吗？



> 你可以尝试监听input-file的上传成功事件，执行关闭弹窗和弹出feedback的动作，例如
> 
> ` { "type": "button", "label": "按钮", "id": "u:ab6ee0f2e004", "onEvent": { "click": { "actions": [ { "actionType": "dialog", "dialog": { "type": "dialog", "title": "模态弹窗", "id": "dialog_001", "body": [ { "type": "input-file", "name": "myfile", "mode": "horizontal", "onEvent": { "success": { "actions": [ { "actionType": "closeDialog" }, { "actionType": "alert", "args": { "msg": "<a href=\"http://www.baidu.com\" target=\"_blank\">${event.data.file|json}~</a>" } } ] } } } ] } } ] } } }` input-file的事件列表参考：https://baidu.github.io/amis/zh-CN/components/form/input-file#%E4%BA%8B%E4%BB%B6%E8%A1%A8 onEvent事件动作用法参考：https://baidu.github.io/amis/zh-CN/docs/concepts/event-action

这个效果不理想啊，有没有办法直接调用文件选择，而不是打开弹出后在点击触发文件选择

**Comment by Niqian** [comment]
> input-file放在dialog里面，想实现选择文件上传完毕后自动关闭窗口并弹出一个feedback，现有的input-file能实现码？button可以轻易实现啊，input-file能吗？

请问下，有没有比较好的实现方式呢，input-file会多一个拖拽或者点击动作，没有办法直接弹出浏览器的文件选择

**Comment by hsm-lv** [comment]
可以考虑有，那这个就不是amis组件级的范畴，是一种动作了
