### ISSUE TITLE
这个低代码只能做一个页面吗？不能一起import吗

### ISSUE THREAD

**Issue by aqnaruto** [baidu/amis#4205]
#### 实现场景：
比如我要做一个公司官网，  我有一个通用的导航栏 一个footer。子页面abcdef

我希望再主体页面里引入abcdef页面，点击导航切换abcd页
翻阅整个文档通篇没有类似的功能。

#### 存在的问题：
根本没有类似的功能

```
code here...
```

**Comment by dongyao8** [comment]
APP多页应用，请看文档：https://aisuda.bce.baidu.com/amis/zh-CN/components/app
