### ISSUE TITLE
空心方角标签

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#4209]
这是当前的所有标签的样式：
![image](https://user-images.githubusercontent.com/5292190/166176495-4a2ab6b3-d2ca-4e4b-a365-a8727c4067ec.png)

对比写element的样式：
![image](https://user-images.githubusercontent.com/5292190/166176468-2f50e70c-9b83-45fa-b20f-3b66336e7188.png)

能否提供线性矩形的标签吗？或者让圆角标签的角度能自定义也可达到效果。

**Comment by lurunze1226** [comment]
可以通过`style`属性实现
