### ISSUE TITLE
button按钮的动作方式

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#4210]
button按钮的动作方式能否实现如下效果，当点击了button之后，在buttong的下方展示一个类似提示的弹层效果，内容区域可疑使用不同的组件填充，注意背景内容不需要模态。
![image](https://user-images.githubusercontent.com/5292190/166182819-ad02f216-6053-4e84-a857-94cdfeb3a5a9.png)

**Comment by hsm-lv** [comment]
可以通过抽屉drawer实现，模态控制通过"overlay": false设置，弹出位置设置为"position": "bottom"即可
