### ISSUE TITLE
1.8.0  service 组件， interval 文档 的描述单位是秒， 实测是毫秒为单位, 请予以修正文档说明。

### ISSUE THREAD

**Issue by keepstep2010** [baidu/amis#4211]
![image](https://user-images.githubusercontent.com/45585794/166661275-8f63e515-b0be-4dd3-b2c8-c9c02517f832.png)

**Comment by lurunze1226** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/36724300/167236132-cee6bf68-7c9b-4c72-9d3d-43ca129505e1.png">
