### ISSUE TITLE
amis-editor  打包失败

### ISSUE THREAD

**Issue by Ding4514** [baidu/amis#4213]
#### 描述问题：

./node_modules/amis-editor/dist/style.css
ReferenceError: document is not defined

#### 截图或视频：

![image](https://user-images.githubusercontent.com/57136111/166857272-d25bdc01-a707-47f6-a93d-e68ddec15cbc.png)

**Comment by wibetter** [comment]
发一下你用的amis-editor版本号，我们定位下，

**Comment by Ding4514** [comment]
原先用的    "amis-editor": "^4.0.2-beta.16",    现在升级成  "amis-editor": "^4.1.0-beta.20",  都打包不成功

**Comment by wibetter** [comment]
./node_modules/amis-editor/dist/style.css里面就没有document哈，你用的是哪个构建工具，执行的命令是什么。方便的话，简述下你们使用editor的方式，

**Comment by Ding4514** [comment]
1  打包用的 Webpack    
2  
![image](https://user-images.githubusercontent.com/57136111/167231865-72b96e53-e3d9-4b4d-8eb7-ed6daf9e967f.png)
3 npm i amis-editor 然后把amis-editor-demo 的关键代码 copy到自己项目中
4 把 import 'amis-editor/dist/style.css‘ 这个样式注释了  就可以打包成功了

**Comment by wibetter** [comment]
光看你这个截图不好定位是哪的问题，但大概率是项目本身工程的问题。你可以参照下这个示例：https://github.com/aisuda/amis-widget，这个也是用webpack打包的，其中也有import 'amis-editor/dist/style.css‘。

**Comment by Ding4514** [comment]
这个是 svg-sprite-loader  引起的   
![image](https://user-images.githubusercontent.com/57136111/167251624-5367b13c-06db-475e-bb70-ed3290dadc64.png)
加 exclude: [/node_modules/], 这个就能打包了

**Comment by wibetter** [comment]
![face_48@2x](https://user-images.githubusercontent.com/11958920/167257025-650ee23f-182d-4ded-b966-93086cb813d2.png)
