### ISSUE TITLE
Checkboxes无法实现某些选项默认勾选

### ISSUE THREAD

**Issue by pathing** [baidu/amis#4218]
#### 是否关联于某个问题吗：
Checkboxes无法实现某些选项默认勾选

**Comment by lurunze1226** [comment]
请提供具体一点的描述，或者你的`schema`

**Comment by pathing** [comment]
Checkboxes类型可以通过接口获得有多少个勾选项，但是默认所有勾选项都是不勾选的，是否可以默认有一些勾选项是已勾选的（比如后端数据那一项is_checked=true则渲染出来的勾选项是勾选的）

**Comment by pathing** [comment]
> 
Checkboxes类型可以通过接口获得有多少个勾选项，但是默认所有勾选项都是不勾选的，是否可以默认有一些勾选项是已勾选的（比如后端数据那一项is_checked=true则渲染出来的勾选项是勾选的）

**Comment by lurunze1226** [comment]
form的初始化数据和checkbox的name绑定
