### ISSUE TITLE
事件动作 跳转链接（actionType：url / link）BUG 

### ISSUE THREAD

**Issue by cxkking** [baidu/amis#4228]
{
    "label": "选择数据",
    "type": "select",
    "name": "table",
    "options": [
        {
            "value": "inspection_rule",
            "label": "评分细则"
        },
        {
            "value": "inspection_rule_type",
            "label": "检查项目"
        },
        {
            "value": "inspection_task",
            "label": "督办单"
        },
        {
            "value": "inspection_test",
            "label": "工作流测试业务表"
        }
    ],
    "value": "inspection_rule",
    "required": true,
    "onEvent": {
        "change": {
            "actions": [
                {
                    "actionType": "link",
                    "link": "https://php54.com"
                },
                {
                    "actionType": "url",
                    "url": "https://php54.com"
                }
            ]
        }
    }
}

触发后会在新 tab 页面打开本页，无法跳转到指定链接

**Comment by hsm-lv** [comment]
1.9.0版本的动作参数需要包裹在args里，例如：

**Comment by cxkking** [comment]
"onEvent": {
        "change": {
            "actions": [
                {
                    "actionType": "url",
                    "args": {
                        "url": "/index?tbale=${value}&token=81c9ed6f475b95b01e020249989743ea64f8f648",
                    }
                }
            ]
        }
    }

可以跳转了，但是使用${value} 获取不到当前值了
