### ISSUE TITLE
table表的height属性？？

### ISSUE THREAD

**Issue by YUHUAJ** [baidu/amis#423]
table表因每页显示的数据条数太多导致页面拉得太开，所以table有没有height这个属性来控制表的高度？
![table-height](https://user-images.githubusercontent.com/51392760/72044672-5aca4780-32ef-11ea-9078-0803dd9ad0ea.png)

**Comment by CareyToboo** [comment]
@YUHUAJ 参照一下这个代码，应该暂时可以解决，这个问题。 http://jsfiddle.net/f2XYF/16/

**Comment by qinaidetonggege** [comment]
> http://jsfiddle.net/f2XYF/16/

请问怎么解决的呢，我打不开这个链接
