### ISSUE TITLE
Select静态数据联动

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#4230]
#### 是否关联于某个问题吗：
两个Select下拉框都是静态数据，需要联动，比如一个下拉框的数据是[{"label": "1","value":"1"},{"label":"2","value":"2"}]，
当选择第一个下拉框后，第二个下拉框根据第一个下拉框的值，初始化静态的options，比如选择1时，options为[{"label": "1.1","value":"1.1"},{"label":"1.2","value":"1.2"}]，选择2时为另外的options

#### 预期的解决方案：
可以实现的解决方案即可

#### 其他可接受方案：
我知道API可以实现此需求，但是我目前的需求就是静态数据，不通过API能否实现此联动功能

**Comment by rumunanfeng** [comment]
> 可以试试事件动作的setValue动作。每次select值变化的时候通过event.data.value获取选中的值，然后获取对应的数据源，将数据源绑定给变量opts
> 
> ```json
> {
>   "type": "form",
>   "title": "表单",
>   "body": [
>     {
>       "type": "select",
>       "label": "选项1",
>       "name": "select1",
>       "options": [
>         {
>           "label": "选项A",
>           "value": "A"
>         },
>         {
>           "label": "选项B",
>           "value": "B"
>         }
>       ],
>       "id": "u:af1ad4e2f8db",
>       "multiple": false,
>       "mode": "inline",
>       "onEvent": {
>         "change": {
>           "weight": 0,
>           "actions": [
>             {
>               "actionType": "setValue",
>               "args": {
>                 "value": {
>                   "opts": "${optList[event.data.value]}"
>                 }
>               },
>               "componentId": "u:d731760b321e"
>             }
>           ]
>         }
>       }
>     },
>     {
>       "type": "select",
>       "label": "选项2",
>       "name": "select2",
>       "id": "u:d731760b321d",
>       "multiple": false,
>       "mode": "inline",
>       "source": "${opts}"
>     }
>   ],
>   "id": "u:d731760b321e",
>   "data": {
>     "optList": {
>       "A": [
>         {
>           "label": "A",
>           "value": "a"
>         },
>         {
>           "label": "B",
>           "value": "b"
>         },
>         {
>           "label": "C",
>           "value": "c"
>         }
>       ],
>       "B": [
>         {
>           "label": "A2",
>           "value": "a2"
>         },
>         {
>           "label": "B2",
>           "value": "b2"
>         },
>         {
>           "label": "C2",
>           "value": "c2"
>         }
>       ]
>     },
>     "opts": []
>   }
> }
> ```

呃，我复制这段代码进去使用，选择第一个下拉框之后，好像数据并未改变，第二个下拉框还是无数据？
是不是版本不对，我的amis版本是1.6.3，请问你的版本是什么？
![image](https://user-images.githubusercontent.com/37805363/167234062-e2883d69-4555-43b6-9819-3c47644e004b.png)

**Comment by hsm-lv** [comment]
嗯，是版本太老了，可以试下1.9.0

**Comment by rumunanfeng** [comment]
升级到1.9.0后可以了，感谢！
