### ISSUE TITLE
InputMonth为什么要单击两次才被选中

### ISSUE THREAD

**Issue by ztky01** [baidu/amis#4231]
InputMonth 月份组件
为什么要单击两次才被选中
故意这样设计的吗
官方文档即可复现
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-month#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95

**Comment by ztky01** [comment]
没找到规律 好像有的时候也不是单击两次

**Comment by lurunze1226** [comment]
文档里没有复现

**Comment by ztky01** [comment]
好吧偶发情况
