### ISSUE TITLE
ActionType="ajax"可以触发校验规则吗？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#4236]
#### 描述问题：

做了一个包含多个提交button稍微复杂点的表单，没有用form自带的actions、submit，而是在button上用ajax提交，发现ajax无法触发表单控件的校验规则（例如required: true属性在ajax提交时无法触发校验规则，用ajax可以提交空值）

能否ajax提交前像submit那样触发校验规则，不符合的红色高亮提示？

**Comment by foxfire881** [comment]
为什么不用submit而要用ajax？因为有时要对一批输入框完成多个不同的提交功能。
比如有A、B、C三个输入字段，要有三个按钮提交到后台不同的接口，提交的参数分别是A+B、A+C、B+C

如果用form的话得做嵌套form，结构上很复杂有冗余，而且A+B、A+C这种有交叉的情况没法做嵌套。最简单的方案就是用三个ajax的button提交。但是这样又不能触发校验规则了，有解决方案吗？

**Comment by foxfire881** [comment]
看到有个onClick事件可以执行js，但是js要怎么触发FormItem的校验规则呢？而且不是全表单每个输入框都校验，比如还是以上案例，点按钮1触发校验A+B字段；点按钮2触发校验A+C字段；点按钮3触发校验B+C字段。

这可以实现？

**Comment by hsm-lv** [comment]
可以通过配置按钮的onEvent来实现表单的校验，目前只支持表单校验，即暂不支持触发单个表单项的校验动作，如下：

```json
{
  "type": "page",
  "title": "test",
  "body": [
    {
      "type": "form",
      "title": "表单",
      "body": [
        {
          "type": "input-text",
          "label": "文本框",
          "name": "name",
          "mode": "horizontal",
          "required": true
        }
      ],
      "id": "u:ada0f15e366b",
      "debug": true
      }
    },
    {
      "type": "button",
      "label": "按钮",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "validate",
              "componentId": "u:ada0f15e366b"
            }
          ]
        }
      },
      "id": "u:ada0f15e366c"
    }
  ]
}
```

详细参考： 
https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E8%A7%A6%E5%8F%91%E5%85%B6%E4%BB%96%E7%BB%84%E4%BB%B6%E7%9A%84%E5%8A%A8%E4%BD%9C

https://baidu.github.io/amis/zh-CN/components/form/index#%E5%8A%A8%E4%BD%9C%E8%A1%A8

**Comment by foxfire881** [comment]
> 
> 详细参考： https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E8%A7%A6%E5%8F%91%E5%85%B6%E4%BB%96%E7%BB%84%E4%BB%B6%E7%9A%84%E5%8A%A8%E4%BD%9C

谢谢，可以考虑增加单个FormItem的验证接口，以配置或者js接口的形式提供调用，这样灵活程度会更大，可以设计出更复杂的表单。
