### ISSUE TITLE
form表单中提交失败去除默认的toast

### ISSUE THREAD

**Issue by flwcy** [baidu/amis#4239]
#### 实现场景：
我表单后台返回提交失败时，采用了submitFail抽屉提示

#### 存在的问题：
即有抽屉提示，也有默认的toast

#### 当前方案：

```
         "onEvent": {
            "submitFail": {
              "actions": [
                {
                  "actionType": "drawer",
                  "drawer": {
                    "title": "预约失败",
                    "body": {
                      "type": "alert",
                      "level": "warning",
                      "icon": "fa fa-cloud",
                      "body": "预约失败，若给您造成不便，敬请谅解。"
                    }
                  }
                },
                {
                  "actionType": "reset"
                }
              ]
            }
          }
```

**Comment by flwcy** [comment]
表单提交成功"redirect": "/show",如何拿到返回中的id做为跳转参数

**Comment by hsm-lv** [comment]
1.当前还没有支持默认toast的阻止，在考虑加进来
2.可以直接从事件对象中获取返回的数据，例如：
```json
{
  "type": "page",
  "title": "表单提交请求错误",
  "regions": [
    "body",
    "toolbar",
    "header"
  ],
  "body": [
    {
      "type": "form",
      "title": "表单",
      "body": [
        {
          "type": "input-text",
          "label": "文本框",
          "name": "name",
          "mode": "horizontal",
          "required": true
        }
      ],
      "id": "l2d4wn3s",
      "initApi": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/initData",
      "debug": true,
      "api": {
        "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveFormFailed",
        "method": "get"
      },
      "onEvent": {
        "submitFail": {
          "weight": 0,
          "actions": [
            {
              "actionType": "drawer",
              "drawer": {
                "title": "预约失败",
                "body": {
                  "type": "alert",
                  "level": "warning",
                  "icon": "fa fa-cloud",
                  "body": "预约失败，若给您造成不便，敬请谅解。"
                }
              }
            },
            {
              "actionType": "url",
              "args": {
                "url": "http://www.baidu.com",
                "blank": true,
                "params": {
                  "errmsg": "${event.data.error.errors.test2}"
                }
              }
            }
          ]
        }
      },
      "actions": [
        {
          "type": "button",
          "label": "按钮",
          "onEvent": {
            "click": {
              "actions": [
                {
                  "actionType": "submit",
                  "componentId": "l2d4wn3s"
                }
              ]
            }
          },
          "id": "u:f4a899de717f"
        }
      ]
    }
  ]
}
```

可以通过${event.data.xxx}获取表单事件的哪些数据，具体参考表单的事件表： https://baidu.github.io/amis/zh-CN/components/form/index#%E4%BA%8B%E4%BB%B6%E8%A1%A8

**Comment by flwcy** [comment]
> 1.当前还没有支持默认toast的阻止，在考虑加进来 2.可以直接从事件对象中获取返回的数据，例如：
> 
> ```json
> {
>   "type": "page",
>   "title": "表单提交请求错误",
>   "regions": [
>     "body",
>     "toolbar",
>     "header"
>   ],
>   "body": [
>     {
>       "type": "form",
>       "title": "表单",
>       "body": [
>         {
>           "type": "input-text",
>           "label": "文本框",
>           "name": "name",
>           "mode": "horizontal",
>           "required": true
>         }
>       ],
>       "id": "l2d4wn3s",
>       "initApi": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/initData",
>       "debug": true,
>       "api": {
>         "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveFormFailed",
>         "method": "get"
>       },
>       "onEvent": {
>         "submitFail": {
>           "weight": 0,
>           "actions": [
>             {
>               "actionType": "drawer",
>               "drawer": {
>                 "title": "预约失败",
>                 "body": {
>                   "type": "alert",
>                   "level": "warning",
>                   "icon": "fa fa-cloud",
>                   "body": "预约失败，若给您造成不便，敬请谅解。"
>                 }
>               }
>             },
>             {
>               "actionType": "url",
>               "args": {
>                 "url": "http://www.baidu.com",
>                 "blank": true,
>                 "params": {
>                   "errmsg": "${event.data.error.errors.test2}"
>                 }
>               }
>             }
>           ]
>         }
>       },
>       "actions": [
>         {
>           "type": "button",
>           "label": "按钮",
>           "onEvent": {
>             "click": {
>               "actions": [
>                 {
>                   "actionType": "submit",
>                   "componentId": "l2d4wn3s"
>                 }
>               ]
>             }
>           },
>           "id": "u:f4a899de717f"
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> 可以通过${event.data.xxx}获取表单事件的哪些数据，具体参考表单的事件表： https://baidu.github.io/amis/zh-CN/components/form/index#%E4%BA%8B%E4%BB%B6%E8%A1%A8

好的，感谢大佬，还有一个问题，panel里面加了二维码，如何居中显示
