### ISSUE TITLE
qsOptions  不符合预期

### ISSUE THREAD

**Issue by fitan** [baidu/amis#4243]
#### 实现场景：
![image](https://user-images.githubusercontent.com/34503273/167240711-3b061f97-6d19-42dd-9710-baaf87f6166c.png)

#### 存在的问题：
![image](https://user-images.githubusercontent.com/34503273/167240755-a4ec89c9-66f0-45e0-8ffa-36133c739127.png)
结果users?0=ids=3&ids=2
希望是  users?ids=3&ids=2

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
不能复现，新版本已经是这样的结果 `ids[0]=1&ids[1]=2`

<img width="239" alt="image" src="https://github.com/baidu/amis/assets/2698393/c7e4ef04-05b8-42a9-901c-5fced8967d41">

api 配置参考你的截图

```
api: {
          method: 'delete',
        url: '/api/test',
        dataType: 'form',
        data: {
          ids: '${ids|split}'
        }
      },
```
