### ISSUE TITLE
表单项加一个可以设置一个提交数据时的别名

### ISSUE THREAD

**Issue by SmallRuralDog** [baidu/amis#4256]
## 表单项加一个可以设置一个提交数据时的别名
通过配置`value`属性，可以设置表单项的默认值。

`value`不支持数据映射，也就是说不可以直接配置类似于这样的语法：`${xxx}`，如果想要映射当前数据域中的某个变量，那么设置该表单项`name`为该变量名就行

现在获取数据，与提交数据都是用`name`来获取。

但是现在有需求在提交表单的时候需要自定义`name`的名称

**Comment by hsm-lv** [comment]
可以通过数据映射
