### ISSUE TITLE
toast无法展示

### ISSUE THREAD

**Issue by luanwulin** [baidu/amis#4267]
#### 描述问题：

同样的配置，dialog可以展示出来，toast无法展示
直接调用amisStore上面的notify也无法展示

#### 截图或视频：
![image](https://user-images.githubusercontent.com/16553854/167381014-25160bbb-6657-43c1-a06d-0c1912587900.png)

![image](https://user-images.githubusercontent.com/16553854/167381339-3b44ed02-17b2-4f84-9e2e-235506132781.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
react方式

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

1.9.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
    "type": "page",
    "body": [
        [
            {
                "type": "button",
                "name": "amis-c2eb818a-d394-4a48-93c8-1318f232eb9a",
                "label": "按钮",
                "identityName": "按钮",
                "fieldId": "amis-c2eb818a-d394-4a48-93c8-1318f232eb9a",
                "onClick": "props.onAction(event, {\n      actionType: 'toast',\n      toast: {\n        items: [\n          {\n            body: '轻提示内容'\n          }\n        ]\n      }\n});"
            }
        ]
    ]
}
```

4. 操作步骤
点击按钮，页面没有反应，不出现toast。用window.amisStore.notify('error', '注册成功')也不行

**Comment by hsm-lv** [comment]
没有复现你说的问题，你发的schema的结构有点问题，body里多一层[]，试试下面的

```json
{
  "type": "page",
  "body": [
      {
        "type": "button",
        "name": "amis-c2eb818a-d394-4a48-93c8-1318f232eb9a",
        "label": "按钮",
        "identityName": "按钮",
        "fieldId": "amis-c2eb818a-d394-4a48-93c8-1318f232eb9a",
        "onClick": "props.onAction(event, {\n      actionType: 'toast',\n      toast: {\n        items: [\n          {\n            body: '轻提示内容'\n          }\n        ]\n      }\n});"
      }
  ]
}
```

**Comment by luanwulin** [comment]
@hsm-lv 已经尝试过了，在demo页面也能看到，这个schema的按钮，点击了没有反应

https://user-images.githubusercontent.com/16553854/167432979-78bb8e83-f531-4259-9d7a-7e5f365788ae.mp4

**Comment by hsm-lv** [comment]
你需要确认一下amis env对notify方法的定义是什么，如果覆盖了原有处理逻辑，那么toast就会失效

**Comment by luanwulin** [comment]
@hsm-lv 这块需要在render的时候传参么？

**Comment by hsm-lv** [comment]
你的editor的amisEnv是怎么设置的呢？

**Comment by luanwulin** [comment]
@hsm-lv 目前render的第三个参数，只传入了fetcher
```
    <div ref={formRef}>
      {renderAmis(
        {
          name: 'amis-page',
          type: 'page',
          body,
        },
        {
          scopeRef: (ref: any) => {
            amisRef.current = ref;
          },
        },
        {
          fetcher,
        },
      )}
    </div>
```

**Comment by hsm-lv** [comment]
嗯，因为你现在的问题是在编辑器里面出现的，所以要看下给editor的属性配置是怎样的，不是renderAmis的

**Comment by luanwulin** [comment]
编辑器那个视频，是官方的编辑器的。我本地没有跑[https://aisuda.github.io/amis-editor-demo](editor)。

我本地有一个展示页面，就是用的render函数渲染的，schema就是上面这个，也是无法通过点击触发notify

**Comment by hsm-lv** [comment]
你是用的sdk的方式？

**Comment by luanwulin** [comment]
@hsm-lv react的方式

**Comment by luanwulin** [comment]
@hsm-lv 已经上传 [https://github.com/luanwulin/amis-demo](github)

两个按钮，dialog可以出现，toast不行

**Comment by hsm-lv** [comment]
问题在于缺少ToastComponent，你需要在你的dom结构中加入 <ToastComponent theme="cxd" />

**Comment by rumunanfeng** [comment]
> 问题在于缺少ToastComponent，你需要在你的dom结构中加入

React要如何加入？文档里没找到任何介绍

**Comment by h7ml** [comment]
> > 问题在于缺少ToastComponent，你需要在你的dom结构中加入
> 
> React要如何加入？文档里没找到任何介绍

import { ToastComponent, AlertComponent } from 'amis'

**Comment by h7ml** [comment]
https://github.com/daimall/react-antd-amis/blob/bd565a8d604b40045a21c98535b63a65307c36fa/src/views/clients/index.tsx#L5
https://github.com/daimall/react-antd-amis/blob/bd565a8d604b40045a21c98535b63a65307c36fa/src/views/clients/index.tsx#L119

**Comment by UltramanWeiLai** [comment]
> 问题在于缺少ToastComponent，你需要在你的dom结构中加入

请问一下在 SDK 的模式下，如何添加 ToastComponent ？
