### ISSUE TITLE
有没有考虑接入一下WebSocket或者可以通过amis.embed之后的对象修改数据

### ISSUE THREAD

**Issue by 502647092** [baidu/amis#430]
- 新增 `WebSocket` 更新数据的功能
- 或者考虑 `Socket.IO`
- 也可以通过 `amis.embed` 返回的对象修改数据后直接生效 这样我们可以自己做兼容

**Comment by 502647092** [comment]
@2betop
这个有考虑嘛

**Comment by 2betop** [comment]
还是不太清楚什么个应用场景

**Comment by 502647092** [comment]
> 还是不太清楚什么个应用场景

你可以理解为 
我要通过别的方式
更新/监听amis的数据
基本页面都可以实现了
就是有些功能没法接口轮询的方式更新
之前的服务端是Socket.io的

**Comment by 2betop** [comment]
amis 在渲染的时候可以传入数据的，我感觉应该能满足这个需求。

**Comment by 502647092** [comment]
@2betop 主要是
我现在的做法是
 一个主页面
然后后续的渲染都是用service渲染
然后调用API填充数据的
不是每个页面都有amis.embed这个渲染逻辑的

转换成具体需求 简单点说就是
能不能通过amis.embed返回的对象 修改页面的数据
不然的话 我得把SocketIO的服务端全部转成http接口才能实现实时更新

**Comment by belongwqz** [comment]
强烈建议接入websocket
