### ISSUE TITLE
amis-editor的侧边栏在jssdk中有组件可以用嘛

### ISSUE THREAD

**Issue by 502647092** [baidu/amis#431]
![image](https://user-images.githubusercontent.com/10203793/72197924-c7fdea00-3461-11ea-8ca5-74734578b06a.png)
就是这个侧边栏部分 有没有直接可以用的组件
如果没有的话 能不能提供一下
或者 nav 这个组件的样式改一下 现在的感觉好丑
![image](https://user-images.githubusercontent.com/10203793/72197929-e19f3180-3461-11ea-8144-aa10c1a6d74a.png)

**Comment by CareyToboo** [comment]
你看下demo项目，项目里都有的。直接  `import { AsideNav } from 'amis'`  在 `amis/lib/components/`目录下有很多组件，可以自己看下，基本都是直接用。不需要渲染器，渲染的。

**Comment by 502647092** [comment]
> 你看下demo项目，项目里都有的。直接 `import { AsideNav } from 'amis'` 在 `amis/lib/components/`目录下有很多组件，可以自己看下，基本都是直接用。不需要渲染器，渲染的。
> 
> Duplicate of #448

emmm我是想在js版本里面用 请问有没有办法

**Comment by CareyToboo** [comment]
JS版本确实没有用过～ 我是直接用的react版本。很多组件都可以用，还能随便自定义，没啥限制。

**Comment by 502647092** [comment]
@2betop 
https://github.com/fex-team/amis-admin 的 jssdk版本
能把左侧的导航栏也封装成一个js可以用的组件嘛
不然还是要写jq之类的js

**Comment by 2betop** [comment]
js 我已经写好了 https://github.com/fex-team/amis-admin/tree/jssdk

**Comment by 502647092** [comment]
@2betop 有没有那种 直接当作amis组件用的
而不是要自己写js的
因为我想单个页面
然后通过左侧导航对应的参数
通过service动态刷新右侧主界面的内容

**Comment by 502647092** [comment]
已提供App模式
