### ISSUE TITLE
input-text组件的enter事件不生效

### ISSUE THREAD

**Issue by 1562217380** [baidu/amis#4312]
#### 描述问题：

input-text组件的enter事件不生效

#### 截图或视频：
官网测试案例：

![image](https://user-images.githubusercontent.com/44864844/167983998-29e25e19-ba72-4b1e-a106-0688a64f8a7f.png)

代码案例：
![image](https://user-images.githubusercontent.com/44864844/167984060-0a5cc1cb-206b-4f6e-907f-c123979abd34.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.9.19

4. 粘贴有问题的完整 `amis schema` 代码：
```
      onEvent: {
            enter: {
              actions: [
                {
                  actionType: 'custom',
                  script: async (renderer, doAction, event) => {
                    console.log('enter---------------',)
                    return;
                  },
                },
              ]
            },
          }
```

5. 操作步骤
1.配置enter属性后，进行操作，不生效

**Comment by lurunze1226** [comment]
`input-text`的`enter` 事件目前仅在[选择器](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-text#%E9%80%89%E6%8B%A9%E5%99%A8%E6%A8%A1%E5%BC%8F) 模式下生效

**Comment by lhtuling** [comment]
> `input-text`的`enter` 事件目前仅在[选择器](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-text#%E9%80%89%E6%8B%A9%E5%99%A8%E6%A8%A1%E5%BC%8F) 模式下生效

遇到同样问题  jssdk模式会经常用到各种事件 希望能尽可能的开放类似的自定义操作  暂时先用提交表单实现

**Comment by lhtuling** [comment]
@1562217380 
我这样完成了  用表单的提交成功事件
``````
{
						"type": "form",
						"title": "",
						"mode": "horizontal",
						"submitText": "",
						"id": "l2d4wn3s",
						"body": [
							{
								"type": "input-text",
								"name": "QrCode",
								"style": {
									"width": "300px"
								},
								"label": "条码录入：",
							},
						],
						"onEvent": {
							"submitSucc": {
								"weight": 0,
								"actions": [
									{
										"actionType": "custom",
										"script": (context, doAction, event) => {
											console.log(event.data.QrCode);//取本组件的 值											
										}
									}
								]
							}
						},
					},
``````

**Comment by 1562217380** [comment]
将input与表格绑定在一起，也可以达到目的，表格的filter与form的input自带enter事件

**Comment by CKask** [comment]
> `input-text`的`enter` 事件目前仅在[选择器](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-text#%E9%80%89%E6%8B%A9%E5%99%A8%E6%A8%A1%E5%BC%8F) 模式下生效

什么时候可以支持输入模式下有enter事件呢？
