### ISSUE TITLE
amis-editor按照官方文档的说明 使用最新版注册自定义组件 显示报错

### ISSUE THREAD

**Issue by hcf1997** [baidu/amis#4316]
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
![image](https://user-images.githubusercontent.com/86106459/167998475-0c4f91f3-e4a0-4e78-bbd9-5a4f6feedc2a.png)

请粘贴你当前方案的完整 amis schema 代码...

```
code here...
![image](https://user-images.githubusercontent.com/86106459/167998515-b13c091b-6de8-4b18-bacc-0b508331decd.png)

```
![image](https://user-images.githubusercontent.com/86106459/167998602-bcaebff8-b7f1-40d3-8870-209e6f21a29f.png)

**Comment by hcf1997** [comment]
![image](https://user-images.githubusercontent.com/86106459/167998661-a594116a-3f2b-4159-b09b-1b40749dbaf8.png)

**Comment by wibetter** [comment]
@hcf1997  先把你自己的MyRendererPlugin import 进来，

**Comment by hcf1997** [comment]
@wibetter 大佬。我看你开发的amis-widget这个库的文档，上面的问题都解决了，现在就是遇到了，注册OptionsControl类型的编辑器组件，官方好像没有文档，wo shi我试着写了下，他不显示下拉框的配置项
![image](https://user-images.githubusercontent.com/86106459/168202643-edb2f2a4-e406-4657-815d-7c8552c1afae.png)
![image](https://user-images.githubusercontent.com/86106459/168202674-37889c55-8c67-4e8d-86ea-eda20f54e08b.png)

**Comment by hcf1997** [comment]
![image](https://user-images.githubusercontent.com/86106459/168202803-bbd824cf-7318-4d89-9032-abd0f3a6958e.png)

**Comment by wibetter** [comment]
看下这个文档：https://console.cloud.baidu-int.com/devops/icafe/issue/amis-saas-4429/show

**Comment by wibetter** [comment]
@hcf1997 你这里的自定义组件是对应下拉框中的配置面板：
![image](https://user-images.githubusercontent.com/11958920/169680104-fc0a76ce-a2f1-4f8b-9e2c-7a92d6f86898.png)
需要设置哪些配置项，你可以参考下当前项目中node_modules/amis-editor/src/plugin/Form/select：
![image](https://user-images.githubusercontent.com/11958920/169680159-8d247245-cbbd-4038-9761-79629b157e1b.png)
