### ISSUE TITLE
正序和倒序 没有中间态

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#4320]
#### 描述问题：

可以在列上配置"sortable": true，该列表头右侧会渲染一个可点击的排序图标，可以切换
样式有三种状态，但是只返回两种，系统能指定，只有上下，或者三种状态，

#### 如何复现（请务必完整填写下面内容）：

react

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.9.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
新版本已经有三种态切换，请升级到最新版本。

1. 未选中，有个示意可以点击排序的 icon
2. 已选中，且为正序排列
3. 已选中，且为倒序排列

目前点击那个区域将会按顺序切换这三种状态
