### ISSUE TITLE
input-tree 无法自动填充其他字段

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#4322]
#### 描述问题：

input-tree 无法自动填充其他字段 ，只能上传value 

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lurunze1226** [comment]
请描述具体一些

**Comment by lengqingfeng** [comment]
> 请描述具体一些
现在上次参数默认value，我想把另一个字段code 自动填充进去，现在做不到啊。

**Comment by lurunze1226** [comment]
可以在form的提交接口里做数据映射，或者使用reqeustAdaptor自定义提交字段

**Comment by jiasijiamn** [comment]
请问这个问题解决了吗 我也遇到这个问题了，除了value 还想多获取一个字段，求解答，非常感谢

**Comment by 2betop** [comment]
> 请问这个问题解决了吗 我也遇到这个问题了，除了value 还想多获取一个字段，求解答，非常感谢

有两种方式
1. inputTree 去修改值给是为 joinValues: false, 这样它就是对象，或者对象数组格式，里面既有 label 也有 value
2. 配置 autoFill，在点选 tree 的时候把选项的其他值填充到表单的其他字段里面。

由于时间跨度比较大，先 close 了，有问题再 reOpen
