### ISSUE TITLE
数据作用域问题

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#433]
`page `等价于全局变量，因为顶级渲染器就是它，所以下面的所有组件都能用到这个里面的数据。
   `params `中的数据 如果地址栏中也携带了参数，也会 merge 到该层的数据中。

可否给一个示例，如何用 `params` 取地址栏中也携带了参数?

**Comment by icodingx** [comment]
@2betop 可否给一个示例，如何用 params 取地址栏中也携带了参数? 感谢 :-)

**Comment by RickCole21** [comment]
tpl使用${xxx}

或者xxxOn里使用data.xxx
