### ISSUE TITLE
InputImage 上传图片组件

### ISSUE THREAD

**Issue by asd018232** [baidu/amis#4330]
#### 描述问题：

InputImage 上传图片组件，在手机移动端上使用。当multiple属性设置为true，进行多选操作时，在安卓手机上有如下问题（苹果手机没有问题）：
1）没有“拍照”选项，只能选择系统图片
2）无法多选文件，一次只能选择一个文件

1. 你是如何使用 amis 的？
js `sdk`

2. amis 版本是什么？
1.8.0

3. 粘贴有问题的完整 `amis schema` 代码：
{
        "type": "input-image",
        "name": "image",
        "label": "image",
        "multiple": true
      }

**Comment by 2betop** [comment]
新版本将开放 capture 属性配置，通过此属性可控制
