### ISSUE TITLE
请问 requestAdaptor 可以取消本次请求么 如果符合某个条件则取消本次请求

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#4344]
#### 描述问题：
请求适配器中 可以取消本次请求
现在ruturn null 会按照原先参数正常提交
如果runturn {}等其他方法会报错

**Comment by luanwulin** [comment]
我也遇到这个问题，目前是配合sendOn来判断是否发起请求了

**Comment by jiangjun316** [comment]
我也遇到了这个问题。。。求官方回应

**Comment by erguotou520** [comment]
请问后来怎么解决的？

**Comment by 2betop** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E6%8B%A6%E6%88%AA%E8%AF%B7%E6%B1%82
