### ISSUE TITLE
crud分页有问题 切换页号的时候 perPage自动变成10

### ISSUE THREAD

**Issue by cbz20000** [baidu/amis#4348]
#### 描述问题：
v1.9.0的crud分页控件有问题 无论一开始程序指定perPage 还是在页面上手工选择其他perPage 切换页号的时候 perPage自动变成10

#### 截图或视频：
![image](https://user-images.githubusercontent.com/79636715/168421843-e1e868f7-8f51-4834-8949-eac087040996.png)
![image](https://user-images.githubusercontent.com/79636715/168421848-c58bcaef-b7da-4cdc-9259-8158903b72cd.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
sdk
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v1.9.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by cbz20000** [comment]
@nwind @luckyufei 这个问题比较严重，官网crud demo页面也能复现

**Comment by Chen-Wendong** [comment]
"url": "/xxxx/${xxxx}?page=${page}&perPage=${perPage}",

url 要设置 perPage

**Comment by dickchy** [comment]
我临时改了js，目前暂时好了，期待官方修复

lib\renderers\CRUD.js
855行
在renderPagination的时候，将perPage作为参数传进去
let perPage = store.perPage;
return (react_1.default.createElement("div", { className: cx('Crud-pager') }, render('pagination', {
    type: 'pagination'
}, (0, tslib_1.__assign)((0, tslib_1.__assign)({}, extraProps), { activePage: page, lastPage: lastPage,perPage:perPage, hasNext: store.hasNext, mode: store.mode, onPageChange: this.handleChangePage }))));


lib\components\Pagination.js
Pagination.prototype.render
在函数最开始，将state改成props一致的
if(_a.perPage) {
  this.state.perPage = _a.perPage;
}

**Comment by lurunze1226** [comment]
[fix](https://github.com/baidu/amis/commit/8829f6346f58fc79f1d5c6f1701a70cf6ec15c42) 已经修复了

**Comment by cbz20000** [comment]
> [fix](https://github.com/baidu/amis/commit/8829f6346f58fc79f1d5c6f1701a70cf6ec15c42) 已经修复了

谢谢 我下源码 自己编译生成sdk吧

**Comment by cbz20000** [comment]
> 我临时改了js，目前暂时好了，期待官方修复
> 
> lib\renderers\CRUD.js 855行 在renderPagination的时候，将perPage作为参数传进去 let perPage = store.perPage; return (react_1.default.createElement("div", { className: cx('Crud-pager') }, render('pagination', { type: 'pagination' }, (0, tslib_1.__assign)((0, tslib_1.__assign)({}, extraProps), { activePage: page, lastPage: lastPage,perPage:perPage, hasNext: store.hasNext, mode: store.mode, onPageChange: this.handleChangePage }))));
> 
> lib\components\Pagination.js Pagination.prototype.render 在函数最开始，将state改成props一致的 if(_a.perPage) { this.state.perPage = _a.perPage; }

赞一个
