### ISSUE TITLE
chart组件引用echarts后高度宽度都不能铺满，或者说可以增加滚动条吗

### ISSUE THREAD

**Issue by hcf1997** [baidu/amis#4365]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...
![image](https://user-images.githubusercontent.com/86106459/168756206-5f29dbce-8d0c-44f4-a9b9-a21c53175315.png)

**Comment by wibetter** [comment]
@hcf1997 新版amis-editor支持可视化调整chart组件宽高，旧版的话，也可以在左侧code面板直接调整：
<img width="1631" alt="image" src="https://github.com/baidu/amis/assets/11958920/8429e11d-ccb4-49f8-a1a1-12b3ea29ad48">
