### ISSUE TITLE
GET请求的多值参数被错误地stringify

### ISSUE THREAD

**Issue by vekit-cn** [baidu/amis#4368]
#### 描述问题：

如 get:/api/foo?bar=1&bar=2&bar=3这样的请求，会被api处理为: /api/foo?bar[0]=1&bar[1]=2&bar[2]=3

这就不符号RFC的规范了，希望在这种情况下不要转化

**Comment by liuxiaoyue** [comment]
如：/api/query?where.user_id.eq=3&where.id.eq=4' 会被转换成/api/query?where[user_id][eq]=3&where[id][eq]=4, 这种 情况下也被转换了

**Comment by liuxiaoyue** [comment]
如果数据映射中的 key 不想被处理路径则需要配置 `convertKeyToPath` 为 false 如：

```
"api": {
    "method": "post",
    "url": "/api/mock2/form/saveForm",
    "convertKeyToPath": false,
    "data": {
        "a.b": "${name}",
        "c[d]": "${name}"
    }
}
```

这样发送的数据格式为

```
{
  "a.b": "xxx",
  "c[d]": "xxx"

**Comment by vekit-cn** [comment]
感谢，已解决
