### ISSUE TITLE
CRUD新建表单的弹框中出现报错，但不影响使用，认为可能是sdk内部的代码没有在合适的位置打分号导致

### ISSUE THREAD

**Issue by OwEnXiaoMing** [baidu/amis#4369]
#### 描述问题：

CRUD中增加表单的弹框会在左下角显示（intermediate value）（intermediate value）（intermediate value）.forEach is not a function

#### 截图或视频：
<img width="333" alt="crud" src="https://user-images.githubusercontent.com/49831490/168799854-1cd22bee-2347-4976-9cfc-81d333d7c024.png">

**Comment by 2betop** [comment]
不能复现了，由于是时间跨度比较大，先关了，有问题再 reOpen
