### ISSUE TITLE
remark上方的popup位置偏移

### ISSUE THREAD

**Issue by asahi-luna** [baidu/amis#437]
这个是bug还是要设置某个属性？

**Comment by asahi-luna** [comment]
![remark](https://user-images.githubusercontent.com/42441687/72231571-2e684100-35f7-11ea-8df2-bf53e44cf868.jpg)

**Comment by 2betop** [comment]
看来是 bug 了，有 margin 的情况下位置出错了。

**Comment by asahi-luna** [comment]
我使用的是jssdk，使用文档上的例子并且未做修改，还是有这个问题，请问有什么解决方案吗？

**Comment by 2betop** [comment]
先换成 labelRemark 即把 remark 改名为 labelRemark

**Comment by asahi-luna** [comment]
还是一样的问题诶

**Comment by asahi-luna** [comment]
![labelRemark](https://user-images.githubusercontent.com/42441687/72234828-c7a05300-3609-11ea-874f-55f162011d58.jpg)

**Comment by 2betop** [comment]
貌似不能复现，https://baidu.github.io/amis/form/mode 使用上有什么特殊的地方吗？

**Comment by asahi-luna** [comment]
是jssdk的方式使用的，代码与效果如下
![code](https://user-images.githubusercontent.com/42441687/72401408-e4ae6080-3786-11ea-8c41-733feba5a9d2.jpg)
![offset](https://user-images.githubusercontent.com/42441687/72401729-cf860180-3787-11ea-8a19-6e81c9b5ee0d.jpg)

**Comment by 2betop** [comment]
知道了

**Comment by 2betop** [comment]
修复了

**Comment by asahi-luna** [comment]
好的，感谢解答
