### ISSUE TITLE
 CRUD组件设置默认分页参数perPage在切换到别的页数会失效，perPage变成10

### ISSUE THREAD

**Issue by aminfly** [baidu/amis#4375]
#### 描述问题：

CRUD组件设置默认分页参数perPage在切换到别的页数会失效，perPage变成10，官方文档现在的例子就存在这个问题，麻烦尽早解决

#### 截图或视频：
设置默认perPage:50 在 第1页正常:
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/105775021/168979826-9d8ec78a-d0b6-408e-8daf-14d69fd11a8b.png">

切换到第2页perPage变成了10:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/105775021/168979877-271f8f7e-915e-4d3f-96fe-8d9a9b8a82c4.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.9.0 ~ 1.9.1-beta.1，包括最新的beta版本都有问题

4. 粘贴有问题的完整 `amis schema` 代码：
```
    "defaultParams": {
      "perPage": 50
    },
```

5. 操作步骤
配置参数，然后翻页就能复现

**Comment by OwEnXiaoMing** [comment]
遇到了同样的问题

**Comment by lurunze1226** [comment]
`amis@1.9.1-beta.11` 升级一下amis版本吧

**Comment by aminfly** [comment]
好的，感谢
