### ISSUE TITLE
crud组件导出excel时不能读取变量

### ISSUE THREAD

**Issue by 4ggg** [baidu/amis#4385]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
使用crud组件的导出excel功能时，对于在columns内配置的label若是变量，则导出的excel中的表头名也为变量。

#### 截图或视频：
![image](https://user-images.githubusercontent.com/43903751/169039663-82644710-3f5a-4b5a-937b-23d7430b8499.png)

#### 如何复现（请务必完整填写下面内容）：
点击【导出 engine 和  browser 列】按钮

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
 经测试1.9.0 及 以下 版本均有此问题

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "data":{
    "aa":"测试1",
    "bb":"测试2"
  },
  "body": {
    "type": "crud",
    "syncLocation": false,
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample",
    "headerToolbar": [
      {
        "type": "export-excel",
        "label": "导出 engine 和  browser 列",
        "columns": [
          "engine",
          "browser"
        ]
      }
    ],
    "columns": [
      {
        "name": "id",
        "label": "ID"
      },
      {
        "name": "engine",
        "label": "${aa}"
      },
      {
        "name": "browser",
        "label": "${bb}"
      }
    ]
  }
}
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 4ggg** [comment]
可以暂时通过自定义到处列去解决：https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E5%87%BA%E5%88%97

**Comment by nwind** [comment]
已经支持了 #6824

**Comment by wiktsweet** [comment]
为什么表格有值,没有导出呢
