### ISSUE TITLE
amisScope问题：  在 SDK 下 与 React 下表现不同

### ISSUE THREAD

**Issue by hyzx86** [baidu/amis#4388]
React 下 amisScope.updateProps is not a function

**Comment by hyzx86** [comment]
这种情况 怎么更新 schema 啊？

**Comment by hyzx86** [comment]
文档里 说 // 功能和前面 SDK 的 amisScoped 一样
但是实际这个对象里面没有这个方法~
scopeRef: (ref,a,b,c) =>{
          console.log('ref,a,b,c: ', ref,a,b,c); 
          this.props.amisMounted(ref,a,b,c) // 功能和前面 SDK 的 amisScoped 一样
        }    


![image](https://user-images.githubusercontent.com/15613121/169195861-4c9de921-594c-447d-bd99-89cf4d5b568a.png)

**Comment by hyzx86** [comment]
SDK scope ：

![image](https://user-images.githubusercontent.com/15613121/169203224-14e1bf8b-29e6-4e96-9fa8-3c2efba6039d.png)

**Comment by myacelw** [comment]
@nwind 我们也遇到同样的问题，能帮忙回复下吗？

**Comment by hyzx86** [comment]
在源码里面找到了答案。。 updateProps 本身就是SDK组件 扩展出来的方法~

**Comment by zsea** [comment]
@hyzx86 你这个问题是怎么解决的呀，我需要在App里更新右边主内容

**Comment by hyzx86** [comment]
更新Schema 就好了啊

**Comment by zsea** [comment]
@hyzx86 谢谢啊，哥，我搞写了，我原来启用了```StrictMode```模式，所以一直报错。
