### ISSUE TITLE
table-operation-action 弹出 drawer 的 form，form的 initApi 取不到table 行的值？

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#439]
```
form的 initApi 取不到table 行的值？
"initApi": "/subsys/apiexec/7/37?prod_id=#{ProdID}&num=1",

实际生成的请求，成了这个样子
/subsys/apiexec/7/37?prod_id=
```
@2betop 请教 ！！

**Comment by icodingx** [comment]
`table` 可以与`service`搭配，基于`service`的`api`监听`category`刷新`table`数据，而`crud`不行！
`category`的`tree`已经在`wizard`，又不能包裹一个form指定 `target`到`table`，我的表述清楚吗？

**Comment by icodingx** [comment]
`table`换成`crud`，而`crud`的`api`又不能监听`category`的变化，如何是好？@2betop

**Comment by 2betop** [comment]
不应该是这样取吗？`${ProdID}`

**Comment by icodingx** [comment]
这样取不到呢 
form的 initApi 取不到table 行的值？
"initApi": "/subsys/apiexec/7/37?prod_id=#{ProdID}&num=1",

实际生成的请求，成了这个样子
/subsys/apiexec/7/37?prod_id=

**Comment by 2betop** [comment]
不是用 `#` 是用 `$`, `#` 起是 hash，本来就不会发送 hash 部分到服务端。

**Comment by icodingx** [comment]
了解，头晕了
