### ISSUE TITLE
下载请求  乱码 不自动下载  Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#4391]
如题
请问如何解决  直接访问接口链接   浏览器会自动下载  但是用行为按钮就不行

**Comment by lhtuling** [comment]
网络面板中响应头明明存在,但是 调试时候发现接受到的response的headers里面并没有  这是什么原因!
![image](https://user-images.githubusercontent.com/44140500/169205681-ba5d15df-ae44-43c5-8daa-39bebac63cb6.png)
![image](https://user-images.githubusercontent.com/44140500/169205685-f7bcc527-9d21-4ff1-8e0c-dde525cd7ba9.png)

**Comment by nwind** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD  或者 actionType 用 download

**Comment by lhtuling** [comment]
明白了 补充下 用这个方式  更好用
https://aisuda.bce.baidu.com/amis/zh-CN/components/action#%E7%9B%B4%E6%8E%A5%E8%B7%B3%E8%BD%AC
