### ISSUE TITLE
事件动作-  reload   传递参数

### ISSUE THREAD

**Issue by weibin529** [baidu/amis#4402]
期望  事件动作 reload  能支持target从而支持传递参数，即支持如下配置
"onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "reload",
              "target": "form-reload?name=${userName}"
            }
          ]
        }
      }

**Comment by hsm-lv** [comment]
看下文档的用法，应该是这样的
```json
"onEvent": {
"click": {
"actions": [
{
"actionType": "reload",
"componentId": "form-reload",
"args": {
"name": "${userName}"
}
}
]
}
}
```

详细：https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E5%88%B7%E6%96%B0
https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E5%B1%9E%E6%80%A7%E8%A1%A8
