### ISSUE TITLE
可以在 wizard 的 action区域扩展按钮吗？

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#441]

**Comment by 2betop** [comment]
steps 成员里面可以定义 actions

**Comment by icodingx** [comment]
影响默认的 `actionPrevLabel` `actionFinishLabel ` 吗？

**Comment by 2betop** [comment]
影响，但是没关系，actionType: 'prev' 就是后台， actionType: 'next' 就是下一步，你要保留就自己配置一个。
