### ISSUE TITLE
严格模式下的全局toast无法使用，amisLib.toast.success('消息通知');

### ISSUE THREAD

**Issue by hoyancy** [baidu/amis#4418]
#### 描述问题：

严格模式下无法使用无法使用全局toast 消息提示

#### 截图或视频：

![image](https://user-images.githubusercontent.com/10858916/169634336-e15f7293-ed35-495d-8a46-1e9882924433.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v1.6.1-beta.1

4. 粘贴有问题的完整 `amis schema` 代码：
```
    let amisLib = amisRequire('amis');
    amisLib.toast.warning('消息通知');
```

**Comment by nwind** [comment]
没复现，后续又再开，另外严格模式目前可能是有问题不建议用
