### ISSUE TITLE
Crud的Columns 能用service请求吗？

### ISSUE THREAD

**Issue by zimo888** [baidu/amis#442]
Hello，
  我想使用"动态加载页面“ 功能，通过接口返回Crud 的Columns的Schema ,试验了一下下面的JSON格式好像不行 。

```javascript
                    "type": "crud",
                    "draggable": false,
                    "api": '', 
                    "columns": {
                         "type":"service",
                         "schemaApi":"xxxxx"
                   }
```

**Comment by 2betop** [comment]
参考这个：https://baidu.github.io/amis/services/schema

你这个用错了，你只需要一个 service 就够了，crud 的配置由 schemaApi 返回。

**Comment by zimo888** [comment]
整个CRUD的配置返回是没问题，部分返回不行么？ 我想着后台添加，管理动态列，然后接口返回。

**Comment by 2betop** [comment]
不支持这种用法，渲染器是作为一个整体返回的。

**Comment by zimo888** [comment]
我想明白了，现在的CRUD的 Columns 是静态的，意味着当后台字段变化的时候，Columns无法通过Service 获取，除非整个CRUD Schema都由后台拼好返回，不过这样就不是JSON Schema管理了，会前后端耦合，以后设计器没法配置。
想实现这个Case 可能得自定义一个组件支持了。

**Comment by 2betop** [comment]
如果你只是单纯的让操作按钮可以根据不同的类型出现不同的按钮，这个只需要把所有可能的按钮配置出来，然后加上 visibleOn 显隐切换就够了。

**Comment by zimo888** [comment]
不是按钮显隐， 当系统的每个实体是可以后台配置的，系统的字段和字段类型也是动态的，布局也是动态的(Amis负责)，都由用户来自行配置，在这种无法预知有多少实体，有什么列的场景下。去通过元数据动态渲染页面。
这个时候JSON的Columns就是个Service，是要在渲染的时候去加载的。

**Comment by 2betop** [comment]
好吧，目前只能整个 crud 都 schemaApi返回了。

**Comment by zimo888** [comment]
感谢回复，Amis真是个好框架，准备读完源码后转一下ReactNative，尝试一下移动端支持，
