### ISSUE TITLE
CRUD的itemAction支持自定义单行的双击事件

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#4426]
#### 是否关联于某个问题吗：
没办法实现CRUD里面，双击多行事件

#### 预期的解决方案：
目前CRUD的itemAction可以支持自定义控制单行的单击事件，希望增加自定义单行的双击事件。例如：

"itemAction": {
  "type": "button",
  "onDbClick": "console.log(data);"
}

#### 其他可接受方案：
可以实现此需求的其他方案也可

#### 任何附加信息：
无

**Comment by hsm-lv** [comment]
已经支持
