### ISSUE TITLE
input-date-range开始时间大于结果时间

### ISSUE THREAD

**Issue by smile1102** [baidu/amis#4430]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

![image](https://user-images.githubusercontent.com/12440651/169811338-017daa48-099f-4c1a-a549-d93b57119266.png)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.9及以上beta 版本，都存在

3. 粘贴有问题的完整 `amis schema` 代码：
官网文档示例

4. 操作步骤
1、选开始时间、结束时间
2、再选开始时间、结束时间，实际是选择的结束时间
3、点击开始时间输入框，再选开始时间

**Comment by nwind** [comment]
输入框下面有条线代表当前选择是开始还是结束时间，可以点击切换
