### ISSUE TITLE
wizard组件 step 内定义了 crud ，如何将crud的数据合并到 wizard 呢？

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#444]

**Comment by 2betop** [comment]
crud 不能放到 wizard 里面，如果你要放表格，放 table 好了。

**Comment by icodingx** [comment]
wizard 放了 table ，在table 的 operation 里定义了 drawer ，drawer里定义了 crud，crud的 operation定义了 form，最后想把form修改的 crud的数据 合并到 wizard 中

**Comment by catchonme** [comment]
@icodingx 你把 json schema 发出来看看

**Comment by catchonme** [comment]
是 drawer 中的 crud 修改了，wizard 中的 table 的数据没有更新是吗？

如果是的话，可以在 drawer -> crud -> operation 中的form的配置中增加 reload 配置，如`reload: wizard 中table 的 name` ，这样当form添加了数据后会自动刷新 wizard 中的 table 重新拉取数据。

**Comment by RickCole21** [comment]
没回复，先关了
