### ISSUE TITLE
跨请求如何实现数据共享问题

### ISSUE THREAD

**Issue by steven-sun** [baidu/amis#4450]
这是另一个issue( #1350 )所述问题的副本

请问页面提交时的请求适配器中怎样获取页面初始化时请求到的数据呢？

或者说，能否提供一个机制，让请求适配器或响应适配器在数据域中创建数据呢？

**Comment by luanwulin** [comment]
我是曲线救国，，把需要的数据放到query或者data中声明好，然后再适配器里面去取

**Comment by 2betop** [comment]
通过 context 变量可获取，已合入 pr，等待下一个版本 https://github.com/baidu/amis/pull/7456
