### ISSUE TITLE
React方式下如何使用amis的公共方法

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#4457]
#### 实现场景：
想要直接调用amis的toast提示信息

#### 存在的问题：
只发现了SDK的使用方法，没有找到React要如何使用
![image](https://user-images.githubusercontent.com/37805363/170443099-59a50cb0-7a7a-4164-800a-bdcf080974fa.png)

#### 当前方案：
无

**Comment by Agzhen** [comment]
遇到了一样的疑问，请问可以使用了吗
