### ISSUE TITLE
弹窗中提交表单如何才能带上原表单的数据？

### ISSUE THREAD

**Issue by xedcoing** [baidu/amis#4476]
#### 实现场景：
在表单中弹窗一个新的表单，在弹窗中使用ajax提交表单如何才能带上原表单的数据？
发起请求body里只有弹窗的表单数据，使用数据映射 {"&": "$$" } 也没有效果

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
现阶段只能通过 `{'&': '${__super.__super}'}` 能获取到原始数据，表单编辑的原始数据，即修改之前的数据，如果要发送最新的还得 `{'&': '${__super.__super}', 'newKey': '${newKey}'}`
