### ISSUE TITLE
combo能否支持每个item自定义deleteBtn

### ISSUE THREAD

**Issue by smile1102** [baidu/amis#4479]
#### 描述问题：

现在combo自定义deleteBtn是对整个items有效，没法单个item单独自定义。
存在这样的情况，某个item不能删除，某个item可以删除的情况，现在不支持，能否优化?

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.9

**Comment by koala-wei** [comment]
求助

**Comment by jackhansir** [comment]
同上，假如有回显数据，回显数据不能删除，还能正常添加新数据，此时无法禁用回显数据的删除操作，虽然可以通过判断做提示处理，但是不符合逻辑
![93CD6A03-DD6B-4880-B031-1BE4CB16D098](https://user-images.githubusercontent.com/26846260/217977165-5470ccaf-98e5-439a-abe6-bd4b9a1895c1.png)

**Comment by hsm-lv** [comment]
https://baidu.github.io/amis/zh-CN/components/form/combo#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%A0%E9%99%A4%E6%8C%89%E9%92%AE
