### ISSUE TITLE
需求：希望增加项目 components 组件的文档

### ISSUE THREAD

**Issue by CareyToboo** [baidu/amis#448]
希望增加components 目录下组件的 使用文档，就像 `ant`文档一样。

官方文档比较详细的只有 `renderers 渲染器手册` 文档与示例。如果不使用renderers, 直接使用 `components` 组件，现在不直观。比如 `Tabs、Layout、Toast` 等等...都是直接看 `amis` 源码。写一个admin系统，确实需要很多组件。如果是 amis 组件库存在的，尽量直接拿来用，减少重复开发。

因此希望大佬，空了可以考虑，增加`components`组件的文档与示例。

**Comment by RickCole21** [comment]
这个应该是针对开发者的文档，可能要迟一些才能出了

**Comment by nwind** [comment]
这个属于内部代码，不保证后续版本兼容性，最好通过源码了解方便后续升级改造
