### ISSUE TITLE
select多选change事件获取已选数据不对

### ISSUE THREAD

**Issue by smile1102** [baidu/amis#4480]
#### 描述问题：

select多选的情况下，change事件触发时，获取已选数据不对

#### 截图或视频：

![image](https://user-images.githubusercontent.com/12440651/170699559-b62f2b55-9af5-462f-b64b-17cd25702a03.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.9

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "body": [
      {
        "label": "选项",
        "type": "select",
        "name": "select",
        "multiple": true,
        "options": [
          {
            "label": "A",
            "value": "a"
          },
          {
            "label": "B",
            "value": "b"
          },
          {
            "label": "C",
            "value": "c"
          }
        ],
        "onEvent": {
          "change": {
            "actions": [
              {
                "actionType": "ajax",
                "args": {
                  "api": {
                    "method": "get",
                    "url": "/url",
                    "data": {
                      "ids": "${select}"
                    }
                  }
                }
              }
            ]
          }
        }
      }
    ]
  }
}
```

4. 操作步骤
选择之后，触发ajax，已选的数据没有获取到

**Comment by hsm-lv** [comment]
> #### 描述问题：
> select多选的情况下，change事件触发时，获取已选数据不对
> 
> #### 截图或视频：
> ![image](https://user-images.githubusercontent.com/12440651/170699559-b62f2b55-9af5-462f-b64b-17cd25702a03.png)
> 
> #### 如何复现（请务必完整填写下面内容）：
> 1. 你是如何使用 amis 的？
>    `sdk`
> 2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
>    1.9
> 3. 粘贴有问题的完整 `amis schema` 代码：
> 
> ```
> {
>   "type": "page",
>   "body": {
>     "type": "form",
>     "debug": true,
>     "body": [
>       {
>         "label": "选项",
>         "type": "select",
>         "name": "select",
>         "multiple": true,
>         "options": [
>           {
>             "label": "A",
>             "value": "a"
>           },
>           {
>             "label": "B",
>             "value": "b"
>           },
>           {
>             "label": "C",
>             "value": "c"
>           }
>         ],
>         "onEvent": {
>           "change": {
>             "actions": [
>               {
>                 "actionType": "ajax",
>                 "args": {
>                   "api": {
>                     "method": "get",
>                     "url": "/url",
>                     "data": {
>                       "ids": "${select}"
>                     }
>                   }
>                 }
>               }
>             ]
>           }
>         }
>       }
>     ]
>   }
> }
> ```
> 
> 4. 操作步骤
>    选择之后，触发ajax，已选的数据没有获取到

可以直接通过事件对象获取选中的数据，event.data.value，如下：

```json
{
  "type": "page",
  "body": [
    {
      "type": "form",
      "debug": true,
      "body": [
        {
          "label": "选项",
          "type": "select",
          "name": "select",
          "multiple": true,
          "options": [
            {
              "label": "A",
              "value": "a"
            },
            {
              "label": "B",
              "value": "b"
            },
            {
              "label": "C",
              "value": "c"
            }
          ],
          "onEvent": {
            "change": {
              "actions": [
                {
                  "actionType": "ajax",
                  "args": {
                    "api": {
                      "method": "get",
                      "url": "/url",
                      "data": {
                        "ids": "${event.data.value}"
                      }
                    }
                  }
                }
              ]
            }
          },
          "id": "u:6ac396944fa1"
        }
      ],
      "id": "u:e718eec74f1a"
    }
  ],
  "id": "u:97a608351c3f"
}
```

**Comment by smile1102** [comment]
get
