### ISSUE TITLE
crud组件autoFillHeight  开启 并且操作列设置   "fixed": "right",会导致显示异常

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#4481]
如图
![image](https://user-images.githubusercontent.com/44140500/170700153-f92c93f3-0892-4101-9755-f81015a25959.png)

配置如下
![image](https://user-images.githubusercontent.com/44140500/170700231-44c585b0-dc8c-44ae-a82d-0c4ea099634b.png)
![image](https://user-images.githubusercontent.com/44140500/170700249-ba645db5-d57b-4e42-a36b-c301fff6d804.png)

**Comment by dsdzjgz** [comment]
遇到相同问题了，只要autoFillHeight: true和固定列同时设置了，table不出现纵向滚动时正常。一旦table出现纵向滚动，固定列就会全部显示，不能联动。
![image](https://user-images.githubusercontent.com/76680520/172980577-904196c7-a449-45f3-bc4c-1e2c851edc71.png)

**Comment by hsm-lv** [comment]
merged to https://github.com/baidu/amis/issues/7606
