### ISSUE TITLE
Group中放入input组件，disabled无效，但是disabledOn表达式可以

### ISSUE THREAD

**Issue by webboyvc** [baidu/amis#4483]
#### 描述问题：
使用以下代码，text1还是可以编辑

{
  "type": "page",
  "body": {
    "type": "form",
    "body": [
      {
        "type": "group",
        "body": [
          {
            "type": "input-text",
            "name": "text1",
            "label": "文本1",
            "disabled": true
          },
          {
            "type": "input-text",
            "name": "text2",
            "label": "文本2"
          }
        ]
      }
    ]
  }
}

**Comment by littledenny** [comment]
是App端的问题嘛？

**Comment by 2betop** [comment]
新版本已没问题，请升级到最新版本，如有问题请 reOpen。
