### ISSUE TITLE
Pagination分页组件强化建议

### ISSUE THREAD

**Issue by lonllua** [baidu/amis#4487]
#### 是否关联于某个问题吗：
pagination组件目前似乎不够强大，我无法为total、activePage、perPage等动态赋值，如

`{
                    "type": "pagination",
                    "layout": "total,perPage,pager,go",
                    "mode": "normal",
                    "activePage": 1,
                    "total": "${total}"
                    "perPage": 10,
                    "maxButtons": 7,
                    "showPerPage": true,
                    "perPageAvailable": [
                      10,
                      20,
                      50,
                      100
                    ],
                    "showPageInput": true,
                    "disabled": false
                  }`

我不明白，为何其他组件都能正常使用表达式获取一些变量值，而分页组件确不可以。
另外我也想pagination组件能够reload指定组件，这样我就能和list组件结合使用。
当然我知道crud组件有list模式，但有些场景使用crud并不够灵活。

#### 预期的解决方案：
我想使用${total}等为分页组件相关属性赋值

#### 任何附加信息：
我的描述基于amis1.9.0版本，使用方法是jssdk。如果是我使用姿势不对，还请告知，谢谢！

**Comment by 2betop** [comment]
新版本已经支持，请更新到最新版本，有问题再 reOpen

**Comment by gfl1** [comment]
2.8.0版本有解决吗？
