### ISSUE TITLE
jssdk使用  icon-picker 可用的icon为什么这么少

### ISSUE THREAD

**Issue by westeast** [baidu/amis#449]
![image](https://user-images.githubusercontent.com/2304604/73432863-90a69d00-437e-11ea-8e5d-ca2f354a01dd.png)

**Comment by 2betop** [comment]
考虑到体积问题，默认只加了几个，但是 jssdk 模式没有口子可以扩充，非 jssdk 模式可以通过以下方式设置。

```js
import {setIconVendor} from 'amis';

setIconVendor([
{
    name: 'Font Awesome 4.7',
    prefix: 'fa fa-',
    icons: [
      'slideshare',
      'snapchat',
      'snapchat-ghost',
      'snapchat-square',
      'soundcloud',
      'spotify',
      'stack-exchange',
      'stack-overflow'
    ]
  }
]);
```

**Comment by westeast** [comment]
> 考虑到体积问题，默认只加了几个，但是 jssdk 模式没有口子可以扩充，非 jssdk 模式可以通过以下方式设置。
> 
> ```js
> import {setIconVendor} from 'amis';
> 
> setIconVendor([
> {
>     name: 'Font Awesome 4.7',
>     prefix: 'fa fa-',
>     icons: [
>       'slideshare',
>       'snapchat',
>       'snapchat-ghost',
>       'snapchat-square',
>       'soundcloud',
>       'spotify',
>       'stack-exchange',
>       'stack-overflow'
>     ]
>   }
> ]);
> ```

jssdk的扩充是否可以加上，如果可以的话，我可以看看源码给加上，我理解应该就是把这个函数也暴露在jssdk中就行了吧。

**Comment by 2betop** [comment]
应该可以 import 到 jssdk 里面。

```
import {setIconVendor} from 'amis';
```
