### ISSUE TITLE
已支持umd模式，vue2,vue3

### ISSUE THREAD

**Issue by h7ml** [baidu/amis#4490]
#### 是否关联于某个问题吗：
看到了很多同学，都没法很好的兼容vue2。于是写个了插件，支持umd模式，支持vue组件化。

#### 预期的解决方案：
- 支持umd模式，直接在html界面调用即可用；
- 支持vue

#### 任何附加信息：
项目地址 https://github.com/h7ml/vue-amis-sdk
预览地址 https://vue-amis-sdk.vercel.app/
npm包地址 https://www.npmjs.com/package/vue-amis-sdk

后期会同步官方amis进行更新支持的

**Comment by beairs** [comment]
小伙子有这个热情挺不错的，希望Amis不会辜负你花那么大力气帮它维护个Vue版

**Comment by wanghuapeng** [comment]
赞，我这边也有这样的需求。试用一下

**Comment by hyzx86** [comment]
赞 ，可惜 Vben 里面样式冲突好多。。大多都是 Antdv 的样式隔离 不如 antdreact 做的好吧。。

**Comment by csjiabin** [comment]
还需要出个vue3

**Comment by csjiabin** [comment]
vite创建vue3项目一堆报错...

**Comment by nwind** [comment]
mark，后续加个。另 vue2 可以试试 https://github.com/aisuda/vue2-amis-demo
