### ISSUE TITLE
响应头内容获取不到  鉴权相关接口 需要从响应头内获取Token 和xToken等信息  但是前端请求拦截器里面没有

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#4494]
如题

![image](https://user-images.githubusercontent.com/44140500/170916636-72317cfa-9bab-4e96-8ef9-a9133a97dacd.png)

但是网络请求里面响应头是有的!

![image](https://user-images.githubusercontent.com/44140500/170916692-002c321c-4917-4ac0-91dc-27756adfdfc9.png)

**Comment by lonllua** [comment]
我想你可以直接重写fetcher，这样http你就能直接接管了

**Comment by lhtuling** [comment]
> 我想你可以直接重写fetcher，这样http你就能直接接管了

感谢大佬提醒   是个方案  然后用axios接管下   
之前搞过  现在碰到还没想起来 这个方式

**Comment by TonyZXK** [comment]
后端配置：Access-Control-Expose-Headers 。
