### ISSUE TITLE
当 option 设置了较高的 menuTpl 之后在pc端显示不正常

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#4495]
#### 描述问题：

当高度超过了Select-option样式设定的值之后显示不正常，简单测试一下，只要把height设置为auto就可以了
这里不太清楚为什么要设定一个固定的高度，可否设置min-height来取代直接设置height？

#### 截图或视频：

![image](https://user-images.githubusercontent.com/3793855/170928821-d40075cb-ea1d-48d7-83de-18bfb67c35f5.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.9.1-beta.12

4. 粘贴有问题的完整 `amis schema` 代码：
```js
          {
            label: 'xxx',
            type: 'select',
            source: {/*略*/},
            menuTpl:
              '<div>' +
              '<div style="font-weight:bold;">$value</div>' +
              '<div style="color: gray;">$address</div></div>',
          }
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
新版本已经不是固定高度了，请升级版本

<img width="1105" alt="image" src="https://github.com/baidu/amis/assets/2698393/124a43eb-df4f-4aa2-9053-eccb2dd02069">
