### ISSUE TITLE
Amis 官网用 Safari 无法浏览，白屏

### ISSUE THREAD

**Issue by beairs** [baidu/amis#4496]
起码一周前开始就这样了，持续这么长时间了，都还这样，无法理解。

用Safari打开官网，直接白屏，如图所示
https://aisuda.bce.baidu.com/amis/zh-CN/docs/index

<img width="260" alt="image" src="https://user-images.githubusercontent.com/21998638/170932630-9a9ab786-d77d-42ea-bfe3-ac1ff3106209.png">

<img width="695" alt="image" src="https://user-images.githubusercontent.com/21998638/170932197-ecc3213b-e9ca-4903-8823-ae7d0070fef5.png">

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/21998638/170932279-5851041b-1ef9-4b56-9726-118234241373.png">

**Comment by wibetter** [comment]
这个问题已经修复了，应该是文档还没有更新，可以先用下github文档：https://baidu.github.io/amis/zh-CN/docs/index。
bug的原因是因为有代码用到了一个正则表达式（零宽断言）在Safari中不支持。
