### ISSUE TITLE
生成jssdk时报错：error TS5023: Unknown compiler option 'allowjs'.

### ISSUE THREAD

**Issue by westeast** [baidu/amis#450]

**Comment by 2betop** [comment]
这个是 typescript 的版本问题，新版本可以支持。不过，这个报错貌似是可以忽略，依然可以生成类型文件。

**Comment by westeast** [comment]
> 这个是 typescript 的版本问题，新版本可以支持。不过，这个报错貌似是可以忽略，依然可以生成类型文件。

好的，多谢
