### ISSUE TITLE
暗色主题能否参考github的暗色主题呢。。。

### ISSUE THREAD

**Issue by gillbates** [baidu/amis#4503]
#### 是否关联于某个问题吗：

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/783547/171102558-1c94b5ab-6ee1-434d-b762-68608644722c.png">

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/783547/171102606-4a4625a3-0c81-4d90-920a-0294098360df.png">

现在云舍的白色主题已经很好看啦，希望开发组的老铁们能提供一个到点了自动换颜色的参数，以及提升下暗色主题的配色。。。

现在的这种土黄色的背景色。。。确实感觉有点拉跨。。。

不知道可以否借鉴github的暗色主题的配色。。。

#### 预期的解决方案：

<img width="1683" alt="image" src="https://user-images.githubusercontent.com/783547/171102827-4d27e746-4094-4658-b1ba-f402e3ad58d4.png">

感觉github的暗色主题就很舒服。。。

**Comment by h7ml** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/style/index 你说的应该是这个

**Comment by cmdares** [comment]
https://element-plus.gitee.io/zh-CN/component/dialog.html
对比下element的暗色系的配色感觉，研究下。
调节这个东西需要花功夫，一个组件一个组件的调，最好有个专业点的美工帮着把关。

**Comment by gillbates** [comment]
感觉element的色系和github的色系都很漂亮，现在那个土黄土黄的。。。有点扎眼睛。。。

**Comment by richmonde** [comment]
我的深色模式背景色没有改变，请问各位碰到过这个问题吗？

**Comment by hyzx86** [comment]
同问~~

**Comment by hyzx86** [comment]
现在 dark 主题 木有了？

**Comment by nwind** [comment]
之前改过一次，不过现在没空维护了，可以自己替换变量，相关变量不多

**Comment by hyzx86** [comment]
呃。。注意到现在的主色似乎要用 brand-x 来调整了
但是只调整 brand-x 还不够 还有一系列的其他 cssvar 要调整， 
sample 中的 主题编辑器也不好使了~
