### ISSUE TITLE
Select 选择器在多选模式下选项展示不全

### ISSUE THREAD

**Issue by TeCHiScy** [baidu/amis#4514]
#### 描述问题：

Select 选择器在普通多选模式下长选项展示不全，会以缩略方式展示。但是在分组多选模式下，选项能展示全。预期是无论在普通还是分组多选模式下选项都能展示全。

#### 截图或视频：

普通多选：
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/741195/171340171-af2db1a2-ad3c-44e6-9ff5-b2e3c59e3e33.png">

分组多选：
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/741195/171340240-cc907174-cff0-4e0c-a0d3-14cb04fd4039.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.8.0 （使用官网也能复现）

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "body": [
      {
        "label": "选项",
        "type": "select",
        "name": "select",
        "multiple": true,
        "options": [
          {
            "label": "我很长我很长我很长我很长我很长我很长我很长我很长我很长",
            "value": "a"
          },
          {
            "label": "我很长我很长我很长我很长我很长我很长我很长我很长我很长",
            "value": "b"
          },
          {
            "label": "我很长我很长我很长我很长我很长我很长我很长我很长我很长",
            "value": "c"
          }
        ]
      }
    ]
  }
}
```

分组多选时加上 selectMode: "group" 配置

4. 操作步骤
在官网文档 https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select 贴入 schema 即可复现。

**Comment by 2betop** [comment]
分组模式显示有问题，按照内部规范应该是是超出隐藏，如果觉得这个宽度太小可以通过 css 样式调整
`--Form-valueLabel-maxWidth: 7.5rem`
