### ISSUE TITLE
inputTree选中后怎么取消选中状态

### ISSUE THREAD

**Issue by acttq** [baidu/amis#4518]
#### 实现场景：
一个页面，左侧为树形，右侧为crud，初始时crud加载全部，点击左侧树右侧进行筛选，想回到页面初始加载的时候

#### 存在的问题：
点树被选中之后，不知道如何取消选中状态

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

**Comment by lurunze1226** [comment]
树的`value`设置为空就取消选中了

**Comment by 2betop** [comment]
可以配置 `hideRoot` 为 false，这样就会多出来一个顶层节点，点这个顶层节点就是取消选中的效果，这样右侧 crud 传参就会传一个空。额外可以用 `rootLabel ` 来配置文案，具体参考： https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-tree#%E5%B1%9E%E6%80%A7%E8%A1%A8
