### ISSUE TITLE
移动端打开项目后，amis-editor报错：variable:DragEvent？

### ISSUE THREAD

**Issue by duqingyu** [baidu/amis#4520]
#### 描述问题：

在PC端没问题，在手机端打开时通过vConsole看到打印amis-editor报错，项目白屏无法加载

#### 截图或视频：

<img width="413" alt="09977b28c4e66029329a13ae3dec7b5" src="https://user-images.githubusercontent.com/30541930/171541501-93a282fb-305f-4228-a75c-cb0efc0a354d.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
amis版本：1.9.0
amis-editor：4.1.0-beta.4

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
回退低版本还是有问题

4. 操作步骤
项目中只要有import { xxxx } from 'amis-editor'，就直接白屏报错

**Comment by duqingyu** [comment]
ios12.2

**Comment by luanwulin** [comment]
@duqingyu 同样问题，请问下后面解决了么？

**Comment by nwind** [comment]
编辑器不支持移动端，预计是安卓有些 webview 版本较老导致的，要使用 chrome。

我们的解决办法是非开发功能的页面不加载 amis-editor。
