### ISSUE TITLE
amis文档（国外）打不开，页面报错

### ISSUE THREAD

**Issue by iceqing** [baidu/amis#4529]
#### 描述问题：

访问 `https://baidu.github.io/amis/`页面显示报错

#### 截图或视频：

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/39587710/171910347-deded56c-5678-4c55-ba50-0634629a0593.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.10.0

3. 粘贴有问题的完整 `amis schema` 代码：
无

4. 操作步骤
打开官网文档地址即可复现，https://baidu.github.io/amis/

**Comment by nwind** [comment]
嗯目前 master 代码还在调整中
