### ISSUE TITLE
某个组件或者整体加载完毕的事件 jssdk使用 需要很多自定义js的操作  然后近期就非常需要这个功能

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#4530]
比如要确定配置都渲染成功了  用自定义js对某些组件做一些操作  比如初始化值什么的
不是用apiinit那种api模式的 做webui用   jssdk纯js操作的 不牵扯接口的
大佬看这个好搞么
#4197

**Comment by ghost** [comment]
后来, 你找到方法没有?
