### ISSUE TITLE
chart里面一个未知的toast弹窗

### ISSUE THREAD

**Issue by gillbates** [baidu/amis#4535]
#### 描述问题：

chart组件会有没有内容的报错toast。。。

#### 截图或视频：

刷新页面，右上角会有这种没有内容的报错toast，但是表格可以加载出来。

<img width="440" alt="image" src="https://user-images.githubusercontent.com/783547/172058044-3ef98230-f145-402e-b266-b521e147cfc6.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

1.10.0

3. 粘贴有问题的完整 `amis schema` 代码：

/api/result/urls?id=1 的响应结果
```
{"status":0,"msg":"ok","data":{"chart":"/data/2022/04/05/3986/c_1.js"}}
```

必现的schema

`   {
 	"type": "service",
 	"api": "/api/result/urls?id=1",
 	"body": {
 		"type": "panel",
 		"body": {
 			"type": "chart",
 			"name": "chart",
 			"api": "${chart}"
 		}
 	}
 }`

但是如果，把chart的api在代码里硬编码一个地址，则无该问题。。。
`   {
 	"type": "service",
 	"api": "/api/result/urls?id=1",
 	"body": {
 		"type": "panel",
 		"body": {
 			"type": "chart",
 			"name": "chart",
 			"api": "/data/2022/04/05/3986/c_1.js"
 		}
 	}
 }`

5. 操作步骤
上述schema刷新页面就必先。。。

**Comment by gillbates** [comment]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/783547/172972958-2c2cf2f6-e34f-4048-bb2b-8a0495d44cee.png">

用昨天的新版，现在显示这个了，然后chart本身不出来了。。。

**Comment by wibetter** [comment]
@gillbates chart api 是用来获取echart配置的接口地址，请截图看下你配置的api返回的接口格式是什么：
"api": "/data/2022/04/05/3986/c_1.js"

**Comment by gillbates** [comment]
这个issue暂时先关了吧，现在那个项目代码都变了。。。
