### ISSUE TITLE
如何在移动端运行,如uniapp中。

### ISSUE THREAD

**Issue by taoyao-code** [baidu/amis#4545]
#### 实现场景：
在uniapp移动端中成功运行，运行到手机，在iOS中出现白屏
#### 存在的问题：
在 uniapp 运行 app-push 到手机，在iOS中出现白屏
#### 当前方案：
当前使用vue-cli下载的uniapp，运行到手机 App 时，导入amis模块直接白屏

```
code here...
```

**Comment by hyzx86** [comment]
...好好看看 uniapp 文档，或者最直接用 h5plus

**Comment by nwind** [comment]
小程序缺少很多 api，预计没法支持
