### ISSUE TITLE
combineNum无效

### ISSUE THREAD

**Issue by cbz20000** [baidu/amis#4550]
#### 描述问题：
crud表格模式的combineNum无效，combineNum:1、combineNum：2、combineNum：3效果都一样

#### 截图或视频：

![image](https://user-images.githubusercontent.com/79636715/172318621-0b510bd0-c12e-4b66-8990-b2afd042ff84.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v1.10.0

3. 粘贴有问题的完整 `amis schema` 代码：
`{
    type: 'page',
    data: {
      canEdit: true,
    },
    body: {
      type: 'crud',
      api: 'get:/fac/report/getLocalOrderQueryNobrand',
      mode: 'table',
      defaultParams: { sendDate: sendDate },
      syncLocation: false,
      filter: {
        title: '条件搜索',
        submitText: '',
        type: 'form',
        mode: 'horizontal',
        horizontal: {
          leftFixed: 'sm',
        },
        body: [
          {
            type: 'group',
            label: false,
            body: [
              {
                type: 'select',
                name: 'tenantCode',
                label: '供应商',
                source: '/system/org/getCompanyValset',
                clearable: true,
                multiple: true,
                // submitOnChange: true,
              },
              {
                type: 'input-text',
                name: 'productNo',
                label: '款式编号',
              },
            ],
          },
          {
            type: 'group',
            label: false,
            body: [
              {
                type: 'input-month-range',
                name: 'sendDate',
                label: '月份范围',
                format: 'YYYY-MM',
                clearable: true,
                columnRatio: 6,
                // submitOnChange: true,
              },
              {
                label: '搜索',
                type: 'submit',
                level: 'primary',
              },
            ],
          },
        ],
      },
      combineNum: 3,
      autoFillHeight: true,
      headerToolbar: ['export-excel'],
      footerToolbar: [],
      columns: [
        {
          name: 'tenantName',
          label: '生产工厂',
          fixed: 'left',
        },
        {
          name: 'sendDate',
          label: '月份',
          fixed: 'left',
        },
        {
          name: 'productNo',
          label: '款式',
          fixed: 'left',
        },
        {
          name: 'color',
          label: '颜色',
          fixed: 'left',
        },
        {
          name: 'size',
          label: '尺寸',
          fixed: 'left',
        },
        {
          type: 'tpl',
          name: 'sendQuantity',
          label: '工厂发货数',
          tpl: '<span style="color:#00AA00">${sendQuantity}</span>',
        },
        {
          type: 'tpl',
          name: 'checkQuantity',
          label: '仓库核对数',
          tpl: '<span style="color:#CC6600">${checkQuantity}</span>',
        },
        {
          type: 'tpl',
          name: 'lastQuantity',
          label: '仓库质检数',
          tpl: '<span style="color:#00DDDD">${lastQuantity}</span>',
        },
      ],
      affixRow: [
        {
          type: 'text',
          text: '总计',
          colSpan: 5,
        },
        {
          type: 'tpl',
          tpl: '${items|pick:sendQuantity|sum|division:2}',
        },
        {
          type: 'tpl',
          tpl: '${items|pick:checkQuantity|sum|division:2}',
        },
        {
          type: 'tpl',
          tpl: '${items|pick:lastQuantity|sum|division:2}',
        },
      ],
    }`

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by yukozy** [comment]
combineNum这个参数其实是有效的，这有个bug，他默认把combineNum加了3。我试了写1他合并了四列，2是五列，最后我写了-2 他只合并了一列。

**Comment by cbz20000** [comment]
> combineNum这个参数其实是有效的，这有个bug，他默认把combineNum加了3。我试了写1他合并了四列，2是五列，最后我写了-2 他只合并了一列。

🐮

**Comment by 2betop** [comment]
已不能复现，请升级到最新版本，有问题再开
