### ISSUE TITLE
sdk使用多页应用，建议增加开关可以关闭面包屑

### ISSUE THREAD

**Issue by qianxiaofendou** [baidu/amis#4562]
#### 描述问题：
在使用多页应用时，建议增加开关可以关闭面包屑(不是每个应用都需要的，辛苦大大加个开关啦！！！)
https://aisuda.bce.baidu.com/amis/zh-CN/components/app

#### 截图或视频：
![image](https://user-images.githubusercontent.com/20673152/172594540-c8cb9e16-0dac-4b13-9f2f-2ae72615c002.png)

如上图，好像面包屑路径也不对，一级目录`专题管理`没显示出来(一级目录的url是空的，但是面包屑里面没有)，可以顺带修复下~~

使用是是sdk1.9.0版本

**Comment by sxaxin** [comment]
赞同,另外能搞成多页切换 选项卡切换关闭就更完美了
