### ISSUE TITLE
需求: 希望给有异步加载文件的组件, 在加载文件时 添加 <Spinner /> 状态。 

### ISSUE THREAD

**Issue by CareyToboo** [baidu/amis#458]
Editor、Chart、富文本组件渲染时，需要异步加载文件，网络不好的时候，会出现白屏一段时间。虽然可以自己通过 ref 或者检查 全局 window.xxx 来显示和隐藏  <Spinner /> , 但是没有官方支持实现好。因此 希望增加懒加载组件的 loading状态。

**Comment by 2betop** [comment]
好的
