### ISSUE TITLE
尝试使用amis来开发desktop app

### ISSUE THREAD

**Issue by wanghaisheng** [baidu/amis#4581]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
https://github.com/wanghaisheng/python-desktop-app-amis-starter
目前从release中下载了最新的js sdk
repo里我也能够实现打开首页
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
1.我打开页面以后，input无法输入
2.api saveForm 我怎么获取两个参数的值 按道理说form的参数应该是post到api的endpoint的
目前我也写了个简单的捕获前台参数值的方法 

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by xiahao90** [comment]
你这个项目有截图吗，我想学习学习

**Comment by lurunze1226** [comment]
建议问题描述具体一些，或者贴出来有问题的schema

**Comment by nwind** [comment]
建议用 Electron，pywebview 可能浏览器版本太低
