### ISSUE TITLE
1.10 select组件多了一个placeholder

### ISSUE THREAD

**Issue by bitray** [baidu/amis#4582]
#### 描述问题：

升级到1.10后, select组件选项中自动新增了一个placeholder的option

#### 截图或视频：

![image](https://user-images.githubusercontent.com/4013037/172974455-a7227d36-df2b-4e43-a81f-1308521aa61d.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.10
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
              type: "select",
              name: "fileStatus",
              label: "File Status",
              size:"sm",
              inline: true,
              source: "xxxxx",
              clearable: true,
              searchable: true,
              "zh-CN": {
                label: "文件状态",
              },
              "en-US": {
                label: "File Status",
              },
            },
```

4. 操作步骤
打开页面就有了

**Comment by TeCHiScy** [comment]
发现同样的问题

**Comment by lengqingfeng** [comment]
遇到同样问题

**Comment by lengqingfeng** [comment]
> #### 描述问题：
> 升级到1.10后, select组件选项中自动新增了一个placeholder的option
> 
> #### 截图或视频：
> ![image](https://user-images.githubusercontent.com/4013037/172974455-a7227d36-df2b-4e43-a81f-1308521aa61d.png)
> 
> #### 如何复现（请务必完整填写下面内容）：
> 1. 你是如何使用 amis 的？
>    sdk
> 2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
>    1.10
> 3. 粘贴有问题的完整 `amis schema` 代码：
> 
> ```
> {
>               type: "select",
>               name: "fileStatus",
>               label: "File Status",
>               size:"sm",
>               inline: true,
>               source: "xxxxx",
>               clearable: true,
>               searchable: true,
>               "zh-CN": {
>                 label: "文件状态",
>               },
>               "en-US": {
>                 label: "File Status",
>               },
>             },
> ```
> 
> 4. 操作步骤
>    打开页面就有了

添加下这个css
import '../../../../node_modules/amis/lib/helper.css';

**Comment by lurunze1226** [comment]
升级到2.0.0试试呢，没有复现

**Comment by 17** [comment]
`.amis-scope .hidden` 的 `none` 被 `.amis-scope .cxd-Select-option` 的 `display: flex;` 覆盖了。  


**解决办法：**  
```
.amis-scope .hidden {
    display: none!important;
}
```

**Comment by nwind** [comment]
新版没复现，应是修了
