### ISSUE TITLE
能否开源amis-editor

### ISSUE THREAD

**Issue by JimFirst** [baidu/amis#4597]
## 概述

能否开源amis-editor

## 动机

当前amis-editor可视化bug有点多，想自己改改，没开源又改不动

## 示例

CRUD的搜索配置无效、新增Button拖拽配置dialog，点完确定Button按钮没了

**Comment by EvanZheng11** [comment]
同等开源

**Comment by BingBlog** [comment]
同等开源

**Comment by shuracwf** [comment]
同等开源

**Comment by DroganC** [comment]
应该没戏 人家上层的saas还要卖钱

**Comment by nwind** [comment]
已合入

**Comment by jiatongwu** [comment]
不是宣称开源的吗？

**Comment by 2betop** [comment]
不是已经开源了吗？代码就在这个仓库里面
