### ISSUE TITLE
怎么获取filter里面的值呢

### ISSUE THREAD

**Issue by dmj199811** [baidu/amis#460]
接口搜索表格数据的时候 多个输入框一个一个清空感觉太麻烦了 想写一个按钮清空所有的输入框的值 目前思路是0nClick 写方法清空 但是不知道在这个方法里面怎么获取输入框的值  大佬可以告知一下吗，感觉挺多场景会用到这个值的

**Comment by 2betop** [comment]
添加一个重置按钮试试？

**Comment by dmj199811** [comment]
是每一个框都加一个clearable那个吗 感觉很麻烦  重置按钮的写法是什么呢 其实还是想在方法内获取到输入框到值 这个场景不能实现的话 感觉很多地方都不灵活

**Comment by 2betop** [comment]
就是加个 

```
{
  "type": "reset",
  "label": "重置"
}
```

一个按钮就够了。

**Comment by dmj199811** [comment]
好的 谢谢老板

**Comment by dayuliu** [comment]
查询后的筛选条件还是在的，reset好像只可以重置本次的输入，而并不能使filter全部初始化。
筛选条件带到了url里面了，reset按钮不好用

**Comment by RickCole21** [comment]
reset本身意义就是`重置`，即**重置到表单初始状态**，而不是`清空`
