### ISSUE TITLE
wizard 向导组件下一步问题

### ISSUE THREAD

**Issue by qianxiaofendou** [baidu/amis#4612]
#### 描述问题：

向导组件中的`jumpableOn`属性控制的是`上一步按钮`是否能点击，对于当前步骤里面的`下一步`不起作用，通过查看源码，在`renderActions `方面里面，`jumpableOn`确实是控制的`上一步`按钮的点击逻辑，因为第一步里面目前我们有从接口异步获取的数据，来控制第一步的下一步是否可点击，目前还没有方案，希望可以增加当前步骤的`下一步`是否可以点击的逻辑，

#### 截图或视频：

![image](https://user-images.githubusercontent.com/20673152/173501705-bedf714f-096c-4154-a2e9-bcf6faca65f3.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.9.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "title": "第一步",
  "body": [
    {
      "name": "website",
      "label": "网址",
      "type": "input-url",
      "required": true
    },
    {
      "name": "email",
      "label": "邮箱",
      "type": "input-email",
      "required": false
    }
  ],
  "mode": "normal",
  "jumpableOn": "this.website == 'http://aa.com'"
}
```

**Comment by lurunze1226** [comment]
下一步按钮上加`disabledOn`

**Comment by qianxiaofendou** [comment]
> 下一步按钮上加`disabledOn`

添加`disabledOn`后会导致当前step上的表单都是禁用模式了

我目前的解决方案是使用`actions`重新定义上一步和下一步两个按钮，然后使用`disabledOn`，达到了我们那个表单想要的效果，完美结局，嘻嘻~~
