### ISSUE TITLE
请问form表单提交前如何对字段的值进行编码处理 JsSDK模式

### ISSUE THREAD

**Issue by 309454886** [baidu/amis#462]
因有个项目，用到代码编辑器，需要提交html代码，但是接口是第三方的，Html代码需要进行Unicode编码后才能提交，AMIS中如何实现。

**Comment by 2betop** [comment]
可以配置发送适配器，在里面篡改发送的数据体，可以在里面写个 debugger; 浏览器里面调试一下，看里面都有啥。

**Comment by 309454886** [comment]
我这个所有接口都是第三方的，自己改不了。能修改的仅是前端页面，适配器也是限制了不能提交html的

**Comment by 309454886** [comment]
配置发送适配器后，问题解决，非常感谢！
