### ISSUE TITLE
crud 分页，每页显示条数重置 问题 Bug

### ISSUE THREAD

**Issue by CrazyFise** [baidu/amis#4620]
#### 描述问题：
使用crud 组件时
1 、重新设置每页显示的条数
2、点击下一页，组件会重置每页显示的数量 “10”

**Comment by CrazyFise** [comment]
使用crud 配合"switch-per-page" 使用分页功能时，每页显示条数修改之后，点击分页跳转时，分页数量会被重置每页10条。
此问题复现的版本是 v1.9.0，之后的版本是否有修复，请告知版本

**Comment by lurunze1226** [comment]
修复过了，试试1.10.x及以后的版本
