### ISSUE TITLE
如何出码

### ISSUE THREAD

**Issue by jackMk** [baidu/amis#4623]
#### 实现场景：
使用amis-editor-demo制作好的效果，如何出码

#### 存在的问题：
不知道如何生成react代码

#### 当前方案：
如何将集成到自己得系统

```
code here...
```

**Comment by nwind** [comment]
参考 https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/getting-started#react，必须使用 amis 框架，不能生成纯 React 项目
