### ISSUE TITLE
datetime 为0 时，可否支持输出- 而不是1970

### ISSUE THREAD

**Issue by dayuliu** [baidu/amis#463]
datetime 为0 时，可否支持输出- 而不是1970
而我目前只能这么做
                "tpl": "<% if (data.update_time == 0) { %>-<% }else{ %> <%= formatDate(data.update_time, format='YYYY-MM-DD HH:mm:ss', inputFormat='X') %> <% } %>",

**Comment by RickCole21** [comment]
目前应该只能这样
