### ISSUE TITLE
sdk.js有大量es6代码未编译

### ISSUE THREAD

**Issue by tianyk** [baidu/amis#4644]
#### 描述问题：

sdk.js有大量es6代码未编译

#### 截图或视频：

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/3387702/174236403-7c37a3e0-45b9-4290-871f-5a44227776c8.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
2. 
sdk

3. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

1.10.2

4. 粘贴有问题的完整 `amis schema` 代码：
<https://cdn.jsdelivr.net/npm/amis@1.10.2/sdk/sdk.js>

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nuan1989** [comment]
能用就好了. 低版本浏览器又不考虑

**Comment by nuan1989** [comment]
人家明确不支持低版本浏览器
