### ISSUE TITLE
combo组件中使用 选择表单项 动态选项组   获取选项数据异常

### ISSUE THREAD

**Issue by mumuhhh** [baidu/amis#4646]
#### 描述问题：

数据链中的变量发生变化后
在combo组件中嵌套的 选择表单项使用动态选项组 source获取选项，
数据域变化  combo嵌套的选择框下拉框不变化

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "mode": "horizontal",
    "body": [
      {
        "label": "选项",
        "name": "options",
        "type": "combo",
        "multiple": true,
        "draggable": true,
        "items": [
          {
            "name": "label",
            "type": "input-text",
            "placeholder": "属性"
          },
          {
            "name": "value",
            "type": "input-text",
            "placeholder": "值"
          }
        ]
      },
      {
        "label": "组合选项",
        "name": "primary",
        "type": "combo",
        "items": [
          {
            "label": "组合",
            "name": "values",
            "type": "select",
            "multiple": true,
            "joinValues": false,
            "extractValue": true,
            "source": "${options}"
          },
          {
            "label": "别名",
            "name": "aName",
            "type": "input-text"
          }
        ]
      }
    ]
  }
}
```

**Comment by mrsdpz** [comment]
试试获取父级数据
或者通过事件 setValue 更新数据

**Comment by mrssgao** [comment]
我也遇到通过样的问题
{
        type: 'group',
        mode: 'horizontal',
        body: [
          {
            type: "combo",
            name: "combo",
            label: "标签",
            multiple: true,
            placeholder:"同一个标签只能选一次",
            "canAccessSuperData": true,
            addBtn: {
              type: "button",
              label: "新增"
            },
            items: [
              {
                type: 'select',
                name: 'AddCustomerSubdivide',
                hideSelected: true,
                // joinValues: false,
                unique: true,
                label: '',
                source: '${initLabel}',
                "onEvent": {
                  "change": {
                    "actions": [
                      {
                        "actionType": "setValue",
                        "componentId": "form-reload"
                      }
                    ]
                  }
                }
              },
              {
                name: "labelSelect",
                label: "",
                id:'form-reload',
                type: "select",
                visibleOn:"this.AddCustomerSubdivide",
                clearValueOnHidden: true,
                source: "${initLabel|filter:value:isIn:[AddCustomerSubdivide]|nth:0|pick:children}",
              },
            ],
            required: true,
            validationErrors: {
              isRequired: '标签不能为空'
            }
          }

**Comment by mrssgao** [comment]
setValue 是改变select的值，select中source无法实时更新

**Comment by mrsdpz** [comment]
> setValue 是改变select的值，select中source无法实时更新

setvalue 是改变你指定的变量的值，修改 source 绑定的变量即可

**Comment by mumuhhh** [comment]
> > setValue 是改变select的值，select中source无法实时更新
> 
> setvalue 是改变你指定的变量的值，修改 source 绑定的变量即可

{
	"type": "page",
	"body": {
		"type": "form",
		"debug": true,
		"mode": "horizontal",
		"body": [
			{
				"label": "选项",
				"name": "options",
				"type": "combo",
				"multiple": true,
				"draggable": true,
				"items": [
					{
						"name": "label",
						"type": "input-text",
						"placeholder": "属性"
					},
					{
						"name": "value",
						"type": "input-text",
						"placeholder": "值"
					}
				]
			},
			{
				"label": "组合选项",
				"name": "primary",
				"type": "combo",
				"strictMode": true,
				"items": [
					{
						"label": "组合",
						"name": "values",
						"type": "input-text",
						"multiple": true,
						"joinValues": false,
						"extractValue": true,
						"source": "${options}"
					},
					{
						"label": "别名",
						"name": "aName",
						"type": "input-text"
					}
				]
			}
		]
	}
}

**Comment by mumuhhh** [comment]
特别是  input-text  这个  直接下拉选择是白的
