### ISSUE TITLE
Tree控件当选中所有子节点时，父节点不会自动选中【JsSDK模式下】

### ISSUE THREAD

**Issue by 309454886** [baidu/amis#465]
代码如下：
 {
        "type": "page",
        "body": {
            "title": "",
            "type": "form",
            "mode": "horizontal",
            "api": "/test/add",
            "autoFocus": false,
            "controls": [{
                "type": "tree",
                "name": "tree",
                "label": "Tree",
                //multiple 默认为 false, 设置成 true 表示可多选
                "multiple": true,
                //withChildren 是指成 true，选中父节点时，值里面将包含子节点的值，否则只会保留父节点的值
                "withChildren": true,
                //cascade 设置成 true 时当选中父节点时不自动选择子节点。
                "cascade": false,
                "options": [{
                    "label": "Folder A",
                    "value": 1,
                    "children": [{
                        "label": "file A",
                        "value": 2
                    }, {
                        "label": "file B",
                        "value": 3
                    }]
                }, {
                    "label": "file C",
                    "value": 4
                }, {
                    "label": "file D",
                    "value": 5
                }]
            }],
        }
    };
当file A和file B都被选中后，父节点Folder A不会被选中，而且值也不会包含Folder A
![image](https://user-images.githubusercontent.com/61499032/75412043-36d4cb00-595c-11ea-91a9-8da5f0a0a279.png)

还有，请考虑实现半选择功能，即当选中了子节点，其父节点为半选状态，取值是包含父节点的值。

**Comment by tanjiancheng** [comment]
同问，使用的是JSSDK,获取值子节点全部数据返回的时候，父节点不会默认选中状态，还有个问题就是如果我cascade =false，选择父节点子节点就会默认禁用不让操作了
![image](https://user-images.githubusercontent.com/7401570/86200403-1f6a5080-bb8f-11ea-9f90-580ffe11107c.png)
能否可以加参数让子节点在父节点选中是也能去掉某些选项，类似如下
![image](https://user-images.githubusercontent.com/7401570/86200443-3d37b580-bb8f-11ea-8007-62d47d095eb9.png)

**Comment by nwind** [comment]
没复现估计是之前的 bug
