### ISSUE TITLE
InputDateRange 日期范围组件bug

### ISSUE THREAD

**Issue by junjieQQ2** [baidu/amis#4651]
#### 描述问题：

1、选择日期时没有点确认，实际上表单未赋值，但是组件上展示了日期。
2、设置了必填属性后，只选择了开始日期或者结束日期，点击确认之后值有了，但是有一个日期为空却不提示红色必填文案

#### 截图或视频：
<img width="875" alt="image" src="https://user-images.githubusercontent.com/96193771/174290828-549df38b-d2f3-454d-abdd-9471823016bf.png">

<img width="859" alt="image" src="https://user-images.githubusercontent.com/96193771/174291349-f030aae5-0cc6-4949-a618-21d2208f49e8.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网可以复现

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "input-date-range",
        "name": "select",
        "required": true,
        "label": "日期范围"
      }
    ]
  }
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by junjieQQ2** [comment]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/96193771/174291349-f030aae5-0cc6-4949-a618-21d2208f49e8.png">

**Comment by lurunze1226** [comment]
2.1.0 fixed
