### ISSUE TITLE
IE11兼容问题

### ISSUE THREAD

**Issue by zhouqiang1983** [baidu/amis#4656]
现象：（组件为form，代码是官方文档代码）
1.使用sdk.js验证，在1.4.0版本后，ie11下使用会报错（1.0.19-1.4.0之间的版本可用ie11）。版本1.10.2下，根据错误排查，可能是插件react-hook-form相关的代码编译后仍不兼容ie11
2.使用react工程，在已使用babel的情况下打包，也无法兼容ie11，排查后，发现的第1个可能原因是amis引用的ansi-to-react组件在amis打包中仍存在es6语法
问题：
在微软关闭ie11的当下，amis还有兼容ie11的打算吗？

代码：
<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="UTF-8" />
    <title>amis demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <link rel="stylesheet" href="sdk.css" />
    <link rel="stylesheet" href="helper.css" />
    <link rel="stylesheet" href="iconfont.css" />
    
    
    
    
    <style>
      html,
      body,
      .app-wrapper {
        position: relative;
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="root" class="app-wrapper"></div>
    <script src="sdk.js"></script>
    <script type="text/javascript">
      (function () {
        let amis = amisRequire('amis/embed');
        // 通过替换下面这个配置来生成不同页面
        let amisJSON = {
          type: 'page',
          title: '表单页面',
          body: {
            type: 'form',
            mode: 'horizontal',
            api: '/saveForm',
            body: [
              {
                label: 'Name',
                type: 'input-text',
                name: 'name'
              },
              {
                label: 'Email',
                type: 'input-email',
                name: 'email'
              }
            ]
          }
        };
        let amisScoped = amis.embed('#root', amisJSON);
      })();
    </script>
  </body>
</html>

**Comment by SheenaghF** [comment]
这是解决了吗
