### ISSUE TITLE
amis 线性图刷新问题

### ISSUE THREAD

**Issue by XiuPunica** [baidu/amis#466]
问题描述：
使用 https://baidu.github.io/amis/chart 中Form + Charts布局来编写页面，
但是发现图表中线形图有时候新的数据下发了，图表刷新。柱状图就没有问题。如图
![image](https://user-images.githubusercontent.com/6257061/75419534-faf83080-5970-11ea-8c18-280ad08605b3.png)

搜了下echarts的解决方案，说是可以通过 重绘画布 window.chartRadar.resize(); 或者强制更新的方式来实现 chartInstance.setOption(option, true);
但这些在amis中是否有可用的配置来实现呢？

**Comment by 2betop** [comment]
https://baidu.github.io/amis/docs/renderers/Chart

应该对应的是这个 replaceChartOption 配置

**Comment by XiuPunica** [comment]
666~
