### ISSUE TITLE
如何控制Service的请求顺序【JsSDK模式】

### ISSUE THREAD

**Issue by 309454886** [baidu/amis#467]
![image](https://user-images.githubusercontent.com/61499032/75439428-baaaa980-5994-11ea-92cc-485273609f3f.png)
代码如下:
```json
 {
        "type": "page",
        "body": {
            "type": "service",
            "api": "get:Service1.json",
            "body": {
                "type": "service",
                "api": "get:Service2.json",
                "body": {
                    "title": "测试",
                    "type": "crud",
                    "api": "get:Service3.json",
                    "pageField": "page",
                    "perPageField": "pagesize",
                    "orderField": "",
                    "perPageAvailable": [10, 20, 50, 100],
                    "defaultParams": {
                        "pagesize": 10,
                    },
                    "syncLocation": false,
                    "columns": [{
                        "label": 'ID',
                        "type": "text",
                        "name": 'ID',
                        "toggled": true
                    }, {
                        "label": '名称',
                        "name": 'Name',
                        "type": "text",
                        "width": 150,
                        "sortable": true,
                        "toggled": true,
                    }, {
                        "label": '操作',
                        "type": "container",
                        "body": [{
                            "type": "button",
                            "label": "测试Service1",
                            "hiddenOn": "data.ServiceA!=true"
                        }, {
                            "type": "button",
                            "label": "测试测试Service2",
                            "hiddenOn": "data.ServiceB!=true"
                        }, {
                            "type": "button",
                            "label": "测试测试Service3",
                            "hiddenOn": "data.ID!=1"
                        }]
                    }]
                }
            }
        }
    }
```

发现最先请求的成了Service3，也就是最里面一层。但是想让最外一层得到数据后再让次层请求并获取数据，最后才是最里层请求。

**Comment by 2betop** [comment]
如果有接口依赖，那就找个依赖的接口返回字段，把这个字段写在当前接口的 url 中，然后配置接口发送条件，这样，当前接口会等依赖接口加载完再开始加载了。

**Comment by 309454886** [comment]
大佬，还有问题请教 。源代码如下：
![image](https://user-images.githubusercontent.com/61499032/75675042-49833300-5cc1-11ea-88f5-f173920b3181.png)
Service1.json数据如下：
![image](https://user-images.githubusercontent.com/61499032/75675082-628be400-5cc1-11ea-8be5-37af2ed0a8ea.png)
Service2.json数据如下：
![image](https://user-images.githubusercontent.com/61499032/75675113-733c5a00-5cc1-11ea-827c-a7f2446ae02d.png)
Service3.json数据如下：
![image](https://user-images.githubusercontent.com/61499032/75675151-82230c80-5cc1-11ea-85b9-d8acad20fa58.png)

但是页面只进行了请求了Service1.json就没有继续请求其他数据了。

请大佬 给个示例代码

**Comment by 2betop** [comment]
sendOn 有误，`data.xxxx > 0`

**Comment by 309454886** [comment]
大佬，我写的是这样：
![image](https://user-images.githubusercontent.com/61499032/75675915-2063a200-5cc3-11ea-9236-6710a0e02abf.png)

**Comment by 309454886** [comment]
大佬，我写的是这样：
![image](https://user-images.githubusercontent.com/61499032/75675915-2063a200-5cc3-11ea-9236-6710a0e02abf.png)

**Comment by 2betop** [comment]
sendOn 和 url 中是两种不一样的语法。

url："${ServiceB_ID}"

sendOn 里面就是目前的用法，没错。

**Comment by 309454886** [comment]
大佬，第二个和第三个都没有请求啊
![image](https://user-images.githubusercontent.com/61499032/75679188-1abd8a80-5cca-11ea-8c14-d3fc710b3530.png)

**Comment by 2betop** [comment]
service 2 的 api 配置如下？

```
api: {
   "url": "./Servcie2.json?ServiceA=${ServiceA}",
   "method": "get",
   "sendOn": "data.ServiceA"
}
```

**Comment by 309454886** [comment]
是的，和Html在同一级

**Comment by 2betop** [comment]
把你最新的配置贴出来， 代码可以用 toolbar 里面的这个插入 
![image](https://user-images.githubusercontent.com/2698393/75680168-ec40af00-5ccb-11ea-9b26-02e860e884be.png)

**Comment by 309454886** [comment]
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>SerVice测试</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">

    <link rel="stylesheet" href="https://houtai.baidu.com/v2/csssdk">
    <script src="https://houtai.baidu.com/v2/jssdk"></script>

</head>

<body style="padding: 6px; overflow: hidden;">
    <div id="root" class="app-wrapper amis-scope">
    </div>
</body>
<script type="text/javascript">
    //定义变量
    var PageJsonData = {
        "type": "page",
        "body": {
            "type": "service",
            "api": "get:Service1.json",
            "body": {
                "type": "service",
                //"api": "get:Service2.json",
                "api": {
                    "url": "/module/Test/Service2.json?ServiceA=${data.ServiceA}",
                    "method": "get",
                    "sendOn": "data.ServiceA",
                },
                "body": {
                    "title": "测试",
                    "type": "crud",
                    "api": {
                        "url": "/module/Test/Service3.json?ServiceB_ID=${data.ServiceB_ID}",
                        "method": "get",
                        "sendOn": "data.ServiceB_ID>0",
                    },
                    "pageField": "page",
                    "perPageField": "pagesize",
                    "orderField": "",
                    "perPageAvailable": [10, 20, 50, 100],
                    "defaultParams": {
                        "pagesize": 10,
                    },
                    //"syncLocation": false,
                    "columns": [{
                        "label": 'ID',
                        "type": "text",
                        "name": 'ID',
                        "toggled": true
                    }, {
                        "label": '名称',
                        "name": 'Name',
                        "type": "text",
                        "width": 150,
                        "sortable": true,
                        "toggled": true,
                    }, {
                        "label": '操作',
                        "type": "container",
                        "body": [{
                            "type": "button",
                            "label": "测试Service1",
                            "hiddenOn": "data.ServiceA!=true"
                        }, {
                            "type": "button",
                            "label": "测试测试Service2",
                            "hiddenOn": "data.ServiceB!=true"
                        }, {
                            "type": "button",
                            "label": "测试测试Service3",
                            "hiddenOn": "data.ID!=1"
                        }]
                    }]
                }
            }
        }
    };
    //
    //
    //
    //初始化
    (function() {
        var amis = amisRequire('amis/embed');
        amis.embed('#root', PageJsonData);
    })();
</script>

</html>

**Comment by 309454886** [comment]
//定义变量
    var PageJsonData = {
        "type": "page",
        "body": {
            "type": "service",
            "api": "get:Service1.json",
            "body": {
                "type": "service",
                //"api": "get:Service2.json",
                "api": {
                    "url": "/module/Test/Service2.json?ServiceA=${data.ServiceA}",
                    "method": "get",
                    "sendOn": "data.ServiceA",
                },
                "body": {
                    "title": "测试",
                    "type": "crud",
                    "api": {
                        "url": "/module/Test/Service3.json?ServiceB_ID=${data.ServiceB_ID}",
                        "method": "get",
                        "sendOn": "data.ServiceB_ID>0",
                    },
                    "pageField": "page",
                    "perPageField": "pagesize",
                    "orderField": "",
                    "perPageAvailable": [10, 20, 50, 100],
                    "defaultParams": {
                        "pagesize": 10,
                    },
                    //"syncLocation": false,
                    "columns": [{
                        "label": 'ID',
                        "type": "text",
                        "name": 'ID',
                        "toggled": true
                    }, {
                        "label": '名称',
                        "name": 'Name',
                        "type": "text",
                        "width": 150,
                        "sortable": true,
                        "toggled": true,
                    }, {
                        "label": '操作',
                        "type": "container",
                        "body": [{
                            "type": "button",
                            "label": "测试Service1",
                            "hiddenOn": "data.ServiceA!=true"
                        }, {
                            "type": "button",
                            "label": "测试测试Service2",
                            "hiddenOn": "data.ServiceB!=true"
                        }, {
                            "type": "button",
                            "label": "测试测试Service3",
                            "hiddenOn": "data.ID!=1"
                        }]
                    }]
                }
            }
        }
    };
    //
    //
    //
    //初始化
    (function() {
        var amis = amisRequire('amis/embed');
        amis.embed('#root', PageJsonData);
    })();

**Comment by 2betop** [comment]
咋关了？

**Comment by 2betop** [comment]
试试这样


```js
    //定义变量
    var PageJsonData = {
        "type": "page",
        "body": {
            "type": "service",
            "api": "get:Service1.json",
            "body": {
                "type": "service",
                //"api": "get:Service2.json",
                "api": {
                    "url": "/module/Test/Service2.json?ServiceA=${ServiceA}",
                    "method": "get",
                    "sendOn": "data.ServiceA",
                },
                "body": {
                    "title": "测试",
                    "type": "crud",
                    "api": {
                        "url": "/module/Test/Service3.json?ServiceB_ID=${ServiceB_ID}",
                        "method": "get",
                        "sendOn": "data.ServiceB_ID>0",
                    },
                    "pageField": "page",
                    "perPageField": "pagesize",
                    "orderField": "",
                    "perPageAvailable": [10, 20, 50, 100],
                    "defaultParams": {
                        "pagesize": 10,
                    },
                    //"syncLocation": false,
                    "columns": [{
                        "label": 'ID',
                        "type": "text",
                        "name": 'ID',
                        "toggled": true
                    }, {
                        "label": '名称',
                        "name": 'Name',
                        "type": "text",
                        "width": 150,
                        "sortable": true,
                        "toggled": true,
                    }, {
                        "label": '操作',
                        "type": "container",
                        "body": [{
                            "type": "button",
                            "label": "测试Service1",
                            "hiddenOn": "data.ServiceA!=true"
                        }, {
                            "type": "button",
                            "label": "测试测试Service2",
                            "hiddenOn": "data.ServiceB!=true"
                        }, {
                            "type": "button",
                            "label": "测试测试Service3",
                            "hiddenOn": "data.ID!=1"
                        }]
                    }]
                }
            }
        }
    };
    //
    //
    //
    //初始化
    (function() {
        var amis = amisRequire('amis/embed');
        amis.embed('#root', PageJsonData);
    })();
```

**Comment by 309454886** [comment]
大佬 ，怎么只请求了两次。crud还是没有请求
![image](https://user-images.githubusercontent.com/61499032/75681350-5d816180-5cce-11ea-9392-f0fc1952c05d.png)

**Comment by 2betop** [comment]
crud 把同步地址栏给关了试试

**Comment by 309454886** [comment]
同步地址栏关了，请求顺序问题解决。非常感谢！

**Comment by Flourad** [comment]
> crud 把同步地址栏给关了试试

我配置了sendOn结果第二个请求没有发送
![image](https://user-images.githubusercontent.com/1535874/92730685-b67d3100-f3a6-11ea-946a-260cde07f127.png)

**Comment by Flourad** [comment]
> crud 把同步地址栏给关了试试

大佬帮忙看看这里

**Comment by toby1991** [comment]
用数据自动更新，把参数加到uri里面
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E8%87%AA%E5%8A%A8%E5%88%B7%E6%96%B0
