### ISSUE TITLE
InputImage多选时，接口返回格式具体怎么配置？items 具体该怎么配置

### ISSUE THREAD

**Issue by echolxltf** [baidu/amis#4672]
以下为单选时配置说明：
{
  "status": 0,
  "msg": "",
  "data": {
    "value": "xxxxxxx",
    "filename": "xxxx.jpg",
    "url": "http://xxxx.xxx.xxx"
  }
}

当为多选时，文档说明：“当表单项为多选模式时，不能再直接取选项中的值了，而是通过 items 变量来取，通过它可以获取当前选中的选项集合。”，
请问返回值该如何配置？

**Comment by lurunze1226** [comment]
```
{
  "status": 0,
  "msg": "",
  "data": {
    "value": "https:/xxx.yy/zz.png"
  }
}
```
接口格式还是这样，`items`不需要你来配置，它是为了方便获取上传完成后**多个文件**的url
