### ISSUE TITLE
checkboxes选项互斥功能

### ISSUE THREAD

**Issue by weeenc** [baidu/amis#4673]
#### 预期的解决方案：
实现checkboxes多选框某些选项互斥功能

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by lurunze1226** [comment]
互斥使用radios

**Comment by wenc2017** [comment]
@lurunze1226

**Comment by wenc2017** [comment]
@lurunze1226 
[https://github.com/baidu/amis/issues/724](url)，相似问题，我的场景是一个表单中，某个属性是checkboxes类型，有三个选项abc，选了a移除bc的checked状态，选了b或c则移除a的checked状态，能否提示一下目前版本有没有什么实现方案

**Comment by hsm-lv** [comment]
> @lurunze1226 [https://github.com/baidu/amis/issues/724](url)，相似问题，我的场景是一个表单中，某个属性是checkboxes类型，有三个选项abc，选了a移除bc的checked状态，选了b或c则移除a的checked状态，能否提示一下目前版本有没有什么实现方案

试试事件动作呢，change的时候更新复选框的值
