### ISSUE TITLE
app多页应用 使用schemaApi拉取远程json配置，其中definitions不起作用

### ISSUE THREAD

**Issue by qianxiaofendou** [baidu/amis#4679]
#### 描述问题：

如下图，在多页应用里面

#### 截图或视频：definitions配置未生效，查看网络面板也未发出请求，但是在编辑器里面是可以的，在多页应用里面通过schemaAPi拉取过来之后就不起作用了麻烦看下

![image](https://user-images.githubusercontent.com/20673152/175193833-90e3e2b1-3e56-4e31-baac-4cbca9ebfb4c.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.9.0

**Comment by Hi-Alan** [comment]
按照错误提示的路径，可能是因为 schemaAPi 定义的 page 之上还有一个已有的 page 导致的

> Error: 找不到对应的渲染器
> Path: app/page/page/body/0/form/0/fieldSet/body/4/undefined

**Comment by huxianfengcn** [comment]
记得刚接触AMIS的时候，是支持app多页应用的definitions功能的。测试了最新发布的几个版本，3.5.3是支持的，3.6.0 
之后再次开始
>  Error: 找不到对应的渲染器
