### ISSUE TITLE
amis本地跑不起来

### ISSUE THREAD

**Issue by qianxiaofendou** [baidu/amis#4681]
#### 描述问题：
amis拉到本地后，发现跑不起来(如下图)，操作步骤如下：
1、lerna bootstrap --hoist
2、npm i --legacy-peer-deps
3、npm run build --workspace amis-formula
4、npm start

node版本是14.16.0

#### 截图或视频：

![image](https://user-images.githubusercontent.com/20673152/175227219-8e6fdc21-620b-4133-a73b-5a589a600b69.png)

![image](https://user-images.githubusercontent.com/20673152/175227254-a7549df1-a47f-4f24-a50e-3e9bf87023d6.png)

**Comment by qianxiaofendou** [comment]
@2betop 帮忙看下这个问题 多谢！

**Comment by mmclofe** [comment]
我也遇到一样的问题了，请问楼主解决了吗 @qianxiaofendou

**Comment by h7ml** [comment]
主要原因是因为在执行[``npm run build --workspace amis-formula``](https://github.com/baidu/amis/blob/master/packages/amis-formula/package.json#L8-L9)命令时。

https://github.com/baidu/amis/blob/86e15457b4e701f90d79066b4f89fe770f0d2f6c/packages/amis-formula/package.json#L8-L9

``NODE_ENV=production`` 中的``NODE_ENV``无法被识别到

**Comment by monkeyDLB** [comment]
安装cross-env 到全局  cross-ev NODE_ENV=production
