### ISSUE TITLE
combo 如何通过 index 获取数据或者 combo 实现复制

### ISSUE THREAD

**Issue by mrsdpz** [baidu/amis#4687]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
combo 增加复制功能,复制某个选项

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
 combo里面遍历数组的时候可以使用${index}获取到下标,但无法使用该下标获取数组数据
请问有什么办法实现 combo item 的复制吗

**Comment by hsm-lv** [comment]
推荐几个思路：表达式GET可以获取对象或者数组指定的数据

**Comment by hsm-lv** [comment]
是否需求是这个 https://baidu.github.io/amis/zh-CN/components/form/combo#%E5%A4%8D%E5%88%B6%E6%95%B0%E5%80%BC
