### ISSUE TITLE
custom组件的 onChange 无法工作

### ISSUE THREAD

**Issue by XuTuKe** [baidu/amis#4693]
[####](url) 描述问题：

请用一段清晰简洁的文字描述
![T4~PZNCW~EKIXO38J7P24L3](https://user-images.githubusercontent.com/7031415/175458160-753466e6-597b-48d5-8818-eb5edaf613a3.png)
问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lurunze1226** [comment]
改一下`onChange`事件，第二个参数传入表单项的name `onChange(value: any, name: string)`

**Comment by XuTuKe** [comment]
> 改一下`onChange`事件，第二个参数传入表单项的name `onChange(value: any, name: string)`

依然无法工作
{
  "type": "page",
  "body": {
    "type": "form",
    "name": "myform",
    "title": "custom 组件",
    "body": [
      {
        "type": "input-text",
        "name": "username",
        "label": "姓名"
      },
      {
        "name": "username",
        "type": "custom",
        "label": "自定义组件",
        "onMount": "const button = document.createElement('button'); button.innerText = '点击修改姓名'; button.onclick = event => { onChange('new name','myform'); event.preventDefault(); }; dom.appendChild(button);"
      }
    ]
  }
}

**Comment by XuTuKe** [comment]
在编辑器中生效了，谢谢
