### ISSUE TITLE
图片放大无法旋转

### ISSUE THREAD

**Issue by luqufei456** [baidu/amis#4718]
crud中columns如下
{
  "type": "image",
  "name": "fileUrl",
  "label": "图片",
  "enlargeAble": true,
  "thumbMode": "cover",
  "rotatable": true
}
我注意到其他issue(https://github.com/baidu/amis/issues/2036)已经提出了希望有图片放大旋转功能，nwind回答已经在新版本默认开启rotatable: true，实际上无效果

由于公司限制无法上传截图，amis可视化编辑器中也无法放大旋转

1. 你是如何使用 amis 的？
使用sdk，版本为 [1.10.2](https://github.com/baidu/amis/releases/tag/1.10.2)

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

4. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "page",
  "title": "图片分拣",
  "body": [
    {
      "type": "crud",
      "syncLocation": false,
      "api": {
        "method": "get",
        "url": "http://127.0.0.1:8080/image-sort/list",
        "dataType": "json"
      },
      "quickSaveItemApi": "http://127.0.0.1:8080/image-sort/update",
      "footerToolbar": [
        "switch-per-page",
        "pagination"
      ],
      "columns": [
        {
          "type": "text",
          "name": "id",
          "label": "ID"
        },
        {
          "type": "image",
          "name": "fileUrl",
          "label": "图片",
          "enlargeAble": true,
          "thumbMode": "cover",
          "rotatable": true
        },
        {
          "name": "sortType",
          "label": "分拣类型",
          "quickEdit": {
            "mode": "inline",
            "type": "select",
            "size": "xs",
            "options": [
              "TJBG",
              "MSBG",
              "DLBG",
              "MJZBL",
              "SFZ"
            ],
            "saveImmediately": true
          }
        },
        {
          "name": "rotationAngle",
          "label": "旋转角度",
          "quickEdit": {
            "mode": "inline",
            "type": "select",
            "size": "xs",
            "options": [
              "0",
              "90",
              "180",
              "270"
            ],
            "saveImmediately": true
          }
        },
        {
          "type": "text",
          "label": "创建用户",
          "name": "creator"
        },
        {
          "type": "date",
          "name": "gmtCreate",
          "label": "创建时间"
        },
        {
          "type": "text",
          "name": "modifier",
          "label": "修改用户"
        },
        {
          "type": "date",
          "name": "gmtModified",
          "label": "修改时间"
        }
      ],
      "bulkActions": [
        {
          "type": "button",
          "level": "danger",
          "label": "批量删除",
          "actionType": "ajax",
          "confirmText": "确定要删除？",
          "api": "post:http://127.0.0.1:8080/image-sort/batch-delete/${ids|raw}"
        }
      ],
      "itemActions": [],
      "features": [
        "create",
        "filter",
        "bulkDelete",
        "bulkUpdate",
        "update",
        "view",
        "delete"
      ],
      "filterColumnCount": 3,
      "headerToolbar": [],
      "messages": {},
      "filter": {
        "title": "查询条件",
        "body": [
          {
            "type": "input-date-range",
            "label": "创建日期",
            "name": "createRange"
          },
          {
            "type": "input-date-range",
            "label": "修改日期",
            "name": "updateRange"
          },
          {
            "type": "input-text",
            "name": "sortType",
            "label": "分拣类型"
          }
        ],
        "rules": []
      },
      "filterTogglable": true
    }
  ]
}

**Comment by lurunze1226** [comment]
2.1.0 图片开启`enlargeAble: true 后支持旋转，放大等功能了
