### ISSUE TITLE
InputTree 树形选择框懒加载完成时表现异常

### ISSUE THREAD

**Issue by sangyuxiaowu** [baidu/amis#4727]
#### 描述问题：

当返回的数据启动懒加载时，第一个项目懒加载完成后，出现100个数据，然后折叠起来，进行第二项目的懒加载，第一个已经折叠的会自行打开，直接将想看的数据移出视线，要把滚动条拉到最下面。

 v1.10.2

**Comment by lurunze1226** [comment]
贴一下schema吧

**Comment by marin1993** [comment]
这个是 [文档的懒加载例子](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-tree#%E6%87%92%E5%8A%A0%E8%BD%BD) 一样会把折叠的分支，在懒加载完成后自动打开
![1](https://user-images.githubusercontent.com/17669599/176346438-48d19caf-e143-4db1-867b-fbaecb8a33ad.gif)

**Comment by sangyuxiaowu** [comment]
已修复
