### ISSUE TITLE
事件动作更新数据 setValue 如何新增数组数据

### ISSUE THREAD

**Issue by mrsdpz** [baidu/amis#4740]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
setvalue 添加对应数组,如何实现
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by bestway15** [comment]
onEvent: {
                      click: {
                        actions: [
                          {
                            actionType: 'setValue',
                            componentId: 'initService',
                            args: {
                              value: {
                                firstDay: '${newFirstDay}',
                              },
                            },
                          },
                        ],
                      },
                    },
                  },

**Comment by mrsdpz** [comment]
> onEvent: { click: { actions: [ { actionType: 'setValue', componentId: 'initService', args: { value: { firstDay: '${newFirstDay}', }, }, }, ], }, }, },

我说的是往数组里面添加元素,你这样写把整个firstDay重置了

**Comment by hsm-lv** [comment]
目前setValue可以针对combo、input-table这种对象数组类型数据的组件完成制定index的更新，另外一种方式就是去处理数据了，比如通过表达式处理数组数据后进行赋值
