### ISSUE TITLE
能不能让table里面值直接变成超链接

### ISSUE THREAD

**Issue by panghu3** [baidu/amis#475]

**Comment by 2betop** [comment]
最简单的方式用 tpl 拼一个

**Comment by panghu3** [comment]
有生成超链接 但是不可以用

**Comment by panghu3** [comment]
{
          name: 'source_url',
          type: 'tpl',
          tpl: '<a href="${source_url}"></a>',
          label: 'xxx',
          sortable: false
        },

**Comment by panghu3** [comment]
怎么插不了图片

**Comment by 2betop** [comment]
{
  type: "tpl",
  tpl: "<a href='${xxxx}'>${xxxLabel}</a>"
}

**Comment by panghu3** [comment]
怎么控制台那里 href里面的内容是正常的 一打开就带有本地域名 就404

**Comment by panghu3** [comment]
怎么去掉本地域名

**Comment by panghu3** [comment]
搞定了 谢谢
