### ISSUE TITLE
[amis-editor] 表单 post 接口配置请求体 dataType 配置为 json 类型，未生效

### ISSUE THREAD

**Issue by rencoo** [baidu/amis#4754]
#### 描述问题：

amis-editor 表单 post 接口配置请求体 dataType 配置为 json 类型，发送请求时，Content-Type 实际为 application/x-www-form-urlencoded

#### 截图或视频：
![截屏2022-06-30 22 46 14](https://user-images.githubusercontent.com/39717611/176708516-241257b4-e0c5-422a-b85b-d4dc833bb6d9.png)
![截屏2022-06-30 22 46 54](https://user-images.githubusercontent.com/39717611/176708582-72258967-8780-4317-872a-f9014c9a031a.png)

#### 如何复现（请务必完整填写下面内容）：

1. 使用官方编辑器项目，amis-editor-demo，版本为最新版本
repository: https://github.com/aisuda/amis-editor-demo.git
commitId: 1b5898b39764b74c5151b89a0755aaebfd42ba23

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "form",
  "title": "表单",
  "body": [
    {
      "label": "文本框",
      "type": "input-text",
      "name": "text"
    }
  ],
  "api": {
    "method": "post",
    "url": "http://127.0.0.1:8082/api/create",
    "dataType": "json"
  },
  "id": "u:56ca5ce96d5f"
}
```

3. 操作步骤
使用最新版 amis-editor-demo，npm start 跑起项目后
1）拖拽一个表单（具体schema配置就是上面👆🏻贴的 schema 代码）
2）右侧操作面板，接口 > 高级配置，发送方式改为 POST，数据格式选择 JSON
3）预览模式，发送请求，Content-Type 实际为 application/x-www-form-urlencoded
4）退出编辑模式，发送请求，结果和预览模式一样

**Comment by wibetter** [comment]
已经修复，
![image](https://user-images.githubusercontent.com/11958920/178958578-7a35379e-d0ae-4936-986b-d764e8cedf59.png)

**Comment by rencoo** [comment]
> 已经修复， ![image](https://user-images.githubusercontent.com/11958920/178958578-7a35379e-d0ae-4936-986b-d764e8cedf59.png)

有提交记录吗，麻烦贴一下

**Comment by github0hello** [comment]
服务器代码呢，没有服务器肯定跑不起来
