### ISSUE TITLE
[amis-editor、amis sdk] 下拉框组件不支持配置onChange属性

### ISSUE THREAD

**Issue by rencoo** [baidu/amis#4755]
#### 描述问题：

下拉框组件（type: 'select'）不支持配置onChange属性

#### 截图或视频：
<img width="1057" alt="截屏2022-06-30 23 04 59" src="https://user-images.githubusercontent.com/39717611/176713046-1d55a31d-b48d-4eec-94dc-d23b0c8aad2b.png">
<img width="1053" alt="截屏2022-06-30 23 05 15" src="https://user-images.githubusercontent.com/39717611/176713070-bcfaff6c-ddb0-4c72-ba50-1be8a12edae6.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、编辑器

2. amis 版本是什么？
1.9.1-beta.11；最新编辑器里存在这个问题

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "form",
  "title": "表单",
  "body": [
    {
      "type": "select",
      "label": "选项",
      "name": "select",
      "options": [
        {
          "label": "选项A",
          "value": "A"
        },
        {
          "label": "选项B",
          "value": "B"
        }
      ],
      "id": "u:ef48b2da7192",
      "onChange": "console.log('hello wolrd')"
    }
  ],
  "api": {
    "method": "post",
    "url": "http://127.0.0.1:8082/api/create",
    "dataType": "json"
  },
  "id": "u:56ca5ce96d5f"
}
```

5. 操作步骤
1）编辑器里拖拽一个表单
2）表单里增加一个select下拉框，并配置onChange属性
3）预览时，切换下拉框选项，触发onChange报错（说明其实onChange属性是有效的，只是sdk没有将onChange属性的值解析为函数？button的onClick就支持）
4）预期：onChange 正常执行；达到下拉选框选项变化，更新表单其他项的目的，这是个极其常见的需求；达到类似下图的效果
![截屏2022-06-30 23 16 11](https://user-images.githubusercontent.com/39717611/176713967-c63c908c-1795-4dab-9c30-43bd6d6dfa06.png)

**Comment by lurunze1226** [comment]
编辑器环境下不支持onChange传入函数，React环境下是可以的。建议编辑器环境中采用[事件动作](https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE) 完成你的需求
