### ISSUE TITLE
v2.0.0 版本 crud > filter > select > options 选项太小

### ISSUE THREAD

**Issue by 17** [baidu/amis#4756]
#### 截图或视频：
**1.9.1-beta.11**
![20220701053308](https://user-images.githubusercontent.com/6132593/176781919-43a0aefa-a901-4d4b-8d55-565918fa60e6.png)

**2.0.0**
![20220701053316](https://user-images.githubusercontent.com/6132593/176781928-7935a9a3-0ace-40ee-a11b-5bd26296a975.png)

#### 如何复现（

请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v2.0.0

3. code
```
{
"type": "select",
"label": "一级分类",
"name": "one_category",
"source": "0.0.0.0",
"clearable": true,
"searchable": true
},
```

**Comment by lurunze1226** [comment]
可以设置一下select组件的宽度

**Comment by 17** [comment]
通过 css 还是 json 属性。查看了 select [文档](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select) 没有找到相关属性。
但是希望可以恢复之前版本的样式。

**Comment by 1436722103** [comment]
可以通过size属性进行配置
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/19168752/178909594-0e92a58f-4575-43fe-bb52-1dadb2053582.png">
