### ISSUE TITLE
v2.0.0 CRUD 组件 affixHeader 样式 错位

### ISSUE THREAD

**Issue by 17** [baidu/amis#4757]
#### 截图或视频：
![20220701054217](https://user-images.githubusercontent.com/6132593/176783880-b430f121-f00b-4014-b1a5-97d7d5e97a5b.png)

**Comment by lurunze1226** [comment]
table内容区有滚动吗？是说没有任何滚动的情况下header变成浮层了？

**Comment by 17** [comment]
sorry，我描述的有点不清楚。


![20220701054217](https://user-images.githubusercontent.com/6132593/176988602-896e8290-2a53-4cc3-aa8b-2ec068f0957f.png)
_**在滚动时，浮动的表头蓝圈内的控件左侧和上侧没有合适距离。**_


之前版本：
![20220702140321](https://user-images.githubusercontent.com/6132593/176988769-a809797c-252f-4926-8f69-6b3d1f7af6c1.png)
