### ISSUE TITLE
2.0.0 sdk方式 select组件多出了第一项"Placeholder"

### ISSUE THREAD

**Issue by lfzfrj88** [baidu/amis#4761]
#### 描述问题：

使用2.0.0，sdk方式，select下拉列表多出了第一项"Placeholder"，这是一个bug？还是有新增的属性来控制是否显示？

#### 截图或视频：

![image](https://user-images.githubusercontent.com/108504969/176816461-d5388a6d-4511-4d3a-afd9-240edb31672e.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.0.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
   "type": "page",
   "body": {
      "type": "form",
      "body": [
         {
            "type": "select",
            "label": "选项",
            "name": "select",
            "options": [
               {
                  "label": "A",
                  "value": "a"
               },
               {
                  "label": "B",
                  "value": "b"
               },
               {
                  "label": "C",
                  "value": "c"
               }
            ]
         }
      ]
   }
}
```

4. 操作步骤
就复制使用的官网文档里里这一段代码，sdk方式，就能看到图示问题

**Comment by gillbates** [comment]
antd也有这个问题，我也遇到了。。。

**Comment by lfzfrj88** [comment]
2.0.1已修正此bug

**Comment by nwind** [comment]
fixed in #4827
