### ISSUE TITLE
amis-editor支持调用外部函数吗

### ISSUE THREAD

**Issue by hcf1997** [baidu/amis#4768]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：
![image](https://user-images.githubusercontent.com/86106459/176855260-c11398a9-b493-45e9-bbae-6899f9a8b05c.png)
![image](https://user-images.githubusercontent.com/86106459/176855272-78fb07d3-f3ef-4b9d-9c53-c5be83aae8e5.png)

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.8.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by wibetter** [comment]
看描述 没太明白你说的支持外部函数是什么意思。
目前使用amis过程中，可以自定义过滤器（https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/data-mapping#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%87%E6%BB%A4%E5%99%A8），也可以通过custom组件（https://aisuda.bce.baidu.com/amis/zh-CN/components/custom）使用一些自定义逻辑，看下这两个能否满足你的需求。
