### ISSUE TITLE
上半部动态添加条件，下半部分生成对应不同表头的表格

### ISSUE THREAD

**Issue by liguang0412** [baidu/amis#477]
如题，同一界面下，界面上半部分是筛选条件，筛选条件可以由多功能选择器条件不同的条件，而这些条件是对应的每个表头，筛选条件的不同，表头就不同，这种该怎么实现呢？

**Comment by 2betop** [comment]
service + schemaApi

**Comment by liguang0412** [comment]
Thank you for your answer！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liaoxuezhi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 晚上6:53
收件人:&nbsp;"baidu/amis"<amis@noreply.github.com&gt;;
抄送:&nbsp;"314452213"<314452213@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baidu/amis] 上半部动态添加条件，下半部分生成对应不同表头的表格 (#477)




service + schemaApi
