### ISSUE TITLE
怎么让amis 默认主题的整体字体调整大一点

### ISSUE THREAD

**Issue by hanwenlu2016** [baidu/amis#4770]
#### 实现场景：
主题字体太小了 官网没有针对整体字体调整的demo 只有单一控件

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by qkiroc** [comment]
:root {
  --fonts-size-1: 48px;
  --fonts-size-2: 40px;
  --fonts-size-3: 32px;
  --fonts-size-4: 24px;
  --fonts-size-5: 18px;
  --fonts-size-6: 16px;
  --fonts-size-7: 14px;
  --fonts-size-8: 12px;
  --fonts-size-9: 12px;
}   
调整这些css变量就行了
