### ISSUE TITLE
amis升级到2.0之后,select下拉框出现bug,多出一项placeHolder. 

### ISSUE THREAD

**Issue by 1204552371** [baidu/amis#4782]
#### 描述问题：
2.0的下拉框选项placeHolder使用的hidden,与.amis-scope .a-Select-option中样式冲突. 目前通过去掉.amis-scope .a-Select-option中的display:flex解决的此问题

#### 截图或视频：

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/51313581/177145076-18dce6f0-b13f-40ea-82ab-3a3ad747b5c4.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/51313581/177146338-1e0ed894-e8af-4b84-9000-29cce00364f3.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.0.0

**Comment by nwind** [comment]
fixed in #4827
