### ISSUE TITLE
CURD的bulkActions如果没有主键ID（或者是联合主键）的话可以批量提交吗？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#479]
场景是这样的，一个CURD绑定了多列（IP地址，端口号port，主机名host，……），没有主键id，但可以把IP+port两列合起来看成唯一主键。当前需要把批量勾选数据条目主机名都改成 XXX  ——这样可以实现？

amis给的示例里面是绑定了一个隐藏的ids的值，提交时可以把勾选的数据条目id用逗号拼成一个字符串一起提交给后端，但是如果是上述场景中联合主键的话要如何处理呢？

**Comment by foxfire881** [comment]
尝试了在bulkActions里面放两个ip、port两个字段，但是提交时只有勾选的第一条数据的IP、port被post到服务端了，其他勾选的数据条目都没有上传。

期望post出去的数据是这样的：
{ip:"ip1,ip2,ip3",port:"prot1,port2,port3"}

**Comment by foxfire881** [comment]
以下配置只能把勾选的第一条数据post到后端去，发出的数据是{ip: "10.0.13.21", port: 22, engine: "sss"}

bulkActions: [
                {
                    "label": "批量修改",
                    "actionType": "dialog",
                    "dialog": {
                        "title": "批量编辑",
                        "name": "sample-bulk-edit",
                        "body": {
                            "type": "form",
                            "api": "https://houtai.baidu.com/api/sample/bulkUpdate2",
                            "controls": [
                                {
                                    "type": "hidden",
                                    "name": "ip"
                                },
                                {
                                    "type": "hidden",
                                    "name": "port"
                                },
                                {
                                    "type": "text",
                                    "name": "engine",
                                    "label": "Engine"
                                }
                            ]
                        }
                    }
                }
            ]

**Comment by foxfire881** [comment]
又尝试给整个CURD增加一个隐藏的ID字段，用tpl写成"$ip-$port"，然后bulkActions里面用ids提交，这样提交的数据只是单独把port拼成字符串{"ids":"port1,port2,port3"}提交了, ip被丢了。

没辙了，求解。

**Comment by foxfire881** [comment]
primaryField弄成string类型适用范围太窄了，应该弄成数组才能解决联合主键问题吧

**Comment by foxfire881** [comment]
最后用了adapter大法，强制把“IP-Port”绑定成一个隐藏的ID列，勉强解决问题，但是太丑陋了一点也不优雅，后端解构也麻烦，等待看看官方有无好的解决方案。

**Comment by 2betop** [comment]
没那么麻烦，直接发送 items，就是一个数组

**Comment by foxfire881** [comment]
好用！原来还有这个items变量啊，这下方便多了。谢谢~
