### ISSUE TITLE
CRUD中如何确保数字小数点位数：例如:希望2位小数有效数字，没有则补0. eg: 5 显示5.00

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#4790]
#### 实现场景：
sdk.js

#### 存在的问题：
crud中数字的格式显示问题

#### 当前方案：
后端转为str字符串

**Comment by qsy1403813547** [comment]
![image](https://user-images.githubusercontent.com/46235687/177301646-2f82104b-8453-49fc-baa2-434fd774182b.png)
使用 过滤器 在 你写参数后面写上过滤器 例如： ${number}  默认是 5 ， 加上过滤器 ${number | round} 默认 显示 5.00

**Comment by qsy1403813547** [comment]
能不能 附上一部分代码啊 我不清楚你需要怎么样

**Comment by Jiangshan00001** [comment]
{
  "type": "page",
  "body": {
    "type": "crud",
    "api": "/amis/api/mock2/sample",
    "columns": [
      {
        "name": "id",
        "label": "ID"
      },
      {
        "name": "val",
        "label": "金额(希望如果传来数值是1.5，显示是1.50.如果传来的是2，则显示2.00)"
      }
    ]
  }
}

**Comment by qsy1403813547** [comment]
em 是 html  标签 字体比较好看

default 默认 就是 后端返回null 默认显示 0.00  

round  小数点

**Comment by qsy1403813547** [comment]
number  这个 是千分符 比如 1000000 就是 1，000，000

**Comment by qsy1403813547** [comment]
可以了吗

**Comment by Jiangshan00001** [comment]
试了,完美解决，多谢。
多写一个防止后期忘了，如果有人想要3位小数，则1改为 "tpl": " ${val | default:0 | round :3 | number} ",

**Comment by qsy1403813547** [comment]
🆗
