### ISSUE TITLE
CRUD组件bug

### ISSUE THREAD

**Issue by gaohui11202** [baidu/amis#4805]
CRUD组件bug，分页如果限定高度，数据出现纵向滚动条时，锁定列，错位了
![image](https://user-images.githubusercontent.com/16601914/177511670-61ff3ec6-c664-4542-b0bc-8f952bf6bfc7.png)

**Comment by meerkat-morecats** [comment]
可以试试把高度加在 contentWrap 上

**Comment by lurunze1226** [comment]
2.1.0 fixed
