### ISSUE TITLE
表格组件，数据提供不换行，多余部分...表示，鼠标放上去可以看全部

### ISSUE THREAD

**Issue by gaohui11202** [baidu/amis#4806]

**Comment by gillbates** [comment]
这个需求好。。。目前我是自己做的。。。后端返回2个字段。。。一个short，一个full。。。如果官方能支持当然最好了。

**Comment by qsy1403813547** [comment]
这个功能不是有了吗

**Comment by gaohui11202** [comment]
怎么用呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月7日(星期四) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] 表格组件，数据提供不换行，多余部分...表示，鼠标放上去可以看全部 (Issue #4806)





 
这个功能不是有了吗

**Comment by qsy1403813547** [comment]
![image](https://user-images.githubusercontent.com/46235687/177723073-160713c0-6ff7-4b13-a5d4-2f902a38952b.png)

**Comment by qsy1403813547** [comment]
是这种吗

**Comment by gaohui11202** [comment]
好的，我试试






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月7日(星期四) 下午4:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] 表格组件，数据提供不换行，多余部分...表示，鼠标放上去可以看全部 (Issue #4806)

**Comment by gaohui11202** [comment]
能加个qq吗，263655516，交流一下，用过vscode这个插件吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月7日(星期四) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] 表格组件，数据提供不换行，多余部分...表示，鼠标放上去可以看全部 (Issue #4806)





 
是这种吗

**Comment by qsy1403813547** [comment]
可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月7日(星期四) 下午4:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baidu/amis] 表格组件，数据提供不换行，多余部分...表示，鼠标放上去可以看全部 (Issue #4806)





 能加个qq吗，263655516，交流一下，用过vscode这个插件吗？ 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年7月7日(星期四) 下午4:03 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [baidu/amis] 表格组件，数据提供不换行，多余部分...表示，鼠标放上去可以看全部 (Issue #4806) 
 
 
 
 
 
   
 是这种吗
