### ISSUE TITLE
子弹窗可以关闭父弹窗吗？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#482]
场景是这样的：一个CRUD，点击某一条数据条目的操作按钮后弹出第一层弹窗Form1，在Form1中点击按钮又弹出一个Form2 —— 当前需求是在Form2中提交表单数据并返回成功后Form1、Form2都关闭掉，同时在保持原来页码的前提下刷新CRUD（因为还要继续操作其他数据条目，所以需要停留在当前页码，并且还想看到刚才上一条数据提交之后的刷新效果）

已经试了以下方式：
1、在Form2中设置reload CRUD，这样Form2提交后只有Form2自身关闭了，CRUD也刷新了，但Form1仍然显示着没有关闭。

2、在Form2中设置reload window，这样Form1、Form2都关闭了，CRUD也刷新了，但CRUD的当前页码也重置了，比如原本是停留在第8页的，reload后又变成第1页了，继续操作其他选项时很麻烦。并且右上角的操作成功提示条也不显示了。

3、在Form2中设置redirect，和reload window结果一样。

请问有没有什么办法，在Form2返回之后可以关闭Form1、关闭Form2，并且保持当前页的前提下刷新CRUD？ 最好还能保持有右上角的操作成功失败提示。

**Comment by foxfire881** [comment]
目前测试相对比较好的是方案1，只要Form2提交返回后能把父窗口Form1页关闭掉就完美了，不知道要怎么实现呢？

**Comment by 2betop** [comment]
第二个 form 用 按钮的 feedback 功能弹出来，同时这个按钮又是个可以关闭 form1 。如果按钮有 feedback，按钮在关闭弹窗千会等 feedback 完成再关闭。

**Comment by foxfire881** [comment]
> 第二个 form 用 按钮的 feedback 功能弹出来，同时这个按钮又是个可以关闭 form1 。如果按钮有 feedback，按钮在关闭弹窗千会等 feedback 完成再关闭。

试了好像有点问题：Form1上面的按钮如果有feedback的话一定要发送一个ajax并等待返回后才能把Form2弹出来，但是我的Form1就是一个静态的二级菜单按钮集合不需要发送ajax，点击Form1上面的不同按钮弹出不同的Form2，在Form2中提交表单才是完成不同的业务功能，Form1只是做菜单按钮展示没有任何动态业务功能的，不需要发送ajax —— 这种情况下要如何feedback弹出第二层Form2？

**Comment by 2betop** [comment]
那，目前没得办法

**Comment by foxfire881** [comment]
额……好吧，看来只能勉强先用着了，后面希望看看能否改进一下，多层弹窗还是有必要关闭父窗口的，很多时候都是最后一层弹窗才是具体的业务Form，提交之后应该所有的祖父窗口都关闭的，不然还有全局遮罩在页面上，操作其他数据条目很不方便。

**Comment by RickCole21** [comment]
新版应该支持了，用法 https://github.com/baidu/amis/issues/697#issuecomment-669164780

**Comment by RickCole21** [comment]
先关了，有问题再开
