### ISSUE TITLE
crud filter 搜索条件配置 重置问题

### ISSUE THREAD

**Issue by kunl** [baidu/amis#4823]
#### 实现场景：
crud filter，搜索条件配置  
```
  {
        "type": "input-text",
        "name": "tenantId",
        "label": "租户ID",
        "placeholder": "输入要查询的租户ID",
        "clearable": true
      }
```

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
如图，租户ID 在第一次查询的时候正常发送到后台，点击  x 后， input 内容显示为空，再次查询的时候，会发送一个空的请求；这样后台就按照 `空` 的条件查询了。
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/2870324/177910067-0ccd5cf0-65ca-4cd9-a61f-9ac642af4209.png">

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/2870324/177909996-7baa1603-b16f-40f9-880a-e24ec2c0d3f4.png">

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by lurunze1226** [comment]
可以在CRUD的api上配置一下 [发送数据映射](https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api?page=1#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E6%95%B0%E6%8D%AE)

**Comment by kunl** [comment]
> 可以在CRUD的api上配置一下 [发送数据映射](https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api?page=1#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E6%95%B0%E6%8D%AE)，过滤掉空值

好的，我先试试
