### ISSUE TITLE
crud渲染器，采用source获取值的时候不能分页了吗？

### ISSUE THREAD

**Issue by XiuPunica** [baidu/amis#483]
主要配置：

`
	{
		"type": "crud",
		"name": "bug列表",
                "loadDataOnce": true,
		"sm": 12,
		"source": "${bug_detail}",
                "columns" : []
        }
`

展示效果：
![image](https://user-images.githubusercontent.com/6257061/76178956-2d691f80-61f4-11ea-8d32-e1c8d053b152.png)

同样的内容，采用api来获取数据的时候，就可以出现分页效果。

**Comment by foxfire881** [comment]
关键问题是，能用api你为啥要用source？

**Comment by roytan883** [comment]
@foxfire881 @RickCole21 @XiuPunica @nwind @TeCHiScy

> 关键问题是，能用api你为啥要用source？

语义上就有歧义：
```
source | string |   | 数据映射接口返回某字段的值，不设置会默认使用接口返回的${items}或者${rows}，也可以设置成上层数据源的内容
```
既然文档上写使用接口或者数据域都可以，但是为什么就是api和source数据域返回完全相同数据，但UI表现是使用数据域的就没有分页？？？

但是如果你这样写文档，请问谁还后在source上使用数据域？那么更大的问题来了，既然只支持API，那amis还搞这一套数据域干什么？

**既然都已经"loadDataOnce": true，两种方式在数据上完全相同，结果展示不同，很明显的一个bug，只是不愿承认而已。**

再用picker中使用pickerSchema来举例，为什么不能用source，这里更加奇葩，文档写：`API 或 数据映射`，凭什么数据映射就低人一等不分页？**而且你不分页也可以啊，起码文档上写明啊！！！** **picker每次点击都要请求网络，理由呢，就因为要分页？？？**

建议官方在 [数据域与数据链](https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/datascope-and-datachain) 开头就写几个大字：
# 数据域不支持分页显示！！！
