### ISSUE TITLE
自定义过滤器中如何根据变量名，取得数据域中变量值

### ISSUE THREAD

**Issue by wencan** [baidu/amis#4833]
传入过滤器的参数，好像是字符串。
看amis实现，isEquals等过滤器，是根据参数中变量名，从数据域中取得变量值。
如果自定义的过滤器，要实现同样效果，应该怎么做？

**Comment by qsy1403813547** [comment]
自定义过滤器可以取值啊

**Comment by hsm-lv** [comment]
过滤器使用时会传入变量，这些变量是作为参数到你的自定义过滤器函数中的
