### ISSUE TITLE
select控件的默认值

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#484]
我的select控件是使用source api属性动态获取options，能否设置：当api返回的options为空时，select默认是空；当api返回的options非空时，select默认选中第一个option？

**Comment by RickCole21** [comment]
`options`同级传`value`属性，如下：
```
{
 "status": 0,
 "msg": "",
 "data": {
     "value": "a", // 这样会默认选中A
     "options": [
         {
             "label": "OptionA",
             "value": "a"
         },
         {
             "label": "OptionB",
             "value": "b"
         }
     ]
 }
}
```

**Comment by foxfire881** [comment]
> `options`同级传`value`字段，如下：

谢谢，不过您好像没有领会我的意思啊。 我的source是从后端API动态获取的，返回结果可能有3个option，可能有5个option，也可能一个都没有；可能包含value a，也可能没有包含value a，所以给它设置一个定值是不行的。

目标是希望根据返回的索引号来设置value，如果返回的options大于1个，那就默认选中index=0的option，它可能是value a，也可能不是value a；如果范围的options为空，那select默认也是空。

**Comment by RickCole21** [comment]
我说的就是后端来动态处理`value`值啊，你后端根据options来决定你要传给前端的`value`值是啥

**Comment by 2betop** [comment]
后端确实是可以，但是前端我感觉也可以考虑加个 defaultSelectedIndex 之类的配置

**Comment by foxfire881** [comment]
> 我说的就是后端来动态处理`value`值啊，你后端根据options来决定你要传给前端的`value`值是啥

原来如此，要在后端动刀呀，好的谢谢~ 幸好自己做的小项目前后端都是我一个人控制的，改后端也还好，如果是跨部门调用其他系统的api和其他开发人员合作项目的话可能就没这么顺利了，如果能在前端加个属性最好啦

**Comment by RickCole21** [comment]
https://baidu.gitee.io/amis/zh-CN/docs/components/form/options#%E9%9D%99%E6%80%81%E9%85%8D%E7%BD%AE

使用 `"selectFirst": true`
