### ISSUE TITLE
CRUD批量操作的复选框是disabled(版本2.0.1)

### ISSUE THREAD

**Issue by dotty-gua** [baidu/amis#4850]
如下图：
<img width="534" alt="截屏2022-07-12 01 21 25" src="https://user-images.githubusercontent.com/56525941/178321915-b8682930-0d10-4911-a0fc-272f890c29a0.png">

**Comment by belongwqz** [comment]
确实是，看来2.0版本没法用了，再等一个月的2.1

**Comment by nwind** [comment]
fixed in #4829

**Comment by dotty-gua** [comment]
> 确实是，看来2.0版本没法用了，再等一个月的2.1

别别，这点小破bug影响不了我更到最新版~~~~~~~~
