### ISSUE TITLE
amis-editor编辑器启动出错

### ISSUE THREAD

**Issue by qianxiaofendou** [baidu/amis#4851]
#### 描述问题：

amis-editor启动出现错误，如下图：

![image](https://user-images.githubusercontent.com/20673152/178392711-c9531f7b-bf9f-4f94-bd36-0878c06d7a86.png)

使用版本如下：
```
***
"amis": "2.0.1",
 "amis-editor": "5.1.8",
***
```

项目里面使用到了以下UI组件
```
import {ToastComponent, AlertComponent, Button, Drawer, Editor as AEditor, InputBox, prompt, toast} from 'amis-ui';
```

辛苦看下这个问题！！！

**Comment by knight-peter** [comment]
我也遇到了这样的问题，尝试了几次没法搞定

**Comment by qianxiaofendou** [comment]
> https://github.com/aisuda/amis-editor-demo

试了下把amis升级到2.0.2，amis-editor升级到5.1.9还是会出现这个问题，项目引用如下：

```javascript
import React, { useCallback, useRef, useEffect, useState } from 'react'
import {ToastComponent, AlertComponent, Button, Drawer, Editor as AEditor, InputBox, prompt, toast} from 'amis-ui';
import { Editor } from 'amis-editor'
import axios from 'axios';
import copy from 'copy-to-clipboard'
import { saveAs } from 'file-saver';
import { useImmer } from "use-immer"
import Header from '../header'
import { getUrlParams, isNumber } from '../../utils'
```

我项目里面确实是只import了一次 ，但是我把import { Editor } from 'amis-editor'去掉就正常了 所以现在不清楚是不是amis-editor的问题 辛苦再看一下

**Comment by qianxiaofendou** [comment]
@nwind @2betop

**Comment by qianxiaofendou** [comment]
@nwind 查看下来是amis2.0之后的版本的入口文件同时包含`module` 和`main`，而2.0之前的版本的入口只有`main`，下图是2.0.2的入口截图

![image](https://user-images.githubusercontent.com/20673152/179647540-961c2d62-f1a1-4f20-acd3-b60e2f2bbdcf.png)

根据webpack(https://webpack.docschina.org/configuration/resolve/#resolveimportsFields)的文档来看，是优先读取`module`入口，没有则读取`main`入口，而`amsi-edit`中有显示的从`amis/lib`下import，也有从`amis`中import的，如下图

![image](https://user-images.githubusercontent.com/20673152/179649191-a2b0be34-e526-400f-967e-de2983db9850.png)

`amis`2.0.2之后的版本是否可去去掉`module`入口，跟 amis2.0 之前的版本保持一致，只需要`main`入口即可，请问是否可行呢

**Comment by hsm-lv** [comment]
可以尝试升级webpack到5.x，并配置conditionNames: ['require', 'node']

**Comment by 0undefined0** [comment]
> 可以尝试升级webpack到5.x，并配置conditionNames: ['require', 'node']

主要是用的umi3.5 是否我们可以从amis本身解决呢

**Comment by Niqian** [comment]
同求一个解决方案，目前项目框架已经稳定，贸然升级webpack会导致很多问题，是否能在amis内部处理，屏蔽多入口的问题
