### ISSUE TITLE
react 版本，在Edge浏览器IE11模式下打开页面，发现页面一片空白，想问下目前对IE的支持情况是怎么样的

### ISSUE THREAD

**Issue by XinKlaus** [baidu/amis#4864]
因项目需要，准备在Edge浏览器下切换到IE模式运行项目，但是发现应用跑不起来。
虽然也看到了以往关于IE11的一些issue，但大部分都是JS SDK版本的，我个人也对IE深恶痛绝，但身在其中没有办法，还是想问下目前的情况是什么样的。

- 想了解下团队这边对IE11的支持情况是什么样的，会专门维护IE11这个运行环境吗？
- 如果想要兼容，从babel配置或者在入口文件增加polyfill文件的方式，还可行吗？目前尝试过之后，页面还是一片空白，控制台报：TypeError: 对象不支持“xxx” 这样的错误。所以想确认下，硬去支持这个IE的方式，可行性怎么样哦！

**Comment by nwind** [comment]
加 polyfill 应该还是能用，得通过 IE 调试工具看看具体是哪行报错，才能定位问题
