### ISSUE TITLE
React 18 注册自定义类型

### ISSUE THREAD

**Issue by ThinkontrolSY** [baidu/amis#4865]
#### 实现场景：
使用react18，按文档 [注册自定义类型](https://baidu.github.io/amis/zh-CN/docs/extend/custom-react) , 出现如下错误，请问在react18中如何注册自定义类型

#### 存在的问题：

(alias) Renderer(config: RendererBasicConfig): <T extends RendererComponent>(component: T) => T
import Renderer
Decorator function return type 'RendererComponent' is not assignable to type 'void | typeof MyRect'.
  Type 'ComponentClass<RendererProps, any> & { propsList?: any[] | undefined; }' is not assignable to type 'void | typeof MyRect'.
    Type 'ComponentClass<RendererProps, any> & { propsList?: any[] | undefined; }' is not assignable to type 'typeof MyRect'.
      Types of parameters 'props' and 'props' are incompatible.
        Type 'MyRectProps | Readonly<MyRectProps>' is not assignable to type 'RendererProps'.
          Type 'MyRectProps' is missing the following properties from type 'RendererProps': render, env, $path, $schema, and 5 more.ts(1270)
Argument of type 'typeof MyRect' is not assignable to parameter of type 'RendererComponent'.
  Type 'typeof MyRect' is not assignable to type 'ComponentClass<RendererProps, any> & { propsList?: any[] | undefined; }'.
    Type 'typeof MyRect' is not assignable to type 'ComponentClass<RendererProps, any>'.
      Types of parameters 'props' and 'props' are incompatible.
        Type 'RendererProps' is not assignable to type 'MyRectProps | Readonly<MyRectProps>'.
          Type 'RendererProps' has no properties in common with type 'Readonly<MyRectProps>'.ts(2345)

```tsx
import React from 'react';

import { Renderer, RendererProps } from 'amis';

interface MyRectProps {
  /**
   * The status of the rectangle
   */
  status?: 'primary' | 'secondary';
  /**
   * What background color to use
   */
  backgroundColor?: string;
  /**
   * How large should the button be?
   */
  size?: 'small' | 'medium' | 'large';
  /**
   * Button contents
   */
  label?: string;
  /**
   * Optional click handler
   */
  onClick?: () => void;
}

@Renderer({
  type: 'my-rect',
  autoVar: true,
})
export class MyRect extends React.Component<MyRectProps> {
  render(): React.ReactNode {
    const backgroundColor = this.props.backgroundColor || 'red';
    const size = this.props.size || 'medium';
    const label = this.props.label || 'test';
    const onClick = this.props.onClick;
    const status = this.props.status || 'primary';
    return (
      <div
        style={{
          backgroundColor,
          width: size == 'large' ? '100px' : size == 'medium' ? '80px' : '40px',
          height:
            size == 'large' ? '100px' : size == 'medium' ? '80px' : '40px',
        }}
      >
        {status}
        <button onClick={onClick}>{label}</button>
      </div>
    );
  }
}
```

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/11331554/178672173-736d8fde-3079-4eeb-949e-fd66b483b556.png">

**Comment by nwind** [comment]
参考 https://baidu.github.io/amis/zh-CN/docs/extend/contribute

```
interface MyRectProps extends RendererProps {
}
```
