### ISSUE TITLE
amis有什么可以设置全局参数的地方吗？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#487]
用的是amis的SDK模式。

主要是想用在登录认证方面，登录后服务端会返回一个token，以后所有向服务端api发送的请求都必须带上这个token才能访问。如果amis每个页面中的api都要单独设置token参数会很麻烦，并且还涉及到跨页面的问题，所以看看是否有啥地方可以设置全局参数token，以后所有的请求都带上这个token？

**Comment by foxfire881** [comment]
当前是把用户认证信息放在服务端session中的，虽然能用但遇到一些奇怪的问题，所以想换成token认证的方式，于是遇到这个问题。

**Comment by 2betop** [comment]
自己实现一下 fetcher 就行了

**Comment by foxfire881** [comment]
https://baidu.github.io/amis/docs/getting-started
抱歉，这个文档没怎么看得太明白。主要是涉及到跨页面获取参数的问题，不知道咋整。

根据这个文档fetcher用来发送ajax请求，但返回也只是给当前页面的。在登陆页面A上输入账号密码提交，后端返回token，那么下一次再B页面上怎么获取这个token呢？能否给个示例？

**Comment by 2betop** [comment]
cookie, localstorage 里面都能存啊

**Comment by foxfire881** [comment]
额。。可能是我的架构设计有点问题。。。我的页面是单纯的json文件，作为一个变量传入统一的一个html模板（就是示例中给的那段js代码）渲染，所以只有那个html页面能执行js。我以为amis框架本身可以支持跨页面传参的。
