### ISSUE TITLE
请教amis2.0执行build.sh打包的问题

### ISSUE THREAD

**Issue by lglbeo** [baidu/amis#4874]
#### 实现场景：
原先在项目没有采用monorepo的时候，项目打包可以直接在根目录下执行build.sh，然后在lib目录可以找到完整的包程序。升级到2.0以后，我蒙圈了，在根项目下，执行yarn workspace run bulid之后，在各个子模块下都会有一个lib文件夹，感觉像是把原先的lib拆散到各个子项目里去了
#### 存在的问题：
想让2.0执行build.sh打出来的lib包跟1.x的lib一样，来自小白的求救，谢谢。
```
code here...
```

**Comment by nwind** [comment]
项目引用的时候需要引入 amis、amis-ui、amis-core，这样才和之前一样，不会有一个统一的了，这样的好处是后面可以自己基于 amis-core 完全实现自己内部组件
