### ISSUE TITLE
Rich-Text报错 init is not function

### ISSUE THREAD

**Issue by ChangYujieCN** [baidu/amis#489]
打开node-modules里面 发现RichText和Editor这两个是注释掉的

**Comment by babulongbo007** [comment]
RichText.js:48 Uncaught (in promise) TypeError: init is not a function
    at RichText.js:48
    at Array.forEach (<anonymous>)
    at Object../node_modules/_amis@1.0.9@amis/lib/components/RichText.js (RichText.js:48)
    at __webpack_require__ (bootstrap:63)
    at RichText.js:11

**Comment by 2betop** [comment]
怎么用的？

**Comment by babulongbo007** [comment]
我这边按照文档配置富文本
{
                type: "group",
                label: "习题设置",
                mode: "normal",
                controls: [
                    {
                        type: "rich-text",
                        label: "题干输入："
                    },
                    {
                        type: "rich-text",
                        label: "题干输入："
                    },
                    {
                        type: "rich-text",
                        label: "题目输入："
                    }
                ]
            }
但是浏览器控制台显示这个报错
@2betop

**Comment by 2betop** [comment]
什么用法？哪来的 webpack_require

**Comment by babulongbo007** [comment]
在执行到RichText.js文件时，
----------------------------------------------------------------------
// Require Editor JS files.
// import 'froala-editor/js/froala_editor.pkgd.min.js';
[
    require('froala-editor/js/froala_editor.min.js'),
    require('froala-editor/js/plugins/align.min'),
    require('froala-editor/js/plugins/char_counter.min'),
    require('froala-editor/js/plugins/code_beautifier.min'),
    require('froala-editor/js/plugins/code_view.min'),
    require('froala-editor/js/plugins/colors.min'),
    require('froala-editor/js/plugins/draggable.min'),
    require('froala-editor/js/plugins/emoticons.min'),
    require('froala-editor/js/plugins/entities.min'),
    // require('froala-editor/js/plugins/file.min'),
    require('froala-editor/js/plugins/font_family.min'),
    require('froala-editor/js/plugins/font_size.min'),
    require('froala-editor/js/plugins/forms.min'),
    require('froala-editor/js/plugins/fullscreen.min'),
    require('froala-editor/js/plugins/help.min'),
    require('froala-editor/js/plugins/image.min'),
    require('froala-editor/js/plugins/image_manager.min'),
    require('froala-editor/js/plugins/inline_class.min'),
    require('froala-editor/js/plugins/inline_style.min'),
    require('froala-editor/js/plugins/line_breaker.min'),
    require('froala-editor/js/plugins/line_height.min'),
    require('froala-editor/js/plugins/link.min'),
    require('froala-editor/js/plugins/lists.min'),
    require('froala-editor/js/plugins/paragraph_format.min'),
    require('froala-editor/js/plugins/paragraph_style.min'),
    require('froala-editor/js/plugins/print.min'),
    require('froala-editor/js/plugins/quick_insert.min'),
    require('froala-editor/js/plugins/quote.min'),
    require('froala-editor/js/plugins/save.min'),
    require('froala-editor/js/plugins/special_characters.min'),
    require('froala-editor/js/plugins/table.min'),
    require('froala-editor/js/plugins/url.min'),
    require('froala-editor/js/plugins/video.min'),
    require('froala-editor/js/plugins/word_paste.min')
].forEach(function (init) {  return init(); });
---------------------------------------------------
出现了错误，说的是init不是函数，是否是引入的插件有问题哪？

**Comment by 2betop** [comment]
这必须是存在的，看看你们编译相关是不是除了什么问题。

**Comment by 2betop** [comment]
https://github.com/fex-team/amis-admin/tree/gh-pages

**Comment by 2betop** [comment]
看下这个里面的有错没？https://github.com/fex-team/amis-admin/tree/webpack

**Comment by ChangYujieCN** [comment]
1.拉取amis-admin webpack分支  
2.将routes/admin/Dashboard.tsx   里面的schem直接替换为富文本
```json
{
    "type": "page",
    "body": {
        "title": "",
        "type": "form",
        "mode": "horizontal",
        "autoFocus": false,
        "controls": [
            {
                "type": "rich-text",
                "name": "html",
                "label": "Rich Text"
            }
        ],
        "submitText": null,
        "actions": []
    }
}
```
3.npm start 错误复现
@2betop

**Comment by 2betop** [comment]
ok，这就明了多了，我试试看

**Comment by babulongbo007** [comment]
webpack的配置与文档上面的一致

**Comment by 2betop** [comment]
https://github.com/fex-team/amis-admin/commit/8cc73ae123e33ad1ec577f2605ea4b7d066bca3e

**Comment by ChangYujieCN** [comment]
@2betop Many thanks!
