### ISSUE TITLE
无法编译出sdk

### ISSUE THREAD

**Issue by xiaoxi-note** [baidu/amis#490]
执行： 
sh publish.sh 
输出:
 [WARNI] Can't resolve `vertx` in file [/node_modules/flv.js/dist/flv.js], did you miss `npm install vertx`?
...
 [WARNI] Can't resolve `moduleId` in file [/node_modules/monaco-editor/esm/vs/base/common/worker/simpleWorker.js], did you miss `npm install moduleId`?
...
 [ERROR] unable to load plugin [fis3-deploy-skip-packed] or [fis-deploy-skip-packed]

并没有输出 sdk，请问应该怎么自己编译sdk？

**Comment by 2betop** [comment]
少了这个插件 `fis3-deploy-skip-packed`, npm 安装一把
