### ISSUE TITLE
官方示例中能否提供一个类似GitHub Issue列表的demo

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#4903]
Demo 列表的效果类似下图：
![image](https://user-images.githubusercontent.com/5292190/179348653-73580839-21dd-456f-b586-5607ad0a9221.png)
个人觉得这个列表的应用模式，要比官方的给出的List模式，实用很多。

官方list如下图：
![image](https://user-images.githubusercontent.com/5292190/179348823-7d137ce4-2266-483d-bba6-d42508066ec4.png)

希望官方能够给提供类似这种样式的版本，应用场景会非常广泛,品质也会上一个层次。
感谢！

**Comment by allenve** [comment]
这个比较类似：https://aisuda.bce.baidu.com/amis/examples/crud/list?page=1&mode=mode1
