### ISSUE TITLE
日期和时间组件样式异常

### ISSUE THREAD

**Issue by ufologist** [baidu/amis#491]
我基于 [amis-admin 的 webpack 分支](https://github.com/fex-team/amis-admin/tree/webpack) 搭建了一个简单的应用, 发现日期和时间相关的组件样式异常, 以"时间范围"组件为例

![rdtPicker-style-exception](https://user-images.githubusercontent.com/167221/76674321-27ef4900-65e9-11ea-992b-081ac732da9a.png)

[比较线上版本的样式](https://fex-team.github.io/amis-admin/admin/form/basic)后发现, 线上的版本有部分额外的样式(以 `.rdtPicker` 为例), 并没有包含在 `amis/lib/themes/default.css` 样式文件中

![rdtPicker1](https://user-images.githubusercontent.com/167221/76674656-d9dc4480-65ec-11ea-9c59-05ff52cabeae.png)

![rdtPicker2](https://user-images.githubusercontent.com/167221/76674659-dea0f880-65ec-11ea-9d3f-84f723cadbf0.png)

去查找源码, 发现也没有在 [_date-range.scss](https://github.com/baidu/amis/blob/b58c2d34fc7dd0eb243a949e4898cbfcbf5b2b27/scss/components/form/_date-range.scss) 或 [_date.scss](https://github.com/baidu/amis/blob/b58c2d34fc7dd0eb243a949e4898cbfcbf5b2b27/scss/components/form/_date.scss) 中定义

同时观察到这些样式是统一打包到 `style.css` 文件中的, 因此看了一下基于 `fis3` 的构建配置 [fis-conf.js](https://github.com/fex-team/amis-admin/blob/979f6fe713acf0e8a01917aaf20a05d8c41bef8c/fis-conf.js#L43), 发现这个 `style.css` 是将 `node_modules` 目录下所有的样式文件打包在了一起

因此搜索了一下本地 `node_modules` 目录, 看额外的 `.rdtPicker` 样式是在哪里定义出来的. 果不其然, 发现 `node_modules/amis/sdk/sdk.css` 和 `node_modules/react-datetime/css/react-datetime.css` 有额外定义这个样式. `sdk.css` 可以排除掉, 是给 [JSSDK 用法](https://baidu.github.io/amis/docs/getting-started#jssdk)的.

因此我们只需要在自己的应用中额外导入 `import 'react-datetime/css/react-datetime.css';` 这个样式就恢复正常了.

这个是由于 `AMis` 有些依赖的样式并没有统一打包在他的样式文件中造成的, 考虑到是否还有其他遗漏, 我搜索了一下 [baidu/amis](https://github.com/baidu/amis/search?l=TSX&q=.css), 发现类似遗漏的还有 `cropper.css`
* [Select.tsx `import 'react-datetime/css/react-datetime.css';`](https://github.com/baidu/amis/blob/13ae3a07c0f8014d690c93d37cc256dd9826ae8c/src/components/Select.tsx#L10)
* [Image.tsx `@require 'cropperjs/dist/cropper.css';`](https://github.com/baidu/amis/blob/01a8b8293a87655cfeabdeb16eb8d8e2f8bc4336/src/renderers/Form/Image.tsx#L3)
* [Video.tsx `import 'video-react/dist/video-react.css';`](https://github.com/baidu/amis/blob/846536f823ddb876993798a698bae297eeba09f7/src/renderers/Video.tsx#L21)

目前在不知道官方什么时候修复这个问题的情况下, 请在自己的应用中导入如下样式, 避免日期组件和图片裁剪组件出现样式问题
```javascript
import 'react-datetime/css/react-datetime.css';
import 'cropperjs/dist/cropper.css';
import 'video-react/dist/video-react.css';
```

**Comment by 2betop** [comment]
求个 pr，谢谢

**Comment by 2betop** [comment]
不用了，我自己修改吧，我貌似是特意把 import css 给干掉了

**Comment by 2betop** [comment]
我已经修改好了，npm 版本中会保留 `require('xxx.css')` 源码，之前是只有 fis3 才认识的注释依赖标记。

**Comment by ufologist** [comment]
[配页坊: 简称配方 - 为配置页面而生, 专注于配置后台页面](https://github.com/ufologist/page-schema-player)

基于 amis-admin 提供以配置的方式快速搭建(后台)页面的能力, 释放前端人力, 提升整体人效

试一试 [Playground](https://ufologist.github.io/page-schema/_demo/index.html)

![page-schema-playground](https://user-images.githubusercontent.com/167221/77224470-ef2f1100-6ba0-11ea-8506-358c6c30e357.gif)

**Comment by ufologist** [comment]
基于自己在应用 AMis 过程中的实践, 整理出了 [AMis 实用手册](https://github.com/ufologist/page-schema-player/blob/master/amis-cookbook.md)
