### ISSUE TITLE
InputDateRange 日期范围组件存在bug

### ISSUE THREAD

**Issue by weiailuxueqi** [baidu/amis#4910]
#### 描述问题：

日期范围面板展开后，点击日期范围面板外的地方，面板关闭后，日期范围显示的值不见了，但是提交表单时，日期范围的值又正常被提交了。

#### 截图或视频：
请直接从18秒开始观看。
https://user-images.githubusercontent.com/27498426/179651534-50847e47-6103-4381-b44d-db76f3d47e85.mp4

#### 如何复现（请务必完整填写下面内容）：

直接通过官方的[文档示例](https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-date-range)即可复现。

#### 操作步骤
日期范围面板展开后，点击日期范围面板外的地方，面板关闭后，日期范围显示的值不见了，但是提交表单时，日期范围的值又正常被提交了。

**Comment by lurunze1226** [comment]
2.1.0 版本修复了，没有确定时不会更新到数据域
