### ISSUE TITLE
以 amis-admin 为蓝本写了个项目实战教程

### ISSUE THREAD

**Issue by mrsdpz** [baidu/amis#4917]
项目地址https://github.com/mrsdpz/amis-admin
第一章: https://github.com/mrsdpz/amis-admin/blob/master/book/1.md
实现了跨域 登录 环境区分 以及 yaml 写法
预计一周一更
手把手完整的实现一个管理系统,应该会涉及 amis 的绝大部分概念

**Comment by wencan** [comment]
很期待。但看起来几个月没更新了
