### ISSUE TITLE
在JS中如何触发amis的事件?

### ISSUE THREAD

**Issue by zhangxx2015** [baidu/amis#4921]
#### 实现场景：
monaco编辑器中按下快捷键时,事件不会被触发
```
{
    "type": "editor",
    "name": "sourcecode",
    "label": "",
    "language": "javascript",
    "allowFullscreen": true,
    "editorTheme": "vs-dark",
    "size": "xxl",
    "options": {
        "lineNumbers": "on",
    },
    "editorDidMount": (editor, monaco) => {
        editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_R, function () {
            // var val=editor.getValue(); // 这里可以获取到内容
            debugger // 这里不会中断
        });
    }
}
```

#### 存在的问题：
monaco-editor无法获取事件

#### 当前方案：
使用 document.onkeydown 实现全局快捷键
但是不知道如何触发 action 按钮的 click 事件?
```
document.onkeydown=function(){
    if( event.ctrlKey && event.keyCode == 82 || //Ctrl + R
        event.ctrlKey && event.keyCode == 83) { //Ctrl + S
        if(event.keyCode==82){//Ctrl + R
            amisScoped.getComponentById("terminal").doAction({type: 'click'});
            ////// **这里如何触发 action 按钮的 click 事件?**
        }
        if(event.keyCode==83){//Ctrl + S
            amisScoped.getComponentById("coder").doAction({type: 'submit'}); // 这个表单事件可以被触发
        }
        event.keyCode = 0;
        event.returnValue = false;
        return;
    }
}
```

**Comment by qsy1403813547** [comment]
什么意思

**Comment by zhangxx2015** [comment]
> 什么意思

在monaco编译器里面写代码的时候,希望使用快捷键Ctrl+R调用AMIS的功能,
但是使用monaco提供的方法注册快捷键,事件无法触发 ( 被 AMIS 拦截了 )
editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_R, function () {

现在想用全局的事件实现快捷键
document.onkeydown=function(){
       if(event.keyCode==82){//Ctrl + R
       // 这里要使用 JS 触发 AMIS 按钮的 click 事件
       }
}
在事件被触发以后,怎么才能使用 JS 触发 AMIS 的事件

**Comment by hyzx86** [comment]
事件广播试过么
参考 https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action

**Comment by DataAlert-cn** [comment]
为什么我"editorDidMount": 后面的内容不带双引号就报错呢？

**Comment by hyzx86** [comment]
我这么写的，并没有任何问题啊

``` javascript
{
                            "type": "editor",
                            "label": "Script",
                            "name": "decodedQuery",
                            "id": "u:57b6fb4bc910",
                            "language": "javascript",
                            editorDidMount,// 直接给函数名称
}
```

或许你可以试试 加载完 json对象后 修改 属性 比如  jsonSchema.find(x=>x.type=="editor").editorDidMount= editorDidMount

**Comment by DataAlert-cn** [comment]
> 我这么写的，并没有任何问题啊
> 
> ```js
> {
>       "type": "editor",
>       "label": "Script",
>       "name": "decodedQuery",
>       "id": "u:57b6fb4bc910",
>       "language": "javascript",
>       editorDidMount,// 直接给函数名称
> }
> ```
> 
> 或许你可以试试 加载完 json对象后 修改 属性 比如 jsonSchema.find(x=>x.type=="editor").editorDidMount= editorDidMount

我用的是“App 多页应用”，页面是json文件，没法在json中直接写函数，只能通过双引号引起来，你说的这两个方式似乎都不能用。
https://aisuda.bce.baidu.com/amis/zh-CN/components/app

**Comment by hyzx86** [comment]
@DataAlert-cn  所以。。你用的是 SDK咯？

**Comment by DataAlert-cn** [comment]
> @DataAlert-cn 所以。。你用的是 SDK咯？

是的

**Comment by hyzx86** [comment]
自己打包个自定义组件吧，想咋玩就咋玩
比如 新建一个 my-editor

**Comment by westeast** [comment]
> > [@DataAlert-cn](https://github.com/DataAlert-cn) 所以。。你用的是 SDK咯？
> 
> 是的

最终解决了吗？ json中如何写这个函数呢

**Comment by hyzx86** [comment]
直接写字符串或函数就行
参考 自定义js事件 文档

https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E8%87%AA%E5%AE%9A%E4%B9%89-js
