### ISSUE TITLE
autoFillHeight配置导致的bug(急)

### ISSUE THREAD

**Issue by ztky01** [baidu/amis#4935]
autoFillHeight配置导致的bug(急)
使用方式  JS SDK
所述情况均处于autoFillHeight=true时
1.当页面列太多出现横向滚动条时,批量勾选某列,并向右稍微滑动一点时,会出现如图的效果,出现横向滚动但不滑动的话不会有次效果.
2.页面初始时高度已撑满,但是当筛选条件收起时,表格区域会出现大面积空白区域.如图.
3.在360极速浏览器中,数据纵向滚动时,滚着滚着表头就消失了,如图.
![image](https://user-images.githubusercontent.com/54745508/180154664-3d0e4dd6-3c87-4801-8f91-ea0dbb082512.png)
![image](https://user-images.githubusercontent.com/54745508/180154448-a26880f8-99ef-49e0-b448-098e3998d807.png)
![image](https://user-images.githubusercontent.com/54745508/180154849-a9f06ad4-d0da-4877-a1f6-83a22101c013.png)
![image](https://user-images.githubusercontent.com/54745508/180155531-75cdba1f-d740-4652-99b4-ba4ffb2e2a2e.png)
![image](https://user-images.githubusercontent.com/54745508/180155651-44ea0a66-f100-48de-a3ce-054d86946f5c.png)
![image](https://user-images.githubusercontent.com/54745508/180155762-d29b902a-48b3-4087-befe-325eb9666707.png)

**Comment by githubliujiawei** [comment]
我也遇到这个问题了，设置完"autoFillHeight": true, 同时设置了bulkActions  ，如果出现了横向滚动条，那么拖动滚动条就出现左侧复选框超出表格边界的问题，期望修复一下

**Comment by ztky01** [comment]
再补充一个截图
对了  用的是最新版js sdk
![image](https://user-images.githubusercontent.com/54745508/180380233-028cdd47-5914-44c1-a658-c036ec0fd799.png)

**Comment by ljy572887369** [comment]
同问题，求解决

**Comment by ztky01** [comment]
@nwind 求助

**Comment by lurunze1226** [comment]
试试2.1.0版本吧

**Comment by ztky01** [comment]
![image](https://user-images.githubusercontent.com/54745508/182060897-72bb2235-7a78-42a7-b490-9f602b9b37ba.png)
第一个问题:好了一些,但还是有一点点小瑕疵
第二个问题:问题依旧
第三个问题:已修复;

**Comment by ztky01** [comment]
补充一下
第一个问题:数据少的时候看不出问题,行数和列数稍微多一些问题就显现出来了;

**Comment by hsm-lv** [comment]
merged to https://github.com/baidu/amis/issues/7606
