### ISSUE TITLE
有纯净版的Schema么？

### ISSUE THREAD

**Issue by ayiaq1** [baidu/amis#4940]
#### 能否将UI与低代码完全分隔：
希望用公司内部的UI组件库实现这一套JSON配置化，type:'input' 目前是完全使用的内置版本。

#### 预期的解决方案：
完全分隔低代码与UI库，核心库是否可以只包含渲染相关的？

**Comment by nwind** [comment]
目前已经拆分了，可以只用 amis-core，但不推荐，因为很多低代码功能是实现在组件内部的，外部的 UI 组件通常没有这些功能，比如 api 加载
