### ISSUE TITLE
表单渲染器的 messages.saveSuccess 实现与文档不符

### ISSUE THREAD

**Issue by ufologist** [baidu/amis#495]
从 [Form](https://baidu.github.io/amis/docs/renderers/Form/Form) 的文档上看, 是可以配置 `messages.saveSuccess` 来自定义保存成功时的提示
> 用于消息提示覆写，默认消息读取的是 API 返回的消息，但是在此可以覆写它。

但从 [amis/src/store/form.ts#saveRemote](https://github.com/baidu/amis/blob/6bce88c92def036975ee5d3cf40717092badfdcc/src/store/form.ts#L278) 上看, 怎么都是优先使用的 API 返回的消息
```javascript
self.updateMessage(json.msg || (options && options.successMessage));
```

PS: [Form](https://baidu.github.io/amis/docs/renderers/Form/Form) 文档中 `messages.saveFailed` 和 `messages.saveSuccess` 的描述搞反了

**Comment by 2betop** [comment]
目前确实是接口优先，
