### ISSUE TITLE
增查删改控件无法使用initapi获取数据

### ISSUE THREAD

**Issue by liuzhe1947** [baidu/amis#4957]
请教一下 增查删改控件,想实现initapi 获取数据,存放到数据映射中,使用表达式来实现按钮显示 隐藏.
但是在增查删改控件中这个方法好像失效了,请教一下实现方法,感谢.

**Comment by lurunze1226** [comment]
CRUD没有这个属性，使用[Service](https://aisuda.bce.baidu.com/amis/zh-CN/components/service) 组件包裹一层吧
