### ISSUE TITLE
dialog组件setValue动作有时候会丢失值

### ISSUE THREAD

**Issue by iaoe** [baidu/amis#4958]
#### 描述问题：
我在combo中嵌套了一个，dialog类型的表单弹窗，表单提交后给combo中setValue，这个操作经常会出现丢失一部分值，大概10次会有3,4次。用的是sdk版本，2.0.2

#### 截图或视频：

![image](https://user-images.githubusercontent.com/102523291/180446110-c8de2792-8fe6-457a-b3f0-dade81b0e0df.png)

#### 如何复现（这是完整json配置）：
```
{
  "type": "page",
  "body": {
    "title": "创建表",
    "debug": true,
    "type": "form",
    "actions": [
      {
        "label": "提交",
        "actionType": "confirm",
        "type": "button",
        "level": "primary"
      },
      {
        "type": "button",
        "label": "生成sql",
        "level": "light",
        "actionType": "ajax",
        "api": "",
        "feedback": {
          "title": "操作成功",
          "body": "xxx 已操作成功"
        }
      }
    ],
    "body": [
      {
        "type": "combo",
        "name": "tables",
        "value": [
        ],
        "minLength": 1,
        "messages": {
          "minLengthValidateFailed": "最少添加一张表"
        },
        "multiLine": true,
        "multiple": true,
        "typeSwitchable": false,
        "conditions": [
          {
            "label": "iceberg ",
            "test": "this.tableType === \"iceberg\"",
            "scaffold": {
              "tableType": "iceberg"
            },
            "items": [
              {
                "type": "input-group",
                "name": "fullyName",
                "label": "${tableType}表",
                "body": [
                  {
                    "type": "select",
                    "size": "sm",
                    "required": true,
                    "name": "databaseName",
                    "placeholder": "请选择库名",
                    "options": [
                      {
                        "label": "Gi",
                        "value": "Gi"
                      },
                      {
                        "label": "Mi",
                        "value": "Mi"
                      },
                      {
                        "label": "Ki",
                        "value": "Ki"
                      }
                    ]
                  },
                  {
                    "type": "input-text",
                    "label": "${tableType}表",
                    "name": "tableName",
                    "placeholder": "请输入表名",
                    "required": true,
                    "className": "m-r-none p-r-none"
                  }
                ]
              },
              {
                "type": "combo",
                "id": "fields",
                "name": "fields",
                "label": "字段",
                "minLength": 1,
                "messages": {
                  "minLengthValidateFailed": "最少添加一个字段"
                },
                "draggable": true,
                "multiple": true,
                "items": [
                  {
                    "type": "input-text",
                    "placeholder": "请输入字段名称",
                    "required": true,
                    "name": "fieldName",
                    "unique": true,
                    "size": "sm",
                    "mode": "inline",
                    "className": "m-r-none p-r-none"
                  },
                  {
                    "type": "checkbox",
                    "option": "分区键",
                    "name": "partitionKey",
                    "value":false,
                    "mode": "inline",
                    "className": "m-r-none m-l-none"
                  },
                  {
                    "icon": "fa fa-cog",
                    "type": "button",
                    "actionType": "dialog",
                    "mode": "inline",
                    "dialog": {
                      "title": "其他配置项",
                      "closeOnEsc": true,
                      "closeOnOutside": true,
                      "data": {
                        "comboIndex": "${index}",
                        "defaultValue": "${defaultValue}",
                        "hiddenPartitionLogic": "${hiddenPartitionLogic}"
                      },
                      "actions": [
                        {
                          "type": "button",
                          "label": "确定",
                          "onEvent": {
                            "click": {
                              "actions": [
                                {
                                  "componentId": "fields",
                                  "actionType": "setValue",
                                  "args": {
                                    "index": "${comboIndex}",
                                    "value": "${&}"
                                  }
                                }
                              ]
                            }
                          }
                        },
                        {
                          "type": "button",
                          "actionType": "close",
                          "label": "取消"
                        }
                      ],
                      "body": [
                        {
                          "type": "form",
                          "body": [
                            {
                              "label": "默认值",
                              "name": "defaultValue",
                              "type": "input-text"
                            },
                            {
                              "label": "隐藏分区处理逻辑",
                              "name": "hiddenPartitionLogic",
                              "type": "input-text"
                            },
                           {
                              "label": "测试",
                              "name": "test",
                              "type": "input-text"
                            }
                          ]
                        }
                      ]
                    }
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
}
```
4. 操作步骤
1）点击新增
2）点击新增字段
3）点击设置按钮
4）输入值点击确定

**Comment by ericzhao007** [comment]
我也遇到了，我在进行编辑后迅速点击提交就会出现字段空的情况，怀疑是双向绑定的问题，感觉有点像是脏检查，定时器获取数据，而不是oninput提取数据

**Comment by hsm-lv** [comment]
> #### 描述问题：
> 我在combo中嵌套了一个，dialog类型的表单弹窗，表单提交后给combo中setValue，这个操作经常会出现丢失一部分值，大概10次会有3,4次。用的是sdk版本，2.0.2
> 
> #### 截图或视频：
> ![image](https://user-images.githubusercontent.com/102523291/180446110-c8de2792-8fe6-457a-b3f0-dade81b0e0df.png)
> 
> #### 如何复现（这是完整json配置）：
> ```
> {
>   "type": "page",
>   "body": {
>     "title": "创建表",
>     "debug": true,
>     "type": "form",
>     "actions": [
>       {
>         "label": "提交",
>         "actionType": "confirm",
>         "type": "button",
>         "level": "primary"
>       },
>       {
>         "type": "button",
>         "label": "生成sql",
>         "level": "light",
>         "actionType": "ajax",
>         "api": "",
>         "feedback": {
>           "title": "操作成功",
>           "body": "xxx 已操作成功"
>         }
>       }
>     ],
>     "body": [
>       {
>         "type": "combo",
>         "name": "tables",
>         "value": [
>         ],
>         "minLength": 1,
>         "messages": {
>           "minLengthValidateFailed": "最少添加一张表"
>         },
>         "multiLine": true,
>         "multiple": true,
>         "typeSwitchable": false,
>         "conditions": [
>           {
>             "label": "iceberg ",
>             "test": "this.tableType === \"iceberg\"",
>             "scaffold": {
>               "tableType": "iceberg"
>             },
>             "items": [
>               {
>                 "type": "input-group",
>                 "name": "fullyName",
>                 "label": "${tableType}表",
>                 "body": [
>                   {
>                     "type": "select",
>                     "size": "sm",
>                     "required": true,
>                     "name": "databaseName",
>                     "placeholder": "请选择库名",
>                     "options": [
>                       {
>                         "label": "Gi",
>                         "value": "Gi"
>                       },
>                       {
>                         "label": "Mi",
>                         "value": "Mi"
>                       },
>                       {
>                         "label": "Ki",
>                         "value": "Ki"
>                       }
>                     ]
>                   },
>                   {
>                     "type": "input-text",
>                     "label": "${tableType}表",
>                     "name": "tableName",
>                     "placeholder": "请输入表名",
>                     "required": true,
>                     "className": "m-r-none p-r-none"
>                   }
>                 ]
>               },
>               {
>                 "type": "combo",
>                 "id": "fields",
>                 "name": "fields",
>                 "label": "字段",
>                 "minLength": 1,
>                 "messages": {
>                   "minLengthValidateFailed": "最少添加一个字段"
>                 },
>                 "draggable": true,
>                 "multiple": true,
>                 "items": [
>                   {
>                     "type": "input-text",
>                     "placeholder": "请输入字段名称",
>                     "required": true,
>                     "name": "fieldName",
>                     "unique": true,
>                     "size": "sm",
>                     "mode": "inline",
>                     "className": "m-r-none p-r-none"
>                   },
>                   {
>                     "type": "checkbox",
>                     "option": "分区键",
>                     "name": "partitionKey",
>                     "value":false,
>                     "mode": "inline",
>                     "className": "m-r-none m-l-none"
>                   },
>                   {
>                     "icon": "fa fa-cog",
>                     "type": "button",
>                     "actionType": "dialog",
>                     "mode": "inline",
>                     "dialog": {
>                       "title": "其他配置项",
>                       "closeOnEsc": true,
>                       "closeOnOutside": true,
>                       "data": {
>                         "comboIndex": "${index}",
>                         "defaultValue": "${defaultValue}",
>                         "hiddenPartitionLogic": "${hiddenPartitionLogic}"
>                       },
>                       "actions": [
>                         {
>                           "type": "button",
>                           "label": "确定",
>                           "onEvent": {
>                             "click": {
>                               "actions": [
>                                 {
>                                   "componentId": "fields",
>                                   "actionType": "setValue",
>                                   "args": {
>                                     "index": "${comboIndex}",
>                                     "value": "${&}"
>                                   }
>                                 }
>                               ]
>                             }
>                           }
>                         },
>                         {
>                           "type": "button",
>                           "actionType": "close",
>                           "label": "取消"
>                         }
>                       ],
>                       "body": [
>                         {
>                           "type": "form",
>                           "body": [
>                             {
>                               "label": "默认值",
>                               "name": "defaultValue",
>                               "type": "input-text"
>                             },
>                             {
>                               "label": "隐藏分区处理逻辑",
>                               "name": "hiddenPartitionLogic",
>                               "type": "input-text"
>                             },
>                            {
>                               "label": "测试",
>                               "name": "test",
>                               "type": "input-text"
>                             }
>                           ]
>                         }
>                       ]
>                     }
>                   }
>                 ]
>               }
>             ]
>           }
>         ]
>       }
>     ]
>   }
> }
> ```
> 
> 4. 操作步骤
>    1）点击新增
>    2）点击新增字段
>    3）点击设置按钮
>    4）输入值点击确定

示例代码字段名字没对上，不过按照你的这个场景，我没有复现问题

**Comment by hsm-lv** [comment]
> 我也遇到了，我在进行编辑后迅速点击提交就会出现字段空的情况，怀疑是双向绑定的问题，感觉有点像是脏检查，定时器获取数据，而不是oninput提取数据

方便贴一下代码吗
