### ISSUE TITLE
 2.0.2 版本 InputDateRange 日期范围 取消按钮无法使用，官方文档示例也是如此！

### ISSUE THREAD

**Issue by zyimm** [baidu/amis#4960]
#### 描述问题：
 2.0.2 版本

InputDateRange 日期范围 取消按钮无法使用，官方文档示例也是如此！

#### 截图或视频：
![图片](https://user-images.githubusercontent.com/13979159/180626955-2d574f42-6e1d-4d41-bac4-1b2dd85afc10.png)

**Comment by Twelveeee** [comment]
测试出来第二个问题
如果第一次选择好开始时间和结束时间，再点击开始时间之前的日期，无法选择结束时间。
例如：
点击15号，15号成为开始时间
点击18号，18号成为结束时间
点击12号，12号成为开始时间，接下来无论点击任何时间，都无法设置为结束时间，只能点弹窗外取消再重新设置。
在官网文档复现成功。

**Comment by lurunze1226** [comment]
2.1.0版本修复了
