### ISSUE TITLE
无法监听抽屉右上角关闭按钮，并添加刷新事件

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#4967]
#### 描述问题：

有个添加操作，添加完，关闭抽屉希望能刷新列表，但是系统关闭按钮不能添加刷新动作，并且关闭后，蒙版也有个关闭动作，能否两个独立控制

官方文档：是否展示关闭按钮，当值为 false 时，默认开启 closeOnOutside，不知道基于什么考虑，两个属性耦合，不能同时关闭

**Comment by hsm-lv** [comment]
当前可以通过监听cancel来设计右上角关闭时的动作
