### ISSUE TITLE
富文本编辑器上传图片不是走的全局的axios

### ISSUE THREAD

**Issue by ChangYujieCN** [baidu/amis#498]
编辑器要求返回的字段要有link这个字段,富文本编辑器上传图片不是走的全局的axios,无法定制返回的数据,请问有什么好的解决办法吗?

**Comment by foxfire881** [comment]
富文本编辑器可以修改上传接口的，在后端重新写个API返回带link的JsonResponse就好了，我就是这么干的

**Comment by foxfire881** [comment]
富文本编辑器可以修改上传接口的，在后端重新写个API返回带link的JsonResponse就好了，我就是这么干的

**Comment by foxfire881** [comment]
富文本编辑器可以修改上传接口的，在后端重新写个API返回带link的JsonResponse就好了，我就是这么干的

**Comment by ChangYujieCN** [comment]
@foxfire881  主要不想麻烦后端同学  我再看看吧

**Comment by 2betop** [comment]
富文本编辑器是第三方插件，改不了

**Comment by foxfire881** [comment]
富文本编辑器如果支持markdown就好了，editormd开源免费功能强大，比那个半吊子frola的富文本编辑器强太多了。

http://editor.md.ipandao.com/

**Comment by 2betop** [comment]
哈哈，理论上自己可以接入哈

**Comment by 2betop** [comment]
看来你一直对 frolaEditor 耿耿于怀

**Comment by foxfire881** [comment]
> 看来你一直对 frolaEditor 耿耿于怀

的确是耿耿于怀，看到那个红色的大横条版权警告和前端渲染时自动增加的"Powered by Froala Editor"就浑身不自在反胃。

我是想把它替代掉啊~ 可是用的是sdk模式，代码都被混淆了看不懂，自己又不会整React没法搞，Vue的话还能看一下，React完全没法弄，而且没有精力再去折腾了。所以一直期待官方作者可以更新一下啊~~ 有免费的editormd那么好用的东西，干嘛要集成收费没注册的半吊子，而且一个文本编辑器还要收费，有点太恶心了，国内类似的富文本编辑器太多了都是免费的，百度自己的UEditor都比它强了不知道多少倍，不知道为啥要集成那个Froala？从各个方面看都无法理解，哪怕集成个PJ版没有大红条和水印的也好啊…… 现在集成的这个真的是个鸡肋，有种一颗老鼠屎坏了一锅汤的感觉。

**Comment by 2betop** [comment]
我们购买了这个但是只能限制公司域名使用。目前应该不会考虑跟换，至于那个红框框，貌似可以用样式隐藏的。

**Comment by foxfire881** [comment]
求PJ攻略~~ sdk混淆代码了没法搞。
另外不止那个大红条，还有前端页面渲染html时会自动加上“Powered by Froala Editor”链接到这个编辑器的网站上去，太恶心了。

**Comment by foxfire881** [comment]
不考虑更换，那可以考虑新增一个写Markdown的组件吗？把Editormd集成进去，毕竟MD现在比HTML富文本编辑器流行多了。

**Comment by 2betop** [comment]
可以考虑

**Comment by 2betop** [comment]
![image](https://user-images.githubusercontent.com/2698393/77304768-e0c32f80-6d2f-11ea-8f7e-8fed65b1cebe.png)

![image](https://user-images.githubusercontent.com/2698393/77304792-e9b40100-6d2f-11ea-9a5e-4c99f85b54df.png)

大概长这样，后续弄到 amis 里面来。

**Comment by 2betop** [comment]
干掉红框

```css
.fr-wrapper > div:first-child:not(.fr-element) {
    display: none;
}
.fr-wrapper.show-placeholder .fr-placeholder {
    margin-top: 0 !important;
}
```

至于自动补一个内容，这个你后端处理一下吧。

要是不贵的话，建议还是买个 frola :)

**Comment by foxfire881** [comment]
貌似有点简陋了，可以考虑集成editormd吗？editormd的功能按钮比它多很多，除了常规的md，还能编辑数据公式、图表、TOC等等，企鹅和阿里巴巴内部现在用的也是editormd编辑器。

**Comment by foxfire881** [comment]
![1](https://user-images.githubusercontent.com/273961/77305360-da818300-6d30-11ea-95bf-41e27ecd9b98.PNG)

**Comment by foxfire881** [comment]
![1](https://user-images.githubusercontent.com/273961/77305495-0d2b7b80-6d31-11ea-9743-63d4b20c78bb.PNG)

**Comment by foxfire881** [comment]
> 干掉红框
> 
> ```css
> .fr-wrapper > div:first-child:not(.fr-element) {
>     display: none;
> }
> .fr-wrapper.show-placeholder .fr-placeholder {
>     margin-top: 0 !important;
> }
> ```
> 
> 至于自动补一个内容，这个你后端处理一下吧。
> 
> 要是不贵的话，建议还是买个 frola :)

不是后端的问题，我后端根本没处理过，是前端渲染HTML时自动追加了一个“Powered by Froala Editor”的链接

**Comment by 2betop** [comment]
我是说，你后端在读取的时候写段代码干掉
