### ISSUE TITLE
autoGenerateFilter自动生成查询表单，是否能对查询表单的列数做限制？

### ISSUE THREAD

**Issue by echolxltf** [baidu/amis#4980]

**Comment by lurunze1226** [comment]
目前还不支持，预计2.1.1 版本支持吧

**Comment by allenve** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E6%9F%A5%E8%AF%A2%E5%8C%BA%E5%9F%9F
