### ISSUE TITLE
from如何自定义高度

### ISSUE THREAD

**Issue by 4AFm** [baidu/amis#4982]
from编辑如何看自己的身高 尝试过很多办法还是不可以 文档没有找到  

_Originally posted by @4AFm in https://github.com/baidu/amis/discussions/4981_

**Comment by lurunze1226** [comment]
用[自定义样式](https://aisuda.bce.baidu.com/amis/zh-CN/style/sizing/height)`"className": "h-2"` 或者外部包裹一个定高的容器

**Comment by 4AFm** [comment]
不可以自己定义一个数值吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月26日(星期二) 晚上8:11
***@***.***&gt;;
抄送:&nbsp;"-                 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] from如何自定义高度 (Issue #4982)





 
用自定义样式"className": "h-2" 或者外部包裹一个定高的容器
