### ISSUE TITLE
如何设置可以取消自适应

### ISSUE THREAD

**Issue by orangetcy** [baidu/amis#499]
1. 有没有可以设置取消自适应布局，展示页面和PC全窗口一致，自己滑动页面即可。
2. 还有我在iframe中嵌套chart垂直有滑动条，但是水平无滑动条，chart自适应屏幕大小导致折线图比例奇怪，可以设置水平不自适应，出现滑动条吗？

**Comment by 2betop** [comment]
我感觉这你可以自己写 css 覆盖？我的自适应都是 css 弄的。

**Comment by orangetcy** [comment]
好的，谢谢，我以为可以JSON配置的
