### ISSUE TITLE
input-kv 解析数据有误

### ISSUE THREAD

**Issue by theojia** [baidu/amis#4999]
![image](https://user-images.githubusercontent.com/21030082/181247091-dd656562-3b02-49e9-b864-3bd66508210e.png)

如图，form里有input-kv组件，通过两种方式data和value赋初始值时，通过data的方式会存在问题：
input-kv会将 { “aaa.aaa”: 1 } 解析为 { “aaa”: { “aaa”: 1 } } ,擅自改变了用户自定义的key值。

麻烦帮忙确认一下，谢谢~

**Comment by theojia** [comment]
请问这个问题有在2.2.0中解决吗😭 @lurunze1226

**Comment by nwind** [comment]
有个配置项 `"autoParseJSON": false` 可以关了自动解析值
