### ISSUE TITLE
引入之后如何配置主题呢？

### ISSUE THREAD

**Issue by WayYOLO** [baidu/amis#5]
真的非常厉害，在主题和样式方面如何做到灵活配置呢

**Comment by RickCole21** [comment]
目前还不支持配置主题和样式哈，只支持默认提供的两套主题。
之后应该会考虑加这个feature

**Comment by 2betop** [comment]
@RickCole21 说的是还不能可视化配置主题样式，实际上目前是可以通过修改变量值来实现定制。
还不能说非常灵活，后面需要再梳理一次做可视化定制！

**Comment by SnailSword** [comment]
> 实际上目前是可以通过修改变量值来实现定制。

@2betop  请问怎么通过修改变量值来实现定制？

**Comment by 2betop** [comment]
要通过引入 scss 文件来实现，先 import 你自己的变量文件然后 import amis default.scss 或者 cxd.scss, 掌握 sass 基本用法就知道怎么定制了。
