### ISSUE TITLE
表单提交，显示【表单验证失败，请仔细检查】

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#500]
![11](https://user-images.githubusercontent.com/57850028/77045520-4f388280-69fc-11ea-99e4-a318c0eb1711.png)
![22](https://user-images.githubusercontent.com/57850028/77045523-51024600-69fc-11ea-8ce9-e656678fb725.png)

两个select下拉框，initApi 未指定其值，通过`source`拉取后，选择某项，提交，显示【表单验证失败，请仔细检查】，不知道什么原因？请指教！

**Comment by 2betop** [comment]
这提供的信息有点少

**Comment by icodingx** [comment]
```
{ "type": "text", "name": "fname", "placeholder": "名称" }, 
{"type": "select", "name": "dsidx", "source":"/biz/ds/#pid/list"},{"type": "select", "name": "pointx", "visibleOn":"dsidx", "autoFill":{"colmeta":"${colmeta}"},"source": {"url":"/biz/ds/#pid/#id/points/${dsidx}","sendOn":"dsidx"}
```
不选这两项，就可以提交表单，选择这两项就提示错误

**Comment by icodingx** [comment]
![33](https://user-images.githubusercontent.com/57850028/77046099-51e7a780-69fd-11ea-8f56-012f160b4f3e.png)

**Comment by 2betop** [comment]
看着没啥问题，source 的格式呢？

**Comment by icodingx** [comment]
```
{"msg":"操作成功","code":0,"data":{"options":[{"colmeta":"id,name,title,type,desc","label":"列表","value":"list"}]},"status":0}
```

**Comment by icodingx** [comment]
我该怎么办 呢？

**Comment by 2betop** [comment]
等会，我尝试本地模拟一下，看能否复现

**Comment by icodingx** [comment]
拜谢 ！

**Comment by RickCole21** [comment]
![image](https://user-images.githubusercontent.com/19327810/77049700-83637180-6a03-11ea-89d1-1ffecbc8f4a4.png)
你`formula`设置给这个的值不是个合法的`url`类型的值，要不改成`text`？

**Comment by RickCole21** [comment]
或者你调整这个url的值，问题就是这里，自己看着调整吧

**Comment by icodingx** [comment]
https://baidu.github.io/amis/docs/renderers/Form/Url
不是有 `type=url` 吗 ？

**Comment by icodingx** [comment]
可以了，就是这个问题，感谢 :-)
