### ISSUE TITLE
富文本类型 在版本2.0.2 无法渲染

### ISSUE THREAD

**Issue by zyimm** [baidu/amis#5001]
```
{
                type: "input-rich-text",
                name: "html",
                label: "Rich Text",
                value: "<p>Just do <code>IT</code>!</p>"
            },
```

**Comment by yuhonyon** [comment]
+1

**Comment by xinfox-ltd** [comment]
+1，我也出现这个问题，不知道是不是姿势不对，7天前发帖都没人回

**Comment by dongyao8** [comment]
+1 一样的问题，对照官方文档，代码应该没错，切回1.X版本就正常

**Comment by lurunze1226** [comment]
```
import 'amis/sdk/tinymce';
import 'amis/sdk/rest';
```

把富文本编辑需要的资源引入，2.0.0版本分包之后把富文本编辑器的资源拆开了

**Comment by dongyao8** [comment]
@lurunze1226 如果是SDK的js方式接入，如何操作？

**Comment by lurunze1226** [comment]
> @lurunze1226 如果是SDK的js方式接入，如何操作？

sdk的tar包里也有对应的文件，在项目入口处加载即可

**Comment by echome123** [comment]
@lurunze1226 我也遇到了，sdk.js接入之后，查看控制台，你说的那几个js文件都已经加载了，依然是个空白，没有渲染，大神可以给一个sdk的富文本接入demo吗

**Comment by lurunze1226** [comment]
> @lurunze1226 我也遇到了，sdk.js接入之后，查看控制台，你说的那几个js文件都已经加载了，依然是个空白，没有渲染，大神可以给一个sdk的富文本接入demo吗

要保证执行`amis.embed()`之前加载资源

**Comment by echome123** [comment]
@lurunze1226 您发的这个demo好像不是sdk.js的，sdk的引入都使用<script>标签引入的，您给的演示demo使用import引入在sdk.js不能生效好像（后端开发对这个不同的引入方式不是很懂，还望见谅）

**Comment by lurunze1226** [comment]
> @lurunze1226 您发的这个demo好像不是sdk.js的，sdk的引入都使用<script>标签引入的，您给的演示demo使用import引入在sdk.js不能生效好像（后端开发对这个不同的引入方式不是很懂，还望见谅）

本质上是一样的，`import 'amis/sdk/tinymce'` 换成script的写法就是 <script src="<sdk-path>/tinymce.js"> , 把sdk.tar.gz里提供的资源加载到就可以了

**Comment by echome123** [comment]
@lurunze1226 已经尝试过这种引入方式了，依然不起作用

**Comment by echome123** [comment]
@lurunze1226  

![a6d94a7068af6e666713537f3acfab1](https://user-images.githubusercontent.com/103982793/182339886-2a5ccdcd-03d3-4995-9767-dcfbe815afdf.png)

**Comment by qianxiaofendou** [comment]
> @lurunze1226
> 
> ![a6d94a7068af6e666713537f3acfab1](https://user-images.githubusercontent.com/103982793/182339886-2a5ccdcd-03d3-4995-9767-dcfbe815afdf.png)

sdk下面有个皮肤样式需要加载一下 `thirds/tinymce/skins/ui/oxide/skin.css`

**Comment by echome123** [comment]
@lurunze1226 你好，按照你的上一步指引，已经加入了这个css资源，依然无法渲染出来：
![a595645bbdf6f74905277713ce5ac70](https://user-images.githubusercontent.com/103982793/182870948-2d39cd56-c645-4006-a91b-113fde379ec8.jpg)

**Comment by qianxiaofendou** [comment]
我这边使用sdk2.1.0加载这个皮肤样式，`rest.js`和`tinymce.js`这两个js不用添加，富文本是可以正常显示出来的

**Comment by belongwqz** [comment]
sdk2.2.0也没解决，收工加载了js和样式表之后，显示没问题，编辑器的菜单还是不可用，比如插入表格之类的，点击了没反应

**Comment by nwind** [comment]
最新版已经不能复现了
