### ISSUE TITLE
新版本编辑器5.2.0，发送请求，没有配置提示窗口内容，没有旧版本方便

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#5004]
旧版本发起请求，url 下面有个填写反馈内容文字，发起请求前先调起弹窗，在请求
新版本，必须先配置个弹窗，然后在弹窗事件里发送请求。操作没有旧版本方便。

**Comment by qianxiaofendou** [comment]
我也发现了 新版的配置需要弹窗 很影响使用，另外之前的显隐功能新版编辑器适配的有点问题；还有select的api和options那一块儿简直要哭晕了 @lurunze1226
