### ISSUE TITLE
amis2.0.1 crud 批量操作 事件里面无法获取 ids, 只能获取 selectedItems

### ISSUE THREAD

**Issue by crizydevl** [baidu/amis#5006]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lurunze1226** [comment]
其实可以通过`selectedItems` + 表达式取到ids，`'${JOIN(ARRAYMAP(event.data.selectedItems, item => item.id), ",")}'`

**Comment by crizydevl** [comment]
只是说以前的代码取的ids，要改为selectedItems 很繁琐

**Comment by jiasws** [comment]
最新版2.2.0仍存在这个问题，批量操作配置Action，在Action里面跳转Url时，agrs参数里可以正常获得selectedItems对象，但ids为空。

**Comment by hsm-lv** [comment]
新版修复了
