### ISSUE TITLE
新版编辑器 curd组件 编辑不刷新  必现bug

### ISSUE THREAD

**Issue by yuhonyon** [baidu/amis#5007]
#### 描述问题：

mock数据下 编辑会刷新
![image](https://user-images.githubusercontent.com/9654460/181461526-e90ff51b-1f27-4181-bc4b-04b7c3906eeb.png)

接口数据下 编辑不刷新
![image](https://user-images.githubusercontent.com/9654460/181461579-b5efe005-7b91-465b-b7aa-144ed8cca6da.png)

**Comment by lengqingfeng** [comment]
确实经常遇到不同步问题

**Comment by hsm-lv** [comment]
尝试下新版本
