### ISSUE TITLE
编辑器有一些组件操作栏直接报错？

### ISSUE THREAD

**Issue by duqingyu** [baidu/amis#5009]
#### 描述问题：

编辑器有一些组件操作栏直接报错

#### 截图或视频：

![image](https://user-images.githubusercontent.com/30541930/181497588-e74948e6-aa3c-4421-a08e-b3bdfa09bd8e.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
使用npm安装
"amis": "^2.0.2",
"amis-editor": "^4.2.0-beta.3",
webpack版本5

4. 操作步骤
部分组件选中某一层级就直接报错

**Comment by duqingyu** [comment]
安装到最新版本5.x的amis-editor也是一样会有这个问题

**Comment by hsm-lv** [comment]
辛苦发下报错组件的schema配置

**Comment by duqingyu** [comment]
> 辛苦发下报错组件的schema配置

没有配置什么，就直接拖入了form表单组件，然后选中form组件的某一部分就会出现。已解决了哈，目测是与react版本不兼容，降到16.x就可以了，有问题的是17.x
