### ISSUE TITLE
自定义组件如何实现自身的数据域？

### ISSUE THREAD

**Issue by wtlsky** [baidu/amis#5017]
#### 实现场景：
我想要实现一个自定义组件，这个组件通过接口或者其他一些内部逻辑产生一些数据，希望这些数据可以被子组件通过数据域所识别，方便在子组件里通过模板的形式使用。

#### 存在的问题：
请问如何实现这样一个拥有自己的数据域的自定义组件 

#### 当前方案：
无

```
code here...
```

**Comment by wibetter** [comment]
目前看，只能通过注册成表单类自定义组件（registerFormItem）才会形成自定义组件的数据域。你可以先说一下你的具体诉求，可能还有其他方式可以满足你的诉求。

**Comment by wtlsky** [comment]
> 



> 目前看，只能通过注册成表单类自定义组件（registerFormItem）才会形成自定义组件的数据域。你可以先说一下你的具体诉求，可能还有其他方式可以满足你的诉求。

就是想做一个可以容纳子组件的自定义组件，这个自定义组件不是表单，但是想要在子组件内访问到这个自定义组件的数据。您所的这个`registerFormItem`方案有示例吗？

我用的是`amis-editor`想在`amis-editor`里做这个自定义组件

**Comment by wibetter** [comment]
@wtlsky 这里有一个react版的容器自定义组件模板，可以看下实现方式：https://github.com/aisuda/container-custom-widget-template
