### ISSUE TITLE
怎么生成sdk.js  1.8.0

### ISSUE THREAD

**Issue by 603550104** [baidu/amis#5021]
#### 实现场景：
1.8.0版本有个功能需要用到 getComponentByName  

#### 存在的问题：
getComponentByName  在1.8.0版本这个方法找不到，升级amis又会有组件更新影响到现有功能，暂时不能升级
1：有没有在不升级情况下更新bug
2：目前想法是根据你们修复的bug将git代码更新，生成新的sdk.js，怎么git代码生成sdk.js

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
 let amis = amisRequire('amis/embed');
        let amisScoped = amis.embed('#root', {
            "type": "page",
            "name": "page1",
            "title": "表单页面",
            "body": {
                "type": "form",
                "name": "form1",
                "body": [
                    {
                        "label": "Name",
                        "type": "input-text",
                        "name": "name1"
                    }
                ]
            }
        });
        console.log(amisScoped.getComponentByName('page1.form1').getValues());
```

**Comment by lurunze1226** [comment]
执行根目录的`build.sh` 构建sdk

**Comment by 603550104** [comment]
![image](https://user-images.githubusercontent.com/26154427/182090251-ea3065d5-6349-4a24-a105-8cdcd31eddf1.png)
![image](https://user-images.githubusercontent.com/26154427/182090340-e26bfbf0-c920-47a6-b154-35c4f12155d5.png)
根据更新记录我修改了embed.tsx 依然找不到
