### ISSUE TITLE
1.8.0 Scoped问题

### ISSUE THREAD

**Issue by 603550104** [baidu/amis#5030]
#### 描述问题：

根据文档以及bug修复记录更新了embed.tsx，重新生成sdk.js
依然获取不到getComponentByName

#### 截图或视频：

![image](https://user-images.githubusercontent.com/26154427/182095139-0f08e7ae-4296-4650-b1eb-e2497a416e62.png)

#### 如何复现（请务必完整填写下面内容）：
![image](https://user-images.githubusercontent.com/26154427/182095255-f9190e25-0169-45bb-8aac-408d00270d36.png)

4. 操作步骤
根据文档以及bug修复记录更新了embed.tsx，重新生成sdk.js
依然获取不到getComponentByName

**Comment by hsm-lv** [comment]
尝试下新版

**Comment by almas1992** [comment]
v3.3.0 版本SDK还是会报 `TypeError: amisScoped.getComponentByName is not a function. (In 'amisScoped.getComponentByName('page1.form1')', 'amisScoped.getComponentByName' is undefined)`
