### ISSUE TITLE
在table或者crud外，获取 crul内勾选的selectedItems数据

### ISSUE THREAD

**Issue by wangk2014** [baidu/amis#5041]
#### 实现场景：
点击按钮时，需要获取两个表格中勾选的数据。

#### 存在的问题：
crud中的selectedItems在crud外不知如何获取。
目前测试能在headerToolbar->bulkActions，但是外部组件无法获取。

#### 当前方案：
自定义一个数组，在表格中增加checkbox，选中时修改数组的元素。
但是这样在每次操作后都需要同时维护数组数据的准确性，不太合适。

是否可以在外部获取到crud的selectedItems ，或者有方法遍历crud，获取勾选中的数据。

```

```

**Comment by lurunze1226** [comment]
监听`selectedChange`[事件](https://aisuda.bce.baidu.com/amis/examples/event/table)，通过`${event.data.selectedItems}`获取信息

**Comment by wangk2014** [comment]
amis文档里没有搜到selectedChange相关示例，可否帮忙提供示例代码？

**Comment by wangk2014** [comment]
@lurunze1226 在crud里加了onEvent，确实可以监听了，谢啦！
如果外部获取的话，是否还需要把这个值set到某个控件上作为载体？

`"onEvent": {
    "selectedChange": {
        "actions": [
            {
                "actionType": "custom",
                "script": (context, actionFun,event) => {
                    let selectedIds = [];
                    event.data.selectedItems.forEach(function (element, index, array)  {
                        selectedIds.push(element.id);
                    });
                }
            }
        ]
    }
`

**Comment by wangk2014** [comment]
目前我这么临时做了下兼容，但如果不能搞明白为什么 “取消勾选”和“勾选”时为何element数据不同，还是有隐患的，辛苦开发组的同学帮忙看一下。
`
if(element.Id != '' && typeof(element.Id) != "undefined") 
{
    selectedIds.push(element.Id);
} else if( typeof(element.data) != "undefined"){
    selectedIds.push(element.data.Id);
}
`

**Comment by wangk2014** [comment]
目前我这么临时做了下兼容，但如果不能搞明白为什么 “取消勾选”和“勾选”时为何element数据不同，还是有隐患的，辛苦开发组的同学帮忙看一下。
`
if(element.Id != '' && typeof(element.Id) != "undefined") 
{
    selectedIds.push(element.Id);
} else if( typeof(element.data) != "undefined"){
    selectedIds.push(element.data.Id);
}
`

**Comment by fan0920** [comment]
试试${GETRENDERERDATA(\"componentId\", \"selectedItems\")}

**Comment by fan0920** [comment]
试试```${GETRENDERERDATA("componentId", "selectedItems")}```
