### ISSUE TITLE
amis-editor最新版本自定义组件——类型错误，无法渲染！

### ISSUE THREAD

**Issue by ccj-007** [baidu/amis#5042]
```js
import { BasePlugin } from 'amis-editor';

export class MyRendererPlugin extends BasePlugin {
  rendererName = 'my-chen';

  // 暂时只支持这个，配置后会开启代码编辑器
  $schema = '/schemas/UnkownSchema.json';

  // 用来配置名称和描述
  name = '我的自定义渲染器';
  description = '这只是个示例';

  // tag，决定会在哪个 tab 下面显示的
  tags = ['我的自定义组件', '表单项'];

  // 图标
  icon = 'fa fa-user';

  // 用来生成预览图的
  previewSchema = {
    type: 'my-renderer',
    target: 'demo'
  };

  // 拖入组件里面时的初始数据
  scaffold = {
    type: 'my-renderer',
    target: '233'
  };

  // 右侧面板相关
  panelTitle = '自定义组件';
  panelControls = [
    {
      type: 'tabs',
      tabsMode: 'line',
      className: 'm-t-n-xs',
      contentClassName: 'no-border p-l-none p-r-none',
      tabs: [
        {
          title: '常规',
          controls: [
            {
              name: 'target',
              label: 'Target',
              type: 'text'
            }
          ]
        },

        {
          title: '外观',
          controls: []
        }
      ]
    }
  ];
}
```

```js
import { MyRendererPlugin } from "./MyRendererPlugin";
import { registerEditorPlugin } from 'amis-editor';

registerEditorPlugin(MyRendererPlugin);
```

Editor组件渲染后显示类型错误，无法渲染，自定义组件失败！

```js
//版本信息
 "amis": "^2.1.0",
"amis-editor": "^5.1.9-beta.0",
"axios": "^0.27.2",
"react": "^16.8.6",
"react-dom": "^16.8.6",

``` 
![Snipaste_2022-08-02_01-44-42](https://user-images.githubusercontent.com/79068732/182210377-59f28009-5e19-4b56-b9db-f33ad960df75.png)
![Snipaste_2022-08-02_01-45-04](https://user-images.githubusercontent.com/79068732/182210401-da6a48c5-1cd1-4861-93f9-6f5f71fcc4fc.png)

**Comment by wtlsky** [comment]
![image](https://user-images.githubusercontent.com/15212547/182280642-ef1ea1e1-31f1-46c4-9cbe-5f7abafe5a30.png)
这几个名字需要一致，另外注册renderer时的type也要一致
![image](https://user-images.githubusercontent.com/15212547/182280759-48f18588-ca6f-4649-ab41-c6711f066f3c.png)

**Comment by ccj-007** [comment]
命名一致也无效， 新版本无需此renderer注册方法吧？

**Comment by ccj-007** [comment]
使用create-react-app的脚手架创建，导入amis-editor，webpack@5.6打包， 存在类型报错问题

**Comment by ccj-007** [comment]
@wtlsky  可以用了， webpack配置确定是需要  conditionNames: ['require', 'node']  ？

**Comment by ccj-007** [comment]
在webpack配置中定义库的入口
 resolve： {
    conditionNames: ['require', 'node']
}

**Comment by wtlsky** [comment]
> conditionNames

https://github.com/baidu/amis/issues/4877#issuecomment-1191487194

**Comment by wibetter** [comment]
@ccj-007 rendererName 和 scaffold.type 要保持一致
