### ISSUE TITLE
2.0.2，2.1.0 版本富文本编辑器无法显示

### ISSUE THREAD

**Issue by zyimm** [baidu/amis#5043]
之前issues 已经有人提问，给出解决方案是引入两个文件 但是貌似没有效果？

```
import './src/sdk/sdk.css'
import './src/sdk/helper.css'
import './src/sdk/iconfont.css'
import './src/assets/style.css'
import './src/sdk/sdk.js'
import '@/sdk/rest'
import '@/sdk/tinymce'
import app from './src/config/app.js'

```

**Comment by lurunze1226** [comment]
确保你的资源加载到了吗？`rest.js` , `tinymce.js` 和 `sdk.js`在同级目录下的

**Comment by zyimm** [comment]
> 
f12 已经看到对应js 加载了

**Comment by lurunze1226** [comment]
那应该是能正常渲染的，发个截图看看有啥报错信息

**Comment by dongyao8** [comment]
@lurunze1226  #5001  破案了，最终发现问题不是你说的rest.js , tinymce.js 和 sdk.js，而是缺少这个样式文件：thirds/tinymce/skins/ui/oxide/skin.css

**Comment by qiaokou** [comment]
上传本地图片还是有问题：Error: Errors: Failed path: (data > src) Could not find valid *required* value for "value" in { "meta": {} } Input object: { "src": { "meta": {} }, "alt": "", "dimensions": { "width": "", "height": "" }, "fileinput": [ {} ]
