### ISSUE TITLE
自定义change事件怎么通过event获取当前组件

### ISSUE THREAD

**Issue by smile1102** [baidu/amis#5049]
#### 描述问题：

自定义change事件，怎么通过event参数来获取当前组件

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
                    "type": "input-number",
                    "label": "测试时间：",
                    "name": "hour",
                    "suffix": "h",
                    "value": 0,
                    "max": "24",
                    "min": "0",
                    "precision": 1,
                    "required": true,
                    "mode": "inline",
                    "size": "xs",
                    "onEvent": {
                      "change": {
                        "actions": [
                          {
                            "actionType": "custom",
                            "script": "window.checkProgress(event)"
                          }
                        ]
                      }
                    }
                  },
```

5. 操作步骤
怎么根据event参数来获取change事件的组件

**Comment by hsm-lv** [comment]
> #### 描述问题：
> 自定义change事件，怎么通过event参数来获取当前组件
> 
> #### 截图或视频：
> #### 如何复现（请务必完整填写下面内容）：
> 1. 你是如何使用 amis 的？
>    `sdk`
> 2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
>    2.0
> 3. 粘贴有问题的完整 `amis schema` 代码：
> 
> ```
> {
>                     "type": "input-number",
>                     "label": "测试时间：",
>                     "name": "hour",
>                     "suffix": "h",
>                     "value": 0,
>                     "max": "24",
>                     "min": "0",
>                     "precision": 1,
>                     "required": true,
>                     "mode": "inline",
>                     "size": "xs",
>                     "onEvent": {
>                       "change": {
>                         "actions": [
>                           {
>                             "actionType": "custom",
>                             "script": "window.checkProgress(event)"
>                           }
>                         ]
>                       }
>                     }
>                   },
> ```
> 
> 5. 操作步骤
>    怎么根据event参数来获取change事件的组件

在custom中，可以访问doAction、context、event：
1.动作执行函数doAction，可以执行所有类型的动作
2.通过上下文对象context可以获取当前组件实例，例如context.props可以获取该组件相关属性
3.事件对象event，在doAction之后执行event.stopPropagation = true;可以阻止后续动作执行
