### ISSUE TITLE
文档里的快速编辑示例不起作用了

### ISSUE THREAD

**Issue by dotty-gua** [baidu/amis#5057]
https://baidu.github.io/amis/zh-CN/components/crud#%E5%BF%AB%E9%80%9F%E7%BC%96%E8%BE%91

猜是因为版本问题？

**Comment by lurunze1226** [comment]
换个站点试试吧 https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E5%BF%AB%E9%80%9F%E7%BC%96%E8%BE%91
