### ISSUE TITLE
编辑器amis-editor切换移动端不能响应式吗？

### ISSUE THREAD

**Issue by duqingyu** [baidu/amis#5058]
#### 描述问题：

编辑器amis-editor切换移动端不能响应式吗？设置了isMobile:true

#### 截图或视频：

![image](https://user-images.githubusercontent.com/30541930/182593157-e0a42d53-91d4-4973-8020-60abdb071cc7.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
"amis": "^2.0.2",
"amis-editor": "^5.1.9",

**Comment by wtlsky** [comment]
> #### 描述问题：
> 编辑器amis-editor切换移动端不能响应式吗？设置了isMobile:true
> 
> #### 截图或视频：
> ![image](https://user-images.githubusercontent.com/30541930/182593157-e0a42d53-91d4-4973-8020-60abdb071cc7.png)
> 
> #### 如何复现（请务必完整填写下面内容）：
> 1. 你是如何使用 amis 的？
>    "amis": "^2.0.2",
>    "amis-editor": "^5.1.9",

大佬，你截图里的自定义组件那个tab怎么弄出来的？

**Comment by duqingyu** [comment]
> > #### 描述问题：
> > 编辑器amis-editor切换移动端不能响应式吗？设置了isMobile:true
> > #### 截图或视频：
> > ![image](https://user-images.githubusercontent.com/30541930/182593157-e0a42d53-91d4-4973-8020-60abdb071cc7.png)
> > #### 如何复现（请务必完整填写下面内容）：
> > 
> > 1. 你是如何使用 amis 的？
> >    "amis": "^2.0.2",
> >    "amis-editor": "^5.1.9",
> 
> 大佬，你截图里的自定义组件那个tab怎么弄出来的？

编辑器自己样式，只要有一个编辑器的自定义组件

**Comment by wibetter** [comment]
@duqingyu 请升级amis-editor到最新版，目前没有这个问题：
<img width="1565" alt="image" src="https://github.com/baidu/amis/assets/11958920/e4e01929-09fd-48ac-baed-0a62e311ebb1">
