### ISSUE TITLE
iframe组件后，关闭 iframe窗口 events 事件会监听不会移除，导致反复打开多次iframe events 事件会执行N次

### ISSUE THREAD

**Issue by zyimm** [baidu/amis#5061]
#### 描述问题：

iframe组件后，关闭 iframe窗口 events 事件会监听不会移除，导致反复打开多次iframe events 事件会执行N次

正常理论关闭 iframe窗口 对应监听应该关闭

**Comment by RickCole21** [comment]
发一下复现的schema吧，而且关闭和打开iframe具体是指什么操作？
