### ISSUE TITLE
inout-group内部text组件无法实时验证格式等只能在提交的时候验证

### ISSUE THREAD

**Issue by storv** [baidu/amis#507]
`{
    "$schema": "https://houtai.baidu.com/v2/schemas/page.json#",
    "type": "page",
    "title": "Hello world",
    "body": [
        {
            "type": "tpl",
            "tpl": "初始页面"
        },
        {
            "type": "form",
            "title": "表单",
            "controls": [
                {
                    "label": "文本框",
                    "type": "text",
                    "name": "text",
                    "validations": {
                        "isEmail": true
                    },
                    "validationErrors": {
                        "isEmail": "Email 格式不正确"
                    },
                    "validateOnChange": true
                },
                {
                    "type": "input-group",
                    "size": "sm",
                    "name": "input-group",
                    "inline": true,
                    "label": "input 组合",
                    "controls": [
                        {
                            "type": "text",
                            "placeholder": "搜索作业ID/名称",
                            "inputClassName": "b-r-none p-r-none",
                            "name": "input-group-text",
                            "validations": {
                                "isEmail": true
                            },
                            "validationErrors": {
                                "isEmail": "Email 格式不正确"
                            },
                            "validateOnChange": true
                        },
                        {
                            "type": "submit",
                            "label": "提交",
                            "level": "primary"
                        }
                    ],
                    "validateOnChange": true,
                    "required": false
                }
            ]
        }
    ]
}`

**Comment by 2betop** [comment]
估计你得给 input-group  随便加个 name 属性
