### ISSUE TITLE
2.1.0 steps无法通过服务容器，动态获取状态

### ISSUE THREAD

**Issue by luanwulin** [baidu/amis#5070]
#### 描述问题：

2.1.0 steps无法通过服务容器，动态获取状态

#### 截图或视频：

![image](https://user-images.githubusercontent.com/16553854/183005592-efdf81ed-34db-4681-acd2-587c5bf89b55.png)

#### 如何复现（请务必完整填写下面内容）：

在amis的editor官方demo上面

在页面上拖了个文字和steps，然后整个页面用服务容器包裹来设置status。

可以看到文字是动态改变了的，但是steps该步骤的状态没有动态修改

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "title": "按钮",
  "body": [
    {
      "type": "tpl",
      "tpl": "${radios}",
      "inline": true,
      "wrapperComponent": "",
      "id": "u:f06834894d9a"
    },
    {
      "type": "service",
      "body": [
        {
          "type": "steps",
          "value": 1,
          "steps": [
            {
              "title": "第一步",
              "subTitle": "副标题",
              "description": "描述"
            },
            {
              "title": "第二步"
            },
            {
              "title": "第三步"
            }
          ],
          "id": "u:27e77efd2850",
          "status": "${status}",
          "source": ""
        },
        {
          "type": "tpl",
          "tpl": "${status}",
          "inline": true,
          "wrapperComponent": "",
          "id": "u:9efe39bf29f9"
        }
      ],
      "id": "u:5e85416ea467",
      "dataProvider": "setData({\n  status: 'error'\n})",
      "messages": {
      }
    },
    {
      "type": "container",
      "body": [
      ],
      "id": "u:7c395c4cf05c"
    }
  ],
  "id": "u:7a9ac1a0d573"
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by RickCole21** [comment]
![image](https://user-images.githubusercontent.com/19327810/184115722-0d10d865-669e-4712-bb10-4e1b0fa94258.png)
我这里看好像是正常的，你再试下

**Comment by luanwulin** [comment]
@RickCole21 Ri 不好意思才看到，我刚才在官网的编辑器demo里面，用上面那段json试了试，还是不行呢

**Comment by luanwulin** [comment]
@RickCole21 Ri 并且我看文档这里，这一块都是空的了
![image](https://user-images.githubusercontent.com/16553854/185053408-fc2b46fd-e999-4b58-bd49-9c617e21e558.png)

https://aisuda.bce.baidu.com/amis/zh-CN/components/steps
