### ISSUE TITLE
条件组合 样式异常

### ISSUE THREAD

**Issue by baozhoutao** [baidu/amis#5073]
![image](https://user-images.githubusercontent.com/6194462/183029213-e477fb04-a465-4e0e-a4e4-79869fb1c9e1.png)

**Comment by 1436722103** [comment]
未复现，请补充一下组件使用的方式的描述等……

**Comment by baozhoutao** [comment]
访问这个就能看到, 添加条件和添加组合文本连在一起了.  https://aisuda.bce.baidu.com/amis/zh-CN/components/form/condition-builder

**Comment by baozhoutao** [comment]
@1436722103

**Comment by qkiroc** [comment]
![image](https://github.com/baidu/amis/assets/30946345/9f626b15-45cb-4e65-8fc6-f0afb243dd36)
新版已无问题
