### ISSUE TITLE
vue2 + vuera + amis 1.9.0 toast弹框相关

### ISSUE THREAD

**Issue by songling0** [baidu/amis#5088]
#### 实现场景：
vue2 + vuera + amis 1.9.0
1. toast轻提示可以正常使用
2. crud的增删改，操作成功后，可以正常提示

#### 存在的问题：
1. toast轻提示按钮点击无反应，使用普通按钮监听单击事件一样无弹框弹出，
2. 发送请求，异常后让走toast.error('msg')，跟踪js，可以正常进入，但走到show的时候，toastRef为null，导致函数直接return退出，无弹框显示，不知道这个ToastComponent该怎么处理，才能适配我使用的方式

#### 当前方案：
像这样引入ToastComponent后，又会报 cx is not function...  (cx是props.classnames)
![image](https://user-images.githubusercontent.com/110800138/183369425-ce58d2e1-c991-4c83-a9a3-3c05f11bcea3.png)

后面我又配置了classnames属性为一个空的function，可以出来提示了，在当前渲染的amis页面下面，可是这个提示的位置不对，也没有靠右上角展示，请问这个classnames应该怎么配置才能把样式带上
![error](https://user-images.githubusercontent.com/110800138/183379776-5c9909f7-5204-4d75-a43d-698d0ea57cae.jpg)

请粘贴你当前方案的完整 amis schema 代码...

```
{
  "type": "page",
  "body": {
    "label": "提示",
    "type": "button",
    "actionType": "toast",
    "toast": {
      "items": [
        {
          "body": "轻提示内容2"
        }
      ]
    }
  }
}
```

**Comment by 154984589** [comment]
大佬你是怎么解决amis-editor自定义组建的，我用vue写显示自定义组建那个属性无效，

**Comment by gaga1990** [comment]
大神你好：
我刚开始接触amis，想把amis做的页面集成到vue2中，一直没啥头绪。
不知道你这边能否帮帮忙提供一下思路？
可以加我微信：15958187876（手机同号），如果可以解决的话，我这边付点费用也是可以的。
期待你的回复。
