### ISSUE TITLE
是否可以隐藏导航栏，将页面通过iframe嵌入其他系统呢？

### ISSUE THREAD

**Issue by liuchy73** [baidu/amis#51]

**Comment by 2betop** [comment]
amis 渲染出来本来就只有内容区域，所以这块是自己控制的

**Comment by liuchy73** [comment]
有没有便捷的参数控制让用户自己能够操作而不是创建页面的时候就不要导航栏呢？比如说用户在当前页面url后加上fullscreen=true这样的参数之后只展现内容区域

**Comment by 2betop** [comment]
amis 渲染出来的部分本来就不包含导航栏，你说的这个功能其实自己的系统里面控制的，目前 amis 平台里面确实也有这种用法，url 加个 embed true,
