### ISSUE TITLE
通过`sh publish.sh`编译的sdk，页面报错 `sdk.js:125 TypeError: t.apply is not a function`

### ISSUE THREAD

**Issue by icodingx** [baidu/amis#511]
有局域网部署的需求，基本的用法如下
```
<link th:href="@{/ajax/libs/amis/sdk/sdk.css}" rel="stylesheet"/>
<style>
html, body, .app-wrapper {position: relative;width: 100%;height: 100%;margin: 0;padding: 0;}
</style>
</head>
<body><div id="root" class="app-wrapper"></div></body>
<script th:src="@{/ajax/libs/amis/sdk/sdk.js}"></script>
<script type="text/javascript">
(function() {amisRequire("amis/embed").embed("#root", {type: "page", body: 'xxx' })})();
</script>
</html>
```

![00](https://user-images.githubusercontent.com/57850028/77544119-91bdfb80-6ee3-11ea-95af-7e6e44d56477.png)

**Comment by 2betop** [comment]
什么版本？是 1.0.10 吗？

**Comment by 2betop** [comment]
实测没问题啊，最新代码，执行 sh publish.sh 编译的代码。

![image](https://user-images.githubusercontent.com/2698393/77602394-57d31080-6f48-11ea-98f7-b8cfe5c8149e.png)

![image](https://user-images.githubusercontent.com/2698393/77602410-60c3e200-6f48-11ea-900a-0ee10e1df0b6.png)
