### ISSUE TITLE
iframe 触发 amis 行为时，希望能加入事件动作的expression属性

### ISSUE THREAD

**Issue by YuanZzhang** [baidu/amis#5116]
在 iframe 组件需要触发 amis 的行为时，好像不支持配置对应的 `expression` 执行条件和事件动作干预等属性。
希望能加入相关属性。

类似于：
![image](https://user-images.githubusercontent.com/81345419/184276173-02520acc-36d1-4bb8-94b6-202590b15be5.png)

**Comment by hsm-lv** [comment]
2.4.1版本将接入事件动作
