### ISSUE TITLE
video在CRUD中展示不正常

### ISSUE THREAD

**Issue by 1178615156** [baidu/amis#5117]
#### 描述问题：
video在CRUD中展示不正常,会占满全屏(好像是直接显示原始的分辨率大小)
- 2.1.0展示异常
- 1.8.0展示正常

使用width也无法控制视频的宽度`"width":300`

#### 截图或视频：

![1660275535577](https://user-images.githubusercontent.com/8329255/184281083-5b7d3323-260d-438c-bba1-2935a9b5ce84.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk
3. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
`2.0`.1,`2.1.0`,`2.1.1-beta.2`都测试过不能正常展示

4. 粘贴有问题的完整 `amis schema` 代码：
```json
{
        "body": [
            {
                "body": [
                    {
                        "columns": [
                            {
                                "label": "label",
                                "name": "name"
                            },
                            {
                                "label": "video",
                                "name": "video",
                                "type": "video"
                            }
                        ],
                        "type": "crud"
                    }
                ],
                "data": {
                    "items": [
                        {
                            "name": "1",
                            "video": "https://amis.bj.bcebos.com/amis/2019-12/1577157317579/trailer_hd.mp4"
                        }
                    ]
                },
                "name": "service",
                "type": "service"
            }
        ],
        "type": "page"
    }
```

**Comment by lovegnep** [comment]
同样遇到该问题

**Comment by lovegnep** [comment]
> #### 描述问题：
> video在CRUD中展示不正常,会占满全屏(好像是直接显示原始的分辨率大小)
> 
> * 2.1.0展示异常
> * 1.8.0展示正常
> 
> 使用width也无法控制视频的宽度`"width":300`
> 
> #### 截图或视频：
> ![1660275535577](https://user-images.githubusercontent.com/8329255/184281083-5b7d3323-260d-438c-bba1-2935a9b5ce84.png)
> 
> #### 如何复现（请务必完整填写下面内容）：
> 1. 你是如何使用 amis 的？
>    sdk
> 2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
>    `2.0`.1,`2.1.0`,`2.1.1-beta.2`都测试过不能正常展示
> 3. 粘贴有问题的完整 `amis schema` 代码：
> 
> ```json
> {
>         "body": [
>             {
>                 "body": [
>                     {
>                         "columns": [
>                             {
>                                 "label": "label",
>                                 "name": "name"
>                             },
>                             {
>                                 "label": "video",
>                                 "name": "video",
>                                 "type": "video"
>                             }
>                         ],
>                         "type": "crud"
>                     }
>                 ],
>                 "data": {
>                     "items": [
>                         {
>                             "name": "1",
>                             "video": "https://amis.bj.bcebos.com/amis/2019-12/1577157317579/trailer_hd.mp4"
>                         }
>                     ]
>                 },
>                 "name": "service",
>                 "type": "service"
>             }
>         ],
>         "type": "page"
>     }
> ```

找到解决方法了，我在引用sdk的index.html的head中加入了css就可以了，你试试吧
<link rel="stylesheet" href="sdk/thirds/video-react/video-react.css" />

**Comment by 1178615156** [comment]
> 

可以了多谢
