### ISSUE TITLE
下一页触发刷新

### ISSUE THREAD

**Issue by sydonay** [baidu/amis#513]
你好，我在使用JSSDK的分页查询时，出现了点击下一页会出现页面刷新的情况。导致刷新前发出的请求必然canceled

**Comment by sydonay** [comment]
![iShot     2020-03-29 上午07 35 56](https://user-images.githubusercontent.com/15826458/77836427-06699200-7191-11ea-906e-88266d7ad257.png)
![iShot     2020-03-29 上午07 44 31](https://user-images.githubusercontent.com/15826458/77836444-24cf8d80-7191-11ea-99b0-88f062ec451f.png)

**Comment by 2betop** [comment]
要不先把 crud 的同步地址栏关了

**Comment by sydonay** [comment]
> 要不先把 crud 的同步地址栏关了

"syncLocation": false

加上这个确实就不会出现页面刷新了，多谢了
