### ISSUE TITLE
怎么在组件中调用js 方法

### ISSUE THREAD

**Issue by LC6LW** [baidu/amis#5133]
#### 实现场景：
在组件中调用js函数 处理后端返回的结果

#### 存在的问题：
![image](https://user-images.githubusercontent.com/29095300/184571721-1e8da94d-e4ec-4031-b726-11c6304e2ac6.png)
这个方法拿不到 变量的值

**Comment by lhtuling** [comment]
牵扯后端接口api处理的  建议仔细阅读下 api的文档
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api

针对接口返回内容做对应处理的话  建议用js的配置文件 + 在配置接收器里面做处理
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8



Amis低代码前端框架QQ交流群
【1群】717791727
【2群】721182449
