### ISSUE TITLE
amis-editor 单选框选择接口获取，在接口的URL处填写一个数据对象变量例${testData}，会强制在前面加上get:

### ISSUE THREAD

**Issue by EvanZheng11** [baidu/amis#5156]
#### 描述问题：

amis@2.0.2, amis-editor@5.2.0 
本意是想使用source: "${testData}"，但被强制加上get:后，就得人工在代码区域改回来（4.1.x版是没问题）。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤

1. 拖入select组件
2. 在属性区的 “选项” - “数据” 选择接口获取，在接口的文本框内填写一个对象的数据映射（不是URL），此时代码区会自动生成"source": {"url": "get:${testData}", "method": "get"}， 但我实际想要的是"source": "${testData}"

**Comment by wibetter** [comment]
新版amis-editor已无此问题了，
<img width="1559" alt="image" src="https://github.com/baidu/amis/assets/11958920/832bebbe-d41b-4bb7-9477-be830db78631">

**Comment by EvanZheng11** [comment]
<img width="842" alt="image" src="https://github.com/baidu/amis/assets/9478026/a57f643b-8871-4482-b5c8-c23075ba7168">
但是还是把source结构给改变了，写${testData}主要是想用source来绑定数据域的变量，不是为了写url

**Comment by wibetter** [comment]
新版已无此问题，请升级amis-editor至最新版本：
<img width="1326" alt="image" src="https://github.com/baidu/amis/assets/11958920/759070a2-0747-47f1-aa2d-e20507c16926">
