### ISSUE TITLE
Vue引入amis运行后报错

### ISSUE THREAD

**Issue by cxiaozhi** [baidu/amis#5166]
#### 实现场景：
我想在Vue里引入amis

#### 存在的问题：
引入之后，运行程序报错：
[Vue warn]: Error in mounted hook: "TypeError: (/((?:https?|file):.*?)\n/.test(...) && RegExp.$1).replace is not a function"

found in

---> <VuePage> at src/view/root/index.vue
       <ElCard> at packages/card/src/main.vue
         <ElMain> at packages/main/src/main.vue
           <ElContainer> at packages/container/src/main.vue... (1 recursive calls)
             <LayoutPage> at src/view/layout/index.vue
               <App> at src/App.vue
                 <Root>

#### 当前方案：
```
<template>
  <div id="root" class="app-wrapper"></div>
</template>

<script>
export default {
  name: "vuePage",
  data() {
    return {

    }
  },
  mounted() {
    this.initData()
  },
  methods: {
    initData() {
      let amis = amisRequire('amis/embed');
      // 通过替换下面这个配置来生成不同页面
      let amisJSON = {
        type: 'page',
        title: '表单页面',
        body: {
          type: 'form',
          mode: 'horizontal',
          api: '/saveForm',
          body: [
            {
              label: 'Name',
              type: 'input-text',
              name: 'name'
            },
            {
              label: 'Email',
              type: 'input-email',
              name: 'email'
            }
          ]
        }
      };
      let amisScoped = amis.embed('#root', amisJSON, {}, {});
    }
  },
}
</script>

<style scoped lang="scss">
</style>
```

**Comment by gaga1990** [comment]
我也在研究这个问题，一直没啥头绪。
不知道你这边解决了没有。
可以加我微信：15958187876（手机同号），一起研究一下。
期待你的回复。

**Comment by WHSnhcZDYRZC** [comment]
你去试试 原代码用 firefox 打开，是正常的 用 chrome 就会报错，RegExp.$1, …, RegExp.$9 是已经被弃用的 api 了（火狐的 RegExp.$1 是空串 chrome 的是 "V"）估计是这个问题

**Comment by atliwen** [comment]
同样的问题   Error in mounted hook: "TypeError: amis.embed is not a function"
![6L50(@C_IXK88XJ}}L~Y5`I](https://user-images.githubusercontent.com/10055836/211507312-ec1ae38f-3fda-4ab5-b8a0-8873685b6d8c.png)

**Comment by lixuecn** [comment]
请问这个问题有解决掉么？我也遇到同样问题

**Comment by QingquanQiu** [comment]
> 请问这个问题有解决掉么？我也遇到同样问题 @cxiaozhi

我也遇见这个问题，是否有人解决了

**Comment by tuotaLijing** [comment]
有人解决吗

**Comment by UltramanWeiLai** [comment]
有人解决了吗？

**Comment by zhushibo** [comment]
通一种写法
我在vue3+vite的项目是正常的
vue2+webpack的老项目是不行的。
这里我换了一个写法，报错虽然还在，但是页面可以正常渲染
```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0"
    />
  </head>

  <body>
    <noscript>
      <strong>请在浏览器打开该页面。</strong>
    </noscript>
    <div id="app">

    <script type="text/javascript" src="<%= BASE_URL %>sdk.js"></script>
  </body>
</html>
```
在html手动引入，大家可以试试。
在vue页面或者main页面引入是不行没，我也没看出这两个有什么区别，暂时只能先这么用了

**Comment by Userluckytian** [comment]
把 webpack 的 devtool 改成 'sourcemap'。解决方案来自[#7550]( https://github.com/baidu/amis/issues/7550)

**Comment by 2betop** [comment]
#7550 同一个问题，先关了，有问题再开
