### ISSUE TITLE
使用json5文件，访问页面报错

### ISSUE THREAD

**Issue by Archerhhh** [baidu/amis#5168]
#### 实现场景：
使用json5文件，内容添加注释后，刷新页面

#### 存在的问题：
提示「sdk.js:2017 Error: Content type is wrong "application/json5; charset=UTF-8"」

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
目前只有官网示例支持 json5，sdk 还不支持，感觉有点小众引入 31k 代码不太划算
