### ISSUE TITLE
amis editor国际化现在有什么方案呢

### ISSUE THREAD

**Issue by CKask** [baidu/amis#5188]
#### 是否关联于某个问题吗：
amis editor国际化现在有什么方案呢
#### 预期的解决方案：

能用配置或者入口注入的方式
然后更改local就可以切换
#### 其他可接受方案：
通过配置文件进入配置
直接使用配置json的字典
#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by wibetter** [comment]
amis-editor已默认支持中英文国际化，相关语料信息可以看这里：
<img width="1251" alt="image" src="https://github.com/baidu/amis/assets/11958920/4c6a1966-f798-4290-badd-2aab565409fb">

**Comment by wibetter** [comment]
amis-editor-demo提供语种切换方式和示例：
<img width="1557" alt="image" src="https://github.com/baidu/amis/assets/11958920/0cbf4902-ec43-4851-adac-11e90d795078">
