### ISSUE TITLE
Tree可以联动展开嘛

### ISSUE THREAD

**Issue by 502647092** [baidu/amis#519]
Tree数据可以通过 `source` 配置获取
但是数据量很大
能不能分层级
比如第一次是最外层
然后点开一个文件夹 加载第二层
不知道有没有这个功能 没有的话能不能加一下

**Comment by 2betop** [comment]
可以加，不过时间要稍微晚点了

**Comment by 502647092** [comment]
> 可以加，不过时间要稍微晚点了

好的 感谢

**Comment by storv** [comment]
这个功能现在做了么@2betop @2betop

**Comment by nwind** [comment]
tree 目前有懒加载了
