### ISSUE TITLE
curd的批量操作怎么控制只刷新当前页，而不是回到第一页

### ISSUE THREAD

**Issue by echome123** [baidu/amis#5203]
当前使用版本：2.1.0
遇到问题： curd的批量操作bulkActions在操作完成后，每次都会自动刷新回到第一页去，如何才能让他只刷新当前页，不要每次都回到第一页去。

通过文档的联动，尝试了reload传参等等，均无效果，不知道如何实现？

**Comment by GetStart13** [comment]
我设置按钮点击行为刷新其它组件，会刷新整个页面，最新版也是这样

**Comment by hsm-lv** [comment]
https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E5%88%B7%E6%96%B0-crud  resetPage:false
