### ISSUE TITLE
ajax download下载请求，无文件下载，页面提示 Response is empty

### ISSUE THREAD

**Issue by songling0** [baidu/amis#5206]
#### 实现场景：
vue中使用amis 1.9.0，download下载后台生成的excel请求，返回的Response Headers里面添加了
Content-Type: application/vnd.ms-excel;charset=utf-8
Content-Disposition: attachment; filename="aa.xlsx"
#### 存在的问题：
无文件下载，页面提示 Response is empty
#### 当前方案：
暂时使用的url下载excel，但还是希望知道ajax download是如何使用的
```
{
  "type": "page",
  "body": {
    "label": "下载",
    "type": "action",
    "actionType": "download",
    "api": "/amis/api/download"
  }
}
```

**Comment by songling0** [comment]
已经找到问题了，是我们自定义的fetcher里面没有传responseType到后台，导致返回到前台的数据类型不是blob。另外原先自定义的fetcher里没有对axios请求的返回数据做attachmentAdpator（‘amis/lib/utils/attachmentAdaptor’）。
具体可参考amis源码examples下的embed.tsx文件实现

**Comment by gaga1990** [comment]
我刚开始接触amis，想把amis做的页面集成到vue2中，一直没啥头绪。
不知道你这边能否帮帮忙提供一下思路？
可以加我微信：15958187876（手机同号），如果可以解决的话，我这边付点费用也是可以的。
期待你的回复。

**Comment by chaos1ee** [comment]
@gaga1990 可以参照     [https://github.com/baidu/amis/blob/7d481e37f0e8e701b621c311b9d970024d9485de/examples/embed.tsx#L213](https://github.com/baidu/amis/blob/7d481e37f0e8e701b621c311b9d970024d9485de/examples/embed.tsx#L213)

把这一行代码加到 fetcher 中，我试了可以正常下载。
