### ISSUE TITLE
amis-editor什么时候会拆分完成，拆分之后可以定制化编辑器吗

### ISSUE THREAD

**Issue by xinlanlan** [baidu/amis#5210]
amis-editor大概什么时候拆分完成呢，拆分完成后可以定制化一些编辑器的插件吗，像lowcode-engine那样，不仅仅是自定义组件。可以在编辑器上增加按钮，有一些钩子可以获取编辑器的一些信息等

**Comment by nwind** [comment]
可以通过自己写插件实现
