### ISSUE TITLE
amis-editor中展现amis已有组件的所有可视化编辑选项

### ISSUE THREAD

**Issue by huzhen813** [baidu/amis#5212]
#### 实现场景：
在amis-editor中，自定义展现**amis已有组件**（例如CRUD）的可视化编辑选项

#### 存在的问题：
amis-editor页面右侧可视化编辑区域，没有组件的所有属性，例如CRUD的autoGenerateFilter属性等。

**Comment by wibetter** [comment]
这个需要自己改对应组件的属性配置项，比如CRUD的属性配置设置在这里：
<img width="808" alt="image" src="https://github.com/baidu/amis/assets/11958920/13de4036-630d-4c8c-93d0-a7db1634d829">
如果发现有缺失的配置项，可以提issue。
