### ISSUE TITLE
react 版本如何动态加载css呢？

### ISSUE THREAD

**Issue by ltsj404** [baidu/amis#5219]
#### 实现场景：
页面中动态加载css，实现不同的主题切换，类似官网的主题切换

#### 存在的问题：
无法同时导入多个css库。如：
cxd.css ,antd.css

<img width="361" alt="image" src="https://user-images.githubusercontent.com/38855041/186295564-c0f2b563-a00c-4aa4-bea0-7260874c4584.png">
导入多个时，只会显示最后一个样式，之前的都被覆盖了。

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
有很多可选方案，自己搜吧，比如 https://stackoverflow.com/questions/28386125/dynamically-load-a-stylesheet-with-react

**Comment by ltsj404** [comment]
好的，感谢提供思路！！
