### ISSUE TITLE
table怎么设置字段排序呢？

### ISSUE THREAD

**Issue by thuglifezhx** [baidu/amis#522]
我想针对Table中的某一个column设置排序，请问要如何配置？

**Comment by 2betop** [comment]
列上配置 sortable: true， 然后接口根据参数处理。

示例里面有

**Comment by thuglifezhx** [comment]
> 列上配置 sortable: true， 然后接口根据参数处理。
> 
> 示例里面有

请问是只能后排序吗？

**Comment by 2betop** [comment]
crud 开启一次性加载， loadDataOnce 可以前端排序

**Comment by thuglifezhx** [comment]
> crud 开启一次性加载， loadDataOnce 可以前端排序

如果只用Table，不用CURD呢？

**Comment by 2betop** [comment]
那恐怕不行

**Comment by duqingyu** [comment]
> 那恐怕不行

请问目前能多字段排序吗？假如我对几个列设置了 sortable: true，目前点击其中一个其他的都会重置。如果目前不支持，后续会考虑支持吗?
