### ISSUE TITLE
CURD增删改查 和  Table 表格组件 建议表头能改颜色

### ISSUE THREAD

**Issue by gaga1990** [baidu/amis#5224]
我们项目中很多表格都是表头带颜色的，我研究了很久，发现amis的CURD增删改查 和  Table 表格组件并没有 修改表头颜色的组件。

不知道这个功能是我没有找到，还是本身就没有？

如果没有的话，建议加一下，这种需求还是很常见的

**Comment by zhangle123** [comment]
可以自定义样式

**Comment by gaga1990** [comment]
> 可以自定义样式

有没有相关的例子，我看表格里面都是只能针对列的样式，没有针对行的。
![image](https://user-images.githubusercontent.com/73697137/186556090-45dbd617-bf7e-46c7-b954-2f8e90cbbb1f.png)

**Comment by yyn0210** [comment]
自定义样式类可以写在page的css里
![image](https://user-images.githubusercontent.com/3253098/186563121-2c6aae59-a7e6-498b-ad9a-f0dfdc6cc8ca.png)

**Comment by LC6LW** [comment]
有的，但是忘了在哪了

**Comment by gaga1990** [comment]
> 自定义样式类可以写在page的css里 ![image](https://user-images.githubusercontent.com/3253098/186563121-2c6aae59-a7e6-498b-ad9a-f0dfdc6cc8ca.png)

能否加个微信：15958187876（手机同号）？

**Comment by gaga1990** [comment]
> 自定义样式类可以写在page的css里 ![image](https://user-images.githubusercontent.com/3253098/186563121-2c6aae59-a7e6-498b-ad9a-f0dfdc6cc8ca.png)

我是刚接触Amis，也不懂前端，只是对html、CSS、js稍稍有点了解；
能否加一下微信：15958187876（手机同号），帮我实现一下这个单独改表头颜色的功能？
我这边可以付一些费用。期待你的回复

**Comment by gaga1990** [comment]
目前这个问题已经解决，解决方案如下：
1、新建一个全局的CSS文件：我的叫public.css，最public目录下：
      .myClass_c  th{
              background-color: #2cbbcd !important;
              color:#ffffff !important;
      }
2、index.html文件里面做CSS引入：
    <link
      rel="stylesheet"
      href="public/public.css"
    />
3、body里面加上我们引入的CSS ：
     "tableClassName" :"myClass_c",
![image](https://user-images.githubusercontent.com/73697137/186638911-eec1eb13-6bb6-4d7c-b598-7eafc39eaab2.png)
4、实现效果
![image](https://user-images.githubusercontent.com/73697137/186639054-692ffc48-98ee-4447-83a0-0d87c5ab7425.png)
5、写在最后：
  感谢大神“yyn0210”的帮助。收货很多，解决了困扰我很久的问题。
