### ISSUE TITLE
amis做出的页面怎样集成到vue2里面？

### ISSUE THREAD

**Issue by gaga1990** [baidu/amis#5239]
#### 实现场景：
1、我用amis编辑器可以做出页面，导出json文件。
2、我们项目一般用vue2开发，我的想法是复杂页面用前端写，简单的页面用amis做。

#### 存在的问题：
amis导出的json文件，还有jsdk怎样集成到vue2中？
菜单栏用vue2做，然后实现vue的页面和amis做出来的页面根据菜单的选择进行切换。

#### 当前方案：
当前没有方案

**Comment by AkkaXdXd** [comment]
自己改下编辑器的代码，对接保存操作调用后端接口，如果你做平台的话，还需要后管，项目管理，目录管理，页面管理等

**Comment by hsm-lv** [comment]
https://github.com/aisuda/vue2-amis-demo
