### ISSUE TITLE
JSSDK使用Chart从后端获取数据

### ISSUE THREAD

**Issue by sydonay** [baidu/amis#525]
JSSDK在使用Chart时如何即在页面中加上config相关信息(配置title,legend, series.type等信息)，又能从后端只获取series.data的信息。

如果只能按照示例中的必须让后端返回完成的echarts配置信息，就有些不灵活了

**Comment by 2betop** [comment]
`onDataFilter` 这个是个加工器，可以式 function 也可以式 function 的字符串形式。

**Comment by sydonay** [comment]
> `onDataFilter` 这个是个加工器，可以式 function 也可以式 function 的字符串形式。

你好这个有使用的示例吗？我在AMis Renderer中没有见到相关的使用例子

**Comment by nwind** [comment]
应该是 dataFilter 这个配置，可以写 js，会传递 config、echarts、data 这几个参数，不过新版加上了动态数据的支持，一般不需要了

**Comment by cheungzh** [comment]
> 应该是 dataFilter 这个配置，可以写 js，会传递 config、echarts、data 这几个参数，不过新版加上了动态数据的支持，一般不需要了

目前6.0.0版本直接使用api 返回的会覆盖原来的配置信息，有没有解决方案
