### ISSUE TITLE
导出带图片的excel，如何设置header

### ISSUE THREAD

**Issue by osenlin** [baidu/amis#5256]
#### 实现场景：
导出带图片的excel，如何设置header

#### 存在的问题：
看到文档里有这一句话，但是在amis里面如何在导出的时候设置header？
<img width="819" alt="image" src="https://user-images.githubusercontent.com/7776208/187084431-6f51811d-0137-4826-87ae-dac7e436e0f1.png">

**Comment by nwind** [comment]
那个链接里有说明了，就是 `Access-Control-Allow-Origin: *` 之类的
