### ISSUE TITLE
onEvent 事件中怎么获取到触发当前事件的Dom 方便一些自定义操作！

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#5277]
onEvent 事件中怎么获取到触发当前事件的Dom 方便一些自定义操作！

**Comment by hsm-lv** [comment]
可以通过event.context.nativeEvent获取原生事件对象，例如：
`
{
  "type": "button",
  "label": "按钮",
  "onEvent": {
    "click": {
      "actions": [
        {
          "args": {
            "msgType": "info",
            "position": "top-right",
            "closeButton": true,
            "showIcon": true,
            "msg": "${event.context.nativeEvent.target.innerHTML|json}"
          },
          "actionType": "toast"
        }
      ]
    }
  },
  "id": "u:a239088834be"
}
`
