### ISSUE TITLE
请问amisRender渲染后可以加一层后处理吗？

### ISSUE THREAD

**Issue by ghost** [baidu/amis#528]
当service和action满足不了我的需求时，我想做个钩子来处理一些事件。目前render的出口应该只有axios这部分的自定义实现。

**Comment by 2betop** [comment]
来个具体的使用场景

**Comment by thuglifezhx** [comment]
> 来个具体的使用场景
比如我想打印、截屏、导出PDF等这类操作

**Comment by thuglifezhx** [comment]
> 来个具体的使用场景

比如我想打印、截屏、导出PDF等这类操作

**Comment by 2betop** [comment]
这些用 amis 不合适吧，打印倒是可以写写样式能成。

**Comment by thuglifezhx** [comment]
> 这些用 amis 不合适吧，打印倒是可以写写样式能成。

老师您好，我们是这样考虑的，amis render引擎把json配置消化渲染后的生成物，是否有可能给我们介入一下，做一点扩增修补的工作？ 
具体而言：
```
     ...
     //json schema配置准备
     ...
     render(schema);
     ...

     //大哥，我们想在这里做一些渲染后处理，或者可以给我们注册一个Component在此处触发渲染链条，是否可行？
     //盼复，谢谢！
```

**Comment by 2betop** [comment]
不好意思，我还是不太清楚是什么个使用场景。 amis 渲染完，返回的其实是 react dom 节点，通过 React-dom 渲染导 html node 上。这个中间产物，你能做啥呢？我不是很明白。
