### ISSUE TITLE
弹框中的表单使用combo多行模式的时候，新增就退出

### ISSUE THREAD

**Issue by toneygu** [baidu/amis#529]
![image](https://user-images.githubusercontent.com/6273928/78484099-209b0580-7779-11ea-868d-01102dd56222.png)

**Comment by RickCole21** [comment]
没能复现呢，发一下版本和具体schema配置？

**Comment by toneygu** [comment]
> 没能复现呢，发一下版本和具体schema配置？

v1.0.10
  "_from": "amis@1.0.10",
  "_resolved": "https://registry.npm.taobao.org/amis/download/amis-1.0.10.tgz"

{
    "type": "page",
    "title": "SubForm 示例2",
    "body": [
        {
            "type": "form",
            "api": "https://houtai.baidu.com/api/mock2/saveForm?waitSeconds=2",
            "title": "Form elements",
            "mode": "horizontal",
            "controls": [
                {
                    "type": "button",
                    "label": "弹个表单",
                    "actionType": "dialog",
                    "dialog": {
                        "title": "在弹框中的表单",
                        "closeOnEsc": false,
                        "actions": [
                            {
                                "label": "取消",
                                "actionType": "close",
                                "type": "button"
                            },
                            {
                                "label": "确认",
                                "actionType": "confirm",
                                "type": "button",
                                "level": "primary"
                            }
                        ],
                        "body": {
                            "type": "form",
                            "api": "https://houtai.baidu.com/api/mock2/form/saveForm?waitSeconds=2",
                            "title": "常规模式",
                            "mode": "normal",
                            "submitOnChange": false,
                            "controls": [
                                {
                                    "type":"combo",
                                    "multiple":true,
                                    "submitOnChange": false,
                                    "value":[{}],
                                    "controls":[
                                        {
                                            "label": "名称",
                                            "name": "label",
                                            "type": "text",
                                            "required": true
                                        }
                                    ]
                                }
                                
                            ]
                        }
                    }
                }
            ]
        }
    ]
}

**Comment by nwind** [comment]
这个配置有点问题，combo 需要有 name
