### ISSUE TITLE
同一个表单如何实现多个初始化请求

### ISSUE THREAD

**Issue by month-june** [baidu/amis#5302]
#### 实现场景：
在一个表单里有两个inputText输入框，我希望可以实现第一个输入框的初始默认值通过api1来获取，第二个输入框的初始默认值通过api2来获取

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by xinlanlan** [comment]
第二个表单框，通过service组件包一层，获取当前层级的data中的数据。是否可以满足你的需求

**Comment by hsm-lv** [comment]
或者监听inited事件，然后执行ajax动作
https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E5%8F%91%E9%80%81-http-%E8%AF%B7%E6%B1%82
