### ISSUE TITLE
富文本编辑器在jssdk模式下，显示不正常，不能正常使用

### ISSUE THREAD

**Issue by huangkaiyan10** [baidu/amis#5303]
![bd462d4761bdc968c126c852dad6c95](https://user-images.githubusercontent.com/5146180/188357120-1d5119f0-3d8f-48ed-bafc-77feb3dfb165.jpg)

<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="UTF-8" />
    <title>amis demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <link rel="stylesheet" href="./assets/amis-sdk/sdk.css" />
    <link rel="stylesheet" href="./assets/amis-sdk/helper.css" />
    
    
    
    <style>
      html,
      body,
      .app-wrapper {
        position: relative;
        width: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="root" class="app-wrapper"></div>
	<button onclick="test()">点击调试-获取值</button>
	<button onclick="test2()">点击调试-設置值</button>
	<button onclick="setVal2()">点击调试-設置值-222</button>
	<button onclick="setVal_service_1()">点击调试setVal_service_1-設置值-222</button>
	<button onclick="setVal_service_2()">点击调试setVal_service_2-設置值-222</button>
    <script src="./assets/amis-sdk/sdk.js"></script>
    <script type="text/javascript">
	var amis=null;
	var amisScoped=null;
      (function () {
         amis = amisRequire('amis/embed');
        // 通过替换下面这个配置来生成不同页面
        let amisJSON = {
			  "type": "page",
			  "body": [
			  {
				"type": "form",
				"id": "form1",
				"body": [
				  {
					"type": "input-text",
					"name": "name",
					"label": "姓名："
				  },
				  {
					"name": "email",
					"type": "input-email",
					"label": "邮箱："
				  },
				  {
					"type": "input-rich-text",
					"name": "rich",
					"label": "Rich Text"
				  }
				],
				"actions": [
					  {
						"type": "button",
						"label": "主要",
						"level": "primary",
						"onClick": (event,props)=>{
						   console.log('setValue  form1')
						    console.log(JSON.stringify(props.data))
						  props.onAction(event, {
								  'actionType': 'setValue',
								  "componentId": "form1",
								  "args": {
										"value": {"name":"lisi xxx","email":" email xxxx"}
									  }
								});
						}
						
					  },
					  {
						"type": "button",
						"label": "次要",
						"level": "secondary",
						"onClick": (event,props)=>{
						   console.log('setValue  form1')
						    console.log(JSON.stringify(props.data))
						  props.onAction(event, {
								  'actionType': 'setValue',
								  "componentId": "service_1",
								  "args": {
										"value": {"text1":"lisi xxx","text2":" email xxxx"}
									  }
								});
						}
					  }
				]
			  },
			  { "type": "service",
			     "id": "service_1",
			     "body": [
				      {
						"type": "tpl",
						"tpl": "Hello ${text1}"
					  },
					  {
						"type": "divider"
					  },
				      {
						"type": "tpl",
						"tpl": "Hello ${text2}"
					  }					  
				 ]
			  }
			  ]
			};
			
         amisScoped = amis.embed('#root', amisJSON);
      })();
	  

	  function getVal3(){

	    let compInstance1=amisScoped.getComponentByName("form1")
		let data=compInstance1.props.data
		 let name1_value=compInstance1.props.data.name1
		 console.log("getVal3 data="+JSON.stringify(data))
		 console.log("getVal3 name1_value="+JSON.stringify(name1_value))
	  }	 
	  
	  function setVal1(){	
	  
	  let compInstance1=amisScoped.getComponentById("form1")
		   compInstance1.setData({"name":"getComponentById setData1111"})
		   
		   /*
		 amisScoped.updateProps(
					  {
						data:{"name1":"通过amisScoped.updateProps 设置值"}
					  } 
					);
					*/
	  }	 

	  function setVal2(){	
           
		   let compInstance1=amisScoped.getComponentById("form1")
		   compInstance1.setData({"name":"getComponentById setData"})
      /*		   
		 amisScoped.updateProps(
					  {
						data:{"name1":"通过amisScoped.updateProps 设置值-2222"}
					  } 
					);
					*/
	  }	 
     function test(){
	   getVal3();
      }	 
	  
	  function test2(){
	    setVal1();
	  }
	  

	  
    </script>
  </body>
</html>

**Comment by huangkaiyan10** [comment]
你的邮件我已经收到。谢谢
 
                              黄开雁

**Comment by huangkaiyan10** [comment]
![1662349990871](https://user-images.githubusercontent.com/5146180/188357485-4c6b17bb-6d07-458b-9461-1595cd3fac91.jpg)

**Comment by huangkaiyan10** [comment]
在jssdk模式下，需要引入什么资源，才能正常使用富文本编辑器呢？下图是我引入的资源
![17e29722839560c5cc3dba7fd6ff51e](https://user-images.githubusercontent.com/5146180/188358444-976d19cd-50d3-4459-83a0-363c3d5882bf.jpg)

**Comment by huangkaiyan10** [comment]
最终引入一个样式文件解决。
		<link rel="stylesheet" href="./assets/amis-sdk/thirds/tinymce/skins/ui/oxide/skin.css" />

**Comment by huangkaiyan10** [comment]
<link rel="stylesheet" href="./assets/amis-sdk/thirds/tinymce/skins/ui/oxide/skin.css" />

**Comment by nwind** [comment]
fixed in #5318
