### ISSUE TITLE
根据官方提供的chart示例无法渲染

### ISSUE THREAD

**Issue by thuglifezhx** [baidu/amis#531]
你好，我根据官方提供的示例和API，但是无法在AMIS中将chart渲染出来，提示error错误，但没有其他信息，渲染table就可以，但是chart就不行。
示例如下：
```
{
    "type": "page",
    "body": {
        "type": "chart",
        "api": "https://houtai.baidu.com/api/mock2/chart/chart",
        "interval": 5000
    }
}
```

**Comment by 2betop** [comment]
你直接用 amis 的 api，可能会存在跨域问题

**Comment by thuglifezhx** [comment]
> 你直接用 amis 的 api，可能会存在跨域问题

那可不可以不通过api，直接撸一个chart出来？直接在body里定义chart的数据可以吧？

**Comment by 2betop** [comment]
chart 支持静态配置，具体看文档： https://baidu.github.io/amis/docs/renderers/Chart#chart

**Comment by thuglifezhx** [comment]
> chart 支持静态配置，具体看文档： https://baidu.github.io/amis/docs/renderers/Chart#chart

我用静态配置依旧渲染不出来。。。
以下是我配置的代码：
```
{
    "type": "chart",
  	"body": {
      "title": {
            "text": "销售情况"
        },
        "tooltip": {},
        "legend": {
            "data": [
                "销量"
            ]
        },
        "xAxis": {
            "data": [
                "衬衫",
                "羊毛衫",
                "雪纺衫",
                "裤子",
                "高跟鞋",
                "袜子"
            ]
        },
        "yAxis": {},
        "series": [
            {
                "name": "销量",
                "type": "bar",
                "data": [
                    95,
                    45,
                    22,
                    73,
                    63,
                    21
                ]
            }
        ]
    }
}
```

**Comment by thuglifezhx** [comment]
> chart 支持静态配置，具体看文档： https://baidu.github.io/amis/docs/renderers/Chart#chart

我试了Table、Form等其他模块，唯独chart无法渲染。。。

**Comment by 2betop** [comment]
应该是

```json
{
  "type": "chart",
  "body": {
    "config": {
      "title": {
          "text": "销售情况"
      },
      "tooltip": {},
      "legend": {
          "data": [
              "销量"
          ]
      },
      "xAxis": {
          "data": [
              "衬衫",
              "羊毛衫",
              "雪纺衫",
              "裤子",
              "高跟鞋",
              "袜子"
          ]
      },
      "yAxis": {},
      "series": [
          {
              "name": "销量",
              "type": "bar",
              "data": [
                  95,
                  45,
                  22,
                  73,
                  63,
                  21
              ]
          }
      ]
    }
  }
}
```

**Comment by thuglifezhx** [comment]
> 应该是
> 
> ```json
> {
>   "type": "chart",
>   "config": {
>       "title": {
>           "text": "销售情况"
>       },
>       "tooltip": {},
>       "legend": {
>           "data": [
>               "销量"
>           ]
>       },
>       "xAxis": {
>           "data": [
>               "衬衫",
>               "羊毛衫",
>               "雪纺衫",
>               "裤子",
>               "高跟鞋",
>               "袜子"
>           ]
>       },
>       "yAxis": {},
>       "series": [
>           {
>               "name": "销量",
>               "type": "bar",
>               "data": [
>                   95,
>                   45,
>                   22,
>                   73,
>                   63,
>                   21
>               ]
>           }
>       ]
>     }
> }
> ```

可以了，非常感谢。建议将官方文档的示例配置更新一下，因为API接口会存在跨域问题，官方文档又没有给出静态配置的示例，真的是太难了。

**Comment by 2betop** [comment]
第一个就是 https://baidu.github.io/amis/chart
左上角可以查看源码
