### ISSUE TITLE
富文本编辑器rich-text，嵌套在dialog、drawer中使用，rich-text的菜单层被遮盖，z-index 是准确

### ISSUE THREAD

**Issue by huangkaiyan10** [baidu/amis#5310]
版本2.2.0 
![3](https://user-images.githubusercontent.com/5146180/188406759-2f2b4faa-adb5-4d8b-b6bf-318ace1024e6.png)
![2](https://user-images.githubusercontent.com/5146180/188406800-fd4f9761-8511-4964-9dcf-1d0cfc73a9b3.jpg)

**Comment by huangkaiyan10** [comment]
富文本编辑器rich-text，嵌套在dialog、drawer中使用，rich-text的菜单层被遮盖，z-index 是不准确的。rich-text的菜单层 应该要在最上面，实际是在下面，看不到。

**Comment by huangkaiyan10** [comment]
jssdk 2.2.0

**Comment by nwind** [comment]
换一下 css 顺序，那个 oxide/skin.css 放 sdk.css 前面，不过现在不清楚为什么 sdk.css 里没包含

**Comment by huangkaiyan10** [comment]
收到，已经验证效果。
