### ISSUE TITLE
Button组件的url或href不生效

### ISSUE THREAD

**Issue by xinlanlan** [baidu/amis#5323]
#### 描述问题：

在官方文档中测试配置，url属性不生效

#### 截图或视频：

<img width="960" alt="image" src="https://user-images.githubusercontent.com/23093206/188578662-3a8e2051-2025-4d0a-a439-3c2665650b8b.png">

#### 如何复现（请务必完整填写下面内容）：

```json
{
  "type": "page",
  "body": {
    "label": "弹个框",
    "type": "button",
    "url": "https://www.baidu.com"
  }
}
```
看源码是href属性，会渲染为a标签，使用href属性依然无效

**Comment by xinlanlan** [comment]
官网文档：https://aisuda.bce.baidu.com/amis/zh-CN/components/button

**Comment by qianxiaofendou** [comment]
你少了个actionType属性

**Comment by xinlanlan** [comment]
> 你少了个actionType属性

看amis-ui 源码，以为有href属性，会渲染为a标签呢，看来都是通过行为来跳转
