### ISSUE TITLE
月份范围，如何提取起始值或者结束值

### ISSUE THREAD

**Issue by Archerhhh** [baidu/amis#5324]
#### 实现场景：
在表单中设置一个月份范围参数

#### 存在的问题：
当发送请求时，如何提取这个月份范围的起始值呢

#### 当前方案：

```
code here...
```

**Comment by Archerhhh** [comment]
已解决

解决方案：
借助表达式-「SPLIT」-https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#split
因为使用月份范围时，获取到的是一个包含起止月份的字符串，可以通过SPLIT表达式将它分割成数组，然后使用数组格式分别提取即可

例如
 "start_date": "${SPLIT(date, ',')[0]}"
 "end_date": "${SPLIT(date, ',')[1]}"

**Comment by xinlanlan** [comment]
> 
我暂时也是通过这种方式解决的，可以加个微信一起交流吗
我的: flytiger123

**Comment by lhtuling** [comment]
自问自答型大佬   牛逼

Amis低代码前端框架QQ交流群 
【1群】717791727
【2群】721182449
