### ISSUE TITLE
如何回显inputImage图片

### ISSUE THREAD

**Issue by taoyao-code** [baidu/amis#5330]
#### 实现场景：
```
{
  "type": "input-image",
  "name": "_attachment",
  "id": "edit__attachment",
  "label": "界面预览图片",
  "clearable": true,
  "receiver": "/upload/0/0",
  "frameImage": "/xxxx/xxxx/xxx/jpg"
}
```
上述例子中，frameImage 为api接口地址，返回为一张图片，但api需要添加请求头信息

#### 存在的问题：
如何在 frameImage 中使用API接口请求(进行拦截请求添加一些接口信息(如token等))

**Comment by lhtuling** [comment]
你这标题内容严重不符啊   

是要添加请求头么？
是的话试试下面的

``````
 "receiver":{
      "method": "post",
      "url": "/amis/api/mock2/form/saveForm",
      "headers": {
        "my-header": "aaa"
      }
    },
``````

在具体看下文档
![image](https://user-images.githubusercontent.com/44140500/190910538-0f5df95a-6cd9-4222-b709-78914124511c.png)
https://aisuda.bce.baidu.com/amis/docs/types/api


Amis低代码前端框架QQ交流群
【1群】717791727
【2群】721182449

**Comment by ltsj404** [comment]
> 

并不是，是这样的，上传是上传的接口，这个位置的链接是一个API接口，并返回图片的(有获取文件权限判断的(类似))
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/38855041/190911995-d598d3a0-11f5-4ce9-9eea-cd1783141e18.png">

**Comment by lhtuling** [comment]
> {
>   "type": "input-image",
>   "name": "_attachment",
>   "id": "edit__attachment",
>   "label": "界面预览图片",
>   "clearable": true,
>   "receiver": "/upload/0/0",
>   "frameImage": "/xxxx/xxxx/xxx/jpg"
> }

调用接口上传成功后 根据返回的地址在这里回显是吧？

**Comment by lhtuling** [comment]
如果是上传成功显示的话   文档写的很清楚
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-image
这个接口需要返回图片地址，比如下面的格式
``````
{
  "status": 0,
  "msg": "",
  "data": {
    "value": "https:/xxx.yy/zz.png"
  }
}
``````
如果是选择图片上传之前直接显示预览的话  可能要自己写js代码了
比较麻烦点了
