### ISSUE TITLE
如何批量请求接口？

### ISSUE THREAD

**Issue by whuter** [baidu/amis#535]
实际场景下，用户操作一次要请求多次接口的情况还是挺多的。
比如，现在需要根据用户输入的多个ID，批量查询/添加一批数据，后端接口不支持批量，由前端逐个ID请求调用，并且拼接结果，该如何实现？
（接口api是同一个，但每次调用传参不一样）
（既有并行的调用，也有可能是串行的，比如需要依赖上次返回的offset拉取下次的数据，直至全部拉取完毕，用户点击一次，导出全部数据）

**Comment by 2betop** [comment]
不好意思，amis 还不支持这种场景，一个操作只能调用个接口

**Comment by whuter** [comment]
那就是现在无法实现吗？有考虑支持么

**Comment by 2betop** [comment]
这个功能，我抽象不出来，所以先不考虑加了。

**Comment by 0undefined0** [comment]
这个需求确实多
