### ISSUE TITLE
input-number & navtive-number控件

### ISSUE THREAD

**Issue by vexos-io** [baidu/amis#5351]
input-number的上下箭头不显示，只有两个空白按钮，如下图：
<img width="334" alt="截屏2022-09-09 19 56 03" src="https://user-images.githubusercontent.com/56525941/189344719-fc087670-1273-4248-9d73-4e620051df2d.png">

而：native-number 在disabled 时，样式还是正常样式，会让操作者以为还可以编辑。

**Comment by nwind** [comment]
第一个是没有引入 iconfont.css，第二个没复现
