### ISSUE TITLE
发送一个请求，请求成功后的联动

### ISSUE THREAD

**Issue by xinlanlan** [baidu/amis#5354]
#### 实现场景：
我点击按钮发送一个请求，请求成功后可能需要打开弹窗，也可能刷新目标组件或者其他联动。目前使用amis-editor时service组件不支持刷新组件，在“其他” 一栏中 点击“添加事件” 没有反应，看起来是不支持添加事件的

**Comment by lhtuling** [comment]
手写代码实现吧
个人建议有能力尽量别太依赖编辑器 
编辑器虽然方便   但是限制太多了
你的需求可以参考下

https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E5%88%B7%E6%96%B0
接受适配器配合js格式的配置文件  可以自定义超级多功能
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E5%87%BD%E6%95%B0%E5%BD%A2%E5%BC%8F

**Comment by hsm-lv** [comment]
没明白你的场景，目前刷新是支持的
