### ISSUE TITLE
淘宝Amis关键子做搜索引擎竞价推广有点不要脸了吧  

### ISSUE THREAD

**Issue by yyn0210** [baidu/amis#5356]
![image](https://user-images.githubusercontent.com/3253098/189818513-877a24a4-7a62-49f8-986d-498b3752c0cc.png)

**Comment by jorgekupkarft** [comment]
。。。对淘宝无语了。。。

**Comment by sangyuxiaowu** [comment]
正常，bing无论你搜什么前几个都是广告
