### ISSUE TITLE
通过json配置的方式，如何保证代码安全？

### ISSUE THREAD

**Issue by ozil-cao** [baidu/amis#5360]
首先，感谢baidu大神们为我们提供了这么优秀的框架工具。在使用sdk模式，页面配置都使用json方式来开发，那么如何保证知识产权呢，可读化json相当于裸奔状态，对手要是抄袭太轻松了，完全避免是不可能，增加被抄袭难度也是一条路径？比如在服务器端做点啥？

**Comment by luanwulin** [comment]
前端哪有什么私密性，你就算普通的前端项目，写了js别人想偷还不是一样的偷

**Comment by nwind** [comment]
amis 是个开源项目所以做不了的，自己用 webassembly 做个简单的加密吧，虽然也只能防小白
