### ISSUE TITLE
文本框input设置默认值引发其他input触发默认值的bug

### ISSUE THREAD

**Issue by rebitco** [baidu/amis#5363]
#### 描述问题：

在内容区拖拽了几个文本框，接着设置其中一个文本框的默认值，其他文本框都把这个值读取过来了

#### 截图或视频：

<img width="960" alt="image" src="https://user-images.githubusercontent.com/17375326/190097335-8c04e2b2-0873-45d3-add7-1482fc5422e3.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
    A：直接使用官方的示例：https://aisuda.github.io/amis-editor-demo/#/edit/2
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
    A：官方示例网站，不知道什么版本
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "input-text",
  "label": "单价",
  "name": "price",
  "id": "u:624dd34f2a04",
  "value": "2.5"
}
```

4. 操作步骤
     1）从组件区拖几个input和select, 然后修改字段名和label;
     2)  然后选中其中一个input，设置默认值为任一数字，设置完失焦后，其他input的value全变成刚才设置的那个数字。

**Comment by lhtuling** [comment]
![image](https://user-images.githubusercontent.com/44140500/190904749-4061b1f4-a1d7-4aac-877b-0d3765086d3d.png)

  "name": "price",
没感觉错的话应该是字段名一样导致的！！
细心检查下看看

Amis低代码前端框架交流群
【1群】717791727
【2群】721182449

**Comment by wibetter** [comment]
@rebitco 大概是因为这几个组件用的是同一个name，这样就会出现其中一个组件数值变动其他同名name的组件也会跟着变动。
