### ISSUE TITLE
dialog 中设置了 menuTpl 和 searchable 的 select 无法选中

### ISSUE THREAD

**Issue by biley** [baidu/amis#5369]
#### 描述问题：

dialog 中设置了 menuTpl 和 searchable 的 select 无法直接选中
![企业微信截图_00b2c8f6-f1cd-465c-8351-382b8cceee35](https://user-images.githubusercontent.com/15087577/190365528-2e850dba-ca6f-4a55-a8e2-63586d8e3b41.png)

但是点击对应选项的 padding 的话，是可以选中的
![截屏2022-09-15 17 11 14](https://user-images.githubusercontent.com/15087577/190365590-c3c44555-0929-4071-8e5d-34ca1ab3f97c.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新 amis，可直接在官网文档中复现：https://aisuda.bce.baidu.com/amis/zh-CN/components/page

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
    {
      "type": "form",
      "body": [
        {
          "type": "button",
          "label": "按钮",
          "actionType": "dialog",
          "dialog": {
            "title": "系统提示",
            "body": [
              {
                "type": "select",
                "label": "选项",
                "name": "select",
                "menuTpl": "<div>${label} 值：${value}, 当前是否选中: ${checked}</div>",
                "options": [
                  {
                    "label": "A",
                    "value": "a"
                  },
                  {
                    "label": "B",
                    "value": "b"
                  },
                  {
                    "label": "C",
                    "value": "c"
                  }
                ],
                "searchable": true
              }
            ],
            "type": "dialog"
          }
        }
      ]
    }
  ]
}
```

5. 操作步骤
直接点击选项 content 是无法选中的，点击选项的 padding 区域可以选中

**Comment by biley** [comment]
好像和 html 标签有关，正常使用模板 ${} 是没关系的；用 html 标签包裹的内容点击就会失效

**Comment by lurunze1226** [comment]
用你提供的Schema没复现
