### ISSUE TITLE
columns中name为变量

### ISSUE THREAD

**Issue by yang2wuhen** [baidu/amis#538]
crud中columns有一个表头字段name为变量，怎么获取到返回数据中变量对应字段的值！

**Comment by RickCole21** [comment]
没太理解，column配置了name应该是自动就会映射对应变量的值

**Comment by yang2wuhen** [comment]
这个name是动态的，后台传过来的一个变量。

**Comment by CareyToboo** [comment]
@yang2wuhen 你说的应该是，根据接口返回字段，生成动态列的需求。你看这个isuue. #442

**Comment by yang2wuhen** [comment]
可以这样描述，问题本质一样

**Comment by RickCole21** [comment]
用 Service 的`schemaApi`
