### ISSUE TITLE
移动端下没有打开菜单图标

### ISSUE THREAD

**Issue by DataAlert-cn** [baidu/amis#5388]
#### 描述问题：

![Screenshot_20220919_122057_com microsoft emmx_edit_104027350140896](https://user-images.githubusercontent.com/107041272/190950031-0d33845b-1fad-45a9-a35b-37d2f4a7f11f.jpg)
![Screenshot_20220919_122109_com microsoft emmx](https://user-images.githubusercontent.com/107041272/190950041-4bfd5710-c5a8-4703-8933-d007dab0a1da.jpg)

如第一张图，右上角没有任何图标，但点击后可以调出第二张图的菜单。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`，按amis admin项目的方式使用。

2. amis 版本是什么？
v2.2

**Comment by sxaxin** [comment]
貌似缺少这个:  <link rel="stylesheet" href="./sdk/iconfont.css" />

**Comment by DataAlert-cn** [comment]
> 貌似缺少这个: `<link rel="stylesheet" href="./sdk/iconfont.css" /> `

的确如此，非常感谢！
