### ISSUE TITLE
table表格高亮行，写class不生效。

### ISSUE THREAD

**Issue by taoyao-code** [baidu/amis#5419]
#### 描述问题：

在表格中高亮行，class无法生效

#### 截图或视频：

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/38855041/191680736-1f4cbc50-fc6b-4320-b0a4-b712f1760907.png">
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/38855041/191680884-a796b630-bbae-47fa-8edb-4377c5e0f3cb.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
版本：2.2.0

3. 粘贴有问题的完整 `amis schema` 代码：

4. 操作步骤
官网可直接操作

**Comment by lhtuling** [comment]
这应该是个小bug   
解放方法
1、自己写个样式吧 
2、用别的颜色  比如  bg-green-100  就可以
![image](https://user-images.githubusercontent.com/44140500/192101614-ac029ee7-85af-4811-94fc-93eafc07956b.png)

**Comment by lurunze1226** [comment]
should be resolved by #5453

**Comment by taoyao-code** [comment]
颜色又无法生效了。
