### ISSUE TITLE
请问如何实现动态配置选项卡

### ISSUE THREAD

**Issue by daiyuanfei741** [baidu/amis#5421]
![image](https://user-images.githubusercontent.com/34326481/191728858-b64182c1-8f08-44bf-b5ba-bd29c069b773.png)
我想实现这种效果，
{
  "type": "page",
  "data": {
    "arr": [
      {
        "a": "收入",
        "b": 199
      },
      {
        "a": "支出",
        "b": 299
      }
    ]
  },
  "body": [
    {
      "type": "tabs",
      "source": "${arr}",
      "tabs": [
        {
          "title": "${a}",
          "body": {
            "type": "tpl",
            "tpl": "金额：${b|number}元"
          }
        }
      ]
    }
  ]
}

请问  arr  如何能通过接口返回得到数据，动态获得选项卡

**Comment by AkkaXdXd** [comment]
```
{
    "type": "tabs",
    "source": "${items}",
    "tabs": [
        {
          "title": "${indexCnName}"
        }
    ]
}
```

**Comment by hsm-lv** [comment]
> 在page里请求数据就行了？

arr可以来自当前数据域，例如page、service等都可以
