### ISSUE TITLE
如何让指定的一个api不受请求适配器的影响？

### ISSUE THREAD

**Issue by imcaoxuan** [baidu/amis#5437]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

**我使用了requestAdapter让某个amis对象的中所有api的header带上Authorization，但是我现在想让其中的“下载”api不使用这个requestAdapter。**

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

**无法让某一个api不使用requestAdapter**

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by lhtuling** [comment]
在适配器里面做判断么~~
网址包含的直接返回
