### ISSUE TITLE
initApi放在type:page下有效,但放在type:input-text下无效,请问是input-text不支持吗?

### ISSUE THREAD

**Issue by jiayouzl** [baidu/amis#5440]
谢谢

**Comment by zhouqiang1983** [comment]
不支持，官网文档有写的。form组件支持，所以想给input-text初始化值，要么在外面放一个form组件，要么放一个service组件。我个人习惯是涉及交互的地方，包一个form组件在外面。

**Comment by jiayouzl** [comment]
> 

懂了朋友

**Comment by jiayouzl** [comment]
> 不支持，官网文档有写的。form组件支持，所以想给input-text初始化值，要么在外面放一个form组件，要么放一个service组件。我个人习惯是涉及交互的地方，包一个form组件在外面。

懂了朋友,谢谢
