### ISSUE TITLE
锚点导航组件在2.2.0版本样式问题

### ISSUE THREAD

**Issue by zhouqiang1983** [baidu/amis#5443]
问题有2个：
1.左侧的导航链接，当标题名称过长时，文字会重叠。
     官方示例即可演示出此bug。（1.10.2版本下，无此问题）
2.当在抽屉drawer中使用锚点导航组件时，发现高度仅占了屏幕的部分，使用h-full也无法生效（1.10.2版本下，无此问题）。
       该jsonschema在amis-editor中显示正常，把它放到react项目中，直接加载此jsonschema时，出现此问题。
       通过F12分析，一共2个css class：antd-AnchorNav和h-full。在1.10.2版本中，h-full定义的height生效；在2.2.0版本中，antd-AnchorNav的height生效。

**Comment by lurunze1226** [comment]
should be resolved by #5469

**Comment by zhouqiang1983** [comment]
作了...效果，也可以接受。最好还是能像1.10.2一样，自动换行哈。

**Comment by cjb1234567** [comment]
在antd.css中，找到：
```
.amis-scope .antd-AnchorNav {
  display: flex;
  height: 25rem;
}
```
把里面的 ` height: 25rem; `删掉即可。

不知道为什么要写这个高度，不明白到底什么意思。
