### ISSUE TITLE
amis-editor从4.1.0-beta.20 升级到5.2.0 引入amis-editor/dist/style.css报错

### ISSUE THREAD

**Issue by heisen16129** [baidu/amis#5446]
![image](https://user-images.githubusercontent.com/57136111/192237645-0b28ef69-84c2-47b7-948f-658d3beef776.png)

**Comment by Scelmx** [comment]
我也遇到相同问题 @Ding4514 你现在解决了吗？

**Comment by wibetter** [comment]
请升级amis-editor到最新版，之前的样式已改放amis-editor-core/lib/style.css中，
