### ISSUE TITLE
[amis-editor-demo] - 预览模式下刷新后，再回到编辑模式，左侧工具栏消失

### ISSUE THREAD

**Issue by rencoo** [baidu/amis#5447]
#### 描述问题：

官方编辑器，预览模式下刷新后，再回到编辑模式，左侧工具栏消失

#### 截图或视频：
预览模式，点击浏览器左上角刷新页面按钮
<img width="1440" alt="截屏2022-09-26 17 18 57" src="https://user-images.githubusercontent.com/39717611/192240767-337cdfec-30f9-4b27-bdb8-75760ebc39c4.png">
点击编辑按钮，查看页面左侧工具栏，左侧工具栏消失（必现）
<img width="1437" alt="截屏2022-09-26 17 18 45" src="https://user-images.githubusercontent.com/39717611/192241246-6f874146-230a-4cd6-997d-1bbb7b5cba3a.png">

#### 解决方案
初始化时，设置模式为"编辑"，临时解决这个问题

**Comment by wibetter** [comment]
@rencoo 此问题已经修复，请更新amis-editor版本，或者也可以在这里验证：https://aisuda.github.io/amis-editor-demo/#/edit/0
