### ISSUE TITLE
CRUD修改后想在提交前直接获取数据如何进行呢，谢谢

### ISSUE THREAD

**Issue by mixiaodiao** [baidu/amis#5448]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
我一个大的form想最后一起提交，但是中间用crud进行一个表部份数据的修改

#### 存在的问题：
不管是快速、理解什么的不是太适合，想最后通过额外js进行提交，想要获取crud修改后（未保存到服务器）的数据
*form中的可以，但是form中的crud部份只是没修改的

#### 当前方案：
希望指导下如何获取，比如amisScoped.getComponentByName("wfpage.wfform").getValues()，这样的
谢谢

**Comment by lhtuling** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E9%80%82%E9%85%8D%E5%99%A8

成功了

**Comment by hsm-lv** [comment]
新版支持通过表达式获取组件数据域，详见https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E8%8E%B7%E5%8F%96%E7%BB%84%E4%BB%B6%E7%9B%B8%E5%85%B3%E6%95%B0%E6%8D%AE
