### ISSUE TITLE
curd  将自己API中返回的总数total 如何转换成  amis 使用的count

### ISSUE THREAD

**Issue by gaga1990** [baidu/amis#5449]
amis需要数据源接口中返回了数据总数**count**
![image](https://user-images.githubusercontent.com/73697137/192281289-e737e1ab-661a-4955-87a3-835747a1c37c.png)

而我的API都是统一返回的是total，大伙有没有办法在不改后端的情况下将 返回的数据 中total字段 适配成amis 需要 count字段

**Comment by myde86** [comment]
在请求接口后返回的数据做一下映射就可以了
`{
  "type": "page",
  "initApi": {
    "method": "get",
    "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/xxx",
    "responseData": {
      "count": "$total"
    }
  }
}`

**Comment by lhtuling** [comment]
接受适配器
看下文档  直接搞定
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8
Amis低代码前端框架交流群
【1群】717791727
【2群】721182449
