### ISSUE TITLE
富文本问题

### ISSUE THREAD

**Issue by iswangyinhao** [baidu/amis#5459]
富文本编辑器，一放上就有两个js文件加载不出来
用的是npm下载的包
这个不知道咋解决
请大神们帮帮忙
<img width="721" alt="image" src="https://user-images.githubusercontent.com/110816705/192701351-5eb73cc0-1360-4fc4-8e8e-8d6048dae07e.png">
<img width="429" alt="image" src="https://user-images.githubusercontent.com/110816705/192701448-d0b3b7af-fd46-4812-bc29-606b1ad3cdab.png">

**Comment by iswangyinhao** [comment]
解决了
在main文件里面引入这两个文件解决了

import "amis/sdk/rest.js"
import "amis/sdk/tinymce.js"

**Comment by nwind** [comment]
vite 应该可以直接用 amis 组件，不需要用 sdk，除非是 vue 项目
