### ISSUE TITLE
json组件支持数据复制功能

### ISSUE THREAD

**Issue by qianxiaofendou** [baidu/amis#5461]
在调试的时候一般会开启debug调试功能，在amis2.2.0之前数据是静态展示，可以进行手动复制，方便数据的mock测试，但是2.2.0开启debug后，改成是使用json组件展示，优点是可以进行层级折叠，确实是方便了许多，但是不能复制数据了，对于需要复制数据二次mock的时候就很痛苦了，希望可以增加复制json的功能，多谢！

https://aisuda.bce.baidu.com/amis/zh-CN/components/json#form-%E4%B8%AD%E9%9D%99%E6%80%81%E5%B1%95%E7%A4%BA

**Comment by lurunze1226** [comment]
```
"debugConfig": {
      "enableClipboard": true,
      "displayDataTypes": true
}
```
debug区域支持配置的，可以加一个复制文本的按钮
