### ISSUE TITLE
事件动作里面actionType为alert时，不能自定义title

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#5462]
#### 是否关联于某个问题吗：
否

#### 预期的解决方案：
开放title属性

#### 其他可接受方案：
或者其他可以自定义title的办法

#### 任何附加信息：
![image](https://user-images.githubusercontent.com/37805363/192741255-fe91816a-c15b-4821-b53b-65020ccd96c2.png)

**Comment by rumunanfeng** [comment]
这么个简单的需求都不能支持一下吗？

**Comment by hsm-lv** [comment]
2.4.1版本将支持
