### ISSUE TITLE
amis表达式中支持用户自定义函数

### ISSUE THREAD

**Issue by genie88** [baidu/amis#5465]
#### 是否关联于某个问题吗：
amis表达式中支持用户自定义函数，例如 isImage 是用户自定义 实现的函数，通过import的方式引入进来。

```
import {isImage} from "@/utils"
...
{
  "type": "tpl",
  "tpl": "当前文件是图片",
  "visibleOn": "isImage(this.format)"
}
```

#### 预期的解决方案：
在页面的schema对象定义中，提供一个自定义用户context的对象，接收用户定义的函数，注入到表达式解析器中

**Comment by lurunze1226** [comment]
请参考[自定义过滤器](https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/data-mapping#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%87%E6%BB%A4%E5%99%A8)

**Comment by ranwawa** [comment]
自定义过滤器已经不推荐使用了....可以考虑把fomula暴露出来,添加自定义公式....找了下代码发现一个`registerFormulaExec`但是没用....

**Comment by StringKe** [comment]
@nwind @2betop 能否考虑一下这个需求，我看提供的 registerFormulaExec 基本没几个组件在用 FormualExec

**Comment by ranwawa** [comment]
你的邮件我已收到，查收后会尽快回复！：）
