### ISSUE TITLE
表单上传文件失败

### ISSUE THREAD

**Issue by thuglifezhx** [baidu/amis#547]
上传文件时一直提示文件上传失败，请问是什么原因？
不管有没有设置reciever都会提示上传失败。
```
{
  "type": "form",
  "name": "sample1",
  "controls": [
      {
          "name": "file",
          "type": "file",
          "label": "上传文件1",
        	"accept": ".csv",
        	"api": "http://.../importdata/powertcrpload"
      }
   ]
}
```
Response
`已成功上传0个文件，1个文件上传失败，重新上传失败文件`

**Comment by 2betop** [comment]
你要贴一下你的接口返回，一般都是接口没有按这样返回出错了

```
{
  status: 0,
  msg: '',
 data: {}
}
```

**Comment by thuglifezhx** [comment]
> 你要贴一下你的接口返回，一般都是接口没有按这样返回出错了
> 
> ```
> {
>   status: 0,
>   msg: '',
>  data: {
>     value: 'xxxx'
>   }
> }
> ```

还没到我的接口。。。就是上传到amis服务器？还没有提交表单，只是上传文件。

**Comment by 2betop** [comment]
文件上传，默认是选中文件就上传到 api 组件配置的 reciever, 默认值是 `/api/upload` ，这是默认行为，除非配置 asBlob 或者 asBase64 为 true 才会伴随 form 一起提交。

**Comment by thuglifezhx** [comment]
> 文件上传，默认是选中文件就上传到 api 组件配置的 reciever, 默认值是 `/api/upload` ，这是默认行为，除非配置 asBlob 或者 asBase64 为 true 才会伴随 form 一起提交。

请问存不存在跨域问题？？？

**Comment by thuglifezhx** [comment]
> reciever

请问reciever的默认值是/api/upload，但这个路径的服务器的是哪个呢？是我的服务器还是amis的服务器？如果要配置成我的服务器请问要怎么配置？

**Comment by 2betop** [comment]
你自己服务地址，直接写api地址

**Comment by thuglifezhx** [comment]
> 你自己服务地址，直接写api地址

我上传文件后控制台没有任何报错，network也没有显示我上传的文件。只是前端显示上传失败。能不能给个示例给我？

**Comment by thuglifezhx** [comment]
> 你自己服务地址，直接写api地址

reciever地址只支持https吗？

**Comment by 2betop** [comment]
重复了
