### ISSUE TITLE
表单上传文件一直失败

### ISSUE THREAD

**Issue by ghost** [baidu/amis#548]
不好意思，一直叨扰你，在这里跟您说声抱歉。但我的文件一直上传失败，找不到原因，也找不到其他示例。
这是我的json配置文件
```
{
    "type": "page",
    "body": {
        "title": "",
        "type": "form",
        "mode": "horizontal",
        "autoFocus": false,
        "controls": [
            {
                "type": "file",
                "name": "file",
                "label": "Fi111le",
                "maxSize": 1048576,
                "accept": ".csv",
                "reciever": "http://example.com:82/importdata/powertcrpload"
            }
        ],
        "submitText": null,
        "actions": []
    }
}
```
然后在[http://example.com:82/admin]这个页面进行上传文件时，出现以下错误
![image](https://user-images.githubusercontent.com/27938747/79183179-5740e200-7e43-11ea-85e4-cc3d061639bb.png)
而且控制台中没有输出任何信息。
但在postman中测试是没有任何问题的。
![image](https://user-images.githubusercontent.com/27938747/79183357-d7674780-7e43-11ea-99ae-0b0f10cf148c.png)
请问这是怎么回事？

**Comment by 2betop** [comment]
amis 是什么用法？

**Comment by thuglifezhx** [comment]
> amis 是什么用法？jssdk 还是 npm？网络请求发起了吗？如果没有发起，调用 amis 的时候的 fetcher 是否实现了？你可以本地跑一下 amis 的 examples，看看那个里面是否正常？

amis的通过npm实现的。然后我用amis已经实现Table和Chart，所以你说的这些应该都是没有问题的。

**Comment by 2betop** [comment]
网络请求发起了没有？

**Comment by thuglifezhx** [comment]
> 网络请求发起了没有？

没有发起，请问是哪里出了问题

**Comment by 2betop** [comment]
那要检查传进去的 fetcher 方法了。
