### ISSUE TITLE
用amis实现了表格输入和显示，如何实现打印功能，并可以自定义打印样式和数据。

### ISSUE THREAD

**Issue by zandb2009** [baidu/amis#5486]
#### 实现场景：
用amis实现了表格输入和显示，如何实现打印功能，并可以自定义打印样式和数据。

#### 存在的问题：
现在并没有这样的组件

```
code here...
```

**Comment by lhtuling** [comment]
这些不是主流功能  自己实现吧   不是所有需求官方都会处理的

Amis低代码前端框架交流群
【1群】717791727
【2群】721182449
