### ISSUE TITLE
crud点击分页后位置偏移

### ISSUE THREAD

**Issue by cmdares** [baidu/amis#5490]
#### 描述问题：

crud点击分页后，整个表格位置偏移！

#### 截图或视频：
1、下图是默认第一页显示效果
![image](https://user-images.githubusercontent.com/5292190/193416969-2ccf0fd6-a6e6-46fc-9bb0-d4971b2f5e16.png)

2、点击分页后，如下图所示，表格整体上移了
![image](https://user-images.githubusercontent.com/5292190/193416999-2769296b-2390-4a94-aaa1-6e880425856c.png)

在官方网站例子中，均出现这个现象。希望点击分页后，数据表格位置不要变化，近刷新表格内部数据即可，目前体验不好，希望抓紧修复。

感谢！

**Comment by lhtuling** [comment]
出现同样问题  会导致crud上面的内容被隐藏  然后无法滚动上去  用其他方式暂时解决了 应该是bug

**Comment by xianlinzhang** [comment]
出现同样问题，希望可以解决

**Comment by xianlinzhang** [comment]
Crud配置属性 autoJumpToTopOnPagerChange 为false，可以解决这个问题
