### ISSUE TITLE
amis-core npm 中不存在2.3.0版本

### ISSUE THREAD

**Issue by ltsj404** [baidu/amis#5497]
#### 描述问题：

<img width="610" alt="image" src="https://user-images.githubusercontent.com/38855041/194694377-9873dc65-98c1-4850-9750-95ea47439f30.png">

**Comment by bestGao** [comment]
taobao的源没有吧，用npm view看下就知道了，npm org的源是有的

**Comment by a15008282884** [comment]
npm  也没有2.30的版本

**Comment by lurunze1226** [comment]
https://www.npmjs.com/package/amis-core/v/2.3.0 npm官方源中有

**Comment by a15008282884** [comment]
> 
就是用的npm 官方源  安装也是提示2.3.0 版本安装失败
![11111](https://user-images.githubusercontent.com/34670198/194697769-5fd72dc3-4d99-4e51-9346-c9653695a0e9.png)

**Comment by a15008282884** [comment]
使用的npm官方源 也是提示不存在
![11222](https://user-images.githubusercontent.com/34670198/194697859-3c53e5c7-8179-46cc-a6a9-81e7cd7cad36.png)

**Comment by zhouqiang1983** [comment]
我在淘宝库点了个同步，现在有了。
