### ISSUE TITLE
sdk 2.3.0版本Log 实时日志组件ANSI 基本颜色不显示

### ISSUE THREAD

**Issue by zljun2010** [baidu/amis#5501]
#### 描述问题：

sdk 2.3.0版本Log 实时日志组件ANSI 基本颜色不显示

#### 截图或视频：

![image](https://user-images.githubusercontent.com/83194044/194734631-960b5010-5b37-4985-905d-a5d084b1c225.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
有问题的版本是 2.3.0。 在2.2.0版本能正常显示。

3. 粘贴有问题的完整 `amis schema` 代码：
```
							{
							  "type": "log",
							  "height": 600,
							  "disableColor": false,
							  "source": "http://192.168.13.22:5000/api/v1/svc/stream",
							  "operation": ["stop","showLineNumber","filter"]
							}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by GrenAnHao** [comment]
好兄弟确实 现在都2.6.0了还没修复这个问题
