### ISSUE TITLE
CRUD 如何将返回数据同步到上一级的Data中

### ISSUE THREAD

**Issue by sibo-git** [baidu/amis#5509]
#### 实现场景：
我想根据Crud统计一些数据信息，如何根据Crud 的接口返回的数据实时显示在其他界面上？

#### 存在的问题：
我想根据Crud统计一些数据信息，如何根据Crud 的接口返回的数据实时显示在其他界面上？

#### 当前方案：
我想根据Crud统计一些数据信息，如何根据Crud 的接口返回的数据实时显示在其他界面上？

**Comment by hsm-lv** [comment]
有两种思路，思路一：将crud和你说的那个界面组件放在同一个数据域下，例如都包裹在service里面，共享数据；思路二：监听crud的初始化事件，获取数据并通过setValue动作做赋值，具体的可以看下amis文档
