### ISSUE TITLE
【细节优化】CRUD 渲染器，加载数据时 Spinner 有失帧卡顿。

### ISSUE THREAD

**Issue by CareyToboo** [baidu/amis#551]
我看了官方DEMO也有这个问题。无论首次加载还是、换页时，均有该问题。没有细看源码不知道具体原因。加载数据Spinner卡顿，有点不流畅。希望大佬后期版本可以修复这个体验小问题。

**Comment by 2betop** [comment]
你说的是 云舍那个主题？

**Comment by CareyToboo** [comment]
就拿这个页面来看，https://baidu.github.io/amis/crud/table?page=4 默认主题。我用的是最新版chrome浏览器，看到的官网 加载数据 spinner 卡顿，与我自己代码 dev server 一致。有 2-3 帧左右，很细微。切换页数，可能看的明显点。先显示出来，再卡顿2-3帧，然后正常。是比较仔细看，才看得出来。你看看是这个情况吗？

**Comment by chenos** [comment]
猜测有两方面原因
1、loading 动画消失有延迟，内容先出来，动画再消失，这样的话，loading 会错位一下再消失，导致肉眼看起来有卡顿感，可以换个 loading svg 试试。
2、现在默认的 loading 动画生硬感比较强，尤其同时出现多个 loading 的时候会更明显，也会显得卡顿，折中的办法，可以 css 的方式把某些看起来多余的 loading 隐藏，效果会好一些
