### ISSUE TITLE
请问，amis怎么结合工作流引擎 flowable，实现工作流业务？

### ISSUE THREAD

**Issue by wuyongjun** [baidu/amis#5514]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by wuyongjun** [comment]
amis怎么使用 jbpm？

**Comment by nwind** [comment]
基于 react 开发
