### ISSUE TITLE
crud中定义的event事件动作actionType:reload无法到当前页

### ISSUE THREAD

**Issue by WuZezhang** [baidu/amis#5525]
"onEvent": {
                      "change": {
                          "actions": [
                              # {
                              #     "actionType": "reload",
                              #     "componentId": "card_service",
                              #     "args": {
                              #         "page": "${page}"
                              #     }
                              #     # "target": "crud"
                              #
                              # },
                          ]
                      }
                         },

**Comment by hsm-lv** [comment]
2.4.0及以上版本已支持，可以通过配置resetPage来控制是否重置页码

```json
{
  "type": "button",
  "id": "u:5d4983074436",
  "label": "刷新列表(get)-不重置页码",
  "onEvent": {
    "click": {
      "actions": [
        {
          "componentId": "u:1bb1c56c3ab1",
          "actionType": "reload",
          "args": {
            "resetPage": false
          }
        }
      ]
    }
  }
}
```

如果想要指定页码可以这样：

```json
{
  "type": "button",
  "id": "u:5d4983074436",
  "label": "刷新列表(get)-不重置页码",
  "onEvent": {
    "click": {
      "actions": [
        {
          "componentId": "u:1bb1c56c3ab1",
          "actionType": "reload",
          "data": {
            "page": "${page}"
          }
        }
      ]
    }
  }
}
```
