### ISSUE TITLE
能否自己定义国际化配置覆盖默认的国际化配置

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#5557]
#### 实现场景：
比如我对于弹窗的按钮文字，有一套自己的文字控制，我想覆盖掉默认的国际化，
默认en-US文件国际化确认按钮为
confirm: 'confirm'

我想修改成确认按钮为
confirm: 'OK'

#### 存在的问题：
参照多语言中的某些方法：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "body": [
      {
        "type": "input-text",
        "name": "name",
        "label": "姓名：",
        "en-US": {
          "label": "username: "
        }
      }
    ]
  }
}
```
只能把属性的内容替换为配置的国际化文字，但是没办法覆盖原有的国际化文件

#### 当前方案：

```
code here...
```

**Comment by lhtuling** [comment]
不知道你是不是要这个
感觉是的~~  
可以自己随便修改然后注册下  
![image](https://user-images.githubusercontent.com/44140500/195806062-8773adcb-cf86-4864-9331-c182e4553e32.png)

在配置好就行了
![image](https://user-images.githubusercontent.com/44140500/195806216-9a815647-8e85-446b-8474-90edbc428503.png)

**Comment by rumunanfeng** [comment]
> 不知道你是不是要这个 感觉是的~~ 可以自己随便修改然后注册下 ![image](https://user-images.githubusercontent.com/44140500/195806062-8773adcb-cf86-4864-9331-c182e4553e32.png)
> 
> 在配置好就行了 ![image](https://user-images.githubusercontent.com/44140500/195806216-9a815647-8e85-446b-8474-90edbc428503.png)
> 
> 参考连接 https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/i18n
> 
> Amis低代码前端框架交流群 【1群】717791727 【2群】721182449

感谢，但这种方式是不是相当于重新定义一个新语言？
我只想要对en-US的某些名称做修改，有没有更简便的方法呢？

**Comment by CheshireJCat** [comment]
```
"en-US": {
    "label": "username: "
}
```
这种写法适合在展示label的地方写，Dialog 组件暂时不支持配置确认和取消按钮，因为他支持自由度更高的 整个按钮配置，要实现你的效果，可以参考以下配置：
```
{
  "type": "page",
  "body": {
    "label": "点击弹框",
    "type": "button",
    "actionType": "dialog",
    "dialog": {
      "title": "弹框标题",
      "body": "这是一个弹框",
      "actions": [
        {
          "type": "button",
          "actionType": "cancel",
          "label": "取消",
          "en-US": {
            "label": "No No No"
          }
        },
        {
          "type": "button",
          "actionType": "confirm",
          "label": "确认",
          "en-US": {
            "label": "OK"
          },
          "primary": true
        }
      ]
    }
  }
}
```
