### ISSUE TITLE
可否增加一个自由布局元素可以自由拖拽定位

### ISSUE THREAD

**Issue by mackjieson** [baidu/amis#5579]
可否增加一个自由布局元素可以自由拖拽定位？AMIS已经很强大了，有这个功能就可以完美了。主要是开发想datav一类的大屏开发工具了

**Comment by wibetter** [comment]
amis-editor有一个自由容器，其直接子元素支持拖拽调整位置。能满足你的需求：
<img width="765" alt="image" src="https://github.com/baidu/amis/assets/11958920/0349bf40-6e3d-439a-9f93-37444f8d6c5e">
