### ISSUE TITLE
希望增加一个图片验证码的组件，可以每次渲染的时候刷新一下，现有组件不能满足

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#5580]
#### 是否关联于某个问题吗：
希望增加一个图片验证码的组件，可以每次渲染的时候刷新一下，现有组件不能满足

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by lurunze1226** [comment]
这种图片需要**服务端**生成，前端生成的没有意义，建议通过API + Image组件实现

**Comment by xiahao90** [comment]
已经找到方案

**Comment by zeroChen00** [comment]
图片组件引入后，不支持刷新链接啊

> 这种图片需要**服务端**生成，前端生成的没有意义，建议通过API + Image组件实现

**Comment by zeroChen00** [comment]
> 已经找到方案

老哥咋实现的，图片加载后连接就无法刷新了

**Comment by xiahao90** [comment]
{
  "type": "flex",
  'justify':"start",
  "items": [
    {
      "type": "input-text",
      "name": "code",
      "label": "验证码",
      "required": true,
      "placeholder": "请输入验证码",
      "size": "sm"
    },
    {
      "type": "hidden",
      "name": "uuid",
    },
    {
      "type": "service",
      "api": "/v1/imgcode",
      "id": "service-reload",
      "body": {
        "type":"tpl",
        "className":"m-t-sm m-l",
        "tpl":'<img src="${img}" class="pull-right" id="captcha" style="cursor: pointer;margin-top: 28px;">',
        "onEvent": {
          "click": {
            "actions": [
              {
                "componentId": "service-reload",
                "actionType": "reload"
              }
            ]
          }
        }
      }
    },
   ]
}
/v1/imgcode接口返回base64格式的验证码

**Comment by zeroChen00** [comment]
感谢老哥！我去试试

**Comment by zeroChen00** [comment]
> > 感谢老哥！我去试试
> 
> 你是做网络安全的吗？

是的，正在用fastapi-amis-admin写一个系统，有些自定义的地方有点难搞

**Comment by zeroChen00** [comment]
> > 感谢老哥！我去试试
> 
> 你是做网络安全的吗？

是的，同行老哥啊
