### ISSUE TITLE
windows环境下npm run dev报错

### ISSUE THREAD

**Issue by zhangyan-hub** [baidu/amis#559]
![image](https://user-images.githubusercontent.com/64058101/79825637-29701600-83cc-11ea-8ec3-753bee66d60c.png)
Doc.jsx编译报错： parser.typescript: Syntax Error: Hexadecimal digit expected.

**Comment by zhangyan-hub** [comment]
node 版本v10.16.3

**Comment by nwind** [comment]
现在应没了，另外最好使用 node v14
