### ISSUE TITLE
样式不起作用

### ISSUE THREAD

**Issue by wuxin2014** [baidu/amis#56]
用renderAmis渲染json，运行出来没样式？不知道如何引入样式

**Comment by RickCole21** [comment]
参考下这个库：https://github.com/fex-team/amis-admin

**Comment by RickCole21** [comment]
可以参考下这个库：https://github.com/fex-team/amis-admin

**Comment by RickCole21** [comment]
可以参考下这个库：https://github.com/fex-team/amis-admin
在`index.html`里引入样式文件：
```
<link rel="stylesheet" title="default" href="amis/lib/themes/default.css">
```

**Comment by wuxin2014** [comment]
index.html 是用webpack build之后 插件自动生成的

**Comment by wuxin2014** [comment]
明白了
