### ISSUE TITLE
useMobileUI 被render函数写死，无法被改变

### ISSUE THREAD

**Issue by luanwulin** [baidu/amis#5615]
#### 描述问题：

[amis-core中useMobileUI被固定](https://github.com/baidu/amis/blob/977c37ba55308755b9d37d2e62db4f72eea5c1df/packages/amis-core/src/index.tsx#L227)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
react

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

2.3.1

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤

![image](https://user-images.githubusercontent.com/16553854/197440688-0d82ba0d-6aa5-4255-969f-8eab8224d893.png)

在options中传值，也无法修改useMobileUI，在源码中typeof始终会返回一个字符串，相当于useMobileUI被写死了

**Comment by iambmg007** [comment]
Confirm code is 2733
