### ISSUE TITLE
Form表单提交后拿到的查询结果发送到Table组件

### ISSUE THREAD

**Issue by doufs** [baidu/amis#5626]
#### 实现场景：
Form表单组件提交后api接口返回的查询结果发送给Table组件，作为Table组件的source数据源

#### 存在的问题：
看文档中有Form提交后将返回内容发送到其他组件，但是demo是发送给其他组件的具体某个文本框类的，请问怎么将Form返回内容发送到Table组件作为Table组件的source数据源呢？Form表单提交的api返回的数据格式是
{
  "status": 0, 
  "msg": "", 
  "data": [
          {"id": 1, "name": "N1", "age": 10}, 
          {"id": 2, "name": "N2", "age": 11}
           ....]
}
这种符合Table组件数据要求的格式。

#### 当前方案：
暂无，不知道如何通过Form表单组件的reload属性来发送数据到Table组件

```
code here...
```

**Comment by hsm-lv** [comment]
有几种方式，一般table的source都绑定指定变量，可以通过将数据发送给table所在数据域，例如联动机制（https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/linkage#%E5%8F%91%E9%80%81%E6%8C%87%E5%AE%9A%E6%95%B0%E6%8D%AE）发送给service；或者通过事件动作的setValue更新指定组件的数据
