### ISSUE TITLE
官网挂了

### ISSUE THREAD

**Issue by darkmirrors** [baidu/amis#5628]
#### 描述问题：

https://aisuda.bce.baidu.com/amis/ 
官网挂了

#### 截图或视频：

![image](https://user-images.githubusercontent.com/1628795/197914147-06a7e444-4d6a-48c9-b1fb-b998caf0db50.png)

#### 如何复现（请务必完整填写下面内容）：

f12

**Comment by lurunze1226** [comment]
可以先使用[github站点](https://baidu.github.io/amis/zh-CN/components/index)

**Comment by hwy1782** [comment]
我这边能打开
