### ISSUE TITLE
表单组件去掉边框后手动加上actions也无法渲染提交等按钮

### ISSUE THREAD

**Issue by doufs** [baidu/amis#5644]
#### 描述问题：

Form表单组件加上"wrapWithPanel": false去掉边框后，手动加上actions也无法渲染提交按钮，请问表单只能带边框才能正常使用吗？那个边框有点多，而且间距默认也稍微有点大

#### 截图或视频：

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/34061363/198487857-0ecca1de-6684-4a62-a274-1759197f44f0.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis版本：2.3.1  最新版2.3.2.beta版本也是一样

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "title": "表单",
    "wrapWithPanel": false,
    "body": [
      {
        "type": "input-text",
        "name": "email",
        "label": "邮箱"
      },
      {
        "type": "input-password",
        "name": "password",
        "label": "密码"
      }
    ],
    "actions": [
      {
        "type": "submit",
        "label": "登录",
        "primary": true
      },
      {
        "type": "action",
        "actionType": "dialog",
        "label": "登录须知",
        "dialog": {
          "title": "登录须知",
          "body": "登录须知"
        }
      },
      {
        "type": "button",
        "label": "百度一下",
        "url": "https://www.baidu.com/"
      }
    ]
  }
}
```

4. 操作步骤
直接渲染一个界面即可，上面用的是官网的一个demo

**Comment by hsm-lv** [comment]
wrapWithPanel就是关闭外面包裹的，包含footer，因此如果关闭情况下，你只能自定义按钮放在form的body里面了
