### ISSUE TITLE
Picker开启内嵌模式卡死，选项无法从下往上选

### ISSUE THREAD

**Issue by BushyyZEus** [baidu/amis#5646]
#### 描述问题：

Picker 选择框开启内嵌模式编辑器卡死
Picker选择框开启内嵌模式后，预览中选项只能从上往下选，从下往上选则崩溃卡死
改变joinvalue为true或false时，无法配置弹窗内容

#### 截图或视频：

![A1% OYSE760 PNUBO7R `O](https://user-images.githubusercontent.com/69668719/198496257-95931458-eff6-49db-9b5a-97d2dbd5b866.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.3.0

3. 粘贴有问题的完整 `amis schema` 代码：
官方文档中Picker内嵌模式代码

4. 操作步骤
直接复制文档中picker内嵌模式代码到官方编辑器中，编辑器卡死

给Picker的pickerSchema配置选项的分页接口，开启多选，配好valuefiled和labelfield，开启内嵌模式，编辑器卡死，或者内嵌模式中，预览中选项只能从上往下选，从下往上选则崩溃卡死

**Comment by lurunze1226** [comment]
`2.4.0`应该fix了
