### ISSUE TITLE
请教下咱们https://baidu.github.io/amis/docs/renderers/crud-list这个地址里面实时预览的功能怎么实现的呢

### ISSUE THREAD

**Issue by dxfstart521** [baidu/amis#565]
请教下咱们https://baidu.github.io/amis/docs/renderers/crud-list这个地址里面根据json配置可以实时预览页面的功能怎么实现的呢

**Comment by 2betop** [comment]
因为用的 react，把 json 配置转成 react 里面的 props，就自动可以了。

**Comment by dxfstart521** [comment]
如何实现实时修改，预览呢？这块是直接操作DOM更新了把

**Comment by 2betop** [comment]
React 的功能，没直接操作 dom，修改了 react 的props。

**Comment by dxfstart521** [comment]
https://baidu.github.io/amis/docs/renderers/form/editor,没太明白editor里面的json怎么实时同步到页面呢？这个文档没有说明呢，https://baidu.github.io/amis/docs/renderers/Form/FormItem跳转更多配置页面也打不开呢

**Comment by 2betop** [comment]
正确的链接应该是：

https://baidu.github.io/amis/docs/renderers/form/editor
https://baidu.github.io/amis/docs/renderers/form/formitem

AMIS 配置项实时预览不是 amis 能配置出来的，文档页面是自己加了些特殊的代码逻辑才可以及时编辑预览。具体逻辑就是前面说的，json 解析后，丢给 React 的props。

**Comment by dxfstart521** [comment]
感谢。不过用这个两个地址访问我这边是404 呢
![image](https://user-images.githubusercontent.com/31570901/80493233-b8b29600-8997-11ea-8a1e-a00fe89a0083.png)
![image](https://user-images.githubusercontent.com/31570901/80493272-c536ee80-8997-11ea-89c4-dc929b2ad2dc.png)

**Comment by 2betop** [comment]
发现问题了，gh-pages 里面的文件夹是大写的 Form, 而链接地址是小写的 form，导致了 404.

**Comment by 2betop** [comment]
现在是一直的了，重新从这里面进 https://baidu.github.io/amis/

**Comment by dxfstart521** [comment]
好的。感谢。
![image](https://user-images.githubusercontent.com/31570901/80565101-3fac5080-8a22-11ea-90f2-302e3fe3f8b1.png)

咱们amis文档里面有实时json预览的这部分，有源码吗？想学习一下哈

**Comment by 2betop** [comment]
https://github.com/baidu/amis/blob/master/examples/components/Play.jsx

**Comment by dxfstart521** [comment]
请教下，咱们这个代码里面renderPreview的方法在哪里定义的呢？我在整个amis工程里面没有找到呢?求这个编辑器实时预览的使用文档.

**Comment by 2betop** [comment]
https://github.com/baidu/amis/blob/master/examples/components/Play.jsx#L179

**Comment by dxfstart521** [comment]
![image](https://user-images.githubusercontent.com/31570901/80596131-71d8a500-8a58-11ea-9a1d-6e0e54ef104f.png)

https://github.com/baidu/amis/blob/master/src/index.tsx
大佬请教下，Editor的组件没有对外export，我在业务里面想针对这个Editor和preview进行自定义实现一个编辑预览组件，这块amis可以对Editor组件进行导出吗

**Comment by 2betop** [comment]
通过路径可以 require 到，这个文件太大了，默认没有同步 require
