### ISSUE TITLE
事件动作中的循环执行动作没有携带数据

### ISSUE THREAD

**Issue by YouthofTime** [baidu/amis#5654]
#### 描述问题：
官网文档事件动作中的循环案列，点击循环发送请求按钮，name和age为空

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

![屏幕截图 2022-10-31 150452](https://user-images.githubusercontent.com/53092143/198953326-3dc57a35-bb2b-4ec9-bdd3-70b78acfe9a6.jpg)

#### 如何复现（请务必完整填写下面内容）：

1. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "wrapWithPanel": false,
    "data": {
      "loopName": "loopData",
      "loopData": [
        {
          "name": "lv",
          "age": "19"
        },
        {
          "name": "xj",
          "age": "21"
        }
      ]
    },
    "body": [
      {
        "type": "button",
        "label": "循环发送两次请求，且每次携带了循环的数据",
        "level": "primary",
        "onEvent": {
          "click": {
            "actions": [
              {
                "actionType": "loop",
                "args": {
                  "level": 3,
                  "loopName": "${loopName}"
                },
                "children": [
                  {
                    "actionType": "ajax",
                    "args": {
                      "api": "/amis/api/mock2/form/saveForm?name=${name}&age=${age}"
                    }
                  }
                ]
              }
            ]
          }
        }
      }
    ]
  }
}
```

**Comment by hsm-lv** [comment]
> #### 描述问题：
> 官网文档事件动作中的循环案列，点击循环发送请求按钮，name和age为空
> 
> 请用一段清晰简洁的文字描述问题是什么...
> 
> #### 截图或视频：
> ![屏幕截图 2022-10-31 150452](https://user-images.githubusercontent.com/53092143/198953326-3dc57a35-bb2b-4ec9-bdd3-70b78acfe9a6.jpg)
> 
> #### 如何复现（请务必完整填写下面内容）：
> 1. 粘贴有问题的完整 `amis schema` 代码：
> 
> ```
> {
>   "type": "page",
>   "body": {
>     "type": "form",
>     "wrapWithPanel": false,
>     "data": {
>       "loopName": "loopData",
>       "loopData": [
>         {
>           "name": "lv",
>           "age": "19"
>         },
>         {
>           "name": "xj",
>           "age": "21"
>         }
>       ]
>     },
>     "body": [
>       {
>         "type": "button",
>         "label": "循环发送两次请求，且每次携带了循环的数据",
>         "level": "primary",
>         "onEvent": {
>           "click": {
>             "actions": [
>               {
>                 "actionType": "loop",
>                 "args": {
>                   "level": 3,
>                   "loopName": "${loopName}"
>                 },
>                 "children": [
>                   {
>                     "actionType": "ajax",
>                     "args": {
>                       "api": "/amis/api/mock2/form/saveForm?name=${name}&age=${age}"
>                     }
>                   }
>                 ]
>               }
>             ]
>           }
>         }
>       }
>     ]
>   }
> }
> ```

最新版本没有复现

**Comment by YouthofTime** [comment]
现在有了
