### ISSUE TITLE
amis 的分页无法使用

### ISSUE THREAD

**Issue by zhongtaoW** [baidu/amis#5675]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by zhongtaoW** [comment]
![image](https://user-images.githubusercontent.com/105036431/199429818-202a99ef-0db2-4893-98ea-eae47ee84164.png)
点击页码没有反应 怎么把点击的页码数当作参数传到url 然后重新发送请求

**Comment by sheeepli** [comment]
文档里有一个 onPageChange 的属性应该是你要的东西

**Comment by zhongtaoW** [comment]
> 文档里有一个 onPageChange 的属性应该是你要的东西

具体怎么配呢 我试了这个 onPageChange 但是无效

**Comment by sheeepli** [comment]
render({
  type: 'pagination',
  // ... 其他属性 
  // 其他属性与官方 demo 一致，额外添加下面这段代码，需要在自己的项目中写，在 demo 中使用会报错。
  // 毕竟 demo 要 json，只能写字符串，不能写函数，而源码中没有对这个传入的内容进行解析。
  onPageChange: function(page: number, perPage: number){console.log(page, perPage)}
})

**Comment by ezingme** [comment]
> render({ type: 'pagination', // ... 其他属性 // 其他属性与官方 demo 一致，额外添加下面这段代码，需要在自己的项目中写，在 demo 中使用会报错。 // 毕竟 demo 要 json，只能写字符串，不能写函数，而源码中没有对这个传入的内容进行解析。 onPageChange: function(page: number, perPage: number){console.log(page, perPage)} })

不能再json中用，不方便
