### ISSUE TITLE
sdk 2.0版本后自己加的样式类不生效的问题!

### ISSUE THREAD

**Issue by lfzfrj88** [baidu/amis#5684]
#### 描述问题：

**sdk2.0以后, 可能css样式做了大的升级变化, 导致className里写的样式类,不生效或错乱! 之前也有人提过issues的
而在1.10.2是正常的!**
如下截图:
1. 想要的效果同1.10.2, 删除按钮文本红色, 含外边框, 有左外边距, 而2.3.1及2.4.0样式都变了
2. bug: CRUD顶部工具栏的, 切换filter按钮在2.4.0尺寸变小了,且有了边框

**能不能在版本升级时保留向下兼容性? 感觉从2.0起后面的版本样式这块问题较多呀, 这个**

#### 截图或视频：
**1.10.2下表现**
![image](https://user-images.githubusercontent.com/108504969/199648025-95fd04cf-a15a-4430-a69d-19844c1620a9.png)
![image](https://user-images.githubusercontent.com/108504969/199648301-db0e6d23-e059-42bc-a08c-866a8facbe76.png)

**2.3.1下表现**
![image](https://user-images.githubusercontent.com/108504969/199648104-f8a7c39c-ff34-41d9-81ce-782e90fe16e5.png)
![image](https://user-images.githubusercontent.com/108504969/199648310-447c9339-aa74-437b-8b90-1d04dd6409a5.png)

**2.4.0下表现**
![image](https://user-images.githubusercontent.com/108504969/199648552-b838c72f-c225-47fb-8905-57e46053f2d1.png)
![image](https://user-images.githubusercontent.com/108504969/199648649-faa62fd6-6c5f-4d0c-9586-7d6b3382f773.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

4. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.10.2  2.3.1   2.4.0
5. 粘贴有问题的完整 `amis schema` 代码：
```
{
   "type": "page",
   "body": [
      {
         "type": "button",
         "label": "编辑",
         "level": "link",
         "className": "text-primary b"
      },
      {
         "type": "button",
         "label": "删除",
         "level": "link",
         "className": "text-danger m-l-lg b"
      }
   ]
}
```
```
"type":"crud",
...省略
"headerToolbar": [
      {
         "type": "filter-toggler"
      }
]
...省略后面
```

6. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lfzfrj88** [comment]
哎,2.0以上的样式问题多多,  官方没人管呀
还是退回到1.10.2用吧

**Comment by Chen-Wendong** [comment]
2.0开始就有问题，sdk 没人修复，1.9还可以！ @nwind 

https://github.com/baidu/amis/issues/5370

https://github.com/baidu/amis/issues/5495

https://github.com/baidu/amis/issues/5553 

https://github.com/baidu/amis/issues/5064
