### ISSUE TITLE
【安全建议】接口加密

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#5688]
#### 是否关联于某个问题吗：
鉴于市场对安全要求越来越高，建议给post接口增加AES等类似的加密请求方式，让请求与返回的数据进行加密传输。

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by luanwulin** [comment]
https就完事了，，前端aes基本没啥用

**Comment by nwind** [comment]
前面两位的回答是正解
