### ISSUE TITLE
问一下表单里的Image图片上传功能

### ISSUE THREAD

**Issue by Actionpeak** [baidu/amis#569]
receiver字段：文档中描述为 “默认 /api/upload 如果想自己存储，请设置此选项”

这边我想要自己存储，post接口实现好之后，对返回值有些疑惑，返回status msg data字段后
request和response打通，但提示系统错误，按钮还是重新上传。

所以想问一下，这个post接口的响应值的格式应该是什么

**Comment by 2betop** [comment]
```
{
  status: 0,
  msg: '',
  data: {}
}
```

**Comment by Actionpeak** [comment]
OK，明白了，我这边应该主要是data里的value字段没有，所以报错的。
感谢！

**Comment by Actionpeak** [comment]
补充一个问题还是image相关：
当上传完成后，上传图片的区域会有三个按钮（查看大图，删除，文件名）
这三个按钮的事件是在哪里控制的，或者 查看大图的功能是什么字段控制的

我在文档中没找到，尝试了popOver，但是popOver好像只支持static-image

**Comment by 2betop** [comment]
https://baidu.github.io/amis/form/static
左上角可以查看源码

**Comment by Actionpeak** [comment]
不不不，那个里只有static-image的放大
我想问的是图片上传组件image：上有三个按钮（放大，删除，源文件名）中的放大按钮
我按static-image添加了enlargeAble或popOver都不行，放大按钮点击没有响应
想问的就是这个放大按钮（上传图片Image组件中）的响应是哪里控制的

**Comment by 2betop** [comment]
版本问题？这个功能是自带的，不用任何配置就没能弹出

**Comment by Actionpeak** [comment]
用的是快速开始示例里html引用https://houtai.baidu.com/v2/jssdk的模式
确实无法弹出，鼠标放上去显示的是blob图片链接
并且我可以右键打开链接，但点击无响应
可能是html或者chrome浏览器问题？

**Comment by 2betop** [comment]
是我那代码有问题，在 jssdk 模式下没有正确弹出，主要是弹出容器不对。今天晚些时候会更新上线，或者你直接改用 npm 里面的 sdk 版本。用 amis@1.0.11-beta.29
