### ISSUE TITLE
vue3+vite项目 The renderer with name "remark" has already exists

### ISSUE THREAD

**Issue by kiananekocharm** [baidu/amis#5697]
#### 描述问题：
vue3+vite创建项目后，运行时报错factory.js:53 Uncaught Error: The renderer with name "remark" has already exists, please try another name!

#### 截图或视频：

![image](https://user-images.githubusercontent.com/56387127/199909661-de141118-cc11-4097-93af-e03714d62103.png)
![image](https://user-images.githubusercontent.com/56387127/199909708-adc089c4-f514-4844-b430-03c545cf0996.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm安装

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.4.0，存在该问题，使用1.10.0问题消失，但amis-editor会提示colorPicker is not supported

4. 粘贴有问题的完整 `amis schema` 代码：

5. 操作步骤
创建项目npm安装后构建

**Comment by linsicong000** [comment]
react+vite 同出现这个问题 amis 版本 2.7.3-beta.0，amis-editor 版本 5.2.4-beta.31

**Comment by 2betop** [comment]
跟这个关联，这个先关了
