### ISSUE TITLE
tinymce 编辑器上传图片时默认是 GET 请求

### ISSUE THREAD

**Issue by PengXing** [baidu/amis#570]
tinymce 编辑器上传图片时默认是 GET 请求，导致出现 405 错误，如下

```js
const schema = {
  name: 'content',
  type: 'rich-text',
  vendor: 'tinymce',
  reciever: '/api/tool/uploadImage',
  videoReciever: 'tinymce',
  size: 'lg',
  label: '页面内容',
}
```

可以通过设置 `reciever: 'post:/api/tool/uploadImage'` 来避免这个问题，但是我们可以做到更进一步

将 `api.ts` 的函数 `buildApi ` 判断 `method` 的地方修改一下 https://github.com/baidu/amis/blob/master/src/utils/api.ts#L56

如果 `data` 是 `Blob`, `FormData`, `ArrayBuffer` 时，`method` 默认是 `POST`，其他情况都默认为 `GET`，这样也许更合理一些

（即使 GET 请求也能在 body 里携带内容，但这并不符合规范）

**Comment by 2betop** [comment]
直接在这改了 https://github.com/baidu/amis/commit/58bb7bfeb71f8bcaf2f37ef213a5130105c07082

**Comment by PengXing** [comment]
不过，改这里治标，改 `api.ts` 更彻底

**Comment by PengXing** [comment]
在这个 ISSUE 里补充一个小问题，RichText.ts 和 Form/Image.ts 上传图片 要求的服务端返回的字段不一致，一个是 `link`，一个是 `url`，会带来一些困扰

- RichText.ts https://github.com/baidu/amis/blob/master/src/renderers/Form/RichText.tsx#L184
- Form/Image.ts https://github.com/baidu/amis/blob/master/src/renderers/Form/Image.tsx#L758

**Comment by 2betop** [comment]
平台的 frolaEditor 的版本要求的是 link，我这是跟原来的IDE格式保持一致了，不过倒是可以都支持以下。

**Comment by PengXing** [comment]
fixed at https://github.com/baidu/amis/commit/f226fc24445f32185a6db7f01f210bb931b9b735
