### ISSUE TITLE
是否可以添加关闭默认弹出toast的配置

### ISSUE THREAD

**Issue by joker77877** [baidu/amis#5709]
#### 是否关联于某个问题吗：
是否可以添加关闭默认弹出toast的配置

#### 预期的解决方案：
希望添加关闭默认弹出toast的配置

#### 其他可接受方案：
希望添加关闭默认弹出toast的配置

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by cnbattle** [comment]
> **事件动作干预是指执行完当前动作后，干预所监听事件默认处理逻辑和后续其他动作的执行。通过preventDefault、stopPropagation分别阻止监听事件默认行为和停止下一个动作执行。**

https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E4%BA%8B%E4%BB%B6%E5%8A%A8%E4%BD%9C%E5%B9%B2%E9%A2%84

参考 下面 是关闭 form submit 默认的toast
```
                type: 'form',
                onEvent: {
                    submitSucc: {
                        actions: [
                            {
                                preventDefault: true,
                            }
                        ]
                    },
                },
```
