### ISSUE TITLE
InputNumber将输入框点击增加减少按钮给去掉

### ISSUE THREAD

**Issue by younglifestyle** [baidu/amis#5723]
#### 实现场景：
![image](https://user-images.githubusercontent.com/19261307/200720815-15785223-1901-458f-accc-e917219d456d.png)
想将数字输入框这个点击样式去掉

#### 存在的问题：
使用最新的版本测试，showSteps字段不起作用，请问有方法能去掉这个样式吗

我把InputNumber放入property属性表中使用，有这个样式会导致鼠标移上去后，间距变化，造成界面抖动

```
code here...
```

**Comment by sheeepli** [comment]
![image](https://user-images.githubusercontent.com/28035703/200725336-3baa0a03-f74d-48a9-928a-8e4175622101.png)
样式被覆盖了，你可以重新写一个样式覆盖掉，或者等官方修复这个问题

**Comment by younglifestyle** [comment]
> ![image](https://user-images.githubusercontent.com/28035703/200725336-3baa0a03-f74d-48a9-928a-8e4175622101.png) 样式被覆盖了，你可以重新写一个样式覆盖掉，或者等官方修复这个问题

官方的 v2.4.1-beta.0 应该是解决了这个问题。

感谢回复，tks
