### ISSUE TITLE
button组件禁用状态，块状样式下展示异常

### ISSUE THREAD

**Issue by Jarod-Xie** [baidu/amis#5732]
#### 描述问题：

button组件禁用状态，块状样式下展示异常

#### 截图或视频：

![image](https://user-images.githubusercontent.com/27668637/201037255-dd8257ab-3450-4a12-a3b8-31daa32950cf.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官方文档中的demo

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
官网使用的版本

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "label": "弹个框",
    "type": "button",
    "actionType": "dialog",
    "disabled": true,
    "block":true,
    "dialog": {
      "title": "弹框",
      "body": "这是个简单的弹框。"
    }
  }
}
```

**Comment by sheeepli** [comment]
block 时的 loading 状态也是异常的

样式冲突。当 disabled 时，按钮会渲染成 div，外加上 block 属性，失去了 flex-inline 的及其附加属性给到的居中效果导致的。

**比较好奇的是为什么要渲染成 div。**

**Comment by qkiroc** [comment]
新版已无问题
