### ISSUE TITLE
表单验证问题

### ISSUE THREAD

**Issue by whitekyo** [baidu/amis#574]
{
                            "type": "text",
                            "name": "title",
                            "placeholder": "请输入资讯标题,长度在450个字符以内...",
                            "label": "资讯标题",
                            "validations": {
                                "notEmptyString": true,
                                "maxLength": 450
                            }
                        },

我同时设置了非空和长度校验，长度校验生效，非空没有生效

**Comment by 2betop** [comment]
可能是这个名字没取好，notEmptyString 其实是不允许输入全空格，如果你想要必填，还得额外加个 required: true 的属性。

![image](https://user-images.githubusercontent.com/2698393/81402232-97099980-9163-11ea-8d0a-ab077596ffca.png)
