### ISSUE TITLE
公式编辑器不支持变量的动态获取、amis内置函数目前没办法隐藏等问题

### ISSUE THREAD

**Issue by EricLoveCode** [baidu/amis#5745]
#### 描述问题：

背景：目前运营一些文本的编辑场景，需要使用变量和文案的组合形式。目前amis的编辑器中只有公式编辑器比较贴合使用的场景。但同时也存在一些问题，导致目前无法使用。

1.公式编辑器目前不支持变量的动态获取，无法支持灵活的配置。
2.amis内置函数目前没办法去掉，因函数的定义与amis内置的函数不一样。
3.混合模式下，目前支持输入文本和输入公式两种格式的值，当输入公式时值会自动用 "${"和"}" 包裹 。如果不是这种格式则认为是输入普通的字符串。但是有些特殊场景中（变量类型不一致），我们需要同时使用"${"和"}"、"#{"和"}"等进行包裹。

#### 预期的解决方案：
问题1：希望能够支持api动态获取变量
问题2：希望能增加开关属性，根据场景自由选择
问题3：希望能在输入公式时，默认使用$,支持自定义。

#### 其他可接受方案：

可以提供一种文本编辑器

#### 截图或视频：

预期的效果图：
![image](https://user-images.githubusercontent.com/103913714/201307124-27d16a6c-2866-44c0-aecd-066999886f8a.png)
目前的效果图：
![image](https://user-images.githubusercontent.com/103913714/201309938-1d004b51-9a25-49c1-ba76-58fe7f044dd4.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "body": [
      {
        "type": "input-formula",
        "name": "formula",
        "label": "公式",
        "evalMode": false,
        "value": "my name is #{name}",
        "variables": [
          {
            "label": "表单字段",
            "children": [
              {
                "label": "文章名",
                "value": "name",
                "tag": "文本"
              },
              {
                "label": "作者",
                "value": "author",
                "tag": "文本"
              },
              {
                "label": "售价",
                "value": "price",
                "tag": "数字"
              },
              {
                "label": "出版时间",
                "value": "time",
                "tag": "时间"
              },
              {
                "label": "版本号",
                "value": "version",
                "tag": "数字"
              },
              {
                "label": "出版社",
                "value": "publisher",
                "tag": "文本"
              }
            ]
          },
          {
            "label": "流程字段",
            "children": [
              {
                "label": "联系电话",
                "value": "telphone"
              },
              {
                "label": "地址",
                "value": "addr"
              }
            ]
          }
        ]
      }
    ]
  }
}

4. 操作步骤
现有功能不支持

**Comment by KillenMr** [comment]
使用 service 组件包裹可以实现动态获取
