### ISSUE TITLE
请问editor组件如何配置amis的json schema

### ISSUE THREAD

**Issue by otaboqq** [baidu/amis#5750]
我想要在json代码编辑器里面能够提示amis的json结构

但是我在editor组件的描述里没找到怎么配置

**Comment by wibetter** [comment]
通过配置$schemaUrl来用来给代码编辑模式提供属性提示信息，默认会使用amis/schemas.json。然后每个组件的plugin可以通过$schema属性来设置当前组件的提示词信息（比如：/schemas/FlexSchema.json）：
<img width="604" alt="image" src="https://github.com/baidu/amis/assets/11958920/0cd480e7-d634-4baa-b6d1-aae217c02137">
