### ISSUE TITLE
请教一下一些使用姿势

### ISSUE THREAD

**Issue by laglangyue** [baidu/amis#5751]
### 实现场景与问题：
请教一下使用姿势问题
1. 安装官网示例我下载了sdk，和schema.json文件
但是我不知道如何使用schema.json文件，或者说如何引用外部某个位置下的schema.json文件；
假设后端同学完全忘记了如何使用js的情况下的，看官网示例很难摸索处理如何引用schmea.json
我是回到github才发现有amis-admin这个项目，最终才知道怎么入门，感觉在官网是不是可以提供一些说明，对一些 相关项目做一些说明。

2. 当前amis-editor如何使用，好像不能导出。

**Comment by 17** [comment]
一般用不着 schmea.json 。
怎么使用可以看[官网](https://baidu.github.io/amis/zh-CN/docs/start/getting-started#sdk) SDK 这部分。
SDK 使用最简单，amis-editor 直接复制页面的 JSON 就可以使用了。
