### ISSUE TITLE
[ERROR] parser.0: The language "schema" has no grammar.

### ISSUE THREAD

**Issue by luolisong1996** [baidu/amis#5762]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
w10系统在cmd运行npm i --legacy-peer-deps 后 
运行npm start 编译报错 [ERROR] parser.0: The language "schema" has no grammar.，启不启来。Mac端无问题
![image](https://user-images.githubusercontent.com/49147408/201871282-8bc73f84-b2d6-45be-bbc0-324e56e594a6.png)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by wujieli0207** [comment]
markdownPlugin.ts 文件的下面这样正则在 windows 上没有匹配出 schema 的内容，猜测可能是换行符导致的，但尝试了增加 \r\n 还是没有效果，不知道有没有大佬知道方案

/```(schema|html)(?::(.*?))?\n([\s\S]*?)```/g
