### ISSUE TITLE
amsi api 返回结果只能是json吗？

### ISSUE THREAD

**Issue by Qiuqiu0505** [baidu/amis#5769]
api 方式调用后端接口，接口返回数据不是json接口。页面显示Response should be JSON.
请问amsi支持非json的response 吗？如果有的话，麻烦给下使用方法吧，谢谢。

**Comment by 17** [comment]
修改 responseAdaptor

**Comment by Qiuqiu0505** [comment]
> 

谢谢，这个我看到,已经解决了，谢谢
还有个问题：amsi api 调用的后端接口时，post接口 请求参数为 object arraylist, 但是想通过某个参数值过滤object.请问有什么好的建议吗？以下是设置参数的部分代码：


`
                 data: {
                        apiName: '${apiNameUpdate}',
                        hosts: '${hosts}',
                        urls: '${urlsUpdate}',
                        'upstream.upstreamName': '${upstreamUpdate}',
                        'upstream.target': '',
                        'plugins': [
                          {
                            pluginName: 'unicorn-auth',
                            enable: '${tokenCheckboxType}',
                            extField: '',
                          },
                          {
                            pluginName: 'unicorn-doorkeeper',
                            enable: '${doopkeeperCheckboxType == 1?true:false}',
                            extField: '',

                          },
                          {
                            pluginName: 'unicorn-signature',
                            enable: '${signatureSwitchType == 1?true:false}',
                            extField: '',
                          },
                          {
                            pluginName: 'unicorn-basic-auth',
                            enable: '${basicAuthType == 1?true:false}',
                            extField: '',
                          },
                          {
                            pluginName: 'unicorn-basic-auth',
                            enable: '${basicAuthSwitch2Type == 1?true:false}',
                            extField: '',
                          },
                        ],
                      },

`

**Comment by 17** [comment]
请求适配器
https://baidu.github.io/amis/zh-CN/docs/types/api

**Comment by Qiuqiu0505** [comment]
> https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E9%80%82%E9%85%8D%E5%99%A8

谢谢。我已经解决了。
