### ISSUE TITLE
fork项目后无法根据readme文档启动amis

### ISSUE THREAD

**Issue by tongchong** [baidu/amis#5776]
#### 实现场景：
启动amis方案1操作步骤如下:
1、lerna bootstrap --hoist
2、npm i --legacy-peer-deps
3、npm run build --workspace amis-formula
4、npm start

<img width="950" alt="屏幕快照 2022-11-18 下午5 04 44" src="https://user-images.githubusercontent.com/25954437/202663797-4609cfad-a85c-4c23-9691-6e9c75abbe5d.png">

启动amis方案2操作步骤如下：
npm i --legacy-peer-deps
npm start
错误同上
<img width="950" alt="屏幕快照 2022-11-18 下午5 04 44" src="https://user-images.githubusercontent.com/25954437/202663797-4609cfad-a85c-4c23-9691-6e9c75abbe5d.png">

请问是否是我lerna安装有问题呢？
我的lerna版本为6.0.3，node版本为14.20.1，npm版本为7.24.2。

amis-editor-demo根据README.md操作同样无法访问。
操作步骤如下：
npm i 安装依赖
npm start 开服务
npm run dev 开始编译，等编译出现时间信息后刷新页面看效果，页面空白
<img width="841" alt="屏幕快照 2022-11-18 下午5 12 52" src="https://user-images.githubusercontent.com/25954437/202665393-23507c19-70b0-47ea-97a6-2bd7768db8ea.png">

vs code编译如下图：
图1: npm run dev
<img width="1107" alt="屏幕快照 2022-11-18 下午5 10 30" src="https://user-images.githubusercontent.com/25954437/202665475-cfa5f99b-668b-4996-ab6c-0ff0634f78c9.png">

图2: npm start
<img width="1097" alt="屏幕快照 2022-11-18 下午5 14 01" src="https://user-images.githubusercontent.com/25954437/202665792-e055fbb4-88ab-4446-8834-624d9a11634f.png">

请问是什么原因呢？

谢谢大佬！

**Comment by Planet-77** [comment]
➕1

**Comment by EvanZheng11** [comment]
+1

**Comment by xukeke520** [comment]
+1

**Comment by nwind** [comment]
windows?

**Comment by tongchong** [comment]
> windows?

mac

**Comment by tongchong** [comment]
之前可能是因为某个包现在已经下架了，npm下载不了
