### ISSUE TITLE
react18中mobx版本与amis的无法兼容怎么处理

### ISSUE THREAD

**Issue by mfkwgizhoujian** [baidu/amis#5787]
#### 实现场景：
项目准备使用react18，amis中使用的mobx版本太低，装上高版本的mobx启动后控制台会出现错误

#### 存在的问题：
控制台会报这个错误：There are multiple, different versions of MobX active
怎么解决mobx兼容性问题呢？

**Comment by nwind** [comment]
暂时不会升级 mobx 版本，先用 `npm i --legacy-peer-deps` 支持旧版安装，目前 amis 项目用的就是 react 18

**Comment by StringKe** [comment]
watch
