### ISSUE TITLE
【Toast 轻提示】能否优化一下

### ISSUE THREAD

**Issue by Tomao2014** [baidu/amis#5793]
你好！

Toast 轻提示组件，是在是太“轻”了，以至于弹出提示时，直接被忽视（难以发现，特别是白色的背景下）。

#### 预期的解决方案：
整个组件调大一些，图标也大一些

比如：https://semi.design/zh-CN/feedback/toast

![image](https://user-images.githubusercontent.com/46468204/203281072-947db51d-0a77-40c5-9b02-1b69005aae30.png)

**Comment by sheeepli** [comment]
这不是可以通过自己修改样式达到效果吗

**Comment by lhtuling** [comment]
+1 
一个css样式自己就搞定了！
不要所有都依赖官方搞定   你会等到天荒地老的！！！
