### ISSUE TITLE
报错：Unexpected template string expression  no-template-curly-in-string

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#580]
"tabsLabelTpl":"接口 ${index|plus}",
此行报错，网上查询应该为`接口 ${index|plus}`
但是这样写又不符合规范

**Comment by 2betop** [comment]
这个报错可能跟自己定义 filter 有关，自定义的 filter 的名字不要用中划线

**Comment by tanmengfei** [comment]
我自己没有定义filter 网上查询的是
ES6的新语法，在获取数据的时候比如${index|plus}，小撇号使用 tab 键上面的引号 ``， 非 enter键旁边的引号''

**Comment by RickCole21** [comment]
amis好像没`plus`这个`filter`吧，重新描述下使用细节？

**Comment by RickCole21** [comment]
再多说点使用细节？报错内容？还有

> ES6的新语法，在获取数据的时候比如${index|plus}，小撇号使用 tab 键上面的引号 ``， 非 enter键旁边的引号''

这是要表达啥意思

**Comment by 2betop** [comment]
仔细看了以下，我觉得这个问题可以忽略了，不是amis的问题，amis 的tpl 取变量语法确实跟 es6 里面的 

```
`${xxx}`
```

中的变量取法很像。但是不要弄混了，是两个东西
