### ISSUE TITLE
select静态的下拉框选择某一项时希望弹窗提示该如何处理

### ISSUE THREAD

**Issue by jijiyangguang** [baidu/amis#5808]
请教一下在select下拉框选择某一项时希望给使用者弹窗或者其他形式提示一下，这个该如何实现

**Comment by lhtuling** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select#%E4%BA%8B%E4%BB%B6%E8%A1%A8
change 事件
然后
https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E6%89%93%E5%BC%80%E5%AF%B9%E8%AF%9D%E6%A1%86
挺简单
