### ISSUE TITLE
registerFilter不能正确执行: filter not exists

### ISSUE THREAD

**Issue by fayeah** [baidu/amis#5810]
#### 描述问题：

registerFilter 自定义的函数不能正确应用。

#### 截图或视频：
想用disabledOn来做状态判断，其中用到了registerFilter来自定义函数，返回true或false

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
1.9.1-beta.30

4. 粘贴有问题的完整 `amis schema` 代码：
```
registerFilter("my-has", (input: string[], value: string) => {
  console.log("xxxxxx", input, value); // 在使用之后该语句没有执行
  if (!input || !Array.isArray(input) || input.length <= 0 || !value)
    return false;
  return input.includes(value);
});

```

5. 操作步骤
调用方法：

```
...
disabledOn: "${users|my-has:xxxxx",
```

并且浏览器react dev tools提示告警，说定义的filter "my-has" 不存在：

<img width="588" alt="image" src="https://user-images.githubusercontent.com/29644978/203788208-9e57f993-3c90-4202-aaa9-84ab59e9db98.png">

**Comment by fayeah** [comment]
额 可以了，需要在一开始就加载filter文件。。。

**Comment by hsm-lv** [comment]
https://github.com/baidu/amis/pull/6883
