### ISSUE TITLE
InputFormula 增加支持隐藏默认函数，方便用户利用 InputFormula 做更多其他业务逻辑

### ISSUE THREAD

**Issue by KillenMr** [baidu/amis#5813]
#### 是否关联于某个问题吗：
我想利用 InputFormula 实现一个简单的低代码 SQL 编辑器，用户可以通过“函数”定义的方法配置简单的 SQL 语句。因为 InputFormula 的 functions 是拼接模式，并且不能隐藏默认函数；导致 InputFormula 组件只适合做公式，扩展性不好。

#### 预期的解决方案：
增加一个属性，禁用或者可选择性的展示默认函数；比如增加一个 defaultFunctions: "all" || ["name1", "name2"]; 

#### 其他可接受方案：
增加一个属性，隐藏掉默认函数

#### 任何附加信息：
<img width="806" alt="image" src="https://user-images.githubusercontent.com/76677526/203932926-e6f2a283-1477-4087-8b28-25103293e307.png">

**Comment by KillenMr** [comment]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/76677526/203934091-f335778e-8433-456a-b7ad-040ae040b0a8.png">

这是当前 amis 版本的逻辑，直接将 `amis-formula/lib/doc` 中定义的公式和 `functions` 参数传入的公式定义拼接到一起，如果用户只希望展示自己定义的公式（或者只想展示部分 amis 定义的参数），则没有办法实现

**Comment by KillenMr** [comment]
临时解决方案：

打包及运行时候，执行下脚本，将 doc 重置为空数组

sed -i ".back" '1,$d' ./node_modules/amis-formula/lib/doc.js
echo -e "\nexport const doc = [];">> ./node_modules/amis-formula/lib/doc.js

**Comment by DataAlert-cn** [comment]
官方的InputFormula确实很受限啊，我想使用它编辑后端表达式，也没法用，希望官方能支持这个预期的解决方案

**Comment by DataAlert-cn** [comment]
@2betop @nwind 我看到InputFormula还是Beta版本，并且使用场景很局限，@KillenMr 提的方案很实用，请问能否支持？

**Comment by KillenMr** [comment]
> @2betop @nwind 我看到InputFormula还是Beta版本，并且使用场景很局限，@KillenMr 提的方案很实用，请问能否支持？

fork源码修改 发到 npm 上了

**Comment by DataAlert-cn** [comment]
> 

太好了，能帮忙提供链接吗？我在npm上没找到

**Comment by DataAlert-cn** [comment]
> > @2betop @nwind 我看到InputFormula还是Beta版本，并且使用场景很局限，@KillenMr 提的方案很实用，请问能否支持？
> 
> fork源码修改 发到 npm 上了

太好了，能帮忙提供链接吗？我在npm上没找到

**Comment by KillenMr** [comment]
> > > @2betop @nwind 我看到InputFormula还是Beta版本，并且使用场景很局限，@KillenMr 提的方案很实用，请问能否支持？
> > 
> > 
> > fork源码修改 发到 npm 上了
> 
> 太好了，能帮忙提供链接吗？我在npm上没找到

https://www.npmjs.com/package/fm-amis

目前基于 amis 2.5.2 版本做的更改：
1. InputFormula 组件增加了两个属性， uncheckFormula（是否校验公式的正确性） hiddenDefFunctions（是否隐藏默认公式）
2. InputFormula 修复了变量模块，文本内容过长导致的文本溢出问题

```
{
                                                        
type: "input-formula",
name: "sub_formula",
functions: cusFunctions, // 传入自定义的公式
uncheckFormula: true, // 对公式编辑器不做校验
hiddenDefFunctions: true, // 隐藏默认公式
...
},
```

**Comment by Jarod-Xie** [comment]
希望能支持隐藏部分自带公式的功能
