### ISSUE TITLE
Api的data对象里面使用了$,被解析

### ISSUE THREAD

**Issue by CKask** [baidu/amis#5817]
#### 描述问题：

Api的data对象里面使用了$,被解析，但是这个业务刚好就是要提交$字符串,能否出一个api配置为不解析数据映射，
下面代码里面的$name在使用过程中是个变量，$name是用户在界面上输入的值

#### 如何复现（请务必完整填写下面内容）：

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.3
3. 粘贴有问题的完整 `amis schema` 代码：
```
api:{
data:{
"test":"$name"
}
```

4. 操作步骤

**Comment by rumunanfeng** [comment]
api里面都可以把$符号改成%24，原理就是使用encodeURIComponent对字符串进行编码，encodeURIComponent('$') = '%24'

不用谢我，我叫雷锋

**Comment by CKask** [comment]
> api里面都可以把$符号改成%24，原理就是使用encodeURIComponent对字符串进行编码，encodeURIComponent('$') = '%24'
> 
> 不用谢我，我叫雷锋
谢谢，这个我也想过，需要修改的地方太多了，希望在json上给个字段设置是否需要解析，$也是用户直接输入的，编码保存后，在程序做逻辑处理的时候也就需要解码，显示也需要解码

**Comment by CKask** [comment]
@rumunanfeng 谢谢，这个办法也想过，就是$使用户输入的，编码后，所有遇到逻辑处理的地方都要解码，显示的时候也需要解码

**Comment by rumunanfeng** [comment]
> @rumunanfeng 谢谢，这个办法也想过，就是$使用户输入的，编码后，所有遇到逻辑处理的地方都要解码，显示的时候也需要解码

用户输入的话，转成\\$，显示就没有问题；传递的话我不太确定，你可以试下

**Comment by CKask** [comment]
> > @rumunanfeng 谢谢，这个办法也想过，就是$使用户输入的，编码后，所有遇到逻辑处理的地方都要解码，显示的时候也需要解码
> 
> 用户输入的话，转成\$，显示就没有问题；传递的话我不太确定，你可以试下
输入$转出\$这种在input组件上做最好

**Comment by zetianul** [comment]
ignoreData 试一下？不会dataMapping

**Comment by CKask** [comment]
> 

能详细说说吗？谢谢

**Comment by CKask** [comment]
> ignoreData 试一下？不会dataMapping

能详细说说吗？谢谢

**Comment by zetianul** [comment]
> 

取决于你怎么用的了，如果你用的是默认的fetcher，可以给env.fetcher的第三个参数传递 { ignoreData: true } 实现不转换，代码参考
https://github.com/baidu/amis/blob/master/packages/amis-core/src/utils/api.ts#L162

**Comment by CKask** [comment]
> > 
> 
> 取决于你怎么用的了，如果你用的是默认的fetcher，可以给env.fetcher的第三个参数传递 { ignoreData: true } 实现不转换，代码参考 https://github.com/baidu/amis/blob/master/packages/amis-core/src/utils/api.ts#L162

![image](https://user-images.githubusercontent.com/38378220/213349217-19fc6cf0-85c5-4f08-ad4d-b9bfe62d4458.png)
第三个参数是data，第四个参数是axios的config，都试了下吗，结果还是转换了

**Comment by nwind** [comment]
可以前面加 \\ 避免转义，改成 `\\$name`
