### ISSUE TITLE
框架使用问题

### ISSUE THREAD

**Issue by whitekyo** [baidu/amis#582]
问题1:
{
                        "type": "button",
                        "icon": "fa fa-times text-danger",
                        "actionType": "ajax",
                        "api": "post:http://localhost:8000/fed/onlineSubject?subjectId=${subjectId}&online=${!isOnline}"
                    }

api中，有个参数online 需要根据isOnline做判断，比如isOnline为1时，online为0。这种情况具体怎么书写？

**Comment by RickCole21** [comment]
使用`tpl`的`isEquals`过滤器，[相关文档](https://baidu.github.io/amis/docs/renderers/Tpl#tpl),具体写法如下:
```
${isOnline|isEquals:1:0:''}
```

**Comment by whitekyo** [comment]
感谢

**Comment by whitekyo** [comment]
问题2:
我在使用json编辑器时，进入页面时候需要直接调用一下接口，从接口中获取数据填充到json编辑器中，这个api我该如何配置？

"columns": [
                        {
                            "type": "form",
                            "api": "https://houtai.baidu.com/api/mock2/saveForm?waitSeconds=2",
                            "title": "",
                            "controls": [
                                {
                                    "name": "json",
                                    "type": "editor",
                                    "language": "json",
                                    "label": "JSON",
                                    "value": `
                                        {"a": 1, "b": 1}
                                    `
                                }
                            ],
                            "md": 6,
                            "height": 500
                        },
                        {
                            "type": "iframe",
                            "className": "b-a",
                            "src": "https://www.baidu.com",
                            "height": 500,
                            "md": 6
                        }
                    ]

**Comment by RickCole21** [comment]
api接口中响应要符合amis要求：

```
{
    "status": 0,
    "msg": "",
    "data": {
        "json" :{"a":"aaa"} // 这里返回你要显示的值，会自动映射到表单中，只要你表单中json-editor的name值与这个key值同名
    }
}
```

**Comment by whitekyo** [comment]
数据结构我知道的，但是这个接口我配置在哪，我写了source，发现没有调用接口。。。

{
                                    "name": "json",
                                    "type": "editor",
                                    "language": "json",
                                    "label": "JSON",
                                    "source": "https://localhost:3000/fed/getTagDetail",
                                    
                                }

**Comment by RickCole21** [comment]
哦，是在form上配`initApi`

**Comment by whitekyo** [comment]
可以了，感谢

**Comment by whitekyo** [comment]
问题3:
我使用的是你们jssdk。我如果想就一个btn做一些定制化的交互，我基于AMIS改怎么做？有规范么？

**Comment by RickCole21** [comment]
具体交互细节简单说说？可能需要自己写自定义组件？

**Comment by whitekyo** [comment]
比如，我需要将json编辑的内容。取出来，做一些数据结构加工。输出到另一个div中。

**Comment by RickCole21** [comment]
amis可以实现

**Comment by RickCole21** [comment]
form配置target，可以实现将数据提交给另外一个组件，数据结构加工具体是要怎么加工

**Comment by whitekyo** [comment]
我配置target，和api是不会有冲突的吧？ 因为我想json编辑完既可以实时预览，也可以提交到服务端

**Comment by 2betop** [comment]
同一个 form 下面放个 tpl 自定义输出就行了

**Comment by whitekyo** [comment]
@2betop  @RickCole21  OK知道了，如果我想把json编辑器的内容写到你们iframe控件里面，我改如何做？

**Comment by 2betop** [comment]
只能用 tpl。

amis 的iframe 是打开别的网址的。

**Comment by whitekyo** [comment]
@2betop  OK

**Comment by whitekyo** [comment]
另外，问下我有办法可以实时拿到你们json编辑器里面的数据么？

**Comment by 2betop** [comment]
在 form 里面可以，在外面不可以

**Comment by whitekyo** [comment]
嗯，是的。我发现通过获取dom然后innerText无法获取到全部的json内容，这个有什么hack办法可以拿到？

**Comment by 2betop** [comment]
你为啥要通过 dom 获取？你再 form 下面弄个 tpl 类型的渲染器，然后 ${表单项的name} 就可以获取

**Comment by whitekyo** [comment]
我说的获取，是指实时获取用户修改的json。tpl只能根据接口返回渲染吧

**Comment by RickCole21** [comment]
tpl里取的变量值就是实时的

**Comment by whitekyo** [comment]
@RickCole21  @2betop  问题已经解决，感谢。
