### ISSUE TITLE
有没有JS SDK版的 admin 后台首页

### ISSUE THREAD

**Issue by flysmallstrong** [baidu/amis#5820]
刚学, 我把amis当UI库用,
有没有JS SDK版的 admin 后台首页example, 就是那种左侧是菜单列表,右侧是空白那种模板?
现在演示的example全都要npm, npm,npm, 太难了.

**Comment by LC6LW** [comment]
https://github.com/LC6LW/amis-manage

**Comment by flysmallstrong** [comment]
谢谢, 我看看
