### ISSUE TITLE
在提交form表单时根据表单值条件的不同判断是否弹窗

### ISSUE THREAD

**Issue by jijiyangguang** [baidu/amis#5833]
![image](https://user-images.githubusercontent.com/58300832/204310895-ba69686e-eb73-43f7-bdcd-a2ef9127d3ed.png)

在提交表单时，假如下拉框选中的值为b时，点击提交按钮希望给一个弹窗提示，这个该如何实现

**Comment by hsm-lv** [comment]
可以监听提交相关的事件，从上下文读取表单项的值作为弹窗动作执行的条件，具体可以了解一下事件动作 https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action
