### ISSUE TITLE
1.8sdk 月份选择框要点击两次才能选上

### ISSUE THREAD

**Issue by hcf1997** [baidu/amis#5841]
{
                            "type": "input-month",
                            "name": "MMonth",
                            "label": "月份:",
                            "clearable": true,
                            "format": "MM",
                            "className": "rdtMonthsTitleHidden",
                            "inputFormat": "MM月",
                            "size": "full"
                        }

**Comment by 2betop** [comment]
最新版本已不存在这个问题，请升级到最新版本 3.1.0
