### ISSUE TITLE
大家猜是不是把amis打包进小程序？

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#5859]
#### 是否关联于某个问题吗：
是不是可以删除一些不要js满足包的大小，然后弄到微信小程序里面，全局用动态api的Schema。然后就相当于功能与页面随时都可以改？

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by xwayway** [comment]
是这样的

**Comment by xwayway** [comment]
是可以这样的，但是你就不能用小程序原生的js能力了吧，既然都这样了，你为啥不选择把资源上传到cdn，然后采取webview的方案呢

**Comment by xiahao90** [comment]
cdn +webview没有打包进去加载起来快把？

**Comment by nwind** [comment]
不太行，小程序不支持很多 dom 接口，需要改很多，只能重新弄个项目
