### ISSUE TITLE
如何在React自定义组件中去更新上级组件数据域中的数据

### ISSUE THREAD

**Issue by wleven** [baidu/amis#5864]
#### 实现场景：
在自定义组件中更新上级组件(比如page)data里面的数据

#### 存在的问题：
在自定义组件中更新上级组件(比如page)data里面的数据

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by wleven** [comment]
等官方支持

**Comment by LhrAlander** [comment]
我也有同样的需求不知道如何实现

**Comment by yanquer** [comment]
怎么关了, 现在的 doAction 貌似有点bug
