### ISSUE TITLE
官方示例中 crud带边栏(用Nav)  配置复制到本地, 边栏不高亮了. 

### ISSUE THREAD

**Issue by flysmallstrong** [baidu/amis#5869]
#### 描述问题：

官方示例中 crud带边栏(用Nav)  配置复制到本地, 边栏不高亮了. 

#### 截图或视频：
![2](https://user-images.githubusercontent.com/36694291/205446923-3d8a19ee-a15c-45a0-8f09-c8bb4b05b3af.png)
![1](https://user-images.githubusercontent.com/36694291/205446929-93bf2b68-a224-47f4-bd7f-301726364a48.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk  2.5.1 

4. 操作步骤
请简单描述一下复现的操作步骤...

使用amis-admin模板https://github.com/aisuda/amis-admin
右侧使用amis示例中的 https://aisuda.bce.baidu.com/amis/examples/crud/aside2?cat=1    crud带边栏(Nav)联动 中的json配置, 
将该配置复制到本地,  边栏不显示,  添加"type":"page" 后, 边栏显示, 但是选项不高亮.

**Comment by hsm-lv** [comment]
建议尝试一下新版本3.3.0
