### ISSUE TITLE
form表单问题

### ISSUE THREAD

**Issue by whitekyo** [baidu/amis#587]
form当中嵌套了一个form。我将内部的form按钮进行了隐藏，并且没有设置api（内部form中包含了一个json editor。因为直接在tab下写json editor，你们的框架会报错）。只有最外层的form设置了api。现在有个问题是，我每次变更editor的时候，都会去发送api的请求。我尝试在外部和内部两个form上添加submitOnChange都无法解决。

{
                            "type": "form",
                            "api": "post:http://10.243.238.44:8000/fed/pushCode",
                            "initApi": "get:http://10.243.238.44:8000/fed/tagDetail",
                            "submitOnChange": false,
                            "title": "",
                            "controls": [
                                {
                                    "type": "grid",
                                    "columns": [
                                        {
                                            "label": "预览",
                                            "type": "button",
                                            "level": "dark",
                                            "actionType": "close",
                                            "tpl": "sm-1",
                                            "sm": 2,
                                            "inline": false,
                                            "className": "review"
                                        },
                                        {
                                            "label": "保存",
                                            "type": "button",
                                            "level": "dark",
                                            "actionType": "dialog",
                                            "dialog": {
                                                "title": "弹框",
                                                "body": "这是个简单的弹框。"
                                            },
                                            "tpl": "sm-1",
                                            "sm": 4,
                                            "inline": false
                                        }
                                    ]
                                },
                                {
                                    "type": "tabs",
                                    "tabs":[ 
                                        {
                                            "title": "json编辑器",
                                            "body": {
                                                "type": "form",
                                                "wrapWithPanel": false,
                                                "className": "json_superman",
                                                "submitOnChange": false,
                                                "title": "",
                                                "controls": [
                                                    {
                                                        "name": "json",
                                                        "type": "editor",
                                                        "language": "json"
                                                    },
                                                    {
                                                        "type": "tpl",
                                                        "tpl": "<%=data.json %>"
                                                    }
                                                ]   
                                            }
                                        },
                                    ],
                                },
                            ],
                            "md": 4,
                            "height": 500
                        }

**Comment by RickCole21** [comment]
已修复，使用 1.0.11-beta.38版本 应该没这个问题

不过我觉得你可能并不需要在form里面放form，fieldSet也许就满足你这个需求了😈

**Comment by whitekyo** [comment]
好的，我试试

**Comment by RickCole21** [comment]
有问题再开，先关了

**Comment by whitekyo** [comment]
你说的fieldSet都是要基于外层有个form的吧，我试过了。提示找不到渲染器。因为我的form表单里面有一个tab控件，tab控件下面放fieldSet

**Comment by whitekyo** [comment]
OK，可以了tab有个controls属性 解决我的问题了
