### ISSUE TITLE
如何拿到table组件选中的项目

### ISSUE THREAD

**Issue by aundis** [baidu/amis#5880]
![112233](https://user-images.githubusercontent.com/61673908/205909191-0df89c2c-fde8-4b40-9473-e8431ed8079b.png)

**Comment by hsm-lv** [comment]
要具体看获取选中项的时机，table支持事件监听，可以参考 https://aisuda.bce.baidu.com/amis/zh-CN/components/table#%E4%BA%8B%E4%BB%B6%E8%A1%A8，监听selectedChange可以获取选中项，例如：
`{
  "type": "page",
  "body": {
    "type": "service",
    "api": "/amis/api/mock2/sample?perPage=5",
    "body": [
      {
        "type": "table",
        "title": "表格1",
        "source": "$rows",
        "selectable": true,
        "multiple": true,
        "columns": [
          {
            "name": "engine",
            "label": "Engine"
          },
          {
            "name": "version",
            "label": "Version"
          }
        ],
        "onEvent": {
          "selectedChange": {
            "actions": [
              {
                "actionType": "toast",
                "args": {
                  "msg": "${event.data.selectedItems|json}"
                }
              }
            ]
          }
        }
      }
    ]
  }
}`
