### ISSUE TITLE
Form表单内嵌套page后，表单reset和clear方法不生效

### ISSUE THREAD

**Issue by zoujean** [baidu/amis#5883]
#### 描述问题：

schema中 Form表单内嵌套page后，表单reset和clear方法不生效，实际数据已经修改，提交的时候能看到数据清空了，但是页面显示没有清空

#### 截图或视频：

![image](https://user-images.githubusercontent.com/20321757/206091323-57453e7a-7a87-4fec-ae8a-c61c9cdec41b.png)
![image](https://user-images.githubusercontent.com/20321757/206091439-60480213-5058-47e3-9247-f463b1e1d521.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis ^2.4.0版本
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
    {
      "type": "form",
      "body": [
        {
          "type": "page",
          "body": [
            {
              "type": "input-text",
              "name": "name",
              "label": "姓名",
              "id": "u:af1e29e66220"
            },
            {
              "type": "input-email",
              "name": "email",
              "label": "邮箱",
              "id": "u:5db6bc9b3b69"
            }
          ],
          "id": "u:bf3b3ae08cf6"
        }
      ],
      "id": "u:13c1d59a66d1",
      "actions": [
        {
          "type": "reset",
          "label": "重置",
          "id": "u:d8a81782a759"
        },
        {
          "type": "submit",
          "label": "保存",
          "id": "u:d4f69ce2bb76"
        }
      ]
    }
  ],
  "id": "u:965c203ce621"
}
```

4. 操作步骤
将官网的  重置表单  例子复制过来修改（在form里嵌套一层page）后，放在 amis-editor-demo 就能复现

**Comment by hsm-lv** [comment]
1.不建议form套page使用，page也是一种容器，但一般作为根组件
2.可以通过事件动作来实现跨层级交互，https://aisuda.bce.baidu.com/amis/zh-CN/components/form/index#%E5%8A%A8%E4%BD%9C%E8%A1%A8
