### ISSUE TITLE
如何实现：表单提交之后， toast提示成功，然后5秒后自动跳转到列表页面

### ISSUE THREAD

**Issue by tangtangsara** [baidu/amis#5884]
#### 实现场景：
编辑页面，表单提交之后，toast提示成功，然后5秒后自动跳转到列表页面。

请问如何实现： toast提示成功，然后5秒后自动跳转到列表页面
```

**Comment by hsm-lv** [comment]
可是尝试事件动作添加toast动作和自定义JS动作，JS动作逻辑实现延迟跳转，跳转的话可以通过doAction来调用跳转动作（url or link）
