### ISSUE TITLE
增加动态注册渲染器机制后，自定义控件无法传入 autoVar 参数

### ISSUE THREAD

**Issue by hotlong** [baidu/amis#5886]
#### 描述问题：

之前可以在注册控件时传入 autoVar 参数。
```
registerMap[curUsage as keyof typeof registerMap]({
      type: curAmisRenderer.type,
      weight: curAmisRenderer.weight || 0,
     autoVar: true
    })(curAmisRendererComponent);
```

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

amis-core@2.5.2-beta.0

4. 粘贴有问题的完整 `amis schema` 代码：
无

6. 操作步骤

自定义控件无法实现 autoVar 功能。

**Comment by wibetter** [comment]
@hotlong 
![face_48@2x](https://user-images.githubusercontent.com/11958920/209298501-da0dd117-c2ab-4af2-b2d2-b1e8427a7f57.png)
