### ISSUE TITLE
amis文档的异步请求全部报跨域异常了

### ISSUE THREAD

**Issue by TedCat** [baidu/amis#5906]
#### 描述问题：

例如这个页面，[table组件介绍](https://baidu.github.io/amis/zh-CN/components/table) ， [mock sample](https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample) 全部都load不出来了

**Comment by AiOkk** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/table  可以用这个文档
