### ISSUE TITLE
希望可以增加可视化编辑器方面的文档.  

### ISSUE THREAD

**Issue by nuan1989** [baidu/amis#5908]
非常感谢开发amis的工作人员, 目前amis在低代码领域算是王重阳的级别.  文档也非常全.  就是可视化编辑器的文档有点少, 想二次开发组件, 没地方下手. 

这个应该很多用amis的新手都有这样困惑.

**Comment by nwind** [comment]
现在可以阅读 https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/editor 及参考源码
