### ISSUE TITLE
子表单如何封装成一个父级表单JSON中的一个对象

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#591]
{
	'a': 'v1',
	'b': 'v2',
	'c': {
              'd':'v3'
              }
}
如果我想向接口传递如上JSON 数据，C那里我做的是一个子表单，那我该如何设置子表单，才能达到这个效果呢？是给子表单加上name属性嘛？

**Comment by RickCole21** [comment]
是的，子表单`name`设置成`c`，然后子表单中表单项`name`设置为`d`

**Comment by tanmengfei** [comment]
> 是的，子表单`name`设置成`c`，然后子表单中表单项`name`设置为`d`

好的，谢啦

**Comment by RickCole21** [comment]
哦多说一句，实际上你某个表单项的`name`设置成`"c.d"`也可以，自己选择下，你可以给`form`设置`"debug": true`，查看当前表单数据域的数据。

**Comment by tanmengfei** [comment]
太谢谢啦，这个很好用，目前还有一个问题：
我用的是Combo的tabs，链接在这里https://baidu.github.io/amis/docs/renderers/Form/Combo#tabs-%E6%A8%A1%E5%BC%8F
然后combo还必须设置一个name属性，如果没有的话debug里边就获取不到combo下表单的数据，但是加了name，就会把comb下的内容封装到name字段名中，但是我不想封装进去，想单独出来，这个有办法解决吗

**Comment by 2betop** [comment]
直接用tabs https://baidu.github.io/amis/docs/renderers/Form/Tabs

**Comment by tanmengfei** [comment]
> 直接用tabs https://baidu.github.io/amis/docs/renderers/Form/Tabs

还想动态的添加项==

**Comment by 2betop** [comment]
要动态添加，那就得是数组，没有设置 name ，存哪里？
