### ISSUE TITLE
官方文档提供的demo出现跨域问题

### ISSUE THREAD

**Issue by GGGxie** [baidu/amis#5922]
![image](https://user-images.githubusercontent.com/26421997/207224803-7634a3fe-ae2f-4b26-8820-c3995a2e875e.png)

**Comment by AiOkk** [comment]
可以用这个文档 https://aisuda.bce.baidu.com/amis/zh-CN/components/table

**Comment by GGGxie** [comment]
> 可以用这个文档 https://aisuda.bce.baidu.com/amis/zh-CN/components/table

感谢~

**Comment by nwind** [comment]
未复现，应该是后来修了
