### ISSUE TITLE
InputFile 文件上传如何实现加载原有文件列表后可以在基础上添加和删除

### ISSUE THREAD

**Issue by jojo-Tony** [baidu/amis#5935]
意思就是如查看表格中的某一项，然后这一项原来是已经上传了文件的，点开后可以查看已上传的文件，并且可以添加或删除
![image](https://user-images.githubusercontent.com/45332881/208010033-6bbcce2f-3a9a-4577-bf94-7735be49bff9.png)

**Comment by hereisok** [comment]
同样的问题， 现在如果添加文件， 会覆盖掉之前的后端返回的文件列表。

如 后端返回

文件A,文件B

amis页面上操作， 添加文件C， 此时视图上还是看见三个文件。

但最终提交， 仅剩文件C被提交了

**Comment by xukeke520** [comment]
我也发现这个问题了，回显的数据必须要加上state才不会被覆盖

**Comment by changejun** [comment]
这个场景， 其实把文件数据的提交与表单数据的提交分开处理就行了


其实，我还有个问题，各位是如何渲染出已上传的文件数据的？请指教

**Comment by nabaonan** [comment]
> state

可以具体说下怎么加这个state吗，我现在也遇到这个问题了

**Comment by hereisok** [comment]
@nabaonan 

如下， 后端接口返回文件对象， 需要加上 state = uploaded

```json
{
      "value": "xxx",
      "filename": "xxx",
      "url": "xxx",
      "state": "uploaded"
}
```
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-file#filevalue-%E5%B1%9E%E6%80%A7%E8%A1%A8

**Comment by nabaonan** [comment]
> @nabaonan
> 
> 如下， 后端接口返回文件对象， 需要加上 state = uploaded
> 
> ```json
> {
>       "value": "xxx",
>       "filename": "xxx",
>       "url": "xxx",
>       "state": "uploaded"
> }
> ```
> 
> https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-file#filevalue-%E5%B1%9E%E6%80%A7%E8%A1%A8

感谢，亲测有效，需要再回显的接口把之前的文件都加一个state状态，每追加上传一个文件再重新加个state状态，最后提交表单的时候应该是根据这个状态判断是否添加到请求体里
