### ISSUE TITLE
Tpl 渲染直接显示文本，而不是HTML

### ISSUE THREAD

**Issue by cnbillow** [baidu/amis#594]
JSSDK引用，相关代码如下：
<pre>
                {
                    "type": "tpl",
                    "label": "内容",
                    "tpl": "{{ information.body }}",
                },
</pre>
渲染后的页面显示文本。请问怎样显示HTML？

**Comment by 2betop** [comment]
你这语法就不对，你还是先看看这个：https://baidu.github.io/amis/docs/renderers/Tpl

**Comment by cnbillow** [comment]
这么迅速。通过 $xxx 取到的值，默认是会做 html 转义的。试了半天了。还是不可以。
<pre>
            "data": {
              "body": "{{ information.body }}"
            },
            他略
                {
                    "type": "tpl",
                    "label": "内容",
                    "tpl": "${body|html}",
                },
</pre>

**Comment by cnbillow** [comment]
可以了，语法好像没问题。
后台是django，加了mark_safe(information.body)处理。

**Comment by 2betop** [comment]
文档里面说了，默认 `${xxx}` 等价于 `${xxx | html}` 所以，如果想要不转义就要 `${xxx | raw}`
