### ISSUE TITLE
validations 正则表达式匹配问题

### ISSUE THREAD

**Issue by PengXing** [baidu/amis#595]
FormItem 的 `validations` 支持正则表达式，可以通过下面这种方式编写 validations

```js
{
  validations: 'matchRegexp:/^(/?\w+)*$/',
  description: '格式如下：hello 或者 hello/world 或者 hello/world/everyone',
}
```

但是，对上面正则表达式的支持有点问题，可以看这个代码https://github.com/baidu/amis/blob/cdf3f9dd6fdc65d48e4283fe5cdf26e77bac1d16/src/utils/validations.ts#L293

由于正则表达式中包含`/` 字符，匹配结果就是错误的，会导致 

`placeholder['__0'] = 'matchRegexp:/^(/'`

拿到的正则表达式不全，所以正确正则表达式无法工作。

**Comment by RickCole21** [comment]
加转义？而且你还可以用这种形式
```
{
  validations: {
    matchRegexp: /^(\/?\w+)*$/
  }
}
```

**Comment by PengXing** [comment]
`matchRegexp:/^(\/?\w+)*$/`，加转义试过，没区别

不过下面的方式我尝试过，是 ok 的
