### ISSUE TITLE
tpl配合html使用时，如果是在${}中，html中的属性值有bug

### ISSUE THREAD

**Issue by Flyingliao** [baidu/amis#5955]
#### 描述问题：

tpl配合html使用时，如果是在${}中，html可能无效

#### 截图或视频：

<img width="992" alt="image" src="https://user-images.githubusercontent.com/41402189/208859625-4d963f57-80e7-44a0-ac13-8124dd8ce3ea.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
amis官网

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "data": {
    "text": true
  },
  "type": "page",
  "body": [
    {
      "type": "tpl",
      "className": "block",
      "tpl": "<span class='w-6 text-danger'>bbb</span>"
    },
    {
      "type": "tpl",
      "tpl":"${text |isTrue: <span class='w-6 text-danger'>bbb</span> : 2}"
    }
  ]
}
```

4. 操作步骤
把上面代码复制到amis官网中就能重现

**Comment by nwind** [comment]
输出结果需要是字符串，改成 `"${text |isTrue:'<span class=\"w-6 text-danger\">bbb</span>': 2| raw}"`
