### ISSUE TITLE
curd 找不到对应的渲染器

### ISSUE THREAD

**Issue by alonghub** [baidu/amis#5961]
#### 描述问题：

使用curd type，显示 Error: 找不到对应的渲染器

#### 截图或视频：

![image](https://user-images.githubusercontent.com/40453075/209103177-c9b2826a-cea7-4e4d-80f1-8a7b7bc59420.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.5.2

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
        "type": "page",
        "body": {
            "type": "curd",
            "api": "/api/info",
        }
}
```

4. 操作步骤
html 
<body>
    <div id="root" class="app-wrapper"></div>
    <script src="http://sinastorage.cn/dpoolstatic/amis/sdk-2.5.2/sdk.js"></script>
    <script type="text/javascript">
        let amisJSON = JSON.parse('{{ page_config }}');
        (function () {
            let amis = amisRequire('amis/embed');
            let amisScoped = amis.embed('#root', amisJSON);
        })();
    </script>
</body>

**Comment by wxlandzyb** [comment]
你这个解决了？

**Comment by LiuQuanYou** [comment]
解决了吗？
