### ISSUE TITLE
input-tree 支持拖拽排序，并且暴露拖拽排序完成的事件

### ISSUE THREAD

**Issue by yi1991er** [baidu/amis#5969]

**Comment by meerkat-morecats** [comment]
@yi1991er 想了解下你这边的使用场景，如果是通过npm安装的话，暂时可以通过自定义组建来实现

**Comment by qianSir01** [comment]
> @yi1991er 想了解下你这边的使用场景，如果是通过npm安装的话，暂时可以通过自定义组建来实现
如何实现，有没有案例？我这边现在想拖拽树input-tree，但是好像还不能拖拽。

**Comment by yi1991er** [comment]
> @yi1991er 想了解下你这边的使用场景，如果是通过npm安装的话，暂时可以通过自定义组建来实现

场景：使用tree的目录组件，做出类似文件和文件夹的操作；

**Comment by meerkat-morecats** [comment]
暂时没有demo，可以弄个自定义组件，用 `amis-ui/Tree` 传入 `dragable=true` 和 `onMove=(dropInfo: IDropInfo) =>void` 函数（拖拽完成后会调用）

```typescript

interface IDropInfo {
  dragNode: Option | null;
  node: Option;
  position: 'top' | 'bottom' | 'self';
  indicator: IDropIndicator;
}

```
