### ISSUE TITLE
自定义组件内无法使用Action，提示TypeError: onAction is not a function

### ISSUE THREAD

**Issue by chareice** [baidu/amis#597]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/1624785/82019578-12b29b80-96ba-11ea-8b84-4040d135c66a.png">
自定义组件中渲染action之后，点击按钮会报错
<img width="708" alt="image" src="https://user-images.githubusercontent.com/1624785/82019610-2231e480-96ba-11ea-9539-be09955aadd0.png">

测试repo: 
https://github.com/chareice/amis-onaction-test

入口文件：
https://github.com/chareice/amis-onaction-test/blob/master/app.tsx

自定义组件：
https://github.com/chareice/amis-onaction-test/blob/master/CustomComponent.tsx

**Comment by 2betop** [comment]
需要先放在 Page 下面，才会响应弹框动作，如果没有渲染 page，直接渲染个自定义组件，其实是没那快逻辑的。这个后续考虑以下，把一些常规动作的处理放到 rootRenderer 里面。

**Comment by chareice** [comment]
好的
