### ISSUE TITLE
select 设置 selectMode 后 labelField 失效

### ISSUE THREAD

**Issue by KillenMr** [baidu/amis#5979]
#### 描述问题：

select 级联模式下 labelField 丢失

#### 截图或视频：

![image](https://user-images.githubusercontent.com/76677526/209524005-570ae134-12e0-46cc-bc5c-6d6a432f66bf.png)

#### 如何复现（请务必完整填写下面内容）：

可以在这里验证，分组展示模式下，增加 "selectMode": "group", "labelField": "text", 并将数据 label 改为 text；如下：
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select#%E5%88%86%E7%BB%84%E5%B1%95%E7%A4%BA%E6%A8%A1%E5%BC%8F

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

v2.5.2

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "label": "分组",
        "type": "select",
        "name": "a",
        "selectMode": "group",
        "labelField": "text",
        "options": [
          {
            "text": "法师",
            "children": [
              {
                "text": "诸葛亮",
                "value": "zhugeliang"
              }
            ]
          },
          {
            "text": "战士",
            "children": [
              {
                "text": "曹操",
                "value": "caocao"
              },
              {
                "text": "钟无艳",
                "value": "zhongwuyan"
              }
            ]
          },
          {
            "text": "打野",
            "children": [
              {
                "text": "李白",
                "value": "libai"
              },
              {
                "text": "韩信",
                "value": "hanxin"
              },
              {
                "text": "云中君",
                "value": "yunzhongjun"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

4. 操作步骤
可以在这里验证，分组展示模式下，增加 "selectMode": "group", "labelField": "text", 并将数据 label 改为 text；如下：
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select#%E5%88%86%E7%BB%84%E5%B1%95%E7%A4%BA%E6%A8%A1%E5%BC%8F

**Comment by allenXu317** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/options#%E9%80%89%E9%A1%B9%E6%A0%87%E7%AD%BE%E5%AD%97%E6%AE%B5-labelfield
------
"默认渲染选项组，会获取每一项中的label变量作为展示文本，如果你的选中项中没有label字段，可能会有显示问题"。
----
我看你的 schema json 中 options 下面的子项没有配置 “label” 字段，导致显示出现了问题。

**Comment by KillenMr** [comment]
> 
"labelField": "text"
