### ISSUE TITLE
表单提交以后，如何把返回信息呈现在页面固定区域

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#598]
类似于postman的response那里

**Comment by RickCole21** [comment]
可以表单中配置一个`json-editor`，`name`与你接口返回的值进行同名映射，应该就能显示了

**Comment by tanmengfei** [comment]
> 可以表单中配置一个`json-editor`，`name`与你接口返回的值进行同名映射，应该就能显示了
假如返回结果是这个{"status":0,"msg":"保存成功","data":{"id":1}}，然后我想把这个显示在json-editor中，那么json-editor的name值该怎么设置呢

**Comment by RickCole21** [comment]
这样的话应该需要在接口写adaptor，大概如下：
```
 "api": {
        "method": "post",
        "url": "/api/mock2/form/saveForm",
        "adaptor": "return {\n    ...payload,\n    data: {\n        ...payload.data,\n        response: response.data\n    }\n}"
    },
```

adaptor内容是：
```javascript
return {
    ...payload,
    data: {
        ...payload.data,
        response: response.data
    }
}
```

逻辑就是把adaptor函数签名中的response数据，加入到data中，这样你的`editor`的`name`设置为`response`就能映射了

> adaptor这里也可以直接配一个function，如果你的使用方法可以配function的话

**Comment by tanmengfei** [comment]
太谢谢啦！现在在form表单里边可以获取返回结果了，有办法在form表单外获取嘛

**Comment by RickCole21** [comment]
可以，给`form`配置`"reload": "xxx?response=${response}"`，`xxx`是另外一个组件的`name`属性值。`response=${response}`可以把当前数据域中的`response`值传给`xxx`组件，`xxx`组件内就可以使用这个数据了

你可能需要看下`https://baidu.github.io/amis/docs/advanced`

**Comment by tanmengfei** [comment]
我天，成功啦，太谢谢啦，我知道这种用法，但是没想到==，还是使用不太熟练

**Comment by RickCole21** [comment]
star 支持一下？😎

**Comment by tanmengfei** [comment]
已支持，哈哈

**Comment by i323654** [comment]
能贴一个完整，可运行的示例吗？

**Comment by Caeser-SONG** [comment]
我按上面的配置写，api 还没返回的时候 json 就已经渲染了   不是想要的结果 这个怎么办
