### ISSUE TITLE
amis功能太强大了，请问开源部分包括后端吗?就像百度内部的amis一样

### ISSUE THREAD

**Issue by westeast** [baidu/amis#60]

**Comment by westeast** [comment]
类似 内部使用的，开发完后台接口，自己在上面配置就行了这种的

**Comment by MrStrangeBao** [comment]
https://github.com/baidu/amis/issues/46, 不会的哦

**Comment by westeast** [comment]
@MrStrangeBao 那我们开源的是哪 部分啊，就是一个界面样式吗？

**Comment by BenwinC** [comment]
同求这个问题

**Comment by 2betop** [comment]
开源的部分是  **配置 => 页面呈现**    配置这一块你可以先从 amis 平台 copy 出来用，或者你要熟悉的话，也可以手写哈。

**Comment by fandasoft** [comment]
amis是基于react的，请问对于Angular是否也适用？

**Comment by 2betop** [comment]
只要不嫌体积大，其实是可以打通的。

**Comment by liutian** [comment]
不要以为框架本身大，就想当然的以为最终项目体积大，我倒是看到不少同体量的vue，react项目最终项目js文件比angular项目的js文件还要大 @2betop

**Comment by quanke** [comment]
现在每个界面需要建立tsx文件吗？可以直接通过接口返回json创建页面吗？

**Comment by 2betop** [comment]
这个不算渲染器的工作了，需要自己实现，先拉取数据（配置 schema）然后再调用渲染。

**Comment by nwind** [comment]
已经有类似的商业版 https://suda.baidu.com/
