### ISSUE TITLE
AMIS 的 echarts 支持 registerMap 方法吗？

### ISSUE THREAD

**Issue by ringsaturn** [baidu/amis#600]
想在 AMIS 里绘制地图，没有找到加载 GeoJSON 文件的方法。

https://echarts.apache.org/examples/zh/editor.html?c=map-HK

**Comment by RickCole21** [comment]
这种貌似实现不了

**Comment by 2betop** [comment]
GeoJson 得自己通过 api 提供，然后配置 onDataFilter 可以把数据设置进去 `echarts.registerMap('HK', geoJson);`
