### ISSUE TITLE
release2.3.1版本起，引入问题 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component

### ISSUE THREAD

**Issue by byron0829** [baidu/amis#6010]
#### 描述问题：

sdk方式使用。在input-table中使用picker作为其中一列，每次点击『新增』时，都会报错。逐个更换以前的sdk测试了一下，是从2.3.1引入的这个问题

#### 截图或视频：
![image](https://user-images.githubusercontent.com/772513/210341733-18088853-29e2-442b-9df5-7d15e05bd084.png)

**Comment by 2betop** [comment]
新版本已不能复现，先关了，有问题再开
<img width="1221" alt="image" src="https://github.com/baidu/amis/assets/2698393/df0dd4f6-3fcb-4fee-ab29-359c3f3efd57">
