### ISSUE TITLE
可视化编辑器  Curd 组件 生成的单行删除按钮 ajax 请求类型是否可以修改为  delete 方式

### ISSUE THREAD

**Issue by atliwen** [baidu/amis#6024]
#### 是否关联于某个问题吗：
当前Curd 组件的 单行删除按钮 请求方式为  post   ，编辑器中也未能按 文档中 的给请求地址绑定一个  '${id}'  

#### 预期的解决方案：

是否可以 按照 标准 restapi   将删除按钮改为 delete 请求方式 

#### 其他可接受方案：

编辑器修复改BUG 

#### 任何附加信息：
期望生成 
![image](https://user-images.githubusercontent.com/10055836/210919327-08443c1e-77cb-4bdb-9a6e-a7c70cc10c95.png)

**Comment by hsm-lv** [comment]
method的设定一般根据接口形态而定，不过这个可以自行修改的
