### ISSUE TITLE
嵌套列表，开启排序功能，上下拖动记录，偶尔会出错。

### ISSUE THREAD

**Issue by cnbillow** [baidu/amis#603]
https://baidu.github.io/amis/crud/nested?page=1
嵌套列表，上下拖动记录后偶尔出错（随便点的）。如图，3行的内容变成和4行一样了。

![image](https://user-images.githubusercontent.com/5892849/82291781-920adc80-99e4-11ea-9d86-380734b22259.png)
另外，一般列表，设置了"draggable": true后，还需要点击工具栏的排序按钮才可以排序。这边不用。如果能统一就好了。

**Comment by RickCole21** [comment]
> 嵌套列表，点排序后经常出错（随便点的）。如图，3行的内容变成和4行一样了。

排序应该是没有实现的，只是个演示效果。

---

> 另外，一般列表，设置了"draggable": true后，还需要点击工具栏的排序按钮才可以排序。这边不用。如果能统一就好了。

这个我们需要再看下

**Comment by cnbillow** [comment]
> 排序应该是没有实现的，只是个演示效果。

是上下拖动后，页面显示内容错误。#1的图片显示的情况下，保存会报错。
<pre>
TypeError: Cannot read property 'notifyDied' of undefined
</pre>

**Comment by RickCole21** [comment]
好像没能复现呢😂，有什么特殊操作吗

**Comment by cnbillow** [comment]
一般左右移动鼠标，会容易出现。

**Comment by nwind** [comment]
偶尔复现一次，还没找到规律
