### ISSUE TITLE
InputDatetimeRange 选择截止时间时候，会把开始时间reset到0点

### ISSUE THREAD

**Issue by ozil-cao** [baidu/amis#6032]
#### 描述问题：

使用的时候，开始时间选择2023-01-07 01:01:01，再选择截止时间2023-01-07 02:02:02，点击确定之后，会把开始时间重置为2023-01-07 00:00:00

#### 截图或视频：
![input-datetime-range_bug (1)](https://user-images.githubusercontent.com/16040296/211152051-2c7709d8-a083-4a85-857f-d8d9beaded19.gif)

关联issue [2816](https://github.com/baidu/amis/issues/2816)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk 2.6.0`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
 sdk 2.6.0
在官方文档中，也能复现。https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-datetime-range

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lvvlxu** [comment]
@ozil-cao 你好，这个问题目前还存在的

**Comment by ozil-cao** [comment]
新版本2.9.0已经修复了
