### ISSUE TITLE
CURD组件如何设置导出按钮状态

### ISSUE THREAD

**Issue by ZhenhuaChen** [baidu/amis#6033]
#### 实现场景：
for crud component, when I use export-excel by Api, how can I set the export button state for prevent the button from being triggered multiple times
使用crud组件，通过api导出excel，api接口较慢， 如何设置导出按钮状态，在接口数据还未返回的时候禁止点击按钮

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
 "headerToolbar": [
                {
                  "type": "export-excel",
                  "label": "export",
                  "align": "right",
                  "api": {
                    "url": //xxxxxxx.com/agent/dasboard/export",
                    "method": "post",
                    "headers": {
                      "content-type": "application/json"
                    }
                  }
                }
              ],

```
code here...
```

**Comment by dickchy** [comment]
贡献一个我的解决方案：
`{
  "type": "export-excel",
  "onClick": "document.getElementsByClassName(\"excel-export-btn\")[1].classList.add(\"is-disabled\") \r\n",
  "reload": "",
  "perPageAvailable": [
    10
  ],
  "name": "exportExcelBtn",
  "disabledOn": "",
  "className": "excel-export-btn",
  "label": "导出",
  "api": {
    "headers": {
      "content-type": "application/json"
    },
    "method": "post",
    "url": "/innerApp/appApi/custom/test_crud/crud",
    "adaptor": "document.getElementsByClassName(\"excel-export-btn\")[1].classList.remove(\"is-disabled\");\nreturn {\n    ...payload\n}"
  },
  "align": "right",
  "target": ""
}`

![22af9f14c278a73f3c6c2b940c504ad](https://user-images.githubusercontent.com/2282562/212872501-495b73ef-aeda-48a9-ac9e-215b7f9e8b01.png)

**Comment by BrookYuGit** [comment]
直接用disabledOn属性就可以达到效果，配合在上级组件定义相应的属性作为开关就可以
