### ISSUE TITLE
编辑器添加事件动作，建议可以选择隐藏域表单项

### ISSUE THREAD

**Issue by qianxiaofendou** [baidu/amis#6035]
如下图，在设置组件数据的时候，是不能选择隐藏域表单项(即type='hidden')的，希望可以支持一下，谢谢~~
![image](https://user-images.githubusercontent.com/20673152/211252378-1a22a685-3e75-4144-b7a9-f4a7e79c9286.png)

**Comment by hsm-lv** [comment]
当前版本是支持的，再看一下？
