### ISSUE TITLE
编辑器：希望在编辑模式下不要发出接口请求。

### ISSUE THREAD

**Issue by ellis-s** [baidu/amis#6037]
#### 描述问题：

我使用了 amis-editor 编辑器，在编辑模式下会自动请求 type=page 中配置的 initapi 接口。导致编辑界面出现 loading ，以至于无法继续编辑。

#### 截图或视频：

![amis-editor-screenshot01](https://user-images.githubusercontent.com/23712186/211259023-50f61452-7e17-4d14-b516-37b70fc3f203.png)

![image](https://user-images.githubusercontent.com/23712186/211259475-f3208957-2a1b-4255-81d6-e132fa1dad43.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
```json
"amis": "2.3.0",
"amis-core": "2.3.0",
"amis-editor": "5.2.0-beta.2",
"amis-ui": "2.3.0",
```

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
每次初始化渲染编辑器的时候，就会自动请求 type=page 的 initapi 中配置的接口。

**Comment by EvanZheng11** [comment]
+1

**Comment by hyzx86** [comment]
可以自己修改 amis-editor  的 env 
已经开放了 Preview 接口 结合下，进行判断

**Comment by 2betop** [comment]
楼上的方案可以解决，所以先关了
