### ISSUE TITLE
实时日志不显示ANSI颜色

### ISSUE THREAD

**Issue by GrenAnHao** [baidu/amis#6039]
老版的SDK 使用ANSI是能正常显示的现在最新的不显示ANSI颜色值了
[33m黄色字体:2023年1月9日16时32分54秒[0m 
最新版的2.6.0 SDK 不正常显示，文档也没详细的解释

**Comment by lurunze1226** [comment]
已经下掉日志的高亮显示了，参考https://github.com/baidu/amis/pull/5376

**Comment by GrenAnHao** [comment]
这也太难受了吧
