### ISSUE TITLE
amis/package.json依赖错误

### ISSUE THREAD

**Issue by ranwawa** [baidu/amis#6044]
#### 描述问题：

amis依赖amis-ui和amis-core

但是在dependecies和peerdependencies指定了不同的依赖版本

这导致我在安装amis@2.4.0的时候,自动安装了amis-ui@2.6.0...而amis-ui@2.6.0又是有bug的代码

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm版本大于7+

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

npm install -E amis@2.4.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
  "dependencies": {
    "amis-core": "^2.6.0",
    "amis-ui": "^2.6.0",
 ...
  "peerDependencies": {
    "amis-core": "*",
    "amis-ui": "*",
    "react": ">=16.8.6",
    "react-dom": ">=16.8.6"
  },
```

**Comment by ranwawa** [comment]
这个问题要处理一下哟..

本身我项目是依赖2.5版本的amis,昨天升级的时候把amis-core和amis-ui升级到2.7.0,引起了bug.


修改建议:

1. 去掉amis/package.json. peerDependencies中的amis-core和amis-ui同级依赖
2. 官网文档中引入amis-core和amis-ui的地方全换成通过amis引入(amis本身就导出了这两个包的所有模块)

**Comment by charles-zh** [comment]
我在2.5.0 版本以上，都无法通过编译构建，错误都一样：
Failed to compile.

./node_modules/amis/esm/index.js
Cannot find module: 'amis-core'. Make sure this package is installed.

You can install this package by running: yarn add amis-core.


error Command failed with exit code 1.

暂时回退到2.4.0

**Comment by ranwawa** [comment]
你的邮件我已收到，查收后会尽快回复！：）

**Comment by nwind** [comment]
可以在项目的 package.json 里引入 amis-ui 和 amis-core 依赖
