### ISSUE TITLE
cards如何不被数据填充

### ISSUE THREAD

**Issue by tainlee** [baidu/amis#605]
```
body: {
    type: "cards",

    body: [
      {
        type: "card",
        body: "清除缓存",
      },
  {
        type: "card",
        body: "清除缓存",
      }
]
}
```
如上代码，会默认填充空数据到cards内，显示没有数据
怎么才能不被填充？

**Comment by RickCole21** [comment]
https://baidu.github.io/amis/docs/renderers/Cards#cards

先看看文档哈，你的配置有些问题；

而且该组件一般要配合`service`来使用，默认没有数据就是会显示`没有数据`

**Comment by tainlee** [comment]
其实只是单纯的需要一个横排多个card，然后每个card都对应不同的功能。
所以这个不能用list去渲染。
如果必须做数据填充的话，我会改为grid 处理。
但是希望能加上这个样式

**Comment by RickCole21** [comment]
嗯，你这个需求`grid`更适合哈，cards是需要绑定数据的

**Comment by tainlee** [comment]
多谢指导，速度很快，已star
