### ISSUE TITLE
crud组件用autoGenerateFilter生成的搜索框点击搜索后会刷新当前页面

### ISSUE THREAD

**Issue by GGGxie** [baidu/amis#6059]
crud组件用autoGenerateFilter生成的搜索框，我设置了10个搜索框，会自动折叠，我展开后填入搜索条件，点击搜索后当前页面刷新了，搜索框也被折叠了，预期是仅刷新表格数据，不刷新页面

**Comment by 2betop** [comment]
这个问题很可能是 env 里面 updateLocation 没实现好，是刷新页面的。

最简单的办法是配置 crud 的 syncLocation 属性为 false

**Comment by GGGxie** [comment]
> 

谢谢~
