### ISSUE TITLE
CRUD组件在外部api props变更之后不触发重新获取数据

### ISSUE THREAD

**Issue by chareice** [baidu/amis#606]
https://github.com/baidu/amis/blob/8d74b6ffca5bcdbf3ffe1bbdaec59097e0579c07/src/renderers/CRUD.tsx#L263

这里的判断没有`syncLocation`为`true`但是仅api props变更的情况，所以没有触发，是不是需要支持一下这种情况，把`props.api && nextProps.api`的判断提到最前面

**Comment by RickCole21** [comment]
明天我看一下

**Comment by chareice** [comment]
好的，还发现一个问题是这里重新获取数据的时候，如果之前不是第一页，那么重新获取数据也不是从第一页开始的。

**Comment by 2betop** [comment]
第一个问题，判断在下面呢，api里面的 url 地址运算结果变了才会重新拉取。还有 sendOn 之类的判断。

第二个问题，看是什么触发重新获取，如果时查询条件触发的就会从重新获取第一页的，如果不是，认为时当前页面的刷新操作。
