### ISSUE TITLE
有关each循环和table-view的结合使用

### ISSUE THREAD

**Issue by idjerry** [baidu/amis#6061]
有一部分数据是需要table-view单独一个个表格去设置的，有一部分数据是需要循环的展示的，所以是否table-view能和table一样进行循环数据展示，现在table和table-view的样式有些差异，所以想循环也可以让table-view进行实现

**Comment by nwind** [comment]
table-view 支持这个比较困难，而且难以可视化编辑，目前建议试试 office-view，里面就能做到部分变量部分固定
