### ISSUE TITLE
crud获取上级组件传递的page参数问题

### ISSUE THREAD

**Issue by qianSir01** [baidu/amis#6066]
#### 实现场景：
我想通过page组件或者sevice组件或form组件设置page变量，然后传递到crud组件中。
#### 存在的问题：
debug发现每次刷新后page变量最终都变为1，无法按照指定的page查询数据，这块不清楚是数据域的问题还是crud组件配置问题，
特别说明下：1.6.4版本的时候是正常的，更新到2.1.0版本后，才出现的这个问题。
#### 当前方案：
暂时没有好的方案，有没有思路或者排查或修改方法能提供的，急急急。

```
code here...
```

**Comment by hsm-lv** [comment]
直接给你说的那几个容器类组件配置data即可，例如data:{a:1}，crud直接通过变量名${a}获取即可
