### ISSUE TITLE
数据域变量能否二次赋值？

### ISSUE THREAD

**Issue by wenxiaod** [baidu/amis#6068]
#### 实现场景：
在页面定义初始化数据域，通过事件触发数据请求，请求到数据后对数据域进行赋值
动作配置 - 服务 - 发送请求 - 高级设置 - HTTP配置 - 接收适配器

#### 存在的问题：
**请问在接收适配器当中是否支持对数据域变量的重新赋值？**

#### 当前方案：
数据域的使用方法是： ${table}
在接收适配器中赋值： ${table} = []

```
(payload, response, api) => {
  ${store.table} = [
{
   "name": "张三2",
    "age": 20,
    "tel": 15825822332,
    "addr": "成都"
},
{
  "name": "李四2",
   "age": 18,
    "tel": 13125465876,
    "addr": "广州"
}
];
  return payload;
}
```

**Comment by hsm-lv** [comment]
可以尝试一下setValue这个动作，https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE
