### ISSUE TITLE
Radios组件样式错误无法选择

### ISSUE THREAD

**Issue by Niceyb** [baidu/amis#6070]
#### 描述问题：

移动端Radios组件样式错误无法选择，通过修改样式暂时解决选中问题，但仍存在选中样式与PC端不一致，怀疑组件未将input:checked class添加上去。请查看如何在后续版本中解决此BUG

#### 截图或视频：
原版SDK：
![image](https://user-images.githubusercontent.com/46703349/212589377-b6684344-4dee-4949-a8ce-e22dd70b35dc.png)
效果图：
![46e3e8e5b140a67aec4f0b3497ba46b](https://user-images.githubusercontent.com/46703349/212589304-60d4568e-2849-4de7-82b5-c53ce002d1d7.jpg)
修改后SDK：
![image](https://user-images.githubusercontent.com/46703349/212589595-f86df328-0f1b-4c11-94ec-893e917d466b.png)
效果图：
![image](https://user-images.githubusercontent.com/46703349/212589706-93cfc45b-3a8c-472a-acfa-f7ead69abdc5.png)
此时可选择 但选中样式与PC端不一致
![image](https://user-images.githubusercontent.com/46703349/212589798-64f828d9-fea5-4213-809a-646bd6c80a47.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk` V2.4.0    (高版本同样测试过，存在相同问题)

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
V2.4.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "radios",
  "label": "radios",
  "name": "radios",
  "options": [
    {
      "label": "OptionA",
      "value": "a"
    },
    {
      "label": "OptionB",
      "value": "b"
    },
    {
      "label": "OptionC",
      "value": "c"
    },
    {
      "label": "OptionD",
      "value": "d"
    }
  ],
  "id": "u:2079641514b1",
  "onEvent": {
    "change": {
      "weight": 0,
      "actions": [
        {
          "actionType": "toast",
          "componentId": "",
          "args": {
            "msgType": "info",
            "position": "top-center",
            "closeButton": true,
            "showIcon": true,
            "msg": "${radios}"
          }
        }
      ]
    }
  },
  "value": "a"
}
```

4.修改后的CSS
```
.amis-scope .antd-Checkbox--radio > i {
  cursor: pointer;.amis-scope .antd-Checkbox--radio > i {
  cursor: pointer;
  width: var(--Radio-size);
  height: var(--Radio-size);
  border: 0.0625rem solid var(--Radio-color);
  margin-left: calc(var(--Radio-size) * -1);
  margin-top: -0.125rem;
  border-radius: 50%;
  background-color: transparent;
  left: 0.05rem;
  top: -0.09rem;
}
```
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
目前最新版本看没有这个问题，请升级到最新版本，如有问题再次 open
