### ISSUE TITLE
crud组件请求地址中拼接数据域变量，导致自带的搜索功能不携带参数查询

### ISSUE THREAD

**Issue by primary-ysj** [baidu/amis#6073]
crud组件请求地址中拼接数据域变量，导致自带的搜索功能不携带参数查询

![OHPM SR1Y4W~DQ_LWZ{Z%Q4](https://user-images.githubusercontent.com/67618096/212624102-20fca344-272d-4778-8fb5-61f6b7b01ffb.png)
在官网demo中 请求地址拼接了一个变量 然后
![U BU$4A(`~UD$90F L~B2RA](https://user-images.githubusercontent.com/67618096/212624235-c3a69206-316b-4959-a66b-a727c848b135.png)
filter调用查询时不将参数携带了

具体schema:
{
  "type": "page",
  "data": {
    "env": ""
  },
  "body": {
    "type": "crud",
    "name": "crud",
    "syncLocation": false,
    "api": "/amis/api/mock2/crud/table4${env}",
    "filter": {
      "debug": true,
      "title": "条件搜索",
      "body": [
        {
          "type": "group",
          "body": [
            {
              "type": "input-text",
              "name": "keywords",
              "label": "关键字",
              "clearable": true,
              "placeholder": "通过关键字搜索",
              "size": "sm"
            },
            {
              "type": "input-text",
              "name": "engine",
              "label": "Engine",
              "clearable": true,
              "size": "sm"
            },
            {
              "type": "input-text",
              "name": "platform",
              "label": "Platform",
              "clearable": true,
              "size": "sm"
            }
          ]
        }
      ]
    },
    "columns": [
      {
        "name": "id",
        "label": "ID"
      },
      {
        "name": "engine",
        "label": "Rendering engine"
      },
      {
        "name": "browser",
        "label": "Browser"
      },
      {
        "name": "platform",
        "label": "Platform(s)",
        "canAccessSuperData": false
      },
      {
        "name": "version",
        "label": "Engine version"
      },
      {
        "name": "grade",
        "label": "CSS grade"
      }
    ]
  }
}

**Comment by hsm-lv** [comment]
可以尝试一下新版

**Comment by hsm-lv** [comment]
设计如此，默认api的url里面不配置变量的时候会带上filter的查询变量，但如果你自己配了变量就不会自动给你追加query变量了，因此如果想要实现你要的功能，需要自己把需要的变量补到url上面
