### ISSUE TITLE
InputTree中节点label如何自定义

### ISSUE THREAD

**Issue by jackhansir** [baidu/amis#6074]
![DB675129-F973-4292-AF8B-B21DFA10F64E](https://user-images.githubusercontent.com/26846260/212630832-fed2a77a-8aa2-4a71-b271-1c25e38ceeed.png)
如何自定义label节点

**Comment by meerkat-morecats** [comment]
这个还不支持

**Comment by hsm-lv** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-tree#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%89%E9%A1%B9%E6%B8%B2%E6%9F%93
