### ISSUE TITLE
如何让crud组件在多选时能够回显选中项

### ISSUE THREAD

**Issue by jackhansir** [baidu/amis#6075]
![B6D3C469-BDA8-476c-922A-BE9440C9DAF1](https://user-images.githubusercontent.com/26846260/212631502-0ae0587f-bebd-4f38-9946-31384908e236.png)
如何让选中状态回显

**Comment by meerkat-morecats** [comment]
@jackhansir 需要再补充一些描述信息，这个描述信息太简单了，不太知道你想要达到什么样的效果。例如在什么情况下显示？

**Comment by jackhansir** [comment]
> @jackhansir 需要再补充一些描述信息，这个描述信息太简单了，不太知道你想要达到什么样的效果。例如在什么情况下显示？

在编辑页面中，如果有crud的多选表格，初始化的时候会有选中状态，需要回显在表格中，这个在开发中应该也会常遇到

**Comment by meerkat-morecats** [comment]
> > @jackhansir 需要再补充一些描述信息，这个描述信息太简单了，不太知道你想要达到什么样的效果。例如在什么情况下显示？
> 
> 在编辑页面中，如果有crud的多选表格，初始化的时候会有选中状态，需要回显在表格中，这个在开发中应该也会常遇到

可以使用 Picker 组件，CRUD不支持

**Comment by jackhansir** [comment]
> > > @jackhansir 需要再补充一些描述信息，这个描述信息太简单了，不太知道你想要达到什么样的效果。例如在什么情况下显示？
> > 
> > 
> > 在编辑页面中，如果有crud的多选表格，初始化的时候会有选中状态，需要回显在表格中，这个在开发中应该也会常遇到
> 
> 可以使用 Picker 组件，CRUD不支持

好的，谢谢
