### ISSUE TITLE
crud如何控制参数的默认类型和默认值

### ISSUE THREAD

**Issue by Henrik-Yao** [baidu/amis#6077]
#### 存在的问题：

![image](https://user-images.githubusercontent.com/77136892/212655072-2bded89c-44c6-4b63-84b6-0c03bf3d4218.png)

当visibleOn为false时候，amis并不会去将videos参数初始化成数组类型

![image](https://user-images.githubusercontent.com/77136892/212655538-1095e4bf-89e4-48bc-8091-2a6cbac1b8fb.png)
导致参数传递存在一些问题

#### 当前方案：
"dialog": {
                "title": "。。。。。。",
                "body": {
                    "type": "form",
                    "name": "crowd-task",
                    "debug": true,
                    "api": {
                        "method": "post",
                        "url": "。。。。。",
                        "data": {
                            。。。。。。
                            "videos": "${videos}",
                            "origin_images": "${origin_images}",
                            "packed_images": "${packed_images}"
                        }
                    },
                    "controls": [
                       。。。。。
                        {
                            "type": "select",
                            "label": "选择 demo 类型",
                            "name": "demo_type",
                            "options": [
                                {
                                    "label": "图片",
                                    "value": "image"
                                },
                                {
                                    "label": "视频",
                                    "value": "video"
                                }
                            ],
                            "size": "sm",
                            "required": true
                        },
                        {
                            "type": "input-image",
                            "multiple": true,
                            "label": "上传图片",
                            "visibleOn": "data.demo_type == 'image'",
                            "receiver": {
                                "method": "post",
                                "url": "。。。。。",
                                "data": {
                                    "parent": "crowd-task",
                                    "pack_width": 300,
                                    "pack_height": 300
                                }
                            },
                            "autoFill": {
                                "origin_images": "${items|pick:orig_path}",
                                "packed_images": "${items|pick:pack_path}"
                            }
                        },
                        {
                            "type": "input-file",
                            "label": "上传视频",
                            "multiple": true,
                            "visibleOn": "data.demo_type == 'video'",
                            "receiver": "。。。。。。",
                            "autoFill": {
                                "videos": "${items|pick:vid}"
                            }
                        }
                    ]
                }
            }

**Comment by meerkat-morecats** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/options#%E6%8F%90%E5%8F%96%E5%A4%9A%E9%80%89%E5%80%BC-extractvalue
