### ISSUE TITLE
你好请问下我该通过什么构件可以实现把如下的惊悚数据传递给接口

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#608]
"headers": {
        "traceId": "dabf842116889c41",
        "X-ClientVersion": "71103",
        "X-UserId": "53820",
        "prelogid": "11e1c7f5fc6b868da59432c6cc2ac743",
        "X-LBS": "116.634751,39.924353",
        "X-Region": "1",
        "rpcId": "1",
        "deviceModel": "SEA-AL10",
        "subAppVersionNumber": "",
        "X-Grade": "1",
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": "okhttp/3.11.0"
      }
其中headers里边的还能动态添加，比如用户在两个框内分别输入User-Agent和okhttp/3.11.0就能把数据拼装上去

**Comment by RickCole21** [comment]
可以参考这个思路：
```
{
    "type": "form",
    "title": "表单",
    "controls": [
        {
            "type": "text",
            "label": "headerKey",
            "name": "headerKey"
        },
        {
            "type": "text",
            "label": "headerValue",
            "name": "headerValue"
        }
    ],
    "api": {
        "method": "post",
        "url": "/api/mock2/form/saveForm",
        "requestAdaptor": "api.headers = api.headers || {};\napi.headers[api.data.headerKey] = api.data.headerValue;\n\nreturn api;"
    }
}
```
---

效果图：

![image](https://user-images.githubusercontent.com/19327810/82421210-48d58e00-9ab3-11ea-94c8-de3f3f1abdc9.png)

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/82424671-17ab8c80-9ab8-11ea-8d0b-cd3354828540.png)
我的是这样的，不是在请求的header里边添加数据，我是有一个如上图的表单，
Headers下边的表格就是添加的headers字段的内容，我是把这些表单里边的内容传到后台接口，这个我该咋实现呢？现在是下图中的样子
![image](https://user-images.githubusercontent.com/64950961/82425025-8e488a00-9ab8-11ea-9c4e-f3bb7e077f8e.png)

**Comment by RickCole21** [comment]
给`form`配提交接口`api`？你问题是这个？

还是说想把`headers`数组转成对象形式

**Comment by tanmengfei** [comment]
我的期望是这种对象的样式
"headers": {
        "traceId": "dabf842116889c41",
}，
但是我得到的是数组形式
"headers": [
        {
          "headerKey": "traceId",
          "headerValue": "dabf842116889c41"
        }
      ]

**Comment by RickCole21** [comment]
还是一样，在`requestAdaptor`里写逻辑吧，js自己处理一下就行

**Comment by RickCole21** [comment]
哦你可以在requestAdaptor操作data，然后返回出去，这样
```
let headerObj = {};
api.data.headers.forEach(h=>headerObj[h. headerKey] === api.data.headers. headerValue)

return {
  ...api,
  data:{
    ...api.data,
    headers:headerObj
  }
}
```

**Comment by tanmengfei** [comment]
刚才试了下，目前表格里边的json数据是这样的
{
  "interface": [
    {
      "method": "POST",
      "headers": [
        {
          "headerKey": "111",
          "headerValue": "111"
        }
      ],
      "type": "form-data"
    }
  ]
}
然后我这个是不是改加一个interface数组，然后我把代码改成了这样
let headerObj = {};
api.data.interface[0].headers.forEach(h=>(headerObj[h. headerKey] = api.data.interface[0].headers.headerValue))

return {
  ...api,
  data:{
    ...api.data,
    headers:headerObj
  }
}
然后还是不太行

**Comment by RickCole21** [comment]
自己debugger调试吧
