### ISSUE TITLE
Pagination组件表现形式和组件示例不同

### ISSUE THREAD

**Issue by jackhansir** [baidu/amis#6081]
![72C5B16F-3F63-424b-BD67-947581C77846](https://user-images.githubusercontent.com/26846260/212788192-5f70440d-7f7a-44e6-8737-2b17c13f3782.png)
1、把pagination组件全部复制到curd中，示例展示共多少条，curd表现为共多少页
2、perPage切换器，切换到只展示一页数据时，分页就会消失，例：有14条数据，切换成一页20条数据，分页就不存在，不能切回到一页10条数据

**Comment by meerkat-morecats** [comment]
> ![72C5B16F-3F63-424b-BD67-947581C77846](https://user-images.githubusercontent.com/26846260/212788192-5f70440d-7f7a-44e6-8737-2b17c13f3782.png) 1、把pagination组件全部复制到curd中，示例展示共多少条，curd表现为共多少页 2、perPage切换器，切换到只展示一页数据时，分页就会消失，例：有14条数据，切换成一页20条数据，分页就不存在，不能切回到一页10条数据

第二点可以加一个 alwaysShowPagination
