### ISSUE TITLE
amis-editor-demo 报错: Cannot find module `node_modules/amis-theme-editor/lib/renderers.css`

### ISSUE THREAD

**Issue by sia-fl** [baidu/amis#6088]
#### 描述问题：

安装 amis-editor-demo 后，启动报错：Cannot find module `node_modules/amis-theme-editor/lib/renderers.css`

#### 截图或视频：

Uncaught [ModJS] Cannot find module `node_modules/amis-theme-editor/lib/renderers.css`

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

node v16.19.0
npm 8.19.3

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

amis-editor-demo 1.0
amis-editor-demo 包含的 amis 2.6.0

4. 粘贴有问题的完整 `amis schema` 代码：

git clone [master](https://github.com/aisuda/amis-editor-demo.git)

5. 操作步骤

npm i
npm run start
npm run dev

**Comment by sia-fl** [comment]
https://user-images.githubusercontent.com/39842393/213203693-e6957feb-3270-4cd0-9306-ef92115921dd.mp4

**Comment by 17** [comment]
fis 配置问题，无法导入 css ，调整一下 fis3 配置。

**Comment by haifding** [comment]
> fis 配置问题，无法导入 css ，调整一下 fis3 配置。

能否具体说一下如何调整吗？百度不到

**Comment by 17** [comment]
> 能否具体说一下如何调整吗？百度不到

https://github.com/fex-team/fis3-preprocessor-js-require-css

**Comment by relaxing0314** [comment]
在配置fis.match('amis/**.js', {
	preprocessor: fis.plugin('js-require-css')
});下面添加配置fis.match('amis-editor/**.js', {
	preprocessor: fis.plugin('js-require-css')
});可以解决这个问题

**Comment by wibetter** [comment]
请使用新版amis-editor-demo（https://github.com/aisuda/amis-editor-demo.git），新版示例改用webpack实现前端工程。
