### ISSUE TITLE
crud get api 带参数问题

### ISSUE THREAD

**Issue by chenos** [baidu/amis#609]
下面例子情况下翻页，排序，defaultParams 等情况都无效。

```json
{
  "type": "crud",
  "api": "/posts/$postId/comments",
  "defaultParams": {
      "orderBy": "created_at",
      "orderDir": "asc"
    }
}
```

https://github.com/baidu/amis/blob/8d74b6ffca5bcdbf3ffe1bbdaec59097e0579c07/src/utils/api.ts#L89-L99

源码来看，现在只在有 api.data，或者 post/put 请求，或者 url 不带 $ 的时候才把 data merge 进来。

**Comment by 2betop** [comment]
是这样的，一旦有 `$` 去变量，url 就是白名单模式了，意思是不会把所有可能有用的数据都发过去，而是用户配置了什么就发送什么。

**Comment by chenos** [comment]
> 一旦有 $ 去变量

用 $ 去控制白名单会不会不太合理呢？而且还有个 ignoreData

**Comment by 2betop** [comment]
ignoreData 并不 schema 配置上的东西，ignoreData 是为了快速 diff api 的 url 结果是否有变化加的参数。

白名单模式我感觉挺合理啊，用户已经主动配置参数了，那应该是要严格点，只发送他配置了的。因为很可能他会问这个参数我没有配置怎么会发送，如何去掉？目前没有规则可以干掉多的参数，倒是如果用户发现发送少了，可以补上需要的。比如你这个栗子就可以 `/posts/$postId/comments?page=${page}&orderBy=${orderBy}&orderDir=${orderDir}`

**Comment by chenos** [comment]
那可以判断一下 $ 的位置么？比如在 path 上就不算，如果不是参数的 $ ，这样是不是直接就给误杀了？

**Comment by chenos** [comment]
$postId 是要指定的，后面那些参数是动态的，没办法像上面给的例子那样固定拼接

**Comment by 2betop** [comment]
不确定行不行，你试试这个用法 `/posts/$postId/comments?&=$$`

**Comment by 2betop** [comment]
或者 

`
 api: {
   method: 'get',
  url: '/posts/$postId/comments',
  data: {&: '$$'}
}
`

**Comment by chenos** [comment]
@2betop `?&=$$` 拼接的不行，object 的这种 OK
