### ISSUE TITLE
actionType:download 文件下载功能能不能支持文件名自定义

### ISSUE THREAD

**Issue by jwxhhxx** [baidu/amis#6096]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by lurunze1226** [comment]
服务端的header里可以设置Content-Disposition的filename，或者使用[saveAs](https://aisuda.bce.baidu.com/amis/zh-CN/components/action#%E4%BF%9D%E5%AD%98%E5%88%B0%E6%9C%AC%E5%9C%B0)

**Comment by lvjinwei1688** [comment]
您好 我想问一下saveAs 如何传递请求参数 @lurunze1226  我使用saveAs可以解决下载error Should have "Content-Disposition" in Header问题 但他无法传参
