### ISSUE TITLE
"affixFooter": true, 底部固定，拉倒最下面， 会出现两行工具条

### ISSUE THREAD

**Issue by tangtangsara** [baidu/amis#6097]
chrome版本 109.0.5414.74（正式版本） （64 位）
amis 2.6.0 
底部固定，拉倒最下面， 会出现两行工具条
如图

![image](https://user-images.githubusercontent.com/11268163/213410663-0401d7aa-8e83-43fb-a567-2bf3f31d9bd5.png)

![image](https://user-images.githubusercontent.com/11268163/213412357-a81a13eb-73dc-428f-bbd6-235a355f6b6c.png)

**Comment by tangtangsara** [comment]
这个问题 之前好多amis版本都存在，不知道是不是我使用不当

**Comment by meerkat-morecats** [comment]
> 这个问题 之前好多amis版本都存在，不知道是不是我使用不当

1. 方便的话提供一下完整的schema吧
2. 有没有在容器外边或容器上增加什么css样式呢，一般css样式可能会影响到定位
3. 截图看一下两个元素的class名字分别是啥

**Comment by tangtangsara** [comment]
我的问题 ， 经过提醒找到了问题， 
<style>
        html,
        body,
        .app-wrapper {
            position: relative;
            width: 100%;
            min-height: 980px;
            margin: 0;
            padding: 0;
        }
    </style> 这个定义引起了以上问题 。改成了和demo一样的样式定义，已经可以了
