### ISSUE TITLE
表单提交期望只更新变化的数据

### ISSUE THREAD

**Issue by superduper-wkl** [baidu/amis#6099]
#### 实现场景：
想请问下，表单提交期望只上传变化的数据如何实现

#### 存在的问题：
目前标签提交是将全部字段都上传到后台服务了

#### 当前方案：

```
code here...
```

**Comment by hyzx86** [comment]
自己实现一个 过滤器 或者 注入一个公共函数
比如 var params= window.objectDiff(a,b)
api.body=params
return api

**Comment by superduper-wkl** [comment]
> 自己实现一个 过滤器 或者 注入一个公共函数 比如 var params= window.objectDiff(a,b) api.body=params return api

感谢，文档上找到了
https://baidu.github.io/amis/zh-CN/components/form/index#%E8%A1%A8%E5%8D%95%E6%8F%90%E4%BA%A4

**Comment by superduper-wkl** [comment]
https://baidu.github.io/amis/zh-CN/components/form/index#%E8%A1%A8%E5%8D%95%E6%8F%90%E4%BA%A4

发送请求默认为 POST 方式，会将所有表单项整理成一个对象发送过过去。除此之外你可以主动获取以下信息。

diff 只会包含 diff 结果
prinstine 原始数据 如:
