### ISSUE TITLE
作为百度的RD没有可视化编辑器学起来有点难哇

### ISSUE THREAD

**Issue by BenwinC** [baidu/amis#61]
求开源可视化编辑器

**Comment by 2betop** [comment]
你的诉求是外部版本可用的可视化编辑器？不在乎是否开源？

**Comment by x8edu** [comment]
能用也是极好的

**Comment by tongluyang** [comment]
@2betop 请问闭源版的可视化编辑器有计划什么时候放出吗，作为工具用

**Comment by 2betop** [comment]
计划是这个 Q，放出来之前还想再优化优化

**Comment by tongluyang** [comment]
@2betop 感谢 👍

**Comment by MrStrangeBao** [comment]
@2betop 厉害,期待,我写了一半现在不写了,等待...;

**Comment by sskf** [comment]
@2betop 

> 计划是这个 Q，放出来之前还想再优化优化

@2betop 是准备做类似于https://www.bootcss.com/p/layoutit/ 这样的可视化编辑器吗，如果是的话就太好了，坐等

**Comment by tfzxyinhao** [comment]
坐等

**Comment by MrStrangeBao** [comment]
期待

**Comment by 2betop** [comment]
http://fex-team.github.io/amis-editor
