### ISSUE TITLE
redirect可以支持window.relpace方式的跳转吗

### ISSUE THREAD

**Issue by shayminsky** [baidu/amis#610]
redirect可以支持relpace方式的跳转吗

**Comment by 2betop** [comment]
感觉你的需求是刷新当前页面？直接 reload: "window"

**Comment by shayminsky** [comment]
> 感觉你的需求是刷新当前页面？直接 reload: "window"

a页面跳到b页面然后history不想留下a的history state

**Comment by 2betop** [comment]
目前还不支持呢，不过，可以自己实现，毕竟 env.updateLocation 是可以传入的，你可以根据跳转目标地址采用是 replace 还是 push

**Comment by shayminsky** [comment]
> 目前还不支持呢，不过，可以自己实现，毕竟 env.updateLocation 是可以传入的，你可以根据跳转目标地址采用是 replace 还是 push
感谢，通过传入updateLocation或jumpTo方法判断确实可以。如果能和blank一样作为action的属性的话感觉会更方便一些？在目前的jumpto方法里多进行一个action的属性的判断就行了吧

**Comment by nwind** [comment]
参考 2betop 的实现方法
