### ISSUE TITLE
AMIS Page 组件 初始化 initApi 不执行了

### ISSUE THREAD

**Issue by hyzx86** [baidu/amis#6100]
#### 描述问题：

最近更新到 2.6.1-alpha.0 后发现 页面初始化数据用的API失效了
2.6.0 也无法初始化
#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`... 

pnpm in antd esign pro 6

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.6.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "id": "u:23a9b0dfb67a",
  "regions": [
    "body",
    "header"
  ],
  "initApi": {
    "url": "http://baidu.com",
    "method": "get"
  }
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by hyzx86** [comment]
编辑器中预览没问题，
但是用amis 渲染时就不行了

**Comment by gexMichael** [comment]
+1

**Comment by hyzx86** [comment]
+1

**Comment by 2betop** [comment]
已不能复现，请升级到最新版本看看，如果有问题再开此 issue
