### ISSUE TITLE
amis-ui/lib/components/Editor定义全局window.MonacoEnvironment导致非amis的monaco editor无法正常使用

### ISSUE THREAD

**Issue by BrookYuGit** [baidu/amis#6106]
【问题】
amis-ui/lib/components/Editor定义全局window.MonacoEnvironment导致非amis的monaco editor无法正常使用
这会影响软件中其他使用到非amis控制的组件的monaco editor的使用。自定义的语法无法正常显示，比对模式的颜色也发生异常。
【截图】
无
【复现】
1.使用amis的sdk方式在vue3工程中使用。
2. amis 版本2.6.0

**Comment by BrookYuGit** [comment]
暂时的解决方式是在引入sdk.js后执行delete window.MonacoEnvironment

**Comment by 2betop** [comment]
已经改成优先试用用户定义了 https://github.com/baidu/amis/blob/master/packages/amis-ui/src/components/Editor.tsx#L19

**Comment by gogoLJY** [comment]
上面修复方法有漏洞，如果先进入了使用 amis 页面，加载了这段代码，window.MonacoEnvironment 已经赋值，再次进入其他非amis的页面，非amis 的 monaco editor 无法正常使用
