### ISSUE TITLE
Form/InputText组件clear时仅未触发change事件

### ISSUE THREAD

**Issue by BrookYuGit** [baidu/amis#6109]
Form/InputText组件clear时仅未触发change事件
【问题】
在该组件中仅可以通过TextControl.prototype.handleInputChange触发change事件。该组件的clearValue()方法仅触发了onChange回调，并不会触发一个change事件。
【问题的起因】
我在vue3中通过sdk使用amis，很多的事件都是需要通过js脚本进行处理。onEvent中actionType为custom的参数和onChange的参数不同，onEvent的参数要更丰富一些，可以进行一些更多的自定义的一些处理。
【导致的现象】
当需要监听input-text的内容变化时，仅设置onEvent:{change:{actions:[...]}}是不够的，必须通过onChange属性进行监听，但是这两个属性提供的参数（或者说props?）是不一样的，例如通过onEvent可以再次触发其他事件（例如弹出另外一个dialog、关闭dialog等），但是onChange好像不容易做到这点。
【建议】
要么在各种组件的clear处理中触发必要的event事件，要么扩展onChange这种属性，使其可以支持覆盖到event事件的参数。
【其他组件是否有类似问题？】
类似的其他组件是否也存在clear时无法触发chang事件的情况？

**Comment by hsm-lv** [comment]
目前的实现只会在用户操作时触发，后面会支持间接触发
