### ISSUE TITLE
从db中加载schema

### ISSUE THREAD

**Issue by chenyphaaa** [baidu/amis#611]
可以从db中加载schema文件吗？目前看只能在代码路径下加载相关文件

**Comment by RickCole21** [comment]
`service`的`schemaApi`满足需求么

https://baidu.github.io/amis/docs/renderers/Service#%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE

https://baidu.github.io/amis/docs/renderers/Form/Service#service-formitem-
