### ISSUE TITLE
如何让 Table 中的 Switch 列发送请求前弹出确认对话框？

### ISSUE THREAD

**Issue by zybzzc** [baidu/amis#6115]
#### 实现场景：
在 Table 或 CURD 中对 Switch 列的开关操作加一层确认对话框

#### 存在的问题：
Switch 组件本身不支持该功能，通过加一个 Button 包装后可以弹出对话框，但是被包裹的 Switch 组件却无法接收到行数据中的值

#### 当前方案：
```json
{
      "name": "boolean",
      "label": "开关",
      "type": "button",
      "actionType": "ajax",
      "confirmText": "确认要更改？",
      "body": {
        "type": "switch",
        "value": "${boolean}" // 无法将 $row.boolean 的值传给 Switch 组件
      },
      "api": "@switch:/amis/api/mock2/sample/${id}:boolean"
}
```

**Comment by zybzzc** [comment]
@meerkat-morecats 
取消或失败时不是设置成false，而是退回到原状态，问题是我怎么在 `setValue` 时拿到当前行中的 `switch` 的值?

**Comment by meerkat-morecats** [comment]
> @meerkat-morecats 取消或失败时不是设置成false，而是退回到原状态，问题是我怎么在 `setValue` 时拿到当前行中的 `switch` 的值?

直接在column里配置 switch组件呢

**Comment by zybzzc** [comment]
> 直接在column里配置 switch组件呢

直接配置 switch 组件则没有办法配置 action 和 confirmText

我现在能想到的方案是封装一个 ActionSwitch 组件来实现

**Comment by BrookYuGit** [comment]
可以通过修改SwitchControl、Switch源代码实现需求。大概思路是：通过配置column，增加一个ignorecheck属性和一个自定义的ignorecheck事件。通过这两个属性达到需要的效果：点击switch时不切换值，且不触发change事件，而是通过ignorecheck事件自己进行后续的逻辑处理，点击confirm后会通过内部未公开的逻辑再设置crud组件的data值。
其中用到了一些未公开的方法，例如action事件的第三个参数涉及的context及parent属性等。
具体步骤（使用的amis版本为2.6.0，我是使用sdk方式在vue3中使用，需要一些特殊方法，将源代码补丁到sdk.js中）：
1）schema配置：
{
            "name": "boolean",
            visible: false,
            "label": "开关",
            "type": "switch",
            ignorecheck:true,
            onEvent: {
              ignorecheck: {
                actions: [
                {
                    actionType: 'dialog',
                    expression:'${boolean}',
                    dialog:{
                      title: '确认要更改？',
                      onEvent: {
                        confirm: {
                          actions: [
                            {
                              "actionType": "custom",
                              script:"let crud, parent = arguments[2].context.scoped;\
                                  while(parent && !crud) {\
                                    crud = parent.getComponents().find(ele => ele.props.type == 'crud');\
                                    parent = parent.parent;\
                                  }\
                                  let item = crud.props.data.items.find(ele => ele.id = arguments[2].data.id);\
                                  item.boolean = !item.boolean;\
                                  crud.props.store.reInitData(crud.props.store.data, false);",
                              script2:(a,b,c,d) => {
                                Promise.resolve(true)
                                .then( () => {
                                  let crud, parent = c.context.scoped;
                                  while(parent && !crud) {
                                    crud = parent.getComponents().find(ele => ele.props.type == 'crud');
                                    parent = parent.parent;
                                  }
                                  let item = crud.props.data.items.find(ele => ele.id = c.data.id);
                                  item.boolean = !item.boolean;
                                  crud.props.store.reInitData(crud.props.store.data, false);
                                })
                              },
                            },
                          ]
                        },
                      }
                    }
                  },
                ],
              },
            }
          }
2）修改Switch的onClick事件处理代码，如下：
Switch.prototype.hanldeCheck = function (e) {
            var _a = this.props, trueValue = _a.trueValue, falseValue = _a.falseValue, onChange = _a.onChange;
            **if (_a.ignorecheck) {
                e.stopPropagation();
                if (onChange) {
                    onChange('ignorecheck')
                }
            }**
            if (!onChange) {
                return;
            }
            onChange(e.currentTarget.checked ? trueValue : falseValue);
        };
3）需要将schema中的ignorecheck属性传递到react：
SwitchControl.prototype.render = function () {
            var _a = this.props, size = _a.size, className = _a.className; _a.style; var ns = _a.classPrefix, cx = _a.classnames, value = _a.value, trueValue = _a.trueValue, falseValue = _a.falseValue; _a.onChange; var disabled = _a.disabled;
            var _b = this.getResult(), on = _b.on, off = _b.off;
            return (React__default["default"].createElement("div", { className: cx("SwitchControl", className) }, this.renderBody(React__default["default"].createElement(amisUi.Switch, { classPrefix: ns, value: value, trueValue: trueValue, falseValue: falseValue, onText: on, offText: off, disabled: disabled, onChange: this.handleChange, size: size, **ignorecheck:_a.ignorecheck** }))));
        };
4）再修改SwitchController的onChange事件处理代码：
SwitchControl.prototype.handleChange = function (checked) {
            return tslib.__awaiter(this, void 0, void 0, function () {
                var _a, dispatchEvent, onChange, rendererEvent;
                return tslib.__generator(this, function (_b) {
                    switch (_b.label) {
                        case 0:
                            _a = this.props, dispatchEvent = _a.dispatchEvent, onChange = _a.onChange;
                            **if (checked === 'ignorecheck') {
                                return [4 /*yield*/, dispatchEvent('ignorecheck', amisCore.resolveEventData(this.props, { value: _a.data }, 'value'))];    
                            }**
                            return [4 /*yield*/, dispatchEvent('change', amisCore.resolveEventData(this.props, { value: checked }, 'value'))];
                        case 1:
                            rendererEvent = _b.sent();
                            if (rendererEvent === null || rendererEvent === void 0 ? void 0 : rendererEvent.prevented) {
                                return [2 /*return*/];
                            }
                            **if (checked === 'ignorecheck') {
                                return [2 /*return*/];
                            }**
                            onChange && onChange(checked);
                            return [2 /*return*/];
                    }
                });
            });
        };

**Comment by BrookYuGit** [comment]
如果可以接受先改值，然后弹对话框确认，待取消时再恢复原值。可以用如下方法，无需改动源代码或增加组件。用到了一些内部的逻辑。
···
         {
            "type": "switch",
            "label": "开关",
            "name": "boolean",
            "onEvent": {
              "change": {
                "actions": [
                  {
                    "actionType": "dialog",
                    "dialog": {
                      "body": "确定切换？",
                      "onEvent": {
                        "cancel": {
                          "actions": [
                            {
                              "actionType": "custom",
                              "script":"let crud, parent = arguments[2].context.scoped, count = 0;\
                                console.log('event', event.data);\
                                while(parent && !crud && count++ < 10) {\
                                  crud = parent.getComponents().find(ele => ele.props.type == 'crud');\
                                  parent = parent.parent;\
                                };\
                                let table = crud.context.getComponents().find(ele => ele.props.type == 'table');\
                                let items = table.props.data.items;\
                                let item = items.find(ele => ele.id == event.data.id);\
                                item.boolean = !event.data.boolean;\
                                table.props.store.initRows(items);\
                                "
                            }
                          ]
                        },
                      }
                    }
                  }
                ]
              }
            }
          },
···

**Comment by zybzzc** [comment]
@BrookYuGit 
script 的这个方案太过复杂、难以测试与维护，并且也不符合 amis 设计原则，只能作为一种临时 hack 的方案。

**Comment by BrookYuGit** [comment]
> @BrookYuGit script 的这个方案太过复杂、难以测试与维护，并且也不符合 amis 设计原则，只能作为一种临时 hack 的方案。

做前台可能不太适用，但是做后台管理系统，这个方式还是可以的。可以做到灵活控制CRUD的数据，这个特性是做后台管理的基础特性。

**Comment by hsm-lv** [comment]
> @meerkat-morecats 取消或失败时不是设置成false，而是退回到原状态，问题是我怎么在 `setValue` 时拿到当前行中的 `switch` 的值?

在动作里直接通过name取值即可，例如${name}

**Comment by hsm-lv** [comment]
可以这样，不过需要等下个版本，下个版本覆盖了确认提示点击取消后，不修改switch的值的场景：
```json
{
    "type": "crud",
    "syncLocation": false,
    "api": "/api/mock2/sample",
    "columns": [
        {
            "name": "id",
            "label": "ID",
            "id": "u:daa79afa2e53"
        },
        {
            "name": "engine",
            "label": "Rendering engine",
            "id": "u:3343cf518656"
        },
        {
            "name": "browser",
            "label": "Browser",
            "id": "u:fbdc85e45e2f"
        },
        {
            "name": "platform",
            "label": "Platform(s)",
            "id": "u:ccdb48cc1804"
        },
        {
            "name": "switch",
            "label": "开关",
            "id": "u:30a36768acce",
            "type": "switch",
            "inline": true,
            "onEvent": {
                "change": {
                    "weight": 0,
                    "actions": [
                    {
                        "actionType": "confirmDialog",
                        "dialog": {
                        "type": "dialog",
                        "title": "弹框标题",
                        "body": [
                            {
                            "type": "tpl",
                            "tpl": "确定要修改${id}吗？",
                            "wrapperComponent": "",
                            "inline": false,
                            "id": "u:1965506c7599"
                            }
                        ],
                        "showCloseButton": true,
                        "showErrorMsg": true,
                        "showLoading": true,
                        "className": "app-popover",
                        "id": "u:d9783223df98",
                        "actions": [
                            {
                            "type": "button",
                            "actionType": "cancel",
                            "label": "取消",
                            "id": "u:302efee8613b"
                            },
                            {
                            "type": "button",
                            "actionType": "confirm",
                            "label": "确定",
                            "primary": true,
                            "id": "u:4a4d63cf35e1"
                            }
                        ]
                        }
                    },
                    {
                        "actionType": "ajax",
                        "outputVar": "responseResult",
                        "options": {
                        },
                        "api": {
                        "method": "get",
                        "url": "/api/mock2/form/saveForm"
                        }
                    }
                    ]
                }
            },
            "value": false
    }
    ],
    "id": "u:6c781a765f97"
}
```
