### ISSUE TITLE
JSSDK：从2.6.0升级到2.7.0 后，报 Uncaught [ModJS] Cannot find module

### ISSUE THREAD

**Issue by Tomao2014** [baidu/amis#6119]
#### 描述问题：

项目使用传统的开发模式，使用的是JSSDK，尝试将版本从2.6.0升级到2.7.0 后，报 Uncaught [ModJS] Cannot find module...

而切换回2.6.0版本时，则能够正常访问。

#### 截图或视频：

![image](https://user-images.githubusercontent.com/46468204/215984505-2da2adf0-1794-499c-83b1-fa9a665f87e2.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
`2.7.0` 出现异常，`2.6.0`正常

3. 粘贴有问题的完整 `amis schema` 代码：

![image](https://user-images.githubusercontent.com/46468204/215985277-4165f448-a874-449b-bac3-43c8ed8f8ceb.png)

4. 操作步骤
无

**Comment by xiahao90** [comment]
+1

**Comment by lurunze1226** [comment]
升级到[2.7.1](https://github.com/baidu/amis/releases/tag/v2.7.1 )试试吧

**Comment by Tomao2014** [comment]
升级到2.71.版本，问题解决
