### ISSUE TITLE
图表渲染错误无法加载static/js/charts.js

### ISSUE THREAD

**Issue by bulubird** [baidu/amis#6121]
#### 实现场景：
我想要加载一个最简单的图表

#### 存在的问题：
我自己本地开发环境，charts.js从/static/js/charts.js加载，这个文件不存在

#### 当前方案：

```
code here...
```

**Comment by meerkat-morecats** [comment]
看起来像是你本地配置的路径有问题？

**Comment by bulubird** [comment]
> 看起来像是你本地配置的路径有问题？

本地没有做过什么配置，只是用了amis.embed()去加载了如下的json页面就报错了：
{
  "type": "chart",
  "config": {
    "xAxis": {
      "type": "category",
      "data": [
        "Mon",
        "Tue",
        "Wed",
        "Thu",
        "Fri",
        "Sat",
        "Sun"
      ]
    },
    "yAxis": {
      "type": "value"
    },
    "series": [
      {
        "data": [
          820,
          932,
          901,
          934,
          1290,
          1330,
          1320
        ],
        "type": "line"
      }
    ]
  },
  "replaceChartOption": true,
  "id": "u:4ac345c0a1be",
  "name": "page-1"
}

试着跟了一下打包后的amis代码，发现在node_modules/amis/lib/renderers/Chart.js中如下引入了echarts：
Promise.resolve().then(function() {return new Promise(function(fullfill) {require(['echarts'], function(mod) {fullfill(tslib.__importStar(mod))})})}),
然后这个echarts路径是这样被resolve的：
![image](https://user-images.githubusercontent.com/124143558/216048711-2fcff070-74d4-445c-8823-20b20c88b7e4.png)
这里的host就是我本地地址localhost:8080/static/js，然后我本地确实没有这个文件

下面是amis打包配置的代码：
      'charts.js': ['zrender/**', 'echarts/**', 'echarts-stat/**']
