### ISSUE TITLE
InputDateRange日期选择显示效果错乱

### ISSUE THREAD

**Issue by smile1102** [baidu/amis#6123]
#### 描述问题：

InputDateRange多次操作选择开始和结束时间，界面显示的选中效果错乱

#### 截图或视频：

![image](https://user-images.githubusercontent.com/12440651/216011217-7b9c1133-e655-4b55-a243-45d94e560ac0.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网案例

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v2.7.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "input-date-range",
        "name": "date",
        "label": "日期范围",
        "value": "1659283200,1661961599"
      }
    ]
  }
}
```

4. 操作步骤
先选择开始时间，再选择结束时间，重复操作几遍即可重现

**Comment by 2betop** [comment]
新版本已经修复，请更新到最新版本
