### ISSUE TITLE
渲染 HTML 变量

### ISSUE THREAD

**Issue by UltramanWeiLai** [baidu/amis#6124]
#### 实现场景：
富文本编辑并且保存后的 html 代码片段，回显；

#### 存在的问题：
找不到可以动态渲染 html 变量的组件和方法

**Comment by lurunze1226** [comment]
https://baidu.github.io/amis/zh-CN/components/html 组件

**Comment by UltramanWeiLai** [comment]
> https://baidu.github.io/amis/zh-CN/components/html 组件

这个组件只能渲染 html 字符串，无法从变量中渲染 html ，不过我刚找到了，需要通过 |raw 的管道符进行渲染
