### ISSUE TITLE
ant design pro 5.2.0整合amis2.7.1异常

### ISSUE THREAD

**Issue by dong-gy** [baidu/amis#6127]
![image](https://user-images.githubusercontent.com/48462501/216207747-981bf320-0c82-4846-a7ab-f0e1361d96f5.png)
![image](https://user-images.githubusercontent.com/48462501/216207800-fc775241-4270-46f4-92de-6335d097f89c.png)
![image](https://user-images.githubusercontent.com/48462501/216207880-eddc45d2-050b-46fe-bd8e-8f5a0f34185d.png)

**Comment by lurunze1226** [comment]
升级2.7.2解决吧，2.7.1的amis-core包有问题
