### ISSUE TITLE
2.7.1 报错 amis-core 不存在

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#6128]
#### 描述问题：

[WARNI] Can't resolve `amis-core` in file [/node_modules/amis-ui/lib/components/json-schema/Array.js], did you miss `npm install amis-core`?

#### 截图或视频：

 Can't resolve `amis-core` in file [/node_modules/amis-ui/lib/components/json-schema/Object.js], did you miss `npm install amis-core`?

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
      npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
    "amis": "2.7.1",
    "amis-core": "2.7.0",
    "amis-editor": "5.2.3",
    "amis-formula": "2.6.1-alpha.0",
    "amis-ui": "2.7.1",
    "amis-widget": "3.0.6",

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lurunze1226** [comment]
2.7.1的amis-core的包有问题，使用2.7.2吧
