### ISSUE TITLE
基于 React 的组件可视化拖拽页面搭建代码生成工具

### ISSUE THREAD

**Issue by anye931123** [baidu/amis#613]
基于 React 的组件可视化拖拽页面搭建代码生成工具,组件自由拖拽，dom实时追踪，组件无限制嵌套组合，不添加多余节点，所见即所得，可完美还原UI设计，多平台支持，代码生成，实时预览，核心功能已抽取为单独组件不依赖任何组件库，并支持任何组件库的拖拽搭建页面，项目开源，欢迎有兴趣的一起开发。
https://github.com/anye931123/react-visual-editor

**Comment by nwind** [comment]
不相关
