### ISSUE TITLE
Uncaught [ModJS] Cannot find module `index.html` 版本 v2.7.2

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#6135]
#### 描述问题：
版本 v2.7.2
Uncaught [ModJS] Cannot find module `index.html` 
npm start 保存

#### 截图或视频：
<script type="text/javascript">
      /* @require index.tsx 标记为同步依赖，提前加载 */
      amis.require(['index.tsx'], function(app) {
        var initialState = {};
        app.bootstrap(document.getElementById('root'), initialState);
      });
    </script>

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.7.2
3. 粘贴有问题的完整 `amis schema` 代码：
```
    "amis": "2.7.2",
    "amis-core": "2.7.2",
    "amis-editor": "5.2.3",
    "amis-editor-core": "5.2.3",
    "amis-formula": "2.7.2",
    "amis-ui": "2.7.2",
```

4. 操作步骤
npm run start

**Comment by minzhenyu** [comment]
+1，
https://github.com/aisuda/amis-editor-demo 拉取最新代码，就会出现这个问题
run dev  还会报以下两错误：
Can't resolve `rc-input-number/lib/utils/MiniDecimal` in file [/node_modules/amis-ui/lib/components/NumberInput.js], did you miss `npm install rc-input-number`?

Can't resolve `vertx` in file [/node_modules/mpegts.js/dist/mpegts.js], did you miss `npm install vertx`?

yarn  add  rc-input-number vertx 之后启动也依旧会报这个错误

**Comment by minzhenyu** [comment]
@nwind

**Comment by nwind** [comment]
先等等吧目前内部在换 vite

**Comment by hsm-lv** [comment]
可以尝试下新版

**Comment by X-W-W** [comment]
> file [/node_modules/mpegts.js/dist/mpegts.js], did you miss `npm install vertx`?
> 
> yarn add rc-input-number vertx 之后启动也依旧会报这个错误

rc-input-number@7.4.*没有rc-input-number/lib/utils/MiniDecimal这个文件
override 到7.3.11就可以了
