### ISSUE TITLE
编辑器5.2.3配合amis2.7.2，从左边拖入CRUD或者input-table时页面白屏同时控制台有报错

### ISSUE THREAD

**Issue by qianxiaofendou** [baidu/amis#6137]
#### 描述问题：

在把编辑器升级到5.2.3，amis升级到2.7.2之后，从左边组件里面拖入CRUD或者input-table时页面出现了白屏(其它组件拖入是正常的)，控制台有报错，如下图

![image](https://user-images.githubusercontent.com/20673152/216526502-f0a630ea-0829-4588-82d9-9deb48c0f086.png)

**Comment by qianxiaofendou** [comment]
试了下 amis包2.6.0配合amis-editor5.2.3是正常的，  @lurunze1226  麻烦看下 amis2.7里面是不是做了什么调整

**Comment by qianxiaofendou** [comment]
amis2.7的版本里面有个关于`tabs`的问题修改，看了下去除了`key`，猜测可能是这个原因引起的在编辑器里面的报错，麻烦 @lurunze1226 大佬看一下，辛苦！！！

**Comment by EvanZheng11** [comment]
从amis-editor 5.2.1*以后都有这个问题，在editor里点一下CRUD就会白屏，报这个错。

**Comment by EvanZheng11** [comment]
同等解决方案

**Comment by hsm-lv** [comment]
建议全部升级到最新版本试试
