### ISSUE TITLE
Amis2.7.2 CRUD快速编辑无法批量保存

### ISSUE THREAD

**Issue by deameamo** [baidu/amis#6138]
#### 描述问题：

使用CRUD快速编辑功能时，当编辑了若干行后，点击提交，quickSaveApi接口返回{"status":0,"msg":"ok"}，已经编辑的行仍然保持原样，提交按钮仍在。

#### 截图或视频：

图1：点击提交前

<img width="766" alt="image" src="https://user-images.githubusercontent.com/28969140/216837907-de2871e2-9586-4cd5-a47c-aef9d963aae3.png">

图2：点击提交后

<img width="773" alt="image" src="https://user-images.githubusercontent.com/28969140/216837992-fe9b61c3-0edf-4998-84c1-1a915d5519c1.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.7.2

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  title: '列表',
  type: 'page',
  body: [
    {
      type: 'crud',
      api: 'http://localhost:7046/account/list',
      perPage: 10,
      quickSaveApi: 'http://localhost:7046/account/saveItem',
      headerToolbar: [
        'columns-toggler',
        'reload'
      ],
      footerToolbar: ['statistics', 'switch-per-page', 'pagination'],
      columns: [
        {
          name: 'accountId',
          label: '子账户ID',
          sortable: true,
          type: 'text',
          toggled: true,
          quickEdit: true
        },
        {
          name: 'name',
          label: '名称',
          sortable: true,
          type: 'text',
          toggled: true,
          quickEdit: true
        },
        {
          label: '开关',
          sortable: true,
          name: 'switch',
          quickEdit: {
            mode: 'inline',
            type: 'switch',
            onText: '已开启',
            offText: '已关闭'
          }
        }
      ]
    }
  ]
}
```

4. 操作步骤
我用以下文档的crud快递编辑代码
https://aisuda.bce.baidu.com/amis/zh-CN/components/crud
自己mock后端接口，依然出现无法保存的情况

**Comment by Lattenike** [comment]
同样的问题，你解决了吗？
