### ISSUE TITLE
通过接口获取到的某个字段的值为object类型，那我该如何展示在crud里边呢

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#614]
`{
	'status': 0,
	'msg': '数据查询成功',
	'data': {
		'items': [{
			'body': {},
			'headers': {
				'appVersion': '7.11.03',
				'requesttime': '1585584412743',
				'pageid': 'MallHomeActivity',
				'systemVersion': '10',
				'appChannel': 'huawei',
				'systemName': 'android',
				'prelogid': 'd371e4dc33b199fe1cba1fe975b1c37c',
				'datalogid': 'bcef1354d3fa0c4b',
				'logid': '96f922e0f8f5208f',
				'rpcId': '1',
				'appVersionNumber': '71103',
				'deviceModel': 'SEA-AL10',
				'location': '39.924353*116.634751',
				'subAppVersionNumber': '',
				'Content-Type': 'application/json; charset=utf-8',
				'User-Agent': 'okhttp/3.11.0'
			},
			'method': 'POST',
			'params': {},
			'type': 'form-data',
			'url': 'https://mall.xueersi.com/cart/getCartCount'
		}
		}]
	}
}`
我想把headers里边的内容展示出来，但是现在是object类型，无法展示，我该如何做呢
想做成如下展示
![image](https://user-images.githubusercontent.com/64950961/82788862-db9f6f80-9e9b-11ea-989d-1975b245fb39.png)

**Comment by 2betop** [comment]
实在找不到，可以用 tpl 拼个 html 片段输出。
