### ISSUE TITLE
升级编辑器导致报错 The renderer with name "bat-editor" has already exists, please try another name!

### ISSUE THREAD

**Issue by minzhenyu** [baidu/amis#6153]
#### 描述问题：

升级编辑器导致报错 The renderer with name "bat-editor" has already exists, please try another name!
#### 截图或视频：
问题具体描述：
https://github.com/aisuda/amis-editor-demo/issues/181

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
升级前：
"amis": "1.9.0-beta.12",
"amis-editor": "^4.1.0-beta.2",

升级后：
"amis": "^2.7.2",
"amis-core": "^2.7.2",
"amis-editor": "^5.2.3",
"amis-ui": "^2.7.2",

报错：
The renderer with name "bat-editor" has already exists, please try another name!

**Comment by minzhenyu** [comment]
还有个问题请教下，编辑器哪个版本开始支持value 可以定义变量、联动其他数据的？ @nwind

**Comment by enkialtria** [comment]
请问你解决了吗

**Comment by wibetter** [comment]
@minzhenyu 默认值支持公式，amis版本是1.10.0开始，amis-editor大概是从4.1.0-beta.25版本开始。

**Comment by wibetter** [comment]
@minzhenyu ’报错 The renderer with name "bat-editor" has already exists‘ 这个报错，大概还是因为当前构建中有两份amis，
同时打包了lib模式的amis和esm模式的amis。这个跟打包工具也有关系，如果是webpack，可以通过设置conditionNames来避免同时使用amis的lib和esm模块：
<img width="650" alt="image" src="https://github.com/baidu/amis/assets/11958920/d10406bf-c1a5-4208-9f5f-36065eb24661">。

另外建议项目中使用到的amis-editor和amis相关联的依赖都升级到最新版。
