### ISSUE TITLE
amis2.7.2的版本crud的filter无法点击勾选

### ISSUE THREAD

**Issue by tanjiancheng** [baidu/amis#6155]
#### 描述问题：

amis2.7.2的版本crud的filter无法点击勾选

#### 截图或视频：
![QQ截图20230209143431](https://user-images.githubusercontent.com/7401570/217739144-ea29a333-e2df-4e9c-85e7-9c940d25c0da.jpg)

https://baidu.github.io/amis/zh-CN/components/crud 这个地址下的自动生成查询区域也是有同样的问题
![image](https://user-images.githubusercontent.com/7401570/217739464-8590c47e-f6ca-449e-af02-435ff569b069.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？

2.7.2

**Comment by hsm-lv** [comment]
尝试一下新版
