### ISSUE TITLE
【amis-editor 使用以及升级问题】:可以提供升级文档，使用文档吗，所有问题自己排查有点麻烦

### ISSUE THREAD

**Issue by minzhenyu** [baidu/amis#6164]
#### 实现场景：
编辑器升级各种报错，只能自己排查，文档内容不够，非常麻烦
#### 存在的问题：
编辑器升级各种报错，只能自己排查，文档内容不够，非常麻烦

#### 当前方案：
希望官方源码不开源的情况下，提供相对有效的开发方案，以及api ，至少常见问题提供有效方案

发布版本最起码也给个升级文档啥的

**Comment by minzhenyu** [comment]
@nwind

**Comment by minzhenyu** [comment]
vue2 下升级 amis-editor

"amis": "^2.7.2",
    "amis-core": "^2.7.2",
    "amis-editor": "^5.2.3",
    "amis-ui": "^2.7.2",

<img width="668" alt="image" src="https://user-images.githubusercontent.com/12856051/217994578-17018c94-8f63-4ff4-9a99-3168437d2f27.png">

报组件名已注册错误，factory.js

解决方案：
node_modules 下找到并注释掉编辑器注册部分
![image](https://user-images.githubusercontent.com/12856051/217994808-e95ebc48-849a-49f9-b324-70c3180b7b03.png)

**Comment by minzhenyu** [comment]
按上述修改报错后发现样式错乱
参考https://github.com/aisuda/amis-widget
替换样式引入：
import "amis-ui/lib/themes/default.css";
import "amis-ui/lib/themes/cxd.css";
import "amis-editor-core/lib/style.css";

此时页面内容基本展示完整，也没有报错，但是 界面英文展示，汉化处理正在查找。。。

**Comment by minzhenyu** [comment]
ps:官方群聊没人管理吗？申请了很多回也进不去，太难了

**Comment by EvanZheng11** [comment]
+1

**Comment by seantech2000** [comment]
这个开源几乎是形式了，靠自己折腾

**Comment by nwind** [comment]
已开源，如果有具体问题再开新 issue，目前研发只用如流群了
