### ISSUE TITLE
希望iframe提供一个src支持POST方式的方法

### ISSUE THREAD

**Issue by zhangxx2015** [baidu/amis#6168]
#### 是否关联于某个问题吗：
希望AMIS的IFRAME能提供一个SRC属性可以提交POST请求的方法,类似于schemaApi

#### 预期的解决方案：
{
    "type": "iframe", 
    "height": "600px",
    "src": {
        "method":"post",
        "url":"xxx",
        "data":{
            "Name": "${Name}",
            "&": "$$"
        }
    }
},

**Comment by nwind** [comment]
浏览器限制，做不到
