### ISSUE TITLE
【amis】【amis-editor】 对应使用版本能否在文档里做一些说明，感觉版本不对应会引发一堆报错

### ISSUE THREAD

**Issue by minzhenyu** [baidu/amis#6178]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nwind** [comment]
目前项目合并了，使用最新版就行
