### ISSUE TITLE
crud里边的可折叠类型的第一条记录总是默认不折叠，这个有办法修改嘛

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#618]
![image](https://user-images.githubusercontent.com/64950961/82819154-79ae2c80-9ed2-11ea-9e3c-3ea058151858.png)

**Comment by 2betop** [comment]
```
footable: {
  expand: 'none'
}
```

默认是 `first` 还可以设置成 `all`

**Comment by tanmengfei** [comment]
好的，谢啦
