### ISSUE TITLE
form中的按钮actionType为dialog时，按钮中的stopPropagation属性不生效

### ISSUE THREAD

**Issue by yinlianghui** [baidu/amis#6186]
#### 描述问题：

在form中配置一个actionType类型为dialog的按钮，点击它期望能弹出窗口，但是实际却会触发form的submit事件（如果不配置submit事件的话就不会触发，也能正常弹出窗口），为该按钮配置stopPropagation属性依赖无法解决此问题。

#### 截图或视频：

![image](https://user-images.githubusercontent.com/6219465/218912996-65ac1631-32c3-4acc-93c8-92e6a99ab04d.png)

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

2.5.2和2.7.2（当前最新版本）都有问题。

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "onEvent": {
      "submit": {
        "actions": [
          {
            "actionType": "custom",
            "script": "alert(44)"
          }
        ]
      }
    },
    "body": [
      {
        "type": "input-text",
        "name": "name",
        "label": "姓名："
      },
      {
        "name": "email",
        "type": "input-email",
        "label": "邮箱："
      },
      {
        "type": "button",
        "label": "设置搜索项",
        "onEvent": {
          "click": {
            "actions": [
              {
                "preventDefault": true,
                "stopPropagation": true,
                "actionType__": "custom",
                "script__": "alert(33)",
                "actionType": "dialog",
                "dialog": {
                  "type": "dialog",
                  "size": "md",
                  "title": "设置搜索项",
                  "body": [
                    {
                      "type": "input-text"
                    }
                  ]
                }
              }
            ]
          }
        }
      }
    ]
  }
}
```

5. 操作步骤

amis官网中可以重现这个bug，把上述代码复制到第一个form示例中即可重现此问题：https://aisuda.bce.baidu.com/amis/zh-CN/components/form/index
另外：
- 如果把上述按钮的actionType改为custom的话，stopPropagation性能是可以生效的，并没有问题，只有actionType为dialog时才有问题。
- 如果把上述form的submit事件代码移除的话，是可以正常弹出dialog的，见下图：
![image](https://user-images.githubusercontent.com/6219465/218913988-18e36b83-0577-43ab-8558-622318521ebf.png)

**Comment by yinlianghui** [comment]
发现就算把actionType从dialog改为custom，并且在自定义脚本中使用doAction来实现dialog弹出窗口也一样有问题，似乎只要执行的是dialog的action就有问题。
```
var onSettingcript =`
  doAction({
    "actionType": "dialog",
    "dialog":...
  });
`;
...
{
    "actionType": "custom",
    "preventDefault": true,
    "stopPropagation": true,
    "script": onSettingcript
}
...
```

**Comment by hsm-lv** [comment]
可以看下新版本是否还有问题，如果需求是配置一个actionType类型为dialog的按钮，点击它期望能弹出窗口，是ok的，没有复现你说的这个问题。另外，stopPropagation是为了阻止actions中后续的动作的执行哦。
