### ISSUE TITLE
官方是否提供给设计人员和产品经理使用的视觉资源

### ISSUE THREAD

**Issue by jackhansir** [baidu/amis#6188]
![AAD1D226-DBA7-4980-9B33-580DB8187C4C](https://user-images.githubusercontent.com/26846260/218968085-4ac02972-c302-4086-baed-ff10c4bf3082.png)
如图，其他框架提供的视觉资源Axure Components和Sketch Template

**Comment by gillbates** [comment]
最好figma那边能提供一套就好了。。。

**Comment by hsm-lv** [comment]
暂时没有
