### ISSUE TITLE
富文本编辑器bug

### ISSUE THREAD

**Issue by ClarenceStar** [baidu/amis#620]
表单中添加富文本编辑器
第一次打开弹窗提交时候可以更新富文本里内容
不刷新页面 再次点击按钮在弹框中提交表单 更改富文本中内容
请求中的字段并没有更新
第一次更新后的字段
![image](https://user-images.githubusercontent.com/15528239/82883102-9602a580-9f74-11ea-981d-fdab723c8b1a.png)
![image](https://user-images.githubusercontent.com/15528239/82883481-0e696680-9f75-11ea-86cf-70863dbbfccc.png)

**Comment by xinghe94** [comment]
第一次打开弹窗提交后 弹窗如果仅保存不关闭 每一次request中富文本的数据是更新的 如果直接保存关闭 再次打开弹窗 编辑富文本直接无效

**Comment by nwind** [comment]
试试新版还有问题就发完整配置吧
