### ISSUE TITLE
crud单条操作按钮控制显隐性问题

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#621]
这是页面返回的两条数据，如果我想让json字段为空的那一条数据的单条操作按钮隐藏，那disabledOn属性该怎么配置呢
![image](https://user-images.githubusercontent.com/64950961/82985669-079b2c00-a027-11ea-905c-e2abf9f4faf9.png)

**Comment by 2betop** [comment]
disabledOn: '!this.json'

**Comment by tanmengfei** [comment]
谢谢，已解决！
