### ISSUE TITLE
amis源码构建失败

### ISSUE THREAD

**Issue by jackhansir** [baidu/amis#6210]
把源码拉取到本地(尝试2.6及2.7) npm 7+
1、npm i --legacy-peer-deps
2、npm run build

报错，不能构建成功，更改后还有报错，报错太多

**Comment by nwind** [comment]
这个命令在每次提交后都会自动运行，目前看起来没问题

如果是 windows 的话试试 wsl 吧，或者贴一下报错信息

**Comment by xiongyachuan** [comment]
![image](https://github.com/baidu/amis/assets/91184124/7ec6814f-88d7-4cfa-b5d6-9170b0b3bcee)
![image](https://github.com/baidu/amis/assets/91184124/f147623c-c922-4f51-9658-665e2b0df9a0)
![image](https://github.com/baidu/amis/assets/91184124/44757936-dcab-4993-9f54-cbe599c7207e)
源码执行npm run build 进行构建报错，本地可以正常运行

**Comment by xiuxiuyifan** [comment]
解决了吗？
