### ISSUE TITLE
Flex布局在app组件的header中不生效

### ISSUE THREAD

**Issue by yuanzzhang** [baidu/amis#6215]
#### 描述问题：

Flex 布局在 app 组件的 header 中没有生效，不知道是不是bug。
想要一个按钮在最左面，另一个在最右边。但现在全挤在最左边了。

#### 截图或视频：

![image](https://user-images.githubusercontent.com/81345419/220040197-dd48a31a-ad69-4b52-aee4-4dda59cc8ee4.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
js sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v2.9.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "app",
  "header": [
    {
      "type": "flex",
      "justify": "space-between",
      "items": [
        {
          "type": "button",
          "icon": "fa-solid fa-house",
          "label": "靠左"
        },
        {
          "type": "button",
          "icon": "fa fa-user",
          "label": "靠右"
        }
      ]
    }
  ]
}
```

**Comment by wibetter** [comment]
@yuanzzhang 先解释下出现这个现象的原因：APP组件的headerBar区域也是flex布局（水平展示），默认子元素并非100%铺开展示，如果需要headerBar区域内的flex容器100%铺开展示，可以为其设置样式如下：
<img width="1362" alt="image" src="https://github.com/baidu/amis/assets/11958920/89c60393-a1ec-4569-bb7f-b4278b535e7c">

**Comment by yuanzzhang** [comment]
好的，感谢。
