### ISSUE TITLE
爱速搭官网合作咨询tab链接有误404了

### ISSUE THREAD

**Issue by cennianer** [baidu/amis#6218]
#### 描述问题：

爱速搭官网合作咨询tab链接有误404了

#### 截图或视频：

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/15810318/220124482-41a943dc-3b94-4f54-8ece-02640a0b2c9a.png">

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/15810318/220124597-2fa721d9-c4fc-410f-9d5f-85fded595f51.png">

**Comment by lurunze1226** [comment]
感谢提醒，我们处理一下
