### ISSUE TITLE
回调函数

### ISSUE THREAD

**Issue by chenyphaaa** [baidu/amis#622]
如何在ajax请求后根据返回的errorCode来再次请求其他接口？具体场景是我想根据请求接口的是否成功来决定是否记录一条行为记录

**Comment by 2betop** [comment]
直接 在给 amis 传入的 fetcher 的后面，加个 then

**Comment by chenyphaaa** [comment]
> 直接 在给 amis 传入的 fetcher 的后面，加个 then

在自己定义的jsonschema中有什么字段能用嘛？这边是想只让开发人员编辑schema就可以使用
