### ISSUE TITLE
建议给CRUD列配置属性表增加onEvent事件

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#6221]
#### 是否关联于某个问题吗：
现阶段列如过设置了width或其他一些属性的时候在开起快捷编辑，列排版就会很难看。
![image](https://user-images.githubusercontent.com/11575908/220258588-c9a984a3-a8e2-41bf-85a3-67624aff9961.png)

#### 预期的解决方案：
建议增加列onEvent事件，可以通过点击列了来进行快捷编辑。或其他操作

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by hsm-lv** [comment]
后面版本会支持
