### ISSUE TITLE
我定义了一个按钮是发送一个ajax请求，如何通过接口返回值判断是否进行rediect呢

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#623]
![image](https://user-images.githubusercontent.com/64950961/83000520-1096f800-a03d-11ea-91f2-29182afe7804.png)

**Comment by 2betop** [comment]
恐怕现在还不支持，下个版本支持。用法：

`<%= data.xxx ? '/admin/xxxx' : ''%>`

**Comment by tanmengfei** [comment]
那什么时候更新下个版本呀==

**Comment by 2betop** [comment]
amis@1.0.11-beta.44 或者等待 amis@1.0.11
