### ISSUE TITLE
TransferPicker 点击没反应好像是svg的样式问题

### ISSUE THREAD

**Issue by mixiaodiao** [baidu/amis#6230]
#### 描述问题：

粘贴官网TransferPicker 最简单的例子点击后”没有反映“

#### 截图或视频：

 
![企业微信截图_20230221221334](https://user-images.githubusercontent.com/44493617/220369182-dab231da-e8c8-48f9-a8f8-ac89bd675215.png)

如上图，我看有人也说点击没反应，今天偶然发现其实有反映，但是样式出了问题，这几个svg的图标太大直接显示到可见范围之外
amis 从2.0到现在最新的都是这样（更早的没测试过）

**Comment by 2betop** [comment]
最新版本已修复，是 jssdk 中样式问题，npm 用法无此问题。请升级到最新版本
