### ISSUE TITLE
【两个异步存在互相依赖的情况怎么处理】form组件内部有异步组件获取信息并且能获取默认值，怎么与外部组件 list 联动初始化

### ISSUE THREAD

**Issue by minzhenyu** [baidu/amis#6239]
#### 实现场景：
form组件内部有异步组件获取信息并且能获取默认值，怎么与外部组件 list 联动初始化

form 组件内部插入自定义的异步组件
异步查询完毕后要把数据传给外部组件

然而外部组件也有初始化，此时form内部异步初始化数据还没拿到就执行初始化，导致传递少参数，无法获取正确数据，

当然，每次变化就触发能解决一定问题

#### 存在的问题：

两个异步存在互相依赖的情况怎么处理？

#### 当前方案：
![image](https://user-images.githubusercontent.com/12856051/220594653-a19bf459-e336-4b63-89e9-9b54990d0406.png)

```
code here...
```

**Comment by minzhenyu** [comment]
修改即提交会导致修改就触发请求，此时按钮就没用了

**Comment by minzhenyu** [comment]
这种异步依赖场景应该挺多的，我form数据异步获取默认值，然后初始数据又依赖于异步form获取的初始值，这种情况怎么处理@nwind

**Comment by hsm-lv** [comment]
可以看下事件动作能不能满足你的需求场景，https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action，组件支持的事件和动作在具体的组件文档的最下方

**Comment by 2betop** [comment]
如果接口有依赖请参考这个规则来设置。https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E8%87%AA%E5%8A%A8%E5%88%B7%E6%96%B0
