### ISSUE TITLE
富文本高度无法设置

### ISSUE THREAD

**Issue by taoyao-code** [baidu/amis#6244]
#### 描述问题：

配置无法生效

#### 截图或视频：

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/38855041/220871201-c85ed25a-c85f-485d-9f13-7c98d60586eb.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

2.6至2.7.2

3. 粘贴有问题的完整 `amis schema` 代码：
```json
{
  "type": "page",
  "body": {
    "type": "form",
    "body": [
      {
        "type": "input-rich-text",
        "label": "内容",
        "name": "content__c",
        "options": {
          "height": 800,
          "plugins": "autoresize"
        },
        "size": "lg"
      }
    ]
  }
}
```

4. 操作步骤
直接复制上方json到官网页面中粘贴，或者 打开 编辑器进行粘贴

**Comment by meerkat-morecats** [comment]
刚我试了下，暂时可以先使用 `min_height` 来解决这个问题，height那个属性看起来是坏了，具体为啥没生效还需要定位一下。 @taoyao-code

**Comment by meerkat-morecats** [comment]
> 刚我试了下，暂时可以先使用 `min_height` 来解决这个问题，height那个属性看起来是坏了，具体为啥没生效还需要定位一下。 @taoyao-code

由于那个 [autoresize](https://www.tiny.cloud/docs/tinymce/6/autoresize/) 这个plugin和 `height` 属性冲突，如果你想用 `autoresize` 的话，可以使用 `min_height` 来处理高度。
