### ISSUE TITLE
requestAdaptor中的=拼装数据问题

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#625]
如下代码写在requestAdaptor中，用于拼装发送给api的数据，其中我定义了bodyObj和body，最后给返回时，我想这两个值哪个不为空就把那个赋值给data中的body，请问data中该如何书写
![image](https://user-images.githubusercontent.com/64950961/83047227-a69d4380-a07a-11ea-8517-89cfbcf5ad9b.png)

**Comment by RickCole21** [comment]
这是js相关的，自己百度吧
