### ISSUE TITLE
crud的某一列的列宽能设置成固定值吗

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#626]

**Comment by RickCole21** [comment]
`width:100`就是100px

**Comment by tanmengfei** [comment]
宽度固定之后，这一列多出去的文字覆盖在了别的列上边
![image](https://user-images.githubusercontent.com/64950961/83094529-72ef0780-a0d4-11ea-85df-321ede02a8d9.png)

**Comment by 2betop** [comment]
再加个 className: 'word-break' 到列上。

**Comment by tanmengfei** [comment]
可以啦，谢谢
