### ISSUE TITLE
Log 实时日志 source URL 执行无法通过 requestAdaptor 拦截

### ISSUE THREAD

**Issue by trainkg** [baidu/amis#6262]
{
  "type": "page",
  "body": {
    "type": "log",
    "height": 1000,
    "source": {
      "method": "get",
      "url": "http://localhost:8000/test/log"
    }
  }
}

amis.embed({
...
requestAdaptor:function(api){
console.log(api)
return api
}
...
})

发现在加载日志的时候未执行requestAdaptor。

**Comment by nwind** [comment]
log 是基于 fetch 实现的，和普通 api 不一样，这里是流式处理的，无法用 responseAdaptor
