### ISSUE TITLE
amis json动态化

### ISSUE THREAD

**Issue by whitekyo** [baidu/amis#627]
如果页面的某个结构因为接口的字段值而去展示或不展示。或者展示结构不一样。换言之就是动态的json，目前amis的解决方案是不是只有service？ 这个要服务端返回具体json结构。还有一种方案就是，我自己通过css控制显示或隐藏，这里需要额外引入一些css。

请问有什么其他比较好一点的方案吗？

**Comment by 2betop** [comment]
可以配置 visibleOn 或者 hiddenOn https://baidu.github.io/amis/form/reaction

**Comment by whitekyo** [comment]
感谢，已解决
