### ISSUE TITLE
Date 日期时间开启fromNow 获取今日内时间的相对描述不对

### ISSUE THREAD

**Issue by ArrNNG** [baidu/amis#6278]
#### 描述问题：
Date 日期时间组件开启fromNow后获取今日内时间的相对描述不对

 
#### 截图或视频：
 例如 2023-02-28 12:00:00 1677556800，得到的结果是14小时前
 
![45a598f5a62506001011c3dc78b9f00](https://user-images.githubusercontent.com/57611350/221767954-635ef380-e19d-4bbf-9f5e-cd8266278722.png)

 例如 2023-02-28 18:00:00 1677578400，得到的结果也是14小时前

测试时间是 2023-02-28 14:05，每次测试都刷新过页面

#### 如何复现（请务必完整填写下面内容）：
 
1. 你是如何使用 amis 的？
官网示例

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
官网示例

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
    "type": "date",
    "fromNow": true,
    "value": "1677556800"
  }
```

4. 操作步骤
在官网示例中的
 [Date 日期时间组件 - date#转成相对当前时间的描述](https://aisuda.bce.baidu.com/amis/zh-CN/components/date#%E8%BD%AC%E6%88%90%E7%9B%B8%E5%AF%B9%E5%BD%93%E5%89%8D%E6%97%B6%E9%97%B4%E7%9A%84%E6%8F%8F%E8%BF%B0)
更改value为当前时间前后几个小时内的时间戳

**Comment by ArrNNG** [comment]
似乎获取的都是零点相对于当前时间的描述

**Comment by 2betop** [comment]
新版本已无此问题，先关闭了
<img width="1564" alt="image" src="https://github.com/baidu/amis/assets/2698393/55e898e8-559e-46b9-8ef5-a47f2280e054">
