### ISSUE TITLE
transfer 找不到渲染器

### ISSUE THREAD

**Issue by iceycc** [baidu/amis#628]

**Comment by iceycc** [comment]
从官方文档粘贴的穿梭器的json，找不到渲染器 
Error: 找不到对应的渲染器

Path: page/drawer/drawer/body/form/0/control/transfer

**Comment by 2betop** [comment]
还没发布正式版本，预计明天发，先用最新的 beta 版本

**Comment by iceycc** [comment]
感谢大佬，bate版本可以了。希望顺便把编辑器的gh-pages也更新下 ❤️

**Comment by RickCole21** [comment]
https://baidu.github.io/amis/docs/components/form/transfer
