### ISSUE TITLE
amis-theme-editor 未提供esm版本导致vite加载两遍amis的cjs和esm代码，会报 remark 重复注册错误

### ISSUE THREAD

**Issue by agileago** [baidu/amis#6290]
#### 描述问题：

用最新版本的amis和amis-editor会运行不起来报错

#### 截图或视频：

![image](https://user-images.githubusercontent.com/11799110/222091882-ea759017-472d-48d7-870a-3944f15f94e8.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

vite

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新版

4. 粘贴有问题的完整 `amis schema` 代码：

5. 操作步骤
启动vite

**Comment by ggymzz** [comment]
同样问题，amis-theme-editor-helper@2.0.8   与 amis-theme-editor@2.0.8 包里面只有lib，跟其它amis*包相比，却少esm~~

**Comment by ggymzz** [comment]
webpack 环境下也是如此 出错的版本信息如下：
"amis": "^2.8.0",
    "amis-editor": "^5.2.4-beta.31",
    "amis-editor-core": "^5.2.4-beta.31",

**Comment by citynook** [comment]
我也遇到了同样的问题，在AntPro工程下安装了 amis 2.8和 editor，页面加入 Editor 控件时，显示 remark 已经存在。

**Comment by agileago** [comment]
@ggymzz @citynook 我看已经发布最新版了，重新安装试试

**Comment by 2betop** [comment]
amis-theme-editor@2.0.10

**Comment by 2betop** [comment]
@agileago 这么快就被你发现了

**Comment by agileago** [comment]
哈哈，看你活跃了，顺手瞄了一眼，没想到有了，为你们的速度点赞！！

**Comment by agileago** [comment]
@2betop 貌似editor有点问题

![image](https://user-images.githubusercontent.com/11799110/224259995-56965a2c-09d0-4321-9d7d-94c8d304230b.png)

引入了cjs的代码

**Comment by hyzx86** [comment]
@agileago 

最新版解决了吗？

我这还是老样子~
``` json
    "amis": "2.8.0",
    "amis-core": "2.8.0",
    "amis-editor": "5.2.5-beta.1",
    "amis-editor-core": "5.2.5-beta.1",
    "amis-formula": "2.8.0",
    "amis-theme-editor": "2.0.10",
    "amis-ui": "2.8.0",
```

**Comment by hyzx86** [comment]
请问下，你的项目也是editor&nbsp; 和业务程序在同一个项目吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月18日(周六) 晚上9:09
收件人: ***@***.***&gt;;
抄送: "Tony ***@***.******@***.***&gt;;
主题: Re: [baidu/amis] amis-theme-editor 未提供esm版本导致vite加载两遍amis的cjs和esm代码，会报 remark 重复注册错误 (Issue #6290)




 
解决了啊，删了lock文件和node_modules重新装一下

**Comment by hyzx86** [comment]
> 解决了啊，删了lock文件和node_modules重新装一下

是的。。我专门还写了个 powershell。。

``` powershell


$amisV="2.8.0"

# $amisV = npm show amis version
# pnpm i amis-core@$amisV amis-ui@$amisV amis@$amisV amis-core@$amisV amis-formula@$amisV

# $amisEditor = npm show amis-editor version

$amisEditor="5.2.5"
# pnpm i amis-editor-core@$amisEditor amis-editor@$amisEditor 

rimraf ./node_modules
pnpm run clearumi
rimraf ./pnpm-lock.yaml
pnpm i amis-core@$amisV amis-ui@$amisV amis@$amisV amis-core@$amisV amis-formula@$amisV amis-editor-core@$amisEditor amis-editor@$amisEditor 
pnpm run start


```

**Comment by hyzx86** [comment]
额 。。现在又好了，我加装了 theme 包 
估计是这个配置的问题

``` js
    config.merge({
      // include: [
      //   /\/node_module\/amis-editor-core\/lib\/.*/
      //   // /\/node_modules\/amis-editor\/dist\/.*/
      // ],
      //修复 /amis-editor-core/lib/style.css
      resolve: {
        conditionNames: ['require', 'node']
      }
    })
```

**Comment by agileago** [comment]
> 额 。。现在又好了，我加装了 theme 包 估计是这个配置的问题
> 
> ```js
>     config.merge({
>       // include: [
>       //   /\/node_module\/amis-editor-core\/lib\/.*/
>       //   // /\/node_modules\/amis-editor\/dist\/.*/
>       // ],
>       //修复 /amis-editor-core/lib/style.css
>       resolve: {
>         conditionNames: ['require', 'node']
>       }
>     })
> ```

@hyzx86 这个配置为了解决webpack5引入node_modules中的css报错问题？https://webpack.js.org/guides/package-exports/#reference-syntax

我现在直接 pnpm patch amis包  

<img width="614" alt="image" src="https://user-images.githubusercontent.com/11799110/226172877-a550b52d-4f3c-49d4-ada0-d76a72dcb320.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/11799110/226172896-4da56952-4c9d-4d92-bed7-5ced5d4b7b3f.png">

@2betop 可以考虑解决一波引入css的问题？

**Comment by hyzx86** [comment]
@agileago 哇哦，道友一波操作6的飞起~~
但你这个导出 怎么没看到指定 amis 的包名称啊，这个导出配置是在你自己项目里的？

**Comment by agileago** [comment]
对的， 直接改node_modules里面的， 主要是 amis和amis-editor-core , 你可以看看 https://pnpm.io/zh/cli/patch

**Comment by hyzx86** [comment]
>  pnpm patch amis包

懂了。。。
