### ISSUE TITLE
如何在显隐设置中的表达式中使用外部JS函数

### ISSUE THREAD

**Issue by atliwen** [baidu/amis#6297]
#### 实现场景：
想通过外部方法来控制是否该按钮或模块显示。
如 通过外部的用户权限数据，和外部的权限比对JS函数来控制按钮是否在当前页面显示
#### 存在的问题：
用户数据在amis外部，渲染时并未传入数据。 判断权限JS函数中通过本地获取用户权限信息来依据权限字符串进行对比 返回是否

没有找到如何在 表达式编辑器中使用外部JS函数的方法

#### 当前方案：
![image](https://user-images.githubusercontent.com/10055836/222628218-39e23179-022b-4646-a508-cacd24305c60.png)
code here...
```

**Comment by 2betop** [comment]
新版本可以通过 props 下发 `context` 属性，这个里面的东西任何组件层都可以使用。比如你可以下发个 

```
context: {
  acl: {
    can: (ability: string) => {}
  }
}
```

这样表达式中就可以这么写了 `visibleOn: "${acl.can('download')}"`
