### ISSUE TITLE
初始页面时的api请求，怎么从我自己写的store里能获取某个id作为参数呢。。。

### ISSUE THREAD

**Issue by iceycc** [baidu/amis#630]
![image](https://user-images.githubusercontent.com/31000421/83135048-dcdcd080-a117-11ea-9cb8-4ea9070891cd.png)
就类似这个，怎么从自己代码写的store动态获取一个id呢。。谢谢了

**Comment by RickCole21** [comment]
`${xxx}`，`xxx`是变量的`key`值
