### ISSUE TITLE
Calender Bugs

### ISSUE THREAD

**Issue by liuzhijun** [baidu/amis#6303]
JSSDK version v2.7.2

Maybe @hy993658052

https://github.com/baidu/amis/blob/0fd5179a8f9564fa44045624283158fff1fd6513/packages/amis-ui/src/components/calendar/DaysView.tsx#LL446C31-L446C31
throw [TypeError: Cannot read properties of undefined (reading 'height')] exception by providing:
                "schedules": [
                    {
                        "startTime": "2023-03-01 08:00:00",
                        "endTime": "2023-03-01 18:00:00",
                        "content": "这是一个日程11111",
                        "className": "bg-success",
                    },
                    {
                        "startTime": "2023-03-01 08:00:00",
                        "endTime": "2023-03-02 18:00:00",
                        "content": "这是一个日程22222",
                        "className": "bg-success",
                    }]

https://github.com/baidu/amis/blob/0fd5179a8f9564fa44045624283158fff1fd6513/packages/amis-ui/src/components/calendar/DaysView.tsx#L466
throw [TypeError: Cannot read properties of undefined (reading 'endTime')] exception by providing:
                "schedules": [
                    {
                        "startTime": "2023-03-01 08:00:00",
                        "endTime": "2023-03-01 18:00:00",
                        "content": "这是一个日程11111",
                        "className": "bg-success",
                    },
                    {
                        "startTime": "2023-03-01 08:00:00",
                        "endTime": "2023-03-02 18:00:00",
                        "content": "这是一个日程22222",
                        "className": "bg-success",
                    },
                    {
                        "startTime": "2023-03-01 08:00:00",
                        "endTime": "2023-03-02 18:00:00",
                        "content": "这是一个日程33333",
                        "className": "bg-success",
                    }]

**Comment by 2betop** [comment]
不能复现，可能新版本已无此问题，有问题再开
