### ISSUE TITLE
我在可折叠的crud里边，折叠的那一行放置了json组件，这一行的宽度有办法控制吗

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#631]
如题，假如这一行很宽的话，整个列表都会很宽，我加了width，但还是无法控制宽度。还有一个问题是假如后台传过来的值是空的话，这里会显示root 0keys，可以设置成没有值的话，为空吗
![image](https://user-images.githubusercontent.com/64950961/83156012-74e8b300-a134-11ea-86e3-85e6a4d77b3c.png)

**Comment by CareyToboo** [comment]
Duplicate of #638
