### ISSUE TITLE
select 组件中 options = [{lable:"a,2",value:"a,2"}] 选中后无法显示lable逗号及后面的文字

### ISSUE THREAD

**Issue by mrwangyin** [baidu/amis#6319]
#### 描述问题：

select 组件中 options = [{lable:"a,2",value:"a,2"}] 选中后无法显示lable逗号及后面的文字

#### 截图或视频：
![image](https://user-images.githubusercontent.com/44059656/223604121-88e874d1-7832-4413-a544-583873669e42.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
"amis": "2.5.2"
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "body": [
      {
        "label": "选项",
        "type": "select",
        "name": "select",
        "options": [
          {
            "label": "a,2",
            "value": "a,2"
          },
          {
            "label": "B",
            "value": "b"
          },
          {
            "label": "C",
            "value": "c"
          }
        ]
      }
    ]
  }
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
因为 delimiter 的默认值 `,` 当做值的分割线，而选中有这个，被认为是多个值了，有两种解法

1. value 中不要有个 `,` 符号
2. 配置  delimiter 为其他不会出现在 value 的字符如 `;`
