### ISSUE TITLE
表格中的 switch 按钮触发弹窗事件  

### ISSUE THREAD

**Issue by chihang9** [baidu/amis#6333]
表格中的 switch按钮触发弹窗事件  弹窗完成后 想将他回复到原值 试过赋值 赋值也搞笑 (只会赋值第一个) 
试过刷新表单 刷新表单这个就有点搞笑了 请求了 是请求了但是不会重新渲染 有解决办法吗
![1678352900053](https://user-images.githubusercontent.com/31495928/223974277-44c88769-49ac-4777-b8e0-a4d74bc6225b.jpg)

**Comment by hsm-lv** [comment]
可以贴下代码，看下你的设计场景是怎样的
