### ISSUE TITLE
amis-editor ^5.2.3 以上版本组合输入无法编辑子项

### ISSUE THREAD

**Issue by 17** [baidu/amis#6348]
#### 描述问题：

amis-editor ^5.2.3 以上版本，组合输入无法编辑子项。

**Comment by wibetter** [comment]
@17  看一下这里能否复现：https://aisuda.github.io/amis-editor-demo/#/hello-world

**Comment by 17** [comment]
SORRY, 旧版本可以在右侧像编辑弹窗编辑子输入，新版本没有了下意识以为不能编辑了。
