### ISSUE TITLE
渲染器的交互

### ISSUE THREAD

**Issue by UltramanWeiLai** [baidu/amis#6350]
#### 实现场景：
场景：一个页面中，有一部分内容（表单）是通过 amis 配置并进行渲染的。

#### 存在的问题：
问题1：项目中，怎么样才可以获取渲染器中表单的数据？
问题2:  项目中，怎么样才可以通过 代码 的形式，触发 amis 渲染器中的表单的提交动作？

#### 当前方案：
一个常规的 单页应用的页面
页面中，只有表单部分是通过 amis 进行渲染的
想使用代码和 amis 进行一些交互

**Comment by 2betop** [comment]
1. props 下发 `scopeRef: (scoped: IScopedContext) => void;` 然后把参数中 scoped 存起来
2. 给 form 的 schema 中写个 name 属性，比如 `myform`
3. 可通过 scoped 对象获取实例如： scoped.getComponentByName("myform")
4. scoped.getComponentByName("myform").store.data 是当前表单的所有数据
5.  scoped.getComponentByName("myform")doAction({actionType: 'submit'}) 可触发表单的提交
