### ISSUE TITLE
树形结构和curd列表联动

### ISSUE THREAD

**Issue by zhongtaoW** [baidu/amis#6352]
#### 实现场景：
点击树形结构下的各个节点，会把点击的id传给相应接口，不同的id有不同的数据，然后把不同的数据放在curd的列表里。目的：点击（input-tree）组件下的节点，刷新curd列表数据，不点击，页面初始化后是所有数据。
#### 存在的问题：
点击树节点，curd数据没有刷新
![image](https://user-images.githubusercontent.com/105036431/224589074-6492127e-3174-45a0-b88e-151c6638ba3c.png)

#### 当前方案：
为curd设置name：“my-curd”，树形结构设置target：“my-curd”，curd列表内容却没有刷新
```
code here...
```

**Comment by hsm-lv** [comment]
有两种方式：
1.crud的api直接query或者参数绑定tree的选中id，这样id变了会自动触发crud的刷新
2.通过事件动作，监听tree的事件，然后调用crud的reload动作，并传id过去
