### ISSUE TITLE
怎么支持多数据源？

### ISSUE THREAD

**Issue by wencan** [baidu/amis#6358]
比如，crud组件
大部分列的数据来自同一个api。
但部分列的数据，来自另一个api。
这个怎么搞？

**Comment by xukeke520** [comment]
我也遇到过这种需求，我是在crud的接收适配器里，自己同步再发送另一个api，拿到接口数据后合并，再返回新的

**Comment by hsm-lv** [comment]
> 我也遇到过这种需求，我是在crud的接收适配器里，自己同步再发送另一个api，拿到接口数据后合并，再返回新的

嗯，是一种思路。反正都是要将多个数据源合并处理为一个给crud，通过变量也好，接口也好
