### ISSUE TITLE
diff-editor获取到的接口的json值显示是object

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#636]
![image](https://user-images.githubusercontent.com/64950961/83241791-ef194600-a1cd-11ea-8dbe-deb58275a3f0.png)
diffValue的数值是${respose.body}返回的是json，但是无法正常显示

**Comment by RickCole21** [comment]
嗯这个应该需要`${respose.body|json}`

**Comment by tanmengfei** [comment]
刚才写错了“|”这个符号，这符号中英文不一样。。
