### ISSUE TITLE
objectToArray函数的预期与实际展示有差别

### ISSUE THREAD

**Issue by QingquanQiu** [baidu/amis#6364]
#### 描述问题：

objectToArray函数的预期与实际展示有差别，反了，value展示的是对象的键，label展示的是对象的值

#### 截图或视频：

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/31943135/224877980-5a20aa21-ea25-4473-9063-dc52ff70e25a.png">

#### 如何复现（请务必完整填写下面内容）：

sdk模式。

amis 版本是最新的sdk下载包。

**Comment by mrchi** [comment]
https://github.com/baidu/amis/blob/6c583f720faaf8f4ab7e4bb80ae8c45ecbf9fd2f/packages/amis-core/src/utils/filter.ts#L246C22-L247

看起来是这两行的问题，k 和 v 的取值写反了

**Comment by 2betop** [comment]
直接 #6933 中讨论，这个先关了
