### ISSUE TITLE
求助 ，APP多页 点击分页 ，都会刷新整个页面

### ISSUE THREAD

**Issue by CJC86** [baidu/amis#6366]
小白求教！

#### 实现场景：
APP多页

#### 存在的问题：
点击分页 ，都会刷新整个页面

请问要怎么解决！！？？

**Comment by tinsn** [comment]
只能结合 vue 等框架来用，现在点击是全部刷新页面。

**Comment by 2betop** [comment]
需要自己实现 updateLocation 和 jumpTo， 默认 sdk 提供的是浏览器 location.url 修改来跳转，如果你单页面是单页应用需要自己来覆盖这几个方法
