### ISSUE TITLE
json组件的width能控制吗

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#638]
![image](https://user-images.githubusercontent.com/64950961/83381835-4ad51080-a414-11ea-88d5-ebbc1f0f3429.png)
我在crud折叠的那一行放了一个json组件用于展示，但是有时候json太长了，导致整个crud被拉长了，整个有办法解决嘛

**Comment by 2betop** [comment]
列上加个 className: 'word-break' 试试

**Comment by tanmengfei** [comment]
还是没办法折叠下来

**Comment by RickCole21** [comment]
目测要自己写css调整下

**Comment by CareyToboo** [comment]
@tanmengfei 写一个样式，限制宽度，再设置下折行应该就好了。不过，建议可以弄一个信息展示弹窗。写一个 Action Dialog 弹出框在 From 展示 静态JSON字段。
![image](https://user-images.githubusercontent.com/15522313/83540879-80b8e880-a52b-11ea-8b05-1bc474bbf151.png)

**Comment by tanmengfei** [comment]
谢谢啦，我这边也是写了个跟你差不多的样式，然后解决啦，哈哈
