### ISSUE TITLE
amis-editor项目启动成功，页面报错

### ISSUE THREAD

**Issue by shawe-tt** [baidu/amis#6381]
![image](https://user-images.githubusercontent.com/78126930/225291051-a2214780-e93d-467f-ae0e-898e16f6e4db.png)

**Comment by shawe-tt** [comment]
编辑器版本：
![image](https://user-images.githubusercontent.com/78126930/225480348-9d357e19-5013-4cf7-a314-d0c3c2110013.png)

**Comment by wibetter** [comment]
@shawe-tt 请问是在哪儿启动的，amis中还是amis-editor-demo中呢?

**Comment by wibetter** [comment]
长期未回复，先关了。

**Comment by wibetter** [comment]
后续有此类问题，请提供当前使用的amis和amis-editor版本信息，页面schema，以及报错时的关键操作路径。
