### ISSUE TITLE
[BUG] 官网问题

### ISSUE THREAD

**Issue by Lattenike** [baidu/amis#6387]
描述问题：
官网curd-快速编辑的渲染失败，无法显示编辑按钮，快速编辑失效（仅限官网，本地和编辑器使用正常）

截图或视频：
链接：https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E5%BF%AB%E9%80%9F%E7%BC%96%E8%BE%91
截图：
<img width="817" alt="image" src="https://user-images.githubusercontent.com/96754993/225505388-a8de21c6-4f13-4197-80da-ceba063dfff4.png">

如何复现：
点击链接进入官网即可查看

**Comment by nwind** [comment]
看起来正常，疑似修了
