### ISSUE TITLE
官网示例BUG

### ISSUE THREAD

**Issue by zhangxx2015** [baidu/amis#6389]
全局搜索文本框位置漂移

![image](https://user-images.githubusercontent.com/11570281/225528138-4b79d0cd-2f3b-45e0-948c-5597c9886a64.png)
![image](https://user-images.githubusercontent.com/11570281/225528179-92d56cf9-e116-42f6-943d-a09d5b31afa3.png)

**Comment by mrwangyin** [comment]
> 全局搜索文本框位置漂移
> 
> ![image](https://user-images.githubusercontent.com/11570281/225528138-4b79d0cd-2f3b-45e0-948c-5597c9886a64.png) ![image](https://user-images.githubusercontent.com/11570281/225528179-92d56cf9-e116-42f6-943d-a09d5b31afa3.png)

人家不会理你的
