### ISSUE TITLE
sdk 引入 的editor编辑器报错

### ISSUE THREAD

**Issue by hotmaycold** [baidu/amis#639]
示例代码
```
{
  "type": "page",
  "body": {
    "title": "",
    "type": "form",
    "mode": "horizontal",
    "autoFocus": false,
    "controls": [
      {
        "type": "json-editor",
        "name": "json",
        "label": "Json Editor"
      }
    ],
    "submitText": null,
    "actions": []
  }
}
```

Uncaught SyntaxError: Unexpected token '<'

**Comment by 2betop** [comment]
引入的是 cdn 上的地址还是 npm 包？

**Comment by hotmaycold** [comment]
> 引入的是 cdn 上的地址还是 npm 包？

npm包中的sdk.js

**Comment by 2betop** [comment]
不能复现，尝试更新以下 amis 的版本？

**Comment by hotmaycold** [comment]
> 不能复现，尝试更新以下 amis 的版本？

最新的1.0.11依然报错，会不会是在vue里引入sdk的原因？其他form都不会有问题只有editor报错

**Comment by 2betop** [comment]
你把错误信息贴详细点

**Comment by hotmaycold** [comment]
> 你把错误信息贴详细点

错误信息只有那一行，cdn引入不报错

**Comment by 2betop** [comment]
sdk 同级目录还有其他文件，也要一起部署到服务器

**Comment by hotmaycold** [comment]
> sdk 同级目录还有其他文件，也要一起部署到服务器

import 引入sdk.js 不应该一起都打包了吗

**Comment by 2betop** [comment]
sdk 有点特殊，等于内置了加载器，里面集成了按需加载，它会自己加载同目录下的其他文件。sdk 就是给不太了解前端的人用的。建议你换成 npm 版本。

**Comment by hotmaycold** [comment]
> sdk 有点特殊，等于内置了加载器，里面集成了按需加载，它会自己加载同目录下的其他文件。sdk 就是给不太了解前端的人用的。建议你换成 npm 版本。

行吧，还有一个问题也是sdk的，我渲染了两个amis的时候传入了两个不同的fetcher，但是后面的fetcher会覆盖前面的，导致全局只能一种请求适配

**Comment by 2betop** [comment]
session: '来点区分'

**Comment by hotmaycold** [comment]
> session: '来点区分'

恍然大明白

**Comment by hotmaycold** [comment]
在同一个issue里提不同问题不太规范，不过问题实在太小太杂了，不好意思
crud 删除按钮删除成功后想返回“”删除成功”提醒

**Comment by 2betop** [comment]
你接口返回 msg 就是提示 接口返回的 msg 字段

**Comment by hotmaycold** [comment]
> 你接口返回 msg 就是提示 接口返回的 msg 字段

成功了，toast停留时间能改吗

**Comment by 2betop** [comment]
也是接口那, msgTimeout: xxx 单位 s, 当设置为0 时不关闭

**Comment by hotmaycold** [comment]
> msgTimeout

驼峰对吗? 不太管用
```{
        status: 1,
        msg: 'delete success',
        msgTimeout: 2,
        data: {
          total: items.length,
          items: items
        }
      }```

**Comment by 2betop** [comment]
会不会是你适配器把这个属性给干掉了？

**Comment by hotmaycold** [comment]
> 会不会是你适配器把这个属性给干掉了？

我直接在适配器里加都没用

**Comment by 2betop** [comment]
那你 debug 以下这块 https://github.com/baidu/amis/blob/master/src/store/crud.ts#L391

**Comment by hotmaycold** [comment]
> 那你 debug 以下这块 https://github.com/baidu/amis/blob/master/src/store/crud.ts#L391

暂时只考虑sdk引入了，这块之后有时间debug一下

**Comment by hotmaycold** [comment]
现在amis支持多阶select了吗？

**Comment by 2betop** [comment]
是有的

**Comment by hotmaycold** [comment]
> 是有的

有没有对应的使用方法

**Comment by 2betop** [comment]
https://baidu.github.io/amis/docs/renderers/Form/Transfer

**Comment by hotmaycold** [comment]
type: iframe  src里能用变量吗？

**Comment by RickCole21** [comment]
可以

**Comment by hotmaycold** [comment]
> 可以
```
{
    "type": "page",
    "data": {
        "a": "https://baidu.com"
    },
    "body": {
        "type": "iframe",
        "src": "$a",
        "style": {
            
        }
    }
}
```
这样好像不管用

**Comment by RickCole21** [comment]
${a|raw}

**Comment by hotmaycold** [comment]
> ${a|raw}

支持tpl <%= a > 模式吗？

**Comment by RickCole21** [comment]
nope，你要不直接tpl拼一个？

**Comment by hotmaycold** [comment]
> nope，你要不直接tpl拼一个？

也行

**Comment by hotmaycold** [comment]
对rich-text使用initApi好像初始化信息注入不进去，而且富文本的options好像也不生效
