### ISSUE TITLE
打开和关闭dialog内存没有释放，时间久了页面崩溃

### ISSUE THREAD

**Issue by fjutnetcxloong** [baidu/amis#6390]
#### 描述问题：

我使用crud表格模式，在操作列上面设置了Action，点击弹出dialog，在dialog里面渲染另一个有500条数据源的crud的表格，所以内存占用会增加，当我关闭弹窗后，内存没有释放，以至于多次打开dialog后内存一直增加，从而导致页面崩溃

#### 截图或视频：

操作前的内存：
![image](https://user-images.githubusercontent.com/44466487/225577519-7fcc9af2-96bf-4ed4-a5a6-0207fbe5b5c4.png)
操作后的内存：
![image](https://user-images.githubusercontent.com/44466487/225577710-d2d91604-a8d2-4d4d-8035-d2e7e05298c8.png)
关闭弹窗后的内存：
![image](https://user-images.githubusercontent.com/44466487/225578947-0882df56-d5c1-45f3-aa06-c2f144045228.png)
n内存占用几乎不变

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
我使用1.6，最新的master上不存在这个问题
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
打开一个弹窗，然后关闭弹窗，观察内存的占用变化

**Comment by 2betop** [comment]
如果是历史 1.6 的问题，不会修复，请升级版本
