### ISSUE TITLE
为什么我在项目中使用amis，自定义组件时，需要在项目中注册一遍，还要在编辑器注册一遍，为什么不能编辑器注册完，项目就可以直接使用，而不是报找不到渲染器的错误

### ISSUE THREAD

**Issue by zhanggq1014** [baidu/amis#6392]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by zhanggq1014** [comment]
> 

没有，你解决了吗

**Comment by zhanggq1014** [comment]
> 你好请问你注册成功了吗我遇到了同样的问题

没有，请问你解决了吗

**Comment by 2betop** [comment]
编辑器应该是设计态才会加载，运行时是不应该加在的，所以两个是分开的。
