### ISSUE TITLE
之前有说近期 amis-editor 项目将会拆分，将 plugins 开源，方便进行调整。目前有何进展吗？

### ISSUE THREAD

**Issue by nekic** [baidu/amis#6396]
之前有说近期 amis-editor 项目将会拆分，将 plugins 开源，方便进行调整。目前有何进展吗？

**Comment by hyzx86** [comment]
你说的是这个么？https://github.com/aisuda/amis-widget

**Comment by nwind** [comment]
editor 源码已经合入了 #6413
