### ISSUE TITLE
嵌套的combo和input-table无法删除

### ISSUE THREAD

**Issue by vexos-io** [baidu/amis#6398]
如下图这样的input-table下继续包含input-table，当子input-table删除时一条时，form的data不变化，请确认

<img width="927" alt="截屏2023-03-19 14 10 59" src="https://user-images.githubusercontent.com/56525941/226157100-2f8e4659-f2d6-4d66-ab40-96e161945cf4.png">

**Comment by 2betop** [comment]
不能复现，看起来没问题 
<img width="1874" alt="image" src="https://github.com/baidu/amis/assets/2698393/131234b9-a89e-4b88-91a0-0a6064fb192b">
