### ISSUE TITLE
icon想要用ant design要怎么做？

### ISSUE THREAD

**Issue by sringly** [baidu/amis#643]

**Comment by 2betop** [comment]
目前不支持

**Comment by llfylwg** [comment]
目前icon只支持fontawesome么？🤣

**Comment by 2betop** [comment]
嗯，主要是 antd 的 icon 是 svg 的，不是字体图标，如果是字体图标会比较好整合，你可以看看别的 字体图标。

**Comment by 2betop** [comment]
amis 内部有些 组件 icon 也是 svg，这个要换的话，需要用js 调用 `registerIcon` 覆盖。

**Comment by llfylwg** [comment]
目前看来是没法替换antd的icon了，这个有计划支持么？

**Comment by llfylwg** [comment]
那我要把antd的svg文件放到amis中，是不是就可以了

**Comment by 2betop** [comment]
看你在哪用，如果是组件里面的是可以用 svg 来输出icon的，如果是 amis 组件配置里面的 icon 属性，现在是没办法支持svg的

**Comment by llfylwg** [comment]
我看Button组件里的icon，是通过icon属性传class的，里面是<i class={icon} />这么用的，意思是这块我替换成antd的Icon组件是没用的？

**Comment by 2betop** [comment]
对，没用，你可以改改渲染器，扩充一种按钮类型

**Comment by llfylwg** [comment]
renders里新建个icon的组件，但是好像里面的console根本不会走
