### ISSUE TITLE
自定义组件-Sdk方式注册组件  

### ISSUE THREAD

**Issue by wangyuan214155** [baidu/amis#6450]
你好我想注册自定义组件

并且想使用ant-design-vue中的组件（本人项目当前使用的是vue3技术栈）但是按照文档上的方法 并没有成功
是现在还不支持vue3的写法吗，本人小白 是不是哪里写的不太对

###代码

	function CustomComponent (props) {
		console.log(props, 11111)

		let dom = React.useRef(null);

		React.useEffect(function () {
			// @ts-ignore
			dom.current.innerHTML = `<a-button>1111</a-button>`
			const aButton = {
				name: 'a-button',
				props: {
					label: {
						type: String,
						default: '测试'
					}
				},
				template: `<a-button>{{label}}</a-button>`
			}
			const testButton = {
				data () {
					return {
						label: '',
					}
				},
				components: {
					'a-button': aButton
				},
			}
			console.log(createApp, 3333)

			createApp(testButton).mount(dom.current)

			// new Vue({
			// 	el: dom.current,
			// 	// data: function () {
			// 	// 	return { visible: false };
			// 	// }
			// });
		})
		return React.createElement('div', {
			ref: dom
		})
	}

**Comment by tierney603** [comment]
`
function diyTemplate(props) {
    // 自定义组件，props 中可以拿到配置中的所有参数，比如 props.label 是 'Name'
    let { label } = props
    
    let dom = React.useRef({});
    React.useEffect(function () {

        // <template></template>
        dom.current.innerHTML = `
            <el-button @click="btnclick()">{{label}}</el-button>
          `;

        new Vue({
            el: dom.current,
            data: () => {
                return { label: label || "按钮" };
            },
            methods: {
                btnclick: function (event) {
                    alert('Hello ' + '!')
                }
            }
        });
    });
    return React.createElement('div', {
        ref: dom
    });
}

amisLib.Renderer({
    test: /(^|\/)diy-template/
})(diyTemplate);
`

**Comment by tierney603** [comment]
`

function diyTemplate(props) {
    // 自定义组件，props 中可以拿到配置中的所有参数，比如 props.label 是 'Name'
    let { label } = props
    
    let dom = React.useRef({});
    React.useEffect(function () {

        // <template></template>
        dom.current.innerHTML = `
            <el-button @click="btnclick()">{{label}}</el-button>
          `;

        new Vue({
            el: dom.current,
            data: () => {
                return { label: label || "按钮" };
            },
            methods: {
                btnclick: function (event) {
                    alert('Hello ' + '!')
                }
            }
        });
    });
    return React.createElement('div', {
        ref: dom
    });
}

amisLib.Renderer({
    test: /(^|\/)diy-template/
})(diyTemplate);


`
