### ISSUE TITLE
input-tree 的 menuTpl 如果设置了event 无法使用preventDefault阻止监听事件默认行为

### ISSUE THREAD

**Issue by baozhoutao** [baidu/amis#6456]
`
{
  'type': 'input-tree',
  'menuTpl': {
     'type': 'tpl',
     onEvent: {}
  }
}
`

**Comment by hsm-lv** [comment]
onEvent中的preventDefault主要是来阻止派发事件的组件的事件逻辑的默认行为，因此你的例子中是tpl的事件默认行为，不知道这样说你能理解了不
