### ISSUE TITLE
type:picker,多选模式选中的值会被清空

### ISSUE THREAD

**Issue by jokerys** [baidu/amis#647]
![image](https://user-images.githubusercontent.com/39823370/83604150-45a8ca80-a5a8-11ea-8f9d-7a76b0d7c3f5.png)
如图，先选中默认企业，再次添加搜索条件，返回的数据不包含默认企业，选中的默认企业会被清空

Amis版本： 1.0.1

**Comment by 2betop** [comment]
那你试下最新版本
