### ISSUE TITLE
是否考虑将事件动作中的 actionType 与原有的行为按钮的 actionType 合二为一？

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#6474]
## 概述

统一两种action的行为定义，提高扩展的便利性。

## 动机

事件动作中的 actionType 支持注册自定义动作，但是原来的行为按钮 actionType 好像都是硬编码写死的，如果这两个能够统一起来，将大大提高扩展的便利性。
也许还能降低用户的学习成本？

**Comment by hsm-lv** [comment]
目前不会考虑合并，事件动作的设计相对解耦，比较灵活
