### ISSUE TITLE
iOS 13.7 safari 加载时报错：Can't find variable: DragEvent

### ISSUE THREAD

**Issue by EvanZheng11** [baidu/amis#6476]
#### 描述问题：
版本：amis@2.3.1

iOS 13.7 safari 加载时报错：Can't find variable: DragEvent

#### 截图或视频：

<img width="461" alt="image" src="https://user-images.githubusercontent.com/9478026/227897474-b72ca55e-b61e-44c8-94d8-44514f66fe0b.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by EvanZheng11** [comment]
官网也会

**Comment by nwind** [comment]
新版已修了
