### ISSUE TITLE
link能不能根据条件判断是否跳转

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#648]
![image](https://user-images.githubusercontent.com/64950961/83620607-2027bb00-a5c0-11ea-870d-35bf45f20c31.png)
在单行操作里边定义了一个跳转标签，会跳转到新页面，同时会带一个查询参数到新页面的crud的api中，我想做成如果查询不到内容的话，就不做跳转，这个可以实现吗

**Comment by 2betop** [comment]
不支持，跳转的时候根本就还没开始查询

**Comment by 2betop** [comment]
当然要是你把结果放在其实的 crud 里面的，是可以通过visibleOn 来展示不展示这个链接的

**Comment by tanmengfei** [comment]
那如果我把link改成一个发送ajax请求的按钮，请求的api是第二个页面crud的api，可以根据返回结果，判定是否redirect吗

**Comment by 2betop** [comment]
可以， redirect 通过 lodash template 语法，在不满足条件的情况下是是个空，就不会跳转了

**Comment by tanmengfei** [comment]
我之前是通过给link加上参数，跳转的时候参数会直接当做新页面api的查询过滤条件；那如果我换成ajax请求的话，如何实现之前的效果呢

**Comment by 2betop** [comment]
配置 redirect属性啊
