### ISSUE TITLE
amis中怎么触发Vue自定义组件中定义的method

### ISSUE THREAD

**Issue by jwxhhxx** [baidu/amis#6480]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by wibetter** [comment]
看下这个使用文档：https://aisuda.github.io/aisuda-docs/NPM%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E5%A6%82%E4%BD%95%E5%AF%B9%E6%8E%A5amis%E4%BA%8B%E4%BB%B6%E5%8A%A8%E4%BD%9C/#%E4%BA%8C%E5%85%B6%E4%BB%96%E7%BB%84%E4%BB%B6%E5%A6%82%E4%BD%95%E8%A7%A6%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E7%9A%84%E5%8A%A8%E4%BD%9C

**Comment by wibetter** [comment]
看下这个文档：https://aisuda.github.io/aisuda-docs/NPM%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E5%A6%82%E4%BD%95%E5%AF%B9%E6%8E%A5amis%E4%BA%8B%E4%BB%B6%E5%8A%A8%E4%BD%9C#%E4%BA%8C%E5%85%B6%E4%BB%96%E7%BB%84%E4%BB%B6%E5%A6%82%E4%BD%95%E8%A7%A6%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E7%9A%84%E5%8A%A8%E4%BD%9C
