### ISSUE TITLE
api请求数据

### ISSUE THREAD

**Issue by chenyphaaa** [baidu/amis#649]
api的配置可以配置成前端的js函数吗？想使用前端js函数去获取导航数据然后加载到table中

**Comment by RickCole21** [comment]
导航数据是指地址栏里的参数？

**Comment by RickCole21** [comment]
你可以写requestAdaptor，自定义请求api结构

**Comment by chenyphaaa** [comment]
> 导航数据是指地址栏里的参数？

是左侧导航菜单，const navigations:Array<NavItem> = []，定义在了这个里面，我通过js函数去获取这个数组里面的元素

**Comment by chenyphaaa** [comment]
不需要调用后端接口

**Comment by RickCole21** [comment]
说下原始需求吧，我没太看懂你想干啥

**Comment by chenyphaaa** [comment]
是这样的，我想做一个权限管理的页面，需要加载所有的菜单到Checkboxes里面，这个菜单是配在前端页面的一个数组里面的，我在前端写js函数就可以获取到这个数组里面的元素，我想把我js函数获取到的数据加载到Checkboxes里面，不需要请求后端api

**Comment by RickCole21** [comment]
那你checkboxes直接设置options不就行了？

**Comment by chenyphaaa** [comment]
> 你配置那里如果能拿到导航数组，那你checkboxes直接设置options不就行了

理解了，这个checkboxes中默认选择了哪些值是想通过后端接口来确定的，这个有什么方法嘛

**Comment by RickCole21** [comment]
form初始化接口里加上这个值吧

**Comment by chenyphaaa** [comment]
谢谢大佬
