### ISSUE TITLE
InputTable 添加时比较慢，而且一个列输完之后，再输入另外一个列，也存在卡顿

### ISSUE THREAD

**Issue by songyinhai2006** [baidu/amis#6499]
#### 描述问题：

InputTable 添加时比较慢，而且一个列输完之后，再输入另外一个列，也存在卡顿

#### 截图或视频：

![image](https://user-images.githubusercontent.com/52561802/228588292-7cf7ff36-44ef-40b0-b4dc-1f0826bf5ebb.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.8.0

3. 粘贴有问题的完整 `amis schema` 代码：
无

4. 操作步骤
见截图

**Comment by songyinhai2006** [comment]
补充：在修改的时候，点击新增那两个字特别慢。

https://user-images.githubusercontent.com/52561802/228595063-b43bc9b0-324a-4443-b4f5-4d60b228226f.mp4

**Comment by songyinhai2006** [comment]
作者好，我看了一下，也有其他小伙伴提出了类似的问题，这个使用场景也很常见，作者有没有改进计划？

**Comment by 2betop** [comment]
master 分支已优化部分，打算进一步优化 form 内部

**Comment by songyinhai2006** [comment]
> master 分支已优化部分，打算进一步优化 form 内部

作者好，测试了一下，80条数据

**Comment by 2betop** [comment]
能否提供一下 schema？目前看好像不太卡

**Comment by 2betop** [comment]
目前最新版本没发现卡顿，有问题再 reOpen
