### ISSUE TITLE
引入编辑器插件报错

### ISSUE THREAD

**Issue by zhanggq1014** [baidu/amis#6512]
#### 描述问题：

Error: The renderer with name "bat-editor" has already exists, please try another name!

#### 截图或视频：
![企业微信截图_16802526222239](https://user-images.githubusercontent.com/54018170/229073534-fc921367-342e-4f64-b477-63ada53d0d5f.png)

**Comment by liwu3230** [comment]
+1

**Comment by 2betop** [comment]
`bat-editor` 不是官方组件，请自己找问题
