### ISSUE TITLE
希望crud等列表类空间支持类似combo根据index跟新本行数据

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#6513]
现在crud如果单行配置service api获取数据，会更新整个表的数据，让每行都变成一样的。希望可以只更新本行数据而不影响其他行。

**Comment by 2betop** [comment]
<img width="537" alt="image" src="https://github.com/baidu/amis/assets/2698393/c71d4542-dd3d-4899-a289-60c4927305da">


没能复现，看起来每个单元格都是自己的数据。抱歉长时间没回复，遇到问题再开
