### ISSUE TITLE
官网最新amis项目在运行编辑器的时候，报“mobx-state-tree”相关的错误

### ISSUE THREAD

**Issue by citynook** [baidu/amis#6517]
#### 描述问题：

下载官网最新的amis项目，运行后通过本地网址：http://127.0.0.1:8888/packages/amis-editor/
进入到编辑器，添加CURD控件后，进入《编辑》按钮的配置界面时，浏览器捕捉到异常，详见下方截图。

#### 截图或视频：

![image](https://user-images.githubusercontent.com/127393297/229353837-8a89c4ba-c4fe-48c2-8bd5-3bed4e505383.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
在此官网下载的最新版本的amis项目。

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "button",
  "label": "编辑",
  "actionType": "dialog",
  "level": "link",
  "dialog": {
    "title": "编辑",
    "body": {
      "type": "form",
      "api": "xxx/update",
      "body": [
        {
          "name": "id",
          "label": "ID",
          "id": "u:b964ae6a18db",
          "type": "input-text"
        },
        {
          "name": "engine",
          "label": "渲染引擎",
          "id": "u:5bd838561553",
          "type": "input-text"
        }
      ]
    }
  },
  "id": "u:3a10e1e160b4"
}
```

4. 操作步骤
1. 进入到编辑器
2. 添加CURD控件
3. 选中《编辑》按钮，打开配置界面的对话框时，浏览器捕捉到异常。

**Comment by fanzhenyang** [comment]
我的一运行就报错：
版本号如下：
 "amis": "^2.9.0",
  "amis-core": "^2.9.0",
  "amis-editor": "^5.2.5-beta.5",
  "amis-editor-core": "^5.2.5-beta.6",
  "amis-formula": "^2.9.0",
  "amis-ui": "^2.9.0",
  "amis-widget": "^3.1.0",
  "react": "^17.0.2",
  "react-dom": "^17.0.2",

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/28777952/229721939-1730be41-078a-44c9-be31-ca4db11750f5.png">

**Comment by citynook** [comment]
官网线上demo没有这个错误，但是下载官网源码直接编译运行就会报这个错误，这是什么原因？

**Comment by citynook** [comment]
现在官网都不理睬这类小问题了吗？

**Comment by hyzx86** [comment]
换成  下面试试？
    "react": "^18.2.0",
    "react-dom": "^18.2.0",

**Comment by citynook** [comment]
> 换成 下面试试？ "react": "^18.2.0", "react-dom": "^18.2.0",

我是从官网下载的源码，没有做任何修改，直接编译运行报的这个错误，官网源码用的react都是18.2的版本。

**Comment by hyzx86** [comment]
😂那看来不是我环境问题了，
我在umi里面也是这样，很多按钮不能用了
部分组件无法拖拽

**Comment by citynook** [comment]
> 😂那看来不是我环境问题了， 我在umi里面也是这样，很多按钮不能用了 部分组件无法拖拽

我也不清楚是什么情况，官网的线上demo就是正常的，但下载源码运行就会报这个错误，谷歌浏览器也是最新版的~

**Comment by citynook** [comment]
如果在其它项目中集成，要用正式版本，amis-editor用beta版本会有异常错误。
"amis": "^2.9.0",
"amis-core": "^2.9.0",
"amis-editor": "^5.2.5",

**Comment by hyzx86** [comment]
Editor 这个问题有点蛋疼~
![image](https://user-images.githubusercontent.com/15613121/234206444-783c4a1a-dac3-458d-9e94-fc13b42dc1c2.png)
我也来看Editor源码了 
![W5$FYAC3R}Y J(5QS7Y036A](https://user-images.githubusercontent.com/15613121/234200313-c4e88944-abde-47ae-91ef-9085a8728560.png)

你们也用 iframe了么？

**Comment by citynook** [comment]
@hyzx86 我是在其它项目中集成 amis 2.9，项目是 vite + vue3的前端，查看node_modules后，发现amis-edit是 5.2.5 版本，但它下载的依赖 amis-edit-core 却是 5.2.5.beta版本，版本不一致造成编译错误。

最开始package.json中只引用了 amis和amis-editor这两个，后面又添加了 amis-edit-core，保持和 amis-editor同一个版本，就不会发生错误了。

我没用iframe，是在vue文件里通过 "veaury": "2.3.12" 包引入 react组件实现的，可以运行，但会时不时发生错误，很头疼~

**Comment by hyzx86** [comment]
我在 umi里 头疼~

**Comment by citynook** [comment]
@hyzx86 如果项目是react的，集成amis应该不太容易出错，但集成到vue项目中，经常出错。下面是我在vue3里引用的依赖，经过反复验证。

    "@fortawesome/fontawesome-free": "6.3.0",
    "@types/react": "18.0.24",
    "@types/react-dom": "18.0.8",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "sass": "^1.60.0",
    "vite-plugin-monaco-editor": "1.1.0",
    "copy-to-clipboard": "3.3.1",
    "veaury": "2.3.12",
    "amis": "2.9.0",
    "amis-editor": "5.2.5",
    "amis-editor-core": "5.2.5"

vite.config.ts 也要添加  monaco-editor 要用到的资源，否则在编辑器里打开代码面板时会报错。

    optimizeDeps: {
      esbuildOptions: {
        target: 'es2020',
      },
      // @iconify/iconify: The dependency is dynamically and virtually loaded by @purge-icons/generated, so it needs to be specified explicitly
      include: [
        '@vue/runtime-core',
        '@vue/shared',
        '@iconify/iconify',
        'ant-design-vue/es/locale/zh_CN',
        'ant-design-vue/es/locale/en_US',
        'monaco-editor/esm/vs/language/json/json.worker',
        'monaco-editor/esm/vs/language/css/css.worker',
        'monaco-editor/esm/vs/language/html/html.worker',
        'monaco-editor/esm/vs/language/typescript/ts.worker',
        'monaco-editor/esm/vs/editor/editor.worker',
      ],
    },

**Comment by hyzx86** [comment]
monaco 不是有现成的组件么，你居然自己搞worker
去年我用vben 搞了一个版本，但是 样式兼容问题太多 ，放弃了 ，如果有需要可以看看
https://github.com/EasyOC/EasyOC.VbenAdmin

**Comment by hyzx86** [comment]
> "@fortawesome/fontawesome-free": "6.3.0",

这东西 官方文档明确说明只支持到 5

**Comment by citynook** [comment]
@hyzx86 你可能理解错了，vite里如果不引用 monaco-editor 的这些workder，amiseditor打开代码面板时会出错，我没有自己做任何worker，amis editor使用了monaco-editor。

"@fortawesome/fontawesome-free": "6.3.0"
 这个也是amiseditor源码中引用的，我只是照常引用。

**Comment by hyzx86** [comment]
> "@fortawesome/fontawesome-free": "6.3.0"
这个也是amiseditor源码中引用的，我只是照常引用。

源码也没这么高。。
![image](https://user-images.githubusercontent.com/15613121/234308383-4cbdb40f-ccd5-4445-91ac-51766128341c.png)

**Comment by citynook** [comment]
@hyzx86 确实没这么高，我升级了一下，没看到发生啥异常，就用着了

**Comment by WangHao1221** [comment]
> @hyzx86 如果项目是react的，集成amis应该不太容易出错，但集成到vue项目中，经常出错。下面是我在vue3里引用的依赖，经过反复验证。
> 
> ```
> "@fortawesome/fontawesome-free": "6.3.0",
> "@types/react": "18.0.24",
> "@types/react-dom": "18.0.8",
> "react": "18.2.0",
> "react-dom": "18.2.0",
> "sass": "^1.60.0",
> "vite-plugin-monaco-editor": "1.1.0",
> "copy-to-clipboard": "3.3.1",
> "veaury": "2.3.12",
> "amis": "2.9.0",
> "amis-editor": "5.2.5",
> "amis-editor-core": "5.2.5"
> ```
> 
> vite.config.ts 也要添加 monaco-editor 要用到的资源，否则在编辑器里打开代码面板时会报错。
> 
> ```
> optimizeDeps: {
>   esbuildOptions: {
>     target: 'es2020',
>   },
>   // @iconify/iconify: The dependency is dynamically and virtually loaded by @purge-icons/generated, so it needs to be specified explicitly
>   include: [
>     '@vue/runtime-core',
>     '@vue/shared',
>     '@iconify/iconify',
>     'ant-design-vue/es/locale/zh_CN',
>     'ant-design-vue/es/locale/en_US',
>     'monaco-editor/esm/vs/language/json/json.worker',
>     'monaco-editor/esm/vs/language/css/css.worker',
>     'monaco-editor/esm/vs/language/html/html.worker',
>     'monaco-editor/esm/vs/language/typescript/ts.worker',
>     'monaco-editor/esm/vs/editor/editor.worker',
>   ],
> },
> ```

我用的webpack，没有用vite，是不是就不需要引入monnaco相关？我用的如下版本，浏览器控制台报错
e-router.esm-bundler.js:3295 Error: The renderer with name "bat-editor" has already exists, please try another name!
    at registerRenderer (factory.js:53:1)
    at registerFormItem (Item.js:868:1)
    at eval (Item.js:872:1)
    at DecorateConstructor (Reflect.js:541:1)
    at Reflect.decorate (Reflect.js:130:1)
    at Module.__decorate (tslib.es6.js:57:1)
    at eval (Editor.js:246:1)
    at eval (Editor.js:253:1)
    at Array.map (<anonymous>)
    at eval (Editor.js:237:1)
t

**Comment by citynook** [comment]
我也是前端小白，找个现成的vite + vue3 项目，集成的amis editor。因为是使用veaury插件在vue中加载react控件，所以在使用编辑器的时候，右侧面板经常会发生渲染错误，已经提了issue给veaury作者，但尚未有回复。

**Comment by hyzx86** [comment]
我的问题解决了。。因为我定义的Rendder  有问题。。
UseEffect 里面做了一些坏事。。
![image](https://user-images.githubusercontent.com/15613121/236378894-65ca39fb-cf6b-4196-832f-daa1c0d3ca97.png)

**Comment by WangHao1221** [comment]
> 我的问题解决了。。因为我定义的Rendder 有问题。。 UseEffect 里面做了一些坏事。。 ![image](https://user-images.githubusercontent.com/15613121/236378894-65ca39fb-cf6b-4196-832f-daa1c0d3ca97.png)

你也是vue3+webpack5吗？可否看下package.json里面引用的相关版本以及.vue文件引入方式？核对下问题在哪里

**Comment by hyzx86** [comment]
我是umi4 amis包全是最新的
&nbsp;

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月5日(周五) 下午2:00
收件人: ***@***.***&gt;;
抄送: "Tony ***@***.******@***.***&gt;;
主题: Re: [baidu/amis] 官网最新amis项目在运行编辑器的时候，报“mobx-state-tree”相关的错误 (Issue #6517)




  
我的问题解决了。。因为我定义的Rendder 有问题。。 UseEffect 里面做了一些坏事。。 
  
你也是vue3+webpack5吗？可否看下package.json里面引用的相关版本以及.vue文件引入方式？核对下问题在哪里

**Comment by WangHao1221** [comment]
> 我是umi4 amis包全是最新的 &nbsp;
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年5月5日(周五) 下午2:00 收件人: ***@***.***&gt;; 抄送: "Tony ***@***.******@***.***&gt;; 主题: Re: [baidu/amis] 官网最新amis项目在运行编辑器的时候，报“mobx-state-tree”相关的错误 (Issue #6517) 我的问题解决了。。因为我定义的Rendder 有问题。。 UseEffect 里面做了一些坏事。。 你也是vue3+webpack5吗？可否看下package.json里面引用的相关版本以及.vue文件引入方式？核对下问题在哪里 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

用的umi啊，veaury版本是多少？.vue文件里面引入方式和我这个有区别吗?帮我看下哪里不对 <template>
   <section class="amis">
     <amisEditor
      className="is-fixed"
      :isMobile="isMobile"
      :preview="handlePreviewChange"
      theme="cxd"
      :value="schema"
      :onChange="onChange"
      :onSave="onSave"
      :actionOptions="actionOptions"
    />
  </section>
</template>

<script>
import { defineComponent, ref, computed ,reactive, onMounted,onUnmounted ,watch} from "vue";
 import { Editor } from 'amis-editor';
  import '../../../../node_modules/amis-editor-core/lib/style.css';
  import 'amis/lib/themes/cxd.css';
  import { applyPureReactInVue } from 'veaury';
export default defineComponent({
  name: 'ChainLog',
  components: {
    amisEditor: applyPureReactInVue(Editor)
    },
    setup() {
      let isMobile = false;
      const actionOptions = {
          showOldEntry: false,
      }
      let schema = {
        type: 'page',
        title: 'Simple Form Page',
        body: [
          {
            type: 'form',
            body: [
              {
                type: 'input-text',
                name: 'a',
                label: 'Text'
              }
            ]
          }
        ]
      }
      const onChange = (v) => {
        console.log('onChange...',v);
      }

      const handlePreviewChange = (e) => {
        console.log(JSON.stringify(e));
      }
      const onSave = () => {
        console.log('save....')
      }
      return {
        isMobile,
        actionOptions,
        schema,
        handlePreviewChange,
        onChange,
        onSave
      };
    }
});
</script>

<style scoped lang="less">
.amis {
    width: 100%;
    height: 100% !important;

    #editor {
      width: 100%;
      height: 100% !important;
    }
  }

  .ae-Editor .ae-Editor-inner {
    height: 100% !important;
  }
</style>

**Comment by hyzx86** [comment]
umi 是react 不用 veaury

**Comment by WangHao1221** [comment]
`<template>
   <section class="amis">
     <amisEditor
      className="is-fixed"
      :isMobile="isMobile"
      :preview="handlePreviewChange"
      theme="cxd"
      :value="schema"
      :onChange="onChange"
      :onSave="onSave"
      :actionOptions="actionOptions"
    />
  </section>
</template>

<script>
import { defineComponent, ref, computed ,reactive, onMounted,onUnmounted ,watch} from "vue";
 import { Editor } from 'amis-editor';
  import '../../../../node_modules/amis-editor-core/lib/style.css';
  import 'amis/lib/themes/cxd.css';
  import { applyPureReactInVue } from 'veaury';
export default defineComponent({
  name: 'ChainLog',
  components: {
    amisEditor: applyPureReactInVue(Editor)
    },
    setup() {
      let isMobile = false;
      const actionOptions = {
          showOldEntry: false,
      }
      let schema = {
        type: 'page',
        title: 'Simple Form Page',
        body: [
          {
            type: 'form',
            body: [
              {
                type: 'input-text',
                name: 'a',
                label: 'Text'
              }
            ]
          }
        ]
      }
      const onChange = (v) => {
        console.log('onChange...',v);
      }

      const handlePreviewChange = (e) => {
        console.log(JSON.stringify(e));
      }
      const onSave = () => {
        console.log('save....')
      }
      return {
        isMobile,
        actionOptions,
        schema,
        handlePreviewChange,
        onChange,
        onSave
      };
    }
});
</script>

<style scoped lang="less">
.amis {
    width: 100%;
    height: 100% !important;

    #editor {
      width: 100%;
      height: 100% !important;
    }
  }

  .ae-Editor .ae-Editor-inner {
    height: 100% !important;
  }
</style>`

**Comment by WangHao1221** [comment]
> umi 是react 不用 veaury

哎这可能就是兼容性的问题了，用react集成问题应该少很多，非常感谢啊！我再试试

**Comment by citynook** [comment]
react的项目，基本上按官方demo用就行了，vue还需要veaury才能使用amis-editor组件，而且偶尔会发生莫各其妙的错误，头大~

**Comment by WangHao1221** [comment]
> react的项目，基本上按官方demo用就行了，vue还需要veaury才能使用amis-editor组件，而且偶尔会发生莫各其妙的错误，头大~

是啊，主要现在问题就是在现有vue3+webpack+js基础上叠加

**Comment by hyzx86** [comment]
@WangHao1221  你这好纠结啊。。。vue3 了干嘛还用 webpack  官方也用的vite
