### ISSUE TITLE
status的source参数已失效

### ISSUE THREAD

**Issue by zyazhb** [baidu/amis#6520]
#### 描述问题：

status的source参数已失效

#### 截图或视频：

官网版本已经异常
https://baidu.github.io/amis/zh-CN/components/status

**Comment by zyazhb** [comment]
https://baidu.github.io/amis/zh-CN/components/status#%E5%8A%A8%E6%80%81%E6%95%B0%E6%8D%AE
@2betop

**Comment by 2betop** [comment]
新版本没有问题，应该是已经修复了，有问题再开
