### ISSUE TITLE
新版本的编辑器，page组件用css属性写的css类会被自动转换成错误的格式

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#6524]
#### 描述问题：
用新版本的编辑器，page组件用css属性写的css类会被自动转换成错误的格式

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...
![微信图片_20230404144414](https://user-images.githubusercontent.com/45064164/229710339-6477964c-cd12-4438-98f6-273d500fb3f3.png)

![228428112-59632462-82b8-46eb-af58-2b6966143f87.png](https://user-images.githubusercontent.com/45064164/229547939-c60bbd9d-4568-445f-a308-c42ed18c2a22.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by EvanZheng11** [comment]
遇到同样问题，等修复。

**Comment by Icodezhan** [comment]
@nwind @TeCHiScy @luckyufei

**Comment by Icodezhan** [comment]
@2betop @wibetter @nwind @blackmady @taosher

**Comment by Icodezhan** [comment]
可是以前是可以的呀，官方文档也说可以的，那升级版本后就不行了，那岂不是之前写的json都废了？不带这样的吧？
![图片](https://user-images.githubusercontent.com/45064164/230278025-1da8af0e-5595-461b-bb5a-40459b18dfad.png)
![图片](https://user-images.githubusercontent.com/45064164/230278036-62cbf812-47cb-47a0-bd28-ed233e49c7b0.png)

**Comment by Icodezhan** [comment]
>  可是以前是可以的呀，官方文档也说可以的，那升级版本后就不行了，那岂不是之前写的json都废了？不带这样的吧？
> ![图片](https://user-images.githubusercontent.com/45064164/230278025-1da8af0e-5595-461b-bb5a-40459b18dfad.png)
> ![图片](https://user-images.githubusercontent.com/45064164/230278036-62cbf812-47cb-47a0-bd28-ed233e49c7b0.png)
> 

@2betop @zhangtao07 @yangwei9012 @meerkat-morecats @wibetter @nwind 
求修复，把自定义css加回来

**Comment by wibetter** [comment]
已修复，请使用最新amis-editor、amis-editor-core版本：5.2.5-beta.7。
