### ISSUE TITLE
新版本编辑器所有组件的外观，边框第一个下拉框点击后会报错

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#6533]
#### 描述问题：

新版本编辑器所有组件的外观，边框第一个下拉框点击后会报错

#### 截图或视频：

![微信图片_20230404155420](https://user-images.githubusercontent.com/45064164/229725922-c52e9a5d-49b1-4bb9-acaf-43b441cb69a4.png)
![微信图片_20230404155444](https://user-images.githubusercontent.com/45064164/229725945-6731dcb9-4033-4f2c-b53f-0788384f80d3.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by Icodezhan** [comment]
@2betop @wibetter @nwind @blackmady @taosher

**Comment by liukai3586** [comment]
我页遇到了这个问题，每个组件 -》外观-》边框 一点就报错

**Comment by LeahLeahWang** [comment]
我也遇到了相同的问题，边框第一个下拉框点击后会报错

**Comment by 2betop** [comment]
新版本已不能复现，请升级到最新版本，有问题再 ReOpen
