### ISSUE TITLE
抽屉式弹框 点击下拉框时弹框会移动到左边

### ISSUE THREAD

**Issue by jackphang** [baidu/amis#6538]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

npm 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.9.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

1. 我定义了一个抽屉式弹框，默认在右边弹出，如下图：
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/26587479/229805149-755a0ab5-7180-4b0c-b82a-be222c606640.png">
2. 当我点击分组 下拉框时，弹框跑到左边去了，如下图：
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/26587479/229805456-3f23d0d9-411d-47ad-886a-ae492b53c18d.png">

**Comment by csx-bill** [comment]
用cxd 样式试试

**Comment by 2betop** [comment]
不能复现，应该是新版没问题了，有问题再开

**Comment by cuixiaojun001** [comment]
依然存在问题

**Comment by githubczb** [comment]
现在2025年了 还有这个问题

**Comment by csx-bill** [comment]
> 现在2025年了 还有这个问题 但是暗黑模式不会

放弃amis了 平替产品 https://www.marsview.com.cn

**Comment by githubczb** [comment]
有没有解决方案啊

**Comment by zbl400** [comment]
是 css 的引入次序问题。
``` <div class="antd-Drawer-content in has-popover">```，   
这个div中， antd-Drawer-content  和 has-popover 分别都定义了position，值不同。 并且 antd-Drawer-content 定义在后，  has-popover  在前。
所以    
单独引入 antd.css ，使用 antd 样式，不会出错；  
单独引入 cxd.css 使用 cxd样式，也不会出错；  
一旦  
先后引入  antd.css ，cxd.css ，然后使用 antd 样式，就会出错。  
同样， 先后引入cxd.css，antd.css 然后使用 cxd 样式，也会出错。
