### ISSUE TITLE
amis-editor初始化点击代码json配置报错

### ISSUE THREAD

**Issue by fanzhenyang** [baidu/amis#6539]
#### 描述问题：
我在运行项目后，点击左侧第三个栏目代码，然后就报错

#### 截图或视频：

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/28777952/230254371-1a1af7e5-61a7-4d00-a4cc-e0538f08e058.png">
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/28777952/230254457-9e7eed26-a4f3-40f8-aa7b-77964398d082.png">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm install amis

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
  "amis": "^2.9.0",
    "amis-core": "^2.9.0",
    "amis-editor": "^5.2.5-beta.5",
    "amis-editor-core": "^5.2.5-beta.6",
3. 粘贴有问题的完整 `amis schema` 代码：
```
 <div className="App">
      <Editor className={"jqp-amis-editor-body"}  preview={preview} isMobile={mobile} onChange={onChange} value={schema} theme={"cxd"} onSave={onSave} showCustomRenderersPanel={true}  $schemaUrl={schemaUrl} />
    </div>
```

4. 操作步骤
初始化出编辑自定义页面，然后点击左侧的代码栏目，就抛出出错

**Comment by Icodezhan** [comment]
你amis-editor-core和amis-editor保持一致试试

**Comment by fanzhenyang** [comment]
> 你amis-editor-core和amis-editor保证一试

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/28777952/230255985-c1923852-a30d-4769-8c26-68a66701db51.png">
我升级了   amis-editor
 "amis-editor": "^5.2.5-beta.6",
  "amis-editor-core": "^5.2.5-beta.6"，
还是抛出了错误，但是我发现我组件中只有这个地方加载了amis-editor-core包下面的css
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/28777952/230256212-063886c1-48d6-4d76-8b10-e3867a51047b.png">

**Comment by hyzx86** [comment]
Monaco editor 的worker 配了吗？

**Comment by Niqian** [comment]
> Monaco editor 的worker 配了吗？

我也要类似问题，需要配置什么呢？

**Comment by wibetter** [comment]
这个是amis项目还是amis-editor-demo啊？

**Comment by wibetter** [comment]
@fanzhenyang 请升级amis-editor到最新版本（5.6.1），新版本无此问题。
