### ISSUE TITLE
page页面自定义css设置后格式变成无法编辑的了

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#6555]
#### 描述问题：

page页面自定义css设置后格式变成无法编辑的了

#### 截图或视频：
page页面是有自定义css功能的，但是现在编辑报错后变成图片的样子了，虽然样式是生效的，但是这样无法对原有的css代码进行修改了
![172c249c9346973fa3f7c9780a6cc24](https://user-images.githubusercontent.com/45064164/230539048-8dd28f6c-75f5-44c1-8751-41f90d32a11f.png)
![b06aaccb06ed93c9f1ac058868a2e79](https://user-images.githubusercontent.com/45064164/230539120-14eb411a-4e6d-4e85-ba6f-f6b357f72358.png)
 应该是这位老哥把这部分代码改坏了
@qkiroc 

![1c766375e91ea16a3ff8f08085846c6](https://user-images.githubusercontent.com/45064164/230539259-68c28b01-683b-4fe0-b3f1-7a8f91b9ed46.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
  2.9.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by Icodezhan** [comment]
@qkiroc @wibetter 两位帮忙改一下

**Comment by Icodezhan** [comment]
@qkiroc @wibetter 正常的逻辑是把自动生成的.myClass属性隐藏起来，而不是把css属性隐藏起来，把page的css属性隐藏起来后就没办法编辑了，我升级到最新版编辑器后以前写的json都出问题了

**Comment by Icodezhan** [comment]
@qkiroc @wibetter 两位麻烦看一下

**Comment by wibetter** [comment]
已修复，请使用最新amis-editor、amis-editor-core版本：5.2.5-beta.7。

**Comment by Icodezhan** [comment]
> 已修复，请使用最新amis-editor、amis-editor-core版本：5.2.5-beta.7。

好像并没有，即使我删除了node_modules，更新amis-editor、amis-editor-core版本为5.2.5-beta.7，重新下载依赖，然后我再使用page自定义css，保存后依旧会将page的css属性隐藏了，无法再次找到css属性进行编辑

**Comment by Icodezhan** [comment]
> @Icodezhan 是不是还没有删lock文件，可以执行npm list amis-editor确认下当前安装的版本。
> 你也可以在这个地址验证下：https://aisuda.github.io/amis-widget/test/preview.html
> <img width="1224" alt="image" src="https://user-images.githubusercontent.com/11958920/231150785-fb09fc74-e1c2-4b07-a6ec-227739b4884b.png">
> 

这个链接加载不出来，我本地删了lock之后也还是不行，你有空在amis-editor-demo那个项目更新一下amis-editor版本试一下
