### ISSUE TITLE
amis最新包报错

### ISSUE THREAD

**Issue by gentilezaLi** [baidu/amis#6557]
#### 描述问题：

amis最新包报错

#### 截图或视频：
![image](https://user-images.githubusercontent.com/51143925/230592724-ad8166d7-60de-4375-a628-e31d6cc91363.png)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
![image](https://user-images.githubusercontent.com/51143925/230592813-588f3bf7-5e89-4d63-ba7d-48ca1838aef5.png)

4. 粘贴有问题的完整 `amis schema` 代码：
5. 对于请求回来的数据set的时候
![image](https://user-images.githubusercontent.com/51143925/230592928-fe4fa380-177e-44e6-a0fe-2cb6846074e9.png)

```
code here...
```

6. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
请贴一下组件的代码？

**Comment by 2betop** [comment]
缺少反馈，先关了
