### ISSUE TITLE
有没有完整的例子？文档不完善

### ISSUE THREAD

**Issue by tlbgqq** [baidu/amis#656]
包含列表页、表单页、增删查改
还有像initFetchOn这种文档里光写了支持表达式，是支持什么格式的表达式也没有说明

**Comment by 2betop** [comment]
https://baidu.github.io/amis/crud/table?page=1
左侧导航里面还有很多

**Comment by tlbgqq** [comment]
> https://baidu.github.io/amis/crud/table?page=1
> 左侧导航里面还有很多
左侧的例子都不全，比如编辑页面设置了api去获取数据，页面中的下拉又是根据自己的api填充的，就会导致下拉的api填充时把已填写的数据覆盖掉
还有像initFetchOn这种也没找到详细说明或者例子

**Comment by RickCole21** [comment]
有问题先提issue吧，新版文档在路上了，预期这个季度放出

**Comment by tlbgqq** [comment]
> 有问题先提issue吧，新版文档在路上了，预期这个季度放出

编辑页面设置了api去获取数据，页面中的下拉又是根据自己的api填充的，就会导致下拉的api填充时把已填写的数据覆盖掉

**Comment by nuan1989** [comment]
> https://baidu.github.io/amis/crud/table?page=1
> 左侧导航里面还有很多
今天发现官网更新了文档. 谢谢.
