### ISSUE TITLE
curd表格中的列显示想要tpl，可是怎么获取到当前列数据的值？

### ISSUE THREAD

**Issue by rodchen-king** [baidu/amis#658]
curd表格中的列显示想要tpl，可是怎么获取到当前列数据的值？
测试过 items.xxx，item.xxx，data.xxx。可是都不行，也没再文档里找到具体的使用方式。

**Comment by RickCole21** [comment]
先参考下这个：https://baidu.github.io/amis/docs/renderers/Tpl#tpl

两种写法：`${xxx}`或者`<%= data.xxx %>`

**Comment by rodchen-king** [comment]
> 先参考下这个：https://baidu.github.io/amis/docs/renderers/Tpl#tpl
> 
> 简单来说有两种写法：`${xxx}`或者`<%= data.xxx %>`

好的，找到了具体的用法，是我用的不太对，因为我加了三元表达式，需要用它给的方式。你知道如何获取当前数据在table的索引值index吗？

**Comment by RickCole21** [comment]
应该是`rowIndex`，你试试

**Comment by rodchen-king** [comment]
> 应该是`rowIndex`，你试试

不行，我试了这个不行。就是不知道这里的怎么玩法，怎么获取到当前这一行

**Comment by RickCole21** [comment]
你说原始需求吧

**Comment by rodchen-king** [comment]
> 你说原始需求吧

好了，"tpl": '<%= data.index%>' 用这个可以，谢谢了啊，这个有群吗，可以大家沟通讨论的群

**Comment by RickCole21** [comment]
提issue就行

**Comment by rodchen-king** [comment]
> 提issue就行

ok，好
