### ISSUE TITLE
Select + autoComplete 请求API数据过多 label无法显示的问题

### ISSUE THREAD

**Issue by zhangyucumt** [baidu/amis#660]
现在遇到的问题是由于数据过多请求API 返回的数据只是一页的数据，无法全部拉取，就造成了数据只能显示value无法显示对应的label。
![image](https://user-images.githubusercontent.com/16399713/84009447-d9fa9f00-a9a5-11ea-9add-aa15e9baaa7a.png)
就像图中显示，第一个用户名字可以显示是因为这个用户在API请求的第一页，而第二个用户的名字无法显示是因为这个用户在后面

这个是配置
```json
{
    "name": "business_charger",
    "type": "select",
    "label": "\u4e1a\u52a1\u4fa7\u9879\u76ee\u8d1f\u8d23\u4eba",
    "size": "full",
    "required": false,
    "remark": null,
    "disabled": false,
    "autoComplete": "xxx/api/?search=${term}"
}
```

这个问题有什么好的解决办法吗？或者能否给term赋个初始值，使得每次都能拉倒对用的数据

**Comment by zhangyucumt** [comment]
或者能不能在这个显示框里面直接显示这个id对应的名字呢？

**Comment by 2betop** [comment]
这个问题主要原因是不知道对应的 label 是啥。有几个方案可以解决。

OptionA:  配置 joinValues: false, 这样值的格式就编程了Array<{label: string: value: any}> 了，这样肯定能正确显示 label 了。

OptionB: 配置个 source 接口 `source: "xxx/getOptions?value=${business_charger}"`  这个接口会在 select 初始化的候执行，如果这个接口把当前值的 options 信息返回了就会正确回显了。

**Comment by zhangyucumt** [comment]
试了第一种方法  配上了 joinValues: false  就可以正常显示了 感谢

**Comment by zhangyucumt** [comment]
之前amis的版本用的是 1.0.8-beta.42，当接口返回如下配置的时候
```json
{
    "name": "project",
    "type": "select",
    "label": "项目",
    "disabled": true,
    "joinValues": false,
    "multiple": false,
    "value":
    {
        "label": "【研2019-013】研发效能-持续交付系统2.0",
        "value": 768,
        "disabled": false
    }
}
```
前端可以正常渲染表单的值。
![image](https://user-images.githubusercontent.com/16399713/93417839-7d2f4e80-f8db-11ea-8cb5-7df95b98c2c6.png)

但是升级到 1.0.15 之后，这个配置就无法正常渲染了，
![image](https://user-images.githubusercontent.com/16399713/93417978-e020e580-f8db-11ea-9815-882be6ebd4b4.png)
必须配置 autoComplete 才可以。如下
```json
{
    "name": "project",
    "type": "select",
    "label": "项目",
    "disabled": true,
    "joinValues": false,
    "autoComplete": "http://test.uat1.rs.com:9002/time-sheet/api/v1/project/?search=$term",
    "multiple": false,
    "value":
    {
        "label": "【研2019-013】研发效能-持续交付系统2.0",
        "value": 768,
        "disabled": false
    }
}
```
但是这样会发送一遍ajax请求，而且返回的结果里面也不包含value的值，加载一次页面有好多个字段都会发送这个ajax。
有没有办法就是只显示值，而不用去发送ajax呢？
