### ISSUE TITLE
最新版CRUD组件批量操作数据域拿不到ids了

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#6600]
#### 描述问题：

最新版CRUD组件批量操作数据域拿不到ids了，按文档里说的【批量操作数据域】有以下：
![d13039d6b6cccfe9d309bcfad175e17](https://user-images.githubusercontent.com/45064164/231688418-2e6ea986-a435-4801-8b3f-ec1173f05755.png)
但是实际上现在只剩下了currentPageData、selectedItems、unSelectedItems这三个，ids拿不到数据了

#### 截图或视频：
例如下图这个之前批量操作数据域使用旧版本事件时，"url": "billMapping/deleteBatch?ids=${ids}"，这里的ids是拿得到数据的，但是现在使用新版本事件，就拿不到ids这个数据了
![63cdf343221a0a111490747715c007b](https://user-images.githubusercontent.com/45064164/231688842-0b1a8830-a034-4e2e-aa05-20ac618f6db9.png)
![1445d1f2e172940253cebc8f4c7433b](https://user-images.githubusercontent.com/45064164/231689057-43cb9c76-f55f-4a58-b375-ca488fd5c3c5.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

2.9.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by Icodezhan** [comment]
我看见最新代码有人修复这个了，那就等更新了

**Comment by 2betop** [comment]
最新代码不能复现此问题，能否补充一下 schema 说明？

**Comment by Icodezhan** [comment]
> 最新代码不能复现此问题，能否补充一下 schema 说明？

我看最新代码有人修改了，但是发行版2.9.0还有问题，等下次发版
