### ISSUE TITLE
报 "amis": "^2.9.0"中inputTag的bug

### ISSUE THREAD

**Issue by dlpanda** [baidu/amis#6601]
#### 描述问题：

文档中labelField和valueField不生效。意外发现当有value和label字段的时候，前面两个字段才会起作用

#### 截图或视频：

![image](https://user-images.githubusercontent.com/29889295/231704972-0cc72a0f-b764-4e6b-a5cd-9ac61a2c07aa.png)
![image](https://user-images.githubusercontent.com/29889295/231705053-2908c10f-8f3e-41c2-942c-d25af9f74a28.png)

#### 如何复现（请务必完整填写下面内容）：

```
{
  "type": "page",
  "body": {
    "type": "form",
    "body": [
      {
        "type": "input-tag",
        "name": "tag",
        "label": "标签",
        "placeholder": "请选择标签",
        "valueField": "testvalue",
        "labelField": "testlabel",
        "options": [
          {
            "testvalue": "A",
            "testlabel": "a"
          },
          {
            "value": "A",
            "label": "a",
            "testvalue": "B",
            "testlabel": "b"
          }
        ]
      }
    ]
  }
}
```

**Comment by 2betop** [comment]
等这个 pr 合了可以解决这个问题 https://github.com/baidu/amis/pull/6611
