### ISSUE TITLE
本地运行amis-editor-demo刷新页面后是空白页

### ISSUE THREAD

**Issue by fan0920** [baidu/amis#6610]
#### 实现场景：
本地运行amis-editor-demo，按照文档中的操作方法：npm i、npm start、npm run dev

#### 存在的问题：
结果刷新页面后是空白页，看了眼终端发现终端报了三个warn，手动install后还是重复报这三个warn，不清楚页面空白是否与这三个warn有关，如果有关的话要怎么解决呢？
![image](https://user-images.githubusercontent.com/43081888/231921900-ac77dfc0-294e-447e-8c47-88969e7b5e95.png)

**Comment by 2betop** [comment]
amis-editor 代码已开源，你可以直接在 amis 里面跑，然后通过 `http://127.0.0.1:8888/packages/amis-editor/` 访问
