### ISSUE TITLE
新版本2.9.0 打包 yarn build 报错 Erroneous area: 1: $zindex-spinner-overlay + 1

### ISSUE THREAD

**Issue by bulesky520** [baidu/amis#6627]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
新版本2.9.0 打包 yarn build 报错 Erroneous area: 1: $zindex-spinner-overlay + 1

#### 截图或视频：
(node:17664) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at D:\CompanySourceCode\v9-admin\node_modules\css-loader\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
    at fastLex (D:\CompanySourceCode\v9-admin\node_modules\cssnano-preset-default\node_modules\postcss-calc\dist\parser.js:1603:27)
    at Parser.parse (D:\CompanySourceCode\v9-admin\node_modules\cssnano-preset-default\node_modules\postcss-calc\dist\parser.js:1677:30)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.9.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by JimmyTsai75** [comment]
同问

**Comment by zmm1988** [comment]
也出现了同样的问题，2.8的版本正常2.9的打不了包
` ERROR  Error: CSS minification error: Lexical error on line 1: Unrecognized text.
               
  Erroneous area:
1: $zindex-spinner-overlay + 1
^..^. File: static/css/chunk-libs.50661ca3.css
Error: CSS minification error: Lexical error on line 1: Unrecognized text.
`

**Comment by JimmyTsai75** [comment]
我把版本改为2.6后，打包就没有问题了，2.9版本是有问题的

**Comment by QiuShuiDyp** [comment]
我这边涉及的amis版本如下：
```
    "amis": "3.0.0",
    "amis-core": "3.0.0",
    "amis-editor": "^5.3.0",
    "amis-editor-core": "^5.3.0",
    "amis-formula": "3.0.0",
```

**Comment by rumunanfeng** [comment]
3.0.0也有此问题
