### ISSUE TITLE
table、crud的itemAction不支持onEvent

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#6628]
#### 描述问题：

table、crud的 itemAction 不支持 onEvent

#### 截图或视频：

1. 你是如何使用 amis 的？
`sdk`、`npm`

2. amis 版本是什么？
2.9.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "service",
    "api": "/amis/api/mock2/sample?perPage=10",
    "body": [
      {
        "type": "table",
        "source": "$rows",
        "itemAction": {
          "type": "button",
          "onEvent": {
            "click": {
              "actions": [
                {
                  "actionType": "toast",
                  "args": {
                    "msg": "test"
                  }
                }
              ]
            }
          }
        },
        "columns": [
          {
            "name": "browser",
            "label": "Browser"
          },
          {
            "name": "version",
            "label": "Version"
          }
        ]
      }
    ]
  }
}
```

**Comment by hsm-lv** [comment]
也可以换个思路，去监听表格的rowClick事件，如下：
```
{
  "type": "page",
  "body": {
    "type": "service",
    "api": "/amis/api/mock2/sample?perPage=10",
    "body": [
      {
        "type": "table",
        "source": "$rows",
        "columns": [
          {
            "name": "browser",
            "label": "Browser"
          },
          {
            "name": "version",
            "label": "Version"
          }
        ],
        "onEvent": {
            "rowClick": {
              "actions": [
                {
                  "actionType": "toast",
                  "args": {
                    "msg": "test"
                  }
                }
              ]
            }
          }
      }
    ]
  }
}
```

**Comment by BeMxself** [comment]
> 也可以换个思路，去监听表格的rowClick事件，如下：
> 
> ```
> {
>   "type": "page",
>   "body": {
>     "type": "service",
>     "api": "/amis/api/mock2/sample?perPage=10",
>     "body": [
>       {
>         "type": "table",
>         "source": "$rows",
>         "columns": [
>           {
>             "name": "browser",
>             "label": "Browser"
>           },
>           {
>             "name": "version",
>             "label": "Version"
>           }
>         ],
>         "onEvent": {
>             "rowClick": {
>               "actions": [
>                 {
>                   "actionType": "toast",
>                   "args": {
>                     "msg": "test"
>                   }
>                 }
>               ]
>             }
>           }
>       }
>     ]
>   }
> }
> ```

这确实也是一个思路

**Comment by mjqjhn** [comment]
crud的 itemAction和rowClick都不生效如何解决

**Comment by hsm-lv** [comment]
> crud的 itemAction和rowClick都不生效如何解决

你那边是什么版本
