### ISSUE TITLE
列表页面选择的可展示的列名想存储在数据库里，对于crud里的列名有没有回调函数可以对接的啊？

### ISSUE THREAD

**Issue by rodchen-king** [baidu/amis#663]

**Comment by RickCole21** [comment]
那个应该是没，目前只存在浏览器缓存里

**Comment by rodchen-king** [comment]
> 那个应该是没，目前只存在浏览器缓存里

好，那只有监控storage的变化了。再问一下，对于crud查询条件想做成类似于列名这种可选的，有没有什么方案？

**Comment by RickCole21** [comment]
- 查询条件那里，表单项可以使用visibleOn实现可选、显隐等交互
- crud接口那里配置数据映射，根据条件获取不同的表单项值，并进行查询

你先看看文档折腾下，不明白的地方再提出来

**Comment by rodchen-king** [comment]
> * 查询条件那里，表单项可以使用visibleOn实现可选、显隐等交互
> * crud接口那里配置数据映射，根据条件获取不同的表单项值，并进行查询
> 
> 你先看看文档折腾下，不明白的地方再提出来

ok，那我折腾看看
