### ISSUE TITLE
组件请求URL请求超时

### ISSUE THREAD

**Issue by codeisallmylife** [baidu/amis#6637]
#### 描述问题：

在使用某个组件的时候，发现了组件请求了“​​https://us-central1-foyer-work.cloudfunctions.net/getConfigForTextSummarizerv2?&token=null”，这个地址请求超时导致页面不渲染

#### 截图或视频：

偶发性问题，暂时无法复现

#### 如何复现（请务必完整填写下面内容）：

偶发性问题，暂时无法复现

**Comment by yakrsa** [comment]
I have the same problem

**Comment by coco723** [comment]
结论是什么，为什么没看到问题，就被关掉了呢？
