### ISSUE TITLE
input-tree  设置高度

### ISSUE THREAD

**Issue by atliwen** [baidu/amis#6639]
#### 是否关联于某个问题吗：
input-tree  设置高度

#### 预期的解决方案：
可以设置 tree 树的高度，目前只能设宽。
期望可以设置高度。

需求是 左边是树 右边是表。 左边的树可以高度自适应铺满。

#### 其他可接受方案：
设置固定高度也行。目前直接设置CSS height 都不生效

#### 任何附加信息：
![image](https://user-images.githubusercontent.com/10055836/232693049-1e6a3aab-35ed-4c19-a750-5619d5ff1ca1.png)

**Comment by 2betop** [comment]
后续可配置 `heightAuto` 属性为 true，让高度自动撑开

**Comment by gexMichael** [comment]
配置 heightAuto 属性为 true
虽可撑高，但数据较多时，无法固定为固定屏幕高度，即使设定 className为 h-full 也无效，
在 antd.css 中，还有如下设定，修改也没有用
--Tree-max-height: 300px;

**Comment by 1776313143** [comment]
> 配置 heightAuto 属性为 true 虽可撑高，但数据较多时，无法固定为固定屏幕高度，即使设定 className为 h-full 也无效， 在 antd.css 中，还有如下设定，修改也没有用 --Tree-max-height: 300px;

你用的这些方式，其中一个改css文件在低版本时还有效果，后来更新后就无效了，其他方式一直无效果。
