### ISSUE TITLE
在使用vite作为开发和构建工具的项目中，amis-editor-core报错

### ISSUE THREAD

**Issue by skymoonya** [baidu/amis#6640]
#### 描述问题：

在使用`vite`作为开发和构建工具的项目中，`amis-editor-core`报错

#### 截图或视频：

<img width="955" alt="image" src="https://user-images.githubusercontent.com/13905873/232699901-be2f64e5-ff6c-44ab-a904-2f6febd4b85c.png">

#### 如何复现：

1. 你是如何使用 amis 的？
`npm`

2. amis-editor 版本是什么？
`5.2.5-beta.7`

**Comment by skymoonya** [comment]
`amis-editor-core`从`amis`中导入的`Schema`是ts类型，应该在构建产物中去掉这个导入

**Comment by findreamer** [comment]
> `amis-editor-core`从`amis`中导入的`Schema`是ts类型，应该在构建产物中去掉这个导入

我也是才接触到amis，遇到了这个问题，您是如何解决的？

**Comment by skymoonya** [comment]
> 

有三个解决方案：
1. 在所有引入ts类型的地方使用`import type`代替`import`(需要提pr)
2. tsconfig中设置`emitDecoratorMetadata`为`false`(需要提pr)
3. 在`node_modules/amis/esm/index.js`的最后一行新增`export const Schema = {};`，可以使用`patch-package`

我在提了issue后发现在他们已经使用了`import type`来导入`Schema `，所以就把issue关了，等下一个版本应该就解决了
