### ISSUE TITLE
CRUD组件在headerToolbar添加按钮发送请求，crud列表不会保持Loading转圈了以及没有了遮罩层

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#6654]
#### 描述问题：

CRUD组件在headerToolbar添加按钮发送请求，crud列表不会保持Loading转圈了以及没有了遮罩层，

#### 截图或视频：

![图片](https://user-images.githubusercontent.com/45064164/233238509-21afe622-560e-46f1-8ce6-2726ed00b956.png)
#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.9.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by Icodezhan** [comment]
@2betop 帮忙看一下

**Comment by hsm-lv** [comment]
嗯，是这样的设计的，因为事件动作的ajax是比较简单的发送请求，它不会与组件有任何关联
