### ISSUE TITLE
建议spinner的show支持变量和表达式

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#6656]
#### 描述问题：

现在spinner当做容器的话，show只能写死true或false，可是正常使用场景不应该一直是true啊，而是可以动态修改，例如数据加载完了就要把show设置成false了

#### 截图或视频：

![图片](https://user-images.githubusercontent.com/45064164/233245036-27f1ce45-46fa-4ac2-bd8b-90ad3109848c.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.9.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by EvanZheng11** [comment]
+1

**Comment by allenve** [comment]
可以通过 showOn 属性配置，补充了文档

**Comment by Icodezhan** [comment]
> 可以通过 showOn 属性配置，补充了文档

showOn是2.9.0已经有的属性了是吗？还是说要等2.10.0发版？

**Comment by allenve** [comment]
已经支持的
