### ISSUE TITLE
select使用defer延时加载与searchApi搜索时，当搜索的结果不在已加载的options时，选中显示了value内容不是label

### ISSUE THREAD

**Issue by lujian0571** [baidu/amis#6666]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
select使用defer延时加载与searchApi搜索时，当搜索的结果不在已加载的options时，选中显示了value内容不是label

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://user-images.githubusercontent.com/1778115/233527811-0a4217b8-7d3f-4a9b-8deb-5f9f67229305.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.9.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
      "label": "延时加载",
      "type": "select",
      "name": "a",
      "multiple": false,
      "selectMode": "tree",
      "searchable": true,
      "searchApi": "/amis/api/mock2/form/deferOptions?label=${term}",
      "searchResultMode": "group",
      "deferApi": "/amis/api/mock2/form/deferOptions?label=${label}&waitSeconds=2",
      "options": [
        {
          "label": "战士",
          "defer": true
        }
      ]
    }
```

5. 操作步骤
请简单描述一下复现的操作步骤...

搜索api返回的选项内容是
```
{
label: "lazy-option-3"
value: "lazy-3"
}
```
选中页面显示的是lazy-3， 期望显示的是lazy-option-3

**Comment by gaochaoGin** [comment]
这个问题在6.10版本又出现了
