### ISSUE TITLE
编辑页面form设置了initApi根据url参数去获取数据，页面中的select又是根据自己的api填充的，就会导致下拉的api填充时把已填写的数据覆盖掉

### ISSUE THREAD

**Issue by tlbgqq** [baidu/amis#667]
没有找到怎么设置form的initApi和select的api执行顺序，保证先执行select的api填充下拉选项，然后再执行form的initApi获取要编辑的业务数据

**Comment by 2betop** [comment]
应该是正好相反的，目前是固定先 form 的 initApi 然后才是  select 的 source, source 还是不要返回 value 字段吧这个case。你可以把已有值也发给 source，后端判断一下有 值了就不返回 value 了，或者返回 已有值

**Comment by tlbgqq** [comment]
> 应该是正好相反的，目前是固定先 form 的 initApi 然后才是 select 的 source, source 还是不要返回 value 字段吧这个case。你可以把已有值也发给 source，后端判断一下有 值了就不返回 value 了，或者返回 已有值

固定先 form 的 initApi？这个现在是没法设置执行顺序的？initFetchOn能否实现？表达式格式是什么样的？

**Comment by 2betop** [comment]
直接配置`initFetch: false`,但是这样只会导致form不初始化了。假如你的 select 绑定的字段名是 'a' ，那你试试配置 `initfetchOn: "${a}"` 同时 form 的 initApi 的地址是需要有 `?a=${a}` 。

**Comment by tlbgqq** [comment]
source 不返回 value 字段可行
