### ISSUE TITLE
amis从1.9升级到2.9，编辑功能报错。应该如何修改？是否依赖版本问题？

### ISSUE THREAD

**Issue by dlpanda** [baidu/amis#6675]
#### 实现场景：

    "amis": "^2.9.0",
    "amis-editor": "^5.2.5",
    "amis-editor-core": "^5.2.5-beta.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "veaury": "^2.3.12",
以上是当前依赖版本。本地运行正常。测试环境打包报错。
[error] [vite]: Rollup failed to resolve import "rc-util/es/hooks/useEvent" from "node_modules/rc-menu/node_modules/rc-overflow/es/hooks/useEffectState.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
[error] error during build:
Error: [vite]: Rollup failed to resolve import "rc-util/es/hooks/useEvent" from "node_modules/rc-menu/node_modules/rc-overflow/es/hooks/useEffectState.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
随后在vite.config.js添加了
![image](https://user-images.githubusercontent.com/29889295/233595941-43700724-b350-4fbe-a14d-c41b214f273b.png)

打包不报错了。但是编辑器白屏显示，控制台报错
TypeError: Failed to resolve module specifier "rc-menu". Relative references must start with either "/", "./", or "../".

#### 存在的问题：
打包报错。添加external后，打包amis编辑器无法使用，控制台报错

**Comment by csx-bill** [comment]
https://github.com/csx-bill/quick-admin 可以参考我这个

**Comment by dlpanda** [comment]
> https://github.com/csx-bill/quick-admin 可以参考我这个

换了同样是版本还是会报错。可能因为vue项目有关系？

**Comment by petway** [comment]
同样的问题，是否有解决呢？

**Comment by petway** [comment]
您好，您的邮件已收到，谢谢！

**Comment by petway** [comment]
您好，您的邮件已收到，谢谢！
