### ISSUE TITLE
video 组件加一个 ‘loop’ 属性，视频可以循环播放

### ISSUE THREAD

**Issue by scc-itcast** [baidu/amis#6677]
视频组件增加循环播放 ‘loop’ 属性
| loop               | `boolean` |           | 是否循环播放                                                              |
我看了 video 源码是引用 video-react 插件提供的播放器， video-react插件是具有 loop 属性的
项目中有需求用到这个，我没有权限Pull requests，请你们收到能尽快加一下，谢谢了

**Comment by hyzx86** [comment]
可以推送到自己的仓库分支，然后在这个仓库创建PR
