### ISSUE TITLE
模块导入问题

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#668]
之前项目没问题，后来重新安装了一边依赖，就开始报这个错误了
![image](https://user-images.githubusercontent.com/64950961/84115770-3078e380-aa61-11ea-9306-6e2d720cc3d3.png)

**Comment by 2betop** [comment]
ts 版本升级一下试试？我可能针对最新的 typescript 改过一些写法

**Comment by tanmengfei** [comment]
这个问题是一开始升级到1.0.12了，然后把node_moudles和package-lock.json删掉重新依赖，然后就出现了这个问题

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/84118432-936c7980-aa65-11ea-945e-8658428cb0e7.png)
升级到了最新的，还是不行。。。

**Comment by 2betop** [comment]
我也不明白了，你可以看看 node_modules/amis/lib/index.d.ts 文件是否存在？正常应该能找到这个文件里面的类型说明。

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/84119613-2fe34b80-aa67-11ea-9334-b65b3b0fa088.png)
一个声明文件都没有了。。。

**Comment by 2betop** [comment]
我去，那你先安装最新的  beta 版本吧？amis@1.0.13-beta.2

**Comment by tanmengfei** [comment]
好的。。

**Comment by tanmengfei** [comment]
声明文件有了，但是之前的报错还在，而且amis包也报错了
![image](https://user-images.githubusercontent.com/64950961/84121047-396db300-aa69-11ea-9521-4acbe74d70f9.png)

**Comment by 2betop** [comment]
这不科学, 难道你那边不支持  export * from 'xxx' ? https://github.com/baidu/amis/blob/master/src/index.tsx#L171

**Comment by 2betop** [comment]
确定用的是最新的 typescript 哈，我这边发版本的时候用最新的 tsc 是没有任何报错的

**Comment by tanmengfei** [comment]
ts版本是3.9.5，应该是最新版的吧，我前边楼发了截图啦

**Comment by 2betop** [comment]
不，你虽然截图了，但是不代表你的程序用的就是那个版本。比如 vscode 是需要额外设置的。

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/84123951-1fce6a80-aa6d-11ea-8154-b3dd52701f68.png)
是在package.json里边修改吗

**Comment by 2betop** [comment]
webpack 这边的设置我也不清楚，要不你先看看 vscode 里面是否有报错？

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/84125376-0a5a4000-aa6f-11ea-8d43-89d1b679aae8.png)
就是zheie这些语法问题报错
而且用这个版本的话1.0.13-beta.2有声明文件，但是amis包内会报一些错误
如果用1.0.11或者1.0.12的话，就没声明文件。。

**Comment by 2betop** [comment]
应该是缓存问题？你右键 `amis` 的 Go to Definition 试试，或者执行按 F1 执行 vscode 的   `Typescript: Restart Ts Server`

**Comment by 2betop** [comment]
![image](https://user-images.githubusercontent.com/2698393/84126703-d849dd80-aa70-11ea-80f2-7ab49b7faf17.png)

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/84127414-d59bb800-aa71-11ea-8534-1e0e7354cec4.png)
![image](https://user-images.githubusercontent.com/64950961/84127468-e51b0100-aa71-11ea-838c-7b664ef4ce94.png)
我这是个啥情况===

**Comment by 2betop** [comment]
用最新的 beta 版本呢，感觉你并没有升级

![image](https://user-images.githubusercontent.com/2698393/84127695-2d3a2380-aa72-11ea-9ba5-a12f45cf3de8.png)

**Comment by 2betop** [comment]
另外底部的 typescript 版本是可以切的 
![image](https://user-images.githubusercontent.com/2698393/84128479-3d9ece00-aa73-11ea-8609-eb650684f1e3.png)

**Comment by tanmengfei** [comment]
我的是这个，关键是我安装了3.9.5，但是没法切换到3.9.5的选项

![image](https://user-images.githubusercontent.com/64950961/84129236-49d75b00-aa74-11ea-9005-9fc298f63da1.png)

**Comment by tanmengfei** [comment]
安装了最新的beta版本，amis定义还是没找到，重启了ts服务，还是报错

**Comment by tanmengfei** [comment]
原来我这个地方的语言是tsreact，改成了ts，报错又变多了
![image](https://user-images.githubusercontent.com/64950961/84129577-bb170e00-aa74-11ea-948d-8e51fbf6992e.png)

**Comment by 2betop** [comment]
用了 jsx 语法，肯定得是  typescript react 而不是 ts。不能切换版本应该是你 vscode 版本问题。

**Comment by tanmengfei** [comment]
我终于理清了我这一连串的问题是咋导致的了。。我是升级1.0.12的时候提示我找不到amis的声明文件，然后我就自己新建了一个声明文件，export default amis，然后之前的写法就出问题了，我都忘记写了这么一个文件了==那现在的问题就是1.0.12版本的这个问题该咋解决呀，我试过npm install @types/amis不行
![image](https://user-images.githubusercontent.com/64950961/84224956-7771e200-ab10-11ea-8f50-27a2e67e5e52.png)

**Comment by tanmengfei** [comment]
这是执行的npm install @types/amis
![image](https://user-images.githubusercontent.com/64950961/84225708-717d0080-ab12-11ea-9cb6-a5b40319e5ff.png)

**Comment by 2betop** [comment]
先用测试版本吧，正式版本本周末会补一个

**Comment by tanmengfei** [comment]
好的

**Comment by 2betop** [comment]
1.0.13 已补上 ts 类型文件。
