### ISSUE TITLE
CRUD组件的查询区域占用空间过多，建议调整默认布局，并增加展开/收起功能

### ISSUE THREAD

**Issue by citynook** [baidu/amis#6682]
#### 是否关联于某个问题吗：
CRUD组件的查询区域占用空间过多，导致其它可显示的内容变少，具体请见图1。

#### 预期的解决方案：
1. 为查询字段增加隐藏属性，默认为false，表示不隐藏。
2. 调整布局，减少查询区域占用的调试，参见：图2
3. 收起隐藏查询字段的布局参见：图3
4. 展开隐藏查询字段的由局参见：图4
5. 隐藏字段的区域默认为收起状态，也可以增加一个属性自定义默认状态。

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
图1：
![image](https://user-images.githubusercontent.com/127393297/233764156-a4527d67-4954-4799-b8e8-272067396666.png)

图2：
![image](https://user-images.githubusercontent.com/127393297/233764335-fa5dbc8d-6f2e-4e53-814e-cd6305a94563.png)

图3：
![image](https://user-images.githubusercontent.com/127393297/233764400-f16552d5-830a-4cf8-a468-bf2e349358e0.png)

图4：
![image](https://user-images.githubusercontent.com/127393297/233764431-34513479-09c6-43b2-bb80-8eb05ea7949f.png)

**Comment by Icodezhan** [comment]
这个可以自己做呀，我就自己做了一个这个功能，现在文本框不是有控制显隐的字段吗？用个变量来控制就好了，然后这个变量随点击收起和展开按钮而改变
