### ISSUE TITLE
表格视图是否支持thead

### ISSUE THREAD

**Issue by haiaj** [baidu/amis#6687]
#### 实现场景：
vue项目用amis实现了一个业务流转报表，现需要支持打印功能，要在分页页面中加入表头

#### 存在的问题：
未找到表头相关的文档或组件，当前表格视图组件是否支持表头标签，如何使用

#### 当前方案：
加入thead

**Comment by 2betop** [comment]
表格视图当配置 title 属性时会以 thead 方式输出。

如果满足需求可以用 tpl 如 

```
{
  type: 'tpl',
  tpl: '<table><thead><tr><th>Title</th></tr></thead></table>'
}
```
