### ISSUE TITLE
如何监听手动调整列宽的事件或者获取到这个动作

### ISSUE THREAD

**Issue by fan0920** [baidu/amis#6688]
#### 实现场景：
我想要能够监听到手动调整列宽的事件或者获取到这个动作

#### 存在的问题：
![image](https://user-images.githubusercontent.com/43081888/233814649-d8c2e03a-de97-459f-94c9-bc646863f51a.png)

**Comment by hsm-lv** [comment]
目前只支持这些 https://aisuda.bce.baidu.com/amis/zh-CN/components/table#%E4%BA%8B%E4%BB%B6%E8%A1%A8，暂时不支持列宽调整的监听
