### ISSUE TITLE
action的dialog内容，是否可以通过接口获取？

### ISSUE THREAD

**Issue by Jiangshan00001** [baidu/amis#6690]
#### 是否关联于某个问题吗：
我有一个新增人员 的按钮，需要在多个页面实现。
内容都是一样的，就是一个新增人员的dialog。
现在是使用action 里的dialog实现，不过每个地方都是重复的新增人员的dialog的代码。

#### 预期的解决方案：
action中的dialog可以通过获取某个api的json数据获取，从而复用一个代码。

**Comment by BeMxself** [comment]
在里面写个service，然后用service的schemaApi就好了
