### ISSUE TITLE
amis编辑器，上传文件和图片，一直报跨域

### ISSUE THREAD

**Issue by jackHuang-123** [baidu/amis#6691]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by hyzx86** [comment]
检查服务端跨域设置

**Comment by wibetter** [comment]
如果是本地启动编辑器（amis-editor），可以在amis.config.js中的proxyTable只是用来图片上传接口代理：
<img width="1062" alt="image" src="https://github.com/baidu/amis/assets/11958920/8fe0b5d4-d910-4a56-b6fd-5adfd4391d9b">
备注：需要将‘api/upload’代理到自己的图片上传接口地址上。
