### ISSUE TITLE
保存查询页面的查询条件后，条件回显的问题

### ISSUE THREAD

**Issue by diabloyong** [baidu/amis#670]
![image](https://user-images.githubusercontent.com/12034479/84127152-73db4e00-aa71-11ea-8e2c-f5b69302c99d.png)
如上图，我将查询的条件保存到数据库，下车进入页面的时候，条件并不会显示我保存的条件

**Comment by 2betop** [comment]
你提交的数据和初始化返回的数据格式一致就行

**Comment by diabloyong** [comment]
> 你提交的数据和初始化返回的数据格式一致就行

比如第二个红条：

**Comment by diabloyong** [comment]
> 你提交的数据和初始化返回的数据格式一致就行
第二个红条保存的："where_dim_cond":"[{\"val\":\"ANDROID\",\"opt\":\"=\",\"dim_id\":\"2\"},{\"val\":\"oppo\",\"opt\":\"=\",\"dim_id\":7}]"

**Comment by diabloyong** [comment]
> 你提交的数据和初始化返回的数据格式一致就行

第一个红条的代码
{
"type": "combo",
"multiple": true,
"name": "events",
"label": "漏斗步骤",
"controls": [
	{
		"type": "select",
		"name": "event_id",
		"required": true,
		"placeholder": "请添加事件/功能步骤",
		"searchable": true,
		"source": "get:/option/event/list",
	}
]
},
保存的结果是：
"events":"[{"event_id":10466},{"event_id":10467}]"}
我查库后端代码返回是用PageNoSizeResult[xxxx] ,xxxx:应该是什么类型

**Comment by nwind** [comment]
可以通过在 form 上加  debug: true 查看数据，保证一致就行
