### ISSUE TITLE
打包就报错，本地启动没问题

### ISSUE THREAD

**Issue by fjutnetcxloong** [baidu/amis#6701]
#### 实现场景：
拉代码，然后安装依赖，然后npm run build,直接就报错

![image](https://user-images.githubusercontent.com/44466487/233953539-da0e523f-05bb-45b4-b1ca-ff71299267c0.png)

**Comment by nwind** [comment]
这个报错是因为 import 了那个 LionCellFile.css，目前不支持这种写法，可以自己加 rollup 插件
