### ISSUE TITLE
CRUD操作栏中的【编辑/查看】按钮配置新版事件【抽出式弹框】无法加载表单数据

### ISSUE THREAD

**Issue by citynook** [baidu/amis#6706]
#### 描述问题：
在CRUD组件中为操作栏中的【编辑】、【查看】按钮配置新版【添加事件】，动作为【打开弹框】，弹框方式为【抽出式弹框】，在预览时弹框中的字段值没有显示。

在【配置动作（旧版）】中配置抽出式弹框可以正常显示表单字段。

#### 截图或视频：
图1：配置好的CRUD组件，能够正常显示表格数据，【编辑】、【查看】按钮是新建组件时，默认生成的【配置动作(旧版)】中的对话框。
![image](https://user-images.githubusercontent.com/127393297/234151226-902424e0-16e0-43e8-874c-112e145163f8.png)

图2：在【配置动作(旧版)】中，将查看按钮的【弹出式】对话框中的json复制到【抽出式弹框】中，表单内容能够正常显示。
![image](https://user-images.githubusercontent.com/127393297/234149472-03e7817c-303c-4890-bc44-8b05f3e5ffe9.png)

图3/图4：在【新版添加事件】配置【抽屉】式弹框，弹框json是直接从旧版中弹框中直接复制过来的，图4中弹框无法正常显示字段内容。
![image](https://user-images.githubusercontent.com/127393297/234150071-c7430538-790b-4ed3-b514-e4cb20e621c1.png)

![image](https://user-images.githubusercontent.com/127393297/234150023-d7429de7-885e-4a52-be4d-4e65c41e2088.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
    "@fortawesome/fontawesome-free": "6.3.0",
    "@types/react": "18.0.24",
    "@types/react-dom": "18.0.8",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "sass": "^1.60.0",
    "vite-plugin-monaco-editor": "1.1.0",
    "copy-to-clipboard": "3.3.1",
    "amis": "2.9.0",
    "amis-editor": "5.2.5",
    "amis-editor-core": "5.2.5"

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
5.1. 新增CRUD组件，在新增对话框中配置拉取记录的 API，加载字段，同时选择生成【编辑】、【查看】按钮的复选框，确认。
5.2. 进入【查看】按钮的【配置动作(旧版)】，在【代码】面板中复制  json，取消退出配置框。
5.3. 为【查看】按钮新增新版【添加事件】，动作为【打开弹框】，类型为【抽屉】，然后配置弹框内容，将第2步复制的 json 粘贴到代码面板中，确认保存退出配置框。
5.4. 进入预览模式，点击【查看】按钮。

最后还有一个小问题，图1中的【事件面板】中，【添加事件】下方的工具栏只显示了一部分，加载的css如下：

  import 'amis/sdk/iconfont.css';
  import '@fortawesome/fontawesome-free/css/all.css';
  import '@fortawesome/fontawesome-free/css/v4-shims.css';
  **import '../../../../node_modules/amis-editor-core/lib/style.css';**
  import 'amis/lib/themes/cxd.css';

2个小问题：
a) 显示【配置动作(旧版)】按钮时，工具栏只显示一部分，不知道这是否是bug？或是缺少了哪个css？
b) 其中 amis-editor-core/lib/style.css 必须要使用相对路径才能找到，否则界面会报无法加载的错误。不知道这个是否是bug？

**Comment by hsm-lv** [comment]
新版已修复
