### ISSUE TITLE
tpl 支持source 属性

### ISSUE THREAD

**Issue by dikar** [baidu/amis#6713]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

我想实现tpl 从source属性获取数据 ，同时支持某些条件下这个tpl会重新拉取source数据再次渲染。

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by allenve** [comment]
可以通过给tpl包一层service解决，如下：
{
  type: 'service',
  api: 'xxx',
  body: {
    type: 'tpl',
    tpl: '${data}'
  }
}
