### ISSUE TITLE
全局引用样式，导致污染样式，怎么解决？目前项目里只是个别页面用amis

### ISSUE THREAD

**Issue by chenyan0023** [baidu/amis#6715]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by citynook** [comment]
@chenyan0023  我是这样使用的，没有全局引用css
项目是vite + vue3，在 main.ts 里引用
import 'amis/sdk/sdk.js';

编辑器vue引用如下：
  import 'amis/sdk/iconfont.css';
  import '@fortawesome/fontawesome-free/css/all.css';
  import '@fortawesome/fontawesome-free/css/v4-shims.css';
  import '../../../../node_modules/amis-editor-core/lib/style.css';
  import 'amis/lib/themes/cxd.css';

动态加载json渲染页面vue是页面里动态加载css，不会污染其它页面：
          const cssFile = '../../../../../node_modules/amis/lib/themes/' + theme + '.css';
          /* @vite-ignore */
          import(cssFile);

编辑器基本上能正常使用，但因为是vue里加载 react 控件，所以会不时发生错误，要F5刷新才能恢复正常。
动态页面渲染用的SDK，所以一切正常，暂时没发现有错误。

**Comment by Lizhooh** [comment]
微应用方案，用 react 包一个子应用吧

**Comment by 2betop** [comment]
用 sdk 方案可以解决，sdk 编译的时候会把大部分 css 加前缀
