### ISSUE TITLE
一般多久会发布新的版本？

### ISSUE THREAD

**Issue by Lizhooh** [baidu/amis#6719]
#### 实现场景：
如题，[2.9.0](https://www.npmjs.com/package/amis/v/2.9.0) 到现在快一个月了

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by citynook** [comment]
不知道百度是不是准备放弃这个项目了。这个项目真心不错，放弃了真就太可惜了~~

**Comment by allenve** [comment]
一般一个月会有一个小版本  这里有发布记录：https://www.npmjs.com/package/amis?activeTab=versions

**Comment by Icodezhan** [comment]
> 2.8.0 到 2.9.0 隔了一年

你在梦游？2.8.0到2.9.0明明是一个月

**Comment by Lizhooh** [comment]
> 2.8.0 到 2.9.0 隔了一年
看图 ...
![Uploading image.png…]()

**Comment by Lizhooh** [comment]
> 2.8.0 到 2.9.0 隔了一年

感觉是一个月发一次 

![image](https://user-images.githubusercontent.com/19299088/234537338-7e7e2348-5e1d-485c-9468-73b2a11942bd.png)

**Comment by Lizhooh** [comment]
主要用到了 amis-editor 有一些 bug， 我看已经修复了，但是还没发布版本 ...
