### ISSUE TITLE
amis的crud和button组件联动，导致页面刷新

### ISSUE THREAD

**Issue by happysmile12321** [baidu/amis#6720]
#### 描述问题：

上面是一个button,下面是一个tab,每个tab中有一个crud的组件，crud里有api请求。
点击了button之后会reload这个crud组件，会导致tab缓存的页码丢失。

**Comment by allenve** [comment]
『刷新』的事件动作有一个『resetPage』属性控制是否重置crud页码，详见：https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E5%88%B7%E6%96%B0

schema示例：
onEvent: {
        click: {
          actions: [
            {
              actionType: 'reload',
              componentId: 'crud-reload',
              args: {
                resetPage: false
              }
            }
          ]
        }
}
