### ISSUE TITLE
注入JS 到AMIS 中

### ISSUE THREAD

**Issue by d0uub** [baidu/amis#6721]
想在React 版本中注入 JS, 因为不想太多复杂逻辑在JSON中,有没有方法?
可否如下面例子:
```
{
  "type": "page",
  "body": [
    {
      "type": "script",
      "body": "alert('Hello, world!');"
    },
    {
      "type": "button",
      "label": "Click me",
      "onClick": "alert('Hello, world!');"
    }
  ]
}
```

**Comment by allenve** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-sdk

**Comment by d0uub** [comment]
只想在JSON 層面引入JS 作复杂逻辑,自定义组件要修改React ..
試過用事件中的自定义JS再加入以下JS 也不行
import { myFunction } from './myModule.js';
myFunction();
會說 Uncaught (in promise) SyntaxError: Cannot use import statement outside a module

**Comment by d0uub** [comment]
找到了,谢谢
```
            {
              "type": "custom",
              "onMount": "let s = document.createElement('script');s.src='CONFIG.js'; dom.appendChild(s);"
            },
```
