### ISSUE TITLE
请问怎么使用 json schema form?

### ISSUE THREAD

**Issue by mqeefqfn** [baidu/amis#673]
请问怎么使用json schema form? https://baidu.github.io/amis/form/json-schema 这个是例子的页面.
感觉你们这个sdk做的很好, 很方便.

**Comment by 2betop** [comment]
这个并没有完全实现，只识别了几个简单的。

**Comment by mqeefqfn** [comment]
好的, 谢谢. 后续有继续实现的计划吗?
