### ISSUE TITLE
表格内容文字过长的时间，文字省略号，使用hover显示全部内容

### ISSUE THREAD

**Issue by lengthy-daydream** [baidu/amis#6733]
#### 是否关联于某个问题吗：
文字太多了，全部展示很丑
![image](https://user-images.githubusercontent.com/58502519/234468230-5c75bbf6-fd87-42fd-a96b-17a048f68f49.png)

#### 预期的解决方案：
希望能像这样
![image](https://user-images.githubusercontent.com/58502519/234468780-9272e007-005b-46e4-901c-a425803e3b54.png)

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by shuracwf** [comment]
+1

**Comment by 2betop** [comment]
```
{
  "type": "page",
  "data": {
    "table": [
      {
        "id": 1,
        "text": "The longest word in any of the major English language dictionaries is pneumonoultramicroscopicsilicovolcanoconiosis, a word that refers to a lung disease contracted from the inhalation of very fine silica particles, specifically from a volcano; medically, it is the same as silicosis."
      },
      {
        "id": 2,
        "text": "The longest word in any of the major English language dictionaries is pneumonoultramicroscopicsilicovolcanoconiosis, a word that refers to a lung disease contracted from the inhalation of very fine silica particles, specifically from a volcano; medically, it is the same as silicosis."
      }
    ]
  },
  "body": [
    {
      "type": "crud",
      "source": "${table}",
      "columns": [
        {
          "name": "id",
          "label": "ID"
        },
        {
          "type": "tpl",
          "name": "text",
          "label": "long text",
          "className": "text-ellipsis",
          "tpl": "${text|truncate:100}",
          "popOver": {
            "trigger": "hover",
            "body": {
              "type": "tpl",
              "tpl": "${text}"
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by Ladtor** [comment]
借楼，请问 如果展示数据不是简单的文本类型，而是 mapping 节点等，应该如何处理？ @2betop

**Comment by fan0920** [comment]
> ```
> {
>   "type": "page",
>   "data": {
>     "table": [
>       {
>         "id": 1,
>         "text": "The longest word in any of the major English language dictionaries is pneumonoultramicroscopicsilicovolcanoconiosis, a word that refers to a lung disease contracted from the inhalation of very fine silica particles, specifically from a volcano; medically, it is the same as silicosis."
>       },
>       {
>         "id": 2,
>         "text": "The longest word in any of the major English language dictionaries is pneumonoultramicroscopicsilicovolcanoconiosis, a word that refers to a lung disease contracted from the inhalation of very fine silica particles, specifically from a volcano; medically, it is the same as silicosis."
>       }
>     ]
>   },
>   "body": [
>     {
>       "type": "crud",
>       "source": "${table}",
>       "columns": [
>         {
>           "name": "id",
>           "label": "ID"
>         },
>         {
>           "type": "tpl",
>           "name": "text",
>           "label": "long text",
>           "className": "text-ellipsis",
>           "tpl": "${text|truncate:100}",
>           "popOver": {
>             "trigger": "hover",
>             "body": {
>               "type": "tpl",
>               "tpl": "${text}"
>             }
>           }
>         }
>       ]
>     }
>   ]
> }
> ```

根据字数显示省略号有点太死了，可以根据列宽来自动显示省略号吗？

**Comment by shenmenga** [comment]
```json
{
  name: 'content',
  label: '模版内容',
  type: 'wrapper',
  size: 'none',
  body: {
      type: 'tooltip-wrapper',
      className: 'text-ellipsis',
      content: '${content}',
      style: {
          maxWidth: '200px',
      },
      body: '${content}',
  },
}
```
