### ISSUE TITLE
编辑器中右边的属性编辑面板应提供扩展接口

### ISSUE THREAD

**Issue by sunger** [baidu/amis#6737]
编辑器中，扩展点比较常见的是右侧的属性面板中属性的扩展：
比如：按钮这个控件，我需要添加一个新的属性auth，来作为权限标识，（虽然也可以自定义按钮控件插件能达到这样的效果，但是这个多余的按钮和现有的按钮仅仅是多了一个属性，没有任何其他区别）
![image](https://user-images.githubusercontent.com/630072/234497778-8671f1af-451c-4bcd-b16e-4c6fd69e7d24.png)

另外入：api的高级弹出对话框，可能也要加一个属性，接口是来自变量列表的选择，这些需求都只需要对现有的面板进行扩展
![image](https://user-images.githubusercontent.com/630072/234499702-893151e9-25a0-4510-aa15-50cb0b9742a6.png)

**Comment by 2betop** [comment]
可以外部通过复写这个改成你自己的api配置器

```
setSchemaTpl('apiControl', {
  type: 'Your Renderer'
}),
```

or 

```
setSchemaTpl('apiControl', {
   component: (props:any) => JSX.Element
}),
```

**Comment by ityue** [comment]
佬 请问怎么使用 自定义按钮控件插件 在做出个 权限按钮啊？ 十分感谢~！

**Comment by Yabsolute** [comment]
> 可以外部通过复写这个改成你自己的api配置器
> 
> ```
> setSchemaTpl('apiControl', {
>   type: 'Your Renderer'
> }),
> ```
> 
> or
> 
> ```
> setSchemaTpl('apiControl', {
>    component: (props:any) => JSX.Element
> }),
> ```

你好 经过使用发现`setSchemaTpl `方法有问题，设置之后部分修改过的设置器无法使用，比如setSchemaTpl('icon',{下拉框})，该问题会在部分设置器上出现，部分设置器上不会没有
