### ISSUE TITLE
【智能总管】一个使用 amis 开发的办公室系统，包含项目管理、行事历、行程管理、CRM等各式功能

### ISSUE THREAD

**Issue by gexMichael** [baidu/amis#6744]
一直以来都是 amis 的爱用者，因为本身是后端出身，前端只具备基础知识，所以初见 amis 时真是如获至宝。
不过因为 amis 的组件非常丰富，而且总不可能完美无缺，所以还是花了一点时间学习、试错。
为了快速开发，所以就整了一个 Wizard 方便快速产生 json，用这个 Wizard 写了一些功能，就顺便发布一个【智能总管】的网站，
这个网站目前暂不开源，但是基本功能免费使用，目前算是在公测期间。
功能还有很大的进步空间，但是希望能抛砖引玉，对还不是很孰悉 amis 的同学们，能在开发系统前，先能有一个初步的认识。
目前只提供繁体版，所有产生的 json 都是存在数据表中，所以可以在线修改后立刻发布，这也是我很喜欢的功能。
如果其他同学也有类似的作品，也欢迎共襄盛举，多多交流，让 amis 更加壮大。

测试站的网址如下(数据会不定期覆盖删除)
https://lowcode.gex.com.tw
公司代号: demo
账号: admin
密码: gex123

online Help 的网址:
https://blog.gex.com.tw

欢迎指教，并再次感谢 amis，他真的是最佳低代码前端框架
如果想要交流，可以发 email 给我
michael@gex.com.tw

**Comment by belongwqz** [comment]
不错

**Comment by dong-gy** [comment]
能不能切换简体中文？

**Comment by Lizhooh** [comment]
这广告打的 ...
