### ISSUE TITLE
Tabs组件添加hash后，切换地址栏参数跳转导致404

### ISSUE THREAD

**Issue by echome123** [baidu/amis#6745]
#### 描述问题：

使用tabs组件，并且配置了hash后，地址栏在切换时，会自动加上#号，并且在点击其他菜单时候，会一直携带，导致其他菜单点击后，路由没有命中规则，页面404错误
#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
SDK  最新版

2. 操作步骤
在app多页应用模式下，页面抽屉组件内的tabs设置activeKey默认值，并配置hash参数，切换tab地址栏会自动加上#hash，关闭抽屉之后，地址栏参数依然存在，其他页面菜单点击跳转时候就会无法打开，必须删掉导航栏的#hash才可以

**Comment by 2betop** [comment]
因为你们的路由用的就是 hash路由，所以跟 tabs 的 hash 功能冲突，所以不能同时使用。
