### ISSUE TITLE
事件无法刷新时间轴(Timeline)组件

### ISSUE THREAD

**Issue by coldest7z** [baidu/amis#6747]
我的时间轴数据是动态获取的，但是通过提交后的时间无法刷新到时间轴重新获取数据
吧时间轴嵌套在表单内，刷新表单也无法让时间轴重新获取数据并刷新

**Comment by coldest7z** [comment]
![企业微信截图_16826487005322](https://user-images.githubusercontent.com/45660758/235039405-a2702917-0ddb-4f38-a641-a414e7fbe73e.png)
![image](https://user-images.githubusercontent.com/45660758/235039454-67f6c5e1-abe2-4233-9bed-ffa3a82c8b35.png)
刷新目标组件都无法选取到时间轴

**Comment by hsm-lv** [comment]
时间轴还没有支持刷新动作，不过你可以通过更新时间轴source参数的方式实现数据的重新load，像下面这样

```
{
  "type": "page",
  "title": "timeline",
  "body": [
    {
      "type": "button",
      "label": "重新加载时间轴数据",
      "onEvent": {
        "click": {
          "actions": [
            {
              "componentId": "u:a9e273734d1f",
              "actionType": "setValue",
              "args": {
                "value": {
                  "flag": 2
                }
              }
            }
          ]
        }
      },
      "id": "u:953a992e8dc0",
      "level": "default",
      "size": "default",
      "editorState": "default"
    },
    {
      "type": "timeline",
      "source": {
        "method": "get",
        "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/timeline/timelineItems?flag=${flag}"
      },
      "id": "u:68c76f6af3f3"
    }
  ],
  "id": "u:a9e273734d1f",
  "data": {
    "flag": 1
  }
}
```
source绑定一个query参数，通过更新query变量的方式触发source重新请求

**Comment by coldest7z** [comment]
> 时间轴还没有支持刷新动作，不过你可以通过更新时间轴source参数的方式实现数据的重新load，像下面这样
> 
> ```
> {
>   "type": "page",
>   "title": "timeline",
>   "body": [
>     {
>       "type": "button",
>       "label": "重新加载时间轴数据",
>       "onEvent": {
>         "click": {
>           "actions": [
>             {
>               "componentId": "u:a9e273734d1f",
>               "actionType": "setValue",
>               "args": {
>                 "value": {
>                   "flag": 2
>                 }
>               }
>             }
>           ]
>         }
>       },
>       "id": "u:953a992e8dc0",
>       "level": "default",
>       "size": "default",
>       "editorState": "default"
>     },
>     {
>       "type": "timeline",
>       "source": {
>         "method": "get",
>         "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/timeline/timelineItems?flag=${flag}"
>       },
>       "id": "u:68c76f6af3f3"
>     }
>   ],
>   "id": "u:a9e273734d1f",
>   "data": {
>     "flag": 1
>   }
> }
> ```
> 
> source绑定一个query参数，通过更新query变量的方式触发source重新请求

确实触发了刷新请求，不过另外一个问题，我是在表单的提交事件里面设置的变量赋值，提交之后会把我的弹窗给关掉，我给表单设置了closeDialogOnSubmit为false也会触发弹窗关闭

**Comment by coldest7z** [comment]
> 时间轴还没有支持刷新动作，不过你可以通过更新时间轴source参数的方式实现数据的重新load，像下面这样
> 
> ```
> {
>   "type": "page",
>   "title": "timeline",
>   "body": [
>     {
>       "type": "button",
>       "label": "重新加载时间轴数据",
>       "onEvent": {
>         "click": {
>           "actions": [
>             {
>               "componentId": "u:a9e273734d1f",
>               "actionType": "setValue",
>               "args": {
>                 "value": {
>                   "flag": 2
>                 }
>               }
>             }
>           ]
>         }
>       },
>       "id": "u:953a992e8dc0",
>       "level": "default",
>       "size": "default",
>       "editorState": "default"
>     },
>     {
>       "type": "timeline",
>       "source": {
>         "method": "get",
>         "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/timeline/timelineItems?flag=${flag}"
>       },
>       "id": "u:68c76f6af3f3"
>     }
>   ],
>   "id": "u:a9e273734d1f",
>   "data": {
>     "flag": 1
>   }
> }
> ```
> 
> source绑定一个query参数，通过更新query变量的方式触发source重新请求

这个方式有另外一个问题是，他无法做到第二次第三次刷新，我尝试了变量赋值给一个随机数也不可以

**Comment by hsm-lv** [comment]
> 

是可以多次刷新的，只要query参数不同
