### ISSUE TITLE
Drawer - 点击“确认” 怎么跳转到指定的页面

### ISSUE THREAD

**Issue by diabloyong** [baidu/amis#675]
Drawer - 点击“确认” 怎么跳转到指定的页面

**Comment by 2betop** [comment]
自己配置确认按钮

**Comment by diabloyong** [comment]
可以给个案例吗？

**Comment by diabloyong** [comment]
> 自己配置确认按钮

可以给个案例吗？

**Comment by 2betop** [comment]
drawer 那层配置 actions: [{actionType: 'link', link: '/xxxx', label: '确认'}]
相关文档：

* https://baidu.github.io/amis/docs/renderers/Drawer
* https://baidu.github.io/amis/docs/renderers/Action#link

**Comment by diabloyong** [comment]
> drawer 那层配置 actions: [{type: 'button', actionType: 'link', link: '/xxxx', label: '确认'}]
> 相关文档：
> 
> * https://baidu.github.io/amis/docs/renderers/Drawer
> * https://baidu.github.io/amis/docs/renderers/Action#link

好的，谢谢

**Comment by diabloyong** [comment]
![image](https://user-images.githubusercontent.com/12034479/84234017-0b01dd80-ab26-11ea-9215-6f5fef018c12.png)
添加这个代码后，api，点击确认，然后没反应，

**Comment by RickCole21** [comment]
嗯，你应该是想提交表单后跳转

用`form`的`redirect`属性

**Comment by 2betop** [comment]
嗯，要有 form 的话就得设置  form 的 redirect 了，你之前又没说清楚

**Comment by diabloyong** [comment]
ok,谢谢
