### ISSUE TITLE
按钮二次确认后并没有触发点击事件

### ISSUE THREAD

**Issue by coldest7z** [baidu/amis#6757]
按钮在二次确认后并没有触发点击事件

**Comment by coldest7z** [comment]
![image](https://user-images.githubusercontent.com/45660758/235038912-da858c27-2a8b-4c57-b3ff-363d883a9943.png)
![image](https://user-images.githubusercontent.com/45660758/235038946-2f9232bf-b905-48bc-825e-6030fa869eb4.png)
点击确定按钮后没有触发事件

**Comment by coldest7z** [comment]
只有关闭二次确认后事件才能正常触发

**Comment by hsm-lv** [comment]
是的，目前是这样设计的，就是说，如果配置了二次确认，click关联的动作会在二次确认弹窗确认后执行。如果你想先执行请求、重新加载，再弹窗的话，需要关闭二次确认，并在重新加载动作后添加弹窗动作

**Comment by coldest7z** [comment]
> 是的，目前是这样设计的，就是说，如果配置了二次确认，click关联的动作会在二次确认弹窗确认后执行。如果你想先执行请求、重新加载，再弹窗的话，需要关闭二次确认，并在重新加载动作后添加弹窗动作

我的意思并不是这样，我的意思是在2.9.0中 开启了二次确认，并且在确认之后不会触发事件的执行，在不开二次确认的情况下就会正常执行，所有这个二次确认没有用

**Comment by coldest7z** [comment]
> 没有复现这个问题呢 😄，建议贴下你的代码

{
  "type": "button",
  "label": "删除",
  "perPageAvailable": [
    10
  ],
  "confirmText": "是否确定删除？",
  "disabledOn": "",
  "visibleOn": "this.userInfo.authorities.some(i => i.authority === 'clue:delete')",
  "id": "u:b6711588773f",
  "onEvent": {
    "click": {
      "weight": 0,
      "actions": [
        {
          "args": {
            "options": {
            },
            "api": {
              "url": "/clue/delete",
              "method": "post",
              "messages": {
              },
              "dataType": "form"
            }
          },
          "actionType": "ajax",
          "outputVar": "responseResult"
        },
        {
          "componentId": "u:04b129795781",
          "args": {
            "resetPage": false
          },
          "actionType": "reload",
          "data": null
        }
      ]
    }
  },
  "actionType": "",
  "api": "/clue/refund"
}
就是在CRUD的工具栏使用这个按钮

**Comment by coldest7z** [comment]
> 没有复现这个问题呢 😄，建议贴下你的代码

![94E747D1AF4AC57757BC34CCE365695A](https://user-images.githubusercontent.com/45660758/235180641-958c70f1-5bd0-4479-873d-1e52b3a4a382.jpg)
我放在外面就可以出发事件，放在CRUD里面就不能触发
