### ISSUE TITLE
Amis Editor 在英文语言下，部分内容还是显示中文

### ISSUE THREAD

**Issue by citynook** [baidu/amis#6758]
#### 描述问题：

将语言设置为英文 'en-US' 后，Amis Editor 还是有部分内容念旧显示为中文，下面截图只列出部分，可能还有其它不支持多语言的内容。

#### 截图或视频：

1. 左侧面板的图标提示，以及组件面板的标题。
![image](https://user-images.githubusercontent.com/127393297/235026621-4d5b135b-79dd-4391-a5eb-d54154a419f5.png)

2. CRUD组件的创建对话框
![image](https://user-images.githubusercontent.com/127393297/235027149-595477b4-c787-40af-906c-aa20014380cb.png)

3. 旧版配置弹框内容
![image](https://user-images.githubusercontent.com/127393297/235028552-2fadcca1-4c1f-451a-ad8b-db7991c787fd.png)

4. 新版动作配置弹框
![image](https://user-images.githubusercontent.com/127393297/235029457-330f1a92-6f56-4598-99f9-f7e3f0744565.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
    "amis": "2.9.0",
    "amis-editor": "5.2.5",
    "amis-editor-core": "5.2.5"

6. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

7. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by LeuisKen** [comment]
我看到了这个 pr，似乎是为了修复这个问题？https://github.com/baidu/amis/pull/7518

**Comment by LeuisKen** [comment]
@qkiroc @2betop 请问 editor 大概什么时候会下一次发版呢？
目前可以确定的是：`amis-editor-core` 这个包编译产出中的 `esn/index.js` 中有部分文本，是没有被 i18n 函数包裹的。因此导致了这个问题。
所以，在更新 vite 插件后，editor-core 重新编译一次再发版应该就可以解决了。

**当前编译产物**
![image](https://github.com/baidu/amis/assets/7701575/255c725f-3664-4a6f-9587-d6b82ca34f7c)

**手动修改为 i18n 函数包裹形式后恢复正常**
![image](https://github.com/baidu/amis/assets/7701575/bde5d2a7-15e5-4a6f-84be-f6c0f51820e1)

**Comment by LeuisKen** [comment]
对于 “组件” 的翻译，还有一个问题，`node_modules/amis-theme-editor/esm/locale/en-US.js` 这个文件会把 `Component` 的翻译覆盖成 `assembly`。

![image](https://github.com/baidu/amis/assets/7701575/00037bcb-da2d-422f-b9d4-237d17d8c00a)

这部分代码似乎没有开源，我可以自己手动盖一下，辛苦 double check 一下。
