### ISSUE TITLE
反馈弹框获取不到接口返回的数据

### ISSUE THREAD

**Issue by lengthy-daydream** [baidu/amis#6759]
#### 描述问题：

1、设置接口之后，返回没有问题，但是弹窗内部获取不到数据！
2、而且总是获取到id为41，但是我的接口并没有返回id！

#### 截图或视频：

![image](https://user-images.githubusercontent.com/58502519/235044001-2d0777fd-3d5a-46cc-9f04-df033fe133cf.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

<img width="433" alt="image" src="https://user-images.githubusercontent.com/58502519/235043736-c6f752a1-b996-43f4-9912-40deb740ef3c.png">

4. 粘贴有问题的完整 `amis schema` 代码：
```
   {
          "label": "新增联合项目",
          "type": "button",
          "level": "primary",
          "actionType": "ajax",
          "api": "get:/system/dept/user",
          "feedback": {
            "size": "xs",
            "title": "新增联合项目",
            "body": [
              {
                "type": "form",
                "title": "表单",
                "labelWidth": 150,
                "body": [
                  {
                    "type": "static-tpl",
                    "name": "deptName",
                    "tpl": "${id}-${deptName}",
                    "label": "企业名称",
                    "size": "full"
                  },
                  {
                    "label": "联合项目名称",
                    "type": "input-text",
                    "name": "projectName",
                    "id": "u:b3d36c063e7e",
                    "description": "",
                    "editorPath": "input.base.default",
                    "required": true
                  }
                ],
                "api": {
                  "url": "/investment/project/union",
                  "method": "post"
                }
              }
            ],
            "id": "u:e80bb23b392f",
            "type": "dialog",
            "showCloseButton": true,
            "closeOnEsc": false,
            "showErrorMsg": false,
            "showLoading": false
          },
          "id": "u:38f510419c20"
        },
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by hsm-lv** [comment]
没有复现你说的问题，按理说如果button的ajax请求没有返回id的话，弹窗表单内是拿不到id的，如果显示了id说明当前数据域下还有名字为id的变量，你可以尝试开启form的debug功能调试一下（{type: form, debug: true})

**Comment by lengthy-daydream** [comment]
我重新用官网的反馈弹窗重新写了个demo，还是不行啊
![image](https://user-images.githubusercontent.com/58502519/236096564-4f7c25f5-40dc-4b86-8291-781cfc477147.png)
![image](https://user-images.githubusercontent.com/58502519/236096648-296a33fc-a3b6-437c-b33b-c61a7fc43f80.png)

**Comment by lengthy-daydream** [comment]
配置代码
`{
  "type": "page",
  "body": {
    "type": "button",
    "label": "Feedback",
    "actionType": "ajax",
    "api": {
      "url":"/system/dept/user",
      "method":"get"
    },
    "feedback": {
      "title": "操作成功",
      "body": "deptName：${deptName} id:${id}已操作成功"
    },
    "id": "u:fcd4870f7eea"
  },
  "asideResizor": false,
  "style": {
    "boxShadow": " 0px 0px 0px 0px transparent"
  }
}`

**Comment by lengthy-daydream** [comment]
我重新使用debug复现了一遍：
第一张图片是我用来获取页面json的接口，是前端自己调用的
第二张图片的接口，是反馈弹窗调用的接口，但是接口调用了，没获取到数据
![6c82cf751072b41bd155e7d6e79e3ba1](https://user-images.githubusercontent.com/58502519/236125939-decddd5e-ea49-415a-bbb1-5aafea149c55.png)
![a85cdfaabc174694c847aca69cecad6a](https://user-images.githubusercontent.com/58502519/236125962-e69da7bf-af83-4b01-9294-812d32c01b31.png)
