### ISSUE TITLE
右上角消息提示窗从开始到消失的时间可以设置吗

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#676]

**Comment by RickCole21** [comment]
接口返回，msg同级返回msgTimeout

```
{
 status:0,
msg:'xxx',
msgTimeout:1000
}
```

**Comment by tanmengfei** [comment]
好的

**Comment by tanmengfei** [comment]
按照你说的设置了下，还是改变不了时间。。

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/84245811-3392d300-ab38-11ea-8340-c2e3a9fbe6ed.png)

**Comment by hotmaycold** [comment]
> 接口返回，msg同级返回msgTimeout
> 
> ```
> {
>   status:0,
>   msg:'xxx',
>   msgTimeout:1000
> }
> ```

大佬好像成功的回调没有msgTimeout，导致设置失效？
