### ISSUE TITLE
在线编辑器里设置inpu-table组件，无法触发事件

### ISSUE THREAD

**Issue by aklices** [baidu/amis#6760]
在amis在线编辑器里设置inpu-table组件，无法触发事件？？，如下就监听不到"add"事件
https://aisuda.github.io/amis-editor-demo/
```
 "onEvent": {
        "add": {
          "actions": [
            {
              "actionType": "toast",
              "args": {
                "msgType": "info",
                "msg": "派发点击事件"
              }
            }
          ]
        }
      }
```
但是在官方组件文档示例上就可以
。。。。。。。。

**Comment by hsm-lv** [comment]
你需要看下你的amis版本是多少，2.9.0应该还没支持

**Comment by aklices** [comment]
我就是在官方在线编辑器demo里试的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月28日(周五) 下午5:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [baidu/amis] 在线编辑器里设置inpu-table组件，无法触发事件 (Issue #6760)




 
你需要看下你的amis版本是多少，2.9.0应该还没支持
