### ISSUE TITLE
如何在表格里显示树结构表（TreeTable）？

### ISSUE THREAD

**Issue by Lizhooh** [baidu/amis#6761]
#### 实现场景：
如何在表格里显示树结构表（TreeTable），看了文档好像不支持，有计划支持吗？

类型 antd 的树显示，如图，每个节点能进行 curd。

![image](https://user-images.githubusercontent.com/19299088/235112785-066b8deb-c570-4879-8f9f-c1ed33ce7d5e.png)

**Comment by allenve** [comment]
支持，可以看下这里 https://aisuda.bce.baidu.com/amis/zh-CN/components/table?page=1#%E5%B5%8C%E5%A5%97

**Comment by allenve** [comment]
图标目前不能改
