### ISSUE TITLE
在CRUD的编辑辅助区，按钮打开二次确认后事件无法触发

### ISSUE THREAD

**Issue by coldest7z** [baidu/amis#6764]
![image](https://user-images.githubusercontent.com/45660758/235196188-321c4b7a-cf36-4a35-aa10-5f9e7cfcb84a.png)

在CRUD中的删除按钮在开启二次确认后无法触发事件，同样的按钮在放在操作列就没问题。

**Comment by hsm-lv** [comment]
https://github.com/baidu/amis/issues/6757
