### ISSUE TITLE
CRUD 的columns的URL 跳转，URL使用变量有问题。

### ISSUE THREAD

**Issue by diabloyong** [baidu/amis#677]
![image](https://user-images.githubusercontent.com/12034479/84238648-f9243880-ab2d-11ea-88f2-c6cc1fd8d382.png)
![image](https://user-images.githubusercontent.com/12034479/84238760-207b0580-ab2e-11ea-9bb1-4791dd5faf47.png)

**Comment by RickCole21** [comment]
https://baidu.github.io/amis/docs/renderers/Action#action

先检查下配置项是否正确，看起来你这个可能要用`"link":"${xxx}"`？

**Comment by RickCole21** [comment]
好像不影响，你的变量值是啥，可能要加个过滤器，参考：

https://baidu.github.io/amis/docs/renderers/Tpl#tpl

**Comment by diabloyong** [comment]
$analysis_page_url 就是已经再后台拼接好的URL

**Comment by diabloyong** [comment]
> 好像不影响，你的变量值是啥，可能要加个过滤器，参考：
> 
> https://baidu.github.io/amis/docs/renderers/Tpl#tpl

https://github.com/baidu/amis/issues/677#issuecomment-641808804

**Comment by diabloyong** [comment]
> 好像不影响，你的变量值是啥，可能要加个过滤器，参考：
> 
> https://baidu.github.io/amis/docs/renderers/Tpl#tpl

$analysis_page_url 就是已经再后台拼接好的URL

**Comment by 2betop** [comment]
意思是说，你需要 `${analysis_page_url|raw}`

**Comment by diabloyong** [comment]
是的，谢谢
