### ISSUE TITLE
JSON文件中的form表单。请求后端接口的时候，想根据返回值code字段来做一些判断，请问如何操作呢？

### ISSUE THREAD

**Issue by liiqii** [baidu/amis#6777]
目前有俩接口一个获取数据和一个保存接口，想根据接的返回值code字段进行跳转，如code==1 保存成功，code==0，跳转到登录页面如何配置一下。
只在当前文件如何操作呢？
{
    "type": "page",
    "title": "系统设置",
    "body": [
        {
            "type": "form",
            "title": "通用设置",
            "body": [
                {
                    "type": "tpl",
                    "tpl": "相关配置",
                    "inline": false
                },
                {
                    "type": "service",
                    "body": [],
                    "messages": {},
                    "schemaApi": {
                        "method": "post",
                        "url": "/setting/query",
                        "dataType": "form",
                        "data": {
                            "name": "domain"
                        }
                    },
                    "initFetch": true,
                    "api": ""
                },
                {
                    "type": "divider",
                    "className": "b-4x m-none"
                }
            ],
            "submitText": "保存",
            "affixFooter": false,
            "panelClassName": "Panel--primary",
            "api": {
                "method": "post",
                "url": "/setting/save",
                "dataType": "json",
                "data": {
                    "&": "$$",
                    "save_type": "general"
                }
            }
        }
    ],
    "aside": []
}

**Comment by hsm-lv** [comment]
可以参考一下这个例子 https://aisuda.bce.baidu.com/amis/examples/event/service

**Comment by liqi1010** [comment]
> 可以参考一下这个例子 https://aisuda.bce.baidu.com/amis/examples/event/service

我在data后面追加了截图里面的内容，但是没生效
"schemaApi": {
      "method": "post",
      "url": "/setting/query",
      "dataType": "form",
      "data": {
             "name": "domain"
      }
},
![image](https://user-images.githubusercontent.com/13864914/236407542-0fb41b0f-5a87-423b-970d-13b6243c738c.png)
