### ISSUE TITLE
Vue3+webpack5+veaury  集成最新amis-editor后控制台报错（renderer with name "bat-editor" has already exists, ）无法启动

### ISSUE THREAD

**Issue by WangHao1221** [baidu/amis#6786]
#### 实现场景：
在现有vue3+webpack5环境中，有需求针对某个模块进行拖拽生成echarts图表，所以了解到了amis，在项目集成amis-editor出现了问题

#### 存在的问题：
"amis": "^2.9.0",  "amis-editor": "^5.2.5-beta.7", "amis-editor-core": "^5.2.5-beta.7",  "react": "^18.2.0","react-dom": "^18.2.0",  "veaury": "^2.3.11-beta.0",  "vue": "^3.0.0",   将amis-editor和amis-editor-core 同步修改为 5.2.5也不生效，但是控制台警告会消失（ warning  in ./node_modules/amis-editor/esm/renderer/DataBindingControl.js

"export 'DSField' was not found in 'amis-editor-core'

 warning  in ./node_modules/amis-editor-core/esm/index.js

"export 'Schema' (imported as 'o') was not found in 'amis'

 warning  in ./node_modules/amis-editor/esm/renderer/style-control/ThemeCssCode.js

"export 'styleMap' was not found in 'amis-core'）
浏览器控制台报错如下：
Error: The renderer with name "bat-editor" has already exists, please try another name!
    at registerRenderer (factory.js:53:1)
    at registerFormItem (Item.js:868:1)
    at eval (Item.js:872:1)
    at Module.__decorate (tslib.es6.js:58:1)
    at eval (Editor.js:246:1)
    at eval (Editor.js:253:1)
    at Array.map (<anonymous>)
    at eval (Editor.js:237:1)
    at ./node_modules/amis/lib/renderers/Form/Editor.js (12.js:14082:1)
    at __webpack_require__ (app.js:857:31)
t

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
 <template>
   <section class="table-page">
     <amisEditor  className="is-fixed"
      :isMobile="isMobile"
      :preview="handlePreviewChange"
      theme="cxd"
      :value="schema"
      :onChange="onChange"
      :onSave="onSave"
      :actionOptions="actionOptions"></amisEditor>
  </section>
</template>

<script>
import { defineComponent } from "vue";
import 'amis-editor-core/lib/style.css';
import 'amis/lib/themes/cxd.css';
import { applyPureReactInVue } from 'veaury'
import { Editor } from 'amis-editor'

export default defineComponent({
  name: 'ChainLog',
  components: {
    amisEditor: applyPureReactInVue(Editor)
    },
    setup() {
       let isMobile = false;
      const actionOptions = {
          showOldEntry: false,
      }
      let schema = {
        type: 'page',
        title: 'Simple Form Page',
        body: [
          {
            type: 'form',
            body: [
              {
                type: 'input-text',
                name: 'a',
                label: 'Text'
              }
            ]
          }
        ]
      }
      const onChange = (v) => {
        console.log('onChange...',v);
      }

      const handlePreviewChange = (e) => {
        console.log(JSON.stringify(e));
      }
      const onSave = () => {
        console.log('save....')
      }
      return {
        isMobile,
        actionOptions,
        schema,
        handlePreviewChange,
        onChange,
        onSave
      };
    }
});
</script>

<style scoped>
.amis {
    width: 100%;
    height: 100% !important;
}
#editor {
    width: 100%;
    height: 100% !important;
}

.ae-Editor .ae-Editor-inner {
height: 100% !important;
}
</style>

```

**Comment by 2betop** [comment]
重复了 https://github.com/baidu/amis/issues/6787

**Comment by clyao** [comment]
> #### 实现场景：
> 在现有vue3+webpack5环境中，有需求针对某个模块进行拖拽生成echarts图表，所以了解到了amis，在项目集成amis-editor出现了问题
> 
> #### 存在的问题：
> "amis": "^2.9.0", "amis-editor": "^5.2.5-beta.7", "amis-editor-core": "^5.2.5-beta.7", "react": "^18.2.0","react-dom": "^18.2.0", "veaury": "^2.3.11-beta.0", "vue": "^3.0.0", 将amis-editor和amis-editor-core 同步修改为 5.2.5也不生效，但是控制台警告会消失（ warning in ./node_modules/amis-editor/esm/renderer/DataBindingControl.js
> 
> "export 'DSField' was not found in 'amis-editor-core'
> 
> warning in ./node_modules/amis-editor-core/esm/index.js
> 
> "export 'Schema' (imported as 'o') was not found in 'amis'
> 
> warning in ./node_modules/amis-editor/esm/renderer/style-control/ThemeCssCode.js
> 
> "export 'styleMap' was not found in 'amis-core'） 浏览器控制台报错如下： Error: The renderer with name "bat-editor" has already exists, please try another name! at registerRenderer (factory.js:53:1) at registerFormItem (Item.js:868:1) at eval (Item.js:872:1) at Module.__decorate (tslib.es6.js:58:1) at eval (Editor.js:246:1) at eval (Editor.js:253:1) at Array.map () at eval (Editor.js:237:1) at ./node_modules/amis/lib/renderers/Form/Editor.js (12.js:14082:1) at **webpack_require** (app.js:857:31) t
> 
> #### 当前方案：
> 请粘贴你当前方案的完整 amis schema 代码...
> 
> ```
>  <template>
>    <section class="table-page">
>      <amisEditor  className="is-fixed"
>       :isMobile="isMobile"
>       :preview="handlePreviewChange"
>       theme="cxd"
>       :value="schema"
>       :onChange="onChange"
>       :onSave="onSave"
>       :actionOptions="actionOptions"></amisEditor>
>   </section>
> </template>
> 
> <script>
> import { defineComponent } from "vue";
> import 'amis-editor-core/lib/style.css';
> import 'amis/lib/themes/cxd.css';
> import { applyPureReactInVue } from 'veaury'
> import { Editor } from 'amis-editor'
> 
> export default defineComponent({
>   name: 'ChainLog',
>   components: {
>     amisEditor: applyPureReactInVue(Editor)
>     },
>     setup() {
>        let isMobile = false;
>       const actionOptions = {
>           showOldEntry: false,
>       }
>       let schema = {
>         type: 'page',
>         title: 'Simple Form Page',
>         body: [
>           {
>             type: 'form',
>             body: [
>               {
>                 type: 'input-text',
>                 name: 'a',
>                 label: 'Text'
>               }
>             ]
>           }
>         ]
>       }
>       const onChange = (v) => {
>         console.log('onChange...',v);
>       }
> 
>       const handlePreviewChange = (e) => {
>         console.log(JSON.stringify(e));
>       }
>       const onSave = () => {
>         console.log('save....')
>       }
>       return {
>         isMobile,
>         actionOptions,
>         schema,
>         handlePreviewChange,
>         onChange,
>         onSave
>       };
>     }
> });
> </script>
> 
> <style scoped>
> .amis {
>     width: 100%;
>     height: 100% !important;
> }
> #editor {
>     width: 100%;
>     height: 100% !important;
> }
> 
> .ae-Editor .ae-Editor-inner {
> height: 100% !important;
> }
> </style>
> ```
大佬，你集成成功了吗？我目前也需要vue3集成，方便给一个demo参考一下吗
