### ISSUE TITLE
Vue3+webpack5+veaury 集成最新amis-editor后控制台报错（renderer with name "bat-editor" has already exists, ）无法启动

### ISSUE THREAD

**Issue by WangHao1221** [baidu/amis#6787]
#### 描述问题：

Vue3+webpack5+veaury 集成最新amis-editor后控制台报错（renderer with name "bat-editor" has already exists, ）无法启动

#### 截图或视频：

The renderer with name "bat-editor" has already exists, please try another name!
    at registerRenderer (factory.js:53:1)
    at registerFormItem (Item.js:868:1)
    at eval (Item.js:872:1)
    at Module.__decorate (tslib.es6.js:58:1)
    at eval (Editor.js:246:1)
    at eval (Editor.js:253:1)
    at Array.map (<anonymous>)
    at eval (Editor.js:237:1)
    at ./node_modules/amis/lib/renderers/Form/Editor.js (12.js:14082:1)
    at __webpack_require__ (app.js:857:31)
t

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
"amis": "^2.9.0", "amis-editor": "^5.2.5-beta.7", "amis-editor-core": "^5.2.5-beta.7", "react": "^18.2.0","react-dom": "^18.2.0", "veaury": "^2.3.11-beta.0", "vue": "^3.0.0", 将amis-editor和amis-editor-core 同步修改为 5.2.5也不生效，但是控制台警告会消失（ warning in ./node_modules/amis-editor/esm/renderer/DataBindingControl.js

"export 'DSField' was not found in 'amis-editor-core'

warning in ./node_modules/amis-editor-core/esm/index.js

"export 'Schema' (imported as 'o') was not found in 'amis'

warning in ./node_modules/amis-editor/esm/renderer/style-control/ThemeCssCode.js

"export 'styleMap' was not found in 'amis-core'）

3. 粘贴有问题的完整 `amis schema` 代码：
```
 <template>
   <section class="table-page">
     <amisEditor  className="is-fixed"
      :isMobile="isMobile"
      :preview="handlePreviewChange"
      theme="cxd"
      :value="schema"
      :onChange="onChange"
      :onSave="onSave"
      :actionOptions="actionOptions"></amisEditor>
  </section>
</template>

<script>
import { defineComponent } from "vue";
import 'amis-editor-core/lib/style.css';
import 'amis/lib/themes/cxd.css';
import { applyPureReactInVue } from 'veaury'
import { Editor } from 'amis-editor'

export default defineComponent({
  name: 'ChainLog',
  components: {
    amisEditor: applyPureReactInVue(Editor)
    },
    setup() {
       let isMobile = false;
      const actionOptions = {
          showOldEntry: false,
      }
      let schema = {
        type: 'page',
        title: 'Simple Form Page',
        body: [
          {
            type: 'form',
            body: [
              {
                type: 'input-text',
                name: 'a',
                label: 'Text'
              }
            ]
          }
        ]
      }
      const onChange = (v) => {
        console.log('onChange...',v);
      }

      const handlePreviewChange = (e) => {
        console.log(JSON.stringify(e));
      }
      const onSave = () => {
        console.log('save....')
      }
      return {
        isMobile,
        actionOptions,
        schema,
        handlePreviewChange,
        onChange,
        onSave
      };
    }
});
</script>

<style scoped>
.amis {
    width: 100%;
    height: 100% !important;
}
#editor {
    width: 100%;
    height: 100% !important;
}

.ae-Editor .ae-Editor-inner {
height: 100% !important;
}
</style>

```

4. 操作步骤
在现有vue3+webpack5项目中，执行npm i amis amis-editor amis-editor-core react react-dom veaury后，新建一个.vue文件配置好路由，文件配置代码如上，然后启动项目访问该路由，此时控制台报错如上，在vue.config加上config.merge({
            resolve: {
                conditionNames: ['require', 'node']
            }
        })后程序直接无法启动，降低amis相关版本也不行，求解在vue3+webpack5中解决方案

**Comment by Lizhooh** [comment]
你去问问 veaury 吧

**Comment by WangHao1221** [comment]
> 你去问问 veaury 吧，放个微前端，自己监听传 value 和 onchange

我在如流咨询了一下，坐着说让提一下issue，因为veaury 包裹娶她react组件是没问题的

**Comment by WangHao1221** [comment]
我重新搭建了一套Vue3+webpack5，"amis": "^2.9.0",  "amis-editor": "^5.2.5",  "amis-editor-core": "^5.2.5",，报错如下：
`Error: Object(...) is not a function
    at eval (helper.js:48:1)
    at ./node_modules/amis-editor/esm/renderer/event-control/helper.js (module-system.js:5641:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (BaseControl.js:1:1)
    at ./node_modules/amis-editor/esm/component/BaseControl.js (module-system.js:2137:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (common.js:1:1)
    at ./node_modules/amis-editor/esm/tpl/common.js (module-system.js:5845:1)
triggerError @ vue-router.esm-bundler.js:3295
eval @ vue-router.esm-bundler.js:3030
Promise.catch (async)
pushWithRedirect @ vue-router.esm-bundler.js:3027
push @ vue-router.esm-bundler.js:2962
handleMenuClick @ sidebar.jsx:30
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
emit$1 @ runtime-core.esm-bundler.js:711
eval @ runtime-core.esm-bundler.js:7371
onInternalClick @ MenuItem.js:128
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:354
helper.js:48 Uncaught (in promise) TypeError: Object(...) is not a function
    at eval (helper.js:48:1)
    at ./node_modules/amis-editor/esm/renderer/event-control/helper.js (module-system.js:5641:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (BaseControl.js:1:1)
    at ./node_modules/amis-editor/esm/component/BaseControl.js (module-system.js:2137:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (common.js:1:1)
    at ./node_modules/amis-editor/esm/tpl/common.js (module-system.js:5845:1)
e`

**Comment by Icodezhan** [comment]
不建议在vue中使用amis，我项目使用的是vue2（jeecg-boot那个项目），使用SDK集成amis基本不会有问题。然后编辑器的话我是单独使用react项目集成amis-editor，后端使用同一个，这样刚好可以将实际项目与编辑器分开，而且多个项目也依旧只使用一个编辑器即可，只需要调整一下编辑器对接的后端

**Comment by Icodezhan** [comment]
不建议在vue中直接使用npm方式引入amis，在vue项目中建议使用SDK方式引入，我项目使用的是vue2（jeecg-boot那个项目），使用SDK集成amis基本不会有问题。
然后编辑器的话我是单独使用react项目集成amis-editor，后端使用同一个，这样刚好可以将实际项目与编辑器分开，而且多个项目也依旧只使用一个编辑器即可，只需要调整一下编辑器对接的后端

**Comment by WangHao1221** [comment]
> 不建议在vue中直接使用npm方式引入amis，在vue项目中建议使用SDK方式引入，我项目使用的是vue2（jeecg-boot那个项目），使用SDK集成amis基本不会有问题。 然后编辑器的话我是单独使用react项目集成amis-editor，后端使用同一个，这样刚好可以将实际项目与编辑器分开，而且多个项目也依旧只使用一个编辑器即可，只需要调整一下编辑器对接的后端

意思是编辑器和preview是两个项目，在vue里面只做preview嘛？主要是我们的需求有点坑，就在当前项目里面集成编辑器并且可以回显，以前做的流程编排也是这样，一个项目越搞越大。Vue3中用SDK还是npm比较简单？

**Comment by Icodezhan** [comment]
> > 不建议在vue中直接使用npm方式引入amis，在vue项目中建议使用SDK方式引入，我项目使用的是vue2（jeecg-boot那个项目），使用SDK集成amis基本不会有问题。 然后编辑器的话我是单独使用react项目集成amis-editor，后端使用同一个，这样刚好可以将实际项目与编辑器分开，而且多个项目也依旧只使用一个编辑器即可，只需要调整一下编辑器对接的后端
> 
> 意思是编辑器和preview是两个项目，在vue里面只做preview嘛？主要是我们的需求有点坑，就在当前项目里面集成编辑器并且可以回显，以前做的流程编排也是这样，一个项目越搞越大。Vue3中用SDK还是npm比较简单？

编辑器实际上没必要集成到应用项目中，这样应用前端搞得越来越大，对于用户来说他们只关注页面，编辑器是我们开发人员用的，而且目前市面上的将react组件转vue的工具基本都有坑，所以建议用SDK方式集成到VUE项目中

**Comment by WangHao1221** [comment]
> > > 不建议在vue中直接使用npm方式引入amis，在vue项目中建议使用SDK方式引入，我项目使用的是vue2（jeecg-boot那个项目），使用SDK集成amis基本不会有问题。 然后编辑器的话我是单独使用react项目集成amis-editor，后端使用同一个，这样刚好可以将实际项目与编辑器分开，而且多个项目也依旧只使用一个编辑器即可，只需要调整一下编辑器对接的后端
> > 
> > 
> > 意思是编辑器和preview是两个项目，在vue里面只做preview嘛？主要是我们的需求有点坑，就在当前项目里面集成编辑器并且可以回显，以前做的流程编排也是这样，一个项目越搞越大。Vue3中用SDK还是npm比较简单？
> 
> 编辑器实际上没必要集成到应用项目中，这样应用前端搞得越来越大，对于用户来说他们只关注页面，编辑器是我们开发人员用的，而且目前市面上的将react组件转vue的工具基本都有坑，所以建议用SDK方式集成到VUE项目中

主要这个编辑器涉及的是客户想自己用，出发点就是不同客户群可以托拉拽自己要的页面样式，我先等等作者看能否解决，一边再试试SDK，因为有小伙伴用Vite+vue3集成是可以的

**Comment by 2betop** [comment]
bat-editor 不是官方渲染器，不过一般出现这个都是即加载了 esm 版本，又加载 cjs 版本导致的。去修改编译工具配置，只走 cjs 可以解决问题。

**Comment by WangHao1221** [comment]
> bat-editor 不是官方渲染器，不过一般出现这个都是即加载了 esm 版本，又加载 cjs 版本导致的。去修改编译工具配置，只走 cjs 可以解决问题。

这个是在哪里配置？我在vue.config配置了config.merge({
            resolve: {
                conditionNames: ['require', 'node']
            }
        })导致程序都无法启动，这是在现有vue3+webpack+js项目中集成的，没有修改其他配置，我就安装依赖，然后再Vue文件使用

**Comment by dsdzjgz** [comment]
提供一个临时解决方案：
找到**node_modules/amis-core/esm/factory.js**，隐藏约第53行代码:
`throw new Error("The renderer with name \"".concat(config.name, "\" has already exists, please try another name!"));`

**Comment by WangHao1221** [comment]
更新Mobx配套依赖后问题解决，可以运行起来

**Comment by JackZhangCNCC** [comment]
现在怎么样了，我们的需求也有点坑，跟你们差不多，也是在当前项目里面集成编辑器并且可以回显。最主要我们的主项目是Vue2，我无论使用npm还是sdk都会有各种依赖报错，集成不进去，我自己新建个vue项目无论哪种方式都是可以使用的，现在毫无头绪了

**Comment by WangHao1221** [comment]
你看我那个地址，现在更新了依赖，可以用，但是时不时报错，不稳定的感觉，毕竟底层是react
---- 回复的原邮件 ----
***@***.***>发送日期2024年04月25日 08:55 ***@***.***> ***@***.***>,
State ***@***.***>主题Re: [baidu/amis] Vue3+webpack5+veaury 集成最新amis-editor后控制台报错（renderer with name "bat-editor" has already exists, ）无法启动 (Issue #6787)
现在怎么样了，我们的需求也有点坑，跟你们差不多，也是在当前项目里面集成编辑器并且可以回显。最主要我们的主项目是Vue2，我无论使用npm还是sdk都会有各种依赖报错，集成不进去，我自己新建个vue项目无论哪种方式都是可以使用的，现在毫无头绪了

**Comment by JackZhangCNCC** [comment]
> 你看我那个地址，现在更新了依赖，可以用，但是时不时报错，不稳定的感觉，毕竟底层是react ---- 回复的原邮件 ---- @***.***>发送日期2024年04月25日 08:55 ***@***.***> ***@***.***>, 状态 ***@***.***>主题Re： [baidu/amis] Vue3+webpack5+veaury 集成最新amis-editor后控制台报错（renderer with name “bat-editor” has already exists， ）无法启动 （Issue#6787) 现在怎么样了，我们的需求也有点坑，跟你们差不多，也是在当前项目里面集成编辑器并且可以回显。最主要我们的主项目是Vue2，我无论使用npm还是sdk都会有各种依赖报错，集成不进去，我自己新建个vue项目无论哪种方式都是可以使用的，现在毫无头绪了 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您修改了打开/关闭状态。消息 ID：***@***.***>

大哥，哪个地址啊，我没看到链接啊啊

**Comment by WangHao1221** [comment]
Issue提的那个，你可以下载启动看看
---- 回复的原邮件 ----
***@***.***>发送日期2024年04月25日 18:19 ***@***.***> ***@***.***>,
State ***@***.***>主题Re: [baidu/amis] Vue3+webpack5+veaury 集成最新amis-editor后控制台报错（renderer with name "bat-editor" has already exists, ）无法启动 (Issue #6787)
你看我那个地址，现在更新了依赖，可以用，但是时不时报错，不稳定的感觉，毕竟底层是react ---- 回复的原邮件 ---- @.>发送日期2024年04月25日 08:55 @.> @.>, 状态 @.>主题Re： [baidu/amis] Vue3+webpack5+veaury 集成最新amis-editor后控制台报错（renderer with name “bat-editor” has already exists， ）无法启动 （Issue#6787) 现在怎么样了，我们的需求也有点坑，跟你们差不多，也是在当前项目里面集成编辑器并且可以回显。最主要我们的主项目是Vue2，我无论使用npm还是sdk都会有各种依赖报错，集成不进去，我自己新建个vue项目无论哪种方式都是可以使用的，现在毫无头绪了 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您修改了打开/关闭状态。消息 ***@***.***>
大哥，哪个地址啊，我没看到链接啊啊

**Comment by dzj0719** [comment]
你好，作者，我现在是vben框架下vue3项目，现在想要在网页的一个页面中展示amis-editor可编辑并且回显对应json内容，ai以及百度提供的vue3对接amis-editor都是使用veaury依赖，但是我这里使用一直报错，大概率是引入问题，请问你可以提供你当时的项目有关于amis-editor但是并不会影响到您业务隐私的部分代码吗，感谢

**Comment by wubin1989** [comment]
> 你好，作者，我现在是vben框架下vue3项目，现在想要在网页的一个页面中展示amis-editor可编辑并且回显对应json内容，ai以及百度提供的vue3对接amis-editor都是使用veaury依赖，但是我这里使用一直报错，大概率是引入问题，请问你可以提供你当时的项目有关于amis-editor但是并不会影响到您业务隐私的部分代码吗，感谢

@dsdzjgz 不要在vue项目里集成amis-editor。我们都有过实践，这条路走不通。amis官方肯定不会把话说死了，直接告诉你不行。但实际上就是会出很多问题。我们也是amis-editor集成到react项目，vue项目只集成amis sdk负责渲染amis页面。

**Comment by dzj0719** [comment]
> > 好，作者，我现在是vben框架下vue3项目，现在想要在网页的一个页面中展示amis-editor可编辑并且回显对应json内容，ai以及百度提供的vue3活动amis-editor都使用veaury依赖可以但是我这里使用你一直报错，大是引入问题，请你提供你当时的项目有关于amis-editor但是并不会影响到你业务隐私的部分代码吗，谢谢
> 
> [@dsdzjgz](https://github.com/dsdzjgz)不要在vue项目里集成amis-editor。我们都有过实践，这条路走不通。amis官方肯定不会把话说死了，直接告诉你不行。但实际上还是会出很多问题。我们也是amis-editor集成到react项目，vue项目只集成amis sdk负责渲染amis页面。如果非要在vue项目里打开amis编辑器，可以用iframe嵌入react项目里amis编辑器页面。很多人吐槽iframe，其实iframe是很常用的，效果也非常好。还可以引入qiankun微前端框架，vue做主应用，react应用做子应用，通过微前端的方式打开react子应用的amis编辑器。

好的，我会尝试使用iframe来将react引入到vue，如果我想使用sdk进行渲染的话，那用户交互方面有没有更好的建议，比如我在editor上创建了表单模板，在vue中使用sdk渲染时，如何得知用户最后提交的结果呢，官网上我查询到是有关amis插件的交互，关于sdk没有查询到想要的信息

**Comment by wubin1989** [comment]
> > > 好，作者，我现在是vben框架下vue3项目，现在想要在网页的一个页面中展示amis-editor可编辑并且回显对应json内容，ai以及百度提供的vue3活动amis-editor都使用veaury依赖可以但是我这里使用你一直报错，大是引入问题，请你提供你当时的项目有关于amis-editor但是并不会影响到你业务隐私的部分代码吗，谢谢
> > 
> > 
> > [@dsdzjgz](https://github.com/dsdzjgz)不要在vue项目里集成amis-editor。我们都有过实践，这条路走不通。amis官方肯定不会把话说死了，直接告诉你不行。但实际上还是会出很多问题。我们也是amis-editor集成到react项目，vue项目只集成amis sdk负责渲染amis页面。如果非要在vue项目里打开amis编辑器，可以用iframe嵌入react项目里amis编辑器页面。很多人吐槽iframe，其实iframe是很常用的，效果也非常好。还可以引入qiankun微前端框架，vue做主应用，react应用做子应用，通过微前端的方式打开react子应用的amis编辑器。
> 
> 好的，我会尝试使用iframe来将react引入到vue，如果我想使用sdk进行渲染的话，那用户交互方面有没有更好的建议，比如我在editor上创建了表单模板，在vue中使用sdk渲染时，如何得知用户最后提交的结果呢，官网上我查询到是有关amis插件的交互，关于sdk没有查询到想要的信息

@dzj0719 编辑器里的schema要通过后端接口存储到数据库里，让后端同事提供接口给前端做查询，前端调接口拿到后端返回的schema以后调用sdk的api做渲染即可。
