### ISSUE TITLE
执行publish-to-internal.sh编译报错

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#6788]
#### 描述问题：

拉代码，安装依赖后，执行publish-to-internal.sh编译报错

#### 截图或视频：

![图片](https://user-images.githubusercontent.com/45064164/236432338-c3532130-8c31-422d-a11a-a3619f6ea793.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.9.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by hsm-lv** [comment]
这个脚本无需使用，只对内部
