### ISSUE TITLE
按钮事件的复制功能怎么复制json格式的代码

### ISSUE THREAD

**Issue by zhongtaoW** [baidu/amis#6794]
#### 实现场景：
我想通过点击【模板复制】按钮，复制对应模板下的json代码，再到编辑页面，达到快速使用模板的目的。
#### 存在的问题：
当前的复制功能只能只能复制单一的值，如
![image](https://user-images.githubusercontent.com/105036431/236595319-aa73bf66-29a3-448b-ac6a-8c519fda5c9b.png)
想复制这种
![image](https://user-images.githubusercontent.com/105036431/236595480-2b2c1630-58c9-4dae-a5bd-16cd9b447f48.png)

#### 当前方案：
怎么复制json代码 或者有其他更好的方式解决呢？

```
code here...
```

**Comment by allenve** [comment]
可以通过过滤器 ${object | json} 实现
{
  "type": "button",
  "label": "按钮",
  "onEvent": {
    "click": {
      "actions": [
        {
          "args": {
            "copyFormat": "text/plain",
            "content": "${{a:1,b:2} | json}"
          },
          "actionType": "copy"
        }
      ]
    }
  }
}
