### ISSUE TITLE
表达式编辑里的 ARRAYMAP 函数没有？

### ISSUE THREAD

**Issue by Lizhooh** [baidu/amis#6795]
#### 描述问题：

在 crud 表格里用表达式，想实现判断状态为 0 时隐藏某个操作按钮，表达式里的 ARRAYMAP 函数没有？
或者说要另外配置什么参数吗？

表达式是：ARRAYMAP(成员, item => item.状态) === 0

#### 截图或视频：

![image](https://user-images.githubusercontent.com/19299088/236596848-1e1c7d86-8cd4-4bf8-a54f-12ab0c4d5a3b.png)

界面上选列表的状态，会自动生成 ARRAYMAP
![image](https://user-images.githubusercontent.com/19299088/236597516-9f5566dc-15de-49ca-bb64-d9125acef31d.png)

生成的表达式
![image](https://user-images.githubusercontent.com/19299088/236597751-0d57afca-9eb5-4bb4-bae8-e09f18bb7ba5.png)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.9.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
表达式改成 `ARRAYSOME(成员, item => item.状态)`

**Comment by 2betop** [comment]
完整的配置是 `"visibleOn": "${ !ARRAYSOME(成员, item => item.状态) }"`

**Comment by Lizhooh** [comment]
我知道了，这些函数要用 `${ ... }` 包起来才会生效，不然报错。
