### ISSUE TITLE
在使用input-tree这个组件的时候，选择多选模式，如何将父节点前的勾选框去掉

### ISSUE THREAD

**Issue by jijiyangguang** [baidu/amis#6798]
在sdk下，如何将父节点前面的勾选框去掉，只保留子节点的勾选框
![image](https://user-images.githubusercontent.com/58300832/236609696-a623de0c-7345-4b58-bfb3-fe525048aaaa.png)

**Comment by 2betop** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-tree#%E5%8F%AA%E5%85%81%E8%AE%B8%E9%80%89%E6%8B%A9%E5%8F%B6%E5%AD%90%E8%8A%82%E7%82%B9 有只选择叶子节点配置，点父级的试试相当于全选子节点

**Comment by jijiyangguang** [comment]
> https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-tree#%E5%8F%AA%E5%85%81%E8%AE%B8%E9%80%89%E6%8B%A9%E5%8F%B6%E5%AD%90%E8%8A%82%E7%82%B9 有只选择叶子节点配置，点父级的试试相当于全选子节点

我是想父节点不可选，然后子节点可以多选，onlyLeaf只能选单个的子节点啊

**Comment by 2betop** [comment]
onlyLeaf 不是指只能选单个子节点，是说只能选叶子节点，依然是可多选的。这个试试父级的点选其实对应子节点的全选功能。

提交的值也只会包含子节点的

**Comment by jijiyangguang** [comment]
> onlyLeaf 不是指只能选单个子节点，是说只能选叶子节点，依然是可多选的。这个时候父级的点选其实对应子节点的全选功能。你可以修改配置加上 `multiple: true` 看看效果
> 
> 提交的值也只会包含子节点的

我是希望父节点前面的勾选框可以去掉，就类似于图片中我圈出来的那几个勾选框
![image](https://user-images.githubusercontent.com/58300832/236613183-88445dca-bba6-459b-9df5-94be8ccc037d.png)

**Comment by 2betop** [comment]
不能去掉，目前点那个效果是其子节点的 全选/ 反选功能

**Comment by jijiyangguang** [comment]
> 不能去掉，目前点那个效果是其子节点的 全选/ 反选功能

好的，谢谢您，然后麻烦问下现有的其他组件可以支持这种父节点前无勾选框的或者说我怎么该一下可以达到这种效果么

**Comment by 2betop** [comment]
我觉得目前的设定是合理的啊，父级点选起到 全选、反选作用
