### ISSUE TITLE
v5.3.0 amis-editor 卡片配置子内容还是出现 unkown 无法配置

### ISSUE THREAD

**Issue by Lizhooh** [baidu/amis#6810]
#### 描述问题：

v5.3.0 amis-editor 卡片配置子内容还是出现 unkown 无法配置

#### 截图或视频：
拖拽一个“卡片列表”组件，进入成员配置。

![image](https://user-images.githubusercontent.com/19299088/236714943-44faca17-c7a4-46aa-ad72-313f2ce9a4b2.png)

创建一个组件变成这样，还是配置不了字段

![image](https://user-images.githubusercontent.com/19299088/236715432-d89ef0da-73bb-4b14-a433-f2aa01b028f0.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

v3.0.0 amis
v5.3.0 amis-editor

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
请提供 amis 配置，目前本地没有复现

**Comment by Lizhooh** [comment]
@2betop 
我知道什么问题了，之前只显式安装了 amis-editor。
现在发现 node_module 有个 amis-editor-core 是一个旧的版本，npm 上显式安装 "amis-editor-core": "5.3.0" 就没这个问题了
