### ISSUE TITLE
themeCss(自定义样式)在SDK里不生效

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#6811]
#### 描述问题：

在外观的自定义样式中修改了颜色，在编辑器里是生效的如下图，对应的页面源码也有生成了样式，但是在SDK中没有生成样式
![图片](https://user-images.githubusercontent.com/45064164/236716939-6f32a5b8-654b-4c6a-a3f9-cf9cac6a5d24.png)
![图片](https://user-images.githubusercontent.com/45064164/236716967-f70e300d-c3f2-49c1-9287-620a45153dfa.png)
![图片](https://user-images.githubusercontent.com/45064164/236716990-90e301ec-1e0d-48d2-a112-41cd829887cf.png)

#### 截图或视频：
在SDK中，样式无效
![图片](https://user-images.githubusercontent.com/45064164/236717168-0f64d86b-4ba7-4f9c-9bbf-a290855fd9ce.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.0.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by Icodezhan** [comment]
@qkiroc @wibetter @nwind @2betop 是不是编译时有些问题，有些依赖没整进去？

**Comment by 2betop** [comment]
> @qkiroc @wibetter @nwind @2betop 是不是编译时有些问题，有些依赖没整进去？

css 样式优先级问题，正在尝试解决

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/6934 已合入，下个版本可用
