### ISSUE TITLE
crud可以在列上加按钮吗

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#682]
![image](https://user-images.githubusercontent.com/64950961/84359600-6fdb3780-abfb-11ea-81d2-06977019ffdc.png)
如图，按钮类似于单条操作，点击展开dialog，展示当前列的一些信息

**Comment by 2betop** [comment]
你把它用按钮渲染不行吗？按钮的 label 也支持变量比如:

{type: 'button', level: 'link', label: '${xxxx}', actionType: 'dialog', dialog: {...}}

**Comment by CareyToboo** [comment]
应该是可以的，只是说，button 的 label 和 columns 的 label 会冲突。也就是说，列头和按钮的label是一样的。不过这个小问题，可以通过一个自定义渲染器解决。

**Comment by 2betop** [comment]
可以再加一层 container, 然后把按钮放在 container 里面。比如：

```
{type: 'container', label: '列的标题', body: [{按钮相关}]}
```

**Comment by nuan1989** [comment]
这个按钮内怎么获取当前行的id呢?
