### ISSUE TITLE
3.0amis和amis-editor同时使用页面报错 #6570

### ISSUE THREAD

**Issue by agileago** [baidu/amis#6820]
#### 描述问题：

#6570 这个pr 导致会提前调用 `render` 创建`global` store, 导致后续传入的 `options` 都不起效，页面报 `fetcher缺失`

#### 截图或视频：

https://github.com/baidu/amis/blob/5fe6cf5dfd3154d9d8de2039f3fce916d8b832a4/packages/amis-editor/src/renderer/APIAdaptorControl.tsx#LL264C1-L264C1

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
 3.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤

**Comment by wqx8821** [comment]
大佬大佬 这问题解决了吗,升级也遇见这种问题

**Comment by agileago** [comment]
> 大佬大佬 这问题解决了吗,升级也遇见这种问题

session随便设置一个值

**Comment by wqx8821** [comment]
方便具体说一下吗, 是在拦截器里加吗?

**Comment by agileago** [comment]
@wqx8821 https://baidu.github.io/amis/zh-CN/docs/start/getting-started#session

**Comment by 2betop** [comment]
最新 master 应该没这个问题了，env 改成 merge 模式了

**Comment by agileago** [comment]
@2betop 这周发版么

**Comment by agileago** [comment]
发个版吧，项目快要上线乐
