### ISSUE TITLE
Dialog里的Table/CRUD，如果affixHeader==true，则显示异常

### ISSUE THREAD

**Issue by vexos-io** [baidu/amis#6827]
会把header溢出dialog并顶到页面头部

**Comment by 2betop** [comment]
版本问题？我看最新的是可以的，或者能提供问题 schema 吗？

**Comment by vexos-io** [comment]
是最新的版本。哦，我这边不太方便提供schema，但我发现是【把crud放进dialog里的**tabs**】，且把窗口调小一点，就会出现上述问题

**Comment by vexos-io** [comment]
//伪shema如下：
```
{
   dialog: {
      body: {
          type: 'tabs'
          tabs: [{type: 'crud with affixHeader'}, {type: 'crud with affixHeader'}]
     }
  }
}
```

**Comment by 2betop** [comment]
不能复现

<img width="1526" alt="image" src="https://github.com/baidu/amis/assets/2698393/403d3aa4-a505-4b67-a391-9be12da63362">

<img width="1447" alt="image" src="https://github.com/baidu/amis/assets/2698393/5183afa5-f7ce-4bbc-bb6e-4b43204513b8">

**Comment by vexos-io** [comment]
先关了吧，我这边依然存在，我找找是不是我个人配置错误的原因
