### ISSUE TITLE
Dialog里input-table，如果设置确认模式，新增的时候，行都没法编辑

### ISSUE THREAD

**Issue by songyinhai2006** [baidu/amis#6828]
#### 描述问题：

Dialog里input-table，如果设置确认模式，新增的时候，行都没法编辑

#### 截图或视频：

![image](https://user-images.githubusercontent.com/52561802/236984405-fbace496-aaa3-44e9-bd8d-d457933be9a1.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
 
3.0

**Comment by 2betop** [comment]
能否提供问题配置，目前无法复现

**Comment by 2betop** [comment]
看起来像是配置了 disabled 属性

**Comment by songyinhai2006** [comment]
> 看起来像是配置了 disabled 属性

{
  "type": "page",
  "title": "Hello world",
  "body": [
    {
      "type": "tpl",
      "tpl": "初始页面",
      "wrapperComponent": "",
      "inline": false,
      "id": "u:f66cac02d655"
    },
    {
      "type": "service",
      "body": [
        {
          "type": "tpl",
          "tpl": "",
          "inline": false,
          "id": "u:3ae59d86d0c3"
        }
      ],
      "id": "u:3e4833e514af"
    },
    {
      "type": "crud",
      "syncLocation": false,
      "api": {
        "method": "get",
        "url": ""
      },
      "columns": [
        {
          "name": "id",
          "label": "ID",
          "type": "text",
          "id": "u:34efb3d08d8a"
        },
        {
          "name": "code",
          "label": "code",
          "type": "text",
          "id": "u:26245568879f"
        },
        {
          "type": "text",
          "name": "name",
          "label": "name",
          "id": "u:c6b220cb97e3"
        },
        {
          "type": "operation",
          "label": "操作",
          "buttons": [
            {
              "label": "编辑",
              "type": "button",
              "actionType": "dialog",
              "level": "link",
              "dialog": {
                "title": "编辑",
                "body": [
                  {
                    "type": "form",
                    "api": "xxx/update",
                    "body": [
                      {
                        "name": "picker",
                        "label": "列表选取",
                        "type": "picker",
                        "id": "u:395578e81725",
                        "options": [
                        ],
                        "modalClassName": "app-popover",
                        "modalMode": "dialog",
                        "multiple": false,
                        "pickerSchema": {
                          "mode": "table",
                          "id": "u:aa227d6ca0a2",
                          "columns": [
                            {
                              "type": "text",
                              "name": "id",
                              "label": "id",
                              "id": "u:3994c0218612"
                            },
                            {
                              "type": "text",
                              "name": "code",
                              "label": "code",
                              "id": "u:488bf19be0e2"
                            },
                            {
                              "type": "text",
                              "name": "productModel",
                              "label": "productModel",
                              "id": "u:8769b2e49958"
                            }
                          ],
                          "bulkActions": [
                          ]
                        },
                        "source": {
                          "method": "get",
                          "url": "http://127.0.0.1:8105/api/product?page=0&size=20&sort=update_time%2Cdesc"
                        },
                        "autoFill": {
                          "name": "${productModel}"
                        },
                        "valueField": "id",
                        "labelField": "name",
                        "embed": false
                      }
                    ],
                    "id": "u:27f55cf79cea"
                  },
                  {
                    "type": "input-table",
                    "name": "table",
                    "label": "表格表单",
                    "columns": [
                      {
                        "label": "名称",
                        "name": "code",
                        "quickEdit": {
                          "type": "input-text",
                          "name": "code",
                          "id": "u:edc8e324e5a7"
                        },
                        "id": "u:9e8a92ae1a99"
                      },
                      {
                        "label": "分数",
                        "name": "model",
                        "quickEdit": {
                          "type": "input-number",
                          "name": "model",
                          "id": "u:af40b05ba191"
                        },
                        "id": "u:642768e59d45"
                      },
                      {
                        "label": "等级",
                        "name": "level",
                        "quickEdit": {
                          "type": "picker",
                          "name": "level",
                          "id": "u:2393aa411240",
                          "pickerSchema": {
                            "mode": "table",
                            "id": "u:5b53d8645f7c",
                            "columns": [
                              {
                                "type": "text",
                                "name": "id",
                                "label": "id",
                                "id": "u:66e4e7d92fcd"
                              },
                              {
                                "type": "text",
                                "name": "code",
                                "label": "code",
                                "id": "u:d6dd708e0574"
                              },
                              {
                                "type": "text",
                                "name": "name",
                                "label": "name",
                                "id": "u:fb361c71f490"
                              },
                              {
                                "type": "text",
                                "label": "productModel",
                                "name": "productModel",
                                "id": "u:1eb6417bda6c"
                              }
                            ],
                            "bulkActions": [
                            ],
                            "listItem": {
                              "title": "${label}"
                            }
                          },
                          "source": {
                            "method": "get",
                            "url": "http://127.0.0.1:8105/api/product?page=0&size=20&sort=update_time%2Cdesc"
                          },
                          "valueField": "id",
                          "labelField": "name",
                          "modalMode": "dialog",
                          "multiple": false,
                          "autoFill": {
                            "model": "${productModel}"
                          }
                        },
                        "id": "u:d729611c7b22"
                      }
                    ],
                    "addable": true,
                    "footerAddBtn": {
                      "label": "新增",
                      "icon": "fa fa-plus",
                      "id": "u:90635fdbf850"
                    },
                    "strictMode": true,
                    "id": "u:240f552ead4d",
                    "minLength": 0,
                    "editable": false,
                    "needConfirm": true
                  }
                ],
                "type": "dialog",
                "id": "u:43bb2c5c5240",
                "showCloseButton": true,
                "closeOnEsc": false,
                "showErrorMsg": true,
                "showLoading": true,
                "size": "xl"
              },
              "id": "u:b057b346a62c"
            }
          ],
          "id": "u:7fc976357215"
        }
      ],
      "bulkActions": [
      ],
      "itemActions": [
      ],
      "features": [
        "update",
        "filter"
      ],
      "filterColumnCount": 3,
      "headerToolbar": [
        {
          "label": "新增",
          "type": "button",
          "actionType": "dialog",
          "level": "primary",
          "dialog": {
            "title": "新增",
            "body": [
              {
                "type": "input-table",
                "id": "u:db8b0c2c283c",
                "name": "table",
                "label": "表格表单",
                "columns": [
                  {
                    "label": "名称",
                    "name": "name",
                    "quickEdit": {
                      "type": "input-text",
                      "name": "name",
                      "id": "u:99646751afa5"
                    },
                    "id": "u:3e498be72a98"
                  },
                  {
                    "label": "分数",
                    "name": "score",
                    "quickEdit": {
                      "type": "input-number",
                      "name": "score",
                      "id": "u:3dc6ec827b08"
                    },
                    "id": "u:71ada5673967"
                  },
                  {
                    "label": "等级",
                    "name": "level",
                    "quickEdit": {
                      "type": "select",
                      "name": "level",
                      "id": "u:8eee9229dd85"
                    },
                    "id": "u:1f4c9eeae9b5"
                  }
                ],
                "addable": true,
                "footerAddBtn": {
                  "label": "新增",
                  "icon": "fa fa-plus",
                  "id": "u:342dccc3bc16"
                },
                "strictMode": true,
                "minLength": 0,
                "editable": true,
                "removable": true
              }
            ],
            "type": "dialog",
            "id": "u:683c40e441dd",
            "showCloseButton": true,
            "closeOnEsc": false,
            "showErrorMsg": true,
            "showLoading": true,
            "size": "xl"
          },
          "id": "u:ca82ee6892f3"
        },
        "bulkActions"
      ],
      "id": "u:23e7bf8de3fe",
      "perPageAvailable": [
        10
      ],
      "messages": {
      }
    }
  ],
  "id": "u:289bb9cc66d2"
}

**Comment by 2betop** [comment]
问题复现了，在弹窗中，且使用footerAddBtn 能复现这个问题。待 #7031 合入后发版可解决此问题
