### ISSUE TITLE
表单项两个一样的text, 设置默认值互相影响

### ISSUE THREAD

**Issue by minzhenyu** [baidu/amis#6842]
#### 描述问题：

表单项两个一样的text, 设置默认值互相影响

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/12856051/195b5055-4d2b-4d21-bc5f-8a91803d1cff)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新稳定版
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "form",
  "title": "表单",
  "body": [
    {
      "label": "文本框",
      "type": "input-text",
      "name": "text",
      "id": "u:8ef9c1f2f2c2",
      "value": "11112"
    },
    {
      "type": "input-text",
      "label": "文本框",
      "name": "text",
      "id": "u:89dfafcd041e",
      "value": "222"
    }
  ],
  "id": "u:1e7c5f15cf1b"
}
```

4. 操作步骤

在右侧面板修改默认值 导致其他text 显示的值夜变化

**Comment by Icodezhan** [comment]
没学过vue或react？数据绑定不知道？别用同一个name好吧

**Comment by 2betop** [comment]
不是问题，先关了

**Comment by minzhenyu** [comment]
> @Icodezhan 我学不学跟你有什么关系？

**Comment by minzhenyu** [comment]
@2betop 但是我设置默认值之后再修改name  依旧存在互相影响的问题，展示层面
![image](https://github.com/baidu/amis/assets/12856051/8b3883a2-833a-43f2-8398-f18e4e992ff4)

**Comment by Icodezhan** [comment]
> > @Icodezhan 我学不学跟你有什么关系？

数据绑定都不知道就不要在这里瞎提pr，会让人觉得你很蠢

**Comment by minzhenyu** [comment]
> > > @Icodezhan 我学不学跟你有什么关系？
> 
> 数据绑定都不知道就不要在这里瞎提pr，会让人觉得你很蠢

不懂就问就是蠢的话，那我觉得你很聪明，到gihub上看别人的成果，说着一些不知所云的东西

**Comment by Icodezhan** [comment]
> @2betop 但是我设置默认值之后再修改name  依旧存在互相影响的问题，展示层面
> ![image](https://github.com/baidu/amis/assets/12856051/8b3883a2-833a-43f2-8398-f18e4e992ff4)
> 
> 

你自己慢慢玩吧，要是有这个bug，大家项目早废了，别乱@大佬，人家很忙

**Comment by minzhenyu** [comment]
> 认值之后再修改name 依旧存在互相影响的问题，展示层面

你这么说只要提出问题就是蠢，你是非常聪明的，别人开源就是找问题的，你别绑架别人----键盘侠

**Comment by Icodezhan** [comment]
> > 认值之后再修改name 依旧存在互相影响的问题，展示层面
> 
> 你这么说只要提出问题就是蠢，你是非常聪明的，别人开源就是找问题的，你别绑架别人----键盘侠

别人要的是修复问题，你一个数据绑定不知道的来提pr，不是添乱？

**Comment by minzhenyu** [comment]
> > > 认值之后再修改name 依旧存在互相影响的问题，展示层面
> > 
> > 
> > 你这么说只要提出问题就是蠢，你是非常聪明的，别人开源就是找问题的，你别绑架别人----键盘侠
> 
> 别人要的是修复问题，你一个数据绑定不知道的来提pr，不是添乱？

那你解决？后面name改了怎么还影响

**Comment by Icodezhan** [comment]
> > > > 认值之后再修改name 依旧存在互相影响的问题，展示层面
> > > 
> > > 
> > > 你这么说只要提出问题就是蠢，你是非常聪明的，别人开源就是找问题的，你别绑架别人----键盘侠
> > 
> > 别人要的是修复问题，你一个数据绑定不知道的来提pr，不是添乱？
> 
> 那你解决？后面name改了怎么还影响，能解决你怎么说都行，虽然不是什么大问题

问题是大家都没你这个问题hhhh，复现不出来，要是有这个问题，大家项目早崩了好吗？麻烦你刷新一下页面或者检查一下json源码看看，而不是在这里瞎添乱

**Comment by minzhenyu** [comment]
> > > > > 认值之后再修改name 依旧存在互相影响的问题，展示层面
> > > > 
> > > > 
> > > > 你这么说只要提出问题就是蠢，你是非常聪明的，别人开源就是找问题的，你别绑架别人----键盘侠
> > > 
> > > 
> > > 别人要的是修复问题，你一个数据绑定不知道的来提pr，不是添乱？
> > 
> > 
> > 那你解决？后面name改了怎么还影响，能解决你怎么说都行，虽然不是什么大问题
> 
> 问题是大家都没你这个问题hhhh，复现不出来，要是有这个问题，大家项目早崩了好吗？麻烦你刷新一下页面或者检查一下json源码看看，而不是在这里瞎添乱

https://aisuda.github.io/amis-editor-demo/#/edit/1
表单组件创建两相同input 先改默认值,然后再改name

**Comment by minzhenyu** [comment]
> 

还有，我只是提出我看到的问题，大佬很快解决我很感谢，你这种没营养的东西麻烦不要发
