### ISSUE TITLE
autoFill需要能设置默认值时也可以自动填充

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#6849]
#### 是否关联于某个问题吗：
在一个form表单里，select控件我需要在设置默认值的情况下，自动填充选项的label值到form.data里面，比如如下代码：
```
  {
  "type": "select",
  "label": "autoFill触发器",
  "name": "type",
  "autoFill": {
    "typeName": "${label}"
  },
  "value": "a",
  "options": [
    {
      "label": "Option A",
      "value": "a"
    },
    {
      "label": "Option B",
      "value": "b"
    }
  ]
}
```
但是实际效果为：
![image](https://github.com/baidu/amis/assets/37805363/3efe36ff-7e49-41d8-a0d2-f600652dacff)

#### 预期的解决方案：
目前autoFill应该是只有主动改变value的时候才会触发，autoFill需要能支持设置了默认值也能根据默认值自动填充

#### 其他可接受方案：
增加配置属性支持也可以

**Comment by allenve** [comment]
应该默认就支持，用最新版试试

**Comment by rumunanfeng** [comment]
> {
>   "type": "select",
>   "label": "autoFill触发器",
>   "name": "type",
>   "autoFill": {
>     "typeName": "${label}"
>   },
>   "value": "a",
>   "options": [
>     {
>       "label": "Option A",
>       "value": "a"
>     },
>     {
>       "label": "Option B",
>       "value": "b"
>     }
>   ]
> }

不行噢，之前使用的2.9.0，我更新到3.0.0也不行

**Comment by rumunanfeng** [comment]
> 应该默认就支持，用最新版试试

不行噢，之前使用的2.9.0，我更新到3.0.0也不行

**Comment by rumunanfeng** [comment]
> 把options改为source试试，比如： `{ "type": "page", "title": "Hello world", "body": [ { "type": "form", "title": "表单", "body": [ { "type": "select", "label": "autoFill触发器", "name": "type", "value": "a", "id": "u:b1d6fbe7c6e0", "autoFill": { "typeName": "${label}" }, "source": "${options}" } ], "id": "u:7c44e4ba1b10", "debug": true } ], "id": "u:9993ea189495", "data": { "options": [ { "label": "Option A", "value": "a" }, { "label": "Option B", "value": "b" } ] } }`

尝试了一下这种方式确实是可以，但是目前我这边都是把选项数据放到select节点的options进行管理的，能否支持下这种情况？

**Comment by rumunanfeng** [comment]
> 可以支持，不过也可以先这样解决 `{ "type": "page", "body": { "type": "form", "debug": true, "api": "/amis/api/mock2/form/saveForm", "data": { "type1": "a" }, "body": [ { "type": "select", "label": "autoFill触发器", "name": "type1", "autoFill": { "typeName": "${label}" }, "source": "${[{'label': 'Option A','value': 'a'},{'label': 'Option B','value': 'b'}]}" } ] } }`

好的，希望后续版本尽快支持下，感谢♥
