### ISSUE TITLE
当crud返回的数据量少于分页配置的数量，配置的autoFillHeight: true的功能会失效

### ISSUE THREAD

**Issue by Flyingliao** [baidu/amis#6850]
#### 描述问题：

crud 配置了分页（每页90）、autoFillHeight: true。
当返回的数据条数大于 90， autoFillHeight: true的功能生效。
当返回的数据条数小于 90， autoFillHeight: true的功能失效。
#### 截图或视频：

正常情况下
![image](https://github.com/baidu/amis/assets/41402189/5ed8f036-5fea-4aad-bcdd-869ec0ff799e)

异常情况下
![image](https://github.com/baidu/amis/assets/41402189/9062ca0f-5898-441f-826c-64fd3d473aa1)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
    amis: 2.9.0. / 3.0.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "crud",
    "api": {
      "method": "get",
      "url": "/amis/api/mock2/sample"
    },
    "defaultParams": {
      "perPage":180
    },
    "footerToolbar": [
      "statistics",
      "pagination"
    ],
    "autoFillHeight": true,
    "syncLocation": false,
    "columns": [
      {
        "name": "id",
        "label": "ID"
      },
      {
        "name": "engine",
        "label": "Rendering engine"
      },
      {
        "name": "browser",
        "label": "Browser"
      }
    ]
  }
}
```

4. 操作步骤
把上面代码贴到amis官网中就能实现

5.原因排查结果
这个 updateAutoFillHeight 函数中有问题，pc端是坏的，同事测试的手机端是正常的。

异常时 antd-Table-footToolbar元素div在 pc端中不会显示出来，导致 updateAutoFillHeight 函数中炸了。
![image](https://github.com/baidu/amis/assets/41402189/8f069fa1-37db-4f07-9c3b-41fe6124319d)

**Comment by hsm-lv** [comment]
merged to https://github.com/baidu/amis/issues/7606
