### ISSUE TITLE
设置默认值之后再修改name  依旧存在互相影响的问题，展示层面，这个爱速搭demo 上我也验证过了

### ISSUE THREAD

**Issue by minzhenyu** [baidu/amis#6853]
@2betop 但是我设置默认值之后再修改name  依旧存在互相影响的问题，展示层面，这个爱速搭demo 上我也验证过了
![image](https://github.com/baidu/amis/assets/12856051/8b3883a2-833a-43f2-8398-f18e4e992ff4)

_Originally posted by @minzhenyu in https://github.com/baidu/amis/issues/6842#issuecomment-1543433113_

**Comment by 2betop** [comment]
name 修改了，之后修改默认值就不会作用在同一个变量上了，应该是符合预期的。
