### ISSUE TITLE
crud在某一列上配置了visibleOn，导致该列右侧内容向左移动

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#686]
![image](https://user-images.githubusercontent.com/64950961/84478322-ad0afc80-acc3-11ea-8a39-fed4243d24cf.png)
![image](https://user-images.githubusercontent.com/64950961/84478433-e17eb880-acc3-11ea-8c68-db31399657ab.png)

**Comment by 2betop** [comment]
列上没有 visibleOn 你可以再包一层。

{
type: 'container',
label: '预期对比',
body: [{/*你原来列上的配置*/}]
}

**Comment by tanmengfei** [comment]
好的

**Comment by tanmengfei** [comment]
加上了以后我的popOver不见了。。
![image](https://user-images.githubusercontent.com/64950961/84479411-7d5cf400-acc5-11ea-81b6-11caffd9cb1f.png)
![image](https://user-images.githubusercontent.com/64950961/84479455-8f3e9700-acc5-11ea-9339-53e79ef7575a.png)

**Comment by 2betop** [comment]
PopOver 只能配置在列上，popOverEnabledOn 可以用表达式配置要不要显示

**Comment by tanmengfei** [comment]
好的，谢啦

**Comment by buptyyf** [comment]
> 列上没有 visibleOn 你可以再包一层。
> 
> ```
> {
>   type: 'container',
>   label: '预期对比',
>   body: [{/*你原来列上的配置*/}]
> }
> ```

这个在1.1.7版本支持吗，我这边加上container后，数据不展示了
