### ISSUE TITLE
动态设置 name

### ISSUE THREAD

**Issue by 17671881483** [baidu/amis#6862]
#### 描述问题：

动态表单需求
有一个表单，我不知道他的具体「数量」和「name」，这一块由接口提供，我这边实现的原理是 each 动态渲染 formItem，可是name 这一块不能支持「表达式」，所有没事自定义 form 数据结构 这一块有什么办法解决吗

#### jsonSchema

{
  "type": "each",
  "id": "u:3bf4717648f4",
  "name": "switchExtArr",
  "items": {
    "type": "container",
    "body": [
      {
        "type": "tpl",
        "id": "u:743de371fcec",
        "tpl": "<div style=\"background-color: rgba(240, 248, 255, 1); margin-bottom:12px;margin-top: 12px;border-radius: 4px 4px 0 0; padding: 6px 0 6px 12px;\"><span style=\"width: 4px; background-color: rgb(76, 132, 255); dispaly: inline-block; border-radius: 2px;\">&nbsp;</span>&nbsp; <strong><%= data.label %></strong></div>",
        "inline": true
      },
      {
        "type": "each",
        "name": "config",
        "items": {
          "type": "switch",
          "label": "${label}：",
          "value": "${show}",
          "className": "m-b m-l",
          "itemId": "${key}"
        }
      }
    ]
  },
  "placeholder": "暂无内容"
}

**Comment by 2betop** [comment]
2.9.0 里面已经支持了 ，主题看 https://github.com/baidu/amis/pull/6372

**Comment by 17671881483** [comment]
我用了2.9amis each 动态设置name还是没用 只是给 name 添加了点存算符吗 不支持 ${} 获取 each item 的属性

**Comment by yuanzhehao** [comment]
3.1.0也遇到这个问题了。。。。
