### ISSUE TITLE
CRUD、Table添加回到顶部按钮

### ISSUE THREAD

**Issue by yahahawork** [baidu/amis#6866]
#### 是否关联于某个问题吗：
当CRUD、Table太长时需要滑动很久

#### 预期的解决方案：
CRUD、Table添加一个回到顶部按钮

**Comment by allenve** [comment]
可以用过自定义事件实现，比如：
{
      "type": "button",
      "label": "按钮",
      "onEvent": {
        "click": {
          "actions": [
            {
              "script": "document.querySelector('.crud').scrollIntoView({ behavior: 'smooth' });",
              "actionType": "custom"
            }
          ]
        }
      }
    }
