### ISSUE TITLE
Input-Image在autoFill不起作用

### ISSUE THREAD

**Issue by vexos-io** [baidu/amis#6872]
版本：3.0.0
模式：SDK
以前还好用，现在返回的数据无法通过autoFill完成form的填充，而input-file没问题

**Comment by 2betop** [comment]
不能复现，能否提供 schema 示例

**Comment by vexos-io** [comment]
请先保持Open，我正在赶项目进度，等有时间马上提供测试用例及schema

**Comment by 2betop** [comment]
由于长时间没反馈，先关闭了，有问题再开
