### ISSUE TITLE
TreeSelect树形选择器，配置远程模糊搜索，选择完选项后收起选项面板，输入框会回显出value

### ISSUE THREAD

**Issue by Whualong** [baidu/amis#6873]
#### 描述问题：

TreeSelect树形选择器，配置远程模糊搜索，选择完选项后收起选项面板，输入框会回显出value

#### 截图或视频：

https://github.com/baidu/amis/assets/44323765/5a6d6556-7509-49e8-8c15-29fc70007253

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
   pnpm 
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在？
  版本：3.0.0 
  测试环境：amis官网

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "tree-select",
        "label": "标签",
        "name": "label",
        "multiple": true,
        "enableNodePath": false,
        "hideRoot": true,
        "showIcon": false,
        "initiallyOpen": false,
        "onEvent": {},
        "clearable": true,
        "searchable": true,
        "autoCheckChildren": false,
        "onlyLeaf": true,
        "showOutline": true,
        "placeholder": "请搜索标签名称",
        "editable": false,
        "autoComplete": "https://www.fastmock.site/mock/aca68dd478dfca5cf4c9eda197eb0ea0/api_aio/label",
        "menuTpl": "<div class=' flex overflow-auto'><span class='flex-1'>${label}${type}</span><span class='ml-2 rounded'>${typeName}</span></div>",
        "hideNodePathLabel": true,
        "onlyChildren": true,
        "size": "lg",
        "mode": "inline",
        "value": "",
        "id": "u:b99de3f94c89"
      }
    ]
  }
}
```

5. 操作步骤
① treeSelect树形选择器
② 配置远程模糊搜索
③ 选择完选项后收起选项面板
④ 输入框会回显出value

**Comment by agileago** [comment]
+1   @2betop

**Comment by 2betop** [comment]
看起来不能复现啊

<img width="826" alt="image" src="https://github.com/baidu/amis/assets/2698393/dfc5715d-9f59-4d66-ac1f-6c9e733685ac">

**Comment by Whualong** [comment]
@2betop   这是最新的配置项，我在官网复现了。bug描述的配置型mock的远程搜索接口是个假json没有复现。
`
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "tree-select",
        "label": "标签",
        "name": "label",
        "id": "u:1ff0be9ca270",
        "multiple": true,
        "enableNodePath": false,
        "hideRoot": true,
        "showIcon": false,
        "initiallyOpen": false,
        "onEvent": {},
        "clearable": true,
        "searchable": true,
        "autoCheckChildren": false,
        "onlyLeaf": true,
        "showOutline": true,
        "placeholder": "请搜索标签名称",
        "editable": false,
        "autoComplete": "https://dev-aio.zuoshouyisheng.com/api/admin/labelcenter/labelInfo/listLabelInfo?term=$term",
        "menuTpl": "<div class=' flex overflow-auto'><span class='flex-1'>${label}${type}</span><span class='ml-2 rounded'>${typeName}</span></div>",
        "hideNodePathLabel": true,
        "onlyChildren": true,
        "size": "lg",
        "mode": "inline",
        "value": ""
      }
    ]
  }
}
`

**Comment by Whualong** [comment]
https://github.com/baidu/amis/assets/44323765/5d5b561d-1532-4cf4-b990-eae352d136ef
