### ISSUE TITLE
CRUD header渲染异常

### ISSUE THREAD

**Issue by yahahawork** [baidu/amis#6880]
#### 描述问题：

向下滑动时header会有重叠区域

#### 截图或视频：

滑动前
![image](https://github.com/baidu/amis/assets/104351842/e536101c-15a3-493c-b092-cb4096ac4bba)

滑动后
![image](https://github.com/baidu/amis/assets/104351842/ef2f4b14-95a3-48db-8e1b-a76c3a078dd7)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
`3.0`

**Comment by 2betop** [comment]
是说有条线吧，3.1.0 应该已经没了
<img width="1340" alt="image" src="https://github.com/baidu/amis/assets/2698393/09549ab9-1dec-40f0-a862-342d1fe22630">
