### ISSUE TITLE
编辑器第一次点击代码块报错：ES Modules may not assign module.exports or exports.*, Use ESM export syntax 33720

### ISSUE THREAD

**Issue by Niqian** [baidu/amis#6886]
#### 实现场景：

使用方法是自己开发了一个组件，组件的框架也是vue，里面引用了amis-editor，（主要目的是解决数据隐射和一些通用的异常处理，然后注入axios等等）并打包成依赖包提供给其他vue项目。

单独在组件中使用编辑器是正常的，但是引用到其他vue工程中就会有问题，当第一次点击代码时，会报ES Modules may not assign module.exports or exports.*, Use ESM export syntax 33720，第二次就好了，当刷新页面后又会一次。

能否提供下解决思路，是打包的问题还是什么？之前刷到一个issue，说可能和monaco-editior有关系。
@nwind

**Comment by hsm-lv** [comment]
估计要看下vue工程内依赖包的版本。monaco-editor的话一般需要MonacoWebpackPlugin，可以网络上搜下
