### ISSUE TITLE
tpl里边写ejs的时候，if条件语句不支持三种条件吗

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#689]
`"tpl":"<% if(data.is_exist == ''){ %><span style='font-size:14px'>-</span> <% } else if(data.is_exist == true){ %> <span style='font-size:14px'>匹配</span> <% } else if(data.is_exist == false){ %> <span style='font-size:14px'>不匹配</span> <% } %>",`
![image](https://user-images.githubusercontent.com/64950961/84519669-fe87ab80-ad04-11ea-8d6a-1e4196afe242.png)

is_exist字段后端返回的有三种情况，true false 和空，我写了if  else if 和else三层，目前的效果是前两层可以正常显示-   和匹配，而第三层不匹配渲染不出来

**Comment by 2betop** [comment]
把 _`==`_ 换成 `===` 因为 `'' == false` 的结果是 `true`
