### ISSUE TITLE
如何在 curl 里只有一条时候强制显示分页?

### ISSUE THREAD

**Issue by iiixxxiii** [baidu/amis#6890]
#### 实现场景：
如何在 curl 里只有一条时候强制显示分页?

#### 存在的问题：
现在 curl 里少于10条不显示分页

#### 当前方案：
在 curl 里只有一条时候强制显示分页

```
code here...
```

**Comment by 2betop** [comment]
`alwaysShowPagination ` 配置成 true， 具体看 crud 属性表：https://aisuda.bce.baidu.com/amis/zh-CN/components/crud?page=1#%E5%B1%9E%E6%80%A7%E8%A1%A8

**Comment by iiixxxiii** [comment]
ok 解决了谢谢
