### ISSUE TITLE
设置了loadDataOnce，但点击分页按钮，页面每次还是会刷新

### ISSUE THREAD

**Issue by upeng** [baidu/amis#690]
api设置了loadDataOnce，但是分页查询时页面每次还是会重复刷新，导致反复对接口发起请求。
前端小白直接使用jssdk，想请教下原因

**Comment by RickCole21** [comment]
分页 和 查询 是两个操作吧

- 分页应该不会重新请求接口，你再确认下？
- 查询时候想不重新请求请求，应该是需要配置`loadDataOnceFetchOnFilter: false`

**Comment by upeng** [comment]
> 分页 和 查询 是两个操作吧
> 
> * 分页应该不会重新请求接口，你再确认下？
> * 查询时候想不重新请求请求，应该是需要配置`loadDataOnceFetchOnFilter: false`

**文档**
loadDataOnce  是否一次性加载所有数据（前端分页）
loadDataOnceFetchOnFilter 在开启 loadDataOnce 时，filter 时是否去重新请求 api

设置了两者，但是在切换页码时还是会重新发起请求，不知道是因为jssdk不支持还是哪里设置有误，
参考这个例子 https://baidu.github.io/amis/crud/load-once?page=1

**Comment by upeng** [comment]
@RickCole21

**Comment by RickCole21** [comment]
咋设置的，给个截图

**Comment by upeng** [comment]
> 咋设置的，给个截图

![image](https://user-images.githubusercontent.com/8914241/84624655-5f390300-af14-11ea-89af-5ce5332d8c29.png)

**Comment by upeng** [comment]
@RickCole21 请问是哪里设置有问题吗？
页面效果：翻页刚开始,页面url上的page参数值改变，而且的确没有触发reload，但是紧随其后就会reload整个页面

**Comment by 2betop** [comment]
你这个只需要在  crud 那配置 syncLocation: false 就完了，你的刷新主要原因是同步地址栏导致的。
