### ISSUE TITLE
curd表格赋值的bug

### ISSUE THREAD

**Issue by Hemri789** [baidu/amis#6907]
使用checkBox赋值事件，赋值出错，只能赋值第一行的数据。
![image](https://github.com/baidu/amis/assets/92628105/1144e971-1b5c-4c59-90ef-49cb4574b6fa)

![权限管理](https://github.com/baidu/amis/assets/92628105/b8be33e0-601a-41f0-b181-e587c0bf2bbf)

**Comment by hsm-lv** [comment]
目前还不支持这种用法，后面会先支持更新行记录
