### ISSUE TITLE
右上角那个点击退出的功能，点击没有反应

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#691]
`import * as React from 'react';

interface UserInfoProps {
    user: any;
};
interface UserInfoState {
    open?: boolean;
};
export default class UserInfo extends React.Component<UserInfoProps, UserInfoState> {
    constructor(props: UserInfoProps) {
        super(props);
        this.state = {
            open: false,
        };
        this.open = this.open.bind(this);
        this.close = this.close.bind(this);
        this.logout = this.logout.bind(this);
    }

    static defaultProps = {
    };
    open() {
        this.setState({
            open: true
        });
    }
    close() {
        this.setState({
            open: false
        });
    }
    handleClickOutside() {
        this.close();
    }

    logout() {  
        const user = this.props.user;
        user.logout();    
        sessionStorage.removeItem('authenticated');  
        window.location.href ="https://sso.100tal.com/portal/login/2084971484?url=beta-zzcov-admin.xesv5.com";    
    }

    render() {
        const user = this.props.user;
        const open = this.state.open;

        return (
            <div className="dropdown">
                <span
                    onClick={this.open}
                >
                    <span className="pull-right m-b-n-sm m-l-sm">
                        <span><i className="iconfont icon-admin" /></span>
                        <i className="on md b-white bottom" />
                    </span>
                    <span className="hidden-sm hidden-md">{user.name}</span>
                    <b className="caret" />
                </span>
            </div>
        );
    }
}`

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/84625347-a673c380-af15-11ea-82e1-2c0b169438df.png)

**Comment by tanmengfei** [comment]
是不是也没有退出按钮

**Comment by 2betop** [comment]
这个不属于 amis 渲染器的范畴，那个只是示例。amis 渲染器只负责内容区的渲染。

**Comment by tanmengfei** [comment]
好的
