### ISSUE TITLE
能不能实现类似于声明变量、给变量赋值、并访问变量的特性？

### ISSUE THREAD

**Issue by wencan** [baidu/amis#6915]
#### 是否关联于某个问题吗：
一个对话框，有若干个formitem，一个提交按钮
现需要根据其中一个formitem的值，执行一个复杂的表达式，计算出一个数值。
需要根据该数值，决定提交按钮是否禁用。
提交时，需要把该数值作为data内容提交。
（实际场景中，需要该数值的，不止两个地方）

目前的实现方案时，复制计算表达式，每次需要该数值时，重新执行表达式计算一遍。

#### 预期的解决方案：
作用域声明一个变量，
每次formitem change时，重新执行表达式，计算结果赋值给声明的变量。
每次需要该数值时，直接使用变量

**Comment by Icodezhan** [comment]
公式组件

**Comment by 2betop** [comment]
看起来 公式组件 可以解决，有问题再开
