### ISSUE TITLE
jsdk 下 crud onEvent "selectedChange" 失效

### ISSUE THREAD

**Issue by hwzero** [baidu/amis#6917]
试了3.0.0 和 2.9.0的jssdk，对crud 配置 
"onEvent": {
        "selectedChange": {
          "actions": [
            {
              "actionType":"custom",
              "script": "debugger;"
            }
          ]
        }
      }

都不起作用

**Comment by hsm-lv** [comment]
当前CRUD的事件还没接入，和是否sdk无关哦

**Comment by hsm-lv** [comment]
我这边没有复现呢。
<img width="1413" alt="image" src="https://github.com/baidu/amis/assets/80095014/531331f7-1a18-4e3a-a2b8-a20e6a05bc9e">
