### ISSUE TITLE
希望在app组件（或其他组件）增加底纹特效功能

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#6921]
#### 是否关联于某个问题吗：
如图增加当前登陆用户的信息，该功能是一个企业级应用的常用功能。为了防止随意截图泄漏信息。
![image](https://github.com/baidu/amis/assets/11575908/80459bdf-7fba-4b49-a3fb-1c5da0bd9626)

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by 2betop** [comment]
这个功能先外围自己加吧，可以考虑用这个 `@hoythan/watermark-dom`

**Comment by xiahao90** [comment]
sdk.js加上watermark.js是不是变量名冲突了哦
![image](https://github.com/baidu/amis/assets/11575908/75c5953d-5334-4b0f-b3d2-1bbf55218d74)

![image](https://github.com/baidu/amis/assets/11575908/92af212f-af6c-48a1-bb2d-05f76b5192bf)

**Comment by xiaozhiliaoo** [comment]
> 自己



> 这个功能先外围自己加吧，可以考虑用这个 `@hoythan/watermark-dom`

这个具体怎么加到aims里面呢，有没有操作指南呀

**Comment by xiahao90** [comment]
> > 自己
> 
> > 这个功能先外围自己加吧，可以考虑用这个 `@hoythan/watermark-dom`
> 
> 这个具体怎么加到aims里面呢，有没有操作指南呀

这么简单还要指南，去看@hoythan/watermark-dom就明白了
