### ISSUE TITLE
definitions在页面amis-editor无法图形化编辑，只能用代码里编辑，修改页面比较麻烦，希望能在editor里图形化编辑它。

### ISSUE THREAD

**Issue by EvanZheng11** [baidu/amis#6922]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by hsm-lv** [comment]
嗯，短期内不会支持，后期会考虑支持的

**Comment by Lijie0981** [comment]
这个功能最近有规划不？

> 嗯，短期内不会支持，后期会考虑支持的

**Comment by hsm-lv** [comment]
近期只会针对弹窗做definitions的可视化，其他的交互还是需要手写。
