### ISSUE TITLE
Amis3.0 webpack devServer 是否支持？

### ISSUE THREAD

**Issue by jokingzhang** [baidu/amis#6930]
#### 实现场景：
本地开发，想使用 devServer 的代理功能，以及 historyApiFallback 搞定路由问题

#### 存在的问题：
在 `amis.config.js` 设置 devServer，出现报错
![image](https://github.com/baidu/amis/assets/10766546/00c50b76-5cfd-4f70-b470-132943fa9e28)

```
ERROR in undefined /Users/zhangbx/dev/demos/fenghua_lowcode/client/tsconfig.json
[tsl] ERROR
      TS6059: File '/Users/zhangbx/dev/demos/fenghua_lowcode/client/demo/scripts/chunk/5849.94e1c0cb.js' is not under 'rootDir' '/Users/zhangbx/dev/demos/fenghua_lowcode/client/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
```

#### 当前方案：
本地起一个Nginx代理，或者其他代理工具：[SwitchyOmega](chrome-extension://padekgcemlokbadohgkifijomclgjgif/options.html#!/about) 解决代理问题
使用 HashRouter 代理 BrowserRouter

**Comment by zwlyn** [comment]
+1

**Comment by jokingzhang** [comment]
代理可以设置：

```
    proxyTable: {
      '/api': {
        target: 'http://localhost:3001',
        pathRewrite: {'^/api': ''}
      }
    },
```
BrowserRouter 还是用不了，只能走Hash了

**Comment by wibetter** [comment]
amis.config.js中的proxyTable只是用来配置本地接口代理的：
<img width="1062" alt="image" src="https://github.com/baidu/amis/assets/11958920/8fe0b5d4-d910-4a56-b6fd-5adfd4391d9b">

**Comment by jokingzhang** [comment]
> <img alt="image" width="1062" src="https://user-images.githubusercontent.com/11958920/244643728-8fe0b5d4-d910-4a56-b6fd-5adfd4391d9b.png">

大佬，现在想用 BrowserRouter，会报404的问题，可以支持 historyApiFallback 的配置吗？
还是这块只能想办法绕过去？
- 自己用 webpack 配置一下，不使用官方cli：https://github.com/aisuda/amis-widget-cli
- 用 express 代理一下（好像更麻烦了 :(  T_T

**Comment by wibetter** [comment]
目前amis.config.js还没有支持devServer配置，不过你提的需求场景挺合理的，我看下怎么支持下哈。

**Comment by wibetter** [comment]
@jokingzhang amis-widget-cli 已默认支持 history 路由模式，无需额外配置。你也可以拉取amis-editor-demo最新代码本地验证效果：https://github.com/aisuda/amis-editor-demo/commit/70e535540bec26a404b3945b625939dd2a244c67
