### ISSUE TITLE
App多页应用怎么隐藏Header顶部区域

### ISSUE THREAD

**Issue by wencan** [baidu/amis#6947]
我想要去掉或者隐藏App页面顶部。

https://github.com/aisuda/amis-admin
可以拿这个例子，将index.html的header的值改为{}，或者直接去掉header字段
效果是header内容为背景色，坑还是被占着

求彻底去掉或者隐藏header的办法

**Comment by 2betop** [comment]
等这个合入后 #6950 下个版本可以通过把 header、brandName 以及 logo 都不配置来关掉 header 输出，同时 env 里面记得下发  `affixOffsetTop` 为 0

**Comment by wencan** [comment]
@2betop 有没有可能，保留brandName、logo，只去掉header?

**Comment by whuwangyong** [comment]
> 

然后把header里面那个侧边栏收起的按钮放到侧边栏底部。

@2betop 大大能考虑下吗~

**Comment by whuwangyong** [comment]
> @2betop 有没有可能，保留brandName、logo，只去掉header?

然后把header里面那个侧边栏收起的按钮放到侧边栏底部。

@2betop 大大能考虑下吗~
