### ISSUE TITLE
终于实现了单页多选项卡效果,仅供参考,App/Tabs/iframe

### ISSUE THREAD

**Issue by ztky01** [baidu/amis#6948]
我这边的的技术栈是Asp.Net Core MVC
所有的老项目都不是前后端分离,而且大多数页面,都是一些增删改查的基础页面
amis JS SDK的方式应用于一切常规页面效果非常好
但是首页一直是一个痛点
期待的效果就是,根据不同的人员权限返回不同菜单,每点一个菜单都在当前页面Tabs中打开一个新的选项卡
然后每个选项卡里其实只是简单嵌套了一个iframe,然后打开一个新模块
之前都是JQueryEasyUI做的首页  或者element-ui做的首页  
这次终于抛弃了其他UI,但是为了一些效果 也使用到了JQuery
主要应用的组件是"App 多页应用"
官网推荐的用法是请参考 amis-admin 项目,但我们并不擅长这种纯前端的方式
所以尝试自己改造了一点点.

下面是演示效果动图,和部分源码
模块没有全部完整所以打开都是404,没关系只看选项卡效果就好.

期待官方大神们能借鉴一下我的操作方式 ,将来出个简单的配置 ,在app组件中就能非常容易的实现我这种效果,那样代码就看起来更清爽了;
对只借鉴操作方式就行,我写的代码部分没什么参考价值
谢谢

**Comment by ztky01** [comment]
效果展示 
![GIF 2023-5-22 11-35-25](https://github.com/baidu/amis/assets/54745508/8b956e69-8677-4185-9d2f-cd83560b1e34)

**Comment by ztky01** [comment]
var userJson = JSON.stringify({"UserCode":"104231","UserName":"User","UnitCode":"JT0001","UnitName":"集团","DepartmentCode":"BM257","DepartmentName":"管理平台项目组","JobCode":null,"JobName":"研发工程师","Guid":"4a5aae08-bd74-424f-a363-c632aa16335a"});


let currentUrl = '/';//选项卡当前激活的地址
let defaultTabName = "欢迎使用";
let virtualIndex = '/Customer/Container?pageName=Cus/empty';//首页地址
let headerHeight = 89;//能让iframe撑开 且不出现纵向滚动条的最大高度差
let amisDoAction = null;//用于调amis内部方法

let amisJSON = {
    "definitions": {
        "indexPage": {
            "type": "form",
            "id": "form_data",
            //"title": "表单",
            //"debug": true,
            "wrapWithPanel": false,
            "data": {
                "tabsMain": [
                    {
                        "name": defaultTabName,
                        "iframeSrc": virtualIndex,
                    },
                ],
            },
            "body": [
                {
                    "type": "combo",
                    "name": "tabsMain",
                    "id": "idTabsMain",
                    "label": false,
                    "multiple": true,
                    "draggable": true,
                    "tabsMode": true,
                    "tabsStyle": "line",
                    "tabsLabelTpl": "${name}",
                    "items": [
                        {
                            "type": "wrapper",
                            "body": {
                                "type": "iframe",
                                "src": "${iframeSrc}",
                            },
                            "size": "none",
                            "style": {
                                "height": innerHeight - headerHeight
                            },
                            "className": "autoHeight"
                        },
                    ],
                    "onEvent": {
                        "tabsChange": {
                            "actions": [
                                {
                                    "actionType": "custom",
                                    "script": function (context, doAction, event) {

                                        //根据当前激活的选项卡 联动左边的菜单
                                        currentUrl = event.data.item.iframeSrc == virtualIndex ? "/" : event.data.item.iframeSrc;

                                        amisScoped.updateProps({
                                            isCurrentUrl: (to, ctx) => { },
                                        });
                                    }
                                }
                            ]
                        },
                        "delete": {
                            "actions": [
                                {
                                    "actionType": "custom",
                                    "script": function (context, doAction, event) {
                                        var arr = event.data.tabsMain;
                                        //太早了不行 此时选项卡还没删呢
                                        setTimeout(function () {
                                            if ($('.cxd-Tabs-link.is-active').length == 0) {
                                                tabsAdd(defaultTabName, '/');//至少留一个默认的 不能全删掉 其实要是能让第一个选项卡不允许删除就好了
                                            }
                                            else {
                                                //根据当前激活的选项卡 联动左边的菜单
                                                var t = $('.cxd-Tabs-link.is-active a').attr('title');
                                                var item = arr.filter(x => x.name == t);
                                                currentUrl = item[0].iframeSrc == virtualIndex ? "/" : item[0].iframeSrc;

                                                amisScoped.updateProps({
                                                    isCurrentUrl: (to, ctx) => { },
                                                });
                                            }
                                        }, 200);
                                    }
                                }
                            ]
                        }
                    }
                }
            ]
        }
    },
    "type": 'app',
    "name": "page1",
    "brandName": '客户服务系统',
    "logo": '/favicon.ico',
    "header": {
        "type": "web-component",
        "tag": "div",
        "props": {
            "class": "w-full flex justify-between",
        },
        "body": [
            {
                "type": "web-component",
                "tag": "div",
                "props": {

                },
                "body": {

                }
            },
            {
                "type": "web-component",
                "tag": "div",
                "body": {
                    "type": "flex",
                    "justify": "flex-end",
                    "items": [
                        {
                            "style": {
                                "margin-left": 10,
                                "margin-right": 10
                            },
                            "type": 'tpl',
                            "tpl": '${userJson.UserName}(${userJson.UserCode}) ${userJson.UnitName}-${userJson.DepartmentName}-${userJson.JobName}'
                        },
                        {
                            "type": "wrapper",
                            "body": [
                                {
                                    "type": "service",
                                    "dataProvider": async (data, setData) => {
                                        const timer = setInterval(() => {
                                            setData({ date: new Date() })
                                        }, 1000);
                                        return () => { clearInterval(timer) }
                                    },
                                    "body": {
                                        "type": "tpl",
                                        "tpl": "${DATETOSTR(date)}"
                                    }
                                },
                            ],
                            "className": 'font-sans text-base text-gray-500',
                            "size": "none",
                            "style": {
                                "width": "120px",
                                "text-align": "center",
                                "height": 50,
                            }
                        }
                    ],
                }
            },

        ]
    },
    //"api":"",//可以通过接口获取动态菜单
    "pages": [
        {
            "label": "首页",
            "children": [
                {
                    "label": defaultTabName,
                    "url": "/",
                    "icon": "fa fa-home",
                    "schema": {
                        "$ref": "indexPage"//可以不用这种方式 单纯为了如果从后台返回数据的话 json结构简单一些
                    },
                }
            ]
        },
        {
            "label": "菜单",
            "children": [
                {
                    "label": "客户基础信息",
                    "icon": "fa fa-leaf",
                    "children": [
                        {
                            "label": "客户公司信息",
                            "url": "/Customer/Container?pageName=Cus/cuscompanyinfo",
                        },
                        {
                            "label": "客户人员信息",
                            "url": "/1",
                        },
                        {
                            "label": "客户子公司信息",
                            "url": "/2",
                        }
                    ]
                },
                {
                    "label": "客户拜访管理",
                    "url": "/3",
                    "icon": "fa fa-leaf",
                },
                {
                    "label": "客户需求管理",
                    "url": "/4",
                    "icon": "fa fa-leaf",
                }
            ]
        },
    ],
    // asideBefore: '<div class="p-2 text-center">菜单前面区域</div>',
    // asideAfter: '<div class="p-2 text-center">菜单后面区域</div>',
    "onEvent": {
        "init": {
            "actions": [
                {
                    "actionType": "custom",
                    "script": function (context, doAction, event) {
                        //为了让 iframe撑满 且不出现滚动条
                        $(window).resize(function () {
                            $('.autoHeight').css('height', (innerHeight - headerHeight) + 'px');
                        });
                        amisDoAction = doAction;
                    }
                }
            ]
        }
    },
};

//window.enableAMISDebug = true;
let amis = amisRequire('amis/embed');
let amisLib = amisRequire('amis');
let amisScoped = amis.embed('#root',
    amisJSON,
    {
        data: {
            userJson: JSON.parse(userJson),//为了取当前登录人信息
        },
    },
    {
        requestAdaptor: function (api) {
            return {
                ...api,
                headers: {
                    "X-Requested-With": "XMLHttpRequest",
                    //"Authorization": 'Bearer ' + localStorage.getItem('tokenStr')
                }
            };
        },
        theme: 'cxd',
        affixOffsetTop: 0,
        jumpTo: (to, action) => {
            var that = $('.cxd-AsideNav-list').find('a[href="' + to + '"]');
            var title = that.children('span').text();
            if (to == '' || to == '/') {
                title = defaultTabName;
            }

            currentUrl = to;

            amisScoped.updateProps({
                isCurrentUrl: (to, ctx) => { },
            });

            tabsAdd(title, to);
        },
        isCurrentUrl: (to, ctx) => {
            if (currentUrl == to) {
                document.title = '客户服务系统-' + ctx.label;
            }
            return currentUrl == to;
        },
    }
);

function tabsAdd(title, to) {
    if ($('.cxd-Tabs-links a[title="' + title + '"]').length > 0) {
        tasbSelected(title);
        return;
    }
    if (to == "/") {
        to = virtualIndex;
    }
    amisDoAction({
        "actionType": "addItem",
        "componentId": "idTabsMain",
        "args": {
            "item": {
                "name": title,
                "iframeSrc": to,
            }
        }
    })

    setTimeout(function () {
        tasbSelected(title);//执行太早了  选项卡还没生成
    }, 200);
}

function tasbSelected(title) {
    var index = $('.cxd-Tabs-link a[title="' + title + '"]').parent().index();
    //debugger;
    if (index == -1) {
        return;
    }
    //目的选中选项卡  因为没有内置的动作
    $('.cxd-Tabs-link').eq(index)[0].click();
    //$('.cxd-Tabs-link').eq(index).addClass('is-active').siblings().removeClass('is-active');
    //$('.cxd-Tabs-pane').eq(index).addClass('in is-active').siblings().removeClass('in is-active');

}

**Comment by ztky01** [comment]
稍微改了一点点样式  <style>
        html,
        body,
        .app-wrapper {
            position: relative;
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
        }

        /*面包屑*/
        .cxd-AppBcn {
            display: none;
        }

        /*combo组件新增按钮*/
        .cxd-ComboTabs-addLink {
            display: none !important;
        }

        /*Tabs选项卡*/
        .cxd-Tabs-pane {
            padding: 0px !important;
        }

        /*"tabsStyle": "line" 这之后会稍微好看些*/
        .cxd-Tabs-links {
            padding-top: 8px !important;
            padding-left: 8px !important;
        }

        /*头部加个线条好看一些*/
        .cxd-Layout-headerBar {
            border-bottom: 1px solid #ebe9eb !important;
        }
    </style>

**Comment by guikeyy** [comment]
老哥，路由怎么解决的？正常路由是：http://xxxx:8000/#/xxx ，用了这个方式，路由变成了：http://xxxx:8000/xxx，无法渲染页面了。

**Comment by gexMichael** [comment]
+1👍

**Comment by goodosoft** [comment]
nice, thanks.

**Comment by cybexr** [comment]
good thanks

**Comment by SukeWalk** [comment]
收藏，谢谢
