### ISSUE TITLE
关于ajax请求

### ISSUE THREAD

**Issue by huangyedie** [baidu/amis#6949]
#### 实现场景：
请问这个ajax请求是异步请求还是同步请求,如果是异步请求可以针对某些接口使用同步请求吗？

**Comment by huangyedie** [comment]
可以使用async ,await吗

**Comment by 2betop** [comment]
你的问题描述不够清晰，不知道在问什么，跟 amis 的关联是什么？

通常 ajax 处理都是异步处理，同步会卡界面。

**Comment by huangyedie** [comment]
是的，我希望可以设置某一些接口为同步，可以接受卡界面。

**Comment by huangyedie** [comment]
我把我出现问题的代码贴出来。
先点击form提交，会提示有必填项报错，在点击查询会返回返回count1，count2，回显到不可编辑的字段，这时候值count1,count2已经回显，但是必填项还是会报错，需要点两次查询，所以我怀疑是异步造成的。


{
			"title": "新增",
			"type": "form",
			"Id": "form_data_001",
			"mode": "horizontal",
			"preventEnterSubmit": true,
			"redirect": "/perupls/list",
			"api": "{提交api}",
			"actions": [
				{
					"type": "submit",
					"label": "提交",
					"level": "primary"
				}
			],
			"body": [{
                    "type": "group",
                    "body": [{
                        "name": "Code",
                        "Id": "Code",
                        "type": "input-text",
                        "label": "主号",
                        "clearable": true,
                        "required": true
                    },
                    {
                        "type": "button",
                        "label": "查询",
                        "primary": true,
                        "wrapWithPanel": false,
                        "actionType": "ajax",
                        "api": {
                            "method": "post",
                            "url": "{自行写一个查询接口返回Count1,Count2}",
                            "data": {
                                "Code": "${Code}",
                                "Type": 1
                            }
                        }
                    }]
                },
				{
                    "type": "group",
                    "body": [{
                            "name": "Count1",
                            "Id": "Count1",
                            "type": "input-text",
                            "label": "Count1数量",
                            "disabled": true,
                            "required":true
                        },
                        {
                            "name": "Count2",
                            "Id": "Count2",
                            "type": "input-text",
                            "label": "Count2数量",
                            "disabled": true,
                            "required":true
                        }
                    ]
                }
			]
		}

**Comment by huangyedie** [comment]
查询接口你模拟一个把

**Comment by 2betop** [comment]
已复现，感谢反馈，等#6961 合入后的下一个版本修复

**Comment by huangyedie** [comment]
感谢处理，问一个别的问题，用ajax请求时候,在配置url时，可以自定义同步吗？比如加上async，await，就是我想让哪个接口请求同步我就配置一个同步属性，类似于ajax请求的 async:false

**Comment by 2betop** [comment]
> 感谢处理，问一个别的问题，用ajax请求时候,在配置url时，可以自定义同步吗？比如加上async，await，就是我想让哪个接口请求同步我就配置一个同步属性，类似于ajax请求的 async:false

不能配置，其实这个问题跟异步还是同步无关。
