### ISSUE TITLE
amis3.0.0 picker 内嵌模式无法勾选

### ISSUE THREAD

**Issue by crizydevl** [baidu/amis#6958]
#### 描述问题：

amis3.0.0 picker 内嵌模式无法勾选

![1684809294913](https://github.com/baidu/amis/assets/43633044/63bcb804-71cf-4395-8d0b-aa802e534231)

**Comment by crizydevl** [comment]
多点几下，有几率能勾选上

**Comment by 2betop** [comment]
最新 master 已修复次问题，等待下次发版本

**Comment by 2betop** [comment]
目前要点整行能选上，点 icon 反而点不上
