### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Richard-yhy** [baidu/amis#6959]
#### 描述问题：

只要执行npm run build就会报一堆找不到对象的错误，npm run start本地运行没任何问题

#### 截图或视频：

(!) Plugin typescript: @rollup/plugin-typescript TS2339: Property 'manager' does not exist on type 'ControlPlugin'.
src/plugin/Form/Control.tsx: (67:37)

67                 onClick={() => this.manager.showRendererPanel('表单项')}
                                       ~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2339: Property 'renderPlaceholder' does not exist on type 'HiddenControlPlugin'.
src/plugin/Form/Hidden.tsx: (38:17)

38     return this.renderPlaceholder(
                   ~~~~~~~~~~~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2339: Property 'manager' does not exist on type 'ArrayControlPlugin'.
src/plugin/Form/InputArray.tsx: (187:26)

187     const manager = this.manager;
                             ~~~~~~~

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？
2.9.0和master都有这问题

**Comment by 2betop** [comment]
ts 错误不影响编译产出，有些地方 ts 语法说明没处理好
