### ISSUE TITLE
rich-text initApi无法注入html变量

### ISSUE THREAD

**Issue by hotmaycold** [baidu/amis#696]
对rich-text使用initApi好像初始化信息注入不进去，而且富文本的options属性好像也不生效

**Comment by 2betop** [comment]
initApi 初始化是没有这个问题，至少我不能复现。options 目前确实无效，不过已经提交代码了下个版本会生效。

**Comment by hotmaycold** [comment]
> initApi 初始化是没有这个问题，至少我不能复现。options 目前确实无效，不过已经提交代码了下个版本会生效。

估计我少了什么异步选项？
tinyMce加载好时数据还没请求完？
我将rich-text的name改了再改回来就有了，sdk引入
```
{
    "type": "page",
    "body": {
      "title": "",
      "type": "form",
      "mode": "horizontal",
      "initApi": "/dev-api/get/rich_text",
      "controls": [
        {
          "type": "rich-text",
          "name": "html",
          "label": "Rich Text"
        },
        {
          "type": "static",
          "name": "html",
          "label": "你刚刚输入的是："
        }
      ],
      "actions": [{ type: 'action', actionType: 'confirm', level: 'primary', label: '提交' }]
    }
```

**Comment by 2betop** [comment]
原来如此，用这个版本先：amis@1.0.15-beta.0

**Comment by hotmaycold** [comment]
> amis@1.0.15-beta.0
大佬好像不顶用，sdk更新了吗
`-- amis@1.0.15-beta.0

**Comment by 2betop** [comment]
npm 里面的 sdk 版本更新了，你不会用的是 cdn 地址吧，cdn 没有更新

**Comment by hotmaycold** [comment]
> npm 里面的 sdk 版本更新了，你不会用的是 cdn 地址吧，cdn 没有更新

用的是npm里的，你引用sdk是成功的？

**Comment by 2betop** [comment]
嗯，亲测过了，没问题

**Comment by hotmaycold** [comment]
> 嗯，亲测过了，没问题

crud不想在外部fetcher有什么好的方式把返回的数据转化为items吗？

**Comment by 2betop** [comment]
看不懂，你再换个描述？

**Comment by hotmaycold** [comment]
> 看不懂，你再换个描述？

用curd但是后端传过来是data{data:{data:[1,2,3]}}
除了全局fetcher请求还有什么别的可以通过改json就能渲染的方式吗

**Comment by 2betop** [comment]
当个请求也可以配置适配器，具体看 类型文档里面的 API 部分。

**Comment by hotmaycold** [comment]
> 当个请求也可以配置适配器，具体看 类型文档里面的 API 部分。

找到了谢谢

**Comment by hotmaycold** [comment]
> 嗯，亲测过了，没问题

今天重新全删，cache clean以后有效果了

**Comment by hotmaycold** [comment]
> 当个请求也可以配置适配器，具体看 类型文档里面的 API 部分。

用combo编辑列表项，编辑成功后想直接更新本地视图而不发请求有什么方法？

**Comment by hotmaycold** [comment]
类似于quickEdit的功能但是用combo做

**Comment by nwind** [comment]
有问题再重新开一个吧，更新本地视图是具体要做啥

**Comment by hotmaycold** [comment]
> 有问题再重新开一个吧，更新本地视图是具体要做啥

现在reload target?name=param 就已经可以解决了，一年前多的问题了
