### ISSUE TITLE
3.0新版本 fromNow  过滤器 变成英文了  

### ISSUE THREAD

**Issue by wensia** [baidu/amis#6964]
刚更新了3.0版本, fromNow  过滤器结果变成英文了
回退到2.9版本即为中文
![image](https://github.com/baidu/amis/assets/113636620/ebb0c1bb-ffd4-4138-b116-6ff4f5ccfd53)

**Comment by 2betop** [comment]
感谢反馈，问题重复了 https://github.com/baidu/amis/issues/6914 
并且已合入了新的 pr，下个版本会修复 https://github.com/baidu/amis/pull/6926
