### ISSUE TITLE
JSONSchema Editor 字段类型为数组的时候，不能新增子项

### ISSUE THREAD

**Issue by KillenMr** [baidu/amis#6967]
#### 描述问题：

JSONSchema Editor 字段类型为数组的时候，不能新增子项

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/76677526/83641dd5-50cf-4474-93f8-b87433ca970b)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3.0.0 版本，beta 也存在问题

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "json-schema-editor",
        "name": "schema",
        "label": "字段类型",
        "rootTypeMutable": true,
        "showRootInfo": true
      }
    ]
  }
}
```

4. 操作步骤
如上描述

**Comment by KillenMr** [comment]
![image](https://github.com/baidu/amis/assets/76677526/b6402779-0bcd-44c1-86e0-c408780d7429)

**Comment by 2333Ge** [comment]
老哥解决了吗，该怎么配置呢

**Comment by KillenMr** [comment]
> 

本身就不应该有，这是 schema

**Comment by KillenMr** [comment]
> 老哥解决了吗，该怎么配置呢

本身就不应该有，这是 schema

**Comment by 2333Ge** [comment]
> > 老哥解决了吗，该怎么配置呢
> 
> 本身就不应该有，这是 schema

噢噢，理解了
