### ISSUE TITLE
多级弹框可以在最后一个弹窗完成后，全部关闭吗

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#697]
![image](https://user-images.githubusercontent.com/64950961/84762137-02fdde00-affd-11ea-8712-5a9870342d5c.png)
比如这个弹框“来吧”这里是“确定”，点击确定发送了ajax请求，然后最外层的弹框自动关闭了，那有办法一起把下边的弹框也关闭吗

**Comment by tanmengfei** [comment]
大佬，这个问题求关注呀

**Comment by RickCole21** [comment]
doing

**Comment by tanmengfei** [comment]
是你们正在做嘛？下个版本就可以出吗

**Comment by RickCole21** [comment]
应该会在beta版里，或者你等正式版

**Comment by tanmengfei** [comment]
好的

**Comment by RickCole21** [comment]
先用 1.0.15-beta.30，或者等正式版，用法是
1. 给想要关闭的dialog上配置name，例如`name: "dialog1"`
2. 操作的action按钮上，配置`close:"dialog1"`

可以关闭多个，用逗号分隔`close:"dialog1,dialog2"`
