### ISSUE TITLE
combo 多行间组件存在事件耦合

### ISSUE THREAD

**Issue by ziBLan** [baidu/amis#6972]
#### 描述问题：

combo 多行间组件存在事件耦合

#### 截图或视频：

https://github.com/baidu/amis/assets/29452405/47191202-4b3d-4749-85e6-e5887d8fc124

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "select",
  "label": "选项",
  "name": "select",
  "options": [
    {
      "label": "选项A",
      "value": "A"
    },
    {
      "label": "选项B",
      "value": "B"
    }
  ],
  "id": "u:ddbc86ff01ea",
  "multiple": false,
  "onEvent": {
    "change": {
      "weight": 0,
      "actions": []
    }
  }
}
```

4. 操作步骤
我希望新增行后每行之间的事件关系隔离不受影响

**Comment by hsm-lv** [comment]
贴一下combo的json代码

**Comment by ziBLan** [comment]
{
  "type": "combo",
  "id": "u:af68d714f78d",
  "onEvent": {
    "tabsChange": {
      "weight": 0,
      "actions": [
        {
          "script": "/* 自定义JS使用说明：\n  * 1.动作执行函数doAction，可以执行所有类型的动作\n  * 2.通过上下文对象context可以获取当前组件实例，例如context.props可以获取该组件相关属性\n  * 3.事件对象event，在doAction之后执行event.stopPropagation = true;可以阻止后续动作执行\n*/\ndebugger;\ncontext.props.id = context.props.index;",
          "actionType": "custom"
        }
      ]
    }
  },
  "label": "组合输入",
  "name": "combo",
  "multiple": true,
  "addable": true,
  "removable": true,
  "removableMode": "icon",
  "addBtn": {
    "label": "新增",
    "icon": "fa fa-plus",
    "level": "primary",
    "size": "sm",
    "id": "u:798db13b4c61",
    "onEvent": {
      "click": {
        "weight": 0,
        "actions": [
          {
            "args": {
            },
            "script": "/* 自定义JS使用说明：\n  * 1.动作执行函数doAction，可以执行所有类型的动作\n  * 2.通过上下文对象context可以获取当前组件实例，例如context.props可以获取该组件相关属性\n  * 3.事件对象event，在doAction之后执行event.stopPropagation();可以阻止后续动作执行\n*/\ndebugger;",
            "actionType": "custom"
          }
        ]
      }
    }
  },
  "items": [
    {
      "type": "select",
      "label": "选项",
      "name": "select0",
      "options": [
        {
          "label": "选项A",
          "value": "A"
        },
        {
          "label": "选项B",
          "value": "B"
        }
      ],
      "id": "u:82cab0721536",
      "multiple": false,
      "onEvent": {
        "change": {
          "weight": 0,
          "actions": [
            {
              "componentId": "u:69a194ee03fb",
              "args": {
                "value": "${IF(event.data.value==='A',true,false)}"
              },
              "actionType": "visibility"
            },
            {
              "args": {
                "value": "\"1\""
              },
              "actionType": "setValue",
              "componentId": "u:69a194ee03fb",
              "stopPropagation": ""
            },
            {
              "args": {
              },
              "actionType": "custom",
              "script": "/* 自定义JS使用说明：\n  * 1.动作执行函数doAction，可以执行所有类型的动作\n  * 2.通过上下文对象context可以获取当前组件实例，例如context.props可以获取该组件相关属性\n  * 3.事件对象event，在doAction之后执行event.stopPropagation = true;可以阻止后续动作执行\n*/\ndebugger;\n"
            }
          ]
        }
      }
    },
    {
      "type": "select",
      "name": "select",
      "placeholder": "选项",
      "options": [
        {
          "label": "A",
          "value": "a"
        },
        {
          "label": "B",
          "value": "b"
        }
      ],
      "id": "u:69a194ee03fb"
    }
  ],
  "strictMode": true,
  "syncFields": [
  ],
  "tabsMode": false,
  "draggable": true
}

**Comment by ziBLan** [comment]
> 贴一下combo的json代码
{
"type": "combo",
"id": "u:af68d714f78d",
"onEvent": {
"tabsChange": {
"weight": 0,
"actions": [
{
"script": "/* 自定义JS使用说明：\n * 1.动作执行函数doAction，可以执行所有类型的动作\n * 2.通过上下文对象context可以获取当前组件实例，例如context.props可以获取该组件相关属性\n * 3.事件对象event，在doAction之后执行event.stopPropagation = true;可以阻止后续动作执行\n*/\ndebugger;\ncontext.props.id = context.props.index;",
"actionType": "custom"
}
]
}
},
"label": "组合输入",
"name": "combo",
"multiple": true,
"addable": true,
"removable": true,
"removableMode": "icon",
"addBtn": {
"label": "新增",
"icon": "fa fa-plus",
"level": "primary",
"size": "sm",
"id": "u:798db13b4c61",
"onEvent": {
"click": {
"weight": 0,
"actions": [
{
"args": {
},
"script": "/* 自定义JS使用说明：\n * 1.动作执行函数doAction，可以执行所有类型的动作\n * 2.通过上下文对象context可以获取当前组件实例，例如context.props可以获取该组件相关属性\n * 3.事件对象event，在doAction之后执行event.stopPropagation();可以阻止后续动作执行\n*/\ndebugger;",
"actionType": "custom"
}
]
}
}
},
"items": [
{
"type": "select",
"label": "选项",
"name": "select0",
"options": [
{
"label": "选项A",
"value": "A"
},
{
"label": "选项B",
"value": "B"
}
],
"id": "u:82cab0721536",
"multiple": false,
"onEvent": {
"change": {
"weight": 0,
"actions": [
{
"componentId": "u:69a194ee03fb",
"args": {
"value": "${IF(event.data.value==='A',true,false)}"
},
"actionType": "visibility"
},
{
"args": {
"value": ""1""
},
"actionType": "setValue",
"componentId": "u:69a194ee03fb",
"stopPropagation": ""
},
{
"args": {
},
"actionType": "custom",
"script": "/* 自定义JS使用说明：\n * 1.动作执行函数doAction，可以执行所有类型的动作\n * 2.通过上下文对象context可以获取当前组件实例，例如context.props可以获取该组件相关属性\n * 3.事件对象event，在doAction之后执行event.stopPropagation = true;可以阻止后续动作执行\n*/\ndebugger;\n"
}
]
}
}
},
{
"type": "select",
"name": "select",
"placeholder": "选项",
"options": [
{
"label": "A",
"value": "a"
},
{
"label": "B",
"value": "b"
}
],
"id": "u:69a194ee03fb"
}
],
"strictMode": true,
"syncFields": [
],
"tabsMode": false,
"draggable": true
}

**Comment by ziBLan** [comment]
> 贴一下combo的json代码

{
  "type": "combo",
  "id": "u:af68d714f78d",
  "onEvent": {
    "tabsChange": {
      "weight": 0,
      "actions": [
        {
          "script": "/* 自定义JS使用说明：\n  * 1.动作执行函数doAction，可以执行所有类型的动作\n  * 2.通过上下文对象context可以获取当前组件实例，例如context.props可以获取该组件相关属性\n  * 3.事件对象event，在doAction之后执行event.stopPropagation = true;可以阻止后续动作执行\n*/\ndebugger;\ncontext.props.id = context.props.index;",
          "actionType": "custom"
        }
      ]
    }
  },
  "label": "组合输入",
  "name": "combo",
  "multiple": true,
  "addable": true,
  "removable": true,
  "removableMode": "icon",
  "addBtn": {
    "label": "新增",
    "icon": "fa fa-plus",
    "level": "primary",
    "size": "sm",
    "id": "u:798db13b4c61",
    "onEvent": {
      "click": {
        "weight": 0,
        "actions": [
        ]
      }
    }
  },
  "items": [
    {
      "type": "select",
      "label": "选项",
      "name": "select0",
      "options": [
        {
          "label": "选项A",
          "value": "A"
        },
        {
          "label": "选项B",
          "value": "B"
        }
      ],
      "id": "u:82cab0721536",
      "multiple": false,
      "onEvent": {
        "change": {
          "weight": 0,
          "actions": [
            {
              "componentId": "u:69a194ee03fb",
              "args": {
                "value": "${IF(event.data.value==='A',true,false)}"
              },
              "actionType": "visibility"
            }
          ]
        }
      }
    },
    {
      "type": "select",
      "name": "select",
      "placeholder": "选项",
      "options": [
        {
          "label": "A",
          "value": "a"
        },
        {
          "label": "B",
          "value": "b"
        }
      ],
      "id": "u:69a194ee03fb"
    }
  ],
  "strictMode": true,
  "syncFields": [
  ],
  "tabsMode": false,
  "draggable": true
}
