### ISSUE TITLE
部分字符出现乱码情况（使用jssdk）

### ISSUE THREAD

**Issue by upeng** [baidu/amis#698]
![image](https://user-images.githubusercontent.com/8914241/84774982-2af73c80-b011-11ea-8ab0-c3770ce8dedf.png)
![image](https://user-images.githubusercontent.com/8914241/84775056-49f5ce80-b011-11ea-8b12-4e01eeb3bcb0.png)

![image](https://user-images.githubusercontent.com/8914241/84775271-96410e80-b011-11ea-8999-5446a0ea9615.png)

**Comment by 2betop** [comment]
这个你还是检查你自己的 server 的 response header 返回是否正确吧

**Comment by upeng** [comment]
@2betop 看着像是特殊字符无法解析的问题，如果server response header设置有问题整个页面都会乱码
