### ISSUE TITLE
 z-index: calc($zindex-spinner-overlay + 1); 问题在master分支上已经修改但是没有合并到tag v3.0.0

### ISSUE THREAD

**Issue by vipmayor** [baidu/amis#6981]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
yarn run build 报错
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
amis-ui  下scss 中已经修复的bug z-index: calc($zindex-spinner-overlay + 1);  115行
问题在master分支上已经修改但是没有合并到tag v3.0.0，帮合并下

**Comment by 2betop** [comment]
每个月底回发布新版本
