### ISSUE TITLE
yarn run build 构建报错，v3.0.0

### ISSUE THREAD

**Issue by vipmayor** [baidu/amis#6983]
此处bug修复了，但是没有合并到v3.0.0 上
![image](https://github.com/baidu/amis/assets/34638588/735fcd3a-0dcb-4f26-ae94-3a94494e119e)

**Comment by 2betop** [comment]
不合，月底发新版本，到时是 3.1

**Comment by vipmayor** [comment]
有啥临时解决方案么，除啦降版本
