### ISSUE TITLE
office-viewer组件打印事件不生效

### ISSUE THREAD

**Issue by atliwen** [baidu/amis#6986]
#### 描述问题：

使用 office-viewer 组件中添加打印按钮，点击无反应

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/10055836/f60b6f7a-6e46-4c92-9139-6309133af277)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
       `sdk` 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

   版本    3.0.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
    {
      "type": "office-viewer",
      "src": "/examples/static/simple.docx",
      "wordOptions": {
        "padding": "8px",
        "ignoreWidth": false
      }
    },
    {
      "type": "action",
      "label": "打印",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "print",
              "componentId": "office-viewer"
            }
          ]
        }
      }
    }
  ]
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
组件需要加上对应的 "id"，不然找不到，具体查看官方例子
