### ISSUE TITLE
#6961 bug修复以后,我看到你合并到master,请问怎么使用

### ISSUE THREAD

**Issue by huangyedie** [baidu/amis#6988]
#### 实现场景：
我目前使用的是jdk方式，请问我需要自己拉取mater打包吗？还是您有特定的时间来升级版本,升级jdk呢？

**Comment by 2betop** [comment]
pull

**Comment by huangyedie** [comment]
> pull

一般都是什么时候更新jdk呢？一个月更新一次吗？

**Comment by hzzlyzz** [comment]
build没有产物是什么情况呀
