### ISSUE TITLE
批量删除的问题

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#699]
这是我配置的批量删除，设置了"primaryField":"url"，我想在请求这个接口的时候，把这些url拼装成一个list传递给接口，这个可以实现吗
![Uploading image.png…]()

**Comment by 2betop** [comment]
配置 primaryField 后，取数据还是通过 ${ids} 取，不过，你这个需求没必要去配置 primaryField， 你直接这样也能取到 `${items|pick:url|join:,}`

**Comment by tanmengfei** [comment]
那这个能做成post请求吗

**Comment by RickCole21** [comment]
可以自定义api，看下api类型文档

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/84850978-bc0af980-b08b-11ea-8cb4-0a2b44734041.png)
这么传的话urls是一个字符串，有办法转数组吗

**Comment by 2betop** [comment]
文档不仔细看，把最后的 join 干掉就行了。https://amis.baidu.com/docs/renderers/tpl

**Comment by tanmengfei** [comment]
哈哈，谢谢啦
