### ISSUE TITLE
多个outputVar输出，只有最后一个存在

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#6994]
#### 描述问题：

一个事件下触发了两个send request动作，想使用outputVar输出到不同的变量，实际上event.data中只有后一个outputVar的变量会存在

#### 截图或视频：
在amis自己的编辑器页面复现的此问题：https://aisuda.github.io/amis-editor-demo/#/edit/0
如下图所示，第一个请求存储到了orgData，第二个请求存储到了staffData，接口都是成功的，但实际上event.data中只有staffData的存在。

![image](https://github.com/baidu/amis/assets/37805363/cc705a8d-6c21-4688-bf76-f3e8329ddb0b)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.9.0，新版本尝试也仍存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
    {
      "type": "button",
      "label": "Button",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "ajax",
              "args": {
                "options": {
                  "silent": true
                },
                "api": {
                  "method": "get",
                  "url": "https://www.fastmock.site/mock/5d74c58f4df39b526ef1713a19a222b6/ab/org"
                }
              },
              "outputVar": "orgData"
            },
            {
              "actionType": "ajax",
              "args": {
                "options": {
                  "silent": true
                },
                "api": {
                  "method": "get",
                  "url": "https://www.fastmock.site/mock/5d74c58f4df39b526ef1713a19a222b6/ab/staff"
                }
              },
              "outputVar": "staffData"
            },
            {
              "actionType": "custom",
              "script": "console.log(event, 'eeeeeeeeeeeee')"
            }
          ]
        }
      },
      "id": "u:d5ea745d0037"
    }
  ]
}
```

4. 操作步骤
code复制进去，点击按钮，查看控制台

**Comment by hsm-lv** [comment]
存在在数据链中，直接取即可，比如event.data. staffData、event.data. orgData等

**Comment by rumunanfeng** [comment]
> 存在在数据链中，直接取即可，比如event.data. staffData、event.data. orgData等

啥意思，怎么存？

**Comment by rumunanfeng** [comment]
> 存在在数据链中，直接取即可，比如event.data. staffData、event.data. orgData等

现在就是不知道如何解决，麻烦给出一下解决方案啊 @hsm-lv

**Comment by hsm-lv** [comment]
> > 存在在数据链中，直接取即可，比如event.data. staffData、event.data. orgData等
> 
> 现在就是不知道如何解决，麻烦给出一下解决方案啊 @hsm-lv

不用管存的问题，直接取你想要的字段就可以了
