### ISSUE TITLE
多页应用模式的pages中无法通过数据映射获取数据

### ISSUE THREAD

**Issue by hapezzz** [baidu/amis#6999]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
能否提供问题 schema ？

**Comment by hapezzz** [comment]
schema如下，其余配置项是按照&nbsp;aisuda/amis-admin: 基于 amis 的后台项目前端模板 (github.com)此项目中进行配置。
{
&nbsp; 
&nbsp; "pages": [
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; "label": "Home",
&nbsp; &nbsp; &nbsp; "url": "/",
&nbsp; &nbsp; &nbsp; "redirect": "/index"
&nbsp; &nbsp; },
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; "label": "示例",
&nbsp; &nbsp; &nbsp; "children": [
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "${ls:role}",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "children": [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "页面A-1",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "/index",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schema": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "type": "page",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "title": "页面A-1",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "body": "页面A-1"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "页面A-2",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "2",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schema": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "type": "page",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "title": "页面A-2",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "body": "页面A-2"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "页面A-3",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "3",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schema": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "type": "page",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "title": "页面A-3",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "body": "页面A-3"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "页面B",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schema": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "type": "page",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "title": "页面B",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "body": "页面B"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "页面C",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schema": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "type": "page",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "title": "页面C",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "body": "页面C"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "列表示例",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "/crud",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "rewrite": "/crud/list",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "icon": "fa fa-cube",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "children": [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "列表",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "/crud/list",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "icon": "fa fa-list",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schemaApi": "get:/pages/crud-list.json"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "新增",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "/crud/new",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "icon": "fa fa-plus",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schemaApi": "get:/pages/crud-new.json"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "查看",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "/crud/:id",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schemaApi": "get:/pages/crud-view.json"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "修改",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "/crud/:id/edit",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schemaApi": "get:/pages/crud-edit.json"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; },
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; "label": "分组2",
&nbsp; &nbsp; &nbsp; "children": [
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "用户管理",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schema": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "type": "page",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "title": "用户管理",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "body": "页面C"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "外部链接",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "link": "http://baidu.gitee.io/amis"
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "部门管理",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schemaApi": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/service/form?tpl=tpl3"
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "jsonp 返回示例",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schemaApi": "jsonp:/pages/jsonp.js?callback=jsonpCallback"
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "修改密码",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "/reset-password",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schemaApi": "get:/pages/reset-password.json",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "visible": false
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "${ls:test}",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "children": [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "用户管理",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "/user-info",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schemaApi": "get:/pages/user-info.json"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "角色管理",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "/role",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schemaApi": "get:/pages/role.json"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "label": "权限管理",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "url": "/auth",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "schemaApi": "get:/pages/auth.json"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; }
&nbsp; ]
}




1448787060
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 中午12:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] 多页应用模式的pages中无法通过数据映射获取数据 (Issue #6999)





 
能否提供问题 schema ？

**Comment by 2betop** [comment]
你的意思应该是指菜单名称需要支持关联上下文数据，等 #7019 合入后发版本可解决次问题

**Comment by hapezzz** [comment]
好的，多谢答复。祝贵司越办越好。&nbsp;




1448787060
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] 多页应用模式的pages中无法通过数据映射获取数据 (Issue #6999)





 
你的意思应该是指菜单名称需要支持关联上下文数据，等 #7019 合入后发版本可解决次问题
