### ISSUE TITLE
关于CRUD组件设计的疑惑

### ISSUE THREAD

**Issue by Mengleijin** [baidu/amis#7005]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
各位Amis研发人员，想问一下为什么CRUD组件中字段类型与Form组件相比要少，是技术原因吗？谢谢
@nwind @popduke @TeCHiScy @luckyufei @xsbchen 

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
Form 里面的是输入类的组件。
CRUD 里面是展示类的组件，确实展示类的组件比输入类的组件更少。但是 CRUD 的列有个快速编辑模式，里面支持内嵌一种输入类组件及时修改。

**Comment by Mengleijin** [comment]
@2betop 明白了，就是说不管单选，文本框，数字框，都可以用展示组件中的文本类替代？
                另外，我发现输入类组件的替换功能了，只是用CRUD组件生成的表单，选中表单填写接口对新手比较隐蔽，在大纲里比较好选中
                谢谢回复！
