### ISSUE TITLE
怎么跨文件引用组件实例？

### ISSUE THREAD

**Issue by wencan** [baidu/amis#7011]
比如，a.js中，有某个对话框。
现在b.js，也需要这个对话框。应该怎么做？

其中一个办法，当然是把对话框放c.js中，a.js和b.js都导入c.js。
不知道还有没有别的办法？

**Comment by 2betop** [comment]
抱歉，不是很理解你的需求，是说如何配置复用吗？看起来跟 amis 没有太多关系，纯 js 范畴的东西。

**Comment by hyzx86** [comment]
你是想说自定义组件么？
@wencan 参考注册自定义组件文档
