### ISSUE TITLE
App多页应用，设置 cssVars 无效

### ISSUE THREAD

**Issue by cnbattle** [baidu/amis#7014]
```
vite vue3 npm方式 引用的
```
#### 实现场景：

多页应用，重置覆盖，左侧选中菜单样式

#### 存在的问题：

cssVars 设置覆盖 `--Layout-aside-onAcitve-bg` `--Layout-asideLink-onActive-color`CSS变量 无效

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
{
    "type":"app",
    "brandName":"管理后台",
    "logo":"https://i.v2ex.co/BT6t2lwM.png",
    "footer":"<div class=\"p-2 text-center bg-light\">@启爱工作室</div>",
    "pages":[
        {
            "children":[
                {
                    "icon":"fa fa-chart-line",
                    "label":"仪表盘",
                    "schemaApi":"get:/admin/page/dashboard",
                    "url":"/dashboard"
                }
            ],
            "label":"首页",
            "redirect":"/dashboard",
            "url":"/"
        }
    ],
    "cssVars":{
        "--colors-brand-4":"#fff",
        "--Layout-aside-onAcitve-bg":"#0960bd",
        "--Layout-asideLink-onActive-color":"#fff"
    }
}
```

**Comment by cnbattle** [comment]
> 同理全局的配置可以弃用cssVars方式了

通过再 main.js 后置引入 同名CSS变量覆盖实现了
main.js
```js
import { createApp } from 'vue'
import App from './App.vue'

// 百度 AMIS
import 'amis/sdk/sdk.css';
import 'amis/lib/helper.css';
import 'amis/sdk/iconfont.css';
import 'amis/lib/themes/default.css';

import 'amis/sdk/sdk.js';
import 'amis/sdk/tinymce.js';

// 自定义 scss 变量，覆盖 amis 的配置
import './index.scss'

createApp(App).mount('#app')
```
index.scss
```scss
:root {
  --Layout-aside-onAcitve-bg: #0960bd; // 选中后 背景颜色
  --Layout-asideLink-onActive-color: #fff;  // 选中后 前景颜色（图标 文字）
  --Layout-asideLink-fontSize: var(--fonts-size-7); // 文字大小
  --Layout-asideLink-onHover-iconColor:  #fff; // 鼠标停留时 图标颜色
  --Layout-asideLink-onHover-color: #fff; // 鼠标停留时 文字颜色
}
```

![截图_20230527135259](https://github.com/baidu/amis/assets/10772658/11775eb7-f530-4674-a306-8eb9da2e4852)

**Comment by ArrNNG** [comment]
> > 同理全局的配置可以弃用cssVars方式了
> 
> 通过再 main.js 后置引入 同名CSS变量覆盖实现了 main.js
> 
> ```js
> import { createApp } from 'vue'
> import App from './App.vue'
> 
> // 百度 AMIS
> import 'amis/sdk/sdk.css';
> import 'amis/lib/helper.css';
> import 'amis/sdk/iconfont.css';
> import 'amis/lib/themes/default.css';
> 
> import 'amis/sdk/sdk.js';
> import 'amis/sdk/tinymce.js';
> 
> // 自定义 scss 变量，覆盖 amis 的配置
> import './index.scss'
> 
> createApp(App).mount('#app')
> ```
> 
> index.scss
> 
> ```css-scss
> :root {
>   --Layout-aside-onAcitve-bg: #0960bd; // 选中后 背景颜色
>   --Layout-asideLink-onActive-color: #fff;  // 选中后 前景颜色（图标 文字）
>   --Layout-asideLink-fontSize: var(--fonts-size-7); // 文字大小
>   --Layout-asideLink-onHover-iconColor:  #fff; // 鼠标停留时 图标颜色
>   --Layout-asideLink-onHover-color: #fff; // 鼠标停留时 文字颜色
> }
> ```
> 
> ![截图_20230527135259](https://user-images.githubusercontent.com/10772658/241360275-11775eb7-f530-4674-a306-8eb9da2e4852.png)

你好，请问您这个app菜单使用其他图标是怎样设置的？

**Comment by cnbattle** [comment]
用的amis集成的 `fontawesome`图标,看下 icon 参数

```
{
  "pages": [
    {
      "label": "首页",
      "url": "/",
      "redirect": "/dashboard",
      "children": [
        {
          "label": "仪表盘",
          "url": "/dashboard",
          "schemaApi": "get:/admin/page/dashboard",
          "icon": "fa fa-chart-line"
        }
      ]
    },
    {
      "label": "应用管理",
      "children": [
        {
          "label": "APP列表",
          "url": "/app",
          "schemaApi": "get:/admin/page/app",
          "icon": "fa fa-austral-sign"
        },
        {
          "label": "Token管理",
          "url": "/app_token",
          "schemaApi": "get:/admin/page/app_token",
          "icon": "fa fa-user-shield"
        }
      ]
    },
    {
      "label": "系统管理",
      "children": [
        {
          "label": "权限管理",
          "url": "/permission",
          "schemaApi": "get:/admin/page/permission",
          "icon": "fa fa-scale-balanced"
        },
        {
          "label": "页面管理",
          "url": "/page",
          "schemaApi": "get:/admin/page/page",
          "icon": "fa fa-pager"
        },
        {
          "label": "管理员管理",
          "url": "/admin",
          "schemaApi": "get:/admin/page/admin",
          "icon": "fa fa-user-gear"
        }
      ]
    },
    {
      "label": "文档",
      "children": [
        {
          "label": "Open API",
          "link": "https://item.dev.cnbattle.com/swagger",
          "icon": "fa fa-folder-tree"
        }
      ]
    }
  ]
}
```

**Comment by ArrNNG** [comment]
> 用的amis集成的 `fontawesome`图标,看下 icon 参数
> 
> ```
> {
>   "pages": [
>     {
>       "label": "首页",
>       "url": "/",
>       "redirect": "/dashboard",
>       "children": [
>         {
>           "label": "仪表盘",
>           "url": "/dashboard",
>           "schemaApi": "get:/admin/page/dashboard",
>           "icon": "fa fa-chart-line"
>         }
>       ]
>     },
>     {
>       "label": "应用管理",
>       "children": [
>         {
>           "label": "APP列表",
>           "url": "/app",
>           "schemaApi": "get:/admin/page/app",
>           "icon": "fa fa-austral-sign"
>         },
>         {
>           "label": "Token管理",
>           "url": "/app_token",
>           "schemaApi": "get:/admin/page/app_token",
>           "icon": "fa fa-user-shield"
>         }
>       ]
>     },
>     {
>       "label": "系统管理",
>       "children": [
>         {
>           "label": "权限管理",
>           "url": "/permission",
>           "schemaApi": "get:/admin/page/permission",
>           "icon": "fa fa-scale-balanced"
>         },
>         {
>           "label": "页面管理",
>           "url": "/page",
>           "schemaApi": "get:/admin/page/page",
>           "icon": "fa fa-pager"
>         },
>         {
>           "label": "管理员管理",
>           "url": "/admin",
>           "schemaApi": "get:/admin/page/admin",
>           "icon": "fa fa-user-gear"
>         }
>       ]
>     },
>     {
>       "label": "文档",
>       "children": [
>         {
>           "label": "Open API",
>           "link": "https://item.dev.cnbattle.com/swagger",
>           "icon": "fa fa-folder-tree"
>         }
>       ]
>     }
>   ]
> }
> ```

好的，谢谢。

我刚看您这个截图的时候，以为APP列表的图标（fa fa-austral-sign ）是使用的 非fontawesome 的其他图标；这个图标好像不在v4的fontawesome 内，可能是因为我用的是SDK的方式，还需要额外导入其他的文件；

我试过在菜单里用这种形式表示来图标，但没有效果。
 `
 "label": "页面",
 “icon”: {
    "type": "icon",
    "icon": "icon-bss-in-protection",
    "vendor": "iconfont"
  }`
单独使用图标组件是可以的
<img width="1454" alt="截屏2023-09-25 14 26 42" src="https://github.com/baidu/amis/assets/57611350/4fdca413-00b6-4a33-8d6e-ec6335458fe1">
