### ISSUE TITLE
Form中自定义input组件

### ISSUE THREAD

**Issue by litianyu0529** [baidu/amis#702]
我想实现一个input的框，功能比form下的number多一项千分符显示，是用@Renderer好一点还是@FormItem好一点，如果用@Renderer是不是需要从From开始重写，还是说有什么更好的写法

**Comment by 2betop** [comment]
https://baidu.github.io/amis/docs/custom#%E8%A1%A8%E5%8D%95%E9%A1%B9%E7%9A%84%E6%89%A9%E5%B1%95
