### ISSUE TITLE
国际化能否增加replaceTextKeys，只替换指定字段

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#7035]
#### 是否关联于某个问题吗：
目前使用replaceText会全部替换，只能指定忽视某些字段，但是比如在接口参数配置里面，字段名是不确定的，这时候就还需要不断的增加忽视字段配置。

#### 预期的解决方案：
期望增加一个replaceTextKeys，可以实现只替换指定字段，比如replaceTextKeys: ['label']
#### 其他可接受方案：
或者可以实现子级不替换，比如接口参数：
data: {
  name: "Bob",
  age: '18
}
可以实现配置了replaceTextIgnoreKeys: ['data']的时候，它的子节点字段名就不会去替换。这也是一种方案。

**Comment by hyzx86** [comment]
可以考虑配合万能的  addSchemaFilter 方案
![3Y9E1DORMC`%OSGX~E_NN$5](https://github.com/baidu/amis/assets/15613121/b0b9613f-3b18-4451-b722-13e35280c9f9)

**Comment by vexos-io** [comment]
我都直接用js展开某个locale块，替换掉默认，如：
{
    type: 'input-text',
    label: '年龄',
    ...locale('age')
}
哈哈，甚至连子schema块都可以替换

**Comment by hyzx86** [comment]
> 我都直接用js展开某个locale块，替换掉默认，如： { type: 'input-text', label: '年龄', ...locale('age') } 哈哈，甚至连子schema块都可以替换

你这 locale 是哪里来的？ amis 里自带那个 i18n？

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/8510 支持函数回调，可以自己写逻辑来跳过部分属性的替换
