### ISSUE TITLE
vue3+vite, crud组件点击导出报错

### ISSUE THREAD

**Issue by enkialtria** [baidu/amis#7043]
error：GET http://localhost/node_modules/.vite/deps/exceljs.js net::ERR_ABORTED 504 (Gateway Timeout)
package： "amis": "^3.0.0",
                   "amis-core": "^3.0.0",

**Comment by 2betop** [comment]
编译问题，自己分析？

**Comment by enkialtria** [comment]
改了渲染方式，成功导出了
<div ref="amisBox" class="box"/>

import { alert, confirm, render as renderSchema, toast } from 'amis'
import ReactDOM from 'react-dom'

ReactDOM.render(
		  renderSchema(
		   schema,
		    {
		    },
		    initEnv()
		  ),
		  amisBox
		)

**Comment by mizhicangyue** [comment]
> 

啊啊啊啊 我也遇到了这个问题 但是我是vue项目 sdk方式导入的 该咋解决啊 救命！

**Comment by walingcc** [comment]
> > 
> 
> 啊啊啊啊我也遇到了这个问题但是我是vue项目sdk方式导入的该咋解决啊救命！

我也遇到了这个问题，是vue项目，请问后来解决了吗
