### ISSUE TITLE
Mapping渲染器对Boolean健的处理不太妥

### ISSUE THREAD

**Issue by billy-poon** [baidu/amis#705]
https://github.com/baidu/amis/blob/eebad4ff2c7449fd1e02058671185118294f864d/src/renderers/Mapping.tsx#L35
Mapping 渲染时对于原始值 `value===true` 的情况会变成从 map 中找健为 `‘1’` 的值，对 `value===false` 则不做处理，这个设计似乎不太妥，如果要配置 `Boolean` 类型的映射，似乎要写成这样：
```
const booleanMap = {
  '1': 'yes',
  'false': 'no'
}
```
太难受了吧。。是不是不要对 `value===true` 做特殊处理，直接找健为 `'true'` 的值更合理些？

**Comment by RickCole21** [comment]
已修复，下个版本

**Comment by RickCole21** [comment]
用最新beta版 1.0.15-beta.30，或者等正式版也行
