### ISSUE TITLE
InputSubForm 子表单 能否支持宽度的调整

### ISSUE THREAD

**Issue by ArrNNG** [baidu/amis#7066]
不支持宽度或大小的调整，对一些组件或复杂表单的显示可能不太友好
<img width="1162" alt="截屏2023-06-02 13 33 07" src="https://github.com/baidu/amis/assets/57611350/c5d3be41-7a75-4053-850b-81bbd038c0d1">

**Comment by 2betop** [comment]
文档里面没说，form 里面可以配置 size: 'lg' 可以让弹窗变大，我去补充文档。
