### ISSUE TITLE
多页应用模式可以支持visibleOn吗?

### ISSUE THREAD

**Issue by hapezzz** [baidu/amis#7067]
仅支持visible，但是不支持visibleOn
{
 "pages": [

    {
      "label": "Home",
      "url": "/",
      "redirect": "/info-list"
    },

    {

      "children": [
        {
          "label": "我的消息",
          "url": "/info-list",
          "schemaApi": "get:/pages/info-list.json",
          "visible": false
        },
        {
          "label": "修改密码",
          "url": "/reset-password",
          "schemaApi": "get:/pages/reset-password.json",
          "visible": false
        },
        {
          "label": "测试标签",
          "visibleOn": "${role==='user'}"
        }
      ]
    }
    
  ]
}

**Comment by phantooom** [comment]
好像是这样，我这边在尝试使用的时候发现不太好使
