### ISSUE TITLE
select组件问题

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#707]
![image](https://user-images.githubusercontent.com/64950961/84981255-acacae80-b166-11ea-9dc4-4341f7d225a1.png)
如上图，我添加了一个selec组件，点击提交的时候向api发送请求，向数据库里边插入选择项。现在这个select选择项是我写死的，然后每次刷新，或者执行完一次ajax请求后，我添加的内容就不见了。然后我就想配置一下从接口获取选项，那我能从我提交的这个接口的返回值拿到选项吗？还是要配置source，如果配置source的话，如果其配置的接口不符个返回要求，可以在前端的adaptor修改吗
![image](https://user-images.githubusercontent.com/64950961/84982736-dadfbd80-b169-11ea-9506-fe9591550e38.png)

**Comment by RickCole21** [comment]
adaptor就是干这个的，参考下文档 https://baidu.github.io/amis/docs/renderers/Types#api

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/84984541-a110b600-b16d-11ea-9c78-9f61c9958b22.png)
是这样配置嘛？options的获取是只能写一个查询接口，不能获取添加接口的返回值配置options是嘛

**Comment by RickCole21** [comment]
![image](https://user-images.githubusercontent.com/19327810/84984843-3ad86300-b16e-11ea-831b-7d79d9cace03.png)

也许你可以用这个

**Comment by RickCole21** [comment]
![image](https://user-images.githubusercontent.com/19327810/84984942-6a876b00-b16e-11ea-88ec-0555467f0f95.png)

添加选项的表单也可以自定制

**Comment by tanmengfei** [comment]
有一个新问题哈，用户在select组件中选中了一些值，提交到了后端，然后把这些值保存在了数据库中，那页面刷新的时候，我还能保持上次勾选的选项是勾选状态吗？也就是说默认选中项可以根据后端接口的返回动态配置嘛

**Comment by RickCole21** [comment]
form配初始化接口，来初始化这个select
或者select的source里返回value字段也可以自动选中

**Comment by tanmengfei** [comment]
返回格式是什么样子的

**Comment by RickCole21** [comment]
## Select类的选择器组件，配置远程拉取`options`时，如何动态设置默认值

1. 直接配置 value: "v1,v2" 是 options 里面的 value 值
2. source接口返回的时候，同时带个 value 属性，值格式一样，如下
```
{
    "status": 0,
    "msg": "",
    "data": {
        "value": "a", // 这样会默认选中A
        "options": [
            {
                "label": "OptionA",
                "value": "a"
            },
            {
                "label": "OptionB",
                "value": "b"
            }
        ]
    }
}
```

## 给Form中的每个表单项设置默认值

通过设置Form中的initApi，然后该请求返回数据
```
{
    "status": 0,
    "msg": "",
    "data": {
        "a": "aaa",
        "b": 12,
        "c": "123",
    }
}
```
然后表单项字段名与接口返回的data中字段进行对应

**Comment by tanmengfei** [comment]
好的，太谢谢啦，我在外层表单设置submitOnChange为true以后，select勾选一下就会请求一遍接口，能等全部勾选结束，收起下拉框的时候提交吗

**Comment by RickCole21** [comment]
那你选完再点击提交不行么，我理解没啥大的区别吧

**Comment by tanmengfei** [comment]
如果没有其他办法，也只能用提交按钮啦
