### ISSUE TITLE
tree 新增交互异常：树结构新增，接口返回报错，然后点X，上一层级的节点也会消失

### ISSUE THREAD

**Issue by 2betop** [baidu/amis#7070]
![image](https://github.com/baidu/amis/assets/2698393/ebec7998-e0b5-46b5-9ab1-64f09894500b)

![image](https://github.com/baidu/amis/assets/2698393/1516e72b-fc5b-4b70-b129-a995d82fb374)

![image](https://github.com/baidu/amis/assets/2698393/c196884b-816a-463f-a75f-c9a650717cc1)

**Comment by shooop** [comment]
1
