### ISSUE TITLE
分栏设置高度后不生效

### ISSUE THREAD

**Issue by coldest7z** [baidu/amis#7076]
![image](https://github.com/baidu/amis/assets/45660758/02e14fa6-eaf5-43f0-ba1e-47a541c96d38)
![image](https://github.com/baidu/amis/assets/45660758/909954e6-a072-4044-b874-0d8e366739e9)
分栏在自定义源码里面设置高度之后不生效，内容仍然显示不完全，高度没有500PX

**Comment by 2betop** [comment]
可以生效啊，版本问题？

<img width="1161" alt="image" src="https://github.com/baidu/amis/assets/2698393/ae58ab6f-fbed-4d25-95b4-3d2f6a83a029">


```
"style": {
    "height": "400px"
  }
```
