### ISSUE TITLE
数据映射脚本中支持输出数组长度的过滤器

### ISSUE THREAD

**Issue by yinlianghui** [baidu/amis#7077]
#### 是否关联于某个问题吗：
数据映射脚本中无法实现对数组长度的判断，比如visibleOn中判断某个数组变量的长度。
![image](https://github.com/baidu/amis/assets/6219465/51678c4a-9124-4531-8441-825e242a40c3)

```json
{
  "type": "page",
  "body": [
    {
      "type": "tpl",
      "tpl": "my name is ${[1,1,1].length}",
      "visibleOn": "${[1,1,1].length > 2}"
    }
  ]
}
```

比如上述数据映射脚本无论是在tpl还是visibleOn中都能正确得到数据的长度，但是以下示例调用了filter或其它任务过滤器组合使用就不能生效了。

```json
{
  "type": "page",
  "body": [
    {
      "type": "tpl",
      "tpl": "my name is ${[1,1,1]|filter:equals:1.length}",
      "tpl__": "my name is ${[1,1,1]|filter:equals:1}",
      "visibleOn": "${[1,1,1]|filter:equals:1.length > 1}"
    }
  ]
}
```

https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/data-mapping#filter

虽然使用 COUNT表达式能获取数组长度，见：，https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#count.
但是有时业务场景下需要在过滤器中使用数组长度来做业务判断。

#### 预期的解决方案：
数据映射脚本中支持输出数组长度的过滤器，比如`"tpl": "my name is ${[1,1,1]|filter:equals:1.length}"`应该返回数组长度，而不是`my name is 1,1,1`。

感觉"my name is ${[1,1,1]|length}"这种表达式能生效就能解决问题，目前是只能写"my name is ${[1,1,1].length}"这种，即缺少数组长度过滤器length功能。

**Comment by 2betop** [comment]
可以用 `COUNT` 公式如：

`${COUNT([1, 2, 3, 4])}`

参考：https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#count

**Comment by yinlianghui** [comment]
> 可以用 `COUNT` 公式如：
> 
> `${COUNT([1, 2, 3, 4])}`
> 
> 参考：https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#count
> 
> 过滤器也可以使用新版公式 `ARRAYFILTER`
> 
> `my name is ${COUNT(ARRAYFILTER([1, 1, 2, 3, 4], item => item == 1))}`

感谢回复，COUNT和过滤器不可以混用吧，我们的业务场景下需要在过滤器中使用数组长度来做业务判断（业务场景是数组中是我们客户配置的visibleOn表达式）。

**Comment by hsm-lv** [comment]
> > 可以用 `COUNT` 公式如：
> > `${COUNT([1, 2, 3, 4])}`
> > 参考：https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#count
> > 过滤器也可以使用新版公式 `ARRAYFILTER`
> > `my name is ${COUNT(ARRAYFILTER([1, 1, 2, 3, 4], item => item == 1))}`
> 
> 感谢回复，COUNT和过滤器不可以混用吧，我们的业务场景下需要在过滤器中使用数组长度来做业务判断（业务场景是数组中是我们客户配置的visibleOn表达式，然后返回为true的个数）。

支持的。
