### ISSUE TITLE
关于布局和样式调整使用疑惑

### ISSUE THREAD

**Issue by Mengleijin** [baidu/amis#7079]
#### 存在的问题：
针对一些布局较复杂的页面，不是简单的增删改查和表单这种页面，在调整布局和样式的时候发现比较困难：
1）是不是布局比较复杂的页面最好用flex布局容器？然后在各个容器内在放组件，调整样式的时候有没有技巧和最佳实践？
2）有些表单组件，比如搜索框，是不是必须放在表单中，否则拖到编辑器里默认是只读的
3）amis在设计的时候，为什么不考虑可以随意拖拽，大小位置可以随意调整这种比较灵活的编辑器，是技术有难点吗？
谢谢大佬解惑！

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by vexos-io** [comment]
1）有很多容器可以用来组装，grid/flex/wrapper/group/tabs...
2）可以不用放在form中，但那样对于逻辑处理就比较麻烦了，因为没有store与其绑定
3）我觉得amis不是一个用编辑器来搞的事，我的经验就是用js写schema，如果需要，配合一定的js逻辑代码，因为我不会vue和react...

**Comment by 2betop** [comment]
3. 如果是绝对定位自由布局的技术方案确实是可以做到，但是这样高宽基本上是固定的，有可能内容超出，但是框架还是原来大小，同时如果是移动端则也没办法适配。所以 amis默认是流式布局。自由布局可以局部容器支持，后续编辑器会扩充这种布局容器

**Comment by 2betop** [comment]
主要是它没找到与之通信的东西，如果 在 service 里面, form 里面是可以操作的。如果直接是页面里面，页面需要配置 initApi 才可以。
