### ISSUE TITLE
crud组件使用问题

### ISSUE THREAD

**Issue by Mengleijin** [baidu/amis#7080]
#### 实现场景：
现在有一个应用分组列表，使用了crud组件，如果想实现展开某一行的一个应用，展示该应用下的服务列表，这种情况支持吗？

#### 存在的问题：
现在使用crud实现了应用分组列表，如果想实现展开某一行的某个应用，展示该应用下的服务列表，这种情况支持吗？
文档里的crud组件嵌套，它的列都是一样的吧？如果不一样应该怎样实现？

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by vexos-io** [comment]
可以用footable: true 加上 breakpoint: "*" 来实现

**Comment by 2betop** [comment]
参考：https://aisuda.bce.baidu.com/amis/examples/crud/footable?page=1

**Comment by Mengleijin** [comment]
@2betop @Mengleijin 谢谢，试了可以
