### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by fastwalkergy** [baidu/amis#7081]

**Comment by fastwalkergy** [comment]
![image](https://github.com/baidu/amis/assets/106460370/249a7373-af53-4ab3-9c99-cd1e240aa13d)
这个错误，刚刚手滑直接提交了，在https://aisuda.bce.baidu.com/amis/examples/iframe?keywords=6发现的，不信的可以自己测试，没使用代理，edge，win10

**Comment by 2betop** [comment]
这个是因为 baidu 站点做了防止 iframe 引入限制，不是 amis 的问题，这个只是个iframe 示例，换个没有限制的站点是没问题的。
