### ISSUE TITLE
CRUD 不能清除嵌套的数组筛选条件.

### ISSUE THREAD

**Issue by acrazing** [baidu/amis#7083]
#### 描述问题：

如果 CRUD 的 filter 中有一个嵌套的多选条件, 比如:

```json
{
    "type": "input-tag",
    "label": "IDs",
    "name": "ids.values",
    "value": "${ids.values}",
    "joinValues": false,
    "extractValue": true,
    "id": "u:502e84f50cc3"
  }
```

并且启用了 `syncLocation`, 将无法清空这个输入.

原因是这里只考虑了顶层的数组元素, 无法处理嵌套情况: <https://github.com/baidu/amis/blob/17e32ce204cfacf65f00db8ea0109295406d9282/packages/amis-core/src/utils/helper.ts#L1314-L1317>.

**Comment by 2betop** [comment]
等 pr 合入后可以支持深层次的数组清空
