### ISSUE TITLE
关于页面变量赋值的使用

### ISSUE THREAD

**Issue by Mengleijin** [baidu/amis#7085]
#### 实现场景：
下面是我的页面，我希望实现
0）选项卡里的宠物主人、宠物列表都会根据左侧的城市过滤
1）切换左侧的城市：比如北京、上海等，更新两个选项卡里的crud列表
2）在选项卡内搜索框内输入内容，点击后刷新对应的crud列表
![image](https://github.com/baidu/amis/assets/28032070/6492a59d-cf7a-45f0-b6ec-81a538b0eaba)

#### 存在的问题：
1）打开调试可以看到，页面变量的值变更了，但是调接口时，取不到值
2）调接口时需要传页面变量city和name，如果这两个值变更了，crud不会自动刷新是吗？
3）如果不用页面变量赋值，有没有其它实现方法？
4）左侧的菜单，试了nav是不行的，除了nav还有比较适合的组件吗？
多谢！

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
用 nav 或者 form + inputTree 都是可以的，你需要把城市信息这个变量设置在他们公共的上层，推荐直接设置到地址栏。

如果变量变更了，默认 crud 是会自动更新的，如果 crud 的 api 的 query 部分有用到 city 这个变量的话。如果你放在 data 里面则不会自动，具体看这里面的说明：https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E8%87%AA%E5%8A%A8%E5%88%B7%E6%96%B0

搜索框也是一样，只要上面那个 crud 的 api 监听了这个变量，就会自动刷新，建议同步地址栏，把搜索值设置到地址栏上。

**Comment by Mengleijin** [comment]
@2betop 你好，我两种方法都试了一下，再请教一下：
1）如果用nav，”直接设置到地址栏“是通过配置”?city=1“这种形式对吧，那搜索框组件怎样设置同步地址栏，文档里没找到
     另外，nav组件是不是不支持默认选中和选中项不能设置选中颜色？
2）form + inputTree 如果用这个组件，也是直接到地址栏吗？应该怎样设置？
3）我今天用另外一种方法，form + inputTree 设置修改即提交，提交给crud组件
      但是用form+搜索框设置修改即提交，好像是不生效的

**Comment by 2betop** [comment]
form 的 target 设置成  'window' 就是把表单数据提交到地址栏了.

form + searhBox 可能不行，得是 form + input-text

**Comment by Mengleijin** [comment]
@2betop 下面这个demo，target设置成window，为啥我这不会把表单数据提交到地址栏啊？
`{
  "type": "page",
  "body": [
    {
      "type": "form",
      "title": "表单",
      "body": [
        {
          "label": "文本框",
          "type": "input-text",
          "name": "city",
          "id": "u:9c3c926a9683"
        }
      ],
      "id": "u:bbd63391b210",
      "target": "window"
    }
  ],
  "id": "u:3aca0d7c5737",
  "asideResizor": false,
  "pullRefresh": {
    "disabled": true
  },
  "regions": [
    "body",
    "header",
    "toolbar"
  ],
  "style": {
    "boxShadow": " 0px 0px 0px 0px transparent"
  },
  "data": {
  },
  "toolbar": [
  ]
}`
