### ISSUE TITLE
InputKV组件value值不对。

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#7092]
#### 描述问题：

如图所示，填写的value值为：{"a":"a"}，应该是一个字符串，而填写后进行提交后变成了一个对象，应该提交的结果也是字符串，由后端程序进行决定是否转义对象。前端进行转义理论上算是某种注入。
#### 截图或视频：

![image](https://github.com/baidu/amis/assets/11575908/40aa850a-b108-4b8f-8673-9eac24c54773)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
adk3.1.0

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
存在

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "debug": true,
    "body": [
      {
        "type": "input-kv",
        "name": "kv"
      }
    ]
  }
}
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by xiahao90** [comment]
同样的inputtext就没有问题
![image](https://github.com/baidu/amis/assets/11575908/f89b32cd-2ec3-43c5-bb27-763b1a34a5fb)

**Comment by 2betop** [comment]
可以先用这个来处理

```
{
        "type": "json-schema",
        "name": "value",
        "label": "字段值",
        "schema": {
          "type": "object",
          "properties": {}
        }
      }
```

参考：https://aisuda.baidu-int.com/amis/zh-CN/components/form/json-schema

**Comment by 2betop** [comment]
等 #7094 合入后，可以通过 `autoParseJSON` 属性来关闭此功能
