### ISSUE TITLE
office-view 表格循环在文档中间，显示时，循环结果在底部

### ISSUE THREAD

**Issue by taoyao-code** [baidu/amis#7097]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：
显示：
![44991686103115_ pic](https://github.com/baidu/amis/assets/38855041/e437b0a2-2be5-40b9-9883-4a94fdd4f1a7)

文档：
![45001686103144_ pic](https://github.com/baidu/amis/assets/38855041/b8014c4b-16f4-469e-a7ee-ecffac8a0b7a)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
最好发文件，大概是因为标签不完整，最好是先复制到代码编辑器里再粘贴进去

**Comment by taoyao-code** [comment]
> 最好发文件，大概是因为标签不完整，最好是先复制到代码编辑器里再粘贴进去

<img width="870" alt="image" src="https://github.com/baidu/amis/assets/38855041/8bd7ccfb-0bd6-4bfc-8ee2-d1c5d544c4b9">
上图为页面显示。

<img width="901" alt="image" src="https://github.com/baidu/amis/assets/38855041/6b720f5a-f289-4f7f-b340-77e1e231bf76">

这个是文档

```json
{
  "type": "page",
  "body": [
    {
      "type": "form",
      "title": null,
      "mode": "inline",
      "initApi": "/getData/520",
      "wrapWithPanel": false,
      "body": [
        {
          "type": "input-text",
          "name": "name",
          "value": "amis",
          "label": "姓名",
          "id": "u:2049883129b3"
        },
        {
          "type": "input-email",
          "name": "email",
          "label": "邮箱",
          "id": "u:7a408c2c4257"
        },
        {
          "type": "input-text",
          "name": "test",
          "label": "手机号",
          "id": "u:92143a19e0d5"
        },
        {
          "type": "office-viewer",
          "id": "office-viewer",
          "src": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "wordOptions": {
            "enableVar": true,
            "padding": "8px"
          }
        }
      ],
      "id": "u:acf8093291af"
    }
  ],
  "initApi": "/getData/130",
  "id": "u:85fae4f636fe"
}

```

xxxxxxxx 是文件URL

**Comment by nwind** [comment]
Duplicate of #7337

**Comment by nwind** [comment]
fixed in #7376
