### ISSUE TITLE
Select限制标签的最大展示数量后，超出数量的部分没有收纳到 Popover 中

### ISSUE THREAD

**Issue by huangyedie** [baidu/amis#7099]
#### 描述问题：

Select限制标签的最大展示数量后，超出数量的部分没有收纳到 Popover 中

#### 截图或视频：
文档中提供的是收纳到了Popover ，实际没用收纳。麻烦作者紧急处理一下,着急上线使用

![0e6dcca140d0344873536408ee9a5743](https://github.com/baidu/amis/assets/51399090/b7bd40a4-8123-4804-b619-2cee1c10a57c)
#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.1.1
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
							"label": "label",
							"type": "select",
							"name": "code",
							"multiple": true,
							"selectMode": "tree",
							"maxTagCount":50,
							"searchable": true,
							"delimiter": "/",
							"source": "源",
							"required": true
						}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by huangyedie** [comment]
虽然是隐藏了。但是鼠标放在上面没用弹出Popover

**Comment by 2betop** [comment]
jssdk 里面确实有问题，npm 版本正常。用 npm 包里面的 css 文件应该能快速解决问题，或者等下次发版本
