### ISSUE TITLE
crud的单条操作可以携带页面的其他表单的数据给接口吗

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#710]
![image](https://user-images.githubusercontent.com/64950961/85038100-c676e180-b1b8-11ea-95c4-a7066df70a77.png)

**Comment by RickCole21** [comment]
`表单name.表单项name`

**Comment by tanmengfei** [comment]
![image](https://user-images.githubusercontent.com/64950961/85092226-d96ecd80-b21b-11ea-9992-29936de61650.png)
![image](https://user-images.githubusercontent.com/64950961/85092245-e25f9f00-b21b-11ea-8e3f-9d455b29c396.png)
![image](https://user-images.githubusercontent.com/64950961/85092277-f0adbb00-b21b-11ea-8c26-4afdfafd50e6.png)
还是不行呢，crud单条操作我是打开的dialog，methd是crud本身的字段就能显示，select里边的就不能显示

**Comment by tanmengfei** [comment]
大佬们，求解决下~~

**Comment by nwind** [comment]
数据放 page 的 data 里，这样都能拿到和修改
