### ISSUE TITLE
0.11-0.15的包我都试了一遍 编译报错了

### ISSUE THREAD

**Issue by xinghe94** [baidu/amis#711]
![image](https://user-images.githubusercontent.com/15528239/85090865-b7c01700-b218-11ea-9f1c-6645aebd614a.png)
求助 ts版本是最新的

**Comment by 2betop** [comment]
试试 1.0.14?

**Comment by xinghe94** [comment]
![image](https://user-images.githubusercontent.com/15528239/85091238-9ad81380-b219-11ea-9c29-082bee3836a4.png)

0.14我也加了 我前些天用的0.11 一直没有动那个包 昨天准备上线 打包编译报错了 我更新了包几个版本都试了 还是这个问题 我都开始怀疑我的代码 但是这明明就是包里面的问题呀 现在本地编译都报错了 但是项目是能跑起来的
> 试试 1.0.14?

**Comment by 2betop** [comment]
看看 @types/React 相关是不是有变动，按理这个方法是有的，除非 React 相关的 ts 类型文件丢失。

**Comment by 2betop** [comment]
我觉得你还是用 vscode 点进去看看吧，根据错误信息分析一下。

**Comment by xinghe94** [comment]
> 看看 @types/React 相关是不是有变动，按理这个方法是有的，除非 React 相关的 ts 类型文件丢失。

![image](https://user-images.githubusercontent.com/15528239/85091591-54cf7f80-b21a-11ea-8cc5-226266f8511e.png)
![image](https://user-images.githubusercontent.com/15528239/85091638-7df01000-b21a-11ea-93e9-b1c823cbbce2.png)
我看了下组件l里的props是有的 react版本是这个

**Comment by 2betop** [comment]
看你的 vscode 并没有报错，应该是编译配置哪有问题？

**Comment by xinghe94** [comment]
> 看你的 vscode 并没有报错，应该是编译配置哪有问题？
![image](https://user-images.githubusercontent.com/15528239/85091971-4766c500-b21b-11ea-8f83-755082290fb2.png)
我昨天还加了skiplibcheck 你看下我编译配置有不一样的吗

**Comment by 2betop** [comment]
不知道加个这个是否有用
```
"typeRoots": ["./node_modules/@types"]
```

**Comment by xinghe94** [comment]
> 不知道加个这个是否有用
> 
> ```
> "typeRoots": ["./node_modules/@types"]
> ```

刚刚试了这个命令还是不管用 我先自查一下代码吧

**Comment by 2betop** [comment]
这不是命令是 tsconfig.json 里面的 compilerOptions 里面的配置

**Comment by xinghe94** [comment]
> 这不是命令是 tsconfig.json 里面的 compilerOptions 里面的配置

终于找到根源了 我代码里想扩展一下你们的mapping 这样去引用之后就报了一大堆包里组件的错误 不知道为啥
![image](https://user-images.githubusercontent.com/15528239/85101433-fbc11500-b234-11ea-99e4-3a329ea00432.png)
我注释掉就好了

**Comment by 2betop** [comment]
要 import lib 里面的

**Comment by xinghe94** [comment]
> 要 import lib 里面的

好的 谢啦
