### ISSUE TITLE
发送get请求在？后边拼接参数的时候，该怎么获取sessionStorage里边的值呢

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#712]

**Comment by 2betop** [comment]
不支持，发送适配器里面处理一下？

**Comment by tanmengfei** [comment]
好的

**Comment by tanmengfei** [comment]
我是想在crud的用来获取列表数据的 api中想携带sessionStorage的用户信息到后端，如果改成post的话，page和perpage好解决，查询参数该怎么带过去呢

**Comment by 2betop** [comment]
你何不直接写到 cookie 里面？这样请求都是自动携带的。

**Comment by tanmengfei** [comment]
这边接入的是统一登录，所以就写在里边了，我在requestAdaptor适配器里边处理了下，谢啦，顺便我那个crud里边用body里边其他表单数据的问题是不是不支持呀

**Comment by 2betop** [comment]
只能取自己作用域的东西，如果不在一个作用域，需要利用 amis 的同步机制，同步数据过来

**Comment by tanmengfei** [comment]
同步机制官方文档里有给嘛

**Comment by tanmengfei** [comment]
我看如果form的target是crud的话，是把表单数据带到查询条件里边去

**Comment by nwind** [comment]
新版已经有了 https://baidu.gitee.io/amis/zh-CN/docs/concepts/data-mapping#namespace
