### ISSUE TITLE
jumpTo的interface定义和文档里的不一致

### ISSUE THREAD

**Issue by chareice** [baidu/amis#713]
https://github.com/baidu/amis/blob/50ce54192030de232aebce3a7406353928a46b89/src/factory.tsx#L155

文档里写的是：
<img width="899" alt="image" src="https://user-images.githubusercontent.com/1624785/85189496-303eda80-b2e2-11ea-8b09-6e79bf30fc1d.png">

**Comment by 2betop** [comment]
已经更新了
