### ISSUE TITLE
CRUD全量导出

### ISSUE THREAD

**Issue by Mengleijin** [baidu/amis#7137]
#### 实现场景：
![image](https://github.com/baidu/amis/assets/28032070/3da68b4b-3aa0-4e65-97ab-84d161fa5d62)

左侧一个表单，右侧一个CRUD组件，
1）请问，使用CRUD API全量导出，接口怎样才能带上过滤参数国家和城市啊？
2）试了另外一种方案是可以的，表单拖进来一个按钮，按钮绑定事件，点击跳转链接

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by lhtuling** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E5%A4%8D%E6%9D%82%E9%85%8D%E7%BD%AE 直接自己写配置api发送的data
