### ISSUE TITLE
这个有外部链接嘛？install在项目中，首页加载特别慢

### ISSUE THREAD

**Issue by TONGTONY163** [baidu/amis#7146]
#### 描述问题：
我在vue3项目中引入的，使用yarn add amis安装的，但是打包后首页加载时这个包占了3MB多，访问太慢了，有啥好的解决办法吗？

**Comment by nwind** [comment]
可以用 unpkg.com，参考 https://github.com/aisuda/amis-admin/blob/master/index.html，但不推荐，这种免费服务随时可能挂掉
