### ISSUE TITLE
1.0.14 版本 TreeSelect 渲染器存在一些小问题

### ISSUE THREAD

**Issue by CareyToboo** [baidu/amis#715]
1.0.14 版本更新后 `TreeSelect` 与原先版本比较存在几个问题，我看源码这块代码改动挺明显的。

- 配置 ` clearable: true` 没有出现 “x” 按钮  
- 配置 `searchable: true` 选择内容后 placeholder 不消失
- 配置 icon 字段后，会出现两个图标------我不知道是否是，故意这样设计的。
- 配置  icon 后，图标偏上了。
- 当动态改动 options 的 `disabled:true/false` 属性，选项会有小抖动。这个问题是 `Tree-item-icons` 根据 disabled 动态添加删除引起的。
![image](https://user-images.githubusercontent.com/15522313/85198713-78c7b980-b31d-11ea-8f85-ebd267445021.png)

我看官网文档页面上只存在部分问题。但是我下载的 amis 1.0.14  包里面这些问题都存在。
> 是否可以在[官网](https://baidu.github.io/amis/docs/intro?page=1)某个地方标注下，官网当前使用的`amis npm`包的版本？

这样遇到问题也比较好定位。现在完全不清楚，官网使用的` amis npm`包的版本与 github 源码对应的关系。随着对 amis 深入使用，amis 版本升级后，有点分不清是由自己代码改动产生的问题，还是 amis 升级产生的问题。 

`TreeSelect` 这些小问题，目前通过简单的 hack 方式，覆盖样式解决了一些。

#### `TreeSelect` JSON 配置
```
{
    "type": "page",
    "body": {
        "title": "",
        "type": "form",
        "mode": "horizontal",
        "autoFocus": false,
        "controls": [
            {
                "type": "tree-select",
                "name": "tree",
                "label": "Tree",
                "clearable": true,
                "searchable": true,
                "options": [
                    {
                        "label": "Folder A",
                        "value": 1,
                        "children": [
                            {
                                "label": "file A",
                                "icon": "fa fa-code",
                                "value": 2
                            },
                            {
                                "label": "file B",
                                "value": 3
                            }
                        ]
                    },
                    {
                        "label": "file C",
                        "value": 4
                    },
                    {
                        "label": "file D",
                        "value": 5
                    }
                ]
            }
        ],
        "submitText": null,
        "actions": []
    }
}
```

![image](https://user-images.githubusercontent.com/15522313/85198521-dfe46e80-b31b-11ea-9bc0-e2a6e7c9017c.png)

**Comment by plenjoy** [comment]
- 配置 icon 字段后，会出现两个图标------我不知道是否是，故意这样设计的。
- 配置 icon 后，图标偏上了。

也遇到了这样的问题，只能把图标隐藏掉。

**Comment by nwind** [comment]
看起来是都修了
