### ISSUE TITLE
接口是否可以做统一的异常处理，比如接口401

### ISSUE THREAD

**Issue by fjl724619679** [baidu/amis#7151]
#### 实现场景：
登录超时时，后端接口返回状态401，这时没法用接收适配器处理，因为在接收适配器之前就报错了

#### 存在的问题：
登录超时时，后端接口返回状态401，这时没法用接收适配器处理，因为在接收适配器之前就报错了

#### 当前方案：

```
code here...
```

**Comment by 2betop** [comment]
你可以自己接管 env.fetcher 的实现

**Comment by fjl724619679** [comment]
> 你可以自己接管 env.fetcher 的实现

感谢你的解答！接管env.fetcher要怎么实现，可不可以稍微详细说一下，我没有头绪

**Comment by fjl724619679** [comment]
> 你可以自己接管 env.fetcher 的实现

已经找到了，非常感谢！
