### ISSUE TITLE
二级弹出会出现两层的bug

### ISSUE THREAD

**Issue by huangyedie** [baidu/amis#7153]
#### 描述问题：
如图,二级弹窗会多出一个标题栏。
但是这个bug，我按一下F12或者拖动一下整个浏览器，多出的部分会消失，也试了其他浏览器,也是一样的。

#### 截图或视频：

![dd49e8444b564c7aea921d64c5938b62](https://github.com/baidu/amis/assets/51399090/967b2a2e-48d2-4c28-9bd1-e78638dd4375)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.1.1。
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
列表->一级弹窗列表->二级弹窗

**Comment by 2betop** [comment]
可有能复现的 schema？

**Comment by huangyedie** [comment]
> 可有能复现的 schema？

代码太多了。还有一些api请求。我从文档上面是没有复现，可能文档编辑器不是最新的或者哪里有问题。
您看您能自己随便写一个列表，里面一级弹窗也是列表，二级弹窗也是列表，在二级弹窗的时候就出现我反应的问题了

**Comment by huangyedie** [comment]
从我的图片中您应该能看出我的schema 结构

**Comment by 2betop** [comment]
<img width="1160" alt="image" src="https://github.com/baidu/amis/assets/2698393/e9cd28c1-04f2-4142-b3e6-087585afcbc2">

复现不了，确定你那边是最新版本？

**Comment by huangyedie** [comment]
你只用了一级弹窗吗？

**Comment by 2betop** [comment]
一级弹窗，2 级弹窗都可以

**Comment by 2betop** [comment]
https://github.com/baidu/amis/assets/2698393/e27f8593-3ddf-4ce7-b3b2-edba40cfa128

**Comment by huangyedie** [comment]
一级弹窗在包含一个弹窗

> 一级弹窗，2 级弹窗都可以

好的，版本是用的3.1.1的sdk，我再重新写一个试试把、

**Comment by huangyedie** [comment]
{
	"type": "page",
	"body": [{
		"type": "crud",
		"syncLocation": false,
		"data": [{
			"id": 1,
			"engine": "测试数据1"
		}, {
			"id": 2,
			"engine": "测试数据2"
		}],
		"columns": [{
				"name": "id",
				"label": "ID",
				"id": "u:06fdd9d5555a"
			},
			{
				"name": "engine",
				"label": "Rendering engine",
				"id": "u:74b43482587d"
			},
			{
				"type": "operation",
				"label": "操作",
				"buttons": [{
					"label": "详情",
					"type": "button",
					"level": "link",
					"actionType": "dialog",
					"dialog": {
						"title": "查看详情",
						"body": {
							"type": "crud",
							"syncLocation": false,
							"columns": [{
									"name": "id",
									"label": "ID",
									"id": "u:06fdd9d5555a"
								},
								{
									"name": "browser",
									"label": "Browser",
									"id": "u:8a225d2f7dcc"
								},
								{
									"type": "operation",
									"label": "操作",
									"buttons": [{
										"label": "详情",
										"type": "button",
										"level": "link",
										"actionType": "dialog",
										"dialog": {
											"title": "查看详情",
											"body": [{
												"type": "crud",
												"api": "https://aisuda.bce.baidu.com/amis/api/sample?waitSeconds=1&orderBy=id&orderDir=asc&page=1&perPage=15",
												"headerToolbar": [
													"reload"
												],
												"columns": [{
														"name": "id",
														"label": "ID"
													}
												]
											}]
										},
										"id": "u:f5e59197816f"
									}],
									"id": "u:980b43ecdadf"
								}
							],
							"id": "u:32ef4dec3388"
						}
					},
					"id": "u:f5e59197816f"
				}],
				"id": "u:980b43ecdadf"
			}
		],
		"id": "u:32ef4dec3388"
	}],
	"id": "u:a6e4c455efc9"
}

**Comment by 2betop** [comment]
复现了，感谢
