### ISSUE TITLE
amis editor: Cannot add property type, object is not extensible

### ISSUE THREAD

**Issue by Jarod-Xie** [baidu/amis#7161]
#### 描述问题：

amis editor 最新代码拉下来后本地运行报错

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/27668637/8c61f464-1ba3-4527-86e6-5689f2841c8a)
![image](https://github.com/baidu/amis/assets/27668637/80ee5dd6-4411-4505-9f36-efb5bea4aef0)

#### 如何复现（请务必完整填写下面内容）：

拉下来的代码截止到commit：f75342505e7589353aa4ce5bcce8a74c736c3b5e，
运行 npm i
运行 npm run dev
打开本地地址，页面空白，控制台报错

**Comment by 2betop** [comment]
感谢反馈已修改 amis-editor-demo 仓库 https://github.com/aisuda/amis-editor-demo/commit/083e83d66ec99c656835d5d7065a813795cd160e 最新版本运行没有报错
