### ISSUE TITLE
模版字符串冲突

### ISSUE THREAD

**Issue by 17671881483** [baidu/amis#7168]
#### 描述问题：

Adaptor 中「amis」变量获取方式与「模版字符串」冲突

#### 截图或视频：

![1FDB9171-E4FE-461A-937E-088E9AEE4A56](https://github.com/baidu/amis/assets/61647474/a1d6ea3b-5571-4f4b-b450-cb7a550bb5d3)

#### 如何复现（请务必完整填写下面内容）：

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.0.0

**Comment by Jarod-Xie** [comment]
我也遇到了，不光是跟模板字符串冲突，只要在接口的返回适配器中编辑代码时，任意字符串中使用${xxx}，就会出现这种问题。
![动画](https://github.com/baidu/amis/assets/27668637/0d3476d7-4017-419a-b398-f6943c86f5bb)

**Comment by 2betop** [comment]
已修复，等待下一个版本 https://github.com/baidu/amis/pull/7310
