### ISSUE TITLE
Form 是否可以执行提交表单发送请求同时调用target，把参数给另一个表单呢？

### ISSUE THREAD

**Issue by cool14521** [baidu/amis#718]
Form 是否可以执行提交表单发送请求同时调用target，把参数给另一个表单呢？

https://baidu.github.io/amis/docs/renderers/Form/Form

如文档，也就是希望配置target后，默认的api继续发送。

**Comment by 2betop** [comment]
换成配置 reload: "xxx" 如果要传递数据那就是 reload: "xxx?a=${a}&b=${b}"
