### ISSUE TITLE
分页组件增强

### ISSUE THREAD

**Issue by wh88725** [baidu/amis#7196]
#### 是否关联于某个问题吗：
数据量大或者无法得到数据总数的场景下，使用“上一页、下一页”这种分页组件简易模式。
在这种模式下，后端会使用类似 id > “lastid” limit perPage 的游标分页方法。目前分页组件向后端传递的page、perPage参数，无法实现 “回退到上一页” 这样的功能。

#### 预期的解决方案：
分页组件简易模式下，能提供标识是 “点击上一页” 还是 “点击下一页” 的参数，或者事件。

#### 其他解决方案：
如果是我使用姿势不对也请告知，感谢

**Comment by 2betop** [comment]
可以获取当前列表数据比如 `${items|last|pick:id}` 或者 `${items|first|pick:id}`

**Comment by wh88725** [comment]
当前列表数据的第一条和最后一条是可以拿到的，但是因为不知道是下一页，还是上一页，所以后端无法确定排序和筛选条件。
比如：按照id升序，下一页应该是 order by id where id>lastid limit perPage，前一页应该是 order by id desc where id < firstid limit perPage
