### ISSUE TITLE
CRUD,pickerMode,affixRow 功能异常。

### ISSUE THREAD

**Issue by zhaolengxin** [baidu/amis#7198]
#### 描述问题：

当CRUD使用pickerMode时,每点击一次行，affixRow,colspan 都会一直增长。
如果使用冻结行，affixRow相应行没有冻结

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk` 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.0.0，beta版本也会出现
3. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "page",
  "body": {
    "type": "crud",
    "data": {
      "items": [
        {
          "ORDER_NO": "XXXX",
          "ITEM_SEQ": 1,
          "YEAR_CODE": null,
          "MONTH_CODE": null,
          "BMMC": null,
          "GZBH": null,
          "XM": "XXX",
          "IN_DUTY": 0,
          "OUT_DUTY": 0,
          "JBGZ": 0,
          "GWGZ": 0,
          "TSGB": 0,
          "PSJB": 0,
          "PSJBF": 0,
          "ZMJB": 0,
          "ZMJBF": 0,
          "FDJB": 0,
          "FDJBF": 0,
          "ZHJJ": 0,
          "GLJJ": 0,
          "JXGZ": 0,
          "GWBT": 0,
          "YBBT": 0,
          "ZFBT": 0,
          "JJ": 0,
          "BFGZ": 0,
          "YFGZ": 0,
          "SBF": 0,
          "GAJJ": 0,
          "ZFGJJ": 118,
          "KKJE": 0,
          "SDF": 0,
          "FKJE": 0,
          "GRSDS": 0,
          "YKGZ": 0,
          "SFGZ": 0,
          "GZBZ": null,
          "SIGNER": null,
          "EDIT_USER": "00000",
          "EDIT_TIME": "2023-06-15T16:50:12",
          "TWO_DEPT_NAME": "XXXX",
          "THREE_DEPT_NAME": null,
          "YX": 0,
          "XJGB": 0,
          "CCBT": 0,
          "BJGZ": 0,
          "GW": 0,
          "BMF": 0,
          "FOUR_DEPT_NAME": null,
          "JNJT": 0,
          "QT": 0,
          "FD_BT": 0,
          "GH": "XXXX",
          "ZCSB": 0,
          "QQ": 168,
          "PSJBGZ": 0,
          "ZMJBGZ": 0,
          "FDJBGZ": 0,
          "ZHJ": 0,
          "GLJ": 0,
          "YB": 0,
          "FB": 0,
          "BF": 0,
          "YF": 0,
          "SB": 221.81,
          "KK": 0,
          "SD": 0,
          "GS": 0,
          "SF": -339.81,
          "JL": 0,
          "REMARK": null,
          "ONE_DEPT_NAME": "XXXX",
          "BJ": null,
          "IC": 0,
          "LQFS": null,
          "ATT_ITEM_SEQ": null,
          "ZW": "职员",
          "ZCQ": 168,
          "QQJ": 0,
          "QQGZ": 7475,
          "DSJT": 0,
          "ZWJT": 0,
          "TXF": 0,
          "JJBCJ": 0,
          "YHZH": "XXXX",
          "FDATE": "2023-07",
          "TX": 0,
          "NJ": 0,
          "DEPT_ID": "XXXX",
          "ATTACH_NAME": null,
          "FILE_PATH": null,
          "ROWSEQ": 1
        }
      ]
    },    
    "syncLocation": false,
    "columns": [
      {
        "type": "text",
        "name": "ITEM_SEQ",
        "label": "序号",
        "fixed": "left"
      },
      {
        "type": "text",
        "name": "FDATE",
        "label": "支付年月",
        "fixed": "left",
        "width": 80
      },
      {
        "type": "text",
        "name": "DEPT_ID",
        "label": "部门ID",
        "fixed": "left",
        "width": 70
      },
      {
        "type": "text",
        "name": "ONE_DEPT_NAME",
        "label": "一级部门",
        "fixed": "left",
        "width": 100
      },
      {
        "type": "text",
        "name": "TWO_DEPT_NAME",
        "label": "二级部门",
        "fixed": "left",
        "width": 100
      },
      {
        "type": "text",
        "name": "THREE_DEPT_NAME",
        "label": "三级部门",
        "fixed": "left",
        "width": 100
      },
      {
        "type": "text",
        "name": "FOUR_DEPT_NAME",
        "label": "四级部门",
        "fixed": "left",
        "width": 100
      },
      {
        "type": "text",
        "name": "GH",
        "label": "工号",
        "fixed": "left",
        "width": 80
      },
      {
        "type": "text",
        "name": "XM",
        "label": "姓名",
        "fixed": "left",
        "width": 80
      },
      {
        "type": "text",
        "name": "ZW",
        "label": "职位",
        "fixed": "left",
        "width": 80
      },
      {
        "type": "text",
        "name": "ZCQ",
        "label": "应出勤",
        "width": 70
      },
      {
        "type": "text",
        "name": "ZCSB",
        "label": "实际出勤",
        "width": 70
      },
      {
        "type": "text",
        "name": "YX",
        "label": "有薪假时数",
        "width": 70
      },
      {
        "type": "text",
        "name": "NJ",
        "label": "年假",
        "width": 70
      },
      {
        "type": "text",
        "name": "QQ",
        "label": "实际缺勤",
        "width": 70
      },
      {
        "type": "text",
        "name": "TX",
        "label": "调休",
        "width": 70
      },
      {
        "type": "text",
        "name": "JBGZ",
        "label": "基本工资",
        "width": 70
      },
      {
        "type": "text",
        "name": "GWGZ",
        "label": "岗位工资",
        "width": 70
      },
      {
        "type": "text",
        "name": "JXGZ",
        "label": "绩效奖励",
        "width": 70
      },
      {
        "type": "text",
        "name": "BMF",
        "label": "保密费",
        "width": 70
      },
      {
        "type": "text",
        "name": "TSGB",
        "label": "特殊岗补",
        "width": 70
      },
      {
        "type": "text",
        "name": "JL",
        "label": "奖励",
        "width": 70
      },
      {
        "type": "text",
        "name": "QT",
        "label": "绩效汇算退补",
        "width": 90
      },
      {
        "type": "text",
        "name": "TXF",
        "label": "通讯费",
        "width": 70
      },
      {
        "type": "text",
        "name": "YB",
        "label": "夜补",
        "width": 70
      },
      {
        "type": "text",
        "name": "DSJT",
        "label": "董事津贴",
        "width": 70
      },
      {
        "type": "text",
        "name": "ZWJT",
        "label": "职务津贴",
        "width": 70
      },
      {
        "type": "text",
        "name": "GWBT",
        "label": "高温补贴",
        "width": 70
      },
      {
        "type": "text",
        "name": "CCBT",
        "label": "出差补贴",
        "width": 70
      },
      {
        "type": "text",
        "name": "FB",
        "label": "房补",
        "width": 70
      },
      {
        "type": "text",
        "name": "BJGZ",
        "label": "病假工资",
        "width": 70
      },
      {
        "type": "text",
        "name": "BF",
        "label": "补发",
        "width": 70
      },
      {
        "type": "text",
        "name": "QQJ",
        "label": "全勤奖",
        "width": 70
      },
      {
        "type": "text",
        "name": "QQGZ",
        "label": "缺勤工资",
        "width": 70
      },
      {
        "type": "text",
        "name": "YF",
        "label": "应发",
        "width": 70
      },
      {
        "type": "text",
        "name": "SB",
        "label": "社保",
        "width": 70
      },
      {
        "type": "text",
        "name": "GAJJ",
        "label": "关爱基金",
        "width": 70
      },
      {
        "type": "text",
        "name": "ZFGJJ",
        "label": "住房公积金",
        "width": 80
      },
      {
        "type": "text",
        "name": "KK",
        "label": "扣款",
        "width": 70
      },
      {
        "type": "text",
        "name": "SD",
        "label": "水电",
        "width": 70
      },
      {
        "type": "text",
        "name": "GS",
        "label": "个税",
        "width": 70
      },
      {
        "type": "text",
        "name": "JJBCJ",
        "label": "经济补偿金",
        "width": 80
      },
      {
        "type": "text",
        "name": "IC",
        "label": "IC卡退款",
        "width": 70
      },
      {
        "type": "text",
        "name": "SF",
        "label": "实发",
        "width": 70
      },
      {
        "type": "text",
        "name": "YHZH",
        "label": "银行账号",
        "width": 120
      },
      {
        "type": "text",
        "name": "REMARK",
        "label": "备注",
        "width": 120
      },
      {
        "type": "link",
        "name": "FILE_PATH",
        "label": "附件",
        "body": "$ATTACH_NAME"
      }
    ],
    "affixRow": [
      {
        "type": "text",
        "text": "总计"
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": "168"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "168"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "7475"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "221.81"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "118"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "0"
      },
      {
        "type": "text",
        "text": "-339.81"
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": ""
      },
      {
        "type": "text",
        "text": ""
      }
    ],
    "pickerMode": true,
    "multiple": true
  }
}

4. 操作步骤
不停的点击选中行，下面合计列会一直增大。冻结列滚动也会出现异常，

**Comment by 2betop** [comment]
新版本已修复
