### ISSUE TITLE
Action 行为按钮有操作前确认confirmText 但是不能设置这个提示的标题

### ISSUE THREAD

**Issue by yshujun** [baidu/amis#7199]
#### 是否关联于某个问题吗：
Action 行为按钮有操作前确认confirmText， 它可以设置内容但是不能设置title，title是”系统消息“

#### 预期的解决方案：
希望可以修改二次确认弹窗的标题

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
![image](https://github.com/baidu/amis/assets/48676074/fc4e5c97-ace0-4c37-b6e3-9b0cbae27a62)

**Comment by 2betop** [comment]
新版支持配置 confirmTitle, 请升级

**Comment by yshujun** [comment]
ok
