### ISSUE TITLE
按钮事件进行二次确认，弹窗标题无法修改

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#7200]
#### 描述问题：

现在按钮开启二次确认后只能自定义弹窗的内容，但是弹窗的标题是写死的【系统消息】，希望可以增加一个confirmTitle属性，自定义弹窗的标题。看了一下源码，env.confirm()方法是支持两个参数的，第二个参数是title，所以只要在Action组件增加一个confirmTitle属性，并传给env.confirm方法即可

#### 截图或视频：

![图片](https://github.com/baidu/amis/assets/45064164/48a377e6-4c52-44ce-a491-0a50e2edf636)
![图片](https://github.com/baidu/amis/assets/45064164/c35bf4af-0700-49ab-9f79-55f654cb816e)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "id": "u:341c288ba649",
  "body": [
    {
      "type": "button",
      "label": "二次确认",
      "onEvent": {
        "click": {
          "actions": [
          ]
        }
      },
      "id": "u:138ed4f95113",
      "level": "primary",
      "confirmText": "这是二次确认内容"
    }
  ]
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
有道理，下个版本支持
