### ISSUE TITLE
两个tab里边配置了两个相同的crud，只不过这两个crudde api传参不同，这两个crud的能不互相影响吗

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#721]
![image](https://user-images.githubusercontent.com/64950961/85369722-3346fe80-b560-11ea-95c0-a7b5bf2b09ac.png)
比如查询条件，我在左边的tab里边输入查询条件查询以后，点开右边的也会存在该查询条件，并且重置按钮失效了
![image](https://user-images.githubusercontent.com/64950961/85369841-68535100-b560-11ea-9b8c-851248921f91.png)
pei配置了"unmountOnExit":true,也不管用

**Comment by RickCole21** [comment]
也许crud是开启了地址栏参数同步，关掉试试

**Comment by xiusin** [comment]
借楼问个问题： tab有删除回调吗？ 就是点叉号提醒一下啥的。 现在点击都没，误点的时候还挺痛苦的

**Comment by RickCole21** [comment]
@xiusin 单开一个issue吧，这个先关了
