### ISSUE TITLE
遍历渲染InputText怎么实现

### ISSUE THREAD

**Issue by sym134** [baidu/amis#7211]
#### 实现场景：
数据结构：
```
{
"lists":{
"key1":111,
"key2":222
…… // 数量不确定
}
}
```
key的数量不确定，所以希望自动遍历渲染成input组件

#### 存在的问题：
可用遍历，但name不知道如何处理

#### 当前方案：

```
{
  "type": "each",
  "name": "lists",
  "items": {
    "type": "input-text",
    "size": "lg",
    "name": "???", // name不知道如何处理？
    "label": "$key"
  },
  "id": "u:9b32fd72f514"
}
```

**Comment by allenve** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/combo
可以试试combo组件

**Comment by 2betop** [comment]
可以用 input-kv https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-kv

**Comment by sym134** [comment]
> 可以用 input-kv https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-kv

但是name这么解决

**Comment by sym134** [comment]
> 可以用 input-kv https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-kv

这个页面展示有点糟糕

**Comment by 2betop** [comment]
?? 你是指 form 的 debug 功能？

**Comment by 2betop** [comment]
缺少反馈先关了，有问题再开
