### ISSUE TITLE
分页组件 疑问

### ISSUE THREAD

**Issue by Ladtor** [baidu/amis#7215]
#### 实现场景：
1. 我想要实现一个带分页的表格，但是Table组件没有分页示例，且分页组件缺少必要的事件表，因此我采用CRUD组件
2. 我需要监听 表格查询返回的 结果，但是CRUD没有提供该事件，因此，我采用service<CRUD>+initFetched事件
3. 采用service包裹之后，CRUD组件的分页不显示

#### 存在的问题：
CRUD 组件用service 套一层之后，就无法展示分页了，同时分页组件的文档过于简陋，缺少事件表

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
{
  "initFetch": true,
  "api": "get:/api/list.json",
  "type": "service",
  "body": {
    "columns": [
      {
        "name": "userId",
        "label": "UserId"
      }
    ],
    "footerToolbar": [
      "pagination"
    ],
    "type": "crud"
  }
}
```

**Comment by black-lattice** [comment]
我这边用CRUD，分页也出不来，数据返回的也有total，api用的post

**Comment by black-lattice** [comment]
> 我这边用CRUD，分页也出不来，数据返回的也有total，api用的post

原来API需要返回axios返回的所有的值，包括请求头，响应头。之前一直都在相应拦截器里过滤了，醉了，感觉需要文档提示一下

**Comment by 2betop** [comment]
可以用 service + paginationWrapper + table 实现，还有问题请 reOpen
