### ISSUE TITLE
amis源码，在md文档写到了两个路由地址，想咨询一下是在哪个文件下配置

### ISSUE THREAD

**Issue by xiongyachuan** [baidu/amis#7216]
![image](https://github.com/baidu/amis/assets/91184124/5178f63b-449f-48ca-9e18-a231c1e7c9b1)
由于开发编辑器，自定义了几个组件，需要配置一下路由，地址栏需要携带参数，需要在开发编辑器的后面拼接几个参数，能否指点指点

**Comment by xiongyachuan** [comment]
拼接到地址后面，不使用？问号拼接

**Comment by 2betop** [comment]
看不明白是什么意思，看起来跟 amis 没多少关系，先关了
