### ISSUE TITLE
拉最新编辑器amis-editor，运行调试直接报TS2345 类型参数...不可分配给类型参数错误

### ISSUE THREAD

**Issue by yyh1998** [baidu/amis#7223]
![image](https://github.com/baidu/amis/assets/44611858/02e7267e-cfdb-43cf-bd33-d35e30a4dd5d)

ERROR in ./src/component/AMISRenderer.tsx 213:20-34
[tsl] ERROR in C:\Users\DELL\Desktop\amis-editor-demo-master\src\component\AMISRenderer.tsx(213,21)
      TS2345: Argument of type 'typeof SchemaRenderer' is not assignable to parameter of type 'ComponentType<SchemaRendererProps>'.
  Type 'typeof SchemaRenderer' is not assignable to type 'ComponentClass<SchemaRendererProps, any>'.
    Types of property 'contextType' are incompatible.
      Type 'React.Context<any> | undefined' is not assignable to type 'import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\react-router-dom\\node_modules\\@types\\react\\ts5.0\\index").Context<any> | undefined'.
        Type 'React.Context<any>' is not assignable to type 'import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\react-router-dom\\node_modules\\@types\\react\\ts5.0\\index").Context<any>'.
          The types of 'Provider.propTypes' are incompatible between these types.
            Type 'React.WeakValidationMap<React.ProviderProps<any>> | undefined' is not assignable to type 'import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\react-router-dom\\node_modules\\@types\\react\\ts5.0\\index").WeakValidationMap<import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\react-router-dom\\node_modules\\@types\\react\\ts5.0\\index").ProviderProps...'.
              Type 'React.WeakValidationMap<React.ProviderProps<any>>' is not assignable to type 'import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\react-router-dom\\node_modules\\@types\\react\\ts5.0\\index").WeakValidationMap<import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\react-router-dom\\node_modules\\@types\\react\\ts5.0\\index").ProviderProps...'.
                Types of property 'children' are incompatible.
                  Type 'React.Validator<React.ReactNode> | undefined' is not assignable to type 'import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\react-router-dom\\node_modules\\@types\\react\\ts5.0\\index").Validator<import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\react-router-dom\\node_modules\\@types\\react\\ts5.0\\index").ReactNode> | undefined'.
                    Type 'React.Validator<React.ReactNode>' is not assignable to type 'import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\prop-types\\index").Validator<import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\react-router-dom\\node_modules\\@types\\react\\ts5.0\\index").ReactNode>'.
                      Type 'React.ReactNode' is not assignable to type 'import("C:\\Users\\DELL\\Desktop\\amis-editor-demo-master\\node_modules\\@types\\react-router-dom\\node_modules\\@types\\react\\ts5.0\\index").ReactNode'.
                        Type '{}' is not assignable to type 'ReactNode'.
ERROR in ./src/route/index.tsx 13:5-11
[tsl] ERROR in C:\Users\DELL\Desktop\amis-editor-demo-master\src\route\index.tsx(13,6)
      TS2769: No overload matches this call.
  Overload 1 of 2, '(props: HashRouterProps | Readonly<HashRouterProps>): HashRouter', gave the following error.
    Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<HashRouter> & Readonly<HashRouterProps>'.
  Overload 2 of 2, '(props: HashRouterProps, context: any): HashRouter', gave the following error.
    Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<HashRouter> & Readonly<HashRouterProps>'.

**Comment by kakalata** [comment]
你好请问解决了吗

**Comment by linzhixiang** [comment]
同样的问题

**Comment by hejun200613224** [comment]
同样的问题，需要支持
