### ISSUE TITLE
mapURL的sendOn问题

### ISSUE THREAD

**Issue by 815010453** [baidu/amis#7226]
#### 实现场景：
我想要实现根据后端返回的${area}的值，通过mapURL的api，get到不同地区的geojson文件，在chart中进行渲染

#### 存在的问题：
我看官方文档中的mapURL是api类型，但配置了sendOn属性后，它似乎只会在最初的页面刷新去get，不会根据表达式的值去get

#### 当前方案：
```
let amisJSON = {
        "type": "page",
        "body": [
          {
            "type": "tpl",
            "tpl": "***",
            "name": "text",
            "text-align": "center",
            "align": "center",
          },
          {
            "type": "service",
            "api": {
              "method": "post",
              "url": "http://localhost:7861/chat",
              "data": {
                "question": "${keywords}",
                "history": []
              },
              "sendOn": "${keywords!=null}",
            },
            "body": [
              {
                "type": "grid-2d",
                "grids": [
                  {
                    "x": 1,
                    "y": 1,
                    "h": 12,
                    "w": 8,
                    "type": "service",
                    "body": {
                      "type": "chart",
                      "mapURL": {
                        "method": "get",
                        "url": "http://localhost:7861/local_map_geojson",
                        "sendOn": "${keywords!=null}",
                      },//http://localhost:7861/local_map_geojson
                      "mapName": "lyd",
                      "trackExpression": "${mapdata}",
                      "height": 600,
                      "config": {
                        "title": {
                          "text": "${year}${area}${topic}"
                        },
                        "tooltip": {
                          "trigger": "item",
                          "formatter": "{b}<br/>{c} (${unit})"
                        },
                        "visualMap": {
                          "min": '${low}',
                          "max": '${high}',
                          "text": [
                            "High",
                            "Low"
                          ],
                          "realtime": false,
                          "calculable": true,
                          "inRange": {
                            "color": [
                              "lightskyblue",
                              "yellow",
                              "orangered"
                            ]
                          }
                        },
                        "series": [
                          {
                            "name": "${year}${area}${topic}",
                            "type": "map",
                            "map": "lyd",
                            "label": {
                              "show": true
                            },
                            "data": "${mapdata || []}"
                          }
                        ]
                      }
                    }
                  },
                  {
                    "x": 10,
                    "y": 1,
                    "h": 12,
                    "w": 3,
                    "type": "container",
                    "body": [
                      {
                        "type": "search-box",
                        "name": "keywords",
                        "clearable": true,
                        "enhance": true,
                        "placeholder": "请输入问题",
                        "align": "center",
                      },
                      {
                        "type": "tpl",
                        "className": "overflow-scroll",
                        "overflow": "scroll",
                        "tpl": "<p>问题:${question}</p><p>答复:${response}</p>"
                      }
                    ]
                  },
                ]
              }

            ]
          }
        ]
      };
```

**Comment by allenve** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E8%B7%9F%E8%B8%AA%E6%95%B0%E6%8D%AE%E8%87%AA%E5%8A%A8%E5%88%B7%E6%96%B0
可以通过 trackExpression 去跟踪数据

**Comment by 815010453** [comment]
@allenve 我改成了如下格式，想通过上层接口返回的${area}去get geojson，但还是不行
"mapURL": {
                        "method": "get",
                        "url": "http://localhost:7861/local_map_geojson",
                        "data":{
                          "area": "${area}"
                        },
                        "trackExpression": "${area}"
}

**Comment by allenve** [comment]
再配合 sendOn 试试

**Comment by 815010453** [comment]
@allenve 还是不行，是因为mapURL中没有autoRefresh属性吗？
"mapURL": {
          "method": "get",
          "url": "http://localhost:7861/local_map_geojson",
          "data": {
          "area": "${area}"
          },
          "trackExpression": "${area}",
          "autoRefresh": true,
          "sendOn": "${area}"
}

**Comment by 815010453** [comment]
我把它替换成了一个chart组件，则可以自动刷新，上层接口会返回${linedataset}
{
                      "type": "chart",
                      "trackExpression": "${linedataset}",
                      "config": {
                        "legend": {
                          "formatter": "${topic}"
                        },
                        "tooltip": {
                          "trigger": "item",
                          "formatter": "{c}(${unit})"
                        },
                        "dataset": {
                          "source": "${linedataset}"
                        },
                        "xAxis": {
                          "type": "category",
                          "axisTick": {
                            "show": false
                          }
                        },
                        "yAxis": {},
                        "series": [
                          {
                            "type": "bar",
                            "seriesLayoutBy": "row"
                          }
                        ]
                      }
                    }

**Comment by 815010453** [comment]
@allenve 我把map组件改为chart则可以在${area}变动时正常刷新，估计可能是mapURL不支持自动刷新
{
                      "type": "chart",
                      "api":{
                        "method": "get",
                        "url": "http://localhost:7861/local_map_geojson",
                        "data": {
                          "area": "${area}"
                        },
                        "trackExpression": "${area}",
                        "sendOn": "${area}"
                      },
                      
                      "trackExpression": "${linedataset}",
                      "config": {
                        "legend": {
                          "formatter": "${topic}"
                        },
                        "tooltip": {
                          "trigger": "item",
                          "formatter": "{c}(${unit})"
                        },
                        "dataset": {
                          "source": "${linedataset}"
                        },
                        "xAxis": {
                          "type": "category",
                          "axisTick": {
                            "show": false
                          }
                        },
                        "yAxis": {},
                        "series": [
                          {
                            "type": "bar",
                            "seriesLayoutBy": "row"
                          }
                        ]
                      }
                    }

**Comment by 2betop** [comment]
mapUrl 目前不支持联动，只有初始的时候加载了

**Comment by 815010453** [comment]
@2betop 有没有考虑后面修复这个问题呢？

**Comment by wibetter** [comment]
@815010453 已在此提交中支持：https://github.com/baidu/amis/pull/9124/commits/7f01a34b4d6c0e3fd7707968ece9e8df5242acd0，请关注，预计下一版本生效。
