### ISSUE TITLE
日期范围偶现取不到值问题

### ISSUE THREAD

**Issue by BootRestart** [baidu/amis#7236]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/37404129/7a891b0b-c618-4352-8699-3fe1e514301d)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
请贴一下问题 schema，需要问题 schema 才能定位出问题。从描述来看不一定是组件的问题，可能是接口所在组件的上下文信息同步问题，目前无法知道是怎么个使用场景。

**Comment by 2betop** [comment]
缺少反馈，先关了，有问题再开
