### ISSUE TITLE
checkboxes的选项互斥怎么实现？

### ISSUE THREAD

**Issue by kkkjjjmmm** [baidu/amis#724]
目前checkboxes有三个选项abc，想要实现一个互斥的功能，选择a不能选择bc，选择bc不能选择a，需要怎么实现？官方文档里没有看到有什么属性能支持到这样子的需求

**Comment by 2betop** [comment]
用这个应该能实现。https://baidu.github.io/amis/linkpage/options-local

**Comment by kkkjjjmmm** [comment]
这个链接里的感觉实现不了我想要的效果，
![image](https://user-images.githubusercontent.com/21272412/86001403-6a764d80-ba41-11ea-86c3-00e2c2da7624.png)
我目前用的是复选框，如果选择了静音，之后再选择提示音和震动的话，静音这个选项的勾自动取消，同理，选择提示音和震动之后，如果再选择静音，后两个的勾就自动取消

**Comment by 2betop** [comment]
哦，是这样，如果要联动修改值，需要用到 formula  https://baidu.github.io/amis/docs/renderers/Form/Formula#formula
