### ISSUE TITLE
3.1.1版更新后 总结行有个负优化 加上总结行隐藏列不能减少到总结行得列数

### ISSUE THREAD

**Issue by yshujun** [baidu/amis#7245]
#### 描述问题：

3.1.1版更新后 总结行有个负优化 加上总结行隐藏列不能减少到总结行得列数
#### 截图或视频：

![image](https://github.com/baidu/amis/assets/48676074/db214e36-466a-4bff-bda6-277b1cea1521)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
已调整，请使用新版本

**Comment by yshujun** [comment]
ok
