### ISSUE TITLE
有a、b两个按钮，这两个按钮都可以控制同一个Drawer，这应该怎么实现

### ISSUE THREAD

**Issue by sym134** [baidu/amis#7250]
#### 实现场景：
有a、b两个按钮，这两个按钮都可以控制同一个Drawer，这应该怎么实现

**Comment by Jarod-Xie** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/definitions  可以用这个definitions ，将同一个Drawer写为一个definitions  ，两个按钮都使用这个definitions

**Comment by Hemri789** [comment]
给按钮添加自定义js事件，通过
let drawer = event.context.scoped.getComponentById("drawer_id")
获取Drawer组件的实例，
drawer_id是Drawer组件的json配置里面的id值。
