### ISSUE TITLE
Crud 总结行问题

### ISSUE THREAD

**Issue by Gentle-Tech** [baidu/amis#7251]
#### 描述问题：

使用总结行并添加批量操作菜单时，进入页面后渲染正常，切换页码（上一页下一页页码范围等）后，总结行会重复添加空白列，导致列移位

#### 截图或视频：
![WX20230624-143627](https://github.com/baidu/amis/assets/46365797/eb68e3f3-9af6-46cd-a944-7ff5a21f49de)

上图是进入页面后未切换页面的效果，展示正常

![WX20230624-143647](https://github.com/baidu/amis/assets/46365797/240c02e7-0ff8-43bc-b3ad-7db6110811e4)

上图这是切换到第三页的效果

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.0.0 往上均测试过
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
crud添加批量操作菜单，进入页面后，点击页码切换页面

**Comment by Gentle-Tech** [comment]
建议参考Layui 在列配置 统计，总结行自动在对应列下方自动统计~

**Comment by vexos-io** [comment]
我刚关了一个issue，现在想起来了，是跟你一样的问题，请相关同学关注一下吧

**Comment by 2betop** [comment]
试一下 3.2.0 应该没问题了
