### ISSUE TITLE
编辑器为什么没办法识别Calendar日历/日程

### ISSUE THREAD

**Issue by coldest7z** [baidu/amis#7252]
![image](https://github.com/baidu/amis/assets/45660758/dc7240e8-6a4b-4b8d-9800-b4e74ea09eac)

**Comment by coldest7z** [comment]
![image](https://github.com/baidu/amis/assets/45660758/3021d7fb-cc0f-4f77-9ba3-e15059de8ce8)
并且需要日程可以有点击事件，希望尽快加上

**Comment by hsm-lv** [comment]
> ![image](https://user-images.githubusercontent.com/45660758/248453198-dc7240e8-6a4b-4b8d-9800-b4e74ea09eac.png)

因为还没做可视化
