### ISSUE TITLE
inputFile选择文件校验文件类型的提示样式bug

### ISSUE THREAD

**Issue by yshujun** [baidu/amis#7257]
#### 描述问题：

inputFile选择文件校验文件类型的提示英文不会换行,而且这个提示不能修改标题和按钮内部也没有国际化处理，国际化的需求不能满足

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/48676074/f03fc617-cb34-4561-8563-465d9c0f05a6)
![image](https://github.com/baidu/amis/assets/48676074/9c384bbb-a8af-40df-821d-94b30768c7ad)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
 3.1.1

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "input-file",
        "name": "file",
        "label": "File",
        "accept": ".png,.gif,.tiff,.txt,.pps,.mdi,.csv,.ppt,.jpeg,.rtf,.7z,.xlsb,.xps,.pdf,.bmp,.docx,.doc,.zip,.rar,.xls,.jpg,.eml,.msg,.xlsx,.tif",
        "receiver": "/amis/api/upload/file"
      }
    ]
  }
}
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
accept 里面适当的添加点空格，看起来新版本无此问题

<img width="932" alt="image" src="https://github.com/baidu/amis/assets/2698393/94332f82-f5e8-4c2f-9abc-9b2bfa6fd182">

**Comment by yshujun** [comment]
加空格确实可以解决这个问题
