### ISSUE TITLE
source里不支持自定义协议调用

### ISSUE THREAD

**Issue by xinghe94** [baidu/amis#726]
![image](https://user-images.githubusercontent.com/15528239/86079621-7d316680-bac3-11ea-99ce-54dd9339659c.png)
如果像这样的协议去调用就可以成功 
`/taf:message/listMessageCategoryNames?platform=${platform}`
我看到你们的底层有做有效url的校验 可以稍微放开一点吗
![image](https://user-images.githubusercontent.com/15528239/86079812-f204a080-bac3-11ea-9c8d-a99ed4ee21ac.png)

**Comment by xinghe94** [comment]
直接用
`taf://message/listMessageCategoryNames?platform=${platform}`
这样的形式也是调用不成功的

**Comment by 2betop** [comment]
求 pr

**Comment by xinghe94** [comment]
> 求 pr

你可以就拿我上述的taf协议去调用 都没有走axios
