### ISSUE TITLE
下拉按钮，点击配置报错

### ISSUE THREAD

**Issue by songyinhai2006** [baidu/amis#7265]
#### 描述问题：

点击配置按钮console控制台报错，但是好像不影响使用

#### 截图或视频：

见截图
![image](https://github.com/baidu/amis/assets/52561802/02a1b5f9-be15-4e3d-8db6-21914a877135)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.1.1

3. 粘贴有问题的完整 `amis schema` 代码：

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
新版本无法复现，有问题再开
