### ISSUE TITLE
sdk crud中导出按钮一直转圈加载，没反应

### ISSUE THREAD

**Issue by songyinhai2006** [baidu/amis#7285]
#### 描述问题：

sdk crud中导出按钮一直转圈加载，没反应

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/52561802/0a299476-e5da-489a-8920-129b1a04565c)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`  麻烦作者在sdk中使用

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.1.1

3. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "page",
  "body": [
    {
      "type": "crud",
      "syncLocation": false,
      "api": {
        "method": "post",
        "url": "http://127.0.0.1:8105/**",
        "requestAdaptor": "",
        "adaptor": "",
        "messages": {}
      },
      "columns": [
        {
          "name": "id",
          "label": "ID",
          "type": "text",
          "id": "u:00759b927ff6"
        },
        {
          "name": "code",
          "label": "code",
          "type": "text",
          "id": "u:e4ee9833afb3"
        },
        {
          "type": "text",
          "name": "name",
          "label": "name",
          "id": "u:486738dda1c6"
        }
      ],
      "bulkActions": [],
      "itemActions": [],
      "id": "u:56fc18fc5575",
      "messages": {},
      "perPageAvailable": [
        10
      ],
      "filter": {
        "title": "查询条件",
        "body": [
          {
            "type": "input-text",
            "name": "keywords",
            "label": "关键字",
            "id": "u:ef84ab046eff"
          }
        ],
        "id": "u:3b1fb1ae5fef"
      },
      "footable": false,
      "hideQuickSaveBtn": false,
      "alwaysShowPagination": false,
      "headerToolbar": [
        {
          "type": "bulk-actions"
        },
        {
          "type": "drag-toggler",
          "tpl": "内容",
          "wrapperComponent": ""
        },
        {
          "type": "export-excel",
          "tpl": "内容",
          "wrapperComponent": "",
          "id": "u:5069721f311e"
        }
      ]
    }
  ],
  "id": "u:15277af8a88d",
  "asideResizor": false,
  "pullRefresh": {
    "disabled": true
  },
  "regions": [
    "body"
  ],
  "style": {
    "boxShadow": " 0px 0px 0px 0px transparent"
  }
}

4. 操作步骤
麻烦作者把url地址改成本地，只要有数据能导出就行

**Comment by 2betop** [comment]
麻烦截图一下浏览器控制台，看看是否有报错

**Comment by songyinhai2006** [comment]
![image](https://github.com/baidu/amis/assets/52561802/0adc976b-0a87-442a-b713-842aa55b71fb)
没有报错

**Comment by 2betop** [comment]
exceljs.js 内容返回不符合预期，难道返回是 html，而不是 js 代码？

**Comment by 2betop** [comment]
vue 打包不熟悉，需要自己研究

**Comment by mizhicangyue** [comment]
同求！请问解决了吗？是咋解决的～

**Comment by 2betop** [comment]
直接用这个将 sdk copy 过去 https://www.npmjs.com/package/rollup-plugin-copy

**Comment by songyinhai2006** [comment]
> 同求！请问解决了吗？是咋解决的～

手动拷贝js到相关路径

**Comment by stonezhao28** [comment]
找了几天终于找到解决方案，谢谢大家.
补充一句，如果在vue使用的话，我这里需要访问根目录，所以在根目录下建立public目录，复制sdk的exceljs.js文件到public目录即可.
