### ISSUE TITLE
条件组合的回显怎么展示的

### ISSUE THREAD

**Issue by shenzhi518** [baidu/amis#7294]
![image](https://github.com/baidu/amis/assets/85657965/02488b8b-814d-483d-a6f4-c4d185ac5eec)
我这边使用 框架里的 条件组合  但是这个条件组合的回显怎么展示的,目前这边存的是生成的那个json数据  但是怎么把这个数据 回显到页面上 麻烦请教一下

**Comment by 2betop** [comment]
什么数据格式提交的，就什么数据格式回显。可以给 form 配置 initApi 返回提交时一样的结构即可
