### ISSUE TITLE
AMIS定义的接口返回格式是否可以自定义

### ISSUE THREAD

**Issue by whitekyo** [baidu/amis#730]
如题，未来是否可以支持自定义，完全copy baidu api格式是不合理的。

**Comment by RickCole21** [comment]
fetcher可以自定义适配啊

**Comment by whitekyo** [comment]
> fetcher可以自定义适配啊

哦，我的这个提问不全面，有问题，我补充下，fetcher是可以解决接口返回的适配，但是AMIS有很多依赖接口的组件，我如果修改了接口返回格式，AMIS的组件该如何适配兼容呢？

**Comment by CareyToboo** [comment]
组件使用的接口，可以用 adaptor 控制请求返回啊，这样是不是满足你的需求？ [amis api](https://baidu.github.io/amis/docs/renderers/Types#api)

**Comment by RickCole21** [comment]
嗯，也可以针对单个接口添加适配器
https://baidu.github.io/amis/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8
