### ISSUE TITLE
renderAmis 怎么引入自定义组件

### ISSUE THREAD

**Issue by 1529751550** [baidu/amis#7300]
编辑器布拉格能注册自定义的组件，但是我想在渲染器里使用，现在提示
Error: 找不到对应的渲染器
路径: page/body/11/my-renderer
想知道这种方式怎么引入自定义组件呢？
渲染器代码：

{renderAmis(
          this.state.schema,
          {
            // props...
            
          },
          {
            fetcher:...,
            isCancel: (e: any) => axios.isCancel(e),
            copy: ...,
            theme: 'antd'
          },
        )}

**Comment by 2betop** [comment]
重复 issue #7299
