### ISSUE TITLE
动态布局-页面加载图表如何由后端控制？？？？

### ISSUE THREAD

**Issue by diabloyong** [baidu/amis#731]
![image](https://user-images.githubusercontent.com/12034479/86214128-52234180-bbad-11ea-8313-79bb33b21ab8.png)
这个页面是写了静态文件生成的，如何通过后端返回图表的个数，动态显示这些图标，
后端返回5 个图，那么页面就显示5个； 后端返回x个，就显示x个。

**Comment by 2betop** [comment]
搜一下 schemaApi

**Comment by diabloyong** [comment]
后端代码返回是是什么类型？

**Comment by RickCole21** [comment]
https://baidu.github.io/amis/docs/components/chart#%E8%BF%9C%E7%A8%8B%E6%8B%89%E5%8F%96%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E9%A1%B9
