### ISSUE TITLE
sdk模式下 请求后端接口如果鉴权失败如何重定向到登录页面

### ISSUE THREAD

**Issue by andrekzwu** [baidu/amis#7314]
sdk模式下 请求后端接口如果鉴权失败如何重定向到登录页面，按照#3754的说法去整
sdk的模式 接口返回 http code=200 返回数据 {"message":"bad","status":302,"url":"/login.html"}

没有生效，sdk版本是3.1.1

**Comment by 2betop** [comment]
可以通过 env 下发 `fetcher` 自己实现接口发送，并实现跳转，或者 下发 `responseAdaptor`。
具体可以看这里面的函数签名 https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA
