### ISSUE TITLE
linux机器上搭建的，启动成功，但是从远程访问页面元素为空白

### ISSUE THREAD

**Issue by Irisxu** [baidu/amis#732]

**Comment by Irisxu** [comment]
在linux虚拟机上搭建的服务，npm run dev成功，npm start成功，在chrome浏览器方式的时候页面titile出来了，内容为空

**Comment by nwind** [comment]
点 Console 看啥报错

**Comment by Coober-Ding** [comment]
mac 系统上也有类似问题 index.html都没有的样子
![image](https://user-images.githubusercontent.com/38315601/86584618-bc762080-bfb7-11ea-9ec1-6ed238e5ab44.png)

**Comment by Coober-Ding** [comment]
> mac 系统上也有类似问题 index.html都没有的样子
> ![image](https://user-images.githubusercontent.com/38315601/86584618-bc762080-bfb7-11ea-9ec1-6ed238e5ab44.png)

![image](https://user-images.githubusercontent.com/38315601/86586734-f4cb2e00-bfba-11ea-96de-3f4876666372.png)

**Comment by Coober-Ding** [comment]
![image](https://user-images.githubusercontent.com/38315601/86586750-fdbbff80-bfba-11ea-866a-529371c4d1a6.png)

**Comment by Coober-Ding** [comment]
![image](https://user-images.githubusercontent.com/38315601/86586822-1debbe80-bfbb-11ea-93f1-968fbf3e3dfa.png)

**Comment by Irisxu** [comment]
浏览器console没有任何报错，控制台也没有报错

**Comment by Irisxu** [comment]
![image](https://user-images.githubusercontent.com/6022913/87402453-2ca32880-c5ee-11ea-9606-0dc02881ba70.png)

**Comment by 2betop** [comment]
尝试更新一下 amis 到1.0.15-beta.9 试试

**Comment by nwind** [comment]
现在应该没了
