### ISSUE TITLE
关于amis-editor-theme是否开源的提问

### ISSUE THREAD

**Issue by HappyYang233** [baidu/amis#7326]
官方是否有明确的计划开源amis-editor-theme？
由于最近在做amis的技术调研，关于amis的各个模块都研究了一下，三月份官方开源了amis-editor的源码，amis-editor中依赖的amis-editor-theme和amis-editor-theme-helper两个包并未开源，这两个包作为编辑器的配套工具是否会进行开源？有bug咱也好一起修复？

**Comment by yyn0210** [comment]
amis-editor 开源了吗？我咋没看到呢。

**Comment by 2betop** [comment]
不打算开源

**Comment by jiatongwu** [comment]
不是宣称开源的吗？
为什么 不开源？

**Comment by lizyChy0329** [comment]
amis 里不是有 amis-editor 的源码么？ amis-editor-core 也有
