### ISSUE TITLE
InputNumber 数字输入框 带单位数字 表单设置为静态时会显示数字无效

### ISSUE THREAD

**Issue by ArrNNG** [baidu/amis#7333]
#### 描述问题：

InputNumber 数字输入框 带单位数字 当表单设置为静态时会显示数字无效

#### 截图或视频：

<img width="1080" alt="截屏2023-07-03 14 36 17" src="https://github.com/baidu/amis/assets/57611350/6f6a768a-eadc-400e-9a42-09993bc278a5">

#### 如何复现（请务必完整填写下面内容）：
 
```
{
  "type": "page",
  "body": {
    "type": "form",
    "static": true,
    "data": {
      "number": "55px"
    },
    "api": "/amis/api/mock2/form/saveForm",
    "debug": true,
    "body": [
      {
        "type": "input-number",
        "name": "number",
        "label": "数字",
        "unitOptions": [
          "px",
          "%",
          "em"
        ]
      }
    ]
  }
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
InputNumber 的值格式是数字，而不是字符串，目前看来符合预期

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/7334 已修复
