### ISSUE TITLE
如何在form的requestAdaptor的函数中获取hidden组件中的value?

### ISSUE THREAD

**Issue by Seizedays233** [baidu/amis#7335]
#### 实现场景：
我想在请求时对hidden组件做一个判断但是不知道如何在函数中获取那个组件的值

#### 存在的问题：
如何在js函数中获取value

#### 当前方案：
无
form的body段代码 console.log提示not defined错误

"body": [
            {
              type: "hidden",
              "ref": "testRef",
              name: "expoId"
            },
            {
              "name": "headImages",
              "label": "上传头图",
              "type": "input-image",
              "name": "image",
              fileField:"headImage",
              "label": "image",
              "receiver": {
                url: "/api/files/images?id=${expoId}&type=10",
                requestAdaptor: function (api, ref) {
                  console.log(${expoId})
                  return api
                },
              },
            },
          ]

**Comment by 2betop** [comment]
发送适配器获取不到组件上下文件的数据，但是api 的参数或者数据体里面是可以的，比如 url 的后面 query 是可以获取到的。
