### ISSUE TITLE
Office Viewer 组件 表格行循环功能 Bug

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#7337]
#### 描述问题：
表格行循环，如果循环行下面还有固定静态行，比如合计行等情况，则会导致循环行在整个表格的最下面显示  并不在中间显示

#### 截图或视频：
这样就有问题
![image](https://github.com/baidu/amis/assets/44140500/3b962356-2d88-4fe6-9b72-e74e105aa2c5)

解决方法只有如下图这样分开，但是这样并不适合与通常的情况 
![image](https://github.com/baidu/amis/assets/44140500/42037f41-dfcd-484d-bf75-8720a1b90ba5)

**Comment by nwind** [comment]
fixed in #7376
