### ISSUE TITLE
如何在编辑器crud右侧添加一个标签栏？ 模型列表中右侧为三个标签栏，怎样才能添加？ crud只能有俩

### ISSUE THREAD

**Issue by onlyThat** [baidu/amis#7342]
![微信图片_20230704111759](https://github.com/baidu/amis/assets/114373085/34ed92ee-3509-4140-b860-b8e95f56cbb6)

**Comment by onlyThat** [comment]
模型列表中右侧为三个标签栏，怎样才能添加？   crud只能有俩

**Comment by 2betop** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/editor#%E5%A6%82%E4%BD%95%E5%AE%9A%E4%B9%89%E5%8F%B3%E4%BE%A7%E9%85%8D%E7%BD%AE%E9%9D%A2%E6%9D%BF
