### ISSUE TITLE
当api接口返回的状态码不为200时，使用jssdk的方式不知道怎么处理

### ISSUE THREAD

**Issue by tanjiancheng** [baidu/amis#735]
![image](https://user-images.githubusercontent.com/7401570/86553244-c4649f00-bf7c-11ea-8e82-92bd0b6a04ad.png)
如上图，我的接口是基于restful风格的，当密码不正确时接口返回的状态码是400，请问如何再jssdk里面处理这个非200错误的状态码，希望给一个例子或者能否增加一个api的catch的处理方式？

**Comment by 2betop** [comment]
fetcher 其实是可以外部传入的，自己实现一个 fetcher 就可以了。

**Comment by tanjiancheng** [comment]
> fetcher

能给一个处理这种非200的例子吗？jssdk的，谢谢了

**Comment by wq599263163** [comment]
> > fetcher
> 
> 能给一个处理这种非200的例子吗？jssdk的，谢谢了

`fetcher: api => {
        let url = api.url
        let exec = reg.exec(url)
        if (exec && domainList[exec[1]]) {
          try {
            url = url.replace(exec[0], domainList[exec[1]])
            api.url = url
          } catch (error) {
            notification.info({
              message: `出错啦！！`,
              description: `请检查通配符是否正确！`,
            })
          }
        }
        return axios(api).then(response => {
          let _status = 1
          const { code, data, message, status, msg } = response.data
          const { url } = response.config
          if (status === 0) {
            _status = 0
            if (!url?.includes('baidu')) {
              notification.info({
                message: `amis 接口请求不符合规范！`,
                description: `请使用
                  code: 200\n
                  data:null \n
                  message: '成功'
                `,
              })
            }
          } else if (code && code === 200) {
            _status = 0
          }

          let payload = {
            status: _status,
            msg: msg || message,
            data,
          }
          return {
            ...response,
            data: payload,
          }
        })
      },
`
