### ISSUE TITLE
drawer中设置select模式为associated，悬浮bug

### ISSUE THREAD

**Issue by hapezzz** [baidu/amis#7355]
当我在抽屉里面设置选择框模式为associated时，元素悬浮出现问题，问题如视频所示。

https://github.com/baidu/amis/assets/55071625/72e894ed-573c-4b6e-9be9-ad1863ba03b3

代码如下所示
{
  "type": "page",
  "title": "列表",
  "name": "roleInfo",
  "toolbar": [
    {
      "type": "button",
      "actionType": "drawer",
      "drawer": {
        "title": "新增角色",
        "closeOnOutside": true,
        "size": "md",
        "body": {
          "type": "form",
          "name": "role_create_form",
          "api": {
            "url": "/role/add",
            "method": "post"
          },
          "body": [
            {
              "type": "input-text",
              "name": "role_name",
              "label": "角色名称",
              "required": true
            },
            {
              "type": "textarea",
              "name": "role_content",
              "clearable": true,
              "showCounter": true,
              "maxLength": 200,
              "label": "角色详述",
              "required": true
            },
            {
              "type": "select",
              "selectMode": "associated",
              "leftMode": "tree",
              "multiple": true,
              "source": "/function/generateAssociated",
              "name": "role_function",
              "label": "对应功能",
              "required": true
            }
          ]
        }
      },
      "label": "新增",
      "primary": true
    }
  ],
  "body": [
    {
      "type": "crud",
      "name": "role_crud",
      "text-align": "center",
      "loadDataOnce": true,
      "api": "/role/roleList",
      "filter": {
        "title": "",
        "mode": "inline",
        "wrapWithPanel": false,
        "submitText": "",
        "controls": [
          {
            "type": "text",
            "name": "keywords",
            "placeholder": "通过关键字搜索",
            "addOn": {
              "label": "搜索",
              "type": "submit",
              "className": "btn-success"
            },
            "clearable": true
          }
        ],
        "className": "m-b-sm"
      },
      "columns": [
        {
          "name": "label",
          "label": "角色名称",
          "sortable": true
        },
        {
          "name": "roleContent",
          "label": "角色详述",
          "sortable": true
        },
        {
          "name": "pages",
          "label": "对应功能",
          "sortable": true,
          "type": "select",
          "selectMode": "associated",
          "leftMode": "tree",
          "multiple": true,
          "static": true
        },
        {
          "type": "operation",
          "label": "操作",
          "width": "",
          "buttons": [
            {
              "type": "button-group",
              "buttons": [
                {
                  "type": "button",
                  "label": "修改",
                  "level": "info",
                  "actionType": "drawer",
                  "drawer": {
                    "title": "修改角色",
                    "closeOnOutside": true,
                    "size": "md",
                    "body": {
                      "type": "form",
                      "name": "role_edit_form",
                      "api": {
                        "url": "/role/edit",
                        "method": "post"
                      },
                      "body": [
                        {
                          "type": "input-text",
                          "name": "role_name",
                          "value": "${roleName}",
                          "label": "角色名称",
                          "required": true
                        },
                        {
                          "type": "input-text",
                          "name": "role_content",
                          "value": "${roleContent}",
                          "label": "角色详述",
                          "required": true
                        },
                        {
                          "type": "select",
                          "selectMode": "associated",
                          "leftMode": "tree",
                          "multiple": true,
                          "source": "/function/generateAssociated",
                          "name": "role_function",
                          "value": "${pages}",
                          "label": "对应功能",
                          "required": true
                        }
                      ]
                    }
                  }
                },
                {
                  "type": "button",
                  "label": "删除",
                  "level": "danger",
                  "actionType": "ajax",
                  "confirmText": "您确认要删除角色${roleName}?",
                  "api": "/role/delete?account=${roleName}"
                }
              ]
            }
          ],
          "placeholder": "-",
          "fixed": "right"
        }
      ],
      "affixHeader": true,
      "columnsTogglable": "auto",
      "placeholder": "暂无数据",
      "tableClassName": "table-db table-striped",
      "headerClassName": "crud-table-header",
      "footerClassName": "crud-table-footer",
      "toolbarClassName": "crud-table-toolbar",
      "combineNum": 0,
      "bodyClassName": "panel-default"
    }
  ]
}

**Comment by allenve** [comment]
没有复现，你的版本是什么？

**Comment by hapezzz** [comment]
最新版本，3.2.0






1448787060
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月14日(星期五) 上午10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] drawer中设置select模式为associated，悬浮bug (Issue #7355)





 
没有复现，你的版本是什么？

**Comment by allenve** [comment]
使用方式是什么？ sdk 还是 npm方式

**Comment by hapezzz** [comment]
sdk




1448787060
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/amis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月14日(星期五) 下午2:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/amis] drawer中设置select模式为associated，悬浮bug (Issue #7355)





 
使用方式是什么？ sdk 还是 npm方式

**Comment by allenve** [comment]
https://github.com/baidu/amis/issues/7372 已修复 详见这个issue
