### ISSUE TITLE
富文本插入媒体，插入时视频重复显示

### ISSUE THREAD

**Issue by zyifan** [baidu/amis#7370]
#### 描述问题：

富文本插入多媒体，插入后显示两个视频内容

#### 截图或视频：

![演示](https://github.com/baidu/amis/assets/19355902/f3325ba6-b307-44fe-badb-3e7e3860adf4)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
使用富文本组件

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
官方演示最新版本

3. 操作步骤
1、打开富文本组件
2、点击插入->多媒体->将自己的多媒体地址复制到地址里

**Comment by Jarod-Xie** [comment]
我也遇到了😅

**Comment by 2betop** [comment]
tinymce 里面，很诡异的问题，先用魔法解决了 #7400
