### ISSUE TITLE
select 下拉框选择-选中之后显示问题

### ISSUE THREAD

**Issue by huangyedie** [baidu/amis#7371]
#### 描述问题：

选中之后-应该展示用户1，而不是user1
看下图

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/51399090/31198804-4dd8-4eab-b9da-70721623cf9c)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
sdk
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.1.1
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "label": "人员选择",
        "type": "select",
        "name": "b",
        "multiple": true,
        "sortable": true,
        "searchable": true,
        "selectMode": "associated",
        "leftMode": "tree",
        "source": "/amis/api/mock2/form/departUser",
        "searchApi": "/amis/api/mock2/form/departUserSearch?term=${term}",
        "deferApi": "/amis/api/mock2/form/departUser?ref=${ref}&dep=${value}"
      }
    ]
  }
}
```

4. 操作步骤

**Comment by huangyedie** [comment]
> 可以试下最新版本

说实话，我不太敢用啊，请看-#7372 issues，升级会有更大的问题

**Comment by hsm-lv** [comment]
> > 可以试下最新版本
> 
> 说实话，我不太敢用啊，请看-#7372 issues，升级会有更大的问题

在新版没有复现你说的问题

**Comment by huangyedie** [comment]
> > > 可以试下最新版本
> > 
> > 
> > 说实话，我不太敢用啊，请看-#7372 issues，升级会有更大的问题
> 
> 在新版没有复现你说的问题

是使用的3.1.1的sdk吗？这个下拉框的遮罩没有复现吗?
