### ISSUE TITLE
office viewer 打印没响应，官方示例页面中点击打印也不响应

### ISSUE THREAD

**Issue by atliwen** [baidu/amis#7389]
office viewer 打印没响应，官方示例页面中点击打印也不响应

[Office-Viewer.webm](https://github.com/baidu/amis/assets/10055836/8c04fd0c-c452-4572-9df3-9ee4129df695)

**Comment by atliwen** [comment]
![image](https://github.com/baidu/amis/assets/10055836/20703966-c687-47d8-bc72-8fa9fb71b0f1)
{
  "type": "page",
  "body": [
    {
      "type": "action",
      "label": "打印",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "print",
              "componentId": "office-viewer111"
            }
          ]
        }
      },
      "id": "u:05b2f26f79ff"
    },
    {
      "type": "form",
      "title": "",
      "wrapWithPanel": false,
      "body": [
        {
          "type": "input-file",
          "name": "file",
          "label": "选择 Docx 文件预览效果（不会上传到服务器）",
          "asBlob": true,
          "accept": ".docx",
          "id": "u:ce2d7eaf8cf9"
        },
        {
          "type": "office-viewer",
          "id": "office-viewer111",
          "name": "file"
        }
      ],
      "id": "u:cb1ca34d2f53"
    }
  ],
  "id": "u:ca503a3ea2f7",
  "asideResizor": false,
  "pullRefresh": {
    "disabled": true
  },
  "regions": [
    "body"
  ]
}

**Comment by nwind** [comment]
奇怪没复现，浏览器和版本是啥？
