### ISSUE TITLE
可以展示视频列表么，type 为video，没有找到相关文档和issue

### ISSUE THREAD

**Issue by shiwl0329** [baidu/amis#7397]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
可以结合 Each，或者 List 组件来展示适配列表

**Comment by shiwl0329** [comment]
有相关的demo么，前端小白一个。。 做算法的想做一些前台展示，采用了amis

**Comment by shiwl0329** [comment]
![image](https://github.com/baidu/amis/assets/13725297/96e49da3-ef7f-412c-864a-df3c3a57a239)

我现在是这么写的，但是数据如何绑定返回接口的数据呢

**Comment by hsm-lv** [comment]
> ![image](https://user-images.githubusercontent.com/13725297/251668962-96e49da3-ef7f-412c-864a-df3c3a57a239.png)
> 
> 我现在是这么写的，但是数据如何绑定返回接口的数据呢

例如：
```
{
  "type": "page",
  "data": {
    "arr": [
      "https://amis.bj.bcebos.com/amis/2019-12/1577157317579/trailer_hd.mp4",
      "https://amis.bj.bcebos.com/amis/2019-12/1577157317579/trailer_hd.mp4",
      "https://amis.bj.bcebos.com/amis/2019-12/1577157317579/trailer_hd.mp4"
    ]
  },
  "body": {
    "type": "each",
    "name": "arr",
    "items": {
      "type": "video",
      "src": "${item}"
    }
  }
}
```
