### ISSUE TITLE
webpack项目兼容性问题

### ISSUE THREAD

**Issue by 21paradox** [baidu/amis#74]
hi，我在webpack环境使用了下发现textarea 配置报错。

![image](https://user-images.githubusercontent.com/6622122/59190188-aaf0f800-8bae-11e9-9ef9-4fb9a33c67b1.png)

在webpack下 require("../../components/Textarea") 取到的模块出错
我创建了一个demo项目复现问题
https://github.com/21paradox/test-amis-textarea

![image](https://user-images.githubusercontent.com/6622122/59190209-b5ab8d00-8bae-11e9-98a5-0506137a20fc.png)

![image](https://user-images.githubusercontent.com/6622122/59190214-ba704100-8bae-11e9-8f17-a6b565a65aa8.png)

**Comment by 2betop** [comment]
先可以用这个版本：1.0.0-beta.25 
后续 rc-4 会修复这个问题。

**Comment by 21paradox** [comment]
1.0.0-beta.25 可以了，多谢～

**Comment by Leonard-Li777** [comment]
@2betop 我测试了1.0.0-rc.8下，这两个组件有问题
                  {
                      "type": "json-editor",
                      "name": "json",
                      "value": "{\n    \"a\": 1,\n    \"b\": [\n        1,\n        2,\n        3\n    ]\n}",
                      "label": "Json Editor"
                  },
                  {
                      "type": "rich-text",
                      "name": "html",
                      "label": "Rich Text",
                      "value": "<p>Just do <code>IT</code>!</p>"
                  },

**Comment by 2betop** [comment]
是说 webpack 下有问题？

**Comment by Leonard-Li777** [comment]
是webpack下有问题
