### ISSUE TITLE
子combo和父combo的数据联动问题

### ISSUE THREAD

**Issue by zhangyucumt** [baidu/amis#740]
我遇到这样一个问题。就是表单的一个字段是combo，而这个combo的一个字段也是combo类型。
我想达到这样的效果，就是随着父combo的某个字段变化，子combo的部分字段产生联动也发生变化。
比如：
```json
{
    "controls": [
    {
        "name": "application_info_set",
        "type": "combo",
        "label": "应用信息",
        "controls": [
        {
            "name": "build_unit",
            "type": "select",
            "label": "打包方式",
            "inline": true,
            "options": [
            {
                "label": "整体打包",
                "value": "whole"
            },
            {
                "label": "每个组件单独打包",
                "value": "single"
            }]
        },
        {
            "name": "component_info_set",
            "type": "combo",
            "label": "组件信息",
            "controls": [
            {
                "name": "build_cwd",
                "type": "text",
                "label": "打包命令执行目录"
            }]
        }]
    }]
}
```
这是我表单的一部分。我现在想让当打包方式build_unit选择whole时，子combo 打包命令执行目录build_cwd字段就隐藏。
查找了文档试了 `hiddenOn ` 但是不知道取哪个字段没有效果，这里有没有什么好的办法呢？

**Comment by RickCole21** [comment]
子combo上配置：
1. `"canAccessSuperData": true`
2. `"strictMode": false`
3. `"syncFields": ['build_unit']`
4. 显影联动地方配置：`hiddenOn:"data.build_unit === 'whole'"`

**Comment by zhangyucumt** [comment]
> 子combo上配置：
> 
> 1. `"canAccessSuperData": true`
> 2. `"strictMode": false`
> 3. `"syncFields": ['build_unit']`
> 4. build_cwd组件配置：`hiddenOn:"data.build_unit === 'whole'"`

可以了 ，太感谢了！
