### ISSUE TITLE
高德地图用不了，提示${vendor} 地图控件不支持

### ISSUE THREAD

**Issue by shirosama** [baidu/amis#7401]
#### 描述问题：

3.1.1还能正常用高德地图，3.2就提示${vendor} 地图控件不支持

#### 截图或视频：

![屏幕截图 2023-07-07 100820](https://github.com/baidu/amis/assets/12275809/255bcd12-0c43-41b5-9dc6-9e50b9669ed6)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.2

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "debug": true,
    "body": [
      {
        "type": "location-picker",
        "name": "location",
        "vendor": "gaode",
        "ak": "8ae6a7549ce3f37f8e5aab9d445df8ad",
        "label": "地址"
      }
    ]
  }
}
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by hsm-lv** [comment]
目前暂时没有支持
