### ISSUE TITLE
amis-editor 设置api请求无效

### ISSUE THREAD

**Issue by Slebee** [baidu/amis#7402]
#### 描述问题：

给按钮设置点击事件选择发送请求，不管怎么设置，在run action ajax 里都会输出invalid api url: 的错误

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/9144738/94596b20-85a1-4e19-b48f-1f011438c6bd)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

amis 3.2；amis-editor@5.5.0 amis-editor-core@5.5.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "button",
  "label": "删除",
  "level": "link",
  "className": "text-danger",
  "disabledOn": "this.grade === 'A'",
  "id": "u:9fc1901ef1ee",
  "onEvent": {
    "click": {
      "weight": 0,
      "actions": [
        {
          "actionType": "ajax",
          "outputVar": "responseResult",
          "api": {
            "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample/${id}",
            "method": "delete",
            "requestAdaptor": "",
            "adaptor": "",
            "messages": {}
          },
          "options": {}
        }
      ]
    }
  }
}
```

5. 操作步骤
我是直接curd操作列上加个按钮，给他设置请求就会复现，排查过后发现是amis-editor@5.5.0 amis-editor-core@5.5.0生成的json跟5.4.1是不一样的：
```
// 这是5.4.1
"actions": [
        {
          "outputVar": "responseResult",
          "actionType": "ajax",
          "args": {
            "options": {
            },
            "api": {
              "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample/${id}",
              "method": "delete",
              "requestAdaptor": "",
              "adaptor": "",
              "messages": {
              }
            }
          }
        }
      ]

// 这是5.5.0
"actions": [
        {
          "actionType": "ajax",
          "outputVar": "responseResult",
          "api": {
            "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample/${id}",
            "method": "delete",
            "requestAdaptor": "",
            "adaptor": "",
            "messages": {}
          },
          "options": {}
        }
      ]
```
缺少了一层 args ；

**Comment by FengZeming** [comment]
多谢 那这不就是bug 了吗? 用了最新版反而有错了 本地 5.3.0 都试过了  生成的跟5.5一样 没有args

**Comment by hsm-lv** [comment]
> #### 描述问题：
> 给按钮设置点击事件选择发送请求，不管怎么设置，在run action ajax 里都会输出invalid api url: 的错误
> 
> #### 截图或视频：
> ![image](https://user-images.githubusercontent.com/9144738/251617850-94596b20-85a1-4e19-b48f-1f011438c6bd.png)
> 
> #### 如何复现（请务必完整填写下面内容）：
> 1. 你是如何使用 amis 的？
>    npm
> 2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
> 
> amis 3.2；amis-editor@5.5.0 amis-editor-core@5.5.0
> 
> 4. 粘贴有问题的完整 `amis schema` 代码：
> 
> ```
> {
>   "type": "button",
>   "label": "删除",
>   "level": "link",
>   "className": "text-danger",
>   "disabledOn": "this.grade === 'A'",
>   "id": "u:9fc1901ef1ee",
>   "onEvent": {
>     "click": {
>       "weight": 0,
>       "actions": [
>         {
>           "actionType": "ajax",
>           "outputVar": "responseResult",
>           "api": {
>             "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample/${id}",
>             "method": "delete",
>             "requestAdaptor": "",
>             "adaptor": "",
>             "messages": {}
>           },
>           "options": {}
>         }
>       ]
>     }
>   }
> }
> ```
> 
> 5. 操作步骤
>    我是直接curd操作列上加个按钮，给他设置请求就会复现，排查过后发现是amis-editor@5.5.0 amis-editor-core@5.5.0生成的json跟5.4.1是不一样的：
> 
> ```
> // 这是5.4.1
> "actions": [
>         {
>           "outputVar": "responseResult",
>           "actionType": "ajax",
>           "args": {
>             "options": {
>             },
>             "api": {
>               "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample/${id}",
>               "method": "delete",
>               "requestAdaptor": "",
>               "adaptor": "",
>               "messages": {
>               }
>             }
>           }
>         }
>       ]
> 
> // 这是5.5.0
> "actions": [
>         {
>           "actionType": "ajax",
>           "outputVar": "responseResult",
>           "api": {
>             "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample/${id}",
>             "method": "delete",
>             "requestAdaptor": "",
>             "adaptor": "",
>             "messages": {}
>           },
>           "options": {}
>         }
>       ]
> ```
> 
> 缺少了一层 args ；

特意去掉args的，但是是兼容的，两种方式都可以。区别是包裹在args中后，里面所有配置项会进行变量解析，如果存在data的情况的话，数据域是不准确的，因此推荐去掉args的用法

**Comment by Slebee** [comment]
> 你上面写的5.4.1和5.5.0中的代码写法是错误的，把按钮动作中的ajax和事件动作中的用混了。按钮动作中的ajax没有args，可以看 [https://baidu.github.io/amis/zh-CN/components/action#ajax-%E8%AF%B7%E6%B1%82?page=1。事件动作中的是https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E5%8F%91%E9%80%81-http-%E8%AF%B7%E6%B1%82](https://baidu.github.io/amis/zh-CN/components/action#ajax-%E8%AF%B7%E6%B1%82?page=1%E3%80%82%E4%BA%8B%E4%BB%B6%E5%8A%A8%E4%BD%9C%E4%B8%AD%E7%9A%84%E6%98%AFhttps://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E5%8F%91%E9%80%81-http-%E8%AF%B7%E6%B1%82)
> 
> 事件动作中的ajax动作是特意去掉args的，但是是兼容的，两种方式都可以。区别是包裹在args中后，里面所有配置项会进行变量解析，如果存在data的情况的话，数据域是不准确的，因此推荐去掉args的用法

不大理解这个区别，因为我就是正常在editor里拉出个curd，给删除按钮增加了一个发送请求的事件，这个行为在5.4和5.5生成的json就产生了上述的区别，有什么我没注意到的点么
![image](https://github.com/baidu/amis/assets/9144738/102c1dd6-87db-4e21-9cbc-9b6767140d67)

**Comment by hsm-lv** [comment]
> > 你上面写的5.4.1和5.5.0中的代码写法是错误的，把按钮动作中的ajax和事件动作中的用混了。按钮动作中的ajax没有args，可以看 [https://baidu.github.io/amis/zh-CN/components/action#ajax-%E8%AF%B7%E6%B1%82?page=1。事件动作中的是https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E5%8F%91%E9%80%81-http-%E8%AF%B7%E6%B1%82](https://baidu.github.io/amis/zh-CN/components/action#ajax-%E8%AF%B7%E6%B1%82?page=1%E3%80%82%E4%BA%8B%E4%BB%B6%E5%8A%A8%E4%BD%9C%E4%B8%AD%E7%9A%84%E6%98%AFhttps://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E5%8F%91%E9%80%81-http-%E8%AF%B7%E6%B1%82)
> > 事件动作中的ajax动作是特意去掉args的，但是是兼容的，两种方式都可以。区别是包裹在args中后，里面所有配置项会进行变量解析，如果存在data的情况的话，数据域是不准确的，因此推荐去掉args的用法
> 
> 不大理解这个区别，因为我就是正常在editor里拉出个curd，给删除按钮增加了一个发送请求的事件，这个行为在5.4和5.5生成的json就产生了上述的区别，有什么我没注意到的点么 ![image](https://user-images.githubusercontent.com/9144738/253155070-102c1dd6-87db-4e21-9cbc-9b6767140d67.png)

旧版的配置是直接给组件配置actionType: "ajax"，事件动作是通过onEvent配置actionType: "ajax"。你可以贴下你完整的配置出来看看。

**Comment by Slebee** [comment]
> 旧版的配置是直接给组件配置actionType: "ajax"，事件动作是通过onEvent配置actionType: "ajax"。你可以贴下你完整的配置出来看看。

同样操作下，这是5.5的editor生成的

```
{
  "type": "page",
  "body": [
    {
      "type": "crud",
      "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample",
      "syncLocation": false,
      "columns": [
        {
          "name": "id",
          "label": "ID",
          "id": "u:6d4c2226876e"
        },
        {
          "name": "engine",
          "label": "Rendering engine",
          "id": "u:35f76d593e89"
        },
        {
          "name": "browser",
          "label": "Browser",
          "id": "u:5d5ffda8e61d"
        },
        {
          "name": "platform",
          "label": "Platform(s)",
          "id": "u:eea3f8d534c4"
        },
        {
          "name": "version",
          "label": "Engine version",
          "id": "u:ec1061494cd2"
        },
        {
          "name": "grade",
          "label": "CSS grade",
          "id": "u:2a86130c168f"
        },
        {
          "type": "operation",
          "label": "操作",
          "buttons": [
            {
              "label": "详情",
              "type": "button",
              "level": "link",
              "actionType": "dialog",
              "dialog": {
                "title": "查看详情",
                "body": {
                  "type": "form",
                  "body": [
                    {
                      "type": "input-text",
                      "name": "engine",
                      "label": "Engine"
                    },
                    {
                      "type": "input-text",
                      "name": "browser",
                      "label": "Browser"
                    },
                    {
                      "type": "input-text",
                      "name": "platform",
                      "label": "platform"
                    },
                    {
                      "type": "input-text",
                      "name": "version",
                      "label": "version"
                    },
                    {
                      "type": "control",
                      "label": "grade",
                      "body": {
                        "type": "tag",
                        "label": "${grade}",
                        "displayMode": "normal",
                        "color": "active"
                      }
                    }
                  ]
                }
              },
              "id": "u:1b8889170ba3"
            },
            {
              "label": "删除",
              "type": "button",
              "level": "link",
              "className": "text-danger",
              "disabledOn": "this.grade === 'A'",
              "id": "u:1cd97bbc35b3",
              "onEvent": {
                "click": {
                  "weight": 0,
                  "actions": [
                    {
                      "actionType": "ajax",
                      "outputVar": "responseResult",
                      "options": {
                      },
                      "api": {
                        "url": "http://xxxxxx.com",
                        "method": "delete",
                        "requestAdaptor": "",
                        "adaptor": "",
                        "messages": {
                        }
                      }
                    }
                  ]
                }
              }
            }
          ],
          "id": "u:6d54a39fad7b"
        }
      ],
      "id": "u:8f77139246df"
    }
  ],
  "id": "u:a00514335e2f"
}
```

这个是5.4生成的：
```
{
  "type": "page",
  "id": "u:ea9a6aa56b7c",
  "body": [
    {
      "type": "crud",
      "id": "u:791fdafaea92",
      "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/sample",
      "syncLocation": false,
      "columns": [
        {
          "name": "id",
          "label": "ID",
          "id": "u:f4cfa87b6d94"
        },
        {
          "name": "engine",
          "label": "Rendering engine",
          "id": "u:fdfc848578db"
        },
        {
          "name": "browser",
          "label": "Browser",
          "id": "u:7cd3f531dfbf"
        },
        {
          "name": "platform",
          "label": "Platform(s)",
          "id": "u:092a5332111d"
        },
        {
          "name": "version",
          "label": "Engine version",
          "id": "u:015e8cb79f06"
        },
        {
          "name": "grade",
          "label": "CSS grade",
          "id": "u:8d7a41b2e804"
        },
        {
          "type": "operation",
          "label": "操作",
          "buttons": [
            {
              "label": "详情",
              "type": "button",
              "level": "link",
              "actionType": "dialog",
              "dialog": {
                "title": "查看详情",
                "body": {
                  "type": "form",
                  "body": [
                    {
                      "type": "input-text",
                      "name": "engine",
                      "label": "Engine"
                    },
                    {
                      "type": "input-text",
                      "name": "browser",
                      "label": "Browser"
                    },
                    {
                      "type": "input-text",
                      "name": "platform",
                      "label": "platform"
                    },
                    {
                      "type": "input-text",
                      "name": "version",
                      "label": "version"
                    },
                    {
                      "type": "control",
                      "label": "grade",
                      "body": {
                        "type": "tag",
                        "label": "${grade}",
                        "displayMode": "normal",
                        "color": "active"
                      }
                    }
                  ]
                }
              },
              "id": "u:89049e60f29b"
            },
            {
              "label": "删除",
              "type": "button",
              "level": "link",
              "className": "text-danger",
              "disabledOn": "this.grade === 'A'",
              "id": "u:9fc1901ef1ee",
              "onEvent": {
                "click": {
                  "weight": 0,
                  "actions": [
                    {
                      "outputVar": "responseResult",
                      "actionType": "ajax",
                      "args": {
                        "options": {
                        },
                        "api": {
                          "url": "http://xxxxxxxx.com",
                          "method": "delete",
                          "requestAdaptor": "",
                          "adaptor": "",
                          "messages": {
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          ],
          "id": "u:763d02827c9d"
        }
      ]
    }
  ]
}
```

区别就是前面说的有没有args的区别，没有args那一层的，在3.2的amis库 render渲染出来的界面里，这个删除按钮就会出现没有args的会报invalid api url:

**Comment by hsm-lv** [comment]
嗯，大概是因为editor的版本与amis版本不匹配，先用不报错的那个版本吧，等下新的版本

**Comment by ziBLan** [comment]
mark
