### ISSUE TITLE
能不能解决类似searchable同时在不同组件中生效的问题

### ISSUE THREAD

**Issue by hapezzz** [baidu/amis#7406]
目前用的版本时3.1.0，在inputtable 中增加某一列使用select，为了开启select的搜索功能，增加searchable为true，但同时生效于inputtable中本列上，增加了搜索按钮。如图所示
![Clipboard_20230707](https://github.com/baidu/amis/assets/55071625/426413de-cd68-4f68-8364-f354b32cd414)

具体列的设置如下
            {
              "name": "model",
              "label": "产品型号",
              "type": "select",
              "searchable":true,
              "source": "/model?largeType=${largeType}",
              "required": true,
              "align": "center"
            }

**Comment by 2betop** [comment]
可以这样配置
<img width="800" alt="image" src="https://github.com/baidu/amis/assets/2698393/db82bf19-f81f-4537-b09a-fa4e171de218">

```
{
            "name": "model",
            "label": "产品型号",
            "quickEdit": {
              "name": "model",
              "mode": "inline",
              "type": "select",
              "searchable":true,
              "source": "/model?largeType=${largeType}",
              "required": true,
            },
            "align": "center"
          }
```
