### ISSUE TITLE
临时扩展这个功能没法用吗

### ISSUE THREAD

**Issue by ClarenceStar** [baidu/amis#741]
https://baidu.github.io/amis/docs/custom#%E4%B8%B4%E6%97%B6%E6%89%A9%E5%B1%95
我通过官方的例子想在schema里写js方法 发现例子贴进去报错
![image](https://user-images.githubusercontent.com/15528239/86579456-f2afa200-bfaf-11ea-9f13-95836b094009.png)

**Comment by 2betop** [comment]
js 里面才能这么用，json 不支持，另外里面用了 React，需要 `import React from 'react';`

**Comment by xinghe94** [comment]
> js 里面才能这么用，json 不支持，另外里面用了 React，需要 `import React from 'react';`

好的 那如果我想在schema里调用组件的props方法 好像也是不可行的呢

**Comment by Flourad** [comment]
> js 里面才能这么用，json 不支持，另外里面用了 React，需要 `import React from 'react';`

我用的这个临时扩展的例子点击之后没有反应
![image](https://user-images.githubusercontent.com/1535874/89105551-9b88da00-d454-11ea-9fe1-130d243ad337.png)
