### ISSUE TITLE
select组件搜索功能出现bug

### ISSUE THREAD

**Issue by tujiajun** [baidu/amis#7410]
#### 描述问题：

搜索"more",应当展示两条记录，但却展示了四条记录，多了两条毫无关系的记录

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/127007861/bebad964-bfa0-46d5-b5b0-761241e87e99)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.9-3.2.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "body": [
      {
        "label": "选项",
        "type": "select",
        "name": "select",
        "searchable": true,
        "options": [
          {
            "label": "Display in the top right corner of the list",
            "value": "list"
          },
          {
            "label": "Displayed in the top right corner of the record viewing page and in the drop-down menu for each item in the list view",
            "value": "record"
          },
          {
            "label": "Displayed in the \"More\" dropdown menu in the upper right corner of the record viewing page, as well as in the dropdown menu for each item in the list view",
            "value": "record_more"
          },
          {
            "label": "Display in the drop-down menu for each item in the list view",
            "value": "list_item"
          },
          {
            "label": "Displayed in the upper right corner of the record viewing page",
            "value": "record_only"
          },
          {
            "label": "Displayed in the \"More\" drop-down menu in the upper right corner of the record viewing page",
            "value": "record_only_more"
          }
        ]
      }
    ]
  }
}
```

4. 操作步骤
点击select并搜索"more"

**Comment by 2betop** [comment]
目前支持这两种匹配，所以匹配上了

>  - ACRONYM: If the item's acronym is the given value (ex. us would match United States)
>  - SIMPLE MATCH: If the item has letters in the same order as the letters of the given value (ex. iw would match Zimbabwe, but not Kuwait because it must be in the same order). Furthermore, if the item is a closer match, it will rank higher (ex. ua matches Uruguay more closely than United States of America, therefore Uruguay will be ordered before United States of America)

**Comment by 2betop** [comment]
#7420 已调整相关性参数
