### ISSUE TITLE
form组件的messages属性支持表达式

### ISSUE THREAD

**Issue by yinlianghui** [baidu/amis#7443]
#### 是否关联于某个问题吗：
如题，如果不支持的话，有些功能不好实现，比如在表达式中实现国际化。
使用 i18next 配合 过滤器 t 函数，实现 amis json 中的 i18n 国际化 #7140

#### 预期的解决方案：
form组件的messages属性支持表达式

**Comment by Icodezhan** [comment]
![%5 {ZA2HQ4CT9 IDNE%X21P](https://github.com/baidu/amis/assets/45064164/939ee422-b90e-4b4d-a1bb-e6114a605d5a)
![D8IHV6N 3@I}JI 9RM)KYHX](https://github.com/baidu/amis/assets/45064164/71744524-9945-47ce-aec3-e2dd84cbf85f)
![1VRGX 8RI)@4{J5UJFC0T{C](https://github.com/baidu/amis/assets/45064164/55070679-4294-405e-864b-84e4684da3d7)
![G)_~GFTE18}BKL4PW WJ9W1](https://github.com/baidu/amis/assets/45064164/e52bb600-c46a-4ef4-99fe-c46707f84804)
早就可以使用全局文本替换进行国际化了

**Comment by yinlianghui** [comment]
> 早就可以使用全局文本替换进行国际化了

感谢回复，这个我们看过的，我们评估下来没有在表达式中实现自定义t函数方便。

使用 i18next 配合 过滤器 t 函数，实现 amis json 中的 i18n 国际化 https://github.com/baidu/amis/issues/7140

#7140 这个清单中的的其他组件属性表达式支持的功能已经都合并到贵司 amis 主分支了，就差目前这个了。

我也提交PR了，见： https://github.com/baidu/amis/pull/7444 麻烦有空的时候安排review code，感谢。

**Comment by 2betop** [comment]
> > 早就可以使用全局文本替换进行国际化了
> 
> 感谢回复，这个我们看过的，我们评估下来没有在表达式中实现自定义t函数方便。
> 
> 使用 i18next 配合 过滤器 t 函数，实现 amis json 中的 i18n 国际化 #7140
> 
> #7140 这个清单中的的其他组件属性表达式支持的功能已经都合并到贵司 amis 主分支了，就差目前这个了。
> 
> 我也提交PR了，见： #7444 麻烦有空的时候安排review code，感谢。

没合是因为用例挂了
