### ISSUE TITLE
下拉框多选全选样式bug

### ISSUE THREAD

**Issue by yshujun** [baidu/amis#7447]
#### 描述问题：

下拉框多选全选样式bug， ”全选“的选项高度比较大， 全选也没有居中

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/48676074/1efc7ebb-3484-4fd2-aaf3-c9007f95d7e5)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
在官网上展示就有这个bug
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "body": [
      {
        "label": "多选",
        "type": "select",
        "name": "select2",
        "searchable": true,
        "checkAll": true,
        "multiple": true,
        "clearable": true,
        "source": "/amis/api/mock2/form/getOptions"
      }
    ]
  }
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
版本问题？无法复现
<img width="905" alt="image" src="https://github.com/baidu/amis/assets/2698393/099dc067-d33f-425f-b656-7840d2d503ad">

**Comment by yshujun** [comment]
你看官网上的 这个就有问题
![image](https://github.com/baidu/amis/assets/48676074/3ba47ae4-d5dd-4c79-b643-bf39f248c029)

**Comment by 2betop** [comment]
master 最新版本没这个问题，那个地址代码较旧
<img width="830" alt="image" src="https://github.com/baidu/amis/assets/2698393/fe923408-b624-454a-85d6-55b4da6c778c">
