### ISSUE TITLE
amis打包太慢了，使用typescript太慢了，有没有考虑使用tsup

### ISSUE THREAD

**Issue by blankzust** [baidu/amis#7448]
#### 是否关联于某个问题吗：
本地打包超过10分钟

#### 预期的解决方案：
使用tsup可以大幅降低打包时间

**Comment by Icodezhan** [comment]
10分钟夸张了，确定不是电脑性能不行了？我打包都是两三分钟左右

**Comment by blankzust** [comment]
真的非常慢。你是在根目录执行npm run build的不 @Icodezhan

**Comment by blankzust** [comment]
本地是用的node版本为16.20，amis是拉取的master最新代码

**Comment by blankzust** [comment]
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
1.7 GHz 四核Intel Core i7

**Comment by blankzust** [comment]
<img width="842" alt="image" src="https://github.com/baidu/amis/assets/8541906/434b747a-1c44-4168-b73c-b9d9a426f5b8">
本地打包到最后一步报错了

**Comment by blankzust** [comment]
npm run build

> @hb/aisuda@0.0.0 build
> npm run build --workspaces


> amis-formula@3.1.0 build
> npm run clean-dist && npm run genDoc && cross-env NODE_ENV=production rollup -c && cp src/doc.md lib/doc.md && cp src/doc.md esm/doc.md


> amis-formula@3.1.0 clean-dist
> rimraf lib/**


> amis-formula@3.1.0 genDoc
> ts-node ./scripts/genDoc.ts

公式文档生成 > /Users/shufeng/study/amis-test/amis/packages/amis-formula/src/doc.ts
公式md生成 > /Users/shufeng/study/amis-test/amis/packages/amis-formula/src/doc.md

./src/index.ts, ./src/doc.ts → lib...
created lib in 4.5s

./src/index.ts, ./src/doc.ts → esm...
created esm in 3.7s

> amis-core@3.1.0 build
> npm run clean-dist && NODE_ENV=production rollup -c


> amis-core@3.1.0 clean-dist
> rimraf lib/** esm/**


./src/index.tsx → lib...
(!) Circular dependency
src/index.tsx -> src/actions/index.ts -> src/actions/DialogAction.ts -> src/index.tsx
created lib in 17.5s

./src/index.tsx → esm...
(!) Circular dependency
src/index.tsx -> src/actions/index.ts -> src/actions/DialogAction.ts -> src/index.tsx
created esm in 14.2s

> amis-ui@3.1.0 build
> npm run clean-dist && NODE_ENV=production rollup -c


> amis-ui@3.1.0 clean-dist
> rimraf lib/** esm/**


./src/index.tsx, ./src/components/ColorPicker.tsx, ./src/components/BarCode.tsx, ./src/components/Markdown.tsx, ./src/components/Tinymce.tsx, ./src/components/RichText.tsx, ./src/components/CityDB.ts, ./scss/themes/antd.scss, ./scss/themes/ang.scss, ./scss/themes/cxd.scss, ./scss/themes/dark.scss, ./scss/themes/default.scss, ./scss/helper.scss → lib...
(!) Circular dependencies
src/components/formula/Editor.tsx -> src/components/formula/plugin.ts -> src/components/formula/Editor.tsx
src/components/json-schema/Item.tsx -> src/components/json-schema/Array.tsx -> src/components/json-schema/Item.tsx
src/components/json-schema/Item.tsx -> src/components/json-schema/Object.tsx -> src/components/json-schema/Item.tsx
...and 4 more
created lib in 1m 17s

./src/index.tsx, ./src/components/ColorPicker.tsx, ./src/components/BarCode.tsx, ./src/components/Markdown.tsx, ./src/components/Tinymce.tsx, ./src/components/RichText.tsx, ./src/components/CityDB.ts → esm...
(!) Circular dependencies
src/components/formula/Editor.tsx -> src/components/formula/plugin.ts -> src/components/formula/Editor.tsx
src/components/json-schema/Item.tsx -> src/components/json-schema/Array.tsx -> src/components/json-schema/Item.tsx
src/components/json-schema/Item.tsx -> src/components/json-schema/Object.tsx -> src/components/json-schema/Item.tsx
...and 4 more
created esm in 43s

> amis@3.1.0 build
> npm run clean-dist && sh build.sh

npm WARN ignoring workspace config at /Users/shufeng/study/amis-test/amis/packages/amis/.npmrc 

> amis@3.1.0 clean-dist
> rimraf lib/** esm/**

===rollup build===

./src/index.tsx → lib...
(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
src/renderers/Chart.tsx
61:                     try {
62:                         if (!(code in EVAL_CACHE)) {
63:                             EVAL_CACHE[code] = eval('(' + code + ')');
                                                   ^
64:                         }
65:                         object[key] = EVAL_CACHE[code];
created lib in 36s

./src/index.tsx → esm...
(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
src/renderers/Chart.tsx
61:                     try {
62:                         if (!(code in EVAL_CACHE)) {
63:                             EVAL_CACHE[code] = eval('(' + code + ')');
                                                   ^
64:                         }
65:                         object[key] = EVAL_CACHE[code];
created esm in 41.2s
===fis sdk===

 [INFO] Currently running fis3 (/Users/shufeng/study/amis-test/amis/node_modules/fis3)

 δ 1174ms

 Ω .................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
 [WARNI] Can't resolve `fs` in file [/node_modules/xlsx/xlsx.js], did you miss `npm install fs`?

 [WARNI] Can't resolve `stream` in file [/node_modules/xlsx/xlsx.js], did you miss `npm install stream`?
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... 160.64s
===postcss ie11===
===sdk locale===
===build-schemas===
npm WARN ignoring workspace config at /Users/shufeng/study/amis-test/amis/packages/amis/.npmrc 

> amis@3.1.0 build-schemas
> ts-node -O '{"target":"es6"}' ../../scripts/build-schemas.ts

**Comment by blankzust** [comment]
不算上npm install的时间，本地打包6分钟

**Comment by 2betop** [comment]
> <img alt="image" width="842" src="https://user-images.githubusercontent.com/8541906/252836560-434b747a-1c44-4168-b73c-b9d9a426f5b8.png"> 本地打包到最后一步报错了

这个应该是前面依赖的包没打成导致的，直接 `npm run build` 运行可以正常

6 分钟时间还好吧，又不是一直都要打包。即打 cjs 的包有打 esm 的包，同时整体还要打个 jssdk 的包，额外还需要读取所有 ts 生成 jsonschema。

**Comment by blankzust** [comment]
我很好奇，jssdk是干嘛的，求大神们提供源码解析的文档，为啥jssdk要单独用fis来打包？

**Comment by blankzust** [comment]
一般来说jssdk是用来给js提供改变环境的方法，比如说app开发web-view的时候，会提供一些jsbridge方法给h5，这个jssdk是给h5提供改变json的方法吗？

**Comment by Icodezhan** [comment]
说实话有点钻牛角尖了，又不是频繁打包发布版本，你看官方也就一个月才打包一次发版。又不差这几分钟，这几分钟用来摸鱼喝杯水不香吗，真要把自己卷死吗？

**Comment by blankzust** [comment]
一方面是想要提高一下打包的体验（私域打包的平台有时间限制），另一方面想要深入了解一下amis的源码

**Comment by 2betop** [comment]
jssdk 给不会前端的同学用的，引一段 js 剩下就是写 amis 配置，具体看 https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/getting-started#sdk 

如果对打包要求，欢迎提个 pr ，新增个 npm script ，只打包 esm 版本，供 npm 方式使用。

**Comment by blankzust** [comment]
> jssdk 给不会前端的同学用的，引一段 js 剩下就是写 amis 配置，具体看 https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/getting-started#sdk
> 
> 如果对打包要求，欢迎提个 pr ，新增个 npm script ，只打包 esm 版本，供 npm 方式使用。

好滴，我刚好在学习amis源码，我来做一下这个事情

**Comment by 932808140** [comment]
我这边已经在Linux环境打完包了，出现lib和esm文件了，之后怎么部署呢？
![image](https://github.com/baidu/amis/assets/75246269/636355e4-8524-4438-bb29-44560d0226d5)
