### ISSUE TITLE
【editor代码组件】使用sdk的amis.embed渲染时，不显示初始值

### ISSUE THREAD

**Issue by zhushibo** [baidu/amis#7450]
#### 描述问题：

我在编辑器中获取数据给editor组件一个初始值，在amis-editor编辑器中预览正常
在渲染器中（详情页）使用 amis/embed 来渲染，但是editor组件中代码不显示

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/26269311/46cc7f31-20ef-4a8f-9050-4d9975f98567)
这是使用amis-editor的编辑器中预览效果，完全正常

![image](https://github.com/baidu/amis/assets/26269311/26ad2290-4d70-4595-9aee-2921e3fc8ddc)
这是是用sdk渲染的结果，不显示代码，并且确认数据已经获取

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
点击按钮，打开抽屉，抽屉中使用service请求接口，然后赋值到 editor的tpl中。（此处换code插件可以显示，但是没有高亮）

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
编辑器：
```
    "amis": "^3.2.0",
    "amis-core": "^3.2.0",
    "amis-editor": "^5.3.0",
    "amis-editor-core": "^5.3.0",
    "amis-formula": "3.0.0",
    "amis-ui": "^3.2.0"
```
渲染器：
```
    "amis": "^3.2.0",
```

3. 粘贴有问题的完整 `amis schema` 代码：
一下为按钮触发抽屉的完整代码，url请自行补充
```
{
  "type": "tpl",
  "id": "u:b0949158d126",
  "onEvent": {
    "click": {
      "weight": 0,
      "actions": [
        {
          "actionType": "drawer",
          "drawer": {
            "type": "drawer",
            "title": "抽屉标题",
            "body": [
              {
                "type": "service",
                "id": "u:792bc195496c",
                "body": [
                  {
                    "type": "editor",
                    "id": "u:4beb9e713882",
                    "name": "editor",
                    "value": "${schema}",
                    "language": "json",
                    "label": "schema代码",
                    "autoFill": {
                    },
                    "disabled": true
                  },
                  {
                    "type": "editor",
                    "id": "u:4beb9e713882",
                    "label": "css代码",
                    "name": "editor",
                    "value": "${css}",
                    "language": "css",
                    "autoFill": {
                    },
                    "disabled": true
                  }
                ],
                "messages": {
                },
                "api": {
                  "url": "xxxxx",
                  "method": "get"
                }
              }
            ],
            "className": "app-popover",
            "id": "u:11cad9a02cab",
            "actions": [
            ],
            "closeOnOutside": true
          }
        }
      ]
    }
  },
  "tpl": "查看配置",
  "inline": true,
  "wrapperComponent": "",
  "style": {
    "fontSize": "14px",
    "color": "#7ed321"
  }
}
```

5. 操作步骤
点击查看配置，弹出抽屉，amis编辑器显示正常，amis sdk渲染不显示editor编辑的内容

**Comment by 2betop** [comment]
运行态没有 ${schema}

**Comment by zhushibo** [comment]
> 运行态没有 ${schema}

但是我在抽屉的input里面已经显示出来了，${schema}值是有的，只是在code这个组件内不显示，其它组件都正常

**Comment by shaofq** [comment]
问题解决了吗？@zhushibo 我也有这问题

**Comment by shaofq** [comment]
我是提示这个错误，http://localhost:9000/node_modules/.vite/deps/thirds/monaco-editor/min/vs/loader.js net::ERR_ABORTED 504 (Outdated Optimize Dep)，我是在vue3中进行使用的

**Comment by zhushibo** [comment]
> 我是提示这个错误，http://localhost:9000/node_modules/.vite/deps/thirds/monaco-editor/min/vs/loader.js net::ERR_ABORTED 504 (Outdated Optimize Dep)，我是在vue3中进行使用的

没解决😂，可能得自己去调试看看了。我的没报错，你这个看着是vite配置的问题

**Comment by shaofq** [comment]
没解决，你重新open一下，要不都没人管了

**Comment by shaofq** [comment]
以前用过echarts也是这个错误后来发现是需要引入amis/sdk/echarts.js，这个我看在amis/sdk/thirds文件夹下面有这个，但是引入不起作用同样报错，是这样引入的 import 'amis/sdk/thirds/monaco-editor/min/vs/loader.js'

**Comment by shaofq** [comment]
![image](https://github.com/baidu/amis/assets/28698892/a3491f2c-c991-4737-ba99-ca3e9f787f4a)
引入后包这个错误

**Comment by zhushibo** [comment]
> 没解决，你重新open一下，要不都没人管了

我好像open不了

**Comment by Lisheri** [comment]
> 我是提示这个错误，http://localhost:9000/node_modules/.vite/deps/thirds/monaco-editor/min/vs/loader.js net::ERR_ABORTED 504 (Outdated Optimize Dep)，我是在vue3中进行使用的

请问解决了吗, 我也是这样的问题~

**Comment by Lisheri** [comment]
> > 我是提示这个错误，http://localhost:9000/node_modules/.vite/deps/thirds/monaco-editor/min/vs/loader.js net::ERR_ABORTED 504 (Outdated Optimize Dep)，我是在vue3中进行使用的
> 
> 请问解决了吗, 我也是这样的问题~

![image](https://github.com/baidu/amis/assets/49238808/5fc5b74a-bd93-4dd5-9ee9-1ea616d25457)

**Comment by Lisheri** [comment]
https://github.com/baidu/amis/issues/2655
这里有方案了~
