### ISSUE TITLE
想在adaptor中获取数据域的数据，文档说可以通过 api.data 获得数据域里的内容，实际情况是undefined

### ISSUE THREAD

**Issue by WangXueZhi** [baidu/amis#7454]
#### 描述问题：

想在adaptor中获取数据域的数据，文档说可以通过 api.data 获得数据域里的内容，实际情况是undefined

#### 截图或视频：
<img width="668" alt="iShot_2023-07-12_05 00 28" src="https://github.com/baidu/amis/assets/6176392/d800e2c5-0a58-4271-a88b-0a4e5fe9f5cf">

![iShot_2023-07-12_04 53 52](https://github.com/baidu/amis/assets/6176392/e9f7caa3-fc39-45ea-9b79-d8a664039ded)

<img width="201" alt="iShot_2023-07-12_05 04 59" src="https://github.com/baidu/amis/assets/6176392/133477bc-1f7e-459f-a617-747a372bab12">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.2.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
"adaptor": "console.log('initapi', api, api.data); return payload;"
```

4. 操作步骤

**Comment by 2betop** [comment]
api.data 是接口发送的数据，如果没有配置是拿不到的。等这个 pr #7456 合入后可以通过 context 变量拿请求发送前的上下文数据

**Comment by WangXueZhi** [comment]
ok, 感谢
