### ISSUE TITLE
请问有组件的文档吗  不是直接以json格式那种，是跟element antd那种的组件。

### ISSUE THREAD

**Issue by Gwq01** [baidu/amis#7457]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
amis-ui 目前没有文档，只有简单示例，启动后通过 http://localhost:8888/packages/amis-ui/#/ 访问，可以从源码中的名字和 props 了解功能及配置，但因为只有内部使用所以可能经常 breaking change
