### ISSUE TITLE
CRUD下的cards模式分页异常

### ISSUE THREAD

**Issue by yahahawork** [baidu/amis#7458]
#### 描述问题：

CRUD下的cards模式分页设置无效

#### 截图或视频：

perPage设置为20时显示只有10个
![image](https://github.com/baidu/amis/assets/104351842/2cf42d39-849a-462c-8e40-9f06da450dda)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
`3.2`

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "crud",
    "api": "/amis/api/mock2/crud/table4",
    "syncLocation": false,
    "mode": "cards",
    "defaultParams": {
      "perPage": 20
    },
    "switchPerPage": true,
    "placeholder": "没有用户信息",
    "columnsCount": 4,
    "card": {
      "header": {
        "title": "$engine",
        "subTitle": "$browser",
      }
    }
  }
}
```

**Comment by 2betop** [comment]
mock 接口没有用传过来的  perPage，而是写死的，既然是 mock 接口，就不改了 
https://github.com/baidu/amis/blob/master/mock/cfc/mock/crud/table4.js#L3
