### ISSUE TITLE
在页面内刷新会报error

### ISSUE THREAD

**Issue by ClarenceStar** [baidu/amis#746]
我正在做一个实时预览的功能 左边是render的内容 右边是编辑器 两者在同一个组件内 刷新页面会报个error 
![image](https://user-images.githubusercontent.com/15528239/86909984-8b2e5980-c14b-11ea-8661-d7556c2178b1.png)
![image](https://user-images.githubusercontent.com/15528239/86909991-8e294a00-c14b-11ea-8309-c98d20b062c8.png)
但是schema我一开始在constrctor就从props开始取了(从mobx的store中) 肯定是拿到了 刷新的瞬间发现控制台一开始的json是未展开的 是因为异步的原因?我发现我写死那个schema也会出现出现

**Comment by nwind** [comment]
我们代码里没有这种 alert，自己查查吧，感觉是 fetcher
