### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by Gwq01** [baidu/amis#7467]
#### 实现场景：
在React  项目中直接以amis作为组件库来使用，与使用element 和 antd一样的方式请问这种方式能实现吗。

#### 存在的问题：
不清楚使用方法，没有具体的文档，亦或者没有暴露出来，需要在源码中去寻找使用方式
#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
![image](https://github.com/baidu/amis/assets/96569767/c6cf0230-a90b-4286-94c7-a48dd7ebeb0f)
![image](https://github.com/baidu/amis/assets/96569767/d1c1b0a7-70d0-495d-b4ea-9b889d0ab1c9)
请问可以以这种方式进行编写吗？
```
code here...
```

**Comment by 2betop** [comment]
可以这么写，但是目前没问题，需要自行查看源码。建议还是用 amis ，json 的方式调用，这块文档比较齐全
