### ISSUE TITLE
请问Table如何展示静态数据？

### ISSUE THREAD

**Issue by chareice** [baidu/amis#747]
https://baidu.github.io/amis/docs/renderers/Table
Table能否指定一个Array Of Object作为数据源呢？

**Comment by 2betop** [comment]
source: "${varName}" 支持这么配置

**Comment by chareice** [comment]
> source: "${varName}" 支持这么配置

这个变量在哪里可以注入进去呢，看了Page和Service都得从API获取，能不能不走API直接写入静态的数据？

**Comment by 2betop** [comment]
如果是 props 里面传，直接通过 items 这个属性。或者参考这个里面的写死数据。https://baidu.github.io/amis/crud/merge-cell

**Comment by chareice** [comment]
> 如果是 props 里面传，直接通过 items 这个属性。或者参考这个里面的写死数据。https://baidu.github.io/amis/crud/merge-cell

谢谢，这个data属性可以解决问题，建议增加到文档里 🤩
