### ISSUE TITLE
询问开发问题

### ISSUE THREAD

**Issue by onlyThat** [baidu/amis#7470]
#### 实现场景：
如何在编辑器crud右侧添加一个标签栏？ 模型列表中右侧为三个标签栏，怎样才能添加？ crud只能有俩

#### 存在的问题：
目前研究了源码无法实现百度amis官网的 模型列表 模型表单那种功能，能告知下怎么实现吗
![微信图片_20230704111759](https://github.com/baidu/amis/assets/114373085/08c5264b-6383-4087-9899-ee60f5b56709)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
![微信图片_20230704111759](https://github.com/baidu/amis/assets/114373085/08c5264b-6383-4087-9899-ee60f5b56709)

```
code here...
```

**Comment by 2betop** [comment]
插件中注册 buildEditorPanel 钩子，额外加个 panel 即可
