### ISSUE TITLE
CRUD组件 搜索栏展开和收起按钮消失

### ISSUE THREAD

**Issue by Seizedays233** [baidu/amis#7471]
#### 描述问题：
autoGenerateFilter.columnsNum=3并且实际搜索项目数量为5的时候 搜索栏的展开/收起按钮会消失， 搜索项目数量为6的时候才会出现

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/54106885/b07f5960-0103-46b9-9d4c-e105b169fa33)
![image](https://github.com/baidu/amis/assets/54106885/4af4b8fa-481c-4e88-bdc6-4335c3a28f53)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
当前的master分支的代码build之后的版本
3. 粘贴有问题的完整 `amis schema` 代码：
```
          autoGenerateFilter: {
            "columnsNum": 3,
            "defaultCollapsed": false,
            "showBtnToolbar": false
          },
```

4. 操作步骤
autoGenerateFilter按照我写的配置， 改变搜索项目的数目即可复现 用v3.2.0版本是正常的 使用当前master分支的代码就会出现这个问题

**Comment by lvjinwei1688** [comment]
好兄弟，能提供下这个条件所有的代码呢 我想换个跟你一样的样式

**Comment by Seizedays233** [comment]
来看看这个问题呀
