### ISSUE TITLE
文档中 快速入门例子有问题，对应的md文件是正确的，希望更新下文档

### ISSUE THREAD

**Issue by mieuf** [baidu/amis#748]
https://baidu.github.io/amis/docs/getting-started 
JSSDK 方式
完整示例:
里面css跟js的引用错了
` <link rel="stylesheet" href="amis/sdk.js" />`
` <script src="amis/sdk.css"></script>`

**Comment by RickCole21** [comment]
多谢提醒，https://baidu.github.io/amis/docs/start/getting-started#sdk
