### ISSUE TITLE
crud 的Table 表格显示间隔

### ISSUE THREAD

**Issue by lvjinwei1688** [baidu/amis#7481]
#### 实现场景：
我想在查询后 实现Table 表格 显示的间隔 有没有样式来增加每条数据的间宽

#### 存在的问题：
able 表格  加完 表格线框后想增加下面每条数据都加上表间距           'columnsTogglable': false,
            'affixHeader': false,
            'combineNum': 1, 想增加下面的表间距
![image](https://github.com/baidu/amis/assets/48401565/c297243b-b003-4dea-be06-709e398ab70d)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
            'columnsTogglable': false,
            'affixHeader': false,
            'combineNum': 1,
            columns: [
              {
                name: 'device_id',
                label: '设备编号',
                type: 'text',
                id: 'u:0f48965e03cc'
              },
              {
                name: 'device_type',
                label: '设备类型',
                type: 'text',
                id: 'u:0f48965e3cc'
              },
              {
                name: 'app_version',
                label: 'app版本',
                type: 'text',
                id: 'u:0f48965e3cc'
              },

```
code here...
```

**Comment by lvjinwei1688** [comment]
我是用的sdk 版本为3.2

**Comment by lvjinwei1688** [comment]
还有作者大大 就是table 表单的内容可以居中显示么

**Comment by 2betop** [comment]
这个请通过附加 css 来实现，amis 测没有相关配置
