### ISSUE TITLE
利用Custom组件开发自定义组件的问题

### ISSUE THREAD

**Issue by large2b** [baidu/amis#7484]
#### 自定义组件：
官方文档中提到：
> 基于 custom 组件可以直接在 amis 配置实现自定义功能，是唯一支持在可视化编辑器中使用的方法。
> ... 解决了JS SDK 和可视化编辑器中难以支持自定义组件的问题

利用 Cutom 组件自定义一个临时的组件，或者 在可视化编辑器中实现一个插件，但好像仅限于此了。

有没有可能 通过 type 为 custom 的 json 自定义一个可复用的组件，比如：利用 custom 自定义一个 组件 my-custom, 然后我在就可以像实现一个新类型一样，通过在 amis 配置中 设置 **type: 'my-custom'**  从而渲染 自定义的组件

**Comment by 2betop** [comment]
你说的组件模版功能，平台中会集成此功能，amis 测不打算支持了

**Comment by TYBWANG** [comment]
我的项目中使用 json schema 构建组件 my-custom，
然后引用该 json文件自定义React Component，
最后注册成amis组件my-custom。
这样就可以在其他json schema中 通过  type: "my-custom" 使用自定义组件了。
我已在多个项目中使用这种方案，非常方便。

详情见
https://github.com/TYBWANG/tyb-amis-admin
