### ISSUE TITLE
3.2.0 dispatchEvent功能异常

### ISSUE THREAD

**Issue by tujiajun** [baidu/amis#7488]
#### 描述问题：

之前开发了一个react组件，把它封装成amis组件了，能成功利用dispatchEvent去触发各类事件，在3.2.0之前都是没问题的，只有在引用了3.2.0之后，dispatchEvent无法触发事件了

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.2.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
export const FullCalendar = ({ 
  dispatchEvent: amisDispatchEvent, 
  data: amisData,
  ...props }
) =>{
...
const dispatchEvent = async (action: string, value?: object) => {

    if (!amisDispatchEvent) return;
    const rendererEvent = await amisDispatchEvent(
      action,
      value ? createObject(amisData, value) : amisData
    );
    return rendererEvent?.prevented ?? false;
 }
  
dispatchEvent('getRef', {calendarRef})
...
}
```

4. 操作步骤

**Comment by hsm-lv** [comment]
没有复现你的问题

**Comment by tujiajun** [comment]
> 没有复现你的问题
我研究了一下源码，发现是childRef中未判断ref.getWrappedInstance()为undefined的情况，导致后面给this.cRef赋了undefined，稍微加了个判断之后，这个问题貌似就解决了，不知是否是这边漏了这一个判断
![image](https://github.com/baidu/amis/assets/127007861/47adb27b-d0b3-42c2-880c-0e1741e2158e)

**Comment by tujiajun** [comment]
如果希望重现，可以按照如下操作：

- 跑好amis源码项目，https://github.com/baidu/amis
- build amis 源码项目暴露sdk.js文件
- 运行华炎魔方模板项目 https://github.com/steedos/steedos-project-template
- 在yarn start前先在env.local文件中配置好环境变量
   STEEDOS_AMIS_URL=${amis访问url}/packages/amis //用于让魔方项目引用这个地址下的sdk.js文件
- PC上访问运行好的华炎魔方项目，使用用户名密码登录进入系统内，可能要先点击注册按钮注册本地账户
- 访问这个路径 /app/admin/events/grid/calendar_view，可进入出现该问题的组件
- 通过改amis源码并build生成新的sdk.js文件就可以调式此问题

**Comment by hsm-lv** [comment]
> > 没有复现你的问题
> 
> 我研究了一下源码，发现是childRef中未判断ref.getWrappedInstance()为undefined的情况，导致后面给this.cRef赋了undefined，稍微加了个判断之后，这个问题貌似就解决了，不知是否是这边漏了这一个判断 ![image](https://user-images.githubusercontent.com/127007861/254446285-47adb27b-d0b3-42c2-880c-0e1741e2158e.png)

按理说不应该出现undefined

**Comment by tujiajun** [comment]
@hsm-lv 你好，请问这个issue是不能处理吗

**Comment by tujiajun** [comment]
https://github.com/steedos/steedos-widgets/commit/924a9f32bb2739c6bf77658e7d48dabe776239d6
![image](https://github.com/baidu/amis/assets/127007861/bbe888d4-446c-4cf1-8c95-6f3919baa790)
![image](https://github.com/baidu/amis/assets/127007861/8326dc48-6cd6-4fa7-8adf-7513a06bbcd8)
目前是通过主动传ref，暂时解决了，但是还是建议官方在childRef函数内增加一下对getWrappedInstance()返回值为空的判断，不应该把空值赋给ref
