### ISSUE TITLE
组件是否可以提供getValue获取数据的方法

### ISSUE THREAD

**Issue by skj198568** [baidu/amis#7491]
#### 是否关联于某个问题吗：
组件中的某个自定义事件custom中，可以通过content.props获取上下文的数据。如果想获取不同数据域下的组件的数据，进行计算就比较困难。

#### 预期的解决方案：
目前解决的办法是通过事件，将当前组件的数据存入store中，然后在其他组件中获取store中存储的数据。或者是创建一个service，将数据都setValue到这个service中，再进行计算。如果组件提供了getValue方法，可以根据doAction来获取某个组件的数据，这样对于复杂多组件间的数据操作方便多了。

#### 任何附加信息：
暂无

**Comment by 2betop** [comment]
可以用此公式来实现 https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E8%8E%B7%E5%8F%96%E7%BB%84%E4%BB%B6%E7%9B%B8%E5%85%B3%E6%95%B0%E6%8D%AE
