### ISSUE TITLE
数据映射join,如何传入'|'来把数组转换字符串，如[1,2,3] => 1|2|3

### ISSUE THREAD

**Issue by liugonghe** [baidu/amis#7492]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by liugonghe** [comment]
"onEvent": {
                                      "click": {
                                        "actions": [
                                          {
                                            "actionType": "setValue",
                                            "componentId": "playAreas-add",
                                            "args": {
                                              "value": "$@{selectedItems|pick:countryCode|join[:|]}"
                                            }
                                          }
                                        ]
                                      }
                                    }

**Comment by 2betop** [comment]
有 bug，被当成 filter 指令了，我们处理一下

**Comment by 2betop** [comment]
#7635 修复后可以通过这种方式实现 `${JOIN([1, 2, 3], "|")}`

**Comment by liugonghe** [comment]
好的，谢谢。 我看了源码，是通过split切割‘|’来分步调用各函数。我目前是通过register自定义函数处理了。
