### ISSUE TITLE
编辑表格，数据无法自动更新

### ISSUE THREAD

**Issue by taoyao-code** [baidu/amis#7496]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：
<img width="1075" alt="image" src="https://github.com/baidu/amis/assets/38855041/df0edb1a-91c7-4d85-9627-d1d6d04ed55b">
<img width="1067" alt="image" src="https://github.com/baidu/amis/assets/38855041/381f87d4-1c5f-4a29-a75b-811ffc0137fc">
<img width="1270" alt="image" src="https://github.com/baidu/amis/assets/38855041/8bfb75bf-3193-412b-a9e7-08c30197bec9">

在编辑表格数据时，列表渲染的数据只获取到了第一条的数据(总金额)， 手动修改数据，下方的总金额才会变动。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新
3. 粘贴有问题的完整 `amis schema` 代码：
```

```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
跟这个类似 https://github.com/baidu/amis/issues/7582 ，请配置 strictMode: false, 有问题再开
