### ISSUE TITLE
如何初始化设置crud组件的selectedItems

### ISSUE THREAD

**Issue by liugonghe** [baidu/amis#7497]
#### 实现场景：
比如点击输入框的addOn，弹框展示一个列表，然后选择了几条数据赋值给了输入框，下次再点击addOn按钮，如何在弹框列表中初始化上次的selectedItems？或者第一次编辑输入框的时候，如何根据输入框的初始化selectedItems？

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
不能配置

**Comment by 2betop** [comment]
建议用 picker 实现

**Comment by liugonghe** [comment]
picker可以满足，thanks

**Comment by flysmallstrong** [comment]
官网https://aisuda.bce.baidu.com/amis/zh-CN/components/form/picker     picker demo, 直接点击多选框, 是选不中的, 必须要偏离一点点,  点击到空白处, 才能选中

**Comment by skj198568** [comment]
用table也可以，table有个select动作，来控制选中。
