### ISSUE TITLE
RichText 还有无法触发更新的问题

### ISSUE THREAD

**Issue by chenos** [baidu/amis#750]
https://github.com/baidu/amis/blob/90c10d74c5266266bdbcdf43708ebee9e96dae2d/src/renderers/Form/RichText.tsx#L239

使用场景：表单单独页面，提交之后跳回crud页
使用中发现 disabled 刚开始是 undefined，但是提交数据之后变成了 true，导致 onChange 无效，数据无法更新。

**Comment by chenos** [comment]
还有个问题，TinyMCE 上传图片，图片地址在当前域下，会被更新为相对地址。

**Comment by nwind** [comment]
目前代码已经改很多了，还有问题就再报吧
