### ISSUE TITLE
Module not found worker_threads

### ISSUE THREAD

**Issue by UltramanWeiLai** [baidu/amis#7501]
#### 描述问题：
```
WARNING in ./node_modules/fflate/lib/node.cjs 15:13-45
Module not found: Error: Can't resolve 'worker_threads' in '/Users/orb/Desktop/feisu/basic-platform/form-manage/node_modules/fflate/lib'
```

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/23336585/68b4990c-2e07-4c3d-86cb-bb69f2a663fa)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm 16 and 18

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.2.0

4. 粘贴有问题的完整 `amis schema` 代码：
运行就报错

5. 操作步骤
运行就报错

**Comment by 2betop** [comment]
这是脚本？不能复现！

**Comment by UltramanWeiLai** [comment]
> 这是脚本？不能复现！

不是脚本，就是正常的用 webpack 运行项目，本质上好像是因为 office-viewer 这个依赖中，有用到 node 宿主环境的 `worker_threads`  所以报警告了

**Comment by mathYang1224** [comment]
我也遇到了同样的错误

**Comment by nwind** [comment]
webpack 加一下配置 `conditionNames: ['require', 'browser', 'web']`

**Comment by UltramanWeiLai** [comment]
> webpack 加一下配置 `conditionNames: ['require', 'browser', 'web']`
@nwind 谢谢，修改了 conditionNames 的配置后这个问题解决了！
