### ISSUE TITLE
官网https://aisuda.bce.baidu.com/amis/zh-CN/components/form/picker picker demo, 直接点击多选框, 是选不中的, 必须要偏离一点点, 点击到空白处, 才能选中

### ISSUE THREAD

**Issue by flysmallstrong** [baidu/amis#7504]
如标题所述.  不管是基本用法, 还是配置 pickerSchema,内嵌模式 . 点击框体本身没有响应, 只有点击旁边的空白处, 框体才能被选中.

**Comment by 2betop** [comment]
官网更新较慢，新版本已无此问题，可在此验证 https://baidu.github.io/amis/zh-CN/components/form/picker
