### ISSUE TITLE
直接使用 amis-core 无法在 React18 严格模式中工作

### ISSUE THREAD

**Issue by StringKe** [baidu/amis#7513]
项目工具 https://nx.dev/packages/react

使用 nx 创建 react vite 项目后独立使用 amis-core 这个进行渲染，默认 react 会打开严格模式，在这个模式下会出现 

Uncaught Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'RootStore', Path upon death: '', Subpath: 'id', Action: '.removeStore()'). Either detach nodes first, or don't use objects after removing / replacing them in the tree.

可能是 mobx 老版本不适配 React 18 导致

React 18的升级可以发一下对应的计划么？我可以帮助实现。

**Comment by 2betop** [comment]
目前无法支持严格模式，内部是在 constructor 和 willUnmount 中负责 mst store 的创建与销毁。严格模式的话得换成 didMount 和 willUnmount 来实现，改动有点大

**Comment by eminoda** [comment]
未来会有版本对 严格模式 做优化码？
