### ISSUE TITLE
Combo的Tab模式下的tab名字tabsLabelTpl可以自定义成表单中的某个字段吗？

### ISSUE THREAD

**Issue by zhangyucumt** [baidu/amis#752]
由于要添加的tab比较多  用成员 1、2、3 这样显示的话，会不好区分哪个tab是对应的是哪个表单，可以用表单中的某个唯一字段来表示tab的名字吗？

**Comment by 2betop** [comment]
可以的，语法：https://baidu.github.io/amis/docs/renderers/Tpl
