### ISSUE TITLE
3.2.0版本, 官网的JSONSchema Editor 文档中开启高级配置,正常显示弹窗.  在本地无弹框. 

### ISSUE THREAD

**Issue by flysmallstrong** [baidu/amis#7520]
官网文档中的版本是与发布最新版版本保持一致吗?

**Comment by nabaonan** [comment]
本地跑了一下3.2，可以弹框
<img width="1004" alt="image" src="https://github.com/baidu/amis/assets/17247526/062f7fe0-a9c9-47b6-b363-6beb33198f13">

**Comment by nabaonan** [comment]
确实没弹框，复现链接：https://codesandbox.io/s/test-amis-nvjgl5

**Comment by 2betop** [comment]
3.3 会支持，已经合入代码 https://github.com/baidu/amis/pull/7329
