### ISSUE TITLE
index.7916cdcc.mjs:53504 Error: <g> attribute transform: Trailing garbage, "…late(-1.338385, micro-app[name=b…".

### ISSUE THREAD

**Issue by mathYang1224** [baidu/amis#7521]
#### 描述问题：

微前端MIcro-app下边貌似D3报错，但是页面有什么问题还没发现，只是控制台报错

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/45762245/24728340-1e4e-4237-87d1-be3a2c2121f4)
![image](https://github.com/baidu/amis/assets/45762245/915b0c4a-14b9-4c31-9f2a-bc126028257b)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
node 16.14.0 npm 8.3.1 pnpm 6.35.1
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.2.0
3. 粘贴有问题的完整 `amis schema` 代码：
```

```

4. 操作步骤

**Comment by 2betop** [comment]
看起来跟 amis 无关，amis 中没有使用 d3 库。
