### ISSUE TITLE
页面之间触发组件reload没有效果

### ISSUE THREAD

**Issue by mjqjhn** [baidu/amis#7523]
#### 描述问题：

使用sdk2.7.2按钮触发另一个页面的crud的reload事件可以重新请求数据，同一个代码使用sdk3.2.0，reload事件不能刷新crud的数据刷新

#### 截图或视频：

![1689754105594](https://github.com/baidu/amis/assets/52816698/fd1be205-87cc-49f7-9074-adbeb9a06044)
![1689754105594](https://github.com/baidu/amis/assets/52816698/0f717adb-3aac-4adf-b283-e15cbbf8095e)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.2.0

3. 粘贴有问题的完整 `amis schema` 代码：
crud事件
"onEvent": {
    "refreshList": {
      "weight": 0,
      "actions": [
        {
          "componentId": "u:6db954704c51",
          "groupType": "component",
          "actionType": "reload"
        }
      ]
    }
  }
触发按钮
{
  "type": "button",
  "label": "按钮",
  "onEvent": {
    "click": {
      "actions": [
        {
          "script": "  doAction({\n  actionType: \"broadcast\",\n  eventName: \"refreshList\",\n  data:null\n})",
          "actionType": "custom"
        },
        {
          "componentId": "u:6db954704c51",
          "groupType": "component",
          "actionType": "reload"
        }
      ]
    }
  },
  "id": "u:ad0a2186e0f1"
}

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by mjqjhn** [comment]
![1689754635272](https://github.com/baidu/amis/assets/52816698/42d8d56a-d09f-4f6d-97bb-842bb82a7da6)
2.7.2

**Comment by hsm-lv** [comment]
看起来是触发了reload动作了，问题是页面没重新渲染还是什么？检查一下数据变了没有呢

**Comment by mjqjhn** [comment]
> 看起来是触发了reload动作了，问题是页面没重新渲染还是什么？检查一下数据变了没有呢

没有触发crud的数据请求

**Comment by hsm-lv** [comment]
> 数据

最好有完整的代码，或者看看新版本

**Comment by BOOM-0** [comment]
解决了吗？方便发一份解决代码吗
