### ISSUE TITLE
SDK能否提供sourcemap，方便调试

### ISSUE THREAD

**Issue by sphui** [baidu/amis#7528]
## 概述

简单地描述这项功能。

## 动机

为什么要做出这个更改？应对什么样的场景？会产生什么结果?

## 示例

如果提案新增或更改 JSON 配置。

## 详细设计

可选。

## 缺陷

我们是不是可以不做这个功能，请考虑：

- 实现这个功能的投入：包括代码的复杂度、代码体积的增加
- 这个功能是不是不需要 amis 提供，比如基于 amis 自己扩展更合适
- 对 amis 现有功能的影响，以及用户进行迁移的成本

## 替代选择

还有其他的方案也可以实现这个功能吗？

## 适配策略

如果我们实现了这个提案，有没有什么办法可以帮助开发者更好地适应这个改动？

**Comment by 2betop** [comment]
近期不打算支持，要调试还是用 npm 包版本
