### ISSUE TITLE
请问image怎么实现图片url地址远程获取？

### ISSUE THREAD

**Issue by kkkjjjmmm** [baidu/amis#753]
image能够支持source属性吗？动态拉取需要展示图片的url地址

**Comment by nwind** [comment]
表单里？用 https://baidu.github.io/amis/docs/renderers/Form/Form#initapi

**Comment by kkkjjjmmm** [comment]
在拉取图片url的时候需要在http请求中带入多个参数，这些参数是在表单里面由用户选择的，initApi在最开始就发送了请求，带不上这些参数，还有什么其他的办法吗？

**Comment by 2betop** [comment]
service , initApi 也可以配置发送提交，并把依赖的参数写在 url 上，这样 api 就会在数据 ready 的时候开始拉取。

**Comment by kkkjjjmmm** [comment]
所以单纯的用image这个组件是无法做到动态拉取图片url，需要依靠service和initApi这类的方法？百度之后考虑给image，video，audio这类组件加上source属性吗？

**Comment by 2betop** [comment]
你要返回的时图片内容，你可以直接用 src 啊， src: "http://xxxx?xx=${xx}"
