### ISSUE TITLE
Form嵌套Form的场景下在第二个Form里面使用Combo组件，点击外层提交按钮时里面的必填项不会做校验

### ISSUE THREAD

**Issue by mttmeng** [baidu/amis#7539]
#### 描述问题：

当form 表单里面有 crud 时，跳转页码输入后，按enter跳转，会同时触发form提交和 crud 页码跳转。 希望：页码跳转加上按钮，手动跳转

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/38351097/82c816c9-7ef4-4cd7-bc39-69475049c67d)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v3.2.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
"type": "page",
"body": {
"type": "form",
"body": [
{
"type": "input-text",
"name": "name",
"label": "姓名：",
"required": true
},
{
"type": "form",
"body": [
{
"type": "input-text",
"name": "name1",
"label": "姓名：",
"required": true
},
{
"type": "combo",
"name": "user",
"items": [
{
"type": "input-text",
"name": "name2",
"label": "姓名：",
"required": true
}
]
}
]
}
]
}
}
```

4. 操作步骤
点击最外层表单提交按钮

**Comment by 2betop** [comment]
form 不允许嵌套 form，是一种非预期组合，按理外层提交都不应该触发内部form的校验，目前会校验的功能后续会干掉，如果你以来接口返回数据，应该用 form + service

**Comment by mttmeng** [comment]
明白了
