### ISSUE TITLE
app组件不支持嵌套吗？

### ISSUE THREAD

**Issue by chaserstrong** [baidu/amis#7540]
#### 描述问题：

app组件不支持嵌套吗？当我嵌套两个app组件时，会出现这个样式。

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/18061322/e299ec6c-bdcd-4b8e-a40c-99b99657bcbc)

我期望的是这样的：
![image](https://github.com/baidu/amis/assets/18061322/8f7a3085-bbb6-4435-8221-d946b0fba88a)

**Comment by 2betop** [comment]
app 只能顶层使用，不能嵌套

**Comment by chaserstrong** [comment]
明白了，谢谢。
