### ISSUE TITLE
input-kv为static时是折叠的json，可读性不强，能否支持nonstatic时的输入框模式

### ISSUE THREAD

**Issue by LoadingZhang** [baidu/amis#7541]
static初始状态，字段都是折叠的：
![image](https://github.com/baidu/amis/assets/10226902/ecbb66bf-848a-4e7e-89f3-720f7957d7bf)
static展开的状态，可读性比编辑模式下要弱：
![image](https://github.com/baidu/amis/assets/10226902/b4efe22d-4184-4784-813a-f8f735a7d7f3)
编辑状态下，有label的映射，可读性较强：
![image](https://github.com/baidu/amis/assets/10226902/ab03397d-e6d9-46b2-b5df-14b24feb65cd)

input-kv能否在static状态下，使用nonstatic的展示方式。

**Comment by 2betop** [comment]
可以用 disabled 态来展示
