### ISSUE TITLE
rror: Unexpected usage     at EditorSimpleWorker.loadForeignModule 

### ISSUE THREAD

**Issue by mathYang1224** [baidu/amis#7542]
#### 描述问题：

微前端micro-app 嵌套表单设计器会有这个错误

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/45762245/c2a7fdd9-c24e-42e8-a0f2-a2e148a1bed0)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
node 16.14.0
npm 8.3.1
pnpm 6.35.1

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.2.0

4. 操作步骤
微前端micro-app状态下，点击源码面板json编辑面板就会报这个错误

**Comment by mathYang1224** [comment]
![image](https://github.com/baidu/amis/assets/45762245/a9fd9189-e149-496c-acf3-470fd2cc4b01)

**Comment by 2betop** [comment]
micro-app 没用过，自己倒腾吧，monaco-editor 编译需要额外的插件，比如：monaco-editor-webpack-plugin
参考：https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-esm.md
