### ISSUE TITLE
amis-editor@5.5.0 添加了setValue/reload动作时，会自动变成key: xx, val: xxx结构，变成这个结构时动作会失效。

### ISSUE THREAD

**Issue by EvanZheng11** [baidu/amis#7543]
#### 描述问题：

amis-editor@5.5.0 添加了setValue/reload动作时，一开始我写的是"data": "${event.data.data}"结构，过一会重新打开它又自动变成了key: data, val: '${xx}'的结构，而且这个结构的动作却会失效。

#### 截图或视频：

![04a1c0cac26bce59a4576490d6993cf0](https://github.com/baidu/amis/assets/9478026/0188a2bc-fe77-4816-aadd-4140460067f9)

![af7c9e6e45f44055aa37730133a3a3ce](https://github.com/baidu/amis/assets/9478026/af2daa84-6902-4a23-b313-df7617c66362)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by hsm-lv** [comment]
没有复现这个问题
