### ISSUE TITLE
amisScoped.getComponentByName('page1.form1').getValues()

### ISSUE THREAD

**Issue by mathYang1224** [baidu/amis#7548]
#### 实现场景：
目前是根据表单名字获取组件
amisScoped.getComponentByName('page1.form1').getValues()

#### 存在的问题：
有没有一种方法可以不根据名字获取。同一个页面会有多张表单，事先不知道name值。可以根据stroeTYpe类型或者其他字段过滤吗

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
除了 `getComponentByName` 还有 `getComponentById`，给 form 配置个 id 属性，则可通过 `getComponentById('id属性')` 获取。另外可以自己找 `getComponents()` 这个会返回所有的组件，可以自己根据 `props.store.storeType`  来找
