### ISSUE TITLE
Tag标签的问题

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#755]
好久没上来，先感谢大佬更新了富文本编辑器，终于清净了。

关于Tag标签，示例里面给的tag控件都是带了“x”删除符号的，管理员在后台增删标签时比较适用。但是如果用户在前台只是展示标签，不需要也不允许用户在前端编辑标签，这要怎么处理呢？Tag控件好像没有区分是可编辑状态还是展示状态？

**Comment by RickCole21** [comment]
clearable

**Comment by 2betop** [comment]
disabled: true 没用？可以试试 clearable: false

**Comment by foxfire881** [comment]
可能是我没表述清楚，我的意思是Tag控件里面有很多小的tag标签，每个小tag标签前面还有一个"x"，管理员在后台加错了标签可以点击小tag前面的“x”删除单个tag。 但是当前需求是，如果在前端展示，普通用户只能看tag，不能编辑、增加、删除tag。

先试了clearable属性 —— 这个是对整个Tag控件里面所有的标签一次性全部删除，false的话只是后面那个全部删除的x没了，每个小tag前面的x还在，前台普通用户仍然可以在Tag控件里面增加、删除小tag。

然后试了disabled:true，无效。

![捕获](https://user-images.githubusercontent.com/273961/87378007-79bbd600-c5bf-11ea-9a80-bdc46ec43a84.PNG)

**Comment by foxfire881** [comment]
看了文档发现还有一个"text"控件，设置成多选模式后和tag控件从UI上看好像是一样的效果，不知道text多选和tag的区别是什么？
{
                    "type": "text",
                    "name": "text-sug-multiple",
                    "label": "文本提示多选",
                    "multiple": true,
                    "options": [
                        "lixiaolong",
                        "zhouxingxing",
                        "yipingpei",
                        "liyuanfang"
                    ]
},

**Comment by 2betop** [comment]
嗯，你先用 text 把，tag 没处理 disabled 的模式，这边补一下

**Comment by foxfire881** [comment]
text模式里面每个tag可以弄成带点击的吗？现在好像是静态的。能不能弄成像csdn那样每篇文章打上关键字标签，点击标签自动进入对应的分类？打标签都是为了分类，不能点击标签的话意义就不大了。

**Comment by 2betop** [comment]
你不如直接用 tpl 拼出来。

**Comment by foxfire881** [comment]
> 你不如直接用 tpl 拼出来。

最开始就是想用tpl拼出来的，后来发现有内置Tag标签所以才试了下。那我还是用tpl拼吧

**Comment by foxfire881** [comment]
报告一个bug:
text用multiple模式，并且设置clearable:true后，如果点击clear按钮，text仍然会留下一个","导致text内容并不是完全null，还残留一个空字符串和","，进而导致text框内仍然会显示一个tag，并不是完全清空。
