### ISSUE TITLE
微前端无界方式，把amis子项目嵌入抛错

### ISSUE THREAD

**Issue by free-qiaochen** [baidu/amis#7550]
#### 描述问题：
使用微前端wuJie方案，把amis子项目嵌入到其他应用中时，出现抛错；
VM5408:formatted:90102 Uncaught TypeError: (/((?:https?|file):.*?)\n/.test(...) && RegExp.$1).replace is not a function

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/24800988/aa0fec55-734e-4eed-80ae-c5c5dfa90927)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
使用的sdk方式
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
 v2.8.0版本；
3. 粘贴有问题的完整 `amis schema` 代码：
```
xxx
```

4. 操作步骤
请简单描述一下复现的操作步骤...
amis子项目嵌入到应用中，初始加载抛错；

**Comment by UltramanWeiLai** [comment]
这个问题，有解决方案吗？

**Comment by 2betop** [comment]
把 webpack 的 devtool 改成 'sourcemap', 而不是 `eval` 模式，如果是用 jssdk，还是建议直接用这个插件，不要让其参与编译
https://github.com/aisuda/vue2-amis-demo/blob/vue-cli/vue.config.js#L19-L21

**Comment by free-qiaochen** [comment]
> 用下边大佬的方式可以；

https://github.com/baidu/amis/issues/7550#issuecomment-1654823836

**Comment by free-qiaochen** [comment]
使用下边的方式嵌入，开发环境目前正常；

把 webpack 的 devtool 改成 'sourcemap', 而不是 eval 模式，如果是用 jssdk，还是建议直接用这个插件，不要让其参与编译
https://github.com/aisuda/vue2-amis-demo/blob/vue-cli/vue.config.js#L19-L21
