### ISSUE TITLE
按钮组件，点击事件，配置“下载文件”动作，文件无法下载到本地，按钮点击后无反应

### ISSUE THREAD

**Issue by liuwc121709** [baidu/amis#7564]
#### 实现场景：
按钮组件，在点击事件上配置“下载文件”动作，点击后，下载excel文件

#### 存在的问题：
尝试的两种方案
1）接口返回数据，不设置格式化"adaptor": ""，点击按钮，接口正常访问，页面提示错误（Should have "Content-Disposition" in Header），无文件下载提示
2）接口返回数据，添加如下格式化后，点击按钮，接口正常访问，页面没有错误提示，无文件下载提示
"adaptor": "return {\n    \"status\": 0,\n    \"msg\": \"\",\n    \"data\": response.data.data\n}",

接口信息：
**### request header:**
GET /xxxx?a=2&b=3
HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: EQID=db049cdb4b4c431198023593ff7137b623; JSESSIONID=09A6E0083CFB4EFB02B8FD68A08B66FD
Host: xxxxxx.com
Origin: https://xxxxxx.com/
Pragma: no-cache
Referer: https://xxxxxx.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"

**### response header:**
HTTP/1.1 200
Server: nginx/1.24.0
Date: Tue, 25 Jul 2023 02:12:21 GMT
Content-Type: application/vnd.ms-excel;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Gaia-Transaction-Id: ecd97b9b-bad6-4d8b-997b-9bbad68d8ba1
X-Gravitee-Request-Id: ecd97b9b-bad6-4d8b-997b-9bbad68d8ba1
Access-Control-Allow-Origin: https://xxxxx.com
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST, PUT, GET, OPTIONS, DELETE
Access-Control-Allow-Headers: Origin, token, X-Requested-With, Content-Type, Accept, client_id, uuid, Authorization, Referer
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Content-Disposition: attachment;filename=B4%A7%E6%95%B0%E6%8D%AE.xlsx
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
Access-Control-Expose-Headers: content-disposition

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
`{
  "type": "page",
  "pullRefresh": {
    "disabled": true
  },
  "asideResizor": false,
  "style": {
    "boxShadow": " 0px 0px 0px 0px transparent"
  },
  "id": "u:dc1cb2bf4326",
  "body": [
    {
      "tpl": "这是你刚刚新增的页面。",
      "wrapperComponent": "",
      "inline": false,
      "id": "u:a0ca47142b3f",
      "type": "tpl"
    },
    {
      "onEvent": {
        "click": {
          "actions": [
            {
              "args": {
                "api": {
                  "headers": {
                    "X-Gaia-Api-Key": "xxxx"
                  },
                  "responseType": "blob",
                  "method": "get",
                  "dataType": "json",
                  "adaptor": "return {\n    \"status\": 0,\n    \"msg\": \"\",\n    \"data\": response.data.data\n}",
                  "messages": {
                  },
                  "requestAdaptor": "",
                  "url": "https://xxx.com?aaa=1&bb=2"
                }
              },
              "actionType": "download"
            }
          ]
        }
      },
      "id": "u:10400221d62a",
      "label": "下载文件",
      "type": "button",
      "themeCss": {
        "className": {
          "padding-and-margin:default": {
            "marginTop": "40",
            "marginRight": "40",
            "marginBottom": "40",
            "marginLeft": "40"
          }
        }
      },
      "className": "className-10400221d62a"
    }
  ],
  "title": "title"
}`

**Comment by liuwc121709** [comment]
label加的不对，这是一个功能性问题咨询

**Comment by 2betop** [comment]
amis-editor-demo. 中的 fetcher 逻辑不全，https://github.com/aisuda/amis-editor-demo/blob/master/src/App.tsx#L14-L36 需要参考  https://github.com/baidu/amis/blob/master/examples/embed.tsx#L216 的实现补充相应附件处理逻辑。

**Comment by lhtuling** [comment]
出现同样的情况

**Comment by liuwc121709** [comment]
已经解决，谢谢

**Comment by PromiseYo** [comment]
怎么解决的 老哥

**Comment by xiangwenhu** [comment]
@liuwc121709 怎么解决的

**Comment by SuCicada** [comment]
amis-editor-demo. 中的 fetcher 这行代码修改：
```ts
return (axios as any)[method](url, data, config);
```
参考  https://github.com/baidu/amis/blob/01f2132847c89326edcc8ee88364cc0db0478f8e/examples/embed.tsx#L211-L212
``` ts
// return (axios as any)[method](url, data, config);

config.headers = headers
  ? {...config.headers, ...headers}
  : config.headers ?? {};
config.method = method;
config.data = data;
config.url = url;

let response = await axios(config);
response = await attachmentAdpator(response, (msg: string) => '');
return response;
```

**Comment by SuCicada** [comment]
@PromiseYo @xiangwenhu
