### ISSUE TITLE
最新的beta版 form组件的ValidateError事件失效的bug

### ISSUE THREAD

**Issue by Seizedays233** [baidu/amis#7565]
#### 描述问题：

form表单验证 ValidateError失效 3.2.0稳定版能正常触发 master分支的 3.3.0 beta最新版无法触发该事件

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.3.0 beta最新版

4. 粘贴有问题的完整 `amis schema` 代码：
```
validateError:{
              "actions": [
                {
                  preventDefault: true,
                },
                {
                  "actionType": "toast",
                  "args": {
                    "msgType": "error",
                    "msg": "存在必填项未填",
                    "position": "top-center"
                  }
                }
              ]
            }
```

5. 操作步骤
随便弄个form组件 把这个validateError放上去  触发一下校验失败的场景 不会生效

**Comment by hsm-lv** [comment]
试试最新的版本呢

**Comment by Seizedays233** [comment]
> 试试最新的版本呢

目前用的是beta4的版本 没有修复这个问题

**Comment by hsm-lv** [comment]
> > 试试最新的版本呢
> 
> 目前用的是beta4的版本 没有修复这个问题

amis 3.2.0

**Comment by Seizedays233** [comment]
> > > 试试最新的版本呢
> > 
> > 
> > 目前用的是beta4的版本 没有修复这个问题
> 
> amis 3.2.0

3.2.0没问题 但是3.2.0的富文本编辑器有bug 我升级到3.3.0 beta4之后 富文本编辑器的问题解决了 然后遇到了这个校验的异常

**Comment by hsm-lv** [comment]
> > > > 试试最新的版本呢
> > > 
> > > 
> > > 目前用的是beta4的版本 没有修复这个问题
> > 
> > 
> > amis 3.2.0
> 
> 3.2.0没问题 但是3.2.0的富文本编辑器有bug 我升级到3.3.0 beta4之后 富文本编辑器的问题解决了 然后遇到了这个校验的异常

嗯，目前是没有复现，或者你等下下个正式版本

**Comment by Seizedays233** [comment]
> > > > > 试试最新的版本呢
> > > > 
> > > > 
> > > > 目前用的是beta4的版本 没有修复这个问题
> > > 
> > > 
> > > amis 3.2.0
> > 
> > 
> > 3.2.0没问题 但是3.2.0的富文本编辑器有bug 我升级到3.3.0 beta4之后 富文本编辑器的问题解决了 然后遇到了这个校验的异常
> 
> 嗯，目前是没有复现，或者你等下下个正式版本

v3.3.0版本依然存在这个问题
