### ISSUE TITLE
增删改查 点击表格行会让浮动列背景透明

### ISSUE THREAD

**Issue by yshujun** [baidu/amis#7577]
#### 描述问题：
增删改查 点击表格行会让浮动列背景透明

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/48676074/13467553-78bc-4278-9ce3-b91364e9719d)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

最新代码本地运行

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
跟 https://github.com/baidu/amis/issues/7585 同一问题，且在  https://github.com/baidu/amis/pull/7597 已修复

**Comment by yshujun** [comment]
ok
