### ISSUE TITLE
如何将获取的字符串与已存在的字符串叠加？

### ISSUE THREAD

**Issue by huajunfree** [baidu/amis#758]
需求是制作一个日志功能，可以通过接口不断获取新产生的日志，并显示在界面上。
service容器可以满足定时请求的要求，但是怎样将获取到的字符串与已存在的字符串拼接呢？
有什么渲染器或者语法能够满足这样的要求么？
@2betop

**Comment by RickCole21** [comment]
我个人觉得需要偏自定义组件，一个日志组件需要考虑的点还挺多的，现成的应该没有很适合组件

**Comment by huajunfree** [comment]
好吧  那就是需要自定义组件了  字符串拼接现在也确实是还没有支持的咯？

**Comment by RickCole21** [comment]
嗯，你form可以配置接口轮训，然后每次返回全量日志就可以实现类似效果，但是体验可能不太好

**Comment by huajunfree** [comment]
嗯  了解了  感谢
