### ISSUE TITLE
请问使用nav怎么设置label和value

### ISSUE THREAD

**Issue by Gwq01** [baidu/amis#7591]
#### 实现场景：
我从后台请求接口，拿到数据 
![image](https://github.com/baidu/amis/assets/96569767/fb9ac0dc-5ca3-4a8d-b19d-2469ccc50644)
然后labelField字段设置不生效 

#### 存在的问题：

![image](https://github.com/baidu/amis/assets/96569767/5cbe2d0b-8b84-478b-b83d-c5328dc4ca83)
我设置值labelfield 但是没有显示成功

#### 当前方案：
 {
        "type": "nav",
        "stacked": true,
        "name": "ceshi",
        "source": "/admin-api/entitymanage/dataSource/getList?env=DEV&appId=appid",
        "labelField": "name",
        "valueField": "id",
        "className": "w-md",
        "itemActions": [
          {
            "type": "dropdown-button",
            "level": "link",
            "icon": "fa fa-ellipsis-h",
            "hideCaret": true,
            "buttons": [
              {
                "type": "button",
                "label": "编辑",
              },
              {
                "type": "button",
                "label": "查看信息"
              },
              {
                "type": "button",
                "label": "删除"
              }
            ]
          }
        ]
      },

```
code here...
```

**Comment by sheeepli** [comment]
文档没有说nav有labelField，和 valueField，所以你这么写肯定是不行的
```
        {
          "type": "page",
          "data": {
            "nav": [
              {
                "name": "数据源B",
                "to": "/docs/index",
                "id": "b"
              },
              {
                "name": "数据源A",
                "to": "/docs/index",
                "id": "a"
              }
            ]
          },
          "body": {
            "type": "nav",
            "stacked": true,
            "source": "${nav|pick:label~name}"
          }
        }
 ```

上面是一种解决方案，不过不是直接获取后台数据进行修改的

可以参考[配置返回数据](https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api?page=1#%E9%85%8D%E7%BD%AE%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE)这个部分的内容来写
