### ISSUE TITLE
时间轴组件detail无法自适应，垂直的时候，很小不支持className

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#7594]
#### 描述问题：
时间轴组件detail无法自适应，垂直的时候，很小不支持className

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
'sdk'

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
版本：3.1.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
把detail 设置字多一些，就能复现。

**Comment by 2betop** [comment]
@Dora-boots

**Comment by lurunze1226** [comment]
新增[`detailClassName`](https://aisuda.bce.baidu.com/amis/zh-CN/components/timeline#%E5%B1%9E%E6%80%A7%E8%A1%A8) 属性
