### ISSUE TITLE
还是富文本编辑器问题

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#760]
https://baidu.github.io/amis/docs/renderers/Form/Rich-Text#rich-text

看示例已经改成tinymce了，可是用jssdk模式时，显示的还是frola编辑器？都是默认配置。

 {
                                type: "rich-text",
                                name: "content",
                                label: "描述",
                                size: "lg",
                                required: true
},

**Comment by 2betop** [comment]
你用的什么jssdk？cdn 版本还是 npm 版本？如果是 cdn 版本是用的最新版本还是旧的？

**Comment by foxfire881** [comment]
> 你用的什么jssdk？cdn 版本还是 npm 版本？如果是 cdn 版本是用的最新版本还是旧的？

用的是这里的sdk，下载后npm i安装，然后从modules里面找到amis文件夹，把里面的sdk复制出来
https://github.com/fex-team/amis-admin/tree/jssdk

**Comment by 2betop** [comment]
加个配置吧,rich-text 渲染器配置里面 

```
{
type: "rich-text",
name: "content",
label: "描述",
size: "lg",
required: true,
vendor: "tinymce"
},
```

**Comment by foxfire881** [comment]
试了加过啦，强制指定vendor还是无效，不知道哪里有问题

**Comment by 2betop** [comment]
那估计你得检查缓存了

**Comment by foxfire881** [comment]
> 那估计你得检查缓存了

检查发现问题了，不是缓存的问题，是从这里下载的jssdk源码中的package.json中amis设置的版本太低，还是1.0.10版，调整到1.0.14就好了。

老板更新一下package.json吧

**Comment by nwind** [comment]
已经升级了
