### ISSUE TITLE
Code组件customLang配置是否支持动态的？

### ISSUE THREAD

**Issue by Mengleijin** [baidu/amis#7618]
#### 实现场景：
我想实现一段文本展示，文中有些词需要高亮展示，想问一下Code组件是否支持customLang动态配置？

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
{
  "type": "code",
  "customLang": {
    "name": "myLog",
    "tokens": [
      {
        "regex": "${regex1}",
        "color": "#FFA500",
        "name": "1"
      }
    ]
  },
  "id": "u:5ad68c3d45f5",
  "name": "text1"
}
```

**Comment by Mengleijin** [comment]
如果Code组件不支持，其它有什么组件可以支持？谢谢。
试了html组件好像也不支持动态的

**Comment by 2betop** [comment]
文档上有说明，应该是支持的 https://aisuda.bce.baidu.com/amis/zh-CN/components/code#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E9%AB%98%E4%BA%AE

**Comment by Mengleijin** [comment]
> 文档上有说明，应该是支持的 https://aisuda.bce.baidu.com/amis/zh-CN/components/code#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E9%AB%98%E4%BA%AE

@2betop 我在提问之前有看文档，用表达式这种方式试了不生效 “customLang": "${}"
