### ISSUE TITLE
错误：monaco editor 提示setModelMarkers  is not function

### ISSUE THREAD

**Issue by shaofq** [baidu/amis#7621]
#### 存在的问题：
    let model = editor.getModel();
    console.log(editor);
    debugger ;let f = editor.setModelMarkers(model, 'owner', [{
        startLineNumber: 2,
        startColumn: 1,
        endLineNumber: 2,
        endColumn: 1,
        message: 'This is a warning message',
        severity: monaco.MarkerSeverity.Warning
    }]);

提示  editor.setModelMarkers is not a function

**Comment by 2betop** [comment]
这个应该转到 monaco-editor 仓库？

**Comment by shaofq** [comment]
![image](https://github.com/baidu/amis/assets/28698892/0f58998d-9a56-4e58-bc6b-b4ea713fddee)
我是在这里加的上面的代码，monaco-editor  官方有这个用法
