### ISSUE TITLE
inputCity的城市选择器的下拉单能调宽一点吗 看不全里面的内容

### ISSUE THREAD

**Issue by Seizedays233** [baidu/amis#7622]
#### 实现场景：
选择省市区的时候 只能看见第一个字 后边的都藏起来了

#### 存在的问题：
![image](https://github.com/baidu/amis/assets/54106885/b69061bb-291c-488d-89a3-3b411c27c088)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by wencan** [comment]
不应该才这点宽度啊
试试加size： https://baidu.github.io/amis/zh-CN/components/form/formitem#%E8%A1%A8%E5%8D%95%E9%A1%B9%E5%B0%BA%E5%AF%B8

**Comment by Seizedays233** [comment]
> 不应该才这点宽度啊 试试加size： https://baidu.github.io/amis/zh-CN/components/form/formitem#%E8%A1%A8%E5%8D%95%E9%A1%B9%E5%B0%BA%E5%AF%B8

和form表单项没关系 你看下官方文档  文档demo里的这个组件就是这么窄 
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-city
