### ISSUE TITLE
请教一下crud与nav联动的问题

### ISSUE THREAD

**Issue by Gwq01** [baidu/amis#7623]
#### 实现场景：
初始化时根据nav栏去请求crud的数据 在官网抄的例子
![image](https://github.com/baidu/amis/assets/96569767/52942b68-f800-45da-9222-c5e2c10e8e0a)

#### 存在的问题：
后端返回值与官网实例不太一样，
![image](https://github.com/baidu/amis/assets/96569767/aa815713-355f-4652-9e14-077e1527c108)
这是后端返回的值，
![image](https://github.com/baidu/amis/assets/96569767/c118d892-6dcd-47fb-85f8-be0a4917f191)
这是处理过后的，然后初始化时不会去请求 crud，
![image](https://github.com/baidu/amis/assets/96569767/70be3228-b54e-424b-98b2-271328a56e3b)
只请求了nav导航栏，那个nav中的to字段的作用是什么 ，需要后端去更改返回值吗？ 加上to字段和刚进来的请求地址。

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
 "aside": {
      "type": "nav",
      "name": "nav",
      "stacked": true,
      "source": {
        "url": "/admin-api/entitymanage/dataSource/getList",
        "method": "get",
        "responseData": {
          "links": "${data|pick:label~name,value~id,to~id}"
        }
      }
    },
    "body": {
      "type": "crud",
      "draggable": true,
      "api": {
        "url": "/admin-api/entitymanage/table/getTableList",
        "sendOn": "?dsId=${to}"
      },
  }
```
code here...
```

**Comment by 2betop** [comment]
"sendOn" 配置有问题，表达式有语法错误，所以不会请求。那个例子是利用 nav 的 to 更新地址栏，to地址通常是 `?xxKey=xxxValue`, 地址栏变化，crud 就会重新请求（前提是 crud 配置了同步地址栏功能），然后crud读取的其实是地址栏上的变量，所以不存在 to 这个变量，而是 xxKey 这个变量。
