### ISSUE TITLE
请教一下向导的使用方法

### ISSUE THREAD

**Issue by Gwq01** [baidu/amis#7626]
#### 实现场景：
在我使用向导模式的时候填写完第二步时，返回第一步去修改某些数据后，再下一步时第二步的表单完全清空，重新填写。

#### 存在的问题：
在我返回上一步再此去往下一步是没有重置数据，请问是有什么办法能给数据重置？

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
第二步配置 initApi，让接口返回对应的 key 设置上 空值，这样每次到第二步的时候都会清空。

**Comment by Gwq01** [comment]
> 第二步配置 initApi，让接口返回对应的 key 设置上 空值，这样每次到第二步的时候都会清空。

好的大佬 能加您个联系方式吗？
