### ISSUE TITLE
请问图片上传以后。接口返回的值是否可以联动给其他formitem

### ISSUE THREAD

**Issue by orange2003** [baidu/amis#763]
具体场景就是。上传身份证进行图片ocr。然后根据ocr 结果把身份证信息。联动到其他值。请问这个现有的控件可以做到吗？谢谢

**Comment by RickCole21** [comment]
image或者file组件上配置`autoFill`：将上传成功后接口返回值的某个字段，自动填充到表单中某个表单项中，只在单选时有效
例如配置
```
"autoFill": {
    "filename":
    "${filename}"
}
```

表示将选中项中的`filename`的值，自动填充到当前`name`为`filename`的表单项中

**Comment by orange2003** [comment]
感谢

**Comment by orange2003** [comment]
我觉得官方文档是不是需要增加这种用法的说明。毕竟这种场景还是挺多的。

**Comment by RickCole21** [comment]
加了，只是还没更新gh-page
