### ISSUE TITLE
自定义amis组件使用vue3问题

### ISSUE THREAD

**Issue by shaofq** [baidu/amis#7631]
#### 实现场景：
我想自定义一个amis组件，组件内容使用vue3开发，使用了组件element-plus

#### 存在的问题：
![image](https://github.com/baidu/amis/assets/28698892/1fea1285-d3ee-4508-be54-9df85d4c8e86)

#### 当前方案：

代码部分：
```
import appva from '../../views/breadcrumb_example/Elbutton.vue'
 function CustomComponent(props) {
    let dom = React.useRef(null);
    React.useEffect(function () {
      var app = createApp({ render: () => h(appva) })
      app.mount(dom.current);
      
    });
    return React.createElement('div', {
      ref: dom
    });
  }
  amisLib.Renderer({
    test: /(^|\/)my-custom/
  })(CustomComponent);

```
感觉需要调用一次 unmonunt但是不知道在哪去调用

**Comment by 2betop** [comment]
import appva from '../../views/breadcrumb_example/Elbutton.vue'
 function CustomComponent(props) {
    let dom = React.useRef(null);
    React.useEffect(function () {
      var app = createApp({ render: () => h(appva) })
      app.mount(dom.current);
      return () => app.unmount()
    });
    return React.createElement('div', {
      ref: dom
    });
  }
  amisLib.Renderer({
    test: /(^|\/)my-custom/
  })(CustomComponent);
