### ISSUE TITLE
下载组件请求成功，响应异常：Unexpected token 'P', "PK  "... is not valid JSON

### ISSUE THREAD

**Issue by TYBWANG** [baidu/amis#7638]
#### 实现场景：
文件下载

#### 存在的问题：
下载请求成功，但是响应异常

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
{
                  "label": "下载资料",
                  "type": "action",
                  "actionType": "download",
                  "api": {
                    "method": "get",
                    "url": "/xxxx"
                  },
                  "id": "u:b0e5a9e127b2",
                  "level": "primary"
 }
requestAdaptor 中统一为请求headers 里加入 token
####  异常信息
![screenshot-20230731-150238](https://github.com/baidu/amis/assets/7733565/e4bfb84f-7f4f-4b43-a422-8b111e2d39c8)
![image](https://github.com/baidu/amis/assets/7733565/ee4bc264-6dee-479e-8294-00a1ee7ab6d3)

**Comment by 2betop** [comment]
返回文件的 header 再加上这个试试 `Access-Control-Expose-Headers:  Content-Disposition`

**Comment by TYBWANG** [comment]
加上了，还是一样的错误。
![screenshot-20230731-162620](https://github.com/baidu/amis/assets/7733565/2e9f108f-032a-451f-b26e-81929fb9a478)

**Comment by 2betop** [comment]
不是 Request header, 是 Response Header

**Comment by TYBWANG** [comment]
可以下载文件了，但是文件的扩展名丢失了。
响应头如下
![image](https://github.com/baidu/amis/assets/7733565/f18c599f-ec3e-4ad7-a4a0-3eaee46a3f3f)
