### ISSUE TITLE
怎么在控制同一个表单定义里某个组件在添加时可用编辑时不可用

### ISSUE THREAD

**Issue by xiusin** [baidu/amis#764]
比如我想要操作的组件名字为`name`
```
        {
                    "type": "text",
                    "label": "我想在添加时可用",
                    "disabledOn": "data.name", // 这里使用data.name
                    "name": "name"
        },
```
但是没办法得到想要的结果

**Comment by RickCole21** [comment]
看起来没啥问题，编辑的时候name值没有么？

**Comment by xiusin** [comment]
@RickCole21 编辑的时候是有值的， 添加的时候我不确定data的数据是什么[苦笑]， 但是从表现来看编辑和添加是同样的。

**Comment by RickCole21** [comment]
换一个字段标识吧，比如id

**Comment by xiusin** [comment]
@RickCole21 一样的， 都试了。 我怎么在组件里打印data的数据呢。 ${data | json}吗？

**Comment by RickCole21** [comment]
form里配置`debug:true`

**Comment by RickCole21** [comment]
我意思是你`disabledOn`换一个字段来标识当前是编辑还是新建，比如`disabledOn:'data.id'`

**Comment by xiusin** [comment]
恩呢， 我是这样操作的。 但是没变化

**Comment by RickCole21** [comment]
不可能啊，你完整配置是啥样的

**Comment by xiusin** [comment]
@RickCole21 擦，   我的错， 属性写错了，少了**d**, 调试了大半天。
