### ISSUE TITLE
crud   两个场景都比较慢

### ISSUE THREAD

**Issue by songyinhai2006** [baidu/amis#7641]
#### 描述问题：
（1）分页返回稍微多一些就比较慢，正常20条显示没问题，50条稍微有一点，100就很明显慢了。
（2）批量操作，在多选时明显卡顿
  具体见视频。
  作者能否优化一下，这个数据稍微多加载一些多卡顿，就没法推广使用了。

#### 截图或视频：

https://github.com/baidu/amis/assets/52561802/d5f9bb2d-712f-4b8d-9cc0-6b8d58e69509

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3.2.0

3. 粘贴有问题的完整 `amis schema` 代码：

4. 操作步骤
作者您那边初始化数据稍微多一点就行，比如行显示50条或者100条。列显示20个左右，应该就能复现。

**Comment by SmallSeaNO3** [comment]
+1

**Comment by 822795778** [comment]
+1  能够明显感觉卡顿，对于amis推广太致命了，终端客户体验非常不友好。

**Comment by ranwawa** [comment]
+1

**Comment by cat69fl** [comment]
+1, 选中一条数据太卡了，没法忍受

**Comment by cat69fl** [comment]
@songyinhai2006 表格中的单元格左右边框线怎么设置能出来？

**Comment by songyinhai2006** [comment]
> @songyinhai2006 表格中的单元格左右边框线怎么设置能出来？

设置了合并单元格combineNum，自动有了。

**Comment by joeoops** [comment]
也碰到这个问题了，数据多实在太卡，期待快解决

**Comment by tomasky** [comment]
+1 ，表格5k的数据量就卡了，个人感受1.5秒渲染完毕。

**Comment by cat69fl** [comment]
@songyinhai2006 3.4版本还是没有解决这问题

**Comment by 2betop** [comment]
下个版本优化

**Comment by cat69fl** [comment]
> 下个版本优化

下个版本要等一个月了吧

**Comment by songyinhai2006** [comment]
> 

真得太好了，耐性等待中

**Comment by songyinhai2006** [comment]
> 下个版本优化

真的太好了，耐心等待中

**Comment by tomasky** [comment]
3.4.0依然有这个问题，当每页显示20条，点击分页和勾选每条的时候，会卡。

**Comment by cat69fl** [comment]
> 3.4.0依然有这个问题，当每页显示20条，点击分页和勾选每条的时候，会卡。
估计3.5版本会解决

**Comment by 2betop** [comment]
目前 master 分支已合入部分优化，还在进一步优化中

**Comment by songyinhai2006** [comment]
> 目前 master 分支已合入部分优化，还在进一步优化中

测试情况如下：返回列数30左右
200条，400条，显示正常，选中，取消选中速度都可以。

但是，50条的情况下，全部选中，取消全部选中有点卡顿（200，400全选更慢了）。
作者能否再优化一下，100以内全部选中速度。

https://github.com/baidu/amis/assets/52561802/044050f3-23ae-4749-ade1-9538384d0407

**Comment by 2betop** [comment]
收到，意思现在纯展示已经有明显的性能优化是吧？

**Comment by songyinhai2006** [comment]
> 收到，意思现在纯展示已经有明显的性能优化是吧？

是的，性能提升还是很明显的

**Comment by 2betop** [comment]
点选场景优化也已合入 master 分支

**Comment by 2betop** [comment]
请尝试 3.4.1 版本，有问题再 reOpen

**Comment by cat69fl** [comment]
> 请尝试 3.4.1 版本，有问题再 reOpen

Releases 未发布3.4.1， 我需要sdk.tar.gz

**Comment by 2betop** [comment]
https://github.com/baidu/amis/releases/tag/3.4.1

**Comment by cat69fl** [comment]
> https://github.com/baidu/amis/releases/tag/3.4.1

之前的版本选中一条卡半天，已经到了无法使用的程度的。这个版本效果很明显，很快了，和领导沟通有信心了

**Comment by songyinhai2006** [comment]
![image](https://github.com/baidu/amis/assets/52561802/bb5716e8-d50f-4602-97f4-8f849721d792)
