### ISSUE TITLE
代码编辑器这块有对nginx配置的支持吗？

### ISSUE THREAD

**Issue by zhangyucumt** [baidu/amis#765]
代码编辑器这块有对nginx配置的支持吗？或者有支持的计划吗？

**Comment by 2betop** [comment]
amis 里面使用的 monaco-editor，要看他支持不支持, 目前你可以去这里面看看有没有语法接近的。https://microsoft.github.io/monaco-editor/

**Comment by zhangyucumt** [comment]
好的~
