### ISSUE TITLE
form表单的通过按钮执行表单的validate动作无法触发validateError的事件

### ISSUE THREAD

**Issue by Seizedays233** [baidu/amis#7657]
#### 描述问题：

使用按钮触发某个表单的validate动作  校验失败后 我自定义的validateError事件无法生效

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/54106885/cb3a42a9-4dc8-440d-9733-f03c43536edf)

![image](https://github.com/baidu/amis/assets/54106885/96f2c8ab-c54a-447d-9706-df05fc6bfb75)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v3.3.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
	"type": "form",
	"api": "/amis/api/mock2/form/saveForm",
	"id": "testForm",
	"body": [
		{
		"type": "input-text",
		"name": "name",
		"required": true,
		"label": "姓名："
		},
		{
		"name": "email",
		"type": "input-email",
		"label": "邮箱："
		}
	],
	"actions": [
		{
			"type": "action",
			"label":  "下一步",
			"level":  "primary",
			"onEvent": {
				"click": {
				actions: [
					{
					"actionType": "validate",
					"componentId": "testForm"
					},
					
				]
				}
			}
			},
	],
	"onEvent":{
		validateError:{
			"actions": [
				{
				preventDefault: true,
				},
				{
				"actionType": "toast",
				"args": {
					"msgType": "error",
					"msg": "自定义消息",
					"position": "top-center"
					}
				}
			]
		}
	}
}
```

4. 操作步骤
按照这个代码执行 点击下一步触发空值校验的时候就会复现这个问题

**Comment by hsm-lv** [comment]
其实可以直接通过validate动作的返回来添加动作，可以看看 https://baidu.github.io/amis/zh-CN/components/form/index#validate，即执行validate动作，执行后可以拿到校验返回，然后在后面执行其他动作

**Comment by hsm-lv** [comment]
其实可以直接通过validate动作的返回来添加动作，可以看看 https://baidu.github.io/amis/zh-CN/components/form/index#validate，即执行validate动作，执行后可以拿到校验返回，然后在后面执行其他动作
