### ISSUE TITLE
v3.3.0版本 form表单的static配置对group内的表单项不生效了

### ISSUE THREAD

**Issue by Seizedays233** [baidu/amis#7658]
#### 描述问题：

form配置了static为true 但是在group里的表单项都是非静态的，不在group里的表单项是正常静态的，是在更新了版本之后出现的这个问题

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/54106885/87dd13e3-3208-490b-b9bd-a2cc26cadea2)
![image](https://github.com/baidu/amis/assets/54106885/45aaf4b4-6a6e-411a-94d3-231c728e9c97)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v3.3.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
	"type": "form",
	"api": "/amis/api/mock2/form/saveForm",
	static: true,
	"id": "testForm",
	"body": [
			{
              "type": "group",
			"body": [
				{
				"type": "input-text",
				"name": "orderNumber",
				"label": "订单号："
				},
				{
				"type": "select",
				"name": "status",
				"label": "订单状态：",
				"options": {
					"10": "待支付",
					"20": "待预约",
					"25": "已预约",
					"27": "已使用",
					"29": "退款中",
					"30": "已退款",
					"31": "退款失败",
					"40": "已取消",
					"41": "超时未支付"
				}
				},
				]
		},
		{
		"type": "input-text",
		"name": "name",
		"required": true,
		"label": "姓名："
		},
		{
		"name": "email",
		"type": "input-email",
		"label": "邮箱："
		}
	],
	"actions": [
		{
			"type": "action",
			"label":  "下一步",
			"level":  "primary",
			"onEvent": {
				"click": {
				actions: [
					{
					"actionType": "validate",
					"componentId": "testForm"
					},
					
				]
				}
			}
			},
	],
}
```

4. 操作步骤
只在form组件配置static 然后将表单项放到group里即可复现

**Comment by 2betop** [comment]
static 应该每个表单项上自己去配置，而不是 form 整体配置？

**Comment by Seizedays233** [comment]
> static 应该每个表单项上自己去配置，而不是 form 整体配置？
之前3.2.0是可以这么配置的，升级之后就不行了 而且现在只是对group里的表单项失效  倒是不影响开发使用

**Comment by Icodezhan** [comment]
因为之前存在外层组件设置static但是内层组件不需要static的情况，如果不这样改就没法用了

**Comment by Seizedays233** [comment]
> 因为之前存在外层组件设置static但是内层组件不需要static的情况，如果不这样改就没法用了，参见 #7088，你这种情况的话，在group层再加个static

好的 明白了 只是好奇为什么突然不能用了
