### ISSUE TITLE
inputDateRange组件 选中某一天后就无法再选中更早的日期了

### ISSUE THREAD

**Issue by Seizedays233** [baidu/amis#7659]
#### 描述问题：

比如我起始日期错选了8月8日  想改成8月1日 这时候就无法选择8日之前的日期了 需要关掉组件再打开才能重新选择

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/54106885/78ee6909-1fab-44ba-a56e-362d227b87f6)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v3.3.0   官方文档的demo也存在这个问题
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "input-date-range",
        "name": "select",
        "label": "日期范围"
      }
    ]
  }
}
```

4. 操作步骤
在起始日期选中某一天，再尝试修改到更早的某一天就可以复现

**Comment by 2betop** [comment]
因为当时在编辑结束时间，自然不能选择比开始时间更早的日期。如果切到开始时间编辑则可
<img width="577" alt="image" src="https://github.com/baidu/amis/assets/2698393/dbf1caec-0818-4ad8-ab3e-592854544801">
