### ISSUE TITLE
alert和二次确认弹出的页面不在正确的页面

### ISSUE THREAD

**Issue by zmm1988** [baidu/amis#7667]
在vue2.0中集成amis，制作了两个amis页面，并且做了缓存(多页签切换的时候不刷新页面)，这两个amis页面实际是共用的一个amisView.vue文件。
bug：先点击要显然弹窗的页面，然后点击另一个amis页面，然后点击页签切回来，分别点击dialog，alert,弹窗，二次确认，其中dialog和弹窗可以正常弹出，而alert和二次确认再最后加载出来的amis页面弹出
此问题在3.1.1和3.2.0中都存在
**视频**：

https://github.com/baidu/amis/assets/48378155/43ffad86-79de-489c-a33b-e5090d3d05fc

**Comment by 2betop** [comment]
alert, confirm 默认都是用的全局的一个实例，不像 dialog 是容器内组件内部的示例。

目前有两种方法可以解决这个问题：

1. 自己实现 env.alert 和 env.confirm。
2. 用 tabs 外面先渲染这两个 组件，然后 tabs 内部就会共用这的了。https://github.com/baidu/amis/blob/master/examples/embed.tsx#L275-L286
