### ISSUE TITLE
我可以用现有的 CRUD 模板替换我的模板吗？

### ISSUE THREAD

**Issue by Trinh-Viet-Dat** [baidu/amis#7668]
我可以用现有的 CRUD 模板替换我的模板吗？

**Comment by 2betop** [comment]
看不懂呢，啥意思？

**Comment by Trinh-Viet-Dat** [comment]
我想更改此模板:
![image](https://github.com/baidu/amis/assets/95202645/295ffc5e-c79e-4bd9-8bde-23c2bbc5fb97)

我想用

![image](https://github.com/baidu/amis/assets/95202645/a39d7a0c-36bf-454c-a7ac-a09d49ac4dd1)

**Comment by 2betop** [comment]
amis 又没提供模版，你是不是问错地方了
