### ISSUE TITLE
请教一下toast没有生效是什么原因

### ISSUE THREAD

**Issue by Gwq01** [baidu/amis#7674]
#### 实现场景：
接口请求之后如果通过 toast提示成功，失败提示失败。

#### 存在的问题：
![LXZ1J66$TVJ(~ VQNOHB0N](https://github.com/baidu/amis/assets/96569767/e8947ed4-61e8-45b5-89a2-7196d61a4cde)
在官方文档上找到的文档 按照这中方式没有反应，
然后我又在文档中
![image](https://github.com/baidu/amis/assets/96569767/1794aa3f-ac21-4b74-abf1-0b65d32f5d23)
找到了这个 但是没搞懂 请问一下应该怎么让他弹出提示信息？

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
参考这个，把这两个组件渲染到的 react 里面 https://github.com/baidu/amis/blob/master/examples/embed.tsx#L275-L286
