### ISSUE TITLE
之前有个问题没有理解

### ISSUE THREAD

**Issue by Gwq01** [baidu/amis#7675]
#### 实现场景：
![image](https://github.com/baidu/amis/assets/96569767/0bff2564-2da5-4f88-b27f-a8a3284556a4)

就是向导清除数据，我设置了initAPI  这个后台所返回的key是指所对应的字段吗？ 这块没有理解是什么意思 麻烦大佬指点一下
#### 存在的问题：
如果那个key指字段的话 我在本地mock的时候没有生效，不清楚是不是我设置的有问题。

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
是的，就是字段的 key

**Comment by Gwq01** [comment]
> 是的，就是字段的 key

大佬先别关 我在去mock一下

**Comment by Gwq01** [comment]
> 是的，就是字段的 key

![image](https://github.com/baidu/amis/assets/96569767/7733b427-9de6-4b76-bd9c-4a75772da650)
![image](https://github.com/baidu/amis/assets/96569767/a1f0fd2d-7157-48ff-b83d-d86842eeb993)
上面是我正常请求的 是这个意思吗 大佬 ，这样没有清掉值。。

**Comment by 2betop** [comment]
wizard 的数据格式是对象，而不是对象数组呢

**Comment by Gwq01** [comment]
> wizard 的数据格式是对象，而不是对象数组呢

这个是指我在选择完数据之后返回上一步在下一步时初始化返回的值是个对象吗？

**Comment by Gwq01** [comment]
> wizard 的数据格式是对象，而不是对象数组呢

就是我第二步中是个picker 我要将这个picker中的数据清空

**Comment by 2betop** [comment]
picker 的值格式有两种，如果配置了  joinValues: true 是字符串，此时返回 `{data: {'picker字段名': ''}}` 即可清空。如果没有配置，picker 的值格式是数组，此时返回 `{data: {'picker字段名': []}}`

**Comment by Gwq01** [comment]
> picker 的值格式有两种，如果配置了 joinValues: true 是字符串，此时返回 `{data: {'picker字段名': ''}}` 即可清空。如果没有配置，picker 的值格式是数组，此时返回 `{data: {'picker字段名': []}}`

明白了 清掉了大佬 我一直以为是要将后台返回的里面的字段清空  原来是直接将picker的name名清空

**Comment by Gwq01** [comment]
> picker 的值格式有两种，如果配置了 joinValues: true 是字符串，此时返回 `{data: {'picker字段名': ''}}` 即可清空。如果没有配置，picker 的值格式是数组，此时返回 `{data: {'picker字段名': []}}`

再请问一下这个只能是后台返回接口清吗 可以自己直接清除掉吗？

**Comment by Gwq01** [comment]
![image](https://github.com/baidu/amis/assets/96569767/c833d98f-4578-4dce-9d98-4d48527b3499)
是这个意思吧

**Comment by 2betop** [comment]
是这个意思，事件动作里面应该也可以清

**Comment by Gwq01** [comment]
> 是这个意思，事件动作里面应该也可以清

 明白了 大佬 真的不能加个联系方式吗? =v=
