### ISSUE TITLE
[问题]: 有没有TreeGrid或TreeTable的打算

### ISSUE THREAD

**Issue by xiusin** [baidu/amis#768]

**Comment by 2betop** [comment]
能具体点吗？table 支持嵌套展示啊

**Comment by xiusin** [comment]
@2betop 额可以 我看下文档, 搜文档内容老是跳404.

**Comment by xiusin** [comment]
@2betop  你好, 这个文字提示能设置不显示并且左边位置也隐藏让tab展示填充满
![image](https://user-images.githubusercontent.com/36065131/88250387-10804500-ccda-11ea-952e-59d28d46a042.png)

**Comment by RickCole21** [comment]
```
label:false
```

**Comment by xiusin** [comment]
@RickCole21 流弊. 
![image](https://user-images.githubusercontent.com/36065131/88257062-7e833700-ccef-11ea-825b-d6e80f5318c4.png)
