### ISSUE TITLE
如何关闭表单提交接口的返回值数据域merge

### ISSUE THREAD

**Issue by jianchaoming** [baidu/amis#7680]
#### 实现场景：
文档这种场景：https://baidu.github.io/amis/zh-CN/docs/concepts/datascope-and-datachain#%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE%E5%9F%9F

#### 存在的问题：
不希望提交接口的返回值合并进数据域且覆盖，如果返回值出现同名参数，会被无意间修改参数值，造成下次提交时参数值错误，比如报错的时候，合并覆盖了数据域，下次提交发现参数变了（最怕没注意到参数变了）

#### 当前方案：
文档这种：https://baidu.github.io/amis/zh-CN/docs/concepts/datascope-and-datachain#%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE%E5%9F%9F

```
code here...
```

**Comment by 2betop** [comment]
可以 给 api 设置  responseData 将结果映射为空，这样就不会写入了

**Comment by jianchaoming** [comment]
好的，如果我们内部把源码里面的默认写入这块改成默认不写入，会有其他影响么

```
// 失败也同样修改数据，如果有数据的话。
if (!isEmpty(json.data) || json.ok) {
  self.updatedAt = Date.now();

  setValues(
    normalizeApiResponseData(json.data),
    json.ok
      ? {
          __saved: Date.now()
        }
      : undefined,
    !!(api as ApiObject).replaceData
  );
}
```

**Comment by jianchaoming** [comment]
> 可以 给 api 设置 responseData 将结果映射为空，这样就不会写入了

这个方案我试了下，无效，只能通过返回适配器去掉data

**Comment by 2betop** [comment]
看了下是因为只有成功才走进 `responseData` 了，不过后续可以优化一下这个

```
if (payload.ok && api.responseData) {
    debug('api', 'before dataMapping', payload.data);
    const responseData = dataMapping(
      api.responseData,

      createObject(
        {api},
        (Array.isArray(payload.data)
          ? {
              items: payload.data
            }
          : payload.data) || {}
      ),
      undefined,
      api.convertKeyToPath
    );
    debug('api', 'after dataMapping', responseData);
    payload.data = responseData;
  }
```

**Comment by 2betop** [comment]
> 好的，如果我们内部把源码里面的默认写入这块改成默认不写入，会有其他影响么
> 
> ```
> // 失败也同样修改数据，如果有数据的话。
> if (!isEmpty(json.data) || json.ok) {
>   self.updatedAt = Date.now();
> 
>   setValues(
>     normalizeApiResponseData(json.data),
>     json.ok
>       ? {
>           __saved: Date.now()
>         }
>       : undefined,
>     !!(api as ApiObject).replaceData
>   );
> }
> ```

你们可以把 `if (!isEmpty(json.data) || json.ok) {` 改成 `if (json.ok) {` 即只有成功才 merge
