### ISSUE TITLE
请问Content-Type的问题

### ISSUE THREAD

**Issue by orange2003** [baidu/amis#769]
```
"autoComplete": {
        "method": "post",
        "headers": {
            "Content-Type": "application/json; charset=utf-8"
        },
        "url": "",
        "data": {
            "datas": {
                "acceptorBank": "${term}"
            }
        },
        "dataType": "json"
    }
```

请问如何制定 Content-Type 为 application/json; charset=utf-8 按上门的配置 post 请求发出去 Content-Type 是application/x-www-form-urlencoded

**Comment by 2betop** [comment]
dataType 你放错地方了，应该是 api 里面

**Comment by 2betop** [comment]
配置没问题，是不是外部传入的 fetcher 没处理好？

**Comment by orange2003** [comment]
我是直接用amis edit 里的那个预览看的是不是 amis edit 里的那个 fetcher 写的有问题 我看App.js 里面是这么写的 
`var store = (window.store = index_1.MainStore.create({}, {
          fetcher: function (_a) {
              var url = _a.url, method = _a.method, data = _a.data, config = _a.config;
              config = config || {};
              config.headers = config.headers || {};
              config.withCredentials = true;
              if (method !== 'post' && method !== 'put' && method !== 'patch') {
                  if (data) {
                      config.params = data;
                  }
                  return axios_1.default[method](url, config);
              }
              else if (data && data instanceof FormData) {
                  // config.headers = config.headers || {};
                  // config.headers['Content-Type'] = 'multipart/form-data';
              }
              else if (data &&
                  typeof data !== 'string' &&
                  !(data instanceof Blob) &&
                  !(data instanceof ArrayBuffer)) {
                  data = JSON.stringify(data);
                  config.headers['Content-Type'] = 'application/json';
              }
              return axios_1.default[method](url, data, config);
          },`

**Comment by orange2003** [comment]
我刚刚去除了"dataType": "json" 这个 参数 发送的请求就正常了。 这个狠奇怪
