### ISSUE TITLE
scopeRef ref中没有updateProps方法

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#7692]
- 在react中使用app多页应用，history路由更新amis内部location，但scopeRef方法参数ref中没有updateProps方法
![image](https://github.com/baidu/amis/assets/141314006/7e5a6b66-80f0-48c4-888b-f1321e40626a)
![image](https://github.com/baidu/amis/assets/141314006/268b3713-89fb-4f2b-baea-d247ff7231c1)

**Comment by 2betop** [comment]
如果是 react 中使用，直接通过 props 下发就行了，updateProps 是给非 react 应用用的

**Comment by coffin03** [comment]
通过history.listen获取最新location传到AMISComponent组件props中然后改变amis location属性，这个思路是否可行？

> 如果是 react 中使用，直接通过 props 下发就行了，updateProps 是给非 react 应用用的

通过history.listen获取最新location传到AMISComponent组件props中然后改变amis location属性，这个思路是否可行？

**Comment by coffin03** [comment]
> 如果是 react 中使用，直接通过 props 下发就行了，updateProps 是给非 react 应用用的

已解决，谢谢！

**Comment by coffin03** [comment]
> 如果是 react 中使用，直接通过 props 下发就行了，updateProps 是给非 react 应用用的

已解决，谢谢！

**Comment by a1035909950** [comment]
请问是怎么解决的？
