### ISSUE TITLE
amis@3.3.0 的事件动作 ajax 的 api url 数据映射上下文与 3.2.0 不一样吗？更新后原来的代码失效了

### ISSUE THREAD

**Issue by BeMxself** [baidu/amis#7699]
#### 描述问题：

我原本有一个按钮的click事件动作中配置了：
如下动作：
```
{
  "type": "ajax",
  "args": {
    "api": {
      "method": "put"
      "url": "/api/dev/${appName}/model/${fullName}"
    }
  }
}
```
其中 appName 和 fullName 是在 renderAmis 时传入到amis全局里的

该代码在3.2.0中可以正常运行，升级3.3.0后，这两个值变成了空

**Comment by 2betop** [comment]
应该是这样配置吧 

```
{
  "type": "ajax",
   "api": {
      "method": "put"
      "url": "/api/dev/${appName}/model/${fullName}"
    }
}
```

**Comment by BeMxself** [comment]
> 应该是这样配置吧
> 
> ```
> {
>   "type": "ajax",
>    "api": {
>       "method": "put"
>       "url": "/api/dev/${appName}/model/${fullName}"
>     }
> }
> ```

可能我理解有误吧，我以为所有的事件动作的参数在新版中都要放在args下面，但是刚才我调整了一下schema，并不影响结果

**Comment by hsm-lv** [comment]
已修复，待发布新版
