### ISSUE TITLE
input-color组件加载出错

### ISSUE THREAD

**Issue by plenjoy** [baidu/amis#7701]
#### 描述问题：

Form中使用input-color组件无法正常显示，请检查一下问题在哪里，版本3.3.0

#### 截图或视频：
![企业微信截图_20230804092538](https://github.com/baidu/amis/assets/10240712/eee01022-fc03-48ce-ac15-f75476e2d8c9)

![企业微信截图_20230804092550](https://github.com/baidu/amis/assets/10240712/1feb04b5-f6f6-4c9c-9a6e-f431b1fc5c3f)

**Comment by 2betop** [comment]
这个提交已修复次问题： https://github.com/baidu/amis/commit/14afe96bb8ba10b2480eeeca79b4c14f7b1000ef
