### ISSUE TITLE
在react可以像配置fetcher一样配置暴露的请求拦截器吗

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#7702]
问题描述
在react中配置请求拦截器来处理token失效等逻辑功能

**Comment by 2betop** [comment]
react 中可以自己实现 fetcher，因为 amis 的 npm 版本是不包含 axios 的，不会内置一个 fetcher 实现，所以需要自己实现

**Comment by coffin03** [comment]
> react 中可以自己实现 fetcher，因为 amis 的 npm 版本是不包含 axios 的，不会内置一个 fetcher 实现，所以需要自己实现

那使用react集成amis的app多页应用搭建一个框架，全局的token失效功能如何配置哪？因为目前amis没有暴露出来请求完成后的回调。

**Comment by Icodezhan** [comment]
在fetcher使用自己封装过的axios不就好了，目前我的项目就是这样实现的

**Comment by coffin03** [comment]
> 在fetcher使用自己封装过的axios不就好了，目前我的项目就是这样实现的

明白了，自己给自己绕进去了，谢谢哥们
