### ISSUE TITLE
希望能给现有插件的配置面板提供扩展

### ISSUE THREAD

**Issue by snowing-x** [baidu/amis#7708]
#### 是否关联于某个问题吗：
希望能对现有插件的配置面板进行扩展，例如增加或替换一个配置项

#### 预期的解决方案：
能解决这种场景就可以，比如暴露相关扩展方法

**Comment by ranwawa** [comment]
你的具体是啥需求,我也正在改这一块的代码,看看能不能一起改了

**Comment by snowing-x** [comment]
> 你的具体是啥需求,我也正在改这一块的代码,看看能不能一起改了

现在api在每个需要的地方都要重复定制一份，我希望能够在外面统一定制，然后这里支持选择定制好的api

**Comment by 2betop** [comment]
通过自定义 schemaTpl 覆盖内部实现 https://github.com/baidu/amis/blob/master/packages/amis-editor/src/tpl/api.tsx#L429-L461

**Comment by ranwawa** [comment]
我们正好也要这个功能,不知道做出来之后官方会不会接收.先想想方案







                       
Original
                       
                     

From:"snowing-x"< ***@***.*** &gt;;

Date:2023/8/8 14:22

To:"baidu/amis"< ***@***.*** &gt;;

CC:"ranwawa"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [baidu/amis] 希望能给现有插件的配置面板提供扩展 (Issue #7708)




  
你的具体是啥需求,我也正在改这一块的代码,看看能不能一起改了
  
现在api在每个需要的地方都要重复定制一份，我希望能够在外面统一定制，然后这里支持选择定制好的api

**Comment by ranwawa** [comment]
1. 先注销之前的组件    unRegisterRenderer('ae-apicontrol');
2. 然后重写一个ae-apicontrol,在里面重写原来的配置
class TestComp extends APIControl {
      renderApiConfigTabs(submitOnChange: boolean) {
        const res = super.renderApiConfigTabs(submitOnChange);
        res.body[0].tabs[0].title = 'xxxx';

        return res;
      }
    }
3. 最后再重新注册这个组件
```
	    registerFormItem({
      type: 'ae-apiControl',
      renderLabel: false,
      component: TestComp,
    });
```

**Comment by snowing-x** [comment]
> 1. 先注销之前的组件    unRegisterRenderer('ae-apicontrol');
> 2. 然后重写一个ae-apicontrol,在里面重写原来的配置
>    class TestComp extends APIControl {
>    renderApiConfigTabs(submitOnChange: boolean) {
>    const res = super.renderApiConfigTabs(submitOnChange);
>    res.body[0].tabs[0].title = 'xxxx';
>    ```
>     return res;
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    }
>    }
> 3. 最后再重新注册这个组件
> 
> ```
> 	    registerFormItem({
>       type: 'ae-apiControl',
>       renderLabel: false,
>       component: TestComp,
>     });
> ```

感谢分享，还想问一下你们选择api后，schema里存的直接就是api具体配置，还是类似于apiId的字段，运行时再获取最新的api配置？我们希望能保证运行时使用的是最新的api，因此想采用后一种方案，但是这种方案需要涉及到对于api的解析逻辑，不改源码的话好像没办法实现。想了解一下你们是怎么解决的？

**Comment by ranwawa** [comment]
我们使用的是第一种方式...只是为了方便初始化一个接口数据,比如请求链接,请求方法,请求体,响应拦截器等.




选择之后,会把这些信息填写到配置面板里面

后续使用的人也可以根据实际需求进行微调




因为同一个接口,在不同的场景下,参数或拦截器可能会有细微差异.考虑到拓展性所以没有用id固定死







                       
Original
                       
                     

From:"snowing-x"< ***@***.*** &gt;;

Date:2023/8/31 11:52

To:"baidu/amis"< ***@***.*** &gt;;

CC:"ranwawa"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [baidu/amis] 希望能给现有插件的配置面板提供扩展 (Issue #7708)




   
 
先注销之前的组件    unRegisterRenderer('ae-apicontrol');
 
 
 
然后重写一个ae-apicontrol,在里面重写原来的配置
 class TestComp extends APIControl {
 renderApiConfigTabs(submitOnChange: boolean) {
 const res = super.renderApiConfigTabs(submitOnChange);
 res.body[0].tabs[0].title = 'xxxx';
  return res;  
}
 }
 
 
 
最后再重新注册这个组件
 
  	    registerFormItem({       type: 'ae-apiControl',       renderLabel: false,       component: TestComp,     });   
感谢分享，还想问一下你们选择api后，schema里存的直接就是api具体配置，还是类似于apiId的字段，运行时再获取最新的api配置？我们希望能保证运行时使用的是最新的api，因此想采用后一种方案，但是这种方案需要涉及到对于api的解析逻辑，不改源码的话好像没办法实现。想了解一下你们是怎么解决的？

**Comment by snowing-x** [comment]
好的，非常感谢
