### ISSUE TITLE
请问Form提交以后。是否能把返回的赋值给变量然后再页面上展示出来

### ISSUE THREAD

**Issue by orange2003** [baidu/amis#771]
如题。就是类似 autoFill 的功能。我提交了一个表单想把结果在页面上显示

**Comment by 2betop** [comment]
在 form 内自动就能显示，如果不在 form 内，你需要配置 reload: "xxx?a=${a}" 表示，把form 内的 a 变量转给其他组件名字为 'xxx' 的

**Comment by orange2003** [comment]
谢谢直接在表单里面插入静态类型搞定了。 另外再请教一个问题 "tpl": " <%= 折价率 data.discountRate*100  预计成交价  data.discountRate%>" 这样写 为啥 试算不出来结果
