### ISSUE TITLE
点击按钮怎样修改该按钮的label

### ISSUE THREAD

**Issue by snowing-x** [baidu/amis#7711]
#### 实现场景：
希望点击某个按钮，可以修改该按钮的label。
比如本来是展开图标，点击展开以后，就变成收起图标了；点击收起以后，又变回展开图标了

**Comment by allenve** [comment]
label 可以通过表达式支持 比如 label: "${boolean ? '1': '2'}"， icon 不支持

**Comment by Icodezhan** [comment]
用两个按钮，控制显隐不就好了
