### ISSUE TITLE
Nested input-sub-form generating duplicates

### ISSUE THREAD

**Issue by tangenttechno** [baidu/amis#7715]
#### 描述问题：
If we give the same name to the fields in nested input-sub-form, then values entered in the parent input-sub-form fields are copied to the child input-sub-form which is not the desired behaviour. Please see screenshots
<img width="525" alt="parent-subform" src="https://github.com/baidu/amis/assets/112683333/4e63ef53-3717-4d66-b583-b41cf45fa415">
<img width="560" alt="child-subform" src="https://github.com/baidu/amis/assets/112683333/0292b87b-cf02-4a6f-8a17-a555b6a5964d">
Please check.

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk'(amis doc site)

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
`{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "body": [
      {
        "type": "input-sub-form",
        "name": "form1",
        "label": "子Form",
        "btnLabel": "设置子表单",
        "form": {
          "title": "配置子表单",
          "body": [
            {
              "name": "a",
              "label": "A",
              "type": "input-text"
            },
            {
              "name": "b",
              "label": "B",
              "type": "input-text"
            },
            {
              "type": "input-sub-form",
              "name": "form2",
              "label": "子Form",
              "btnLabel": "设置子表单",
              "form": {
                "title": "配置子表单",
                "body": [
                  {
                    "name": "a",
                    "label": "A",
                    "type": "input-text"
                  },
                  {
                    "name": "b",
                    "label": "B",
                    "type": "input-text"
                  }
                ]
              }
            }
          ]
        }
      }
    ]
  }
}`

4. 操作步骤
paste the above code in amis doc site sub form example, then fill the parent subform first, then open the child sub form which will be already filled using parent form data since both have same field names.

**Comment by 2betop** [comment]
因为默认 form 是可以读取上层数据的，可以通过配置 `canAccessSuperData`: false 来关闭。后续的版本将改成默认关闭如果在 input-sub-form里面

**Comment by tangenttechno** [comment]
@2betop By configuring canAccessSuperData: false and inheritData: false issue got resolved.  Thank you. If possible can you answer this simple [question](https://github.com/baidu/amis/discussions/7686)?
