### ISSUE TITLE
dialog对话框有监听关闭的事件吗？

### ISSUE THREAD

**Issue by onlyThat** [baidu/amis#7716]
#### 描述问题：

目前在文档只看到点击按钮关闭对话框的功能，怎么监听他的关闭呢？

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/114373085/891d4ec6-470c-4f93-8b1c-eabfe4f3ef6f)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
用 `cancel` 事件监听
