### ISSUE TITLE
react模式下APP多页应用解析table、crud组件json报错

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#7717]
![image](https://github.com/baidu/amis/assets/141314006/24f42a1c-927d-442a-a60b-6d114d7e7515)
![image](https://github.com/baidu/amis/assets/141314006/16d91782-7797-461d-9fba-0e404d569fc1)

**Comment by X-W-W** [comment]
3.2也有这个问题，升级3.3之后没有了
