### ISSUE TITLE
Picker里面的 crud 的 filter不支持 tree或group模式的Select组件

### ISSUE THREAD

**Issue by qq57941500** [baidu/amis#7718]
Picker里面的 crud 的 filter不支持 tree模式的Select组件，症状是点击之后不下拉，没反应。
同样的配置在普通的 crud 里面是好用的
{
  "type": "picker",
  "name": "drawings",
  "joinValues": true,
  "valueField": "id",
  "labelField": "name",
  "multiple": true,
  "source": "/api/drawings",
  "label": "选择图纸",
  **"pickerSchema": {
      "filter": {**
          "title": "查询条件",
          "columnCount": 3,
          "mode": "horizontal",
          "body": [
              {
                  "label": "图纸类型",
                  **"type": "select",**
                  "name": "q_drawing_type",
                  **//"selectMode": "tree", 
                  //不知道为啥 group/tree 模式不好用**
                  "searchable": true,
                  "checkAll": true,
                  "multiple": true,
                  "clearable": true,
                  "source": "/api/drawing_types",
                  //"source": "/api/drawing_types_tree",
              },
              {
                  "type": "input-text",
                  "label": "图号",
                  "name": "q_drawing_no",
              }
          ],
      },
      "columns": [
          {
              "label": "图号",
              "type": "text",
              "name": "drawing_no",
          },
          {
              "label": "图纸类型",
              "type": "text",
              "name": "drawing_type__name",
          },
      ],
  }
}

**Comment by 2betop** [comment]
不能复现，猜测是你用的版本不是最新的
