### ISSUE TITLE
react 18下 渲染amis.render返回的dom时报错

### ISSUE THREAD

**Issue by blankzust** [baidu/amis#7720]
#### 描述问题：
复现的git仓库：https://github.com/blankzust/amis-error-in-react18
报错位置：/packages/amis-core/store/manage.ts这里
![image](https://github.com/baidu/amis/assets/8541906/6bd111c2-7afc-4320-9eeb-9dcdb0652495)

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/8541906/9a6b41b3-2222-462d-a1c5-496321431f0f)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？3.3.0

3. 粘贴有问题的完整 `amis schema` 代码：
和schema没有关系

4. 操作步骤
```shell
git clone https://github.com/blankzust/amis-error-in-react18
pnpm i
npm run dev
```
浏览器打开http://127.0.0.1:5173/#/test

**Comment by blankzust** [comment]
试出了一个解决方案：
```diff
ReactDOM.createRoot(document.getElementById('root') as any).render(
 <React.StrictMode>
      <App />
    </React.StrictMode>
  )
```
去掉React.StrictMode就可以了
```diff
ReactDOM.createRoot(document.getElementById('root') as any).render(
      <App />
  )
```

**Comment by 2betop** [comment]
amis 不支持 React.strictMode 目前内部 store 的实现利用的 custractor 构建，willunmount 销毁。严格模式会重复一次 didmount 和 willunmount，导致 store 被销毁。
