### ISSUE TITLE
支持设置特定表单项（未隐藏）不出现在提交数据中吗

### ISSUE THREAD

**Issue by snowing-x** [baidu/amis#7734]
#### 实现场景：
表单里某些表单项可能是辅助项，这些表单项的值只是作为另一个表单项的依赖，提交表单时，不希望把辅助项也进行提交。
目前知道可以通过api的配置更改提交的数据，想了解一下，表单项可以支持这个配置吗

**Comment by 2betop** [comment]
不考虑支持。建议制定一个规范，比如辅助类的字段名 `__` 打头，然后再全局发送适配器里面，凡是字段名是这个特征的剔除掉

**Comment by snowing-x** [comment]
好的，谢谢

**Comment by zhaoyinger623** [comment]
> 全局发送适配器

请问全局发送适配器是哪个变量，怎么配置呀

**Comment by snowing-x** [comment]
> > 全局发送适配器
> 
> 请问全局发送适配器是哪个变量，怎么配置呀

<img width="607" alt="企业微信截图_5522928f-b361-485f-8a01-546ac9d7429c" src="https://github.com/baidu/amis/assets/51695385/44c0f757-74fa-47f0-b07e-edc169baca25">
https://baidu.github.io/amis/zh-CN/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA
