### ISSUE TITLE
官方可视化编辑器demo中导航（nav）组件右边配置面板无法删除导航菜单

### ISSUE THREAD

**Issue by braveletsgo** [baidu/amis#7740]
#### 描述问题：

官方可视化编辑器demo中，在可视化编辑器中在侧边栏添加一个导航（nav）组件，然后在右边组件配置面板中点击删除导航菜单项的按钮无效，控制台中有报错

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/135848617/f39a42d7-4b0d-42de-a9e9-8bdb36e244c9)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
下载官方可视化编辑器demo源码后本地跑发现该问题，然后发现官方给的演示链接中一样存在该问题
amis 可视化编辑器, 在线体验：https://aisuda.github.io/amis-editor-demo

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
源码中使用的版本为  "amis": "3.2.0"
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
官方可视化编辑器demo中，在可视化编辑器中在侧边栏添加一个导航（nav）组件，然后在右边组件配置面板中点击删除导航菜单项的按钮无效，控制台中有报错

**Comment by 2betop** [comment]
已修改交互 
<img width="315" alt="image" src="https://github.com/baidu/amis/assets/2698393/925b3387-776f-4689-9a6b-61b7bca4d59b">
