### ISSUE TITLE
按钮点击事件，发送API请求报错

### ISSUE THREAD

**Issue by atliwen** [baidu/amis#7742]
#### 描述问题：

版本 3.2.0  编辑器版本 5.5.0

按钮点击事件，发送API请求报错

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/10055836/ec09ae97-86a7-4e17-b9eb-f405c195a758)

使用 按钮点击事件发送一个api请求，报错。   直接用旧版的 直接写API 就行。 

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3.2.0  编辑器版本 5.5.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "title": "ccc",
  "body": [
    {
      "type": "button",
      "label": "按钮",
      "onEvent": {
        "click": {
          "actions": [
            {
              "outputVar": "responseResult",
              "actionType": "ajax",
              "options": {
              },
              "api": {
                "url": "/prod-api/mapi/sys_page_modeling/list",
                "method": "get",
                "requestAdaptor": "",
                "adaptor": "",
                "messages": {
                },
                "dataType": "json"
              }
            }
          ]
        }
      },
      "id": "u:c8bc7744aa0d"
    }
  ],
  "id": "u:548f3edfe5bf"
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by atliwen** [comment]
`{
  "type": "button",
  "label": "删除",
  "id": "u:a1e111a9bd8d",
  "api": {
    "method": "post",
    "url": "/prod-api/mapi/sys_page_modeling/list",
    "messages": {
    },
    "requestAdaptor": "",
    "adaptor": ""
  },
  "actionType": "ajax",
  "level": "link",
  "className": "text-danger",
  "confirmText": "确定要删除？"
}`


这样写的不报错。

**Comment by 2betop** [comment]
不能复现呢

**Comment by lhtuling** [comment]
"requestAdaptor": "",
压根没有用为啥要加上呢  个人感觉是这个问题
