### ISSUE TITLE
表格编辑组件卡死

### ISSUE THREAD

**Issue by gongkai9** [baidu/amis#7749]
#### 描述问题：

表格编辑组件容易卡死，基本上一行10个录入格，什么都不录入加到5行就开始卡顿。如果添加一个离焦时间基本没法使用，还会页面卡死。

#### 截图或视频：

https://github.com/baidu/amis/assets/3414088/4a2f760c-bc5e-41d0-bf69-5804db86c046

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm方式。

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
使用的3.3

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
我录了视频，监听了渲染情况。咋们的表格编辑组件只要改变值，会全部渲染一边。可能是这个原因导致表格性能差的。我集成了ag-grid组件测试，发现它改变值只会渲染一行而已。1000行的数据编辑滚动也不卡顿。希望各位老师能解决表格编辑组件的性能问题。

**Comment by songyinhai2006** [comment]
+1,希望作者能优化一下

**Comment by 2betop** [comment]
请帮忙试试最新的 master 分支

**Comment by 2betop** [comment]
请尝试 3.4.1 版本，有问题再 reOpen
