### ISSUE TITLE
[咨询]SDK升级版本后不支持相对路径迁移方案

### ISSUE THREAD

**Issue by phantooom** [baidu/amis#7750]
我们这边所有的api都用的是相对路径，最近看到了一个pr似乎禁止了相对路径。
1. 是否有些能力能够强制开启支持相对路径的模式？
2. 如过没有是否有批量迁移的方案，我们有数百个api需要迁移，采用了简单的替换，总是会有漏网之鱼。

https://github.com/baidu/amis/commit/71c406883a801b5f032788a37b5e5f7a6e0a7fde

**Comment by 2betop** [comment]
在这里一起讨论吧 https://github.com/baidu/amis/issues/7815
