### ISSUE TITLE
表格编辑框、表单组件性能很差

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#7757]
#### 描述问题：

如果页面（表单）存在多个表格编辑框组件，或者表格编辑框的行数比较多，页面会变得特别卡顿，我通过react_dev工具发现，只要每改动表格编辑框，就会重现渲染整个表单，这样只要页面组件一多就会十分卡，详见下面视频：
再说一下我自己的业务场景，例如下面的长截图，我有八个表格，其中主要是第一个表格是有数据录入的，我根据数据录入后在自定义js里进行计算，然后通过setValue动作事件，修改掉八个表格name对应的数组（初始化在表单的data里），只有一行时还好，但是只要行数一多，例如有三四行以上就开始非常卡顿，setValue事件执行后要等很久页面才完成了重新渲染
#### 截图或视频：

https://github.com/baidu/amis/assets/45064164/b0d45eff-05fc-4662-8ed8-cd754567b09f

![2023-08-09_152053](https://github.com/baidu/amis/assets/45064164/f2e3beac-099a-4557-afa3-e54db28f9033)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3.3.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
请尝试 3.4.1 版本，有问题再 reOpen

**Comment by Icodezhan** [comment]
> 请尝试 3.4.1 版本，有问题再 reOpen

看一下 #8267
