### ISSUE TITLE
Operation中的按钮可以根据列表中的数据来决定是否显示吗？

### ISSUE THREAD

**Issue by chareice** [baidu/amis#776]
在一个CRUD列表中，比如针对state为1的行需要提供一个A按钮，state为2的行需要提供B按钮，应该如何实现呢？

**Comment by RickCole21** [comment]
```
{
  type:"button"
  label:"A",
  visibleOn:"data.state === 1"
}

```

**Comment by chareice** [comment]
> ```
> {
>   type:"button"
>   label:"A",
>   visibleOn:"data.state === 1"
> }
> ```

感谢🙏
