### ISSUE TITLE
升级3.3.0后调试工具有bug

### ISSUE THREAD

**Issue by jianchaoming** [baidu/amis#7768]
#### 描述问题：

升级到了3.3.0，有接口访问的情况下，debug工具显示不出来

#### 截图或视频：

<img width="1507" alt="image" src="https://github.com/baidu/amis/assets/39518514/4aaf08d1-6552-4877-b56b-1f0707df83a8">
<img width="1500" alt="image" src="https://github.com/baidu/amis/assets/39518514/22f91ecc-3365-4e2d-889b-010e774353c9">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
如上图，只要配置可访问的url，调试工具就不见了

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis 3.3.0
amis-editor 5.5.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
配置可用url，必现，3.2.0没问题
顺便一提：升级3.3.0后样式问题有点多，比如：树、table固定列/头的阴影

**Comment by jianchaoming** [comment]
编辑器里面点击代码会有一大堆报错，比如：
<img width="485" alt="image" src="https://github.com/baidu/amis/assets/39518514/612ac12d-dca6-470d-8145-f02c454b1ca8">

**Comment by 2betop** [comment]
这个应该是 monaco-editor 的  worker.js  加载失败，得看是什么编译工具

**Comment by jianchaoming** [comment]
> 这个应该是 monaco-editor 的 worker.js 加载失败，得看是什么编译工具

vite+pnpm

"dependencies": {
    "@fortawesome/fontawesome-free": "6.4.0",
    "ahooks": "3.7.7",
    "amis": "3.3.0",
    "amis-core": "3.3.0",
    "amis-editor": "5.5.0",
    "amis-editor-core": "5.5.0",
    "amis-formula": "3.3.0",
    "amis-ui": "3.3.0",
    "axios": "1.4.0",
    "classnames": "2.3.2",
    "copy-to-clipboard": "3.3.3",
    "crypto-js": "4.1.1",
    "decimal.js": "10.4.2",
    "history": "5.3.0",
    "i18next": "23.2.7",
    "lodash": "4.17.21",
    "qs": "6.11.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "13.0.1",
    "react-router": "6.12.1",
    "react-router-dom": "6.12.1"
  },
  "devDependencies": {
    "@types/lodash": "4.14.195",
    "@types/node": "20.3.1",
    "@types/react": "18.0.37",
    "@types/react-dom": "18.0.11",
    "@types/react-router": "5.1.20",
    "@types/react-router-dom": "5.3.3",
    "@typescript-eslint/eslint-plugin": "5.59.0",
    "@typescript-eslint/parser": "5.59.0",
    "@vitejs/plugin-react": "4.0.0",
    "eslint": "8.38.0",
    "eslint-plugin-react-hooks": "4.6.0",
    "eslint-plugin-react-refresh": "0.3.4",
    "pre-commit": "1.2.2",
    "typescript": "5.0.2",
    "vite": "4.3.9"
  },
