### ISSUE TITLE
select相互依赖联动问题

### ISSUE THREAD

**Issue by xinghe94** [baidu/amis#777]
我有三个select 从左到右 相互依赖 通过source渲染options
![image](https://user-images.githubusercontent.com/15528239/88388984-2a0fb280-cde8-11ea-8648-0a61d579b554.png)
第一次都选完 没有问题
当产品线开始切换 一级类型接口触发 但是我并没有给它默认值 还是未选择状态 左数第三个select二级类型还是会请求source 带上上一次的一级类型messageCategory 并没有清空 schema贴上
`{
                    "type": "select",
                    "name": "platform",
                    "label": "产品线: ",
                    "required": true,
                    "labelClassName": "text-muted",
                    "inline": true,
                    "source": "taf://Unite.AmisMessageService.AmisMessageObj/message/listPlatforms"
                },
                {
                    "type": "select",
                    "name": "messageCategory",
                    "label": "一级类型: ",
                    "labelClassName": "text-muted",
                    "inline": true,
                    "source": {
                        "url": "taf://Unite.AmisMessageService.AmisMessageObj/message/listMessageCategoryNames?platform=${platform}",
                        "sendOn": "data.platform"
                    },
                    "clearable": true
                },
                {
                    "type": "select",
                    "name": "messageType",
                    "label": "二级类型: ",
                    "labelClassName": "text-muted",
                    "inline": true,
                    "source": {
                        "url": "taf://Unite.AmisMessageService.AmisMessageObj/message/listMessageTypeNames?platform=${platform}&messageCategory=${messageCategory}",
                        "sendOn": "data.platform && data.messageCategory"
                    },
                    "disabledOn": "data.messageCategory == 0",
                    "clearable": true
                },`

**Comment by 2betop** [comment]
要不要请求可以配置 sendOn, 要清空数据可以利用  formula 来完成，或者利用 select 的 autoFill 来完成

**Comment by xinghe94** [comment]
> 要不要请求可以配置 sendOn, 要清空数据可以利用 formula 来完成，或者利用 select 的 autoFill 来完成

您看下上面的schema 我的接口都配置了sendOn 并没有生效 autoFill好像不符合我的需求 你能给我指点下吗

**Comment by xinghe94** [comment]
用formula解决了 谢谢
