### ISSUE TITLE
请假一下自定义事件调用amis内部方法的使用方式

### ISSUE THREAD

**Issue by Gwq01** [baidu/amis#7773]
#### 实现场景：
在crud中 进行本地的增删改，删除数据刷新表格
#### 存在的问题：
事件执行但不会刷新表格
![image](https://github.com/baidu/amis/assets/96569767/48d835c5-35a9-44c7-a4b1-12061367d740)
![image](https://github.com/baidu/amis/assets/96569767/aedf81b5-af89-4f00-a324-5ab00a72ab45)

#### 当前方案：
![image](https://github.com/baidu/amis/assets/96569767/1afb0631-ca72-4bec-b4d5-5ecaa0dc07c6)

```
code here...
```

**Comment by 2betop** [comment]
用 `doAction` 来调别的动作，比如设置数据动作 https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE

**Comment by Gwq01** [comment]
> 用 `doAction` 来调别的动作，比如设置数据动作 https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE

![image](https://github.com/baidu/amis/assets/96569767/3843ac23-7a75-449b-b29a-243ed0410693)
我是这样解决的  我的字段中如果同时存在了value和label字段那么他的更新就会失效 所以我将label改成了label1 就可以了。
