### ISSUE TITLE
feedback 新版本编辑器没有配置 5.4.0

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#7782]
#### 描述问题：

feedback 新版本编辑器没有配置 版本5.4.0 ，只能写代码，但是还是旧的的，没有老版本放吧

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
 编辑器版本5.4.0 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
 3.1.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
无
```

4. 操作步骤
使用编辑器版本5.4.0

**Comment by hsm-lv** [comment]
老版默认关闭的，可以通过配置actionType: 'ajax'，保存后再刷新就会显示老的入口
