### ISSUE TITLE
在APP多页应用中使用nav无法高亮、联动刷新等效果不生效

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#7787]
#### 描述问题：

在APP多页应用中使用nav无法高亮、联动刷新等效果不生效

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm、react

2. amis 版本是什么？
3.3.0

**Comment by coffin03** [comment]
不高亮是因为isCurrentUrl判断是否选中逻辑有误，已解决
联动不生效是因为没有对全局变量search进行赋值操作，已解决

**Comment by lawbc** [comment]
> 不高亮是因为isCurrentUrl判断是否选中逻辑有误，已解决 联动不生效是因为没有对全局变量search进行赋值操作，已解决

请问你是怎么解决的
