### ISSUE TITLE
build构建出来后 amis子包未生成sdk目录。

### ISSUE THREAD

**Issue by learner-L** [baidu/amis#7788]
#### 描述问题：

npm 7.24.2，node 16.17.1

#### 截图或视频：

打包出来的packages/amis目录下，未发现sdk目录

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm run build

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by wujieli0207** [comment]
排查了一整天一直以为是打包失败，原来是配置了 vscode 不展示打包后的目录，实际目录是存在的
<img width="987" alt="image" src="https://github.com/baidu/amis/assets/66515269/b438792e-1bd3-443d-9dff-ecfe612607aa">

**Comment by 2betop** [comment]
不小心蒙对了
