### ISSUE TITLE
请教一下, 在移动端点击导航会有卡顿现象, 有没啥优化技巧?

### ISSUE THREAD

**Issue by nuan1989** [baidu/amis#779]
请教一下, 在移动端点击导航会有卡顿现象, 有没啥优化技巧? 包括我们的官网手册的导航也是这样. 
amis的后台模板, 好像有点陋 ....., amis底层是基于哪个框架开发的, 比如Bootstrap ?, 我要不去找个对应的后台.

**Comment by nwind** [comment]
目前已经换实现了，有问题再报吧
