### ISSUE TITLE
InputImage组件，剪裁会增大图片的大小

### ISSUE THREAD

**Issue by hereisok** [baidu/amis#7796]
#### 描述问题：

开启图片检查会导致图片超过原图大小

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/16496811/882b564c-a2a8-4b07-b8fb-6ded933deba2)
![image](https://github.com/baidu/amis/assets/16496811/f8b1c60a-e0f6-4b31-9b59-1601afff90e3)
![image](https://github.com/baidu/amis/assets/16496811/ac02d3cc-b382-4728-8a9a-62701678d119)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.3.0 （旧版本1.7.0同样也有问题）

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "asideResizor": false,
  "regions": [
    "body"
  ],
  "body": [
    {
      "type": "input-image",
      "label": "图片上传",
      "name": "image",
      "autoUpload": true,
      "proxy": true,
      "uploadType": "fileReceptor",
      "imageClassName": "r w-full",
      "id": "u:0b778a764f55",
      "accept": ".jpeg, .jpg, .png, .gif",
      "multiple": false,
      "hideUploadButton": false,
      "crop": {
        "viewMode": 1,
        "aspectRatio": 1,
        "scalable": true
      },
      "limit": true,
      "maxSize": 409600
    }
  ],
  "id": "u:79d966494595"
}
```

4. 操作步骤
如amis-json， 限制400KB大小图片， 上传一个原图大小为300多K， 简单剪裁一下， 就会导致报错

这个是原图
![2023-06-26_20-00](https://github.com/baidu/amis/assets/16496811/1df92cc7-1961-4abf-89cd-eb24bd9b8b58)

**Comment by 2betop** [comment]
这个看起来没有办法，可以尝试修改 `cropFormat` 属性为 `image/jepg` 和 `cropQuality` 为 0.7 之类的

**Comment by hereisok** [comment]
OK， 改了之后的确有一些改善
