### ISSUE TITLE
请教一下小问题

### ISSUE THREAD

**Issue by Gwq01** [baidu/amis#7797]
#### 实现场景：
![image](https://github.com/baidu/amis/assets/96569767/c3f3d030-f286-48f5-9bbe-350325acd77b)
以中文显示  
#### 存在的问题：
现在是英文方式展示的周及月份

#### 当前方案：
![image](https://github.com/baidu/amis/assets/96569767/de7cfe4d-f291-4dc3-a202-bf0e376a0174)
请问一下应该怎么将他变为中文显示，我在文档里没有看到相对性的属性。
![image](https://github.com/baidu/amis/assets/96569767/ac26444f-aa6c-4781-9885-87fc66d2ffb9)

code here...
```

**Comment by lhtuling** [comment]
默认就是中文的吧？系统文档里就是中文的！  你是不是初始化amis时候设置语言了？
![image](https://github.com/baidu/amis/assets/44140500/28198b1f-cb71-4fa2-8dda-fe9409cb3abd)

**Comment by nwind** [comment]
似乎是旧版问题
