### ISSUE TITLE
在app多页应用中使用nav，nav识别不到app多页应用的location，如何给nav的location赋值

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#7798]
#### 实现场景：
在app多页应用中使用nav，nav识别不到app多页应用的location，如何给nav的location赋值

#### 存在的问题：
在app多页应用中使用nav的to选中失效

#### 当前方案：
![image](https://github.com/baidu/amis/assets/141314006/37b568bc-f662-4bda-9a25-efafb6e13bb4)
![image](https://github.com/baidu/amis/assets/141314006/bc5b7500-b5fe-47e0-9605-b66063bce0b8)

**Comment by coffin03** [comment]
![1691833891231](https://github.com/baidu/amis/assets/141314006/5e0c08bb-c3e8-4443-82f6-25b0dfe68d62)
已解决，在全局受控数据里对search进行操作

**Comment by lawbc** [comment]
> ![1691833891231](https://private-user-images.githubusercontent.com/141314006/260219298-5e0c08bb-c3e8-4443-82f6-25b0dfe68d62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MTE5OTEsIm5iZiI6MTcyMDcxMTY5MSwicGF0aCI6Ii8xNDEzMTQwMDYvMjYwMjE5Mjk4LTVlMGMwOGJiLWMzZTgtNDQ0My04MmY2LTI1YjBkZmU2OGQ2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxNTI4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWY5Zjk4ZmNhNWE4OGFiMTA1ZmZhOTRiZDAyY2QxZGZkNjMwNTg0MTllN2YyZGQ5NTk0Yjk2NGQwYTAwNjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eAjwWHXdO0l4xkayhNWI03DG6I2knOr5zpoImGWTY60) 已解决，在全局受控数据里对search进行操作

请问app中使用nav选中问题解决了吗，我加了search:this.state.search启动就报错了
