### ISSUE TITLE
ts里引入amis-editor编译报错

### ISSUE THREAD

**Issue by ClarenceStar** [baidu/amis#780]
我是这样去引用的
`import AMisEditor from 'amis-editor'`
使用方式如下 但是tsserver编译不通过
![image](https://user-images.githubusercontent.com/15528239/88512131-9e309d00-d018-11ea-84a1-b28b0b596ef4.png)
![image](https://user-images.githubusercontent.com/15528239/88512136-a1c42400-d018-11ea-8a16-489d4c4064c5.png)
麻烦帮忙看下叻

**Comment by a775611** [comment]
不应该是这样引用吗 import { Editor } from "amis-editor";

**Comment by nwind** [comment]
import {Editor as AMISEditor} from 'amis-editor';
