### ISSUE TITLE
TinyMCE如何新增插件，比如数学函数公式

### ISSUE THREAD

**Issue by develop-kevin** [baidu/amis#7801]
#### 实现场景：
TinyMCE如何新增插件，比如数学函数公式

#### 存在的问题：
[
                        'plugins' => [
                            "advlist","autolink","autoresize","link","image","lists","charmap","preview","anchor","pagebreak","searchreplace","wordcount","visualblocks","visualchars","code","fullscreen","insertdatetime","media","nonbreaking","table","emoticons","template","help","quickbars"
                        ],
                        'toolbar'=> 'undo redo | blocks | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | preview media | fontfamily fontsize forecolor backcolor emoticons | code kityformula-editor | print help'
                    ]

#### 当前方案：
![image](https://github.com/baidu/amis/assets/30752149/6fd27c7e-89d3-4070-9ff7-35655bb1ec8a)

![image](https://github.com/baidu/amis/assets/30752149/9a3d2c5f-5c41-45f5-ace5-2739329011a2)
按照第三方提供的扩展进行添加，如何加入新的数学函数公式
```
code here...
```

**Comment by 2betop** [comment]
相关 pr 中会补充机制 https://github.com/baidu/amis/pull/7821
