### ISSUE TITLE
adapter 抓不到缓存请求

### ISSUE THREAD

**Issue by hotmaycold** [baidu/amis#781]
大佬帮忙看看
initapi设置了adapter处理数据，但是返回到页面的时候走的是缓存，抓不到

**Comment by RickCole21** [comment]
你api配了cache？

**Comment by hotmaycold** [comment]
> 你api配了cache？

没配，没配默认为0？

**Comment by hotmaycold** [comment]
> 你api配了cache？

initApi设置cache:0好像没效果

**Comment by RickCole21** [comment]
配置代码贴一下？

**Comment by hotmaycold** [comment]
> 配置代码贴一下？

这个问题已经解决了，请求不应该放在page的initApi里，应该放在crud的api里，后退是实时刷新的，而且在toolbar中操作ajax之后能reload crud
