### ISSUE TITLE
编辑器里组件上下文数据手动更改后有意义吗

### ISSUE THREAD

**Issue by snowing-x** [baidu/amis#7811]
<img width="797" alt="image" src="https://github.com/baidu/amis/assets/51695385/3e4ae1b5-dd28-411b-b150-b6b4f6f13b6c">
请问一下编辑器里组件的上下文数据弹框里为啥支持新增、编辑、删除啊？这个不能实际生效吧

**Comment by 2betop** [comment]
没啥意义，我去干掉

**Comment by 2betop** [comment]
看了下，如果是当前层是支持修改的，改完后会影响设计态，运行态不会有影响。

**Comment by 2betop** [comment]
此功能较鸡肋，打算去掉了
