### ISSUE TITLE
为什么 api.ts中isValidApi方法 在3.3版本 中 不允许直接相对路径写 api

### ISSUE THREAD

**Issue by yangsen-cn** [baidu/amis#7815]
#### 描述问题：

isValidApi方法为什么不在3.3版本中不允许直接相对路径写 api

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/12471974/d55ca9b9-e80d-4ade-af6e-e93ca4646652)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`方式使用

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
在3.2版本中，运行正常
在3.3版本中报错，使用的方式是
 const app = {
                type: 'app',
                brandName: '管理平台',
                logo: 'images/logo.png',
                header: {
                    type: 'tpl',
                    inline: false,
                    className: 'w-full',
                    tpl: '<div class="flex justify-between"><div>顶部区域左侧</div><div>顶部区域右侧</div></div>'
                },   
                api: 'site.json'
            };

4. 粘贴有问题的完整 `amis schema` 代码：

5. 操作步骤

**Comment by 2betop** [comment]
相对路径是基于页面的 pathname 来的，如果换了 pathname ，api 请求地址就可能不对，所以直接不让支持这种配置方式了。

**Comment by yangsen-cn** [comment]
如果API请求地址不对，在进行页面测试时很容易发现
为了一个可观测的配置错误，直接禁用能力，个人觉得并不合理

**Comment by phantooom** [comment]
我看到好像重新开放了相对路径的api请求，感谢。
