### ISSUE TITLE
Cards 卡片组

### ISSUE THREAD

**Issue by xhbCloud** [baidu/amis#7818]
#### 描述问题：

卡片组设置了卡片点击事件后，卡片的选中样式不触发了。

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by hsm-lv** [comment]
辛苦贴一下schema代码
