### ISSUE TITLE
请问CRUD中有每行 index 的变量吗?

### ISSUE THREAD

**Issue by orange2003** [baidu/amis#782]
想要有个名字为"序号"的列。内容就是当前行的行号从1开始自增.这么写了一下 。但是翻页序号就又从1开始了。能翻页以后继续累加吗 
{
    "$schema": "https://houtai.baidu.com/v2/schemas/page.json#",
    "type": "page",
    "title": "人员列表",
    "body": [
        {
            "type": "crud",
            "api": "/api/employee/list",
            "messages": {},
            "columns": [
                {
                    "name": "",
                    "label": "序号",
                    "type": "tpl",
                    "tpl": "<%=page>"
                }
                ]
            },
            "mode": "table"
        }
    ],
    "data": {
        "index": 0
    }
}

**Comment by RickCole21** [comment]
适配器里自己map一下好了

**Comment by RickCole21** [comment]
关了，有问题再开
