### ISSUE TITLE
表达式的使用问题

### ISSUE THREAD

**Issue by UltramanWeiLai** [baidu/amis#7826]
#### 实现场景：
场景是 2.8 升级到 3.2 后。

#### 存在的问题：
在设置一些 控件 的默认值的时候，以及使用事件触发 变量赋值 这个行为的时候，使用表达式的时候 JS 代码执行无效，例如：

![image](https://github.com/baidu/amis/assets/23336585/37b441df-a531-44e1-b882-74365e9f4076)

无法生效，但是在 2.8 中是可以生效的

#### 当前方案：
最小复现 schema 代码...
效果是一个 复选框 和 一个 文本框
当 复选框 勾选了 选项 A 的时候，文本框隐藏
![image](https://github.com/baidu/amis/assets/23336585/533cf9a1-9154-4937-a27d-7054ce30c9ff)

但是实际上的行为不符合预期

```
{
  "type": "page",
  "id": "u:ae2f8e68ce1d",
  "body": [
    {
      "type": "form",
      "title": "表单",
      "body": [
        {
          "type": "checkboxes",
          "label": "复选框",
          "name": "checkboxes",
          "multiple": true,
          "options": [
            {
              "label": "选项A",
              "value": "A"
            },
            {
              "label": "选项B",
              "value": "B"
            }
          ],
          "id": "u:d8b076cee262"
        },
        {
          "label": "文本框",
          "type": "input-text",
          "name": "text",
          "id": "u:2243b9ab0bfc",
          "hiddenOn": "${checkboxes.includes('A')}",
          "value": "${checkboxes}"
        }
      ],
      "id": "u:9c257ee6e6d6",
      "debug": true
    }
  ],
  "asideResizor": false,
  "style": {
    "boxShadow": " 0px 0px 0px 0px transparent"
  }
}
```

**Comment by lhtuling** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#contains
不能直接写js代码的  用表达式来试试看
```
          "hiddenOn": "${CONTAINS(checkboxes,'A')}",
```

**Comment by UltramanWeiLai** [comment]
> https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#contains 不能直接写js代码的 用表达式来试试看
> 
> ```
>           "hiddenOn": "${CONTAINS(checkboxes,'A')}",
> ```

2.8 是可以写 JS 的，表达式的函数东西还是有限的，没有 JS 灵活，而且之前配置的很多都用了 JS

**Comment by lhtuling** [comment]
> > https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#contains 不能直接写js代码的 用表达式来试试看
> > ```
> >           "hiddenOn": "${CONTAINS(checkboxes,'A')}",
> > ```
> 
> 2.8 是可以写 JS 的，表达式的函数东西还是有限的，没有 JS 灵活，而且之前配置的很多都用了 JS

那没办法了不是要么不升级 要么就更换么~~也不算太麻烦  基本常用的js方法都封装了表达式函数 

刚才帮你测试了可以这样
```
        "hiddenOn": "data.checkboxes.includes('A')"
```
![image](https://github.com/baidu/amis/assets/44140500/3f23e21f-faf7-43e6-b556-995bc73dd97f)

**Comment by UltramanWeiLai** [comment]
> > > https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#contains 不能直接写js代码的 用表达式来试试看
> > > ```
> > >           "hiddenOn": "${CONTAINS(checkboxes,'A')}",
> > > ```
> > 
> > 
> > 2.8 是可以写 JS 的，表达式的函数东西还是有限的，没有 JS 灵活，而且之前配置的很多都用了 JS
> 
> 那没办法了不是要么不升级 要么就更换么~~也不算太麻烦 基本常用的js方法都封装了表达式函数
> 
> 刚才帮你测试了可以这样
> 
> ```
>         "hiddenOn": "data.checkboxes.includes('A')"
> ```
> 
> ![image](https://user-images.githubusercontent.com/44140500/261572020-3f23e21f-faf7-43e6-b556-995bc73dd97f.png)

意思是写纯 字符串的 JS 是可行的？ 不用 ${} 进行包裹即可？回头试试

**Comment by lhtuling** [comment]
> > > > https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression#contains 不能直接写js代码的 用表达式来试试看
> > > > ```
> > > >           "hiddenOn": "${CONTAINS(checkboxes,'A')}",
> > > > ```
> > > 
> > > 
> > > 2.8 是可以写 JS 的，表达式的函数东西还是有限的，没有 JS 灵活，而且之前配置的很多都用了 JS
> > 
> > 
> > 那没办法了不是要么不升级 要么就更换么~~也不算太麻烦 基本常用的js方法都封装了表达式函数
> > 刚才帮你测试了可以这样
> > ```
> >         "hiddenOn": "data.checkboxes.includes('A')"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/44140500/261572020-3f23e21f-faf7-43e6-b556-995bc73dd97f.png)
> 
> 意思是写纯 字符串的 JS 是可行的？ 不用 ${} 进行包裹即可？回头试试

是的吧  然后取值需要data.   我没怎么这样用过  刚才看文档测试发现ok
