### ISSUE TITLE
crud的重置按钮无法清除原有过滤信息

### ISSUE THREAD

**Issue by yahahawork** [baidu/amis#7827]
#### 描述问题：

crud的syncLocation为true时，打开页面时url已经有参数（使用返回回到上一页），重置过滤器表单没有效果

#### 截图或视频：

1、初始url带参数
![image](https://github.com/baidu/amis/assets/104351842/c56db510-61be-47c4-a170-27b9e83279f8)
2、点击重置后
![image](https://github.com/baidu/amis/assets/104351842/6a71f5b1-86f9-4ba3-a8fe-d4e8ffebced1)
3、点击搜索后
![image](https://github.com/baidu/amis/assets/104351842/cf992326-a4a6-4c8a-89d6-29b91a1d8f05)
4、再点重置
![image](https://github.com/baidu/amis/assets/104351842/436f4249-744a-4c31-9bc4-5cb4f5742803)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
`3.3`

**Comment by hsm-lv** [comment]
目前的重置只针对条件筛选表单中的字段，不含盖地址栏中其他字段

**Comment by yahahawork** [comment]
@hsm-lv 请问下后面版本会处理url的字段吗

**Comment by hsm-lv** [comment]
或者，如果可以用提交+清空动作：
```json
{
    "type": "button",
    "label": "清空表单并提交",
    "actionType": "clear-and-submit"
  }
```
