### ISSUE TITLE
表格添加行，通过第一个下拉选择框，选择之后，其他列的数据自动适配上，有方式可以做吗？

### ISSUE THREAD

**Issue by rodchen-king** [baidu/amis#783]
![image](https://user-images.githubusercontent.com/19780441/88617762-04292d00-d0ca-11ea-8a95-c395ca888674.png)
表格添加行，通过第一个下拉选择框，选择之后，其他列的数据自动适配上，有方式可以做吗？

**Comment by RickCole21** [comment]
目前应该不可以
