### ISSUE TITLE
text的options是从接口拿的，json中怎么去拿接口其他数据呢？

### ISSUE THREAD

**Issue by llfylwg** [baidu/amis#784]
接口返回：  
 `options: [
 {
    label:  111,
    value: 222,
    count:  333
 }
]`   
 每次选中下拉选项后需要拿到count值，该怎么做呢？

**Comment by RickCole21** [comment]
select 组件上配置`joinValues:false`，选中选项后，当前组件的值就是选中的完整对象了，具体要怎么使用你应该知道了吧

**Comment by RickCole21** [comment]
或者也可以用autoFill，文档里先找找

**Comment by llfylwg** [comment]
哦哦，我没说清楚，前提是使用的是text组件，要实现这种效果

**Comment by llfylwg** [comment]
该怎么搞呢？

**Comment by RickCole21** [comment]
text也可以当做选择器组件使用，https://baidu.github.io/amis/docs/components/form/text#%E9%80%89%E6%8B%A9%E5%99%A8%E6%A8%A1%E5%BC%8F

也就可以用这些功能：
https://baidu.github.io/amis/docs/components/form/options
