### ISSUE TITLE
definitions 抽离body报错? data 如何扩展私有字段呢(drawer/dlg等可以)？

### ISSUE THREAD

**Issue by JoweiBlog** [baidu/amis#785]
### definitions 抽离body报错? 
eg:
{
    "body": [
        {
            "type": "button",
            "label": "add",
            "actionType": "drawer",
            "drawer": {
                "body": {
                    "$ref": "adslot_dlg"
                }
            }
        }
    ],
    "definitions": {
        "dlg": {
            "type": "form"
        }
    }
}

Error: 找不到对应的渲染器
Path: page/drawer/drawer/body/body/

### data 如何扩展私有字段呢(drawer/dlg等可以)？
对作用域理解不是特别好。
比如想在某个form下扩展

"data": {
  "&": "&&",
  "_priv": "test"
}
但control中并没有_priv 字段。

**Comment by nwind** [comment]
那个是只有 data 才有的配置
