### ISSUE TITLE
项目引入amis-ui后编译报错

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#7853]
#### 描述问题：

今天我那截至到至今最新的master编译打包后在上传到我自己的私服，我的项目再引入amis，然后编辑项目时报错了，我看应该是这里写得引入路径有问题，写死成相对路径了
![屏幕截图 2023-08-17 113808](https://github.com/baidu/amis/assets/45064164/3a04ffb7-51b9-467e-902a-c67724d4814a)

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
确实有问题，看来编译的 esm 版本有问题了我查一下编译

**Comment by 2betop** [comment]
原因已定位，因为 package 里面的 package.json 缺少依赖 rc-overflow  https://github.com/baidu/amis/pull/7880
