### ISSUE TITLE
使用 service组件，在amis-editor设计器编辑时报错，但预览时正常显示。

### ISSUE THREAD

**Issue by shenjler** [baidu/amis#7857]
#### 描述问题：

使用 service组件，在amis-editor设计器编辑时报错，但预览时正常显示。

#### 截图或视频：

<img width="1502" alt="image" src="https://github.com/baidu/amis/assets/4507904/26d3c044-fa02-49aa-b7b8-550716c023ab">

<img width="1491" alt="image" src="https://github.com/baidu/amis/assets/4507904/8c79f88e-03d3-4203-adfb-5d6c58c1a060">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
通过npm方式 React使用amis

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
 版本：node 14 、amis = 3.3.0、amis-editor = 5.5.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "title": "test service",
  "body": [
    {
      "type": "service",
      "schemaApi": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/service/schema?type=controls"
    }
  ],
  "id": "u:2d210553f5e3"
}
```

**Comment by 2betop** [comment]
版本问题？
<img width="1649" alt="image" src="https://github.com/baidu/amis/assets/2698393/a7eeb4f9-4b1d-49c1-a08a-e2edd9bc0bf8">

**Comment by shenjler** [comment]
是啊，有点奇怪。同样的配置，在当前amis项目是没报错的。但在amis-editor-demo （https://github.com/aisuda/amis-editor-demo）项目运行的，把amis升级版本到3.3.0（试了3.2.0或3.3.0都报错），amis-editor版本是5.5.0，还是会报这个错误。

<img width="1511" alt="image" src="https://github.com/baidu/amis/assets/4507904/70ced06c-8996-4485-ad8c-747086bd71fa">

在amis-editor-demo配置情况：
<img width="1511" alt="image" src="https://github.com/baidu/amis/assets/4507904/8f175eba-2662-43dd-b978-f5bb1e4549d9">

**Comment by shenjler** [comment]
<img width="996" alt="image" src="https://github.com/baidu/amis/assets/4507904/0ad152d5-1a25-4e31-94ab-b85e19436bcc">

**Comment by hsm-lv** [comment]
https://github.com/baidu/amis/pull/7474
