### ISSUE TITLE
tabs组件的tabsClassName属性不生效

### ISSUE THREAD

**Issue by Miao0er** [baidu/amis#7859]
#### 描述问题：

tabs组件的tabsClassName属性不生效

#### 截图或视频：

<img width="1549" alt="截屏2023-08-17 15 18 47" src="https://github.com/baidu/amis/assets/37327757/5ab229f7-9406-4926-9ca0-ad47cfe580a8">

#### 如何复现（请务必完整填写下面内容）：

官网文档可复现

**Comment by 2betop** [comment]
文档有点过时，请参考这个 https://baidu.github.io/amis/zh-CN/components/tabs#%E5%B1%9E%E6%80%A7%E8%A1%A8
