### ISSUE TITLE
crud 中使用button:ajax 关闭feedback弹窗会自动刷新crud

### ISSUE THREAD

**Issue by hotmaycold** [baidu/amis#786]
大佬帮忙看看
crud 中使用button:ajax 关闭feedback弹窗会自动刷新crud
actions已经置空了，其他dialog不会出现这种情况

**Comment by RickCole21** [comment]
貌似是有这个问题，后续修复吧

**Comment by hotmaycold** [comment]
> 貌似是有这个问题，后续修复吧

行

**Comment by oyhngithub** [comment]
button设置"reload": "none"试过吗

**Comment by whuwangyong** [comment]
> button设置"reload": "none"试过吗

无效。

这个刷新是分两步：
1. 点击button，开始ajax请求，同时crud组件清空
2. 关闭feedback之后，curd组件重新展示

设置"reload": "none"之后，不能阻止第一步，只能阻止第二步，最后结果就是一个空的crud组件。

**Comment by 2betop** [comment]
新版本 reload: “none” 是有效的，请升级版本。有问题再开
