### ISSUE TITLE
SDK 方式使用，选项卡渲染报错

### ISSUE THREAD

**Issue by KillenMr** [baidu/amis#7860]
#### 描述问题：

SDK 方式使用，选项卡渲染报错

#### 截图或视频：

<img width="640" alt="image" src="https://github.com/baidu/amis/assets/76677526/824a624a-5d33-4932-bf17-908fada84803">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

sdk

3. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3.3.0 

5. 粘贴有问题的完整 `amis schema` 代码：
```
{
      "type": "tabs",
      "mode": "line",
      "tabs": [
        {
          "title": "选项卡1",
          "body": "选项卡内容1"
        },
        {
          "title": "选项卡2",
          "body": "选项卡内容2"
        },
        {
          "title": "选项卡3",
          "body": "选项卡内容3"
        }
      ]
    },
```

6. 操作步骤

**Comment by KillenMr** [comment]
相同类型的 Portlet 门户栏目渲染没有问题

**Comment by 2betop** [comment]
能否提供一个问题仓库，没用用 vite 跑过 sdk，只跑过 npm 包
