### ISSUE TITLE
页面里select获取的数据源，其他组件可以回去到这个数据源吗？

### ISSUE THREAD

**Issue by rodchen-king** [baidu/amis#788]
页面里select获取的数据源，其他组件可以回去到这个数据源吗？

**Comment by daffy6537** [comment]
form下面的组件都可以吧

**Comment by RickCole21** [comment]
这个场景？

https://baidu.github.io/amis/docs/components/form/options#%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%85%85-autofill

**Comment by RickCole21** [comment]
暂无回应，先关了
