### ISSUE TITLE
Textarea组件输出的值没有带上换行符

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#7884]
#### 描述问题：

Textarea组件输出的值没有带上换行符，期望换行能带上\n

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/37805363/8b0bf7f1-e6e4-420a-a813-b1f534001d6c)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
存在

4. 操作步骤
按图所示，官网复现即可

**Comment by lhtuling** [comment]
![image](https://github.com/baidu/amis/assets/44140500/f5fc31b9-4693-4985-8e25-d5f7628e224a)
没毛病，  是debug上面估计做什么处理了  已提交表单时候为准吧~~
