### ISSUE TITLE
文件上传组件设置为必须输入的时候。报错

### ISSUE THREAD

**Issue by orange2003** [baidu/amis#789]
代码如下。 再amis edit 中生成的代码。在文件上传设置为"required": true,的时候。即使选择了文件。第一次点提交也会提示验证不通过。需要再点一次提交才能正常提交表单。
{
    "$schema": "https://houtai.baidu.com/v2/schemas/form.json#",
    "type": "form",
    "title": "人员批量导入",
    "controls": [
        {
            "type": "select",
            "label": "所属服务商:",
            "name": "select",
            "options": [
                {
                    "label": "选项A",
                    "value": "A"
                },
                {
                    "label": "选项B",
                    "value": "B"
                }
            ],
            "checkAll": false,
            "mode": "inline",
            "size": "md",
            "required": true
        },
        {
            "type": "file",
            "label": "人员信息文件:",
            "name": "file",
            "btnLabel": "请选择文件",
            "useChunk": "auto",
            "chunkSize": 5242880,
            "startChunkApi": "",
            "chunkApi": "",
            "finishChunkApi": "",
            "accept": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "fileField": "file",
            "hideUploadButton": true,
            "mode": "inline",
            "className": "",
            "labelClassName": "m-l-lg",
            "asBlob": true,
            "autoUpload": false,
            "required": true,
            "maxLength": 1,
            "maxSize": 20480
        },
        {
            "type": "link",
            "body": "批量导入模板下载",
            "className": "m-l-lg",
            "href": "https://gyoss.inabei.cn/product/template/EmpImportTemplate.xlsx"
        },
        {
            "type": "tpl",
            "tpl": "<p><span style=\"color: #e03e2d;\">* 只能上传已填写好的标准模板文件，数据记录最多不能超过500条，且文件大小不超过2M</span></p>",
            "inline": false
        }
    ],
    "submitText": "上传",
    "actions": [
        {
            "type": "submit",
            "label": "提交",
            "level": "primary",
            "actionType": "",
            "feedback": {
                "title": "人员导入确认",
                "body": {
                    "type": "crud",
                    "api": "",
                    "columns": [
                        {
                            "name": "empName",
                            "label": "姓名",
                            "type": "text"
                        },
                        {
                            "name": "idcard",
                            "label": "身份证",
                            "type": "text"
                        },
                        {
                            "type": "text",
                            "label": "银行卡",
                            "name": "accountNo"
                        },
                        {
                            "type": "text",
                            "label": "手机",
                            "name": "phone"
                        }
                    ]
                },
                "size": "md"
            }
        }
    ],
    "api": {
        "method": "post",
        "url": "/api/employee/import"
    },
    "resetAfterSubmit": true
}

**Comment by orange2003** [comment]
没人理我还是自己。说下怎么解决的 把 "autoUpload": false 改为  true 就行了。这一点文档上说的不清楚。

**Comment by 2betop** [comment]
我映像中这个 case 会自动触发上传，然后上传完后会自动再次提交的呢

**Comment by orange2003** [comment]
因为我是 提交成二进制的形式。要跟表单一起提交。所以设置了 "autoUpload": false  。但是貌似这样在 "required": true的情况下一定要点两次表单提交才行。 第一次永远说校验失败。 然后改成 "autoUpload": true
