### ISSUE TITLE
编辑页面外面是一个商品列表，想通过新增弹出框，选择多条商品之后，回传到页面商品列表，可以做到吗？

### ISSUE THREAD

**Issue by rodchen-king** [baidu/amis#792]
编辑页面外面是一个商品列表，想通过新增弹出框，选择多条商品之后，回传到页面商品列表，可以做到吗？

![image](https://user-images.githubusercontent.com/19780441/88753207-40be5c80-d18e-11ea-9bd0-d5205acc0d67.png)

![image](https://user-images.githubusercontent.com/19780441/88753191-39974e80-d18e-11ea-9430-2852162c2c50.png)

**Comment by daffy6537** [comment]
保存后，触发列表刷新，从接口里拉吧
