### ISSUE TITLE
【Formula公式】浮点计算问题好像并没有解决

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#7920]
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/formula#%E4%BD%BF%E7%94%A8%E6%96%B0%E8%A1%A8%E8%BE%BE%E5%BC%8F%E8%AF%AD%E6%B3%95
![image](https://github.com/baidu/amis/assets/44140500/ec9bca0f-e0ba-40db-889c-d63e3c5b4098)

**Comment by 2betop** [comment]
目前需要自己补 ROUND 公式

**Comment by lhtuling** [comment]
ok
