### ISSUE TITLE
Crud设置操作列固定后，当表格变小触发固定时无法正常显示固定列样式阴影，需要拉动一次滚动条后才能显示固定列阴影

### ISSUE THREAD

**Issue by jiasws** [baidu/amis#7924]
如题，如图
![pic](https://sws.qva.cc/202308/webstorm64_3vGUqJ.gif)

**Comment by cat69fl** [comment]
感觉3.3版本的crud组件bug 好多了，希望下个版本这些bug都能解决掉，特别是性能问题
