### ISSUE TITLE
对于api的pickerMode的疑问

### ISSUE THREAD

**Issue by snowing-x** [baidu/amis#7929]
<img width="570" alt="企业微信截图_c91823f8-6a1b-473c-8d6b-f2c310684a05" src="https://github.com/baidu/amis/assets/51695385/69e7319b-4196-469b-a482-f39d3dc3f38d">

在APIControl里看到了pickerMode，看起来像是支持选择api，然后用选择的api配置替代原来的api字段。
但是我看文档上好像没有相关的说明，是这种方案有什么问题吗？

**Comment by 2betop** [comment]
这个是给平台实现下拉选择 api 功能留的口子，编辑器本身是填写 api
