### ISSUE TITLE
combo多项表单值初始化

### ISSUE THREAD

**Issue by xinghe94** [baidu/amis#793]
scaffold这个字段只能设置单组初始化 但是我想初始化多组表单的值 怎么实现呢

**Comment by RickCole21** [comment]
这个是添加combo每一项的时候，表单项默认的值

你说的是设置combo默认值吧，设置对象数组就行，类似：

```
value:[
    {a:'a1',b:'b1'},
    {a:'a2',b:'b2'}
]
```

**Comment by xinghe94** [comment]
> 这个是添加combo每一项的时候，表单项默认的值
> 
> 你说的是设置combo默认值吧，设置对象数组就行，类似：
> 
> ```
> value:[
>     {a:'a1',b:'b1'},
>     {a:'a2',b:'b2'}
> ]
> ```

非常感谢 会用了
