### ISSUE TITLE
强烈建议option类的组件的labelField支持tpl或jsonPath表达式

### ISSUE THREAD

**Issue by vexos-io** [baidu/amis#7934]
如
{
  type: 'select',
  source: '${user.pets}',
  valueField: 'origin.id'
  labelField: 'origin.name'
}

这样会极大减少后端接口数量，团队内互相吵架的事就少很多了

**Comment by Icodezhan** [comment]
没看懂你这操作？如果origin是数组，那你source直接user.pets.origin，然后labelField:"name"，valueField:"id"，即刻，如果user.pets才是数组，那是元素的origin.id当作value的话，你在source使用数组函数map一下也就好了.................

**Comment by vexos-io** [comment]
感谢指导，我没想到可以用map，谢谢！！
