### ISSUE TITLE
panelBodyCreator方法中的context上下文参数怎样可以触发更新

### ISSUE THREAD

**Issue by zhaoyinger623** [baidu/amis#7935]
#### 描述问题：

例如日期选择组件，拖动到编辑器中，修改日期类型为“日期时间”，默认值、最大值、最小值的日期选择组件不会同步更新成“日期时间”，需要取消选中一下，再选择日期组件才能更新。

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/62292666/4eb512d8-f708-47ff-a368-f6385d2c83c9)
![image](https://github.com/baidu/amis/assets/62292666/0d7ce9e4-fb73-4bdd-b355-600c70b8865b)

**Comment by wibetter** [comment]
@zhaoyinger623 已在此处修复：https://github.com/baidu/amis/pull/8171
