### ISSUE TITLE
http返回的结果采用setValue方式绑定，数据未显示到界面

### ISSUE THREAD

**Issue by zhouruisong** [baidu/amis#7936]
#### 实现场景：
我想要实现请求http后结果展示出来

#### 存在的问题：
采用ajax请求发送了http请求，结果已经返回，toast也弹出json内容，但是结果text中数据一直没有，采用setValue方式，数据未显示。
如何实现请求后将结果数据绑定并且显示出来

#### 当前方案：
代码如下：

```
(function() {
    const response = {
      "type": "page",
      "title": "",
      "asideResizor": false,
      "pullRefresh": {
        "disabled": true
      },
      "asideSticky": true,
      "remark": "",
      "data": {
      },
      "regions": [
        "body"
      ],
      "style": {
        "backgroundColor": "rgba(203, 200, 200, 1)"
      },
      "body": [
        {
          "type": "container",
          "body": [
            {
              "type": "container",
              "body": [
                {
                  "type": "tpl",
                  "tpl": "输入是:${cmdname} 输出是:${cmdresp}",
                  "clearable": true,
                  "name": "cmdresp",
                  "inline": true,
                  "id": "cmd-resp",
                  "style": {
                    "text-align": "left"
                  }
                }
              ],
              "style": {
                "position": "static",
                "display": "block",
                "textAlign": "left",
                "background": "#ffffff"
              },
              "wrapperBody": false,
              "id": "u:f2f1c03bf649",
              "isFixedHeight": false,
              "isFixedWidth": false,
              "size": "sm"
            }
          ],
          "style": {
            "position": "static",
            "display": "block",
            "overflowY": "auto",
            "height": "400px",
            "textAlign": "left",
            "background": "#ffffff"
          },
          "wrapperBody": false,
          "isFixedHeight": true,
          "isFixedWidth": false,
          "size": "lg",
          "stickyStatus": false
        },
        {
          "type": "flex",
          "className": "p-1",
          "items": [
            {
              "type": "container",
              "body": [
                {
                  "type": "input-group",
                  "name": "input-group",
                  "label": "请输入命令",
                  "body": [
                    {
                      "type": "input-text",
                      "inputClassName": "b-r-none p-r-none",
                      "name": "cmdname",
                      "id":"input-cmd"
                    },
                    {
                      "type": "button",
                      "label": "提交",
                      "level": "primary",
                      "onEvent": {
                        "click": {
                          "weight": 0,
                          "actions": [
                            {
                              "outputVar": "responseResult",
                              "actionType": "ajax",
                              "args": {
                                "options": {
                                  "silent": true
                                },
                                "api": {
                                  "method": "post",
                                  "url": "/v1/remotectl/commands",
                                  "requestAdaptor": "",
                                  "adaptor": "",
                                  "messages": {
                                  },
                                  "dataType": "json",
                                  "data": {
                                    "to": [
                                      {
                                        "sn": "YXTO3SWMFK6EPUMKXPAP27244755CF000002"
                                      }
                                    ],
                                    "from": "iot_web_console",
                                    "command": "sh",
                                    "publishNow": true,
                                    "maxRetries": 1,
                                    "expires": 1800,
                                    "detached": true,
                                    "body": {
                                      "shcmd": "${cmdname}",
                                      "sn": "YXTO3SWMFK6EPUMKXPAP27244755CF000002"
                                    }
                                  },
                                }
                              },
                            },
                            {
                              "actionType": "toast",
                              "expression": "${event.data.responseResult !== 'undefined'}",
                              "args": {
                                "msg": "var1:${event.data.responseResult.to[0].id}, var2:${event.data.responseResult.to[0].sn}"
                              }
                            },
                            {
                              "actionType": "setValue",
                              "args": {
                                "cmdresp": "${event.data.responseResult.to[0].id}"
                              },
                              "componentId":"cmd-resp"
                            },
                            {
                              "actionType": "clear",
                              "componentId":"input-cmd"
                            },
                          ]
                        }
                      }
                    }
                  ]
                }
              ],
              "size": "sm",
              "style": {
                "position": "static",
                "display": "block",
                "flex": "1 1 auto",
                "flexGrow": 1,
                "flexBasis": "200px",
                "overflowX": "auto",
                "background": "#ffffff"
              },
              "wrapperBody": false,
              "isFixedHeight": false,
              "isFixedWidth": false
            }
          ],
          "style": {
            "position": "relative"
          }
        }
      ]
    }
    
    window.jsonpCallback && window.jsonpCallback(response);
})();
```

**Comment by zhouruisong** [comment]
{
                              "actionType": "toast",
                              "expression": "${event.data.responseResult !== 'undefined'}",
                              "args": {
                                "msg": "cmdresp:${event.data.responseResult.to[0].id} ,var1:${event.data.responseResult.to[0].id}, var2:${event.data.responseResult.to[0].sn}"
                              }
                            },
                            {
                              "actionType": "setValue",
                              "args": {
                                "cmdresp": "${event.data.responseResult.to[0].id}"
                              },
                              "componentId":"cmd-resp"
                            },

**Comment by zhouruisong** [comment]
下面toast已经打印出来cmdresp的值了，但是为什么setValue没有成功，界面没有任何显示，还需要reload吗？

{
                              "actionType": "toast",
                              "expression": "${event.data.responseResult !== 'undefined'}",
                              "args": {
                                "msg": "cmdresp:${event.data.responseResult.to[0].id} ,var1:${event.data.responseResult.to[0].id}, var2:${event.data.responseResult.to[0].sn}"
                              }
                            },
                            {
                              "actionType": "setValue",
                              "args": {
                                "cmdresp": "${event.data.responseResult.to[0].id}"
                              },
                              "componentId":"cmd-resp"
                            },

**Comment by zhouruisong** [comment]
没人解答吗？

**Comment by zhouruisong** [comment]
> tpl 没有数据域， setValue 更新顶层的page试试，另外args的参数格式是 args: {value: {"cmdresp": "${event.data.responseResult.to[0].id}"}}

你好，刷新顶层的page是ok的，请问amis有没有动态触发某种请求，比如上面的例子我获取到了一个id后，会触发在以这个id为body的定时请求？ 是否要设置一个触发动作或者标记，在满足这个条件后就会干什么事？  多谢回复

**Comment by allenve** [comment]
可以通过sendOn配置请求条件  参考：https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api?page=1#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E6%9D%A1%E4%BB%B6

**Comment by zhouruisong** [comment]
> 可以通过sendOn配置请求条件 参考：https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api?page=1#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E6%9D%A1%E4%BB%B6

非常感谢

**Comment by zhouruisong** [comment]
> 可以通过sendOn配置请求条件 参考：https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api?page=1#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E6%9D%A1%E4%BB%B6

你好，参考你发的链接，把sendOn放到了如下位置，但是没有触发发送http请求


 const response = {
      "type": "page",
      "title": "执行命令",
      "id": "cmd-resp",
      "asideResizor": false,
      "pullRefresh": {
        "disabled": true
      },
      "asideSticky": true,
      "remark": "",
      "data": {
      },
      "regions": [
        "body"
      ],
      "style": {
        "backgroundColor": "rgba(203, 200, 200, 1)"
      },
      "body": [
        {
          "type": "container",
          "body": [
            {
              "type": "container",
              "body": [
                {
                  "label": "命令界面",
                  "type": "tpl",
                  "tpl": "输入是:${cmdname} 输出是:${cmdresp}",
                  "clearable": true,
                  "name": "cmdresp",
                  "inline": true,
                  "style": {
                    "text-align": "left"
                  },
                  **"source": {
                    "method": "get",
                    "url": "/v1/remotectl/commands/responses?from=iot_web_console&id=${cmdresp}",
                    "sendOn": "${cmdresp !== 'undefined'}"
                  }**
                }
              ],
              "style": {
                "position": "static",
                "display": "block",
                "textAlign": "left",
                "background": "#ffffff"
              },

**Comment by zhouruisong** [comment]
cmdresp返回的值是一个数字组成的字符串

**Comment by allenve** [comment]
tpl 没有 source 属性，可以外面套一个service组件

**Comment by zhouruisong** [comment]
> tpl 没有 source 属性，可以外面套一个service组件

这样两个service或者其中一个是service，都无法 触发sendOn，难道是"sendOn": "${cmdresp} !== 'undefined'"的问题？

 "body": [
        {
          "type": "service",
          "body": [
            {
              "type": "service",
              "body": [
                {
                  "label": "命令界面",
                  "type": "tpl",
                  "tpl": "sn是: ${sn} 输入是:${cmdname} 输出是:${cmdresp}",
                  "clearable": true,
                  "name": "cmdresp",
                  "inline": true,
                  "style": {
                    "text-align": "left"
                  },
                  "source": {
                    "method": "get",
                    "url": "/v1/remotectl/commands/responses?from=iot_web_console&id=${cmdresp}",
                    "sendOn": "${cmdresp} !== 'undefined'"
                  }
                }
              ],

**Comment by allenve** [comment]
{
      "type": "service",
      "body": [
        {
          "label": "命令界面",
          "type": "tpl",
          "tpl": "sn是: ${sn} 输入是:${cmdname} 输出是:${cmdresp}",
          "clearable": true,
          "name": "cmdresp",
          "inline": true,
          "style": {
            "text-align": "left"
          },
          "id": "u:a7a52d63734d"
        }
      ],
      "id": "u:a6dae975831b",
      "api": {
        "method": "get",
        "url": "/v1/remotectl/commands/responses?from=iot_web_console&id=${cmdresp}",
        "sendOn": "cmdresp !== undefined"
      }
    }

**Comment by zhouruisong** [comment]
> { "type": "service", "body": [ { "label": "命令界面", "type": "tpl", "tpl": "sn是: ${sn} 输入是:${cmdname} 输出是:${cmdresp}", "clearable": true, "name": "cmdresp", "inline": true, "style": { "text-align": "left" }, "id": "u:a7a52d63734d" } ], "id": "u:a6dae975831b", "api": { "method": "get", "url": "/v1/remotectl/commands/responses?from=iot_web_console&id=${cmdresp}", "sendOn": "cmdresp !== undefined" } }

多谢了
