### ISSUE TITLE
编辑器页面外观配置渲染器找不到

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#7937]
![image](https://github.com/baidu/amis/assets/141314006/712cc770-a6cc-4254-84b5-3e8242df4037)

**Comment by allenve** [comment]
未复现   使用方式和版本是什么？

**Comment by coffin03** [comment]
使用方式：私服部署，npm私服使用
版本：
    "amis": "3.3.0",
    "amis-core": "3.3.0",
    "amis-editor": "5.5.0",
    "amis-editor-core": "5.5.0",
问题：
单独启动amis底层项目没有问题，第三方项npm引用后，编辑器page组件外观配置出现找不到渲染器问题
希望提供可能出现这种问题的原因及解决思路，感谢

**Comment by coffin03** [comment]
> 未复现 使用方式和版本是什么？

使用方式：私服部署，npm私服使用
版本： “amis”： “3.3.0”， “amis-core”： “3.3.0”， “amis-editor”： “5.5.0”，
“amis-editor-core”： “5.5.0”， 问题：

单独启动amis底层项目没有问题，第三方项npm引用后，编辑器页面组件外观配置出现找不到渲染器问题
希望提供可能出现这种问题的原因及解决思路，


感谢

**Comment by allenve** [comment]
npm install amis-theme-editor 试试

**Comment by coffin03** [comment]
> npm install amis-theme-editor 试试

版本 2.0.11-beta.2   不行

**Comment by sspl-d** [comment]
只能是依赖安装导致的问题。我拿我手上的项目做了个测试，使用yarn安装完和你一样丢失，npm安装却正常。
如果你使用的是yarn那大概率是这个问题，删了node_modules换npm安装可解。如果是npm那就把demo里对应的依赖版本都复制过去重新安装试试。希望对你有帮助。😘

**Comment by 2betop** [comment]
也可能是安装了多份 amis-core，注册进去的渲染器和运行时跑的不是一份代码导致，解决办法是统一 amis-core 的版本，在工程里面只有一份

**Comment by coffin03** [comment]
> 也可能是安装了多份 amis-core，注册进去的渲染器和运行时跑的不是一份代码导致，解决办法是统一 amis-core 的版本，在工程里面只有一份

您说的安装多份指的是amis其他依赖库（例如amis、amis-editor这些）里所依赖的amis-core是嘛

**Comment by mengxiangji** [comment]
@coffin03 请问解决了吗

**Comment by mengxiangji** [comment]
> 也可能是安装了多份 amis-core，注册进去的渲染器和运行时跑的不是一份代码导致，解决办法是统一 amis-core 的版本，在工程里面只有一份
使用私有仓库的amis-editor会出现这个问题，用官方包没问题，我把源码拉下来什么也没改直接build发布包也会有这个问题
