### ISSUE TITLE
Textarea组件如果输入了反斜杠\再换行, 详情展示就会没有内容

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#7942]
#### 描述问题：

Textarea组件如果输入了反斜杠\再换行, 详情展示就会没有内容,也就是内容为aa\\\nbb的话,会导致静态展示表单的textarea组件不渲染内容

#### 截图或视频：

1. 我们在textarea输入如下内容
![image](https://github.com/baidu/amis/assets/37805363/914e3053-f530-453f-8926-2787851849b4)
2. 我们到设计器中,设计一个详情页面如下
![image](https://github.com/baidu/amis/assets/37805363/5792e0f7-b89a-4737-a6b0-3ffc5bba4161)
3. 然后再点击预览,没有内容呈现
![image](https://github.com/baidu/amis/assets/37805363/80e00eda-623f-4dcc-a9fd-3beaa76eb6ea)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网使用

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新版本存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "form",
  "data": {
    "textarea": "aa\\\nbb"
  },
  "api": "/amis/api/mock2/form/saveForm",
  "body": [
    {
      "name": "textarea",
      "type": "textarea",
      "label": "多行文本",
      "id": "u:e8b7f2900196"
    }
  ],
  "id": "u:aeea1a0042b8",
  "static": true
}
```

4. 操作步骤
操作步骤见上方

**Comment by lhtuling** [comment]
![1af1f754-2194-423b-b6d2-a02704b604fa](https://github.com/baidu/amis/assets/44140500/d1a3506d-1ce0-4b11-86d8-93ed4dd4e347)
