### ISSUE TITLE
富文本 上传/插入 视频 功能

### ISSUE THREAD

**Issue by bestraven** [baidu/amis#7943]
#### 描述问题：

如题，配置了videoReceiver 没有上传按钮

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/16594309/edb5edbc-eaa2-41c8-92e7-ce4800026890)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
              {
                              "type": "input-rich-text",
                              "label": "图文详情",
                              "name": "content",
                              "receiver": "/oss/aliyun",
                              "videoReceiver": "/oss/aliyun",
                              "size": "lg",
                              "options": {
                                "min_height": 500
                              }
                            }

**Comment by EvanZheng11** [comment]
+1

**Comment by 2betop** [comment]
tinymce 插件不支持，目前无法实现
