### ISSUE TITLE
matrix 怎么设置默认值

### ISSUE THREAD

**Issue by xiusin** [baidu/amis#796]
**如题**
我想在矩阵输入框设置一些选中怎么操作

**Comment by 2betop** [comment]
你先看这个表单提交的数据格式怎么样的，比如，你把你默认想选中的勾选，然后提交，或者开启 form 的 debug，看数据格式是怎样的。然后把初始值设置成那样就行了。至于怎么设置初始值，有多种最简单的方式就是直接配置 value: xxx

**Comment by RickCole21** [comment]
关了，有问题再开
