### ISSUE TITLE
通过API获得JSON字符串， 然后用"json"控件渲染， 未如预期

### ISSUE THREAD

**Issue by zhuzemin** [baidu/amis#7960]
#### 实现场景：
通过API获得JSON字符串， 然后用json控件渲染

#### 存在的问题：
使用"source"属性传入字符串对象， 但渲染的结果如图：
![json](https://github.com/baidu/amis/assets/5208817/0354fbb5-1ee4-480f-a9d6-ceaf334b3b75)

#### 当前方案：
{
                                                                "source": "${value}",
                                                                "type": "json"
}
传入值${value}： "{"unit":"milimeter"}"

**Comment by 2betop** [comment]
不能是json字符串，而是json对象，可以试试 `${DECODEJSON(value)}`

**Comment by zhuzemin** [comment]
> 不能是json字符串，而是json对象，可以试试 `${DECODEJSON(value)}`

非常感谢, 该方法可行!
