### ISSUE TITLE
image 上传的图片放置到表单字段后，提交无反应

### ISSUE THREAD

**Issue by zhao365845726** [baidu/amis#799]
这个地址无法打开   
https://github.com/baidu/amis/tree/master/docs/renderers/Form/Image.md

`{
                                        "type": "image",
                                        "name": "cover",
                                        "label": "封面",
                                        "reciever":"/api/upload",
                                        "autoFill": {"cover": "${url}"},
                                        "required": true
                                    },`

代码如上所示，我点击上传图片后，返回了图片

但是点击表单确定提交后，直接显示一直再提交
![image](https://user-images.githubusercontent.com/7474354/88893214-9a9b5100-d278-11ea-9d2e-5a929b5f32ba.png)

**Comment by RickCole21** [comment]
是不是接口有问题呢，检查下后端？

**Comment by RickCole21** [comment]
#836 这个问题，请使用beta版：`1.0.15-beta.37`

**Comment by RickCole21** [comment]
> 这个地址无法打开
> https://github.com/baidu/amis/tree/master/docs/renderers/Form/Image.md

换新文档了，新地址：https://baidu.gitee.io/amis/docs/components/form/file
