### ISSUE TITLE
如何在JS中触发amis中的事件

### ISSUE THREAD

**Issue by ozil-cao** [baidu/amis#7991]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

业务场景是IOT，比如我要去查看IOT的某些设备信息，在页面提交之后，需要等待大约10~50s甚至更长的时间，设备的数据才会到后端，后端才会给到前端页面，目前在app上都是通过socket通知数据准备好了，页面再去拉取结果。在web上想用websocket的方式来收取通知，不知道如何实现。
也可以通过service/crud轮训的方式，但是地方很多，造成后段很多无效的请求。
目前想的方式是在index.html里面，通过js自动开启一个websocket链接，收到消息之后，广播给amis，amis在自己需要的地方去监听通知，然后干自己的业务

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

js在收到websocket的消息之后，如何广播消息给amis。
在官方文档中看到了
“还可以通过 amisScoped.getComponentByName('page1.form1').setValues({'name1': 'othername'}) 来修改表单中的值”
https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/getting-started
但是不知道如何去触发其它的事件，例如broadcast

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by nabaonan** [comment]
service支持websocket    使用onWsFetched事件接收消息

**Comment by hsm-lv** [comment]
https://github.com/baidu/amis/pull/8875
