### ISSUE TITLE
curd自适应高度参数不好使了

### ISSUE THREAD

**Issue by jiangwenwen2022** [baidu/amis#7992]
#### 描述问题：

amis使用v3.4.0-beta.12，curd自适应高度参数不好使了。之前使用v3.1.0是没有问题的

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/97872284/15865d07-4695-470f-a7d1-c4f0998e92d1)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk 引入

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

v3.4.0-beta.12

4. 粘贴有问题的完整 `amis schema` 代码：

5. 操作步骤
一样的配置，v3.1.0就没有 问题呢，升级到v3.4.0-beta.12就不能自适应高度了

**Comment by 2betop** [comment]
请尝试一下 3.4.0， 目前amis 的示例中无法复现此类情况

**Comment by 2betop** [comment]
缺少反馈，有问题再重开
