### ISSUE TITLE
框架好像只是针对于前端渲染，后端没有涉及

### ISSUE THREAD

**Issue by qiu8310** [baidu/amis#8]
所以想问下，有没有匹配的后端框架？

或者我们自己定制我们的后端框架有没有一些规范？

**Comment by qiu8310** [comment]
前端可能开发起来会简单多了，但如果这些 json 配置能通过后端自动渲染出来，那么前后端都可以减少开发量了

**Comment by 2betop** [comment]
没有涉及到后端，后端需要提供 api 对接，api 对接方面后面补充详细文档。

要求格式返回这样。可以先看看 examples 里面返回的格式。

```json
{
  status: 0,
  msg: '',
  data: {
  }
}
```
