### ISSUE TITLE
progress组件动态展示怎么实现呢

### ISSUE THREAD

**Issue by xinghe94** [baidu/amis#800]
想模拟一个进度 用到了progress 好像没有暴露一些props方法去控制它的值?

**Comment by RickCole21** [comment]
先看下这个https://baidu.github.io/amis/docs/components/progress

**Comment by RickCole21** [comment]
关了，有问题再开

**Comment by xinghe94** [comment]
> 关了，有问题再开

好的 谢了

**Comment by cjb1234567** [comment]
怎么获取数据域的值呢？
 写表达式 "value":${xxx} 会报错,  写"value": "${xxx}"又成了字符串了，没法显示进度条。
真的有人成功用过这个组件吗？
