### ISSUE TITLE
Dialog真的需要12.5rem的min-height吗？

### ISSUE THREAD

**Issue by backrunner** [baidu/amis#803]
感觉如果只有一行的内容的话，这个min-height看起来有点奇怪。
有的时候想弹出的弹框可能只会有一行提示内容，有这样一个min-height，内容下面会有很大留白：
![image](https://user-images.githubusercontent.com/12205593/88922310-84a28600-d2a2-11ea-8730-6150a3152e73.png)
![image](https://user-images.githubusercontent.com/12205593/88922233-6b99d500-d2a2-11ea-94ad-aacd8da1d7b3.png)
dialog body的padding已经够了，加上这样一个min-height感觉没必要？

**Comment by 2betop** [comment]
欢迎 pr, cxd 主题请保持现状，默认主题可以设置成 unset 为默认

**Comment by nwind** [comment]
可以先自己改
