### ISSUE TITLE
自由容器组件，在85版本的谷歌浏览器，拖拽进去的其他组件无法移动

### ISSUE THREAD

**Issue by huangyipingChina** [baidu/amis#8044]
#### 描述问题：

自由容器组件，在85版本的谷歌浏览器，拖拽进去的其他组件无法移动
#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "page",
  "title": "Simple Form Page",
  "regions": [
    "body"
  ],
  "body": [
    {
      "type": "container",
      "isFreeContainer": true,
      "size": "xs",
      "body": [
        {
          "type": "input-text",
          "label": "文本",
          "name": "text",
          "id": "u:da21f53bbd35",
          "style": {
            "position": "absolute",
            "inset": "54px auto auto 273px"
          }
        }
      ],
      "wrapperBody": false,
      "style": {
        "position": "relative",
        "minHeight": "200px"
      },
      "id": "u:d8deaf9211c6"
    }
  ],
  "id": "u:6fb79f330c6b"
}

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by huangyipingChina** [comment]
这个问题好像是因为低版本浏览器不支持css的inset导致的
尝试着修改amis-editor-core/src/store/editor的updateContainerStyleByDrag方法，
在执行this.changeValueById()方法的地方，修改代码如下
const newInsetArr=newInset.split(' ')
this.changeValueById(curDragId,{
   ...curSchema,
  style:{
   ...curSchemaStyle,
  inset:newInset,
  top:newInsetArr[0],
  right:newInsetArr[1],
  bottom:newInsetArr[2],
  left:newInsetArr[3]
 }
})
这样应该能解决在自由容器中不能拖拽的问题，但是低版本浏览器自由容器中拖拽的时候会存在延迟

**Comment by wibetter** [comment]
感谢反馈：我们记录下这个问题，后续看下怎么兼容支持下。
