### ISSUE TITLE
CRUD怎么取消placeholder?

### ISSUE THREAD

**Issue by vexos-io** [baidu/amis#8051]
placeholder太大了，有什么办法不要placeholder呢？

**Comment by 2betop** [comment]
可以自己配置 placeholder文案, 如果觉得 placeholder 高度太高，可以通过配置css变量来调整如： `--Table-placeholder-height: 30px;`

**Comment by vexos-io** [comment]
非常感谢，同时也需要设置一下图标 --Table-empty-icon-size: 30px
