### ISSUE TITLE
amis报错，Cannot read properties of undefined (reading 'cachedValue')

### ISSUE THREAD

**Issue by findreamer** [baidu/amis#8064]
#### 描述问题：

升级amis版本至3.4.0后，配置schema默认data属性后，页面设计器组件，执行pipeIn函数报错，实测仅在amis-editor中报错，直接使用sdk版本渲染schema不会报错。

#### 截图或视频：

<img width="1506" alt="image" src="https://github.com/baidu/amis/assets/116187210/387863cb-121a-4db5-8394-87f6a1837845">
<img width="1511" alt="image" src="https://github.com/baidu/amis/assets/116187210/d59955c3-f317-428c-b275-82503ebbcdde">
修改了pipeIn、pipeOut函数的调用方式，导致this丢失：
<img width="1169" alt="image" src="https://github.com/baidu/amis/assets/116187210/8fcbdc2e-961f-4b5a-b242-ab7f4400e94f">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis@3.4.0
amis-editor@5.5.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
import './App.css';
import { Editor } from 'amis-editor';
import { useState, useCallback } from 'react';
import '@fortawesome/fontawesome-free/css/all.css';
import '@fortawesome/fontawesome-free/css/v4-shims.css';
import 'amis/lib/themes/cxd.css';
import 'amis/lib/helper.css';
import 'amis/sdk/iconfont.css';
import 'amis-editor-core/lib/style.css';
import { RecordPlugin } from './plugins/records';

function App() {
  const [sechema, setSchema] = useState({
    type: 'page',
    title: '你好周杰伦',
    data: {
      userId: '123',
      formType: '111',
    },
    body: [
      {
        type: 'tpl',
        tpl: '<h1>hahah</h1>',
      },
      {
        type: 'tpl',
        tpl: '${name}',
      },
    ],
  });

  const handleChange = useCallback((val) => {
    setSchema(val);
  }, []);

  return (
    <div className='App'>
      <Editor
        className='custom-editor'
        onChange={handleChange}
        value={sechema}
        data={{ name: 'zhangsan' }}
        plugins={[RecordPlugin]}
      ></Editor>
    </div>
  );
}

export default App;
```

5. 操作步骤
1、在amis-editor中引入Editor组件；
2、配置schema，**并配置data属性**。
3、运行工程，页面报错。
4、删除data属性后，页边设计器组件运行正常。

**Comment by 2betop** [comment]
这是一个新引入的问题，目前已在 https://github.com/baidu/amis/pull/8007 中修复，需要等待下次发版。
问题由此 pr 引入 https://github.com/baidu/amis/pull/7963

**Comment by findreamer** [comment]
已在3.4.1版本中修复
