### ISSUE TITLE
最近的几次代码提交出现很多bug，希望加强合并请求时代码审查

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#8073]
#### 是否关联于某个问题吗：
最近的几次代码提交出现很多bug，希望加强合并请求时代码审查

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by nwind** [comment]
有时候很难看出相互影响，目前主要原因还是测试覆盖不够，如果是之前出过的问题，帮忙补个测试用例吧，这样最靠谱
