### ISSUE TITLE
crud根据内容自动计算宽度有偏差

### ISSUE THREAD

**Issue by songyinhai2006** [baidu/amis#8079]
#### 描述问题：

设置表格属性white-space-nowrap，如图，
sdk3.3版本效果,内容是不换行的
![image](https://github.com/baidu/amis/assets/52561802/3a1e55c0-db73-41ac-8a7c-e8e2910ebc0d)
升级3.4之后效果如下，内容换行了
![image](https://github.com/baidu/amis/assets/52561802/3689b759-b947-440d-ad34-370952279afb)

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/52561802/18e3bfa1-0bcd-4159-ad2d-cd8cc05da361)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.4.0

4. 粘贴有问题的完整 `amis schema` 代码：

5. 操作步骤

**Comment by 2betop** [comment]
下个版本会解决这个问题，3.4 为了让宽度可拖拽配置切成 fixed 表格布局，后续会换成 auto

**Comment by 2betop** [comment]
请尝试 master 分支，已调整为 auto
