### ISSUE TITLE
把JSON存储在后端

### ISSUE THREAD

**Issue by jingsewu** [baidu/amis#8086]
#### 预期的解决方案：
把JSON存储在后端，然后前端调用后端接口返回JSON直接渲染，这样就可以在后端通过接口修改JSON，不用部署前端直接生效。特别是对于SAAS的服务，每个客户都需要不同的页面渲染。

**Comment by 2betop** [comment]
这个 issue 的意图是啥？amis 只管前端渲染，至于 json 要不要存后端，是后端整合的工作。
