### ISSUE TITLE
除了service组件，如何实现2个表单共用一个表单schema配置？

### ISSUE THREAD

**Issue by liugonghe** [baidu/amis#8111]
#### 实现场景：
比如有3个复杂的表单，新增、编辑、查看，amis schema配置重合度有90%，如何快速复用相同的schema配置？

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by skj198568** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/definitions

**Comment by wibetter** [comment]
目前除了通过service组件（schemaApi）实现schema复用外，也可以使用页面公共的配置项（[Definitions](https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/definitions)）实现。
