### ISSUE TITLE
按照操作文档，报错如下：observable.observers.add is not a function，请问什么问题，感谢

### ISSUE THREAD

**Issue by xichangzhou** [baidu/amis#812]

**Comment by RickCole21** [comment]
怎么使用的

**Comment by xichangzhou** [comment]
> 怎么使用的

import React from 'react';
import { render as renderAmis } from 'amis';

const Home = () => {
  return (
    <div>
      {renderAmis({
        type: 'page',
        body: {
          type: 'form',
          api: 'https://houtai.baidu.com/api/mock2/form/saveForm',
          controls: [
            {
              type: 'text',
              name: 'name',
              label: '姓名：',
            },
          ],
        },
      })}
    </div>
  );
};

export default Home;

**Comment by xichangzhou** [comment]
最简单的使用方式

**Comment by xichangzhou** [comment]
这种最简单的使用方式都报错
```
import React from 'react';
import { render as renderAmis } from 'amis';

const Home = () => {
  return (
    <div>
      {renderAmis({
        type: 'page',
        body: 'Hello World!',
      })}
    </div>
  );
};

export default Home;
```

**Comment by RickCole21** [comment]
貌似没能复现，能再描述一些细节么

**Comment by xichangzhou** [comment]
```
"mobx": "^4.5.0",
 "mobx-react": "^6.1.4",
```
上面是amis里面的依赖

下面是我项目里面的依赖
```
"mobx": "^5.13.0",
"mobx-react": "^6.1.3",
```
或许是版本不一样导致的吧

**Comment by RickCole21** [comment]
哦那应该是这个原因

**Comment by xichangzhou** [comment]
我新建一个项目不安装mobx依赖，然后再安装amis就能使用，难道我旧系统里面先安装了mobx,就不能再使用amis了吗？

**Comment by RickCole21** [comment]
mobx版本需要统一

**Comment by RickCole21** [comment]
先关了，有问题再开
