### ISSUE TITLE
CRUD 表格是否支持index

### ISSUE THREAD

**Issue by laizuan** [baidu/amis#8137]
#### 实现场景：
- crud 表格在文档中没有找到序列号配置，类似：input-table的showIndex
- 如果要自定义列的内容需要怎么做呢？没有找到示例或者文档
- 
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by laizuan** [comment]
解决方案
```json

 {
          "label": "序号",
          "type": "tpl",
          "tpl": "${(start - 1) * size + index + 1}"
        },
```

文档好像没有type=tpl

**Comment by wanquantong** [comment]
> 解决方案
> 
> ```json
>  {
>           "label": "序号",
>           "type": "tpl",
>           "tpl": "${(start - 1) * size + index + 1}"
>         },
> ```
> 
> 文档好像没有type=tpl

分页的序号怎么连续？

**Comment by ltx0633** [comment]
> > 解决方案
> >  {
> >           "label": "序号",
> >           "type": "tpl",
> >           "tpl": "${(start - 1) * size + index + 1}"
> >         },
> >     
> >   
> > 文档好像没有type=tpl
> 
> 分页的序号怎么连续？

{
              "label": "序号",
              "type": "tpl",
              "tpl": "${(page - 1) * perPage + index + 1}"
            }
