### ISSUE TITLE
Dropdown下的菜单都加了蓝色边框，是有意为之吗

### ISSUE THREAD

**Issue by vexos-io** [baidu/amis#8138]
版本3.4.0，请问是测试方便还是确实改为了带蓝色边框的？

**Comment by 2betop** [comment]
能否截个图？看起来并没有啊
<img width="305" alt="image" src="https://github.com/baidu/amis/assets/2698393/41d3c483-f21d-4303-8435-0941e6fdb8d4">

**Comment by vexos-io** [comment]
我发现是我包装时默认用了enhance，以前是不带框的，现在带了。但我觉得是amis处理的是合理的~~
![截图 2023-09-22 08-23-06](https://github.com/baidu/amis/assets/56525941/45ecd3d4-a6c6-4f67-a573-8122f6e0e56a)
