### ISSUE TITLE
tab选项卡之间联动，无法第一次传递数据

### ISSUE THREAD

**Issue by shaofq** [baidu/amis#8141]
![image](https://github.com/baidu/amis/assets/28698892/7cba53b7-217d-4fa7-9094-c8c849969bcc)

![image](https://github.com/baidu/amis/assets/28698892/3b2103c4-a0d3-4efa-855b-02f198a7839d)

![image](https://github.com/baidu/amis/assets/28698892/05e695ec-d378-4935-90cb-dccd6751e205)

tab选项卡之间联动，无法第一次传递数据，只有第二次才能传递数据过去，是因为第一次tab页面没有渲染吗？如何解决

@2betop

**Comment by Mengleijin** [comment]
可以试试mountOnEnter设置为false，不确认行不行

**Comment by 2betop** [comment]
隐藏组件无法通信，要配置 `mountOnEnter : false` 初始就渲染那个 tab 才行。或者 tabs 放在一个form 里面，将数据同步到 form
