### ISSUE TITLE
Error: Element type is invalid. Received a promise that resolves to: [object Module]. Lazy element type must resolve to a class or function.

### ISSUE THREAD

**Issue by Slowlyo** [baidu/amis#8145]
#### 描述问题：

使用 React 版本，控制台报错： 
```
Error: Element type is invalid. Received a promise that resolves to: [object Module]. Lazy element type must resolve to a class or function.
```
但是组件可以正常使用

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/94038215/1c554f23-32da-4e5a-b66d-d9deb2421ac3)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

`npm`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

`v3.4.0`

3. 粘贴有问题的完整 `amis schema` 代码：

经测试，与 `schema` 无关~

4. 操作步骤

刷新页面后，会在控制台显示该错误，后续操作不会出现该问题~

**Comment by NightGod-A** [comment]
我也有同样的问题。我是渲染不了type为json的数据。并且我的json格式组件无法显示
![image](https://github.com/baidu/amis/assets/56927804/eaa4b2c7-8902-4ee8-98b6-a1824e784e0d)

**Comment by 2betop** [comment]
如何复现？可否来个简单的仓库？

**Comment by NightGod-A** [comment]
> 如何复现？可否来个简单的仓库？

https://github.com/NightGod-A/amis-app   这个可以吗，我本地是设置type为json的出问题。string的是可以渲染的。

**Comment by Slowlyo** [comment]
> 如何复现？可否来个简单的仓库？

https://github.com/Slowlyo/owl-admin/tree/master/admin-views

`admin-views` 目录下是前端

**Comment by Slowlyo** [comment]
> 如何复现？可否来个简单的仓库？

https://github.com/Slowlyo/issue-amis-demo

在有 `curd` 组件的页面会出现该问题

**Comment by NightGod-A** [comment]
> > 如何复现？可否来个简单的仓库？
> 
> https://github.com/Slowlyo/issue-amis-demo
> 
> 在有 `curd` 组件的页面会出现该问题

在单纯json组件不会出现这个问题吗。我是crud组件下使用json组件出现这个问题，单纯使用json组件也会报这个错误。
