### ISSUE TITLE
amis有没有截图组件

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#8146]
#### 实现场景：
管理后台上传一张图片 能对这个图片进行固定长宽比的截取

#### 存在的问题：
在amis文档中没有找到截图相关功能的组件

**Comment by allenve** [comment]
看看这里： https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-image#%E6%94%AF%E6%8C%81%E8%A3%81%E5%89%AA

**Comment by Liary0** [comment]
啊 看了几遍居然没看到 谢谢
