### ISSUE TITLE
侧边栏aside的背景颜色如何设置？

### ISSUE THREAD

**Issue by zou27** [baidu/amis#8164]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by gexMichael** [comment]
"aside": {
    "type": "form",
    "promptPageLeave": true,
    "className": "bg-green-100",
    "wrapWithPanel": false,
    "target": "dataList",
    "submitOnInit": true,

**Comment by allenve** [comment]
asideClassName  比如

**Comment by zou27** [comment]
> "className": "bg-green-100",

谢谢谢谢

**Comment by zou27** [comment]
> asideClassName 比如 { "type": "page", "asideClassName": "bg-black", "aside": [ { "type": "tpl", "tpl": "这是侧边栏部分" } ], "body": [ { "type": "tpl", "tpl": "这是内容区" } ] }

谢谢谢谢
