### ISSUE TITLE
tinymce编辑器上传图片返回的json数据格式是什么样的？

### ISSUE THREAD

**Issue by foxfire881** [baidu/amis#818]
之前的frola返回数据格式是{"link":"images/xxx.jpg"}这样的，换成tinymce之后报错提示“接口返回格式不符合，请参考http://amis.baidu.com/v2/docs/api" 但是这个参考地址又打不开。

**Comment by foxfire881** [comment]
按照官方文档试了返回 {"location":"/images/xx.jpg"} 这样也不行，不知道咋整了，到底应该返回什么格式呢？

https://www.tiny.cloud/docs/advanced/php-upload-handler/

**Comment by foxfire881** [comment]
最新的1.0.14版是否对Rich-Text组件的图片上传接口做调整了？现在设置成tinymce是完全无法上传，一直返回接口格式错误；设置成frola，调用的又是默认的/upload/file接口，不是原来的upload/image接口，保存的路径也是upload指定的目录，而且传上去的图片文件访问地址变成了blob开头的地址…… 好乱好乱。。。

另外请问一下，1.0.14的frola是和谐版吗？如果和谐过还是用frola吧，tinymce的全屏功能有些bug

**Comment by foxfire881** [comment]
研究了一下frola的options，似乎找到解了，明天上班仔细看下。问题是frola是和谐版吗，还有大红条和狗尾续貂吗？

tinymce上传接口还没找到解，不知道要返回啥，而且全屏功能有bug，全屏之后收不回来了。

**Comment by foxfire881** [comment]
Froala大红条还是存在，已经扩展了css干掉了。

tinymce一直调试不成功。

**Comment by nwind** [comment]
新版修了 tinymce 的一个 bug，可以看看
