### ISSUE TITLE
编译器本地运行选择组件【外观】-【边框】报错，build包直接运行又不报错

### ISSUE THREAD

**Issue by 1999716** [baidu/amis#8195]
#### 描述问题：

拉取最新编译器master分支代码本地运行，选择【外观】-【边框】，可选择边框类型，但选择边框粗细样式报错。

构建后的demo直接运行，该问题又不报错。

node:  14.18.0
npm:  6.14.15

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/100275780/e99ffd53-8633-46b7-88e3-3e048140a420)

![image](https://github.com/baidu/amis/assets/100275780/4b18b8aa-0d3a-4a0c-910a-a739333b0f19)

![image](https://github.com/baidu/amis/assets/100275780/bbdf8ea1-0342-4249-9b0d-f461d32d4c63)

**Comment by 1999716** [comment]
原因:  amis-theme-editor 包中【lib/renderers/Border.js】边框宽度下拉选内容容错


![image](https://github.com/baidu/amis/assets/100275780/426a562a-86f7-49c3-ac72-1cf386b59a11)

![image](https://github.com/baidu/amis/assets/100275780/23b42a31-f66c-40e7-9f70-89aff3a8165b)

**Comment by wibetter** [comment]
请升级amis-editor到最新版本（5.5.0以上），目前已无此问题：
<img width="1756" alt="image" src="https://github.com/baidu/amis/assets/11958920/79c99921-67bf-4702-b2f4-f9c27efff743">
