### ISSUE TITLE
嵌套表格，可选择的选择框有时候选择不上，但是数据却选择上了。嵌套表格的父级选择有的时候会将孩子一起勾选上

### ISSUE THREAD

**Issue by rodchen-king** [baidu/amis#820]
![image](https://user-images.githubusercontent.com/19780441/89296643-31ab4300-d695-11ea-9c85-da7eeb807980.png)

第一个问题：
下图，我先选择红色框，然后点击了一下绿色框，绿色框没有选中，但是点击编辑弹出来框的title，确实显示了三条数据的id
嵌套表格，可选择的选择框有时候选择不上，但是数据却选择上了。

第二个问题：
可以控制当前父子数据的影响嘛？

**Comment by RickCole21** [comment]
嵌套表格的批量操作应该是不稳定的，建议先不要使用，后续有时间会重新搞一下这块，或者欢迎PR😝

**Comment by rodchen-king** [comment]
> 嵌套表格的批量操作应该是不稳定的，建议先不要使用，后续有时间会重新搞一下这块，或者欢迎PR😝
老哥，这个最近有修改吗？

**Comment by 2betop** [comment]
新版本没发现此问题，请升级版本，有问题再开
