### ISSUE TITLE
select定位问题

### ISSUE THREAD

**Issue by zmm1988** [baidu/amis#8201]
select定位跑顶上去了，要么跑偏了

![1695351495306](https://github.com/baidu/amis/assets/48378155/8aac8256-42e3-4879-b00f-3d52001e3bed)

![1695351529700](https://github.com/baidu/amis/assets/48378155/578d1871-1495-445b-bd6b-b36955fd93f8)

1. 你是如何使用 amis 的？
用的是npm引入amis，用的sdk的方式

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis@3.0.0以上的版本都有这个问题的。amis@2.8.0的版本是正常的

3 json
{
  "type": "page",
  "id": "u:ce3e5dc31fa0",
  "asideResizor": false,
  "regions": [
    "body"
  ],
  "body": [
    {
      "type": "crud",
      "syncLocation": false,
      "api": {
        "method": "post",
        "url": "${apiUrl}/api/amis/productPlan/getPageList",
        "requestAdaptor": "",
        "adaptor": "",
        "messages": {
        },
        "headers": {
          "Authorization": "${token}"
        }
      },
      "columns": [
        {
          "name": "id",
          "label": "ID",
          "type": "text",
          "id": "u:77eb875172d5"
        },
        {
          "name": "taskCode",
          "label": "工单号",
          "type": "text",
          "id": "u:03642a15f884"
        }
      ],
      "bulkActions": [
        {
          "label": "打印",
          "type": "button",
          "onEvent": {
            "click": {
              "weight": 0,
              "actions": [
                {
                  "actionType": "dialog",
                  "dialog": {
                    "type": "dialog",
                    "title": "弹框标题",
                    "body": [
                      {
                        "type": "form",
                        "title": "表单",
                        "body": [
                          {
                            "label": "工单号",
                            "type": "input-text",
                            "name": "taskCode",
                            "id": "u:a964aa0769e9"
                          }
                        ],
                        "api": {
                          "url": "${apiUrl}/api/getPageList",
                          "method": "post",
                          "requestAdaptor": "",
                          "adaptor": "",
                          "messages": {
                          },
                          "headers": {
                            "Authorization": "${token}"
                          },
                          "data": {
                            "page": 1,
                            "perPage": 30
                          }
                        },
                        "id": "u:4b399f36ca5c",
                        "onEvent": {
                          "submitSucc": {
                            "weight": 0,
                            "actions": [
                              {
                                "outputVar": "responseResult",
                                "actionType": "ajax",
                                "options": {
                                },
                                "api": {
                                  "url": "http://127.0.0.1:1632",
                                  "method": "post",
                                  "requestAdaptor": "",
                                  "adaptor": "",
                                  "messages": {
                                  },
                                  "data": {
                                    "id": "${printList}",
                                    "name": "销售出库"
                                  }
                                }
                              }
                            ]
                          }
                        },
                        "closeDialogOnSubmit": false,
                        "canAccessSuperData": false,
                        "submitText": "提交",
                        "debug": false,
                        "persistData": false,
                        "rules": [
                        ]
                      }
                    ],
                    "showCloseButton": true,
                    "showErrorMsg": true,
                    "showLoading": true,
                    "className": "app-popover",
                    "id": "u:f0382c79d19a"
                  }
                }
              ]
            }
          },
          "id": "u:107c18606166"
        }
      ],
      "itemActions": [
      ],
      "id": "u:0a41fc92f198",
      "perPageAvailable": [
        10
      ],
      "messages": {
      },
      "filter": {
        "title": "",
        "body": [
          {
            "type": "input-text",
            "name": "id",
            "label": "ID",
            "id": "u:e5c3129b17ca"
          },
          {
            "type": "select",
            "label": "选项",
            "name": "select",
            "options": [
              {
                "label": "选项A",
                "value": "A"
              },
              {
                "label": "选项B",
                "value": "B"
              }
            ],
            "id": "u:dd5c71909256",
            "multiple": false,
            "value": ""
          }
        ],
        "id": "u:8bf3206b6764"
      }
    },
    {
      "type": "select",
      "label": "选项",
      "name": "select",
      "options": [
        {
          "label": "选项A",
          "value": "A"
        },
        {
          "label": "选项B",
          "value": "B"
        }
      ],
      "id": "u:03d831e25e20"
    }
  ]
}

**Comment by zmm1988** [comment]
日期也有类似的问题
![image](https://github.com/baidu/amis/assets/48378155/bb2d63dd-30af-400e-a693-d0b7cacc4517)

**Comment by zmm1988** [comment]
![image](https://github.com/baidu/amis/assets/48378155/dfa792aa-17b7-483f-ac9f-7cdd87939955)

**Comment by 2betop** [comment]
@zmm1988 感觉可能跟框架的 css 有关，能大概说一下那个选项卡外围的 css 结构吗

**Comment by zmm1988** [comment]
> @zmm1988 感觉可能跟框架的 css 有关，能大概说一下那个选项卡外围的 css 结构吗
经过你的提醒，我检查了下布局，发现头部是fixed定位的，现在改了正常的布局后正常了，谢谢

**Comment by zmm1988** [comment]
> @zmm1988 感觉可能跟框架的 css 有关，能大概说一下那个选项卡外围的 css 结构吗
经过你的提醒，我检查了下布局，发现头部是fixed定位的，现在改了正常的布局后正常了，谢谢

**Comment by zhushibo** [comment]
我这里有侧边栏和顶部栏，也会出现偏移，需要在渲染的盒子（我这里是中间最大的container）加上position: relative就可以了
