### ISSUE TITLE
mobx 有打算升级到5吗?

### ISSUE THREAD

**Issue by MyCupOfTeaOo** [baidu/amis#821]
如题,还是说为了兼容浏览器不打算升级?

**Comment by nwind** [comment]
嗯，因为兼容性问题短期内不会升级，amis 还用在我们其它重要产品上，升级成本很高，而 mobx 4 已经能完全满足需求了。

**Comment by MyCupOfTeaOo** [comment]
> 嗯，因为兼容性问题短期内不会升级，amis 还用在我们其它重要产品上，升级成本很高，而 mobx 4 已经能完全满足需求了。

嗯,主要我们项目内部用了mobx 5,但是缺号一些mobx 4的api会导致使用报错,如果暂时没打算升级我只能fork自己改下了ヾ|≧_≦|〃
