### ISSUE TITLE
官方文档的【单页跳转】和【直接跳转】按钮无效，控制台会报错

### ISSUE THREAD

**Issue by zhaoyibin** [baidu/amis#822]
在 
[https://baidu.github.io/amis/docs/components/action#%E5%8D%95%E9%A1%B5%E8%B7%B3%E8%BD%AC](url)
文档中单页跳转】和【直接跳转】按钮无效，控制台会报错 
**Please implements this. see https://baidu.github.io/amis/docs/getting-started#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8**
点进去这个链接是个404页面，感谢解答，谢谢～

**Comment by RickCole21** [comment]
已修复，多谢提醒
