### ISSUE TITLE
从 3.4 版后，picker 的 keywords 传入值都被固定传入 0，退回 3.2 版正常无误

### ISSUE THREAD

**Issue by gexMichael** [baidu/amis#8223]
#### 描述问题：

从 3.4 版后，picker 的 keywords 传入值都被固定传入 0
退回 3.2 版正常无误

#### 截图或视频：

v 3.2 (ok)
![image](https://github.com/baidu/amis/assets/22609092/f38e58c9-a7b0-4f69-bdf4-a748ac65db5a)

v3.4 (bug)
![image](https://github.com/baidu/amis/assets/22609092/09d2296a-739c-47f3-847b-14fd8b1bd8d1)

**Comment by allenve** [comment]
发下配置的Json Schema

**Comment by gexMichael** [comment]
{
  "title": "細項權限設定",
  "type": "page",
  "asideResizor": true,
  "asideMinWidth": 150,
  "asideMaxWidth": 400,
  "aside": {
    "type": "form",
    "promptPageLeave": true,
    "className": "bg-green-100",
    "wrapWithPanel": false,
    "target": "dataList",
    "submitOnInit": true,
    "body": [
      {
        "type": "input-tree",
        "initiallyOpen": false,
        "heightAuto": true,
        "name": "menuid",
        "inputClassName": "no-border h-full",
        "submitOnChange": true,
        "selectFirst": false,
        "source": {
          "method": "post",
          "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/get_treedata/6/",
          "data": {
            "para01": "menuid"
          },
          "dataType": "form"
        }
      }
    ]
  },
  "toolbar": [
    {
      "type": "button",
      "label": "新增",
      "icon": "fa fa-plus pull-left",
      "primary": true,
      "actionType": "drawer",
      "disabledOn": "${ls:sys0a@insert == null}",
      "drawer": {
        "position": "right",
        "resizable": true,
        "size": "md",
        "actions": [
          {
            "label": "存檔",
            "actionType": "submit",
            "primary": true,
            "type": "button"
          },
          {
            "label": "取消",
            "actionType": "cancel",
            "type": "button"
          }
        ],
        "title": "新增",
        "body": {
          "type": "form",
          "promptPageLeave": true,
          "mode": "horizontal",
          "horizontal": {
            "leftFixed": true
          },
          "name": "sample-edit-form",
          "api": {
            "method": "post",
            "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/2/",
            "dataType": "form",
            "requestAdaptor": "return {\n    ...api,\n    data: {\n        ...api.data,\n    token: local_get_token(),\n    _$_tableName: \"sys_rolemenusecurity\",\n    _$_pk: \"roleid,menuid,controlname\",\n    _$_action: \"C\"}\n}"
          },
          "body": [
            {
              "type": "picker",
              "name": "roleid",
              "joinValues": true,
              "valueField": "roleid",
              "labelField": "rolename",
              "label": "角色代號",
              "source": {
                "method": "post",
                "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/3/",
                "data": {
                  "page": "${page}",
                  "perPage": "${perPage}",
                  "keywords": "${roleid-keywords}",
                  "_$_tableName": "sys_roles",
                  "_$_pk": "roleid",
                  "_$_action": "P",
                  "_$_query_filter": "1^10^roleid^*^^^roleid,rolename,description^${roleid}"
                },
                "dataType": "form"
              },
              "size": "md",
              "value": "",
              "multiple": false,
              "pickerSchema": {
                "mode": "table",
                "tableClassName": "myGridHeader_a",
                "title": "角色設定",
                "name": "sys_roles-roleid",
                "headerToolbar": {
                  "wrapWithPanel": false,
                  "type": "form",
                  "promptPageLeave": true,
                  "className": "text-right",
                  "target": "sys_roles-roleid",
                  "mode": "inline",
                  "body": [
                    {
                      "type": "input-text",
                      "name": "roleid-keywords",
                      "addOn": {
                        "type": "submit",
                        "label": "查詢",
                        "tooltip": "輸入 * 可以查詢全部資料",
                        "level": "primary",
                        "icon": "fa fa-search pull-left"
                      }
                    }
                  ]
                },
                "columns": [
                  {
                    "type": "text",
                    "name": "roleid",
                    "label": "角色代號",
                    "toggled": true
                  },
                  {
                    "type": "text",
                    "name": "rolename",
                    "label": "角色名稱",
                    "toggled": true
                  },
                  {
                    "type": "text",
                    "name": "description",
                    "label": "描述",
                    "toggled": true
                  },
                  {
                    "type": "text",
                    "name": "msad",
                    "label": "MSAD否",
                    "toggled": true
                  }
                ]
              }
            },
            {
              "type": "picker",
              "name": "menuid",
              "joinValues": true,
              "valueField": "menuid",
              "labelField": "caption",
              "label": "選單代號",
              "source": {
                "method": "post",
                "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/3/",
                "data": {
                  "page": "${page}",
                  "perPage": "${perPage}",
                  "keywords": "${menuid-keywords}",
                  "_$_tableName": "sys_menutable",
                  "_$_pk": "menuid",
                  "_$_action": "P",
                  "_$_query_filter": "1^10^menuid^*^^^menuid,parent_menuid,caption,moduleid,seq_no^${menuid}"
                },
                "dataType": "form"
              },
              "size": "md",
              "value": "",
              "multiple": false,
              "pickerSchema": {
                "mode": "table",
                "tableClassName": "myGridHeader_a",
                "title": "Menu",
                "name": "sys_menutable-menuid",
                "headerToolbar": {
                  "wrapWithPanel": false,
                  "type": "form",
                  "promptPageLeave": true,
                  "className": "text-right",
                  "target": "sys_menutable-menuid",
                  "mode": "inline",
                  "body": [
                    {
                      "type": "input-text",
                      "name": "menuid-keywords",
                      "addOn": {
                        "type": "submit",
                        "label": "查詢",
                        "tooltip": "輸入 * 可以查詢全部資料",
                        "level": "primary",
                        "icon": "fa fa-search pull-left"
                      }
                    }
                  ]
                },
                "columns": [
                  {
                    "type": "text",
                    "name": "menuid",
                    "label": "選單代號",
                    "toggled": true
                  },
                  {
                    "type": "text",
                    "name": "parent_menuid",
                    "label": "上層選單代號",
                    "toggled": true
                  },
                  {
                    "type": "text",
                    "name": "caption",
                    "label": "選單抬頭",
                    "toggled": true
                  },
                  {
                    "type": "text",
                    "name": "moduleid",
                    "label": "模組代號",
                    "toggled": true
                  },
                  {
                    "type": "text",
                    "name": "seq_no",
                    "label": "序號",
                    "toggled": true
                  },
                  {
                    "type": "text",
                    "name": "isLocalMenu",
                    "label": "本地功能",
                    "toggled": true
                  }
                ]
              }
            },
            {
              "type": "select",
              "name": "controlname",
              "creatable": true,
              "addControls": [
                {
                  "type": "text",
                  "name": "label",
                  "label": "選項標題"
                },
                {
                  "type": "text",
                  "name": "value",
                  "label": "選項值"
                }
              ],
              "options": [
                {
                  "label": "delete",
                  "value": "delete"
                },
                {
                  "label": "insert",
                  "value": "insert"
                },
                {
                  "label": "print",
                  "value": "print"
                },
                {
                  "label": "read",
                  "value": "read"
                },
                {
                  "label": "update",
                  "value": "update"
                }
              ],
              "required": true,
              "label": "權限控制項"
            }
          ]
        }
      }
    }
  ],
  "body": {
    "type": "crud",
    "tableClassName": "myGridHeader_a",
    "name": "dataList",
    "api": {
      "method": "post",
      "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/3/",
      "data": {
        "token": "${ls:token}",
        "page": "${page}",
        "perPage": "${perPage}",
        "keywords": "${keywords}",
        "_id_": "${menuid}",
        "_field_": "menuid",
        "_$_frmQueryFlds_": "roleid^menuid^controlname",
        "_$_frmQueryData_": "${search-roleid}^${search-menuid}^${search-controlname}",
        "_$_frmQueryType_": "Clike^Clike^Clike",
        "_$_tableName": "sys_rolemenusecurity",
        "_$_pk": "roleid,menuid,controlname",
        "_$_action": "P",
        "_$_query_filter": "1^10^roleid,menuid,controlname^*^^sys0a^roleid,menuid^${ls:query_id}"
      },
      "dataType": "form",
      "//requestAdaptor": "return {\n    ...api,\n    data: {\n        ...api.data,\n    _$_tableName: \"sys_rolemenusecurity\",\n    _$_pk: \"roleid,menuid,controlname\",\n    _$_action: \"P\",\n    _$_query_filter: \"1^10^roleid,menuid,controlname^*\"}\n}"
    },
    "syncLocation": false,
    "autoGenerateFilter": true,
    "perPage": 10,
    "headerToolbar": [
      {
        "type": "export-excel",
        "label": "匯出 Excel",
        "api": {
          "method": "post",
          "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/2/",
          "data": {
            "token": "${ls:token}",
            "page": "${page}",
            "perPage": "10000",
            "keywords": "${keywords}",
            "_id_": "${menuid}",
            "_field_": "menuid",
            "_$_frmQueryFlds_": "roleid^menuid^controlname",
            "_$_frmQueryData_": "${search-roleid}^${search-menuid}^${search-controlname}",
            "_$_frmQueryType_": "Clike^Clike^Clike",
            "_$_tableName": "sys_rolemenusecurity",
            "_$_pk": "roleid,menuid,controlname",
            "_$_action": "P",
            "_$_query_filter": "1^10^roleid,menuid,controlname^*^^sys0a^roleid,menuid"
          },
          "dataType": "form"
        }
      },
      {
        "type": "button",
        "level": "info",
        "tooltip": "查看 Source",
        "icon": "fas fa-bullseye",
        "actionType": "drawer",
        "drawer": {
          "size": "lg",
          "resizable": true,
          "body": {
            "type": "service",
            "schemaApi": "get:/pages/zen_codeviewer.json"
          },
          "actions": []
        }
      },
      {
        "type": "columns-toggler",
        "align": "right"
      },
      {
        "type": "drag-toggler",
        "align": "right"
      },
      {
        "type": "pagination",
        "align": "right"
      }
    ],
    "footerToolbar": [
      "statistics",
      "switch-per-page",
      "pagination"
    ],
    "columns": [
      {
        "type": "text",
        "name": "roleid",
        "searchable": {
          "type": "input-text",
          "name": "search-roleid",
          "label": "角色代號"
        },
        "label": "角色代號"
      },
      {
        "type": "text",
        "name": "menuid",
        "searchable": {
          "type": "input-text",
          "name": "search-menuid",
          "label": "選單代號"
        },
        "label": "選單代號"
      },
      {
        "type": "text",
        "name": "controlname",
        "label": "權限控制項"
      },
      {
        "type": "operation",
        "label": "操作",
        "width": 100,
        "buttons": [
          {
            "type": "button",
            "icon": "fa fa-eye",
            "actionType": "dialog",
            "tooltip": "查看",
            "dialog": {
              "title": "查看",
              "size": "md",
              "actions": [],
              "body": {
                "type": "form",
                "promptPageLeave": true,
                "mode": "horizontal",
                "horizontal": {
                  "leftFixed": true
                },
                "body": [
                  {
                    "type": "picker",
                    "name": "roleid",
                    "disabled": true,
                    "joinValues": true,
                    "valueField": "roleid",
                    "labelField": "rolename",
                    "label": "角色代號",
                    "source": {
                      "method": "post",
                      "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/3/",
                      "data": {
                        "_$_tableName": "sys_roles",
                        "_$_pk": "roleid",
                        "_$_action": "P",
                        "_$_query_filter": "1^10^roleid^*^^^roleid,rolename,description^${roleid}"
                      },
                      "dataType": "form"
                    }
                  },
                  {
                    "type": "picker",
                    "name": "menuid",
                    "disabled": true,
                    "joinValues": true,
                    "valueField": "menuid",
                    "labelField": "caption",
                    "label": "選單代號",
                    "source": {
                      "method": "post",
                      "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/3/",
                      "data": {
                        "_$_tableName": "sys_menutable",
                        "_$_pk": "menuid",
                        "_$_action": "P",
                        "_$_query_filter": "1^10^menuid^*^^^menuid,parent_menuid,caption,moduleid,seq_no^${menuid}"
                      },
                      "dataType": "form"
                    }
                  },
                  {
                    "type": "static",
                    "name": "controlname",
                    "label": "權限控制項"
                  }
                ]
              }
            }
          },
          {
            "type": "button",
            "icon": "fa fa-pencil",
            "tooltip": "編輯",
            "actionType": "drawer",
            "disabledOn": "${ls:sys0a@update == null}",
            "drawer": {
              "position": "right",
              "resizable": true,
              "size": "md",
              "actions": [
                {
                  "label": "存檔",
                  "actionType": "submit",
                  "primary": true,
                  "type": "button"
                },
                {
                  "label": "取消",
                  "actionType": "cancel",
                  "type": "button"
                }
              ],
              "title": "編輯",
              "body": {
                "type": "form",
                "promptPageLeave": true,
                "mode": "horizontal",
                "horizontal": {
                  "leftFixed": true
                },
                "name": "sample-edit-form",
                "api": {
                  "method": "post",
                  "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/2/",
                  "dataType": "form",
                  "requestAdaptor": "return {\n    ...api,\n    data: {\n        ...api.data,\n    token: local_get_token(),\n    _$_tableName: \"sys_rolemenusecurity\",\n    _$_pk: \"roleid,menuid,controlname\",\n    _$_action: \"U\"}\n}"
                },
                "body": [
                  {
                    "type": "picker",
                    "name": "roleid",
                    "disabled": true,
                    "joinValues": true,
                    "valueField": "roleid",
                    "labelField": "rolename",
                    "label": "角色代號",
                    "source": {
                      "method": "post",
                      "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/3/",
                      "data": {
                        "page": "${page}",
                        "perPage": "${perPage}",
                        "keywords": "${roleid-keywords}",
                        "_$_tableName": "sys_roles",
                        "_$_pk": "roleid",
                        "_$_action": "P",
                        "_$_query_filter": "1^10^roleid^*^^^roleid,rolename,description^${roleid}"
                      },
                      "dataType": "form"
                    },
                    "size": "md",
                    "value": "",
                    "multiple": false,
                    "pickerSchema": {
                      "mode": "table",
                      "tableClassName": "myGridHeader_a",
                      "title": "角色設定",
                      "name": "sys_roles-roleid",
                      "headerToolbar": {
                        "wrapWithPanel": false,
                        "type": "form",
                        "promptPageLeave": true,
                        "className": "text-right",
                        "target": "sys_roles-roleid",
                        "mode": "inline",
                        "body": [
                          {
                            "type": "input-text",
                            "name": "roleid-keywords",
                            "addOn": {
                              "type": "submit",
                              "label": "查詢",
                              "tooltip": "輸入 * 可以查詢全部資料",
                              "level": "primary",
                              "icon": "fa fa-search pull-left"
                            }
                          }
                        ]
                      },
                      "columns": [
                        {
                          "type": "text",
                          "name": "roleid",
                          "label": "角色代號",
                          "toggled": true
                        },
                        {
                          "type": "text",
                          "name": "rolename",
                          "label": "角色名稱",
                          "toggled": true
                        },
                        {
                          "type": "text",
                          "name": "description",
                          "label": "描述",
                          "toggled": true
                        },
                        {
                          "type": "text",
                          "name": "msad",
                          "label": "MSAD否",
                          "toggled": true
                        }
                      ]
                    }
                  },
                  {
                    "type": "picker",
                    "name": "menuid",
                    "disabled": true,
                    "joinValues": true,
                    "valueField": "menuid",
                    "labelField": "caption",
                    "label": "選單代號",
                    "source": {
                      "method": "post",
                      "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/3/",
                      "data": {
                        "page": "${page}",
                        "perPage": "${perPage}",
                        "keywords": "${menuid-keywords}",
                        "_$_tableName": "sys_menutable",
                        "_$_pk": "menuid",
                        "_$_action": "P",
                        "_$_query_filter": "1^10^menuid^*^^^menuid,parent_menuid,caption,moduleid,seq_no^${menuid}"
                      },
                      "dataType": "form"
                    },
                    "size": "md",
                    "value": "",
                    "multiple": false,
                    "pickerSchema": {
                      "mode": "table",
                      "tableClassName": "myGridHeader_a",
                      "title": "Menu",
                      "name": "sys_menutable-menuid",
                      "headerToolbar": {
                        "wrapWithPanel": false,
                        "type": "form",
                        "promptPageLeave": true,
                        "className": "text-right",
                        "target": "sys_menutable-menuid",
                        "mode": "inline",
                        "body": [
                          {
                            "type": "input-text",
                            "name": "menuid-keywords",
                            "addOn": {
                              "type": "submit",
                              "label": "查詢",
                              "tooltip": "輸入 * 可以查詢全部資料",
                              "level": "primary",
                              "icon": "fa fa-search pull-left"
                            }
                          }
                        ]
                      },
                      "columns": [
                        {
                          "type": "text",
                          "name": "menuid",
                          "label": "選單代號",
                          "toggled": true
                        },
                        {
                          "type": "text",
                          "name": "parent_menuid",
                          "label": "上層選單代號",
                          "toggled": true
                        },
                        {
                          "type": "text",
                          "name": "caption",
                          "label": "選單抬頭",
                          "toggled": true
                        },
                        {
                          "type": "text",
                          "name": "moduleid",
                          "label": "模組代號",
                          "toggled": true
                        },
                        {
                          "type": "text",
                          "name": "seq_no",
                          "label": "序號",
                          "toggled": true
                        },
                        {
                          "type": "text",
                          "name": "isLocalMenu",
                          "label": "本地功能",
                          "toggled": true
                        }
                      ]
                    }
                  },
                  {
                    "type": "select",
                    "name": "controlname",
                    "creatable": true,
                    "addControls": [
                      {
                        "type": "text",
                        "name": "label",
                        "label": "選項標題"
                      },
                      {
                        "type": "text",
                        "name": "value",
                        "label": "選項值"
                      }
                    ],
                    "options": [
                      {
                        "label": "delete",
                        "value": "delete"
                      },
                      {
                        "label": "insert",
                        "value": "insert"
                      },
                      {
                        "label": "print",
                        "value": "print"
                      },
                      {
                        "label": "read",
                        "value": "read"
                      },
                      {
                        "label": "update",
                        "value": "update"
                      }
                    ],
                    "disabled": true,
                    "required": true,
                    "label": "權限控制項"
                  }
                ]
              }
            }
          },
          {
            "type": "button",
            "icon": "fa fa-times text-danger",
            "actionType": "ajax",
            "disabledOn": "${ls:sys0a@delete == null}",
            "tooltip": "刪除",
            "confirmText": "確定要刪除本筆資料?",
            "api": {
              "method": "post",
              "url": "${ls:base_ip}/xapi/v2/${ls:base_db}/orm_api/2/",
              "dataType": "form",
              "requestAdaptor": "return {\n    ...api,\n    data: {\n        ...api.data,\n    token: local_get_token(),\n    _$_tableName: \"sys_rolemenusecurity\",\n    _$_pk: \"roleid,menuid,controlname\",\n    _$_action: \"D\"}\n}"
            }
          }
        ]
      }
    ]
  }
}

**Comment by allenve** [comment]
"keywords": "${roleid-keywords}",
这里的变量名避免使用中横线   会被当做公式计算

**Comment by gexMichael** [comment]
改为 _ 后测试正确，谢谢
