### ISSUE TITLE
CRUD表格树控件无法懒加载节点下阶数据

### ISSUE THREAD

**Issue by citynook** [baidu/amis#8234]
#### 描述问题：
现在的表格树只能一次性加载表格树所有节点的数据并显示，无法在点击树节点时才懒加载下一阶的数据。

当前的应用场景希望页面初始化时，只加载第一阶的数据，有下阶数据的表格树节点显示为+，点击后展开并调用API获取下一阶数据并展示，实现懒加载。
因数据量比较大，若按现有的方式一次性加载全部数据，性能方面会受到很大影响，并且大部分数据可能是不需要展开及关注的。

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.4.1

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by citynook** [comment]
@2betop 请问有什么方案可以实现表格树的懒加载吗？

**Comment by 2betop** [comment]
目前不支持，目前只有 tree 组件才支持

**Comment by citynook** [comment]
已提出新功能建议，自行关闭。
