### ISSUE TITLE
【bug】最新编辑器 表格列选择后 属性存在报错

### ISSUE THREAD

**Issue by lhtuling** [baidu/amis#8236]
下载最新源码编译启动后 即可复现
![image](https://github.com/baidu/amis/assets/44140500/61133244-66f2-486b-a37b-892e1571e7fc)

**Comment by wibetter** [comment]
npm list amis-editor 看下当前的版本号是多少，

**Comment by lhtuling** [comment]
好像没毛病   可能是我这边有问题。。。重新下载了一次又没有了
