### ISSUE TITLE
请问 initApi 如果拿到地址栏上的参数 拼接到上去

### ISSUE THREAD

**Issue by zhao812** [baidu/amis#824]
"initApi": "/api/getUser/$id"
 id 是网页地址栏上的?id=1

**Comment by RickCole21** [comment]
你的问题是啥

**Comment by zhao812** [comment]
"tpl": "这是你刚刚新增的页面,id=${id}。"
页面上的?id=1
在body 中拿不到
"body": [
				{
					"type": "tpl",
					"tpl": "这是你刚刚新增的页面,id=${id}。"
				}
			]

**Comment by RickCole21** [comment]
发使用方法，以及完整配置schema

**Comment by zhao812** [comment]
http://127.0.0.1:8001/#/page/2?id=86
![image](https://user-images.githubusercontent.com/19986834/89403494-f703e200-d74a-11ea-88ce-0d6dfab75cc6.png)

**Comment by zhao812** [comment]
很简单的一个配置 拿url 上的id参数

**Comment by RickCole21** [comment]
配置看起来没问题，console里有啥报错吗

**Comment by zhao812** [comment]
大佬，控制台 没有报错。
amis 或自动拿url上的参数么？

**Comment by RickCole21** [comment]
https://baidu.github.io/amis/docs/concepts/datascope-and-datachain

地址栏里的参数应该可以通过数据链获取到的，你链接是啥

**Comment by zhao812** [comment]
谢谢 大佬， 我这边看了render 方法的RootRenderProps参数， 已经处理了
![image](https://user-images.githubusercontent.com/19986834/89480360-b72f1000-d7c7-11ea-97e9-e4b425d049b7.png)
