### ISSUE TITLE
remark属性的通用性

### ISSUE THREAD

**Issue by xinghe94** [baidu/amis#825]
打扰了 可以把remark兼容到每个formitem层级嘛 感觉平常在表单的label附近放个小提示还是挺常见的需求 发现最新版本有暴露这个remark组件 但是很多场景的样式还得自定义才能符合业务需求 因为它作为一个组件独占一行了

**Comment by RickCole21** [comment]
`labelRemark`，看来要补一下文档了
```
{
    "type": "text",
    "name": "text",
    "label": "text",
    "labelRemark": "remarkkkkkkk"
}
```

**Comment by xinghe94** [comment]
>     "labelRemark": "remarkkkkkkk"
好的 thx

**Comment by qinaidetonggege** [comment]
> `labelRemark`，看来要补一下文档了
> 
> ```
> {
>     "type": "text",
>     "name": "text",
>     "label": "text",
>     "labelRemark": "remarkkkkkkk"
> }
> ```

请问remark的值可以传变量吗

**Comment by xinghe94** [comment]
> > `labelRemark`，看来要补一下文档了
> > ```
> > {
> >     "type": "text",
> >     "name": "text",
> >     "label": "text",
> >     "labelRemark": "remarkkkkkkk"
> > }
> > ```
> 
> 请问remark的值可以传变量吗

可以的啊 类似这样  "remark":"$xx", xx是变量名
