### ISSUE TITLE
请问一下，crud如何修改行记录数据

### ISSUE THREAD

**Issue by tujiajun** [baidu/amis#8258]
#### 实现场景：
我希望能修改crud指定的某行数据，最好是能同时触发quickedit接口

#### 存在的问题：
查阅文档，发现貌似setvalue只能一次性更新列表所有数据，无法按行赋值
![image](https://github.com/baidu/amis/assets/127007861/b9f92c80-af7e-457e-82d9-02cdd3a27d23)
而行记录字段赋值的方式只能赋予某个行内的某个字段
![image](https://github.com/baidu/amis/assets/127007861/344fa5c3-4d3d-4415-8cff-9a1abb5b5ef3)

**Comment by lhtuling** [comment]
现在可以通过自定义js事件修改   
既然能修改全部的如果数据量不大直接吧所有数据都获取过来然后修改其中你想要修改的  然后整体赋值过去就行了

自定义js用好很强大~~~
Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by lhtuling** [comment]
![e3ed35da-d516-4491-97a2-c282a7911a15](https://github.com/baidu/amis/assets/44140500/7d6b45c0-aab6-4f4f-83ae-107fa02f5848)
```
let newItems = JSON.parse(JSON.stringify(event.data.InvPurchaseItems));
newItems.forEach(function (item) {
  if (item.InStockQty < item.PurchaseQty) {
    item.InStockQty = item.PurchaseQty;
  }
});

doAction({
  actionType: "setValue",
  componentId: "inputtable",
  args: {
    value: newItems,
  },
});
```
做过一个批量修改所有行的指定列的   改改就能用

**Comment by hsm-lv** [comment]
https://baidu.github.io/amis/zh-CN/components/crud#%E6%9B%B4%E6%96%B0%E6%8C%87%E5%AE%9A%E8%A1%8C%E8%AE%B0%E5%BD%95
