### ISSUE TITLE
CRUD 导出的excel文件 丢失总结行

### ISSUE THREAD

**Issue by DreamingLight** [baidu/amis#8262]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by faceair** [comment]
你这问题提的太敷衍了，提交一下 amis 的描述 json，方便的话给一下脱敏后的 excel 表格

**Comment by DreamingLight** [comment]
不好意思和哈，我补充一下，测试的json内容如下：

{
  "type": "page",
  "title": "测试4",
  "body": [
    {
      "type": "crud",
      "syncLocation": false,
      "source": "${rows}",
      "columns": [
        {
          "name": "id",
          "label": "ID",
          "type": "text",
          "id": "u:8a93d4e1a7ac"
        },
        {
          "name": "engine",
          "label": "渲染引擎",
          "type": "text",
          "id": "u:d3c571e557d7"
        }
      ],
      "bulkActions": [
      ],
      "itemActions": [
      ],
      "id": "u:e0c1883c062d",
      "perPageAvailable": [
        10
      ],
      "messages": {
      },
      "headerToolbar": [
        {
          "type": "export-excel",
          "id": "u:a95a12f40fc2"
        }
      ],
      "affixRow": [
        {
          "type": "text",
          "text": "总计",
          "id": "u:431872cad4b5"
        },
        {
          "type": "tpl",
          "tpl": "${rows|pick:id|sum}",
          "id": "u:b526345a45ae"
        }
      ]
    }
  ],
  "id": "u:e58ac9458b52",
  "data": {
    "rows": [
      {
        "id": 1,
        "engine": "aaaa"
      },
      {
        "id": 2,
        "engine": "bb"
      }
    ]
  }
}

json 预览截图如下：
![image](https://github.com/baidu/amis/assets/43959776/35c26ac8-62d3-4194-9e64-0f72eb01ba19)



导出的excel内容如下：
![image](https://github.com/baidu/amis/assets/43959776/f83bf56c-2edb-47c4-886e-acf49cc19948)


期望能把实际的excel 的总结行也一并导出

**Comment by nwind** [comment]
Duplicate of #2911

**Comment by nwind** [comment]
#8286
