### ISSUE TITLE
inputTable 自动计算包含父级数据，数据不更新不全

### ISSUE THREAD

**Issue by DreamingLight** [baidu/amis#8263]
#### 描述问题：
在form表单里面增加一个数字框组件和一个inputTable组件，然后inputTable组件中一个字段需要关联父级数字框做计算，当前结果是页面的最后一条数据计算发生了变化，但是其它列的没有更新。

#### 截图或视频：
如图分数的前两列都为0，没有更新，分数=首年保费*分数1
![image](https://github.com/baidu/amis/assets/43959776/6cb7121d-2062-42cd-9b7f-53e55fae128e)

#### 如何复现（请务必完整填写下面内容）：
创建 test.html  内容如下：
```html
<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="UTF-8" />
    <title>amis demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/amis@3.4.2/sdk/helper.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/amis@3.4.2/sdk/iconfont.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/amis@3.4.2/sdk/antd.css" />
    <!-- 这是默认主题所需的，如果是其他主题则不需要 -->
    <!-- 从 1.1.0 开始 sdk.css 将不支持 IE 11，如果要支持 IE11 请引用这个 css，并把前面那个删了 -->
    <!-- <link rel="stylesheet" href="antd-ie11.css" /> -->
    <!-- 不过 amis 开发团队几乎没测试过 IE 11 下的效果，所以可能有细节功能用不了，如果发现请报 issue -->
    <style>
      html,
      body,
      .app-wrapper {
        position: relative;
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="root" class="app-wrapper"></div>
    <script src="https://cdn.jsdelivr.net/npm/amis@3.4.2/sdk/sdk.js"></script>
    <script type="text/javascript">
      (function () {
        let amis = amisRequire('amis/embed');
        // 通过替换下面这个配置来生成不同页面
        let amisJSON = {
  "type": "page",
  "title": "测试3",
  "body": [
    {
      "type": "form",
      "title": "表单",
      "body": [
        {
          "type": "input-number",
          "label": "数字",
          "name": "number",
          "keyboard": true
        },
        {
          "type": "table-view",
          "trs": [
            {
              "background": "#F7F7F7",
              "tds": [
                {
                  "body": {
                    "type": "tpl",
                    "wrapperComponent": "",
                    "tpl": "保费信息"
                  }
                },
                {
                  "body": {
                    "type": "tpl",
                    "wrapperComponent": "",
                    "tpl": "首年保费"
                  }
                }
              ],
              "height": 65
            },
            {
              "tds": [
                {
                  "rowspan": 1,
                  "body": {
                    "type": "tpl",
                    "wrapperComponent": "",
                    "tpl": "美元"
                  }
                },
                {
                  "body": [
                    {
                      "type": "input-number",
                      "name": "dollar",
                      "keyboard": true,
                      "step": 1
                    }
                  ]
                }
              ],
              "height": 79
            }
          ]
        },
        {
          "type": "input-table",
          "name": "table",
          "label": "表格表单",
          "columns": [
            {
              "label": "名称",
              "name": "name",
              "type": "input-text"
            },
            {
              "label": "分数1",
              "name": "score1",
              "type": "input-number"
            },
            {
              "label": "分数",
              "type": "input-number",
              "name": "score",
              "value":"${score1 * dollar}"
            }
          ],
          "strictMode": false,
          "needConfirm": false,
          "canAccessSuperData": true
        }
      ],
      "debug": true
    }
  ],
  "regions": [
    "body",
    "header"
  ],
  "data": {
    "table": [
      {
        "name": "aaa",
        "score1": 1
      },
      {
        "name": "bbb",
        "score1": 2
      },
      {
        "name": "ccc",
        "score1": 3
      }
    ]
  }
};
        let amisScoped = amis.embed('#root', amisJSON,{},{theme: "antd"});
      })();
    </script>
  </body>
</html>
```

4. 操作步骤
页面正常打开之后 在  首年保费录入数字，
问题情况：  分数的最后一列变更，其它列都变是0。
正确情况： 分数的所有列都及时变更。

**Comment by DreamingLight** [comment]
问题现象：
   使用最新的3.4.3版本  发现以下代码仍然有问题，inputTable的数据无法更新，页面数字一直在跳动
页面正常打开之后 在 在数字录入数字，然后在首年保费录入数字，
问题情况： 分数列的公式不发生变化。
正确情况： 分数的所有列都及时变更，数值和显示都及时能正常。


<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="UTF-8" />
    <title>amis demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    
    <link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/amis@3.4.3/sdk/helper.css" />
    <link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/amis@3.4.3/sdk/iconfont.css" />
    <link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/amis@3.4.3/sdk/antd.css" />
    
    
    
    
    <style>
      html,
      body,
      .app-wrapper {
        position: relative;
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="root" class="app-wrapper"></div>
    <script src="https://fastly.jsdelivr.net/npm/amis@3.4.3/sdk/sdk.js"></script>
    <script type="text/javascript">

      (function () {
        let amis = amisRequire('amis/embed');
        // 通过替换下面这个配置来生成不同页面
        let amisJSON = {
  "type": "page",
  "title": "测试3",
  "body": [
    {
      "type": "form",
      "name":"form",
      "id":"id-form",
      "title": "表单",
      "body": [
        {
          "type": "input-number",
          "label": "数字",
          "name": "number",
          "keyboard": true
        },
        {
          "type": "table-view",
          "trs": [
            {
              "background": "#F7F7F7",
              "tds": [
                {
                  "body": {
                    "type": "tpl",
                    "wrapperComponent": "",
                    "tpl": "保费信息"
                  }
                },
                {
                  "body": {
                    "type": "tpl",
                    "wrapperComponent": "",
                    "tpl": "首年保费"
                  }
                }
              ],
              "height": 65
            },
            {
              "tds": [
                {
                  "rowspan": 1,
                  "body": {
                    "type": "tpl",
                    "wrapperComponent": "",
                    "tpl": "美元"
                  }
                },
                {
                  "body": [
                    {
                      "type": "input-number",
                      "name": "dollar",
                      "keyboard": true,
                      "step": 1,
                      "value":0
                    }
                  ]
                }
              ],
              "height": 79
            }
          ]
        },
        {
          "type": "input-table",
          "name": "table",
          "id": "id-table",
          "label": "表格表单",
          "columns": [
            {
              "label": "名称",
              "name": "name",
              "type": "input-text"
            },
            {
              "label": "分数1",
              "name": "score1",
              "type": "input-number"
            },
            {
              "type": "input-number",
              "name": "score",
              "label": "分数",
              "value": "${dollar*score1*number}"
            },
            {
              "type": "input-number",
              "name": "score2",
              "label": "分数",
              "value": "${dollar*score1*number*score}"
            },
            {
              "type": "input-number",
              "name": "score3",
              "label": "分数"
            },
            {
              "type": "input-number",
              "name": "score4",
              "label": "分数",
              "value": "${score2 - score3}"
            }

          ],
          "strictMode": false,
          "needConfirm": false,
          "canAccessSuperData": true
        }
      ],
      "debug": true,
      "actions": [
        {
          "type": "submit",
          "label": "提交",
          "primary": true
        }
      ],
      "data": {
        "table": [
          {
            "name": "aaa",
            "score1": 1
          },
          {
            "name": "bbb",
            "score1": 2
          },
          {
            "name": "ccc",
            "score1": 3
          }
        ]
      }
    }
  ],
  "regions": [
    "body",
    "header"
  ]
};
        let amisScoped = amis.embed('#root', amisJSON,{},{theme: "antd",enableAMISDebug :true});
      })();
    </script>
  </body>
</html>
`

**Comment by 2betop** [comment]
奇怪之前是好的，又坏了
