### ISSUE TITLE
下面readme文件说明中，交流群QQ里搜索不到，请问可以更新一下交流群号吗

### ISSUE THREAD

**Issue by w969883297** [baidu/amis#8265]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by allenve** [comment]
README中是如流群，不是QQ群   https://infoflow.baidu.com/#/

**Comment by nwind** [comment]
qq 群实在没空打理，之前有出现发小广告的情况，影响不太好所以目前隐藏了
