### ISSUE TITLE
jssdk 3.4.2 版本select组件启用搜索在mobile模式不显示

### ISSUE THREAD

**Issue by leaf188** [baidu/amis#8282]
#### 描述问题：

jssdk 3.4.2 版本select组件的searchable设为true，在PC模式下正常，在mobile模式搜索框不显示

代码：
`{
      "type": "page",
      "body": [{
          "type": "form",
          "title":"",
          "body": [
            {
              "type": "select",
              "name": "select",
              "label": "选项",
              "clearable": true,
              "placeholder": "请选择",
              "multiple": false,
              "searchable": true,
              "options": [
                {
                  "label": "A",
                  "value": 0
                },
                {
                  "label": "B",
                  "value": 1
                },
                {
                  "label": "C",
                  "value": 2
                }
              ]
            }
          ]
        }
      ]
    }`
截图：
[
![20230928145754](https://github.com/baidu/amis/assets/19721678/e6e8c79b-c44e-4c7d-a847-0202f95240bf)
](url)

**Comment by lhtuling** [comment]
我也昨天刚碰到过    
看下面移动端文档  解决
https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/mobile

Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449
