### ISSUE TITLE
可视化编辑器有没有 jssdk 版本?

### ISSUE THREAD

**Issue by d0uub** [baidu/amis#8290]
那么就整个也不用react 了

**Comment by lhtuling** [comment]
下载下来源码 build一下  就是了吧~   没试过   
专门学了下react发现用着也挺方便，现在在自己改编辑器 方便自己各种情况用

Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by Mengleijin** [comment]
@lhtuling 有微信群吗

**Comment by 2betop** [comment]
可视化编辑器没有 jssdk 版本，后续也没计划，这个先关了
