### ISSUE TITLE
InputTable如何监听到拖拽的orderChange事件

### ISSUE THREAD

**Issue by yegao** [baidu/amis#8291]
#### 实现场景：
我需要使用InputTable，配置draggable为true使之支持拖拽行，我希望在拖拽完之后监听到orderChange事件，以对比发生的变化。

#### 存在的问题：
在拖拽完行之后我没有办法监听到orderChange事件

**Comment by hsm-lv** [comment]
https://baidu.github.io/amis/zh-CN/components/crud#%E6%9B%B4%E6%96%B0%E6%8C%87%E5%AE%9A%E8%A1%8C%E8%AE%B0%E5%BD%95
