### ISSUE TITLE
编辑器生成的代码，sdk 无法解析

### ISSUE THREAD

**Issue by csx-bill** [baidu/amis#8292]
#### 描述问题：

编辑器生成的代码，sdk 无法解析

#### 截图或视频：
编辑器
![image](https://github.com/baidu/amis/assets/31872268/c9d4c3df-a347-4510-a44c-8266ae51e18e)

sdk 
![image](https://github.com/baidu/amis/assets/31872268/02d4b987-398a-48d0-b9e5-513492b7a66b)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

react  npm  方式 引入 sdk 方式

3. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
    "amis": "^3.4.2",
    "amis-core": "^3.4.2",
    "amis-editor": "^5.6.1",
    "amis-editor-core": "^5.6.1",
4. 粘贴有问题的完整 `amis schema` 代码：

{
  "type": "button",
  "id": "u:65cb14e9a542",
  "label": "编辑",
  "level": "link",
  "onEvent": {
    "click": {
      "weight": 0,
      "actions": [
        {
          "drawer": {
            "id": "u:35f404e0de40",
            "body": [
              {
                "id": "u:ef5d6da7d8ba",
                "api": {
                  "url": "/api/system/SysDict/updateById",
                  "method": "put",
                  "dataType": "json",
                  "messages": {
                  }
                },
                "body": [
                  {
                    "id": "u:5c722c2a8a54",
                    "name": "id",
                    "type": "input-text",
                    "label": "ID",
                    "hidden": true
                  },
                  {
                    "id": "u:052907cba961",
                    "name": "dictCode",
                    "type": "input-text",
                    "label": "字典编码",
                    "disabled": true,
                    "readOnly": false,
                    "required": true,
                    "editorPath": "input.base.default"
                  },
                  {
                    "id": "u:fc1f6dbc3b67",
                    "name": "dictName",
                    "type": "input-text",
                    "label": "字典名称",
                    "required": true
                  },
                  {
                    "id": "u:d698b60224bc",
                    "name": "status",
                    "type": "select",
                    "label": "状态",
                    "source": {
                      "url": "/api/system/SysDictData/queryDictDataByDictCode?dictCode=sys_dict_status",
                      "method": "get",
                      "messages": {
                      }
                    },
                    "multiple": false,
                    "required": true,
                    "labelField": "dictText",
                    "valueField": "dictValue"
                  }
                ],
                "type": "form",
                "title": "表单"
              }
            ],
            "type": "drawer",
            "title": "编辑",
            "resizable": false
          },
          "actionType": "drawer"
        }
      ]
    }
  },
  "hiddenOn": "${!ARRAYINCLUDES(permsCode,'SysDict:update')}"
}  编辑器 可以解析， sdk   无法解析这个json

**Comment by lhtuling** [comment]
不能直接放控件json  最外层需要包裹 page
![5ce2aebc-929b-47a8-a893-457b8d644604](https://github.com/baidu/amis/assets/44140500/c3fbd298-fb92-4cc0-9d5b-67edbf6b96df)


Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449
