### ISSUE TITLE
升级3.4.2后，CURD嵌套表格的展开按钮没有显示

### ISSUE THREAD

**Issue by mfkwgizhoujian** [baidu/amis#8301]
#### 描述问题：

3.4.2之前的版本中，CURD只要数据中有children字段，会自动渲染出树形结构，可以展开收缩，升级后，展开收缩按钮没有了，是需要增加额外的配置吗？

#### 截图或视频：

<img width="1233" alt="image" src="https://github.com/baidu/amis/assets/33543763/15c1a25d-5ef9-4924-befd-9249d98b1287">
<img width="849" alt="image" src="https://github.com/baidu/amis/assets/33543763/58a313f2-b099-4c6c-968b-4d4b99ebea20">

**Comment by 2betop** [comment]
有问题 schema 吗？amis 示例看起来功能正常

**Comment by 2betop** [comment]
貌似文档里面的示例能复现，我先分析

**Comment by 2betop** [comment]
清空一下 localStorage 试试？难道是因为列被设置成隐藏了

**Comment by mfkwgizhoujian** [comment]
> 有问题 schema 吗？amis 示例看起来功能正常

我找到原因了，现在的展开图标是渲染在第一列，但是如果第一列的toggled默认设置为隐藏，就会导致展开图标没法显示了，但是之前的版本是没有这个问题的，你可以去官网示例中CRUD的嵌套例子看，无论隐藏哪一列，展开图标都会显示的，新版本貌似把展开后的竖线也给取消了。

**Comment by mfkwgizhoujian** [comment]
@2betop

**Comment by jackHuang-123** [comment]
>



> > 有问题 schema 吗？amis 示例看起来功能正常
> 
> 我找到原因了，现在的展开图标是渲染在第一列，但是如果第一列的toggled默认设置为隐藏，就会导致展开图标没法显示了，但是之前的版本是没有这个问题的，你可以去官网示例中CRUD的嵌套例子看，无论隐藏哪一列，展开图标都会显示的，新版本貌似把展开后的竖线也给取消了。
你好，这个页面的json配置代码可以贴一下吗，我用curd，嵌套出现问题了，用的amis3.0版本

**Comment by 2betop** [comment]
https://github.com/baidu/amis/pull/8302 中修复了此问题
