### ISSUE TITLE
更新到3.2及后续版本 api 中带有变量从上级组件获取数据异常

### ISSUE THREAD

**Issue by phantooom** [baidu/amis#8304]
#### 描述问题：

```

{
  "type": "page",
  "title": "列表",
  "remark": null,
  "name": "admin-dev-list",
  "body": {
    "type": "service",
    "data":{
      "machine-list-api":"api/v1/admin/machines"
    },
    "schemaApi": "get:pages/machine-list.json"
  }
}

// 下边这段是  pages/machine-list.json
{
  "type": "crud",
  "name": "get-machine-list",
  "api": "${machine-list-api}?page=${page}&perPage=${perPage}&orderBy=${orderBy}&orderDir=${orderDir}&name=${name}&status=${status}",
  "syncLocation": false,
  "interval": 10000,
  "silentPolling": true,
  "filter": {
    "title": "",
    "mode": "inline",
    "wrapWithPanel": false,
    "submitText": "",
    "className": "m-b-sm"
  },
  "columns": [
    {
      "name": "id",
      "label": "ID",
      "width": 20,
      "sortable": true
    }
  ]
}
```

machine-list-api 这个变量在3.2.0->3.4.2 的版本会被替换到0，而3.1.1 及之前版本会被替换成  api/v1/admin/machines
#### 截图或视频：
正常的版本3.1.1 及以前的版本
![image](https://github.com/baidu/amis/assets/10242001/76b59dd5-3e09-434e-a71e-4110120135ca)

异常的版本(3.2.0 之后的版本)
![image](https://github.com/baidu/amis/assets/10242001/90a79e46-a52e-4d90-a228-485a5ef59355)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

存在

4. 操作步骤
amis 的json贴上去了

**Comment by 2betop** [comment]
因为变量规则问题，请修改成这样

`api: '${&["machine-list-api"]}?page=${page}&perPage=${perPage}&orderBy=${orderBy}&orderDir=${orderDir}&name=${name}&status=${status}',`

**Comment by phantooom** [comment]
感谢，按照你的说明已经成功了。

还有一个问题困扰了比较久了，能否指点一下呐。https://github.com/baidu/amis/issues/8012
