### ISSUE TITLE
仅仅只是搭建前端页面使用怎么部署，没看懂文档

### ISSUE THREAD

**Issue by liuliran123** [baidu/amis#8320]
仅仅只是搭建前端页面使用怎么部署，没看懂文档

**Comment by xuzengguo** [comment]
同问 +1

**Comment by duian** [comment]
> 仅仅只是搭建前端页面使用怎么部署，没看懂文档

部署需要你自己实现。 例如如果是把 amis 当做 React 组件来用， 那么原来的项目该如何部署构建就如何部署构建。 如果是想做成类似 aisuda 的形式， 那就需要自己实现一套完成的应用创建，管理，发布等功能。

amis 本身只是提供 JSON 渲染 React 组件以及提供了 amis-editor 这个可视化编辑器。

**Comment by 2betop** [comment]
amis 仅仅是个前端库，怎么部署需要自行解决
