### ISSUE TITLE
CRUD中header里的form提交表单时会把table的rows作为data提交

### ISSUE THREAD

**Issue by hyyan112** [baidu/amis#834]
列表里的rows如下
![image](https://user-images.githubusercontent.com/13252148/89749773-bf56ba80-dafb-11ea-8ac6-3e40f3446d7e.png)

form header配置如下
![image](https://user-images.githubusercontent.com/13252148/89749733-9504fd00-dafb-11ea-9c93-26385f8d4786.png)

提交时被带上了所有rows
![image](https://user-images.githubusercontent.com/13252148/89749705-756dd480-dafb-11ea-9ee3-d35b821ea019.png)

是本身这么设计的,还是有bug呢?

**Comment by 2betop** [comment]
bug，应该是不需要单独配置 api 的，直接走 crud 的 api，这个后面让配置 api 失效

**Comment by 2betop** [comment]
1.5.0 里面 filter配置 api 将无效了
