### ISSUE TITLE
crud page lose orderDir value when using quicksearch

### ISSUE THREAD

**Issue by mizililo** [baidu/amis#8342]
#### 描述问题：
crud组件，表头快捷搜索关键词，当搜索字段非当前排序字段时，排序方向失效

#### 截图或视频：
见下方操作步骤

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网示例
https://baidu.github.io/amis/examples/crud/table?orderBy=id&orderDir=asc&page=1

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.4.2

3. 粘贴有问题的完整 `amis schema` 代码：
参考官网示例

4. 操作步骤
默认orderBy=id，orderDir=asc，使用快捷搜索一个非排序字段
![image](https://github.com/baidu/amis/assets/85606977/f4ebbc06-dd91-4258-9513-3743d545cd7e)
orderDir置为空
![image](https://github.com/baidu/amis/assets/85606977/d159eabe-ae6c-405d-bef3-c3c998ce120a)
个人认为搜索行为不应该影响排序行为，此时应当仍复用原先的orderDir

https://github.com/baidu/amis/blob/365c87599c3c7de6740caaf291b6a58d89769b35/packages/amis/src/renderers/Table2/HeadCellSearchDropdown.tsx#L295
请斟酌一下是否需要去除这一段
![image](https://github.com/baidu/amis/assets/85606977/05d24379-8081-4cbe-985c-c802f755e81f)

**Comment by 2betop** [comment]
看起来没问题，因为切换了字段，那么原来属于前字段的排序顺序应该失效。

目前列上的排序按钮点击也是，比如首次点 A 排序，a 是正序，然后再点 B 排序，b 是正序。而不是 b 就变成反序。我觉得这两操作应该是一个逻辑。

**Comment by 2betop** [comment]
不过，这段逻辑是原来排序与搜索合并表单用的，后来被改成两个 icon 了，确实不应该有这个逻辑了
