### ISSUE TITLE
弹窗大纲中无法选择弹窗外组件，因此无法设置相关状态和数据

### ISSUE THREAD

**Issue by 52flutter** [baidu/amis#8344]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
弹窗大纲中无法选择弹窗外组件，因此无法设置相关状态和数据
#### 截图或视频：
![image](https://github.com/baidu/amis/assets/11569655/d6873d12-36a6-47af-8e3a-54139ae2c4d0)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
https://aisuda.github.io/amis-editor-demo/#/edit/0
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
都存在
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by Icodezhan** [comment]
随便选一个，完了改源码id即可

**Comment by wibetter** [comment]
@52flutter 感谢反馈，确实是个问题。

**Comment by wibetter** [comment]
@52flutter 目标组件 可以选择「输入组件id」，手动录入当前页面任何层级中的组件元素ID：
<img width="877" alt="image" src="https://github.com/baidu/amis/assets/11958920/c4582c80-9eb2-4b5a-b3f0-49c53fe44937">
<img width="868" alt="image" src="https://github.com/baidu/amis/assets/11958920/93918049-09a9-44ce-b93d-d45813186e29">
