### ISSUE TITLE
input-datetime 和 input-date 能否支持手动输入方式

### ISSUE THREAD

**Issue by laizuan** [baidu/amis#8346]

**Comment by wibetter** [comment]
@laizuan 可以在左侧code面板手动调整：
<img width="900" alt="image" src="https://github.com/baidu/amis/assets/11958920/1848a89e-f96c-40e4-92a5-eaf97faaafc7">

**Comment by laizuan** [comment]
我表述的是两个组件手动输入日期，不需要鼠标选择日期

**Comment by wibetter** [comment]
@laizuan 是说手动输入日期时间，那你换input-text就好了

**Comment by wibetter** [comment]
@laizuan 已在此修复，待下一版生效：https://github.com/baidu/amis/pull/8797/commits/5bf903e32e52f45c0bdb1fde7585bbce76a4b44f

**Comment by laizuan** [comment]
👍
