### ISSUE TITLE
编辑器中-状态显示组件-编辑左侧源码-先添加className，再在右侧面板修改图标配置-比如修改颜色，组件刷新后定义的className不见了

### ISSUE THREAD

**Issue by w969883297** [baidu/amis#8348]
问题1：编辑器中-状态显示组件-编辑左侧源码-先添加className，再在右侧面板修改图标配置-比如修改颜色，组件刷新后定义的className不见了
例如：
"跳过": {
  "label": "跳过",
  "icon": "",
  "color": "#f5a623",
  "className": "bg-primary"
},

问题2：
这个"className"可以设成变量吗，在crud组件里，下方的 label是可以获取到变量的，但是className依然是字符串，或者该用什么方式实现
例如
"未审批": {
"label": "${jumpTypeName}",
"icon": "rolling",
"className": '${className}'
},

**Comment by wibetter** [comment]
@w969883297 
第一个问题没复现；
第2个目前新版amis已经支持：
<img width="968" alt="image" src="https://github.com/baidu/amis/assets/11958920/77410b6b-73d3-4cce-8708-dab55af29be7">
