### ISSUE TITLE
table2的嵌套数据问题

### ISSUE THREAD

**Issue by jackHuang-123** [baidu/amis#8363]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
使用table2，然后会出现嵌套下的数据出现第一层的数据，在官网和amis渲染器上试了都这样，
![image](https://github.com/baidu/amis/assets/120307935/1d70095b-19ca-4777-bc78-bda95e69907b)

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
npm ，加ami-editor编辑器

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3. amis版本3.0，编辑器^5.2.4-beta.31

4. 粘贴有问题的完整 `amis schema` 代码：
5.  {
          "title": "角色树",
          "type": "page",
          "body": {
            "type": "service",
          "data":{
            "roleOid": 0,
            "roleName": "ROOT",
            "roleCode": "0000",
            "children": [
                {
                    "roleOid": 1,
                    "roleName": "系统超管",
                    "roleCode": "1000000000000000",
                    "parentOid": 0,
                    "allowBind": 1,
                    "bound": 1,
                    "locked": false,
                    "children": []
                },
                {
                    "roleOid": 6,
                    "roleName": "2222",
                    "roleCode": "6",
                    "parentOid": 0,
                    "allowBind": 11,
                    "bound": 0,
                    "locked": false,
                    "children": [
                        {
                            "roleOid": 9,
                            "roleName": "22",
                            "roleCode": "60009",
                            "parentOid": 6,
                            "allowBind": 1,
                            "bound": 0,
                            "locked": false,
                            "children": [
                                {
                                    "roleOid": 10,
                                    "roleName": "孩子",
                                    "roleCode": "600090010",
                                    "parentOid": 9,
                                    "allowBind": 1,
                                    "bound": 0,
                                    "locked": false,
                                    "children": []
                                }
                            ]
                        }
                    ]
                },
                {
                    "roleOid": 8,
                    "roleName": "擦擦",
                    "roleCode": "8",
                    "parentOid": 0,
                    "allowBind": 1,
                    "bound": 0,
                    "locked": false,
                    "children": []
                }
            ]
        
          },
            "body": [
              {
                "type": "table2",
                "source": "children",
                "childrenColumnName": "children",   
                "headerToolbar": [
                  {
                    "label": "新增",
                    "type": "button",
                    "actionType": "dialog",
                    "level": "primary",
                    "dialog": {
                      "type": "dialog",
                      "title": "新增",
                      "closeOnEsc": false,
                      "closeOnOutside": false,
                      "showCloseButton": true,
                      "data": {
                        "&": "$$",
                        "status": "__undefined"
                      },
                      "body": [
                        {
                          "type": "form",
                          "api": "/amis/api/mock2/form/saveForm",
                          "debug": false,
                          "body": [
                            {
                              "type": "input-text",
                              "name": "name",
                              "label": "姓名",
                              "disabled": false,
                              "selectFirst": false
                            },
                            {
                              "type": "input-text",
                              "name": "sax",
                              "label": "下单",
                              "disabled": false,
                              "selectFirst": false
                            }
                          ]
                        }
                      ]
                    }
                  }
                ],
                "columns": [
                  {
                    "name": "roleName",
                    "title": "roleName"
                  },
                  {
                    "name": "roleOid",
                    "title": "roleOid"
                  },
                  {
                    "type": "operation",
                    "label": "操作",
                    "width": 350,
                    "buttons": [
                      {
                        "type": "button",
                        "label": "新增",
                        "actionType": "dialog",
                        "level": "primary",
                        "size": "md",
                        "style": {
                          "margin": "5px"
                        },
                        "dialog": {
                          "title": "新增角色",
                          "body": {
                            "type": "form",
                            "controls": [
                              {
                                "name": "roleName",
                                "label": "角色名称",
                                "type": "text",
                                "required": true
                              },
                              {
                                "name": "allowBind",
                                "label": "允许绑定的账户数量",
                                "type": "number",
                                "required": true
                              }
                            ],
                            "api": {
                              "url": "$api_domain/plugins/ucenter/role/add_new",
                              "method": "post",
                              "data":{
                                "parentOid":"${roleOid}",
                                "roleName":"${roleName}",
                                "allowBind":"${allowBind}"
                              },
                              "messages": {
                                "success": "角色添加成功",
                                "error": "角色添加失败"
                              },
                              "onSuccess": {
                                "type": "request",
                                "api": "YOUR_CRUD_API_ID"
                              }
                            },
                            "reload": ["YOUR_TABLE_COMPONENT_ID"]
                          }
                        }
                      },
                      {
                        "type": "button",
                        "label": "修改",
                        "actionType": "dialog",
                        "level": "info",
                        "size": "md",
                        "style": {
                          "margin": "5px"
                        },
                        "dialog": {
                          "title": "编辑角色",
                          "body": {
                            "type": "form",
                            "controls": [
                              {
                                "name": "roleName",
                                "label": "角色名称",
                                "type": "text",
                                "required": true
                              },
                              {
                                "name": "allowBind",
                                "label": "允许绑定的账户数量",
                                "type": "number",
                                "required": true
                              }
                            ],
                            "api": {
                              "url": "$api_domain/plugins/ucenter/role/modify/${roleOid}",
                              "method": "put",
                              "messages": {
                                "success": "角色更新成功",
                                "error": "角色更新失败"
                              }
                            }
                          }
                        }
                      },
                      {
                        "type": "button",
                        "label": "删除",
                        "actionType": "ajax",
                        "level": "danger",
                        "size": "md",
                        "style": {
                          "margin": "5px"
                        },
                        "confirmText": "确定要删除该角色吗？",
                        "api": {
                          "url": "$api_domain/plugins/ucenter/role/del/${roleOid}",
                          "method": "delete",
                          "messages": {
                            "success": "角色删除成功",
                            "error": "角色删除失败"
                          }
                        
                        },
                        "reload": ["YOUR_TABLE_COMPONENT_ID"]
                      }
                    ]
                  }
                ],
                "keyField": "roleOid"
              }
            ]
          }
        },
```
code here...
```

6. 操作步骤
7. 试试官网的table2，嵌套，嵌套的chileren数据还是第一层的，有什么解决方法，还是说用其他组件，比如，curd类的，有什么解决方案吗

![image](https://github.com/baidu/amis/assets/120307935/1d05fa9f-0e7a-42dc-a481-9e4cef788389)

请简单描述一下复现的操作步骤...

**Comment by wanglinfang2014** [comment]
问题已修复，原获取嵌套行数据的逻辑有问题，详情参考：https://github.com/baidu/amis/commit/16adbbd99353902a71df84c7db04e377bcd367ef#diff-3bc5e2ed0ca1bd67c009ac1d3a0f2a3ea8dea46ebef912b948ccf3fc5d76aa58
<img width="1236" alt="image" src="https://github.com/baidu/amis/assets/9547595/b6f1388a-b28b-4cf0-bb00-88e99c94b985">
