### ISSUE TITLE
amis-editor 5.6.1 版本编辑器加载 schema 后被转换成错误格式，造成编辑器无法正常显示

### ISSUE THREAD

**Issue by citynook** [baidu/amis#8366]
#### 描述问题：
下载官网的 2023.10.11 日的源码，编译运行编辑器时，【代码】窗口内被转换成错误的 schema 格式，造成编辑器无法正常使用。

这个问题在 amis-editor@5.5.0 版本以旧版本中没有发生，只在最新的 5.6.1 中发生。 

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/127393297/52d8ad28-a440-4e85-97a7-f95aa22f988f)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网的 2023.10.11 日的源码
amis：3.4.2
amis-editor: 5.6.1

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
官网的 2023.10.11 日的源码
amis：3.4.2
amis-editor: 5.6.1

3. 粘贴有问题的完整 `amis schema` 代码：
这段代码就是在启动编辑器后，加了一个编辑框和一个CRUD控件后，在【代码】窗口中生成的。
```
{
  "type": "page",
  "title": "新页面",
  "regions": [
    "body",
    "header"
  ],
  "body": [
    {
      "type": "input-text",
      "label": "文本",
      "name": "text",
      "id": "u:e2ae7064723c"
    },
    {
      "type": "crud",
      "syncLocation": false,
      "api": {
        "method": "get",
        "url": ""
      },
      "columns": [
        {
          "name": "id",
          "label": "ID",
          "type": "text",
          "id": "u:e6f59a01f1d8"
        },
        {
          "name": "engine",
          "label": "渲染引擎",
          "type": "text",
          "id": "u:bdccf1994b10"
        }
      ],
      "bulkActions": [],
      "itemActions": [],
      "id": "u:1c8a69ea7601"
    }
  ]
}
```

4. 操作步骤
4.1 下载官网 2023.10.11 日源码，修改 packages\amis-editor\examples\Editor.tsx 文件，在【编辑/预览】按钮后新增一个【重置】按钮。
```
              <div
                className={`header-action-btn primary'`}
                onClick={() => {
                  this.reset();
                }}
              >
                重置
              </div>
```

4.2 新增 reset 方法，方法中调用已有的 clearCache 方法，重置 schema
```
  reset = () => {
    this.clearCache();
  };
```

4.3 运行编辑器，将上面第3点中的 json 复制到【代码】窗口中，如下图所示：
![image](https://github.com/baidu/amis/assets/127393297/c247fb27-9f4a-4b12-9d14-4037c1527b4a)

4.4 点击【重置】按钮，此时【代码】窗口中的 schema 已经变成错误的格式。
![image](https://github.com/baidu/amis/assets/127393297/4f8bc958-ce79-4610-a9f9-83131e0c51e7)

**Comment by citynook** [comment]
@2betop 这可能是一个比较严重的bug，可以抽时间关注一下吗，重现很简单~~

**Comment by 2betop** [comment]
clearCache 是啥逻辑？

**Comment by citynook** [comment]
clearCache 是官网源码 packages\amis-editor\examples\Editor.tsx 中已有的方法，不是我新增的，详见下图：

![image](https://github.com/baidu/amis/assets/127393297/d06282d2-8ed7-4567-8e00-22e947ab78a1)

**Comment by 2betop** [comment]
https://github.com/baidu/amis/assets/2698393/318b34d4-238c-43bf-ac4b-d27a5f07345c

是不是这样操作？目前看来不能复现，直接在 amis 仓库上跑的

**Comment by citynook** [comment]
@2betop 我下载最新的代码再试下~

**Comment by citynook** [comment]
@2betop 我在今天 2023.10.13 日 下午 3 点下载了官网最新代码，发现此问题已经不再发生

我又再度测试了10.11日下载的源码，这个问题依旧存在。

应该是这两天修复的一些bug把这个问题也解决了，现在只能等发布新版本再测试下，如果没有问题再关闭 issue。

**Comment by citynook** [comment]
@2betop  请问 amis-edit 预计何时会发布新版本？

**Comment by citynook** [comment]
@2betop 请问今天能发布 editor 新版本吗，不然这个问题会一直将以前编辑的schema搞乱掉，无法正常编辑~

**Comment by citynook** [comment]
更新 amis-editor@5.6.2 后，问题依旧存在，准备下载最新的源码再测试下，暂时关闭此贴，若测试出问题再开新贴。

**Comment by voidjay** [comment]
我也有相同问题，已严重影响进度
