### ISSUE TITLE
pagination组件 修改默认展示条数 分页组件不展示

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#8373]
#### 描述问题：

在 "type": "crud"中的footerToolbar设置pagination ，分页组件不展示

#### 截图或视频：

<img width="787" alt="image" src="https://github.com/baidu/amis/assets/48573389/5e8a273a-2f1f-4f79-b2ef-1e7cdd83f639">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
 "type": "crud",
 "footerToolbar": [
                {
                    "type": "pagination",
                    "mode": "normal",
                    "perPage": 100,
                    "showPerPage": true,
                    "perPageAvailable": [
                      100,
                      50,
                      10
                    ],
                    "showPageInput": true,
                    "disabled": false
                  }
            ],
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
因为接口返回的数据不够 2 页？

**Comment by Liary0** [comment]
数据够的 总共三百多条数据，分页设置的每页展示100条

**Comment by 2betop** [comment]
接口返回 count 字段或者 total 字段了吗

**Comment by Liary0** [comment]
接口返回 total: 390 
设置默认条数我是这样配置的
 "defaultParams": {
                "perPage": 100
              },
使用分页组件我就把这个配置去掉了 替换成"footerToolbar": [
                {
                    "type": "pagination",
                    "mode": "normal",
                    "perPage": 100,
                    "showPerPage": true,
                    "perPageAvailable": [
                      100,
                      50,
                      10
                    ],
                    "showPageInput": true,
                    "disabled": false
                  }
            ],

**Comment by 2betop** [comment]
看起来可以
<img width="1223" alt="image" src="https://github.com/baidu/amis/assets/2698393/2a81d2c6-adda-4018-8966-ac516d521f3c">

**Comment by Liary0** [comment]
<img width="1099" alt="image" src="https://github.com/baidu/amis/assets/48573389/569f2799-9359-4092-8b08-543056c7ca2a">
是这个分页组件

**Comment by 2betop** [comment]
之前理解错了，是个 bug，下个版本修复一下

**Comment by Liary0** [comment]
那这个问题修复好之后我会收到通知吗 还是需要我去关注一下你们版本修复的说明

**Comment by 2betop** [comment]
代码合入就会 close 掉这个，月底发版本后就可用了，或者自行拿 master 编译，发版自己的版本
