### ISSUE TITLE
3.4.2版本，不支持连字符变量吗？

### ISSUE THREAD

**Issue by qzo123** [baidu/amis#8376]
#### 描述问题：
3.4.2版本连字符问题：
例如获取sessionStorage ${ss: user-token} 获取不到值，去掉连字符，修改成${ss: usertoken}就可以获取到；
2.xx的版本的时候连字符是可以正常使用的；
这个连字符的问题后续会兼容一下吗？希望看到回复一下。

**Comment by 2betop** [comment]
目前可以用转义可以支持

```json
{
  "type": "page",
  "title": "标题",
  "body": "Hello World! 先试试 ${ls:user\\-token} "
}
```

**Comment by 2betop** [comment]
等这个 pr 合入后 https://github.com/baidu/amis/pull/8385 可以通过 `${&['user-token']}` 获取

**Comment by qzo123** [comment]
> 等这个 pr 合入后 #8385 可以通过 `${&['user-token']}` 获取

好的，👌
