### ISSUE TITLE
使用自定义组件-React开发组件

### ISSUE THREAD

**Issue by leung0727** [baidu/amis#8382]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
前提：公司后台系统使用 amis 框架搭建，现如今的需求是我用 react 开发一个组件，把这个组件注册到公司后台系统中，然后 json 配置里面调用这个组件来实现具体功能
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
组件开发出来，不知道怎么注册到公司后台系统和调用该组件
#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
示例：开发完组件，进行注册和使用
```
 - 注册 -
Renderer({
  type: 'my-renderer',
  autoVar: true
})(CustomRenderer);

- 调用 -
{
  "type": "page",
  "title": "自定义组件示例",
  "body": {
    "type": "my-renderer",
    "tip": "简单示例"
  }
}
```

**Comment by 2betop** [comment]
是指如何扩充编辑器中？https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/editor#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8F%92%E4%BB%B6

**Comment by leung0727** [comment]
是可以这么理解，其实就是想在公司系统里面能像调用amis内置组件那样来调用我开发的自定义组件

**Comment by leung0727** [comment]
> 是指如何扩充编辑器中？https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/editor#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8F%92%E4%BB%B6

但是公司后台系统不是用 react 搭建的，不知道如何把组件代码融入进去，需要把组件进行打包编译成html文件吗，但打包编译完还能传递参数到组件内部吗

**Comment by 2betop** [comment]
我们外人更加不知道，需要靠你自己了

**Comment by leung0727** [comment]
好的，谢谢解答

**Comment by Lisa1787** [comment]
单独打包成sdk

**Comment by wubin1989** [comment]
> 单独打包成sdk

@Lisa1787 我用amis-widget-cli的react + ts 模板开发的自定义组件，单独打包出来的umd文件里面有require，浏览器会报require is not defined这样的报错，有什么解决办法吗？谢谢！
