### ISSUE TITLE
CRUD或者Table能否固定高度 超出固定高度部分可滚动查看内容 效果与autoFillHeight类似

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#8395]
#### 实现场景：
CRUD或者Table能否固定高度 超出固定高度部分可滚动查看内容 效果与autoFillHeight类似

![image](https://github.com/baidu/amis/assets/48573389/bef457d8-7ce2-4b25-bb14-ccd3241b0c3a)

**Comment by 2betop** [comment]
用 autoFillHeight + 设置 maxHeight 样式应该可以满足

**Comment by Liary0** [comment]
![image](https://github.com/baidu/amis/assets/48573389/b143a5e0-2dbc-4b47-99b8-3637d7015d0e)
没有出现预想的效果

**Comment by 2betop** [comment]
试试这样

```
autoFillHeight: true,
tableContentClassName: 'max-h-96',
```

**Comment by Liary0** [comment]
可以
