### ISSUE TITLE
通过import导入样式, 为啥在编译是报Unexcepted character '@'

### ISSUE THREAD

**Issue by wuxin2014** [baidu/amis#84]
import * as React from 'react'
import { render } from  'react-dom'
import Hello from './page/Hello'

import 'amis/lib/themes/default.css'
import './css/index.css'

render(<Hello />, document.getElementById('root'))

![image](https://user-images.githubusercontent.com/6781980/59484079-f7844e00-8ea2-11e9-9b84-b42ebc506ffe.png)

**Comment by 2betop** [comment]
you may need an appropriate loader to handle this file type.

**Comment by 2betop** [comment]
跟 amis 无关，先关了。你需要一个 css loader

**Comment by wuxin2014** [comment]
明明有配置css-loader

{
    test: /\.css$/,
    use: ['style-loader', 'css-loader'],
  },
