### ISSUE TITLE
How to access amis form store from react

### ISSUE THREAD

**Issue by abasse** [baidu/amis#8410]
How can I access the form store from a custom react component or amis form component? Not only the individual field.

BTW. I use amis with react, similar to amis admin (https://github.com/iceqing/react-amis-admin).

Thx.

**Comment by 2betop** [comment]
If your custom component is placed inside a form, you can access the form store by `this.props.formStore`

**Comment by abasse** [comment]
Thanks. Unfortunately my component sits in the toolbar section of the page. Is there a way to access from there?

**Comment by abasse** [comment]
So still open.

**Comment by 2betop** [comment]
In this case, you should use `Scoped` context.

https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react#%E7%BB%84%E4%BB%B6%E9%97%B4%E9%80%9A%E4%BF%A1

```tsx
import React from 'react';
import {Renderer, ScopedContext} from 'amis';
@Renderer({
  type: 'my-renderer'
})
export class CustomRenderer extends React.Component {
  static contextType = ScopedContext;

  constructor() {
    const scoped = this.context;
    scoped.registerComponent(this);
  }

  componentWillUnmount() {
    const scoped = this.context;
    scoped.unRegisterComponent(this);
  }

  doSomeThing() {
     //. {type: 'form', body: [], id: 'theForm'}
     const form = this.context.getComponentById('theForm');
     console.log(form.props.formStore)
  }
}
```

**Comment by abasse** [comment]
Thx
