### ISSUE TITLE
希望CRUD及Table等支持表格树的控件能提供懒加载功能

### ISSUE THREAD

**Issue by citynook** [baidu/amis#8411]
#### 是否关联于某个问题吗：
无

#### 预期的解决方案：
现在的表格树只能一次性加载表格树所有节点的数据并显示，无法在点击树节点时才懒加载下一阶的数据。

当前的应用场景希望页面初始化时，只加载第一阶的数据，有下阶数据的表格树节点显示为+，点击后展开并调用API获取下一阶数据并展示，实现懒加载。
在企业系统中，很多资料数据量比较大，若按现有的方式一次性加载全部数据，性能方面会受到很大影响，并且大部分数据可能是不需要展开及关注的。需要看哪些资料，就自行展开哪层的节点，更加灵活方便。

对一些大型企业应用来说，表格树应用场景非常多，能提供表格树的懒加载功能，可以极大推动企业使用amis-editor来快速构建应用。

#### 其他可接受方案：
无

#### 任何附加信息：
无

**Comment by EvanZheng11** [comment]
+1
