### ISSUE TITLE
编辑器使用antd主题有些样式不正确

### ISSUE THREAD

**Issue by NewNewKing** [baidu/amis#8413]
#### 描述问题：
如图1所示，我的编辑器使用的主题是antd的，当我想要切换按钮样式时，发现编辑器提供的按钮样式都不正确，查看代码后得知，应该是源码中写死了cxd前缀

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/20492226/b8bc02cd-256c-4d5b-bfa2-15ab5eef0184)

![image](https://github.com/baidu/amis/assets/20492226/cf5376b2-8107-429f-8a9b-067b7f627f5b)

![image](https://github.com/baidu/amis/assets/20492226/f2a1d51d-efcb-40ea-8eae-32f6f9cbea0e)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by laosandegudai** [comment]
设置antd主题后，在编辑器中样式设置中会出现部分控件异常。

`import 'amis/lib/themes/antd.css';`
`setDefaultTheme('antd');`
`        <Editor
            onChange={actionChange}
            value={pageSchema}
            theme='antd'
        />`

![image](https://github.com/baidu/amis/assets/17979159/cfccaffd-19e9-460b-a607-ca7d0bab7f18)
![image](https://github.com/baidu/amis/assets/17979159/f92069b5-0851-411c-9e46-31d72ad0f2bb)
我在官方的示例中发现这个控件  是以  theme 开头的class，目前不知道如何设置。
