### ISSUE TITLE
[新特性]建议为env.fetcher增加额外的store参数

### ISSUE THREAD

**Issue by entropy-cloud** [baidu/amis#8426]
目前AMIS虽然已经支持事件编排，但是大量的调用还是只支持配置ajax请求，比如CRUD控件的initApi和api配置等。可以通过定制env.fetcher的方式拦截ajax请求，把它转化为调用本地js函数。通过这种方式我们可以将只支持ajax调用的CRUD组件改造成一个可以获取局部数据，并提交修改到本地store的控件。

另外ajax的处理函数会接收到form提交的数据，目前似乎没有很方便的方式直接获取到form上经过验证的待提交数据。

我们的需求是编辑一个复杂的主子表结构，列表中的每一行必须要弹出表单来进行编辑，而且弹出的表单还是一个多tab页的嵌套主子表，所以无法用CRUD组件的quickEdit机制来处理，也无法使用现有的input-table控件。但是，只要允许拦截ajax调用到本地函数，就可以在js函数中直接操作store进行处理。

#### 预期的解决方案：
希望env.fetcher调用增加参数，传入调用时对应的store。例如 env.fetcher(options, props.store)。
虽然可以从全局的amisScoped来按照名称获取store。但是这个scoped是从根开始向下拿，我们现在把界面分解了，当前的page不知道自己如何通过scoped拿到，所以必须要通过相对坐标拿store。

#### 参考
env.fetcher = (options, store)=>{
   if(options.url.startsWith("action://")){
        return page.getAction(options.url.substring("action://".length))(options, store);
   }
   return ajaxFetch(options);
}

**Comment by 2betop** [comment]
看起来配置 api 请求适配器可以做到 https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E6%8B%A6%E6%88%AA%E8%AF%B7%E6%B1%82

**Comment by 2betop** [comment]
发送适配器中，第二个参数 context 里面能拿到相关信息，同时 篡改 api.mockResponse 可以拦截后续的请求，看起来满足需求了，有问题再开

**Comment by entropy-cloud** [comment]
@2betop 多谢回复。但是我的需求实际上是使用统一的方式来实现ajax拦截，而适配器的方式是在每个调用处都要处理。在整个amis的响应处理体系中，事件处理函数都是可以拿到context的，只有ajax fetcher拿不到，这产生了结构上的不一致性。 如果是相对复杂的代码，在json格式的amis页面中就会导致大量的代码重复。

**Comment by 2betop** [comment]
@entropy-cloud 一定要拿 store 吗？store 应该是拿不了，但是请求发送前的上下文数据倒是可以打通给全局适配器

**Comment by entropy-cloud** [comment]
多谢回复。这和我希望的使用场景有关。我不确定如果没有store信息，如何能够将CRUD控件从支持远程调用模拟为将全部数据都保存到本地store中，然后一次性提交到后台。目前的CRUD控件是只支持远程ajax调用，而一般的Table控件没有办法通过弹出对话框的形式来更新行数据。本质上是希望传入环境对象，从而有一些amis引擎没有内置实现，但是又需要使用的功能可以被屏蔽在env.fetcher调用之中。
如果fetcher中能够拿到环境对象，那么我可以通过
{
   api: "action://mylib.myAction"
}
这种url的形式触发本地的函数，从而实现定制逻辑。
目前的情况是ajax调用在amis的体系中非常特殊，有些地方只有ajax接口，并没有其他的动作触发接口，没有其他方式统一拦截这些ajax调用，并且允许引入amis设计之外的定制逻辑。
