### ISSUE TITLE
CRUD 组件 数据嵌套显示异常

### ISSUE THREAD

**Issue by hyzx86** [baidu/amis#8453]
amis verision

amis 3.4.3
amis-core 3.4.3
amis-editor 5.6.1
amis-editor-core 5.6.1

第一层第二层正常，第三层会直接显示成第一层~

![image](https://github.com/baidu/amis/assets/15613121/b7ec0e7d-d812-4d85-8e1f-bc62b18d9636)

**Comment by 2betop** [comment]
不能复现，能否提供 数据返回脱敏数据？

**Comment by 2betop** [comment]
<img width="895" alt="image" src="https://github.com/baidu/amis/assets/2698393/8ed12287-060e-4311-9e04-22f0b62c80a7">

**Comment by hyzx86** [comment]
稍等 啊， 等会我整个 json 或者文件上来

**Comment by 2betop** [comment]
reminder

**Comment by hyzx86** [comment]
官网的demo 是最新版本吗？  我在官网修改 居然没有复现。。 比如这里
https://aisuda.bce.baidu.com/amis/zh-CN/components/crud

**Comment by 2betop** [comment]
这个是最新的 https://baidu.github.io/amis/zh-CN/components/crud

**Comment by 2betop** [comment]
暂时先关了，有问题再 reOpen

**Comment by hyzx86** [comment]
好的，我昨天模拟的东西找不到了- - 后面复现了再提
