### ISSUE TITLE
tinymce/plugins/help/js/i18n/keynav/zh_CN 找不到

### ISSUE THREAD

**Issue by Jarod-Xie** [baidu/amis#8454]
#### 描述问题：

本地运行，打开富文本编辑器文档，报错

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/27668637/870bcc56-d360-4b23-9c5f-07ac043f6e51)

#### 如何复现（请务必完整填写下面内容）：
拉取最新代码
执行 `npm i --legacy-peer-deps`,  `npm start`,
然后 打开 http://localhost:8888/zh-CN/components/form/input-rich-text

**Comment by 2betop** [comment]
去 node_modules 目录里面看这个文件是否存在，如果不存在，那应该是 tinymce版本问题，尝试锁定版本。如果存在，那应该就是 @types/tinymce 的版本问题

**Comment by nwind** [comment]
没复现

**Comment by nwind** [comment]
删了 node_modules 再试试，有问题再开
