### ISSUE TITLE
download下载文件，请求正常返回，报错should have content-disposition（实际有返回）

### ISSUE THREAD

**Issue by liweiye-2021** [baidu/amis#8456]
![image](https://github.com/baidu/amis/assets/17706417/c8aed74a-ffb5-47d8-9812-34e24fb37722)
将请求URL直接贴在浏览器访问可以正常下载文件

JSON相关配置：
{
      "type": "action",
      "label": "导出",
      "id": "u:442fad4b1771",
      "actionType": "download",
      "align": "right",
      "api": "http://test.ubssdic.com:9200/yfdw-biz-position/XXXXX"
    }

Java后端接口相关代码：
            response.setContentType("application/octet-stream");
            response.setHeader("Content-Disposition", "attachment;filename=" + URLEncoder.encode((fileName + ""), "UTF-8"));
            ServletOutputStream os = response.getOutputStream();
            os.write(excelTemplate.getResultByte());
            os.close();

**Comment by nwind** [comment]
大概是自己实现的 fetcher 漏了 attachmentAdpator，参考一下 https://github.com/baidu/amis/blob/master/examples/embed.tsx#L216
