### ISSUE TITLE
配置了 onBuildPanels方法 第一次点击不生效

### ISSUE THREAD

**Issue by ityue** [baidu/amis#8482]
#### 描述问题：
配置了 onBuildPanels方法 第一次点击 看配置面板的数据变了，但显示没有更新，需要点击其他处在回来点击才可以。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm 引用的amis

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新版本
3. 粘贴有问题的完整 `amis schema` 代码：
```
onBuildPanels={(event) => {
          let pulginType = event.context.schema.type;
          if (pulginType == 'button') {
            let panel = event.context.info.plugin.panelBodyCreator(
              event.context
            );
            panel.tabs[0].body[0].activeKey.push('自定义');
          }
}
}
```

4. 操作步骤
1、使用onBuildPanels扩展配置
2、判断类型为button
3、增加自定义

**Comment by 2betop** [comment]
onBuildPanels 是构建 panel，但是你并没有改变 panel。应该是把 panels 数组将旧的移除，插入新的。而且不是构建完 panel 后去修改 schema，而不是构建前就处理好

**Comment by ityue** [comment]
感谢回复，多谢~
