### ISSUE TITLE
点击原生Html组件加载amis dialog弹框，加载成功后amis弹框关闭报错

### ISSUE THREAD

**Issue by taohq** [baidu/amis#8483]
1、使用SDK方式
2、在index.html页面渲染amis
3、页面右上角有个修改密码的按钮（使用tpl加载原生的html元素,代码见图）
![image](https://github.com/baidu/amis/assets/28134649/e9597486-5954-4e90-bd70-ad12bc342153)

4、点击这个按钮弹出amis dialog弹框（代码见图）
![image](https://github.com/baidu/amis/assets/28134649/9dafa211-8484-45e3-b5b5-cde3fc3d6017)

**问题：弹框弹出后无法关闭，console中报错（见图）**
![image](https://github.com/baidu/amis/assets/28134649/eb6ee7ba-9aea-4d6c-8f84-58a1e78eed87)

**Comment by 2betop** [comment]
dialg 当更节点渲染，需要外层控制弹出状态。props 要包含 `show: boolean` 、`onHide: () => void`和 `onConfirm: (values) => void;`

**Comment by taohq** [comment]
没太理解，可以给个代码示例吗？

**Comment by taohq** [comment]
> dialg 当更节点渲染，需要外层控制弹出状态。props 要包含 `show: boolean` 、`onHide: () => void`和 `onConfirm: (values) => void;`

没太理解  可以给个代码示例吗

**Comment by 2betop** [comment]
```js
const instance = amis.embed('#amisDialogContainer', amisDialogConfig, {
  show: true,
  onHide: () => {
    instance.unmount();
  },
  onConfirm: values => {
    console.log(values);
  }
});
```

**Comment by taohq** [comment]
还是不行，一样的错，我把代码贴上来您帮忙看下
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <link
      rel="stylesheet"
      title="default"
      href="sdk/sdk.css"
    />
    <link rel="stylesheet" href="sdk/helper.css" />
    <link rel="stylesheet" href="./css/dropDownStyle.min.css" />
    <link
      rel="stylesheet"
      href="sdk/iconfont.css"
    />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <script src="sdk/sdk.js"></script>
    <script src="https://unpkg.com/vue@2"></script>
    <script src="https://unpkg.com/history@4.10.1/umd/history.js"></script>
    <script src="js/jquery-3.5.1.min.js"></script>
    <script src="js/util.js"></script>
    <script src="pages/common.js"></script>
    <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    <style>
      html,
      body,
      .app-wrapper {
        position: relative;
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="root" class="app-wrapper"></div>
    <div id="amisDialogContainer"></div>
    <script>
        //用户权限信息
        let userPerms;

      (function () {
        let amis = amisRequire('amis/embed');
        let amisLib = amisRequire('amis');
        const match = amisRequire('path-to-regexp').match;

        // 如果想用 browserHistory 请切换下这处代码, 其他不用变
        // const history = History.createBrowserHistory();
        const history = History.createHashHistory();

        const app = {
          type: 'app',
          brandName: '',
          logo: '/public/zllogo.webp',
          header: {
            type: 'tpl',
            inline: false,
            className: 'w-full',
            tpl: '<div class="flex justify-between"><div style="line-height:50px;"></div><div class="customized-drop-down-boxes"><ul><li class="drop-down"><a class="menu" href="#"><img src="./images/user.webp"><div id="userLoginName">这里是ID</div><img src="./images/edit.webp"></a><ul class="drop-down-content"><li><a href="#"><img src="./images/password.webp"><span id="openDialogButton">修改密码</span></a></li><li><a class="dividing-line" href="#" onclick="logout()"><img src="./images/logout.webp"><span>退出登录</span></a></li></ul></li></ul></div></div>'
          },
          // footer: '<div class="p-2 text-center bg-light">底部区域</div>',
          // asideBefore: '<div class="p-2 text-center">菜单前面区域</div>',
          // asideAfter: '<div class="p-2 text-center">菜单后面区域</div>',
          //   api: 'pages/site.json'
            api: {
                url:'/manager/index/getMenus',
                adaptor: function (payload, response, api, context) {
                    userPerms = payload.data.permsMenu;
                    $("#userLoginName").text(payload.data.loginUserName);
                    payload.data = payload.data.amisMenu;
                    return payload;
                }
            }
        };

        

        function isCurrentUrl(to, ctx) {
          if (!to) {
            return false;
          }
          const pathname = history.location.pathname;
          const link = to;

          if (!~link.indexOf('http') && ~link.indexOf(':')) {
            let strict = ctx && ctx.strict;
            return match(link, {
              decode: decodeURIComponent,
              strict: typeof strict !== 'undefined' ? strict : true
            })(pathname);
          }

          return decodeURI(pathname) === link;
        }
        let amisInstance = amis.embed(
          '#root',
          app,
          {
            location: history.location,
            data: {
              // 全局数据，是受控的数据
            },
            context: {
              // 全局上下文数据, 非受控的数据，无论哪一层都能获取到，包括弹窗自定义数据映射后都能获取到。
              // 可以用来放一下全局配置等。比如 API_HOST, 这样页面配置里面可以通过 ${API_HOST} 来获取到。
              API_HOST: 'http://localhost:8080/manager'
            }
          },
          {
            // watchRouteChange: fn => {
            //   return history.listen(fn);
            // },
            updateLocation: (location, replace) => {
              if (location === 'goBack') {
                return history.goBack();
              } else if (
                (!/^https?\:\/\//.test(location) &&
                  location ===
                    history.location.pathname + history.location.search) ||
                location === history.location.href
              ) {
                // 目标地址和当前地址一样，不处理，免得重复刷新
                return;
              } else if (/^https?\:\/\//.test(location) || !history) {
                return (window.location.href = location);
              }

              history[replace ? 'replace' : 'push'](location);
            },
            // 全局响应处理器
            responseAdaptor(api, payload, query, request, response){
                if(payload.status==10040 || payload.status==10021 || payload.status==10051){
                    //TODO 多次弹窗问题
                    amisLib.toast.error(payload.msg);
                    setTimeout(function (){
                        toLogin();
                    },1000);
                }
                return payload
            },
            jumpTo: (to, action) => {
              if (to === 'goBack') {
                return history.goBack();
              }


              if (isCurrentUrl(to)) {
                return;
              }

              if (action && action.actionType === 'url') {
                action.blank === false
                  ? (window.location.href = to)
                  : window.open(to, '_blank');
                return;
              } else if (action && action.blank) {
                window.open(to, '_blank');
                return;
              }

              if (/^https?:\/\//.test(to)) {
                window.location.href = to;
              } else if (
                (!/^https?\:\/\//.test(to) &&
                  to === history.pathname + history.location.search) ||
                to === history.location.href
              ) {
                // do nothing
              } else {
                history.push(to);
              }
            },
            isCurrentUrl: isCurrentUrl,
            theme: 'cxd'
          }
        );

        history.listen(state => {
          amisInstance.updateProps({
            location: state.location || state
          });
        });
      })();

    </script>

    <script>
          let amis2 = amisRequire('amis/embed');

          var amisDialogConfig = {
              id:"dialogAbc",
              type: "dialog",
              title: "修改密码",
              showCloseButton:true,
              actions: [
                  {
                      "type": "button",
                      "actionType": "close",
                      "label": "取消",
                      "close":true
                  },
                  {
                      "label": "确认",
                      "actionType": "submit",
                      "primary": true,
                      "close":true,
                      "type": "button",
                      "api": "/manager/userLogin/updatePwd"
                  }
              ],
              body: {
                  "type": "form",
                  "body": [
                      {
                          "type": "input-password",
                          "name": "oldPwd",
                          "required": true,
                          "label": "原密码",
                          "placeholder": "请输入原密码"
                      },
                      {
                          "type": "input-password",
                          "name": "pwd",
                          "label": "新密码",
                          "required": true,
                          "placeholder": "请输入新密码"
                      },
                      {
                          "type": "input-password",
                          "name": "confirmPwd",
                          "label": "确认密码",
                          "required": true,
                          "placeholder": "请再次输入新密码"
                      }
                  ]
              }
          };

          document.getElementById("openDialogButton").addEventListener("click", function() {
            const instance = amis2.embed('#amisDialogContainer', amisDialogConfig, {
              show: true,
              onHide: () => {
                instance.unmount();
              },
              onConfirm: values => {
                console.log(values);
              }
            });
          });
    </script>


  </body>
</html>
`

**Comment by taohq** [comment]
还是不行，一样的错。我把代码贴上来您帮忙看下

`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <link
      rel="stylesheet"
      title="default"
      href="sdk/sdk.css"
    />
    <link rel="stylesheet" href="sdk/helper.css" />
    <link rel="stylesheet" href="./css/dropDownStyle.min.css" />
    <link
      rel="stylesheet"
      href="sdk/iconfont.css"
    />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <script src="sdk/sdk.js"></script>
    <script src="https://unpkg.com/vue@2"></script>
    <script src="https://unpkg.com/history@4.10.1/umd/history.js"></script>
    <script src="js/jquery-3.5.1.min.js"></script>
    <script src="js/util.js"></script>
    <script src="pages/common.js"></script>
    <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    <style>
      html,
      body,
      .app-wrapper {
        position: relative;
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="root" class="app-wrapper"></div>
    <div id="amisDialogContainer"></div>
    <script>
        //用户权限信息
        let userPerms;

      (function () {
        let amis = amisRequire('amis/embed');
        let amisLib = amisRequire('amis');
        const match = amisRequire('path-to-regexp').match;

        // 如果想用 browserHistory 请切换下这处代码, 其他不用变
        // const history = History.createBrowserHistory();
        const history = History.createHashHistory();

        const app = {
          type: 'app',
          brandName: '',
          logo: '/public/zllogo.webp',
          header: {
            type: 'tpl',
            inline: false,
            className: 'w-full',
            tpl: '<div class="flex justify-between"><div style="line-height:50px;"></div><div class="customized-drop-down-boxes"><ul><li class="drop-down"><a class="menu" href="#"><img src="./images/user.webp"><div id="userLoginName">这里是ID</div><img src="./images/edit.webp"></a><ul class="drop-down-content"><li><a href="#"><img src="./images/password.webp"><span id="openDialogButton">修改密码</span></a></li><li><a class="dividing-line" href="#" onclick="logout()"><img src="./images/logout.webp"><span>退出登录</span></a></li></ul></li></ul></div></div>'
          },
          // footer: '<div class="p-2 text-center bg-light">底部区域</div>',
          // asideBefore: '<div class="p-2 text-center">菜单前面区域</div>',
          // asideAfter: '<div class="p-2 text-center">菜单后面区域</div>',
          //   api: 'pages/site.json'
            api: {
                url:'/manager/index/getMenus',
                adaptor: function (payload, response, api, context) {
                    userPerms = payload.data.permsMenu;
                    $("#userLoginName").text(payload.data.loginUserName);
                    payload.data = payload.data.amisMenu;
                    return payload;
                }
            }
        };

        

        function isCurrentUrl(to, ctx) {
          if (!to) {
            return false;
          }
          const pathname = history.location.pathname;
          const link = to;

          if (!~link.indexOf('http') && ~link.indexOf(':')) {
            let strict = ctx && ctx.strict;
            return match(link, {
              decode: decodeURIComponent,
              strict: typeof strict !== 'undefined' ? strict : true
            })(pathname);
          }

          return decodeURI(pathname) === link;
        }
        let amisInstance = amis.embed(
          '#root',
          app,
          {
            location: history.location,
            data: {
              // 全局数据，是受控的数据
            },
            context: {
              // 全局上下文数据, 非受控的数据，无论哪一层都能获取到，包括弹窗自定义数据映射后都能获取到。
              // 可以用来放一下全局配置等。比如 API_HOST, 这样页面配置里面可以通过 ${API_HOST} 来获取到。
              API_HOST: 'http://localhost:8080/manager'
            }
          },
          {
            // watchRouteChange: fn => {
            //   return history.listen(fn);
            // },
            updateLocation: (location, replace) => {
              if (location === 'goBack') {
                return history.goBack();
              } else if (
                (!/^https?\:\/\//.test(location) &&
                  location ===
                    history.location.pathname + history.location.search) ||
                location === history.location.href
              ) {
                // 目标地址和当前地址一样，不处理，免得重复刷新
                return;
              } else if (/^https?\:\/\//.test(location) || !history) {
                return (window.location.href = location);
              }

              history[replace ? 'replace' : 'push'](location);
            },
            // 全局响应处理器
            responseAdaptor(api, payload, query, request, response){
                if(payload.status==10040 || payload.status==10021 || payload.status==10051){
                    //TODO 多次弹窗问题
                    amisLib.toast.error(payload.msg);
                    setTimeout(function (){
                        toLogin();
                    },1000);
                }
                return payload
            },
            jumpTo: (to, action) => {
              if (to === 'goBack') {
                return history.goBack();
              }


              if (isCurrentUrl(to)) {
                return;
              }

              if (action && action.actionType === 'url') {
                action.blank === false
                  ? (window.location.href = to)
                  : window.open(to, '_blank');
                return;
              } else if (action && action.blank) {
                window.open(to, '_blank');
                return;
              }

              if (/^https?:\/\//.test(to)) {
                window.location.href = to;
              } else if (
                (!/^https?\:\/\//.test(to) &&
                  to === history.pathname + history.location.search) ||
                to === history.location.href
              ) {
                // do nothing
              } else {
                history.push(to);
              }
            },
            isCurrentUrl: isCurrentUrl,
            theme: 'cxd'
          }
        );

        history.listen(state => {
          amisInstance.updateProps({
            location: state.location || state
          });
        });
      })();

    </script>

    <script>
          let amis2 = amisRequire('amis/embed');

          var amisDialogConfig = {
              id:"dialogAbc",
              type: "dialog",
              title: "修改密码",
              showCloseButton:true,
              actions: [
                  {
                      "type": "button",
                      "actionType": "close",
                      "label": "取消",
                      "close":true
                  },
                  {
                      "label": "确认",
                      "actionType": "submit",
                      "primary": true,
                      "close":true,
                      "type": "button",
                      "api": "/manager/userLogin/updatePwd"
                  }
              ],
              body: {
                  "type": "form",
                  "body": [
                      {
                          "type": "input-password",
                          "name": "oldPwd",
                          "required": true,
                          "label": "原密码",
                          "placeholder": "请输入原密码"
                      },
                      {
                          "type": "input-password",
                          "name": "pwd",
                          "label": "新密码",
                          "required": true,
                          "placeholder": "请输入新密码"
                      },
                      {
                          "type": "input-password",
                          "name": "confirmPwd",
                          "label": "确认密码",
                          "required": true,
                          "placeholder": "请再次输入新密码"
                      }
                  ]
              }
          };

          document.getElementById("openDialogButton").addEventListener("click", function() {
            const instance = amis2.embed('#amisDialogContainer', amisDialogConfig, {
              show: true,
              onHide: () => {
                instance.unmount();
              },
              onConfirm: values => {
                console.log(values);
              }
            });
          });
    </script>


  </body>
</html>
`

**Comment by taohq** [comment]
> ```js
> const instance = amis.embed('#amisDialogContainer', amisDialogConfig, {
>   show: true,
>   onHide: () => {
>     instance.unmount();
>   },
>   onConfirm: values => {
>     console.log(values);
>   }
> });
> ```

还是不行，一样的错。我把代码贴上来您帮忙看下
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <link
      rel="stylesheet"
      title="default"
      href="sdk/sdk.css"
    />
    <link rel="stylesheet" href="sdk/helper.css" />
    <link rel="stylesheet" href="./css/dropDownStyle.min.css" />
    <link
      rel="stylesheet"
      href="sdk/iconfont.css"
    />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <script src="sdk/sdk.js"></script>
    <script src="https://unpkg.com/vue@2"></script>
    <script src="https://unpkg.com/history@4.10.1/umd/history.js"></script>
    <script src="js/jquery-3.5.1.min.js"></script>
    <script src="js/util.js"></script>
    <script src="pages/common.js"></script>
    <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    <style>
      html,
      body,
      .app-wrapper {
        position: relative;
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="root" class="app-wrapper"></div>
    <div id="amisDialogContainer"></div>
    <script>
        //用户权限信息
        let userPerms;

      (function () {
        let amis = amisRequire('amis/embed');
        let amisLib = amisRequire('amis');
        const match = amisRequire('path-to-regexp').match;

        // 如果想用 browserHistory 请切换下这处代码, 其他不用变
        // const history = History.createBrowserHistory();
        const history = History.createHashHistory();

        const app = {
          type: 'app',
          brandName: '',
          logo: '/public/zllogo.webp',
          header: {
            type: 'tpl',
            inline: false,
            className: 'w-full',
            tpl: '<div class="flex justify-between"><div style="line-height:50px;"></div><div class="customized-drop-down-boxes"><ul><li class="drop-down"><a class="menu" href="#"><img src="./images/user.webp"><div id="userLoginName">这里是ID</div><img src="./images/edit.webp"></a><ul class="drop-down-content"><li><a href="#"><img src="./images/password.webp"><span id="openDialogButton">修改密码</span></a></li><li><a class="dividing-line" href="#" onclick="logout()"><img src="./images/logout.webp"><span>退出登录</span></a></li></ul></li></ul></div></div>'
          },
          // footer: '<div class="p-2 text-center bg-light">底部区域</div>',
          // asideBefore: '<div class="p-2 text-center">菜单前面区域</div>',
          // asideAfter: '<div class="p-2 text-center">菜单后面区域</div>',
          //   api: 'pages/site.json'
            api: {
                url:'/manager/index/getMenus',
                adaptor: function (payload, response, api, context) {
                    userPerms = payload.data.permsMenu;
                    $("#userLoginName").text(payload.data.loginUserName);
                    payload.data = payload.data.amisMenu;
                    return payload;
                }
            }
        };

        

        function isCurrentUrl(to, ctx) {
          if (!to) {
            return false;
          }
          const pathname = history.location.pathname;
          const link = to;

          if (!~link.indexOf('http') && ~link.indexOf(':')) {
            let strict = ctx && ctx.strict;
            return match(link, {
              decode: decodeURIComponent,
              strict: typeof strict !== 'undefined' ? strict : true
            })(pathname);
          }

          return decodeURI(pathname) === link;
        }
        let amisInstance = amis.embed(
          '#root',
          app,
          {
            location: history.location,
            data: {
              // 全局数据，是受控的数据
            },
            context: {
              // 全局上下文数据, 非受控的数据，无论哪一层都能获取到，包括弹窗自定义数据映射后都能获取到。
              // 可以用来放一下全局配置等。比如 API_HOST, 这样页面配置里面可以通过 ${API_HOST} 来获取到。
              API_HOST: 'http://localhost:8080/manager'
            }
          },
          {
            // watchRouteChange: fn => {
            //   return history.listen(fn);
            // },
            updateLocation: (location, replace) => {
              if (location === 'goBack') {
                return history.goBack();
              } else if (
                (!/^https?\:\/\//.test(location) &&
                  location ===
                    history.location.pathname + history.location.search) ||
                location === history.location.href
              ) {
                // 目标地址和当前地址一样，不处理，免得重复刷新
                return;
              } else if (/^https?\:\/\//.test(location) || !history) {
                return (window.location.href = location);
              }

              history[replace ? 'replace' : 'push'](location);
            },
            // 全局响应处理器
            responseAdaptor(api, payload, query, request, response){
                if(payload.status==10040 || payload.status==10021 || payload.status==10051){
                    //TODO 多次弹窗问题
                    amisLib.toast.error(payload.msg);
                    setTimeout(function (){
                        toLogin();
                    },1000);
                }
                return payload
            },
            jumpTo: (to, action) => {
              if (to === 'goBack') {
                return history.goBack();
              }


              if (isCurrentUrl(to)) {
                return;
              }

              if (action && action.actionType === 'url') {
                action.blank === false
                  ? (window.location.href = to)
                  : window.open(to, '_blank');
                return;
              } else if (action && action.blank) {
                window.open(to, '_blank');
                return;
              }

              if (/^https?:\/\//.test(to)) {
                window.location.href = to;
              } else if (
                (!/^https?\:\/\//.test(to) &&
                  to === history.pathname + history.location.search) ||
                to === history.location.href
              ) {
                // do nothing
              } else {
                history.push(to);
              }
            },
            isCurrentUrl: isCurrentUrl,
            theme: 'cxd'
          }
        );

        history.listen(state => {
          amisInstance.updateProps({
            location: state.location || state
          });
        });
      })();

    </script>

    <script>
          let amis2 = amisRequire('amis/embed');

          var amisDialogConfig = {
              id:"dialogAbc",
              type: "dialog",
              title: "修改密码",
              showCloseButton:true,
              actions: [
                  {
                      "type": "button",
                      "actionType": "close",
                      "label": "取消",
                      "close":true
                  },
                  {
                      "label": "确认",
                      "actionType": "submit",
                      "primary": true,
                      "close":true,
                      "type": "button",
                      "api": "/manager/userLogin/updatePwd"
                  }
              ],
              body: {
                  "type": "form",
                  "body": [
                      {
                          "type": "input-password",
                          "name": "oldPwd",
                          "required": true,
                          "label": "原密码",
                          "placeholder": "请输入原密码"
                      },
                      {
                          "type": "input-password",
                          "name": "pwd",
                          "label": "新密码",
                          "required": true,
                          "placeholder": "请输入新密码"
                      },
                      {
                          "type": "input-password",
                          "name": "confirmPwd",
                          "label": "确认密码",
                          "required": true,
                          "placeholder": "请再次输入新密码"
                      }
                  ]
              }
          };

          document.getElementById("openDialogButton").addEventListener("click", function() {
            const instance = amis2.embed('#amisDialogContainer', amisDialogConfig, {
              show: true,
              onHide: () => {
                instance.unmount();
              },
              onConfirm: values => {
                console.log(values);
              }
            });
          });
    </script>


  </body>
</html>
`

**Comment by 2betop** [comment]
记错了，把 onHide 改成 onClose

**Comment by taohq** [comment]
> onClose

可以了，多谢多谢
