### ISSUE TITLE
文件名带空格时文件下载命名不正确

### ISSUE THREAD

**Issue by Miao0er** [baidu/amis#8488]
#### 描述问题：
文件下载接口，响应头返回

Content-Disposition: attachment;filename=1+-+%E5%89%AF%E6%9C%AC+%2811%29.doc
Content-Type: application/msword;charset=UTF-8

理论上下载的文件的名字应该是：“1-中国（11）.doc”
但实际上下载结果为：“1+-+中国（11）.doc”

这个空格没有被转出来，是为什么？

**Comment by nwind** [comment]
空格编码后应该是 %20 而不是 +
