### ISSUE TITLE
Select组件不支持labelInValue的模式吗？

### ISSUE THREAD

**Issue by blankzust** [baidu/amis#8489]
#### 是否关联于某个问题吗：
select组件貌似没有labelInValue的模式，但是这是种很常见的场景，即接口需要保存[{value: 11, label: 'ssss'}]这种格式的数据，回显的时候也是这个数据结构

#### 预期的解决方案：
支持labelInValue的模式

#### 其他可接受方案：
适配器转换也可以接受，暂时不知道怎么写

**Comment by 2betop** [comment]
是指这个吧 https://aisuda.bce.baidu.com/amis/zh-CN/components/form/options#%E6%8B%BC%E6%8E%A5%E5%80%BC-joinvalues

**Comment by blankzust** [comment]
对的
