### ISSUE TITLE
crud 表格的顶部如果设置为固定表头，滚动到底部，和正常 inline 时候，上传的文件会不同步

### ISSUE THREAD

**Issue by hq5544** [baidu/amis#849]
crud 表格的顶部如果设置为固定表头，滚动到底部，和正常 inline 时候，上传的文件会不同步
![image](https://user-images.githubusercontent.com/10363393/90129581-791f8680-dd9b-11ea-95ab-321476f01db0.png)
![image](https://user-images.githubusercontent.com/10363393/90129594-80469480-dd9b-11ea-8aa4-826ecf7c886f.png)

**Comment by 2betop** [comment]
这目前没得版本，不开启固顶，或者别放 form 在 header 里面
