### ISSUE TITLE
amis renderSchema函数第三个参数env配置问题

### ISSUE THREAD

**Issue by wuxin2014** [baidu/amis#85]
看了amis-admin，是规定必须要用mobx-state-tree
![image](https://user-images.githubusercontent.com/6781980/59575894-ed0ac400-90ef-11e9-99ed-bcaa1279357c.png)

**Comment by 2betop** [comment]
是的，里面数据是用 mst 管理的

**Comment by wuxin2014** [comment]
不用mst能配置吗？

**Comment by 2betop** [comment]
可以啊，这个栗子用 mst，但是你可以不用
