### ISSUE TITLE
弹窗获取不到弹窗外的组件

### ISSUE THREAD

**Issue by zmm1988** [baidu/amis#8502]
#### 描述问题：

编辑器的弹窗获取不到弹窗外的组件

#### 截图或视频：

![1698234631355](https://github.com/baidu/amis/assets/48378155/39645d4b-325f-4ec9-acd6-0249508a5b92)

#### 如何复现（请务必完整填写下面内容）：
![1698234911215](https://github.com/baidu/amis/assets/48378155/0f58b090-a757-42a8-a695-b97d53b4e761)
从这边新建的弹框获取不到弹窗以外的组件

1. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

"amis": "3.4.2",
"amis-core": "3.4.2",
"amis-formula": "3.4.2",
"amis-ui": "3.4.2",
"amis-editor": "5.6.1",
"amis-editor-core": "5.6.1",

**Comment by Icodezhan** [comment]
可以先随便选一个弹窗内的组件，然后改json源码中的id，把id改成弹窗外的组件的id即可

**Comment by wibetter** [comment]
@Icodezhan 感谢反馈，确实是个问题。

**Comment by wibetter** [comment]
@zmm1988 目标组件 可以选择「输入组件id」，手动录入当前页面任何层级中的组件元素ID：
<img width="877" alt="image" src="https://github.com/baidu/amis/assets/11958920/c4582c80-9eb2-4b5a-b3f0-49c53fe44937">
<img width="868" alt="image" src="https://github.com/baidu/amis/assets/11958920/93918049-09a9-44ce-b93d-d45813186e29">
