### ISSUE TITLE
怎么在英文版中修改默认的中文弹窗确认显示内容

### ISSUE THREAD

**Issue by haohello** [baidu/amis#8503]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
请参考以下截屏， 我使用的是英文版本，在props中设置了locale为 en-US, 因为我使用的是react， 也引用了 import 'amis-ui/lib/locale/en-US'， 大部分地方英文显示都是正常的，但是在crud操作中的弹窗删除确认窗口中的按钮却显示的是中文内容， 请问怎么修改这两个按钮中的文字内容呢？
#### 截图或视频：
![image](https://github.com/baidu/amis/assets/134774/9f53a311-740f-4bdf-91fb-bf23150a22f9)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
通过react使用的
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
"amis": "^3.4.2",
"amis-ui": "^3.4.2",
4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
https://github.com/baidu/amis/blob/master/examples/embed.tsx#L275-L286

可能你需要提前渲染这两个组件，指定语言。如果没有提前渲染，内部是自动渲染到 document.body 里面，那个时候可能没有语言信息

**Comment by 2betop** [comment]
无法复现，先关了，有问题再开，猜测是上面说的问题

<img width="1446" alt="image" src="https://github.com/baidu/amis/assets/2698393/38e72cab-9527-4e5b-9d71-95d9b8322169">
