### ISSUE TITLE
【严重】-AMIS编辑器选中[增删改查]组件后页面会卡死

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#8523]
#### 描述问题：

AMIS编辑器选中[增删改查]组件后页面会卡死

#### 截图或视频：

https://github.com/baidu/amis/assets/45064164/73234d68-3bee-4887-9a8a-a8ad6a85dd5a

![2023-10-27_111551](https://github.com/baidu/amis/assets/45064164/c9bafb93-9a29-4708-bd9c-6c4afdb9442b)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
```
截止此时此刻master分支最新代码
```

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by Icodezhan** [comment]
随便一个增删改查组件100%触发， @2betop @wibetter

**Comment by 2betop** [comment]
amis 版本不对？

**Comment by 2betop** [comment]
怀疑你那用的是此合入之前的 amis 版本 https://github.com/baidu/amis/pull/8210/files

**Comment by Icodezhan** [comment]
> amis 版本不对？

不是哦，我用的是截止现在。master分支最新的代码，就你刚刚几十分钟前还提交代码的最新的master分支代码呀

**Comment by Icodezhan** [comment]
> 怀疑你那用的是此合入之前的 amis 版本 https://github.com/baidu/amis/pull/8210/files

**Comment by Icodezhan** [comment]
> 怀疑你那用的是此合入之前的 amis 版本 https://github.com/baidu/amis/pull/8210/files

就完全是现在master分支最新代码，直接拉下来，然后启动项目，进入编辑器拖一个增删改查，然后选中增删改查组件，就会卡死了

**Comment by Icodezhan** [comment]
> amis 版本不对？

你用的内网版本无法复现吗？你试试用现在这个master分支试试

**Comment by 2betop** [comment]
列可以选，crud 不能点选，点选有个死循环，在查原因

**Comment by Icodezhan** [comment]
> 列可以选，crud 不能点选，点选有个死循环，在查原因

嗯，列是可以点选，但不能选中【增删改查】层级，会卡死

**Comment by 2betop** [comment]
感谢反馈，fixed
