### ISSUE TITLE
crud定制分页参数: 如何将"page"替换为"跳过n条数据"

### ISSUE THREAD

**Issue by wakuflair** [baidu/amis#853]
后端的分页api接口接收的不是page参数, 而是`skipCount`, 即"需要跳过的数据条数".
其实就是一个简单的计算: `skipCount = (page  - 1) * perPage`
我想在`requestAdaptor`中做该计算,  但是不知道如何能取到`page`和`perPage`的值:

``` javascript
                "requestAdaptor": function (api) {
                    return {
                        data: {
                            skipCount: (api.data.page - 1) * api.data.perPage,    // 无法取到`api.data.page`和`api.data.perPage`
                            // 配置其它参数
                        }
                    }
                },
```

我debug了一下, 好像`page`和`perPage`并不存在于data中, 而是直接拼接在了url后面.
那么如何能取得它们呢? 谢谢.

**Comment by RickCole21** [comment]
如果默认使用get请求方式，就会拼接在url上，你可以换成post，data中就有了

或者自己解析地址栏参数，具体方法可以先自己查一下

**Comment by wakuflair** [comment]
@RickCole21 谢谢你的回答!

我也发现get没有api.data, 只有post才有. 但是因为后端限制, 我没法更改请求方式.

请问能在get中也保留data数据吗? 这样可以让使用者有机会在调用前对data做一些调整, 也更符合`requestAdaptor`的存在的意义.

我现在用了一种hack的办法: 先使用post, 然后在`requestAdaptor`中处理完api.data后, 再将method改为get

``` javascript
api": {
                "url": "/api/app/book",
                "method": "post",      // 临时设置为post, 目的是让 requestAdaptor能取到api.data
                "requestAdaptor": function (api) {
                    return {
                        ...api,
                        method: "get",  // 再改为真正的get
                        data: {
                            skipCount: (api.data.page - 1) * api.data.perPage,    // 这里能使用api.data.page和perPage
                            maxResultCount: api.data.perPage,
                        }
                    };
                },
```

你能看到, 这种方法很丑陋, 也不容易看懂.
所以我想最好的解决方法是让get方法也保留api.data.

**Comment by 2betop** [comment]
新版本 api.context 能够拿到原始上下文数据，另外这有个类似的文档说明

`/api/mock2/sample?limit=${perPage}&offset=${(page - 1) * perPage}`

这个问题先关了，有问题再开
