### ISSUE TITLE
3.4.0版本 . input-number 组件 , blur事件bug, 取值, 不完整,缺失 

### ISSUE THREAD

**Issue by tangtangsara** [baidu/amis#8534]
3.4.0版本 . input-number 组件 , blur事件, bean.classId 取值, 不完整,缺失
例如 bean.classId 填写的是 12345,  blur ajax发的请求是   "/class-promotion/blur.do?content=1"
将 input-number 改为 input-text 就没问题 

  {
        "type": "input-number",
        "name": "bean.classId",
        "visibleOn": "true",
        "required": true,
        "validationErrors": {
            "isRequired": "课程id是必填项,不能为空"
        },
        "onEvent": {
            "blur": {
                "actions": [
                    {
                        "actionType": "ajax",
                        "args": {
                            "api": {
                                "url": "/class-promotion/blur.do?content=\${bean.classId}",
                                "method": "get"
                            },
                            "messages": {
                                "success": "",
                                "failed": "没查询到相关信息，请确认您填写的无误"
                            },
                            "age": 18
                        }
                    },
                    {
                        "actionType": "setValue",
                        "componentId": "className",
                        "args": {
                            "value": "\${event.data.className}"
                        }
                    },
                    {
                        "actionType": "setValue",
                        "componentId": "teacherName",
                        "args": {
                            "value": "\${event.data.teacherName}"
                        }
                    },
                    {
                        "actionType": "setValue",
                        "componentId": "bean.teacherId",
                        "args": {
                            "value": "\${event.data.teacherId}"
                        }
                    }
                ]
            }
        }

**Comment by wibetter** [comment]
@tangtangsara  目前新版已无此问题，请升级到最新版：
<img width="1268" alt="image" src="https://github.com/baidu/amis/assets/11958920/351753cb-7dd1-4e1c-bca5-19dfddd7d9cc">
