### ISSUE TITLE
post请求中，在requestApater里操作api，api里的data和post的data是一回事吗

### ISSUE THREAD

**Issue by qinaidetonggege** [baidu/amis#854]

**Comment by RickCole21** [comment]
是

**Comment by qinaidetonggege** [comment]
`"method": "post",
                                                                "dataType": "form",
                                                                "requestAdaptor": "function a(api) {let spuIdList = api.data.spuId.split(',');for(let item in spuIdList){ spuIdList[item] = spuIdList[item].substring(0,spuIdList[item].indexOf('\-'));}let spuIdString = spuIdList.join(','); return {...api,data: { ...api.data, spuId: spuIdString }};} a(api); console.log('api',a(api)); ",
                                                                "url": "/api/spu/getChannelNoBySpuIds",
                                                                "data":{
                                                                    "spuId":"${spuPicker}"
                                                                }`
spuPicker是picker的name，默认取picker的valueField

**Comment by RickCole21** [comment]
你的适配器写的有问题，字符串形式是需要执行后 return 出去东西的，你现在这种没任何效果，你再看看文档吧：
https://baidu.gitee.io/amis/docs/types/api#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E9%80%82%E9%85%8D%E5%99%A8

**Comment by RickCole21** [comment]
https://github.com/baidu/amis/blob/master/src/utils/api.ts#L121

实现在这里，方便理解

**Comment by qinaidetonggege** [comment]
> 你的适配器写的有问题，字符串形式是需要执行后 return 出去东西的，你现在这种没任何效果，你再看看文档吧：
> https://baidu.gitee.io/amis/docs/types/api#%E9%85%8D%E7%BD%AE%E8%AF%B7%E6%B1%82%E9%80%82%E9%85%8D%E5%99%A8

想知道怎么return呢，源码一时半会看不懂…

**Comment by qinaidetonggege** [comment]
知道了
`"requestAdaptor": "function a(api) {let spuIdList = api.data.spu.split(',');for(let item in spuIdList){ spuIdList[item] = spuIdList[item].substring(0,spuIdList[item].indexOf('\-'));} let spuIdString = spuIdList.join(','); return spuIdString;} a(api); return { ...api, data: { ...api.data, spuId: a(api) }};",`

要在函数外面return你要添加的值，唉哭了。个人感觉文档可以写的明确一点（小声波波

**Comment by RickCole21** [comment]
这我是在不知道咋明确了，要不你提个pr那，我相信以你们的角度写出来可能更适合理解😜

**Comment by qinaidetonggege** [comment]
`requestAdaptor: function (api) {
      // 操作你想操作的。
    }
// 一定要return！不然一顿操作猛如虎
return {
        ...api,
        data: {
          ...api.data, // 获取暴露的 api 中的 data 变量
          foo: 'bar' // 新添加数据
        }
      };
`

**Comment by RickCole21** [comment]
ok
