### ISSUE TITLE
按照官网文档搭建 amis 开发环境, 运行示例 case 的时候报错

### ISSUE THREAD

**Issue by luoquanquan** [baidu/amis#855]
#### 描述问题：

按照官网文档执行示例 case, 执行到 https://baidu.github.io/amis/docs/concepts/datascope-and-datachain#%E6%B7%BB%E5%8A%A0%E5%88%9D%E5%A7%8B%E5%8C%96%E6%8E%A5%E5%8F%A3 配置中加了 initApi 的时候, 会 alert 一个 error

#### 截图或视频：

![image](https://user-images.githubusercontent.com/17781641/90466261-eccae600-e143-11ea-8831-3a59a5ca2f82.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

npm

2. 粘贴有问题的完整 `amis schema` 代码：

```
import * as React from 'react';
import 'amis/lib/themes/default.css';
import { render as renderAmis } from 'amis';

export default class extends React.Component<any, any> {
  render() {
    return (
      renderAmis(
        {
          "type": "page",
          "initApi": "https://houtai.baidu.com/api/mock2/page/initData",
          "body": "date is ${date}"
        }
      )
    );
  }
}
```

3. 操作步骤

- 通过 cra 创建 react 项目
- npm i amis
- 运行示例代码

**Comment by luoquanquan** [comment]
控制台报错里边指出的文档地址应该是老版文档地址, 现在已经 404 了

![image](https://user-images.githubusercontent.com/17781641/90466483-81cddf00-e144-11ea-8ac3-99ddbbe74474.png)

**Comment by RickCole21** [comment]
嗯，需要自行实现`fetcher`，文档地址我一会更新下：https://baidu.gitee.io/amis/docs/start/getting-started#%E4%BD%BF%E7%94%A8

**Comment by RickCole21** [comment]
关了，有问题再开
