### ISSUE TITLE
最新的3.4.3版本，sdk方式，表单内，无法为项设置默认值

### ISSUE THREAD

**Issue by yqking** [baidu/amis#8559]
#### 描述问题：

最新的3.4.3版本，sdk方式，表单内，无法为项设置默认值

#### 复现代码： 
{
  "type": "form",
  "id": "u:066e591d75dc",
  "body": [
    {
      "type": "input-text",
      "name": "keywords",
      "addOn": {
        "type": "submit",
        "label": "搜索",
        "level": "primary",
        "icon": "fa fa-search pull-left",
        "id": "u:21c80ebe68e4"
      },
      "id": "u:84084c557494",
      "size": "lg",
      "value": "33333"
    }
  ],
  "debug": true,
  "wrapWithPanel": false
}
![设置默认值无效](https://github.com/baidu/amis/assets/15767890/67b02f50-a9db-4464-90f7-f62ee7d5f527)

**Comment by 2betop** [comment]
不能复现，是不是外部传了什么参导致的？

<img width="431" alt="image" src="https://github.com/baidu/amis/assets/2698393/4c126c28-2d80-4c1b-98f6-234150c5c727">

**Comment by yqking** [comment]
> 不能复现，是不是外部传了什么参导致的？
> 
> <img alt="image" width="431" src="https://user-images.githubusercontent.com/2698393/279235456-4c126c28-2d80-4c1b-98f6-234150c5c727.png">

我这边，同样的代码，在3.2.0没问题。在3.4.3版本就有问题

**Comment by yqking** [comment]
![3 43](https://github.com/baidu/amis/assets/15767890/3944004b-1461-454e-89df-6b7c08d17994)

**Comment by yqking** [comment]
![3 2 0](https://github.com/baidu/amis/assets/15767890/25fc2b28-ced3-4c68-a0d8-3f8d5e1bf089)

**Comment by yqking** [comment]
3.4.3版本，在预览页面，按ctrl+F5，强制刷新后，可以显示默认值，但是编辑，重新预览后，默认值又消失了。。。
3.4.3版本，我是昨天直接git拉下来编译运行的，没做任何调整。

**Comment by 2betop** [comment]
不是说 sdk 方式，你截图都是编辑器的，调用 sdk 之前都传了哪些参数，能否截个图

**Comment by yqking** [comment]
我不太明白传参是指的什么，能不能详细说下^_^。
3.4.3我用的是git上面项目的源码，下载后编译运行，显示的就是这种结果。
具体用处，是 弹窗（dialog）-->选择器（picker)-->表单(form)，同样的json 3.2.0版本没问题。

**Comment by yqking** [comment]
![Snipaste_2023-10-31_11-26-45](https://github.com/baidu/amis/assets/15767890/b1b2ebe5-296b-4a87-a74d-718cd3c84834)

**Comment by 2betop** [comment]
用 amis-admin 里面的代码将版本改成 3.4.3 也没复现

**Comment by 2betop** [comment]
<img width="387" alt="image" src="https://github.com/baidu/amis/assets/2698393/a02a789d-5264-4fe3-9172-330883ceac13">

<img width="1015" alt="image" src="https://github.com/baidu/amis/assets/2698393/a09fa195-f48f-4023-9142-efb44c1e4979">

**Comment by 2betop** [comment]
咦，编辑器里面如果不包在一个 page 里面，确实是有问题

**Comment by yqking** [comment]
确实，外部得再包一层，才会正常显示默认值

**Comment by yqking** [comment]
如下是项目中的片段，外面加了一层page，搜索框还是无法设置默认值。
###############
{
  "type": "page",
  "body": [
    {
      "type": "picker",
      "label": "项目名称",
      "name": "id",
      "id": "u:875a444018dd",
      "modalMode": "dialog",
      "multiple": false,
      "pickerSchema": {
        "mode": "table",
        "id": "u:4a0b63abcb6b",
        "headerToolbar": {
          "body": [
            {
              "type": "input-text",
              "name": "keywords",
              "addOn": {
                "type": "submit",
                "label": "搜索",
                "level": "primary",
                "icon": "fa fa-search pull-left",
                "id": "u:21c80ebe68e4"
              },
              "id": "u:84084c557494",
              "size": "lg",
              "value": "333"
            }
          ],
          "type": "form",
          "wrapWithPanel": false,
          "className": "text-right",
          "target": "projectList",
          "mode": "inline",
          "id": "u:066e591d75dc",
          "autoFocus": false,
          "submitOnInit": true
        },
        "footerToolbar": [
          "statistics",
          {
            "type": "pagination",
            "showPageInput": true,
            "layout": "perPage,pager,go"
          }
        ],
        "name": "projectList",
        "perPageAvailable": [
          7
        ],
        "primaryField": "id",
        "pageField": "page",
        "autoJumpToTopOnPagerChange": true,
        "syncResponse2Query": true,
        "columnsTogglable": "auto",
        "bulkActions": [
        ],
        "messages": {
        },
        "perPage": 7,
        "showFooter": false
      },
      "source": "get:/admin/getFinancePName",
      "size": "lg",
      "onEvent": {
        "change": {
          "weight": 0,
          "actions": [
            {
              "componentId": "u:de0c6526dac6",
              "args": {
                "value": {
                  "snum": "${event.data.selectedItems.snum}",
                  "id": "${event.data.selectedItems.id}"
                }
              },
              "actionType": "setValue"
            }
          ]
        }
      },
      "required": true,
      "embed": false,
      "options": [
      ],
      "valueField": "id",
      "labelField": "pName"
    }
  ],
  "id": "u:eedd45c03d31",
  "asideResizor": false
}

**Comment by yqking** [comment]
如下是项目中的片段，外面加了一层page，搜索框还是无法设置默认值。
###############
{
  "type": "page",
  "body": [
    {
      "type": "picker",
      "label": "项目名称",
      "name": "id",
      "id": "u:875a444018dd",
      "modalMode": "dialog",
      "multiple": false,
      "pickerSchema": {
        "mode": "table",
        "id": "u:4a0b63abcb6b",
        "headerToolbar": {
          "body": [
            {
              "type": "input-text",
              "name": "keywords",
              "addOn": {
                "type": "submit",
                "label": "搜索",
                "level": "primary",
                "icon": "fa fa-search pull-left",
                "id": "u:21c80ebe68e4"
              },
              "id": "u:84084c557494",
              "size": "lg",
              "value": "333"
            }
          ],
          "type": "form",
          "wrapWithPanel": false,
          "className": "text-right",
          "target": "projectList",
          "mode": "inline",
          "id": "u:066e591d75dc",
          "autoFocus": false,
          "submitOnInit": true
        },
        "footerToolbar": [
          "statistics",
          {
            "type": "pagination",
            "showPageInput": true,
            "layout": "perPage,pager,go"
          }
        ],
        "name": "projectList",
        "perPageAvailable": [
          7
        ],
        "primaryField": "id",
        "pageField": "page",
        "autoJumpToTopOnPagerChange": true,
        "syncResponse2Query": true,
        "columnsTogglable": "auto",
        "bulkActions": [
        ],
        "messages": {
        },
        "perPage": 7,
        "showFooter": false
      },
      "source": "get:/admin/getFinancePName",
      "size": "lg",
      "onEvent": {
        "change": {
          "weight": 0,
          "actions": [
            {
              "componentId": "u:de0c6526dac6",
              "args": {
                "value": {
                  "snum": "${event.data.selectedItems.snum}",
                  "id": "${event.data.selectedItems.id}"
                }
              },
              "actionType": "setValue"
            }
          ]
        }
      },
      "required": true,
      "embed": false,
      "options": [
      ],
      "valueField": "id",
      "labelField": "pName"
    }
  ],
  "id": "u:eedd45c03d31",
  "asideResizor": false
}

**Comment by yqking** [comment]
如下是项目中的片段，外面加了一层page，搜索框还是无法设置默认值。
###############
{
  "type": "page",
  "body": [
    {
      "type": "picker",
      "label": "项目名称",
      "name": "id",
      "id": "u:875a444018dd",
      "modalMode": "dialog",
      "multiple": false,
      "pickerSchema": {
        "mode": "table",
        "id": "u:4a0b63abcb6b",
        "headerToolbar": {
          "body": [
            {
              "type": "input-text",
              "name": "keywords",
              "addOn": {
                "type": "submit",
                "label": "搜索",
                "level": "primary",
                "icon": "fa fa-search pull-left",
                "id": "u:21c80ebe68e4"
              },
              "id": "u:84084c557494",
              "size": "lg",
              "value": "333"
            }
          ],
          "type": "form",
          "wrapWithPanel": false,
          "className": "text-right",
          "target": "projectList",
          "mode": "inline",
          "id": "u:066e591d75dc",
          "autoFocus": false,
          "submitOnInit": true
        },
        "footerToolbar": [
          "statistics",
          {
            "type": "pagination",
            "showPageInput": true,
            "layout": "perPage,pager,go"
          }
        ],
        "name": "projectList",
        "perPageAvailable": [
          7
        ],
        "primaryField": "id",
        "pageField": "page",
        "autoJumpToTopOnPagerChange": true,
        "syncResponse2Query": true,
        "columnsTogglable": "auto",
        "bulkActions": [
        ],
        "messages": {
        },
        "perPage": 7,
        "showFooter": false
      },
      "source": "get:/admin/getFinancePName",
      "size": "lg",
      "onEvent": {
        "change": {
          "weight": 0,
          "actions": [
            {
              "componentId": "u:de0c6526dac6",
              "args": {
                "value": {
                  "snum": "${event.data.selectedItems.snum}",
                  "id": "${event.data.selectedItems.id}"
                }
              },
              "actionType": "setValue"
            }
          ]
        }
      },
      "required": true,
      "embed": false,
      "options": [
      ],
      "valueField": "id",
      "labelField": "pName"
    }
  ],
  "id": "u:eedd45c03d31",
  "asideResizor": false
}
