### ISSUE TITLE
select值变化 依次清空combo值

### ISSUE THREAD

**Issue by xinghe94** [baidu/amis#856]
#### 实现场景：
有一个select 我想在点击切换的时候 清掉下面combo的值
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
我是这样去写的
上方的select变化就清空下方的combo 这个select的初始值是根据initapi带进来的 所以我设置了一个全局初始值做对比 不知道这个formula写的是不是有问题
![image](https://user-images.githubusercontent.com/15528239/90468912-1981fc00-e14a-11ea-9212-85cee61b18df.png)
![image](https://user-images.githubusercontent.com/15528239/90468764-c6a84480-e149-11ea-933f-efef4c07908a.png)

**Comment by 2betop** [comment]
x 是什么东西呢？不支持 x，你可以把 formula 放到 combo 里面，这样就不需要 combo[x] 了，而是直接就是里面的成员。采用全局变量应该是可以，只是全局变量数据变化的时候amis是不会知道的。

**Comment by RickCole21** [comment]
把`formula`写`combo`里试试，你现在这个`formula`的`name`看起来是没啥用的

获取之前的值作对比可以用`data.__prev.xxx`

**Comment by 2betop** [comment]
另外combo外的数据要实时同步到combo内部需要看这：https://baidu.github.io/amis/docs/components/form/combo#%E5%90%8C%E6%AD%A5%E6%9B%B4%E6%96%B0%E5%86%85%E9%83%A8%E8%A1%A8%E5%8D%95%E9%A1%B9

**Comment by xinghe94** [comment]
> 另外combo外的数据要实时同步到combo内部需要看这：https://baidu.github.io/amis/docs/components/form/combo#%E5%90%8C%E6%AD%A5%E6%9B%B4%E6%96%B0%E5%86%85%E9%83%A8%E8%A1%A8%E5%8D%95%E9%A1%B9

好的 辛苦 我参照着试一下

**Comment by RickCole21** [comment]
关了，有问题再开
