### ISSUE TITLE
amis文档网站无法访问，多个浏览器尝试报一样错

### ISSUE THREAD

**Issue by AprildreamMI** [baidu/amis#8560]
![image](https://github.com/baidu/amis/assets/31964372/11829ac2-45ac-4aa5-9089-b1a8192c8a7c)

**Comment by AprildreamMI** [comment]
![image](https://github.com/baidu/amis/assets/31964372/7b9a13bd-6f3e-4963-8716-92fafa63b0f9)

**Comment by 2betop** [comment]
收到，看文档先用这个 https://aisuda.bce.baidu.com/amis/
