### ISSUE TITLE
报错："export 'DSBuilderManager' was not found in 'amis-editor-core'

### ISSUE THREAD

**Issue by 173974319** [baidu/amis#8562]
#### 描述问题：

以前是正常的，今天将项目里的node_modules删除，重新install后，收到如下报错

 warning  in ./node_modules/amis-editor/esm/plugin/CRUD2.js

"export 'DSBuilderManager' was not found in 'amis-editor-core'

 warning  in ./node_modules/amis-editor/esm/plugin/Form/Combo.js

"export 'DSBuilderManager' was not found in 'amis-editor-core'

 warning  in ./node_modules/amis-editor/esm/plugin/Form/InputTable.js

"export 'DSBuilderManager' was not found in 'amis-editor-core'

 warning  in ./node_modules/amis-editor/esm/plugin/CRUD2.js

"export 'DSFeature' was not found in 'amis-editor-core'

编译的时候虽然是warning，但是会导致页面直接空白，控制台也有此报错

#### 如何复现（请务必完整填写下面内容）：

amis版本如下（已经尝试过固定版本号3.2.0）
"amis": "^3.2.0",
"amis-editor": "5.4.1",

**Comment by 2betop** [comment]
amis-formula, amis-core, amis-ui, amis

**Comment by 173974319** [comment]
> amis-formula, amis-core, amis-ui, amis amis-editor-core, amis-editor 这 6 个包都固定版本吧，这两组分别用统一的版本号

还是不太行。。分别用的3.2.0和5.4.1

**Comment by 2betop** [comment]
不是用的 yarn 吧，yarn 的话，还需要配置 resolutions 

https://stackoverflow.com/questions/49072905/yarn-installing-multiple-versions-of-the-same-package

**Comment by 173974319** [comment]
> 不是用的 yarn 吧，yarn 的话，还需要配置 resolutions
> 
> https://stackoverflow.com/questions/49072905/yarn-installing-multiple-versions-of-the-same-package

最后发现是这六个依赖必须要版本配对使用，比如3.2.0里引用了core的某个对象，但是5.4.1的core里已经没有这个对象了。把所有包的版本固定成最新的版本，就没问题了
