### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by wangzhongliang** [baidu/amis#857]
#### 描述问题：
本地运行amis的examples的时候，报错，在使用radios组件的时候出现：
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@134]' TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ObjectNode'
    |     property '_parent' -> object with constructor 'ObjectNode'
    |     property 'identifierCache' -> object with constructor 'IdentifierCache'
    |     ...
    |     index 0 -> object with constructor 'ObjectNode'
    --- property '_parent' closes the circle
    at JSON.stringify (<anonymous>)
    at Options.tsx:162
    at npm.js:55367
    at trackDerivedFunction (npm.js:53992)
    at Reaction.track (npm.js:55020)
    at reactionRunner (npm.js:55366)
    at Reaction.onInvalidate (npm.js:55354)
    at Reaction.runReaction (npm.js:54992)
    at runReactionsHelper (npm.js:55123)
    at reactionScheduler (npm.js:55101)

#### 截图或视频：
![image](https://user-images.githubusercontent.com/17668601/90480480-e26c1480-e162-11ea-9ce1-ecfc780c2cbd.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm install
npm run dev
npm start

node v12.16.1
npm 6.13.4
操作系统win10
浏览器Chrome 84.0.4147.105（正式版本） （64 位）

2. 粘贴有问题的完整 `amis schema` 代码：
不只是下面的代码，examples中所有radios相关的都有问题，可能不止radios
```
{
    "type": "page",
    "title": "自定义组件示例",
    "data": {
        radios: 1
    },
    "body": {
        "type": "form",
        "controls": [
            {
                "name": "radios",
                "type": "radios",
                "label": "radios",
                "options": [
                    {
                        "label": "Motor1",
                        "value": 1
                    },
                    {
                        "label": "Motor2",
                        "value": 2
                    }
                ]
            }, {
                type: "page",
                body: "${radios}",
                visibleOn: 'radios==1'
            }
        ]
    }
}
```

3. 操作步骤
npm install
npm run dev
npm start
访问127.0.0.1/examples，点击一个带有radios的例子，就报错

**Comment by 2betop** [comment]
初步估计是mobx 版本问题，试试 mobx@4.15.4

**Comment by nwind** [comment]
新版应该解决了
