### ISSUE TITLE
更新 amis@3.6.0 版本后运行时报错：找不到 "moment-timezone": "^0.5.34" 依赖

### ISSUE THREAD

**Issue by citynook** [baidu/amis#8571]
#### 描述问题：
在项目中更新 amis@3.6.0 版本后，运行时报错：找不到 "moment-timezone": "^0.5.34" 这个依赖，删除 node_modules 目录重新安装所有依赖还是发生同样的问题。

解决方案：将 "moment-timezone": "^0.5.34"  加入到项目的 package.json中，重新安装依赖，此问题消失。

3.6.0 之前的版本没有这个问题，是否新版本的 package.json 中配置缺失，造成安装 amis 时没有自动安装 moment-timezone？还是说使用新版本时，需要在项目中同时单独安装 "moment-timezone": "^0.5.34" 这个依赖？ 

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/127393297/c43b5b68-cdc3-435f-b3a3-73dffaa96fd4)
![image](https://github.com/baidu/amis/assets/127393297/ed8f3ae0-8680-40a7-8420-9864ae224966)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
先项目里加一下依赖吧，amis 中本来以为加了，后来发现加的是 devDependencies 里面

**Comment by citynook** [comment]
@2betop 没问题，不过请问 amis-editor 什么时候能发布新版，5.6.1 的 editor 无法正常加载旧版本生成的 schema 的问题，很影响控件的使用，重新设计一次太辛苦了~

**Comment by 2betop** [comment]
5.6.2 昨天一起发了

**Comment by citynook** [comment]
@2betop 刚改了镜像地址，看到 5.6.2了，旧的镜像还没有。多谢~~

**Comment by 2betop** [comment]
这个问题应该是已经修复了，先关了
