### ISSUE TITLE
编辑器中，表格2.0，基于接口自动生成字段，会一直loading

### ISSUE THREAD

**Issue by jianchaoming** [baidu/amis#8576]
#### 描述问题：

编辑器中，表格2.0，基于接口自动生成字段，会一直loading

#### 截图或视频：

<img width="801" alt="image" src="https://github.com/baidu/amis/assets/39518514/ace9903a-6a5d-49dd-9394-c1acc1a09663">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
{
    "amis": "3.4.3",
    "amis-core": "3.4.3",
    "amis-editor": "5.6.2",
    "amis-editor-core": "5.6.2",
    "amis-formula": "3.4.3",
    "amis-ui": "3.4.3",
}

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
随便用一个真实接口，必现
点击下一步会消失
但是删除个字段又出现了

**Comment by zhaoyinger623** [comment]
请问这个问题解决了吗，是用的哪个版本的编辑器呢，我们用5.6.1还存在问题

**Comment by jianchaoming** [comment]
> 请问这个问题解决了吗，是用的哪个版本的编辑器呢，我们用5.6.2还存在问题，amis的版本是3.5.2，与amis-editor-demo中package.json中写的版本保持一致

新版本解决了
