### ISSUE TITLE
日期为毫秒值怎么转换为日期时间格式

### ISSUE THREAD

**Issue by yang2wuhen** [baidu/amis#858]
服务器返回毫秒值日期,怎么用amis转化为日期时间格式!

**Comment by RickCole21** [comment]
显示格式：https://baidu.gitee.io/amis/docs/components/form/date#%E6%98%BE%E7%A4%BA%E6%A0%BC%E5%BC%8F
值格式：https://baidu.gitee.io/amis/docs/components/form/date#%E5%80%BC%E6%A0%BC%E5%BC%8F

`datetime`同理

**Comment by yang2wuhen** [comment]
1591862818876这样的时间戳格式怎么显示为YYYY-MM-DD这样的格式,依然没有找到答案!

**Comment by RickCole21** [comment]
要自行查阅 [moment文档](https://momentjs.com/docs/#/displaying/format/)，你这个应该是配置`format`为`'x'`

还有希望以后可以按照 issue 模板进行提问，而不是删了自己写，谢谢

**Comment by RickCole21** [comment]
不过我在文档里再补充说明下好了

**Comment by yang2wuhen** [comment]
我是在crud中使用服务器返回的毫秒值,来显示日期时间. 
如果按照你说的 配置format为'x',显示的效果是毫秒值再加3个0,而不是日期时间格式

**Comment by yang2wuhen** [comment]
应该是 "type":"datetime",  "valueFormat":"x"
