### ISSUE TITLE
点击button按钮传参并根据返回url跳转新页面

### ISSUE THREAD

**Issue by qinaidetonggege** [baidu/amis#859]
`"type": "button",
   "label": "查看",
    "actionType": "ajax",
     "api":"/api/spu/getDetailUrl?spuId=${spuId}&cateCode=${cateCode}",
     "redirect":"${payload.data.url}",`

redirect获取不到url

**Comment by RickCole21** [comment]
试试`"redirect":"${url}"`

还有希望可以按照`issue template`来提问，而不是一把删了模板自己写，谢谢😁

**Comment by qinaidetonggege** [comment]
好的，redirect不会跳转啊，有返回数据，但是不跳转
