### ISSUE TITLE
CRUD组件找不到懒加载API deferApi 的配置项

### ISSUE THREAD

**Issue by citynook** [baidu/amis#8590]
#### 描述问题：
CRUD组件的接口面板中，只有API的配置项，找不到懒加载deferApi 的配置项。
手动加 deferApi  到 json 中会被自动删除掉。

#### 截图或视频：
![1698901450587](https://github.com/baidu/amis/assets/127393297/47d8ef65-edcb-44ea-9a27-d13143206271)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis: 3.5.0
amis editor: 5.6.2

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
通常 amis 中新加入的属性，要等一段时间才会出现在编辑器里面 ：（

**Comment by citynook** [comment]
那还要等，加到 json 代码窗口中也会被自动删除掉~~>_<~~

**Comment by 2betop** [comment]
不会删掉

**Comment by citynook** [comment]
多谢，等待编辑器更新，先手动改 json，关闭。
