### ISSUE TITLE
表单post提交是转义json字符串

### ISSUE THREAD

**Issue by wuming333666** [baidu/amis#8607]
#### 描述问题：

post 提交时。变成转义的json字符串
#### 截图或视频：
<img width="1415" alt="image" src="https://github.com/baidu/amis/assets/19487048/cfdf1d5e-1518-4544-b34c-c7a25ecaae19">

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
在 https://aisuda.github.io/amis-editor-demo上编辑
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lhtuling** [comment]
![image](https://github.com/baidu/amis/assets/44140500/8f2b53e2-e649-480f-b08d-a807117fd959)

大胸弟。。。。  这。。。。


Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449

**Comment by xiaoyuanr** [comment]
这个问题解决了吗？我遇到了相同的问题。
我复制了官方示例中的“增删改查示例”的配置，然后没有任何修改的粘贴到amis-editor-demo(master分支)。点击新增，提交发出了post请求。结果请求体与官方示例不用。
官方示例发送的请求体是一个json，也就是curl的请求体是：
--data '{"name":"abc"}'

但是在amis-editor-demo中请求体是
--data '"{\"name\":\"abc\"}"'

看上去在amis-editor-demo将json转成了字符串。

**Comment by Lisa1787** [comment]
问题同上，post会自动转为json字符串，请问怎么解决可以发送json格式？

**Comment by atliwen** [comment]
有人解决了嘛

**Comment by mxian** [comment]
我也遇到了，怎么解决呢

**Comment by xiaoyuanr** [comment]
@mxian 回退到旧版本。可以回退到git commit：f3c3a7af。然后修改下amis-editor和amis-editor-core的版本号。我在本地是可以的。
![image](https://github.com/baidu/amis/assets/21323843/f5909d3e-4e92-4589-8799-755fd89ce57f)

**Comment by luoxue2017** [comment]
我也遇到了这个问题 amis-editor-demo 6.0.0也有这个问题，post json 自动转义了，引号的自动加了 反斜杠转义
![image](https://github.com/baidu/amis/assets/30230921/bc1661c3-0656-4655-a64e-b2d52985be01)

6.0.0的SDK是正常的，只有 amis-editor-demo是有问题的
下面是正常的
![image](https://github.com/baidu/amis/assets/30230921/3c706eea-fcbb-4871-8485-c39d70fbe91e)

看这个问题 出现在了好几个版本的 amis-editor-demo上一直没有解决 @CheshireJCat
