### ISSUE TITLE
AMisRender.tsx   renderSchema增加 acl:xxx 这段代码，导致page组件 data属性不可用

### ISSUE THREAD

**Issue by yangkun2197** [baidu/amis#861]
AMisRender.tsx 
的 renderSchema增加 acl:xxx 这段代码
导致 page组件中的 data属性 不可用

    return renderSchema(
      schema,
      {
        onAction: onAction || this.handleAction,
        location,
        locale,
        data: {
          //权限
          acl: {
            can: (permission: string) => {
              try {
                return store.application.permissions.indexOf(permission) > -1;
              } catch (error) {
                return false;
              }
            },
          },
        },
        theme: store && store.theme,
        ...rest,
      },
      this.env
    );

如下:
{
    "data": {
        "text": "World!"
    },
    "type": "page",
    "body": "Hello ${text}"
}

期望显示的是 Hello World  但是只会显示Hello

这个是怎么回事？？

**Comment by 2betop** [comment]
目前不能复现，尝试最新  amis@1.0.15-beta.38  试试

**Comment by RickCole21** [comment]
关了，有问题再开
