### ISSUE TITLE
向 amis-editor 5.6.2 编辑器中拖入一些控件时报错

### ISSUE THREAD

**Issue by citynook** [baidu/amis#8612]
#### 描述问题：
下载官方2023.11.3日最新源码运行编辑器，在向编辑器拖拖入一些控件时报错，详见下面图片。

界面上的【重置】按钮是单独加的，直接调用了源码中已有的 clearCache 方法，未再改动其它源码。

暂时只测试了下拉框文本框、状态容器、表格2.0、CRUD这几个控件，可能其它一些控件也会发生类似的问题，应该都属于同样的问题。

#### 截图或视频：
问题1：按F5刷新网页，拖入【文档框】然后点击【重置】按钮，都会输出如下警告和错误信息。其它的一些控件也有类似的情况。
![image](https://github.com/baidu/amis/assets/127393297/b89be70e-e8e8-48f2-a48a-d0e13388a79d)

问题2：按F5刷新网页，拖入【CRUD】控件，然后点击【重置】按钮。其它如表格2.0控件也会发生同样的问题。
![image](https://github.com/baidu/amis/assets/127393297/a699d339-b903-438d-b37d-a0c7a27ae507)

问题3：按F5刷新网页，拖入【下拉框】控件
![1698986529678](https://github.com/baidu/amis/assets/127393297/b26f8f80-4592-4e2b-a2ea-a2b068149345)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
amis: 2023.11.3日中午12点下载的官网源码
nodejs: 18.16.1

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
在【编辑】按钮后面新增了一个【重置】按钮，调用已有的 clearCache 方法，重置编辑框。
```
              <div
                className={`header-action-btn 'primary' : ''}`}
                onClick={() => {
                  this.clearCache();
                }}
              >
                {'重置'}
              </div>
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by citynook** [comment]
@2betop 烦请有时间看下这些问题是否需要修改~

**Comment by citynook** [comment]
@2betop 可以抽空过一眼这个 issue 吗~

**Comment by 2betop** [comment]
好像复现不了

**Comment by citynook** [comment]
那我再下载一版最新的源码运行下看看，是否已经被修复~

**Comment by citynook** [comment]
下载了2023.11.17日的版本，此问题没有复现，可能已经修复，先关闭此issue，待新版本发布再测试。
