### ISSUE TITLE
api里，解析url中的模板字符串，未识别转义字符"\\"

### ISSUE THREAD

**Issue by hehuasa** [baidu/amis#8613]
#### 描述问题：

api里，解析url中的模板字符串，未识别转义字符"\\"

#### 截图或视频：
url如下：
xxxxx&filters[name][\\$contains]=${name}&filters[appType][\\$eq]=${appType}
![D834B6A2F6E5CD111339B7EDEDBA29BD](https://github.com/baidu/amis/assets/26007057/522d2e27-4135-42cc-a1ce-755c612af5bf)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网demo可复现

3. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
aims 3.5.2 以及 aims-editor 5.6.2
4. 粘贴有问题的完整 `amis schema` 代码：
```
xxxxx&filters[name][\\$contains]=${name}&filters[appType][\\$eq]=${appType}
```

5. 操作步骤
请简单描述一下复现的操作步骤...
编辑器中拖拽一个crud组件，配置url，url中添加转义字符"\\"以及${变量}  xxxxx&filters[name][\\$contains]=${name}&filters[appType][\\$eq]=${appType}

**Comment by 2betop** [comment]
新版本复现不了了，先关了，有问题再开

<img width="1383" alt="image" src="https://github.com/baidu/amis/assets/2698393/7e653fc3-91c2-4f22-8103-be5c09dacc2b">
