### ISSUE TITLE
外观配置不能正常渲染的问题

### ISSUE THREAD

**Issue by snowing-x** [baidu/amis#8619]
#### 实现场景：
我把amis仓库fork下来修改后重新打了包xxx/amis、xxx/amis-core，但是amis-theme-editor引入的依赖是amis-core，这就导致编辑器注册进去渲染器的和实际进行渲染的不是同一份代码，编辑器的外观配置就会提示找不到对应的渲染器。
amis-theme-editor现在也没有开源，有什么办法能够让外观配置正常渲染吗？

<img width="272" alt="image" src="https://github.com/baidu/amis/assets/51695385/f6b4a801-d6c6-46a7-8669-f14bcdd561bc">

**Comment by 2betop** [comment]
自己发个 amis-theme-editor ，字符替换

**Comment by snowing-x** [comment]
amis-theme-editor不是没开源吗？怎么自己发呢

**Comment by 2betop** [comment]
改 npm 里面的

**Comment by snowing-x** [comment]
好的谢谢
