### ISSUE TITLE
Audio样式有遮挡

### ISSUE THREAD

**Issue by 52flutter** [baidu/amis#8623]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：
官网Demo，调节音量有折叠
![image](https://github.com/baidu/amis/assets/11569655/900417c5-dc19-4787-9048-89b4281291f4)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by wibetter** [comment]
@52flutter 感谢反馈

**Comment by wibetter** [comment]
已修复：https://github.com/baidu/amis/pull/8797。待下一版本生效。
