### ISSUE TITLE
maxLength限制输入长度能否以字符为单位

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#8630]
#### 实现场景：
我想要通过maxLength限制输入长度为40个字符 即汉字限制20个 英文限制40个
#### 存在的问题：
暂未发现有相关功能

**Comment by nwind** [comment]
后端是 gbk？先自己加个自定义校验规则吧 https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/addon#%E6%89%A9%E5%B1%95%E8%A1%A8%E5%8D%95%E9%AA%8C%E8%AF%81

这个太定制了不打算加
