### ISSUE TITLE
属性的扩展

### ISSUE THREAD

**Issue by ityue** [baidu/amis#8635]
#### 实现场景：
自定义组件的右侧面板属性，想继承现有组件的属性，比如想实现个自定义组件，想右侧面板的属性/外观/事件 能够继承现有的文本框组件的属性/外观/事件。

#### 存在的问题：
不清楚怎么继承现有文本框的属性

#### 当前方案：
使用panelBodyCreator方法定制扩展，copy文本框组件的属性

```
 panelBodyCreator = (context: BaseEventContext) => {

    return getSchemaTpl('tabs', [
      {
        title: '属性',
        body: getSchemaTpl(
          'collapseGroup',
          [
            {
              title: '基本',
              body: [
                getSchemaTpl('formItemName', {
                  required: true
                }),
                getSchemaTpl('label'),
                getSchemaTpl('tplFormulaControl', {
                  name: 'value',
                  label: '默认值',
                }),
                {
                  name: 'multiple',
                  label: '多选',
                  type: 'switch',
                }
              ]
            },
          ],
          {...context?.schema, configTitle: 'props'}
        )
      }

```

**Comment by wibetter** [comment]
可以继承现有的plugin，比如继承TextControlPlugin，但需要重新声明当前自定义组件的name、rendererName等信息（除panelBodyCreator外）：
<img width="843" alt="image" src="https://github.com/baidu/amis/assets/11958920/ea48feed-8ebf-4871-8cac-95da241b729e">。
如果想重新定义整个属性配置面板，需要在自定义组件的plugin/panelBodyCreator 定制自定义组件的配置面板。

**Comment by ityue** [comment]
TextControlPlugin 好像没用暴漏出来,请问外部的怎么引用

**Comment by wibetter** [comment]
@ityue 
<img width="956" alt="image" src="https://github.com/baidu/amis/assets/11958920/67a3644c-46df-42bd-9891-566f9e339135">

效果如下：
<img width="1231" alt="image" src="https://github.com/baidu/amis/assets/11958920/504e6f1f-66fa-45e3-9099-d20c71983b12">

**Comment by ityue** [comment]
感谢感谢 十分感谢~~~
