### ISSUE TITLE
如何通过Picker 列表选择器选择多行，选中之后，inputtable自动增加多行？

### ISSUE THREAD

**Issue by songyinhai2006** [baidu/amis#8638]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

通过Picker 列表选择器选择多行，选中之后，inputtable自动增加多行

#### 预期的解决方案：
请简单描述你想达到的效果...

![image](https://github.com/baidu/amis/assets/52561802/8ce3ab84-d149-4501-92e3-56618fec11ce)
期望如弹框中选中5行，将这5行数据返回到inputtable中，inputtable中多出5行，在此基础上再修改

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by gexMichael** [comment]
+1

**Comment by hsm-lv** [comment]
可以监听picker的change事件，获取选中行数据后赋值给inputtable

**Comment by songyinhai2006** [comment]
> 可以监听picker的change事件，获取选中行数据后赋值给inputtable https://aisuda.bce.baidu.com/amis/zh-CN/components/form/picker#%E4%BA%8B%E4%BB%B6%E8%A1%A8 https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-table#setvalue

好的 谢谢 我来试试
