### ISSUE TITLE
input-date-range使用maxDuration无效

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#8648]
#### 描述问题：

input-date-range使用maxDuration设置最大跨度无效

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/48573389/a844a31b-b7e6-4fa2-9029-0ff351d93199)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官方文档 https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-date-range

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "input-date-range",
        "name": "select",
        "label": "日期范围",
        "maxDuration": "1weeks"
      }
    ]
  }
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
看起来是很早之前版本就修了的 #4820

官方文档不是所有属性都实时修改生效
