### ISSUE TITLE
action 直接跳转没法在新 Tab 页打开

### ISSUE THREAD

**Issue by qyf381389362** [baidu/amis#865]
#### 描述问题：
action 直接跳转没法在新 Tab 页打开

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网示例就不好使。https://baidu.gitee.io/amis/docs/components/action#%E7%9B%B4%E6%8E%A5%E8%B7%B3%E8%BD%AC

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
    "body": {
        "label": "打开 Baidu",
        "type": "button",
        "level": "success",
        "actionType": "url",
        "url": "http://www.baidu.com/",
        "blank": true
    }
}
```

**Comment by RickCole21** [comment]
多谢提醒，已修复
