### ISSUE TITLE
InputDate组件和input-time组件在执行默认值公式时未识别valueFormat属性

### ISSUE THREAD

**Issue by yinlianghui** [baidu/amis#8652]
#### 描述问题：

如题，给表单中日期（不包含小时分秒）、时间（不包含年月日）字段设置默认值时，这两种字段类型的valueFormat格式有特别的要求，但是并没有被识别。

##### InputDate组件
- 表单初始化时，值为数据域中配置的`${TODAY()}`值，从form组件debug出来的字段值可以看出其值没有识别valueFormat属性

![image](https://github.com/baidu/amis/assets/6219465/3c57d634-31f4-4faa-820b-44a88b313fdd)

- 如果手动在控件中点选操作变更字段值，可以看到valueFormat属性是生效的。

![image](https://github.com/baidu/amis/assets/6219465/efbbf992-363e-4e66-960d-756fe8e094f6)

##### input-time组件
- 表单初始化时，值为数据域中配置的`${NOW()}`值，从form组件debug出来的字段值可以看出其值没有识别valueFormat属性

![image](https://github.com/baidu/amis/assets/6219465/4ee26e0a-a945-4c75-96a1-0373df9eaff9)

- 如果手动在控件中点选操作变更字段值，可以看到valueFormat属性是生效的。

![image](https://github.com/baidu/amis/assets/6219465/6e7df918-b67f-46ba-b47c-55ee8fcc02c1)

- amis 3.4.1版本才支持valueFormat属性，在amis 2.9版本中可以用format属性，两个amis版本的都是有问题的，没有字段值进行格式化。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3.4.1，2.9.0都有问题

4. 粘贴有问题的完整 `amis schema` 代码：
##### InputDate组件
```
{
  "type": "page",
  "data": {
    "date": "${TODAY()}"
  },
  "body": {
    "type": "form",
    "debug": true,
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "input-date",
        "name": "date",
        "label": "日期",
        "valueFormat": "YYYY-MM-DDT00:00:00.000[Z]"
      }
    ]
  }
}
```

##### input-time组件
```
{
  "type": "page",
  "data": {
    "time": "${NOW()}"
  },
  "body": {
    "type": "form",
    "debug": true,
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "input-time",
        "name": "time",
        "label": "时间",
        "valueFormat": "1970-01-01THH:mm:00.000[Z]",
        "timeConstraints": {
          "hours": {
            "min": 9,
            "max": 17
          },
          "minutes": {
            "step": 15
          }
        }
      }
    ]
  }
}
```

6. 操作步骤
以上`amis schema` 代码复制到amis官网中的示例code中就能重现问题。

另外我们尝试过在代码中使用pipeIn/pipeOut来修正这个问题并没有成功，因为字段默认值在表单初始化时只会执行pipeIn而不会执行pipeOut，实测pipeOut只有手动点选变更字段值才有触发，以下是我们尝试给input-time组件加的`pipeIn/pipeOut`脚本代码。

```
pipeIn: (value, data) => {
    console.log("=time==pipeIn===", value, data);
    if (value) {
        // value = moment(value).utc().format('HH:mm');
        value = moment(value).utc()
        value.set("year", 1970);
        value.set("month", 0);
        value.set("date", 1);
        // value.set("hours", value.hours() + value.utcOffset() / 60)
        value.set("seconds", 0);
        value.set("milliseconds", 0);
        return value;
    } else {
        return "";
    }

},
pipeOut: (value, oldValue, data) => {
    console.log("=time==pipeOut===", value, data);
    if (value) {
        value = moment('1970-01-01 ' + value).format('1970-01-01THH:mm:00.000[Z]');
        return value;
    } else {
        return "";
    }
}
```

**Comment by zhaoyinger623** [comment]
同样碰到了这个问题

**Comment by 2betop** [comment]
目前是初始值只做适配，没做纠正，后续考虑处理一下吧

**Comment by 2betop** [comment]
@yinlianghui 你的配置方式跟 @zhaoyinger623 不一样，我觉得后者是一个需要解决的场景。而直接配置数据域，组件没有交互不应该去变更它关联值
