### ISSUE TITLE
isObjectShallowModified实现性能优化

### ISSUE THREAD

**Issue by 52flutter** [baidu/amis#8656]
#### 是否关联于某个问题吗：
isObjectShallowModified方法会对比react元素导致性能不好

#### 预期的解决方案：

```tsx
export function isObjectShallowModified(   
  prev: any,
  next: any,
  strictModeOrFunc: boolean | ((lhs: any, rhs: any) => boolean) = true,
  ignoreUndefined: boolean = false,
  statck: Array<any> = []
): boolean {
  // 如果是元素 直接判断
  if(React.isValidElement(prev) || React.isValidElement(next)){
    if(prev===next){
      return false;
    }
  }
  if (Array.isArray(prev) && Array.isArray(next)) {
    return prev.length !== next.length
      ? true
      : prev.some((prev, index) =>
          isObjectShallowModified(
            prev,
            next[index],
            strictModeOrFunc,
            ignoreUndefined,
            statck
          )
        );
  }

  if (isNaN(prev) && isNaN(next)) {
    return false;
  }

  if (
    null == prev ||
    null == next ||
    !isObject(prev) ||
    !isObject(next) ||
    isObservable(prev) ||
    isObservable(next)
  ) {
    if (strictModeOrFunc && typeof strictModeOrFunc === 'function') {
      return strictModeOrFunc(prev, next);
    }

    return strictModeOrFunc ? prev !== next : prev != next;
  }

  if (ignoreUndefined) {
    prev = rmUndefined(prev);
    next = rmUndefined(next);
  }

  const keys = Object.keys(prev);
  const nextKeys = Object.keys(next);
  if (
    keys.length !== nextKeys.length ||
    keys.sort().join(',') !== nextKeys.sort().join(',')
  ) {
    return true;
  }

  // 避免循环引用死循环。
  if (~statck.indexOf(prev)) {
    return false;
  }

  statck.push(prev);

  for (let i: number = keys.length - 1; i >= 0; i--) {
    const key = keys[i];
    // 参考react-fast-compare 去掉一些层次很深的对象
      if ((key === '_owner' || key === '__v' || key=== '__o') && prev.$$typeof) {
        // React-specific: avoid traversing React elements' _owner
        // Preact-specific: avoid traversing Preact elements' __v and __o
        //    __v = $_original / $_vnode
        //    __o = $_owner
        // These properties contain circular references and are not needed when
        // comparing the actual elements (and not their owners)
        // .$$typeof and ._store on just reasonable markers of elements

        continue;
      }
    if (
      isObjectShallowModified(
        prev[key],
        next[key],
        strictModeOrFunc,
        ignoreUndefined,
        statck
      )
    ) {
      return true;
    }
  }
  return false;
}
```

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
主要修改了二处
![image](https://github.com/baidu/amis/assets/11569655/a8973433-4616-4b1c-a0aa-37efac575f97)
看看有没有啥毛病

**Comment by 2betop** [comment]
什么情况下会进来 diff react element 来着？

```tsx
// 如果是元素 直接判断
  if(React.isValidElement(prev) || React.isValidElement(next)){
    if(prev===next){
      return false;
    }
  }
```

这里应该是不管一样不一样都得返回吧，如果不是一个对象不需要往下走了

```tsx
// 如果是元素 直接判断
  if(React.isValidElement(prev) || React.isValidElement(next)){
    return prev===next;
  }
```

 下面 那些 key 的判断，我觉得是没必要的，因为已经加上上面的那段代码

**Comment by 52flutter** [comment]
调试了一下是 
![image](https://github.com/baidu/amis/assets/11569655/fa1c9bc7-31b8-4665-8236-555cdb6ee7f0)
![image](https://github.com/baidu/amis/assets/11569655/a57e2da5-fa4d-4375-be93-0abc3ee36d54)

**Comment by 52flutter** [comment]
类似这样的都会走 tab是不是只需要判断一层 body交给底下组件自己去判断

**Comment by 52flutter** [comment]
statck 可以改成set吧 性能比数组查找应该要快

**Comment by 52flutter** [comment]
![image](https://github.com/baidu/amis/assets/11569655/aca56411-0534-474f-9a17-589ab9443642)
![image](https://github.com/baidu/amis/assets/11569655/f8bc411f-49a5-4a42-982e-54c396695384)
我拖个按钮到按钮组

**Comment by 52flutter** [comment]
![image](https://github.com/baidu/amis/assets/11569655/7de6b52e-1ad0-49b0-b24d-ee4e8151ff68)

**Comment by 2betop** [comment]
加了这个应该不会再递归进去了吧？

```tsx
// 如果是元素 直接判断
  if(React.isValidElement(prev) || React.isValidElement(next)){
    return prev===next;
  }
```

可以换成 Set

**Comment by 52flutter** [comment]
应该是返回不等于吧

**Comment by 52flutter** [comment]
export function isObjectShallowModified(   
  prev: any,
  next: any,
  strictModeOrFunc: boolean | ((lhs: any, rhs: any) => boolean) = true,
  ignoreUndefined: boolean = false,
  statck:Set<any>=new Set()
): boolean {

 // 如果是元素 直接判断
  if(React.isValidElement(prev) || React.isValidElement(next)){
    return prev!==next;
  }

  if (Array.isArray(prev) && Array.isArray(next)) {
    return prev.length !== next.length
      ? true
      : prev.some((prev, index) =>
          isObjectShallowModified(
            prev,
            next[index],
            strictModeOrFunc,
            ignoreUndefined,
            statck
          )
        );
  }

  if (isNaN(prev) && isNaN(next)) {
    return false;
  }

  if (
    null == prev || null == next || !isObject(prev) || !isObject(next) || isObservable(prev) || isObservable(next)
  ) {
    if (strictModeOrFunc && typeof strictModeOrFunc === 'function') {
      return strictModeOrFunc(prev, next);
    }

    return strictModeOrFunc ? prev !== next : prev != next;
  }

  if (ignoreUndefined) {
    prev = rmUndefined(prev);
    next = rmUndefined(next);
  }

  const keys = Object.keys(prev);
  const nextKeys = Object.keys(next);
  if (
    keys.length !== nextKeys.length ||
    keys.sort().join(',') !== nextKeys.sort().join(',')
  ) {
    return true;
  }
  // 避免循环引用死循环。
  if(statck.has(prev)){
    return false;
  }

  statck.add(prev)
  // statck.push(prev);

  for (let i: number = keys.length - 1; i >= 0; i--) {
    const key = keys[i];
   
    if (
      isObjectShallowModified(
        prev[key],
        next[key],
        strictModeOrFunc,
        ignoreUndefined,
        statck
      )
    ) {
      return true;
    }
  }
  return false;
}

**Comment by 52flutter** [comment]
```  ts
export function isObjectShallowModified(   
  prev: any,
  next: any,
  strictModeOrFunc: boolean | ((lhs: any, rhs: any) => boolean) = true,
  ignoreUndefined: boolean = false,
  statck:Set<any>=new Set()
): boolean {

 // 如果是元素 直接判断
  if(React.isValidElement(prev) || React.isValidElement(next)){
    return prev!==next;
  }

  if (Array.isArray(prev) && Array.isArray(next)) {
    return prev.length !== next.length
      ? true
      : prev.some((prev, index) =>
          isObjectShallowModified(
            prev,
            next[index],
            strictModeOrFunc,
            ignoreUndefined,
            statck
          )
        );
  }

  if (isNaN(prev) && isNaN(next)) {
    return false;
  }

  if (
    null == prev || null == next || !isObject(prev) || !isObject(next) || isObservable(prev) || isObservable(next)
  ) {
    if (strictModeOrFunc && typeof strictModeOrFunc === 'function') {
      return strictModeOrFunc(prev, next);
    }

    return strictModeOrFunc ? prev !== next : prev != next;
  }

  if (ignoreUndefined) {
    prev = rmUndefined(prev);
    next = rmUndefined(next);
  }

  const keys = Object.keys(prev);
  const nextKeys = Object.keys(next);
  if (
    keys.length !== nextKeys.length ||
    keys.sort().join(',') !== nextKeys.sort().join(',')
  ) {
    return true;
  }
  // 避免循环引用死循环。
  if(statck.has(prev)){
    return false;
  }

  statck.add(prev)
  // statck.push(prev);

  for (let i: number = keys.length - 1; i >= 0; i--) {
    const key = keys[i];
   
    if (
      isObjectShallowModified(
        prev[key],
        next[key],
        strictModeOrFunc,
        ignoreUndefined,
        statck
      )
    ) {
      return true;
    }
  }
  return false;
} 
![image](https://github.com/baidu/amis/assets/11569655/5d7ff2d2-47b6-474e-a11d-36c6eb5a5997)

**Comment by 52flutter** [comment]
![image](https://github.com/baidu/amis/assets/11569655/28ab5b61-1bc7-47fc-a7f5-966baee1784a)

**Comment by 52flutter** [comment]
这么改变成1s多了  是不是tab那里也可以优化下  下面标签页的body需要参数diff吗

**Comment by 52flutter** [comment]
![image](https://github.com/baidu/amis/assets/11569655/98985cea-bcd9-4ac8-9004-9486ef9aef54)
这里还有manager 这个是不是也可以不参与diff

**Comment by 2betop** [comment]
试试这个

```ts
export function isObjectShallowModified(
  prev: any,
  next: any,
  strictModeOrFunc: boolean | ((lhs: any, rhs: any) => boolean) = true,
  ignoreUndefined: boolean = false,
  statck: Array<any> = []
): boolean {
  if(React.isValidElement(prev) || React.isValidElement(next)){
    return prev!==next;
  }
  
  if (Array.isArray(prev) && Array.isArray(next)) {
    return prev.length !== next.length
      ? true
      : prev.some((prev, index) =>
          isObjectShallowModified(
            prev,
            next[index],
            strictModeOrFunc,
            ignoreUndefined,
            statck
          )
        );
  }

  if (isNaN(prev) && isNaN(next)) {
    return false;
  }

  if (
    null == prev ||
    null == next ||
    !isPlainObject(prev) ||
    !isPlainObject(next) ||
    isObservable(prev) ||
    isObservable(next)
  ) {
    if (strictModeOrFunc && typeof strictModeOrFunc === 'function') {
      return strictModeOrFunc(prev, next);
    }

    return strictModeOrFunc ? prev !== next : prev != next;
  }

  if (ignoreUndefined) {
    prev = rmUndefined(prev);
    next = rmUndefined(next);
  }

  const keys = Object.keys(prev);
  const nextKeys = Object.keys(next);
  if (
    keys.length !== nextKeys.length ||
    keys.sort().join(',') !== nextKeys.sort().join(',')
  ) {
    return true;
  }

  // 避免循环引用死循环。
  if (~statck.indexOf(prev)) {
    return false;
  }

  statck.push(prev);

  for (let i: number = keys.length - 1; i >= 0; i--) {
    const key = keys[i];
    if (
      isObjectShallowModified(
        prev[key],
        next[key],
        strictModeOrFunc,
        ignoreUndefined,
        statck
      )
    ) {
      return true;
    }
  }
  return false;
}
```

**Comment by 52flutter** [comment]
![image](https://github.com/baidu/amis/assets/11569655/4ed38007-971c-40ba-8e24-efdf9f3f21cd)
在这里传入进去的

**Comment by 52flutter** [comment]
> 试试这个
> 
> ```ts
> export function isObjectShallowModified(
>   prev: any,
>   next: any,
>   strictModeOrFunc: boolean | ((lhs: any, rhs: any) => boolean) = true,
>   ignoreUndefined: boolean = false,
>   statck: Array<any> = []
> ): boolean {
>   if(React.isValidElement(prev) || React.isValidElement(next)){
>     return prev!==next;
>   }
>   
>   if (Array.isArray(prev) && Array.isArray(next)) {
>     return prev.length !== next.length
>       ? true
>       : prev.some((prev, index) =>
>           isObjectShallowModified(
>             prev,
>             next[index],
>             strictModeOrFunc,
>             ignoreUndefined,
>             statck
>           )
>         );
>   }
> 
>   if (isNaN(prev) && isNaN(next)) {
>     return false;
>   }
> 
>   if (
>     null == prev ||
>     null == next ||
>     !isPlainObject(prev) ||
>     !isPlainObject(next) ||
>     isObservable(prev) ||
>     isObservable(next)
>   ) {
>     if (strictModeOrFunc && typeof strictModeOrFunc === 'function') {
>       return strictModeOrFunc(prev, next);
>     }
> 
>     return strictModeOrFunc ? prev !== next : prev != next;
>   }
> 
>   if (ignoreUndefined) {
>     prev = rmUndefined(prev);
>     next = rmUndefined(next);
>   }
> 
>   const keys = Object.keys(prev);
>   const nextKeys = Object.keys(next);
>   if (
>     keys.length !== nextKeys.length ||
>     keys.sort().join(',') !== nextKeys.sort().join(',')
>   ) {
>     return true;
>   }
> 
>   // 避免循环引用死循环。
>   if (~statck.indexOf(prev)) {
>     return false;
>   }
> 
>   statck.push(prev);
> 
>   for (let i: number = keys.length - 1; i >= 0; i--) {
>     const key = keys[i];
>     if (
>       isObjectShallowModified(
>         prev[key],
>         next[key],
>         strictModeOrFunc,
>         ignoreUndefined,
>         statck
>       )
>     ) {
>       return true;
>     }
>   }
>   return false;
> }
> ```

这个很快 只对比基本对象的话 在几ms级别

**Comment by 2betop** [comment]
等我们后面优化一下这块吧，应该是只需要判断基础数据 + PlainObject + amis 那个数据链，其他都可以简单判断

**Comment by 52flutter** [comment]
> 等我们后面优化一下这块吧，应该是只需要判断基础数据 + PlainObject + amis 那个数据链，其他都可以简单判断

这个版本改不 或者先简单改下 把那个manager改成方法获取 加上react元素返回    @2betop

**Comment by 52flutter** [comment]
只对比简单的对象有问题 

export function isReact(prev:any){
    if (React.isValidElement(prev)){
      return true;
    }
    if(prev?.type?.prototype && (prev?.type?.prototype instanceof React.Component|| prev?.type?.prototype instanceof React.PureComponent)){
      return true
    }
    return false
}

  if (isReact(prev) ||isReact(next)) {
    return prev !== next;
  }


这样性能可以提升很多。把react元素和ref的实例都去掉了 @2betop

**Comment by 2betop** [comment]
React.isValidElement 就够了吧，下面是用来判断哪种 case？

**Comment by 52flutter** [comment]
组件实例 manage里面有很多组件实例

**Comment by 52flutter** [comment]
React.isValidElement 判断不了如下aRef这种，这种比Element多很多，而且每个层级都很深
<A ref={aRef} />

**Comment by 2betop** [comment]
不对吧，React.isValidElement 就会拦截 `<A />` 这层了，就不会继续进去了，按理轮不到 ref 了

**Comment by 52flutter** [comment]
![image](https://github.com/baidu/amis/assets/11569655/50df3641-5bef-4ac2-9566-b5f23d42391b)
这里manage里面

**Comment by 52flutter** [comment]
这里就会一直递归下去，时间就消耗在这里

**Comment by 2betop** [comment]
你这个是咋复现的，我尝试将按钮拖入按钮组没能复现

**Comment by 52flutter** [comment]
crud2选中操作列，然后拖个按钮，一定让编辑器显示操作列的配置，必现

**Comment by 2betop** [comment]
感谢，已复现，打算改成这样 

```ts
export function isObjectShallowModified(
  prev: any,
  next: any,
  strictModeOrFunc: boolean | ((lhs: any, rhs: any) => boolean) = true,
  ignoreUndefined: boolean = false,
  stack: Array<any> = []
): boolean {
  if (Array.isArray(prev) && Array.isArray(next)) {
    return prev.length !== next.length
      ? true
      : prev.some((prev, index) =>
          isObjectShallowModified(
            prev,
            next[index],
            strictModeOrFunc,
            ignoreUndefined,
            stack
          )
        );
  }

  if (isNaN(prev) && isNaN(next)) {
    return false;
  }

  if (
    null == prev ||
    null == next ||
    !isObject(prev) ||
    !isObject(next) ||
    prev.constructor !== Object || // 不是 Object.create 创建的对象
    next.constructor !== Object
  ) {
    if (strictModeOrFunc && typeof strictModeOrFunc === 'function') {
      return strictModeOrFunc(prev, next);
    }

    return strictModeOrFunc ? prev !== next : prev != next;
  }

  if (ignoreUndefined) {
    prev = rmUndefined(prev);
    next = rmUndefined(next);
  }

  const keys = Object.keys(prev);
  const nextKeys = Object.keys(next);
  if (
    keys.length !== nextKeys.length ||
    keys.sort().join(',') !== nextKeys.sort().join(',')
  ) {
    return true;
  }

  // 避免循环引用死循环。
  if (~stack.indexOf(prev)) {
    return false;
  }

  stack.push(prev);

  for (let i: number = keys.length - 1; i >= 0; i--) {
    const key = keys[i];
    if (
      isObjectShallowModified(
        prev[key],
        next[key],
        strictModeOrFunc,
        ignoreUndefined,
        stack
      )
    ) {
      return true;
    }
  }
  return false;
}
```

**Comment by 52flutter** [comment]
验证了下常规的场景应该可以
