### ISSUE TITLE
自定义js怎么获取全局变量的值呢？

### ISSUE THREAD

**Issue by qzo123** [baidu/amis#8670]
jssdk版本：3.4.2

#### 描述问题：
1. 在自定义js内如何获取全局变量的值？
2. 自定义js内应该怎么使用函数呢？

全局页面上定义的变量tableData，在表单按钮，新增点击事件-->自定义js ；
1）直接使用 console.log(tableData); ---这个时候会报错；
2）想使用GETRENDERERDATA函数获取，在按着文档示例：消息提示-->表达式内使用${GETRENDERERDATA('页面id','tableData')}可以正常读取数据，但是在自定义js内使用console.log(${GETRENDERERDATA('页面id','tableData')}) 或者console.log(GETRENDERERDATA('页面id','tableData')) 都报错，自定义js内应该怎么使用函数呢？

#### 截图或视频：
<img width="277" alt="image" src="https://github.com/baidu/amis/assets/57881678/649026e4-6129-49d0-8bb1-b1825b84052d">

希望看到能回复一下，谢谢~

**Comment by findreamer** [comment]
这个问题我也遇到过，我尝试在`event.data.__super.__super.__super`的上下文中获取到想要的值，但是发现了新的问题，如果跨层级较深，取到的值不是最新的，如果是最近的父级节点的值能获取到。
![image](https://github.com/baidu/amis/assets/116187210/dcd6ad40-c16d-410a-a0b2-a6f92e008554)

**Comment by CheshireJCat** [comment]
直接使用 event.data.tableData 获取即可，不用使用 __super, 因为数据链会类似原型链一样自动查找
但是要注意同名问题，因为查找的时候是就近查找
```
{
  "type": "button",
  "label": "新增",
  "level": "primary",
  "onEvent": {
    "click": {
      "weight": 0,
      "actions": [
        {
          "actionType": "custom",
          "script": "console.log(event.data.tableData);"
          }
        }
      ]
    }
  }
}
```

**Comment by CheshireJCat** [comment]
> 这个问题我也遇到过，我尝试在`event.data.__super.__super.__super`的上下文中获取到想要的值，但是发现了新的问题，如果跨层级较深，取到的值状态不是最新的（比如取一个`Page`组件下data的初始值，发生变化后，拿不到最新值），如果是最近的父级节点的值能获取到。 ![image](https://user-images.githubusercontent.com/116187210/281728905-dcd6ad40-c16d-410a-a0b2-a6f92e008554.png)

可以不适用 __super, 直接 event.data.tableData
