### ISSUE TITLE
`amis-theme-border` 组件无法修改边框颜色

### ISSUE THREAD

**Issue by LeuisKen** [baidu/amis#8694]
#### 描述问题：

`amis-theme-border` 组件无法修改边框颜色

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/7701575/f8419632-9c39-4626-b6b4-ca4f9dc8ed66)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
https://aisuda.github.io/amis-editor-demo/#/edit/0

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
同上

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "title": "啊",
  "body": [
    {
      "type": "tpl",
      "tpl": "这是你刚刚新增的页面。",
      "wrapperComponent": "",
      "inline": false,
      "id": "u:a225bb111a13"
    },
    {
      "type": "button",
      "label": "Button",
      "onEvent": {
        "click": {
          "actions": [
          ]
        }
      },
      "id": "u:d62b69259129"
    }
  ],
  "id": "u:c32549bdd680"
}
```

5. 操作步骤
- 选择 button 组件
- 尝试修改 border 颜色
- 失败
- 顺便，新的 color picker 没有展示英文。

**Comment by LeuisKen** [comment]
<img width="1470" alt="image" src="https://github.com/baidu/amis/assets/7701575/c200b8a2-0b4d-4dd5-b1d1-691057e918c0">

![image](https://github.com/baidu/amis/assets/7701575/6e30d7ba-d266-4ffa-bf4b-cbcb99af3101)

常用颜色被硬编码了

**Comment by qkiroc** [comment]
需要更新下amis-theme-editor包版本，demo随着后续editor新版本部署
