### ISSUE TITLE
这段代码会自动从返回结果中获取data,然后返回，但是后端如果没有按照这个规则，就无法获取正确的数据了

### ISSUE THREAD

**Issue by ZephyrTan** [baidu/amis#8695]
https://github.com/baidu/amis/blob/01f2132847c89326edcc8ee88364cc0db0478f8e/packages/amis-core/src/utils/api.ts#L437

**Comment by lhtuling** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8

Amis低代码前端框架交流群【QQ1群】：717791727
Amis低代码前端框架交流群【QQ2群】：721182449
