### ISSUE TITLE
针对 crud 两个场景都比较慢 #7641这个问题，在点击的开始渲染的那一刻能否快一些

### ISSUE THREAD

**Issue by songyinhai2006** [baidu/amis#8700]
#### 描述问题：

后台响应完成后（400毫秒左右），前端有个明显渲染等待的过程，这块能否优化一下？数据200条，渲染之后没问题。
#### 截图或视频：

![bf23d8c1211d85f3d6a077acde7f16d](https://github.com/baidu/amis/assets/52561802/c1a6ebda-351a-4c15-9851-13548e8ac246)

https://github.com/baidu/amis/assets/52561802/2506c30b-e198-451d-85f5-74c0d7fedc50

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3.4.1

4. 粘贴有问题的完整 `amis schema` 代码：

5. 操作步骤

**Comment by nwind** [comment]
加个 "lazyRenderAfter": 50 试试

**Comment by songyinhai2006** [comment]
> 加个 "lazyRenderAfter": 50 试试
感觉不是特别明显，分页我直接she'zhi设置成50，也加了这个参数，感觉还是差不多。


https://github.com/baidu/amis/assets/52561802/82320a6e-9d40-440d-9cc7-0982714a4209

![image](https://github.com/baidu/amis/assets/52561802/67793958-ca3c-4c33-b63f-fbbbb4de07ad)
