### ISSUE TITLE
期望能够提供更多“好看”的主题

### ISSUE THREAD

**Issue by wencan** [baidu/amis#8702]
目前已经使用amis成功搭建了一套公司内部用的管理后台web。
但更多时候，管理后台web往往是给客户用的。
一个项目中，我推荐使用amis搭建管理后台web，被否决了，原因就是amis美观问题。
so，可否在美化上多下点功夫，或者说多移植几个主题？

**Comment by belongwqz** [comment]
不大可能，原先有四个主题，现在都只维护了两个。

**Comment by qkiroc** [comment]
目前仅支持[速搭](https://aisuda.bce.baidu.com/)的主题编辑器来扩展主题
<img width="1438" alt="image" src="https://github.com/baidu/amis/assets/30946345/471e1b02-f75a-4b44-a4fd-fa02c7203a38">

**Comment by wibetter** [comment]
amis也是能搭建出好看的页面的，这个取决于开发者的设计能力，比如以下几个页面都是使用amis设计的页面，可以参考下：
1、爱速搭首页：
![爱速搭首页搭建](https://github.com/baidu/amis/assets/11958920/1723055c-c5c0-4046-8068-317fd5ac32e7)
2、大屏报表页效果1:
![主题风格大屏报表](https://github.com/baidu/amis/assets/11958920/9b658797-8a1e-4d11-a118-441e7ea9a69b)
3、大屏报表效果2:
![停车管理系统](https://github.com/baidu/amis/assets/11958920/8f1f930e-a7b1-400e-a42c-3a2d50c3c680)

**Comment by wencan** [comment]
@wibetter 
这些都需要写样式吧？
有点尴尬，本人除了js，完全不会前端
不过amis本来的设计意图，不就是no-code吗？
所以，个人建议多多提供现成的主题/样式

**Comment by wibetter** [comment]
@wencan 这几个页面，90%的内容，是通过可视化界面设计的，只有少部分样式是通过手动style的形式设计的（比如花纹边框）。

**Comment by wibetter** [comment]
可视化界面设计，是指编辑器端纯配置类操作

**Comment by wencan** [comment]
@wibetter 理解。
是amis专用编辑器工具，还是通用编辑器工具？
还望提供具体的编辑器工具信息

**Comment by wibetter** [comment]
就是amis-editor啊，
<img width="1527" alt="image" src="https://github.com/baidu/amis/assets/11958920/bae89d0c-ea02-455d-9eab-e5acff8ab570">
