### ISSUE TITLE
amis-editor没有开放出文档里面的所有组件，原因是啥

### ISSUE THREAD

**Issue by blankzust** [baidu/amis#8707]
#### 实现场景：
例如轮播图组件，在amis-editor左侧菜单是没有，但是能通过json代码可以写入，不开放是出于什么原因？
![image](https://github.com/baidu/amis/assets/8541906/e3e9a5ab-772f-4453-b365-920eb6a066c4)

#### 存在的问题：
希望开放文档中有的所有组件，或者给出不能开放的原因？是配置项还没写完整或者存在bug？

**Comment by wibetter** [comment]
<img width="908" alt="image" src="https://github.com/baidu/amis/assets/11958920/85404dd8-b005-45ef-91d9-f63bd6709d18">
这里难道找不到轮播图组件？

**Comment by blankzust** [comment]
这个我的问题，抱歉抱歉，隐藏了一些组件

**Comment by blankzust** [comment]
这个我的问题，抱歉抱歉，隐藏了一些组件
