### ISSUE TITLE
select组件前端传值问题

### ISSUE THREAD

**Issue by leung0727** [baidu/amis#8715]
#### 描述问题：

在3.4.0之后的版本中，当select组件中存在value值为0的选项时，利用clearable属性进行清空的时候，最终提交传值依然为0，实际期望为空值

#### 截图或视频：

![1699872941089](https://github.com/baidu/amis/assets/116611745/44403ed9-5383-4a9f-b6e3-18e4a7f32570)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.4.0及以上版本

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
新版本中无法复现，能否提供一下 select 的 schema 示例

**Comment by 2betop** [comment]
目前无法复现，有问题再开
