### ISSUE TITLE
作用域之外, 有办法修改data的值吗?

### ISSUE THREAD

**Issue by nuan1989** [baidu/amis#872]
#### 存在的问题：
用的是jssdk
1. Click事件里面, 怎么修改data数据的值呢?  
2. 在json之外, 有没办法修改data数据的值?

**###附上代码 :**
```
var json = {
    "type": "page",
    "title": "Hello world ${data}",
    "body": [
        {
            "type": "tpl",
            "tpl": "初始页面"
        },
        {
            "type": "button",
            "label": "确认",
            "actionType": "close",
            onClick: (e1, e2) => {
                console.log(e1)
                console.log(e2)
                alert('clicked');
                //这里可以访问到data变量, 但是怎么修改data变量呢?
            }
        }
    ],
    "data": {
        "data": "这是测试按钮"
    }
}

var amis = amisRequire("amis/embed");
amis.embed("#main", json);
//这里有办法修改data变量吗 ? 
```

**Comment by 2betop** [comment]
通过这个文档下面的 https://baidu.github.io/amis/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA getComponentByName 拿到 page 那层的组件。然后通过 props.store.updateData(xxx) 可以修改。

**Comment by nuan1989** [comment]
> 通过这个文档下面的 https://baidu.github.io/amis/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA getComponentByName 拿到 page 那层的组件。然后通过 props.store.updateData(xxx) 可以修改。

谢谢

**Comment by nuan1989** [comment]
> > 通过这个文档下面的[http://Baidu . github . io/amis/docs/start/入门# % E6 % 8E % A7 % E5 % 88% B6-amis-% E7 % 9A % 84% E8 % A1 % 8C % E4 % B8 % BA](https://baidu.github.io/amis/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA)getComponentByName拿到页那层的组件。然后通过props.store.updateData(xxx)可以修改。
> 
> 谢谢



> 通过这个文档下面的 https://baidu.github.io/amis/docs/start/getting-started#%E6%8E%A7%E5%88%B6-amis-%E7%9A%84%E8%A1%8C%E4%B8%BA getComponentByName 拿到 page 那层的组件。然后通过 props.store.updateData(xxx) 可以修改。

![1](https://user-images.githubusercontent.com/43518669/91000984-1c269a80-e5fd-11ea-87ee-2e7372429563.png)

![2](https://user-images.githubusercontent.com/43518669/91000993-234da880-e5fd-11ea-888c-08e5ea54d92a.png)

请教一下, updateData方法的参数格式有没什么要求, 是json吗? 返回undefined

**Comment by nuan1989** [comment]
分享一下"amis onClick内修改data变量"

`var json = {
    "type": "page",
    "title": "Hello world ${data}",
    "name": "page1",
    "body": [
        {
            "type": "tpl",
            "tpl": "初始页面"
        },
        {
            "type": "button",
            "label": "确认",
            "actionType": "close",
            onClick: (e, props) => {
                var abc2 = props.store.updateData({
                    "data": "1111111111111"
                })
            }
        }
    ],
    "data": {
        "data": "这是测试按钮",
    }
}

`
