### ISSUE TITLE
crud中filter默认没有塞入

### ISSUE THREAD

**Issue by xinghe94** [baidu/amis#874]
#### 实现场景：
api接口的域名用模板字符串替换的时候 crud里的过滤条件默认不会自动带上

#### 存在的问题：
![image](https://user-images.githubusercontent.com/15528239/90851454-657dac80-e3a7-11ea-91fe-9ad4fb1c2bdb.png)
![image](https://user-images.githubusercontent.com/15528239/90851460-69a9ca00-e3a7-11ea-8076-e39640f316ee.png)
![image](https://user-images.githubusercontent.com/15528239/90851466-6d3d5100-e3a7-11ea-8f9f-de58f5d1db8e.png)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
一旦用变量后，就变成了白名单模式了，要发送什么就要主动配置。
