### ISSUE TITLE
select 组件设置 onEvent 事件动作

### ISSUE THREAD

**Issue by leung0727** [baidu/amis#8749]
#### 描述问题：

select 组件设置 onEvent 事件动作，在组件被 focus 时实现 reload 组件的 source 数据映射，3.2.0 版本正常，其余及以上版本 reload 失效

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/116611745/96ff6676-6443-4c70-a9db-38a7e9795350)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
       "type": "select",
       "name": "select",
       "source":"xxx",
       "onEvent" : {
        "focus": {
          "actions": [
            {
              "actionType": reload"
            }
          ]
        }
      }
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by leung0727** [comment]
我是点击自身就触发reload，应该能获取到目标组件吧。
而且有个问题想请教下就是右侧下拉是通过左侧下拉选择来决定渲染什么组件(有文本输入框，下拉，级联，日期等)，当左侧下拉选择是两个 select 组件之间切换，reload就不会重新执行source数据源的刷新，不知道是什么问题？

**Comment by 2betop** [comment]
> 我是点击自身就触发reload，应该能获取到目标组件吧。

问题版本上需要指定 componentId 或者 componentName 来指定目标，默认不是自己，默认是没有就不处理了

> 而且有个问题想请教下就是右侧下拉是通过左侧下拉选择来决定渲染什么组件(有文本输入框，下拉，级联，日期等)，当左侧下拉选择是两个 select 组件之间切换，reload就不会重新执行source数据源的刷新，不知道是什么问题？

估计也是要指定刷新目标的

**Comment by leung0727** [comment]
我有动态指定对应的componentId 或者 componentName，但右侧是通过左侧下拉选择来决定渲染，有没有可能是左侧选择后就立马执行指定componentId 组件的reload，但右侧还没来得及渲染，因此reload触发之后，componentId 才绑定到select组件上，而且现在指定了componentId ，但select组件有options数据源和source数据源，当我从options数据源的select切换到source数据源的select，reload有触发但source没重新刷新，两个source数据源的select之间切换现在是没问题的
