### ISSUE TITLE
amis编译器里面如何自定义事件

### ISSUE THREAD

**Issue by wldwl** [baidu/amis#8760]
#### 实现场景：
我添加了自定义组件，自定义组件拖动到编译器里，如何在json里写入自定义事件？

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by wibetter** [comment]
参考下这个文档：https://aisuda.github.io/aisuda-docs/NPM%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E5%A6%82%E4%BD%95%E5%AF%B9%E6%8E%A5amis%E4%BA%8B%E4%BB%B6%E5%8A%A8%E4%BD%9C

**Comment by wibetter** [comment]
如果是为自定义组件的右侧属性面板补充事件配置，可以参考下已有plugin的配置：
<img width="658" alt="image" src="https://github.com/baidu/amis/assets/11958920/3ba272f8-2e8a-47e9-8424-41f6de7ec1da">
