### ISSUE TITLE
crud表格搜索表单无法自动获取url 上面参数

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#8769]
#### 描述问题：

crud表格搜索表单无法自动获取url 上面参数

#### 截图或视频：
url参数  &indextag=111， crud 搜索有个字段也叫indextag，无法自动填充进去

![WechatIMG4260](https://github.com/baidu/amis/assets/4401182/dc638a71-fa0a-4c3f-9059-26c6fc488e38)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm 3.5.2

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```

```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by CheshireJCat** [comment]
在 filter 中设置初始值
```
{
  "type": "crud",
  "filter": {
    "data": {
      "indextag": "${indextag}"
    }
  }
}
```
