### ISSUE TITLE
可视化编辑器中自定义插件时，如何对接数据

### ISSUE THREAD

**Issue by chaserstrong** [baidu/amis#8770]
#### 实现场景：
我想要自定义一个表单类型的插件，引入到编辑器中使用

#### 存在的问题：
看文档没找到表单类型的插件的value如何对接，希望能提供这方面的思路或文档或代码。
https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/editor#%E5%B1%9E%E6%80%A7%E8%AF%B4%E6%98%8E

**Comment by chaserstrong** [comment]
如果是用react渲染，找到了文档：
https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react#%E8%A1%A8%E5%8D%95%E9%A1%B9%E7%9A%84%E6%89%A9%E5%B1%95

但是还有一个问题是，如果我本身是借用amis的schema渲染的，如何获取schema里的那些data数据呢

**Comment by 2betop** [comment]
基本上是被 amis 接管了，没有输出，amis 直接负责将数据提交到后端。但是部分组件可以外部受控，比如纯 form 组件。可以通过 onChange， onSubmit 之类的 callback 拿到 data 产出

**Comment by chaserstrong** [comment]
@2betop 是的，我用onChange可以获取到select组件的变化。

**Comment by 2betop** [comment]
没有其他问题先关了，有问题再开
