### ISSUE TITLE
无法导入excel文件解析

### ISSUE THREAD

**Issue by taoyao-code** [baidu/amis#8776]
#### 描述问题：

无法导入excel文件解析，无法获取解析数据

#### 截图或视频：

<img width="1294" alt="image" src="https://github.com/baidu/amis/assets/38855041/3c6340af-33ef-4475-961c-950cef01d715">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "debug": true,
    "body": [
      {
        "type": "input-excel",
        "name": "excel",
        "label": "上传 Excel"
      }
    ]
  }
}
```

4. 操作步骤
官网文档链接：https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-excel

**Comment by nwind** [comment]
不知道啥版本的打包有问题，先用 https://baidu.github.io/amis/
