### ISSUE TITLE
自定义插件中，使用@FormItem注解后，如何自定义右侧的配置面板？

### ISSUE THREAD

**Issue by chaserstrong** [baidu/amis#8780]
#### 实现场景：
在amis-editor中，想要自定义表单类型的插件，使用了@FormItem注解后，原来在@render中配置的那些右侧配置项都失效了。请问这种情况下要如何配？

**Comment by 2betop** [comment]
没看懂，请补充信息

**Comment by chaserstrong** [comment]
@2betop 是我没看清，是能正常用的
