### ISSUE TITLE
日期组件配置表达式后，值格式不再生效

### ISSUE THREAD

**Issue by zhaoyinger623** [baidu/amis#8789]
#### 描述问题：

如下图

![image](https://github.com/baidu/amis/assets/62292666/8663eb6f-1057-44d6-9506-578d254b3493)
![image](https://github.com/baidu/amis/assets/62292666/5659d8ae-ec01-4887-8d15-23bbcd73812c)

**Comment by 2betop** [comment]
默认值设置得不对，应该是 `${DATETOSTR(NOW(), 'YYYY-MM-DD HH;mm:ss')}`

**Comment by zhaoyinger623** [comment]
好滴，谢谢，我试一下。但是如果默认值和值格式实现绑定，能降低用户歧义，不需要用户再做额外的操作了。

**Comment by 2betop** [comment]
#8652 重复了，要不这个关了？

**Comment by zhaoyinger623** [comment]
好滴，可以关了
