### ISSUE TITLE
自定义了一个权限包裹容器，可以配置权限代码，想通过配置的权限代码调用context中的方法进行显示隐藏控制

### ISSUE THREAD

**Issue by hooli67** [baidu/amis#8790]
#### 实现场景：
自定义了一个权限包裹容器，可以配置权限代码，想通过配置的权限代码调用context中的方法进行显示隐藏控制，效果见下图：
<img width="1238" alt="image" src="https://github.com/baidu/amis/assets/126787744/19dd6bfe-d3d6-4224-9f58-c1ecd8e1b142">

右侧配置面板 配置代码如下：
```
{
            title: '权限',
            body: [
              getSchemaTpl('accessCode', {
                label: '权限代码'
              }),
            ]
          },
```
在renderAmis中的context中自定义了权限校验代码如下：
<img width="884" alt="image" src="https://github.com/baidu/amis/assets/126787744/9680d544-6e1f-441e-b6eb-3a520ca96baf">

#### 存在的问题：
能配置权限代码，但是不知道如何用配置的权限代码调用context中的access.can方法控制控件是否显示

#### 当前方案：
当前控制权限的方式是通过是否可见当中调用表达式的方式实现，见下图：
<img width="741" alt="image" src="https://github.com/baidu/amis/assets/126787744/6ef66f75-96d6-4443-b68f-0171a07f6c62">

```
{
  "type": "button",
  "id": "u:8659ebd8e905",
  "label": "按钮",
  "onEvent": {
    "click": {
      "actions": [
      ]
    }
  },
  "visibleOn": "access.can(['1111'])"
}
```

**Comment by 2betop** [comment]
就是这样用的

**Comment by hooli67** [comment]
> 样用的

老哥，我界面上在线配置权限码，怎么实现在组件内部自动根据配置的权限代码调用方法实现隐藏组件呢

**Comment by 2betop** [comment]
我们平台就是用这个方式，直接写在 visibleOn 上或者写在 disabledOn 上

**Comment by hooli67** [comment]
已解决，非常棒

**Comment by walingcc** [comment]
> 已解决，非常棒

大佬，请问下，如何解决的呢，能贴个代码吗

**Comment by hooli67** [comment]
> > 已解决，非常棒
> 
> 大佬，请问下，如何解决的呢，能贴个代码吗

解决不到visibleOn里面不能调用方法

**Comment by 151819880412** [comment]
能贴一下  权限包裹容器  的代码吗？
