### ISSUE TITLE
自定义插件事件无响应

### ISSUE THREAD

**Issue by hanhango** [baidu/amis#8792]
#### 实现场景：
自定义插件实现对页面的成员赋值

#### 存在的问题：
模仿原生插件Button click发请求并成员赋值事件JSON，但没有任何效果

#### 当前方案：
模仿原生插件Button click发请求并成员赋值事件JSON，但点击按钮后没有触发click事件
这是正常可以触发click事件的Button插件JSON源码
<img width="264" alt="image" src="https://github.com/baidu/amis/assets/44162509/2b6ce7e4-02ed-428d-850b-39b520ca8b92">

这是我自己写的自定义插件的JSON源码，无法触发click事件
<img width="465" alt="image" src="https://github.com/baidu/amis/assets/44162509/fd17c6a0-9598-4e85-9f04-59f70e1500ac">

怀疑是不是我直接赋值的关系导致无法触发。这是我的写法
```
this.context.schema.onEvent = {
          click: {
            actions: [
              {
                ignoreError: false,
                outputVar: 'responseResult',
                actionType: 'ajax',
                options: {},
                api: {
                  url: this.apiURL.value,
                  method: this.apiMethod.value,
                  requestAdaptor: '',
                  adaptor: '',
                  messages: {},
                  data: this.list.reduce((pre, curr) => {
                    pre[curr.keyName] = curr.valueName;
                    return pre;
                  }, {})
                }
              },
              {
                componentId: this.manager.store.schema.id,
                ignoreError: false,
                actionType: 'setValue',
                args: {
                  value: this.pageList.reduce((pre, curr) => {
                    pre[curr.keyName] = curr.valueName;
                    return pre;
                  }, {})
                }
              }
            ]
          }
        };
```

比较着急，希望路过有解决方案的大佬也可以评论下，谢谢

**Comment by 2betop** [comment]
my-button 的 react 组件里面有调用 this.props.dispatchEvent('click') 吗？

**Comment by hanhango** [comment]
> my-button 的 react 组件里面有调用 this.props.dispatchEvent('click') 吗？
我尝试了一下，会打印yes，但还是没有调用到JSON的click事件
<img width="619" alt="image" src="https://github.com/baidu/amis/assets/44162509/eeb59fdc-3ce9-469a-b786-1a6d730b384f">

**Comment by 2betop** [comment]
试试这个 `this.props.dispatchEvent('click', this.props.data) `

**Comment by hanhango** [comment]
> 试试这个 `this.props.dispatchEvent('click', this.props.data) `

解决了，感谢大佬！能不能顺带问下，我注册了my-button之后再拉原生的按钮组件开始警告并且无法正常渲染了是什么原因呀。
![image](https://github.com/baidu/amis/assets/44162509/8d9e4037-5a78-4b41-8dc2-bfcfec24de17)
![image](https://github.com/baidu/amis/assets/44162509/0ee3a5c0-8004-4daf-b818-dbc8525d71b0)

**Comment by 2betop** [comment]
这个警告跟你的代码无关，后续会干掉那个 warning #8788

**Comment by hanhango** [comment]
> 这个警告跟你的代码无关，后续会干掉那个 warning #8788

了解，但是button组件的外观设置那里显示找不到对应的渲染器了，这个大佬知道是为啥吗，我没有去对原生button配置面板做任何的操作诶

**Comment by 2betop** [comment]
会不会是因为你安装了多个 amis 的原因？

**Comment by hanhango** [comment]
> 会不会是因为你安装了多个 amis 的原因？

我这里拉的是amis-demo。  amis3.4的版本，现在升级到3.5.2报错消失了。感谢大佬！
