### ISSUE TITLE
3.5.2版本下启用千分位和双精度的inputNumber组件无法正常输入小数

### ISSUE THREAD

**Issue by JYPang7** [baidu/amis#8795]
#### 描述问题：

3.5.2版本下启用千分位和双精度的inputNumber组件无法正常输入小数，在3.2.0版本时是正常的，目前确定原因是变更了数字输入框的formatter，导致在输入过程中进行了数字value格式化操作，从而引发输入偏移、小数不能正常输入。

在inputNumber.tsx中这一块代码的改造不能根治该问题，请确认。
##“
 // 取真实用户输入的值去改变光标的位置
  @autobind
  changeCursorPos(value: number)   ”##

#### 截图或视频：

可以把schema粘贴到官网组件inputNumber样例中复现

#### 如何复现（请务必完整填写下面内容）：

1.schema样例如下：
{
  "type": "page",
  "body": {
    "type": "form",
    "debug": true,
    "api": "/amis/api/mock2/form/saveForm",
    "data": {
      "number2": 3.1234
    },
    "body": [
      {
        "type": "input-number",
        "name": "number1",
        "label": "数字",
        "kilobitSeparator": true,
        "precision": 2,
        "step": 0.01,
        "value": 2.98786
      },
      {
        "type": "input-number",
        "name": "number2",
        "label": "数字2",
        "kilobitSeparator": true,
        "precision": 3,
        "step": 0.001
      },
      {
        "type": "input-number",
        "name": "number3",
        "label": "数字3",
        "kilobitSeparator": true,
        "step": 0.001,
        "description": "不设置precision，仅设置step, 实际精度为3"
      }
    ]
  }
}

**Comment by dengdamei** [comment]
最新版本还有问题，鼠标移到小数点前输入数字，会跳到后面去
