### ISSUE TITLE
事件动作ajax请求网址带端口号提示invalid api url

### ISSUE THREAD

**Issue by leaf188** [baidu/amis#8796]
#### 描述问题：

下拉按钮，按钮动作配置点击事件发送ajax请求，网址带端口号，点击按钮提示Invalid api url

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`js sdk 3.5.2`

**Comment by 2betop** [comment]
请贴一下问题 api 地址

**Comment by lengqingfeng** [comment]
跟我那个是一个问题，需要把你们引用的版本升级也要，不只是编辑器。

**Comment by leaf188** [comment]
@2betop ``

**Comment by 2betop** [comment]
@leaf188 不能复现呢，是否版本不对？

<img width="1056" alt="image" src="https://github.com/baidu/amis/assets/2698393/bd0a27d8-2dc8-4efc-94fe-6bfc6ea1634e">

请升级版本，有问题再 reOpen
