### ISSUE TITLE
请问amis我可以将schema当做一个模板来用，动态生成页面么？

### ISSUE THREAD

**Issue by yuyijq** [baidu/amis#88]
比如类似这样的：
render(schema); 
schema后端可以通过接口提供，然后渲染出定制化的页面来

**Comment by 2betop** [comment]
渲染之前通过ajax 获取 schema 然后再 render 就可以了，这没什么特别的吧。

**Comment by yuyijq** [comment]
@2betop 不好意思，我是个后端，主要是现在的“快速开始”这个文档，一上来就是讲渲染器，没怎么看明白怎么接入。。
