### ISSUE TITLE
如何封装amis的组件后，仍旧暴露组件的所有配置项

### ISSUE THREAD

**Issue by chaserstrong** [baidu/amis#8800]
#### 实现场景：
在写amis-editor的plugins时，想要封装下amis的组件，比如在业务里有一个城市下拉组件，需要调用接口获取下拉数据，想要把这个封装成一个业务组件。这个情况下，这个业务组件的配置项只能通过plugin里手写controls提供吗？还是有什么可以继承amis下拉组件的方法？

**Comment by wibetter** [comment]
可以继续现有的plugin，比如继承SelectControlPlugin，但需要重新声明当前自定义组件的name、rendererName等信息（除panelBodyCreator外）：
<img width="749" alt="image" src="https://github.com/baidu/amis/assets/11958920/57082fe6-ab57-4a54-95a2-e20e59dc1dde">
