### ISSUE TITLE
LocationPicker 地理位置：增加参数将其设为不可手动选择（仅自动获取并填入）

### ISSUE THREAD

**Issue by DavidMastrenet** [baidu/amis#8802]
#### 是否关联于某个问题吗：
我现在利用amis开发了班级综合服务平台的前端，其中有一个课程签到功能需要获取位置，但是这个“LocationPicker”组件允许用户手动选择位置，也就失去了签到获取位置的作用。

#### 预期的解决方案：
通过引入一个参数（例如editable），限制用户手动选择位置

#### 其他可接受方案：
提供相应的思路也可以捏

#### 任何附加信息：
无

**Comment by wibetter** [comment]
@DavidMastrenet 感谢反馈，后续我们支持下。

**Comment by wibetter** [comment]
@DavidMastrenet 关注下这个提交：https://github.com/baidu/amis/pull/8834/commits

**Comment by wibetter** [comment]
这个提交合入后，可以通过配置autoSelectCurrentLoc和onlySelectCurrentLoc为true来实现你想要的效果。

**Comment by DavidMastrenet** [comment]
好的好的，谢谢！！
