### ISSUE TITLE
在自定义的容器组件内，有提供方法可以修改容器内的schema值吗

### ISSUE THREAD

**Issue by zhaoyinger623** [baidu/amis#8804]
#### 实现场景：
![image](https://github.com/baidu/amis/assets/62292666/e2c9f7af-0510-419d-848e-a8f14ed1de2a)
如上图所示，我们新增了一个“新增表单”的自定义容器，在配置面板中用户可以勾选需要的表单项，我们会填充到“新增表单”的容器中。

#### 当前方案：
目前的解决方案是：
第一步：深拷贝全局的schema即copySchema，深度遍历copySchema，通过用户正在操作的容器id，找到用户正在操作容器的schema片段即targetSchema；
第二步：修改targetSchema的body；
第三步，将修改后的copySchema赋值给全局schema，触发更新。

#### 存在的问题：
以上操作虽然可以实现，但是每次都对全局schema进行了深拷贝和重新赋值，想问问有没有其他可行的方法。

此外如果用户删除了容器中的元素，是否有对应的事件监听可以提供？

**Comment by wibetter** [comment]
@zhaoyinger623 在右侧属性面板中，可以通过context.node.updateSchema添加自定义属性字段（支持多个）：
<img width="651" alt="image" src="https://github.com/baidu/amis/assets/11958920/e53e42f8-edbe-4539-a557-d6cda915474c">

 <img width="1141" alt="image" src="https://github.com/baidu/amis/assets/11958920/ef84e69e-28ae-496b-a3be-96b95b5b0930">

**Comment by zhaoyinger623** [comment]
如果我更新了配置面板的值，context没有重新打印，证明panelBodyCreate没有重新执行，context.node.schema取值会不准确，从而导致我勾选的值依然不能添加到容器中。请问有解吗。
<img width="593" alt="image" src="https://github.com/baidu/amis/assets/62292666/01935b08-202d-4f12-81cf-7bf8d0730bdd">
