### ISSUE TITLE
如何调节锚点导航的大小？

### ISSUE THREAD

**Issue by hanhango** [baidu/amis#8807]
#### 实现场景：
我想要调节锚点导航插件的高度，而不是固定高度内向下滑动查看

#### 存在的问题：
不知道如何调节高度

#### 当前方案：
没找到调节高度的配置
![image](https://github.com/baidu/amis/assets/44162509/c7abdd0f-8ef0-416a-afb9-0a6e1e078206)

**Comment by wibetter** [comment]
@hanhango 可以通过添加style设置宽高：
<img width="1433" alt="image" src="https://github.com/baidu/amis/assets/11958920/e37ae5cb-5a3f-457f-aa83-aac5642b3b30">

**Comment by wibetter** [comment]
@hanhango 可以通过添加style设置宽高：
<img width="1433" alt="image" src="https://github.com/baidu/amis/assets/11958920/e37ae5cb-5a3f-457f-aa83-aac5642b3b30">

**Comment by hanhango** [comment]
> @hanhango 可以通过添加style设置宽高： <img alt="image" width="1433" src="https://user-images.githubusercontent.com/11958920/284179176-e37ae5cb-5a3f-457f-aa83-aac5642b3b30.png">

设置高度为100%后，锚点效果消失了，可以帮忙看下吗

**Comment by 2betop** [comment]
瞄点组件现在靠内滚，实际上应该不管是内滚还是外层容器滚动，都应该支持，目前外部容器滚动支持得有些问题，需要等后续优化

**Comment by 2betop** [comment]
不过你这个截图，内容都在可视区域，点击跳转肯定是没效果的

**Comment by hanhango** [comment]
> 不过你这个截图，内容都在可视区域，点击跳转肯定是没效果的

并不是的，是组件自带了高度，有部分内容要滚动才能看到。在可视区的时候跳转是有效果的。设置为高度100%后才失去锚点效果

**Comment by 2betop** [comment]
调整为 100% 后就没有内滚了吧，没有内滚目前是没办法调整定位的

**Comment by hanhango** [comment]
> 调整为 100% 后就没有内滚了吧，没有内滚目前是没办法调整定位的

好的，了解。请问这个优化会到下个版本吗

**Comment by wibetter** [comment]
@hanhango  设置高度为100%后，锚点效果消失，这个可以重新创建个issue卡片，标记成bug。

**Comment by wibetter** [comment]
@2betop 这里反馈的是怎么调整的宽高，如果设置宽高后暴露其他问题，需要创建个新的issue跟进下。
