### ISSUE TITLE
自定义插件数据独立的问题

### ISSUE THREAD

**Issue by hanhango** [baidu/amis#8809]
#### 实现场景：
在实现自定义插件(my-button)时定义了一些数据，用来做右边配置面板的数据做绑定。但我拖拉自定义插件写入了一些数据后，再拉一个新的my-button出来,发现数据被复用了。

#### 存在的问题：
希望能解决不同自定义组件之间数据复用的问题

#### 当前方案：
自定义插件定义数据：
<img width="578" alt="image" src="https://github.com/baidu/amis/assets/44162509/ad8a46d1-8145-4b5b-9681-47e417ccc217">

定义的数据和配置面板做了数据绑定
<img width="571" alt="image" src="https://github.com/baidu/amis/assets/44162509/839104ce-4433-4dad-b7e5-ac88b26e57c9">

具体步骤
1. 新拖进来一个my-button，并对其配置数据做更改
![image](https://github.com/baidu/amis/assets/44162509/83b97dea-b14d-41ff-b03b-31111a50e94c)
2. 再拖进来新的my-button，发现配置还是刚刚更改的数据，不是初始化的
![image](https://github.com/baidu/amis/assets/44162509/f92c281c-09a9-46fc-8c5f-4aa87b4c8cd6)

**Comment by wibetter** [comment]
@hanhango list 数据对象改放 state 试下。

**Comment by hanhango** [comment]
> @hanhango list 数据对象改放 state 试下。
请问是这样去写吗，我刚刚试了下还是共用了同一份数据诶
<img width="408" alt="image" src="https://github.com/baidu/amis/assets/44162509/e43bdf22-542c-45bd-806a-7af4a7653909">

**Comment by wibetter** [comment]
@hanhango 是指react组件的state中，
<img width="771" alt="image" src="https://github.com/baidu/amis/assets/11958920/a85bdf32-5ab2-4fa6-a2d6-f0cdaae91cdd">

**Comment by hanhango** [comment]
> @hanhango 是指react组件的state中， <img alt="image" width="771" src="https://user-images.githubusercontent.com/11958920/284223612-a85bdf32-5ab2-4fa6-a2d6-f0cdaae91cdd.png">

我需要改的是配置面板的数据，我看官方文档配置面板用的是class继承basePlugin去做更改，amis-editor-demo项目中继承的BasicEditor，但也是class。而React组件写的是渲染器的内容。配置面板如何用react组件做更改呢

**Comment by wibetter** [comment]
@hanhango 先确认下改用state还会不会存在你说的问题？然后再说下一个问题吧

**Comment by hanhango** [comment]
> @hanhango 先确认下改用state还会不会存在你说的问题？然后再说下一个问题吧

我问的其实是同一个问题，配置面板那块官方编辑器demo用的就是class而不是react组件。渲染器用的才是react组件，我是模仿着写的

**Comment by wibetter** [comment]
@hanhango 截图说先你指的是哪块，这种写法是不规范的，需要干掉或者换成正常的写法示例，避免误导更多人。

**Comment by hanhango** [comment]
> @hanhango 截图说下你指的是哪块，这种写法是不规范的，需要干掉或者换成正常的写法示例，避免误导更多人。
这个写法是我看官方文档和编辑器demo关于配置面板那里看到的。我看demo组件用react组件写的是渲染器而不是配置面板那块
<img width="527" alt="image" src="https://github.com/baidu/amis/assets/44162509/6aeeef5f-f88e-4b86-8496-6586016b2d0c">

**Comment by wibetter** [comment]
plugin中这么用，确实会存在数据复用的问题，因为页面中创建的多个同类型的组件用的是同一个plugin实例。所有要避免在plugin中这样设置和存储数据。正常使用情况，组件关联的数据我们都是存在每个组件的schema中的。然后通过配置面板更新当前组件schema的数据。
