### ISSUE TITLE
input-text maximum校验不生效

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#8811]
#### 描述问题：

input-text maximum校验不生效

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/48573389/95198ddf-9bd3-4840-bc1d-3b82720aee6f)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网 https://aisuda.bce.baidu.com/amis/zh-CN/components/form/formitem#%E6%A0%BC%E5%BC%8F%E6%A0%A1%E9%AA%8C

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
 {
        "type": "input-text",
        "label": "文本",
        "name": "text",
        "validations": {
          "isNumeric": true,
          "minimum": 0,
          "maximum": 9
        },
        "validateOnChange": true,
        "description": "请输入数字类型文本"
      }
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by wibetter** [comment]
@Liary0 默认校验是当进行行为操作时（默认是表单提交时，对表单项进行校验），如果你想每次表单项的值发生变化的时候就校验，请配置"validateOnChange": true。
<img width="1389" alt="image" src="https://github.com/baidu/amis/assets/11958920/59f735d9-b1a1-4eeb-aaf3-51d9c13420d3">
