### ISSUE TITLE
image图片上传失败

### ISSUE THREAD

**Issue by zengqinchris** [baidu/amis#882]
#### 实现场景：
请简单描述你想要实现的原始场景，
![image](https://user-images.githubusercontent.com/44901627/90951110-312eec80-e48a-11ea-96b4-b8c5ae11e5b7.png)
我 是用image控件来上传图片，选择图片的图片的时候无法上传

![image](https://user-images.githubusercontent.com/44901627/90952534-ed8eaf80-e496-11ea-8ece-c304a9de1015.png)

后端的接口一直无法获取图片的属性值

```
{
                            "name": "event_image_name",
                            "label": "事件对应的需求点位图片：",
                            "type": "image",
                            "autoUpload": true,
                            "toggled": true,
                            "reciever": "post:/event/xxxx/add",
                            "crop": true,
                            "fileField": "images/event"
                        },
```

**Comment by RickCole21** [comment]
换个`fileField`试试，别加`/`
