### ISSUE TITLE
自定义容器组件内修改schema的方法

### ISSUE THREAD

**Issue by zhaoyinger623** [baidu/amis#8823]
#### 实现场景：
我们 **自定义** 了一个**容器组件**，支持用户自由添加元素，
请问容器组件有提供用户**新增或者移除元素的监听方法**吗。容器组件有类似updateSchema的方法可以提供用来**更新容器的schema**吗，因为我们想用户新增某些组件的时候，往容器组件中添加一些配置。

**Comment by 2betop** [comment]
如果说的是设计态需求，组件本身应该是不需要任何监听的，因为 schema 变化（拖入子组件，或者删除子组件）会自动让组件的 props 变化，自动就会更新过来。（我假定你的子组件渲染是通过 this.props.render(this.props.xxxRegion)渲染的）

如果说的是运行态，这里应该不存在 schema 一说，应该操作结果产出是前端运行时的 data。比如 combo 里面加一行就是关联数组新增一条记录。

所以比较困惑，不知道如何回答

**Comment by 2betop** [comment]
问题不清晰，且缺乏反馈，先关了有问题再开
