### ISSUE TITLE
Amis文档图表不展示，报500错误码

### ISSUE THREAD

**Issue by levin80** [baidu/amis#8825]
![WechatIMG797](https://github.com/baidu/amis/assets/22766488/b38b28d4-aa3d-4158-8e5a-c7851db8b896)

链接：https://aisuda.bce.baidu.com/amis/zh-CN/components/chart 中 https://aisuda.bce.baidu.com/amis/pkg/charts.js 加载500错误，导致图表无法展示，看不到图表效果，影响学习及使用；

Amis文档管理员请帮忙解决，谢谢！

**Comment by 2betop** [comment]
先用这个代替，https://baidu.github.io/amis/zh-CN/components/chart

aisuda.bce 那个同步有点延后，下次平台上线会解决这个问题

**Comment by levin80** [comment]
@2betop  ok,非常感谢！
