### ISSUE TITLE
npm run dev报错[ERROR] parser.0: Cannot read property 'rest' of undefined

### ISSUE THREAD

**Issue by FatDong1** [baidu/amis#885]
#### 描述问题：
`npm run dev`报错

```
[ERROR] parser.0: Cannot read property 'rest' of undefined
```

#### 截图或视频：
![image](https://user-images.githubusercontent.com/22772600/90976013-16cd3f80-e56c-11ea-9ae9-e3457112dffc.png)

#### 如何复现（请务必完整填写下面内容）：
```
npm run dev
```

3. 操作步骤
```
npm run dev
```

**Comment by FatDong1** [comment]
应该是prismjs里面没有schema这个语言导致的报错

**Comment by 2betop** [comment]
先把这个parser注释了把。
![image](https://user-images.githubusercontent.com/2698393/95553509-4b745800-0a41-11eb-9f39-5f5c3b1973cb.png)

**Comment by yinchengyao** [comment]
你把 md-parser.js 文件下的 /```(schema|html)(?::(.*?))?\n([\s\S]*?)```/g, 正则表达式替换成 /```(schema|html)(?::(.*?))?[\n|\r]([\s\S]*?)```/g,就行了
