### ISSUE TITLE
表单项校验接口抛异常没有提示

### ISSUE THREAD

**Issue by snowing-x** [baidu/amis#8850]
#### 是否关联于某个问题吗：
表单项校验接口如果本身抛出了异常，现在只有控制台能看到error，没有notify的提示，用户无法感知到

#### 预期的解决方案：
和其它接口一样，能够通过notify提示用户

**Comment by allenve** [comment]
接口返回是什么样子的？

**Comment by snowing-x** [comment]
我描述的场景是httpCode不是200的情况，我看表单项的validate方法里没有catch异常
<img width="610" alt="企业微信截图_c3e2e402-6e2a-4c13-96bb-4b47d80bc9b6" src="https://github.com/baidu/amis/assets/51695385/bc1ed66b-e8f0-4b9d-a202-b2805a787b2d">

**Comment by snowing-x** [comment]
我描述的场景是httpCode不是200的情况，我看表单项的validate方法里没有catch异常
<img width="610" alt="企业微信截图_c3e2e402-6e2a-4c13-96bb-4b47d80bc9b6" src="https://github.com/baidu/amis/assets/51695385/bc1ed66b-e8f0-4b9d-a202-b2805a787b2d">

**Comment by allenve** [comment]
确认了一下  这里的fetcher是统一的   如果错误会有notify   所以还是得看看你的返回是啥

**Comment by snowing-x** [comment]
可以试一下最简单的，配一个不存在的api给validateApi，这样httpCode肯定是404，但是没有notify提示
