### ISSUE TITLE
Input-Table setValue存在分页时数据更新错误！

### ISSUE THREAD

**Issue by wwsheng009** [baidu/amis#8853]
#### 描述问题：

当input-table存在分页时，使用setValue更新行数据，并指定index，不会更新当前页面的index指向的行数据，而是修改了前面分页的数据。

比如input-table的行数据有20条，使用setValue,index = 1,并不会更新第11条数据，而是更新了第1条数据。

另外在onEvent中取到input-table的index是当前页面的index，如果有办法计算出当前行在数据集中的实际index也行，但是并没有找到相关的方法或是属性。

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis-3.5.3

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
            "groupType": "component",
            "actionType": "setValue",
            "args": {
              "value": {
                "&": "$$"
              },
              "index": "${index}"
            },
            "componentId": "model_columns"
          }
        ],
```

4. 操作步骤

创建input-table，并启用分页，通过对话框按钮更新当前行数据。

**Comment by wwsheng009** [comment]
目前折衷的方法是在事件里计算出正确的index。期望有更好的处理方法。

```js
{
                                            "actionType": "custom",
                                            "script": "debugger;const page = event.context.scoped.getComponentById('model_columns').state?.page;\n const idx = (page ? page - 1 : 0)  * event.context.scoped.getComponentById('model_columns').props?.perPage + event.data?.index;\n event.setData({...event.data,'__index':idx});\n"
                                          }
```

**Comment by 2betop** [comment]
新版将处理上下文数据，index 直接就是带偏移的
