### ISSUE TITLE
crud下checkbox不能选中问题

### ISSUE THREAD

**Issue by ljinkai** [baidu/amis#8857]
#### 实现场景：
在crud下进行多行数据的选中
#### 存在的问题：
在官方的例子中，和我自己本地调试的代码里，虽然设置的是多选，但是，点击一个只有最新的选中，之前的点击选中不生效
#### 当前方案：
无

![WX20231122-195732](https://github.com/baidu/amis/assets/2224673/8783202b-f311-4b64-a166-670872482526)

```
code here...
```

**Comment by wanglinfang2014** [comment]
这个是因为近期改动导致的，目前已修复https://github.com/baidu/amis/pull/8852
