### ISSUE TITLE
最新版getComponentById无效

### ISSUE THREAD

**Issue by Sybiil** [baidu/amis#8864]
#### 描述问题：

升级到最新版后，getComponentById拿不到组件了，查看了issue改成getComponentByName里虽然实现了功能，但是有几点疑问。

1 getComponentById无效到底是bug还是feature？这个破坏性改动真的很坑人，很多功能都依赖这个方法，不改就全部失效了。如果是bug希望尽快修复。
2 如果是feature，我觉得不太合理。因为用amis本来大部分甚至可以说绝大部分逻辑都是由amis完成的，需要额外处理的组件本来就是少数，这时用id指定组件非常准确和简洁。现在改成name以后，需要从最外层开始给每个组件加上name字段，才拿得到最后想要的组件。
比如一个常见的curd场景，想拿到某个表单里的某个输入框，name里有4、5个点了也要额外加很多name，无疑极大的增加了复杂度。希望能恢复到两个方法都支持的情况。

用amis很久了，很喜欢这个框架，确实能节约不少重复工作，但是这次的改动让我有点揪心。。。
祝amis越做越好。

**Comment by 2betop** [comment]
getComponentById 貌似没有修改啊，什么情况下拿不到？能否提供一下问题 schema？

**Comment by Sybiil** [comment]
稍等 我单独写个demo吧

**Comment by Sybiil** [comment]
> getComponentById 貌似没有修改啊，什么情况下拿不到？能否提供一下问题 schema？

[index.txt](https://github.com/baidu/amis/files/13446225/index.txt)
后缀名改成.html。1.7.0是我们升级前的版本。
这个demo运行以后，点新增按钮出现dialog以后，再在控制台输入
var o=amisInstance.getComponentById("add_form")
console.log(o)
是拿得到对象的
如果把引用js的版本号改成最新版 ，同样上面的操作，o就是undefined了。

这个1.7.0应该是去年某次更新后的版本，不是找这个bug我还真没注意到amis版本号涨的这么快，你们更新也辛苦了。
麻烦帮我看看这个问题吧，谢谢

**Comment by 2betop** [comment]
找到原因了，因为这个（#6807）的修改影响了 ，等 #8868 合入可以修复此问题

**Comment by Sybiil** [comment]
> 找到原因了，因为这个（#6807）的修改影响了 ，等 #8868 合入可以修复此问题

好的 谢谢
