### ISSUE TITLE
能否通过amis的组件动态渲染出其他的amis组件

### ISSUE THREAD

**Issue by wertycn** [baidu/amis#887]
#### 实现场景：
通过一个Amis组件，如何动态的渲染另一个组件，比如页面左边有一个Amis的JSON editor , 在编辑器内输入amis的json配置，然后在右边动态的渲染出来，仅通过amis的配置该如何实现呢？ 

#### 存在的问题：
1.  在现有的组件行为中，没有找到如何动态渲染出其他组件的行为，看到了一个通过name刷新其他组件的行为,不过这种目测主要用于数据变动后的刷新，而不是重新渲染一个新的组件
2.  如何获取到amis编辑器的值呢？ 

#### 当前方案：
目前的方案时json编辑器不通过amis组件实现，获取到值后，使用JS重新执行amis渲染，不过想了解仅通过amis配置能否实现这样的功能

**Comment by nwind** [comment]
如果是编辑器的整合自己实现吧

**Comment by wertycn** [comment]
新版本已提供type:amis 组件，可实现该功能  https://github.com/baidu/amis/pull/7586
