### ISSUE TITLE
请问怎么更新值，有什么方法吗

### ISSUE THREAD

**Issue by ityue** [baidu/amis#8876]
#### 实现场景：
我在自定义组件里 扩展属性，有两个属性，这俩属性是下拉框的，我在选择属性1后想将选择的值，带给属性2的值

![image](https://github.com/baidu/amis/assets/15856497/7a631f41-709b-438b-9940-fcdb3bbd50df)

#### 存在的问题：
现在是可以将数据带给属性2，但是需要在重新选择进入右侧设置区才可以，想了解怎么才能更新这处，让属性2的接口能随着属性1的操作后直接执行

#### 当前方案：
select 配置source请求接口，属性2的请求入参为请求1的值

```
choseAppState为属性1的值
$('tabs', [
      {
        title: '定制拓展',
        body: [
 $('select', {
            name: 'getCustomSchemaData',
            label: '属性2',
            type: 'select',
            searchable: true,
            source: `http://123.57.49.3:9001/api/aaa?perPage=10&t1=${component.state.choseAppState}`,
          })
```

**Comment by hsm-lv** [comment]
和amis联动机制一样，接口直接绑定属性1的name即可，比如属性1选择框的name是select1，那么属性2的select的source接口里可以直接写?t1=${select1}

**Comment by ityue** [comment]
感谢回复，目前是可以获取到属性1的数据，但是属性1的修改后，属性2的接口没有在执行。想做的是属性1修改完后，属性2的接口能够用属性1的值再次调用。属性1和属性2，都是用的select，请问需要怎么处理，十分感谢~

**Comment by ityue** [comment]
您好 是想如源码里的选取变化，重新构建面板。但此方法没有对外暴漏，有其他可以实现的方案吗？
![image](https://github.com/baidu/amis/assets/15856497/4a5fff84-a641-4066-8ca8-5c51a6bb5778)

**Comment by ityue** [comment]
使用buildPanels方法已解决 不过修改完需要加延迟
