### ISSUE TITLE
获取不到input-text属性

### ISSUE THREAD

**Issue by ityue** [baidu/amis#8890]
#### 描述问题：
想修改crud组件配置弹框里type为input-table里面的columns里的input-text属性。方法 使用setSchemaTpl方法，请问怎么获取到这个层级setSchemaTpl('input-table') 或 setSchemaTpl('input-text')都不可以

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/15856497/f5171c72-2627-43f2-abd2-d6bc08c5fb05)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
最新版 存在

4. 粘贴有问题的完整 `amis schema` 代码：
```
setSchemaTpl('input-table', {
  label: '字段名2',
  name: 'name',
  onBindingChange(field, onBulkChange) {
    onBulkChange(field.resolveEditSchema?.() || { label: field.label });
  }
});
```

5. 操作步骤
入口文件使用setSchemaTpl 设置crud组件配置弹框里的type为input-table里面的columns里的input-text属性

**Comment by ityue** [comment]
那crud组件配置弹框里type为input-table里面的columns里的input-text属性需要通过什么方式修改呢？

**Comment by lurunze1226** [comment]
Duplicate with #8871
