### ISSUE TITLE
在vue2项目里引入editor编辑器并开发自定义组件，拖拽生成的json文件，给另一个vue2项目使用，目前有实现方案吗？

### ISSUE THREAD

**Issue by DanQingKeE** [baidu/amis#8894]
就是项目A引入editor，开发自定义组件，生成json
在项目B作展示
都是使用vue2，目前能实现吗？

**Comment by wibetter** [comment]
这个应该不是很难实现的问题吧，比如：A项目生成的json，保存到服务端C，B项目通过接口从服务端C获取项目A保存的json。

**Comment by DanQingKeE** [comment]
@wibetter 流程的确是这样，难点是vue项目引入editor编辑器，这个好像没有vue版本的？
然后是项目B拿到的json是包含了项目A的自定义组件的，项目B安装的官方amis是没有那些自定义组件呀

**Comment by citynook** [comment]
@DanQingKeE vue2里引入react组件，可使用下面的第三方组件实现：https://github.com/devilwjp/vuereact-combined，虽然可能会出些问题，但至少能用。

在项目B中用json渲染页面，可使用 amis 提供的 SDK 实现。

**Comment by wibetter** [comment]
@DanQingKeE 可以参考amis-widget-cli中自定义组件的打包方式，插件（对接amis-editor需要）和渲染器（注册amis自定义组件需要）分开打包，然后其他项目需要使用这个自定义组件，只需要引用对应渲染器打包后的js脚本即可。

**Comment by wibetter** [comment]
@DanQingKeE 目前amis-editor没有提供vue版，也没有sdk实现，你可以将页面设计器独立出来，改用react实现，实现页面的可视化设计，设计后的页面保存到服务端，其他项目就可以获取这个页面的json，使用ams sdk 渲染。

**Comment by DanQingKeE** [comment]
@wibetter 目前思路是编辑器用amis-editor-amis项目，用iframe嵌入vue的项目，然后开发的自定义的组件代码copy去amis源码那去生成sdk。不晓得能不能行得通。

**Comment by DanQingKeE** [comment]
> 不用这么麻烦的吧~~我在vite+vue3的项目中，用veaury插件加载amis editor组件，基本上可以正常使用，将json保存到数据库中，然后用amis sdk在页面中渲染 json 生成页面就能直接使用了。当然了，自定义组件没有试过，但amis带的组件都没啥问题。
> 
> vue2项目中可以用 https://github.com/devilwjp/vuereact-combined 这个组件加载amis editor。
> 
> 不需要使用 iframe，正常的页面交互就行了。

我这需求主要是移动端的，所以需要写蛮多自定义组件的，我看看这个能不能支持。

**Comment by citynook** [comment]
@DanQingKeE 难道页面设计也要在移动端做吗?我的理解是设计在PC Web端做，然后在移动端做展示，展示的时候就可以用 amis sdk 渲染生成页面。

**Comment by DanQingKeE** [comment]
@citynook 是在PC端设计，移动端展示，问题就是移动端引入官方的amis是没有我的自定义组件得

**Comment by citynook** [comment]
@DanQingKeE o~明白了，我没玩自定义组件这一块，要是有方案了也期望能分享下~

**Comment by citynook** [comment]
@DanQingKeE o~明白了，我没玩自定义组件这一块，要是有方案了也期望能分享下~

**Comment by citynook** [comment]
@DanQingKeE o~明白了，我没玩自定义组件这一块，要是有方案了也期望能分享下~

**Comment by wibetter** [comment]
@DanQingKeE 移动端展示自定义组件没有展示，应该是没有正常加载自定义组件的渲染器脚本，需要确保这个脚本加载完成才能正常渲染自定义组件。

**Comment by DanQingKeE** [comment]
> @DanQingKeE 移动端展示自定义组件没有展示，应该是没有正常加载自定义组件的渲染器脚本，需要确保这个脚本加载完成才能正常渲染自定义组件。

我看了vue2-amis-custom-widget项目，看不太懂这个项目，能在已有vue项目引入么，编辑器是在哪引入的，打包出来是只有一个自定义组件？

**Comment by wibetter** [comment]
@DanQingKeE  vue2-amis-custom-widget 是一个vue2的自定义组件模板，主要用于参考 封装现有vue的业务组件 注册到爱速搭平台使用。

**Comment by wibetter** [comment]
类似vue2-amis-custom-widget这类自定义组件，打包后的脚本可以直接引入amis项目使用，但需要确保先加载自定义组件脚本再渲染amis页面，避免自定义组件渲染异常（自定义组件还未注册）。
