### ISSUE TITLE
crud组件能否保留列元素内的换行功能

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#8897]
#### 实现场景：
客户端的评论存在换行的情况，crud组件默认将列元素内的换行符替换为空格，能否保留列元素内换行功能？

**Comment by nwind** [comment]
这是浏览器的默认行为，FAQ 里有提解决方案 https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/faq#%E5%A6%82%E4%BD%95%E6%8D%A2%E8%A1%8C
