### ISSUE TITLE
linux环境，chrome报错Uncaught [ModJS] Cannot find module `index.html`

### ISSUE THREAD

**Issue by Irisxu** [baidu/amis#890]
![image](https://user-images.githubusercontent.com/6022913/91015091-29538180-e61d-11ea-84c1-2498134968e9.png)
后端无报错，前端报错。mac上正常，linux上异常

**Comment by nuan1989** [comment]
linux大小写敏感, 你是否有大小写命名?

**Comment by nuan1989** [comment]
你是编译后打不开, 还是在linux编程调试?

**Comment by nwind** [comment]
有可能是大小写但不确定，在 mac、windows 上开发吧，没必要使用 linux
