### ISSUE TITLE
crud 整体流程使用问题。

### ISSUE THREAD

**Issue by li2568261** [baidu/amis#891]
我想本地运行demo，但是远程post, houtai.baidu.com存在跨域，我想完整的跑完一个crud流程，所以把错误请求都正常返回。
![image](https://user-images.githubusercontent.com/4476377/91026239-16e14400-e62d-11ea-8628-811dbfbfe438.png)
使用表单组件代码如下：
![image](https://user-images.githubusercontent.com/4476377/91026455-560f9500-e62d-11ea-8034-7671726c1c85.png)
报错如下：
![image](https://user-images.githubusercontent.com/4476377/91026378-3f693e00-e62d-11ea-83aa-48923ed4b734.png)
已参考文档：
![image](https://user-images.githubusercontent.com/4476377/91026701-b1418780-e62d-11ea-8294-83c3dc550023.png)
但是`http://amis.baidu.com/v2/docs/api`打不开。

**Comment by 2betop** [comment]
一切都看着没问题，难道是 catch 的问题？

**Comment by 2betop** [comment]
直接 return Promise.resolve({status: 0, msg: ''}) 试试？

**Comment by 2betop** [comment]
catch 里面应该再包一层

return {
   data: {
      status: 0,
      msg: '',
      data: {}
   }
}

**Comment by li2568261** [comment]
可以了，真的太感谢了。
