### ISSUE TITLE
内网 npm 发版 @fex别名的作用

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#8918]
npm发版
请问@fex别名的作用？
发版后到@fex文件夹下，引用依赖下载404问题的可能原因？

**Comment by wibetter** [comment]
@coffin03  @fex/xxx 是我们内部的npm包，外部使用不需要带@fex。

**Comment by coffin03** [comment]
> @coffin03 @fex/xxx 是我们内部的npm包（仅百度内部网络可用），外部使用不需要带@fex。
也就是说如果我在内网 发版npm包 使用的话，并不需要执行publish-to-internal、publish-editor-to-internal脚本里的 内部包名称 替换部分是吗？

**Comment by wibetter** [comment]
@coffin03 是的。
