### ISSUE TITLE
拉取最近的amis-editor-demo报错

### ISSUE THREAD

**Issue by weikoiDYD** [baidu/amis#8919]
![17e1f141256f183f5ed0b81b4e2240d](https://github.com/baidu/amis/assets/142581888/bc5cc90c-ff38-4675-8298-0c70c2dce984)
     
报错：
TS2345: Argument of type 'typeof SchemaRenderer' is not assignable to parameter of type 'ComponentType<SchemaRendererProps>'.
  Type 'typeof SchemaRenderer' is not assignable to type 'ComponentClass<SchemaRendererProps, any>'.

**Comment by linzhixiang** [comment]
问题是怎么解决的呀，我也遇到了同样的问题
