### ISSUE TITLE
react 中使用自定义组件，通过配置 visibleOn :"条件表达式"，但组件 js 中内部无法获取这个 visibleOn 属性结果

### ISSUE THREAD

**Issue by leung0727** [baidu/amis#8920]
#### 描述问题：

react 中使用自定义组件，通过配置 visibleOn :"条件表达式"，但组件 js 中内部无法获取这个 visibleOn 属性最终是true/false，只能获取到字符串的表达式，例如 input-text 组件配置 visibleOn : "this._amisUserType =='customer'"，当条件不成立时，input-text 组件会隐藏，但我在 js 中主动获取 visibleOn 属性来做其余业务开发，无法得到 visibleOn 属性的结果是 true/false，在js中只能获取到字符串的"this._amisUserType =='customer'"，无法用其来进行业务上的判断

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/116611745/d9746013-9dae-4e53-8254-4751bf4ed34f)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
目前使用 3.4.2，但猜测和版本wu无相关
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
      "maxLength": 10,
      "showCounter": true,
      "required": true,
      "type":"text",
      "name":"__id",
      "size": "xs",
      "matchType": "=",
      "visibleOn": "this._amisUserType =='customer'"
    }
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
自定义组件，如果 visibleOn 条件不满足都不会渲染你的自定义组件呢？所以你无法做别的逻辑。换个属性名的话也许可以。

渲染器会自动 xxxOn 的表达式，把结果通过 props.xxx 下发

**Comment by leung0727** [comment]
visibleOn 条件不满足时会把组件进行隐藏的，只是在 js 中无法得到表达式结果

**Comment by 2betop** [comment]
不知道你说的 js 和组件什么关系

**Comment by leung0727** [comment]
就是我在组件内部通过this.props.visibleOn，拿到的结果是字符串的"this._amisUserType =='customer'",我想得到true/false来进行其他开发

**Comment by 2betop** [comment]
改成拿 `this.props.visible`

**Comment by leung0727** [comment]
好吧，谢谢
