### ISSUE TITLE
sdk生成 build.sh 脚本报错

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#8928]
![image](https://github.com/baidu/amis/assets/141314006/5fd4a4d4-5d5c-42f1-995a-220269751812)

**Comment by 2betop** [comment]
master 没有复现，github 已接入 ci，每次改动都会执行 sdk 构建逻辑，要有错误 ci 就会失败。所以我怀疑你们改源码了？

**Comment by zliang01** [comment]
你打包好了吗，我始终没有办法生成正常的sdk文件

**Comment by coffin03** [comment]
> 你打包好了吗，我始终没有办法生成正常的sdk文件


好了，使用master最新代码，记得把脚本文件中@fex别名替换部分去除掉

**Comment by zliang01** [comment]
我这的报错和您截图中的不一样，只是一直编译不成功，方便指导一下吗，有偿
![image](https://github.com/baidu/amis/assets/15192404/72207460-6b60-46be-afab-4023514d016b)
