### ISSUE TITLE
editor-demo中的字体文件路径错误问题?

### ISSUE THREAD

**Issue by ranwawa** [baidu/amis#8932]
#### 描述问题：

通过官方的amis-editor-demo启了个应用,做低代码开发

但是图标字体文件统统加载失败,导致界面上很多图标都看不见

amims-editor-demo是基于amis-widget-cli打包配置的,不知道去哪儿配置,图标文件的输出路径

需要请教下

#### 截图或视频：
下图是字体文件404截图.

<img width="743" alt="image" src="https://github.com/baidu/amis/assets/30344590/97b8b05d-3c63-46a2-b179-470958fdf04f">

该字体文件是通过css引入的

<img width="440" alt="image" src="https://github.com/baidu/amis/assets/30344590/5aa979be-eeee-4c21-bd5c-1d319cfb9412">

css文件打包后是放css目录下,而css代码里面又是引用的相对路径,但实际上打包后的目录结构如下

<img width="196" alt="image" src="https://github.com/baidu/amis/assets/30344590/ebcad88f-ae2a-4968-b407-a1d574fc0cd7">

所以404很正常

#### 如何复现（请务必完整填写下面内容）：

尝试修改amis.config.js中的webpack.module.rules规则,不生效
<img width="1017" alt="image" src="https://github.com/baidu/amis/assets/30344590/2d07b7ee-377f-4b2a-89df-46a9bebf3f17">

**Comment by ranwawa** [comment]
没办法通过webpack配置进行覆盖 .只能通过build.assetsPublicPath进行覆盖

**Comment by feng-1** [comment]
> 没办法通过webpack配置进行覆盖 .只能通过build.assetsPublicPath进行覆盖

老哥最后怎么解决的
