### ISSUE TITLE
请问页面链接中的携带参数是注入到哪里的呢

### ISSUE THREAD

**Issue by zhaoyinger623** [baidu/amis#8937]
#### 实现场景：
![image](https://github.com/baidu/amis/assets/62292666/79ce1061-c455-47dc-b539-005487e341e3)
如图所示，页面链接中携带了id的查询参数，在页面变量中没有看见。
![image](https://github.com/baidu/amis/assets/62292666/01f29c06-2048-475a-b4ad-dac4aa998678)
却依旧可以作为变量使用。
![image](https://github.com/baidu/amis/assets/62292666/b08e4ed8-63cd-4d1e-8797-4c030183578a)
在schema中也没有看见。
![image](https://github.com/baidu/amis/assets/62292666/399f35b5-7f0d-4ac8-8b75-700ca0dc3291)
请问这个参数是在编辑器中不会展示出来吗，是注入到哪里的呢。

**Comment by Tera-ravyn** [comment]
应该是直接保存到数据域里了，在上下文变量里可以看到，比page还要外一层

**Comment by zhaoyinger623** [comment]
请问您说的上下文变量在哪里看呢

**Comment by hsm-lv** [comment]
这个目前在上下文可视化里没有体现，代码的话可以直接通过id或者__query.id获取

**Comment by Tera-ravyn** [comment]
可视化其实也可以看到，组件的那个小虫虫图标就是上下文变量，在代码里也可以通过打印context对象查看目前数据域里的变量
