### ISSUE TITLE
3.5.3版本分页按钮样式没有对齐

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [baidu/amis#8958]
#### 描述问题：

3.5.3版本分页按钮样式没有对齐，主要是单页数量的那个下拉框比前面的数字大

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/15119304/2bb50ac4-3bc5-41d1-ac63-0bf52eda9a03)
![image](https://github.com/baidu/amis/assets/15119304/211abec8-d628-47de-9365-4be77cf74e0b)
![image](https://github.com/baidu/amis/assets/15119304/7ee32b5d-30e7-4ce4-a027-f395dc25ecbc)

#### 如何复现（请务必完整填写下面内容）：

官方文档也有同样问题，不管在哪个主题下

**Comment by qkiroc** [comment]
https://github.com/baidu/amis/pull/9340
