### ISSUE TITLE
CRUD组件单元格合并Bug

### ISSUE THREAD

**Issue by hsg4ok** [baidu/amis#8959]
#### 描述问题：

CRUD组件单元格合并有Bug，合并第一列。有的合并，有的不合并。

#### 截图或视频：

<img width="639" alt="image" src="https://github.com/baidu/amis/assets/2274281/195b05c1-7780-4407-a934-dd3ecee1bb24">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3.1.1 和 3.5.2 都有此问题

**Comment by hsg4ok** [comment]
这个表数据两百多行

**Comment by Miao0er** [comment]
这个问题没人解决么？
