### ISSUE TITLE
crud组件能否支持直接对列表元素进行操作

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#8961]
crud组件能否支持直接对列表元素进行操作

![image](https://github.com/baidu/amis/assets/48573389/d1a428f8-fd2e-411d-a59b-5299c86c7445)

**Comment by hsm-lv** [comment]
没太明白，可以具体说下列表内容无法正常显示是指什么吗？最好贴下代码

**Comment by Liary0** [comment]
![image](https://github.com/baidu/amis/assets/48573389/a477530e-2ac7-492d-a3a9-7ed293577f40)
原来列表的内容是这样的，设置成button之后列表内容就变成label了。
```
 {
        "name": "engine",
        "label": "Rendering engine",
        "type": "button",
        "actionType": "dialog",
        "dialog": {}
      },
```

**Comment by hsm-lv** [comment]
> ![image](https://private-user-images.githubusercontent.com/48573389/287120827-a477530e-2ac7-492d-a3a9-7ed293577f40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTY2MjksIm5iZiI6MTcwMTM5NjMyOSwicGF0aCI6Ii80ODU3MzM4OS8yODcxMjA4MjctYTQ3NzUzMGUtMmFjNy00OTJkLWEzYTktN2VkMjkzNTc3ZjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAyMDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZGQ4NmYxNmZkZDAxOGVmMjYwNTNhNDc4ZDAxZDgzZTM5ZDg5NGM5ZDZiYjRkNWE5NDZkMDM0YmI5YzE1MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rf0ILquRcABF3PW57uUTU2OlUcgR1hn6thkhl4jzNHk) 原来列表的内容是这样的，设置成button之后列表内容就变成label了。
> 
> ```
>  {
>         "name": "engine",
>         "label": "Rendering engine",
>         "type": "button",
>         "actionType": "dialog",
>         "dialog": {}
>       },
> ```

哦，明白了，你是想显示列内容，然后有交互对吧，可以直接添加事件动作，如下：
```json
{
  "name": "engine",
  "onEvent": {
     "click": {
       "actions": [
          {
            "actionType": "dialog",
            "dialog": {
              ...
            }
          }
       ] 
     }
  }
}
```

**Comment by Liary0** [comment]
ok 感谢
