### ISSUE TITLE
amis-editor编译出错TS2339

### ISSUE THREAD

**Issue by Ms-CutieSong** [baidu/amis#8964]
#### 描述问题：

编译报错  (!) Plugin typescript: @rollup/plugin-typescript TS2339: Property 'data' does not exist on type 'Readonly<ValidationControlProps>'.
src/renderer/ValidationControl.tsx: (52:20)
git拉的代码，对packages/amis-editor进行编译，有很多类似问题，这些问题对编译有影响吗？编译之后的包存在于哪里？
node版本：v16.0.0

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/42562279/2c54f38e-9b2d-4652-a628-acae75935afe)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
``npm` 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.5.3
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
npm run build

**Comment by igrowp** [comment]
这些报错不影响构建，执行完build后，会在当前包下生成lib、esm等文件夹存放打包后的产出，只是由于项目中在vscode配置了files.exclude配置，隐藏了这些文件夹。
可以在文件目录中找到这些打包产出
