### ISSUE TITLE
onEvent的actionType事件发送后是怎么接收的，目前遇见问题是执行事件后，数据变了。但是组件的值没有更新

### ISSUE THREAD

**Issue by ityue** [baidu/amis#8967]
#### 实现场景：
a组件修改后执行onEvent事件，修改name为creator的组件，name为creator的组件数据变了，但是组件内部并没有接收，如执行setVal赋值和reload都没执行。name为creator的组件为自定义组件，请问哪个方法是接收的

#### 存在的问题：
![image](https://github.com/baidu/amis/assets/15856497/57e19583-66b0-4e9a-b730-9ba543892384)
数据变了。但是组件的值没有更新
#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
"onEvent": {
    "change": {
      "actions": [
        {
          "actionType": "setValue",
          "componentName": "creator",
          "args": {
            "value": "芋艿"
          },
          "groupType": "component"
        },
        {
          "actionType": "reload",
          "target": "name"
        }
      ]
    }
  }
```

**Comment by ityue** [comment]
自定义组件部分是这么写的export default class Component extends React.Component {}。是用的FormItem注册代码为FormItem({
    type: TYPE,
    autoVar: true 
  })(Component); 请问是需要继承接收事件的方法吗？

**Comment by hsm-lv** [comment]
> #### 实现场景：
> a组件修改后执行onEvent事件，修改name为creator的组件，name为creator的组件数据变了，但是组件内部并没有接收，如执行setVal赋值和reload都没执行。name为creator的组件为自定义组件，请问哪个方法是接收的
> 
> #### 存在的问题：
> ![image](https://private-user-images.githubusercontent.com/15856497/286922225-57e19583-66b0-4e9a-b730-9ba543892384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTQ3MzksIm5iZiI6MTcwMTM5NDQzOSwicGF0aCI6Ii8xNTg1NjQ5Ny8yODY5MjIyMjUtNTdlMTk1ODMtNjZiMC00ZTlhLWI3MzAtOWJhNTQzODkyMzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAxMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NzUxMDQ1ZTMwYWIyMWZjZWY5MjQ5NjVlY2U3NzI2NjIyYjkzNGZjM2MxMmRlYWM2ODdiODZhNzRkYjE0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uD6WAaTMIzpa4w_7VCFT0XAB6U8kY4typZR1-KXGkAA) 数据变了。但是组件的值没有更新
> 
> #### 当前方案：
> 请粘贴你当前方案的完整 amis schema 代码...
> 
> ```
> "onEvent": {
>     "change": {
>       "actions": [
>         {
>           "actionType": "setValue",
>           "componentName": "creator",
>           "args": {
>             "value": "芋艿"
>           },
>           "groupType": "component"
>         },
>         {
>           "actionType": "reload",
>           "target": "name"
>         }
>       ]
>     }
>   }
> ```

代码里需要注意两点：1.componentName是当前层就近查找，componentId是全局查找（跨层级），所以可以更换成componentId；2.reload动作在事件动作机制中指定目标组件是通过componentId或componentName来指定的，这个与原来的联动机制不同，所以可以试试下面的方法：

```json
"onEvent": {
    "change": {
      "actions": [
        {
          "actionType": "setValue",
          "componentId": "xxxxx_id",
          "args": {
            "value": "芋艿"
          }
        },
        {
          "actionType": "reload",
          "componentId": "xxxxx_id"
        }
      ]
    }
  }
```

**Comment by hsm-lv** [comment]
> 自定义组件部分是这么写的export default class Component extends React.Component {}。是用的FormItem注册代码为FormItem({ type: TYPE, autoVar: true })(Component); 请问是需要继承接收事件的方法吗？

不需要，如果是正常注册为amis渲染器都是自动支持的

**Comment by ityue** [comment]
十分感谢您的回复，刚试了下换成componentId也不可以，目前是同级的修改。详细场景是写的自定义代码是对picker进行了封装，目前componentId或componentName都可修改picker组件内容，故怀疑是自己组件的封装有问题。请问是需要在继承这些属性吗？不过我继承了也不行呢
![image](https://github.com/baidu/amis/assets/15856497/58a374f0-75e9-42dd-889a-6bb6c44fa985)

**Comment by hsm-lv** [comment]
> 十分感谢您的回复，刚试了下换成componentId也不可以，目前是同级的修改。详细场景是写的自定义代码是对picker进行了封装，目前componentId或componentName都可修改picker组件内容，故怀疑是自己组件的封装有问题。请问是需要在继承这些属性吗？不过我继承了也不行呢 ![image](https://private-user-images.githubusercontent.com/15856497/287119819-58a374f0-75e9-42dd-889a-6bb6c44fa985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTU1MTksIm5iZiI6MTcwMTM5NTIxOSwicGF0aCI6Ii8xNTg1NjQ5Ny8yODcxMTk4MTktNThhMzc0ZjAtNzVlOS00MmRkLTg4OWEtNmJiNmM0NGZhOTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAxNDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MjhiOGQzMmM2NzE0ZTU4YzdkNDY5ZDU5NmEyYzM5NGI0ODZkNGJmZWQ1OGM3MzAyN2RhZGRiODJjNmFhZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mfVEeSz3efeM_T6aRwDTq7OFHIZdra06vlFf4Q5McU4)

哦，你是自定义封装的，那还需要scoped，可以参考 https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E6%8E%A5%E5%85%A5%E4%BA%8B%E4%BB%B6%E5%8A%A8%E4%BD%9C

**Comment by ityue** [comment]
感谢您的回复，您好 按照文档示例 import { render, ScopedContext } from 'amis';
export default class Component extends React.Component {
  static contextType = ScopedContext;
  constructor(props) {
    super(props);
    const scoped = this.context;
    scoped.registerComponent(this);  结果是this.context拿不到，报错 TypeError: Cannot read properties of undefined (reading 'registerComponent')。请问有个完整的例子吗？或怎么解决这问题

**Comment by hsm-lv** [comment]
> registerComponent

```javascript
import {ScopedContext} from 'amis-core';
import type {IScopedContext} from 'amis-core';

class XXXX extends React.Component{
  static contextType = ScopedContext;

  constructor(props: XXXXProps, context: IScopedContext) {
    super(props);
    context.registerComponent(this);
  }

  componentWillUnmount() {
    const scoped = this.context;
    scoped.unRegisterComponent(this);
  }
}
```
