### ISSUE TITLE
请问bulkActions里面的按钮支持visibleOn吗

### ISSUE THREAD

**Issue by chareice** [baidu/amis#898]
因为业务需要，要在CRUD的filter表单中，一个下拉选项为某个特定值时才显示特定的批量操作，是否可以通过的bulkActions的visibleOn属性来实现这个功能？

**Comment by RickCole21** [comment]
filter提交之后会同步到crud数据域中的，就可以用visibleOn联动了

**Comment by chareice** [comment]
> filter提交之后会同步到crud数据域中的，就可以用visibleOn联动了

有没有办法可以inspect、观察到数据域中的数据呢

**Comment by 2betop** [comment]
inspect 选中目标节点，然后点开 react 开发插件，component， 这个时候 $r 就是选中的节点的 component 实例，然后控制台输入以下内容就可以看了

$r.props.data
