### ISSUE TITLE
3.6.1 sdk版本无法使用fontawesome v6 版本的图标

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#8996]
#### 描述问题：
3.6.1 sdk版本无法使用fontawesome v6 版本的图标

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/11575908/d57e6ff2-242a-4d33-92cb-8c8a8cfd5e7f)

![image](https://github.com/baidu/amis/assets/11575908/17030a2b-3efa-4fcc-865c-09de91c9c794)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk3.6.1

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
   
    {
      "type": "icon",
      "icon": "fa-solid fa-y",
      "vendor": ""
    },
    {
      "type": "icon",
      "icon": "fa-regular fa-address-book",
      "vendor": "",
      "className": "text-info text-xl"
    },
   
  ]
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lurunze1226** [comment]
<img width="489" alt="image" src="https://github.com/baidu/amis/assets/36724300/e44ae7fc-8461-450d-8195-168f9a478adf">
@fortawesome/fontawesome-free的`6.0`版本干掉了svg 字体，后面确认没影响的话，晚点发布`3.6.2`

**Comment by lurunze1226** [comment]
Closed by [3.6.2](https://github.com/baidu/amis/releases/tag/v3.6.2)
