### ISSUE TITLE
请问下JSON Schema是手动编写的还是通过解析代码生成的？

### ISSUE THREAD

**Issue by Gezii** [baidu/amis#90]
比如这里 （ https://houtai.baidu.com/v2/schemas/page.json ） 的schema定义，理论上是应该跟渲染器可以支持的配置对应起来的。当某些渲染器的代码更新了导致配置字段也更新了，这时的schema是人为手工跟着维护还是可以通过最新代码解析生成呢？

**Comment by 2betop** [comment]
目前是手写的，已经写晕了
