### ISSUE TITLE
options动态传值

### ISSUE THREAD

**Issue by whitekyo** [baidu/amis#900]
有如下几个场景：
1.页面的三个select的数据来源于一个接口，这个需要如何处理？
2.一般编辑页面刷出来的时候，详情页接口和select的数据接口是分开的，我看了option被选中的配置，是把value写在select接口中，这种改动，服务端是肯定不会这么做的，这个需要如何处理？

我想就是options的source是否支持异步传入json去生成select，不是单单依赖接口返回？如果有，具体该怎么写？

**Comment by RickCole21** [comment]
1. 没看懂，是三个select的value值还是options来源同一接口
2. 详情接口里返回select的值就会[自动选中](https://baidu.gitee.io/amis/docs/components/form/options#%E9%BB%98%E8%AE%A4%E5%80%BC-%E8%87%AA%E5%8A%A8%E9%80%89%E4%B8%AD-value)的

**Comment by RickCole21** [comment]
无反馈，先关了
