### ISSUE TITLE
npm包发版引用后编辑器外观配置无法渲染问题，咨询打包脚本使用是否正确

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#9003]
#### 实现场景：
1、拉取官方master最新代码
2、执行脚本发版npm包
3、第三方项目引用依赖

#### 存在的问题：
![image](https://github.com/baidu/amis/assets/141314006/d002004a-0647-4579-a083-20be7e83a19d)

#### 当前方案：
去除脚本中@fex别名部分
执行脚本及顺序
npm i --legacy-peer-deps
sh publish-to-internal.sh
sh publish-editor-to-internal.sh
bash publish-theme.sh

npm引用
![image](https://github.com/baidu/amis/assets/141314006/e3e807df-9865-4d6d-9de2-91ae9c05c00a)

**Comment by coffin03** [comment]
> 请问解决了吗

没有

**Comment by mengxiangji** [comment]
@coffin03 兄弟，解决了吗

**Comment by coffin03** [comment]
> @coffin03 兄弟，解决了吗

解决了 就是因为下载了多个版本的包导致的 把子依赖也改成自己的私服就行了

**Comment by mengxiangji** [comment]
> > @coffin03 兄弟，解决了吗
> 
> 解决了 就是因为下载了多个版本的包导致的 把子依赖也改成自己的私服就行了

所有关于amis的包全用自己的私服吗？

**Comment by coffin03** [comment]
> > > @coffin03 兄弟，解决了吗
> > 
> > 
> > 解决了 就是因为下载了多个版本的包导致的 把子依赖也改成自己的私服就行了
> 
> 所有关于amis的包全用自己的私服吗？

对，假如底层项目里amis模块线上会使用amis-core依赖，那amis的package里的依赖地址也需要改成私服的包地址，总结就是保证整体底层项目的工程化依赖统一版本
