### ISSUE TITLE
crud能否扩大click事件触发范围

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#9010]
#### 实现场景：

![image](https://github.com/baidu/amis/assets/48573389/068ee51d-e75c-4590-b2f8-2a2097e6e2cc)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
{
        "name": "version",
        "label": "Engine version",
        "onEvent": {
          "click": {
            "actions": [
              {
                "actionType": "dialog",
                "dialog": {}
              }
            ]
          }
        }
      },
```

**Comment by Liary0** [comment]
这样确实可以，但是不能对该列使用sortable进行排序了

**Comment by igrowp** [comment]
如果要支持排序的话，可以将name字段在container组件这层再声明一次
{
  "type": "container",
  "name": "name",
  "sortable": true,
  ....
}
