### ISSUE TITLE
自行打包js sdk

### ISSUE THREAD

**Issue by zliang01** [baidu/amis#9016]
#### 实现场景：
我想自己打包一个js sdk

#### 存在的问题：
我刚pull下来的代码，比如3.4.x的分支，安装依赖后，启动成功，可以正常访问、打开页面，看起来功能正常。
执行npm run buil，各种失败，执行 npm run publish-to-internal 也失败。
首先就会提示  NODE_ENV 不是可执行的，我是在windows 11下的git bash进行执行，我于是使用了cross-env NODE_ENV=production进行修复，但是还是不行。

昨天有一次生成了js sdk，但是实际使用的提示amis undefined，能否有生成sdk的指导方案。
看之前的issue，有人说使用publish.sh，我看了现在的，并没有这个脚本。
package下的amis包， "publish-to-internal": "sh build.sh && sh publish.sh",  不存在publish.sh，折腾了挺久，没有打包成功
![image](https://github.com/baidu/amis/assets/15192404/8c85d6cb-2f44-4464-a086-d608ee929f12)

#### 当前方案：
而且有时候会提示下面这些

```
(!) Plugin typescript: @rollup/plugin-typescript TS2307: Cannot find module 'amis-ui' or its corresponding type declarations.
src/components/TimelineItem.tsx: (6:38)

6 import type {IconCheckedSchema} from 'amis-ui';
```

**Comment by 932808140** [comment]
我也想问这个问题

**Comment by 2betop** [comment]
linux 或者 mac 上应该是可以直接 `npm run build`  正常编译，windows，我们平时没这个环境，需要等后面找个环境调整一下脚本语法

**Comment by zliang01** [comment]
问题解决过了。有两个问题，第一个问题是，我用git bash环境执行npm install的时候，安装的包有问题，所以windows环境一定要用cmd执行包的安装。第二个问题，是我用的组件有问题，详细见这个，这个组件还有个循环引用的问题，造成打包后的顺序有点问题。
https://github.com/STDSuperman/super-image-cropper/issues/18

**Comment by zliang01** [comment]
> 我也想问这个问题

我这解决了，下载的源码。按照步骤，windows环境用cmd安装包是没问题的
