### ISSUE TITLE
amis-editor打包发布npm使用报The renderer with name "xxx" has already exists, please try another name!错误

### ISSUE THREAD

**Issue by mengxiangji** [baidu/amis#9019]
#### 描述问题：

amis-editor打包发布npm使用报The renderer with name "xxx" has already exists, please try another name!错误，把名字改后还有别的重复，请问怎么解决

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/42375179/f9030244-8d3e-4f7d-b03a-c1083d0956aa)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by mengxiangji** [comment]
已解决 amis包和自己发布到npm的包同时存在

**Comment by z54749412** [comment]
> amis包和自己发布到npm的

你好，如何解决的，我也遇到了同样的问题
