### ISSUE TITLE
模态窗 在IE 11 高度 有问题（应该是 flex布局兼容导致）

### ISSUE THREAD

**Issue by yangkun2197** [baidu/amis#903]
[http://imsc-dvlp-files.oss-cn-hangzhou.aliyuncs.com/melete-temp/2020-08-31/e16ec6f0-eb61-11ea-b380-75a9e7843f68.jpg](url)

**Comment by nwind** [comment]
发一下完整配置吧，不过 IE 11 后续可能不支持了
