### ISSUE TITLE
希望crud的title属性支持schema

### ISSUE THREAD

**Issue by belongwqz** [baidu/amis#9030]
#### 是否关联于某个问题吗：
有时希望在表头部分显示一些换行或者更复杂的内容

#### 预期的解决方案：
希望crud的title属性支持schema

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by allenve** [comment]
crud label 支持直接配置 schema，比如
`
"label": {
      "type": "tpl",
      "tpl": "1123<br>5rr"
}
`
