### ISSUE TITLE
picker组件 点击时异步调用接口

### ISSUE THREAD

**Issue by ityue** [baidu/amis#9033]
#### 是否关联于某个问题吗：
picker组件 配置接口获取数据是初始化就调用了数据，为什么当初要这么设计呢？感觉会有几处不足，1页面picker组件过多 会影响整体页面性能。2 想异步修改picker的source请求地址，无法实现

#### 预期的解决方案：

在点击按钮时暴漏事件，外部可调用
#### 其他可接受方案：
source请求地址修改后能自动检测再次调用

#### 任何附加信息：
![image](https://github.com/baidu/amis/assets/15856497/2f5ae53d-ab20-4077-ba18-250d94f0d4c7)

**Comment by lurunze1226** [comment]
主要还是为了选项 label 的回显，如果说初始值就提供了，其实也不需要发起请求了

**Comment by ityue** [comment]
label 的回显调的接口和picker里面的内容接口还不是一个呢，回显调的是fetchOptions里调用的`${api}?value=xxx`的接口，内容是`${api}?page=1&pagesize=10`的接口，有回显一组件会调用俩接口。请问picker目前有点击上图的图标按钮事件吗？
