### ISSUE TITLE
react继承现有的crud封装的新组件，在vue3 通过vue3-amis-widget 注册crud新组件报错

### ISSUE THREAD

**Issue by xiukun** [baidu/amis#9041]
#### 描述问题：
我想对现有组件二次开发，是否只能通过 extends 基础组件，创建新的组件形式二开？

react继承现有的crud封装的新组件，在vue3 通过vue3-amis-widget 注册crud新组件报错

请用一段清晰简洁的文字描述问题是什么...
问题1:在vue3中通过vue3-amis-widget  的registerRendererByType 进行组件注册，使用sdk方式使用
```
import { CRUDStore } from 'amis'
// 重构的表格渲染注册
  registerRendererByType(AnjiCrud, {
    type: 'ag-crud',
    //渲染类型 renderer、formitem、options
    usage: 'renderer',
    framework: 'react',
    storeType: CRUDStore.name,
    isolateScope: true,
  });
```
**Error: It is not allowed to use shouldComponentUpdate in observer based components.**

<img width="795" alt="image" src="https://github.com/baidu/amis/assets/4969279/ea3b19ce-2b7a-4704-a19f-1be43d178f3f">

我的AnjiCrud组件就是复制了 amis项目下的crud.tsx里的CRUDRenderer，把type换了下
<img width="835" alt="image" src="https://github.com/baidu/amis/assets/4969279/03616252-e6e4-4ec5-89e4-bc5e6d7b211f">

问题2:我封装的CRUD组件AnjiCrud 在react下 Renderer 方式注册正常显示，但是用registerRendererByType注册不显示
// 渲染组件需要
  Renderer({ type: 'anji-label', autoVar: true })(AnjiLabelRender)  //自定义组件
  // // 重点：storeType: CRUDStore.name
  Renderer({ type: 'ag-crud', storeType: CRUDStore.name, isolateScope: true })(AnjiCrud as any) // 在react下renderer方式注册正常显示，但是用registerRendererByType注册不显示。
<img width="1158" alt="image" src="https://github.com/baidu/amis/assets/4969279/4ae44cda-7436-49f8-9fb4-43dbce37461e">

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
问题1:vue3中使用的sdk方式
问题2:react中使用npm 
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis最新版本3.6.3
3. 粘贴有问题的完整 `amis schema` 代码：
```
import { createApp } from 'vue'
import { CRUDStore } from 'amis'
import 'amis/sdk/sdk.js'
import 'amis/lib/themes/default.css'

import { registerRendererByType } from 'vue3-amis-widget'
import {
	renderVue3AmisEditor,
	registerVue3AmisRenderer,
	AnjiLabel,
} from 'wodetian-ui'

import App from './App.vue'

import 'font-awesome/css/font-awesome.css'
import { AnjiCrud } from 'wodetian-ui'

registerRendererByType(AnjiCrud, {
	type: 'ag-crud',
	//渲染类型 renderer、formitem、options
	usage: 'renderer',
	framework: 'react',
	storeType: CRUDStore.name,
	isolateScope: true,
})

createApp(App).mount('#app')


```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by Hookuku** [comment]
请问解决了吗

**Comment by xiukun** [comment]
> 请问解决了吗

fork amis 新增和注册组件 解决了这个问题

**Comment by wfxs2012** [comment]
> > 请问解决了吗
> 
> @Hookuku fork amis 新增和注册组件 解决了这个问题

你好，能学习下您具体怎么解决的步骤吗？ 我也卡到这里了

**Comment by xiukun** [comment]
> > > 请问解决了吗
> > 
> > 
> > @Hookuku fork amis 新增和注册组件 解决了这个问题
> 
> 你好，能学习下您具体怎么解决的步骤吗？ 我也卡到这里了

我创建了私有amis库，开发的react组件，vue3-amis-widget插件创建的组件注册简单组件能正常展示，但是继承amis的复杂组件有问题，所以我方剂使用vue3-amis-widget插件了
