### ISSUE TITLE
input-table某行数据如何联动计算

### ISSUE THREAD

**Issue by africa1207** [baidu/amis#9046]
#### 实现场景：
1. 在input-table中，我想要新增或者编辑某一行的时候，将该行中某列的值设置为该行其他字段的值联动计算，比如结果的值不需要用户手动输入，就是成绩和比例相乘而来。该如何实现呢？
![image](https://github.com/baidu/amis/assets/21698755/80fcf423-6512-45a7-8038-99fa80c593d1)
2. 另外我需要添加某行数据的时候新增一个隐藏字段并设置默认值，但是提交表单的时候并没有这个隐藏字段
#### 存在的问题：
不知如何实现

#### 版本
```
    "amis": "^3.4.1",
    "amis-formula": "^3.4.1",
```

#### 当前方案：

```
{
  "type": "input-table",
  "name": "table",
  "label": "表格表单",
  "columns": [
    {
      "label": "成绩",
      "name": "score",
      "quickEdit": {
        "type": "input-number",
        "name": "score",
      }
    },
    {
      "quickEdit": {
        "type": "input-number",
        "name": "rate"
      },
      "name": "rate",
      "label": "比例"
    },
    {
      "quickEdit": {
        "type": "input-number",
        "name": "result"
      },
      "name": "result",
      "label": "结果"
    }
  ],
  "addable": true,
  "footerAddBtn": {
    "label": "新增",
    "icon": "fa fa-plus"
  },
  "strictMode": true,
  "editable": true
}
```

**Comment by africa1207** [comment]
> 直接给result列配置"value": "${score * rate}即可

谢谢，已通过自定义js实现。但是第二个问题如何解决呢？“另外我需要添加某行数据的时候新增一个隐藏字段并设置默认值，但是提交表单的时候并没有这个隐藏字段”

**Comment by hsm-lv** [comment]
直接加一列就行，例如：
```json
{
  "type": "hidden",
  "name": "var1",
  "label": "隐藏域",
  "value": "11111",
  "hidden": true
}
```

**Comment by hsm-lv** [comment]
> > 直接给result列配置"value": "${score * rate}即可
> 
> 你好，还有个问题，如果我第一列是个下拉框，我需要选择下拉框值以后将该下拉框中其他字段填充到该行其他列，比如选中one，然后将其中的level和score字段填充到该行对应列，如何实现呢？我使用该下拉框的change事件自定义setData，但是这里的setData只是当前作用域，上层作用域的行拿不到
> 
> ```
> {
>   "type": "input-table",
>   "name": "table",
>   "label": "表格表单",
>   "columns": [
>     {
>       "label": "名称",
>       "name": "name",
>       "quickEdit": {
>         "type": "select",
>         "name": "name",
>         "mode": "popOver",
>         "saveImmediately": true,
>         "multiple": false,
>         "options": [
>           {
>             "label": "one",
>             "value": "1",
>             "score": "666",
>             "level": "11"
>           },
>           {
>             "label": "two",
>             "value": "2",
>             "score": "999",
>             "level": "22"
>           }
>         ],
>         "value": ""
>       },
>       "placeholder": "-"
>     },
>     {
>       "label": "分数",
>       "name": "score",
>       "quickEdit": {
>         "type": "input-text",
>         "name": "score",
>         "static": true
>       },
>     },
>     {
>       "label": "等级",
>       "name": "level",
>       "quickEdit": {
>         "type": "input-text",
>         "name": "level",
>         "static": true
>       },
>     }
>   ],
>   "addable": true,
>   "footerAddBtn": {
>     "label": "新增",
>     "icon": "fa fa-plus",
>   },
>   "strictMode": true,
>   "editable": true,
>   "removable": true
> }
> ```

文档里有响应的行内联动的例子： https://baidu.github.io/amis/zh-CN/components/form/input-table#%E8%A1%8C%E8%AE%B0%E5%BD%95%E5%86%85%E8%A1%A8%E5%8D%95%E9%A1%B9%E8%81%94%E5%8A%A8

**Comment by africa1207** [comment]
> > > 直接给result列配置"value": "${score * rate}即可
> > 
> > 
> > 你好，还有个问题，如果我第一列是个下拉框，我需要选择下拉框值以后将该下拉框中其他字段填充到该行其他列，比如选中one，然后将其中的level和score字段填充到该行对应列，如何实现呢？我使用该下拉框的change事件自定义setData，但是这里的setData只是当前作用域，上层作用域的行拿不到
> > ```
> > {
> >   "type": "input-table",
> >   "name": "table",
> >   "label": "表格表单",
> >   "columns": [
> >     {
> >       "label": "名称",
> >       "name": "name",
> >       "quickEdit": {
> >         "type": "select",
> >         "name": "name",
> >         "mode": "popOver",
> >         "saveImmediately": true,
> >         "multiple": false,
> >         "options": [
> >           {
> >             "label": "one",
> >             "value": "1",
> >             "score": "666",
> >             "level": "11"
> >           },
> >           {
> >             "label": "two",
> >             "value": "2",
> >             "score": "999",
> >             "level": "22"
> >           }
> >         ],
> >         "value": ""
> >       },
> >       "placeholder": "-"
> >     },
> >     {
> >       "label": "分数",
> >       "name": "score",
> >       "quickEdit": {
> >         "type": "input-text",
> >         "name": "score",
> >         "static": true
> >       },
> >     },
> >     {
> >       "label": "等级",
> >       "name": "level",
> >       "quickEdit": {
> >         "type": "input-text",
> >         "name": "level",
> >         "static": true
> >       },
> >     }
> >   ],
> >   "addable": true,
> >   "footerAddBtn": {
> >     "label": "新增",
> >     "icon": "fa fa-plus",
> >   },
> >   "strictMode": true,
> >   "editable": true,
> >   "removable": true
> > }
> > ```
> 
> 文档里有响应的行内联动的例子： https://baidu.github.io/amis/zh-CN/components/form/input-table#%E8%A1%8C%E8%AE%B0%E5%BD%95%E5%86%85%E8%A1%A8%E5%8D%95%E9%A1%B9%E8%81%94%E5%8A%A8

谢谢，已实现
