### ISSUE TITLE
select的onChange方法是异步的吗

### ISSUE THREAD

**Issue by xinghe94** [baidu/amis#905]
![image](https://user-images.githubusercontent.com/15528239/91720453-bf614c00-ebc9-11ea-9691-ec3716e1d0b9.png)
![image](https://user-images.githubusercontent.com/15528239/91720419-b1133000-ebc9-11ea-97b5-358b45fc75b9.png)
![image](https://user-images.githubusercontent.com/15528239/91720386-a22c7d80-ebc9-11ea-80db-a78ad813e4f4.png)
监听select值变化的操作 赋给window一个变量 但是这个window值并没有实时更新

**Comment by xinghe94** [comment]
就是deviceTypeChange这个值 我想要用最新的 但是这个onChange里赋的值 在console里抓到的是旧值

**Comment by nuan1989** [comment]
https://github.com/baidu/amis/issues/872 参考这个试试 , 应该是可以携带参数.

**Comment by xinghe94** [comment]
> #872 参考这个试试 , 应该是可以携带参数.

thx 我参考一下

**Comment by xinghe94** [comment]
> #872 参考这个试试 , 应该是可以携带参数.

通过更新data值是很有效的👍
