### ISSUE TITLE
editor-core编辑模式下如何让collapse默认展开的呢?

### ISSUE THREAD

**Issue by ranwawa** [baidu/amis#9056]
#### 实现场景：
自定义了一些amis组件,要在editor中使用

因为自定义的组件有点击展开/折叠的状态,但是在editor中,默认屏蔽了点击事件,所以没办法展开了

如下图是一个搜索表单,超过3行的会隐藏,点击展开按钮会显示所有表单项,但编辑器中点不了

<img width="1248" alt="image" src="https://github.com/baidu/amis/assets/30344590/343bf11d-e08d-4cf7-8c8d-778f11eb2947">

#### 当前方案：

但是观察官方的`collapse`组件,在编辑器下面会自动添加is-active类实现展开功能,如下图.但实际schema代码中并没有配置展开

<img width="630" alt="image" src="https://github.com/baidu/amis/assets/30344590/fa84e892-3ef8-4de9-b656-a9ad93af55bc">

```
{
  "type": "page",
  "body": {
    "type": "collapse-group",
    "activeKey": [
      "12"
    ],
    "body": [
      {
        "type": "collapse",
        "key": "1",
        "header": "标题1",
        "body": "这里是内容1"
      },
      {
        "type": "collapse",
        "key": "2",
        "header": "标题2",
        "body": "这里是内容2"
      },
      {
        "type": "collapse",
        "key": "3",
        "header": "标题3",
        "body": "这里是内容3"
      }
    ]
  }
}
```

#### 我的问题

官方`collapse`具体是怎么做到的呢?既不污染原始的schema,又可以在编辑状态下默认全部展开.....

想借鉴下这个功能,应用在自己定义的组件上面

**Comment by wibetter** [comment]
@ranwawa  
1. 编辑器中默认会拦截屏蔽点击等操作事件，如果想在编辑器端保留这些点击事件，可以给对应元素加.ae-editor-action-btn；
2. 编辑器端，可以通过schemaFilter给编辑器态调整schema属性，比如把schema中的api地址替换成 proxy 地址，也就是说你可以通过这个方法改变某些组件编辑态的属性数值；
3. collapse组件默认是展开状态（collapsed为false）,collapse-group组件默认子元素（collapse）是折叠状态（根据activeKeys中是否有当前面板key来确定是否展开，而activeKeys默认为空，所以collapsed默认为true）。collapse-group组件在编辑态和预览态折叠状态不一致，是受amis-editor/RegionWrapper组件的影响。
