### ISSUE TITLE
能否增加导入和导出功能

### ISSUE THREAD

**Issue by zaijianafei** [baidu/amis#906]
#### 是否关联于某个问题吗：
CRUD都做了，添加导入导出不是更加锦上添花吗，支持Excel导入导出功能应该可以实现的。

#### 预期的解决方案：
添加Excel导入导出功能

#### 其他可接受方案：
要添加的可以一起沟通下

#### 任何附加信息：
我这边的扩展实现如下
![1](https://user-images.githubusercontent.com/32755141/91791941-f9246800-ec46-11ea-84b4-828acf5bc25d.png)

**Comment by nwind** [comment]
有打算做，不过引入一个 Excel 库体积又要大不少。。

**Comment by zimo888** [comment]
导入做csv 就行了，可以引入react-csv-reader 做自定义组件。

**Comment by nwind** [comment]
#1077
