### ISSUE TITLE
markdown 能否支持渲染 Mermaid？

### ISSUE THREAD

**Issue by Aaronlong31** [baidu/amis#9085]
#### 是否关联于某个问题吗：
需要能动态展示流程图，能否通过 markdown 支持 Mermaid，或者是直接支持 Mermaid？

#### 预期的解决方案：
通过 markdown 支持 Mermaid，或者是直接支持 Mermaid。

**Comment by nwind** [comment]
这个库的依赖非常多，会导致 amis sdk 文件变大很多，有这个需求的用户也很少，所以不打算支持，如果有需要可以自己写自定义组件
