### ISSUE TITLE
【重金求解】使用amis-sdk做ui组件库，如何通过js验证表单以及获取表单数据

### ISSUE THREAD

**Issue by 1532332928** [baidu/amis#9091]
#### 实现场景：
我想配合jQuery的Ajax实现表单请求

#### 存在的问题：
看完文档没有相关使用方法验证表单以及获取表单数据的方法
如果有解决能力的大佬欢迎联系我我，有偿解决问题

<img width="1202" alt="image" src="https://github.com/baidu/amis/assets/50939596/ba90bd5f-9ad6-4de1-a57b-a5a48404b7db">

**Comment by 1532332928** [comment]
【已经解决一半】使用doAction行为方法实现验证表单功能，和自定义按钮提交表单，获取表单数据暂时无解，具体实现代码参考如下
`
$(function () {
        let amis = amisRequire('amis/embed');
        amisScoped = amis.embed('#root', {
            type: 'page',
            overlay: true,
            body: {
                id: "form_validate",// 一定要存在
                type: "form",// 表单类型
                wrapWithPanel: false,// 隐藏包裹panel，包括标题和底部按钮
                api: "/amis/api/mock2/form/saveForm",// 表单提交接口
                body: []//表单字段
            }
        });
        // 验证表单
        amisScoped.doAction({
            actionType: "validate",// 行为类型
            componentId: "form_validate",// 表单id
            outputVar: "form_validate_result"// 验证结果
        })
        // 提交表单
        amisScoped.doAction({
            actionType: "submit",
            componentId: "form_submit",
            outputVar: "form_submit_result"
        })
    });
`

**Comment by SimmonsSue** [comment]
sdk运行时amisScoped.parent.getComponentById('id').props.data可以拿到
编辑器预览是amisScoped.getComponentById('id').props.data
