### ISSUE TITLE
组件使用"api"拉取数据时页面弹窗error

### ISSUE THREAD

**Issue by d2913360** [baidu/amis#910]
#### 实现场景：
拉取数据

#### 存在的问题：
使用线上的可视化编辑工具能正常获取数据，但是使用react渲染后页面弹窗error

请问下有没有人知道是什么问题啊

**Comment by Chengxi9** [comment]
遇到了同样的问题，console报错看不到什么信息

**Comment by nwind** [comment]
需要贴具体报错信息
