### ISSUE TITLE
react使用amis-ui当组件，使用公式组件，选择布尔类型，选择就会报错

### ISSUE THREAD

**Issue by onlyThat** [baidu/amis#9104]
![image](https://github.com/baidu/amis/assets/114373085/a25a8083-86ab-4c0d-868e-e0ea01081740)
![image](https://github.com/baidu/amis/assets/114373085/d04fd04f-beb5-4cc6-9afc-7148e8979076)
![image](https://github.com/baidu/amis/assets/114373085/80073f2b-c7d7-40e2-b389-1d88a49507ca)

**Comment by 2betop** [comment]
新版本已无此问题，请更新最新代码
