### ISSUE TITLE
组件右侧属性面板如何简单扩展属性

### ISSUE THREAD

**Issue by liyang0612** [baidu/amis#9108]
#### 实现场景：
我想对现有组件的属性进行扩展，例如添加某一个属性，但是我又不想重新写一个自定义组件。因为它们可能就一个属性的差别，这种场景需要怎么做呢？
![image](https://github.com/baidu/amis/assets/19622871/24b70521-f30d-4e32-89ba-db31acf3e514)

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
现在我是对继续现有组件，然后复写panelBodyCreator方法

```
code here...
```

**Comment by liyang0612** [comment]
现在我是为了添加一个属性重新复写了整个panelBodyCreator，把原有的属性从源码中复制了过来
![image](https://github.com/baidu/amis/assets/19622871/2db80351-e096-4096-a271-cbe454f66545)

**Comment by wibetter** [comment]
@liyang0612 
1、如果是扩展现有组件的属性配置面板，比如添加一个配置项，可以通过覆盖对应组件的plugin，并覆盖原有的panelBodyCreator；
2、如果是调整某个配置项，可以通过 setSchemaTpl('xxx', xxx) 方式重新定制配置项。
