### ISSUE TITLE
amis editor 从 5.6.3 开始，右侧面板中【外观】报错：找不到对应的渲染器

### ISSUE THREAD

**Issue by citynook** [baidu/amis#9110]
#### 描述问题：
amis editor 从 5.6.3 开始，包括最新版的 5.7.0，右侧面板中【外观】报错：找不到对应的渲染器

使用官方demo: https://github.com/aisuda/amis-editor-demo/tree/master
将 amis editor 升级到 5.7.0后，发生同样的错误。

5.6.2 版本正常，没有发生此异常。

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/127393297/c191763c-e1a7-45df-bf77-2caa483f0ee1)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis: 3.6.3
amis editor: 5.7.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by hehuasa** [comment]
+1

**Comment by qkiroc** [comment]
尝试重装下依赖，这部分渲染器的依赖变化了。如果还有问题，尝试直接在项目中安装amis-theme-editor-helper包的最新版本

**Comment by citynook** [comment]
@qkiroc 每次升级 amis 组件都会删除 node_modules 目录并重新安装全部依赖。现在再重装一次，不行的话就安装 amis-theme-editor-helper 最新版，如果还不行那就只能等待修复了~

**Comment by citynook** [comment]
重新安装依赖，面板显示已正常，关闭。
