### ISSUE TITLE
schemaApi返回的配置中的国际化配置无效

### ISSUE THREAD

**Issue by jianchaoming** [baidu/amis#9111]
#### 描述问题：

schemaApi返回的配置中的国际化配置无效，比如en-US配置英文，没有生效，只显示了中文

#### 截图或视频：

<img width="465" alt="image" src="https://github.com/baidu/amis/assets/39518514/bf6166b6-82ab-4a76-867f-70837f433d48">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
"amis": "3.5.2",
"amis-core": "3.5.2",
"amis-editor": "5.6.2",
"amis-editor-core": "5.6.2",
"amis-formula": "3.5.2",
"amis-ui": "3.5.2",

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "tpl",
  "tpl": "安全验证项",
  "en-US": {
    "tpl": "Security Settings"
  },
  "inline": false,
  "wrapperCustomStyle": {
    "margin-bottom": "12px",
    "font-weight": "500"
  },
  "id": "u:73cc0cebee70"
}
```

4. 操作步骤
选中某个tab后，动态取出对应页面的schema进行渲染

**Comment by 2betop** [comment]
重复问题: #9163 , 已在 #9610 中修复
