### ISSUE TITLE
amis-theme-editor

### ISSUE THREAD

**Issue by lideng11** [baidu/amis#9129]
#### 实现场景：
能发布一下 amis-theme-editor 项目源码

#### 存在的问题：
独立发布的 amis 需要引用 amis-theme-editor 项目

#### 当前方案：
![image](https://github.com/baidu/amis/assets/13286185/f1a909de-ccf6-4764-a101-915114ea42a5)

```
code here...
```

**Comment by qkiroc** [comment]
这部分渲染器已开源，在amis-theme-editor-helper中

**Comment by lideng11** [comment]
谢谢
