### ISSUE TITLE
3.6.3版本from表单dug不显示数据，前几个版本好像也是这样的

### ISSUE THREAD

**Issue by wensia** [baidu/amis#9155]
如图
![image](https://github.com/baidu/amis/assets/113636620/b6ab1df7-4419-4156-a878-4a2bb2d7c193)

**Comment by wensia** [comment]
只显示...，不显示json对数据

**Comment by 2betop** [comment]
JSSDK 中没能复现，估计是 npm 用法，如果也是 vite  编译，可以尝试加上这个看看是否能解决

```
    optimizeDeps: {
      include: ['react-json-view'],
    },
```

**Comment by mixiaodiao** [comment]
自己不要var amis

**Comment by aclisp** [comment]
加上这个就行了。
```
import 'amis/sdk/json-view.js';
```

**Comment by 2betop** [comment]
sdk 不要做二次编译，直接 copy 过去使用
