### ISSUE TITLE
引用主题编辑器组件报错：The renderer with name "amis-theme-select" has already exists, please try another name!

### ISSUE THREAD

**Issue by citynook** [baidu/amis#9161]
#### 描述问题：
项目中除了引入 amis, amis-editor外，又新引入了 amis-theme-editor，试一下主题编辑器的功能，在启动项目时报错：The renderer with name "amis-theme-select" has already exists, please try another name!

报错的文件为：amis-core/ems/factory.js

在引入 amis-theme-editor 之前，amis-editor 编辑器可以正常使用。

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/127393297/810d7921-12e5-4d11-9ecf-f9fff8a16b05)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
vite: 3
npm: 9.5.1
node: 18.16.1

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
    "amis": "3.6.3",
    "amis-editor": "5.7.0",
    "amis-theme-editor": "2.0.10"

4. 粘贴有问题的完整 `amis schema` 代码：
加入下面代码就会触发错误，删除后恢复正常。
```
import ThemeEditor from 'amis-theme-editor';
```
感觉上面的代码和
import Editor from 'amis-editor'
这行代码都存在时，会引起这个错误。

6. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
尝试把 esm 功能关掉试试，也许是工程里面对 amis 的包有两种写法，比如既有 import 又有 require 导致 cjs 和 esm 的包都加载了。

```
resolve: {
    conditionNames: ["require", "browser", "web"],
},
```

**Comment by citynook** [comment]
@2betop 项目用的Vite构建，并非WebPack，没有 conditionNames 这个配置项，但是有 conditions，应该是相似的功能。

在vite.config.js的添加如下配置项：
    resolve: {
      conditions: ['require', 'browser'],
  }
运行后依旧报错，但错误信息变成了：
![image](https://github.com/baidu/amis/assets/127393297/b1bad806-fd70-4718-8635-3957dab3d93e)
配置成  ["require", "browser", "web"] 也是同样的错误。

请问 vite 下要如何关闭 esm，在网上找了半天没找到相关的文章~~

**Comment by 2betop** [comment]
先 `npm ls` 看看依赖，是不是出现安装了多份 amis ，如果不是再确认是不是既加载了 cjs 又加载了 esm

**Comment by citynook** [comment]
1. package.json中引用的 amis 包
    "amis": "3.6.3",
    "amis-core": "3.6.3",
    "amis-formula": "3.6.3",
    "amis-ui": "3.6.3",
    "amis-editor": "5.7.0",
    "amis-editor-core": "5.7.0",
    "amis-theme-editor": "2.0.10"

在第一次报错后，删除了一些未在代码中引用的包，只保留了：
    "amis": "3.6.3",
    "amis-editor": "5.7.0",
    "amis-theme-editor": "2.0.10"

编辑器的功能也能正常运行。

2. npm ls 查看依赖，有 amis 相关的如下，没有安装多份 amis：
├── amis-editor-core@5.7.0 extraneous -> .\node_modules\.pnpm\amis-editor-core@5.7.0_b44q5wgtr6cwtorep3uykil4ea\node_modules\amis-editor-core    
├── amis-editor@5.7.0 -> .\node_modules\.pnpm\amis-editor@5.7.0_vulbbzfql3tmw4y6rp6mwb6ugu\node_modules\amis-editor
├── amis-postcss@1.0.0 extraneous -> .\node_modules\.pnpm\amis-postcss@1.0.0\node_modules\amis-postcss
├── amis-theme-editor-helper@2.0.26 -> .\node_modules\.pnpm\amis-theme-editor-helper@2.0.26_knhnagtyfncgg2hpin7s37uixq\node_modules\amis-theme-editor-helper
├── amis-theme-editor@2.0.10 -> .\node_modules\.pnpm\amis-theme-editor@2.0.10_vulbbzfql3tmw4y6rp6mwb6ugu\node_modules\amis-theme-editor
├── amis@3.6.3 -> .\node_modules\.pnpm\amis@3.6.3_knhnagtyfncgg2hpin7s37uixq\node_modules\amis

3. 项目中有4种引用 amis 包的代码
3.1 amis 编辑器的代码
  import { alert, confirm } from 'amis';
  import { Editor, setThemeConfig } from 'amis-editor';

3.2 amis 编辑器自定义布局组件，从官网示例中复制过来的
import { FlexPluginBase } from 'amis-editor/lib/plugin/Layout/FlexPluginBase';

3.3 amis 主题编辑器的代码
  import ThemeEditor from 'amis-theme-editor';

3.4  在 index.html 中用入 amis sdk，用SDK实现页面的渲染。
    <script type="module">
      import 'amis/sdk/sdk';
    </script>

在未加入 amis-theme-editor 之前，amis 编辑器，amis SDK 渲染页面都一切正常。

加上 import ThemeEditor from 'amis-theme-editor'; 这行代码就立马报错，删除后恢复正常。

**Comment by citynook** [comment]
@2betop 几个月前 amis editor 也报过类似的问题，后面由官方修复了。

**Comment by 2betop** [comment]
能否来个问题仓库？我们基于仓库工程排查一下？

**Comment by qkiroc** [comment]
最新版本可以删掉项目中的amis-theme-editor
<img width="603" alt="image" src="https://github.com/baidu/amis/assets/30946345/f8e0b900-5f70-433c-9df4-fa6265abf151">

**Comment by 2betop** [comment]
锁定 `amis-theme-editor-helper@2.0.11-beta.2` 或者升级 amis + amis-editor 到最新版本可解决

**Comment by citynook** [comment]
参见：JS SDK版本无法正常渲染部分组件，例如颜色选择，编辑器，富文本编辑器等 #9148
