### ISSUE TITLE
基于 tinymce的富文本能否实现视频拖拽上传？

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#9163]
#### 实现场景：
1.基于 tinymce的富文本能否实现视频拖拽上传？类似于图片这种
![image](https://github.com/baidu/amis/assets/48573389/fb12432a-0204-4cb5-93bb-7f4e750537bc)
2.基于 tinymce的富文本能否实现通过接口返回的视频url上传视频
<img width="522" alt="c2881e3ddbc4fac7b813e5cf0bdafd5a" src="https://github.com/baidu/amis/assets/48573389/f216af60-5c5c-4cf4-a457-7dcabf973c79">

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
目前官方没方案，可以尝试自己扩充 tinymce 的插件 https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-rich-text#%E6%89%A9%E5%85%85-tinymce-%E6%8F%92%E4%BB%B6
