### ISSUE TITLE
安全漏洞-each标签官网释例代码有xss安全漏洞，建议修改一下

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#9164]
#### 描述问题：

each标签使用data.item进行循环时候会造成xss注入，建议官网把文档改一下，不然一般复制过去用就糟了。

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/11575908/7d06a2d8-74d3-448b-a14d-23bea554975a)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk3.6.3

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "data": {
    "arr": [
      "A",
      "B",
      "<img src=x onerror=alert(\"1\") />",
      "C"
    ]
  },
  "body": [
    
    {
      "type": "each",
      "name": "arr",
      "items": {
        "type": "tpl",
        "tpl": "<span class='label label-default m-l-sm'><%= data.item %></span> "
      }
    },
    {
      "type": "each",
      "name": "arr",
      "items": {
        "type": "tpl",
        "tpl": "<span class='label label-default m-l-sm'>${item}</span> "
      }
    }


  
  ]
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
使用 amis 时，通过 env 下发 `filterHtml` 自行处理，目前 amis 本身不处理这块。

参考代码：

```
filterHtml: (html: string) => {
        return xss(html, {
          onIgnoreTagAttr: (tag: any, name: string, value: any) => {
            if (
              name === 'class' ||
              name === 'style' ||
              name.substring(0, 5) === 'data-'
            ) {
              // escape its value using built-in escapeAttrValue function
              return name + '="' + escapeAttrValue(value) + '"';
            }

            return '';
          }
        });
      },
```

**Comment by xiahao90** [comment]
是官网的释例代码有点误导人，一般人直接复制过去就用了。

**Comment by 2betop** [comment]
明白，示例我们处理一下，业务测需要加入以上代码处理 xss 问题。

**Comment by 2betop** [comment]
等下，这个不是 xss 数据不是自己写的吗？那我的理解业务测加入以上逻辑即可

**Comment by xiahao90** [comment]
我建议把示例代码中的 `<span class='label label-default m-l-sm'><%= data.item %></span>  `换成`<span` class='label label-default m-l-sm'>${item}</span> `

**Comment by 2betop** [comment]
感谢，我们文档做一下调整 https://github.com/baidu/amis/pull/9165。 同时如果有代码配置成 `${ xxx | raw}` 同样存在 xss 风险。所以建议业务测还是要加以上 `filterHtml` 逻辑
