### ISSUE TITLE
请问amis的picker组件怎么修改显示的名称

### ISSUE THREAD

**Issue by ityue** [baidu/amis#9169]
#### 实现场景：
对picker组件进行封装自定义组件，使用FormItem进行注册，渲染时反显数据不调用接口，如picker组件的点击（input框显示中文name，表单提交用的字段名为id）

#### 存在的问题：
初始化时input的name显示中文，id显示对应的id格式为number

#### 当前方案：
目前使用props的onChange和setValue方法时，name和id都会一起修改，（希望name显示中文，id显示对应的id格式为number），使用setOptions方法时，源码里修改可以，但自定义里没有setOptions方法， 使用formItem的setOptions也不生效。changeTmpValue方法也不可以，请问怎样才能实现（name显示中文，id显示对应的id格式为number）
![image](https://github.com/baidu/amis/assets/15856497/6a0160e5-a714-472a-9563-2c0e563fb4a1)

```
props.onChange('change');
    props.setValue('123', 'code1');
```

**Comment by 2betop** [comment]
有两种方式可以让 picker 的显示值为 label

a. 配置 joinValues 为 false，这样它的值格式是对象了，里面既有 value 也有 label，展示的时候会用 label 作为展示。
b. 配置 source 为接口，picker 初始化的时候，发现初始值中没有包含 label 信息，会发送个请求给 source 配置对应的接口。接口返回选项信息，就会关联显示对应的 label

**Comment by ityue** [comment]
感谢回复，a配置的joinValues 为false，点击后返回为对象，影响业务逻辑。目前不想改变业务逻辑。b的源码简单看了下，我们目前业务想的是没有label时不调用接口，在其他初始化接口返回label数据，我目前想把这label赋值，没有找到怎么赋值label。请问用什么方法可以赋值label，使展示时使用label，作用域的请求接口的id字段不变

**Comment by ityue** [comment]
请问 接口返回选项信息，就会关联显示对应的 label，这部是怎么实现的，在自定义组件里有方法将值赋值到label，用于显示吗

**Comment by ityue** [comment]
`目前使用setValue显示能为对应的值,但是作用域中code1为对象了,希望显示为ceshi010, code1为 '888' 使用代码为
props.setValue(
  {
    name: 'ceshi010',
    id: '888'
  },
  'code1'
);
请问怎么实现此功能多谢`

**Comment by ityue** [comment]
我在源码里使用changeTmpValue和setOptions能实现此效果
`// setOptions([
    //   {
    //     id: '999',
    //     name: 'value'
    //   }
    // ]);
    this.props.formItem.changeTmpValue('value', 'initialValue');` 但自定义代码里使用不生效，请问怎么处理呢，俩处shecma配置一样
![image](https://github.com/baidu/amis/assets/15856497/1e2f77c6-f523-4904-8bed-64d7ac7cba8a)

**Comment by 2betop** [comment]
应该是用 `this.props.setOptions()` 可以补充 label 信息。如果没有配置 labelField, valueField 那么直接就是 this.props.setOptions([{label: 'A', value: 'a'}]) 这种。注意这里是设置全量的选项

**Comment by ityue** [comment]
您好，使用this.props.setOptions()报错，TypeError: props.setOptions is not a function。代码为`export default class Component extends React.Component {
  static contextType = ScopedContext;
  constructor(props) {
    props.setOptions([{ label: 'A', value: 'a' }]);`

**Comment by 2betop** [comment]
你的自定义组件不是通过 `@OptionsControl` 注册的？你的自定义组件是什么形式的？

**Comment by ityue** [comment]
您好 ，自定义组件使用FormItem注册， 代码为`  FormItem({
    type: TYPE,
    autoVar: true
  })(Component);`，使用 props.formItem.setOptions([{ label: 'A', value: 'a' }]);没反应，目前将 labelField, valueField配置都去了

**Comment by 2betop** [comment]
要通过 `@OptionsControl` 注册才有选项类功能，否则就只能调用. `this.props.formItem.setOptions`

**Comment by ityue** [comment]
您好，这自定义需要继承from的一些配置，所以用的formItem注册，目前使用props.formItem.setOptions([{ label: 'A', value: 'a' }]);配置没有反应

**Comment by 2betop** [comment]
自定义组件，跟 picker 的关系是什么？

**Comment by ityue** [comment]
这自定义组件是对picker 配置的封装和修改 picker 初始化的时候，发现初始值中没有包含 label 信息，会发送个请求给 source 配置对应的接口，这个方案。想自己拿数据动态赋值

**Comment by ityue** [comment]
这自定义组件的实际type类型为picker

**Comment by 2betop** [comment]
你的自定义组件里面的 render 方法大概是这样？

```
render() {
  return this.props.render('inner', {type: 'picker', label: 'xxx', name: this.props.name})
}
```

**Comment by ityue** [comment]
嗯嗯 是的 大概这样的。数据放到了state里 ，如render(this.state.finalSchema, {}, { fetcher })

**Comment by 2betop** [comment]
那么 this.props.formItem 和 picker 的 formItem 不是同一个对象，所以没效果。

可以试试 props 里面直接下发 options， 这个 options 是把 label 映射好了的 options

```
render() {
  return this.props.render('inner', {type: 'picker', label: 'xxx', name: this.props.name}, {options: [{label: 'A', value: 'a'}]})
}
```

**Comment by ityue** [comment]
感谢回复，但还没有生效。请问{options: [{label: 'A', value: 'a'}]}这加完是往props里传值吗？对应props的哪个字段，这样写完，props里没找到options，但props的fromItem里有options。

**Comment by 2betop** [comment]
下发给 picker 的 options 的，要不你贴一下自定义组件的代码？

**Comment by ityue** [comment]
您好，大概是这样的`export default class Component extends React.Component {
  static contextType = ScopedContext;
  constructor(props) {
    super(props);
    this.state = {
      // 渲染的所有数据
      finalSchema: {
        type: 'picker',
        label: 'xxx',
        name: this.props.name
      }
    };
  }
  render() {
    return (
      <>
        {render(
          this.state.finalSchema,
          { options: [{ label: 'A', value: 'a' }] }
        )}
      </>
    );
  }
}`  其中加了些业务逻辑所以finalSchema放到了state里

**Comment by 2betop** [comment]
用 this.props.render 呢？不要用 import {render} from 'amis'

**Comment by ityue** [comment]
嗯嗯 需要 抱歉，有些业务的没粘全 import { render, addSchemaFilter } from 'amis';

**Comment by ityue** [comment]
`import React from 'react';
import { render } from 'amis';
import { ScopedContext } from 'amis-core';
export default class Component extends React.Component {
  static contextType = ScopedContext;
  constructor(props) {
    super(props);
    this.state = {
      finalSchema: {
        type: 'picker',
        label: 'xxx',
        name: this.props.name
      }
    };
  }
  render() {
    return (
      <>
        {render(this.state.finalSchema, {
          options: [{ label: 'A', value: 'a' }]
        })}
      </>
    );
  }
}`  大概是这样的

**Comment by ityue** [comment]
请问这么改完 props的selectedOptions还是没有值，目标是要selectedOptions 赋值则可以实现了把？

**Comment by ityue** [comment]
十分感谢作者的回答，使用options 加name目前看是可行的，请问是formItem注册和@OptionsControl 注册的方法不一致，能否优化呢，十分感谢作者，多谢多谢

**Comment by 2betop** [comment]
这边有说明 https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/custom-react#optionscontrol
