### ISSUE TITLE
CRUD组件分页器点击触发页面reload

### ISSUE THREAD

**Issue by ydiego** [baidu/amis#9170]
#### 描述问题：
CRUD组件分页器点击触发页面reload

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.5.2
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
    {
      "type": "crud",
      "id": "u:4770cd64ebee",
      "api": "/apiv1/by_kol/live_list",
      "columns": [
        {
          "id": "u:0f22b94ce07f",
          "name": "uid",
          "type": "tpl",
          "label": "达人"
        },
        {
          "id": "u:d89051af0b23",
          "name": "start_at",
          "type": "date",
          "label": "直播日期"
        },
        {
          "id": "u:76a0b90c839f",
          "type": "operation",
          "label": "操作",
          "buttons": [
          ]
        }
      ]
    }
  ],
  "regions": [
    "body"
  ],
  "id": "u:677b5be0a410"
}
```

4. 操作步骤
使用amis-editor生成了上诉schema 然后通过接口获取schema然后使用amis.embed渲染
```
const CustomPage = () => {
  const [searchParams] = useSearchParams();
  const tplId = searchParams.get('tplId');
  const { run } = useRequest(getTplSchema, {
    manual: true,
    onSuccess: ({ data }) => {
      let amis = window.amisRequire('amis/embed');
      amis.embed('#amis-render-root', data.schema, null, options);
    },
  });

  useEffect(() => {
    if (!tplId) {
      return message.error('模板id异常');
    }
    run(tplId);
  }, [tplId]);

  return <div id="amis-render-root" style={{ position: 'relative' }}></div>;
};
```

相比于正常情况下，这次异常是接口返回了columns字段，接口返回结构如下
![image](https://github.com/baidu/amis/assets/13268002/1ba600eb-5720-4e31-bbeb-d048b7fae34f)

这个时候通过分页器切换页数会导致页面reload
参照按照文档动态列
https://aisuda.bce.baidu.com/amis/zh-CN/components/crud?page=1&perPage=10#%E5%8A%A8%E6%80%81%E5%88%97
将上诉schema中的columns去掉后问题依旧存在
但是在编辑器中预览时，分页器正常工作不会reload

想了解下这个是什么原因导致的，如果是配置问题应该如何修改

**Comment by 2betop** [comment]
`amis.embed` 的第四个参数是 env。这个里面如果传入了 `updateLocation` 函数，会覆盖内部默认的地址栏跳转逻辑。jssdk 默认的使用 window.history.replaceState 做的，怀疑你在外部覆盖了这个。

页面分页的时候为了更新地址栏，会调用 `env.updateLocation`。可以跟一下这块逻辑

**Comment by ydiego** [comment]
```
var options = {
  fetcher,
  isCancel: (value: any) => axios.isCancel(value),
};
```
抱歉 漏掉了部分代码，options如下， 没有你提到的`updateLocation `,所以这个算正常吗

**Comment by ydiego** [comment]
路由使用的`react-router-dom V6`
其他如果接口没有返回colum字段，且schema中配置了的情况下，点击分页是正常请求并更新的

**Comment by 2betop** [comment]
`crud` 配置 `syncLocation` 为 false 看看正常不，如果正常了，说明还是 `updateLocation` 里面的逻辑有问题，需要跟进里面看看为何页面会刷新。另外浏览器控制台有没有报错信息？

**Comment by ydiego** [comment]
配置了依旧会刷新；另外没有`updateLocation`相关配置，应该是走的默认；还有控制台没有报错，看网络请求是发出去了，然后立马刷新页面

**Comment by 2betop** [comment]
env 下发个 updateLocation 然后写个 `debugger` 看看吧，直接 什么都不做，看看是否会刷新。从你的回复来看你们的应用本身就用了 react-router ，正常是需要覆盖 updateLocation 和 jumpTo 实现的，否则跟你们的单页路由断层。

可以参考一下这个 ：https://github.com/aisuda/amis-admin/blob/react/components/AMisRenderer.tsx#L76-L118

**Comment by ydiego** [comment]
```
updateLocation: (location: string, replace: boolean) => {
    console.log(location, replace);
  },
```
加了个空函数之后确实不刷新了，不过每次点击分页会触发`updateLocation `,  很好奇这是动态列导致的吗？前面都是写死columns的没出现过这个情况，因为业务需要有了这个动态列才发现的这个问题

**Comment by 2betop** [comment]
分页不管有没有 动态列都会执行到 updateLocation 里面来同步地址了，所以用你们的 react-router 复写这块逻辑吧。

**Comment by ydiego** [comment]
了解了  非常感谢  还是有最后个问题动态列是会忽略`syncLocation`这个选项吗，设置之后依旧会同步地址

**Comment by 2betop** [comment]
不会忽略哎
<img width="1746" alt="image" src="https://github.com/baidu/amis/assets/2698393/15e52dde-158c-4619-b35e-4ea1fc0774ec">

```
{
  "title": "动态表格",
  "subTitle": "返回表格数据的同时返回列信息",
  "body": {
    "type": "crud",
    "api": "/api/crud/dynamic?waitSeconds=1",
    "syncLocation": false
  }
}
```

**Comment by ydiego** [comment]
那就很奇怪了哎
![image](https://github.com/baidu/amis/assets/13268002/eb03d125-7b44-4718-8176-0dc231b0432f)
![image](https://github.com/baidu/amis/assets/13268002/62eebe15-a76f-475f-b0f5-da8ab743ed12)

**Comment by ydiego** [comment]
知道了，`updateLocation`参数中是携带的，需要另外处理，非常感谢你的解答
