### ISSUE TITLE
使用官方的amis-editor-demo出现异常“The renderer with name "amis-theme-color-picker" has already exists, please try another name!”

### ISSUE THREAD

**Issue by iamcyw** [baidu/amis#9174]
#### 描述问题：
直接clone的amis-editor-demo仓库，`npm i` `npm run dev` 启动进编辑器报错

The renderer with name "amis-theme-color-picker" has already exists, please try another name!

#### 截图或视频：

<img width="1912" alt="image" src="https://github.com/baidu/amis/assets/11208441/677eca50-3638-415d-b88e-f54fd580aae4">

#### 如何复现（请务必完整填写下面内容）：

直接clone的amis-editor-demo仓库，`npm i` `npm run dev` 启动进编辑器报错

**Comment by 2betop** [comment]
执行 `npm ls amis-theme-editor` 和 `npm ls amis-theme-editor-helper` 看看？或者删了依赖重新安装试试看？新版本按理是不需要 `amis-theme-editor` 了，而是 `amis-theme-editor-helper`

刚拉最新的 `amis-editor-demo` 安装依赖没能复现

**Comment by iamcyw** [comment]
> npm ls amis-theme-editor-helper

<img width="697" alt="image" src="https://github.com/baidu/amis/assets/11208441/e3f7dd58-686e-4e42-b4ef-fae5c0f02f79">

删除了`node_modules` 重新安装也是一样

**Comment by 2betop** [comment]
用最新的 amis-editor@5.7.0 或者限制 amis-theme-editor-helper 到版本 2.0.11-beta.2 都可以解决。主要问题是 amis-editor@5.6.2 没有限制版本，装了最新的 amis-theme-editor-helper 导致，而最新的 amis-theme-editor-helper 其实是给 ami-editor@5.7.0 用的。

**Comment by iamcyw** [comment]
> 用最新的 amis-editor@5.7.0 或者限制 amis-theme-editor-helper 到版本 2.0.11-beta.2 都可以解决。主要问题是 amis-editor@5.6.2 没有限制版本，装了最新的 amis-theme-editor-helper 导致，而最新的 amis-theme-editor-helper 其实是给 ami-editor@5.7.0 用的。

限制amis-theme-editor-helper的版本是可以的，但是直接升级amis-editor@5.7.0好像还有其他问题

<img width="1912" alt="image" src="https://github.com/baidu/amis/assets/11208441/f29f17b7-a67b-4e36-a5e9-c8ccf6c5989a">

**Comment by 2betop** [comment]
收到，5.7.0 的问题我们看看

**Comment by 932808140** [comment]
怎么限制amis-theme-editor-helper的版本？

**Comment by jiangbinwangyi** [comment]
amis@3.3.0  amis-editor@5.5.0  在Linux(centos7)下运行，存在同样的问题
