### ISSUE TITLE
tabs切换tab时如何重置新tab页的筛选条件+刷新表单

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#9175]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

![image](https://github.com/baidu/amis/assets/48573389/40f9e192-1fd0-4f6b-88e0-2bd589e90ed5)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by Liary0** [comment]
期望效果是重置条件搜索内容+刷新表格

**Comment by Liary0** [comment]
已解决  "reload":true, 
还有其他解决方案吗

**Comment by 2betop** [comment]
没有了，还有个等级的配置就是在 tab 上配置 "mountOnEnter": true, "unMountOnExit": "true"
