### ISSUE TITLE
在select的onChange里给最外层data里的变量赋值

### ISSUE THREAD

**Issue by coffin03** [baidu/amis#9179]
如何在 select 的 onChange 里给最外层 data 里的变量赋值？

**Comment by 2betop** [comment]
用事件动作应该可以 https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E6%9B%B4%E6%96%B0%E7%BB%84%E4%BB%B6%E6%95%B0%E6%8D%AE

**Comment by coffin03** [comment]
> 用事件动作应该可以 https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/event-action#%E6%9B%B4%E6%96%B0%E7%BB%84%E4%BB%B6%E6%95%B0%E6%8D%AE

![image](https://github.com/baidu/amis/assets/141314006/103fd158-60da-40e6-a379-7c60ff932a98)
![image](https://github.com/baidu/amis/assets/141314006/0621061f-f55c-4386-82f3-38d7c0185d09)

就是这种情况应该怎么写
