### ISSUE TITLE
amis-editor-demo提交的依赖更新存在问题

### ISSUE THREAD

**Issue by iamcyw** [baidu/amis#9184]
#### 描述问题：

https://github.com/aisuda/amis-editor-demo/commit/3b30b5d700d6539920ee2e1973e4c0cebfa07902
更新这个提交以后，编辑器存在问题
#### 截图或视频：

<img width="2153" alt="image" src="https://github.com/baidu/amis/assets/11208441/8a4f452c-843c-46af-ae1f-ea1c9429d7bb">

**Comment by qkiroc** [comment]
![image](https://github.com/baidu/amis/assets/30946345/157893a2-cedf-4f41-9df2-1e0e8c215590)
确认版本信息是否和该图一致

**Comment by iamcyw** [comment]
@qkiroc 不好意思，刚有时间看。
<img width="716" alt="image" src="https://github.com/baidu/amis/assets/11208441/8b513c51-8e30-4a28-a69e-b9390566a743">

**Comment by qkiroc** [comment]
重装下依赖，amis-theme-editor-helper的版本不对

**Comment by iamcyw** [comment]
指定amis-theme-editor-helper的版本2.0.26
