### ISSUE TITLE
看文档时发现代码显示部分和最新firefox不兼容, 眯成一条缝了

### ISSUE THREAD

**Issue by hlizard** [baidu/amis#922]
#### 描述问题：
看文档时发现代码显示部分和最新firefox不兼容, 眯成一条缝了

#### 截图或视频：
![image](https://user-images.githubusercontent.com/6994037/92106906-9504ce00-ee17-11ea-95ab-c9bd8b8c4c6f.png)

#### 如何复现（请务必完整填写下面内容）：

火狐开发版访问https://baidu.gitee.io/amis/docs/components/json#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95

2. 粘贴有问题的完整 `amis schema` 代码：
无

3. 操作步骤
略

**Comment by nwind** [comment]
应该是已经解决l
