### ISSUE TITLE
像a标签那样为nav组件加个target属性

### ISSUE THREAD

**Issue by hlizard** [baidu/amis#923]
#### 是否关联于某个问题吗：
无

#### 预期的解决方案：
nav导航不能配置为点击以后在iframe中打开url, 感觉nav都还没原始的a标签的功能丰富, 现在点击nav导航甚至不能设置为在新窗口中打开. 按理像a标签那样再加个target属性, 然后指定为iframe的name就可以, 但是目前没有target属性. 希望添加target属性, 用法和功能需和a标签的一样.

#### 其他可接受方案：
如果有其他简便的方法实现这个也可以.

#### 任何附加信息：
无

**Comment by wuyudian1** [comment]
类似诉求还是不少，看来开发者不想做啊
