### ISSUE TITLE
修改全局样式不起作用 ！！！！！！！！！

### ISSUE THREAD

**Issue by mengxiangji** [baidu/amis#9230]
#### 描述问题：
1. 通过cssVars设置全局变量在amis文档中起作用，在编辑器中不起作用
2. 通过增加style方式也不起作用
上面两种方式组件提示里面的样式变了，但是画布里面的组件样式没有变
 

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/42375179/47eab1dd-ab05-420e-bb0a-3e96e62f54fa)
![image](https://github.com/baidu/amis/assets/42375179/98402187-423b-4a53-a504-0588eefab74c)
![image](https://github.com/baidu/amis/assets/42375179/d7d3e4f5-d005-4fdf-83d5-f83d5f8a41f3)
#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm
4. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
"amis": "^3.6.3",
    "amis-core": "^3.6.3",
    "amis-editor": "5.7.0",
    "amis-editor-core": "5.7.0",
"amis-ui": "^3.6.3",
5. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

6. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by qkiroc** [comment]
作用域的原因，在页面中的元素被限制到了AMISCSSWrapper这个空间下，所以在root上加变量就无效了。可以使用速搭的主题编辑器，里面可以对组件进行样式定制 https://aisuda.baidu-int.com/

**Comment by qkiroc** [comment]
作用域的原因，页面中的元素被限制到了AMISCSSWrapper这个作用域下，所以在root下加变量就没有效了。可以使用爱速搭的主题编辑器定制组件的样式  https://aisuda.bce.baidu.com/

**Comment by mengxiangji** [comment]
> 作用域的原因，页面中的元素被限制到了AMISCSSWrapper这个作用域下，所以在root下加变量就没有效了。可以使用爱速搭的主题编辑器定制组件的样式 https://aisuda.bce.baidu.com/

我想要动态修改页面中的元素样式，应该怎么写呢

**Comment by qkiroc** [comment]
style支持表达式
