### ISSUE TITLE
数字框单位样式错乱

### ISSUE THREAD

**Issue by ggymzz** [baidu/amis#9251]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis:3.6.3, 当前版本无beta版本

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "input-number",
  "label": "数字",
  "name": "number",
  "keyboard": true,
  "id": "u:a9fa1b3cfbbc",
  "step": 1,
  "unitOptions": [
    {
      "label": "g",
      "value": "g"
    }
  ],
  "size": "md"
}
```

5. 操作步骤
复现步骤：任意amis schema的表单或可加入数字框的区域中，加上带有单位的数字框，调整数字框大小size除full之外的值就会导致该控件样式错乱。见下图所示：
![微信截图_20231226212539](https://github.com/baidu/amis/assets/67571519/752d321c-33fa-4682-a1be-209554e3399a)

**Comment by qkiroc** [comment]
https://github.com/baidu/amis/pull/9333
