### ISSUE TITLE
crud批量操作时，把选中的item中指定字段展示在tpl中，渲染出问题了

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#926]
#### 实现场景：
crud批量操作，把选中的item中指定字段展示在tpl中，渲染出问题了

#### 存在的问题：
![image](https://user-images.githubusercontent.com/64950961/92343037-3da37e00-f0f5-11ea-9aad-839fd8951f7b.png)
想把每一个item的某个字段，放到一个数组里，然后循环数组，分别渲染到span标签中
渲染出来是这样子的
![image](https://user-images.githubusercontent.com/64950961/92343146-83f8dd00-f0f5-11ea-94a3-2dfb6e41974f.png)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by RickCole21** [comment]
因为`${xxx}`和`<% %>`不能混用，再去看下模板文档

**Comment by tanmengfei** [comment]
> 因为`${xxx}`和`<% %>`不能混用，再去看下模板文档

那我如果想实现这种功能该咋办，其实就是想把选中的item里边的一个字段，展示在dialog里边

**Comment by RickCole21** [comment]
`<%= data.items.map()  %>`，具体代码我不写了吧，就是js代码

**Comment by tanmengfei** [comment]
> `<%= data.items.map() %>`，具体代码我不写了吧，就是js代码

好嘞，谢啦
