### ISSUE TITLE
下载文件提示Should have "Content-Disposition" in Header

### ISSUE THREAD

**Issue by sym134** [baidu/amis#9265]
#### 实现场景：
我想现在zip文件

#### 存在的问题：
下载总是失败，提示：Should have "Content-Disposition" in Header

#### 当前方案：
```
{
  "type": "button",
  "label": "更新弹窗数据",
  "onEvent": {
    "click": {
      "actions": [
        {
          "actionType": "download",
          "ignoreError": false,
          "api": {
            "url": "这是测试url",
            "method": "post",
            "requestAdaptor": "",
            "adaptor": "",
            "messages": {},
            "data": {
              "&": "$$"
            }
          }
        }
      ]
    }
  },
  "id": "u:5289975c96c6"
}
```

响应头已按要求添加
<img width="734" alt="image" src="https://github.com/baidu/amis/assets/32946251/19692ccd-0263-4cf9-9688-59c8d9cf6b1f">

**Comment by 2betop** [comment]
我猜跨域了，需要额外配置个 header

```
Access-Control-Expose-Headers:  Content-Disposition
```

https://aisuda.bce.baidu.com/amis/zh-CN/components/action#%E4%B8%8B%E8%BD%BD%E8%AF%B7%E6%B1%82

**Comment by sym134** [comment]
> 我猜跨域了，需要额外配置个 header
> 
> ```
> Access-Control-Expose-Headers:  Content-Disposition
> ```
> 
> https://aisuda.bce.baidu.com/amis/zh-CN/components/action#%E4%B8%8B%E8%BD%BD%E8%AF%B7%E6%B1%82

没有跨域，都是本地127.0.0.1，当然我也试着加了，不行还是这个错误
<img width="591" alt="image" src="https://github.com/baidu/amis/assets/32946251/9cb66a34-0fff-49eb-8259-ce541ead5c55">

**Comment by 2betop** [comment]
自己写的 fetcher？ 有没有实现 调用 `attachmentAdpator` ?  https://github.com/baidu/amis/blob/master/packages/amis-core/src/utils/attachmentAdpator.ts

**Comment by zhushibo** [comment]
俺也一样
![image](https://github.com/baidu/amis/assets/26269311/876ed3f7-3105-468b-8c22-096a74b8815e)

**Comment by zhushibo** [comment]
> > 我猜跨域了，需要额外配置个 header
> > ```
> > Access-Control-Expose-Headers:  Content-Disposition
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://aisuda.bce.baidu.com/amis/zh-CN/components/action#%E4%B8%8B%E8%BD%BD%E8%AF%B7%E6%B1%82
> 
> 没有跨域，都是本地127.0.0.1，当然我也试着加了，不行还是这个错误 <img alt="image" width="591" src="https://private-user-images.githubusercontent.com/32946251/293183403-9cb66a34-0fff-49eb-8259-ce541ead5c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTk0OTUsIm5iZiI6MTcwNjQ5OTE5NSwicGF0aCI6Ii8zMjk0NjI1MS8yOTMxODM0MDMtOWNiNjZhMzQtMGZmZi00OWViLTgyNTktY2U1NDFlYWQ1YzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzMzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZDVmMjMyODgxODY4ODdhMWExNzY2YmMzNTNiMDc2NjFhMTc1NzMxOTYwZjYyZDVlODQwYmVlNjEzNTc4OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rPJMTimDZhODUxonPMLqhyQWoqiB3WBcSvT_95Gx7tY">

自定义的fetch需要加入attachmentAdpator,参考下面代码
```js
    config.headers['Content-Type'] = 'application/json';

    if (method !== 'post' && method !== 'put' && method !== 'patch') {
      if (data) {
        config.params = data;
      }
      return (axios as any)[method](url, config);
    } else if (
      data &&
      typeof data !== 'string' &&
      !(data instanceof Blob) &&
      !(data instanceof ArrayBuffer)
    ) {
      data = JSON.stringify(data);
      config.headers['Content-Type'] = 'application/json';
    }
    config.headers = headers
      ? { ...config.headers, ...headers }
      : config.headers ?? {};
    config.method = method;
    config.data = data;
    config.url = url;
    config.responseType = api.responseType || 'json';

    // 需要适配
    let response = await (axios as any)[method](url, data, config);
    response = await attachmentAdpator(response, () => '');
    return response;
```

**Comment by RocChing** [comment]
按照如下代码 已经修改
// 需要适配
    let response = await (axios as any)[method](url, data, config);
    response = await attachmentAdpator(response, () => '');
    return response;

已经不报   Should have "Content-Disposition" in Header 这个错误
但是下载后 没有任何反应 也没报错。

**Comment by RocChing** [comment]
已经可以了，把请求改成异步就可以了
