### ISSUE TITLE
amis

### ISSUE THREAD

**Issue by fightingGril0621** [baidu/amis#930]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
1.我想要在一个vue项目中配置一个入口，添加html页面实现对数据的crud，准备用amis快速搭建多个crud页面。
jssdk比较方便。我在项目中配置了json-server ,url配置http://localhost：3000/table.但是amis的crud接受不到json数据
2.后来又配置请求localhost:8080/api/table,解决了跨域还是获取不到json，显示网络错误
3.想在相对路径下直接请求db.json文件也显示获取不到数据
#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
为什么获取不到json呢？
有amis的jssdk的crud的demo么？

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>AMIS Demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <link rel="stylesheet" 
        href="https://houtai.baidu.com/v2/csssdk">
    <style>
        html, body, .app-wrapper {
            position: relative;
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
        }
    </style>
</head>
  </head>
  <div id="about"></div>
  <div id="root" class="app-wrapper"></div>
  <script src="https://houtai.baidu.com/v2/jssdk"></script>
  <script type="text/javascript">
  (function() {
      var amis = amisRequire('amis/embed');
      amis.embed('#root', {
          type: 'page',
          title: 'AMIS Demo',
          
          body: {
            "type":"crud",
              "api": {
                "method":"post",
                "url":"/api/BlogList",
                adaptor:'return {\n    ...payload,\n    status: payload.code === 200 ? 0 : payload.code\n}',
                "data": {
                  "&": "$"
                  }  
              },
              "columns": [
                {
                  "name": "id",
                  "label": "ID"
                },
                
                {
                  "type":"service",
                  "label": "title",
                  "api":"http://localhost:3000/BlogList",
                  "adaptor":"return {\n    ...payload,\n    status: payload.code === 200 ? 0 : payload.code\n}",
                  "body": {
                    "type": "tpl",
                    "tpl": "标题："
                  }
                },
                {
                  "type":"service",
                  "label": "auther",
                  "api":"http://localhost:3000/BlogList",
                  "adaptor":"return {\n    ...payload,\n    status: payload.code === 200 ? 0 : payload.code\n}",
                  "body": {
                    "type": "tpl",
                    "tpl": "作者："
                  }
                }
                ],
              // "controls": [
              //   {
              //     "type":"text",
              //     "name": "id",
              //     "label": "ID"
              //   },
              //   {
              //     "type":"text",
              //     "name": "title",
              //     "label": "title"
              //   },
              //   {
              //     "type":"text",
              //     "name": "auther",
              //     "label": "auther"
              //   }
              //   ],
        "status": 0,
        "msg": "",
        "data":{
          "items":[
            {
              // 每一行的数据
              "id": 1,
              "title":"testo01",
              "auther":"hjl"
            },
            {
              // 每一行的数据
              "id": 2,
              "title":"testo02",
              "auther":"hjl"
            },
            {
              // 每一行的数据
              "id": 3,
              "title":"testo03",
              "auther":"hjl"
            },
            {
              // 每一行的数据
              "id": 4,
              "title":"testo04",
              "auther":"hjl"
            },
          ],
        //"total": 200 
            // 注意！！！这里不是当前请求返回的 items 的长度，而是数据库中一共有多少条数据，用于生成分页组件
      // 如果你不想要分页，把这个不返回就可以了。
      "hasNext":true
        }
      }
      });
  })();
  </script>
  
</body>
</html>
```
code here...
```

**Comment by nwind** [comment]
跨域问题
