### ISSUE TITLE
table变成非确认模式后，默认会有一行，加号点击两次才能新增一行

### ISSUE THREAD

**Issue by tanmengfei** [baidu/amis#931]
#### 描述问题：
table变成非确认模式后，默认会有一行，加号点击两次才能新增一行

#### 截图或视频：
![image](https://user-images.githubusercontent.com/64950961/92365714-cb4b9180-f126-11ea-8801-26ffc9262cc8.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. 粘贴有问题的完整 `amis schema` 代码：
![image](https://user-images.githubusercontent.com/64950961/92365670-bbcc4880-f126-11ea-9d87-e9f826ce32bd.png)

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by RickCole21** [comment]
贴代码吧，图片不好复制

**Comment by tanmengfei** [comment]
> 贴代码吧，图片不好复制

`{
                                    "type": "table",
                                    "name": "body",
                                    "hiddenOn": "data.type != 'application/x-www-form-urlencoded'",
                                    // "editable": true,
                                    "addable": true,
                                    "removable": true,
                                    "needConfirm": false,
                                    "label": false,
                                    "columns": [
                                        {
                                            "name": "bodyKey",
                                            "label": "KEY"
                                        },
                                        {
                                            "name": "bodyValue",
                                            "label": "VALUE"
                                        }
                                    ] 
                                `

**Comment by nwind** [comment]
新版应该是改了
