### ISSUE TITLE
在富文本编辑器tinymce中插入表格页面会卡死

### ISSUE THREAD

**Issue by wuchunxu** [baidu/amis#9317]
#### 描述问题：
富文本编辑器tinymce，插入表格这个插入图片页面会卡死，最后崩溃。

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/33026829/07aaa0ec-c2de-4add-8e69-f08fe251a5e1)

#### 如何复现（请务必完整填写下面内容）：
官方示例中即可复现：
步骤：
1、打开官方示例地址：https://aisuda.github.io/amis-editor-demo/#/hello-world
2、点击编辑，在编辑器内拖一个富文本组件
3、富文本编辑器中插入表格，页面即卡死
4、6.0版也有这个问题

其他提示：
1、使用sdk没有这个问题；
2、react中仅引入amis，不引入amis-editor，也没有这个问题
3、react中**同时引入amis和amis-editor**后，问题出现

**Comment by wuchunxu** [comment]
另外，我新建一个包，仅引入amis（没有amis-editor），做一些组件自定义操作，然后再导出amis-renderer组件作为库供其他项目使用，有同样问题。所以，我猜测问题是引入amis再导出这样的操作出现bug。

**Comment by hsg4ok** [comment]
我这里也出现了同样的问题，插入图片和插入表格，都会把浏览器卡崩溃掉。控制台也没有出现报错

**Comment by 2betop** [comment]
不能复现，能否录个视频？

**Comment by wuchunxu** [comment]
升级到新版本，大概6.0之后，这个问题没有了
