### ISSUE TITLE
编辑器问题，发送Psot方式Json格式数据无法正确发送

### ISSUE THREAD

**Issue by atliwen** [baidu/amis#9318]
#### 描述问题：

在新版的编辑器中，发送PSOT 请求，设置为json格式。无法发送Json数据。 发送的是个字符串。

#### 截图或视频：
5.6.2 版本  和 自己升级为 6.0.0 版本都有这个问题
![image](https://github.com/baidu/amis/assets/10055836/20d0c352-afaf-4c5a-bac1-da9c2e84fcd2)

5.4.1 版本 就没这个问题。
![image](https://github.com/baidu/amis/assets/10055836/6f5c9605-8c35-4574-bf80-988b053f1db2)

#### 如何复现（请务必完整填写下面内容）：

https://aisuda.github.io/amis-editor-demo/demo-5.6.2/index.html#/edit/1  

使用官方编辑器地址，新增一个表单，然后设置post 请求，选择json方式。
![image](https://github.com/baidu/amis/assets/10055836/0dad281a-e355-480d-b968-50d698b01816)

**Comment by atliwen** [comment]
@2betop  大佬求帮忙啊。现在升级版本升级不上去了。

**Comment by 2betop** [comment]
请贴一下 fetcher 的实现

**Comment by atliwen** [comment]
@2betop  我找为什么了，  是axios 的版本升级了的问题，  原先用是 0.21.1 ，后来升级到了 0.21.2 。 0.21.1 没问题！  您这边也改一下版本吧。

**Comment by Heming9** [comment]
同样的问题，搞了一天了，我是新拉下来的editor

**Comment by Heming9** [comment]
> 0.21.1
感谢老哥，实测有效，折磨死我了

**Comment by Heming9** [comment]
> @2betop 我找为什么了， 是axios 的版本升级了的问题， 原先用是 0.21.1 ，后来升级到了 0.21.2 。 0.21.1 没问题！ 您这边也改一下版本吧。

感谢老哥，实测有效，折磨死我了

**Comment by luoxue2017** [comment]
@2betop 源码也改下，demo也改下，看master分支 axios 还是 0.21.2版，还有好多人会遇到问题
