### ISSUE TITLE
为控件选择图标时有bug，配置图标麻烦且耗时

### ISSUE THREAD

**Issue by citynook** [baidu/amis#9326]
#### 描述问题：
1. 图标列表只有几个示例的图标，手动输入不匹配则显示"No Data"，必须在左侧代码面板中找到 icon 属性并修改值才能完成图标的设置，当代码面板代码很多的时候，整个过程麻烦且耗时。
2. 图标选择控件的bug复现步骤
2.1 鼠标点击输入框，弹出图标选择下拉框
2.2 再次鼠标点击输入框，图标选择下拉框消失
2.3 从此时开始，只要鼠标点击输入框，图标选择下拉框都是闪了一下就消失。

建议改善方案：
方案1，能提供更好的用户体验：
方案说明：图标选择控件由一个文本框和一个按钮组成，开发者在Font Awesome官网找到图标后，直接粘贴图标名到文本框即可。
               点击按钮后，弹出一个图标选择对话框，类似于 Font Awesome官网的图标搜索界面，可以快速预览及选择图标。

方案2：实现简单，开发者操作也简单：
方案说明：图标选择控件只提供一个文本框，开发者在Font Awesome官网找到图标后，直接粘贴图标名即可。

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/127393297/e6056541-1887-4524-b10a-da440a8d072c)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

4. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis-editor: 6.0.0

6. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

7. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by qkiroc** [comment]
图标的升级版本是[爱速搭平台](https://aisuda.bce.baidu.com)的功能，开源项目建议自行优化并替换图标选择插件

**Comment by citynook** [comment]
@qkiroc 请问要替换图标选择插件是要修改 amis-editor 的源码吗？那能否用最简单的方案，请官方直接将图标选择下拉框改成文本框即可，至少不让要使用者到代码面板中改属性~~

**Comment by qkiroc** [comment]
这个属于高级功能，开源项目没有计划提供。可以写一个插件去覆盖，比如setSchemaTpl('icon', {...})，{...}为自行实现的图标选择器的amis schema

**Comment by citynook** [comment]
下拉框改成文本框就属于高级功能范围，有点理解不了~

**Comment by qkiroc** [comment]
旧版的图标选择器不维护了，用户可以自行替换

**Comment by qkiroc** [comment]
旧版的图标选择器目前没有维护计划了。新版的功能类似这样，但这个目前没有开源计划。所以如果觉得旧版的功能无法满足需求，可以自行替换插件
<img width="1123" alt="image" src="https://github.com/baidu/amis/assets/30946345/397151c8-c3a2-45bd-9349-7c83a71f5f3d">

**Comment by Yabsolute** [comment]
> 旧版的图标选择器目前没有维护计划了。新版的功能类似这样，但这个目前没有开源计划。所以如果觉得旧版的功能无法满足需求，可以自行替换插件 <img alt="image" width="1123" src="https://private-user-images.githubusercontent.com/30946345/294424415-397151c8-c3a2-45bd-9349-7c83a71f5f3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQyNjk2MjksIm5iZiI6MTc0NDI2OTMyOSwicGF0aCI6Ii8zMDk0NjM0NS8yOTQ0MjQ0MTUtMzk3MTUxYzgtYzNhMi00NWJkLTkzNDktN2M4M2E3MWY1ZjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDEwVDA3MTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YzdhNDM1OWRkNWJjOGI0ZTI0MTEzNjg1YzQwNTJjN2E0MjgzZThhYjA1ZjJjMjVkMWIyOGNkY2RlOGE4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dT69krpKGL0ZF-R1lEZNQ2OS0ltFWc1MlQ8iOHvcimA">

你好 麻烦问下这个setSchemaTpl在哪里使用

**Comment by Yabsolute** [comment]
> > 旧版的图标选择器目前没有维护计划了。新版的功能类似这样，但这个目前没有开源计划。所以如果觉得旧版的功能无法满足需求，可以自行替换插件 <img alt="image" width="1123" src="https://private-user-images.githubusercontent.com/30946345/294424415-397151c8-c3a2-45bd-9349-7c83a71f5f3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQyNjk2MjksIm5iZiI6MTc0NDI2OTMyOSwicGF0aCI6Ii8zMDk0NjM0NS8yOTQ0MjQ0MTUtMzk3MTUxYzgtYzNhMi00NWJkLTkzNDktN2M4M2E3MWY1ZjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDEwVDA3MTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YzdhNDM1OWRkNWJjOGI0ZTI0MTEzNjg1YzQwNTJjN2E0MjgzZThhYjA1ZjJjMjVkMWIyOGNkY2RlOGE4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dT69krpKGL0ZF-R1lEZNQ2OS0ltFWc1MlQ8iOHvcimA">
> 
> 你好 麻烦问下这个setSchemaTpl在哪里使用

这个方法貌似有问题，统一覆盖后个别属性异常 setSchemaTpl
