### ISSUE TITLE
数据映射种【json】的参数说明有误

### ISSUE THREAD

**Issue by qidasheng369** [baidu/amis#9339]
#### 描述问题：
`join
当变量值是数组时，可以把内容连接起来。

基本用法
${xxx | join[:glue]}
glue：连接符，默认为空字符
编辑代码 
array is a,b,c`

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/22865380/20f73338-2075-4f6b-9278-ed020754d9df)

#### 如何复现（请务必完整填写下面内容）：

https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/data-mapping#join

4. 操作步骤
打开上边连接

**Comment by qidasheng369** [comment]
可能是我理解的有问题，默认是空字符串，是说的调用let glue = ''; Arrays.join(glue)的参数是空字符串吗？

**Comment by nwind** [comment]
默认确实不是空字符串，而是 undefined，一会改一下文档

**Comment by nwind** [comment]
#10306
