### ISSUE TITLE
能否对富文本的输入和输出内容做处理？

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#9364]
#### 实现场景：
希望能对富文本的输入和输出内容做处理。例如pipeIn和pipeOut这样的方法

#### 存在的问题：
目前不支持

#### 当前方案：

```
{ 
  label: 'Rich-Text',
  value: 'rich-text',
  pipeIn: (value) => {
    return value
  }
}
```

**Comment by nwind** [comment]
只有表单项支持 pipeIn 和 pipeOut，这种展示类的过滤在后端做或 api 适配器里做好了
