### ISSUE TITLE
页面变量与 内存变量在 amis-edit 编辑器中不能选择，不能使用

### ISSUE THREAD

**Issue by xiaofeihe** [baidu/amis#9373]
#### 描述问题：

页面变量与 内存变量在 amis-edit 编辑器中不能选择，不能使用

#### 截图或视频：

![图片](https://github.com/baidu/amis/assets/1018509/867442c8-88f2-45aa-8f12-488d403a05e6)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
如：点击某个按钮后，去修改页面变量值，

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
使用 amis-edit  3.6.3 
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by xiaofeihe** [comment]
升级到6.0后 正常了。

**Comment by cheungzh** [comment]
> 升级到6.0后 正常了。

大佬想问一下， 我升级到6.0.0还是有问题是为啥啊
