### ISSUE TITLE
inputable父子结构数据下，可编辑存在bug(同时开启编辑多行)

### ISSUE THREAD

**Issue by ziBLan** [baidu/amis#9379]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
{
  "type": "service",
  "id": "u:056a6ccb30de",
  "data": {
    "rows": [
      {
        "engine": "Trident",
        "browser": "Internet Explorer 4.0",
        "platform": "Win 95+",
        "version": "4",
        "grade": "X",
        "children": [
          {
            "engine": "Trident",
            "browser": "Internet Explorer 4.0",
            "platform": "Win 95+",
            "version": "4",
            "grade": "X",
            "id": 1001
          },
          {
            "engine": "Trident",
            "browser": "Internet Explorer 5.0",
            "platform": "Win 95+",
            "version": "5",
            "grade": "C",
            "id": 1002
          }
        ],
        "id": 1
      },
      {
        "engine": "Trident",
        "browser": "Internet Explorer 5.0",
        "platform": "Win 95+",
        "version": "5",
        "grade": "C",
        "children": [
          {
            "engine": "Trident",
            "browser": "Internet Explorer 4.0",
            "platform": "Win 95+",
            "version": "4",
            "grade": "X",
            "id": 2001
          },
          {
            "engine": "Trident",
            "browser": "Internet Explorer 5.0",
            "platform": "Win 95+",
            "version": "5",
            "grade": "C",
            "id": 2002
          }
        ],
        "id": 2
      },
      {
        "engine": "Trident",
        "browser": "Internet Explorer 5.5",
        "platform": "Win 95+",
        "version": "5.5",
        "grade": "A",
        "id": 3,
        "children": [
          {
            "engine": "Trident",
            "browser": "Internet Explorer 4.0",
            "platform": "Win 95+",
            "version": "4",
            "grade": "X",
            "id": 3001
          },
          {
            "engine": "Trident",
            "browser": "Internet Explorer 5.0",
            "platform": "Win 95+",
            "version": "5",
            "grade": "C",
            "id": 3002
          }
        ]
      },
      {
        "engine": "Trident",
        "browser": "Internet Explorer 6",
        "platform": "Win 98+",
        "version": "6",
        "grade": "A",
        "id": 4,
        "children": [
          {
            "engine": "Trident",
            "browser": "Internet Explorer 4.0",
            "platform": "Win 95+",
            "version": "4",
            "grade": "X",
            "id": 4001
          },
          {
            "engine": "Trident",
            "browser": "Internet Explorer 5.0",
            "platform": "Win 95+",
            "version": "5",
            "grade": "C",
            "id": 4002
          }
        ]
      },
      {
        "engine": "Trident",
        "browser": "Internet Explorer 7",
        "platform": "Win XP SP2+",
        "version": "7",
        "grade": "A",
        "id": 5,
        "children": [
          {
            "engine": "Trident",
            "browser": "Internet Explorer 4.0",
            "platform": "Win 95+",
            "version": "4",
            "grade": "X",
            "id": 5001
          },
          {
            "engine": "Trident",
            "browser": "Internet Explorer 5.0",
            "platform": "Win 95+",
            "version": "5",
            "grade": "C",
            "id": 5002
          }
        ]
      }
    ]
  },
  "body": [
    {
      "type": "input-table",
      "className": "m-b-none",
      "columns": [
        {
          "name": "id",
          "label": "ID",
          "id": "u:2f5e24f83357",
          "placeholder": "-"
        },
        {
          "name": "engine",
          "label": "Engine",
          "id": "u:0855e7f1ba77"
        },
        {
          "name": "grade",
          "label": "Grade",
          "id": "u:5a7c156add1c"
        },
        {
          "name": "version",
          "label": "Version",
          "id": "u:81a46704a3c1"
        },
        {
          "name": "browser",
          "label": "Browser",
          "id": "u:27c23ea2c4c3"
        },
        {
          "name": "id",
          "label": "ID",
          "id": "u:a0671b84b8aa"
        },
        {
          "name": "platform",
          "label": "Platform",
          "id": "u:23fe1bb0dc5a"
        }
      ],
      "id": "u:42df96349b55",
      "minLength": 0,
      "addable": true,
      "name": "rows",
      "columnsTogglable": false,
      "editable": true,
      "showIndex": false
    }
  ]
}

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by lengqingfeng** [comment]
我也在看这个组件一个问题，setVariable，导致父子的超过2行每次编辑都自动折回去，难受啊？这个bug。公司让我修复呢，不知道怎么改，哪位大神写的代码
