### ISSUE TITLE
jssdk版的音视频，文件不存在的时候会一直请求，是不是bug啊？

### ISSUE THREAD

**Issue by 309454886** [baidu/amis#939]
#### 描述问题：
jssdk版的音视频，文件不存在的时候会一直请求？
![QQ图片20200910153012](https://user-images.githubusercontent.com/61499032/92695621-4d33f880-f37b-11ea-99c2-fe6ff8455f3e.png)

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
jssdk版

2. 粘贴有问题的完整 `amis schema` 代码：

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
没复现可能是新版修了
