### ISSUE TITLE
autoFill功能异常，在表单初始化时不应该执行

### ISSUE THREAD

**Issue by yinlianghui** [baidu/amis#9391]
#### 描述问题：

autoFill的设计应该是用户点击字段填写值的时候才去触发autoFill功能，但是目前是表单初始化的时候也会自动执行autoFill，这在被填充字段本身就有初始值的情况下是不合理的，比如编辑表单窗口刚打开的时候不应该触发autoFill去改写字段本身的值。

#### 截图或视频：

如下图所示，官网demo中可以看到，给字段配置默认值的情况下，表单初始化时，会自动把字段默认值改为autoFill填充值。
![image](https://github.com/baidu/amis/assets/6219465/8bf4ad8e-6aa9-4f91-b37f-e4c9d38a32ea)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.6，目前实测3.2,3.6,6.0都有问题，2.9是好的。

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "data": {
    "option.submitValidate": "xxxx",
    "select": "a"
  },
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "debug": true,
    "debugConfig": {
      "levelExpand": 2
    },
    "body": [
      {
        "type": "select",
        "label": "autoFill触发器",
        "name": "select",
        "autoFill": {
          "option.instantValidate": "${label}",
          "option.submitValidate": "${label}"
        },
        "clearable": true,
        "options": [
          {
            "label": "Option A",
            "value": "a"
          },
          {
            "label": "Option B",
            "value": "b"
          }
        ]
      },
      {
        "type": "input-text",
        "name": "option.instantValidate",
        "label": "目标1",
        "description": "填充后立即校验",
        "required": true,
        "validateOnChange": true,
        "validations": {
          "equals": "Option B"
        },
        "validationErrors": {
          "equals": "校验失败，数据必须为Option B"
        }
      },
      {
        "type": "input-text",
        "name": "option.submitValidate",
        "label": "目标2",
        "description": "填充后提交表单时才校验",
        "required": true,
        "validations": {
          "equals": "Option B"
        },
        "validationErrors": {
          "equals": "校验失败，数据必须为Option B"
        },
        "value": "abc"
      },
      {
        "type": "input-text",
        "name": "option.c",
        "label": "表单项3",
        "description": "不受autoFill影响的表单项"
      }
    ]
  }
}
```

5. 操作步骤
把上面的schema code copy到官网autoFill示例demo https://aisuda.bce.baidu.com/amis/zh-CN/components/form/options#%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%85%85-autofill 内即可重现此问题。

**Comment by yinlianghui** [comment]
鉴于amis 2.9没有这个问题，希望不要添加配置项来修正此问题，最好能改为跟2.9的效果一样，这样我们之前项目中大量使用autoFill的地方就不用额外处理了，谢谢 @2betop

**Comment by lengqingfeng** [comment]
我们用的都需要自动执行，不执行各种问题了，初始化不应该自动填充进去吗，新版本导致很多表单数据么提交上去

**Comment by yinlianghui** [comment]
> 我们用的都需要自动执行，不执行各种问题了，初始化不应该自动填充进去吗，新版本导致很多表单数据没提交上去

比如弹出编辑记录表单时，如果刚打开表单的那该A字段中因为配置了autoFill自动把B字段值按某个需求逻辑填充上去了，此时会把B字段值在数据库中已经保存好的真实值改掉的，但是实际上我们肯定需要在刚打开编辑表单时B字段显示为数据库中真实的值而不是A字段autoFill填充的值。

**Comment by 2betop** [comment]
@yinlianghui initAutoFill 默认为 fillIfNotSet ，如果初始值里面已经有对应的值了，会跳过，理论上能兼容你那边旧的用法。

`initAutoFill` 有三种值分别如下，默认为 `fillIfNotSet`。

- `fillIfNotSet` 如果目标值不存在则填充，如果目标值存在则不填充。
- `true` 总是填充，如果目标值存在则覆盖。
- `false` 总是不填充，如果目标值存在则不填充。

**Comment by yinlianghui** [comment]
@2betop 感谢支持，但是如果配置了api的情况下问题依然存在 ，希望兼容下，让initAutoFill参数在配置了api属性时也能生效，我已经另外建了issue了：autoFill的initAutoFill属性是否能支持配置了api接口属性的情况 #9631

**Comment by yinlianghui** [comment]
@2betop picker组件也需要autoFill的initAutoFill属性功能，已经另外建issue了，见：https://github.com/baidu/amis/issues/9716 ，感谢支持。
