### ISSUE TITLE
怎么实现一个按钮根据返回结果跳转到不同的url

### ISSUE THREAD

**Issue by 123sdy** [baidu/amis#9419]
#### 实现场景：
我想实现一个功能，定义一个表单，表单内有公司，有提交按钮，如何在提交按钮后，请求api之后，根据api返回结果重定向到不同的页面

#### 存在的问题：
目前无法根据条件重定向百度或者搜狗页面，请大佬指点一下

#### 当前方案：
![image](https://github.com/baidu/amis/assets/52692833/5ada931a-6eba-4ed0-ae78-01ef9e298026)

**Comment by CheshireJCat** [comment]
方法1，直接在api的适配器里`adaptor` 进行拦截，判断后用类似你现在写的一样，location跳转
方法2，把提交api配置在form上，然后在form的提交成功事件上可以获取到请求后的结果，然后进行判断用打开页面事件跳转
方法3，把type submit 换成 button，然后添加一个请求api动作，后面再添加一个跳转动作，用expression判断处理或者用表达式拼接不同的url即可
