### ISSUE TITLE
crud中的数据如何居中显示，用什么属性调整，麻烦解惑，感谢！

### ISSUE THREAD

**Issue by JayHandsome** [baidu/amis#943]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by RickCole21** [comment]
目前需要在 CRUD 的`column`上配置`className:"text-center"`

**Comment by JayHandsome** [comment]
> 目前需要在 CRUD 的`column`上配置`className:"text-center"`

有用，非常感谢~
