### ISSUE TITLE
input-text组件添加值变化自定义事件，开启可清除属性后，只会在输入值时触发，点清除按钮不会触发

### ISSUE THREAD

**Issue by Hemri789** [baidu/amis#9436]
#### 描述问题：

input-text组件添加值变化自定义事件，开启可清除属性后，只会在输入或删除值时触发，点清除按钮不会触发

#### 截图或视频：

![PixPin_2024-01-15_16-32-22](https://github.com/baidu/amis/assets/92628105/3577f9b1-5608-4ad4-a9db-dd552c7276bd)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

官网demo页面https://aisuda.github.io/amis-editor-demo/#/edit/2

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "input-text",
  "label": "输入文本框",
  "name": "text",
  "id": "u:378b4e736a7a",
  "clearable": true,
  "onEvent": {
    "change": {
      "weight": 0,
      "actions": [
        {
          "ignoreError": false,
          "script": "console.log('值变化自定义事件')",
          "actionType": "custom"
        }
      ]
    }
  },
  "size": "sm",
  "mode": "normal"
}
```

4. 操作步骤

**Comment by hsm-lv** [comment]
后面会补上，可以先通过监听clear来解决您的问题
