### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by liuxiangyu1984** [baidu/amis#9452]
前端的地址是localhost:1803，要访问的接口是localhost:52789，前端是vue，后端采用的是.net core
一直提示跨域问题"Access to XMLHttpRequest at 'http://localhost:52789/api/project_basicinfos/load' from origin 'http://localhost:1803' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute."

需要在配置文件里面如何配置
	api: {
		    url: "http://localhost:52789/api/project_basicinfos/load",
		    method: "post",
		    requestAdaptor: "",
		    adaptor: "",
		    messages: {},
		  }

**Comment by hu54301969** [comment]
经典问题,要么后端配置跨域,要么前端全局适配器走axios,但还是推荐后端配置好它,就可以使用amis的默认方式了

**Comment by liuxiangyu1984** [comment]
> 经典问题,要么后端配置跨域,要么前端全局适配器走axios,但还是推荐后端配置好它,就可以使用amis的默认方式了

后端用的是.net core，我建立一个简单的webapi来测试，结果也是提示跨域错误，在startup里面也配置了跨域的方式，我用官网上的例子就能请求成功
namespace webapi
{
    public class Startup
    {
        public IHostEnvironment Environment { get; }
        public IConfiguration Configuration { get; }
        public Startup(IConfiguration configuration,IHostEnvironment environment)
        {
            Configuration = configuration;
            Environment = environment;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
        }

        public void Configure(IApplicationBuilder app,IHostEnvironment env,ILoggerFactory loggerFactory)
        {
            app.UseCors(builder => builder.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader());
        }
    }
}
