### ISSUE TITLE
build2lib 打出来的包在浏览器报错 ReferenceError: require is not defined

### ISSUE THREAD

**Issue by wubin1989** [baidu/amis#9482]
用amis-widget-cli工具 执行 npm run build2lib 打出来的包在浏览器报错 ReferenceError: require is not defined，react+ts技术栈，请问有没有办法解决？

**Comment by wibetter** [comment]
@wubin1989  请提供以下几个背景信息：
1、用amis-widget-cli工具打包的是哪个项目？
2、amis-config.js 的全量配置发过来看看；
3、在什么技术栈什么项目中如何使用打包后的包？

**Comment by wubin1989** [comment]
@wibetter 这个工具打出来的包是不是只有爱速搭支持？不用爱速搭，直接通过script标签引到index.html文件里，浏览器加载执行是不是不支持？

**Comment by wubin1989** [comment]
@wibetter 我试了几种情况，vue的，react，react+ts的，npm run build2lib执行以后打出来的umd.js文件都有require

**Comment by wibetter** [comment]
amis-widget-cli中的build2lib 方法主要是用来构建lib库的，跟使用的地方没关系。你想直接在浏览器端使用，还需要确保打包的lib模块引入的依赖模块也都是UMD的包，避免引入commonJS模块。
