### ISSUE TITLE
如何通过amis实现异步download?

### ISSUE THREAD

**Issue by chixiaopao** [baidu/amis#9485]
#### 实现场景：
![9722edab-32bb-471f-b73a-61f1282237bd](https://github.com/baidu/amis/assets/101961274/4b4aa224-f136-40b0-b4e8-df392221ff6f)
想点击download按钮后，直接在右上角进行异步下载.
但是现在点击完成download按钮后，浏览器一直在转动，不进行异步下载.
![3a4dbeaf-16b1-40b7-bb5c-f4f5e959a256](https://github.com/baidu/amis/assets/101961274/a82e0cc4-3844-46e9-8d5c-bffd9c0c0950)

不是前端开发所以不知道该如何实现?

#### 存在的问题：
不知道该如何实现异步下载.

#### 当前方案：
前端等待下载完成.

**Comment by yyccvae** [comment]
同问，后端接口已经返回了文件流，通过打开新浏览器窗口可以实现下载，但是在其他组件，比如视频，得等下载请求加载完，如果文件过大，会卡顿很久

**Comment by chixiaopao** [comment]
> 同问，后端接口已经返回了文件流，通过打开新浏览器窗口可以实现下载，但是在其他组件，比如视频，得等下载请求加载完，如果文件过大，会卡顿很久

我也是这种情况，从hdfs download文件几个G，后端已经返回了文件流，前端一直转啊转.

**Comment by yyccvae** [comment]
> > 同问，后端接口已经返回了文件流，通过打开新浏览器窗口可以实现下载，但是在其他组件，比如视频，得等下载请求加载完，如果文件过大，会卡顿很久
> 
> 我也是这种情况，从hdfs download文件几个G，后端已经返回了文件流，前端一直转啊转.

你这种可以通过打开新窗口解决
`{
  "type": "button",
  "label": "按钮",
  "onEvent": {
    "click": {
      "actions": [
        {
          "ignoreError": false,
          "actionType": "url",
          "args": {
            "url": "/dowloadurl",
            "blank": true
          }
        }
      ]
    }
  }
}`

**Comment by chixiaopao** [comment]
> > > 同问，后端接口已经返回了文件流，通过打开新浏览器窗口可以实现下载，但是在其他组件，比如视频，得等下载请求加载完，如果文件过大，会卡顿很久
> > 
> > 
> > 我也是这种情况，从hdfs download文件几个G，后端已经返回了文件流，前端一直转啊转.
> 
> 你这种可以通过打开新窗口解决 `{ "type": "button", "label": "按钮", "onEvent": { "click": { "actions": [ { "ignoreError": false, "actionType": "url", "args": { "url": "/dowloadurl", "blank": true } } ] } } }`

thanks，我试一下~

**Comment by 2betop** [comment]
直接用新浏览器打开可以的
