### ISSUE TITLE
PopOver与TooltipWrapper用法扩展

### ISSUE THREAD

**Issue by ggymzz** [baidu/amis#9487]
#### 是否关联于某个问题吗：
1、我想要在点击input-tag时可以弹出PopOver或TooltipWrapper，允许自定义SchemaNode内容，效果如下所示：
![image](https://github.com/baidu/amis/assets/67571519/19f0663f-69ee-45ce-8d63-0cbcde2d9e00)
2、点击tag元素可以自定义弹出PopOver或TooltipWrapper，允许自定义内容SchemaNode内容，效果如下所示：
![image](https://github.com/baidu/amis/assets/67571519/9905a09b-83bb-429c-9da1-67a480959eae)
3、作为一款优秀的框架，如果再加一个Popconfirm组件，那就完美了，如下图所示：
![image](https://github.com/baidu/amis/assets/67571519/e77d850e-3dd5-44be-ac14-965e9ea8863e)
4、希望input-image图片上传完成后的按钮可以自定义，如下图所示：
![image](https://github.com/baidu/amis/assets/67571519/b0ba1c71-d62f-49fd-8be5-c9b0474883b0)

#### 预期的解决方案：
从1点几版本一直用到当前最新6.0版本，惊叹amis框架的逐渐强大成熟，给了系统前端不一样的开发体验，解决了很多问题，预期解决方案是amis能够将PopOver或TooltipWrapper组件变的更为强大，给我们开发更大的灵活与自由度，它会发挥的更好！

#### 其他可接受方案：
可接受的效果是能实现上述的功能就行

#### 任何附加信息：
无

**Comment by yyccvae** [comment]
可以自己扩展dropdown-button实现
{
  "type": "page",
  "body": {
    "type": "dropdown-button",
    "label": "下拉菜单",
    "body": [
      {
        "tpl": "确认吗？",
        "type": "tpl"
      },
      {
        "type": "flex",
        "items": [
          {
            "type": "button",
            "label": "取消"
          },
          {
            "type": "button",
            "label": "确认"
          }
        ]
      }
    ]
  }
}

**Comment by ggymzz** [comment]
@yyccvae 是的 Popconfirm样式的组件确实可以用dropdown-button模拟。 其它的PopOver样式有没有什么办法扩展呢，您知道吗？

**Comment by yyccvae** [comment]
> @yyccvae 是的 Popconfirm样式的组件确实可以用dropdown-button模拟。 其它的PopOver样式有没有什么办法扩展呢，您知道吗？

没研究出来其他的写法了

**Comment by hu54301969** [comment]
> > @yyccvae 是的 Popconfirm样式的组件确实可以用dropdown-button模拟。 其它的PopOver样式有没有什么办法扩展呢，您知道吗？
> 
> 没研究出来其他的写法了

请问知道如何给dropdownbutton的下拉菜单设置宽度么?

**Comment by yyccvae** [comment]
> > > @yyccvae 是的 Popconfirm样式的组件确实可以用dropdown-button模拟。 其它的PopOver样式有没有什么办法扩展呢，您知道吗？
> > 
> > 
> > 没研究出来其他的写法了
> 
> 请问知道如何给dropdownbutton的下拉菜单设置宽度么?

这个得自己写css，没研究过

**Comment by wibetter** [comment]
@ggymzz tooltip-wrapper 和 PopOver 的body中是可以插入任何组件的，比如插入你说的头像组件：
![image](https://github.com/baidu/amis/assets/11958920/be213b8b-73f4-42da-9ceb-14e5dc54da36)

实现以下效果：
![image](https://github.com/baidu/amis/assets/11958920/a24974d4-c8be-4318-82c1-730e136be31f)
