### ISSUE TITLE
Button按钮在primary样式设置为loading状态时，无法看清loading，其颜色也无法更改

### ISSUE THREAD

**Issue by jiangbinwangyi** [baidu/amis#9489]
#### 描述问题：

button按钮组件，在primary样式状态下，无法看清loading，loading的图标颜色也无法进行更改。

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://github.com/baidu/amis/assets/14882998/8be57174-de05-4cc7-91f2-713481817fe2)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
5.5.0。最新版存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "label": "弹个框",
    "type": "button",
    "level": "primary",
    "loading": true
  }
}
```

4. 操作步骤
添加一个button按钮组件；
给button的level设置为primary；
给button的loading设置为true；

**Comment by qkiroc** [comment]
loading优化为根据父级背景颜色自动适配深浅
