### ISSUE TITLE
富文本编辑器如何禁用工具

### ISSUE THREAD

**Issue by Liary0** [baidu/amis#9491]
#### 实现场景：
富文本编辑器如何禁用工具

#### 存在的问题：
![image](https://github.com/baidu/amis/assets/48573389/69b266d9-a9d0-4826-9fc5-0bdb912082d7)

**Comment by 2betop** [comment]
这里有例子 https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-rich-text#tinymce-%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE
