### ISSUE TITLE
现在应该是用3.6.4版本还是6.0.0版本

### ISSUE THREAD

**Issue by wuhan169** [baidu/amis#9495]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
6.0.0发布的时候说统一amis和editor的版本，现在又出了3.6.4，有点不知所措，请告知amis和editor的版本号是统一还是分开
#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
以此处的版本为准 https://github.com/baidu/amis/releases
npm 上会存在给历史大版本发布补丁版本的情况，所以 3.6.5 其实是 3.6.x 的一个补丁版本
