### ISSUE TITLE
mapping的source偶尔会取不到service中的变量值

### ISSUE THREAD

**Issue by ydiego** [baidu/amis#9504]
#### 描述问题：
通过service获取字典数据，然后再crud中通过mapping做字典映射，但是发现存在取不到值的情况

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/13268002/cb80727e-70b4-4eed-b5ab-9514cf66c1af)
![image](https://github.com/baidu/amis/assets/13268002/d0b56176-d361-4a28-802b-1d177f81b4a6)
![image](https://github.com/baidu/amis/assets/13268002/346cca85-2639-4d0a-85f9-44afec66632c)
![image](https://github.com/baidu/amis/assets/13268002/7469277f-e0bc-4fb8-92cf-304d67632f3c)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
v3.5.2
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by ydiego** [comment]
另外在page中使用initapi时，也会出现类似的变量问题
```
"data": {
    "dictKeys": [
      "erp_policy_media_type",
      "erp_policy_rebate_type",
      "erp_policy_use_category",
      "erp_policy_payback_time",
      "erp_policy_effective_time",
      "erp_policy_media_product_category",
      "erp_policy_payback_day",
      "erp_policy_settle_method"
    ]
  },
  "initApi": "/system/dict/data/batchQuery/${JOIN(dictKeys, ',')}"
```
首次访问的时候会出现请求地址信息中无变量信息的情况“/system/dict/data/batchQuery/”导致404错误，再次刷新后正常

然后改成data在page service中使用该变量请求的方式，此时请求正常，但又出现了标题所示的问题

**Comment by 2betop** [comment]
让 crud 在 service 请求完后再去请求，给 crud 的 api 配置 sendOn + trackExpression 可实现

**Comment by ydiego** [comment]
非常感谢

**Comment by 2betop** [comment]
问题场景，crud 的 api 是在 service 接口请求回来后吗？贴一下你的 `sendOn + trackExpression` 具体配置

**Comment by ydiego** [comment]
> 问题场景，crud 的 api 是在 service 接口请求回来后吗？贴一下你的 `sendOn + trackExpression` 具体配置

![78b90aacdd32ec86704b4cf34341eb6](https://github.com/baidu/amis/assets/13268002/b432fe95-5b5a-43f6-8407-620781b46110)
![b4b9b50bdf9c9e0834921c55846f5c2](https://github.com/baidu/amis/assets/13268002/e629a093-0639-4ab6-aedc-c818cc8c654d)

**Comment by ydiego** [comment]
sdk升到最新6.0了 用`sendOn + trackExpression`这个方式结果还是一样

**Comment by ydiego** [comment]
> sendOn 表达式不对应该是 sendOn: "${erp_policy_effective_time}" ，另外还需要配置 trackExpression: "${erp_policy_effective_time}" 当 `erp_policy_effective_time` 值变化时重新请求 crud 接口
 
有几点疑惑想教教下您：
1、这块的表达跟我上面的做法应该是一致的，service请求完成后在service数据域中新增了一个变量，接着crud基于这个变量发送请求，上诉配置也做到了curd的请求，在service中新增tpl模板也能打印对应的变量值，但是crud中的mapping无法读取变量导致失效不能正常展示。
2、按照您的回复我调整了下写法，在service完成之后刷新crud，crud不加sendOn，验证的时候发现curd调用多次，此时mapping那个问题依旧存在
![image](https://github.com/baidu/amis/assets/13268002/65205397-912a-47c5-aefc-1ae85630f865)
![image](https://github.com/baidu/amis/assets/13268002/4edaec86-8792-4f3e-b118-9d89dc20f607)
![image](https://github.com/baidu/amis/assets/13268002/581241b3-26d0-4825-927c-25e87b6dd2f6)
然后在curd中加入trackExpression，此时curd不再触发请求，sendOn里面带不带$的方式都一样，在官方文档编辑中验证过不带的话也是可以的
![image](https://github.com/baidu/amis/assets/13268002/57e036fc-ac83-4062-80b1-9f1fe2af3329)
