### ISSUE TITLE
多选的select在静态展示，或者table中怎么使用mapping？

### ISSUE THREAD

**Issue by argan** [baidu/amis#951]
#### 实现场景：
某字段是多选，在新增和编辑的时候，select加上multiple:true 就可以工作

#### 存在的问题：
在crud的列表中，或者静态查看的时候，无法展示select 的option中的描述

**Comment by RickCole21** [comment]
目前mapping不支持多选这种形式。

提供一种解决方案供参考：
1. select 配置 `joinValues: false`，保存完整对象数组
2. 展示的时候用 tpl ，通过js代码进行map展示

**Comment by argan** [comment]
最好是直接支持这种形式，自己用tpl去处理显示问题的化，inline edit的时候也会碰到问题
