### ISSUE TITLE
editor使用

### ISSUE THREAD

**Issue by snowing-x** [baidu/amis#9528]
想问一下对于Editor来说，直接更新传入的value（不是通过操作编辑器）也会触发onChange吗？
我看现在好像是会的，而且会处理regions里的字段：
<img width="179" alt="image" src="https://github.com/baidu/amis/assets/51695385/0467c4dd-5523-47f1-ad20-cc5bc0b35f24">

**Comment by 2betop** [comment]
有具体复现步骤吗？新版本里面貌似修复过此类问题

**Comment by snowing-x** [comment]
升级到6.0.0版本后，没问题了
