### ISSUE TITLE
选择类组件，使用非静态数据源，无法操作事件流【编辑器】

### ISSUE THREAD

**Issue by jianchaoming** [baidu/amis#9531]
#### 描述问题：

选择类组件，比如：select、radio、checkbox，使用source数据源不使用静态的options，无法点击事件的添加、或者点击之前加好的事件打开编辑，有报错

#### 截图或视频：

<img width="1460" alt="image" src="https://github.com/baidu/amis/assets/39518514/3f8c99ff-f367-4fb3-82ab-7816003cb821">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
正常使用，必现

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.0.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
常规操作，必现，手动添加一个options可以点击打开事件进行编辑了，但是下次打开会被自动删掉，所以，每次要修改事件，要么写源码，要么每次手动添加一个空options

**Comment by qkiroc** [comment]
最新master分支无法复现
