### ISSUE TITLE
InputSubForm如何提交或排除该数据域下指定的数据

### ISSUE THREAD

**Issue by ydiego** [baidu/amis#9539]
#### 实现场景：
在一个表单中存在一个子表单项，子表单项通过initApi初始化得到了一个数据rows，子表单中的某些表单项以来这个数据rows做展示

#### 存在的问题：
当提交子表单的时候除了各个表单项外同时也会将rows这个数据带过去。

#### 当前方案：
尝试使用target方式，但是似乎没用，如果是hiddenon结婚clearonhhide的话能实现，但是其他依赖这个数据的字段也没了，请教还有什么实现方案嘛
这是在官网文档上测试的伪代码
![企业微信截图_17062630518187](https://github.com/baidu/amis/assets/13268002/44830d19-7131-42ff-bd09-c1cb251895cd)

```
code here...
```

**Comment by wuyihong** [comment]
在requestAdaptor里面将不需要的排除掉。

**Comment by ydiego** [comment]
> 在requestAdaptor里面将不需要的排除掉。

感谢回复。这确实是一种方案，不过上面提到的数据都是子表单提交上来的，这样一来到真正提交的form表单中时所提交的表单数据是一个多层级的数据，有没有可能在子表单那层的时候就处理掉呢？

**Comment by ydiego** [comment]
找到解决方案了。
