### ISSUE TITLE
带有options属性的组件，使用上下文变量赋值时在编辑器中无法编辑事件

### ISSUE THREAD

**Issue by ggymzz** [baidu/amis#9549]
#### 描述问题：

list-select、input-tag组件在编辑器中如果使用上下文变量赋值，会导致在编辑器中无法编辑事件，错误截图如下：
![image](https://github.com/baidu/amis/assets/67571519/f58a8be3-460f-472e-8f81-456f988044e3)
复现代码附在后面第4点，可使用[amis-editor-demo](https://aisuda.github.io/amis-editor-demo)复现测试。

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm react18

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
  "amis": "^3.6.4",
  "amis-core": "^3.6.4",
  "amis-editor": "^6.0.0",
  "amis-editor-core": "^6.0.0",
  "amis-formula": "^3.6.4",
  "amis-ui": "^3.6.4",

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "title": "测试",
  "body": [
    {
      "type": "input-tag",
      "label": "标签",
      "name": "tag",
      "id": "u:06e67d1697b2",
      "optionsTip": "最近您使用的标签",
      "onEvent": {
        "change": {
          "weight": 0,
          "actions": [
            {
              "ignoreError": false,
              "script": "const myMsg = '我是自定义JS';\ndoAction({\n  actionType: 'toast',\n  args: {\n    msg: myMsg\n  }\n});\n",
              "actionType": "custom"
            }
          ]
        }
      },
      "source": "${dataList}"
    },
    {
      "type": "list-select",
      "label": "列表",
      "name": "list",
      "id": "u:af407e27561c",
      "multiple": false,
      "source": "${dataList}",
      "onEvent": {
        "change": {
          "weight": 0,
          "actions": []
        }
      }
    }
  ],
  "id": "u:3e5e059b0ae2",
  "pullRefresh": {
    "disabled": true
  },
  "regions": [
    "body"
  ],
  "data": {
    "dataList": [
      "a",
      "b"
    ]
  },
  "asideResizor": false
}
```

5. 操作步骤
将上面代码复制到[amis-editor-demo](https://aisuda.github.io/amis-editor-demo)即可复现

**Comment by 2betop** [comment]
因为跟 #9531 重复了，所这个关了
