### ISSUE TITLE
lerna+nuxt+amis在SSR模式下无法渲染，CSR模式下报错(/((?:https?|file):.*?)\n/.test(...) && RegExp.$1).replace is not a function

### ISSUE THREAD

**Issue by lucyluxiliu** [baidu/amis#9551]
#### 描述问题：

lerna+nuxt+amis
SSR模式下无法渲染，报错render function or template not defined in component: anonymous
CSR模式下报错(/((?:https?|file):.*?)\n/.test(...) && RegExp.$1).replace is not a function

#### 截图或视频：
![企业微信截图_1706527831148](https://github.com/baidu/amis/assets/48850688/0477ae9c-959a-49ca-a58f-1d71cf8d25fb)
![企业微信截图_17065280915792](https://github.com/baidu/amis/assets/48850688/0fcb5165-9759-4001-9264-8b12c74593a2)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk方式

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis 6.0.0，webpack 4.44.2，node 16.20.2，lerna 3.22.1，nuxt 2.14.12

3. 粘贴有问题的完整 `amis schema` 代码：
```
# SSR模式下 nuxt.config.js
{ ssr: true }
已经用copy-webpack-plugin单独对amis进行了处理，还是有报错 (/((?:https?|file):.*?)\n/.test(...) && RegExp.$1).replace is not a function
设置webpack devtool = sourcemap有相同报错，nuxt.config.js build.extend 里 
if (isDev && isClient) {
      config.devtool = 'source-map';
}

# CSR模式下 nuxt.config.js
{ ssr: false }
```

4. 操作步骤
可复现最小项目 https://github.com/lucyluxiliu/lerna-nuxt-amis , 先执行 npm run bootstrap，再执行 npm run dev:project，访问路径 http://ip:3000/pages/search

**Comment by 2betop** [comment]
不要对 amis 的 sdk 做二次变异，跳过变异，直接用

**Comment by lucyluxiliu** [comment]
您的邮件我已经收到啦，我会尽快回复哒~lucy~

**Comment by lucyluxiliu** [comment]
> 不要对 amis 的 sdk 做二次编译，跳过编译，直接用。 如果要编译，还是用 amis 的 npm 包版本吧。

amis npm包版本 -- 当前项目是使用npm install amis安装的，然后项目内引用，参考你之前写的 https://github.com/aisuda/vue2-amis-demo/blob/main/src/components/AMISRenderer.vue，我还缺了什么配置吗

**Comment by 2betop** [comment]
lerna 不会用，我估摸着差一个忽略某个目录编译的插件配置。比如 webpack 里面有这个  https://github.com/aisuda/vue2-amis-demo/blob/vue-cli/vue.config.js#L19-L21

npm 版本的可以参考 https://github.com/aisuda/amis-admin/blob/react/components/AMisRenderer.tsx

**Comment by lucyluxiliu** [comment]
> lerna 不会用，我估摸着差一个忽略某个目录编译的插件配置。比如 webpack 里面有这个 https://github.com/aisuda/vue2-amis-demo/blob/vue-cli/vue.config.js#L19-L21
> 
> npm 版本的可以参考 https://github.com/aisuda/amis-admin/blob/react/components/AMisRenderer.tsx

copy-webpack-plugin 已经加到nuxt.config.js配置里了 https://github.com/lucyluxiliu/lerna-nuxt-amis/blob/070ff802fa40fb0eabdb2e150d23b8dcc288e4db/packages/project/nuxt.config.js#L104-L111

但并未生效

npm版本也试过了，用了最简单的schema https://github.com/lucyluxiliu/lerna-nuxt-amis/blob/main/packages/project/components/AMISRenderer2.vue 页面见 https://github.com/lucyluxiliu/lerna-nuxt-amis/blob/main/packages/project/pages/Form.vue

依旧有 render function or template not defined in component: anonymous 的错误
