### ISSUE TITLE
VUE3 通过sdk引入amis， 提示”选择器不对，页面上没有此元素“ 问题bug

### ISSUE THREAD

**Issue by wqx8821** [baidu/amis#9553]
#### 描述问题：
vue3+vite通过sdk使用amis， 浏览器控制台报错

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/79678729/4a79a7b6-3eb8-4c1c-96ec-3b95de29752d)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk` ， vite 初始化Vue3 ts 模板

测试使用代码
`<template>
  <div id="amis"></div>
</template>`
<script setup lang="ts">
import { Schema } from "amis/lib/types";
import 'amis/sdk/sdk.js'
import 'amis/sdk/color-picker.js'
import 'amis/sdk/rest.js'
// @ts-ignore
const amis = amisRequire('amis/embed');

function onRendering(schema: Schema) {
  amis.embed('#amis', schema);
}
onRendering({
  "type": "page",
  "body": "Hello World!"
})
</script>
![image](https://github.com/baidu/amis/assets/79678729/356bcb79-ffa5-4624-bedc-421fcf63760c)

安装依赖和版本
![image](https://github.com/baidu/amis/assets/79678729/72b44aa2-fc02-4a5e-8607-205131633d3c)

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.6.4， 使用3版本也一样, 不清楚是什么问题
3. 粘贴有问题的完整 `amis schema` 代码：

4. 操作步骤
看上述

**Comment by 2betop** [comment]
一定是实际不对，你调用 amis 的时候，vue 还没把 `#amis` 这个元素渲染出来

**Comment by 2betop** [comment]
请先确认时机问题，先关了，有问题再开
