### ISSUE TITLE
TreeSelect 选择后勿重置搜索条件

### ISSUE THREAD

**Issue by Ladtor** [baidu/amis#9567]
#### 是否关联于某个问题吗：
TreeSelect 每次选择后，都会重置搜索条件，在多选的场景下，需重复键入关键词，交互体验较差

#### 预期的解决方案：
使用类似Select的搜索交互方式

#### 任何附加信息：

![20240201152602_rec_](https://github.com/baidu/amis/assets/19227210/0cb5a5a1-655a-4c30-9ead-692a03a838e2)

**Comment by qkiroc** [comment]
不能复现，某一次版本已经修复了

**Comment by Ladtor** [comment]
> 不能复现，某一次版本已经修复了

@qkiroc 
```json
{
  "label": "Tree",
  "name": "tree",
  "options": [
    {
      "label": "A",
      "value": 1
    },
    {
      "label": "B1",
      "value": 4
    },
    {
      "label": "B2",
      "value": 5
    }
  ],
  "searchable": true,
  "multiple": true,
  "type": "tree-select"
}
```
实测最新6.2.2版本仍然存在该问题
