### ISSUE TITLE
button在使用themeCss设置字体大小后hover设置背景色功能失效

### ISSUE THREAD

**Issue by onlyistranger** [baidu/amis#9585]
#### 描述问题：

button在使用themeCss设置字体大小后hover设置背景色功能失效，屏蔽相关语句后hover功能恢复正常
见代码

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.10
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "button",
  "label": "按钮",
  "onEvent": {
    "click": {
      "actions": []
    }
  },
  "id": "u:8bf2ec9bc515",
  "block": false,
  "className": "h-1/3 w-1/3",
  "themeCss": {
    "className": {
      "background:hover": "var(--colors-brand-5)",
      "font:default": {
        "fontSize": "var(--fonts-size-4)"//屏蔽此条语句后hover正常
      },
      "font:hover": {
        "color": "var(--colors-neutral-fill-11)"
      }
    },
    "iconClassName": {
      "iconSize:default": "var(--sizes-size-1)"
    }
  },
  "icon": "fa fa-slideshare"
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by qkiroc** [comment]
<img width="964" alt="image" src="https://github.com/baidu/amis/assets/30946345/02a44a2c-b967-4cce-a2f4-46bf8862dfa6">
hover:
