### ISSUE TITLE
crud操作表单数据提交数据类型错误

### ISSUE THREAD

**Issue by xiusin** [baidu/amis#959]
#### 描述问题：
crud操作表单数据提交数据类型错误

#### 截图或视频：

返回数据
![image](https://user-images.githubusercontent.com/36065131/91437314-477ae500-e89c-11ea-9b8b-d689a43ecb99.png)

提交数据
![image](https://user-images.githubusercontent.com/36065131/91437207-1ac6cd80-e89c-11ea-9227-db19f7773a16.png)

**Comment by xiusin** [comment]
项目又G了？

**Comment by nwind** [comment]
用 number 而不是 text
