### ISSUE TITLE
TooltipWrapper 文字提示容器 的content字段建议改成SchemaNode

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#9594]
#### 是否关联于某个问题吗：
TooltipWrapper 文字提示容器 的content字段建议改成SchemaNode，这样就能实现鼠标移入头像，弹出菜单功能

#### 预期的解决方案：
实现鼠标移入头像，弹出菜单功能

#### 其他可接受方案：
无

#### 任何附加信息：
![image](https://github.com/baidu/amis/assets/11575908/c1b9bcf6-f21e-48b1-989e-80f2b04fc239)

**Comment by wibetter** [comment]
@xiahao90  tooltip-wrapper 的body中是可以插入任何组件的，比如插入你说的头像组件：
<img width="867" alt="image" src="https://github.com/baidu/amis/assets/11958920/8977751f-7344-4a29-8f54-e0fc3b710aea">
实现以下效果：
<img width="168" alt="image" src="https://github.com/baidu/amis/assets/11958920/69b4abc2-fc0f-4cd9-bd65-15ab3fc7efcb">

**Comment by luoliyi** [comment]
你回答的答案是人家想问的吗？

**Comment by wibetter** [comment]
@xiahao90 不好意思，看错意思了，看issue标题还以为是想在tooltipWrapper中插入其他组件元素（SchemaNode）。
原来是说想在提示窗体中插入组件元素。
实现hover展示菜单效果，这个目前确实是不支持的，因为content仅支持string写法（最后使用Html渲染）。
你可以尝试着自己提一个PR，先在packages/amis/src/renderers/TooltipWrapper.tsx中识别content类型，如果识别到content为一个对象或数组类型就使用props.render渲染并返回给content。最后在packages/amis-ui/src/components/TooltipWrapper.tsx 中再简单调整下。
