### ISSUE TITLE
ls 取值问题

### ISSUE THREAD

**Issue by csx-bill** [baidu/amis#9599]
#### 描述问题：

ls 取值问题

#### 截图或视频：
![82A1323F1257B5A939129F829D0FFE83](https://github.com/baidu/amis/assets/31872268/41a1e8ae-5a53-4ea0-ace1-06ed634affb7)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
 6.1.0

如果用自定义js  localStorage.getItem('X-Access-Token'); 可以取到

问题在于 - 的问题 导致无法取值

**Comment by 2betop** [comment]
`-` 有可能是个运算符，冲突了，可以用以下方式 `${ls:&['X-Access-Token']}` 或者 `${ls:X\-Access\-Token}`

**Comment by 2betop** [comment]
<img width="1291" alt="image" src="https://github.com/baidu/amis/assets/2698393/20cb59b8-5f7c-4828-be68-d77f554292ab">

**Comment by csx-bill** [comment]
已解决
