### ISSUE TITLE
子表单能否控制外部显示一行一条，不要把多条放到同一行

### ISSUE THREAD

**Issue by zwjsoft** [baidu/amis#9609]
#### 实现场景：
子表单可以控制每一条记录分行显示

#### 存在的问题：
![1708239092035](https://github.com/baidu/amis/assets/35764692/0cfeec19-9183-401a-9895-0a3c06900acb)

**Comment by CheshireJCat** [comment]
配置这个属性 "itemClassName": "block" 就可以了
