### ISSUE TITLE
6.1.0 status 组件无法显示图标了，6.0.0是正常的，必现。

### ISSUE THREAD

**Issue by gillbates** [baidu/amis#9613]
#### 描述问题：

6.0.0 是正常显示图标的，6.1.0无法显示了。。。

#### 截图或视频：

6.1.0 出问题了，status里面的图标无法显示：

![CleanShot 2024-02-19 at 08 19 02@2x](https://github.com/baidu/amis/assets/783547/01be4307-a9de-4d74-adc3-cc2912f5d78e)

6.0.0 正常的。

![CleanShot 2024-02-19 at 08 20 04@2x](https://github.com/baidu/amis/assets/783547/4834b44b-c155-45e7-a764-de4e5618390f)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.1.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
let amis = amisRequire('amis/embed');
            var crudData = [];
            for (var i = 0; i < 2; i++) {
                crudData.push({ 'id': i, "status": i % 2 });
            }

            let amisJSON = {
                type: 'page',
                title: '表单页面',
                data: {
                    "crudData": crudData
                },
                body: [
                    {
                        "type": "crud",
                        "source": "$crudData",
                        "syncLocation": false,
                        "columns": [
                            {
                                "name": "id",
                                "label": "ID"
                            },
                            {
                                "name": "status",
                                "label": "状态"
                            },
                            {
                                "name": "status",
                                "label": "状态2",
                                "type": "mapping",
                                "map": {
                                    "*": {
                                        "type": "status",
                                        "map": {
                                            "0": "schedule",
                                            "1": "rolling",
                                            "2": "success",
                                            "3": "fail",
                                            "4": "warning"
                                        },
                                        "labelMap": {
                                            "2": "任务成功",
                                            "1": "处理中",
                                            "3": "异常终止",
                                            "0": "等待中",
                                            "4": "已过期"
                                        }
                                    }
                                }
                            },
                        ]
                    }
                ]
            };
            let amisScoped = amis.embed('#root', amisJSON);
```

4. 操作步骤
上述json，配合

```
    <link href="https://cdn.jsdelivr.net/npm/amis@6.0.0/sdk/sdk.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/amis@6.0.0/sdk/helper.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/amis@6.0.0/sdk/iconfont.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/amis@6.0.0/sdk/sdk.min.js"></script>
```

```
    <link href="https://cdn.jsdelivr.net/npm/amis@6.1.0/sdk/sdk.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/amis@6.1.0/sdk/helper.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/amis@6.1.0/sdk/iconfont.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/amis@6.1.0/sdk/sdk.min.js"></script>
```

可以必现。

**Comment by 2betop** [comment]
是个 bug，不过可以直接使用 status 绕过这个问题

```
{
      name: 'status',
      label: '状态2',
      type: 'status',
      map: {
        0: 'schedule',
        1: 'rolling',
        2: 'success',
        3: 'fail',
        4: 'warning'
      },
      labelMap: {
        2: '任务成功',
        1: '处理中',
        3: '异常终止',
        0: '等待中',
        4: '已过期'
      }
    }
```

mapping 里面组合 status 确实有问题

**Comment by gillbates** [comment]
> 是个 bug，不过可以直接使用 status 绕过这个问题
> 
> ```
> {
>       name: 'status',
>       label: '状态2',
>       type: 'status',
>       map: {
>         0: 'schedule',
>         1: 'rolling',
>         2: 'success',
>         3: 'fail',
>         4: 'warning'
>       },
>       labelMap: {
>         2: '任务成功',
>         1: '处理中',
>         3: '异常终止',
>         0: '等待中',
>         4: '已过期'
>       }
>     }
> ```
> 
> mapping 里面组合 status 确实有问题

嗯，主要是我们实际场景，值很多，需要mapping来映射，这个月有空fix下呗，开年快乐！ @2betop 而且，貌似是6.1才改出来的。

**Comment by gillbates** [comment]
> 提 pr #9616 了，月底会发新版本。
> 
> 另外，里面补一个 name 应该也能解决
> 
> ```
> {
>                                 "name": "status",
>                                 "label": "状态2",
>                                 "type": "mapping",
>                                 "map": {
>                                     "*": {
>                                         "name": "status",
>                                         "type": "status",
>                                         "map": {
>                                             "0": "schedule",
>                                             "1": "rolling",
>                                             "2": "success",
>                                             "3": "fail",
>                                             "4": "warning"
>                                         },
>                                         "labelMap": {
>                                             "2": "任务成功",
>                                             "1": "处理中",
>                                             "3": "异常终止",
>                                             "0": "等待中",
>                                             "4": "已过期"
>                                         }
>                                     }
>                                 }
>                             },
> ```

嗯，确实是，等你们月底发版，谢谢了。
