### ISSUE TITLE
jquery 是否是必需品, 能否剔除自己全局引入

### ISSUE THREAD

**Issue by nuan1989** [baidu/amis#962]
#### 实现场景：
我用layui+Amis Jssdk
layui已经加载一遍jquery了, 我能否自己编译jssdk版本 , 把jquery剔除, 然后我全局引入呢?

#### 存在的问题：
amis-master\examples\loader.ts, 是不是在这里面屏蔽, 重新编译就行? 

#### 当前方案：
无

**Comment by nwind** [comment]
并不需要这么做，js sdk 中不包含 jquery，只有用到 froala 编辑器的时候才会异步加载
