### ISSUE TITLE
txt, csv类型的文件无法通过链接下载

### ISSUE THREAD

**Issue by junjieQQ2** [baidu/amis#9622]
#### 描述问题：

后端返回文件的下载链接，xlsx类型可以通过url组件下载，txt和csv只能在新标签页打开，无法直接下载。

#### 截图或视频：

后端返回文件的下载链接，xlsx类型可以通过url组件下载，txt和csv只能在新标签页打开，无法直接下载。

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.0.2版本，存在。

3. 粘贴有问题的完整 `amis schema` 代码：
```
            {
              "type": "button",
              "label": "下载",
              "level": "link",
              "actionType": "url",
              "url": "${downloadUrl}"
            },
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by junjieQQ2** [comment]
通过url下载的xlsx文件不能之定义名称

**Comment by 2betop** [comment]
没看懂，自定义文件名只能是 actionType 为 download 才可以(3.5.0 版本之后才支持)。如果是用 actionType 为 url 相当于是浏览器里面打开地址下载，跟前端代码就无关了

**Comment by 2betop** [comment]
要下载得有 `Content-Disposition` header，http协议相关的东西与amis无关
