### ISSUE TITLE
关于disabledOn和visibleOn表达式的疑问

### ISSUE THREAD

**Issue by vexos-io** [baidu/amis#9629]
在不同的情况下有时候要加${}，有时候不能加${}
比如：
disabledOn: '${parent.age > 18}'
disabledOn: 'selectedItems.some(x => x.age > 18)'
而且有的情况加不加${}都可以

没看过源代码，请解答一下，谢谢

**Comment by 2betop** [comment]
<img width="1137" alt="image" src="https://github.com/baidu/amis/assets/2698393/e8a803e0-2c5c-4e34-b4bb-16f886b4d4ab">

https://aisuda.bce.baidu.com/amis/zh-CN/docs/concepts/expression
