### ISSUE TITLE
行为按钮复制粘贴换行问题

### ISSUE THREAD

**Issue by echome123** [baidu/amis#9634]
```
{
  "type": "button",
  "reload": "none",
  "label": "复制文本",
  "level": "info",
  "icon": "fa-solid fa-copy",
  "actionType": "copy",
  "content": "${title }\r\n 内容：${content}\r\n 其他信息：${extra_info}"
}
```

复制内容到剪贴板之后，部分设备换行无效，部分有效，换行符也尝试过 `\n` 和 `\n\n` 均不起作用，对照文档添加过`wrapperComponent` 的，好像也无效。

具体的复现过程有些奇怪： 复制结果粘贴在微信聊天框和WPS文件内无法正常换行，但是放在记事本或者其他软件上就正常换行。不知道有没有人遇到过。

**Comment by CheshireJCat** [comment]
这种情况可能是由于不同软件对于换行符的解释方式不同所导致的。
微信聊天框和WPS文件可能对于从剪贴板中复制的文本的换行符处理方式与记事本或其他软件不同。

微信聊天框和WPS文件可能会在显示文本时自动将换行符忽略或替换为特定的空格或其他字符，这可能导致文本在这些软件中无法正常换行。
记事本或其他软件可能更接近原始文本的显示方式，因此可以正常显示换行符。

**Comment by echome123** [comment]
> 请问解决了吗, 都没法正常粘贴内容到微信了

@Heming9 无解，后来单独把复制功能用原生JS写了一下解决的
