### ISSUE TITLE
接口返回结果如何回显，刚开始研究amis求助

### ISSUE THREAD

**Issue by wangnew143143** [baidu/amis#9635]
#### 实现场景：
我用表单向接口提交一些信息，并且获得返回值

#### 存在的问题：
但是现在接口调用成功了可是返回数据怎么拿到并且展示出来

#### 当前方案：
{接口能够调用，console.log也能打印出来，但是不知道怎么回显}

```
{
					"type": "page",
					"title": "api",
					"body": [{
						"type": "flex",
						"className": "p-1",
						"items": [{
								"type": "container",
								"body": [{
										"type": "select",
										"label": "性别",
										"name": "sex",
										"id": "u:1cd0ad5fbffa",
										"options": [{
												"label": "男",
												"value": "男"
											},
											{
												"label": "女",
												"value": "女"
											}
										],
										"multiple": false,
										"size": "full",
										"value": "男"
									},
									{
										"type": "switch",
										"name": "checked",
										"label": "是否选中",
										"id": "u:0df2fe9903a8",
										"value": true,
										"visible": false
									},
									{
										"type": "switch",
										"name": "flag",
										"label": "是否标记",
										"id": "u:f87852867ee1",
										"value": false,
										"visible": false
									},
									{
										"type": "switch",
										"name": "cangGanflag",
										"label": "藏干标志",
										"id": "u:8906d6e0c746",
										"value": true,
										"visible": false
									},
									{
										"type": "input-date",
										"label": "生日",
										"name": "birthday",
										"id": "u:9c42ba9ab704",
										"placeholder": "请选择日期",
										"valueFormat": "YYYY-MM-DD",
										"displayFormat": "YYYY-MM-DD",
										"minDate": "",
										"maxDate": "",
										"value": "",
										"required": true
									},
									{
										"type": "input-text",
										"label": "姓名",
										"name": "name",
										"id": "u:c1622487001c",
										"required": true
									},
									{
										"type": "input-time",
										"label": "时间",
										"name": "birthTime",
										"id": "u:0ec1263d40fb",
										"placeholder": "请选择时间",
										"valueFormat": "HH:mm:ss",
										"displayFormat": "HH:mm:ss",
										"minDate": "",
										"maxDate": "",
										"value": ""
									},
									{
										"type": "input-city",
										"label": "出生地点",
										"name": "address",
										"allowCity": true,
										"allowDistrict": true,
										"extractValue": false,
										"id": "u:38991824196a",
										"value": "110000",
										"searchable": true
									},
									{
										"type": "input-text",
										"label": "文本",
										"name": "gongnong",
										"id": "u:c65c51fb4fba",
										"value": "0",
										"visible": false
									},
									{
										"type": "button",
										"data": {
											"token": ""
										},
										"label": "提交",
										"onEvent": {
											"click": {
												"actions": [{
													"ignoreError": false,
													"outputVar": "res",
													"actionType": "ajax",
													"options": {},
													"api": {
														"url": "https://www.zhiyunbazi.com/aiwudao-api/api/baziNew/queryInfo",
														"method": "post",
														"data": {
															"sex": "${sex}",
															"checked": "${checked}",
															"birthday": "${birthday}",
															"birthTime": "${birthTime}",
															"name": "${name}",
															"flag": "${flag}",
															"gongnong": "${gongnong}",
															"address": "北京市区",
															"cangGanflag": "${cangGanflag}"
														},
														"responseData": {
															"&": "$$"
														},
														"requestAdaptor": "",
														"adaptor": "console.log(payload.data);return {\n    ...payload,\n    data: {\n        ...payload.data,\n        response: response.data\n    }\n}",
														"messages": {
															"success": "正在测试您的健康状况",
															"failed": "对不起请求超时请稍后再试"
														},
														"headers": {
															"Authorization": "${token}"
														}
													}
												}]
											}
										},
										"id": "u:52a28944d9e2",

									}
								],
								"size": "xs",
								"style": {
									"position": "static",
									"display": "block",
									"flex": "1 1 auto",
									"flexGrow": 1
								},
								"wrapperBody": false,
								"isFixedHeight": false,
								"isFixedWidth": false,
								"id": "u:1c24dece9da6"
							},
							{
								"type": "container",
								"body": [{
										"type": "static",
										"label": "反对法${response|json}",
										"name": "${response|json}",
										"id": "u:cb12a5865b87"
									},

									{
										"type": "input-text",
										"label": "文本",
										"name": "text",
										"id": "u:bc933b84f5b5",
										"value": "${response|json}"
									}
								],
								"size": "xs",
								"style": {
									"position": "static",
									"display": "block",
									"flex": "1 1 auto",
									"flexGrow": 1,
									"flexBasis": "auto"
								},
								"wrapperBody": false,
								"isFixedHeight": false,
								"isFixedWidth": false,
								"id": "u:77a8801f4770"
							},
							{
								"type": "container",
								"body": [],
								"size": "xs",
								"style": {
									"position": "static",
									"display": "block",
									"flex": "1 1 auto",
									"flexGrow": 1,
									"flexBasis": "auto"
								},
								"wrapperBody": false,
								"isFixedHeight": false,
								"isFixedWidth": false,
								"id": "u:33cb138074ce"
							}
						],
						"style": {
							"position": "relative",
							"inset": "auto",
							"flexWrap": "nowrap",
							"flexDirection": "column"
						},
						"id": "u:d334de8a4fbe",
						"isFixedHeight": false,
						"isFixedWidth": false
					}],
					"id": "u:fd9151583470",
					"asideResizor": false,
					"pullRefresh": {
						"disabled": true
					},
					"regions": [
						"body"
					]
				}
```

**Comment by ydiego** [comment]
为啥不用crud

**Comment by wangnew143143** [comment]
我试试，刚开始研究

**Comment by wangnew143143** [comment]
不行，接口返回的信息crud不支持，是这么一堆{
    "msg": "操作成功",
    "code": 200,
    "data": [
        {
            "TaiXi": "乙卯（大溪水）",
            "year": "辛巳",
            "XingWest": "狮子座",
            "TaiYuan": "丁亥（屋上土）",
            "qmdjyinyang": "阴",
            "GregorianDateTime": "2001-8-15 08:43:01",
            "sum": "2001-8-15 08:25:01",
            "SanYuan": "艮卦（西四命）",
            "qmdjlunardate": "2001-6-26",
            "ShenGong": "辛丑（壁上土）",
            "LunarDateTime": "辛巳年六月廿六日 辰时",
            "XingEast": "参宿西方白虎",
            "LYear": "蛇",
            "lichunBefore": false,
            "month": "丙申",
            "KongWang": "申酉(年) 寅卯(日)",
            "jieqi": [
                {
                    "four": "白露:2001-09-07 21:46:11",
                    "one": "出生于立秋后7天13小时33分0秒",
                    "two": "立秋:2001-08-07 18:52:21",
                    "three": "出生于白露前23天13小时21分0秒"
                }
            ],
            "time": "庚辰",
            "day": "庚戌",
            "MingGong": "癸巳（长流水）"
        },
        {
            "shouyuan": "73岁\r\n",
            "sex": "男",
            "mingge": "交友多情有损，小心防之再发之命\r\n",
            "weight": 49,
            "content": "此命推来福不轻，自成自立显门庭；\r从来富贵人钦敬，使婢差奴过一生。",
            "cnWeight": "四两九钱",
            "content2": "从来富贵人钦敬，使婢差奴过一生。",
            "content1": "此命推来福不轻，自成自立显门庭；",
            "itro": "此命为人品性纯和，做事勤俭，恩中招怨，兄弟有克，亲朋相怨，赔酒赔饭，反说不美，初限贫愁，交过二十六七岁如逆水行舟，不能聚财，中限驳杂多端，刑妻克子，交过四十岁，方可成家立业，般般如意，件件称心，至四十六七有一灾，宁可损财交过，后有十年好运来，家中钱财聚备，三子送老，寿元七十三。",
            "geju": "中上\r\n",
            "chenghun": "晚婚\r\n",
            "zhishu": "80%\r\n",
            "caiyun": "不聚财，独自求财\r\n"
        },
        {
            "mingzhushuxing": "庚",
            "jishen": "土 金",
            "yongshen": "水 木 火",
            "shen": "身身强(84.0)"
        },
        {
            "tu": {
                "tu": 24.0,
                "value2": 0,
                "value1": 2,
                "name2": "正印",
                "name1": "偏印"
            },
            "huo": {
                "huo": 16.0,
                "value2": 1,
                "value1": 1,
                "name2": "正官",
                "name1": "七杀"
            },
            "tianyunxuwing": "金",
            "mu": {
                "value2": 0,
                "value1": 0,
                "mu": 0,
                "name2": "正财",
                "name1": "偏财"
            },
            "shui": {
                "value2": 0,
                "value1": 0,
                "name2": "伤官",
                "shui": 0,
                "name1": "食神"
            },
            "jin": {
                "value2": 1,
                "value1": 3,
                "name2": "劫财",
                "name1": "比肩",
                "jin": 60.0
            }
        },
        {
            "yangCang": 69,
            "yang": 75.0,
            "yinCang": 31,
            "YB": "七杀",
            "geju": "七杀",
            "xiong": 56,
            "wordlife": null,
            "yin": 25.0,
            "ji": 19
        },
        {
            "word1": "优势:坚强豪爽，讲义气，刚毅果决，公正侠义。提醒:好胜心强，顽固，粗心，易情绪化",
            "word2": "日元-庚:阳金，刀剑兵器之金"
        },
        {
            "profession": "进出口贸易、国际企业经营、汽车维修、管理顾问业、百货业、超市超商、运输业、渔业、水族馆、航空业、广告业、广告设计、商品设计、网路美编、建筑设计、补教事业(如一对一英语辅导)、房屋代销、观光业、房屋中介、大众传播业、演艺圈、IC设计业、政治、加油站、娱乐业、饭店业、医生、土地开发设计、植物养殖业、花店、农业、出版业、化妆品、火锅店、等。属水行业，漂游性质、奔波性质、流动性质、连续运动性质、易变化性质、水属性质、音响性质、清洁性质，冷温具不燃性之化学界。入海求生活者。以水发财之事业属水「例如雨衣、雨帆、洗衣粉等]。航海界「船员]、冷温不燃液体、冰水界、鱼类界、水产界、水利界、水物界、冷藏界、打水界、扫除界、流水界、港内界、泳池界、湖、池塘、浴池、菜市场内售卖冷食物[鱼、肉豆腐]均属之。迁旅业、特技表演业、运动家、导游业、旅行业、玩具业、声乐音响业、魔术、马戏团、采访记者、侦探、旅社、或灭火器具、钓鱼器具等。"
        }
    ]
}
crud怎么展示出来，一直报item必须是数组

**Comment by ydiego** [comment]
接口返回的data是个对象
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E6%AD%A3%E7%A1%AE%E7%9A%84%E6%A0%BC%E5%BC%8F

**Comment by wangnew143143** [comment]
所以amis 的crud没法使用是吧

**Comment by ydiego** [comment]
是你接口返回不符合amis规范，建议先看看文档

**Comment by wangnew143143** [comment]
接口没法规范，我改不了后端，难受

**Comment by 2betop** [comment]
可以用接收适配器转一下 https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8
