### ISSUE TITLE
关于页面编辑器组件扩展「多重身份」配置的使用

### ISSUE THREAD

**Issue by joelost** [baidu/amis#9638]
#### 实现场景：
请问大佬，amis-editor中组件扩展时多重身份配置的正确使用方法是怎样的？有无简单的示例提供参考呢？

「multifactor?: boolean 是否有多重身份？比如 CRUD 即是 CRUD 又可能是 Table，表格的列，即是表格列，也可能是其他文本框。 配置了这个后会自动添加多个 Panel 面板来编辑。」

**Comment by 2betop** [comment]
没有文档，目前基本上只有 crud 和 cell 是这样，先参考具体的代码实现吧 https://github.com/baidu/amis/blob/master/packages/amis-editor/src/plugin/CRUD.tsx
