### ISSUE TITLE
InputTree 树形选择框配置onlyLeaf和defer时，如果defer未触发叶子节点应不可选中

### ISSUE THREAD

**Issue by ydiego** [baidu/amis#9639]
#### 描述问题：

配置中添加了defer属性，当没有点击箭头图标触发deferapi时，当前节点可选，是否应改成根据deferapi返回结果来决定是否可点击

#### 截图或视频：
未触发defer可选择
![image](https://github.com/baidu/amis/assets/13268002/fa8f09ac-025c-4532-afb4-8cc334fd8c9c)
触发后不可选择
![image](https://github.com/baidu/amis/assets/13268002/89c01fc9-b2e2-4ddc-8ad6-f36b1a1d5f68)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
官网

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
官网
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "type": "tree-select",
        "name": "tree",
        "label": "Tree",
        "deferApi": "/amis/api/mock2/form/deferOptions?label=${label}&waitSeconds=2",
        "onlyLeaf": true,
        "options": [
          {
            "label": "Folder A",
            "value": 1,
            "collapsed": true,
            "children": [
              {
                "label": "file A",
                "value": 2
              },
              {
                "label": "file B",
                "value": 3
              }
            ]
          },
          {
            "label": "这下面是懒加载的",
            "value": 4,
            "defer": true
          },
          {
            "label": "file D",
            "value": 5
          }
        ]
      }
    ]
  }
}
```

4. 操作步骤

**Comment by lengqingfeng** [comment]
必须点击文字才能拿触发点击事件，确实有这个bug

**Comment by F-jianchao** [comment]
当配置onlyLeaf和defer时，如果defer未触发，并且父节点的value是有值的，父节点也是可选的。
当defer触发后，只可选中其叶子节点。
如果设置defer的父节点没有value值，点击父节点后会直接触发懒加载。这种实现逻辑认为符合实际场景，故不认为是一个bug。

**Comment by ydiego** [comment]
> 当配置onlyLeaf和defer时，如果defer未触发，并且父节点的value是有值的，父节点也是可选的。 当defer触发后，只可选中其叶子节点。 如果设置defer的父节点没有value值，点击父节点后会直接触发懒加载。这种实现逻辑认为符合实际场景，故不认为是一个bug。

不能认同，defer应该是优于value值判断才对，而且问题描述中父节点有值的情况下触发了defer，其表单值仍为父节点，明显不合理，那么这onlyLeaf配置有何意义呢

**Comment by F-jianchao** [comment]
我觉得你说的有一定道理，这么做确实更符合逻辑一点。但是考虑到有循环嵌套的子节点的情况。父节点的子节点还可以进行点击和懒加载。如果同样做成defer触发后重置选择，用户可能只是想点开看看这个子节点懒加载的数据，但并不想取消选中这个子节点。 
        如果你只是为了选defer触发后的数据，其实可以直接不给父节点value的。defer: true 的节点，同时没有配置 value 的情况，是不能点选的，点选的话，就应该加载子节点。 希望可以理解

**Comment by ydiego** [comment]
> ```
>     我觉得你说的有一定道理，这么做确实更符合逻辑一点。但是考虑到有循环嵌套的子节点的情况。父节点的子节点还可以进行点击和懒加载。如果同样做成defer触发后重置选择，用户可能只是想点开看看这个子节点懒加载的数据，但并不想取消选中这个子节点。 
>     如果你只是为了选defer触发后的数据，其实可以直接不给父节点value的。defer: true 的节点，同时没有配置 value 的情况，是不能点选的，点选的话，就应该加载子节点。 希望可以理解
> ```
因为业务场景只允许选择子节点，按照现有做法是有可能把父节点的值给提交的，这与onlyLeaf这个含义不符，如果你们这边不好处理，那么建议把value相关的必要条件说明写在文档上把。
