### ISSUE TITLE
crud中如何控制某一列不显示？

### ISSUE THREAD

**Issue by xiahao90** [baidu/amis#9644]
#### 实现场景：
因为有权限要起，某列只有超级管理员可以查看，crud中如何设置呢？搞不来哦

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by ydiego** [comment]
visibleOn

**Comment by xiahao90** [comment]
感谢
