### ISSUE TITLE
点击CRUD表格操作按钮打开抽屉后，抽屉内部Each循环组件会优先取表格数据而不是抽屉内Service获取到的数据

### ISSUE THREAD

**Issue by rumunanfeng** [baidu/amis#9649]
#### 描述问题：

CRUD表格操作按钮打开抽屉后，抽屉内部Each循环组件会优先取表格数据而不是抽屉内Service获取到的数据

#### 截图或视频：
如下面两张图所示，Each动态循环渲染里面的name字段，期望应该是取testList接口返回的name。但是这里却优先取了表格行数据的name。导致数据显示有问题。

![image](https://github.com/baidu/amis/assets/37805363/94991f20-e162-4fd3-973c-60da0955db99)

![image](https://github.com/baidu/amis/assets/37805363/394473da-a1e9-4f4b-8050-0ef0336fbe72)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.5.0
在官网的编辑器中尝试也存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "bodyClassName": "bg-white",
  "body": [
    {
      "type": "crud",
      "headerToolbar": [],
      "bulkActions": [],
      "footerToolbar": [
        {
          "type": "pagination",
          "layout": [
            "perPage",
            "pager"
          ]
        }
      ],
      "loadDataOnce": true,
      "syncLocation": false,
      "keepItemSelectionOnPageChange": true,
      "api": "https://mock.iwhalecloud.com/mock/3889/pagelist",
      "columns": [
        {
          "name": "id",
          "label": "id",
          "type": "operation",
          "buttons": [
            {
              "type": "button",
              "label": "${id}",
              "onEvent": {
                "click": {
                  "actions": [
                    {
                      "actionType": "drawer",
                      "drawer": {
                        "type": "page",
                        "title": "Title"
                        "body": [
                          {
                            "type": "form",
                            "title": "",
                            "body": [
                              {
                                "type": "service",
                                "body": [
                                  {
                                    "type": "each",
                                    "name": "eachList",
                                    "items": [
                                      {
                                        "type": "static",
                                        "name": "name",
                                        "label": "Name"
                                      },
                                      {
                                        "type": "static",
                                        "name": "title",
                                        "label": "Title"
                                      }
                                    ]
                                  }
                                ],
                                "api": {
                                  "url": "https://mock.iwhalecloud.com/mock/3889/testList"
                                }
                              }
                            ]
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            }
          ]
        },
        {
          "name": "name",
          "label": "name",
          "type": "text"
        }
      ],
      "columnsTogglable": "auto"
    }
  ]
}
```

4. 操作步骤
1. 复制code到编辑器
2. 点击表格行id列的按钮
3. 打开抽屉后查看抽屉内渲染的数据

**Comment by ydiego** [comment]
service返回的数据用responseData做个映射换个名称

**Comment by rumunanfeng** [comment]
> testList

要如何配置？
抽屉内的服务返回的数据字段是eachList，已经是特殊的名称了吧

**Comment by rumunanfeng** [comment]
> service返回的数据用responseData做个映射换个名称

要如何配置？
抽屉内的服务返回的数据字段是eachList，已经是特殊的名称了吧

**Comment by ydiego** [comment]
试试map处理下返回新字段？

> > service返回的数据用responseData做个映射换个名称
> 
> 要如何配置？ 抽屉内的服务返回的数据字段是eachList，已经是特殊的名称了吧

**Comment by rumunanfeng** [comment]
> 试试map处理下返回新字段？
> 
> > > service返回的数据用responseData做个映射换个名称
> > 
> > 
> > 要如何配置？ 抽屉内的服务返回的数据字段是eachList，已经是特殊的名称了吧

和字段名应该没关系，我mock数据里面的字段名修改了也不行

**Comment by rumunanfeng** [comment]
能尽快修复一下这个问题吗？

**Comment by 2betop** [comment]
@rumunanfeng  没有复现呢，能否提供一下 pagelist 单接口返回信息？

**Comment by rumunanfeng** [comment]
> @rumunanfeng 没有复现呢，能否提供一下 pagelist 单接口返回信息？
> 
> ```json
> {
>   "type": "page",
>   "bodyClassName": "bg-white",
>   "body": [
>     {
>       "type": "crud",
>       "headerToolbar": [],
>       "bulkActions": [],
>       "footerToolbar": [
>         {
>           "type": "pagination",
>           "layout": [
>             "perPage",
>             "pager"
>           ]
>         }
>       ],
>       "loadDataOnce": true,
>       "syncLocation": false,
>       "keepItemSelectionOnPageChange": true,
>       "api": {
>         "method": "get",
>         "url": "https://mock.iwhalecloud.com/mock/3889/pagelist",
>         "mockResponse": {
>           "status": 200,
>           "data": {
>             "status": 0,
>             "data": {
>               "items": [
>                 {
>                   "id": "111",
>                   "name": "outterName1"
>                 },
>                 {
>                   "id": "2222",
>                   "name": "outterName2"
>                 }
>               ]
>             }
>           }
>         }
>       },
>       "columns": [
>         {
>           "name": "id",
>           "label": "id",
>           "type": "operation",
>           "buttons": [
>             {
>               "type": "button",
>               "label": "${id}",
>               "onEvent": {
>                 "click": {
>                   "actions": [
>                     {
>                       "actionType": "drawer",
>                       "drawer": {
>                         "type": "page",
>                         "title": "Title",
>                         "body": [
>                           {
>                             "type": "form",
>                             "title": "",
>                             "body": [
>                               {
>                                 "type": "service",
>                                 "body": [
>                                   {
>                                     "type": "each",
>                                     "name": "eachList",
>                                     "items": [
>                                       {
>                                         "type": "static",
>                                         "name": "name",
>                                         "label": "Name"
>                                       },
>                                       {
>                                         "type": "static",
>                                         "name": "title",
>                                         "label": "Title"
>                                       }
>                                     ]
>                                   }
>                                 ],
>                                 "api": {
>                                   "url": "https://mock.iwhalecloud.com/mock/3889/testList",
>                                   "method": "get",
>                                   "mockResponse": {
>                                     "status": 200,
>                                     "data": {
>                                       "status": 0,
>                                       "data": {
>                                         "eachList": [
>                                           {
>                                             "id": 1,
>                                             "name": "Inner Name1",
>                                             "title": "title 1"
>                                           },
>                                           {
>                                             "id": 2,
>                                             "name": "Inner Name2",
>                                             "title": "title 2"
>                                           }
>                                         ]
>                                       }
>                                     }
>                                   }
>                                 }
>                               }
>                             ]
>                           }
>                         ]
>                       }
>                     }
>                   ]
>                 }
>               }
>             }
>           ]
>         },
>         {
>           "name": "name",
>           "label": "name",
>           "type": "text"
>         }
>       ],
>       "columnsTogglable": "auto"
>     }
>   ]
> }
> ```
> 
> <img alt="image" width="1749" src="https://private-user-images.githubusercontent.com/2698393/311705052-44d4d00c-2822-4bc0-bd42-b5d1341a20c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzk5MzgsIm5iZiI6MTcxMDM3OTYzOCwicGF0aCI6Ii8yNjk4MzkzLzMxMTcwNTA1Mi00NGQ0ZDAwYy0yODIyLTRiYzAtYmQ0Mi1iNWQxMzQxYTIwYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMDEyNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmE5YTNjY2EzOTAyMmRiYjkyZTc5MDcxY2FiZjc5YzdjNmFjM2QxZGFmZGVmNjhhZTk0OWRmMTgzYjk3YjVmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3MojlFeWUVcjclHH46dCQ04EEMQZnVytqhFCTVjE-B4">

你是用的哪个版本？我用你这段代码，在amis官网的编辑器内也是能复现的：
![image](https://github.com/baidu/amis/assets/37805363/e814590c-20ab-4145-819e-31a49767c333)

**Comment by 2betop** [comment]
请更新到最新的 amis，官网编辑器中的版本可能比较旧
