### ISSUE TITLE
input-table在没有数据的时候显示高度异常

### ISSUE THREAD

**Issue by coldest7z** [baidu/amis#9651]
![image](https://github.com/baidu/amis/assets/45660758/062708ed-4445-4858-a5ae-34d8d0449414)
没数据之前，有数据之后
![image](https://github.com/baidu/amis/assets/45660758/34b12559-9958-4ad4-8694-3cfe3872e24d)
能否修改一下，没数据时占用高度不要这么高，就像编辑器里面这样
![image](https://github.com/baidu/amis/assets/45660758/5ce730e7-5cfc-496c-98e6-6216599985cf)

**Comment by allenve** [comment]
没有数据的样式暂时不支持定制
编辑器中是因为有一个条内容为空的数据 [{}]
