### ISSUE TITLE
CRUD组件调用setValue报错，功能失效。

### ISSUE THREAD

**Issue by findreamer** [baidu/amis#9659]
#### 描述问题：

CRUD组件调用setValue控制台报错。

#### 截图或视频：

https://github.com/baidu/amis/assets/116187210/d44da16f-8069-42b0-885a-caca86e4857e

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis 官网稳定复现

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": [
    {
      "type": "button",
      "label": "更新数据，记录总数被更新为20",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "setValue",
              "componentId": "crud_setvalue",
              "args": {
                "value": {
                  "count": 20
                }
              }
            }
          ]
        }
      }
    },
    {
      "type": "crud",
      "id": "crud_setvalue",
      "syncLocation": false,
      "api": "/amis/api/mock2/sample",
      "quickSaveApi": "/amis/api/mock2/sample/bulkUpdate",
      "headerToolbar": [
        {
          "type": "tpl",
          "tpl": "记录总数：${count}"
        }
      ],
      "columns": [
        {
          "name": "id",
          "label": "ID",
          "id": "u:3db3f2b1b99e"
        },
        {
          "name": "engine",
          "label": "engine",
          "id": "u:0b9be99f3403"
        },
        {
          "name": "version",
          "label": "version",
          "id": "u:4868d7db0139"
        }
      ]
    }
  ]
}
```

5. 操作步骤
如视频所示，首次点击按钮调用setValue不会报错，后续点击按钮，调用setValue控制台报异常。

**Comment by findreamer** [comment]
最终定位到这里[CRUD组件setData方法](https://github.com/baidu/amis/blob/e2db651475a1be3872f698042ad5126959a08650/packages/amis/src/renderers/CRUD.tsx#L2719)，首次调用setValue，store.data.items被覆盖，值变为undefined，再次调用报错。

**Comment by findreamer** [comment]
@2betop 这个bug依然存在啊，官网demo还是在报错
![image](https://github.com/baidu/amis/assets/116187210/07cbcd72-c182-430c-8801-b3c6d335f257)

**Comment by 2betop** [comment]
官网 demo 不会及时更新，请用最新的版本，或者 pull 最新代码

**Comment by findreamer** [comment]
> 官网 demo 不会及时更新，请用最新的版本，或者 pull 最新代码

  @2betop 收到🫡，感谢您的回复，笔芯。
