### ISSUE TITLE
js sdk样式 弹窗不能显示

### ISSUE THREAD

**Issue by beloved-zh** [baidu/amis#9660]
#### 描述问题：

sdk 弹窗样式 `cxd-Modal` 外包了一层 `amis-scope` 导致弹窗创建出来不能打开

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/52067640/8c6d68ee-9ac0-4cad-9dee-303a30ae8005)
![image](https://github.com/baidu/amis/assets/52067640/c8d2e70b-3f32-4f05-a4a9-65d937c82030)
![image](https://github.com/baidu/amis/assets/52067640/ceabecb5-a6c6-4ddb-babe-64a91ba707e5)

#### 如何复现（请务必完整填写下面内容）：
sdk引入，打开个弹窗

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.1.0
3. 粘贴有问题的完整 `amis schema` 代码：
任意弹窗

4. 操作步骤
sdk引入
导入默认主题样式
```js
loadStyles([
  'amis/sdk/sdk.css',
  'amis/sdk/helper.css',
  'amis/sdk/iconfont.css'
])
```
打开任意弹窗

**Comment by 2betop** [comment]
难道是 引入的 amis npm 包，但是用的是 sdk 的 css？如果是这样，建议改成以下两种之一。

* npm 包的 js + amis/lib/themes/cxd.css
* sdk 版本的 js  + sdk 版本的 css

**Comment by beloved-zh** [comment]
想通过npm包管理版本，amis的npm包的sdk目录和releases下载的sdk文件是不一样的吗？
目前引入的都是npm amis包下的sdk目录产物

**Comment by 2betop** [comment]
npm 包里面也有 sdk 目录，前面说的 npm 包的 js 是指，lib 目录下或者 esm 目录下的，不包含底座依赖的版本。

这里有两种方式的快速开始文档 https://aisuda.bce.baidu.com/amis/zh-CN/docs/start/getting-started

**Comment by beloved-zh** [comment]
目前js和css用的都是下载的sdk，编译的`sdk.css`是有问题的
所有的`.cxd-Modal` 都是在 `.amis-scope` 下
创建的 dom 对不上 没有 `.amis-scope`  这一层
![image](https://github.com/baidu/amis/assets/52067640/54344c55-c0b0-4ddd-a372-de7a38be6886)

**Comment by 2betop** [comment]
你用的应该不是 sdk 目录的 js

**Comment by beloved-zh** [comment]
是sdk的，我现在吧npm包去除了，直接下载的 releases 里的`[sdk.tar.gz](https://github.com/baidu/amis/releases/download/6.1.0/sdk.tar.gz)`

**Comment by 2betop** [comment]
是所有的样式都失效，还是只有某个场景下的弹窗失效？从你的截图看 dom 没有添加上 .amis-scope标记，这个有点不符合预期

**Comment by beloved-zh** [comment]
目前测出来是所有的弹窗都没有

**Comment by 2betop** [comment]
amis 项目没能复现，截图看一下 embed 入口的参数？

**Comment by beloved-zh** [comment]
测试和 `env` 中的 `getModalContainer` 有关
目前设置的是 `document.body` 去除就好了
![image](https://github.com/baidu/amis/assets/52067640/808ee74c-0f92-4278-90f5-e04babc49f56)
加这个是因为基座项目是基于vue3 有多标签页，路由缓存
当打开多个 `amis` 渲染的页面，第二个标签打开的弹窗就会显示到第一个标签中

**Comment by beloved-zh** [comment]
不是所有的弹框都是这样，通过事件动作打开的是弹框、抽屉是没有问题
只有表格删除的二次确认消息提示框会串标签

**Comment by 2betop** [comment]
因为自己下发了 getModalContainer 导致的，这个如果不传，默认的是会弹出在 .amis-scope 下面。

**Comment by 2betop** [comment]
> 不是所有的弹框都是这样，通过事件动作打开的是弹框、抽屉是没有问题 只有表格删除的二次确认消息提示框会串标签

自定义的 getModalContainer 里面可以再创建个 div，并且加上  amis-scope，然后让其弹出在这里

**Comment by beloved-zh** [comment]
好的 我试一下

**Comment by beloved-zh** [comment]
怎么样能同时通过 `embed` 创建多个实例共存
现在是新创建的好像会覆盖之前创建的

**Comment by beloved-zh** [comment]
多标签页中每个标签页都会通过 `embed` 创建，测试出来 `env` 中配置的自定义函数，最终调用的都是最新创建的，之前打开的标签页调用的也是最新的

**Comment by beloved-zh** [comment]
env好像全局只有一份

**Comment by 2betop** [comment]
env 里面通过 session 来区分，默认为 global，可以传入 session: 'tab1'

**Comment by beloved-zh** [comment]
好的 明白了 谢谢

**Comment by sweetcard** [comment]
也有可能是AlertComponent的container设置不正确。
参考： 
https://github.com/baidu/amis/blob/e53d6d0d0c5264efa1e8cd3ed53f9593aa5d1b09/examples/embed.tsx#L295
