### ISSUE TITLE
使用SDK模式，如何将token全局注入到请求header中

### ISSUE THREAD

**Issue by zwjsoft** [baidu/amis#9674]
#### 实现场景：
使用sdk模式，如何将token全局注入到请求header中！

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
在 env 中下发 requestAdaptor 并且在里面给api.headers 里面加上token 即可

**Comment by woxiangbo** [comment]
> headers

请问amis-admin中，如何给所有请求加上token呢？
