### ISSUE TITLE
请问 dialog中 form表单和table怎么进行数据关联

### ISSUE THREAD

**Issue by rodchen-king** [baidu/amis#968]
请问 dialog中 form表单和table怎么进行数据关联，通过target关联，操作如下：
1. 点击新增按钮，弹出dialog，里面是一个form。
2. 输入数据，点击确认按钮，dialog关闭。
3. table表格现在只是新增了一条空数据。

期望结果：希望表单填入的内容可以添加到table中。

![image](https://user-images.githubusercontent.com/19780441/94235759-a173d680-ff3e-11ea-86d5-59bd55e8c295.png)

**Comment by ChrisHRZ** [comment]
同问，请问解决了吗？

**Comment by nwind** [comment]
用 crud 吧，直接 reload 就好
