### ISSUE TITLE
【6.1.0编辑器】下拉框组件选择数据源为[上下文变量]时，生成的 schema 多出了 \\，要将这两个 \\ 在代码窗口中手动删除后，tpl 才能正常执行

### ISSUE THREAD

**Issue by citynook** [baidu/amis#9691]
#### 描述问题：
下拉框组件选择数据源为[上下文变量]时，生成的 schema 多出了2个 \\，要将这2个 \\ 在代码窗口中手动删除后，tpl 才能正常执行

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/127393297/2a17c9fd-ee49-414b-88da-c8c1b0214965)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by CheshireJCat** [comment]
请点击 fx 在表达式编辑器中输入表示式
