### ISSUE TITLE
【6.1.0编辑器】弹窗大纲窗口中树节点文本没有执行【标题】的 tpl，无法显示 tpl 返回值 

### ISSUE THREAD

**Issue by citynook** [baidu/amis#9692]
#### 描述问题：
在弹窗大纲中为弹框的【标题】属性指定了 tpl，例如：${t('system.uom.viewTitle')}，这个 tpl 返回值为【度量单位详情】。

弹窗大纲的树节点文本没有执行标题的 tpl，直接显示了标题的属性值。

#### 截图或视频：
![1709198817434](https://github.com/baidu/amis/assets/127393297/4c2c2f5e-ae2d-461c-8bc6-5500287d63c8)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by CheshireJCat** [comment]
符合预期，暂不处理
- 1  解析表达式需要依赖上下文数据，大纲这里并不能拿到期望的运行上下文数据，所以解析也基本没意义
- 2 大纲这里是用来区分弹窗分类的，解析后更加不容易分清是哪个弹窗
