### ISSUE TITLE
支持设置表格嵌套默认展开层级

### ISSUE THREAD

**Issue by Ladtor** [baidu/amis#9697]
#### 是否关联于某个问题吗：
如何设置表格展开层级，似乎只能设置全部展开或全不展开，但是全部展开前端会卡顿，全不展开操作又不方便。

#### 预期的解决方案：
可指定展开层级

#### 其他可接受方案：
1. 每一项都能指定是否自动展开，类似defer标识
2. 可指定子项数量小于某个值的自动展开
3. 可用表达式控制是否自动展开

**Comment by 2betop** [comment]
table 已添加 `setExpanded` 动作，可以指定打开哪条数据，利用初始化动作可以走通这个场景 
https://github.com/baidu/amis/pull/9910/files
