### ISSUE TITLE
cd packages/amis, 执行npm run build 报错，无法打包

### ISSUE THREAD

**Issue by 738326776zby** [baidu/amis#9699]
cd packages/amis, 执行npm run build 报错，无法打包
![Uploading 小米办公20240301-104702.jpg…]()

**Comment by 738326776zby** [comment]
![Uploading 小米办公20240301-104702.jpg…]()

**Comment by 738326776zby** [comment]
![Uploading 小米办公20240301-104702.jpg…]()

**Comment by 738326776zby** [comment]
![小米办公20240301-104702](https://github.com/baidu/amis/assets/18243595/2c3d3cdb-bd60-4049-94f2-9fd65a709f0f)
[!] (plugin commonjs--resolver) Error: Could not load /Users/zhangboya/Desktop/amis/packages/amis/esm/index.js: ENOENT: no such file or directory, open '/Users/zhangboya/Desktop/amis/packages/amis/esm/index.js'

**Comment by 738326776zby** [comment]
我想用a mis 做二开，执行npm run build 的时候会报错，可以帮我看一下

**Comment by nwind** [comment]
需要先在顶层目录运行 npm run build
