### ISSUE TITLE
表达式解析错误，/被转译？

### ISSUE THREAD

**Issue by lqPrototype** [baidu/amis#9705]
#### 描述问题：

"/" 被转译"&#x2F";

#### 截图或视频：
<img width="769" alt="image" src="https://github.com/baidu/amis/assets/30515981/a7080102-8e1e-409c-88c2-831653b6b0d5">
<img width="1282" alt="image" src="https://github.com/baidu/amis/assets/30515981/3c342dc3-b5df-4b96-bfb2-0e90cba33b64">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？

下载源码，暴露amis-core filter方法到全局。

2. 粘贴有问题的完整 `amis schema` 代码：
```javascript

const http = "https://aisuda.bce.baidu.com/amis/zh-CN/docs/index";

Window.amisFilter("${data}", {data: http})；// 'https:&#x2F;&#x2F;aisuda.bce.baidu.com&#x2F;amis&#x2F;zh-CN&#x2F;docs&#x2F;index'

http.slice(6, 15) // '//aisuda.'

Window.amisFilter("${data}", {data: http}).slice(6, 15) // '&#x2F;&#x'

'//aisuda.' === '&#x2F;&#x' // false;


比如上图的slice方法截取也会错误。


```

3. 期望

转译前后，结果一样。

**Comment by CheshireJCat** [comment]
参考https://baidu.github.io/amis/zh-CN/docs/concepts/data-mapping#raw
raw
不同场景下，在使用数据映射时，amis 可能默认会使用html过滤器对数据进行转义显示，这时如果想要输出原始文本，请配置raw过滤器。

基本用法
使用raw可以直接输出原始文本

${xxx | raw}
