### ISSUE TITLE
Table2 表格, 有个想法建议.

### ISSUE THREAD

**Issue by 888go** [baidu/amis#9712]
网页的这种, 想要实现复杂报价系统,  没xls灵活. 
"Table2 表格", 和xls有很大的相似地方. 
如果能直接编辑表格值,  那和xls体验就接近了.  灵活度也会很大提升

 
![1](https://github.com/baidu/amis/assets/43518669/533e2dd1-e9c8-45cc-afd9-89859aa3c6cf)

**Comment by CheshireJCat** [comment]
可以关注一下两个针对 xlsx 的特化组件，看看是否满足需求

[InputExcel 解析 Excel](https://baidu.github.io/amis/zh-CN/components/form/input-excel)
这个组件是通过前端对 Excel 进行解析，将结果作为表单项，使用它有两个好处：

节省后端开发成本，无需再次解析 Excel
可以前端实时预览效果，比如配合 input-table 组件进行二次修改

以及
[Office Viewer Exce](https://baidu.github.io/amis/zh-CN/components/office-viewer-excel)
