### ISSUE TITLE
关于富文本引入的问题

### ISSUE THREAD

**Issue by liuyunpenggit** [baidu/amis#972]
用demo中最简单的方式引入富文本，永远都是froala编辑器。无法切换到tinymce

**Comment by 2betop** [comment]
https://baidu.gitee.io/amis/docs/components/form/rich-text
配置 vendor 试试

**Comment by liuyunpenggit** [comment]
> https://baidu.gitee.io/amis/docs/components/form/rich-text
> 配置供应商尝试

配置我试了 没有效果

**Comment by 2betop** [comment]
怎么使用的？尝试用最新的版本

**Comment by chenyphaaa** [comment]
我这边使用富文本的时候显示Cannot GET /icons/default/icons.js,菜单栏上的图标不能显示

**Comment by 2betop** [comment]
应该是 tinymce 没有安装最新版本？

**Comment by liuyunpenggit** [comment]
再更新最新版本的js后问题解决了
