### ISSUE TITLE
Error: 找不到对应的渲染器  Path: form/0/tabs/tab/1/0/collapse-group/body/0/collapse/body/1/amis-theme-border

### ISSUE THREAD

**Issue by hyy984750073** [baidu/amis#9728]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
将amis-editor升级到6.0.0版本之后，在使用容器类组件时，容器的外观配置无法使用

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://github.com/baidu/amis/assets/22184934/cc5e062b-cffc-46aa-9b8c-9157af55fc79)
![image](https://github.com/baidu/amis/assets/22184934/8bcd6f21-3642-4cd1-b37b-20722fff8e10)
![image](https://github.com/baidu/amis/assets/22184934/b9ff54c6-4387-453f-8b87-035f1d2716b4)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

npm引用的

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.0.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "id": "u:d4acf35fcaab",
  "body": [
    {
      "id": "u:56566128f2ec",
      "api": "test",
      "body": [
        {
          "id": "u:8b7e2c2ed6a2",
          "name": "name",
          "type": "input-text",
          "label": "人物",
          "required": true
        },
        {
          "id": "u:5e2db9e01d72",
          "name": "intro",
          "type": "textarea",
          "label": "百度百科介绍",
          "maxRows": 20,
          "minRows": 3
        }
      ],
      "data": {
        "name": "zhangsan",
        "test2": 20,
        "source": {
          "options": [
            {
              "label": "file C",
              "value": 4
            },
            {
              "label": "file D",
              "value": 5
            }
          ]
        }
      },
      "feat": "Insert",
      "mode": "horizontal",
      "type": "form",
      "title": "表单",
      "dsType": "api",
      "actions": [
      ],
      "resetAfterSubmit": true
    }
  ],
  "data": {
    "age": 20,
    "name": "zhangsan",
    "phone": "15245212244"
  },
  "title": "",
  "regions": [
    "body"
  ],
  "pullRefresh": {
    "disabled": true
  },
  "asideResizor": false
}
```

4. 操作步骤
请简单描述一下复现的操作步骤...
1、大纲中选中“页面”；
2、右侧面板选“外观”，即可看到；
补充：我的截图里有我的项目的配置和引入，不知道是否是缺少什么？

**Comment by 2betop** [comment]
请尝试 6.2.2

**Comment by hyy984750073** [comment]
> 请尝试 6.2.2

仍然有一样的问题

**Comment by hyy984750073** [comment]
> 把 amis-theme-editor-helper 干掉，或者用最新版本

其实我项目没有安装 amis-theme-editor-helper ，因为我看demo里也没有，之前用6.0.0是没有问题的，今天升级到6.2.2就有问题了，我刚才手动安装 amis-theme-editor-helper ，已经可以了
