### ISSUE TITLE
表单编辑器，表单项的绑定字段的数据来自哪里？

### ISSUE THREAD

**Issue by hyy984750073** [baidu/amis#9729]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
在表单编辑器中，我拖出一个表单项，字段名希望从绑定字段中进行选择，我应当如何配置这个这个绑定数据？有什么格式要求？

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://github.com/baidu/amis/assets/22184934/79f2b9e0-f44d-4aad-ac82-e0879e6aa3b3)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.2.2

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "title": "测试01",
  "body": [
    {
      "type": "input-text",
      "label": "姓名",
      "name": "form.name",
      "id": "u:7edc0886b51b"
    }
  ],
  "id": "u:f07ac0b65c21",
  "asideResizor": false,
  "pullRefresh": {
    "disabled": true
  },
  "regions": [
    "body"
  ]
}
```

5. 操作步骤
请简单描述一下复现的操作步骤...
1、打开表单编辑器；
2、从组件面板拖出一个表单项-文本框；
3、右侧面板字段名输入框，点击！图标，打开绑定字段弹窗；
4、弹窗提示“暂无可绑定字段”；
5、应当如何配置这个可绑定字段？

**Comment by allenve** [comment]
这是爱速搭平台的功能

**Comment by hyy984750073** [comment]
> 这是爱速搭平台的功能

这不是amis-editor就有的吗？只是没告诉我们怎么用而已

**Comment by allenve** [comment]
https://github.com/baidu/amis/blob/master/packages/amis-editor/src/builder/DSBuilder.ts
需要去实现 DSBuilder，但是这个目前只在爱速搭实现了
