### ISSUE TITLE
dateTime组件bug

### ISSUE THREAD

**Issue by hellozqy** [baidu/amis#973]
表单项dateTime组件的fomat无法正确生效，只有日期部分生效，而时间部分不生效。
比如"format": "YYYY-MM-DD HH:ss:mm"就只生效年月日，而时分秒不生效。

**Comment by 2betop** [comment]
那个要配置 timeFormat

**Comment by 306392691** [comment]
我经过了更加详细的试验，发现这个dataTime的format在form里面的时候能够正常生效，但是在crud的filter里面的时候没办法正常生效，只有日期部分生效。timeFormat也不能生效。
使用方式是npm引入，版本是1.0.17

**Comment by nwind** [comment]
没复现可能是之前的问题
