### ISSUE TITLE
官方项目也会提示：ReactDOM.render is no longer supported in React 18.   虽然不影响使用

### ISSUE THREAD

**Issue by hyy984750073** [baidu/amis#9731]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
随便拖动一个组件都会提示这个问题。

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...
![image](https://github.com/baidu/amis/assets/22184934/8afbec91-cc50-4f55-81fa-6b3c476ba6f8)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.2.2
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by CheshireJCat** [comment]
已知警告，不影响使用暂时保持现状
