### ISSUE TITLE
react+vite下的amis编辑器json问题

### ISSUE THREAD

**Issue by zhuominlooper** [baidu/amis#9734]
#### 参考官方demo搭建的编辑器，版本都是6.0.0，但是json编辑有问题时候没有飘红提示

![image](https://github.com/baidu/amis/assets/42455623/69ecf396-9010-4d32-8790-b8e359e05084)

原因猜想：编辑器飘红功能应该是monaco编辑器的功能，但是不知道是不是vite打包引起的这个问题。

期待效果：
![image](https://github.com/baidu/amis/assets/42455623/ff7ba6d9-0ad7-42fa-8ceb-a746a6ad69e2)

**Comment by zhuominlooper** [comment]
找到原因了这个文件加载404
![image](https://github.com/baidu/amis/assets/42455623/623e4268-7977-4e3f-a465-f9066aacfe98)
路径是：http://localhost:4000/pkg/editor.worker.js,文件没找到

**Comment by 2betop** [comment]
vite 需要用 monaco-editor 插件 `vite-plugin-monaco-editor`

**Comment by zhuominlooper** [comment]
> vite 需要用 monaco-editor 插件 `vite-plugin-monaco-editor`

好的，感谢大佬，解决了

**Comment by Yyx1999-boss** [comment]
您好 请问您react+vite中是如何集成amis编辑器的 我这里集成就会报各种依赖的错误
