### ISSUE TITLE
crud列排序显示列保存失效（有视频展示）

### ISSUE THREAD

**Issue by YSceshi** [baidu/amis#9741]
#### 描述问题：

crud显示列选择保存后，F5刷新页面，显示列保存失败

#### 截图或视频：

https://github.com/baidu/amis/assets/161827768/2bf7dc82-c2bf-4644-a2cf-d34fb40a6f7e

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

6.2.2

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
点击选择显示列并保存，保存后页面不显示保存的显示列

**Comment by 2betop** [comment]
amis 项目中看起来没事，是不是用错版本了？

**Comment by YSceshi** [comment]
使用的是最新的amis版本

**Comment by YSceshi** [comment]
> amis 项目中看起来没事，是不是用错版本了？

使用是最新的版本6.2.2

**Comment by YSceshi** [comment]
> amis 项目中看起来没事，是不是用错版本了？
