### ISSUE TITLE
如何显示当前时间并实时显示啊？请教一下各位大佬

### ISSUE THREAD

**Issue by gjy0712** [baidu/amis#975]
#### 实现场景：
想要实现当前时间 并实时显示

#### 存在的问题：
不知道如何才能实时显示

#### 当前方案：
{
    "$schema": "https://houtai.baidu.com/v2/schemas/tpl.json#",
    "type": "tpl",
    "tpl": "<%= date(new Date(), 'YYYY年MM月DD日 HH:mm:ss') %>"
}

**Comment by RickCole21** [comment]
目前没有这类组件，用自定义组件实现吧

**Comment by nwind** [comment]
service 加了个例子倒是能实现 https://baidu.gitee.io/amis/zh-CN/components/service#%E8%B0%83%E7%94%A8%E5%A4%96%E9%83%A8%E5%87%BD%E6%95%B0%E8%8E%B7%E5%8F%96%E6%95%B0%E6%8D%AE
