### ISSUE TITLE
vite+vue3生产环境下charts资源找不到，本地打包时候没问题

### ISSUE THREAD

**Issue by zhuominlooper** [baidu/amis#9750]
#### 版本：
1. amis版本:6.0.0
2. 引入方式如下：
![image](https://github.com/baidu/amis/assets/42455623/5ebae93e-e6b5-4425-a480-1816f53cbd05)
#### 问题
1.vite本地打包时候，只是预编译了一下，正常
2.生产构建时候：打包出来没得charts资源
![image](https://github.com/baidu/amis/assets/42455623/43da8019-b326-4071-b517-5c8e144dbd88)
3.导致加载资源404
![image](https://github.com/baidu/amis/assets/42455623/eeb4748d-fe1b-41f5-831e-8c81a57529f1)
麻烦大佬帮看一下，还需要什么插件吗

**Comment by zhuominlooper** [comment]
我现在是用了别的方式线上打包把源码里的charts加载进去了，就行了
不晓得是啥问题

**Comment by 2betop** [comment]
sdk 就不要再编译了，直接 copy 过去使用即可，参考： https://github.com/aisuda/vue2-amis-demo/blob/main/vite.config.js#L32-L39

**Comment by zhuominlooper** [comment]
> sdk 就不要再编译了，直接 copy 过去使用即可，参考： https://github.com/aisuda/vue2-amis-demo/blob/main/vite.config.js#L32-L39

ok,我现在就是copy过去用的，就正常了
