### ISSUE TITLE
input-table组件中columns中字段被包一层的时候，其在form中行数据中字段必填属性在表单提交时没有触发校验 

### ISSUE THREAD

**Issue by yinlianghui** [baidu/amis#9756]
#### 描述问题：

如下图所示：
- a和b两个字段被包了一层wrapper组件，其中b为static模式
- c和d两个字段没有被其他组件包一层，其中d为static模式
- a、b、c、d4个字段都是必填的
- 整个input-table是放在form组件中，图示测试的是点击form底部的提交按钮是否会触发上面4个字段的必填校验

图示结果：
- a和b两个字段没有被触发校验，这是bug
- c和d两个字段会被触发校验，这是正常的

当input-table组件中要渲染的字段是自定义组件时会遇到像上面a和b两个字段这种多层组件的情况。

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/6219465/59a1a11b-4453-49eb-bb64-c17a7a30296d)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis 3.6/6.0版本中是坏的，issue： https://github.com/baidu/amis/issues/9537 中提交的代码实测也是坏的

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "data": {
      "table": [
        {
          "a": "a1",
          "b": "b1",
          "c": "c1",
          "d": "d1"
        },
        {
          "a": "a2",
          "b": "b2",
          "c": "c2",
          "d": "d2"
        },
        {
          "a": "",
          "b": "",
          "c": "",
          "d": ""
        }
      ]
    },
    "api": "/amis/api/mock2/form/saveForm",
    "body": [
      {
        "label": "abc",
        "showIndex": true,
        "type": "input-table",
        "showTableAddBtn": false,
        "name": "table",
        "addable": true,
        "mode": "normal",
        "columnsTogglable": false,
        "columns": [
          {
            "type": "wrapper",
            "label": "A",
            "body": [
              {
                "name": "a",
                "label": false,
                "type": "input-text",
                "required": true
              }
            ]
          },
          {
            "type": "wrapper",
            "label": "B",
            "body": [
              {
                "name": "b",
                "label": false,
                "type": "input-text",
                "required": true,
                "static": true
              }
            ]
          },
          {
            "name": "c",
            "label": "C",
            "type": "input-text",
            "required": true
          },
          {
            "name": "d",
            "label": "D",
            "type": "input-text",
            "required": true,
            "static": true
          }
        ]
      }
    ]
  }
}
```

5. 操作步骤
把上面的schema示例copy到上面的官网示例  https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-table#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95 代码中就能重现此问题

**Comment by 2betop** [comment]
没你说的问题呢
<img width="1763" alt="image" src="https://github.com/baidu/amis/assets/2698393/b541f9df-496d-4c33-bb96-3fc5c4ec10be">

**Comment by yinlianghui** [comment]
> 没你说的问题呢 <img alt="image" width="1763" src="https://private-user-images.githubusercontent.com/2698393/311569068-b541f9df-496d-4c33-bb96-3fc5c4ec10be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjI2MTUsIm5iZiI6MTcxMDMyMjMxNSwicGF0aCI6Ii8yNjk4MzkzLzMxMTU2OTA2OC1iNTQxZjlkZi00OTZkLTRjMzMtYmI5Ni0zZmM1YzRlYzEwYmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTNUMDkzMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjEzN2FkMTVkMjEwMTIyMWM1NTEyZTI3OGUzMWIzZjU5YzVlYjNiYWZlM2NiY2E3ZDhlMDFmYTk4ZDRiYWMwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tykQgrozvhREv4JuQq1_CqdKqRUOAHgaOwNpKLtcX3M">

你们官方平台测试没问题就好，这这边有问题应该是因为在3.6分支基础上抄的上面提交的代码，暂时也不影响使用，可以先收了，再次感谢 @2betop  修正此问题。
