### ISSUE TITLE
select creatable之后options里没有的值无法默认填充

### ISSUE THREAD

**Issue by hotmaycold** [baidu/amis#976]
大佬，有没有类似的可以实现的方法，input和select结合的组件，既可以用户输入又可以勾选

**Comment by RickCole21** [comment]
没太看懂，看看这个？https://baidu.github.io/amis/docs/components/form/options#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%B0%E5%A2%9E%E8%A1%A8%E5%8D%95%E9%A1%B9-addcontrols

**Comment by RickCole21** [comment]
无反馈，先关了

**Comment by hotmaycold** [comment]
> 无反馈，先关了

select creatable打开之后，新增选项完成还要再点一下选项才能选中，能不能输入新选项后立即选中
