### ISSUE TITLE
如何配置全局url？

### ISSUE THREAD

**Issue by VanMesure** [baidu/amis#977]
#### 实现场景：
我生成了N个页面，如果我要改动接口url地址的话（比如从测试地址切换到线上地址），就得去每个文件里边单独改一份。

#### 存在的问题：
怎样可以让所有页面文件引用同一个全局url变量？

**Comment by RickCole21** [comment]
直接用一个配置文件来配置，其他文件引用就好了吧

**Comment by shiwl0329** [comment]
> 直接用一个配置文件来配置，其他文件引用就好了吧
怎么配置呢？

**Comment by shiwl0329** [comment]
> #### 实现场景：
> 我生成了N个页面，如果我要改动接口url地址的话（比如从测试地址切换到线上地址），就得去每个文件里边单独改一份。
> 
> #### 存在的问题：
> 怎样可以让所有页面文件引用同一个全局url变量？
> 
> #### 当前方案：

有配置出来么

**Comment by MoNianGolang** [comment]
> 直接用一个配置文件来配置，其他文件引用就好了吧

该怎么引用的？有代码吗？

**Comment by fengde** [comment]
同问
