### ISSUE TITLE
请问上传文件的时侯是否提供记录文件在本地的路径名字？

### ISSUE THREAD

**Issue by laofuzi123321** [baidu/amis#9770]
#### 是否关联于某个问题吗：
请用一段简单清晰的文字描述你的想法是关联于某个问题，例如：因为我没办法实现xxx...

#### 预期的解决方案：
请简单描述你想达到的效果...

#### 其他可接受方案：
请简单描述其他你可以接受的效果...

#### 任何附加信息：
请添加任何可以补充说明上述问题的材料，例如图片或视频等...

**Comment by CheshireJCat** [comment]
在浏览器中直接访问本地文件路径通常是不可能的，因为出于安全原因，现代浏览器限制了直接访问文件系统的能力。
