### ISSUE TITLE
本地 npm run build 报错 无法构建出产物

### ISSUE THREAD

**Issue by Wss199mz** [baidu/amis#9774]
clone到本地后 npm i 安装依赖没报错，执行npm run build报错无法构建

<img width="932" alt="image" src="https://github.com/baidu/amis/assets/30562216/3a4b0e07-796d-466f-9343-d1f137613ae9">
<img width="934" alt="image" src="https://github.com/baidu/amis/assets/30562216/62786c64-e289-40a0-b229-05fdc39142f3">
<img width="862" alt="image" src="https://github.com/baidu/amis/assets/30562216/38421a77-9645-4aa4-8f12-43ae6490744e">
<img width="861" alt="image" src="https://github.com/baidu/amis/assets/30562216/e4eeb7dd-4eca-419f-8417-20e51cff1e6a">

<img width="750" alt="image" src="https://github.com/baidu/amis/assets/30562216/10ed10df-3b23-40a3-a29f-5411099c25d7">

本地执行 npm run build

amis 版本: 3.6.0

环境：mac node16+  npm@8.5.0

**Comment by 2betop** [comment]
看起来没问题，很可能是你只是在 vscode 里面看不到那些目录而已，实际是存在的。因为 `./vscode/setting.json` 里面把那几个目录排除掉了。

**Comment by Wss199mz** [comment]
> 看起来没问题，很可能只是你在 vscode 里面看不到那些目录而已，实际是存在的。因为 `./vscode/setting.json` 里面把那几个目录排除掉了。

我重新打包看了下，amis-core、amis-formula、amis-ui 只有这三个包有产物，amis、amis-editor、amis-editor-core、amis-theme-editor-helper、office-viewer 这几个包没有产物。
打包后命令行卡在这里：
<img width="922" alt="image" src="https://github.com/baidu/amis/assets/30562216/7be95dc5-fab3-4b47-8278-154efb97f64e">

**Comment by Wss199mz** [comment]
<img width="922" alt="image" src="https://github.com/baidu/amis/assets/30562216/245002f5-fa7f-4016-a31b-1e9c40e9e73a">

**Comment by 2betop** [comment]
直接跑 `npm run build --workspace=amis` 看编译卡在哪一步，目前你的截图是没有错误信息的

**Comment by 2betop** [comment]
由于长时间没反馈，先关闭，有问题再开
