### ISSUE TITLE
【6.2.2】amis 源码如何自行编译成 sdk.tar.gz 压缩包

### ISSUE THREAD

**Issue by leung0727** [baidu/amis#9779]
#### 描述问题：

我 clone 了 https://github.com/baidu/amis.git 源码【6.2.2】版本，如何将源码自行编译成你们发布版本下面的 sdk.tar.gz 文件，按照文档上的编译步骤会报错

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/116611745/f525a3b7-f4cc-4e0b-a83c-ba2c84fda2d5)
![image](https://github.com/baidu/amis/assets/116611745/19fa47de-f922-4a5d-8c20-6b9dcac55890)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.2.2

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
要用 linux 或者 mac，windows 下面没跑过

**Comment by leung0727** [comment]
就是 linux 下就能将源码编译成 sdk.tar.gz 文件吗，因为我这边项目是依靠 sdk.tar.gz来支撑的

**Comment by 2betop** [comment]
`npm run build`  然后用 packages/amis/sdk 目录

**Comment by leung0727** [comment]
好的谢谢，我这边试下
