### ISSUE TITLE
6.2.2版本下启用千分位和双精度时inputNumber组件无法正常输入小数

### ISSUE THREAD

**Issue by JinlongHo** [baidu/amis#9795]
#### 描述问题：

最新版本下启用千分位和双精度的inputNumber组件无法正常输入小数，在3.2.0版本时是正常的，目前确定原因是变更了数字输入框的formatter，导致在输入过程中进行了数字value格式化操作，从而引发输入偏移、小数不能正常输入。

#### 截图或视频：

https://github.com/baidu/amis/assets/26133643/be0300fa-e7cc-478d-b087-8b5d66593b6b

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

amis 版本是6.2.2

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
"type": "page",
"body": {
"type": "form",
"debug": true,
"api": "/amis/api/mock2/form/saveForm",
"data": {
"number2": 3.1234
},
"body": [
{
"type": "input-number",
"name": "number1",
"label": "数字",
"kilobitSeparator": true,
"precision": 2,
"step": 0.01,
"value": 2.98786
},
{
"type": "input-number",
"name": "number2",
"label": "数字2",
"kilobitSeparator": true,
"precision": 3,
"step": 0.001
},
{
"type": "input-number",
"name": "number3",
"label": "数字3",
"kilobitSeparator": true,
"step": 0.001,
"description": "不设置precision，仅设置step, 实际精度为3"
}
]
}
}
```

4. 操作步骤
输入带小数点数字

**Comment by idjerry** [comment]
我这边也遇到了，有什么好的解决方法吗。目前还是存在这种情况

**Comment by wibetter** [comment]
已在amis中支持，相关改动建见：https://github.com/baidu/amis/pull/9948/commits/f76e6b10a410c037089945c802c64bfc6edb4098
