### ISSUE TITLE
编辑器升级到6.2.2版本后右侧面板出现bug

### ISSUE THREAD

**Issue by wubin1989** [baidu/amis#9811]
![截屏2024-03-16 下午11 52 36](https://github.com/baidu/amis/assets/12456315/a30c919e-2093-429d-8c85-1066eebb5230)

**Comment by czc945** [comment]
添加 amis-theme-editor-helper 最新版本依赖可以解决。
npm i amis-theme-editor-helper

**Comment by wubin1989** [comment]
> 添加 amis-theme-editor-helper 最新版本依赖可以解决。 npm i amis-theme-editor-helper

@czc945 谢谢！问题已解决！
