### ISSUE TITLE
api接口如果是Get请求，则requestAdaptor脚本中重写api.data后，请求参数未按此data来，多出的参数无法删除

### ISSUE THREAD

**Issue by yinlianghui** [baidu/amis#9813]
#### 描述问题：

比如在Form组件initApi接口中本身data属性中有参数，此时如果想在requestAdaptor脚本中重写参数把data中的参数删除并加上新参数，发现新加参数可以生效，但是原data中的参数还是会出现在api接口请求中。

- 实测只有接口为GET请求才有问题，POST是好的。
- 不只是Form组件有此问题，实测CRUD也有此问题，应该是api统一的功能存在问题。

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/6219465/291a7538-c432-4c4f-976a-bdc49c5b751a)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
amis目前的官网还有此问题，应该是6.x，我们3.6版本sdk存在此问题。

4. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "initApi": {
      "url": "/amis/api/mock2/form/initData",
      "data": {
        "x": 1
      },
      "adaptor": "console.log('==adaptor===api.body==',api.body);return payload;",
      "requestAdaptor": "api.data = {m:5};console.log('===api===',api);return {...api,data:{s:3}};"
    },
    "title": "编辑用户信息",
    "body": [
      {
        "type": "input-text",
        "name": "name",
        "label": "姓名"
      },
      {
        "type": "input-text",
        "name": "email",
        "label": "邮箱"
      }
    ]
  }
}
```

5. 操作步骤

在官网示例 https://aisuda.bce.baidu.com/amis/zh-CN/components/form/index#%E8%A1%A8%E5%8D%95%E9%A1%B9%E6%95%B0%E6%8D%AE%E5%88%9D%E5%A7%8B%E5%8C%96 中把上面的schema json复制进去，打开浏览器控制台查看示例中的network面板可以看到form的请求接口中未能把data.x参数删除。

**Comment by 2betop** [comment]
这个应该是修改 api.query 对象，因为 amis 目前内部会把所有参数（包含 get 时的 data 参数、 写在 url 问号后面的参数） 都整合到 api.query 里面。参数放到 api.url 后就会删掉 api.data ，如果适配器里面要修改参数，还是去修改 api.query 好了

相关代码提交见：#10249
