### ISSUE TITLE
树形选择框自动选中问题

### ISSUE THREAD

**Issue by Ladtor** [baidu/amis#9815]
#### 是否关联于某个问题吗：
在权限控制的场景中，我们把父节点理解为文件夹，子节点理解为文件；
1. 那么，选中文件夹的含义包括文件夹内的所有文件，因此，我期望选中父节点的时候可以自动选中子节点，这是已支持的功能(`autoCheckChildren=true`)
![image](https://github.com/baidu/amis/assets/19227210/759f06f1-459c-4028-8fa5-f718d46c32e5)

2. 但是，与此同时，我选中了所有文件则不代表我选中了文件夹（区别在于我没权限对文件夹操作，例如重命名，删除文件夹，后续新增文件的权限等），因此，我期望选中所有子节点的时候不要自动选中父节点，这是已支持的功能(`autoCheckChildren=false`)
![image](https://github.com/baidu/amis/assets/19227210/ec5d5fcd-c3cf-4854-b162-f92268038718)

3. 由于这是同一个参数`autoCheckChildren`控制的，因此我难以实现我的需求

#### 预期的解决方案：
期望在树形选择框中，选中父节点可以自动选中子节点，但选中所有子节点不要默认选中父点
1. 对于父子节点是否自动选中，提供独立的参数设置

**Comment by Ladtor** [comment]
> 抱歉，如果是每一项都独立配置`父子节点是否自动选中`，这种需求太过于个性化，不适合在公共组件实现

@CheshireJCat 不好意思，没描述清楚，我的意思是：
将 `选中父节点是否自动选中子节点` 以及 `选中所有子节点是否自动选中父节点` 的配置项分离，不共用同一个配置项；

**Comment by CheshireJCat** [comment]
无法支持，
autoCheckChildren默认为 true，选中父节点会自动选中子节点，
"autoCheckChildren": false，不自动选中子节点
并不是你描述的选中子节点的时候不要自动选中父节点

你可以用 onlyChildren，实现只包含子节点的值，不携带父节点的值
