### ISSUE TITLE
跳转链接动作，当前页url带有hash时，对目标url的处理有问题

### ISSUE THREAD

**Issue by snowing-x** [baidu/amis#9817]
#### 描述问题：

使用跳转链接动作时，如果当前页面url带有hash，而要跳转的目标url不包含hash，那么实际跳转的url会自动带着当前页的hash。

#### 如何复现（请务必完整填写下面内容）：

[可以直接通过文档里的例子复现](https://baidu.github.io/amis/zh-CN/components/action?page=1#%E7%9B%B4%E6%8E%A5%E8%B7%B3%E8%BD%AC)
<img width="823" alt="企业微信截图_5070f720-c41f-4d26-8b52-cb8a94a1cedf" src="https://github.com/baidu/amis/assets/51695385/7555f2aa-99c8-489b-9678-37781ddb8f99">

4. 操作步骤
点击【打开Baidu】按钮，会发现url带有原页面的hash
<img width="369" alt="企业微信截图_ae222f06-496b-42d2-88c4-ef74ba7f8342" src="https://github.com/baidu/amis/assets/51695385/51d09841-8541-4f5b-8eee-eb4a9126dd02">

**Comment by CheshireJCat** [comment]
是这么设计的
