### ISSUE TITLE
office-viewer 报错amis.define is not a function

### ISSUE THREAD

**Issue by 603550104** [baidu/amis#9818]
#### 描述问题：

office-viewer 报错amis.define is not a function

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/26154427/82a866ab-5864-4ac5-a387-d2a4fe98c863)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.2.2
3. 粘贴有问题的完整 `amis schema` 代码：
```
 var page = {
        "type": "page",
        "body": {
            "type": "office-viewer",
            "src": "simple.docx",
            "wordOptions": {
                "padding": "8px",
                "ignoreWidth": false
            }
        }
    }

    var amisJSON = page;

    let amis = amisRequire('amis/embed');
    let amisScoped = amis.embed('#root', amisJSON);
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
未复现，怀疑是 sdk 不完整导致，或者使用第三方 cdn 有问题，另外新版有改动，去掉了外部依赖，可以试试 https://github.com/baidu/amis/blob/gh-pages/sdk.tar.gz

**Comment by veincheng** [comment]
我的解决方案很简单,在引入sdk.js的代码后面添加script引入第三方库的链接,比如office-viewer/json-view之类的
