### ISSUE TITLE
amis 研发招人啦，坐标北京

### ISSUE THREAD

**Issue by nwind** [baidu/amis#983]
### 职位描述

主要工作：

- amis 开源项目的开发和维护
- [爱速搭](https://suda.baidu.com/)低代码平台的前后端开发

地点：北京

时间：2020.12.31 前能入职

职位要求：

- 前端基础扎实，熟悉 React、TypeScript
- 熟悉 Node、Express
- 对新技术感兴趣，一直在持续学习
- 熟悉 amis 配置及源码的优先

其它：非 996，平时不加班，每周只有一个会

联系方式： 发简历到 wuduoyi@baidu.com

**Comment by FatDong1** [comment]
可惜不在深圳

**Comment by yeyuguo** [comment]
喜欢  low code

**Comment by yeyuguo** [comment]
喜欢

**Comment by yeyuguo** [comment]
真香

**Comment by westeast** [comment]
amis做的太好了，后端想转，要吗 :)
