### ISSUE TITLE
clone代码失败：error: invalid path 'packages/office-viewer/src/excel/types/X14Sparkline/x14:sparklines.ts'

### ISSUE THREAD

**Issue by AprildreamMI** [baidu/amis#9833]
![image](https://github.com/baidu/amis/assets/31964372/fc9311ef-2e10-429b-aba7-06433aec7422)

**Comment by AprildreamMI** [comment]
@nwind

**Comment by AprildreamMI** [comment]
文件名`packages\office-viewer\src\excel\types\X14Sparkline\x14`存在`:`

**Comment by Stitch-1028** [comment]
菜就多练，哪来这些B问题，我Mac怎么就好好的？

![菜就多练](https://github.com/baidu/amis/assets/83273005/a5316c37-1f77-4bfc-870f-1feafcf0b98f)

**Comment by nwind** [comment]
fixed in @9842

**Comment by AprildreamMI** [comment]
fixed in #9842
