### ISSUE TITLE
js sdk模式下： input tree的tooltip位置显示异常

### ISSUE THREAD

**Issue by ljmCoder** [baidu/amis#9834]
#### 描述问题：
js sdk模式下： input tree的tooltip位置显示异常
请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：
js sdk 6.2.2版本下， 树组件开启编辑操作： 悬浮编辑的时候 tooltip位置异常
![image](https://github.com/baidu/amis/assets/41459781/5270cedf-440a-471f-aff4-db5eac86ff9b)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
sdk
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
sdk6.2.2
3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "title": "Simple Form Page",
  "regions": ["body"],
  "body": [
    {
      "type": "input-tree",
      "label": "树组件",
      "name": "tree",
      "options": [
        {
          "label": "选项A",
          "value": "A",
          "children": [
            {
              "label": "选项C",
              "value": "C"
            },
            {
              "label": "选项D",
              "value": "D"
            }
          ]
        },
        {
          "label": "选项B",
          "value": "B"
        }
      ],
      "id": "u:b0f0ebb830d3",
      "multiple": false,
      "enableNodePath": false,
      "hideRoot": true,
      "showIcon": true,
      "initiallyOpen": true,
      "editable": true
    }
  ],
  "id": "u:24951e233ba3"
}

```

4. 操作步骤
js sdk 6.2.2版本下， 树组件开启编辑操作： 悬浮编辑的时候 tooltip位置异常
sdk下，原逻辑是想把所有弹窗放在amis-scope下，样式也都是amis-scope为前缀。 在input tree组件中， 开启编辑的时候， 悬浮编辑，这个悬浮出来的tooltip并没有显示在.amis-scope下， 显示在了body下，也就导致了针对tooltip的样式没有应用上。

**Comment by ljmCoder** [comment]
@nwind @TeCHiScy @luckyufei @weien601 是否可以针对这类通用场景优化：类似input tree组件中直接引用弹窗类组件， 弹窗并未放进amis-scope里面。

**Comment by ljmCoder** [comment]
@2betop 这应该是一个通用类的问题， 组件代码直接引用amis的tooltipwrapper，都会导致在sdk模式下tooltip的位置异常，搜了下组件里面直接引用tooltipwrapper的组件，比如其中tabs组件就有这种场景:
如下：
{
  "type": "page",
  "title": "Simple Form Page",
  "regions": ["body"],
  "body": [
    {
      "type": "tabs",
      "tabs": [
        {
          "title": "选项卡1",
          "body": [],
          "id": "u:ea303bda9ec3"
        },
        {
          "title": "选项卡2",
          "body": []
        }
      ],
      "id": "u:eb6268114055",
      "showTip": true
    }
  ],
  "id": "u:24951e233ba3"
}
![image](https://github.com/baidu/amis/assets/41459781/329501a6-304e-4fd1-b3a5-fb6419128066)


所以大佬是不是考虑有更通用的解决办法， 不然以后封装组件代码里面用到了amis ui的tooltipWrapper， 都得手动传env.getContainer， 我看现有的amis组件库也有好多用到了tooltipWrapper的

**Comment by 2betop** [comment]
嗯，说得对，改成调整 Overlay 更底层的逻辑了。
