### ISSUE TITLE
使用JS SDK方式使用，请求如何加密参数让后台可以校验

### ISSUE THREAD

**Issue by OnGoingLzy** [baidu/amis#9839]
#### 实现场景：
使用JS SDK方式使用，请求如何加密参数让后台可以校验。目前的请求是明文请求，我想要在请求前将参数加密签名，作为请求头参数，由后端对其进行校验签名。

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by 2betop** [comment]
在 env 中下发 fetcher 或者 requestAdaptor，来扩充功能

**Comment by OnGoingLzy** [comment]
Cannot read properties of undefined (reading 'content-type')

**Comment by OnGoingLzy** [comment]
> 在 env 中下发 fetcher 或者 requestAdaptor，来扩充功能
![1711012020834](https://github.com/baidu/amis/assets/65748123/b5e8eb73-ea2d-4e19-b194-06b91ee36eb0)
我已经配置了fetcher，get请求正常。但是在post请求时，虽然接口已经成功调用了，但是amis还是弹出错误toast；

我的fetcher代码如下：fetcher: ({ url, method, data, config, headers }) => {
                      config = config || {};
                      config.headers = config.headers || headers || {};
                      config.credentials = 'include';

                  // 获取当前时间戳
                      let timestamp = Date.now();

                      // 根据method、data和时间戳生成签名
                      let signature = "489787" + timestamp;

                      if (method !== 'post' && method !== 'put' && method !== 'patch') {
                          if (data) {
                              
                              const queryString = Object.keys(data).map(key => `${encodeURIComponent(key)}=${encodeURIComponent(data[key])}`).join('&');
                              url += (url.indexOf('?') === -1 ? '?' : '&') + queryString;
                          }
                          config.headers['Content-Type'] = 'application/json';
                          config.headers['signature'] = signature;
                          config.headers['timestamp'] = timestamp;

                          return fetch(url, config).then(res => res.json());
                      } else if (data && data instanceof FormData) {
                          
                          config.method = method;
                          config.body = data;
                      } else if (
                          data &&
                          typeof data !== 'string' &&
                          !(data instanceof Blob) &&
                          !(data instanceof ArrayBuffer)
                      ) {
                          
                          config.method = method;
                          config.body = JSON.stringify(data);
                          config.headers['content-type'] = 'application/json';
                          config.headers['signature'] = signature;
                          config.headers['timestamp'] = timestamp;
                          data = JSON.stringify(data);
                          //debugger
                      }

                      return fetch(url, config).then(res => res.json());
                  },//fetcher结束
