### ISSUE TITLE
我们想要一个dateTime组件在展示性容器里面用于可视化的去展示时间范围！

### ISSUE THREAD

**Issue by 306392691** [baidu/amis#984]
就像text在form里面是一个输入框而在table里面是文本展示一样。

**Comment by 2betop** [comment]
https://baidu.gitee.io/amis/docs/components/date

**Comment by 306392691** [comment]
具体情况应该是像一个日历一样的去展示一个时间，而不是用类似文本展示，比如说这样根据日期可视化的展示时间范围。
![image](https://user-images.githubusercontent.com/48118280/95958555-e26f5480-0e33-11eb-976f-1d711235cef8.png)

**Comment by 2betop** [comment]
目前组件还不支持默认打开，后续加个 embed: true 直接展示模式

**Comment by 2betop** [comment]
> 目前组件还不支持默认打开，后续加个 embed: true 直接展示模式

已经提交代码了，后续版本会有
