### ISSUE TITLE
Error: The following dependencies are imported but could not be resolved

### ISSUE THREAD

**Issue by cutestyxy** [baidu/amis#9840]
#### 描述问题：

amis，master分支拉代码下来，按照依赖，启动报错

#### 截图或视频：

<img width="986" alt="image" src="https://github.com/baidu/amis/assets/73709680/c102fd30-04fc-47e5-9035-017657a47150">

#### 如何复现（请务必完整填写下面内容）：

 npm i --legacy-peer-deps
 npm start
然后就报错 Error: The following dependencies are imported but could not be resolved:

**Comment by cutestyxy** [comment]
node 14.21  ｜ npm 6

**Comment by 2betop** [comment]
npm 要 7+

**Comment by cutestyxy** [comment]
> npm 要 7+

<img width="845" alt="image" src="https://github.com/baidu/amis/assets/73709680/d84f5740-3822-4876-88d3-3ea16a2ac277">
node 16.20 | npm 8.19

**Comment by cutestyxy** [comment]
> npm 要 7+

大佬再帮忙看看呢 换了版本 安装不上依赖了

**Comment by cutestyxy** [comment]
> npm 要 7+

搞定了 感谢大佬
