### ISSUE TITLE
怎么给组件赋值呢?

### ISSUE THREAD

**Issue by xjxqd** [baidu/amis#9851]
onChange: function(value) {
                                    // 当表格数据发生变化时，这个函数将被调用
                                    console.log('表格数据:', value);
                                   let that = this; // 保存当前上下文
                                    // 将数据发送到后端
                                    fetch('/calcAmount', {  // 替换为实际的后端计算API
                                        method: 'POST',
                                        headers: {
                                            'Content-Type': 'application/json',
                                        },
                                        body: JSON.stringify(value),
                                    })
                                        .then(response => response.json())
                                        .then(data => {
                                            console.log('后端返回的合计金额:', data.data.total);
                                            // 可以在这里更新页面上的显示等
                                            let totalAmount = data.data.total;
                                            // 赋值操作，无论金额正负都将其显示
                                           that.setValue('total', totalAmount);
                                        })
                                        .catch(error => {
                                            console.error('Error:', error);
                                        });
                                },
                            },
                            {
                                "name": "total",
                                "id": "total",
                                "label": "合计金额",
                                "type": "input-number",
                                "precision": 2,
                                "step": 0.01,
                                "disabled": true,
                            },
                            怎么把totalAmount赋值给total

**Comment by 2betop** [comment]
最好是不要自己写这种逻辑，利用 form 的 initApi 就能实现同样的功能。

如果要用代码赋值，则需要用到onChange 回调的第四个参数 `form.changeValue(name, value)`
