### ISSUE TITLE
变量循环引用

### ISSUE THREAD

**Issue by lhkg1988** [baidu/amis#9864]
#### 描述问题：低版本的直接赋默认值，升到3.4.x版本，表单集合上的同名变量直接赋值不生效，改成用$符在value中手动赋值，升到6.2.2后，同名变量直接赋值不生效，手动给value赋值，报变量循环引用

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：
<img width="1429" alt="image" src="https://github.com/baidu/amis/assets/7578173/a9febee9-a2d6-4dd3-82b7-5ebb8b9ad464">

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...
npm
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.2.2
3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
符合预期，不允许自己引用自己
