### ISSUE TITLE
API不支持PATCH方法，只支持get/post/put/delete

### ISSUE THREAD

**Issue by WangShaoyu1** [baidu/amis#987]
API不支持PATCH方法；
当强行添加PATCH方法的时候，接口请求过程中不会带上body内容，从而导致请求失败

![image](https://user-images.githubusercontent.com/16829507/95993510-ca162e80-0e61-11eb-9924-dc2bcec3592b.png)

**Comment by 2betop** [comment]
应该是支持的，如果没有 body，检查一下 fetcher 处的逻辑

**Comment by WangShaoyu1** [comment]
真不支持PATCH，打印出来的话data 是undefined；而改用post请求的话，data是表达项中的所有数据

**Comment by 2betop** [comment]
主动配置 data 了没有？

**Comment by WangShaoyu1** [comment]
![Uploading image.png…]()

**Comment by WangShaoyu1** [comment]
![image](https://user-images.githubusercontent.com/16829507/96072712-76dec300-0ed7-11eb-8a0a-e7989cecdf68.png)

**Comment by 2betop** [comment]
这不科学啊，没写啥特殊逻辑处理。麻烦跟一下这个 https://github.com/baidu/amis/blob/master/src/utils/api.ts#L41

**Comment by WangShaoyu1** [comment]
可以了，主动添加data是可以的。不主动加就不行

**Comment by 2betop** [comment]
看来是符合预期的，关了。

**Comment by faceair** [comment]
![image](https://user-images.githubusercontent.com/3659110/125610045-3c5052e0-9251-4b29-aa0e-77576d3ed379.png)
https://github.com/baidu/amis/blob/1.2.1/src/utils/api.ts#L95
@2betop 这里为啥不再加个 `&& api.method === 'patch'` 的判断呢？
