### ISSUE TITLE
react版本安装"amis": "^6.2.2",版本，run build时报错

### ISSUE THREAD

**Issue by 1462062613** [baidu/amis#9880]
node版本v16.17.0，
npm版本：8.15.苹果电脑以上配置，
问题描述：安装amis后，可以run起来，但是npm run build时，报错
使用方式：
import { ConditionBuilder } from 'amis';
 <ConditionBuilder
        fields={formData}
        onChange={handleSearch}
      />
问题截图：
![微信图片_20240326141416](https://github.com/baidu/amis/assets/160719767/83815068-cf5b-4d1a-9cc7-5ffb9b30c9ad)

期望可以npm run build成功

**Comment by 2betop** [comment]
外围问题自行解决吧，报错是 uglify 尝试去压缩一个大于 500kb 的文件
