### ISSUE TITLE
amis-editor-demo post json自动转义成了字符串

### ISSUE THREAD

**Issue by luoxue2017** [baidu/amis#9887]
**问题描述：**
我也遇到了这个问题 amis-editor-demo 6.0.0也有这个问题，post json 自动转义了，引号的自动加了 反斜杠转义
![image](https://github.com/baidu/amis/assets/30230921/bc1661c3-0656-4655-a64e-b2d52985be01)

**重现地址：**
官方6.0的demo 可以重现，https://aisuda.github.io/amis-editor-demo/
![image](https://github.com/baidu/amis/assets/30230921/1d5c8046-5179-4eb1-a261-043d79de0027)

6.0.0的SDK是正常的，只有 amis-editor-demo是有问题的
下面是正常的（6.0.0的 sdk）
![image](https://github.com/baidu/amis/assets/30230921/3c706eea-fcbb-4871-8485-c39d70fbe91e)

看这个问题 出现在了好几个版本的 amis-editor-demo上一直没有解决 

看这个问题 出现在了好几个版本的 amis-editor-demo上一直没有解决
问题同：https://github.com/baidu/amis/issues/8607

**Comment by 2betop** [comment]
同 https://github.com/baidu/amis/issues/9318  axios 版本问题，已经修改成了 0.21.1
