### ISSUE TITLE
CRUD 组件增加 “行点击”+“变量赋值” 事件后，第一次点击正常，第二次开始报错

### ISSUE THREAD

**Issue by Ice-clean** [baidu/amis#9889]
#### 描述问题：

CRUD 组件增加 “行点击”+“变量赋值” 事件后，第一次点击正常，第二次开始报错。即使变量赋值事件什么都不干（排除了赋值影响）

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/69073935/0f0799e4-15a0-442f-8d36-d5009a6ab4fd)
![image](https://github.com/baidu/amis/assets/69073935/75a37aa4-62b8-45a8-ac0d-f6b0ac2c0319)
第一次正常，随后都报错

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
sdk

4. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
官方编辑器、以及 6.2.2 版本，都一样会报错

6. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "type": "crud",
  "id": "u:416b1ca845d9",
  "syncLocation": false,
  "columns": [
    {
      "label": "测试行",
      "name": "name",
      "id": "u:c244f8de2291"
    }
  ],
  "messages": {},
  "autoFillHeight": false,
  "bodyClassName": "",
  "className": "",
  "onEvent": {
    "rowClick": {
      "weight": 0,
      "actions": [
        {
          "componentId": "u:416b1ca845d9",
          "ignoreError": false,
          "actionType": "setValue",
          "args": {
            "value": {
              "aaa": "bbb"
            }
          }
        }
      ]
    }
  },
  "primaryField": "id",
  "data": {
    "list": [
      {
        "name": "第一行"
      },
      {
        "name": "第二行"
      },
      {
        "name": "第三行"
      }
    ]
  },
  "source": "$list",
  "perPageAvailable": [
    10
  ],
  "bulkActions": []
}
```

7. 操作步骤
1. 使用 CURD 组件（经测试 table 组件也存在）
2. 添加行点击事件类型，添加变量赋值事件
3. 点击列表行（第一次正常），随后继续点击会报错

**Comment by 2betop** [comment]
这个最新版本已经修复, 等待下个版本发布 6.3.0 https://github.com/baidu/amis/pull/9778
