### ISSUE TITLE
Combo的条件分支

### ISSUE THREAD

**Issue by en-o** [baidu/amis#9897]
#### 描述问题：

1. 新增按钮无法隐藏
1.1. 只像做分类的切换不需要新增按钮

2. 传输的数据变成了list
2.1. 无法通过json配置实现只要当前组数据对象

3. 传输数据里多了个type字段

**Comment by 2betop** [comment]
1. addable 配置成 false，并且开启 typeSwitchable 为 true
2. combo 的 multiple 模式是 数组，multiple false 模式为 对象
3. 条件依靠一个字段来区分是什么类型的节点，这个依赖条件怎么配置，如果条件做了修改可以不依赖这个 type

**Comment by en-o** [comment]
谢了

**Comment by en-o** [comment]
> 1. addable 配置成 false，并且开启 typeSwitchable 为 true
> 2. combo 的 multiple 模式是 数组，multiple false 模式为 对象
> 3. 条件依靠一个字段来区分是什么类型的节点，这个依赖条件怎么配置，如果条件做了修改可以不依赖这个 type

谢了
