### ISSUE TITLE
两个子节点怎么互相传递数据

### ISSUE THREAD

**Issue by SnailSword** [baidu/amis#99]
比如一个form中，有两个service，这两个service的数据怎么传递给对方比较好？

**Comment by 2betop** [comment]
包含关系？

**Comment by SnailSword** [comment]
> 包含关系？

包含关系和并列关系，我都想知道怎么传比较好。

比如form中有几个item依赖同一个api
本来想的是用service包一下这几个item，但是发现这样的话，这几个item的数据没法给到外层form中。
感觉service会阻止数据像上层传递？
然后只能写成：

```
const nestApi = (apiArray, main) => {
    let result = main;
    apiArray.forEach(api => {
        result = {
            type: 'service',
            api,
            body: result,
            name: api.name
        }
    });
    return result;
}

// 把所有的依赖的api都套在最外层
… 
body: [
         nestApi([nlpGetDeatilApi, initWithDataApi, nlpGetConfApi, clusterApiFromJobId], getMainForm(opt))
 ],
…
```

感觉这么写虽然实现功能了，但是太ugly了，想请教一下正常应该咋把service里面包的数据和外层的数据绑定，以便实现类似外层form提交时候，可以正常校验和提交service里面包住的部分这样的功能。

**Comment by 2betop** [comment]
你可能用错了，service 底下要用 controls  而不是用 body 包东西。

https://baidu.github.io/amis/linkpage/form2

**Comment by SnailSword** [comment]
> 你可能用错了，service 底下要用 controls 而不是用 body 包东西。

![image](https://user-images.githubusercontent.com/19756301/60712064-c4d0f100-9f48-11e9-970f-a18296cb6c46.png)

... ... 啊 原来这样啊   谢谢
