### ISSUE TITLE
在原生HTML怎么单独使用某个组件呢？

### ISSUE THREAD

**Issue by 1532332928** [baidu/amis#9907]
我使用的是JS-SDK库，在配合jQuery、HTML页面使用时，比如我想单单弹个toast的提示，或者弹个modal对话框该如何实现，我不希望先是渲染一个容器，再在这个容器里面去执行相当于的操作，如何实现！麻烦出一下相关文档

**Comment by 1532332928** [comment]
@2betop @luckyufei  @TeCHiScy  @nwind 麻烦大佬提供一下原文档

**Comment by 2betop** [comment]
https://github.com/baidu/amis/blob/master/packages/amis/src/index.tsx 

不渲染无法调用里面的组件

**Comment by 1532332928** [comment]
@2betop 如果这样那我想打开页面就使用相关的弹窗组件的时候怎么办？我看这些操作都是需要使用事件行为才能干的，就是说能不能推出一个方法能够直接调用，不需要渲染什么，或者必须渲染的话能隐藏到body里面去嘛？目前我在使用对话框就是这个干的，一点都不友好，需要先渲染一个按钮，才能提供调用方法去模拟点击这个渲染的按钮的行为事件才发起的弹窗
![image](https://github.com/baidu/amis/assets/50939596/fe11cd6a-bf5b-4934-9a50-1117e606a177)

**Comment by 2betop** [comment]
没有办法，不渲染打不开

**Comment by 1532332928** [comment]
渲染可以，但是我该怎么像执行toast提示一样去弹module对话框呢？而不是提供按钮事件去，不是提供了一些公共方法嘛，目前文档里面我就看到有toast的提供amisRequire('amis')触发

**Comment by 2betop** [comment]
目前就这些有方法，其他都不可以

amisRequire('amis').alert('提示信息', '系统提示')
const confirmed = await amisRequire('amis').confirm('确认框内容', '确认框标题')
const result = await amisRequire('amis').promt([{type: 'input-text', name: 'a', label: 'A'}], {a: '初始值'}, '确认框')
amisRequire('amis').toast.success('Toast');
amisRequire('amis').toast.error('Toast');
amisRequire('amis').toast.info('Toast');
amisRequire('amis').toast.warning('Toast');
amisRequire('amis').openContextMenus({x: 0, y: 0}, [{label: '上下文菜单', onSelect: () => {}}])

**Comment by 2betop** [comment]
打开弹窗应该可以这样

```
amisScope.doAction([{actionType: 'dialog', dialog: {title: '弹窗标题', body: []}}], {/*初始数据*/})

```

**Comment by 1532332928** [comment]
好的，希望能更新到文档里面去，还有这个确认内容支持表单组件嘛？以及确认、取消按钮事件等等，都更新到文档里面去呗
