### ISSUE TITLE
curd 批量操作 怎么初始化数据（api1）的时候，通过请求api2  去拿到一个数组id  ，然后匹配做勾选？

### ISSUE THREAD

**Issue by is-vino** [baidu/amis#9908]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
curd 批量操作 怎么初始化数据（api1）的时候，通过请求api2  去拿到一个数组id  ，然后匹配做勾选？

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
找不到如何配置请求勾选匹配项
![微信图片_20240327164246](https://github.com/baidu/amis/assets/74162391/d601b5dd-ff7b-40d1-98df-0ee9926a0a84)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...
{
  "type": "crud",
  "api": {
    "method": "get",
    "url": "http://service-dev.phonpagroup.com/apis/faas/DEVOPS/Project/Error",
    "messages": {
      "fetchSuccess": ""
    },
    "requestAdaptor": "",
    "adaptor": "var res = response.data.Data\r\nif (res) {\r\n    if (res.rows.length > 1) {\r\n        res.rows.forEach((item, index) => {\r\n            item.index = index + 1\r\n        })\r\n    }\r\n}\r\nreturn {\r\n    msg: response.data.Meaasge,\r\n    status: response.data.Code,\r\n    data: {\r\n       ...res\r\n    }\r\n}",
    "data": {
      "PageSize": "${PageSize}",
      "PageIndex": "${PageIndex}"
    }
  },
  "id": "u:1da4858ee46d",
  "syncLocation": false,
  "bulkActions": [
    {
      "label": "一键绑定",
      "actionType": "cancel",
      "api": "delete:/amis/api/sample/${ids|raw}",
      "confirmText": "",
      "id": "u:da8807d4a138",
      "onEvent": {
        "click": {
          "weight": 0,
          "actions": [
            {
              "ignoreError": false,
              "outputVar": "responseResult",
              "actionType": "ajax",
              "options": {},
              "api": {
                "url": "http://service-dev.phonpagroup.com/apis/faas/DEVOPS/Function/FunctionErrorMapping",
                "method": "post",
                "requestAdaptor": "let FunctionDetailId = api.data.FunctionDetailId\r\nif (context.rows.length == 0) {\r\nreturn\r\n}\r\nlet arr = context.rows.map(item => {\r\n    return {\r\n        ErrorCodeId: item.Id,\r\n        FunctionDetailId\r\n    }\r\n})\r\napi.body = JSON.stringify({\r\n    Mappings: arr\r\n})\r\napi.data = JSON.stringify({\r\n    Mappings:arr\r\n})\r\nreturn api\r\n",
                "adaptor": "",
                "messages": {},
                "data": {
                  "FunctionDetailId": "${Id}"
                },
                "dataType": "json"
              }
            }
          ]
        }
      }
    }
  ],
  "itemActions": [],
  "headerToolbar": [
    {
      "type": "bulk-actions",
      "align": "left"
    }
  ],
  "messages": {
    "fetchSuccess": ""
  },
  "filter": {
    "title": "查询条件",
    "body": [
      {
        "type": "input-text",
        "label": "错误ID",
        "name": "Id",
        "id": "u:802d2c088a84"
      },
      {
        "type": "input-text",
        "name": "ModuleId",
        "label": "错误枚举名称",
        "id": "u:f2dfd8c4e9c8",
        "size": "md",
        "wrapperCustomStyle": {
          ".cxd-Form-item": {
            "margin-bottom": "0"
          }
        }
      },
      {
        "type": "submit",
        "label": "搜索",
        "primary": true,
        "id": "u:ff2dacc27b52"
      },
      {
        "label": "新增",
        "type": "button",
        "actionType": "dialog",
        "level": "primary",
        "editorSetting": {
          "behavior": "create"
        },
        "dialog": {
          "type": "dialog",
          "title": "新增",
          "body": [
            {
              "type": "form",
              "api": {
                "method": "post",
                "url": "http://http://service-dev.phonpagroup.com/apis/faas/DEVOPS/Function/FunctionHead/interfaces"
              },
              "body": [
                {
                  "type": "input-text",
                  "name": "infoTitle",
                  "label": "模块中文名称",
                  "id": "u:aef134962e85",
                  "required": true,
                  "validateOnChange": false,
                  "clearable": true,
                  "placeholder": "请输入模块中文名称"
                },
                {
                  "type": "select",
                  "name": "serversUrls",
                  "label": "项目选择",
                  "id": "u:8661071cbf00",
                  "validateOnChange": false,
                  "required": true,
                  "options": [
                    {
                      "label": "选项A",
                      "value": "A"
                    },
                    {
                      "label": "选项B",
                      "value": "B"
                    }
                  ],
                  "multiple": false
                },
                {
                  "type": "select",
                  "name": "select",
                  "label": "模块类型选择",
                  "id": "u:936ac0afc9b9",
                  "options": [
                    {
                      "label": "DEV",
                      "value": "A"
                    },
                    {
                      "label": "UAT",
                      "value": "B"
                    },
                    {
                      "label": "PRO",
                      "value": "PRO"
                    }
                  ],
                  "multiple": false,
                  "value": "",
                  "validateOnChange": false,
                  "required": true,
                  "clearable": true,
                  "placeholder": "请进行环境选择"
                },
                {
                  "type": "textarea",
                  "name": "InfoDescription",
                  "label": "模块内容备注",
                  "id": "u:1324ca3d3e2f",
                  "minRows": 3,
                  "maxRows": 20,
                  "required": true,
                  "validateOnChange": false,
                  "placeholder": "请详细对此模块进行说明"
                }
              ],
              "id": "u:b32f3daa907d",
              "actions": [
                {
                  "type": "submit",
                  "label": "提交",
                  "primary": true
                }
              ],
              "feat": "Insert"
            }
          ],
          "id": "u:d7ab1b82cdba",
          "actions": [
            {
              "type": "button",
              "actionType": "cancel",
              "label": "取消",
              "id": "u:20df4e05f559"
            },
            {
              "type": "button",
              "actionType": "confirm",
              "label": "确定",
              "primary": true,
              "id": "u:e0bccd70fe05"
            }
          ],
          "showCloseButton": true,
          "closeOnOutside": true,
          "closeOnEsc": true,
          "showErrorMsg": true,
          "showLoading": true,
          "draggable": true,
          "withDefaultData": false,
          "dataMapSwitch": false
        },
        "id": "u:6d578a3ca1d4"
      }
    ],
    "id": "u:20331a8dc810",
    "feat": "Insert",
    "visible": true,
    "wrapWithPanel": false,
    "mode": "inline",
    "className": "p-l-sm",
    "debug": false
  },
  "footerToolbar": [
    {
      "type": "pagination"
    },
    {
      "type": "statistics"
    },
    {
      "type": "switch-per-page"
    }
  ],
  "perPageAvailable": [
    10
  ],
  "mode": "table",
  "columns": [
    {
      "type": "text",
      "label": "序列号",
      "id": "u:4024a59484e2",
      "placeholder": "-",
      "name": "index",
      "width": 37
    },
    {
      "type": "tpl",
      "inline": true,
      "wrapperComponent": "",
      "label": "错误ID",
      "id": "u:5d384280db14",
      "placeholder": "-",
      "name": "Id"
    },
    {
      "type": "tpl",
      "inline": true,
      "wrapperComponent": "",
      "label": "错误代码",
      "id": "u:db63ab05f5e9",
      "placeholder": "-",
      "name": "Code"
    },
    {
      "type": "tpl",
      "inline": true,
      "wrapperComponent": "",
      "label": "错误枚举名称",
      "id": "u:02152694cced",
      "placeholder": "-",
      "name": "EnumName",
      "remark": "错误枚举名称，用于生成代码"
    },
    {
      "name": "Description",
      "label": "错误详细信息",
      "type": "tpl",
      "id": "u:4ed08914e9e3",
      "placeholder": "-",
      "inline": true,
      "wrapperComponent": "",
      "remark": "可以使用{0}这类占位符号"
    },
    {
      "type": "text",
      "label": "创建人",
      "id": "u:5ac267cb3125",
      "placeholder": "-",
      "name": "Creator"
    },
    {
      "name": "CreateTime",
      "label": "创建时间",
      "type": "datetime",
      "id": "u:29e9e5b90075",
      "placeholder": "-",
      "format": "YYYY-MM-DD HH:mm:ss",
      "value": 1711369157
    },
    {
      "type": "text",
      "label": "更新人",
      "name": "Updator",
      "id": "u:76e83bbc667d",
      "placeholder": "-"
    },
    {
      "type": "text",
      "label": "更新时间",
      "id": "u:04f91fd1016f",
      "name": "UpdateTime",
      "placeholder": "-"
    },
    {
      "type": "operation",
      "label": "操作",
      "buttons": [
        {
          "label": "编辑",
          "type": "button",
          "actionType": "dialog",
          "level": "link",
          "editorSetting": {
            "behavior": "update"
          },
          "dialog": {
            "type": "dialog",
            "title": "编辑",
            "body": [
              {
                "type": "form",
                "api": {
                  "method": "get",
                  "url": "http://service-dev.phonpagroup.com/apis/faas/DEVOPS/Function/FunctionHead",
                  "requestAdaptor": "console.log(\"content\", comtext)\r\nreturn  console.log(\"api\", api)\r\n",
                  "adaptor": "",
                  "messages": {
                    "success": "修改成功",
                    "failed": "编辑失败 ，请重新提交编辑内容"
                  },
                  "data": {
                    "Id": "${Id}",
                    "InfoTitle": "${InfoTitle}",
                    "ServersUrl": "${ServersUrls}"
                  }
                },
                "body": [
                  {
                    "name": "Id",
                    "label": "Id",
                    "type": "input-text",
                    "id": "u:f24871946863",
                    "visible": false
                  },
                  {
                    "name": "InfoTitle",
                    "label": "函数中文名称",
                    "type": "input-text",
                    "id": "u:647b3eb3a50f"
                  },
                  {
                    "label": "调试地址",
                    "name": "ServersUrls",
                    "type": "input-text",
                    "id": "u:6db57fcb8877"
                  },
                  {
                    "label": "函数详情备注",
                    "name": "InfoDescription",
                    "type": "textarea",
                    "id": "u:c199dfe43ccc",
                    "minRows": 3,
                    "maxRows": 20
                  }
                ],
                "id": "u:9e1cc2d45091",
                "actions": [
                  {
                    "type": "submit",
                    "label": "提交",
                    "primary": true
                  }
                ],
                "feat": "Insert",
                "dsType": "api"
              }
            ],
            "id": "u:2aae94a4395d",
            "actions": [
              {
                "type": "button",
                "actionType": "cancel",
                "label": "取消",
                "id": "u:8c223c9a5551"
              },
              {
                "type": "button",
                "actionType": "confirm",
                "label": "保存",
                "primary": true,
                "id": "u:62a85a25609c",
                "confirmText": "修改内容会覆盖之前内容，请确认是否继续操作？？？",
                "onClick": "function click (event, props) {\r\n    console.log(event,\"event\")\r\n    console.log(props,\"props\")\r\n}",
                "hotKey": ""
              }
            ],
            "showCloseButton": true,
            "closeOnOutside": false,
            "closeOnEsc": true,
            "showErrorMsg": true,
            "showLoading": true,
            "draggable": true,
            "themeCss": {
              "dialogClassName": {
                "border": {
                  "top-border-style": "var(--borders-style-1)",
                  "left-border-style": "var(--borders-style-1)",
                  "right-border-style": "var(--borders-style-1)",
                  "bottom-border-style": "var(--borders-style-1)",
                  "top-border-color": "var(--colors-neutral-text-4)",
                  "left-border-color": "var(--colors-neutral-text-4)",
                  "right-border-color": "var(--colors-neutral-text-4)",
                  "bottom-border-color": "var(--colors-neutral-text-4)"
                },
                "box-shadow": "var(--shadows-shadow-none)"
              }
            }
          },
          "id": "u:b30f6a3aa4d6",
          "icon": "fa fa-spotify"
        },
        {
          "label": "查看",
          "type": "button",
          "actionType": "dialog",
          "level": "link",
          "editorSetting": {
            "behavior": "view"
          },
          "dialog": {
            "title": "test2",
            "body": [
              {
                "type": "crud",
                "api": {
                  "method": "get",
                  "url": "http://service-dev.phonpagroup.com/apis/faas/DEVOPS/Function/FunctionHead",
                  "messages": {
                    "fetchSuccess": ""
                  },
                  "requestAdaptor": "",
                  "adaptor": "var res = response.data.Data\r\nif (res) {\r\n    if (res.rows.length > 1) {\r\n        res.rows.forEach((item, index) => {\r\n            item.index = index + 1\r\n        })\r\n    }\r\n}\r\nreturn {\r\n    msg: response.data.Meaasge,\r\n    status: response.data.Code,\r\n    data: {\r\n       ...res\r\n    }\r\n}",
                  "data": {
                    "PageSize": "${PageSize}",
                    "PageIndex": "${PageIndex}",
                    "ModuleId": "${ModuleId}"
                  }
                },
                "id": "u:3ea5754ff398",
                "syncLocation": false,
                "bulkActions": [],
                "itemActions": [],
                "headerToolbar": [
                  {
                    "type": "bulk-actions",
                    "align": "left"
                  }
                ],
                "messages": {
                  "fetchSuccess": ""
                },
                "filter": {
                  "title": "查询条件",
                  "body": [
                    {
                      "type": "input-text",
                      "name": "ModuleId",
                      "label": "模块Id",
                      "id": "u:f2dfd8c4e9c8",
                      "size": "md",
                      "wrapperCustomStyle": {
                        ".cxd-Form-item": {
                          "margin-bottom": "0"
                        }
                      }
                    },
                    {
                      "type": "submit",
                      "label": "搜索",
                      "primary": true,
                      "id": "u:ff2dacc27b52"
                    },
                    {
                      "label": "新增",
                      "type": "button",
                      "onClick": "console.log(event,props )",
                      "actionType": "dialog",
                      "level": "primary",
                      "editorSetting": {
                        "behavior": "create"
                      },
                      "dialog": {
                        "type": "dialog",
                        "title": "新增",
                        "body": [
                          {
                            "type": "form",
                            "api": {
                              "method": "post",
                              "url": "http://http://service-dev.phonpagroup.com/apis/faas/DEVOPS/Function/FunctionHead/interfaces"
                            },
                            "body": [
                              {
                                "type": "input-text",
                                "name": "OpenapiVersion",
                                "label": "版本",
                                "id": "u:525891900551",
                                "validateOnChange": false,
                                "required": true,
                                "value": "3.1.0"
                              },
                              {
                                "type": "input-text",
                                "name": "ModuleId",
                                "label": "模块ID",
                                "id": "u:6fef7a936003",
                                "required": true,
                                "validateOnChange": false,
                                "hidden": false
                              },
                              {
                                "type": "input-text",
                                "name": "InfoTitle",
                                "label": "中文名称",
                                "id": "u:16bb0f88bd1e",
                                "required": true
                              },
                              {
                                "type": "input-text",
                                "label": "函数英文名称",
                                "name": "Name",
                                "id": "u:aef134962e85",
                                "required": true,
                                "validateOnChange": false,
                                "clearable": true
                              },
                              {
                                "type": "input-array",
                                "label": "调试地址集合",
                                "name": "ServersUrls",
                                "id": "u:402da020a01e",
                                "mode": "horizontal",
                                "value": [],
                                "scaffold": "",
                                "inline": true,
                                "items": {
                                  "type": "input-text",
                                  "clearable": true,
                                  "size": "lg"
                                },
                                "required": true
                              },
                              {
                                "type": "input-array",
                                "label": "允许跨域集合",
                                "name": "CrosDomains",
                                "id": "u:402da020a01e",
                                "required": true,
                                "mode": "horizontal",
                                "value": [],
                                "scaffold": "",
                                "inline": true,
                                "items": {
                                  "type": "input-text",
                                  "clearable": true,
                                  "size": "lg"
                                }
                              },
                              {
                                "type": "textarea",
                                "label": "函数详情备注",
                                "name": "InfoDescription",
                                "id": "u:1324ca3d3e2f",
                                "minRows": 3,
                                "maxRows": 20,
                                "required": true,
                                "validateOnChange": true
                              }
                            ],
                            "id": "u:b32f3daa907d",
                            "actions": [
                              {
                                "type": "submit",
                                "label": "提交",
                                "primary": true
                              }
                            ],
                            "feat": "Insert"
                          }
                        ],
                        "id": "u:d7ab1b82cdba",
                        "actions": [
                          {
                            "type": "button",
                            "actionType": "cancel",
                            "label": "取消",
                            "id": "u:20df4e05f559"
                          },
                          {
                            "type": "button",
                            "actionType": "cancel",
                            "label": "确定",
                            "primary": true,
                            "id": "u:e0bccd70fe05",
                            "onEvent": {
                              "click": {
                                "weight": 0,
                                "actions": [
                                  {
                                    "ignoreError": false,
                                    "outputVar": "responseResult",
                                    "actionType": "ajax",
                                    "options": {},
                                    "api": {
                                      "url": "http://service-dev.phonpagroup.com/apis/faas/DEVOPS/Function/FunctionHead",
                                      "method": "post",
                                      "requestAdaptor": "api.body = JSON.stringify(api.body)\r\napi.data = JSON.stringify(api.data)\r\nreturn api",
                                      "adaptor": "",
                                      "messages": {},
                                      "dataType": "json",
                                      "data": {
                                        "CrosDomains": "${CrosDomains}",
                                        "InfoDescription": "${InfoDescription}",
                                        "ModuleId": "${ModuleId}",
                                        "ServersUrls": "${ServersUrls}",
                                        "Name": "${Name}",
                                        "OpenapiVersion": "${OpenapiVersion}",
                                        "InfoTitle": "${InfoTitle}"
                                      }
                                    }
                                  }
                                ]
                              }
                            }
                          }
                        ],
                        "showCloseButton": true,
                        "closeOnOutside": true,
                        "closeOnEsc": true,
                        "showErrorMsg": true,
                        "showLoading": true,
                        "draggable": true,
                        "onClick": "console.log(event.data)"
                      },
                      "id": "u:6d578a3ca1d4",
                      "onEvent": {
                        "click": {
                          "weight": 0,
                          "actions": [],
                          "debounce": {
                            "wait": 100
                          }
                        }
                      }
                    }
                  ],
                  "id": "u:20331a8dc810",
                  "feat": "Insert",
                  "visible": true,
                  "wrapWithPanel": false,
                  "mode": "inline",
                  "className": "p-l-sm",
                  "debug": false,
                  "autoFocus": false
                },
                "footerToolbar": [
                  {
                    "type": "pagination"
                  },
                  {
                    "type": "statistics"
                  },
                  {
                    "type": "switch-per-page"
                  }
                ],
                "perPageAvailable": [
                  10
                ],
                "mode": "table",
                "columns": [
                  {
                    "name": "index",
                    "label": "序列号",
                    "type": "text",
                    "id": "u:4024a59484e2",
                    "placeholder": "-",
                    "width": 37
                  },
                  {
                    "name": "Id",
                    "label": "函数ID",
                    "type": "text",
                    "id": "u:5ac267cb3125",
                    "placeholder": "-"
                  },
                  {
                    "name": "InfoTitle",
                    "label": "函数名称",
                    "type": "text",
                    "id": "u:76e83bbc667d",
                    "placeholder": "-"
                  },
                  {
                    "type": "text",
                    "label": "详细备注",
                    "name": "InfoDescription",
                    "id": "u:04f91fd1016f",
                    "placeholder": "-"
                  },
                  {
                    "type": "text",
                    "label": "模块ID",
                    "name": "Base_CF_Moudle_ID",
                    "id": "u:d3ae33ec9f8f",
                    "placeholder": "-"
                  },
                  {
                    "type": "text",
                    "label": "创建人",
                    "name": "Creator",
                    "id": "u:6c58ead27eaa",
                    "placeholder": "-"
                  },
                  {
                    "type": "text",
                    "label": "更新人",
                    "name": "Updator",
                    "id": "u:8eb766503c63",
                    "placeholder": "-"
                  },
                  {
                    "type": "text",
                    "label": "函数URL",
                    "name": "ServersUrls",
                    "id": "u:329336f29c04",
                    "placeholder": "-"
                  },
                  {
                    "type": "operation",
                    "label": "操作",
                    "buttons": [
                      {
                        "label": "编辑",
                        "type": "button",
                        "actionType": "dialog",
                        "level": "link",
                        "editorSetting": {
                          "behavior": "update"
                        },
                        "dialog": {
                          "type": "dialog",
                          "title": "编辑",
                          "body": [
                            {
                              "type": "form",
                              "api": {
                                "method": "get",
                                "url": "http://service-dev.phonpagroup.com/apis/faas/DEVOPS/Function/FunctionHead",
                                "requestAdaptor": "console.log(\"content\", comtext)\r\nreturn  console.log(\"api\", api)\r\n",
                                "adaptor": "",
                                "messages": {
                                  "success": "修改成功",
                                  "failed": "编辑失败 ，请重新提交编辑内容"
                                },
                                "data": {
                                  "Id": "${Id}",
                                  "InfoTitle": "${InfoTitle}",
                                  "ServersUrl": "${ServersUrls}"
                                }
                              },
                              "body": [
                                {
                                  "name": "Id",
                                  "label": "Id",
                                  "type": "input-text",
                                  "id": "u:f24871946863",
                                  "visible": false
                                },
                                {
                                  "name": "InfoTitle",
                                  "label": "函数中文名称",
                                  "type": "input-text",
                                  "id": "u:647b3eb3a50f"
                                },
                                {
                                  "label": "调试地址",
                                  "name": "ServersUrls",
                                  "type": "input-text",
                                  "id": "u:6db57fcb8877"
                                },
                                {
                                  "label": "函数详情备注",
                                  "name": "InfoDescription",
                                  "type": "textarea",
                                  "id": "u:c199dfe43ccc",
                                  "minRows": 3,
                                  "maxRows": 20
                                }
                              ],
                              "id": "u:9e1cc2d45091",
                              "actions": [
                                {
                                  "type": "submit",
                                  "label": "提交",
                                  "primary": true
                                }
                              ],
                              "feat": "Insert",
                              "dsType": "api"
                            }
                          ],
                          "id": "u:2aae94a4395d",
                          "actions": [
                            {
                              "type": "button",
                              "actionType": "cancel",
                              "label": "取消",
                              "id": "u:8c223c9a5551"
                            },
                            {
                              "type": "button",
                              "actionType": "confirm",
                              "label": "保存",
                              "primary": true,
                              "id": "u:62a85a25609c",
                              "confirmText": "修改内容会覆盖之前内容，请确认是否继续操作？？？",
                              "onClick": "function click (event, props) {\r\n    console.log(event,\"event\")\r\n    console.log(props,\"props\")\r\n}",
                              "hotKey": ""
                            }
                          ],
                          "showCloseButton": true,
                          "closeOnOutside": false,
                          "closeOnEsc": true,
                          "showErrorMsg": true,
                          "showLoading": true,
                          "draggable": true,
                          "themeCss": {
                            "dialogClassName": {
                              "border": {
                                "top-border-style": "var(--borders-style-1)",
                                "left-border-style": "var(--borders-style-1)",
                                "right-border-style": "var(--borders-style-1)",
                                "bottom-border-style": "var(--borders-style-1)",
                                "top-border-color": "var(--colors-neutral-text-4)",
                                "left-border-color": "var(--colors-neutral-text-4)",
                                "right-border-color": "var(--colors-neutral-text-4)",
                                "bottom-border-color": "var(--colors-neutral-text-4)"
                              },
                              "box-shadow": "var(--shadows-shadow-none)"
                            }
                          },
                          "bodyClassName": "dialog-scrollable"
                        },
                        "id": "u:b30f6a3aa4d6",
                        "icon": "fa fa-spotify"
                      },
                      {
                        "label": "查看",
                        "type": "button",
                        "actionType": "dialog",
                        "level": "link",
                        "editorSetting": {
                          "behavior": "view"
                        },
                        "dialog": {
                          "title": "查看详情",
                          "body": [
                            {
                              "type": "form",
                              "api": "xxx/update",
                              "body": [
                                {
                                  "name": "Id",
                                  "label": "Id",
                                  "type": "input-text",
                                  "id": "u:ca84517a77ed",
                                  "hidden": true
                                },
                                {
                                  "name": "InfoTitle",
                                  "label": "函数中文名称",
                                  "type": "static",
                                  "id": "u:f624b8e30a71",
                                  "quickEdit": false,
                                  "popOver": false,
                                  "copyable": false
                                },
                                {
                                  "label": "函数英文名称",
                                  "name": "Name",
                                  "type": "static",
                                  "id": "u:e95bdb9346db",
                                  "quickEdit": false,
                                  "popOver": false,
                                  "copyable": false
                                },
                                {
                                  "label": "调试地址",
                                  "name": "ServersUrls",
                                  "type": "static",
                                  "id": "u:6e657b230393",
                                  "quickEdit": false,
                                  "popOver": false,
                                  "copyable": false
                                },
                                {
                                  "label": "函数详情备注",
                                  "name": "InfoDescription",
                                  "type": "static",
                                  "id": "u:8dc12a54d155",
                                  "quickEdit": false,
                                  "popOver": false,
                                  "copyable": false
                                }
                              ],
                              "id": "u:00f47ba74c36",
                              "actions": [
                                {
                                  "type": "submit",
                                  "label": "提交",
                                  "primary": true
                                }
                              ],
                              "feat": "Insert"
                            }
                          ],
                          "type": "dialog",
                          "id": "u:910aefa483e4",
                          "actions": [],
                          "showCloseButton": true,
                          "closeOnOutside": false,
                          "closeOnEsc": true,
                          "showErrorMsg": true,
                          "showLoading": true,
                          "draggable": false
                        },
                        "id": "u:5c23a5127d14",
                        "icon": "fa fa-snapchat-ghost"
                      },
                      {
                        "type": "button",
                        "label": "删除",
                        "actionType": "ajax",
                        "level": "link",
                        "className": "text-danger",
                        "confirmText": "确定要删除？",
                        "api": {
                          "method": "post",
                          "url": "http://localhost:3000/api/interfaces"
                        },
                        "editorSetting": {
                          "behavior": "delete"
                        },
                        "id": "u:d0e1cb7ced2b",
                        "onEvent": {
                          "click": {
                            "weight": 0,
                            "actions": []
                          }
                        }
                      }
                    ],
                    "id": "u:7407092c1ace"
                  }
                ],
                "initFetch": true,
                "loadDataOnce": false,
                "matchFunc": "",
                "pageField": "PageIndex",
                "perPageField": "PageSize"
              }
            ],
            "type": "page",
            "id": "u:80c2a2fe6d6b",
            "showCloseButton": true,
            "closeOnOutside": false,
            "closeOnEsc": false,
            "showErrorMsg": true,
            "showLoading": true,
            "draggable": false,
            "asideResizor": false,
            "pullRefresh": {
              "disabled": true
            },
            "regions": [
              "body"
            ]
          },
          "id": "u:5c23a5127d14",
          "icon": "fa fa-snapchat-ghost"
        },
        {
          "type": "button",
          "label": "删除",
          "actionType": "ajax",
          "level": "link",
          "className": "text-danger",
          "confirmText": "确定要删除？",
          "api": {
            "method": "post",
            "url": "http://localhost:3000/api/interfaces"
          },
          "editorSetting": {
            "behavior": "delete"
          },
          "id": "u:d0e1cb7ced2b",
          "onEvent": {
            "click": {
              "weight": 0,
              "actions": []
            }
          }
        }
      ],
      "id": "u:bb9590e38de2"
    }
  ],
  "initFetch": true,
  "loadDataOnce": false,
  "matchFunc": "",
  "pageField": "PageIndex",
  "perPageField": "PageSize",
  "title": "错误信息维护"
}
```
code here...
```

**Comment by 2betop** [comment]
目前不支持初始勾选
