### ISSUE TITLE
[Form 表单 可新增行表格 ] 体验有点异常

### ISSUE THREAD

**Issue by CareyToboo** [baidu/amis#991]
#### 描述问题：

体验问题：

1. 新增一条后，并输入内容，点击保存，会继续停留在 “编辑状态”。---（只能进行 “再+一条” 或者 “编辑当前行” 操作）无法正常恢复到展示状态，只有点击新增一行，再点击取消，才能恢复展示状态。

> 预期结果，点击**保存**按钮，能直接回到展示状态

2. 点击编辑一条时---取消操作异常
    a. 如果不变更输入框内容呢，无法取消编辑
    b. 如果变更输入框内容，再点取消，则会一直停留在编辑状态，无法取消。

> 预期结果，点击**取消**按钮，能直接放弃所有更改，回到展示状态

3. 点击编辑一条时----保存操作异常
     a. 如果不变更输入框内容呢，需要点击两次保存。才能恢复展示状态。
     b. 如果变更输入框内容，点击保存，则会和第一条体验问题类似。---无法正常恢复到展示状态

> 预期结果，点击**保存**按钮，能直接回到展示状态

#### 截图或视频：
不属于界面UI问题，不好截图。但是手动按照文档 Demo 操作一下应该很容易复现。[Form可新增行表格文档地址](https://baidu.github.io/amis/docs/components/form/table#%E5%8F%AF%E6%96%B0%E5%A2%9E%E8%A1%8C)

**Comment by 2betop** [comment]
确实存在问题，是上次优化 Table 性能带来的新问题。主要问题是没有及时刷新 Table 导致的。刚提交代码，下次版本会带上。

**Comment by 2betop** [comment]
先关了，有问题再开
