### ISSUE TITLE
curd 拉取 method 为get接口 url 如果是模板生成，筛选时无法在 url 上拼接筛选参数

### ISSUE THREAD

**Issue by dingwen1** [baidu/amis#9914]
#### 描述问题：

curd 拉取 method 为get接口 url 如果是模板生成，筛选时无法在 url 上拼接筛选参数

#### 如何复现（请务必完整填写下面内容）：

1.  curd 拉取接口是 get，并且 url 上拼接了参数，例如：${baseUrl}/arch/amis_api/config_get
2. 然后通过 curd 的筛选搜索，发现最终链接上没有筛选参数
3. amis 版本是什么：6.2.2

**Comment by 2betop** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#query-%E5%8F%82%E6%95%B0 

数据源接口地址可以通过变量实现动态拼接，例如： /api/mock2/sample/${id}，但需要注意的是接口地址拼接变量后，amis 就不会自动追加默认参数了，例如：分页参数、查询参数等，如需追加，可以自行拼接，例如： /api/mock2/sample/${id}?page=${page}&perPage=${perPage}
