### ISSUE TITLE
开发环境中如何解决使用相对路径启动失败！

### ISSUE THREAD

**Issue by is-vino** [baidu/amis#9918]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
因为我目前的是微服务，我希望用amis作为子应用，同时通过相对路径引用静态资源

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
但是一旦设置了相对路径    . /   官方的例子就启动不了  ，请问如何解决
#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

![微信图片_20240329095140](https://github.com/baidu/amis/assets/74162391/6b7849af-e48e-4f53-a837-cdcff00c74e4)

```
code here...
```

**Comment by 2betop** [comment]
工程编译相关问题，请自行解决
