### ISSUE TITLE
目前通过amis SDK的应式在非react项目中使用，请问如何设置请求 withCredentials  ？？

### ISSUE THREAD

**Issue by is-vino** [baidu/amis#9926]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
目前通过amis SDK的应式在非react项目中使用，请问如何设置请求 withCredentials  ？？

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
![微信图片_20240329152105](https://github.com/baidu/amis/assets/74162391/83e56c4f-77d6-450c-a650-a25c4c4b543d)

code here...
```

**Comment by 2betop** [comment]
默认是开的？要关？

**Comment by is-vino** [comment]
是的，我希望能够按需设置，该如何配置？还有就是我还在统一设置一下请求的headers添加一些东西又如何设置呢？谢谢

**Comment by is-vino** [comment]
> 默认是开的。要关吗？

是的，我希望能够自由设置withCredentials，怎么配置？还有我想统一设置一下请求的headers添加一些东西又如何设置呢？谢谢

**Comment by 2betop** [comment]
目前没有专门的 withCredentials 配置，但是整个发送逻辑可以自定义，通过 env 下发 fetcher

**Comment by is-vino** [comment]
> 目前没有专门的 withCredentials 配置，但是整个发送逻辑可以自定义，通过 env 下发 fetcher

那么headers 也是一样 在fetcher 设置？

**Comment by is-vino** [comment]
> 都自己写 fetcher 了，想不发送任何 header 都行

ok，谢谢
