### ISSUE TITLE
react18+vite中该如何集成amis-editor？求教

### ISSUE THREAD

**Issue by Yyx1999-boss** [baidu/amis#9928]
我的项目用的是react18+vite 想要集成amis-editor该如何集成？ 官网的方式只安装amis-editor不行 缺少其他库 安装了其他的库还会报错 想请问下该如何操作

**Comment by 2betop** [comment]
参考 amis-editor-demo

**Comment by 2betop** [comment]
https://github.com/aisuda/amis-admin/tree/react 这个分支就是 vite 的

**Comment by 2betop** [comment]
抱歉 amis 不处理这类问题，就 monaco-editor 集成麻烦的，要用  `vite-plugin-monaco-editor` 插件，其他就是标准用法

**Comment by Yyx1999-boss** [comment]
> 抱歉 amis 不处理这类问题，就 monaco-editor 集成麻烦的，要用 `vite-plugin-monaco-editor` 插件，其他就是标准用法

您好，请问推荐的react版本和node版本是多少

**Comment by youngZhu123** [comment]
官方还是给出react18+vite的各依赖版本吧，或者出一个demo，现在按照文档集成问题是真的多
