### ISSUE TITLE
CRUD如何能统一CRU的表单

### ISSUE THREAD

**Issue by zbl400** [baidu/amis#9935]
#### 实现场景：
一个普通的CRUD场景的 新增/修改/详情 表单，几乎是一摸一样的，有什么办法可以使用一个 详情表单 而不是定义 3 个详情表单?

#### 存在的问题：
目前按照示例代码， 针对  新增/修改/详情 按钮定义各自的弹窗表单， 是可以达到目的。但是一旦有修改，就必须要修改 3个 弹窗的代码，不是很方便。

虽然可以改为引用既存弹窗，但是表单中的api限制了只能让表单只有一种使用场景。

#### 当前方案：
即crud示例

```
code here...
```

**Comment by skj198568** [comment]
可以用公共配置，来写表单内容。
我这边是用后端语言，多个小json拼接一个大json配置。

**Comment by 2betop** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/definitions

**Comment by 2betop** [comment]
新版本编辑器已经可以多个动作弹出同一个弹窗了

**Comment by zbl400** [comment]
> https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/definitions

是，我也使用过definitions ， 对于定义一个表单，被 增改查  3个按钮调用是没有问题。

**Comment by 2betop** [comment]
{
 "$ref": "xxx",
 "initApi": "xxxx" // 引用后可以覆盖部分属性
}
