### ISSUE TITLE
amis编辑界面，相关功能如 接口配置 能不能做到配置显隐性？

### ISSUE THREAD

**Issue by is-vino** [baidu/amis#9940]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...
我打算使用amis给不懂代码的人群进行页面搭建功能，但是我不希望他们能够编辑配置一些高级功能，所有希望这类人群打开的时候，我把这块内容给影藏起来，但是同时希望管理员才能去处理编辑，所有能否配置，怎么配置？  再者 如下图二，字段能否通过接口返回，通过下拉选择？

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...
咱没有找到解决方案
![a](https://github.com/baidu/amis/assets/74162391/af73e59b-db82-46d0-85c4-96e3328f1176)
![微信图片_20240401095817](https://github.com/baidu/amis/assets/74162391/8b0f5411-9987-4f1d-a0c5-51f26f354db2)

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by is-vino** [comment]
help me

**Comment by 2betop** [comment]
不支持，可以基于源码二开
