### ISSUE TITLE
type为json的时候value支持 JavaScript 模板引擎

### ISSUE THREAD

**Issue by WangShaoyu1** [baidu/amis#995]
1、
{
            type: 'json',
            levelExpand: 3,
            value: '<% data %>',
},
会报错：error:"Unexpected token < in JSON at position 0"
2、
 {
            type: 'tpl',
            tpl: '<%= JSON.stringify(data) %>',
            label: 'tpl模板内容：',
 },
可以显示所有内容，希望支持1中这种类型情况

**Comment by nwind** [comment]
目的是啥来着？如果原始数据是 string 的话，目前倒是会自动 parse，不需要 <%= JSON.parse(data) %>
