### ISSUE TITLE
新版本请求适配器没有data字段了吗？和文档里说的不符

### ISSUE THREAD

**Issue by Icodezhan** [baidu/amis#9952]
#### 描述问题：
新版本请求适配器没有data字段了，和文档里说的不符。那我应该如何修改发送请求数据？
我试着在api.body、api.context、api.query加上我要的请求数据，但是都不行
![2024-04-02_104607](https://github.com/baidu/amis/assets/45064164/d97b23a6-8086-459e-976f-4a6d8133abef)
![2024-04-02_104621](https://github.com/baidu/amis/assets/45064164/32485b8b-4e69-433d-90e0-d02a3206d2e8)
![2024-04-02_104650](https://github.com/baidu/amis/assets/45064164/8d8b2a14-e9b9-4428-b424-8082d638b8a3)

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by Icodezhan** [comment]
@2betop

**Comment by 2betop** [comment]
get 请求没有 body

**Comment by Icodezhan** [comment]
> get 请求没有 data

那get请求要修改发送参数，应该怎么处理？

**Comment by 2betop** [comment]
改 api.url
