### ISSUE TITLE
crud为啥不支持bordered属性

### ISSUE THREAD

**Issue by warning5** [baidu/amis#9953]
#### 实现场景：
请简单描述你想要实现的原始场景，例如：我想要实现xxx的功能...

#### 存在的问题：
请简单描述你现在遇到的不符合预期的问题...

#### 当前方案：
请粘贴你当前方案的完整 amis schema 代码...

```
code here...
```

**Comment by qkiroc** [comment]
![image](https://github.com/baidu/amis/assets/30946345/a96adb88-3ae9-402b-ab65-87a5bb0a60e2)
可以通过style来添加
