### ISSUE TITLE
发送请求返回status不为0，msg不显示

### ISSUE THREAD

**Issue by zhushibo** [baidu/amis#9958]
#### 描述问题：
当我发送请求时，返回status非0，但是提示是空，并没有抓msg中的值

#### 截图或视频：
走到了这个地方
<img width="843" alt="image" src="https://github.com/baidu/amis/assets/26269311/5979b439-9290-4c08-a143-f2806eb927d4">

返回数据
<img width="204" alt="image" src="https://github.com/baidu/amis/assets/26269311/ca39f77b-aa7e-4df4-909d-5c807a8b7366">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.3.0

4. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

5. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by 2betop** [comment]
是不是自己写了适配器？

**Comment by zhushibo** [comment]
> 是不是自己写了适配器？
写了返回适配器，没有修改status和msg的数据，理论上不会有问题？
<img width="577" alt="image" src="https://github.com/baidu/amis/assets/26269311/edb8ba7d-78c6-4fab-a87f-a94dcd291d77">

**Comment by 2betop** [comment]
你这是 fetcher 的覆写，你说的返回适配器是指啥？

**Comment by zhushibo** [comment]
> 你这是 fetcher 的覆写，你说的返回适配器是指啥？
我说的是你们提供的attachmentAdpator（代码倒数第二行），之前下载文件出错，然后加上的

**Comment by zhushibo** [comment]
> api 上没有配置什么返回适配器吗？没有的话不符合预期，但是这个功能一直没动过，我们这边没有出现这个情况

确定没有返回适配器，而且我在其它页面是正常的，弹窗代码如下
`{
  "type": "dialog",
  "title": "修改手机号",
  "body": [
    {
      "type": "input-text",
      "label": "原手机号",
      "name": "tr.phone",
      "id": "u:e1f8d443f1de",
      "size": "md",
      "static": false,
      "readOnly": true
    },
    {
      "type": "input-text",
      "label": "新手机号",
      "name": "newPhone",
      "id": "u:bba0b0b46123",
      "size": "md",
      "required": true,
      "validations": {
        "maxLength": 20,
        "minLength": 10
      },
      "showCounter": false,
      "maxLength": 20
    }
  ],
  "showCloseButton": true,
  "showErrorMsg": true,
  "showLoading": true,
  "className": "app-popover",
  "id": "u:32a539e71c4c",
  "closeOnEsc": false,
  "onEvent": {
    "confirm": {
      "weight": 0,
      "actions": [
        {
          "outputVar": "responseResult",
          "actionType": "ajax",
          "api": {
            "url": "xxxxx/changePhone",
            "method": "post",
            "requestAdaptor": "",
            "adaptor": "",
            "messages": {
              "success": "保存成功",
              "failed": ""
            },
            "dataType": "json",
            "data": {
              "trId": "${tr.id}",
              "phone": "${newPhone}"
            }
          },
          "options": {
          }
        },
        {
          "componentId": "u:b39a9bca17a5",
          "actionType": "reload",
          "dataMergeMode": "merge"
        }
      ]
    }
  },
  "actions": [
    {
      "type": "button",
      "actionType": "cancel",
      "label": "取消",
      "id": "u:263b1e615694"
    },
    {
      "type": "button",
      "actionType": "confirm",
      "label": "确定",
      "primary": true,
      "id": "u:916c981634be"
    }
  ],
  "closeOnOutside": false,
  "draggable": false
}`

我拿到amis playground中也可以复现
![Uploading image.png…]()

**Comment by zhushibo** [comment]
> api 上没有配置什么返回适配器吗？没有的话不符合预期，但是这个功能一直没动过，我们这边没有出现这个情况

越来越迷了，为什这个可以显示，还没有status
![image](https://github.com/baidu/amis/assets/26269311/dbf868bc-1f65-43da-bc52-e3650ee20ff4)

**Comment by 2betop** [comment]
因为动作里面自定义了个 messages.failed  干掉就好了

```
{
  "type": "page",
  "title": "表单页面",
  "body": [
    {
      "type": "button",
      "label": "open",
      "actionType": "dialog",
      "dialog": {
        "type": "dialog",
        "title": "修改手机号",
        "body": [
          {
            "type": "input-text",
            "label": "原手机号",
            "name": "tr.phone",
            "id": "u:e1f8d443f1de",
            "size": "md",
            "static": false,
            "readOnly": true
          },
          {
            "type": "input-text",
            "label": "新手机号",
            "name": "newPhone",
            "id": "u:bba0b0b46123",
            "size": "md",
            "required": true,
            "validations": {
              "maxLength": 20,
              "minLength": 10
            },
            "showCounter": false,
            "maxLength": 20
          }
        ],
        "showCloseButton": true,
        "showErrorMsg": true,
        "showLoading": true,
        "className": "app-popover",
        "id": "u:32a539e71c4c",
        "closeOnEsc": false,
        "onEvent": {
          "confirm": {
            "weight": 0,
            "actions": [
              {
                "outputVar": "responseResult",
                "actionType": "ajax",
                "api": {
                  "url": "xxxxx/changePhone",
                  "method": "post",
                  "requestAdaptor": "",
                  "adaptor": "",
                  "messages": {
                    "success": "保存成功"
                  },
                  "dataType": "json",
                  "data": {
                    "trId": "${tr.id}",
                    "phone": "${newPhone}"
                  },
                  "mockResponse": {
                    "status": 200,
                    "data": {
                      "data": -1,
                      "msg": "账号已融合",
                      "skyWalkingDynamicField": null,
                      "status": 1,
                      "tid": "b1111111",
                      "time": 17120434343
                    }
                  }
                },
                "options": {}
              },
              {
                "componentId": "u:b39a9bca17a5",
                "actionType": "reload",
                "dataMergeMode": "merge"
              }
            ]
          }
        },
        "actions": [
          {
            "type": "button",
            "actionType": "cancel",
            "label": "取消",
            "id": "u:263b1e615694"
          },
          {
            "type": "button",
            "actionType": "confirm",
            "label": "确定",
            "primary": true,
            "id": "u:916c981634be"
          }
        ],
        "closeOnOutside": false,
        "draggable": false
      }
    }
  ]
}
```

**Comment by zhushibo** [comment]
万万没想道😂，这个是后台配的，估计是之前写了错误返回，后来把错误返回文案删除了。
但是删除之后，这个属性就变成了failed: ""，于是乎这里一直提示空。
这里后面是不是得兼容下更好， 用 message.failed || response.msg

**Comment by 2betop** [comment]
最早是后端返回的 message 优先的，但是有用户说即便是这样，也要不展示 message，所以事件动作里面的  message 的优先级提高了。
