### ISSUE TITLE
Each 循环渲染器 的value只能显示赋值，不能取数据链中的值么？

### ISSUE THREAD

**Issue by WangShaoyu1** [baidu/amis#996]
#### 描述问题：
请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：
可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

3. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by RickCole21** [comment]
可以在form或table中，用name获取数据域中的值

https://baidu.github.io/amis/docs/components/each#%E7%94%A8%E4%BD%9C-field-%E6%97%B6
