### ISSUE TITLE
什么时候能支持下chat这种组件，可以设置app key 。

### ISSUE THREAD

**Issue by lengqingfeng** [baidu/amis#9962]
#### 是否关联于某个问题吗：
什么时候能支持下chat这种组件，可以设置app key 。集成AI能力

**Comment by CheshireJCat** [comment]
chat组件使用率低，差异性高，且一般用到chat场景的都需要独立UE设计，无法满足通用需求，不适宜作为原子组件。
暂时没有这方面安排，如果您有兴趣可以支持，可以提交一下代码，感谢。
