### ISSUE TITLE
Combo 嵌套 自定义 deleteBtn 不显示 Bug

### ISSUE THREAD

**Issue by Ladtor** [baidu/amis#9975]
#### 描述问题：

套两层Combo时，使用自定义删除按钮 不生效，且原本的删除x号 也没有了

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/19227210/e67a04ea-8897-4e55-9122-ea79f6b7b879)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.3.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
  "body": [
    {
      "body": [
        {
          "items": [
            {
              "deleteBtn": {
                "label": "删除",
                "type": "button"
              },
              "items": [
                {
                  "label": "中奖人数",
                  "min": 1,
                  "minimum": 1,
                  "name": "winnersCount",
                  "required": true,
                  "type": "input-number"
                },
                {
                  "label": "奖励内容",
                  "name": "rewardContent",
                  "required": true,
                  "type": "input-text"
                }
              ],
              "label": "部分抽取规则配置",
              "multiple": true,
              "name": "partConfig",
              "required": true,
              "type": "combo"
            }
          ],
          "label": "抽奖规则配置",
          "multiLine": true,
          "name": "lottery",
          "type": "combo"
        }
      ],
      "type": "form"
    }
  ],
  "type": "service"
}
```

4. 操作步骤
a. Form + Combo + Combo + deleteBtn

**Comment by CheshireJCat** [comment]
写错位置了，我猜你是要这样，deleteBtn 属性应该和 第一层 combo 同级
```
{
  "body": [
    {
      "body": [
        {
          "items": [],
          "label": "抽奖规则配置",
          "multiLine": true,
          "name": "lottery",
          "type": "combo",
          "deleteBtn": {
            "label": "删除",
            "type": "button"
          }
        }
      ],
      "type": "form"
    }
  ],
  "type": "service"
}
```

**Comment by Ladtor** [comment]
> 写错位置了，我猜你是要这样，deleteBtn 属性应该和 第一层 combo 同级 ![image](https://private-user-images.githubusercontent.com/16409259/322480410-0fed5e84-5a73-45d0-b7c3-a5a7d68d91fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzk0NzksIm5iZiI6MTcxMzMzOTE3OSwicGF0aCI6Ii8xNjQwOTI1OS8zMjI0ODA0MTAtMGZlZDVlODQtNWE3My00NWQwLWI3YzMtYTVhN2Q2OGQ5MWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA3MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZWYwMTA5NTViYmNjZWIzNzgyNDhmN2E5OGJiNGFmYzcyMGQwMzdjODEwNTY3Zjk1Zjk4MDgwNmY4YmU2MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WOcGDzgf3w9ZPInQjFj1IGwcg8yNMEDEHJLepVckLzw)
> 
> ```
> {
>   "body": [
>     {
>       "body": [
>         {
>           "items": [],
>           "label": "抽奖规则配置",
>           "multiLine": true,
>           "name": "lottery",
>           "type": "combo",
>           "deleteBtn": {
>             "label": "删除",
>             "type": "button"
>           }
>         }
>       ],
>       "type": "form"
>     }
>   ],
>   "type": "service"
> }
> ```

@CheshireJCat 我的例子没错，这个bug只有套两层combo可以复现，不仅deleteBtn没出现，原本的x符号 也没了

**Comment by CheshireJCat** [comment]
![image](https://github.com/baidu/amis/assets/16409259/a4c25a8c-cad0-42e8-8a29-594c479be207)
发现了：是你外层的属性名写错了，写对就正常了，ru'd如下
![image](https://github.com/baidu/amis/assets/16409259/b56010d9-685a-490d-b8ae-0e83de786dd6)
