### ISSUE TITLE
react安装amis6.2.2，使用ConditionBuilder组件，"type"= "number",时图标不兼容火狐

### ISSUE THREAD

**Issue by 1462062613** [baidu/amis#9978]
实现场景：
想要实现条件组合功能：代码如下：
  {
    "label": "请求执行时间（秒）",
    "type": "number",
    "name": "time",
    "required": 1,
    "operators": [
        "greater_or_equal",
        "greater",
        "less_or_equal",
        "less"
    ],
    "suffix": "秒",
  },

存在问题：火狐浏览器的图表出现问题：

![image](https://github.com/baidu/amis/assets/160719767/9379118d-e223-435c-8ea9-d7539f0050bd)
![微信图片_20240408174810](https://github.com/baidu/amis/assets/160719767/38346aac-d1f1-42a6-b9d3-42017be57631)
![image](https://github.com/baidu/amis/assets/160719767/fdfaf99a-e96d-4c6f-8abd-02733f5810ba)

`求助：如何解决兼容问题。发现在谷歌上，图标也没出来，但不是这种乱码

**Comment by nwind** [comment]
漏了这个依赖 

`import 'amis/sdk/iconfont.css';`
