### ISSUE TITLE
amis如何实现sse功能，就是ai对话的流式返回内容的功能

### ISSUE THREAD

**Issue by yurentle** [baidu/amis#9987]
如何使用amis搭建一个ai对话的模块，百度的爱速搭有这个功能，说是基于amis实现的，不知道爱速搭实现的ai对话是不是单独处理的，还是amis直接就能实现，麻烦知道的朋友帮忙解答一下，谢谢

**Comment by oubeichen** [comment]
> 是单独处理的，amis可以搭个大致框架，处理不了StreamEvent，需要自己实现

要在哪个部分实现呢?目前我看接口的返回适配器已经是完整的结果了,发送适配器也只能改几个参数,有什么办法修改请求的逻辑使得可以流式输出处理呢?
