### ISSUE TITLE
SchemaApi 使用js请求的js文件怎么写呀，官方文档报错了

### ISSUE THREAD

**Issue by lpn666** [baidu/amis#9997]
SchemaApi 使用js请求的js文件怎么写呀，官方文档报错了。我试着这么写，但是浏览器不渲染呀。

纯后端，前段一点不会，麻烦了
```
function f() {
    return {
        type: 'button',
        label: '按钮修改',
        onClick: (e, props) => {
            alert('消息通知');
        }
    }
}
f()
```

**Comment by vexos-io** [comment]
我是伪造了一个请求，然后用adaptor改掉返回值。如下，希望对你有帮助：
`
export function loadSchema(page)
{
  return {
    url: '/null', //这是一个空返回的占位路径
    adaptor: async (body, res, api) =>
    {
      const o = await import(page); //实际import目标文件
      return {
        status: 0,
        data: o.default
      };
    }
  };
}
`

**Comment by lpn666** [comment]
> 我是伪造了一个请求，然后用adaptor改掉返回值。如下，希望对你有帮助：
> 
> export function loadSchema(page) { return { url: '/null', //这是一个空返回的占位路径 adaptor: async (body, res, api) => { const o = await import(page); //实际import目标文件 return { status: 0, data: o.default }; } }; }

没看懂你这写的是啥，按照你这个写返回还是报错

**Comment by vexos-io** [comment]
https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8

**Comment by lpn666** [comment]
我按照您说的写了，但是加载还是白屏。请问这是为啥呢
![image](https://github.com/baidu/amis/assets/26716574/dadef8c0-6bda-45c4-b207-cabefbdf7316)
![image](https://github.com/baidu/amis/assets/26716574/ce5bde39-38fe-4863-a74a-a80942efcb12)



> https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8

**Comment by lpn666** [comment]
> https://aisuda.bce.baidu.com/amis/zh-CN/docs/types/api#%E9%85%8D%E7%BD%AE%E6%8E%A5%E6%94%B6%E9%80%82%E9%85%8D%E5%99%A8

我按照您说的写了，但是还是白屏，请问这是为啥呢
![image](https://github.com/baidu/amis/assets/26716574/49c341cc-a0f3-4249-9ff2-84bf469b455f)
![image](https://github.com/baidu/amis/assets/26716574/1f92d919-2eaa-4952-bd43-c97148feb64b)

**Comment by nwind** [comment]
不需要包一层函数，那个 js 里就直接写

```javascript
    return {
        type: 'button',
        label: '按钮修改',
        onClick: (e, props) => {
            alert('消息通知');
        }
    }
```

**Comment by lawbc** [comment]
> 不需要包一层函数，那个 js 里就直接写
> 
> ```js
>     return {
>         type: 'button',
>         label: '按钮修改',
>         onClick: (e, props) => {
>             alert('消息通知');
>         }
>     }
> ```

如果需要import这样写好像不行
